### ISSUE TITLE
Adding GlusterFS bundle

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#1]
👋 Hi there Clear Linux team,

arjan_work from the #clearlinux IRC channel sent me over here to request adding GlusterFS as a bundle. I think it would be well suited for the [`storage-cluster`](https://github.com/clearlinux/clr-bundles/blob/92faefb0a1b6c21cc4e1019155c0065c2be87372/bundles/storage-cluster) bundle as an alternative to Ceph.

Here is a link to the tarball of the latest version: https://download.gluster.org/pub/gluster/glusterfs/LATEST/glusterfs-3.13.1.tar.gz.

**Comment by KollegaDe** [comment]
+1

**Comment by iphutch** [comment]
@nesiusra

**Comment by AthenasJimenez** [comment]
@bswinnerton GlusterFS is now available in storage-cluster bundle, may I close this issue?

**Comment by iphutch** [comment]
Thanks @AthenasJimenez !
