### ISSUE TITLE
systemd[1]: gdm-hw-accel.service: Two services allocated...

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/distribution#10]
![img_20171203_164206](https://user-images.githubusercontent.com/24626743/33526051-aa1845f4-d84b-11e7-98e4-002416ff8a76.jpg)
systemd[1]: gdm-hw-accel.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
also login animation is gone (no blackout, directly to xfce loading screen)
This issue is still happening since Dec 3, 2017, i assumed that i need to give more information about https://github.com/clearlinux/distribution/issues/9 .
This iisue didn't affected the https://github.com/clearlinux/distribution/issues/9 directly.

**Comment by unixbhaskar** [comment]
Turn off or disable gdm.service and try again. It's clashing with other display services.

**Comment by iphutch** [comment]
@mrkz please work with @ahkok to remove conflicting units and replace with something wrapped.

**Comment by josuedhg** [comment]
as far as I know this issue is already fixed, isn't it?
