### ISSUE TITLE
cockpit (sysadmin-remote) cant login anymore ?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#100]
I try to figure out why i can't login via cockpit anymore after i did a `swupd verify -f -Y` i did reinstall the bundle and reused all the old /etc files, settings.
In the web interface i simply get: `Wrong user name or password ` yet i'm 100% sure the root user and password is correct, since i can login via ssh just fine.

Here is what i get in the logs, maybe someone can help me out again?
```
cockpit-session[6115]: pam_warn(cockpit:auth): function=[pam_sm_authenticate] flags=0 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[192.168.1.101]
Jun 19 09:38:10 clear-vm dbus-daemon[226]: [system] Activating via systemd: service name='org.freedesktop.PolicyKit1' unit='polkit.service' requested by ':1.44' (uid=0 pid=6165 comm="pkexec cockpit-bridge ")
Jun 19 09:38:10 clear-vm systemd[1]: Starting Authorization Manager...
Jun 19 09:38:10 clear-vm polkitd[6168]: Started polkitd version 0.114
Jun 19 09:38:10 clear-vm polkitd[6168]: Loading rules from directory /etc/polkit-1/rules.d
Jun 19 09:38:10 clear-vm polkitd[6168]: Error opening rules directory: Error opening directory “/etc/polkit-1/rules.d”: No such file or directory (g-file-error-quark, 4)
Jun 19 09:38:10 clear-vm polkitd[6168]: Loading rules from directory /usr/share/polkit-1/rules.d
Jun 19 09:38:10 clear-vm polkitd[6168]: Finished loading, compiling and executing 1 rules
Jun 19 09:38:10 clear-vm dbus-daemon[226]: [system] Successfully activated service 'org.freedesktop.PolicyKit1'
Jun 19 09:38:10 clear-vm systemd[1]: Started Authorization Manager.
Jun 19 09:38:10 clear-vm polkitd[6168]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Jun 19 09:38:10 clear-vm pkexec[6165]: pam_unix(polkit-1:session): session opened for user root by root(uid=0)
Jun 19 09:38:10 clear-vm pkexec[6165]: root: Executing command [USER=root] [TTY=/dev/pts/0] [CWD=/root] [COMMAND=/usr/bin/cockpit-bridge]
```

**Comment by bryteise** [comment]
@matthewrsj Do the post scripts get rerun after a verify --fix --picky? That's the only thing that jumps out to me as a possibility.

@Andy2244 Could you try wiping /var and rebooting as my shot in the dark?

**Comment by matthewrsj** [comment]
Yes, post-scripts are run after a verify if --fix or --install are provided.

**Comment by Andy2244** [comment]
@bryteise Same problem after deleting /var and rebooting, any other ideas?

All i can see is this after the failed login try is:
```
clear-vm systemd[1]: Starting Cockpit Web Service...
clear-vm systemd[1]: Started Cockpit Web Service.
clear-vm cockpit-ws[15214]: Using certificate: /etc/cockpit/ws-certs.d/0-self-signed.cert
clear-vm cockpit-session[15218]: pam_warn(cockpit:auth): function=[pam_sm_authenticate] flags=0 service=[cockpit] terminal=[<unknown>] user=[root] ruser=[<unknown>] rhost=[192.168.1.101] 
```

**Comment by Andy2244** [comment]
@bryteise Just hopped into the cockpit irc and a friendly dev quickly noted that the pam.d cockpit file is probably missing and thats the problem.

Seems after we closed the initial request https://github.com/clearlinux/clr-bundles/issues/25 the actual `/usr/share/pam.d/cockpit` file did not made it into the bundle.

Here is what you suggested the file to look like based on the fedora one, which solved my issue:
```
#%PAM-1.0
auth substack common-auth
account required pam_nologin.so
account include common-account
password include common-password
session required pam_loginuid.so
session optional pam_keyinit.so force revoke
session include common-session
```

So the problem was that the `swupd verify -f -Y` did delete the pam.d file and therefor it could not work and i forgot that we did this manually back than.

**Comment by ahkok** [comment]
Did you try putting the file in `/etc/pam.d/` and see if that works? This is where you should put locally created pam.d files.

**Comment by phmccarty** [comment]
But if a `/usr/share/pam.d/cockpit` config *is* needed for cockpit, then we should probably install that file as part of the cockpit package, correct?

**Comment by ahkok** [comment]
@phmccarty absolutely, I'm just checking that that works :)

**Comment by Andy2244** [comment]
@ahkok Yes after creating the file under /usr/share/pam.d cockpit works again.

**Comment by bryteise** [comment]
@Andy2244 Does it work if you put it under /etc/pam.d instead of /usr? (That way it won't get removed by verify --fix --picky). That said I'm adding the pam config to the distro, don't know how I ended up missing that, sorry X(.

**Comment by bryteise** [comment]
Updated cockpit package to include the pam config so hopefully this is a non issue for you in the next release.

**Comment by Andy2244** [comment]
@bryteise cool thanks again for the quick fix!

**Comment by ahkok** [comment]
Confirmed, broken. `pam` files must not have any extensions. Fixing.

**Comment by ahkok** [comment]
`cockpit-178-26`
