### ISSUE TITLE
emacsclient -c does not open a new frame

### ISSUE THREAD

**Issue by lsandov1** [clearlinux/distribution#1000]
emacs has a client-server architecture, where clients (`emacsclient`) can connect to the server (`emacs --daemon`) either through `emacsclient -t` or `emacsclient -c`, terminal and frame clients, respectively. However, the latter, `emasclient -c`, does not open a frame (GUI interface) but instead it opens the client in terminal.

Steps to reproduce it:
```
$ emacs --daemon
$ emacsclient -c
```
Expected result:
a client frame should be created

Current result:
a client terminal is created

**Comment by bryteise** [comment]
Ah this is due to having two versions of emacs. If you do this using:
```$ emacs-x11 --daemon```
```$ emacsclient -c```
You should get the frame.

**Comment by lsandov1** [comment]
thansk @bryteise, worked when launching the emacs-x11 daemon.
