### ISSUE TITLE
openbox for desktop-lxqt

### ISSUE THREAD

**Issue by 0n0w1c** [clearlinux/distribution#1002]
The openbox window manager is the default for the LXQt desktop. The fast and lightweight window manager seems to be missing. Please add openbox to the desktop-lxqt bundle, or as a separate bundle.

**Comment by fenrus75** [comment]
done.. should be in the next build once it passes QA

**Comment by 0n0w1c** [comment]
In taking a look at the LXQt bundle online, it does not list obconf-qt as being included.  It (or obconf) would be very helpful to be included when openbox is added, as it the tool to modify the openbox desktop configuration.
