### ISSUE TITLE
Add static library for python3-basic

### ISSUE THREAD

**Issue by florinpapa** [clearlinux/distribution#1007]
swupd info
Installed version: 30330 (in AWS)
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

I am trying to install uwsgi via pip and I am running into an error because of the Python3 static library is missing:
```
sudo swupd bundle-add unzip git python3-basic c-basic
python3 -m virtualenv -p python3 venv
source venv/bin/activate
pip install uwsgi>=2.0.15
```

Can you please add support for building the Python3 static library as part of python3-basic? I could only find the .so on the system.

**Comment by bryteise** [comment]
Okay, change pushed for review on the mailing list. Should likely be in this week.

**Comment by florinpapa** [comment]
@bryteise I have just tried again after a fresh `swupd update` and I get the same result. 

swupd info
Installed version: 30770
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

**Comment by phmccarty** [comment]
We have a `python3-staticdev` package now, but it might not be present in any bundle yet...

**Comment by florinpapa** [comment]
@phmccarty thanks for the reply. Do you know when there will be a python3 bundle containing this `python3-staticdev` package?

**Comment by phmccarty** [comment]
@florinpapa I'm not sure how we should incorporate `python3-staticdev`, given that the python3 package needs some rework to not make shared library configuration the default.

We recently added a `c-basic-static` bundle. Would a new `python3-basic-static` bundle suffice?

**Comment by florinpapa** [comment]
@phmccarty a `python3-basic-static` bundle would work great for me.

**Comment by phmccarty** [comment]
I sent a clr-bundles patch for review: https://lists.clearlinux.org/pipermail/dev/2019-August/003391.html

**Comment by phmccarty** [comment]
Patch has been integrated. The `python3-basic-static` bundle should be available within a couple days.

**Comment by florinpapa** [comment]
I was able to install `python3-basic-static` with swupd version 30810 and my issue was solved. Thank you @phmccarty for your help.

**Comment by phmccarty** [comment]
Great, thanks for confirming!

For the record, the new bundle was added in release `30810`, which resolves this issue.
