### ISSUE TITLE
bundle web-server-basic installs two web servers?

### ISSUE THREAD

**Issue by technerdchris** [clearlinux/distribution#1009]
When performing `swupd bundle-add web-server-basic` I noticed in the output:
```
 - web-server-basic
 - httpd
 - nginx
```
Bundle `httpd` installs apache. It doesn't make sense to also install nginx. I believe `web-server-basic` should be a symlink to `httpd`. Nginx is not exactly common and should be left separate and anyone wanting to run nginx will know to look for it.

**Comment by ahkok** [comment]
We're going to deprecate this bundle - it will be deleted. Once that is done, you can either remove one or the other (nginx/apache).

**Comment by puneetse** [comment]
I'm closing this issue because the `web-server-basic` bundle has been deprecated and replaced by separate `nginx` and `apache` bundles.
