### ISSUE TITLE
os-core: sysusers.d configuration conflicts

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#101]
The os-core bundle installs two files in /usr/lib/sysusers.d: clear.conf and dbus.conf.

Running systemd-sysusers the following message:
`Two or more conflicting lines for messagebus configured, ignoring.`

The messagebus user is indeed defined in both files.

**Comment by ahkok** [comment]
Agreed, the `dbus.conf` file shouldn't be there to begin with.

**Comment by ahkok** [comment]
Fixed by removing the dbus.conf file. Should be in a release within 24h.
