### ISSUE TITLE
firewalld needs python package slip

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#1020]
firewall-offline-cmd from the firewalld package complains about not finding slip. 

```
$ firewall-offline-cmd

Traceback (most recent call last):
  File "/usr/bin/firewall-offline-cmd", line 31, in <module>
    from firewall.client import FirewallClientIPSetSettings, \
  File "/usr/lib/python3.7/site-packages/firewall/client.py", line 29, in <module>
    import slip.dbus
ModuleNotFoundError: No module named 'slip'
```

**Comment by mrkz** [comment]
yeah, loos like we're missing https://github.com/nphilipp/python-slip

**Comment by puneetse** [comment]
FWIW, `pip install slip` didn't solve it for me.

It also looks like firewalld itself wants it:

```
$ sudo /usr/bin/firewalld --nofork
Traceback (most recent call last):
  File "/usr/bin/firewalld", line 194, in <module>
    main()
  File "/usr/bin/firewalld", line 189, in main
    startup(args)
  File "/usr/bin/firewalld", line 142, in startup
    from firewall.server import server
  File "/usr/lib/python3.7/site-packages/firewall/server/server.py", line 40, in <module>
    import slip.dbus
ModuleNotFoundError: No module named 'slip'
```

**Comment by mrkz** [comment]
I pushed a fix for this (packaged python-slip and make firewalld to ask for it). This should be available in release **30420** or later

**Comment by puneetse** [comment]
Thanks @mrkz 

Looks like decorator may need to be added requires_add too:

```
Traceback (most recent call last):
  File "/usr/bin/firewall-cmd", line 31, in <module>
    from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
  File "/usr/lib/python3.7/site-packages/firewall/client.py", line 29, in <module>
    import slip.dbus
  File "/usr/lib/python3.7/site-packages/slip/dbus/__init__.py", line 8, in <module>
    from . import service
  File "/usr/lib/python3.7/site-packages/slip/dbus/service.py", line 34, in <module>
    from . import polkit
  File "/usr/lib/python3.7/site-packages/slip/dbus/polkit.py", line 31, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```
After that firewalld starts but complains about missing /etc/ config

```
 ERROR: Failed to load '/etc/firewalld/firewalld.conf': [Errno 2] No such file or directory: '/etc/firewalld/firewalld.conf'

```

**Comment by mrkz** [comment]
> Thanks @mrkz
> 
> Looks like decorator may need to be added requires_add too:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/bin/firewall-cmd", line 31, in <module>
>     from firewall.client import FirewallClient, FirewallClientIPSetSettings, \
>   File "/usr/lib/python3.7/site-packages/firewall/client.py", line 29, in <module>
>     import slip.dbus
>   File "/usr/lib/python3.7/site-packages/slip/dbus/__init__.py", line 8, in <module>
>     from . import service
>   File "/usr/lib/python3.7/site-packages/slip/dbus/service.py", line 34, in <module>
>     from . import polkit
>   File "/usr/lib/python3.7/site-packages/slip/dbus/polkit.py", line 31, in <module>
>     from decorator import decorator
> ModuleNotFoundError: No module named 'decorator'
> ```

Thanks for the update, I just pushed a change that should pull-in decorator python package as well.

> 
> After that firewalld starts but complains about missing /etc/ config
> 
> ```
>  ERROR: Failed to load '/etc/firewalld/firewalld.conf': [Errno 2] No such file or directory: '/etc/firewalld/firewalld.conf'
> ```

As for ^ I'd like to open a new bug instead. 

Thanks for your contribution :tada:
