### ISSUE TITLE
Make GIMP removable

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1023]
[Initial discussion](https://community.clearlinux.org/t/make-gimp-removable/1120)

The brief version: GIMP isn't a non-alternative solution anymore, make sense to split it from desktop apps.

**Comment by ahkok** [comment]
This is dependent on a feature request in `swupd`.

**Comment by ahkok** [comment]
currently blocked by:  https://github.com/clearlinux/mixer-tools/issues/562

**Comment by ahkok** [comment]
Next it'll be blocked by https://github.com/clearlinux/clr-bundles
