### ISSUE TITLE
VMware tools with no effect

### ISSUE THREAD

**Issue by ghost** [clearlinux/distribution#1026]
Hello,

I run CL in Vmware Workstation Pro 15.1.0 for Windows and after installation of the VM tools the clipboard does not work:

swupd bundle-add os-cloudguest-vmware
reboot

Copy/Paste from Host>Guest not working nor the other way around.

It works fine on all my Debian 9/10 VM's.

**Comment by puneetse** [comment]
Some notes while I was taking a look at this:

- The vmtools plugin that handles copy+paste is called dndcp

- I verified vmtoolsd is not using the dndcp plugin (`sudo lsof +D /usr/lib64/open-vm-tools/plugins`)

- The dnd plugin is pulled out into an [extras package](https://github.com/clearlinux-pkgs/open-vm-tools/blob/master/extras), but isn't installed as part of the open-vm-tools bundle or an RPM dependency.

- Manually installing the individual `open-vm-tools-extras` package and rebooting got copy+paste from host-to-guest and guest-to-host working for me.

- The [stateless patch](https://github.com/clearlinux-pkgs/open-vm-tools/blob/master/0002-Stateless.patch#L94) isn't behaving like I'd expect. It isn't changing configuration reading order from to be `/etc/` + `/usr`, but only reads `/usr` as far as I can tell.

- I enabled debug logging with a file at `/usr/share/defaults/open-vm-tools/vmware-tools/tools.conf` with the content:
```
[logging]
log = true
 
vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = /tmp/vmtoolsd.${USER}.log
 
vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = /tmp/vmsvc.log

vmusr.level = debug
vmusr.handler = file
vmusr.data = /tmp/vmusr.${USER}.log
 
toolboxcmd.level = debug
toolboxcmd.handler = file
toolboxcmd.data = /tmp/vmtoolboxcmd.log

dndcp.level = debug
dndcp.handler = file
dndcp.data = /tmp/vmtoolsd.${USER}.log
```


reference: https://kb.vmware.com/s/article/1007873

**Comment by puneetse** [comment]
> * The dnd plugin is pulled out into an [extras package](https://github.com/clearlinux-pkgs/open-vm-tools/blob/master/extras), but isn't installed as part of the open-vm-tools bundle or an RPM dependency.

Oops, that's not true. It's part of the `os-cloudguest-vmware-gui` bundle. @Pummelchen try:
```
sudo swupd bundle-add os-cloudguest-vmware-gui

sudo systemctl enable open-vm-tools

sudo reboot
```

**Comment by puneetse** [comment]
Closing this issue as the `os-cloudguest-vmware-gui` enables copy+paste when the hypervisor allows it. If you continue to have issues after installing the bundle, please let us know!
