### ISSUE TITLE
update to kubernetes 1.11

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#103]
### What is the issue type?

* [ ] Bug report
* [x] Enhancement request

### Describe the problem

kubernetes 1.11 is about to be released. kubernetes in Clear is currently at 1.9.4 so the ask is to get 1.11 once it's out.

**Comment by mythi** [comment]
1.11 is now released

**Comment by iphutch** [comment]
@bryteise

**Comment by bryteise** [comment]
@DnPlas Would this be something you'd want to try and package too or would you prefer to stick closer to docker/kata-containers only?

**Comment by AthenasJimenez** [comment]
Updated. Should be available on next release.

**Comment by DnPlas** [comment]
@bryteise sure thing, I can give it a look and try it :)

**Comment by bryteise** [comment]
@AthenasJimenez is too fast! I somehow thought there might have been more to fixup for k8s instead of it being a normal autospec and release X(. Thanks much all!
