### ISSUE TITLE
xrdp is compiled without PAM support

### ISSUE THREAD

**Issue by dlo9** [clearlinux/distribution#1030]
**Clear Linux Version**: 30380

**Description**
 The `xrdp` package is compiled without  `--enable-pam`, resulting in a lack of PAM authentication when using RDP, causing login failures. This can be verified with `ldd /usr/bin/xrdp-sesman | grep libpam`. Additionally, running `LD_LIBRARY_PATH=/usr/lib64/xrdp/ ./xrdp-sesman` using a binary from Arch Linux allows login via PAM, which is the expected use case.

**Steps To Reproduce**
1. Install xrdp and Xvnc: `swupd bundle-add x11-tools vnc-server`
1. Copy config files: `cp -r /usr/share/defaults/xrdp /etc`
1. Set Xvnc session as the default: `sed -i 's/^autorun=$/autorun=Xvnc2/' /etc/xrdp/xrdp.ini` 
1. Start xrdp: `systemctl start xrdp`
1. Attempt to connect to the rdp session (e.g. `xfreerdp /v:<server ip> +glyph-cache /u:<user> /p:<pass>`)

**Result**: Login fails with error `login failed for display 0`. If running xrdp-sesman manually in the foreground (`xrdp-sesman -k; xrdp-sesman -n`), we see a more helpful error: `krb5_parse_name failed in k5_begin`, indicating kerberos is the default authentication method. Kerberos has not been set up and so is not expected to succeed.

**Comment by dlo9** [comment]
Actually, it looks like this isn't due to a missing `--enable-pam` but instead because PAM and Kerberos are mutually exclusive in the [makefile](https://github.com/neutrinolabs/xrdp/blob/e7c0b11336bce95fbd2c8a5624bb476f038536de/sesman/Makefile.am#L30), and right now `--enable-kerberos` is used. Since I believe Kerberos can be used through a PAM [module](https://linux.die.net/man/8/pam_krb5), IMO `--enable-kerberos` should be removed.

**Comment by ahkok** [comment]
`xrdp-0.9.10-34`
