### ISSUE TITLE
Package request: fdupes

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#1031]
FDUPES is a program for identifying or deleting duplicate files residing within specified directories.

https://github.com/adrianlopezroche/fdupes

**Comment by ahkok** [comment]
We have already `hardlink`. Does this fit your need, or is `fdupes` significantly different?

**Comment by thiagomacieira** [comment]
We also have `duperemove`.

From the man pages, `fdupes` is more flexible in its search than `hardlink`, but is functionally the same. `duperemove` can work with intra-file extents for sharing on suitable filesystems (btrfs and xfs), and it can consume `fdupes` output, but it does not perform hardlinking.

**Comment by cmarcelo** [comment]
In my case I'll have a series of files, and want to keep only one copy of each content. Don't care about which of the duplicates is kept (if a, b and c have equal contents, I'm fine keeping any of them and removing the other two). It is the functionality provided by `fdupes -d`.

I couldn't find a similar option in neither `hardlink` and `duperemove`, but I might be missing something. The fact that `duperemove` has an option to read output from `fdupes`, maybe is another reason to pull the new package in :-)

I know how to write a script to get this done, is just that the tool seemed popular enough so I thought could be a good addition.

**Comment by ahkok** [comment]
Added. Will be a separate `fdupes` bundle.
