### ISSUE TITLE
`xkeystone` from `x11-tools` bundle not working

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1034]
`xkeystone` is a nickle script which needs nickle programming language support. And it also needs nickle cairo bindings. (ref: https://narkive.com/i0HwNAwX:2.471.32)

This script itself is not documented, and even its dependencies are also not documented. This seems to be a problem from upstream, and doesn't has high priority, but please consider to remove this script if it's not ever used.

**Comment by puneetse** [comment]
For reference `xkeystone` is coming from the `xrandr` package. Other distros also commonly remove this script.

**Comment by rossburton** [comment]
Patch on the list.

**Comment by rossburton** [comment]
Done in xrandr 1.5.1-9.
