### ISSUE TITLE
`yarnpkg` from `nodejs-basic` bundle not working

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1037]
To reproduce the error, run `yarnpkg` in shell, you'll see

```
Error: Cannot find module '/usr/lib/node_modules/yarn/bin/../lib/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by nsgnn** [comment]
See also #962

**Comment by lebensterben** [comment]
The workaround is to install `yarn` module
`sudo npm install yarn --global`

**Comment by karansapolia** [comment]
Having yarnpkg function correctly would help a lot of developers :slightly_smiling_face:

**Comment by karansapolia** [comment]
> The workaround is to install `yarn` module
> `sudo npm install yarn --global`

Installing `yarn` using your method, throws an error if the `big-data-basic` bundle installed.

```bash
$ sudo npm install yarn --global
Password: 
npm ERR! path /usr/bin/yarn
npm ERR! code EEXIST
npm ERR! Refusing to delete /usr/bin/yarn: is outside /usr/lib/node_modules/yarn and not a link
npm ERR! File exists: /usr/bin/yarn
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-10T11_59_49_224Z-debug.log
```

**Comment by lebensterben** [comment]
> > The workaround is to install `yarn` module
> > `sudo npm install yarn --global`
> 
> Installing `yarn` using your method, throws an error if the `big-data-basic` bundle is installed.
> 
> ```shell
> $ sudo npm install yarn --global
> Password: 
> npm ERR! path /usr/bin/yarn
> npm ERR! code EEXIST
> npm ERR! Refusing to delete /usr/bin/yarn: is outside /usr/lib/node_modules/yarn and not a link
> npm ERR! File exists: /usr/bin/yarn
> npm ERR! Move it away, and try again.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-10T11_59_49_224Z-debug.log
> ```

Hi, I had a new installation of Clear Linux after I made that comment.

I had `yarnpkg` installed but not `yarn` from `big-data-basic`. I installed this bundle and then found `/usr/bin/yarn` is replaced by the it, but meanwhile `/usr/bin/yarnpkg` is also working fine.

So if you can remove `big-data-basic`, first do that, then install `yarnpkg` and finally add `big-data-basic` back if it's needed.

**Comment by lebensterben** [comment]
> > The workaround is to install `yarn` module
> > `sudo npm install yarn --global`
> 
> Installing `yarn` using your method, throws an error if the `big-data-basic` bundle is installed.
> 
> ```shell
> $ sudo npm install yarn --global
> Password: 
> npm ERR! path /usr/bin/yarn
> npm ERR! code EEXIST
> npm ERR! Refusing to delete /usr/bin/yarn: is outside /usr/lib/node_modules/yarn and not a link
> npm ERR! File exists: /usr/bin/yarn
> npm ERR! Move it away, and try again.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-10T11_59_49_224Z-debug.log
> ```

Hi, I had a new installation of Clear Linux after I made that comment.

I had `yarnpkg` installed but not `yarn` from `big-data-basic`. I installed this bundle and then found `/usr/bin/yarn` is replaced by the it, but meanwhile `/usr/bin/yarnpkg` is also working fine.

So if you can remove `big-data-basic`, first do that, then install `yarnpkg`  and finally add `big-data-basic` back if it's needed.

But also notice that, `sudo swupd search-file /usr/bin/yarn` told me that,
`yarn` is exclusively for `big-data-basic`, and the one from nodejs is called `yarnpkg`. So I guess it'd suffice if you just install `nodejs-basic` bundle instead of installing a custom `yarnpkg`.

**Comment by ngohaibac** [comment]
I am using CLR# 32760
```
swupd info
Distribution:      Clear Linux OS
Installed version: 32760
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```
When install:`sudo swupd bundle-add nodejs-basic`, there is no pkg `yarn`, `yarnpkg` in /usr/bin. 

Only, when I install using npm, then there are `/usr/bin/yarn` and `/usr/bin/yarnpkg` point to same  `/usr/lib/node_modules/yarn/bin/yarn.js`

```
sudo npm install yarn --global
Password: 
/usr/bin/yarn -> /usr/lib/node_modules/yarn/bin/yarn.js
/usr/bin/yarnpkg -> /usr/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.4
added 1 package in 0.786s
```

**Comment by bryteise** [comment]
@ngohaibac Clear Linux removed yarn. Also I do not recommend installing globally as that puts content in places where Clear Linux considers it owns things. Your content may be replaced or removed unexpectedly during update due to conflicting with Clear Linux content.
