### ISSUE TITLE
Package request: GNOME Clocks

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1038]
https://wiki.gnome.org/Apps/Clocks - the part of default GNOME desktop, provide world clocks, alarm, timer, stopwatch etc.

**Comment by mrkz** [comment]
packaged now and created a new bundle `gnome-clocks`. Should be available soon-ish.

Will close this issue once a release with the content is out.

**Comment by mrkz** [comment]
`gnome-clocks` bundle is available now via update (version **30500** or later).

Closing this issue now.

Thanks for the report :tada:
