### ISSUE TITLE
Trackpad doesn't move when key pressed on kb

### ISSUE THREAD

**Issue by epipenau** [clearlinux/distribution#1039]
In games (steam+proton) when holding a key (e.g. W to move forward) one can no longer move the pointer.  I don't see this problem with SuSE, however I have seen it with Kali and Clear.

im using a dell inspiron laptop.

**Comment by ephut** [comment]
this happens with trackpads and it's intentional - @mrkz  to document how this behavior can be disabled

**Comment by mrkz** [comment]
@epipenau Hello, thanks for your report! :tada: 

This is a default setting from GNOME that we're just following up. If you'd want to be able to move the trackpad/touchpad while typing, you could change this by opening `gnome-tweaks` -> Keyboard & Mouse -> disable the `Disable While Typing` switch on the `Touchpad` section.

![gnome-tweaks-disable-when-typing](https://user-images.githubusercontent.com/978752/61886062-9baadd00-aec4-11e9-85c3-8e7aa4ae3841.png)

Doing so would fix your issue.
