### ISSUE TITLE
Squahfs: Support more compression methods

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#104]
Squashfs supports several compression methods on other distributions, but only gzip on clearlinux.

This prevents me from opening the squashfs images I want to mount.

Could more compression options get added, please?

**Comment by fenrus75** [comment]
just added lz4/lzo/zstd.

I'd suggest using zstd for all new images please

**Comment by hunger** [comment]
Thanks!

I just tried mounting an existing image I have around using lz4 and that does not work in 23260 (using 4.17.2-586). The kernel still complains that lz4 is unsupported in the journal.

Do I need to do something special to enable this?

**Comment by fenrus75** [comment]
so this is where I am going to have to admit to a typo. fixed that (blush)

**Comment by hunger** [comment]
No problem, I am great at adding typos to things, too.

When will the fix get released? It's been 21h since you claimed this to be fixed and I am still on 23260.

**Comment by hunger** [comment]
Works now with version 23280. Thanks!
