### ISSUE TITLE
Please add the_silver_searcher

### ISSUE THREAD

**Issue by cHolzberger** [clearlinux/distribution#1040]
the_silver_searcher or ag is so much faster than grep and provides much better visual experience than grep. 
please add the_silver_searcher to clearlinux: https://github.com/ggreer/the_silver_searcher

**Comment by lebensterben** [comment]
It's slower than `ripgrep`, if speed really matters to you.

**Comment by cHolzberger** [comment]
recursive searching and visual highlighting are more important than speed but ripgrep is ok, thanks no need for the_silver_searcher anymore ;), 

is ripgrep only available to desktop-apps-extra?

**Comment by cHolzberger** [comment]
hm, no seems like ripgrep is not available in bundeld form, the_silver_searcher works with autospec out of the box, ripgrep isn't.

**Comment by lebensterben** [comment]
>hm, no seems like ripgrep is not available in bundeld form, the_silver_searcher works with autospec out of the box, ripgrep isn't.

@cHolzberger people asked for ripgrep before but they're still working on Rust support for autospec. So  I built ripgrep myself, or you can download the prebuilt binary.

If you're using Intel CPU and you want REALLY fast searching, you can build ripgrep with nightly release of rust compiler but that is not in swupd.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by curantes** [comment]
I have packaged it and submitted it to https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/XVUJ4G334VYNM5UEOS3QBBSBIC7PFBCI/ for review. Hopefully it will be added.

**Comment by bryteise** [comment]
@curantes Thanks, your packaging looks great. I am going to tweak it a little to put the bash-completion in a different location but otherwise no changes needed =).
