### ISSUE TITLE
please inculde snd-aloop driver

### ISSUE THREAD

**Issue by cHolzberger** [clearlinux/distribution#1041]
would love to pass loopback sound devices to qemu, can you add snd-aloop please.

**Comment by miguelinux** [comment]
@cHolzberger 
They were added at https://github.com/clearlinux-pkgs/linux/commit/999c80b1f3833b86d29ae2bfff77ca9c0c5cd8b2  and add public avaible now (Linux 5.2.3)

Let us know if you need more modules to enable.
