### ISSUE TITLE
Enable CONFIG_RT2800USB_RT55XX in Kernel Config

### ISSUE THREAD

**Issue by macromorgan** [clearlinux/distribution#1042]
I would like to request that the option "CONFIG_RT2800USB_RT55XX" be set to Y in the default kernel config.  This request is so that the onboard WiFi of the "Atomic Pi" (which uses the USB bus for some reason) work by default.

Thank you.

**Comment by ahkok** [comment]
Ohhh that's a good one, I never did test the wifi on this board.

If you have anything else to share, please post it to the relevant forum thread - would love to see some other posts about this board:

https://community.clearlinux.org/t/clear-linux-os-on-an-atomic-pi/326

**Comment by macromorgan** [comment]
Only other thing I can see is a large volume of errors in the dmesg log for "Audio Port: ASoC: no backend DAIs enabled for Audio Port".  Near as I can tell though everything seems to work, the message might just be for information purposes (but there sure are a lot of instances of the same message in the dmesg log).

**Comment by miguelinux** [comment]
You will find this change at `linux-5.2.2-803` kernel version.
You will see it in 1 or 2 days.
