### ISSUE TITLE
Please include the dropwatch package

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#1043]
https://github.com/nhorman/dropwatch

Allow me to quote the project's author:

"Dropwatch is a project I started in an effort to improve the ability for developers and system administrator to diagnose problems in the Linux Networking stack, specifically in our ability to diagnose where packets are getting dropped"

This is a useful tool indeed for finding out the reason behind packet drops. Example output

dropwatch -l kas
Initalizing kallsyms db
dropwatch> start
Enabling monitoring...
Kernel monitoring activated.
Issue Ctrl-C to stop monitoring
1 drops at skb_queue_purge+18 (0xffffffff8151a968)
41 drops at __brk_limit+1e6c5938 (0xffffffffa0a1d938)
1 drops at skb_release_data+eb (0xffffffff8151a80b)
2 drops at nf_hook_slow+f3 (0xffffffff8155d083)

Note - this requires STP and possibly some kernel changes
https://github.com/pavel-odintsov/drop_watch/wiki/Ubuntu-14.04-LTS-kernel-with-drop_monitor-support

The DROP_MONITOR functionality is disabled by default (base-5.1)

CONFIG_NET_DROP_MONITOR is not set

**Comment by mpurzynski** [comment]
Note - this requires STP and possibly some kernel changes
https://github.com/pavel-odintsov/drop_watch/wiki/Ubuntu-14.04-LTS-kernel-with-drop_monitor-support

**Comment by bryteise** [comment]
@miguelinux I have this packaged would you mind enabling the CONFIG_NET_DROP_MONITOR in the kernels? It is using tracepoints from what I understand so it shouldn't hurt performance in theory.

**Comment by bryteise** [comment]
Package should be in the next release, not sure what release will get the kernel config for it to be useful though yet.

**Comment by miguelinux** [comment]
it will be added to `linux-5.2.2-806`, also I added as base for `5.2` and `LTS2017` and `LTS2018`.

you will get this change in 1 or 2 days
