### ISSUE TITLE
`Solaar` and `Solaar-gui` not working

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1045]
`Solaar` has the CLI program and users needs to be added to `plugdev` group for it to work (without sudo privilege). Currently users are not added to that group.

---

`Solaar-gui` is not working, see the error below
```
gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  __import__(module)
solaar: error: invalid syntax (__init__.py, line 126)
```

**Comment by bryteise** [comment]
I don't think we've generally added users to groups by default at this point. Might be something that the installer could do by default though for admin users though.

**Comment by ahkok** [comment]
We generally shouldn't assign groups even to admin users. That would increase the attack surface of all default accounts dramatically.

**Comment by lebensterben** [comment]
@bryteise @ahkok Thx for the explanation.

But the error with GUI client is not resolved even after I added my user account to the group.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahkok** [comment]
It's asking for `gtk3` support. Our `pygtk` only has `gtk2` support? I don't even know where this would come from.... o_O

**Comment by ahkok** [comment]
Updated to `1.0.1`. Upstream has a fix for this, so, it's probably good now.

**Comment by lebensterben** [comment]
I can confirm this. Actually they have been working normally for several weeks. Not sure whether it's due to the upstream fix.
