### ISSUE TITLE
nouveau driver crash on CD Boot

### ISSUE THREAD

**Issue by vrdhn** [clearlinux/distribution#1047]
[Dell-g3-nouveau-crash.txt](https://github.com/clearlinux/distribution/files/3425080/Dell-g3-nouveau-crash.txt)

nouveau driver crash when booting from live ISO.
Able to use normally after that, and i've this issue on other kernel versions too.

I can provide any help required to debug this issue, as ( i think) without this, i won't be able 
to get HDMI working.

[    9.732887] Hardware name: Dell Inc. G3 3579/03TF0Y, BIOS 1.1.0 05/25/2018
[    9.732913] RIP: 0010:gf100_gr_init_ctxctl_ext+0x362/0x500 [nouveau]

Thanks

**Comment by puneetse** [comment]
Can you confirm what GPU that laptop has? If it is the GTX 10​60MQ, it is not fully supported by the nouveau driver yet: https://nouveau.freedesktop.org/wiki/FeatureMatrix/ 

This is probably a bug in the nouveau driver and not Clear Linux specific.
https://bugzilla.redhat.com/show_bug.cgi?id=1705207

**Comment by vrdhn** [comment]
yes perhaps so.
i'm closing the ticket as this is really a kernel issue.
Thanks for your time
