### ISSUE TITLE
Can't select wine-stable vs development version. Can't select older wine releases.

### ISSUE THREAD

**Issue by KKotzak** [clearlinux/distribution#1049]
I just added the bundle through clear linux swupd bundle manager but there is no option to select if I prefer the stable or the development version. Even more on other (non clear linux) machines, I have found that the previous wine stable version (3.0) performs better in most cases than latest stable (4.0) but yet again there is no option to select which stable version I require through the bundle installation process.

I am new to Clear Linux (but not in Linux) so maybe I am missing something?
I can build the wine 3.0 stable from source but that defeats the purpose of bundles.

**Comment by bryteise** [comment]
Currently only the latest stable version of wine is packaged. Since the wine maintainers do support the old stable release with bug fixes there isn't an issue with us having both but it just hasn't been done yet.

**Comment by ahkok** [comment]
We have requests now for -devel and -stable. We'll stick to mainline instead, this is enough work for now. (if someone wants to contribute the work, that's fine).
