### ISSUE TITLE
[LVM] Clearlinux takes a long time to shut down

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#105]
### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

Shutting down clearlinux takes a long time (about 1:30min) to power-off -- which smells like the usual systemd 90s timeout. It does not matter whether I use systemctl poweroff or the UI from the desktop bundle to trigger the shutdown, the time it takes stays the same.

Looking into the journal, there is indeed a timeout: lvm2-pvscan@8:3.service. Up to that point the shutdown works nice and fast and afterwards it is fast again.

Apparently LVM is currently prone to timeouts on start-up, at least with more than one PV, thin-provisioning, cache, or snapshots. I do have more than one PV and thin provisioning enabled:-)

### Extra information:
Clearlinux version 23260, kernel version 4.17.2-586.

**Comment by iphutch** [comment]
@ahkok @bwarden

**Comment by tpleavitt** [comment]
@jairglez please retest and close if you cannot reproduce

**Comment by jairglez** [comment]
I haven't been able to reproduce the issue in my test environment. However, @miguelinux reports that he has experienced this issue intermittently in his laptops. He also has had a similar occurrence in Fedora 29.

**Comment by thiagomacieira** [comment]
LVM has this problem in other distros too. It's caused by this sequence of events:
* something (lvmetad, usually) is still running
* because that is running, filesystem cannot be mounted read-only
* because the FS is still read-write, Volume Groups cannot be deactivated
* because the VGs are still active, the daemon cannot be shut down

**Comment by alanorth** [comment]
For the record I get this issue on Arch Linux, but only with the Clear Linux kernel. On reboot the system has a black screen with a cursor blinking for about 90 seconds, then the following message is printed on the screen before it reboots:

```
[  116.123456] sd-umoun[1040]: Failed to unmount /oldroot: Device or resource busy
[  116.123456] sd-umoun[1041]: Failed to unmount /oldroot/dev: Device or resource busy
[  117.123457] reboot: Restarting system
```

I am using LVM on top of LUKS. Kernel version is 5.0.5-725 and systemd is 241.67.
