### ISSUE TITLE
swupd: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by liujianjunhq** [clearlinux/distribution#1052]
**Describe the bug**
When building a clearlinux docker image, such as: nginx,  after "swupd update" in the 1st stage, it will run "swupd os-install". But it reports that "swupd: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory". 
This issue could be solved if adding "RUN ldconfig" after "RUN swupd update --no-boot-update $swupd_args". 
This issue does not exist if the host machine is Ubuntu, as https://travis-ci.org/clearlinux/dockerfiles/jobs/562853425. 

**To Reproduce**
(host Clear Linux machine) $ git clone https://github.com/clearlinux/dockerfiles.git
(host Clear Linux machine) $ cd dockerfile/nginx
(host Clear Linux machine) $ sudo docker build --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy -t clearlinux/mytest . --no-cache

**Expected behavior**
dockerfile build successfully

**Actual behaviour**
Below error message was gotten:  
Update successful. System updated from version 30450 to version 30500
Removing intermediate container b96750fe1cb1
 ---> d0d0e163c76a
Step 3/15 : COPY --from=clearlinux/os-core:latest /usr/lib/os-release /
 ---> 24348cf3c6ed
Step 4/15 : RUN source /os-release &&     mkdir /install_root     && swupd os-install -V ${VERSION_ID}     --path /install_root --statedir /swupd-state     --bundles=nginx --no-scripts
 ---> Running in 524e158503ea
swupd: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
The command '/bin/sh -c source /os-release &&     mkdir /install_root     && swupd os-install -V ${VERSION_ID}     --path /install_root --statedir /swupd-state     --bundles=nginx --no-scripts' returned a non-zero code: 127

**Comment by bryteise** [comment]
See #831 as this is the same root cause.
