### ISSUE TITLE
iptables-restore and ip6tables-restore conflict on xtables lock

### ISSUE THREAD

**Issue by alanbutt** [clearlinux/distribution#1058]
When firewall rules are created for both IPv4 and IPv6 and saved (via ip*tables-save).  On reboot iptables-restore fails with "Another app is currently holding the xtables lock.".   It may be that the conflict is with ip6tables-restore.   One of the IPv4 or IPv6 rules are not restored (on my system it is usually the IPv4 rules). 

systemctl status iptables-restore returns:

● iptables-restore.service - Restore IPv4 firewall settings across reboots
   Loaded: loaded (/usr/lib/systemd/system/iptables-restore.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-07-26 11:05:52 MDT; 1min 9s ago
  Process: 470 ExecStart=/usr/bin/iptables-restore /etc/iptables.rules (code=exited, status=4)
 Main PID: 470 (code=exited, status=4)

Jul 26 11:05:52 abb-clear systemd[1]: Starting Restore IPv4 firewall settings across reboots...
Jul 26 11:05:52 abb-clear iptables-restore[470]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Jul 26 11:05:52 abb-clear systemd[1]: iptables-restore.service: Main process exited, code=exited, status=4/NOPERMISSION
Jul 26 11:05:52 abb-clear systemd[1]: iptables-restore.service: Failed with result 'exit-code'.
Jul 26 11:05:52 abb-clear systemd[1]: Failed to start Restore IPv4 firewall settings across reboots.

The fix is easy.   Simply add a -w 5 to the unit files for iptables-restore.service and ip6tables-restore.service (in /usr/lib/systemd/system).  With the wait of a few seconds, the conflict disappears.

The version of Clear is 30500.  Desktop.
[bug.zip](https://github.com/clearlinux/distribution/files/3436916/bug.zip)

Attached are: sample /etc/iptables.rules /etc/ip6tables.rules, the systemctl status report (after reboot) for ip*tables-restore.service, and a "fixed" version of the .service files. 

Of course you can't just 'fix' these files they need to be fixed in the bundle.

**Comment by ahkok** [comment]
I'm taking the same approach as https://access.redhat.com/solutions/3138851 - adding a `--wait=X` option to iptables-restore/ip6tables-restore services. Hopefully this remedies the situation. Should be in a release early next week.
