### ISSUE TITLE
Systemd ignores system-wide environment variables

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#106]
I'm trying to define a couple of environment variables

http_proxy="http://hostname.domain:3128"
https_proxy="http://hostname.domain:3128"
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com, 1.2.3.4/24, *.domain.name, *.domain2.name, 169.$
HTTP_PROXY="http://hostname.domain:3128"
HTTPS_PROXY="http://hostname.domain:3128"
NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com, 1.2.3.4/24, *.domain.name, *.domain2.name, 169.$

I'd like to have them defined globally, for every user (in the user's environment) and for every starting service. Here is what I tried:

1. I wrote (a couple in fact) env generator, like so

cat /etc/systemd/system-environment-generators/30-proxies.sh 

#!/usr/bin/bash

http_proxy='http://proxy.dmz.mdc1.mozilla.com:3128'
echo http_proxy=$http_proxy

This file has permissions 0755 and executes correctly from the command line

No luck. I tried user-environment-generators as well with the same result

2. I added some files to the /etc/environment.d directory

cat /etc/environment.d/30-proxy.conf 

ala=makota

(just as a test)

Also no luck.

I tried reloading systemd with systemctl daemon-reload, logged out, in, etc. Nothing helps.

I kind of feel frustrated that after 10+ years of using Linux on a daily basis I do not see a clear way to define a system-wide environment variable.

**Comment by mpurzynski** [comment]
After further debugging, looks like systemd does not export variables to the current shell

1. variables. defined with system-environment-generators are visible only with

systemctl --system show-environment

2. variables generated with user-environment-generators are visible only with

systemctl --user show-environment

3. running just 'export' shows none of them

**Comment by miguelinux** [comment]
Have you tried to place your script at `/etc/profile.d/` directory?
or define your variables in `/etc/profile` file?

**Comment by mpurzynski** [comment]
We have a design problem here.

1. one needs to write 'generators' to export a simple variable

2. even doing 1. does not do anything good, because that variable will only be exported to systemd itself (and nowhere else)

3. systemd authors claim this is not a bug, it is a feature. I disagree. They demand every application modify or add some code, to import variables from systemd

4. the behavior is not consistent. With /etc/environment existing
a. ssh server <- variables are not visible in user's shell
b. sudo -s <- variables are visible in root's shell
c. su - anotheruser <- variables are not visible in anotheruser's shell

I'll try to export things in /etc/profile next

**Comment by mpurzynski** [comment]
Exporting variables in /etc/profile works for ssh, su, sudo.

Doing so does NOT export anything to systemd - so services won't see those variables.

One needs to export the same set of variables for systemd, either as generators (systemd-wide but not system-wide), or per service and also for interactive environments, with /etc/profile

Can we have this systemd design bug documented?

**Comment by ahkok** [comment]
> Can we have this systemd design bug documented?

that would be an upstream thing.
