### ISSUE TITLE
Broadcom wireless modules/firmware - No wireless adapter found

### ISSUE THREAD

**Issue by jamesclarke28** [clearlinux/distribution#1064]
Wireless firmware for BCM43142 [14e4:4365] is missing. I found out that only the "wl" drivers work for the wireless adapter. Please tell me how can I get my wifi to work again.

**Comment by lebensterben** [comment]
>Wireless firmware for BCM43142 [14e4:4365] is missing. I found out that only the "wl" drivers work for the wireless adapter. Please tell me how can I get my wifi to work again.

@jamesclarke28 install proprietary driver manually

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamesclarke28** [comment]
I copied all the files manually to their respective places after downloading from the RPM file but it did not work.

**Comment by lebensterben** [comment]
>I copied all the files manually to their respective places after downloading the RPM file but it did not work.

@jamesclarke28 
https://askubuntu.com/a/60395
This seems to be a very comprehensive guide. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamesclarke28** [comment]
need to have a compiler and headers for libc installed.. Where can I find them?

**Comment by miguelinux** [comment]
You should install `kernel-native-dkms` bundle 

Please read https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules-dkms
and https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules

**Comment by mvincerx** [comment]
@puneetse please take this one. Thanks.

**Comment by puneetse** [comment]
We've published a document for Broadcom Drivers with as much detail about the we are able to currently provide here: https://docs.01.org/clearlinux/latest/tutorials/broadcom.html

**Comment by Exospheric** [comment]
Comment: this is a major headache that shouldn't happen. If Ubuntu can just work, clear linux should just work. 

software can identify the hardware, decide which driver, decide whether LTS kernel should be installed, wget everything, all during the install. Instead thousands of people are going to have to try to figure it out, learn which outdated advice on the net to ignore, and many will give up and move one. \r
