### ISSUE TITLE
Too long time/10mins to enter the command console when Launch container-host by USB in bare metal machine

### ISSUE THREAD

**Issue by yanchao-hu** [clearlinux/distribution#1065]
- Description

Launch container-host by USB in bare metal machine,it's too long time when Image boot into command console first time.
**results 10mins**, normally only 20s.

- Steps to reproduce the issue:

1.dd container-host image to U-disk
2.set PC BIOS boot from U-disk
3.boot into command console and record the time meanwhile.

- version

https://cdn.download.clearlinux.org/releases/30450/clear/clear-30450-container-host.img.xz

- Envrionment

64GB Kingston USB3.0
DELL OptiPlex 5050

**Comment by ahkok** [comment]
I need at least a copy of the bootchart and/or systemd analyze --blame to figure this out.

**Comment by shaoyuta** [comment]
1, I capture the log of 'systemd-analyze critical-chain' :

The first time bootup
```
graphical.target @1min 3.4592s
└─multi-user.target @1min 3.4502s
  └─getty.target @1min 3.4433s
    └─getty@tty1.service @1min 3.4360s
      └─systemd-user-sessions.service @1min 3.4119s +7.8ms
        └─network.target @1min 3.4042s
          └─systemd-resolved.service @1min 3.0999s +286.5ms
            └─systemd-networkd.service @1min 2.7166s +373.1ms
              └─ucd.service @936.7ms +1min 1.7692s
                └─basic.target @926.2ms
                  └─sockets.target @926.0ms
                    └─pcscd.socket @925.9ms
                      └─sysinit.target @923.5ms
                        └─systemd-backlight@backlight:acpi_video0.service @1.3627s +3.6720s
                          └─system-systemd\x2dbacklight.slice @1.3607s
                            └─system.slice @448.0ms
                              └─-.slice @448.0ms
```

The second time bootup
```
graphical.target @3.3544s
└─multi-user.target @3.3543s
  └─getty.target @3.3542s
    └─getty@tty1.service @3.3540s
      └─systemd-user-sessions.service @3.3470s +4.1ms
        └─network.target @3.3462s
          └─systemd-resolved.service @3.0503s +295.6ms
            └─systemd-networkd.service @2.7724s +269.7ms
              └─ucd.service @1.0126s +1.7587s
                └─basic.target @1.0081s
                  └─sockets.target @1.0081s
                    └─pcscd.socket @1.0081s
                      └─sysinit.target @992.3ms
                        └─systemd-backlight@backlight:acpi_video0.service @1.1705s +91.0ms
                          └─system-systemd\x2dbacklight.slice @1.1700s
                            └─system.slice @476.2ms
                              └─-.slice @476.2ms
```
The difference between them is 'ucd.service'. 

2, If I disable ucd.service from container-host.img firstly, then use this image to boot the PC, the boot time is OK

3, 
/lib/systemd/system/ucd.service
```
[Service]
Type=oneshot
ExecStart=/usr/bin/ucd --fix-disk --first-boot-setup --metadata --user-data-once
```
So I feel this issue due to '/usr/bin/ucd --fix-disk --first-boot-setup --metadata --user-data-once'. First time to bootup system, ucd will spend some time to adjust the partition size.

**Comment by ahkok** [comment]
1min to resize is entirely expected on many drive/system configurations. ext4 on spinning HDD or USB devices can be slow.
