### ISSUE TITLE
Make Cassandra version strictly numerical

### ISSUE THREAD

**Issue by florinpapa** [clearlinux/distribution#1067]
The current Cassandra version in Clear Linux is reported as `3.11.4-SNAPSHOT`, causing the cassandra python package to fail at run time when setting up https://github.com/Instagram/django-workload

```
$ DJANGO_SETTINGS_MODULE=cluster_settings django-admin setup
. . .
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ValueError("invalid literal for int() with base 10: '4-SNAPSHOT'",)})
. . .
```

Can someone please remove the `-SNAPSHOT` from the version string?

**Comment by ahkok** [comment]
@AthenasJimenez ?

**Comment by ZhongbaoShi** [comment]
@wxb071216 , Jue, could you help on?

**Comment by florinpapa** [comment]
I just confirmed that the issue comes from the Cassandra version. For me, the `cassandra` pip package breaks here because it expects the version to be strictly numerical:
```
/home/clear/venv/lib/python3.7/site-packages/cassandra/util.py:1254:        self.patch = int(parts.pop()) if parts else 0
```

**Comment by wxb071216** [comment]
I will submit a patch to remove SNAPSHOT from version string soon.

**Comment by AthenasJimenez** [comment]
I see this issue has been fixed, so closing for now. 

[Commit](https://github.com/clearlinux-pkgs/cassandra/commit/84e9e1cdbed2636cdcad71d7839fff775f6d995a)

**Comment by florinpapa** [comment]
I don't see how the commit on Jul 10 fixes this issue.

**Comment by phmccarty** [comment]
The fix has been merged, but it's not in a release yet. Reopening.

**Comment by florinpapa** [comment]
I was able to pull the latest cassandra and this issue is fixed. I will go ahead and close. Thank you for fixing this.

**Comment by phmccarty** [comment]
Yep, this was fixed in release `30800`.
