### ISSUE TITLE
Support ClearLinux in Tencent Cloud

### ISSUE THREAD

**Issue by jwang11** [clearlinux/distribution#1069]
I have been working on ClearLinux in Tencent Cloud for a few days. The key problem I need to resolve is ssh keys can't be injected into image when ucd doing cloud-init at first boot inside Tencent environment. I have talked with Tencent support to get their meta-data service details.  Finally, I can make ucd work with Tencent cloud now. I submitted the patch to ucd, https://github.com/clearlinux/micro-config-drive/pull/36.

**Comment by ahkok** [comment]
If there's a patch we can close this and resolve in the linked PR.
