### ISSUE TITLE
Flatpak unable to run correctly.

### ISSUE THREAD

**Issue by FoxBuru** [clearlinux/distribution#107]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

Flatpak is unable to run. The file /usr/share/dbus-1/system.d/org.freedesktop.Flatpak.SystemHelper.conf doesn't exists. This helper is used during the escalation privileges phase to be able to run install/update/remote-add as a normal user, asking for credentials dynamically if needed using polkit. Adding it manually, solves the Segmentation Faults when trying to remote-add. and allows to install/update without problems.

### References

https://github.com/flatpak/flatpak/blob/master/system-helper/org.freedesktop.Flatpak.SystemHelper.conf

**Comment by mrkz** [comment]
will look into it.

**Comment by ahkok** [comment]
I've added this file, and updated flatpak to 0.99.2. Once this updates, please test and let us know if there are any additional issues. The fix should be available 7/3.
