### ISSUE TITLE
how to enable kdump on clearlinux?

### ISSUE THREAD

**Issue by mcao6** [clearlinux/distribution#1070]
kdump is an important feature to debug some kernel panic issues. Is there a guide or wiki to enable it on ClearLinux?

**Comment by miguelinux** [comment]
@mcao6 Clear Linux  disabled **kexec**,  please refer to https://github.com/clearlinux/distribution/issues/397#issuecomment-461168526.

>Yes, we don't have kexec enabled for security reasons. It allows non-signed code to be executed and, generally speaking, arbitrary code to be executed. We explicitly disallow that.

You can create/build your own kernel with **kexec** enabled for **kdump**

**Comment by mcao6** [comment]
@miguelinux thanks for your info!  one question further: we can enable kernel support by enable related configure macro; but for kdump-tools, we have to build, and install it in clearlinux? or is there  a general BKM?

**Comment by miguelinux** [comment]
On Clear Linux currently we don't have a BKM, you can follow what upstream said: 

https://www.kernel.org/doc/Documentation/kdump/
https://www.kernel.org/doc/Documentation/kdump/kdump.txt

You can download, compile and install
https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.20.tar.xz

it will be installed to `/usr/local` which is good, and compile your own kenrel.

**Comment by miguelinux** [comment]
Just move binaries from `/usr/local/sbin` to `/usr/local/bin`

**Comment by mcao6** [comment]
@miguelinux  OK, thank you!  you can close this ticket.
