### ISSUE TITLE
Add 'dpftextract' - companion to thermal_daemon

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#1073]
Here's the link to dptfextract:
* https://github.com/intel/dptfxtract

Let me know how I can help.

**Comment by miguelinux** [comment]
Usually Clear Linux  is open source package sourced.
Maybe a good solution is to create a documentation on how Clear Linux users can use it.

**Comment by ahkok** [comment]
We shouldn't package this. We can't audit that it doesn't do anything weird, nor can we fix it if there are problems with it.
