### ISSUE TITLE
Nano editor could easily be enhanced to show colors

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#1074]
Right now when using `nano` you don't see any color coding. On other Linux distributions nano shows the colors. This is easy to enable on clear linux by doing the following. 

```
ls -1 /usr/share/nano/*.nanorc | sed 's/^\//include \//' >> ~/.nanorc
```

**Comment by miguelinux** [comment]
@abecastillo

**Comment by eadamsintel** [comment]
I just tried this on a different clear linux box and it worked.  I think i was using an old version or looking at the wrong file.  I will close this.
