### ISSUE TITLE
dhcp leases lost always occurred in clearlinux

### ISSUE THREAD

**Issue by ewanglong** [clearlinux/distribution#1079]
1)Either in clearlinux desktop or aws images, we can see frequent "DHCP lease lost" messages by journalctl. It may cause Ethernet lost and recovery in shortly. But for other based-on virtual network tun/tap like docker0, it caused lots of additional work including “Lost carrier, link_config: autonegotiation, port 1(veth2eb1ae2) entered disabled state" etc. In some case of heavy workloads running, it will cause network lost at last;

2)But by comparing it in ubuntu, we saw it do dhcp-renew before DHCP lease expired. This maybe good reference. For example, journalctl will show "renewal in 1565 seconds." when it's dhcp server configure the lease time is 1800 seconds.

So is there configurable netplan to do dhcp-renew other than dhcp request only when dhcp lease lost?

**Comment by ahkok** [comment]
Is this system using NetworkManager to manage the ethernet interfaces, or, systemd-networkd?

**Comment by ewanglong** [comment]
Originally this issue was observed when aws image used systemd-networkd. After installation of NetworkManager bundle, still saw this issue reproducible.

**Comment by ewanglong** [comment]
Updated it latest. When disabling systemd-networkd after installation of NetworkManager, this issue cannot be reproduced.  Then we saw "dhdp renew" in journalctl.
