### ISSUE TITLE
`lynx` not working

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1083]
This bundle is added recently, but it's not working due to the lack of `lynx.cfg` and `lynx.lss` file, which are available in the package but not included in `rpm` generated by autospec.

Here is the list of files in the package, https://lynx.invisible-island.net/lynx2.8.9/breakout/index.html

Also, would you set the configure option `--with-screen=ncursesw` instead of `--with-screen=ncurses`.

**Comment by shaoyuta** [comment]
I found the same issue.
But even if add lynx.cfg , lynx.lss to fold /etc/, lynx still will crash.
Segmentation fault (core dumped)

**Comment by lebensterben** [comment]
>I found the same issue. ...

@shaoyuta I can reproduce this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ganeshmaharaj** [comment]
Same issue for me. Bumping this up in the bug list. 

```
ganeshma@ganeshma-lab2 <> ~ % sudo swupd bundle-add lynx
Loading required manifests...
No packs need to be downloaded
No extra files need to be downloaded
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts
Successfully installed 1 bundle
ganeshma@ganeshma-lab2 <> ~ % lynx

Configuration file "/etc/lynx.cfg" is not available.

```

**Comment by bryteise** [comment]
Hrm looks like it needs a bit of stateless work.

**Comment by bryteise** [comment]
Hrm segfaulting inside ncurses in a way I don't understand. May be a little bit. For those who want to follow along at home my package changes so far are [here](https://github.com/bryteise/lynx).

**Comment by phmccarty** [comment]
@bryteise Can you sync with @shaoyuta, since it looks like they have been investigating the segfault. (See #1130)

**Comment by bryteise** [comment]
@phmccarty thanks for the linkup

**Comment by lebensterben** [comment]
Closing this issue since it's working now.
If someone still sees segfaults, I will reopen this.
