### ISSUE TITLE
Please update `gnutls` to 3.6.9

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1084]
Currently it's 3.6.7, below are the release notes for 3.6.8 and 3.6.9, which contains bug fixes

https://lists.gnupg.org/pipermail/gnutls-help/2019-May/004527.html
https://lists.gnupg.org/pipermail/gnutls-help/2019-July/004556.html

**Comment by phmccarty** [comment]
Thanks for the notice! I'm working on the update to 3.6.9.

**Comment by phmccarty** [comment]
The update to 3.6.9 has been integrated. It will available in 30670 or newer.

**Comment by phmccarty** [comment]
This package was updated in release `30670`.
