### ISSUE TITLE
python-subnettree module missing?

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#1087]
I installed a bundle:
<pre>
$ swupd bundle-add  network-monitor-node
Loading required manifests...
Downloading packs (27.15 Mb) for:
 - suricata
 - network-monitor-node
        ...100%
Finishing packs extraction...
No extra files need to be downloaded
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts
Successfully installed 1 bundle

</pre>
Then I issued the command:
<pre>
$ trace-summary

</pre>

I get:
<pre>
Traceback (most recent call last):
  File "/usr/bin/trace-summary", line 21, in <module>
    import SubnetTree
ModuleNotFoundError: No module named 'SubnetTree'

</pre>

Seems CLR misses the package "python-subnettree" (and include it in the bundle "network-monitor-node")

Searching for the package failed:
<pre>
sudo swupd search python-subnettree
Search failed, no reasonable results found

</pre>

**Comment by fenrus75** [comment]
adding now

and need to debug why this isn't getting caught in our QA tests

**Comment by phmccarty** [comment]
Should be fixed in release `30670`
