### ISSUE TITLE
Is it possible to pack Tensorflow profiler?

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1088]
Hi guys:
Is it possible to add tensorflow profiler to the tensorflow bundle?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/g3doc/command_line.md

Best
Stokhos

**Comment by phmccarty** [comment]
Tensorflow was removed from Clear Linux OS in November, so we can close this request.
