### ISSUE TITLE
Can not open files in flatpaks

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#109]
I can not open files on the host system using flatpaks. E.g. org.keepassxc.KeePassXC can not open a database file. Trying to do so does not even show a file dialog.

KeePassXC is a Qt application, so that might actually be an integration issue with Qt and flatpak.

**Comment by ahkok** [comment]
This looks like an upstream issue. The Qt libraries bundled with this flatpak are not the clearlinux Qt/KDE files, but the flathub KDE platform components'.

**Comment by hunger** [comment]
I do not think that this is an issue with the flatpak: They *do* work on fine on my machine if I boot into a different Linux version.

**Comment by ahkok** [comment]
can you run `flatpak list` ? Qt is provided by the `org.kde.Platform` flatpak, and not by the OS. So you're potentially running into issues with that flatpak.

**Comment by hunger** [comment]
As I said: The same set if flatpaks work on other distributions.

I even installed all of them in clearlinux and mounted /var/lib/flatpak from clearlinux into the other distribution.

It does not work in clearlinux but does work in the other.

So I doubt that this is a problem in the flatpaks.

**Comment by hunger** [comment]
All the flatpaks are listed the same on both distributions.

**Comment by AthenasJimenez** [comment]
I tried this out as well using Fedora and Clear Linux, on Clear is not working as expected. I would dig a little more and try to fix this. For now, the only work around I can recommend is running KeePassXC with sudo, that's how I make it works.

sudo -E flatpak run org.keepassxc.KeePassXC

**Comment by AthenasJimenez** [comment]
Issue fixed on release 23840.

**Comment by ahkok** [comment]
For reference, the fix was: 

https://github.com/clearlinux-pkgs/xdg-desktop-portal/commit/b633b5e74f1b0e3a91136978d0c64f5c1506a078
