### ISSUE TITLE
/usr/lib64/libjli.so overwritten during post install

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#1093]
Every time I do a `swupd repair`, the symlink `/usr/lib64/libjli.so` is "fixed", because it is being overwritten at post-install time, presumably by one of the update trigger services. I have not identified which service is to blame, so I am filing a bug for tracking.

When swupd fixes the symlink, the target value is:

```
$ ls -l /usr/lib64/libjli.so                                                                                                                                               
lrwxrwxrwx 2 root root 59 Feb  1  2019 /usr/lib64/libjli.so -> /usr/lib/jvm/java-1.8.0-openjdk/jre/lib/amd64/jli/libjli.so
```

However, after the update triggers complete, you can see that the symlink has been overwritten, pointing to a new target:

```
$ ls -l /usr/lib64/libjli.so 
lrwxrwxrwx 1 root root 11 Aug  5 15:02 /usr/lib64/libjli.so -> libjli11.so
```

**Comment by phmccarty** [comment]
@AthenasJimenez Any ideas on what is causing this?

**Comment by AthenasJimenez** [comment]
no, but I'll take a look.

**Comment by AthenasJimenez** [comment]
java8 depends on /usr/lib/jvm/java-1.8.0-openjdk/lib/amd64/jli/libjli.so 
java11 depends on /usr/lib/jvm/java-1.11.0-openjdk/lib/jli/libjli.so

These dependencies makes ldconfig to overwrites the value of /usr/lib64/libjli.so everytime it runs. So, to avoid this situation I did patched openjdk11 and rename the library from libjli.so to libjli11.so. Should be fixed  on release 30810.

/usr/lib64/libjli11.so -> /usr/lib/jvm/java-1.11.0-openjdk/lib/jli/libjli11.so
/usr/lib64/libjli.so -> /usr/lib/jvm/java-1.8.0-openjdk/jre/lib/amd64/jli/libjli.so

openjdk11 commit: https://github.com/clearlinux-pkgs/openjdk11/commit/7d410f6611b03dc511fbd9cb1d80444d5a0cb40a
