### ISSUE TITLE
`file` broken: `Bad system call`

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#1096]
```
$ file /usr/bin/lsusb.py 
Bad system call
$ file /usr/bin/file
Bad system call
$ file /
Bad system call
```

`30670`

**Comment by phmccarty** [comment]
Must be related to my change: https://github.com/clearlinux-pkgs/file/commit/b1e247acf3b477770b9e22d3e541ddc3bbd266c6

**Comment by phmccarty** [comment]
Fix in progress

**Comment by phmccarty** [comment]
Fixed in release `30700` with https://github.com/clearlinux-pkgs/file/commit/46b2e93e916b63134631f6fec96a301ba5e23a3a
