### ISSUE TITLE
Clear Linux website intellectual property compliance

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#11]
The main Clear Linux uses Clear Linux*.

![screen shot 2018-01-23 at 7 14 41 pm](https://user-images.githubusercontent.com/33820650/35308168-404f599a-0074-11e8-8de0-ea3871e5a3fd.png)

This is ostensibly to provide proper attribution for the Linux trademark.

The * refers to this:

![screen shot 2018-01-23 at 7 15 21 pm](https://user-images.githubusercontent.com/33820650/35308187-551689de-0074-11e8-93f6-d2e1ea4621a5.png)

Which is a link a trademarks page on [Intel.com](https://www.intel.com/content/www/us/en/legal/trademarks.html).

The problem is, there is no trademark notice for Linux there:

![screen shot 2018-01-23 at 7 17 04 pm](https://user-images.githubusercontent.com/33820650/35308204-7357708e-0074-11e8-8a20-c9632813ff6b.png)

Under the Linux [trademark sublicense agreement](https://www.linuxmark.org/programs/legal/trademark/sublicense-agreement), Intel has to state the following:

> "The registered trademark Linux® is used pursuant to a sublicense from the Linux Foundation, the exclusive licensee of Linus Torvalds, owner of the mark on a world­wide basis."

You should probably have Intel legal review the website and the trademark disclosure page for compliance regarding Linux, Amazon, and Microsoft trademarks listed on the Clear Linux website.

**Comment by fenrus75** [comment]
thank you for your report

we have worked closely with the LF on the trade mark things and we are ok.
