### ISSUE TITLE
[Packaging Request] TDE

### ISSUE THREAD

**Issue by Vistaus** [clearlinux/distribution#110]
### What is the issue type?

* [ ] Bug report
* [x] Enhancement request

### Describe the problem

It would be great if Trinity Desktop Environment (TDE) could be included in Clear Linux. If it gets included, I'll switch to Clear Linux.

Website: http://trinitydesktop.org

**Comment by fenrus75** [comment]
hmm the last release was in 2016.. that's... concerning. Do you know if
there is active development happening?

**Comment by Vistaus** [comment]
Yes, as you can see in the commit history, there is very active development :)
https://trinitydesktop.org/patches/
If you want, you could also package it from the latest git master or something, that's what Q4OS (the only distribution to use TDE by default) has done in the last release.

**Comment by thiagomacieira** [comment]
Sorry, I don't think we can. It looks like Trinity installs binaries with the same names as the standard applications from KDE does. At least that's what I see in <https://build.opensuse.org/package/view_file/home:PunisherHD:Trinity:stable/k3b/k3b-14.0.4.spec?expand=1>. How do other distributions handle this, as some are quite strict about never installing anything in a prefix other than /usr? Can you provide links to their official packages?

We're also concerned about continuing development of Qt 3. Trinity looks to have taken up development of it, but it's still a toolkit EOLed by the original developers close to 10 years ago. There seems to have been only minor upkeep commits in the last 4 years, not active development. Note we don't even package Qt 4 at this time.

**Comment by Vistaus** [comment]
Qt 3 has seen minor commits by the TDE Team because:

1 It's rock solid already.
2 A Qt 4 port of TDE is under development, which will open up the way for a Qt 5/6 port eventually.

TDE itself sees active development, they also added support for modern things like screen brightness buttons on laptops and other modern stuff in git master last year. Could it have more active development? Sure. But the team is small (much like the MATE team), so they can only do so much in their spare time. They do have active meetings with the community as well, so they are very, very loyal and dedicated.

I want to point you to the Q4OS packages, but their repo is not available online AFAIK (or at least, they don't publicly link to it) but I know that they add -tde after everything. So e.g. Ark become ark-tde, K3B becomes k3b-tde, etc.

**Comment by thiagomacieira** [comment]
Take it from someone whose job has been to fix everything that was wrong with Qt 3 for the past 15 years: no, it's not rock solid. Just for starters, the `QStrings` are not thread-safe and the containers are using early 1990s technology you'd see in a C framework, not a proper C++ one.

In any case, the lack of there being official packages in other distributions pretty much seals this one. We take our cue from them and usually need one (preferably two) major distro to ship something for us to be convinced. I did a cursory search in Fedora, Debian, openSUSE, Arch and Gentoo and couldn't find it. Please provide links if I missed anything.
