### ISSUE TITLE
Desktop-Awesome Enhancement Requests

### ISSUE THREAD

**Issue by dedguy21** [clearlinux/distribution#1100]
Hello, the current desktop awesome needs several additional programs to serve as a stand alone desktop option.

It would be great if we could add the following programs to the existing bundle:

1) Autorandr - display profile detection
2) Arandr - display set up
3) Rofi
4) Blueman - including bluez tools
5) pa-applet (pulse audio applet)
6) nm-applet (network manager applet)
7) GVFS - without which we lose a lot of functionality in whatever file manager chosen
8) light - for brightness ctl
9) a file manger my preference would be thunar or PCManFM
10) some type of screen locker my preference would be i3lock (not sure if lightdm comes with light_locker 
11) awmtt -- for theming testing
12) mousepad or leafpad
13) Poppler
14) lxpolkit (or mate-polkit-agent)
15) udevil
16) file-roller
17) rxvt-unicode
18) urxvt-perls
19) scrot
20) some type of battery monitor icon

**Comment by hnanni** [comment]
Il giorno mar, 06/08/2019 alle 14.03 -0700, dedguy21 ha scritto:
> Hello, the current desktop awesome needs several additional programs to serve as a stand alone desktop option.
> 
> It would be great if we could add the following programs to the existing bundle:
> 

Hello @dedguy21.
Yep, the desktop-awesome is extremely lean. I need to decide which other items
it should include so it is usable right after of the swupd bundle-add
operation.

I'll use your list as an starting point of what other persons use/need/want. It
is an interesting list, for example hadn't heard of arand, neither light (which
could replace the clunky shell scripts I use to achieve their functionality).
awmtt sounds cool.

I'll prefer to keep the bundle small and have the SW that is packed in other
bundles in those extra bundles (e.g. poppler, gvfs). But lets see

> Autorandr - display profile detection
> Arandr - display set up
> Rofi
> Blueman - including bluez tools
> pa-applet (pulse audio applet)
> nm-applet (network manager applet)
> GVFS - without which we lose a lot of functionality in whatever file manager chosen
For gvfs and the such, while the awesome bundle get revamped, you may use
"bundle-add desktop"
> light - for brightness ctl
> a file manger my preference would be thunar or PCManFM
> some type of screen locker my preference would be i3lock (not sure if lightdm comes with light_locker
> awmtt -- for theming testing
> mousepad or leafpad
> Poppler
> lxpolkit (or mate-polkit-agent)
> udevil
> file-roller
> rxvt-unicode

The terminal is already in the bundle ;)
> urxvt-perls

though, not the items for !Urxvt*perl-lib

**Comment by dedguy21** [comment]
Thank you for your consideration. 

I also forgot to mention that it might be useful to have a front end for software manager, I'm ok with the cli but some users like the visuals.

**Comment by dedguy21** [comment]
Also a branded version of awesome WM ( clear Linux wallpaper and icon) wouldn't be a bad idea either

**Comment by dedguy21** [comment]
There's a project here on GitHub called awesome-gnome that integrates awesome wm with gnome-flashback (metacity). If you would include this in the bundle then a user would have gnome but with awesome as the windows manager. Then you could keep this bundle pretty light I guess. Worth checking out?

https://www.google.com/url?sa=t&source=web&rct=j&url=https://github.com/SirJson/awesomewm-gnome&ved=2ahUKEwi-pqqM5ZzkAhVCheAKHYiFACMQFjACegQIBhAC&usg=AOvVaw2N-ZC_Cj0G9u0MUWFkPXTi

**Comment by lebensterben** [comment]
>There's a project here on GitHub called awesome-gnome that integrates awesome wm with gnome-flashback (metacity). If you would include this in the bundle then a user would have gnome but with awesome as the windows manager. Then you could keep this bundle pretty light I guess. Worth checking out? ...

@dedguy21 I suggest to separate those package requests into different issues. It's easy to track and this kind of mega request just discourage people even to try.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dedguy21** [comment]
But it isn't a separate issue. The issue is the current desktop-awesome bundle is pretty useless out if the box in it's current state. The above programs,any of which already exists in Clear dev-pkg and a few on GitHub can be included in the awesome WM bundle to provide a great stand alone experience out of the box. Manjaro does it with just a few scripts. So it isn't a "big" request really. If I knew how to use the mixer tool I'd do it myself.

**Comment by dedguy21** [comment]
Where's the edit button?

**Comment by todfox** [comment]
@hnanni just wondering if you have made any progress on this?

**Comment by hnanni** [comment]
@todfox sorry. I'm not working on this

**Comment by todfox** [comment]
@hnanni If you're not working on this. Do you know who is?

**Comment by lebensterben** [comment]
>@hnanni If you're not working on this. Do you know who is? 

@todfox Why not trying to package those programs with autospec by yourself. And send your autospec configs and patches to the mailing list.

**Comment by dedguy21** [comment]
Should have been closed long ago
