### ISSUE TITLE
wpa_supplicant does not support Access Point mode

### ISSUE THREAD

**Issue by MarkRose** [clearlinux/distribution#1102]
I'm unable to create a WiFi access point. My device supports AP mode according to `iw list`, but I get the error:

    # nmcli dev wifi hotspot ifname wlp0s20f0u9 ssid foo password barbazqux 
    Error: Failed to setup a WiFi hotspot: Connection 'Hotspot' is not available on device wlp0s20f0u9 because profile is not compatible with device (wpa_supplicant does not support Access Point mode)

This is on Clear Linux 30690. WiFi as a client works fine.

In #985 @ahkok mentioned enabling `CONFIG_AP` but I don't know if that happened.

**Comment by bwarden** [comment]
I've theoretically enabled it. Should be in release within 1-2 days. This issue will be automatically updated when it's published.

**Comment by MarkRose** [comment]
I can confirm it's fixed, at least for this issue.
