### ISSUE TITLE
Add numlockx to x11-tools bundle

### ISSUE THREAD

**Issue by 0n0w1c** [clearlinux/distribution#1108]
The numlockx utility is used to manipulate the status of the numlock key.

**Comment by nsgnn** [comment]
Would this be a new package or just to include it into the bundle?

**Comment by 0n0w1c** [comment]
Adding numlockx to the x11-tools bundle would be fine, I do not have a need for it to be packaged separately.

**Comment by fenrus75** [comment]
I'd prefer it in the existing bundle; there's a set of these very small (in
size) but useful tools, the overhead of a separate bundle is more than the
size of the files added up :0
I'll see what it takes to package

(also a minor request for the future; if you could put in an URL in as
well.. sometimes the same name is used by multiple tools and it avoids the
confusion if you also have an URL)
