### ISSUE TITLE
Add xscreensavers to the x11-tools bundle

### ISSUE THREAD

**Issue by 0n0w1c** [clearlinux/distribution#1109]
No screensavers are installed with xscreensaver. Please add the screensavers to the X11-tools bundle. Often other distros they are installed via separate packages ie. xscreensaver-extras or some such package name.

**Comment by lebensterben** [comment]
>No screensavers are installed with xscreensaver. Please add the screensavers to the X11-tools bundle. Often other distros they are installed via separate packages ie. xscreensaver-extras or some such package name.

@0n0w1c I the past screensaver is needed because if the screen shows the same image from a long time, it would 'burn' it self. But is this really needed now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by 0n0w1c** [comment]
I am building for our production environment in which we have a security policy that requires the obfuscating of the screen and to be password locked after a period of inactivity. While "blanking" the screen is sufficient, some users prefer to have pretty things displayed.

**Comment by 0n0w1c** [comment]
The screensavers are usually stored in /usr/libexec/xscreensaver/ and the configs go into /usr/share/xscreensaver/. These default paths prevent me from installing them myself.

**Comment by ahkok** [comment]
Try `/usr/local/libexec/xscreensaver` and `/usr/local/share/xscreensaver`

Note: xscreensaver is unmaintained, insecure, and really really out of date. I strongly encourage you to use alternatives.

**Comment by 0n0w1c** [comment]
I'll beg to differ with you on the status of the XScreenSaver project. [https://www.jwz.org/xscreensaver/changelog.html](url)

I will attempt to install the screensavers in the alternate directories as advised.

**Comment by 0n0w1c** [comment]
![image](https://user-images.githubusercontent.com/47831850/63020007-86d9bd80-be62-11e9-81f4-cbc48bdb88b3.png)

**Comment by 0n0w1c** [comment]
Placing the screensavers in the /usr/local/ path does not seem to work. Maybe if the configuration is run with --prefix=/usr/local/ this location would work?

For now, I copied the screensavers from another distro and placed them in the normal locations.

**Comment by 0n0w1c** [comment]
To be more socially conscious and progressive, maybe also add [https://boinc.berkeley.edu/wiki/BOINC_screensaver](url) to a bundle to help fold proteins, search for intelligent alien life, or many other mass parallel computing projects?

**Comment by hnanni** [comment]
@fenrus75  do you know why the binaries that xscreensaver is meant to display are %exclude 'd
https://github.com/clearlinux-pkgs/xscreensaver/blob/master/excludes

**Comment by bwarden** [comment]
> (On Linux, it is a screensaver for XScreenSaver, but not supplied with it.)

We do ship /usr/bin/boincscr in the boinc-client bundle.

**Comment by 0n0w1c** [comment]
Bah, I searched the web site and a "swupd search bionic" and nothing. But you are correct, a "swupd search bionic-client" does indeed find the bundle. Thank you.

**Comment by ahkok** [comment]
I've created a new `xscreensaver` and `xsceensaver-extras` bundle. These give you the basics and all the extras.
