### ISSUE TITLE
Blank screen with mouse pointer after reboot

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#111]
I just rebooted my clearlinux installation after upgrading to 23370 (with desktop bundle).

The system comes up and I see the mouse pointer I expect from the graphical login. But the screen stays black and there is no input field or any other UI showing up. I can move the mouse pointer though.

I can switch to a different console and log in there, but I have a rectangle of random pixels in the upper left corner of the screen when I do that.

Checking the journal, I see that Gnome-Shell stopped due to some error in a script pointing to ModemManager.

![screenshot from the journal](https://i.imgur.com/6Xg1aV4.jpg)

**Comment by fenrus75** [comment]
thanks for the great picture; with it I found that the MM version update
changed in.. interesting.. ways and needed a bit of attention to make sure
the gir/typelib of it gets shipped properly.
23410 or later should have it (I'll try to kick that off later today,
probably in a few hours)

**Comment by hunger** [comment]
When will the fix become available? My laptop is currently almost unusable due to this issue.

**Comment by ahkok** [comment]
Usually bug fixes are available in normal updates within 24h.

**Comment by hunger** [comment]
@ahkok: Just asking since I have been on 23370 for a while now and that still seems to be current:-(

**Comment by ahkok** [comment]
Yes, the update that was generated early this morning had errors, so normally this would have already been fixed and available to you. We'll hopefully have an update out later today, though.

**Comment by hunger** [comment]
Still no update:-(

**Comment by fenrus75** [comment]
450 got out 5 minutes ago

**Comment by ahkok** [comment]
> <Kestutis> but gnome-shell still not working after todays update

(verified this was with 450)

**Comment by hunger** [comment]
Yes, saw it right after complaining about the missing update:-(

23450 fixes the issue for me.

A huge THANK YOU from me!

**Comment by KestutisMa** [comment]
Strange, because it doesn't fix for me. But workaround is to use gnome-flashback, just "startx".
log: https://pastebin.com/zFDXCaUJ
screenshot https://photos.app.goo.gl/q87CLJ4cL1iaNuyo8
also "poweroff" and "reboot" shell commands don't work

**Comment by hunger** [comment]
That image is not the behavior I got: I had a black screen with the mouse pointer and nothing else. You got a different bug than me.

My bug is fixed. Go file a different issue to track yours.

**Comment by KestutisMa** [comment]
I had mouse over black screen before, but after update to 23450 I have this.
