### ISSUE TITLE
Support switch of multiple versions of a package in Clear Linux

### ISSUE THREAD

**Issue by ttzeng** [clearlinux/distribution#1114]
Clear Linux always provides the latest stable version of packages is good, but in some scenarios, some software may depends on specific version of packages, or the development may require an older tool-chain. We can setup multiple versions of a software in Ubuntu, and use 'update-alternatives' to switch between different versions. Is there similar mechanism in Clear Linux to do the same?

For example, I'd like to roll-back to tensorflow-1.12, but since Clear Linux ships with Python 3.7, only tensorflow-1.13 and above is available for Python 3.7.

**Comment by thiagomacieira** [comment]
We can't do that. It's an core building block of how bundles work that there's exactly one of each file from any and all sources. We can't select one of multiple.

What we can do is provide additional bundles that contain what you want. That can be provided as part of the distribution itself, like we do with compat libraries or with gcc8 (c-basic-gcc8 bundle), or by way of a third party swupd repository that installs elsewhere.

Therefore, I'm closing this, as we cannot satisfy what you asked. If you have specific versions of things you require, please file tickets with the reasoning. We need a very strong reason to accept and the software in question must be offering security fixes in the version you're asking for.
