### ISSUE TITLE
Please add `isync`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1118]
> A command line utility for synchronizing remote IMAP mailboxes and local maildir-style mailboxes. This is useful for working in disconnected (off-line) mode, such as on a laptop, but also for mirroring mailboxes between servers.
https://sourceforge.net/projects/isync/

**Comment by ahkok** [comment]
Any reason not to use `fetchmail` + `procmail`? This is the go-to implementation and has been working since forever. I'll look at adding this, though.

**Comment by ahkok** [comment]
Will be available in 1-2 working days.

**Comment by lebensterben** [comment]
>Any reason not to use `fetchmail` + `procmail`? This is the go-to implementation and has been working since forever. I'll look at adding this, though.

@ahkok Thanks.

The reason for not using `fetchmail` is it doesn't support keywords/tags according to `notmuch`'s comparison on mail fetchers [here](https://notmuchmail.org/software/).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
