### ISSUE TITLE
Separate SDDM bundle

### ISSUE THREAD

**Issue by 0n0w1c** [clearlinux/distribution#1119]
SDDM can be used by multiple desktops environments (ie. LXQt). Currently SDDM is only supplied by the desktop-kde bundle which is far more to install than desired for a DM. Please make a smaller bundle just for SDDM, similar to what was made for lightdm.

**Comment by ahkok** [comment]
@anselmolsm can I ask you to consider making this bundle, and make it work e.g. without plasma installed?

**Comment by anselmolsm** [comment]
Released in 31050.
