### ISSUE TITLE
Additional support for printers

### ISSUE THREAD

**Issue by FoxBuru** [clearlinux/distribution#112]
### What is the issue type?

* [ ] Bug report
* [X] Enhancement request

### Describe the problem

It'd be great if clearlinux could add some extra cups filters (like Gutenprint or Foomatic, for example). Right now if you need to print you have to do a very obscure procedure to make it work, or hope that your printer supports any kind of USB printing / Web Printing.

**Comment by fenrus75** [comment]
Gutenprint should be in the current releases
