### ISSUE TITLE
formatbump goes wild? Unable to update with 29750 as server version

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#1124]
```
$ sudo swupd update -s
Current OS version: 30740
Latest server version: 29750
There are no updates available
```
Confirmed by me, reported by @ganeshmaharaj

**Comment by ahkok** [comment]
@gtkramer @mbelluzzo @abecastillo @phmccarty

**Comment by sunnyflunk** [comment]
Well the version matches what's found here:
https://download.clearlinux.org/update/version/format28/first
https://download.clearlinux.org/update/version/format28/latest

**Comment by ganeshmaharaj** [comment]
I have no idea how formatbump is supposed to work, but i do see a `format29` in that folder. https://download.clearlinux.org/update/version/format29/ Should this be getting the preference somehow?

**Comment by miguelinux** [comment]
```
$ curl https://download.clearlinux.org/latest
30740
$ curl https://cdn.download.clearlinux.org/latest
30740
```

**Comment by ahkok** [comment]
The content on the CDN/download server is for sure incorrect. We'll let devops figure out a path to resolution.

**Comment by gtkramer** [comment]
This issue has been fixed.  We pushed outdated version files from our builder rather than from our staging server by accident.
