### ISSUE TITLE
libglfw bundle ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#1125]
Any chance to get the dev glfw library ?
https://www.glfw.org/

It is a dependency of the vlang compiler for graphical apps :
https://vlang.io/

**Comment by ahkok** [comment]
It will be `devpkg-glfw3` due to the name of the `.pc` file. Should be available in 1-2 working days.

**Comment by nsauzede** [comment]
thanks !!!!

**Comment by nsauzede** [comment]
looks like the bundle 'glfw3' is on its way..
will the the 'devpkg-glw3' bundle be also available in the same release ?
I'm on 30820 currently, but search for 'glfw' returns nothing

**Comment by nsauzede** [comment]
@ahkok it seems like I still can't find glfw3 nor devpkg-glfw3

<pre><font color="#3465A4"><b>~</b></font>$ sudo swupd bundle-add devpkg-glfw3 glfw3
Loading required manifests...
Warning: Bundle &quot;glfw3&quot; is invalid, skipping it...
Warning: Bundle &quot;devpkg-glfw3&quot; is invalid, skipping it...
Failed to install 2 of 2 bundles
<font color="#3465A4"><b>~</b></font>$ sudo swupd search glfw3 devpkg-glfw3
Search failed, no reasonable results found
<font color="#3465A4"><b>~</b></font>$ sudo swupd info
Distribution:      Clear Linux OS
Installed version: 30970
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
<font color="#3465A4"><b>~</b></font>$ 
</pre>

**Comment by bryteise** [comment]
Currently we need to manually create a bundle for this.

**Comment by nsauzede** [comment]
@bryteise thanks for taking time with this one

**Comment by bryteise** [comment]
Okay, this is in the repo and should be in a build near you soon.

**Comment by nsauzede** [comment]
thanks so much @bryteise 
having devpkg glfw3 would allow testing V language in CLR
