### ISSUE TITLE
Upgrade Docker and Kata Containers versions

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1127]
Work to get Docker 19.03.1 and Kata Containers 1.8 upgraded.

/cc @mcastelino @ganeshmaharaj

And while we're at it, we could review the kata-runtime patches on how we set kata-runtime as the runtime option for cri-o/docker.

**Comment by bryteise** [comment]
Want to ensure firecracker integration with kata isn't broken with the new release and that the k8s works with the updated crio parts I would imagine.

We should also reassess the mechanisms used for setting and unsetting the use of the kata-runtime by default.

@CraigSterrett I would like to talk to you about this task if you have time to chat this week.

**Comment by CraigSterrett** [comment]
I will setup some time to chat

**Comment by hnanni** [comment]
adding myself to the thread

**Comment by miguelinux** [comment]
@bryteise me to :-)

**Comment by mythi** [comment]
The versions are updated.
