### ISSUE TITLE
Please add libratbag

### ISSUE THREAD

**Issue by AWHubGit** [clearlinux/distribution#1132]
I installed "flatpak install flathub org.freedesktop.Piper".
Piper requires libratbag’s ratbagd, the daemon to actually communicate with the mice. Piper is merely a front end to ratbagd, ratbagd must be installed and running when Piper is launched.
ratbagd cannot be flatpaked yet so users must install manually.
Please add libratbag
https://github.com/libratbag/libratbag

**Comment by ahkok** [comment]
I'll put this in the `games` bundle. It'll take 2+ working days for it to be included.
