### ISSUE TITLE
"Fontconfig error: Cannot load default config file" when running VSCode

### ISSUE THREAD

**Issue by rieznik** [clearlinux/distribution#1138]
Hello! Could not find a bug about this but experienced it twice. I think it might be connected to the electron apps.

**Steps to reproduce:**

1. Download tar.gz VSCode form Microsoft website https://code.visualstudio.com/Download#
2. Run VSCode `./code`

It will show the error
`Fontconfig error: Cannot load default config file`

**System information:**
```
$ swupd info
Installed version: 30800
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```

Let me know if I can provide more information.

**Comment by ahkok** [comment]
Could be the same issue as:

https://github.com/clearlinux/distribution/issues/639#issuecomment-495972657

**Comment by rieznik** [comment]
@ahkok yes, thank you :pray:
