### ISSUE TITLE
[java] openjdk test InfoTest.java failed on java packages

### ISSUE THREAD

**Issue by vivanov-gh** [clearlinux/distribution#1142]
The openjdk test jdk/java/lang/ProcessHandle/InfoTest.java failed on the java11-basic bundle for the ClearLinux with message:
"java.lang.AssertionError: Command: expected: 'sleep', actual: /usr/bin/coreutils expected [true] but found [false]"

This tests passed on the RHEL7.7

How to reproduce:
checkout openjdk ws:
hg clone https://hg.openjdk.java.net/jdk-updates/jdk11u
checkout latest build for the jtreg harness
https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg
set java11 as default java in system, JT_HOME and PATH variables
run tests as
jtreg jdk/java/lang/ProcessHandle/InfoTest.java

Note, this test start the 'sleep' command and try to read name of executed process. The test expects that process name is 'sleep'.

**Comment by fenrus75** [comment]
this is a test bug afaics

coreutils and BusyBox both do single tool binary with symlinks for space
and performance reasons...
all standards allow this as well

**Comment by vivanov-gh** [comment]
mark it as 'expected' and exclude test.
