### ISSUE TITLE
Please update `stack` to 2.1.1

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1145]
Current version of `stack` is 1.9.3, but the latest version is 2.1.1.

**Comment by anselmolsm** [comment]
In fact there's 2.1.3 already

**Comment by phmccarty** [comment]
I integrated the update to 2.1.3, and it should be available within a couple of days.

**Comment by phmccarty** [comment]
The update to 2.1.3 landed in release `31030`.
