### ISSUE TITLE
swupd diagnose always fails for the dtc bundle

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1148]
When installing the dtc bundle, updating, and then diagnosing, swupd fails with the following error:
```
Missing file: /usr/lib/libfdt.so.1
```
Installing the dtc bundle and then updating should not result in this error.

**Comment by phmccarty** [comment]
I have updated the package to 1.5.1 and fixed the library install path to be `/usr/lib64` instead of `/usr/lib`. So, let's see if that results in improvement.

**Comment by phmccarty** [comment]
The packaging changes for `dtc` in release `30950` appear to have fixed the issue. Please reopen if you can still reproduce.
