### ISSUE TITLE
Add clang-tidy

### ISSUE THREAD

**Issue by deepankarsharma** [clearlinux/distribution#115]
We use GitHub issues for bug reports and enhancement requests.
If you have a troubleshooting issue or have questions, please write to our
mailing list: dev@lists.clearlinux.org. You can also find helpful folks on our
IRC channel: #clearlinux on irc.freenode.net.

------------------------

### What is the issue type?

* [ ] Bug report
* [X] Enhancement request

### Describe the problem

Would like to request clang-tidy tool be added to c-basic bundle.

**Comment by fenrus75** [comment]
release 23530 (entering QA now) should have this

**Comment by ahkok** [comment]
bundles: dev-utils, c-basic

**Comment by snoe925** [comment]
It does not seem that clang-tidy is available at this time?

$ swupd search clang-tidy
Search failed, no reasonable results found
$ swupd info
Distribution:      Clear Linux OS
Installed version: 31270
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

**Comment by thiagomacieira** [comment]
It's in a different source tarball. I'll add it.

**Comment by thiagomacieira** [comment]
Added. Will be in a build near you in the near future.
