### ISSUE TITLE
[java] the openjdk test sun/tools/jinfo/Basic.sh failed on java-basic package

### ISSUE THREAD

**Issue by vivanov-gh** [clearlinux/distribution#1153]
The openjdk test jdk/test/sun/tools/jinfo/Basic.sh failed on java-basic package with message:
================
sysctl: cannot stat /proc/sys/kernel/yama/ptrace_scope: No such file or directory
Exception in thread "main" java.lang.reflect.InvocationTargetException
================

This test try to call command "sysctl -n kernel.yama.ptrace_scope" before the test run and this command on Clear Linux failed with this message (ptrace_scope: No such file or directory).
This test works on RHEL7.7.

If it is expected behavior for the Clear Linux I'll mark this test as invalid and exclude it. Otherwise fix this issue on the OS level.

**Comment by AthenasJimenez** [comment]
@miguelinux can you confirm if we have enable/disable this?

**Comment by miguelinux** [comment]
CL do not enabled YAMA
https://github.com/clearlinux-pkgs/linux/blob/master/config#L7918

So, **Yes**, this is expected in CL.

**Comment by AthenasJimenez** [comment]
Ok, closing it since this is not supported on CLR.
