### ISSUE TITLE
[java] openjdk test sun/security/lib/cacerts/VerifyCACerts failed for java-basic package

### ISSUE THREAD

**Issue by vivanov-gh** [clearlinux/distribution#1156]
The openjdk test jdk/tets/sun/security/lib/cacerts/VerifyCACerts.java failed on the java-basic package with output:
===============================
cacerts file: /usr/lib/jvm/java-1.8.0-openjdk/jre/lib/security/cacerts
...
ERROR: 199 entries, should be 88
ERROR: camerfirmachambersignca [jdk] is not in cacerts
ERROR: thawteprimaryrootcag2 [jdk] is not in cacerts
ERROR: entrust2048ca [jdk] is not in cacerts
...
ERROR: cert "intelintranetbasicissuingca1a" expiry "Fri May 15 11:41:30 PDT 2015" will expire within 90 days
ERROR: cert cannot be verified:Signature does not match.
ERROR: cert cannot be verified:Signature does not match.
ERROR: cert is expired
ERROR: cert "intelintranetbasicissuingca2a-2" expiry "Fri May 15 11:46:56 PDT 2015" will expire within 90 days
ERROR: cert cannot be verified:Signature does not match.
ERROR: cert is expired
...
===============================
This test passed on RHEL 7.7.

The reason for this failure is used cacert file. In case of RHEL it is "jre/lib/security/cacerts" file from the jdk workspace (size: 98310). In case of Clear Linux it is link:
> ls -la /usr/lib/jvm/java-1.8.0-openjdk/jre/lib/security/cacerts
lrwxrwxrwx 1 root root 44 Feb  1  2019 /usr/lib/jvm/java-1.8.0-openjdk/jre/lib/security/cacerts -> /var/cache/ca-certs/compat/ca-roots.keystore
> ls -la /var/cache/ca-certs/compat/ca-roots.keystore
-rw-r--r-- 1 root root 258487 Aug 16 17:46 /var/cache/ca-certs/compat/ca-roots.keystore

**Comment by AthenasJimenez** [comment]
Closing since test doesn't apply.
