### ISSUE TITLE
Experiment for far faster boot time 

### ISSUE THREAD

**Issue by LifeIsStrange** [clearlinux/distribution#1158]
https://www.phoronix.com/scan.php?page=news_item&px=LG-Optimize-Hibernate-Boot

**Comment by lebensterben** [comment]
hey, I see no source code

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LifeIsStrange** [comment]
@lebensterben
Me neither :m
I guess Kyungsik Lee from LG should be emailed or Michael from phoronix.

**Comment by ahkok** [comment]
Not interesting. This isn't a full explanation but it goes roughly like this:

- hibernate is buggy and unreliable
- booting is likely always faster if you do booting properly
- the posted resume times are not impressive
- extreme wear on NAND media
- there's a time cost to suspending!
- the cost of power suspending and resuming isn't worth it
- you're going to have to reboot for an updated kernel anyway
- sometimes you really want to shed old processes from cgroups that are unmaintainable (desktop sessions), so rebooting/restarting has benefits

(I'm not saying there are no benefits to doing this, my point is that this is likely only useful in very limited use cases, and generally is not useful instead).

**Comment by LifeIsStrange** [comment]
@ahkok well your points seems valid but I would like to say that from my experience on a laptop SSD, windows boot noticeably faster than my linuxes and I guess it's because they handle well hibernation.
(cf windows 10 fast boot feature) 

I would like Linux to catch up on this front, and to know what is needed to make *hibernate is buggy and unreliable* no longer true.

But you can indeed keep the issue closed as this is less actionable.

**Comment by fenrus75** [comment]
do you have your clear Linux machine boot slower?

**Comment by LifeIsStrange** [comment]
@fenrus75 well to be honest I'm not yet on clear linux, but I've observed this on both fedora and arch Linux.
Maybe you could time on average clear Linux boot time vs W10 time on a "representative laptop"?

Anyway this is not high priority

**Comment by LifeIsStrange** [comment]
Wow I see that you made huge boot time improvements! 
https://www.phoronix.com/scan.php?page=news_item&px=Clear-Linux-Kernel-3s-to-300ms

**Comment by ahkok** [comment]
Note: That is not actually an engineer in the clearlinux OS team, and the results of that experiment are not merged into the clearlinux kernels.
