### ISSUE TITLE
Installer hangs on downloading part of installation

### ISSUE THREAD

**Issue by Jacalz** [clearlinux/distribution#1166]
I have been quite successfull in the past with installing Clear, but my atempts today just went really bad. I had a usb stick with a 2 to 3 week old installation image on it. I had used it for the same amount of time ago to install to my 1TB external hard drive, which was everything I had available at the time. It’s a usb 3 spinning disk and it worked great to install it back then.

Today I tried using the old installer and installing to another usb 3 disk with less capacity (500 GB) because I needed the 1TB disk for other stuff. When using the installer it when on to the downloading of packs and went to one fourth of the full bar until it just stoped and didn’t want to move any more.

I figured that I probably had an installer that was too old so I flashed on the latest version available and user enough it failed at the same stage in installation but this time it came to three quarters of the way before stoping. I restarted my pc and tried again and sure enough it failed at the very same point. I looked at the system monitor and no data was being downloaded at all and the internet was fully functional to 100 mb/s...

**Comment by Jacalz** [comment]
We currently have a power outage, but the power should be back tomorrow. I will retry the installation then if I get the time :)

**Comment by Jacalz** [comment]
I have now tested to install once again, after having a huge thunder storm yesterday which wiped out all the power in my whole city. Notable in the logs is that I gave up at 19:28 which is pretty much 40 minutes after the last call in the `clr-installer.log` file, I also set the password to null in `pre-install-clr-installer.yaml` to be on the safe side.

[logs.zip](https://github.com/clearlinux/distribution/files/3557069/logs.zip)

**Comment by mdhorn** [comment]
@Jacalz Thank you for sharing the log information.
Yes, it appears that swupd stalled in the middle of downloading the content for the install. Swupd should timeout if the network connection is lost or becomes unstable.

Is the installation always stopping at the same point? Or after a similar amount of time?
I'm wondering what type of internet connection you have; 5G? Cable? Fiber?  
I've seen something similar happen if the network endpoints change; for example, your external IP address (or the system's IP address) changes during the install.
Maybe check how long your dhcp lease time is?

Seems like something changed network wise in the past few weeks. 
We can also check with the swupd owners about reasons for possible hangs during the download of packs.

**Comment by Jacalz** [comment]
It was stopping at roughly one forth of the full installation bar when I tried installing with the image from a couple weeks ago, but the three last tries with version 30850 has been stopping at almost the same point. I think it almost exactly the same point with three quarters filled on the installation bar, but it's hard to tell for certain.

My internet connection to this computer is a wall plug feeding internet over the power network in the house. The network infrastructure behind that is fiber with 500/100 in terms of megabit per second speed, but I get around 100/100 with these wall plugs because I haven't had the time to drag a wire in to this room. While they tend to be a bit unstable in some situations they usually (when they fail) stop working completely and have to be plugged in and out again, though that is maybe a once in a month situation. I have had internet connection when I shut down the installer so that is not the problem.

Yeah dhcp lease times may be a factor in the equation, especially with the wall plugs. I will try to plug them in to a switch directly and see if that changes things.

**Comment by Jacalz** [comment]
Managed to install it now without any issues using a cable to the nearest switch. Might be related to some weird behavior of the wall plugs, but it really shouldn’t cause swupd or the installer to freak out like they do...

**Comment by mdhorn** [comment]
Glad you were able to get the installation completed.
Yes, the installer needs swupd to install the OS content, and it should not hang.
I've been trying to create a reproducible test case of swupd hanging and not recovering to submit a GitHub Issue in [their repo ](https://github.com/clearlinux/swupd-client), but no luck so far.
Each time I've tried disconnecting the network for a minute or two and reconnecting it, swupd has recovered. May have to try with a short DHCP lease time. If I can document a non-recoverable case I will open an Issue against swupd-client.
