### ISSUE TITLE
Asus VivoBook S15: no boot from USB unless edit to remove intel_ucode

### ISSUE THREAD

**Issue by adacaccia** [clearlinux/distribution#1168]
and no boot from the laptop even after a successful installation!
At power-on, the ASUS logo appears, then it just stays like this, forever...

So the only system log I can share is the one I've got from the live USB itself, which I made to boot by editing the "Clear Linux" line at boot time, in order to remove the reference to initrd=[...]intel_ucode.cpio.

Finally, let me share that I've come to this workaround from my little 2 months experience with this laptop with other distros (Manjaro and SwagArch, both Arch derivatives), and a big 20y+ experience in Linux.

So I guess the problem lies with the CPU itself (an 8th gen i7), prior to go and look to internal vs discrete Nvidia GPU.

Please advise, since at the moment it seems no Linux distribution works well on this Laptop (Ubuntu 19.04 is not even able to boot from the USB stick at all, and since there's no mention to intel_ucode on the GRUB line, my usual workaround didn't help that tine; Manjaro is unstable withe the graphics, and cannot boot most of the times unless I remove intel_ucode; SwagArch had the only issue with the failing boot, but it is discontinued nowadays), and I've come to Clear Linux OS while hunting a solution on Google... but I really LOVE the stateless approach, so I would really like choosing Clear Linux OS as my default distribution from now on!
[Xorg.0.log](https://github.com/clearlinux/distribution/files/3550811/Xorg.0.log)
[journalctl-xb.log](https://github.com/clearlinux/distribution/files/3550828/journalctl-xb.log)

**Comment by adacaccia** [comment]
The BIOS is working fine AFAIK, plus there's the chance it can only be
updated by a Windows app, so no-go for me.
Moreover, it is the Linux Kernel trying to update CPU's internal microcode
by means of the Intel_ucode file, and I can add that I've managed to
install Arch Linux then GNOME on top of it, and everything is now working
fine.
I've done this by first deleting initrd Intel_ucode stuff when booting Arch
from USB, then purposely ignorating grub instructions on how to add CPU
microcode update on boot!
On Clear Linux, I've got the chance to only remove the ucode stuff when
booting from USB, but then the system became completely useless: even
accessing it from the Live, no file had been touched after the install!
Finally, as a Clear Linux area for improvement, I've noticed by looking at
the journal I've attached from the live, that the "systemd first" approach,
while providing undoubtedly many advantages, has got a severe drawback,
since it clearly states that it just dropped 2k+ kernel messages, whose I
guess were the usual kernel boot messages, so we missed even processor
model (which is an i7-8565, as seen from the BIOS).
Adalberto


Il mer 28 ago 2019, 18:59 Lucius Hu <notifications@github.com> ha scritto:

**Comment by ahkok** [comment]
> The BIOS is working fine AFAIK, plus there's the chance it can only be updated by a Windows app, so no-go for me.

To save you the time, I checked for you. It appears ASUS BIOS update version 307 is available but it looks like a file that can be dropped on the UEFI system partition and then applied through the BIOS screen.

https://www.asus.com/support/faq/1030673

https://www.asus.com/Laptops/ASUS-VivoBook-S15-S510UN/HelpDesk_BIOS/

> ... while providing undoubtedly many advantages, has got a severe drawback, since it clearly states that it just dropped 2k+ kernel messages, whose I guess were the usual kernel boot messages, so we missed even processor model

Archlinux also uses systemd. Likely, they don't load early microcode and this leaves your system possibly vulnerable. Because there are issues applying the firmware, this is likely causing the long kernel dmesg output, and causing the dmesg buffer to overfill. You can tune the dmesg buffer size and make it larger, of course. Clearlinux also enables module init timestamping which consumes additional buffer space.

But that's not sufficient reason to blame systemd for everything, really. Let's try and stay focused on the problem.

**Comment by adacaccia** [comment]
Hi,
I'm pleased to announce that after a BIOS upgrade (from version 300 to 305,
since my model is X530FN), intel_ucode worked fine for the first time!
And it cnotinued to boot OK every morning in the last week, so I reckon the
BIOS upgrade has really fixed the issue.
Many thanks,
best regards
Adalberto


Il giorno ven 30 ago 2019 alle ore 23:26 ahkok <notifications@github.com>
ha scritto:

**Comment by adacaccia** [comment]
I'm goingo to install ClearLinux on all my PC's!!!
Thank you all!
Adalberto
