### ISSUE TITLE
coturn TURN server

### ISSUE THREAD

**Issue by pixelblender** [clearlinux/distribution#1169]
TURN server is critical component in setting up WebRTC infrastructure. Any chance to have it on Clear Linux?

https://github.com/coturn/coturn

**Comment by ahkok** [comment]
Added. Will be a `coturn` bundle. You'll for now need to manually add the `turnserver` user ID, since I haven't allocated a UID for it just yet.

Please test when this bundle becomes available (after the weekend, I think) and file bugs in case you encounter issues with it.
