### ISSUE TITLE
incompatible 'time' and missing 'gtime'?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#117]
### What is the issue type?

[* ] Bug report
[* ] Enhancement request

### Describe the problem

Trying again to switch from Ubuntu to ClearLinux to compile openwrt, unfortunately one of the first errors i get is: `Build dependency: Please install GNU 'time' or BusyBox 'time'`

based on:
```
$(eval $(call SetupHostCommand,time,Please install GNU 'time' or BusyBox 'time', \
	gtime --version 2>&1 | grep GNU, \
	time --version 2>&1 | grep GNU, \
	busybox time 2>&1 | grep BusyBox))
```

`time --version` = bash time has no --version option
`gtime` and `busybox `= no bundle exists containing those

Maybe bash time could be changed to a full version or add gtime in some bundle?

**Comment by Andy2244** [comment]
Manually compiling gnu-time from [ftp.gnu.org](https://ftp.gnu.org/gnu/time/time-1.9.tar.gz) and putting it as `/usr/bin/gtime` seems to fix this issue.

**Comment by fenrus75** [comment]
time is also a bash builtin which is likely what you get. We do have
/usr/bin/time in one bundle

Bundle os-testsuite-phoronix    [installed]     (18551 MB on system)
        /usr/bin/time

but that's a large one. suggestions for other places to put it welcome

**Comment by ahkok** [comment]
I'll add `/usr/bin/time` to `sysadmin-basic` bundle, which isn't that large.

**Comment by ahkok** [comment]
I'd almost suggest filing a feature request instead to bundle `openwrt` entirely in clearlinux already, given its wide use.

**Comment by Andy2244** [comment]
> I'd almost suggest filing a feature request instead to bundle openwrt entirely in clearlinux already, given its wide use.

What do you mean by "bundle openwrt" ? I just want a working dev-platform to compile/build it from source and these days ClearLinux us my choice for doing some light linux stuff in a VM.

**Comment by ahkok** [comment]
I put `/usr/bin/time` into `performance-tools` and `sysadmin-basic` bundles, so hopefully in a day or so that will be released and available. Please do consider making a separate request for `openwrt`!

**Comment by ahkok** [comment]
@Andy2244 with `bundle openwrt` I meant have clearlinux offer (include) `openwrt` as a bundle that can just be installed (with `swupd`), without having the need to compile it.

**Comment by Andy2244** [comment]
@ahkok mhh i think we have some miscommunication here, openwrt itself is a linux distro mainly for router and embedded devices. So what would be the point bundling it?

PS: I actually only work with the openwrt sdk, since i'm the maintainer of a hopefully soon to-be merged samba-4.8 package, to replace the older samba36. I use ClearLinux as host to crosscompile for other targets (arm, mips), which i than test via qemu.

**Comment by Andy2244** [comment]
oki time is now picked up by the sdk on the latest clearlinux versions. 
Maybe add a softlink to `gtime`, since the script also tests for this name:
`gtime --version 2>&1 | grep GNU, \`

I also notice that the new bundled version gives a "unknown" version, while my own manual compiled showed "1.9", whats up with this?

**Comment by nesiusra** [comment]
Confirming the version is not reported correctly... 

$ /usr/bin/time --version
time (GNU Time) UNKNOWN
...

**Comment by bryteise** [comment]
Updating time fixes the unknown version.

**Comment by Andy2244** [comment]
@bryteise Thanks, sdk builds fine now, without any extra changes.

**Comment by bryteise** [comment]
Yay!
