### ISSUE TITLE
Nginx-Mainline - unknown directive "set_real_ip_from" / "real_ip_header"

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1170]
Nginx-maineline module is missing `"set_real_ip_from"` and `"real_ip_header"` directives which are used to fetch the real IP of connections when using Nginx as a proxy. Furthermore this is commonly utilized in Jenkins and XenForo installations.

This can be solved by compiling Nginx with "--with-http_realip_module".

Thanks.

**Comment by ahkok** [comment]
Pushed to koji, please test in 2-3 days.

**Comment by ahkok** [comment]
`nginx-mainline-1.17.3-82`
