### ISSUE TITLE
Nginx Unit bundle request

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1171]
Nginx Unit is a new package that offers a lot of new functionalities and it's used alongside of a regular Nginx installation, here's a quote from the release news:
> NGINX Unit is a dynamic web and application server, suitable for both stand‑alone applications and distributed, microservices application architectures. It launches and scales application processes on demand, executing each application instance in its own secure sandbox. 

**Resources:**
https://www.nginx.com/products/nginx-unit/
https://www.nginx.com/blog/nginx-unit-1-0-released/

**Usage example:**
https://www.nginx.com/blog/installing-wordpress-with-nginx-unit/
https://unit.nginx.org/installation/

Thanks!

**Comment by ahkok** [comment]
Seriously, why do people think writing their own manual configure scripts is OK.

**Comment by ahkok** [comment]
Ok, I think I have it worked out. It will have `python3` and `php` support. Should be in a bundle `nginx-unit` in a few days.
