### ISSUE TITLE
libmodplug

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#1173]
Hi, any chance to get libmodplug-dev ?

It seems required for SDL2 Mixer (already present in CLR) to offer MOD-like format support (MOD (trackers), MID, etc..)

It is available in standard on MSYS2 (windows), and Ubuntu

Apparently, this package is in public domain and might be hosted here :
https://github.com/Konstanty/libmodplug

**Comment by ahkok** [comment]
May require extra work - I'm investigating.

**Comment by nsauzede** [comment]
Note that I'm unsure of the actual upstream source repository.

Maybe it could be :
https://sourceforge.net/p/modplug-xmms/git/ci/master/tree/
As seen here :
http://modplug-xmms.sourceforge.net/

**Comment by nsauzede** [comment]
Note I could succesfully build from source on CLR :
`$ \rm -rf libmodplug;git clone https://github.com/Konstanty/libmodplug.git;cd libmodplug/;libtoolize;aclocal;autoheader;automake --add-missing;autoconf;automake;./configure --prefix=`pwd`/the_install && make install`
Not sure how to proceed creating a bundle/dev-bundle then.. :-(

**Comment by ahkok** [comment]
That was somewhat frustrating to accomplish. Out in 1-2 days.

**Comment by nsauzede** [comment]
Thanks for the SDL_mixer / libmodplug support : I confirm it works.
However, it does not provide libmodplug support for SDL2 (SDL1 might EOL at some point, who knows..)

Note that I managed to enable the libmodplug support compiling SDL2_mixer sources manually,
but with some hack because their configure seems to be bugged.
Here is the command line :
`$ (export MODPLUG_LIBS="buggybuggy" MODPLUG_CFLAGS="-I${HOME}/perso/tmp/sdl/libmodplug/libmodplug/the_install/include" ; ../SDL2_mixer-2.0.4/configure --prefix=`pwd`/the_install && make clean install)`

With that I obtain a libSDL2_mixer so which does support MODs (tested by overriding LD_LIBRARY_PATH)

HTH & BR,
NS.

**Comment by nsauzede** [comment]
Should I open another issue, for the specific SDL2 (Two) support ?

**Comment by ahkok** [comment]
Let's figure it out over here :)

I pushed something, but, can't test atm. Revisit in 2 days when it's released and circle again.

**Comment by nsauzede** [comment]
Hey @ahkok I confirm that SDL2_mixer as shipped with CLR 30970 *does* support music (MODPLUG), and it works really fine
Thanks !
