### ISSUE TITLE
Add new devpkg for gnu-efi (`devpkg-gnu-efi`)

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/distribution#1174]
The development files for `gnu-efi` are currently only available via the `os-core-dev` bundle which is quite large. Creating such `devpkg-gnu-efi` would considerably reduce the size of the environment to be installed to compile [ACRN](https://projectacrn.org). This would be especially useful when creating a container image based on Clear Linux that can build it.

If it's as simple as adding this to `auto.devpkgs`, then I have a PR ready for it ;)

**Comment by gvancuts** [comment]
https://github.com/clearlinux/clr-bundles/pull/152

**Comment by ahkok** [comment]
Just needs a bundle now, I believe?

**Comment by bryteise** [comment]
Bundle change is made, will be out next week.

**Comment by gvancuts** [comment]
> Bundle change is made, will be out next week.

Thanks 👍
