### ISSUE TITLE
TPM device is not shown in clear-30840-live-server.iso.

### ISSUE THREAD

**Issue by xyzhao2018** [clearlinux/distribution#1179]
I installed clear-30840-live-server.iso on a NUC7i5DNH. But found TPM device is not there. 
I have checked in BIOS, there is TPM device on my NUC. 
Just remembered that TPM drive has been enabled in kernel, but why it was not shown in clear-30840-live-server.iso ?

By the way, I have checked /usr/lib/kernel/config-5.2.10-828.native and , /usr/lib/kernel/config-5.2.11-829.native, CONFIG_TCG_TPM=m is set, but CONFIG_TCG_CRB=m is not set. 
Not sure whether it is the reason why TPM driver is not enabled.

**Comment by amygilliam1** [comment]
What do you need this functionality for?

**Comment by miguelinux** [comment]
CL blacklist the tpm modulles at **/usr/lib/modprobe.d/tpm-blacklist.conf**,
but the user can overwrite this blacklist.
    
To load TPM modules just do:
```    
$ sudo mkdir -p /etc/modprobe.d
$ sudo ln -s /dev/null /etc/modprobe.d/tpm-blacklist.conf
```

I'm adding the missing _tpm_crb_ module.

You will find this update in 1 or 2 days on kernel **linux-5.2.11-830**

**Comment by xyzhao2018** [comment]
Thanks so much. 
Currently, the kernel on my machine is linux-5.2.11.829. 
Does this mean the clear linux image release in 1 or 2 days will update into linux-5.2.11.830, right?

**Comment by miguelinux** [comment]
> Does this mean the clear linux image release in 1 or 2 days will update into linux-5.2.11.830, right? 

Yes

**Comment by miguelinux** [comment]
@xyzhao2018 I'm closing this as the change is in the kernel.
