### ISSUE TITLE
[Enhancement] 'make' bash completion missing

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#118]
### What is the issue type?
[* ] Enhancement request

### Describe the problem

While trying to switch from Ubuntu to ClearLinux i noticed that make auto-completion is not working, something like `make m->` = `make menuconfig` or `make def->` = `make defconfig`

Would be nice to have those, similar to ubuntu.

**Comment by fenrus75** [comment]
this is odd, since tihs works for me, make m<tab> expands.to options
(listing choices if there are multiple etc)

or did you mean some other type of autocomplete?

**Comment by Andy2244** [comment]
What i mean is that if i use the openwrt sdk as example:
`git clone https://git.openwrt.org/openwrt/openwrt.git`

Under Ubuntu i can switch into the openwrt directory and type `make m<tab>`, which gets expanded to `make menuconfig`, same thing with `make d<tab>` = `make defconfig`.
If i compare what `make <tab>` lists on Ubuntu vs ClearLinux, it seems under ClearLinux only files, folders are know, while Ubuntu knows the make/makefile commands, so some "magic" is happening there.

**Comment by fenrus75** [comment]
so this works for me. going to check which bundles this is in

**Comment by ahkok** [comment]
```
Bundle shells	[installed]	(264 MB on system)
	/usr/share/bash-completion/completions/make
```

**Comment by Andy2244** [comment]
@ahkok ok thanks works now, was assuming these come with the same bundle that adds make etc. (c-basic)?

**Comment by ahkok** [comment]
we could do that, but it would be a lot of work since those all come from one package. By default, we don't install the `shells` bundle, which is how you ran into this issue. Ideally maybe we add `shells` as a dependency of `dev-utils` bundle, perhaps.
