### ISSUE TITLE
Mounting /var on another physical disk causes boot issues

### ISSUE THREAD

**Issue by dedguy21** [clearlinux/distribution#1180]
I've attempted to mount my /home and /var folders on another physical disk. While I mounting /home folder causes no issues, every time I try to mount the /var on a disk other than where "/" folders is located it causes boot issues. 

Something in the boot process is rejecting the configuration on my fstab of /var being mounted on a different physical disck.

**Comment by ahkok** [comment]
Did you migrate `/var` or just mount an empty mountpoint over it?

**Comment by dedguy21** [comment]
I migrated. Unfortunately I the permissions settings weren't set to the
standard 755 for /var and so Clear Linux rejected the folders until I
corrected the settings.

**Comment by ahkok** [comment]
Given your last message I assume that the permissions were the cause, as that seems the most likely culprit here.

**Comment by dedguy21** [comment]
Solved... Permissions on folder were not set correctly
