### ISSUE TITLE
syncthing-GTK no update check at start-up

### ISSUE THREAD

**Issue by AWHubGit** [clearlinux/distribution#1182]
Each time syncthing-GTK starts it throws:
me.kozec.syncthingtk.desktop[1041]: I App           Checking for updates...
me.kozec.syncthingtk.desktop[1041]: I App           Warning: No write access to daemon binary; Skipping update check.

me.kozec.syncthingtk was installed from flathub.

**Comment by ahkok** [comment]
This software is packaged by and maintained by flathub.com, not clearlinux. The daemon it refers to runs on the inside of the flatpak sandbox - there is nothing I can see that the clearlinux team can do about. I think you want to raise this issue with the flathub project here:

https://github.com/flathub/me.kozec.syncthingtk/issues/new

**Comment by AWHubGit** [comment]
Thanks. Sorry for my mistake.
Raised issue with https://github.com/flathub/me.kozec.syncthingtk/issues
