### ISSUE TITLE
lost network interfaces on backup using rsync /dev/sda3 root to sdb3

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1183]
I have dual Samsung 860 512GB SSD on a live running Clear Linux LEMP stack.
However I'm testing this on a local home PC with similar dual SSD setup before deploying the rsync backup strategy to the Live server.

sda is primary SSD root being on /dev/sda3

sdb is secondary backup SSD root being on /dev/sda3

sdb is same size model SSD intended to be a bootable backup for the primary SSD running Clear Linux LEMP stack. The intent is to use rsync or similar backup tool on a nightly crond to backup the installation on running sda3 root partition to a root partition of second storage device. If the primary SSD goes down, dies etc I can remote to the machine, get into the BIOS and change the boot order to the the secondary backup SSD and reboot and continue operations until such time the failed storage device can be replaced.

In testing on the home PC with a keyboard monitor and mouse (KVM) I run command:

`sudo mount /dev/sdb3 /mnt`

then rsync command:

`sudo rsync -ahPHAXx --delete --exclude={/mnt/*,/media/*,/lost+found} / /mnt`

It copies everything from dev/sda3 (root on running live system) to the second sdb3 root partition. Essentially the rsync command is configured to copy any files from source to destination that do not exist on destination, copy newer files from on the source to the destination and replace existing files on destination that are older than the equivalent file on the source.  

After switching boot device to the second SSD (after rync'd the data) I boot and login directly with local KVM, however I cannot ssh into it from another machine because apparently the IP address on the copy is not the same supplied DHCP IP.

It didn’t display a local IP like was supposed to be 192.168.1.8

The backup copy appears has completely lost all network interface configuration.

So seems there’s some network file or config that rsync is either not copying or some other issue preventing the copy to resolve ip address.

I ran `/sbin/ifconfig` and

![clear-linux-rsync-clone-no-ip](https://user-images.githubusercontent.com/49221849/64223837-ebd77f00-cf07-11e9-9316-c3ec8a279e38.JPG)

Locally i've tried to reconfigure the network interface with nmtui apparently according to this utility theres no interfaces available to configure. I did add a en0 and configured it as auto. Rebooted and still no interface appears.

ifconfig reports only lo the loopback interface nothing else.

My rsync command and Clear Linux seem to have some issues, maybe corruption of files, maybe network interface config files not being copied etc.

I noticed also the nvidia frame buffer is not executed on the backup resulting in not native display resolution text size.

Anyone have any clear ideas on whats going wrong and or have a working rsync config to allow this backup strategy with Clear Linux? Thanks

**Comment by ketonik** [comment]
This may have been the result of previously creating an fstab file in /etc of sda3 (to mount sdb3 on restart) then running rsync after.

`# [device-spec] [mount-point] [fs-type] [options] [dump] [pass]
/dev/sdb3	/mnt		ext4		defaults	0 0`

I've since reinstalled Clear Linux (an older version) to sdb3 with the clr-installer, destructively. The ran rsync command:

`sudo rsync -axHAWXS --numeric-ids --info=progress2 --delete --exclude={/mnt/*,/media/*,/lost+found} / /mnt`

 to sdb3 and i've not seen the same issues. 

I assume fstab caused some issues deeper in the system than anticipated.
I guess also that once trying to boot the second SSD sdb with a copied fstab which telling it to mount sdb3 to /mnt is the heart of the problem, perhaps as a guess it gave the kernel faulty instructions.

**Comment by ahkok** [comment]
There's certainly many things that can be done to facilitate some stuff like this, but I feel this isn't a `bug` in the classical sense - things are working as intended here, and that's causing confusion.

Have you considered perhaps instead using software raid-1 (mirroring) to accomplish this very thing? Also `btrfs` snapshots are likely a good solution here, removing some of the complexities that are causing what you see.

`journalctl -a` may prove instrumental as to what happened to the network and should contain output.

Bootloaders have to be properly configured as well and they can't be identical setups for obvious reasons, you'd be booting the wrong rootfs.

**Comment by ketonik** [comment]
> There's certainly many things that can be done to facilitate some stuff like this, but I feel this isn't a `bug` in the classical sense - things are working as intended here, and that's causing confusion.

I agree, not a bug. Another user reported no issue with the rsync command:

[](https://community.clearlinux.org/t/rsync-to-clone-root-sda3-to-sdb3-can-boot-to-backup-but-cant-ssh-no-ip/1496/4?u=ketonik)

I put it down to the fstab config mentioned in my follow up. Consider it user misunderstanding.

> Have you considered perhaps instead using software raid-1 (mirroring) to accomplish this very thing? Also `btrfs` snapshots are likely a good solution here, removing some of the complexities that are causing what you see.

I have considered Raid1 and found some rather uninspiring performance of EXT4 in Raid1 in a SQLite v3.22 test I saw:

[](https://www.phoronix.com/scan.php?page=article&item=samsung-960-raid&num=2)
 
PostgreSQL:

[](https://www.phoronix.com/scan.php?page=article&item=linux418-nvme-raid&num=3)

> `journalctl -a` may prove instrumental as to what happened to the network and should contain output.

Thanks, will note this for future

> Bootloaders have to be properly configured as well and they can't be identical setups for obvious reasons, you'd be booting the wrong rootfs.
