### ISSUE TITLE
`CONFIG_CDROM=m` and `CONFIG_BLK_DEV_SR=m` in `-kvm` kernel - should be builtin for `config-drive` support

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#1184]
Boot is currently slowed down significantly on many of our hypervisor kernels where `config-drive` support is used. This causes the system to fail to initialize early despite all the devices to be available, but not mounted and ready to use.

For at minimum, the `linux-kvm` kernel, `CONFIG_CDROM` and `CONFIG_BLK_DEV_SR` should be builtin, and not a module.

This is likely less applicable for other hypervisor kernels, though.

**Comment by miguelinux** [comment]
It will be available at **linux-kvm-5.2.11-383**
