### ISSUE TITLE
[BBT][devpkg-talloc]broken symlinks in /usr/bin64

### ISSUE THREAD

**Issue by sleonbau** [clearlinux/distribution#1185]
In build 30680, we have a broken symlink for bundle devpkg-talloc
This is the error
```
not ok 12 no broken symlinks in /usr/lib64 
# (in test file clean_FHS.t, line 81) 
# `[ -z "$links" ]' failed 
# 1338357 0 lrwxrwxrwx 1 root root 54 Mar 26 22:09 /usr/lib64/libpytalloc-util.cpython-37m-x86-64-linux-gnu.so -> libpytalloc-util.cpython-37m-x86-64-linux-gnu.so.2.2.0 
```

**Comment by phmccarty** [comment]
@sleonbau Is this a new regression, or has it been present for a while?

**Comment by sleonbau** [comment]
it has been for a while since build 30680 (Aug 6ht). It was reported in JIRA but we moved here to have more visibility on the issue, and have it solved soon

**Comment by phmccarty** [comment]
@sleonbau Okay, thank you. I have a fix in progress.

**Comment by phmccarty** [comment]
After attempting some additional housekeeping on the talloc package, and I ran into an autospec bug. I would prefer to resolve that issue before integrating this fix.

https://github.com/clearlinux/autospec/issues/463

**Comment by phmccarty** [comment]
Fixed in release `30960`.
