### ISSUE TITLE
ruby-basic's irb doesn't include readline support

### ISSUE THREAD

**Issue by ChaiTRex** [clearlinux/distribution#1187]
Readline support appears to not be built into `irb`

0. Install the `ruby-basic` package
0. Run `irb`
0. Enter a line like `5 + 2`
0. Press Enter to execute the line
0. Press the up arrow to modify the previous line
0. Note that the up arrow fails to work properly

**Comment by phmccarty** [comment]
Thanks for the report. I have integrated a fix for `ruby`, and it should be available within a couple days.

**Comment by phmccarty** [comment]
Fixed in release `30960`.
