### ISSUE TITLE
does not install on virtualbox ! hangs ! there is no NEXT button on lang page

### ISSUE THREAD

**Issue by osde8info** [clearlinux/distribution#1188]
host cpu i5 
does not install on virtualbox ! hangs ! there is no NEXT button on lang page

![VirtualBox_clear_05_09_2019_10_04_50](https://user-images.githubusercontent.com/51541/64331955-9c5a8700-cfcb-11e9-84e8-4641b5cd6088.png)

![VirtualBox_clear_05_09_2019_10_03_47](https://user-images.githubusercontent.com/51541/64331858-792fd780-cfcb-11e9-8d9b-bfe11e876d88.png)

**Comment by puneetse** [comment]
Use the live-server installer with the documentation here: https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/virtualbox-cl-installer.html

The virtalbox linux guest additions, which provide graphics capabilities, aren't available until after installation so using the live-desktop installer doesn't work well.

**Comment by osde8info** [comment]
ok thanks will try that

**Comment by osde8info** [comment]
cant get past CANCEL INSTALL options will have to wait until gui installer is working

**Comment by puneetse** [comment]
That probably means you're missing a required option to proceed in the installer.
Follow https://docs.01.org/clearlinux/latest/get-started/bare-metal-install-server.html#bare-metal-install-server which is linked to see what might be missing.
