### ISSUE TITLE
veracrypt

### ISSUE THREAD

**Issue by adriank41** [clearlinux/distribution#1190]
hi,I know that cryptsetup can encrypt / decrypt veracrypt file,but with veracrypt is easy and convenient.

**Comment by puneetse** [comment]
I was interested in this at one point too but moved onto another task because there is a non-SPDX license: https://github.com/veracrypt/VeraCrypt/blob/master/License.txt#L200

Maybe @ahkok can help evaluate

**Comment by ahkok** [comment]
We can't consider this right now. Sorry.

**Comment by puneetse** [comment]
> We can't consider this right now. Sorry.

For those searching in the future, can you shed light on why?
