### ISSUE TITLE
Rxvt-unicode - Customizable terminal emulator

### ISSUE THREAD

**Issue by davidferlay** [clearlinux/distribution#1194]
Hi here, I would like to request the addition of [rxvt-unicode](https://wiki.archlinux.org/index.php/Rxvt-unicode) into CL swupd repository
- https://github.com/exg/rxvt-unicode

**Comment by ahkok** [comment]
`sudo swupd bundle-add  rxvt-unicode`

**Comment by treeshateorcs** [comment]
any reason rxvt-unicode is preferred over rxvt-unicode-256color?

**Comment by hnanni** [comment]
the distributed rxvt-unicode [is built with the 256-color option enabled](https://github.com/clearlinux-pkgs/rxvt-unicode/blob/bcac59218bd311e7861480435ece6302fb1f616e/rxvt-unicode.spec#L79)
