### ISSUE TITLE
git subtree command missing?

### ISSUE THREAD

**Issue by damageboy** [clearlinux/distribution#1199]
I can't seem to invoke `git subtree` in clearlinux, running latest of course.

moreover, running `locate subtree` brings up:
```
/usr/share/package-licenses/git/contrib_subtree_COPYING
```

But nothing else related to git.

Is this intentional?

**Comment by ahkok** [comment]
No. `git-subtree` lives in `/contrib/` and is therefore not installed by default. The `/contrib/` section of the git sources are labeled `not-so-stable` and so we will have skipped them on first import.

I'll enable this mod though. Will be in a release in 1-2 working days.

**Comment by damageboy** [comment]
Thanks a million!
