### ISSUE TITLE
Newly installed 20570 has poor graphics performance

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/distribution#12]
As continue of #9 i have tried to install version 20570 from scratch and i am still getting poor graphical performance, i have detailed information at #9 , [Antergos issue page](https://forum.antergos.com/topic/9008/intel-hd-graphics-is-slower-than-it-should-be?page=1) and [intel community page](https://communities.intel.com/message/522012#522012)

**Comment by ahkok** [comment]
This needs to be addressed in the relevant driver, kernel or mesa projects. Unfortunately, the clearlinux distribution can't be the owner of this issue. Please file issues in the relevant upstream projects instead.
