### ISSUE TITLE
Sans-serif fonts rendered incorrectly in FLTK applications

### ISSUE THREAD

**Issue by bwarden** [clearlinux/distribution#120]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

Sans-serif font selected by FLTK apps (e.g. fldigi, flmsg, flnet) is incorrectly rendered. Specifically, the characters are monospaced with large gaps between them. This is evident in the menu bar.

It seems to be an issue with rendering the Clear Sans font that is the default sans-serif font in Clear Linux.

This can be worked around by creating ~/.fonts.conf.d/20-unhint-clear-sans.conf:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
        <match target="font">
                <test name="family" compare="eq" ignore-blanks="true">
                        <string>Clear Sans</string>
                </test>
                <edit name="spacing">
                        <const>proportional</const>
                </edit>
        </match>

</fontconfig>
```

**Comment by iphutch** [comment]
@mrkz should we have a different default sans-serif font?

**Comment by bwarden** [comment]
WIP: https://github.com/clearlinux-pkgs/fontconfig/commit/3aa16d140158cf6b2bd7c57224a134f8ea0eb347

**Comment by AthenasJimenez** [comment]
@bwarden this is now fixed on release 24110. Please feel free to close this issue.

**Comment by bwarden** [comment]
Looks good, thanks!
