### ISSUE TITLE
remove duplicate bundles glibc-locale / locales

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#1200]
`locales` bundle was introduced to provide glibc-locales data back in [clr-bundles@8590a357](https://github.com/clearlinux/clr-bundles/commit/8590a357), but later on a `glibc-locale` bundle was introduced to optimize update packs for swupd in [clr-bundles@d3d0228a](https://github.com/clearlinux/clr-bundles/commit/d3d0228a), effectively both bundles provides the very same content:

```
$ cat clr-bundles/bundles/glibc-locale
# [TITLE]: glibc-locale
# [DESCRIPTION]: GNU/Linux locale files to support cultural conventions of a language and region.
# [STATUS]: Active
# [CAPABILITIES]:
# [TAGS]: Developer Tools
# [MAINTAINER]: William Douglas <william.douglas@intel.com>

# start of custom additions

# end of custom additions

# main package
glibc-locale
```

and `locales` bundle:
```
$ cat clr-bundles/bundles/locales
# [TITLE]: locales
# [DESCRIPTION]: Machine-readable data files, shared objects, and programs for localization and internationalization.
# [STATUS]: Active
# [CAPABILITIES]:
# [TAGS]: Developer Tools
# [MAINTAINER]: Mark Horn <mark.d.horn@intel.com>

include(glibc-locale)
```

In order to keep simplicity and avoid duplication, one of previous bundles should be deleted.

**Comment by bryteise** [comment]
I think these bundles could possibly diverge so I'm not sure if we should remove one. @mdhorn any thoughts on this? Is locales a hard coded bundle for clr-installer? We'd want to coordinate the switch over to glibc-locale at some point if that is the case.

**Comment by mdhorn** [comment]
@bryteise Yes, `locales` is included into the clr-install bundle and also hardcoded as a string in the code:
https://github.com/clearlinux/clr-installer/blob/d10becc59715302b654f70ecd43d957686d702e9/language/language.go#L34

We will need to update the clr-installer first.

**Comment by mdhorn** [comment]
Tracking in clr-installer
https://github.com/clearlinux/clr-installer/issues/506

**Comment by mdhorn** [comment]
clearlinux/clr-installer#506 is now complete and the clr-installer is only using `glibc-locale`.

Also just pushed a change to the clr-installer bundle definition:

```
Author: Mark D Horn <mark.d.horn@intel.com>
Date:   Mon Sep 16 14:34:24 2019 -0700

    clr-installer: change include to glibc-locale

    Replace the soon to be remove 'locales' bundle to the new
    'glibc-locale' bundle.

    Signed-off-by: Mark D Horn <mark.d.horn@intel.com>

diff --git a/bundles/clr-installer b/bundles/clr-installer
index fb6c1ff1f2b8..a49ef4db97ab 100644
--- a/bundles/clr-installer
+++ b/bundles/clr-installer
@@ -11,7 +11,7 @@ include(less)
 include(libstdcpp)
 include(linux-firmware-extras)
 include(linux-firmware-wifi)
-include(locales)
+include(glibc-locale)
 include(openssh-server)
 include(telemetrics)
 include(tzdata)
```

**Comment by bryteise** [comment]
Just pending a format bump now.
