### ISSUE TITLE
Not able to ping clearlinux.org while other sites are reachable via Ping

### ISSUE THREAD

**Issue by rmehta75in** [clearlinux/distribution#1202]
Hi,
This is the ClearLinux Version i am using clear-30890-hyperv.vhdx
Ping to Google, Yahoo is all working. 
Ping to CLearLinux is failing.
regds,
rakesh

**Comment by ahkok** [comment]
Not a bug. Ping is not supported. If you have to determine if the service is available, use a method that relies on e.g. `curl`.

**Comment by rmehta75in** [comment]
Even when I try to add a bundle the Curl communication remains very
erratic...see the error message below.

It works after 4 to 5 attempts
Regds
Rakesh

**Comment by ahkok** [comment]
I don't see any error messages. 

Can I ask why you need to determine if the service is available? All the `swupd` code handles connection issues properly.
