### ISSUE TITLE
PPPoEconf

### ISSUE THREAD

**Issue by Miku-nya** [clearlinux/distribution#1205]
Hello.
Please add the pppoeconf utility to add PPPoE connections. The built-in nm-connection-editor does not allow you to connect to the Internet through this connection (it does not create a ppp0 interface).

**Comment by sunnyflunk** [comment]
Possibly as an alternative, I see that pppoe is broken in `ppp` which NM uses. Adding this patch https://github.com/paulusmack/ppp/commit/50a2997b256e0e0ef7a46fae133f56f60fce539c.patch to `ppp` should allow the plugin (`/usr/lib/pppd/2.4.7/rp-pppoe.so`) to be built.

**Comment by Miku-nya** [comment]
sunnyflunk, this file (rp-pppoe.so) is not in this path. Please write down in more detail what and how to do it, I do not have much knowledge in this.

**Comment by sunnyflunk** [comment]
@Miku-nya, yes the file is missing and that is likely why `nm-connection-editor` doesn't currently work with PPPoE. I was describing the way to improve PPPoE support in Clear Linux by building and including the file in a future update. If it does indeed allow `nm-connection-editor` to work with PPPoE for you, then adding PPPoEconf may not be required (whether it's still wanted or not I have no opinion).

However, I did write it more to a support person than yourself, so I see how it was confusing. So hang tight till it's reviewed by the team.

**Comment by Miku-nya** [comment]
Thanks for the information. Then it remains to wait with the transition to this operating system until this one of the main functions is added

**Comment by Miku-nya** [comment]
@sunnyflunk Thanks for the information. Then it remains to wait with the transition to this operating system until this one of the main functions is added

**Comment by ahkok** [comment]
We can pull this patch - is that everything that is needed?

**Comment by sunnyflunk** [comment]
Everything that I know of! This was based off fixing basically the same issue in Solus (PPPoE connection failing in NM, then reported working after patch).

While I can't be sure there's no other issue, I'm fairly sure PPPoE wouldn't work without applying the patch to fix building the rp-pppoe plugin.

**Comment by ahkok** [comment]
Patch is in, I see the `rp-ppoe.so` is now built as well as `pppoe-discovery`. Please test once it is released (1-2 work days) and reopen this if there are issues.

**Comment by Miku-nya** [comment]
@ahkok Was it added to the 30980 build? If so, I can check in 2-3 days and report the results
