### ISSUE TITLE
Realtek RTL8812AU not recognized

### ISSUE THREAD

**Issue by fixerivan** [clearlinux/distribution#1206]
Hi, 

my usb wifi adapter 

(lsusb output): 

Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter

was not recognized, swupd bundle-add hardware-wifi didn't help 

please advise 

Thanks

**Comment by puneetse** [comment]
These drivers for that USB wifi adapter are not upstream part of the Linux kernel.
See this previous issue with advice on manually installing it: https://github.com/clearlinux/distribution/issues/869

**Comment by ahkok** [comment]
duplicate of #869
