### ISSUE TITLE
ClearLinux VM on KVM boots into UEFI shell

### ISSUE THREAD

**Issue by somequery** [clearlinux/distribution#1208]
Hi,

I followed the steps at [https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/kvm.html] to rum ClearLinux OS in KVM VM. In the step 4 the recommendation is to use original OVMF files to avoid booting into the shell. Despite that I did exactly what is recommended, I ended up booting into a shell in the step 6. All previous steps (except #4) finished successfully.

I was using the image file clear-30960-kvm.img

Can anybody advise me for the steps I need to fix this situation?
Thanks.

**Comment by miguelinux** [comment]
Are you using [start_qemu.sh](https://cdn.download.clearlinux.org/image/start_qemu.sh) script?
Are you using [OVMF.fd](https://cdn.download.clearlinux.org/image/OVMF.fd) or [OVMF_CODE.fd](https://cdn.download.clearlinux.org/image/OVMF_CODE.fd) and [OVMF_VARS.fd](https://cdn.download.clearlinux.org/image/OVMF_VARS.fd)?

**Comment by miguelinux** [comment]
One solution is when you already boot to OS erase the **NvVars** file at **ESP**.

**Comment by somequery** [comment]
> 
> 
> Are you using [start_qemu.sh](https://cdn.download.clearlinux.org/image/start_qemu.sh) script?
> Are you using [OVMF.fd](https://cdn.download.clearlinux.org/image/OVMF.fd) or [OVMF_CODE.fd](https://cdn.download.clearlinux.org/image/OVMF_CODE.fd) and [OVMF_VARS.fd](https://cdn.download.clearlinux.org/image/OVMF_VARS.fd)?

yes, I am using those files, and modified start_qemu.sh according instructions.

**Comment by nesiusra** [comment]
@puneetse - would you be willing to help reproduce this by following our docs as @somequery did?

**Comment by puneetse** [comment]
Sure. I should have some time in the next couple of days to check this out.

**Comment by puneetse** [comment]
So I tried this on a freshly installed host (30870) with 30960 kvm image, as you described in your setup, but wasn't able to reproduce.  Are you able to reproduce this even with fresh/never downloads?

The fact that you were able to get the VM working originally but it stopped working after following the steps to add graphics is good info. 

Can you share the qemu-system-x86_64 section of start-qemu.sh script after you modified? `tail -n 15 start_qemu.sh` should do the trick.

**Comment by somequery** [comment]
Thank you for answer. I'm on business trip till September 30, and don't have access  to the computer with CL. I'll do it after I return.

Thanks.

**Comment by somequery** [comment]
1. I haven't tried the newest downloads

2.Here is the qemu-system-x86_64 section:
qemu-system-x86_64 \
    -enable-kvm \
    ${UEFI_BIOS} \
    -smp sockets=1,cpus=4,cores=2 -cpu host \
    -m 4096 \
    -vga qxl -nographic \
    -spice port=5924,disable-ticketing \
    -usb \
    -device usb-tablet,bus=usb-bus.0
    -drive file="$IMAGE",if=virtio,aio=threads,format=raw \
    -netdev user,id=mynet0,hostfwd=tcp::${VMN}0022-:22,hostfwd=tcp::${VMN}2375-:2375 \
    -device virtio-net-pci,netdev=mynet0 \
    -device virtio-rng-pci \
    -debugcon file:debug.log -global isa-debugcon.iobase=0x402 $@

3. where can I locate debug.log?

Thanks.

**Comment by puneetse** [comment]
I edited your post to include the codeblock formatting so we can see the backslashes for line continuation.

This parameter in your command is missing a backslash at the end of it, which is probably causing the lines after it to not be passed as parameters properly:
`    -device usb-tablet,bus=usb-bus.0 \`

This probably matters less, but try splitting this into two lines instead of one:
```
    -vga qxl \
    -nographic \
```

debug.log is in the same sirctory you launch ` start_qemu.sh` from

**Comment by somequery** [comment]
I did the changes but still I am booting into the shell. The debug.log file was created (didn't exist before), but it is empty.

**Comment by somequery** [comment]
I deleted the *.fd files and downloaded them again, after the changes you recommended for *.sh file. It seems it helped as I started the VM and logged in. I don't have the graphical inerface yet, but at least I am in.

During the start there was an error message  after "starting Boot0002 "UEFI Misc Device":

> Failed to start QEMU Guest Agent

Next logs were OK.

**Comment by somequery** [comment]
I went through all instructions in https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/kvm.html. Successfully.

However, the KVM VM has no GUI running (if I connect remotely with remote-viewer, the windows will be showing the text "Connecting to graphic server" and nothing happens.

**Comment by puneetse** [comment]
I'm glad to hear you were able to get the VM up successfully. 

The kvm image by default does not have a desktop environment installed. You'll need to add the bundle `swupd bundle-add desktop-autostart`.

With the remote-viewer, try using `127.0.0.1` or `localhost` in place of the ip address.

**Comment by somequery** [comment]
I tried using 127.0.0.1 instead of IP address and it works just fine now. Thank you for help.

**Comment by puneetse** [comment]
@somequery thanks for the update!
