### ISSUE TITLE
Syslogging solution

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#121]
### What is the issue type?

* [ ] Bug report
* [x] Enhancement request

### Describe the problem
Offer a package/bundle for a centralized logging solution (rsyslog, syslog-ng, etc) of multiple clear linux hosts. This is a commonly used in datacenter environments. 

There are logging and shipping capabilities in systemd too :
https://github.com/systemd/systemd-netlogd 
https://github.com/systemd/systemd/tree/master/src/journal-remote

**Comment by iphutch** [comment]
We are planning to add this. Looking at rsyslog. We've tested the systemd remote logging but it's not quite there yet.

**Comment by ahkok** [comment]
rsyslog and journal can safely live side-by-side, so this would likely be an optional bundle you can just install. Shouldn't be too complex to add.

**Comment by ahkok** [comment]
journald-remote is currently semi-disabled in our systemd packaging.

**Comment by ahkok** [comment]
I'm enabling journald-remote functionality. For now, this is all we're currently will support.

**Comment by puneetse** [comment]
@ahkok awesome, thank you!

**Comment by ahkok** [comment]
`rsyslog` is now also a bundle.
