### ISSUE TITLE
texlive SRPM cannot be downloaded

### ISSUE THREAD

**Issue by pauleggleton** [clearlinux/distribution#1210]
If I attempt to download the texlive SRPM file, I get an error:

https://download.clearlinux.org/releases/30970/clear/source/SRPMS/texlive-20190410-25.src.rpm

The error is as follows (reference number changes on each request):

```
An error occurred while processing your request.

Reference #172.4d052017.1568168087.1020bdde
```

I tried the same for release 30980 and from cdn.download.clearlinux.org and got similar results in both cases. 

(In case you are wondering, I am using https://github.com/intel/clear-linux-dissector/ to download package sources, and this issue currently prevents the tool from fetching an entire Clear Linux release.)

**Comment by nesiusra** [comment]
@mdpitterle  - can you please look into this?

**Comment by mdpitterle** [comment]
@pauleggleton , @nesiusra - I think I know what is happening here, I should have this fixed fairly quickly if I am right.

**Comment by nesiusra** [comment]
Thanks, Matt!

**Comment by mdpitterle** [comment]
@pauleggleton - can you verify that you can download now?

**Comment by pauleggleton** [comment]
Yep, seems to be fixed. Thanks!
