### ISSUE TITLE
screen rotation does not work, need iio-sensor-proxy

### ISSUE THREAD

**Issue by chaoyi** [clearlinux/distribution#1211]
Screen rotation does not work under Clear Linux.  Rotation works out of box for Debian, Ubuntu etc.  After installing iio-sensor-proxy manually, it works as expected.

**Comment by adamhsparks** [comment]
Not just screen rotation, also auto screen brightness needs this as I understand it

**Comment by shtirlic** [comment]
+1 to this, Screen rotation does not work  on Dell XPS 7390 2 in 1

**Comment by bryteise** [comment]
I've added iio-sensor-proxy as a bundle and it should be in a release early next week.
