### ISSUE TITLE
Update Gnome 3.32 to Gnome 3.34

### ISSUE THREAD

**Issue by bkdwt** [clearlinux/distribution#1218]
The Gnome team has released the 3.34 version of Gnome today. This release promises many performance improvements among other things.

https://help.gnome.org/misc/release-notes/3.34/

**Comment by mrkz** [comment]
Hey folks, 

in Summary regarding the GNOME 3.34 update:

we updated GNOME but some stuff was breaking and we had to rollback:
 - [materia-theme/issues/430](https://github.com/nana-4/materia-theme/issues/430) Bad text on gnome-shell 3.34 for non-dark variants of the themes
 - [dash-to-dock extension broken for 3.34](https://github.com/micheleg/dash-to-dock/pull/975)
 - [broken scailing on 3rd party applications](https://gitlab.gnome.org/GNOME/mutter/issues/771)

among other minor issues we noticed as well.

All the issued have been addressed by now, but we continue ensuring that content meets the quality criteria for a proper release.

Expect the new version of GNOME to arrive soon-ish :rocket:

**Comment by ronaldfm** [comment]
Please support the N2600 processor and 3d acceleration on your graphics card, many people in Brazil, many people using this hardware, I understand a new mobo 5950 positive netbook this year, new that came with this hardware. i'm having problems with video card support.

**Comment by harpingon** [comment]
@mrkz did you re-test the GNOME Online Accounts bug with this release?

https://github.com/clearlinux/distribution/issues/599

**Comment by fenrus75** [comment]
the GOA thing is very likely a missing API key not a code bug

**Comment by mrkz** [comment]
GNOME 3.34 is available since CLR release **31110**

**Comment by bkdwt** [comment]
Any thanks @mrkz
