### ISSUE TITLE
Clearlinux user repository CUR??

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1221]
I installed chrome in my clear linux system with multiple line of code copied and paste from some blogger. finally got  chrome running.

Requesting for a clearlinux user repository (like AUR) handled with Cay (like yay for arch) :-)

It will be so much easy to handle all those code/terminal commands if already managed in a user repository.

**Comment by bryteise** [comment]
A user repository bug was much needed, thank you.

**Comment by nazar2sfive** [comment]
advantage of AUR in arch linux for me are(with help of yay or similar)
1. it can virtually allow me to install any software that is available on linux world for me to download and install with ease.
2. yay can check for new software, update my system, and many more. 
![image](https://user-images.githubusercontent.com/12841320/64902186-6e0f3280-d6c2-11e9-9c64-22e7339a1740.png)

![image](https://user-images.githubusercontent.com/12841320/64902188-749daa00-d6c2-11e9-947c-30bbaf48eca3.png)

![image](https://user-images.githubusercontent.com/12841320/64902189-79625e00-d6c2-11e9-9fe4-6ccc547de34d.png)


![image](https://user-images.githubusercontent.com/12841320/64902187-72d3e680-d6c2-11e9-8428-b5b439a56a4b.png)

**Comment by str225** [comment]
Since there's a history of malware in the AUR, wouldn't it be more secure to let users add centralized third-party repositories and let the community contribute on these repositories? Like RPMFusion for Fedora or packman for openSUSE.

**Comment by bryteise** [comment]
I think we probably would want to have some community feedback on the form it takes. Also 3rd-party repositories likely will have some limitations in comparison to other distributions (where packages from the 3rd-party repo can conflict with the base distribution, a feature we don't allow at even the base distribution in Clear). Currently the thought is to have the 3rd-party repositories handle applications (things that go in $PATH) to start but they wouldn't be allowed to shadow something already in the base distribution. We can see about possibly extending that to libraries but that gets a little more risky and it also isn't obvious you'd want this as plugins using dlopen need the path anyway.

**Comment by paulcarroty** [comment]
Automatic file conflicts checker will be an easiest solution.

Is this in CL team viable plans for next month or two, or just the beginning of theoretical stage?

'Cause I'm tired for compiling/hacking/tweaking, using another distros can provide the same software out the box or in one click.

**Comment by bryteise** [comment]
The 3rd-party content would be placed in its own namespace under /var (say /var/3rd-party/unique-repoid/) so it wouldn't be able to conflict with the base distro.

I don't have a timeline for something like a hosted user repository being available.

**Comment by nazar2sfive** [comment]
@bryteise 
any updates?

**Comment by bryteise** [comment]
Not before the end of the year.

**Comment by nazar2sfive** [comment]
@bryteise any progress?

**Comment by bryteise** [comment]
I'm doing some testing on our progress so far this week and last. There are some feature gaps so while I can tell you how to make it work (I have 3rd-party chrome running for instance) there are too many work-arounds required at this point.

There is still mixer and swupd-client changes that need to made which were scheduled for this quarter.

**Comment by nazar2sfive** [comment]
https://github.com/clearlinux/clr-user-bundles/blob/master/README.md

@bryteise any update?

**Comment by paulcarroty** [comment]
https://github.com/clearlinux/swupd-client/releases/tag/v3.24.0

**Comment by bryteise** [comment]
@nazar2sfive as @paulcarroty noted, the swupd-client has been released with support and https://github.com/clearlinux/mixer-tools/releases/tag/v6.2.0 is the corresponding change for mixer-tools. We are still working on more documentation for the feature though.

**Comment by bryteise** [comment]
So the [documentation ](https://docs.01.org/clearlinux/latest/guides/clear/swupd-3rd-party.html) is out and the latest release 32700 has all the corresponding components to make use of it. At this point we don't see the Clear Linux team hosting a user repository but with the 3rd-party implementation users are able to host their own repositories and subscribe to others repositories. With that I am closing this issue but I want to add we aren't done doing development on 3rd-party features.
