### ISSUE TITLE
Update materia-theme to version 20190912

### ISSUE THREAD

**Issue by curantes** [clearlinux/distribution#1232]
This theme is the default in Clear Linux Gnome desktop. This version adds support for GNOME Shell 3.34 which is nice since Gnome 3.34 is just around the corner.

https://github.com/nana-4/materia-theme/releases/tag/v20190912

**Comment by phmccarty** [comment]
This is a work-in-progress. Assigning to @mrkz.

**Comment by curantes** [comment]
Closing this since this package is at version: 20191017 in clearlinux
