### ISSUE TITLE
Add GFXbench as a bundle

### ISSUE THREAD

**Issue by zakiahmdismail** [clearlinux/distribution#1236]
This request is similar to https://github.com/clearlinux/distribution/issues/920. Instead of Vulkan, shall we have a bundle for GFXBench?

**Comment by bryteise** [comment]
This gfxbench https://gfxbench.com/ ? Seems like it isn't open source.

**Comment by puneetse** [comment]
I'm closing this becasue gfxbench does not appear to be opensource and Clear Linux cannot package it.
