### ISSUE TITLE
WebKit applications show overlapped or misaligned text with HTML content

### ISSUE THREAD

**Issue by jairglez** [clearlinux/distribution#124]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

Text in HTML content is displayed overlapped or misaligned in some WebKit applications. Two examples are the GNOME Help and Evolution applications. One exception is Firefox. Tested on Clear Linux 23730.

GNOME Help example:
![gnome help overlapped text](https://user-images.githubusercontent.com/23246311/42832126-df1446ec-89b5-11e8-9155-cd11bbab8b34.png)

**Comment by mrkz** [comment]
@josuedhg

**Comment by AthenasJimenez** [comment]
This issue has been fixed since release 24240. @jairglez would you mind to confirm this?

**Comment by mrkz** [comment]
I can confirm it works for me on version **24240** 

![gnome-help-screenshot](https://user-images.githubusercontent.com/978752/43734013-0b8a7ec8-997c-11e8-9297-a15c331ebaf8.png)

**Comment by AthenasJimenez** [comment]
Then I would assume it's fixed :)
