### ISSUE TITLE
cmus (C* Music Player)

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#1242]
cmus is a small, fast and powerful console music player for Unix-like operating systems.

cmus is my favorite music player and should be included in Clear Linux as a minimalist alternative to rhythmbox, gnome-music, etc.

Website: https://cmus.github.io/
GitHub: https://github.com/cmus/cmus

**Comment by ahkok** [comment]
Done. Will be available soon as `cmus` bundle.

Very nice indeed, might make me switch music players.
