### ISSUE TITLE
Wayland session not available after 31030 update

### ISSUE THREAD

**Issue by crispinb** [clearlinux/distribution#1243]
To repro:

* start with Clear Linux version 30970
* install wayland with `swupd bundle-add devpkg-wayland`
* wayland gnome session is now available in GDM menu
* upgrade to Clear Linux version 31030
* wayland gnome session is no longer available

Downgrading to 30970 with `swupd repair -V 30970 --picky` brings the wayland session option back.

**Comment by thiagomacieira** [comment]
Are we officially supporting Wayland sessions with GNOME now? Because it's not a bug if it wasn't supposed to exist in the first place.

**Comment by crispinb** [comment]
If Wayland isn't supported, then the gdm session option appearing & disappearing randomly is most certainly a bug.

**Comment by thiagomacieira** [comment]
That's a good point.

**Comment by crispinb** [comment]
This may be a false alarm anyway. Thinking that I might skip gdm and start gnome from a VT, I upgraded back to 31050. On reboot this time, the Wayland entry was there as usual. Good for me, but oddly non-deterministic. 

I'm not sure where that leaves this bug report. "Can't repro" I guess?

@thiagomacieira I do hope if I've inadvertently alerted you to a non-supported feature it's not going to be removed in future builds ;)

**Comment by thiagomacieira** [comment]
Not by me (KDE Plasma user here). We were having problems with GNOME on Wayland some time ago, so we had decided to turn it off by default and go back to X11. Since I don't pay attention to GNOME, I don't know whether the problems were solved.

**Comment by crispinb** [comment]
Well FWIW  I'm having no problems using Gnome on Wayland f/t. I prefer it to X11 because it works more elegantly with per-monitor scaling (no ugly xrandr hacks etc). Admittedly my setup is a low-bar test as it's rather simple - I don't use my discrete GPU & my usage is largely confined to browser, IDE & terminal.
