### ISSUE TITLE
Bundle request: OpenImageIO

### ISSUE THREAD

**Issue by gssgh** [clearlinux/distribution#1249]
Please consider adding OpenImageIO.

The primary target audience for OIIO is VFX studios and developers of tools such as renderers, compositors, viewers, and other image-related software you'd find in a production pipeline.

https://github.com/OpenImageIO/oiio

**Comment by fenrus75** [comment]
do you want the developer version of the package (headers etc) or is this just a request for the .so file ?

**Comment by seanvk** [comment]
It's a part of the blender build as packaged today if I recall when I did it.  Just not exposed as a developer-pkg and such...

**Comment by gssgh** [comment]
I need it to built a program that uses the library. So yes, I want the dev version.

**Comment by bryteise** [comment]
Change submitted, should be available in the next day or so.

**Comment by gssgh** [comment]
Thanks!
