### ISSUE TITLE
Feature request: pahole

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#125]
"pahole shows data structure layouts encoded in debugging information formats, DWARF and CTF being supported."

Good candidate for dev-utils bundle.

https://git.kernel.org/pub/scm/devel/pahole/pahole.git/

**Comment by ahkok** [comment]
definitely, I've used this many times in the past.

**Comment by cmarcelo** [comment]
This was added as part of dev-utils bundle. Thanks!
