### ISSUE TITLE
IDLE and Plotly.py

### ISSUE THREAD

**Issue by PlatonB** [clearlinux/distribution#1254]
Please add [IDLE](https://docs.python.org/3/library/idle.html) to `python-extras` bundle and [Plotly.py](https://plot.ly/python/) to `python-data-science`.

**Comment by bryteise** [comment]
python-extras looks like it already has idle in it to me (/usr/bin/idle3).

**Comment by PlatonB** [comment]
I don't see IDLE in the Nautilus context menu, Activities or Software.

**Comment by bryteise** [comment]
The idle menu entry should be available now in gnome3 now.

**Comment by bryteise** [comment]
And plotly should be in the next day or so.
