### ISSUE TITLE
Samtools

### ISSUE THREAD

**Issue by PlatonB** [clearlinux/distribution#1255]
[Samtools](http://www.htslib.org/) is a very popular, but difficult to install, bioinformatics toolkit. It would be more convenient to get it as bundle.

**Comment by ahkok** [comment]
Adding. Available after the weekend.

**Comment by ahkok** [comment]
`samtools` bundle.

**Comment by PlatonB** [comment]
Please, add [BCFtools](http://www.htslib.org/) to this bundle.
