### ISSUE TITLE
[java] test jdk8u.git/jdk/test/sun/security/rsa/TestCACerts.java failed on java-basic

### ISSUE THREAD

**Issue by vivanov-gh** [clearlinux/distribution#1257]
The test jdk8u.git/jdk/test/sun/security/rsa/TestCACerts.java failed for java-basic package on Clear Linux r 31050 with output:
======================
----------System.out:(10/400)----------
* Testing verisignclass2publicprimarycertificationauthority-g3...
Signature algorithm: SHA1withRSA
* Testing intelsha256rootca...
Signature algorithm: SHA256withRSA
* Testing hellenicacademicandresearchinstitutionsrootca2011...
Signature algorithm: SHA1withRSA
* Testing teliasonerarootcav1...
Signature algorithm: SHA1withRSA
* Testing intelexternalissuingca6b...
Signature algorithm: SHA384withRSA
----------System.err:(13/709)----------
java.security.SignatureException: Signature does not match.
        at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:449)
        at TestCACerts.main(TestCACerts.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:246)
        at java.lang.Thread.run(Thread.java:748)
======================

Most probably, this issue have same root cause as https://github.com/clearlinux/distribution/issues/1156.

To reproduce issue:
1. checkout openjdk ws:
hg clone https://hg.openjdk.java.net/jdk8u/jdk8u/
and get sources as "cd jdk8u; get_source.sh"
2. checkout latest build for the jtreg harness
https://ci.adoptopenjdk.net/view/Dependencies/job/jtreg
3. set java8 as default java in system, JT_HOME and PATH variables
4. run tests as
jtreg jdk/test/sun/security/rsa/TestCACerts.java

**Comment by vivanov-gh** [comment]
The test jdk8u.git/jdk/test/sun/security/pkcs11/rsa/TestCACerts.java failed with same out message.

**Comment by AthenasJimenez** [comment]
Same answer for issue #1156, CLR makes use of a central TLS trust store to manage the certificates, so tests won't find the bundled certificates. More info [here](https://github.com/clearlinux/clrtrust).

Closing since test doesn't apply.
