### ISSUE TITLE
Gnome crashes after following tutorial for installing NVIDIA proprietary drivers

### ISSUE THREAD

**Issue by npafitis** [clearlinux/distribution#1259]
My System:
Dell XPS 15  9570 (2018)
```bash
H/W path       Device   Class          Description
==================================================
                        system         XPS 15 9570 (087C)
/0                      bus            0D0T05
/0/0                    memory         64KiB BIOS
/0/3e                   memory         8GiB System Memory
/0/3e/0                 memory         4GiB SODIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/3e/1                 memory         4GiB SODIMM DDR4 Synchronous 2667 MHz (0.4 ns)
/0/47                   memory         384KiB L1 cache
/0/48                   memory         1536KiB L2 cache
/0/49                   memory         9MiB L3 cache
/0/4a                   processor      Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
/0/100                  bridge         8th Gen Core Processor Host Bridge/DRAM Registers
/0/100/1                bridge         Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16)
/0/100/1/0              display        GP107M [GeForce GTX 1050 Ti Mobile]
/0/100/2                display        UHD Graphics 630 (Mobile)
/0/100/4                generic        Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
/0/100/8                generic        Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixt
/0/100/12               generic        Cannon Lake PCH Thermal Controller
/0/100/14               bus            Cannon Lake PCH USB 3.1 xHCI Host Controller
/0/100/14/0    usb1     bus            xHCI Host Controller
/0/100/14/0/4           communication  Bluetooth wireless interface
/0/100/14/0/7           communication  Goodix Fingerprint Device
/0/100/14/0/c           multimedia     Integrated_Webcam_HD
/0/100/14/1    usb2     bus            xHCI Host Controller
/0/100/14.2             memory         RAM memory
/0/100/15               bus            Cannon Lake PCH Serial IO I2C Controller #0
/0/100/15.1             bus            Cannon Lake PCH Serial IO I2C Controller #1
/0/100/16               communication  Cannon Lake PCH HECI Controller
/0/100/17               storage        Cannon Lake Mobile PCH SATA AHCI Controller
/0/100/1b               bridge         Cannon Lake PCH PCI Express Root Port #17
/0/100/1c               bridge         Cannon Lake PCH PCI Express Root Port #1
/0/100/1c/0    wlp59s0  network        QCA6174 802.11ac Wireless Network Adapter
/0/100/1c.4             bridge         Cannon Lake PCH PCI Express Root Port #5
/0/100/1c.4/0           generic        RTS525A PCI Express Card Reader
/0/100/1d               bridge         Cannon Lake PCH PCI Express Root Port #9
/0/100/1d/0             storage        SK hynix
/0/100/1f               bridge         Intel Corporation
/0/100/1f.3             multimedia     Cannon Lake PCH cAVS
/0/100/1f.4             bus            Cannon Lake PCH SMBus Controller
/0/100/1f.5             bus            Cannon Lake PCH SPI Controller
/1                      power          DELL CP6DF88
```

I tried multiple (3+) times to install NVIDIA proprietary drivers since nouveu and nvidiafb seem to not work for me, following the guide that can be found here https://docs.01.org/clearlinux/latest/tutorials/nvidia.html.

But after rebooting i get a white screen and the error "Oh no something has went wrong. A problem has occurred and the system can't recover. Please log out and try again.". From my understanding this is a Gnome error. I tried installing a different driver but to no result.

**Comment by amygilliam1** [comment]
@puneetse , can you please repro using our docs?

**Comment by puneetse** [comment]
hey @npafitis, it looks like your system has dual graphics (Intel + NVIDIA) that can be independently switched and offloaded between, known as NVIDIA Optimus technology. 

Optimus adds an additional layer of complexity to get working on Linux, sometimes even platform specific, and is not covered by the documentation. For example, I see some notes specifically for your laptop regarding Optmius (linked below). 

Unfortunately, you'll likely have to spend time learning about the options and tools folks out there have created for Optimus on Linux if you haven't already. Each of them has different pros/cons and need to be compiled manually on Clear Linux. The good news is that a couple members on the [forums ](https://community.clearlinux.org) have had success in getting Optimus working on Clear Linux with some trial and error. 

Here are some links that I hope are helpful:
https://wiki.archlinux.org/index.php/NVIDIA_Optimus
https://wiki.archlinux.org/index.php/Dell_XPS_15_9570#NVIDIA_Optimus
https://community.clearlinux.org/search?q=optimus
https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-435.17-Linux-Driver (native improvements on the horizon for PRIME offloading)

**Comment by 0xA1B2** [comment]
Related

https://github.com/clearlinux/distribution/issues/1276
