### ISSUE TITLE
Update LLVM to version 9.0.0

### ISSUE THREAD

**Issue by rumela** [clearlinux/distribution#1260]
LLVM on Clear Linux is still on version 8.0.0, notwithstanding that version 8.0.1 was released on 19 July 2019. The most up to date release is now version 9.0.0, released on 19 September 2019.

**Comment by thiagomacieira** [comment]
Thanks. I'd checked two days before that (17-Sept) and rc6 had just been released. We'll update, but LLVM may take upwards of a week to get through, with dependencies and everything else that needs to be rebuilt.

**Comment by thiagomacieira** [comment]
Local build done. We'll post some patches for review and we should be good to go in about a day.

**Comment by chaoyi** [comment]
Nice.  Can you consider enabling clang-tools-extra for clangd & clang-tidy?

**Comment by thiagomacieira** [comment]
I'll take a look.

**Comment by thiagomacieira** [comment]
Done.
