### ISSUE TITLE
Updating scdoc

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#1261]
The package `scdoc` in the `dev-utils` bundle is version 1.9.4, released on 2019-03-04. The [most recent](https://git.sr.ht/~sircmpwn/scdoc) one is 1.10.0, released on 2019-09-11.

Can you consider updating this package?

**Comment by bryteise** [comment]
Thanks for the notification, the detection we were using was breaking on that package. @phmccarty

**Comment by bryteise** [comment]
Update should be available in the next day or so.
