### ISSUE TITLE
DPDK: add devpkg-dpdk

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1266]
Clear Linux documentation [Use DPDK to send packets between platforms](https://docs.01.org/clearlinux/latest/guides/network/dpdk.html) does not work today.

OTOH, it's not obvious whether the doc is outdated/incomplete or the distro packaging has changed. Based on a quick look both needs changing. This bug is about adding devpkg-dpdk bundle to be able to install the necessary build dependencies and to satisfy "install dpdk".

/cc @poussa

**Comment by ahkok** [comment]
> OTOH, it's not obvious whether the doc is outdated/incomplete or the distro packaging has changed. Based on a quick look both needs changing. This bug is about adding devpkg-dpdk bundle to be able to install the necessary build dependencies and to satisfy "install dpdk".

Looks like `dpdk` doesn't install a `.pc` file, so, this would have to 
be a manual devpkg. Maybe we can get upstream to generate a pkg-config 
file as part of the standard installation?

**Comment by bryteise** [comment]
Bundles patched.
