### ISSUE TITLE
 Cannot start live desktop environment from USB: failed to execute /init (error -2)

### ISSUE THREAD

**Issue by msmart** [clearlinux/distribution#1268]
I see the following console error:

![image](https://user-images.githubusercontent.com/85249/65533429-de595780-defd-11e9-98f3-7d6781c4e0f8.png)

when I try to boot from an usb key with `clear-31080-live-desktop.iso` on a Lenovo T480s. The log above was generated without the `quiet` and `console**` option as advised in https://github.com/clearlinux/distribution/issues/726

Let me know if I can provide any additional information.

**Comment by mdhorn** [comment]
Any chance of getting a video for the full boot?
Those that have reviewed the screenshot want to see what happened up to that point.

Could you also verify the checksum on the ISO you download and that it wrote to the USB driver okay?

**Comment by msmart** [comment]
Thanks for the quick response! I went through all the steps again and now the OS boots up correctly. As the checksums of the .xz archive were ok, I suspect that the USB key may not have been properly unmounted the first time. 

In any case, I would like to close this issue. Sorry for the noise. Btw, the first impression is great!
