### ISSUE TITLE
Add liblttng-* to some bundle

### ISSUE THREAD

**Issue by jakob-engblom-i** [clearlinux/distribution#1269]
Trying to run some software that required "liblttng-ust".  Seems no liblttng variant is covered any existing Clear Linux bundle.  Therefore, it would make sense to have liblttng, liblttng-ust, and more in some CL bundle.  Other Linux distros like Ubuntu do make these available for installation using their package managers.

**Comment by ahkok** [comment]
I'll add an `lttng` bundle in the next few days. It will contain `lttng-ust` and `lttng-tools`. However, note that `lttng-modules` will not be part of it. And, you may have to compile the kernel modules needed to make some of this work yourself.

I assume at some point that that is needed as well, so @miguelinux may need to look at whether we can integrate these modules into one or more of our relevant kernels. Note: in general, tracing and debugging features aren't enabled by default if they pose a significant security risk, so, it may very well be that we won't package them. I'm writing this to make sure your expectations are more realistic here - this is likely something that may not just work "OOTB".

**Comment by jakob-engblom-i** [comment]
Thanks! Not entirely sure how hard that would be to use. For Ubuntu that I ended up using instead to solve the immediate problem, I could just install the libs with apt install which is handy.  No build needed.

**Comment by ahkok** [comment]
They may have the kernel modules prebuilt already, or, you may not even need them. I honestly don't know at this point since I've never used lttng myself.

**Comment by ahkok** [comment]
Pushed. The bundle will appear in 1-2 working days. If any issue arises with it's use, please open a separate issue.
