### ISSUE TITLE
Static ip

### ISSUE THREAD

**Issue by nomo-w** [clearlinux/distribution#1275]
Hi
I have a question.
How to set static IP for clr?

I used the "nmcli" command, but it doesn't work.

**Comment by puneetse** [comment]
This guide should help:

https://docs.01.org/clearlinux/latest/guides/network/assign-static-ip.html

**Comment by ketonik** [comment]
Hi, having issue unable to define Static IP with the above documentation.

clear-33180-live-server.iso

`$ nmcli device status`
`DEVICE   TYPE      STATE         CONNECTION`         
`enp9s0   ethernet  connected     Wired connection 1` 

`$ networkctl list`
`IDX LINK    TYPE     OPERATIONAL SETUP`      
  `1 lo      loopback carrier     unmanaged`
  `2 enp9s0  ether    routable    configured` 

`nmtui`

![Screen Shot 2020-05-22 at 22 46 09](https://user-images.githubusercontent.com/49221849/82680418-d1ecf080-9c7e-11ea-95e5-2e96aa55820c.png)

![Screen Shot 2020-05-22 at 22 46 16](https://user-images.githubusercontent.com/49221849/82680454-dca78580-9c7e-11ea-996d-b3bedc387f5c.png)


`sudo nmcli connection modify “Wired connection 1” \`
`ipv4.method manual \`
`ipv4.addresses 192.168.1.100/24 \`
`ipv4.gateway 192.168.1.1 \`
`ipv4.dns 192.168.1.1,1.1.1.1`

Error: unknown connection '“Wired'.

Change Wired connection to device `enp9s0`

Error: unknown connection 'enp9s0'.

`sudo $EDITOR /etc/systemd/network/70-static.network`
add:

[Match]
Name=[enp9s0]

[Network]
Address=[192.168.1.100]/[24]
Gateway=[192.168.1.1]
DNS=[192.168.1.1]
DNS=[1.1.1.1]

`networkctl status` returns

`●   State: routable     `                    
  Address: 192.168.1.7 on enp9s0`        
           `fe80::d46f:127b:d61:44f on enp9s0`
 `Gateway: 192.168.1.1 on enp9s0`            
      `DNS: 192.168.1.1`

No change, still using DHCP dynamic address.
