### ISSUE TITLE
Tor Browser - command not found

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1278]
When I try to start the Tor Browser, this comes up:

root@t520/usr/share/tor-browser_en-US # sudo ./start-tor-browser.desktop
Launching './Browser/start-tor-browser --detach'...
./Browser/start-tor-browser: line 37: [: : integer expression expected
./Browser/start-tor-browser: line 54: zenity: command not found
./Browser/start-tor-browser: line 62: kdialog: command not found
./Browser/start-tor-browser: line 69: xmessage: command not found
./Browser/start-tor-browser: line 84: gxmessage: command not found

I located zenity and kdialog in these bundles:

os-utils-gui-dev
desktop-kde-apps

however xmessage and gxmessage I don't know where to get those from ..

Is there any easier way to install the Tor Browser on CL ?

**Comment by ahkok** [comment]
Several big issues with your report:

- clearlinux does not provide a tor browser. You should consider reporting bugs to the software provider. The clearlinux team likely can't fix script issues in this launcher. The tor team can.

- Don't run sensitive software that you downloaded from the internet as `root`. It's terrible for security.

- You're already root. Why are you still using `sudo`?

Poking around, you should just be able to run

`./Browser/start-tor-browser`

which works for me. You only need the `games` bundle, but not any of the others. Once you have `zenity`, the script should not complain about missing `kdialog` or the others.
