### ISSUE TITLE
Docker: bind-mounts broken for CSI in Kubernetes

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#128]
### What is the issue type?

* [X ] Bug report
* [ ] Enhancement request

### Describe the problem

I'm running Kubernetes on Clear Linux. Deploying a CSI container needs to bind-mount /var/lib/kubelet/pods, and that fails with:

    linux mounts: Could not find source mount of /var/lib/kubelet/pods"

This is a known regression in Docker 18.05.0-ce: https://github.com/moby/moby/issues/37032

There is a fix upstream: https://github.com/moby/moby/pull/37031

Can you backport that to the Clear Linux package until the next Docker release comes with the fix?

**Comment by bryteise** [comment]
Thanks for the details, patch applied and the updated docker should be in tomorrow's release.
