### ISSUE TITLE
Request to update libvirt

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#1280]
Hello,

This is a request to bump libvirt to the latest version, `5.8.0`. It appears that right now the latest version we have is [`4.10.0`](https://github.com/clearlinux-pkgs/libvirt/blob/8e64e9b68c5c46d828ca87e2acaa11786afba769/libvirt-4.10.0.tar.xz.asc).

**Comment by bryteise** [comment]
Update completed.

**Comment by bswinnerton** [comment]
Thank you!
