### ISSUE TITLE
Slow boot/shutdown

### ISSUE THREAD

**Issue by cyberpika2** [clearlinux/distribution#1281]
Slow boot / shutdown time and frozen screen while shutting down 30 - 240 secs.

HARDWARE:
XPS 15 9560
DESKTOP(asrock Z370, i7-7700K, samsung 970 pro, samsung 860 evo, nvidia 1070)

STEPS:
Fresh install. 
Reboot.
Reboot again.

Same issues as bug# 898, and I would like to explore this if possible.
Slow boot/shutdown times and frozen screen while it waits.
- 8 installs, 4 different builds, 2 different sets of hardware, same bug.
- Current is the xps 15, a new install from 31090, updated to 31111.
- Only tweaks since were a blacklist of mic and cam.
- Bug was present from first boot. Settings/Power tray delay was present even during installation media. Installation media was hash checked.
- Issues may all be related, which is why I am listing.

1. Power options / settings delay - 15 sec then a pop-up says settings is ready as if it just installed, every time, and then it renders the control panel.
- Issue also present on bootable media during installation

'$ gnome-control-center -v

`nvc0_screen_create:1107 - Error allocating PGRAPH context for M2MF: -16
16:49:34.0052         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Power,/org/gnome/SettingsDaemon/Power,org.gnome.SettingsDaemon.Power.Screen)
16:49:34.0053         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Power,/org/gnome/SettingsDaemon/Power,org.gnome.SettingsDaemon.Power.Screen) → 0x7fd098001870) to the storage
16:49:34.0053            power-cc-panel:    DEBUG: ALS enabled: on
16:49:34.0053         cc-object-storage:    DEBUG: Finished creating D-Bus proxy for CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Power,/org/gnome/SettingsDaemon/Power,org.gnome.SettingsDaemon.Power.Keyboard)
16:49:34.0053         cc-object-storage:    DEBUG: Adding object GDBusProxy (CcObjectStorage::dbus-proxy(org.gnome.SettingsDaemon.Power,/org/gnome/SettingsDaemon/Power,org.gnome.SettingsDaemon.Power.Keyboard) → 0x7fd098001ea0) to the storage
16:49:34.0054            power-cc-panel:    DEBUG: ALS enabled: on`

2. Long startup/shutdown times. 30-60 seconds. Screen freezes during shutdown.
- Boot delayed approx 8 seconds according to systemd-analyze by clr_power.service

`$ clr-power.service -d

10.033s clr-power.service                                  
 1.085s systemd-logind.service                             
  655ms systemd-resolved.service                           
  499ms systemd-backlight@leds:dell::kbd_backlight.service 
  374ms dev-nvme0n1p7.device                               
  278ms upower.service                                     
  218ms systemd-udevd.service                              
  190ms systemd-journald.service                           
  103ms NetworkManager.service                             
   98ms udisks2.service                                    
   76ms systemd-udev-trigger.service                       
   57ms rtkit-daemon.service                               
   57ms polkit.service                                     
   47ms user@1000.service                                  
   29ms networkd-fallback.service                          
   28ms systemd-tmpfiles-setup.service                     
   27ms ModemManager.service                               
   18ms colord.service                                     
   18ms irqbalance.service                                 
   16ms systemd-journal-flush.service                      
   15ms gdm.service                                        
   13ms thermald.service                                   
   12ms accounts-daemon.service                            
   10ms systemd-update-utmp.service                        
    9ms bluetooth.service                                  
    9ms systemd-rfkill.service                             
    8ms systemd-random-seed.service                        
    8ms wpa_supplicant.service                             
    6ms dev-nvme0n1p6.swap                                 
    5ms user-runtime-dir@1000.service                      
    5ms systemd-backlight@backlight:intel_backlight.service
    4ms kmod-static-nodes.service                          
    4ms systemd-sysctl.service                             
    3ms systemd-boot-system-token.service                  
    3ms systemd-remount-fs.service                         
    3ms systemd-user-sessions.service                      
    2ms tmp.mount`

Any help is appreciated.

**Comment by ahkok** [comment]
`clr-power` is run as a post-`OnStartupSec` timer. It does not get accounted for in delaying bootup. It just runs after the system is done booting.

**Comment by ahkok** [comment]
It's confusing to have 1 issue for 2 problems. I'd prefer a separate issue for slow shutdown. Is bootup 240s? Is shutdown 30s? your report is ambiguous. The `systemd-analyze` output suggests bootup is a few seconds, not 30. What does `systemd-analyze` without options say?

**Comment by fenrus75** [comment]
also we always have a full bootchart in  /run/log/    should show if
something i stalling

**Comment by cyberpika2** [comment]
So bootup, from the time it leaves grub is between 120-240 seconds.
Even though it shows it is just a few seconds.
Maybe a issue in gnome?

**Comment by cyberpika2** [comment]
So bootup, from the time it leaves grub is between 120-240 seconds.
Even though it shows it is just a few seconds.
Maybe a issue in gnome?


[bootchart-20191002-1904.txt](https://github.com/clearlinux/distribution/files/3683780/bootchart-20191002-1904.txt)

**Comment by ahkok** [comment]
What is `systemd-analyze` output?

**Comment by cyberpika2** [comment]
My efi bootloader seems to have died during an update.
Dual booting on uefi is a pain. But I think I finally have a solution for it.
I will close this and do another ticket if it is still an issue after the next install.
Thank you for your time!
