### ISSUE TITLE
hosts file permissions

### ISSUE THREAD

**Issue by cyberpika2** [clearlinux/distribution#1282]
HARDWARE:
xps 15 9670

REPRO:
Install

Fresh install file permissions on /usr/share/defaults/etc/hosts is:
`$ ls -al /usr/share/defaults/etc/hosts

-rwxr-xr-x  1 root root    19 Feb  1  2019 hosts
`

Just wondering if there is a reason it is executable.
I'm probably just ig.

**Comment by ahkok** [comment]
@fenrus75 added this a long time ago, I think it was just a copypasta?

**Comment by ahkok** [comment]
`filesystem-3.0.14-192`
