### ISSUE TITLE
CUPS

### ISSUE THREAD

**Issue by Nirgendsdorf** [clearlinux/distribution#1283]
CUPS 2.3.0 has recently been released. I wonder if it might be easier to install a working printer on it than on the version we currently have...

https://apple.github.io/cups/

**Comment by ahkok** [comment]
Not a trivial update. Several issues arose when I tried to update it.

**Comment by Nirgendsdorf** [comment]
Sorry to hear that. Given my recent experiences, though, I'm not surprised. Seems that printer setup in Linux is generally non-trivial.

**Comment by ahkok** [comment]
done
