### ISSUE TITLE
poppler required for printing PDF

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#1285]
Poppler is required for printing PDFs (at least when printing from evince).

I suggest this be included in the hardware-printing bundle.

**Comment by ahkok** [comment]
That seems very unattractive. `poppler` pulls in a huge array of dependencies, like `Qt5`.

Is this needed for `evince` or for an actual standalone `cupsd` server?

**Comment by fenrus75** [comment]
if nothing else we should add this to evince then, not hardware-printing?

**Comment by pceiley** [comment]
Probably, though I haven't tested if this is required by other apps yet (I suspect it might be)

**Comment by ahkok** [comment]
I see `pdf2ps` is likely the used thing here. I hadn't heard of `cups` directly executing it. Maybe we can split it out.

**Comment by thiagomacieira** [comment]
The qt5 dependency is in the poppler-extras package.

**Comment by ahkok** [comment]
`cups-2.3.0-45` will pull in `poppler-bin` which has `pdf2ps` which is what cups wants to call.
