### ISSUE TITLE
php-extras php-imagick unable to load undefined symbol: FT_Done_MM_Var)

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1286]
Trying to load the "imagick" extension in PHP.

`php -i`  reports:

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so 
(/usr/lib64/haswell/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var), 
/usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so 
(/usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

phpinfo()
PHP Version => 7.3.9

My PHP ini file:

`/etc/php.d/php.ini`

```
[zendopcache]
extension = apcu.so
extension = redis.so
extension = imagick.so
opcache.memory_consumption=256
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=180
opcache.fast_shutdown=1
opcache.enable_cli=0
opcache.enable=0
opcache.huge_code_pages=1
max_execution_time = 300
max_input_time = 1000
upload_max_filesize = 150M
post_max_size = 150M
```

**Comment by fenrus75** [comment]
curious, it works on my system with a pretty full install, so this looks
like some missing dependency. going to try next on a much more minimal
system

**Comment by ahkok** [comment]
Same here. We actually have a test that loads these and makes sure that `php` works.

```
imagick

imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
Imagick compiled with ImageMagick version => ImageMagick 7.0.8-65 Q16 x86_64 2019-09-18 https://imagemagick.org
Imagick using ImageMagick library version => ImageMagick 7.0.8-66 Q16 x86_64 2019-09-23 https://imagemagick.org
ImageMagick copyright => © 1999-2019 ImageMagick Studio LLC
ImageMagick release date => 2019-09-23
ImageMagick number of supported formats:  => 241
ImageMagick supported formats => 3FR, 3G2, 3GP, A, AAI, AI, ART, ARW, AVI, AVS, B, BGR, BGRA, BGRO, BMP, BMP2, BMP3, BRF, C, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUBE, CUR, CUT, DATA, DCM, DCR, DCRAW, DCX, DDS, DFONT, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FLV, FRACTAL, FTP, FTS, G, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K, K25, KDC, LABEL, M, M2V, M4V, MAC, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, O, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PS, PS2, PS3, PSB, PSD, PTIF, PWP, R, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGB565, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCREENSHOT, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TM2, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, Y, YCbCr, YCbCrA, YUV
```

**Comment by ahkok** [comment]
Can you `swupd diagnose`? What Clear Linux version do you have?

**Comment by ketonik** [comment]
> Can you `swupd diagnose`? What Clear Linux version do you have?

# swupd diagnose
Diagnosing version 31110

Checking for missing files
	...100%

Checking for corrupt files
 -> Hash mismatch for file: /usr/bin/nologin
 -> Hash mismatch for file: /usr/lib64/mysql/plugin/auth_pam_tool_dir
 -> Hash mismatch for file: /usr/share/defaults/php/php-fpm.conf
 -> Hash mismatch for file: /usr/share/defaults/php/php-fpm.d/www.conf
 -> Hash mismatch for file: /usr/share/defaults/php/php.ini
 -> Hash mismatch for file: /usr/share/doc/openssh/sshd_config
	...100%

Checking for extraneous files
	...100%

Inspected 151944 files
  6 files did not match

Use "swupd repair" to correct the problems in the system

Diagnose successful

**Comment by ahkok** [comment]
`FT_` is probably freetype.... do you have `libfreetype.so.6` in `ldconfig -p` ?

**Comment by ketonik** [comment]
> `FT_` is probably freetype.... do you have `libfreetype.so.6` in `ldconfig -p` ?

libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
libfreetype.so.6 (libc6,x86-64) => /usr/lib64/libfreetype.so.6

**Comment by ahkok** [comment]
How bizarre. Everything looks fine from what I can see, but it's obviously not on your end.

**Comment by ahkok** [comment]
Do the other DSO's load properly? e.g. run:

`sudo grep extension /proc/`pgrep php-fpm`/maps`

Assuming you're using `php-fpm`.

**Comment by ahkok** [comment]
Since we can't figure out a root cause, can you backup the modifications you made to these files and let `swupd repair` restore them?

```
-> Hash mismatch for file: /usr/share/defaults/php/php-fpm.conf
-> Hash mismatch for file: /usr/share/defaults/php/php-fpm.d/www.conf
-> Hash mismatch for file: /usr/share/defaults/php/php.ini
```

**Comment by ketonik** [comment]
> > `FT_` is probably freetype.... do you have `libfreetype.so.6` in `ldconfig -p` ?
> 
> libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
> libfreetype.so.6 (libc6,x86-64) => /usr/lib64/libfreetype.so.6

I also actually have freetype in:
`/usr/local/lib/`

![Screen Shot 2019-09-30 at 02 33 28](https://user-images.githubusercontent.com/49221849/65837563-6f2f9900-e32b-11e9-961b-35f36e27d160.png)

This was added when I had an issue with freetype not being linked to GD in php.
That was fixed by Auk so I imagine this freetype in this location is redundant now.

**Comment by ketonik** [comment]
> Since we can't figure out a root cause, can you backup the modifications you made to these files and let `swupd repair` restore them?
> 
> ```
> -> Hash mismatch for file: /usr/share/defaults/php/php-fpm.conf
> -> Hash mismatch for file: /usr/share/defaults/php/php-fpm.d/www.conf
> -> Hash mismatch for file: /usr/share/defaults/php/php.ini
> ```

Actually ran this without backing up the files moments before you posted.
On this exactly what can cause this hash mismatch? Me opening these in my SFTP client in BBEdit on macOS?

**Comment by ketonik** [comment]
> Do the other DSO's load properly? e.g. run:
> 
> `sudo grep extension /proc/`pgrep php-fpm`/maps`
> 
> Assuming you're using `php-fpm`.

Yes using php-fpm.

Unable to determine correct use of the command posted or is that two command? Do i need be in a specific directory?

**Comment by ahkok** [comment]
> On this exactly what can cause this hash mismatch? Me opening these in my SFTP client in BBEdit on macOS?

Sure, that would likely do it already.

**Comment by ahkok** [comment]
> I also actually have freetype in: `/usr/local/lib/`

Those are likely to conflict. I'd recommend (backing them up first) deleting them, and re-running `sudo ldconfig`. Then try again :)

**Comment by ahkok** [comment]
> Unable to determine correct use of the command posted or is that two command? Do i need be in a specific directory?

Sorry, formatting went wrong. Copy+paste this:
```
sudo grep extension /proc/`pgrep php-fpm`/maps
```

**Comment by ketonik** [comment]
# grep extension /proc/`pgrep php-fpm`/maps
```
7fc6a728c000-7fc6a72a8000 r--p 00000000 08:03 26918996                   /usr/lib64/extensions/no-debug-non-zts-20180731/redis.so
7fc6a72a8000-7fc6a72fd000 r-xp 0001c000 08:03 26918996                   /usr/lib64/extensions/no-debug-non-zts-20180731/redis.so
7fc6a72fd000-7fc6a730f000 r--p 00071000 08:03 26918996                   /usr/lib64/extensions/no-debug-non-zts-20180731/redis.so
7fc6a730f000-7fc6a7316000 r--p 00082000 08:03 26918996                   /usr/lib64/extensions/no-debug-non-zts-20180731/redis.so
7fc6a7316000-7fc6a731a000 rw-p 00089000 08:03 26918996                   /usr/lib64/extensions/no-debug-non-zts-20180731/redis.so
7fc6a786a000-7fc6a7878000 r--p 00000000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6a7878000-7fc6a78ec000 r-xp 0000e000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6a78ec000-7fc6a78fe000 r--p 00082000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6a78fe000-7fc6a78ff000 ---p 00094000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6a78ff000-7fc6a7908000 r--p 00094000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6a7908000-7fc6a7909000 rw-p 0009d000 08:03 26941508                   /usr/lib64/extensions/no-debug-non-zts-20180731/opcache.so
7fc6ab289000-7fc6ab290000 r--p 00000000 08:03 26908255                   /usr/lib64/extensions/no-debug-non-zts-20180731/apcu.so
7fc6ab290000-7fc6ab29a000 r-xp 00007000 08:03 26908255                   /usr/lib64/extensions/no-debug-non-zts-20180731/apcu.so
7fc6ab29a000-7fc6ab29d000 r--p 00011000 08:03 26908255                   /usr/lib64/extensions/no-debug-non-zts-20180731/apcu.so
7fc6ab29d000-7fc6ab29f000 r--p 00013000 08:03 26908255                   /usr/lib64/extensions/no-debug-non-zts-20180731/apcu.so
7fc6ab29f000-7fc6ab2a0000 rw-p 00015000 08:03 26908255                   /usr/lib64/extensions/no-debug-non-zts-20180731/apcu.so
```

**Comment by ahkok** [comment]
Does `ldconfig -p | grep freetype` show just the ones in `/usr/lib64` or also ones in `/usr/local` ?

**Comment by ketonik** [comment]
`ldconfig -p | grep freetype`
	```
libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
	libfreetype.so.6 (libc6,x86-64) => /usr/lib64/libfreetype.so.6
	libfreetype.so (libc6,x86-64) => /usr/lib/libfreetype.so
```

**Comment by ahkok** [comment]
We've had you change/remove a few things. Is the original error still the same one? IOW, does it still throw:
```
(/usr/lib64/haswell/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var),
```
?

**Comment by ketonik** [comment]
> We've had you change/remove a few things. Is the original error still the same one? IOW, does it still throw:
> 
> ```
> (/usr/lib64/haswell/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var),
> ```
> 
> ?

Yes mate, still same error.

PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so (/usr/lib64/haswell/libharfbuzz.so.0: undefined symbol: FT_Done_MM_Var), /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so (/usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

I wonder now if the `imagick.so` extension itself is corrupted after it was opened by BBEdit over SFTP...swupd didn't determine that it had a hash mismatch, but as a long shot, I wonder if it would it be worthwhile, have you zip up your `imagick.so` binary files and i can place them in the correct directory and test to see if that is the issue?

**Comment by ahkok** [comment]
> I wonder now if the imagick.so extension itself is corrupted

`swupd diagnose` will tell you, and `swupd repair` will fix it.

For completeness:

```
$ sha512sum /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so 
713ee1d473849e675895605af823cfba2330d0515c993eb1f9f374132cf6fbf676d8771669ea81390bbeccbc6c720c9bb4d1ed38bb19f9ccd30d1a8e90ea583b  /usr/lib64/extensions/no-debug-non-zts-20180731/imagick.so
```

**Comment by ketonik** [comment]
> swupd diagnose

I can report same checksum hash as yours..

swupd diagnose
no issues

**Comment by ahkok** [comment]
You posted before:

```
$ ldconfig -p | grep freetype
libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
```

This isn't right. Clear Linux doesn't install `libfreetype.so.6` into `/usr/lib`. You shouldn't have any `.so` files in `/usr/lib` except maybe `ld-linux.so.2`

**Comment by ketonik** [comment]
There are several google results related to `FT_Done_MM_Var`
Which is affecting other users with different software:

Most searches point to issue with libfontconfig:
/usr/lib/libfontconfig.so

https://bbs.archlinux.org/viewtopic.php?pid=1766377

https://bbs.archlinux.org/viewtopic.php?id=234082

https://web.archive.org/web/20190522143329/https://forum.antergos.com/topic/9563/error-launching-software-undefined-symbol-ft_done_mm_var

https://forum.manjaro.org/t/steam-recently-civ-vi-stops-to-launch/68244

**Comment by ketonik** [comment]
> ldconfig -p | grep freetype

**Comment by ketonik** [comment]
> You posted before:
> 
> ```
> $ ldconfig -p | grep freetype
> libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
> ```
> 
> This isn't right. Clear Linux doesn't install `libfreetype.so.6` into `/usr/lib`. You shouldn't have any `.so` files in `/usr/lib` except maybe `ld-linux.so.2`

```
ldconfig -p | grep freetype
	libfreetype.so.6 (libc6,x86-64) => /usr/lib/libfreetype.so.6
	libfreetype.so.6 (libc6,x86-64) => /usr/lib64/libfreetype.so.6
	libfreetype.so (libc6,x86-64) => /usr/lib/libfreetype.so
```

I am unsure about this, I had a system admin trying to setup freetype in PHP a while back before we understood there was actually an issue with freetype not linked to php, my system admin probably messed around installing things without knowledge (hack and see).

if you recall freetype2 libgd, pho issues:

"so, we had freetype2 enabled in libgd, but not in php itself. I'm not
100% sure since, well, you never know, but, I fixed that. It'll take 2
days before it's available in a release, maybe tomorrow, earliest.

After rebuilding it it shows:

$ /usr/bin/php -i 'phpinfo();'|grep FreeType
FreeType Support => enabled
FreeType Linkage => with freetype
FreeType Version => 2.10.1

Before it said nothing."

**Comment by ahkok** [comment]
You should check:
```
ldd /usr/bin/php|grep free
	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fc8b6c6a000)
```

Note: `lib64`.

**Comment by ahkok** [comment]
Run `swupd diagnose --picky`. Note all the `Extra file:` entries. Any library that shows up in that list is a possible cause of this breakage. I suggest backing them up to a different directory (outside `ldconfig` range) and re-running `ldconfig`.

**Comment by ketonik** [comment]
> ldd /usr/bin/php|grep free

# ldd /usr/bin/php|grep free
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f12b3802000)

**Comment by ketonik** [comment]
> Run `swupd diagnose --picky`. Note all the `Extra file:` entries. Any library that shows up in that list is a possible cause of this breakage. I suggest backing them up to a different directory (outside `ldconfig` range) and re-running `ldconfig`.

Well 978 lines of them:

[swupd diagnose --picky.txt](https://github.com/clearlinux/distribution/files/3672401/swupd.diagnose.--picky.txt)

**Comment by ahkok** [comment]
```
 -> Extra file: /usr/lib/libfreetype.so.6.10.2
 -> Extra file: /usr/lib/libfreetype.so.6
 -> Extra file: /usr/lib/libfreetype.so
 -> Extra file: /usr/lib/libfreetype.la
 -> Extra file: /usr/lib/libfreetype.a
```

These are in the list. I'd consider backing them up or removing them.

Side note:
```
 /usr/save/freetype-2.5.0.1/
```
This is where you likely compiled it. Note that `/usr/src` is the canonical place to put sources and compile them.

**Comment by ketonik** [comment]
> ```
>  -> Extra file: /usr/lib/libfreetype.so.6.10.2
>  -> Extra file: /usr/lib/libfreetype.so.6
>  -> Extra file: /usr/lib/libfreetype.so
>  -> Extra file: /usr/lib/libfreetype.la
>  -> Extra file: /usr/lib/libfreetype.a
> ```
> 
> 
> These are in the list. I'd consider backing them up ~or~ and removing them from `/usr/lib` (edit).
> 
> 
> Side note:
> 
> 
> ```
>  /usr/save/freetype-2.5.0.1/
> ```
> 
> 
> This is where you likely compiled it. Note that `/usr/src` is the canonical place to put sources and compile them.

You're 'The MAN!' ahkok

As you suggested I removed all the above freetype files from /usr/lib/
ran php -i to confirm, no error
restarted nginx-mainline and php and now my php posts imagick

as a side note I should be able to safely delete all:
**/usr/save/freetype-2.5.0.1/**

and those extra files above i removed from:
**/usr/lib/**

**Comment by ketonik** [comment]
This what i have remaining after:

`swupd diagnose --picky`

Checking for extra files under /usr
 -> Extra file: /usr/share/man/man1/ffprobe.1
 -> Extra file: /usr/share/man/man1/ffmpeg.1
 -> Extra file: /usr/share/man/man1/ffmpeg-utils.1
 -> Extra file: /usr/share/man/man1/ffmpeg-scaler.1
 -> Extra file: /usr/share/man/man1/ffmpeg-resampler.1
 -> Extra file: /usr/share/man/man1/ffmpeg-protocols.1
 -> Extra file: /usr/share/man/man1/ffmpeg-formats.1
 -> Extra file: /usr/share/man/man1/ffmpeg-filters.1
 -> Extra file: /usr/share/man/man1/ffmpeg-devices.1
 -> Extra file: /usr/share/man/man1/ffmpeg-codecs.1
 -> Extra file: /usr/share/man/man1/ffmpeg-bitstream-filters.1
 -> Extra file: /usr/share/man/man1/ffmpeg-all.1
 -> Extra file: /usr/share/doc/openssh/sshd_config_jd
 -> Extra file: /usr/save/
 -> Extra file: /usr/lib64/php/test/apcu/tests/data/
 -> Extra file: /usr/lib64/php/test/apcu/tests/bad/
 -> Extra file: /usr/lib64/php/test/apcu/tests/
 -> Extra file: /usr/lib64/php/test/apcu/
 -> Extra file: /usr/lib64/php/doc/apcu/
 -> Extra file: /usr/lib64/php/.registry/.channel.pecl.php.net/
 -> Extra file: /usr/lib64/php/.depdblock
 -> Extra file: /usr/lib64/php/.depdb
 -> Extra file: /usr/lib64/p11-kit-trust.so
 -> Extra file: /usr/lib64/libXvMCgallium.so
 -> Extra file: /usr/lib32/libXvMCgallium.so
 -> Extra file: /usr/lib/pkgconfig/freetype2.pc
 -> Extra file: /usr/lib/pkgconfig/
 -> Extra file: /usr/include/ft2build.h
 -> Extra file: /usr/bin/composer

few remaining freetype bits (shall i remove these?)
<anything else in the list i can remove>?
**note:** the ffmpeg bits are likely there after running:
`composer require php-ffmpeg/php-ffmpeg`

 **-> Extra file: /usr/include/ft2build.h
 -> Extra file: /usr/lib/pkgconfig/freetype2.pc**

**Comment by ahkok** [comment]
The remaining ones are relatively harmless. Certainly you could `swupd repair --picky` these away, but `/usr/share/doc/openssh/sshd_config_jd` is something you probably want to save :)

The only ones that could cause issues are `libXvMCgallium.so`. The others won't really hurt anything, though.
