### ISSUE TITLE
How to set default kernel to boot up?

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1287]
Hi 
I noticed that there are two kernels installed in my laptop. 5.2.17 and 5.3.1. The default kernel to boot up is 5.2.17. Is there a way to set it to 5.3.1. My clearlinux version is 31110

**Comment by ahkok** [comment]
You want `5.2.17`. We noticed some issues with the `5.3.1` kernel and decided to revert it until we sorted out the problems discovered. Therefore, the `5.2.17` kernel is actually the one you should be running right now.

**Comment by ahkok** [comment]
Once a newer kernel is released, it will automatically be the default kernel from there on.

**Comment by stokhos** [comment]
Ok, got it.
