### ISSUE TITLE
Kernel support for Mellanox Gen2 PCI IDs (Connect-X2)

### ISSUE THREAD

**Issue by jquagga** [clearlinux/distribution#1288]
Good day ClearLinux,

I've been happily running Clear on a server in a kvm machine with a Debian base and today went to move the machine to bare metal clear.  And in doing so the Connect-X2 card which has provided 10gig connectivity to the machine for some time disappeared.  I tried loading the mlx4_en module to no avail.  

I believe the issue here is that Clear, unlike every other distro I've put on this machine has config MLX4_CORE_GEN2 set to n instead of the y default (in the kernel config).  Is that something that can be considered to be changed or was an intentional decision?

My guess is that it was the latter.  I'm aware Mellanox is trying to kill these cards off but it's hardware that just works with the option flipped to y so I figured I'd ask.

**Comment by bryteise** [comment]
We like to enable hardware when possible, currently we are dealing with some kernel issues with the 5.3 update though so it may be a little longer than normal for turning on.

**Comment by jquagga** [comment]
Thank you very much!  

I went ahead and as a trial followed the kernel development guide to compile the kernel with MLX4_CORE_GEN2=y.  Based on the KConfig I thought that was the default anyway but it doesn't seem so.  The card is UNCLAIMED in lshw on kernel-native even after manually loading mlx4_en.  The recompile I did with below "just works" as soon as the system boots.  This is running 5.3.1-843.  

```patch
diff --git a/config b/config
index a0f32fb..4f8a444 100644
--- a/config
+++ b/config
@@ -2765,7 +2765,7 @@ CONFIG_MLX4_EN=m
 CONFIG_MLX4_EN_DCB=y
 CONFIG_MLX4_CORE=m
 CONFIG_MLX4_DEBUG=y
-# CONFIG_MLX4_CORE_GEN2 is not set
+CONFIG_MLX4_CORE_GEN2=y
 CONFIG_MLX5_CORE=m
 CONFIG_MLX5_ACCEL=y
 CONFIG_MLX5_FPGA=y
```

**Comment by miguelinux** [comment]
The change is already in the `-native`and `-lts`
you will find it, in the next public release.

**Comment by jquagga** [comment]
Thank you very much!  

With 5.3.6-849.native I'm back up and running on stock kernel-native :).  The card works great.
