### ISSUE TITLE
Traefik - a cloud based reverse proxy and load balancer

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1290]
**Overview**
Traefik is a highly optimized reverse proxy and load balancer for cloud infrastructures. It has native support for local service discovery which is one of the biggest features that enables this software to work perfectly out of the box with containerized microservices like for instance ECS in AWS.

**Website:** [traefik.io](https://traefik.io/)
**Releases:** [Github releases](https://github.com/containous/traefik/releases)
**Installation:** [docs.traefik.io](https://docs.traefik.io/getting-started/install-traefik/)

**Comment by bryteise** [comment]
This looks like something that really wants to run in a container and not in the distro on bare metal. Could you describe the use case a little so I can integrate this in a sensible way? To me it would seem you would probably just use the dockerhub image rather than something from the OS.

**Comment by curantes** [comment]
traefik is cloud-native so the primary use case would be with the docker image. However it can easily be run in vm/bare metal and it is a feature rich reverse proxy that is more easily configured than nginx and haproxy. Personally I just use treafik in Kubernetes as ingress controller but I can see this can also be nice to have available native.

Just my 2 cents.

**Comment by bryteise** [comment]
Alrighty, so just one just needs /usr/bin/traefik in that case and not the webui bits?

**Comment by curantes** [comment]
Webui is in the traefik binary. You just enable it with flags if you wish to use it as most config options during start. Basicly you need the binary and a sane default config in /usr/share/default/traefik and systemd service with some sane defaults to have it properly integrated.

**Comment by bryteise** [comment]
I just added the sample config in /usr/share/traefik. Similarly the systemd service is also included but not activated by default in the bundle. Should be a release next week.
