### ISSUE TITLE
Full system crash when changing network interface

### ISSUE THREAD

**Issue by felixg3** [clearlinux/distribution#1292]
After setting up a wireguard interface with wg-quick or disabling Wifi/Ethernet, the whole system halts and crashes. The capslock light starts to flash on my dell latitude. This issue is rather weird and I have trouble getting the right logs to present here. Any idea how I can get some more verbose output about what happens so that I can post it here?

Issue does not seem to exist when using a userspace implementation of wireguard (wireguard-go) or when launching the lts kernel. However I do not have WiFi with the LTS-kernel, as the AX200 chipset seems to be supported only from 5.1 onwards.

**Comment by ahkok** [comment]
Can you check which version of the kernel you were running when this crash happened?

**Comment by ahkok** [comment]
We may need to refresh the kernel patch.

**Comment by ahkok** [comment]
Did you happen to catch any errors in `journalctl` from the crash?

**Comment by ahkok** [comment]
We can certainly enable that wifi chipset in the `LTS` kernels, as well.

**Comment by felixg3** [comment]
Hi ahkok, I didn't find anything particular in journalctl, but I think this is related to my capability of interpreting the information. I will upload the log here once I get home. The kernel version is 5.3.1 when the crash happened. It is reproduceable with either using wg-quick (kernel module implementation) or switching the wifi off/on. 
Full specs of the device: dell latitude e5x70, i5-6300u, 8gb ram, bios version 1.17.3, ax200 wifi chip (self-upgraded) running the most recent clearlinux version.

Maybe you can give me some hint to access verbose logging, I am not very familiar with the debugging capabilities, then I can crash it and upload the logs here.

> 
> 
> We can certainly enable that wifi chipset in the `LTS` kernels, as well.

**Comment by felixg3** [comment]
Issue does not seem to persist with Kernel 5.4.x.
