### ISSUE TITLE
Erlang Development Files Missing

### ISSUE THREAD

**Issue by gworkman** [clearlinux/distribution#1294]
Looks like the erlang package in the openstack-common bundle is missing the development files. Specifically, I require some header and source files like "erl_nif.h". I'm hoping this can be integrated into either the erlang package itself or in a new erlang-dev package. 

If given pointers in the right direction, I'm more than happy to help.

Clear Linux Version 31140

**Comment by bryteise** [comment]
devpkg-otp should be in the next day or two with the development content for erlang.

**Comment by gworkman** [comment]
@bryteise great, thanks!
