### ISSUE TITLE
Sway won't start

### ISSUE THREAD

**Issue by libXq** [clearlinux/distribution#1295]
I want to test how well Sway runs under Clear Linux. I installed Clear Linux via "clear-31140-live-server.iso" in VMware.

I just installed the base system with the defaults bundles.
clr-installer.yaml: [os-core, os-core-update, openssh-server, NetworkManager, sysadmin-basic, tzdata, kbd] I did not select any additional bundle.

After the installation and a reboot. I installed sway using "swupd bundle-add sway". But it won't start. typing "sway" in the tty1 I am getting the error: 
"xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
Segmentation fault (core dumped)

**Comment by ahkok** [comment]
So, I added this bundle as a "hail mary" to see if it would just work, but, I didn't have high hopes.

Desktops are complex and integration of them is time intensive. Ideally, we have an owner that cares about this desktop and can slowly identify and resolve problems with them, but, I'm not that person at the moment - I don't have the time right now.

Running `sway` manually likely doesn't work. I think you may have better success launching GDM and then selecting `sway` as a login session. Or use `lightdm`.

**Comment by GitHubRepositoryX** [comment]
Somehow after installing "sudo swupd bundle-add x11-server". Sway finally launches from TTY.

**Comment by GitHubRepositoryX** [comment]
> So, I added this bundle as a "hail mary" to see if it would just work, but, I didn't have high hopes.
Thank you!!

> Desktops are complex and integration of them is time intensive. Ideally, we have an owner that cares about this desktop and can slowly identify and resolve problems with them, but, I'm not that person at the moment - I don't have the time right now.
I accept that, If I could get any documentation about making clear linux packages. I would look into it, if it is not to hard for beginners.

> Running `sway` manually likely doesn't work. I think you may have better success launching GDM and then selecting `sway` as a login session. Or use `lightdm`.
there were some missing components see comment above.

**Comment by MattiaVerticchio** [comment]
> I want to test how well Sway runs under Clear Linux.

At least for me, Sway runs really well on Clear, way better than i3 considering the absence of tearing. I had a problem with starting it via GDM, but [this](https://github.com/clearlinux/distribution/issues/801#issuecomment-536158879) solved it, I don't know if it's related to this issue or may be helpful.

> I accept that, If I could get any documentation about making clear linux packages. I would look into it, if it is not to hard for beginners. I really like sway and clear linux is a nice design, slim , fast like sway so I am pretty much hyped about this.

These are some [contribution guidelines](https://github.com/clearlinux/distribution/blob/master/contributing.md) I found. :smile:

**Comment by ahkok** [comment]
> At least for me, Sway runs really well on Clear

How? I've yet to get it to start...

**Comment by MattiaVerticchio** [comment]
I followed [this](https://github.com/clearlinux/distribution/issues/801#issuecomment-536158879) comment. Just commenting out the wallpaper line in the default config, or changing `@datadir@` to `/usr/share/` worked for me. Obviously it won’t load the wallpaper, since `swaybg` is not bundled, but it starts and works fairly well.

**Comment by Svanto24** [comment]
> So, I added this bundle as a "hail mary" to see if it would just work, but, I didn't have high hopes.
> 
> Desktops are complex and integration of them is time intensive. Ideally, we have an owner that cares about this desktop and can slowly identify and resolve problems with them, but, I'm not that person at the moment - I don't have the time right now.
> 
> Running `sway` manually likely doesn't work. I think you may have better success launching GDM and then selecting `sway` as a login session. Or use `lightdm`.

I thought the entire point of Clear Linux was that packages were thoroughly tested as parts of bundles.

This, after the slew of security vulnerabilities on the multitude of Intel hardware I have been sold, frankly makes me wonder if the entire Intel Corporation has an irrational fear of quality assurance.

**Comment by lebensterben** [comment]
>> So, I added this bundle as a "hail mary" to see if it would just work, but, I didn't have high hopes. ...

@Svanto24
> we still want to attract developers but we are not as invested as we were in supporting a diverse and complex desktop environment, or even multiple desktop environments.
> It is with that in mind that we’ve decided to streamline our content offerings with a bias to cloud and server use cases. We do find that it remains critical to developers that we offer actual optimized components unrelated to desktops - that is, cloud and server workloads. This is absolutely where things matter most - being able to develop, deploy and operate those workloads.

from https://community.clearlinux.org/t/changes-coming-to-clear-linux-direction/4337?u=doct0rhu

**Comment by nobodyatandnothing** [comment]
this has been fixed by @fenrus75 
https://github.com/clearlinux/distribution/issues/2571
