### ISSUE TITLE
Cannot install from clear-31140-live-desktop.iso.xz

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#1298]
I am trying to install again in one of my machines, however it is not booting from a 4GB USB with clear-31140-live-desktop.iso.xz. This machine already had clear installed in the past.

The error:

![image](https://user-images.githubusercontent.com/10139950/66150719-22c6b080-e5ec-11e9-8060-27ea3c37a9e6.png)

**Comment by mdhorn** [comment]
@lf-araujo Seem like the image didn't write correctly.
Please verify the checksum, ensure the image is decompressed before putting it on the USB:
https://docs.01.org/clearlinux/latest/guides/maintenance/download-verify-decompress.html#download-verify-decompress

**Comment by ahkok** [comment]
Note the `device descriptor read/64, error -110`.

Possible causes (generally speaking):
- bad write or download
- damaged USB media
- USB stick too small (read past end of block device)

**Comment by ahkok** [comment]
Ohhh actually

`USB error -110 means power exceeded` ( From https://stackoverflow.com/questions/13653692/device-descriptor-read-64-error-110 )

**Comment by ahkok** [comment]
This indicates a hardware problem, sorry :(
