### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1299]
I tried to disable middle click paste. But couldn't do it. Also it seem there is noway to disable touchpad in gnome setting.

**Comment by ahkok** [comment]
Middle click paste:

1. open gnome-tweak-tool
2. search "paste"

Works for me (tested)

I don't think GNOME supports entirely disabling a touchpad. This can be done by disabling a driver, or in the BIOS. `Disable while typing` can be done, and is by default, in gnome-tweak-tool already.
