### ISSUE TITLE
MacBook Pro 2015 Trackpad Driver Missing/Broken

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#13]
Issue:

Clear Linux lacks a driver for the MacBook Pro 2015 Trackpad.

Steps to Reproduce:

1. Install Clear Linux with desktop-autostart checked on a MacBook Pro 2015.
2. Restart.
3. Login.
4. Check if Trackpad works.

Expected Results:

Trackpad works. Pretty sure it's just a synaptics driver.

Actual Results:

No response from Trackpad.

**Comment by fenrus75** [comment]
google suggests this is the CONFIG_MOUSE_BCM5974 driver, wihch we did not
have turned on.

I'm turning this on now

**Comment by fenrus75** [comment]
one of the interesting things to maybe collect is "lsacpi" output
(but google is pretty firm on the BCM5974 thing)

**Comment by sirredbeard** [comment]
Thank you. That appears correct. I did Google the issue but went down several inconclusive rabbit holes, my Google-fu must not be working.
