### ISSUE TITLE
coredumpctl bin always show "No coredumps found"

### ISSUE THREAD

**Issue by liuwei987** [clearlinux/distribution#130]
------------------------

### What is the issue type?

* [x] Bug report

### Describe the problem

I write an application to generate coredump, i can see the the core file in path "/tmp/core"
but when i use the "/usr/bin/coredumpctl" to show the coredump info, i always got the message
"No coredumps found".
The clearlinux version: 23950

**Comment by VictorRodriguez** [comment]
Can you share the source code of the application you are testing?

**Comment by fenrus75** [comment]
actually that's not needed
 we should be able to reproduce this with even basic coredumping test cases

**Comment by VictorRodriguez** [comment]
@liuwei987 thanks a lot for reporting this bug, @bryteise made a fix in our systemd to send the coredump files to the proper location. I tested his solution and works fine : 

$ cat main.c
#include <stdio.h>
#include <stdlib.h>

int main(){
    abort();
    return 0;
}
$ ./main
Aborted (core dumped)

 $ coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Sat 2018-07-28 12:11:30 UTC     889  1001  1001   6 present   /home/vrodri3/personal/hobbies/c_programing_exercises/coredumps/m>
lines 1-2/2 (END)

As soon as a new release came i will let you know so you can update with swupd 

thanks a lot

**Comment by VictorRodriguez** [comment]
@liuwei987 let me know if 24070 version fix the problem for you , it does for me

**Comment by liuwei987** [comment]
Seems the issue in the later clearlinux version:
root@clr-f22955655829422abe8ba5d29ac01f2f ~ # gcc test.c
root@clr-f22955655829422abe8ba5d29ac01f2f ~ # ./a.out
Aborted (core dumped)
root@clr-f22955655829422abe8ba5d29ac01f2f ~ # coredumpctl
No coredumps found.
root@clr-f22955655829422abe8ba5d29ac01f2f ~ # swupd info
Installed version: 24090
Version URL:       http://linux-ftp.bj.intel.com/pub/mirrors/clearlinux/update
Content URL:       http://linux-ftp.bj.intel.com/pub/mirrors/clearlinux/update
root@clr-f22955655829422abe8ba5d29ac01f2f ~ #

**Comment by alexjch** [comment]
Make sure that you have a build >= 24070 (already mentioned by Victor).
This fix was a patch to systemd so you might need to reboot (there might be a better way). The change to ```core_pattern``` did not take place in my box until I rebooted the system.

**Comment by bryteise** [comment]
You can avoid rebooting with systemctl daemon-reload.

**Comment by liuwei987** [comment]
Please let me know if i have the wrong reproduce steps.
Currently, i can reproduced the issue on: 
Installed version: 24110

**Comment by VictorRodriguez** [comment]
@liuwei987 can you share your cat /proc/sys/kernel/core_pattern ?

**Comment by liuwei987** [comment]
@VictorRodriguez  after core dump , execute below cmd:
 root@clr-27f4d54aadf34a1ab67672579d1157e1 ~ #  cat /proc/sys/kernel/core_pattern
|/usr/bin/usercrash_c %p %e %s

**Comment by VictorRodriguez** [comment]
It should not be that, something might be not right with swupd @bwarden  ?

**Comment by alexjch** [comment]
@liuwei987 you installed ["ACRN usercrash"](https://projectacrn.github.io/latest/tools/acrn-crashlog/usercrash/README.html) in your system and that's what is replacing the pattern. This is not a problem with clear.

**Comment by fenrus75** [comment]
this is not a Clear Linux issue, we aren't shipping this agent afaict.

**Comment by fenrus75** [comment]
Fixed this by not defaulting acrn usercrash to clobber the system
