### ISSUE TITLE
audio randomly going.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1302]
![image](https://user-images.githubusercontent.com/12841320/66177370-ef823100-e680-11e9-8c27-eebf30258fd0.png)

audio output randomly goes. 
```

android@clr~ $ sudo swupd bundle-add devpkg-pulseaudio
Password: 
Loading required manifests...
Warning: Bundle "devpkg-pulseaudio" is already installed, skipping it...
1 bundle was already installed
android@clr~ $ 
```
previously i had done above to correct it.
now its not working.

**Comment by nazar2sfive** [comment]
```
android@clr~ $ sudo swupd bundle-add devpkg-pulseaudio
Password: 
Loading required manifests...
Warning: Bundle "devpkg-pulseaudio" is already installed, skipping it...
1 bundle was already installed
android@clr~ $ sudo swupd bundle-remove devpkg-pulseaudio
Deleting bundle files...
Total deleted files: 43
Successfully removed 1 bundle
android@clr~ $ sudo swupd bundle-add devpkg-pulseaudio
Loading required manifests...
Downloading packs (7.61 MB) for:
 - devpkg-pulseaudio
	...100%
Finishing packs extraction...
No extra files need to be downloaded
Installing bundle(s) files...
	...100%
Calling post-update helper scripts
Successfully installed 1 bundle
android@clr~ $ 

```

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/66177553-9797fa00-e681-11e9-8bee-2af6be1753df.png)

after reboot and above re-install its back again up.

**Comment by ahkok** [comment]
I'm confused. What do you mean with "randomly going" - does the hardware device disappear? Does pulseaudio show errors in the journal?

**Comment by nazar2sfive** [comment]
@ahkok after my fresh install of 31230 this problem has not appeared to me yet.
previously it used to randomly disappear as if pusleaudio had crashed in background or something.
