### ISSUE TITLE
fonts wrong after chrome.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1303]
https://community.clearlinux.org/t/installing-google-chrome-on-clear-linux/1132

font was working for few days until i installed opera using following: https://community.clearlinux.org/t/installing-opera-browser/392

![image](https://user-images.githubusercontent.com/12841320/66177657-070de980-e682-11e9-9363-b7f8f36b90b6.png)

now both font in opera and chrome is wrong.

in chrome forum:
f=/etc/environment; s='export FONTCONFIG_PATH=/usr/share/defaults/fonts'; touch $f; if ! grep -q "$s" $f; then echo $s >> $f; fi

in opera install forum:
f=/etc/environment; s='export FONTCONFIG_PATH=/usr/share/defaults/fonts'; touch $f; if ! grep -q "$s" $f ; then echo $s >> $f; fi

i did both in both install.
its not working.

**Comment by ahkok** [comment]
```
f=/etc/environment; s='export FONTCONFIG_PATH=/usr/share/defaults/fonts'; touch $f; if ! grep -q "$s" $f; then echo $s >> $f; fi

in opera install forum:
f=/etc/environment; s='export FONTCONFIG_PATH=/usr/share/defaults/fonts'; touch $f; if ! grep -q "$s" $f ; then echo $s >> $f; fi
```

You are writing `export F....` into `/etc/environment`. This is wrong. The correct formatting is described in `man environment.d`.

After modifying these files, you may have to logout or even restart your computer for the changes to take effect. Not all services may even honor these changes.

Make sure you test your changes by launching a terminal and verifying that `env` outputs the desired shell settings.
