### ISSUE TITLE
how to extract .rar?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1305]
![image](https://user-images.githubusercontent.com/12841320/66191521-45b99900-e6ae-11e9-8605-c83c8c1ab8e2.png)
i tried this after

` sudo swupd bundle-add dev-utils`

it failed.

```
android@clr~ $ unrar
unrar: command not found
The command unrar is not available, consider using: zip or tar
android@clr~ $ sudo dnf install unrar
Password: 
Unable to detect release version (use '--releasever' to specify release version)
Failed loading plugin: changelog
Last metadata expiration check: 18:57:58 ago on Thu 03 Oct 2019 07:05:04 PM +0545.
No match for argument: unrar
Error: Unable to find a match
android@clr~ $ 

```

**Comment by OpenSourceAnarchist** [comment]
You should not use dnf. Try 7z (from the Clear Linux repos). GNOME's file-roller (available as a separate bundle called file-roller) can handle .rar files too. See [https://community.clearlinux.org/t/what-software-can-i-use-to-extract-rar/1372](https://community.clearlinux.org/t/what-software-can-i-use-to-extract-rar/1372)

**Comment by ahkok** [comment]
`file-roller` implements it's own parsing algorithm for `rar` files. It does not use an external library or command. I know of no other tool we can ship that can extrar `rar` files because the canonical tool is not open-source.
