### ISSUE TITLE
AWS DKMS bundle for supporting Nvidia drivers and CUDA in Tensorflow

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1306]
AWS offers AI computing with Nvidia Tesla GPUs in the EC2 service but this is troublesome to set up without a DKMS bundle that's compatible with the `kernel-aws`.

Could we please have a DKMS bundle for the AWS kernel?

**Comment by bryteise** [comment]
I know @miguelinux was looking at this so just doing the tracking assignment.

**Comment by miguelinux** [comment]
@xRiot `kernel-aws-dkms` bundle is already added to Clear Linux, please let us know if it works for you.

**Comment by xRiot** [comment]
Thank you @miguelinux.

Our main objective is to get CUDA 10.1 and latest Nvidia drivers for Tensorflow in AWS but the `kernel-aws-dkms` bundle seems to be missing something as the driver installation is failing to complete.

We followed [NVIDIA* Drivers](https://docs.01.org/clearlinux/latest/tutorials/nvidia.html) guide but replaced native kernel/dkms with aws variants and we also removed `no-nvidia-modprobe` parameter for CUDA support _(it also fails when the parameter is specified)_:
```
sh NVIDIA-Linux-x86_64-418.87.01.run \
--utility-prefix=/opt/nvidia \
--opengl-prefix=/opt/nvidia \
--compat32-prefix=/opt/nvidia \
--compat32-libdir=lib32 \
--x-prefix=/opt/nvidia \
--x-module-path=/opt/nvidia/lib64/xorg/modules \
--x-library-path=/opt/nvidia/lib64 \
--x-sysconfig-path=/etc/X11/xorg.conf.d \
--documentation-prefix=/opt/nvidia \
--application-profile-path=/etc/nvidia \
--no-precompiled-interface \
--no-distro-scripts \
--force-libglx-indirect \
--glvnd-egl-config-path=/etc/glvnd/egl_vendor.d \
--egl-external-platform-config-path=/etc/egl/egl_external_platform.d  \
--dkms \
--silent
```
This returns the following error log: [nvidia-installer.log](https://pastebin.com/raw/ehFpeXVA)

We then tried to apply the suggested bundles and steps from [Tutorial for Installing CUDA needed #464](https://github.com/clearlinux/clear-linux-documentation/issues/464) which results in a more detailed error:
```
sh NVIDIA-Linux-x86_64-418.87.01.run --no-distro-scripts --no-opengl-files --no-libglx-indirect --no-install-libglvnd --no-install-compat32-libs --dkms --ui=none
```
Terminal: [output](https://pastebin.com/raw/sYqMPvF1)
Log: [nvidia-installer.log](https://pastebin.com/raw/dbJ2CJxw)
Build: [make.log](https://pastebin.com/raw/hX3AUDDX)

NVIDIA driver v418.87 was acquired from [NVIDIA Driver Downloads](https://www.nvidia.com/Download/index.aspx):
``
Product Type: Tesla
Product Series: M-Class
Product: M60
Operating System: Linux 64-bit
CUDA toolkit: 10.1
Language: English (US)
```
AWS instance type is: `g3s.xlarge`

Thanks in advance for the help.

**Comment by puneetse** [comment]
It's an incompatibility between that version of the NVIDIA driver and the 5.3 Linux kernel.

```
In file included from /var/lib/dkms/nvidia/418.87.01/build/nvidia/nv_uvm_interface.c:21:
/var/lib/dkms/nvidia/418.87.01/build/nvidia/nv_uvm_interface.c: In function 'nvUvmInterfaceDeRegisterUvmOps':
/var/lib/dkms/nvidia/418.87.01/build/common/inc/nv-linux.h:733:21: error: void value not ignored as it ought to be
  733 |         int __ret = on_each_cpu(func, info, 1);        \
      |                     ^~~~~~~~~~~
/var/lib/dkms/nvidia/418.87.01/build/nvidia/nv_uvm_interface.c:991:5: note: in expansion of macro 'NV_ON_EACH_CPU'
  991 |     NV_ON_EACH_CPU(flush_top_half, NULL);
      |     ^~~~~~~~~~~~~~
```

You can try searching around for this error on the Internet. Sometimes people create patches to the nvidia installer to work around specific versions incompatibilities.

**Comment by xRiot** [comment]
Thanks for the information @puneetse.

Although I believe the cause of the installation issues is mainly due to `libGLdispatch.so.0` missing in the system, here's a closed ticket that's describing a similar issue: #1133.

We spinned up a new instance with a clean Clean Linux's official AMI _(aka ISO)_ to try more [recent drivers](https://www.nvidia.com/en-us/drivers/unix/) _(v435.21)_ which doesn't come with CUDA Toolkit 10.1 and by only following the [NVIDIA* Drivers](https://docs.01.org/clearlinux/latest/tutorials/nvidia.html#nvidia-drivers) guide _(native kernel/dkms is replaced with aws variant like I've described above)_. This unfortunately also fails, see below:

Terminal: [output](https://pastebin.com/raw/n6T5CVY9)
Build: [make.log](https://pastebin.com/raw/An6UnmZC)
Log: [nvidia-installer.log](https://pastebin.com/raw/ybBkMNz2)

Any advice on how we can proceed?

**Comment by xRiot** [comment]
Quick update, I've just confirmed that the `kernel-native` and `kernel-native-dkms` works perfectly fine with Nvidia driver version v435.21 on a local computer outside of AWS, it's only failing with the AWS bundle variants in EC2.

Console output for my local system _(native kernel)_:
```
root@unix~ # lsmod | grep ^nvidia
nvidia_drm             45056  0
nvidia_modeset       1122304  1 nvidia_drm
nvidia              19513344  1 nvidia_modeset
nvidiafb               53248  0
root@unix~ # cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  435.21  Sun Aug 25 08:17:57 CDT 2019
GCC version:  gcc version 9.2.1 20191013 gcc-9-branch@276932 (Clear Linux OS for Intel Architecture)
root@unix~ # uname -r
5.3.6-849.native
```

**Comment by puneetse** [comment]
> I believe the cause of the installation issues is mainly due to `libGLdispatch.so.0` missing in the system

This error in the install logs is ok. The nvidia-install tries to detect if a libglvnd is installed in the system (not distributed by Clear Linux) before installing it. The error is an output of that check.

**Comment by xRiot** [comment]
Another update, we just tried a pre-release version of NVIDIA driver ([440.26](https://download.nvidia.com/XFree86/Linux-x86_64/440.26/)) but this results in the same error as described above.

Going back to the desired NVIDIA driver _(418.87.01)_ with CUDA Toolkit 10.1, we were able to generate a bug report using `sh /opt/bin/nvidia-bug-report.sh` _(last link)_:
Terminal: [output](https://pastebin.com/raw/HXuDiVgn)
Build: [make.log](https://pastebin.com/raw/HEr5TdTB)
Log: [nvidia-installer.log](https://pastebin.com/raw/yTJa9mng)
Dump: [nvidia-bug-report.log](https://pastebin.com/raw/W0ybSJU6)

Maybe this could shine some light on the core of this issue @miguelinux?

**Comment by xRiot** [comment]
This ticket got closed since the main request got fulfilled.

I've opened up a discussion in Clear Linux's community forum and the dev team was able to identify the issue in `kernel-aws`. In summary it comes with setting `CONFIG_TRIM_UNUSED_KSYMS=y` which renders a lot of module symbols inaccessible. There's a patch coming and you can track the discussion [here](https://community.clearlinux.org/t/nvidia-drivers-with-cuda-10-1-on-aws-ec2/1962).

**Comment by bwarden** [comment]
Fixed in https://github.com/clearlinux-pkgs/linux-aws/commit/23de37a5ca10c167f06c749bf68fd9d8227ee557

**Comment by chriseomi** [comment]
does anyone know if this enables AWS "enhanced networking"?

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html
