### ISSUE TITLE
how to create gdm as default in clear linux

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1308]
i installed kde in clear linux and am using it once in a while.

but my gdm has been changed to sddm. how can i change back sddm to gdm?

**Comment by OpenSourceAnarchist** [comment]
Can you run `systemctl disable sddm` and `systemctl enable gdm` as root? You may have to do this every time sddm updates. A Clear Linux* developer may have a better option.

**Comment by bryteise** [comment]
Hrm I'd be surprised if you need to enable gdm each time but you could `systemctl mask sddm` which should prevent it from starting regardless of updates.

**Comment by OpenSourceAnarchist** [comment]
@bryteise You're right, I forgot about masking. That should be enough to prevent sddm from taking control away from gdm.

**Comment by thiagomacieira** [comment]
Please note that KDE developers only test SDDM, so it's the recommended solution. Some functionality like rebooting from inside the session manager, auto-login, etc. may be missing if you use GDM.

**Comment by ahkok** [comment]
Issue answered in comment 2 and 3.
