### ISSUE TITLE
/usr/etc should not exist

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1310]
In build 31210, we have several bundles that have content in /usr/etc, and this path should not exist

This is the error

> /usr/etc/jupyter

>  /usr/etc/jupyter/nbconfig

 

> /usr/etc/jupyter/nbconfig/notebook.d

 

> /usr/etc/jupyter/nbconfig/notebook.d/plotlywidget.json

The some of the affected bundles are 

- machine-learning-web-ui
- machine-learning-basic
- machine-learning-mycroft
- machine-learning-tensorflow
- python-data-science
- eigen
- computer-vision-basic
- os-testsuite-phoronix
- file-roller
- gpaste
- python2-basic

**Comment by phmccarty** [comment]
This was introduced in the new `plotly` package, added by @bryteise.

**Comment by bryteise** [comment]
X( well lets figure out where that should actually be.

**Comment by bryteise** [comment]
Should be fixed next week.
