### ISSUE TITLE
Add notepadqq to desktop-app-extras bundle

### ISSUE THREAD

**Issue by szollin** [clearlinux/distribution#1311]
Clear Linux is lacking a graphical text program that is really good at highlighting code. Please add notepadqq to the desktop-app-extras bundle to help cover that

**Comment by szollin** [comment]
The highlighting for different types of codes isn't as good in those 3 editors. It's an editor I have been using for a while.

**Comment by ahkok** [comment]
Unfortunately we have to reject this request. `notepadqq` depends on an outdated component that we can not add (qtwebkit).
