### ISSUE TITLE
weather not showing my location on drop down over clock.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1318]
![image](https://user-images.githubusercontent.com/12841320/66265136-dddf8b80-e830-11e9-8e5f-67f4e7285195.png)

**Comment by curantes** [comment]
I had similar problem but with the latest version that came today **31230** this is now fixed and works correctly for me. Can you test again with the new version?

**Comment by mrkz** [comment]
Sorry, I've not been able to reproduce this on any of my systems, If you continue to have this issue, please open a new issue specifying the clearlinux version.

Thanks for your issue report.
