### ISSUE TITLE
Please add fail2ban

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1327]
A program which might help to detect and ban intruders, thx.

https://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by fenrus75** [comment]
By default we ship tallow that does the same...

**Comment by ahkok** [comment]
`tallow` is enabled and operational in clearlinux by default, and instructed to moderate SSH attacks. It is pluggable and can be configured to protect other services, and has significantly smaller resource footprint. If you have any specific requirements - e.g. needs to protect a specific service, please let us know.

**Comment by ahkok** [comment]
https://github.com/clearlinux/tallow for reference.

**Comment by seafrog1** [comment]
Thx, didn't see. I'll close the issue
