### ISSUE TITLE
flake8 broken by newer pycodestyle than supported

### ISSUE THREAD

**Issue by bwarden** [clearlinux/distribution#133]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

flake8 explicitly depends on pycodestyle < 2.4.0 due to a breaking change, but Clear Linux provides pycodestyle == 2.4.0. This dependency is overridden here:
https://github.com/clearlinux-pkgs/flake8/blob/85b05e80b7f2a4d9db66e164aa0f0dd439135a8d/reqs.patch#L29

See https://github.com/PyCQA/pycodestyle/issues/741 for more context.

**Comment by fenrus75** [comment]
looks like we need to delete flake8 from the OS.

**Comment by fenrus75** [comment]
fix is already upstream; backporting now

**Comment by fenrus75** [comment]
fixed
