### ISSUE TITLE
Nordvpn

### ISSUE THREAD

**Issue by HeikoSc** [clearlinux/distribution#1330]
https://nordvpn.com/download/

**Comment by thiagomacieira** [comment]
Doesn't look like it's Open Source, so we can't add it. Searching online shows that it's possible to configure OpenVPN to connect to NordVPN and we do have that.

https://www.reddit.com/r/nordvpn/comments/bf9nmz/does_nord_have_plans_to_go_open_source/
https://nordvpn.com/pt-br/tutorials/windows-7/openvpn/
