### ISSUE TITLE
HSDPA HSUPA Modem plugin Missing

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1332]
For my two Modems
Bus 001 Device 017: ID 12d1:1001 Huawei Technologies Co., Ltd. E161/E169/E620/E800 HSDPA Modem
and 
Bus 001 Device 015: ID 19d2:2000 ZTE WCDMA Technologies MSM MF627/MF628/MF628+/MF636+ HSDPA/HSUPA
Modem Managers shows me
● ModemManager.service - Modem Manager
   Loaded: loaded (/usr/lib/systemd/system/ModemManager.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-10-10 10:30:55 WITA; 51s ago
 Main PID: 3704 (ModemManager)
    Tasks: 3
   Memory: 1.7M
   CGroup: /system.slice/ModemManager.service
           └─3704 /usr/bin/ModemManager

Oct 10 10:30:55 b1 systemd[1]: Starting Modem Manager...
Oct 10 10:30:55 b1 ModemManager[3704]: <info>  ModemManager (version 1.10.4) starting in system bus...
Oct 10 10:30:55 b1 systemd[1]: Started Modem Manager.
Oct 10 10:30:58 b1 ModemManager[3704]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-11': not supported by any plugin
Oct 10 10:30:58 b1 ModemManager[3704]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:1d.0/0000:02:00.0': not supported by any plugin
Oct 10 10:30:58 b1 ModemManager[3704]: <info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:1f.6': not supported by any plugin

Did I miss something to add, Thx in advance.

**Comment by seafrog1** [comment]
Update: After reboot with connected Modem the Huawei one is now recognized, still not connected, the ZTE (Bus 001 Device 015: ID 19d2:2000 ZTE WCDMA Technologies MSM MF627/MF628/MF628+/MF636+ HSDPA/HSUPA) is still not recognized

**Comment by ahkok** [comment]
I'm updating ModemManager. Unsure if this will help, though.

**Comment by sunnyflunk** [comment]
I checked to see if `usb-modeswitch` was in CLR, and it didn't look like it. It helps with problematic modems that try to load the drivers when plugged in. Requires both the main program and the -data udev files http://www.draisberghof.de/usb_modeswitch/#download

Taking a peek at the data files, there is a rule for that device specifically:
```
# ZTE devices, some Onda devices
ATTR{idVendor}=="19d2", ATTR{idProduct}=="2000", RUN+="usb_modeswitch '/%k'"
```

**Comment by ahkok** [comment]
Looks like that's exactly what you need. I'll be adding these and figuring out how to make these available through bundles...

**Comment by ahkok** [comment]
`NetworkManager-extras` bundle will have this in a few days...

**Comment by seafrog1** [comment]
Thx for helping.  BR Rainer
