### ISSUE TITLE
postgresql11-install.service failed to start

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1335]
In build 31280, we have a regression for  postgresql11, service failed to start

This is the error
`systemctl start postgresql11-install.service failed
 Job for postgresql11-install.service failed because the control process exited with error code.
 See "systemctl status postgresql11-install.service" and "journalctl -xe" for details.`

**Comment by bwarden** [comment]
postgresql11-install.service attempts to use "su" to run a command as postgres user, while needing to start as root to create the postgresql11 data directory. systemd provides a cleaner mechanism to do this:
```
[Service]
User=postgres
PermissionsStartOnly=true
```
With this change, the ExecStartPre directive runs as root, but the ExecStart directive runs as postgres, eliminating the need for a complex su/bash command.

**Comment by bwarden** [comment]
Fix is committed; should appear next release.

**Comment by arturo-garcia-garcia** [comment]
Issue is gone in build 31130, closing this issue

**Comment by arturo-garcia-garcia** [comment]
Issue is gone in build 31130, closing this issue
