### ISSUE TITLE
python's venv module fails to install pip

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#1337]
Using python3's `venv` module to create a virtual environment fails with an unexpected error:

```
$ python3 -m venv my_env
Error: Command '['/tmp/testdir/my_env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

If instructed not to install pip, the error disappears:

```
$ python3 -m venv my_env --without-pip
```

**Comment by jack23247** [comment]
This can be reproduced by attempting to install [Throttled](https://github.com/erpalma/throttled) 

Running the following commands...
```
$ sudo swupd bundle-add c-basic python3-basic devpkg-cairo devpkg-glib devpkg-pygobject devpkg-gobject-introspection 
$ git clone https://github.com/erpalma/lenovo-throttling-fix.git
$ sudo ./lenovo-throttling-fix/install.sh
```
...yields:
```
Copying config file...
Copying systemd service file...
Building virtualenv...
Error: Command '['/opt/lenovo_fix/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Comment by bryteise** [comment]
Currently python3 doesn't provide the pip whl causing these failures.

**Comment by jack23247** [comment]
Thank you for clarifying.
Honestly, I'm no Python expert: is there any way to manually install the whl or is it something that must be fixed system-wise?

**Comment by lebensterben** [comment]
>Thank you for clarifying. ...

@jack23247 I've a good news if you know basic Python. Throttle only uses very minimal amount of Python and you can either manually patch your system, or translate the several .py files to shell scripts. In either cases, it won't take long.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bryteise** [comment]
@jack23247 Should be fixed system side that said, virtualenv works if you want to hack the script a bit or just follow @lebensterben's advice.

**Comment by jack23247** [comment]
Thank you very much @lebensterben @bryteise, I'll let you work your magic.
I'll try and hack the script a little bit in case I really need to use Throttled

**Comment by bryteise** [comment]
This should be fixed in the next release.
