### ISSUE TITLE
ldd depends on python-extras

### ISSUE THREAD

**Issue by shaicoleman** [clearlinux/distribution#1339]
To use the `ldd` command, it requires installing the `python-extras` package, which adds a lot of unnecessary packs, and it has nothing to do with Python. In Ubuntu for example, it's included in the `libc-bin` essential package.

```
# ldd
To install ldd use: swupd bundle-add python-extras
# swupd bundle-add python-extras
Downloading packs (361.51 MB) for:
```

OS version: 31140 via the docker image

**Comment by shaicoleman** [comment]
It might be just a problem with the suggestion, it seems to also be included in `sysadmin-basic`

**Comment by fenrus75** [comment]
$ swupd-search -vv ldd
Adding  20 ( 20.0 ) to  python-extras due to command-not-found file match
Dividing  python-extras by  2.0  to  10.0 due to adjust for bundle already
being installed
Bundle with the best search result:
     python-extras                      - Improve user experience with a
common set of prebuilt Python libraries. with score 10.0 and size 804 MB


so the search function of swupd goes to the cnf list, time to debug that
there l-)

**Comment by fenrus75** [comment]
Bundle python-extras  with size  84358565.8 has  ldd
Bundle sysadmin-basic with size 10006980.93 has  ldd

ok so the cnf generator things python-extras is smaller than
sysadmin-basic, likely because it is directly (but not with dependencies
counted)

**Comment by fenrus75** [comment]
hmm sysadmin-basic got bloated, we should fix THAT and hte rest falls in
place ;_)

**Comment by bryteise** [comment]
I'd imagine ldd should be bundled specifically. Would make sysadmin-basic smallerish with an also add as a side-effect.

**Comment by fenrus75** [comment]
I'll shrink sysadmin basic anyway it's too bloated

**Comment by thiagomacieira** [comment]
Can we just put ldd in os-core? It's a 5488 byte shell script!

**Comment by fenrus75** [comment]
yeah makes sense... the bundle files would be bigger than the payload

**Comment by ahkok** [comment]
> Can we just put ldd in os-core? It's a 5488 byte shell script!

I bet I can make it smaller, too XD

**Comment by thiagomacieira** [comment]
If you don't need the options (like -d, -r or -h), then:

```sh
#!/bin/sh
LD_TRACE_LOADED_OBJECTS=1 exec "$@"
```

-d is `LD_WARN=yes`, while -r is `LD_BIND_NOW=yes` which is unnecessary in Clear since we default to "now" anyway.

**Comment by ahkok** [comment]
Submitted a patch

**Comment by rossburton** [comment]
`ldd` is in `os-core` now, closing.
