### ISSUE TITLE
AWS AMI SSH public key authentication issues.

### ISSUE THREAD

**Issue by c-edw** [clearlinux/distribution#134]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

I have been trying out the AMI (machine image) for Clear Linux in AWS. 

I am able to SSH as normal to `t2.micro` instances, using the username `clear`, and my SSH key. However, if I spin up a `c5.large` instance with the Clear Linux AMI, my SSH key does not work. It is not denied, but ignored, and I am asked for a password. 

Passing `-vv` to `ssh` outputs the following relevant debug info.

```
...
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:G/csmNUgwmF4cREO3C7IteYRszuO0uC8YC6v306gIg4 /home/cedwards/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Authentications that can continue: publickey,password,keyboard-interactive
...
```

**Comment by vaclave** [comment]
We have seen this reported intermittently.  Can you confirm what version of Clear that your instance was created from?

**Comment by c-edw** [comment]
Wow, thanks for the quick response. The AMI description says that the version is 23760. On first boot, it might update though. [Link to AMI.](https://aws.amazon.com/marketplace/pp/B075TXF7KJ?ref=cns_srchrow) Thanks.

**Comment by ahkok** [comment]
I am awaiting a new release of a clr AMI that has a fix to `ucd`. Then I can test and see if that fixes the issue.

**Comment by ahkok** [comment]
This is a duplite of #68. We'll track it in there further.
