### ISSUE TITLE
Desktop: LibreOffice Calc: search and replace in .xlsx file freezes user interface

### ISSUE THREAD

**Issue by msmart** [clearlinux/distribution#1341]
On version 31270, I could reproduce the following behavior on two laptops using different xlsx files. One laptop was running from an USB stick, on the other Clear Linux was installed. 

To reproduce:

1. Boot into a fresh install of Clear Linux
2. Open LibreOffice Calc
3. Open a sample .xlsx file that contains data
4. Select a column with data, click on "Edit" -> "Find & Replace"
5. Enter a value (that exists in the selected column) in the "Find" input field
6. Click on Replace (sometimes several times)
7. Observe how the interface is freezing

Switching to a terminal input via Ctrl-Alt F3, shows the following soffice.bin running at 100%

![image](https://user-images.githubusercontent.com/85249/66677724-93b03d00-ec6a-11e9-9820-2e30779cb4d0.png)

The user interface hangs while showing that a process is not responding.
![image](https://user-images.githubusercontent.com/85249/66677739-9d39a500-ec6a-11e9-937f-8736f6633b25.png)

(Please note that this error does not happen for .ods files).

**Comment by bwarden** [comment]
We've upgraded LibreOffice from 6.3.1.2 to 6.3.2.2. Can you recheck in the newer version?

**Comment by ahkok** [comment]
Tried but could not reproduce yesterday with 6.3.2.2. @msmart can you retest?

**Comment by msmart** [comment]
@ahkok I can still reproduce it on version 31310 (LibreOffice 6.3.2.2), tried with different different files. But if you cannot re-produce it, maybe it should be closed. I can investigate upstream for solutions.

**Comment by ahkok** [comment]
Probably best is to tackle the issue with upstream, they may be better suited to figure out a root cause.
