### ISSUE TITLE
https://clearlinux.org/ down

### ISSUE THREAD

**Issue by pdxjohnny** [clearlinux/distribution#1343]
```
The website encountered an unexpected error. Please try again later.
```

Also, https://downloads.clearlinux.org/ is down

**Comment by miguelinux** [comment]
our apologies for this inconvenient, our server is on maintenance, it will be back soon.

**Comment by ahkok** [comment]
@mdpitterle

**Comment by mdhorn** [comment]
@pdxjohnny The site with all of the past downloads is actually https://download.clearlinux.org/ and it is working.

**Comment by mdhorn** [comment]
Though the main site seems to be down for maintenance, the document site is still operational if needed:
https://docs.01.org/clearlinux/latest/index.html

**Comment by mdpitterle** [comment]
The maintenance event is over.
