### ISSUE TITLE
Mine Time

### ISSUE THREAD

**Issue by HeikoSc** [clearlinux/distribution#1346]
https://minetime.ai/

**Comment by ahkok** [comment]
Please tell us *what it does* and *why anyone would want it*

You can save us a lot of time by giving us links to *source code releases*.

After having tracked down where source code for `mine time` is released, I find this statement:

```
MineTime is free to use but not open-source (yet).
```

Therefore, we can't add this. You could have saved us some time here.

If it ever is open sourced, open a new ticket.

**Comment by HeikoSc** [comment]
I am very sorry, that I caused unnecessary work. It will not happen
again!

Am Samstag, den 12.10.2019, 22:40 -0700 schrieb ahkok:
