### ISSUE TITLE
Wrong download links to the Desktop .iso image

### ISSUE THREAD

**Issue by bciscato** [clearlinux/distribution#1348]
The download links to the Desktop .iso image at:

https://clearlinux.org/downloads

point to the wrong files:

Desktop -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-desktop.iso-SHA512SUMS.sig
SHA512 -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-server.iso
Signature -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-server.iso-SHA512SUMS

I think they should point to:

Desktop -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-desktop.iso
SHA512 -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-desktop.iso-SHA512SUMS
Signature -> https://cdn.download.clearlinux.org/releases/31290/clear/clear-31290-live-desktop.iso-SHA512SUMS.sig

**Comment by cherryshine** [comment]
Yeah, I was reporting this too. I was a little confused what to download.

**Comment by puneetse** [comment]
D'oh, sorry about this. We're aware if the issue

**Comment by Stupendoussteve** [comment]
Came here to report this - links are also incorrect for the server images and the other virtual images farther down the page.

**Comment by puneetse** [comment]
The downloads page has been fixed. Thanks for bearing with us.
