### ISSUE TITLE
cronie bundle stat/opendir failed in /etc/cron.d on start

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1349]
On clean installation of bundle `cronie` you get the following errors every time when the package starts:
```
Oct 12 22:19:02 unix crond[385]: (CRON) STAT FAILED (/etc/cron.d): No such file or directory
Oct 12 22:19:02 unix crond[385]: (CRON) OPENDIR FAILED (/etc/cron.d): No such file or directory
```
This is due to the fact that Clear Linux doesn't generate these directories for compliance with stateless design, although cronie should by default not return this error and rather look in its responsive directories: `/usr/share/cronie/`

**Comment by ahkok** [comment]
There's nothing in `/usr/share/cronie/` so it should just not throw an error if the folder does not exist.

**Comment by ahkok** [comment]
`cronie-1.5.4.final-20` should no longer show these errors.
