### ISSUE TITLE
Zswap Support

### ISSUE THREAD

**Issue by airend** [clearlinux/distribution#135]
### What is the issue type?

* [ ] Bug report
* [X] Enhancement request

### Describe the problem

While zRAM is enabled, Zswap is not, and `systemd-swap` cannot fully work. Is it possible to enable Zswap support (CONFIG_ZSWAP, CONFIG_ZPOOL, CONFIG_ZBUD, CONFIG_Z3FOLD, CONFIG_FRONTSWAP) and CONFIG_CLEANCACHE?

**Comment by fenrus75** [comment]
done

I just put this into our build infra, but given the time of day on friday
it may be until Monday for a release to go out with this

**Comment by airend** [comment]
Thanks.
