### ISSUE TITLE
Package request: Alloy

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#1353]
> Alloy is a language for describing structures and a tool for exploring them. It has been used in a wide range of applications from finding holes in security mechanisms to designing telephone switching networks.

https://github.com/AlloyTools/org.alloytools.alloy

**Comment by ahkok** [comment]
Java -> @AthenasJimenez

**Comment by grayswandyr** [comment]
As Alloy Analyzer is distributed as a self-contained JAR, I don't really see what would be the advantage of a distribution-specific package here?

**Comment by cmarcelo** [comment]
Main reason is it does make convenient to handle install and updates the same way as the rest of the system.

Clear Linux team may decide to reuse the existing upstream provided binaries, but more likely will prefer to build it from the sources themselves.
