### ISSUE TITLE
jack_control: python exceptions

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#1354]
OS version: 31290

Steps to reproduce:
<pre>
$  sudo swupd bundle-add jack2
Loading required manifests...
Downloading packs (3.28 MB) for:
 - jack2
        ...100%
Finishing packs extraction...
No extra files need to be downloaded
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts
Successfully installed 1 bundle

$ jack_control
  File "/usr/bin/jack_control", line 80
    print 'shit'
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('shit')?
</pre>

**Comment by anselmolsm** [comment]
In 31290, it's jack2 1.9.12. An update to jack 1.9.13 is already work in progress in Clear Linux, and that upstream release [contains a fix for this](https://github.com/jackaudio/jack2/blob/v1.9.13/example-clients/jack_control#L81).

**Comment by jurobystricky** [comment]
There is also another exception, hopefully fixed as well (but I am not too sure):

<pre>
File "/usr/bin/jack_control", line 187
elif arg == 'sm':
^
TabError: inconsistent use of tabs and spaces in indentation
</pre>

**Comment by ahkok** [comment]
`jack2-1.9.13-4`
