### ISSUE TITLE
RTL8812BU cant be recognised with manually installed drivers

### ISSUE THREAD

**Issue by kirillinda** [clearlinux/distribution#1355]
Manually installed drivers (https://github.com/MaxG87/DWA-182_Rev-D1). It installed fine, appears in modules list, but not recognized as network interface. (now using another pci-e wifi card)
https://pastebin.com/7nQ1PKCm - nmcli, lsusb, dmesg outputs

**Comment by miguelinux** [comment]
Did you install them using the  `kernel-native-dkms` bundle?

**Comment by kirillinda** [comment]
Yes
