### ISSUE TITLE
[BBT][perl-extras]missing SplitStatement module

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1358]
In build 31310, we have 4 errors in perl-extras bundle. looks like SplitStatement is missing.

 This is the errors
` (in test file bat-perl-extras-perl-use_parallel.t, line 1846)
perl  -MDBIx::Class::DeploymentHandler -e 1 failed with status 2
 Can't locate SQL/SplitStatement.pm in @INC (you may need to install the SQL::SplitStatement module) (@INC contains: /usr/local/lib/perl5/site_perl/5.28.2/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.28.2 /usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.28.2 /usr/lib/perl5/5.28.2/x86_64-linux-thread-multi /usr/lib/perl5/5.28.2) at /usr/lib/perl5/vendor_perl/5.28.2/DBIx/Class/DeploymentHandler/DeployMethod/SQL/Translator.pm line 15.
`

This seems to be the root cause

Updated packages:
     perl-DBIx-Class-DeploymentHandler   0.002232-15     -> 0.002233-16   

Changes in package perl-DBIx-Class-DeploymentHandler (from 0.002232-15 to 0.002233-16):
     Arjan van de Ven - perl-DBIx-Class-DeploymentHandler: Autospec creation for version 0.002233

**Comment by ahkok** [comment]
Fixed by `perl-DBIx-Class-DeploymentHandler: Autospec creation for version 0.002233`
