### ISSUE TITLE
Tensorflow and tensorflow_probability are outdated

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1359]
Hi,
The latest tensorflow is 2.0, and tensorflow probability is 0.8. Tensorflow 1.X are under maintainance, but new features will not be add to tensorflow 1.x.
The latest pytorch is 1.3. 
Also please consider to include a tensorflow with gpu supported version.

Best
Stokhos

**Comment by bryteise** [comment]
Working on pytorch. I'm not sure about the gpu support however at this point as I haven't looked at that before.
