### ISSUE TITLE
Upgrade Suricata to 5.0 with Rust and eBPF

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#1360]
Hey,

the new Suricata 5.0 has just been released with all the XDP/eBPF/Rust goodness.

Let's have this goodness enabled, shall we?

It looks like there are some changes to the build process in order to have eBPF working correctly

https://suricata.readthedocs.io/en/suricata-4.1.5/capture-hardware/ebpf-xdp.html

CC=clang ./configure --enable-ebpf --enable-ebpf-build

**Comment by bryteise** [comment]
Looks like @fenrus75 already updated this one. I don't see any changes to configure for the ebpf support though so I'll poke it.

**Comment by mdhorn** [comment]
5.0.0 added to Clear Linux OS release 31350.
The latest update to 6.0.0 in Clear Linux OS release 33850
