### ISSUE TITLE
Neovim "stack smashing detected"

### ISSUE THREAD

**Issue by Resonious** [clearlinux/distribution#1362]
Running `nvim` always results in the following output:
```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

Here's my current `swupd check-update` output:
```
$ swupd check-update
Current OS version: 31310
Latest server version: 31310
There are no updates available
```

I haven't looked into the problem in detail, but it might be related to https://github.com/neovim/neovim/issues/9498. [blueyed](https://github.com/blueyed) on that thread says
> Yes, libvterm1 is not compatible with nvim < 0.4, and libvterm0 not with nvim >= 0.4.

I'm not sure how to get the current versions of my installed packages with `swupd`, so I don't know if that's the exact issue or not.

My workaround for now is to use [the official AppImage](https://github.com/neovim/neovim/releases/tag/v0.4.2).

**Comment by phmccarty** [comment]
Thanks for the report. libvterm was moved to 0.1.2 tarball instead of the bzr snapshot, which I think is newer than 0.1.2. I am investigating.

**Comment by phmccarty** [comment]
Yep, I've confirmed that the libvterm package version change broke neovim. The fix is integrated and will be available a couple builds from now.

**Comment by ahkok** [comment]
`neovim-0.4.2-4` `libvterm-0.1.2-5`
