### ISSUE TITLE
Please enable vmmouse module for better vm mouse support

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#1364]
Please enable `CONFIG_MOUSE_PS2_VMMOUSE` in the native and lts kernels for enhanced vm host-guest mouse support. 

See for context:

https://community.clearlinux.org/t/must-use-ctrl-alt-to-free-mouse-from-vmware-console/1853?u=puneetse

**Comment by ahkok** [comment]
Why not in the `-kvm` kernel?

**Comment by ahkok** [comment]
Ah, I see, VMware.

**Comment by puneetse** [comment]
KVM kernel might be a good candidate too. The description does say QEMU too.

**Comment by puneetse** [comment]
Also ran across this: https://github.com/vmware/open-vm-tools/issues/335

**Comment by miguelinux** [comment]
The change will be on the next public release
