### ISSUE TITLE
[BBT][os-clr-on-clr-dev_any-bundle]: pip3check failed

### ISSUE THREAD

**Issue by sleonbau** [clearlinux/distribution#1365]
In build 31320, we have pip3check fail, this is the error:

```
# (in test file pip.t, line 13)
#   `pip3 check' failed
# pip3 is /usr/bin/pip3
# jsonschema 3.1.1 requires pyrsistent, which is not installed.
```

**Comment by phmccarty** [comment]
@sleonbau This issue confuses me, because `jsonschema` depends on `pyrsistent` at runtime...

**Comment by phmccarty** [comment]
@sleonbau I just tested this on my development system, and I cannot reproduce.

**Comment by sleonbau** [comment]
This issue is not present anymore
