### ISSUE TITLE
fakeroot fails with error regarding libfakeroot.so

### ISSUE THREAD

**Issue by jeremiah** [clearlinux/distribution#1367]
After installing the bundle for fakeroot, running the binary leads to;
`fakeroot: preload library `libfakeroot.so' not found, aborting.`

**Comment by ahkok** [comment]
Oh hey, long time no see! I'll poke at it a bit

**Comment by ahkok** [comment]
`fakeroot-1.23-5` - simple packaging error. Should be in a release in 1-2 working days.

**Comment by jeremiah** [comment]
Awesome - thanks!
