### ISSUE TITLE
Consider disabling LLDP by default

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#1368]
The lldpd and systemd-networkd daemons have this nasty habit of opening the AF_PACKET RAW socket in some sort of compatibility mode.

A user, not knowing that, will experience a difficult to troubleshoot overhead when doing any kind of network security monitoring / packet sniffing with high-throughput tools like Suricata or Zeek.

The overhead is not represented in the systemd-networkd CPU usage. Packet drops just happen and it is difficult to say why, without reading the kernel code. Actually, it's difficult even after reading it ;)

Could we put a line in documentation, or provide network scripts, with LLDP=off?

**Comment by fenrus75** [comment]
is there any reason to keep this thing on?

**Comment by mpurzynski** [comment]
systemd-networkd or LLDP?

LLDP is mostly useless, unless someone wants to identify what servers are connected to a given switch port, etc.

**Comment by ahkok** [comment]
From the docs, it seems reasonable to turn this off by default. I'll see if we can easily do this.

**Comment by ahkok** [comment]
`systemd-243-267`
