### ISSUE TITLE
Consider switching default netcat from GNU Netcat to nmap-netcat or netcat-openbsd

### ISSUE THREAD

**Issue by oranenj** [clearlinux/distribution#137]
### What is the issue type?

* [x] Bug report
* [x] Enhancement request

### Describe the problem

I suppose this is both an enhancement request and a bug report.

the current version of netcat used in Clear Linux is GNU Netcat, which unfortunately is very old and lacks many useful features. In particular, it lacks UNIX socket support (`-U`), which virt-manager and virsh happen to rely on for remote connections to a libvirtd hosted on Clear Linux.

Both nmap's version of netcat (https://nmap.org/download.html) and the version ported from OpenBSD (see eg. https://packages.debian.org/sid/netcat-openbsd) provide this flag and would be suitable replacements. In addition on a cursory glance nmap's netcat appears to be fully backwards compatible.

**Comment by oranenj** [comment]
I'm currently figuring out how to build nmap-netcat for Clear Linux.

My initial quick and dirty attempt shows some success after disabling some optional features, though it seems building nmap along with the ncat binary is not optional, and I do not know how to instruct autospec to split it into multiple packages. I suppose simply excluding the extra files would suffice

**Comment by fenrus75** [comment]
we more or less use socat for this; the nmap side of things is a bit
complex to include from a non-technical angle

**Comment by oranenj** [comment]
I managed to build ncat, but if there are non-technical concerns (Licensing?) I confess my ignorance.

I suppose libvirt could be patched to use socat as well, or the OpenBSD version could be used.

The logic in libvirt is not very flexible: https://github.com/libvirt/libvirt/blob/3ad77f853230f870efa396636e008292c7f2b1c0/src/rpc/virnetclient.c#L604

**Comment by oranenj** [comment]
Turns out that libvirt supports configuring the path to the remote netcat binary in the connection URI, so for my usecase (accessing libvirt via virt-manager) I was able to work around this issue by creating a wrapper for socat like so:
```
#!/bin/sh
if [ "$1" = "-q" ]; then
	exit 0
fi
exec socat STDIO "UNIX-CONNECT:$2"
```
It might still be worth switching to another netcat so that other people can avoid this issue when using libvirt.

**Comment by ahkok** [comment]
ncat is now bundled. Please adjust your scripts :)
