### ISSUE TITLE
Include NetworkManager-L2TP 

### ISSUE THREAD

**Issue by Ralim** [clearlinux/distribution#1372]
Hey :wave:,
Would it be possible to include "network-manager-l2tp" addon for Networkmanager and deps.
Have not been able to setup a more common IPSec VPN under Clear Linux.

Would extremely useful to have this out of the box.

**Comment by bryteise** [comment]
This https://github.com/nm-l2tp/NetworkManager-l2tp?

**Comment by Ralim** [comment]
Yeah I believe that's it, I've been mostly using it in Ubuntu/Pop/Mint. Once setup makes setting up IPSec to non-cisco stuff much easier (such as Unifi or Meraki networks)

**Comment by bryteise** [comment]
So they have this note on their repo:
```DO NOT PROVIDE PRE-BUILT BINARIES OF THIS RELEASE UNTIL THE INTENDED LINUX DISTRIBUTION SHIPS WITH OPENSSL 3.0.0 OR LATER THAT IS COMPATIBLE WITH THE GPLv2 LICENSE. But the source code will build with OpenSSL 1.1.0 and later.```

I would say that we can't ship it at this point but once the openssl upgrade happens we can take a look again.

**Comment by Ralim** [comment]
Yeah okay thats fair enough :smile: 
Just wish it was easier to get IPSec up on clear-linux

**Comment by ahkok** [comment]
Blocked until `openssl-3.0.0`

**Comment by dkosovic** [comment]
Other Linux distributions are using NetworkManage-l2tpr-1.2.x from the` nm-1-2` branch which hosts the stable releases :
* https://github.com/nm-l2tp/NetworkManager-l2tp/tree/nm-1-2

The `master` branch currently hosts the unstable version which builds with OpenSSL 1.1.0 and later, but for GPLv2/OpenSSL licensing issues, requires OpenSSL 3.0 or later for shipping binary releases of the package.

You'll notice on the following page, NetworkManager-l2tp 1.2.14 was released a couple of weeks ago:
* https://github.com/nm-l2tp/NetworkManager-l2tp/releases

NetworkManager-l2tp 1.2.14 currently ships with (or within the next few days) Fedora, EPEL, OpenSUSE, Debian Sid, ArchLinux and possibly others.

**Comment by ahkok** [comment]
@dkosovic always great to hear from upstream. Thanks for clarifying - we certainly had missed the branch.

**Comment by ahkok** [comment]
The `NetworkManager-extras` bundle will have this available in 1-2 working days.
