### ISSUE TITLE
Custom AVX512 autospec build of Mariadb and postgres fail

### ISSUE THREAD

**Issue by LiuBijun** [clearlinux/distribution#1373]
OS: Clear Linux 31300
After I modify the option.conf file to enable avx512 (set use_avx512 = true), I run 'make autospec'.
It outputs error logs.
_**Unknown pattern match:  Java
Unknown pattern match:  JNI

total tests: 0
total passing: 0
[FATAL] Build failed, aborting
make: *** [../common/Makefile.common:165: autospec] Error 1**_

**Comment by ahkok** [comment]
Those messages are unrelated, and not the actual compile error.

You need to inspect `results/build.log` and possible other log files to determine the actual error.

**Comment by ahkok** [comment]
Note: enabling avx512 through autospec for packages in clearlinux is "experimental" at best. Many programs or software will not compile and need special patches before this will actually work. You've likely stumbled upon these by chance, and this may just not work.

**Comment by LiuBijun** [comment]
Mariadb can build successfully with AVX512 now. But postgresql11 still failed.
The log of results/build.log is attached. Please help to check.
[build-postgresql11.log](https://github.com/clearlinux/distribution/files/3753760/build-postgresql11.log)

**Comment by qzheng527** [comment]
Please try echo "perl(Time::HiRes)" >> buildreq_add then "make autospec" again.

**Comment by LiuBijun** [comment]
Build successfully after doing this step ""echo "perl(Test::More)" >> buildreq_add "" .

**Comment by bwarden** [comment]
Note that we've updated `autospec` to catch these requirements now:
https://github.com/clearlinux/autospec/pull/506
