### ISSUE TITLE
How to enable all animation in gnome?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1376]
I am missing all those smooth transition and animation of gnome.

How can i enable them in clear linux?

**Comment by mrkz** [comment]
We have [disabled animations](https://github.com/clearlinux/clr-desktop-defaults/commit/1e1220293982a3900b88dc054f2c9f100a1d1132) recently (when we moved to GNOME 3.34 really).

If you want animations back, just open **gnome tweaks** and click the **Animations** toggle button in the general tab.

![gnome-tweak-window](https://user-images.githubusercontent.com/978752/67105396-50842b80-f18e-11e9-8073-42376e9576f1.png)
