### ISSUE TITLE
Add an issue message to the PXE image warning installation in progress and not to interrupt

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#1379]
I think it would be nice to add an issue message to the PXE image that states:

"PXE installation of Clear Linux in progress and will reboot automatically when completed.  Please do not interrupt."

**Comment by ahkok** [comment]
Do these installer/image issues need to move to a different project?

**Comment by bktan8** [comment]
There isn't a "PXE" project.  Do you think one should be created?

**Comment by mdhorn** [comment]
This was address by our DevOps in the image generate already. The following message is already added to the /etc/issue file

```
PXE installation of Clear Linux in progress and will reboot
automatically when completed. Please do not interrupt.
```
