### ISSUE TITLE
Firefox Sandbox breaks Mesa rendering

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#138]
We use GitHub issues for bug reports and enhancement requests.
If you have a troubleshooting issue or have questions, please write to our
mailing list: dev@lists.clearlinux.org. You can also find helpful folks on our
IRC channel: #clearlinux on irc.freenode.net.

------------------------

### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

Using Firefox 61.0.1 or Firefox-nightly on Clear Linux with the following GFX test sites results in WebGL failing to load the Mesa driver and no hardware rendering

MOZ_SANDBOX_LOGGING=1 firefox http://webglreport.com/?v=2
MOZ_SANDBOX_LOGGING=1 firefox http://webglsamples.org/aquarium/aquarium.html

In looking at the logs in essentially both cases for both FIrefox 61.0.1 and Firefox-nightly I see the following consistent /sys/ path being blocked (skip to the end for further comments by me):

Sandbox: using seccomp tsync
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0
path=/home/seanvk/.drirc for pid=9987
Sandbox: Failed errno -13 op open flags 00 path /home/seanvk/.drirc
Sandbox: Recording mapping /sys/bus/pci ->
/sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/bus/pci ->
/sys/dev/char/226:0/device/subsystem
Sandbox: SandboxBroker: denied op=stat rflags=400000 perms=0 path=/sys
for pid=9987
Sandbox: Failed errno -13 op stat flags 0400000 path /sys

The root cause is a change in libdrm which is not anticipated by Firefox's sandbox:

Libdrm update to 2.4.93 

https://cgit.freedesktop.org/mesa/drm/commit/?id=a02900133b32dd4a7d6da4966f455ab337e80dfc

" In other words, instead opening the /sys/dev/char/*/device symlink, we opt for the actual /sys/devices/pci*/*/"

The offending line is this call which fails with errno 13 "permission denied" for path /sys/:

https://gitlab.freedesktop.org/mesa/drm/blob/87fdbfb62fb3de6759d465d07cc13f922084694e/xf86drm.c#L3007

Symlink input path of /sys/dev/char/226:128/device:
/sys/dev/char/226:128/device -> ../../../0000:00:02.0/ and that realpath() is 
supposed to resolve to /sys/devices/pci0000:00/0000:00:02.0/
and that doesn't complete.

**Comment by seanvk** [comment]
Blocked by: https://bugzilla.mozilla.org/show_bug.cgi?id=1480755
Please use the above bug to track resolution of this Clear issue.

Thanks,

Sean

**Comment by OpenSourceAnarchist** [comment]
From the link, it appears the issue has been resolved and will be included in Firefox 63. As a workaround until then, users can add this custom string variable to about:config to fix the issue:
security.sandbox.content.read_path_whitelist;/sys/

**Comment by mrkz** [comment]
@seanvk having CLR 25010 with firefox 62.0 this is part of the output I get from running

`$ MOZ_SANDBOX_LOGGING=1 firefox http://webglsamples.org/aquarium/aquarium.html`
```
[...]
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:128/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:128/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Failed errno -2 op open flags 00 path /usr/share/mesa/drirc
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0 path=/home/mesiment/.drirc for pid=13007
Sandbox: Failed errno -13 op open flags 00 path /home/mesiment/.drirc
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:128/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Failed errno -2 op open flags 02000000 path /usr/lib64/dri/tls/i965_dri.so
Sandbox: Failed errno -2 op open flags 00 path /usr/share/mesa/drirc
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0 path=/home/mesiment/.drirc for pid=13007
Sandbox: Failed errno -13 op open flags 00 path /home/mesiment/.drirc
Sandbox: Failed errno -2 op open flags 00 path /usr/share/mesa/drirc
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0 path=/home/mesiment/.drirc for pid=13007
Sandbox: Failed errno -13 op open flags 00 path /home/mesiment/.drirc
Sandbox: Failed errno -2 op stat flags 00 path /tmp/Temp-100c1b19-a9ad-43e7-8a2f-a700dcc50240/mesa_shader_cache
Sandbox: Failed errno -2 op open flags 00 path /usr/share/mesa/drirc
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0 path=/home/mesiment/.drirc for pid=13007
Sandbox: Failed errno -13 op open flags 00 path /home/mesiment/.drirc
[...]
```

Also, notice that the [bug you mentioned](https://bugzilla.mozilla.org/show_bug.cgi?id=1480755) for tracking and closing this issue is marked as **RESOLVED FIXED in Firefox 62**

So I guess we can close this now?

**Comment by AthenasJimenez** [comment]
@seanvk running on release 25770 with firefox version 62.0.3. I can't see the error with path=/sys anymore. 

`
[...]
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:128/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:0/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/card0 -> /sys/dev/char/226:0
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/card0/device
Sandbox: Recording mapping /sys/bus/pci -> /sys/dev/char/226:128/device/subsystem
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128 -> /sys/dev/char/226:128
Sandbox: Recording mapping /sys/devices/pci0000:00/0000:00:02.0 -> /sys/devices/pci0000:00/0000:00:02.0/drm/renderD128/device
Sandbox: Failed errno -2 op open flags 00 path /usr/share/mesa/drirc
Sandbox: SandboxBroker: denied op=open rflags=0 perms=0 path=/home/anaidaji/.drirc for pid=24893
Sandbox: Failed errno -13 op open flags 00 path /home/anaidaji/.drirc
[...]
`

May we close the issue?

**Comment by seanvk** [comment]
@AthenasJimenez Looks fixed to me.  Yes I think we can close it.
