### ISSUE TITLE
Output PXE installation progress to standard out so you can watch the progress

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#1380]
Instead of having to log and tail the installation log file, I think it would be nice to display the progress to standard output.  A copy of the progress should be written to a log as well though.

**Comment by mdhorn** [comment]
@bktan8 I believe this is addressed by the latest release of the clr-installer service.
As long as the [console is set on the kernel command line as noted in the service file](https://github.com/clearlinux/clr-installer/blob/master/etc/systemd/clr-installer-provision.service#L8), the progress of the installation is display on the console.

**Comment by bktan8** [comment]
@mdhorn - Yep!  Thank you!
