### ISSUE TITLE
Qalculate! - GTK based calculator

### ISSUE THREAD

**Issue by Ralim** [clearlinux/distribution#1381]
Hi,

It would be very nice to have [Qalculate!](https://qalculate.github.io/index.html) available as a package. 

I have been using it for around two years now and its a very nice calculator replacement, that handles conversions (and units) correctly.

Thanks,
Ralim :smile:

**Comment by ahkok** [comment]
Adding

**Comment by ahkok** [comment]
Bundle name is `qalculate-gtk`. Should be available in 1-2 working days.
