### ISSUE TITLE
akonadi needs to depend on mariadb

### ISSUE THREAD

**Issue by rakuco** [clearlinux/distribution#1382]
I'm booting a Clear KVM image inside a Clear host, and installed the "desktop-kde" and "desktop-kde-apps" bundles.

By default, applications that need Akonadi (such as KMail) fail to work correctly because Akonadi fails to start.

```
$ akonadictl start
[...]
org.kde.pim.akonadiserver: mysqld not found. Please verify your installation
```

**Comment by ahkok** [comment]
Huh

Why would Kmail *require* mysqld? That makes absolutely no sense....

It should default to e.g. `sqlite3` backend instead. Having a desktop app require mariadb is just out of proportion.

**Comment by ahkok** [comment]
I've changed the default to sqlite, which should avoid this problem.

**Comment by ahkok** [comment]
`akonadi-19.08.2-23`

**Comment by thiagomacieira** [comment]
Please undo that and add the `requires_add`. Upstream does not recommend the sqlite backend because sqlite is not powerful enough and has caused corruption in the past.

MySQL ir PostgreSQL is recommended.

**Comment by ahkok** [comment]
I'm not going to make mariadb required

**Comment by ahkok** [comment]
Why make `mariadb` required if it can also work using `postgresql`? People who want postgres likely don't really want mariadb, and vice versa.

Seems like the user needs to choose, or better, we `also-add(mariadb)` at the bundle level instead.

heck, THAT solution would make it possible to use `sqlite` without the need to have `mariadb` nor `postgresql` installed, which IMHO would be preferred.

**Comment by ahkok** [comment]
```
diff --git a/bundles/akonadi b/bundles/akonadi
index e5cbf9a2..4d5ad8f2 100644
--- a/bundles/akonadi
+++ b/bundles/akonadi
@@ -17,6 +17,7 @@ akonadi-mime
 akonadi-notes
 akonadi-search
 akonadiconsole
+also-add(mariadb)
 # end of custom additions
 
 # main package
```

**Comment by thiagomacieira** [comment]
`also-add` is even better, thanks.
