### ISSUE TITLE
Please enable dvisvgm for texlive

### ISSUE THREAD

**Issue by blsz** [clearlinux/distribution#1386]
The texlive package is currently configured with --disable-dvisvgm.  Please consider including dvisvgm.

Many TeX workflows need dvisvgm.  For example, the TexMaths Libreoffice extension needs a dvisvgm binary to render equations in svg. 

Also, tlmgr (texlive manager) does not run.    tlmgr allows the user to install and update thousands of texlive packages.   Is it possible to package a working tlmgr?  If not, then it could be deleted.

**Comment by hnanni** [comment]
Hello @blsz 

Thanks for pointing out the dvisvgm tool. I was not familiar with it and found it really useful/cool. 
I've packaged it and tested on a couple of examples from https://dvisvgm.de/Examples/. Let me know your milleage with it (I think the release 31470 will catch it).

Reg. tlmgr I've changed a couple of bits to have it running and got:

```
$ tlmgr --user-mode install dvisvgm
tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet (not verified: pubkey missing)
Package dvisvgm is not relocatable, cannot install it in user mode!

```
It seems like relevant packages can not be instaled in user mode, and for system wide install, it won't play well with swupd. I think I will remove it

**Comment by bryteise** [comment]
@hnanni I wonder if it would be possible to make tlmgr install to /usr/local or /opt for system wide installs? It does at least produce useful errors when user mode installs would break.

**Comment by hnanni** [comment]
@bryteise Yes, I would like to have tlmgr pointing outside the realms of swupd, but it happens that having it modified to be able to juggle with TEX{DIR|MFLOCAL|MFHOME} vars having several paths assigned to them, is an interesting project by itself.

---
packed texlive is up-to-date.I think I will use tlmgr inside mock is a package not packed by the texlive friends is requested

```
$ tlmgr  --self
tlmgr: package repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet (not verified: pubkey missing)
tlmgr: no self-updates for tlmgr available.

$ tlmgr --list
tlmgr: package repository http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet (not verified: pubkey missing)
tlmgr: no updates available
```

**Comment by blsz** [comment]
Thank you for adding dvisvgm.

Could you require users to run "sudo tlmgr" as a way of simplifying the packaging?

Does the MacTeX method of packaging TeX Live provide any useful methods? 
https://www.tug.org/mactex/What_Is_Installed.pdf
https://tex.stackexchange.com/questions/229265/installing-mactex-multiple-user-accounts

**Comment by lebensterben** [comment]
It's best if tlmgr works normally in usermode. But if we have to install LaTeX packages globally, it seems that tlmgr install them in a directory two levels up from itself, which is the 'realm of swupd'. And there's no way to configure it.

This problem also applies to 'pip' and 'npm' when installing packages globally. It's best if swupd can be more smart that it allow users to opt out the packages managed by other package managers.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bryteise** [comment]
The difficulty we have is we need to teach python and npm to use the alternate content paths. I believe we did this for perl already. Likely R has similar problems. npm and pip do handle user installs reasonably at least.

**Comment by lebensterben** [comment]
> The difficulty we have is we need to teach python and npm to use the alternate content paths. I believe we did this for perl already. Likely R has similar problems. npm and pip do handle user installs reasonably at least.

This reminds me of macOS Catalina's new dedicated system volume, that system files are separated on a read-only partition, and user content's are located on a data partition. But their filesystem API makes programs and users to believe that it's just a single partition. Maybe this is hard to implement, but it seems to me like a way to solve our problem, that if we cannot teach other package manager to use alternate content paths, we make an alternative path but make them believe they're using the right one...
