### ISSUE TITLE
Consider adding ghostscript to hardware-printing bundle

### ISSUE THREAD

**Issue by jquagga** [clearlinux/distribution#1388]
Good day,

As part of my transition of my home server to Clear, I set up cups with the hardware-printing bundle.  I use it to print to a postscript printer historically that's not be a problem.  However on Clear, it seems ghostscript isn't included in the hardware-printing bundle and appears to only be included in fairly large bundles I wouldn't normally install on a server (like say "desktop").  

I even tried to use the gutenprint drivers which are included in hardware-printing, but those also seem to fail as they seem to want functions ghostscript performs in order to print to this printer (a Samsung ML-2850ND if it matters).  This would only seem to impact "print servers" as anyone with the desktop bundle installed would probably work fine.  In the interim, I've built a docker image for cups which is working nicely to fill the gap but I figure I'd pass this suggestion on.

**Comment by ahkok** [comment]
Done. It'll pull in X11 though, but, it's removable as well.
