### ISSUE TITLE
Please include Intel software for measuring cache efficiency

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#1391]
https://github.com/intel/intel-cmt-cat/

This software package provides basic support for
Intel(R) Resource Director Technology (Intel(R) RDT) including:
Cache Monitoring Technology (CMT), Memory Bandwidth Monitoring (MBM),
Cache Allocation Technology (CAT), Code and Data Prioritization (CDP)
and Memory Bandwidth Allocation (MBA).

**Comment by ZhongbaoShi** [comment]
It's available, https://github.com/clearlinux-pkgs/intel-cmt-cat

**Comment by mpurzynski** [comment]
Yes indeed! Thanks for pointing that out, I added it to the local mix and successfully installed on servers.
