### ISSUE TITLE
add intel-ipsec-mb

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1394]
I want to run `stress-ng --ipsec-mb N` but it errors:
`stress-ng: info:  [73821] ipsec_mb stressor will be skipped, CPU needs to be an x86-64 and a recent IPSEC MB library is required.`

Can we get https://github.com/intel/intel-ipsec-mb ?

**Comment by fenrus75** [comment]
done

sadly the makefile of that guy is !#$@#$@#$#@ bad but not a surprise given
the prefix of the github url

**Comment by ColinIanKing** [comment]
Thank you for your positive comment about my Makefile.

**Comment by mythi** [comment]
@ColinIanKing `stress-ng` should be fine. intel-ipsec-mb had issues AFAICS.

The package is now added, closing.
