### ISSUE TITLE
Mouse scrolls in the opposite direction of the trackpad.

### ISSUE THREAD

**Issue by gorakhargosh** [clearlinux/distribution#1398]
If I turn on Natural scrolling, the trackpad on my keyboard scrolls in the reverse direction
of natural scrolling on the mouse. If I turn it off for the mouse, the trackpad again reverses direction.

I'm not sure, but shouldn't these two be scrolling in the same direction or perhaps can an option be presented to make them behave the same way? This is kind of confusing for people new to Linux.

**Comment by ahkok** [comment]
This is how upstream defines the behavior, and I must say I'm personally not a fan. There are some extensions to address this, since other users have experienced similar issues. I'm not sure what we can do about this other than ask you to consider filing an upstream bugreport.

**Comment by gorakhargosh** [comment]
I see. I don't mind filing an upstream bug report. Could you please point me in the right direction?

**Comment by mrkz** [comment]
@gorakhargosh You could report this issue at https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas/. I'm closing this issue now so we can follow-up there instead.
