### ISSUE TITLE
Allow 'swupd' to run without root access for simple operation

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/distribution#14]
Some operations such as `search`, `bundle-list` and possibly `check-update` should not need root access to be run. Today running those without root access returns an error:

```
swupd check-update 
swupd-client software update checker 3.14.6
   Copyright (C) 2012-2017 Intel Corporation

This program must be run as root..aborting.
```

**Comment by ahkok** [comment]
This is not the correct location for this bug. Swupd has it's own github project and this issue should be moved, but github doesn't allow moving issues. Please reopen the issue here:

https://github.com/clearlinux/swupd-client/issues

**Comment by ahkok** [comment]
FWIW, the reason it needs `root` privileges is because it needs to manipulate files in the spool folders. It's a known issue, and there is no good solution available.

**Comment by gvancuts** [comment]
Thanks @ahkok , I have filed https://github.com/clearlinux/swupd-client/issues/398 to track this.

It's not a high-priority item and thanks for explaining why it cannot be solved easily. I would consider this a low-priority feature request.
