### ISSUE TITLE
systemd-hwdb spamming the journal

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#140]
### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

Recently, I noticed systemd-hwdb has been logging excessively to the journal (roughly 6900 times per software update). Log lines look like this:

```
systemd-hwdb[451]: /usr/lib/udev/hwdb.d/20-pci-vendor-model.hwdb:6: Property expected, ignoring record with no properties
systemd-hwdb[451]: /usr/lib/udev/hwdb.d/20-pci-vendor-model.hwdb:9: Property expected, ignoring record with no properties
systemd-hwdb[451]: /usr/lib/udev/hwdb.d/20-pci-vendor-model.hwdb:12: Property expected, ignoring record with no properties
systemd-hwdb[451]: /usr/lib/udev/hwdb.d/20-pci-vendor-model.hwdb:15: Property expected, ignoring record with no properties
...
```

**Comment by ahkok** [comment]
yuck.

**Comment by ahkok** [comment]
We should just remove this file entirely, I believe it's entirely unused at this point.

**Comment by phmccarty** [comment]
I am still seeing the journal spam, so I believe this issue is not resolved yet.

**Comment by iphutch** [comment]
@ahkok has since re-fixed. re-closing.
