### ISSUE TITLE
9 Missing modules after update for perl-basic

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1400]
In build 31400, we have 22 new regression in perl-basic bundle, they are relate to these missing modules

1. POE
2. Reply
3. AnyEvent
4. Coro
5. DBI
6. DateTime
7. Event
8. Irssi
9. Params

This is the error

`(in test file bat-perl-basic-perl-use_parallel.t, line 2885)
   perl  -MIO::Async::Stream -e 1' failed with status 2
 Can't locate Future.pm in @INC (you may need to install the Future module) (@INC contains: /usr/local/lib/perl5/site_perl/5.28.2/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.28.2 /usr/lib/perl5/vendor_perl/5.28.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.28.2 /usr/lib/perl5/5.28.2/x86_64-linux-thread-multi /usr/lib/perl5/5.28.2) at /usr/lib/perl5/vendor_perl/5.28.2/IO/Async/Notifier.pm line 16.
 BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/5.28.2/IO/Async/Notifier.pm line 16.
 Compilation failed in require at /usr/lib/perl5/5.28.2/base.pm line 137.
 	...propagated at /usr/lib/perl5/5.28.2/base.pm line 159.
 BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/5.28.2/IO/Async/Handle.pm line 10.
 Compilation failed in require at /usr/lib/perl5/5.28.2/base.pm line 137.
 	...propagated at /usr/lib/perl5/5.28.2/base.pm line 159.
 BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/5.28.2/IO/Async/Stream.pm line 13.
 Compilation failed in require.
 BEGIN failed--compilation aborted.`

This seems to be the root cause
`Updated packages:
     perl-B-COW                          0.001-1         -> 0.001-2        
     perl-Clone                          0.43-16         -> 0.43-17        
     perl-DateTime-Format-Flexible       0.32-2          -> 0.32-3         
     perl-DateTime-Format-ISO8601        0.08-1          -> 0.08-2         
     perl-HTTP-Cookies                   6.04-26         -> 6.05-28        
     perl-IO-Async                       0.74-15         -> 0.74-16        
     perl-Net-IP                         1.26-1          -> 1.26-2         
     perl-Net-SSLeay                     1.88-49         -> 1.88-50        
     perl-NetAddr-IP                     4.079-10        -> 4.079-11       
     perl-Test-MockModule                0.170.0-13      -> 0.171.0-15     
     perl-XML-Feed                       0.59-17         -> 0.59-18        
     perl-XML-LibXML                     2.0134-13       -> 2.0201-15      
     perl-libwww-perl                    6.39-43         -> 6.40-45        

Changes in package perl-B-COW (from 0.001-1 to 0.001-2):
     Brett T. Warden - perl-B-COW: Autospec creation for version 0.001

Changes in package perl-Clone (from 0.43-16 to 0.43-17):
     Brett T. Warden - perl-Clone: Autospec creation for version 0.43

Changes in package perl-DateTime-Format-Flexible (from 0.32-2 to 0.32-3):
     Brett T. Warden - perl-DateTime-Format-Flexible: Autospec creation for version 0.32

Changes in package perl-DateTime-Format-ISO8601 (from 0.08-1 to 0.08-2):
     Brett T. Warden - perl-DateTime-Format-ISO8601: Autospec creation for version 0.08

Changes in package perl-HTTP-Cookies (from 6.04-26 to 6.05-28):
     Brett T. Warden - perl-HTTP-Cookies: Autospec creation for version 6.05
     Brett T. Warden - perl-HTTP-Cookies: Autospec creation for update from version 6.04 to version 6.05

Changes in package perl-IO-Async (from 0.74-15 to 0.74-16):
     Brett T. Warden - perl-IO-Async: Autospec creation for version 0.74

Changes in package perl-Net-IP (from 1.26-1 to 1.26-2):
     Brett T. Warden - perl-Net-IP: Autospec creation for version 1.26

Changes in package perl-Net-SSLeay (from 1.88-49 to 1.88-50):
     Brett T. Warden - perl-Net-SSLeay: Autospec creation for version 1.88
     Patrick McCarty - odd is devel

Changes in package perl-NetAddr-IP (from 4.079-10 to 4.079-11):
     Brett T. Warden - perl-NetAddr-IP: Autospec creation for version 4.079

Changes in package perl-Test-MockModule (from 0.170.0-13 to 0.171.0-15):
     Brett T. Warden - perl-Test-MockModule: Autospec creation for version 0.171.0
     Brett T. Warden - perl-Test-MockModule: Autospec creation for version 0.171.0

Changes in package perl-XML-Feed (from 0.59-17 to 0.59-18):
     Brett T. Warden - perl-XML-Feed: Autospec creation for version 0.59

Changes in package perl-XML-LibXML (from 2.0134-13 to 2.0201-15):
     Brett T. Warden - perl-XML-LibXML: Autospec creation for version 2.0201
     Brett T. Warden - perl-XML-LibXML: Autospec creation for update from version 2.0134 to version 2.0201

Changes in package perl-libwww-perl (from 6.39-43 to 6.40-45):
     Brett T. Warden - perl-libwww-perl: Autospec creation for version 6.40
     Brett T. Warden - perl-libwww-perl: Autospec creation for update from version 6.39 to version 6.40`

**Comment by bwarden** [comment]
Resolving runtime Perl deps is an ongoing project.
