### ISSUE TITLE
nodejs returns a warning with default configuration

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1401]
In build 31400, we have a warning with the fault configuration for node-js

This is the error
` (in test file bat-nodejs-basic.t, line 44)
   [ "$count" == "1" ]     failed
 /home/clear/BBT/src/bat-nodejs-basic /home/clear/BBT/bundles/nodejs-basic
 Hugepages WARNING: failed to find text region
 Reverting to default page size
 v12.13.0`

This seems to be the root cause
 Updated packages:
     nodejs                              10.16.3-84      -> 12.13.0-85     
	 
 Changes in package nodejs (from 10.16.3-84 to 12.13.0-85):
     William Douglas - nodejs: Autospec creation for version 12.13.0

**Comment by Tornado-Tim** [comment]
Yup also having this issue.

**Comment by V-H-R-Oliveira** [comment]
Same issue here: 
 node --version
Hugepages WARNING: failed to find text region
Reverting to default page size
v12.13.0

**Comment by SPAstef** [comment]
Same here

**Comment by bryteise** [comment]
This is intentional. As far as I can tell, nodejs doesn't really support the use of THP which Clear Linux uses by default. We are looking into if that is the right choice for the OS but for now the warning is a side-effect of that choice.

**Comment by Tornado-Tim** [comment]
Problem though is that error does not allow npm to run.

**Comment by bryteise** [comment]
@Tornado-Tim Can you open a bug for that? I don't see failures for npm on 31440 for the few things I tried.

**Comment by SPAstef** [comment]
> @Tornado-Tim Can you open a bug for that? I don't see failures for npm on 31440 for the few things I tried.

I had problems with neovim, basically the plug-in doesent work (error on opening and when running checkhealth)

**Comment by lebensterben** [comment]
> > @Tornado-Tim Can you open a bug for that? I don't see failures for npm on 31440 for the few things I tried.
> 
> I had problems with neovim, basically the plug-in doesent work (error on opening and when running checkhealth)

What error do you see in the result of `:checkhealth`?

**Comment by SPAstef** [comment]
![immagine](https://user-images.githubusercontent.com/9153046/67975234-041bff80-fc14-11e9-853a-5d7743ca98ac.png)
Actually it is a warning, not an error, but still is pretty annoying to see it everytime nvim starts

**Comment by lebensterben** [comment]
>![immagine](https://user-images.githubusercontent.com/9153046/67975234-041bff80-fc14-11e9-853a-5d7743ca98ac.png) ...

@SPAstef I see. This is exactly related to this issue. But fortunately not many plugins require Nodejs in neovim I suppose.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SPAstef** [comment]
> > ![immagine](https://user-images.githubusercontent.com/9153046/67975234-041bff80-fc14-11e9-853a-5d7743ca98ac.png) ...
> 
> @SPAstef I see. This is exactly related to this issue. But fortunately not many plugins require Nodejs in neovim I suppose.
> 
> Sent with [GitHawk](http://githawk.com)

No no they all do work. I thought at first they didn't, but this message seems to be just an annoying warning, everything still works, just every time you open neovim this message pops up in the command prompt.
