### ISSUE TITLE
gnome file index doesnot index my ntfs volume.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1407]
![image](https://user-images.githubusercontent.com/12841320/67647130-34844500-f959-11e9-9418-c1996e1ae2b2.png)

gnome search fails to show any file from ntfs volume. (from activities search)

/dev/sda8 is automounted on bootup (/etc/fstab)

**Comment by ahkok** [comment]
I doubt clearlinux changed anything relevant - this is likely an upstream bugreport. It may be interesting to ask upstream if they know about this. @mrkz

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/80197624-97bc0f00-863e-11ea-94a7-0bb97d90aa4c.png)

even bookmarks from ntfs volume is not searched

**Comment by nazar2sfive** [comment]
mount NTFS volume in $HOME/mount_dir. 

Add directory /media/4416017316016770 in gsettings org.freedesktop.Tracker.Miner.Files index-recursive-directories. You could use dconf-editor (install it if you don't have it), navigate to org.freedesktop.Tracker.Miner.Files, and modify key index-recursive-directories. My current value is ['&DESKTOP', '&DOCUMENTS', '&DOWNLOAD', '&MUSIC', '&PICTURES', '&VIDEOS', '**/home/user/windowsmount'** , '/bin'] (I have added also /bin to test the difference between adding a directory in the same drive and a different drive).

![image](https://user-images.githubusercontent.com/12841320/81266214-1ca62000-9064-11ea-951e-9e3ef77910b9.png)
`
sudo swupd bundle-add tracker-miners`

    Stop and start the daemons.
```

$ tracker daemon -t
$ tracker daemon -s
```

    Make sure indexing finished with
`
$ tracker daemon -f`
