### ISSUE TITLE
OpenVINO for Deep Learning failed on model optimizer

### ISSUE THREAD

**Issue by AmmarZolkipli** [clearlinux/distribution#1409]
I was going through the OpenVINO for Deep Learning tutorial at https://docs.01.org/clearlinux/latest/tutorials/openvino.html

On the step to convert the model, "python3 /usr/share/openvino/model-optimizer/mo.py --input_model squeezenet1.1.caffemodel" , the script gave out a bunch of error outputs below:

[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'Graph' object has no attribute 'node'
[ ERROR ]  Traceback (most recent call last):
  File "/usr/share/openvino/model-optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "/usr/share/openvino/model-optimizer/mo/main.py", line 261, in driver
    custom_layers_mapping_path=custom_layers_mapping_path)
  File "/usr/share/openvino/model-optimizer/mo/pipeline/caffe.py", line 63, in driver
    graph, original_shapes = loader.caffe_pb_to_nx(proto, model)
  File "/usr/share/openvino/model-optimizer/mo/front/caffe/loader.py", line 294, in caffe_pb_to_nx
    graph.add_node(layer.name, pb=layer, model_pb=model_layer, kind='op', type='Parameter')
  File "/usr/share/openvino/model-optimizer/mo/graph/graph.py", line 499, in add_node
    node.update_node()
  File "/usr/share/openvino/model-optimizer/mo/graph/graph.py", line 464, in update_node
    in_ports_count = self.in_ports_count if self.has_valid('in_ports_count') else None
  File "/usr/share/openvino/model-optimizer/mo/graph/graph.py", line 155, in has_valid
    return self.has(k) and not self.graph.node[self.node][k] is None
  File "/usr/share/openvino/model-optimizer/mo/graph/graph.py", line 152, in has
    return k in self.graph.node[self.node]
AttributeError: 'Graph' object has no attribute 'node'

[ ERROR ]  ---------------- END OF BUG REPORT --------------

**Comment by bryteise** [comment]
@AmmarZolkipli This looks like an upstream bug as far as I can tell.

**Comment by bwarden** [comment]
Might be https://github.com/opencv/dldt/issues/294

**Comment by AmmarZolkipli** [comment]
Yep. The pip install fixed the issue. Please consider to put it in the bundle, as it's used in the official clear tutorial.

**Comment by thiagomacieira** [comment]
Did you install 2.3 as the dldt issue suggested, or the networkx from Clear (which is version 2.4, see https://github.com/clearlinux-pkgs/networkx). If you installed the latter, then we can add the necessary dependencies to the bundle.

If you didn't, can someone test networkx==2.4?

**Comment by thiagomacieira** [comment]
https://github.com/opencv/dldt/issues/289 says that it's not compatible with 2.4. Therefore, upstream bug.

**Comment by AmmarZolkipli** [comment]
> Did you install 2.3 as the dldt issue suggested, or the networkx from Clear (which is version 2.4, see https://github.com/clearlinux-pkgs/networkx). If you installed the latter, then we can add the necessary dependencies to the bundle.
> 
> If you didn't, can someone test networkx==2.4?

Yes, I installed 2.3. Therefore agree, upstream bug. Need to be fixed.

**Comment by chivakker** [comment]
fwiw, you can also follow their instructions to create a virtual environment /usr/share/openvino/model-optimizer/README.md.

It is also normal to keep virtual environment when this kind of errors happen.  In that environment you can roll back networkx version, or modify their requirements.txt file as well.
