### ISSUE TITLE
How to install feh? Is there any specific bundle?

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#141]
------------------------

### What is the issue type?
Software package missing and trying to install.

* [ ] Bug report
* [ ] Enhancement request

Kindly bundle it to the appropriate place, so an end user can get it.

### Describe the problem
 Not found a suitable bundle to install specific software, in this feh, to install in the system.

**Comment by ahkok** [comment]
```
$ sudo swupd search bin/feh
Searching for 'bin/feh'

Search term not found.
```

`feh` is not packaged by Clear Linux OS.

**Comment by unixbhaskar** [comment]
Yup, I did that search before posting ...

Any chance it will get bundled sometime in the near future??

**Comment by ahkok** [comment]
in progress.

**Comment by ahkok** [comment]
Should be part of the `desktop-i3` bundle within 2 days.

**Comment by unixbhaskar** [comment]
Thanks,, man...will keep an eye on that :)
