### ISSUE TITLE
vlc(flatpak) doesnot save subtitle in clear linux.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1412]
![image](https://user-images.githubusercontent.com/12841320/67774230-13b90e00-fa85-11e9-89ef-3638a6e8347c.png)

**Comment by ahkok** [comment]
Duplicate of upstream:

https://github.com/flathub/org.videolan.VLC/issues/70

**Comment by nazar2sfive** [comment]
@ahkok 
`mkdir ~/.var/app/org.videolan.VLC/cache/vlc`

just above solved problem for me
