### ISSUE TITLE
UPS Support: apcupsd or network-ups-tools

### ISSUE THREAD

**Issue by ghost** [clearlinux/distribution#1414]
Good day,

I think it would be nice for ClearLinux to have a way to communicate / gracefully shutdown when notified by a UPS that the battery / power is about to run out.  Both apcupsd and nut are GPL licensed and both support a variety of UPS (apcupsd supports more than APC ups'es).  They are also potentially network exposed so I know that's a security consideration.  I can make either one work; I just think it would be software people would appreciate having.

**Comment by ahkok** [comment]
I'd love to see this supported. We'll work on a good solution here, but it may take a bit :)

**Comment by KyleSanderson** [comment]
Any update on this one @ahkok ?

**Comment by ahkok** [comment]
I'm inclined to get `nut` to work, but, there's not even a release available that works with `python3`. So this is pretty bad.

**Comment by ahkok** [comment]
Trying to see if a git revision works atm...

**Comment by KyleSanderson** [comment]
Using this (lab machine) until it's upstream and I can remove polling.

```
FROM alpine:3.11.6
RUN apk add --no-cache apcupsd && \
sed -i "s/UPSCABLE smart/UPSCABLE usb/" /etc/apcupsd/apcupsd.conf && \
sed -i "s/UPSTYPE apcsmart/UPSTYPE usb/" /etc/apcupsd/apcupsd.conf && \
sed -i "s/DEVICE/#DEVICE/" /etc/apcupsd/apcupsd.conf && \
sed -i "s/BATTERYLEVEL 5/BATTERYLEVEL 80/" /etc/apcupsd/apcupsd.conf && \
printf "#!/bin/sh\necho 1 | tee -a /tmp/powerfail\n" | tee /etc/apcupsd/doshutdown && \
chmod +x /etc/apcupsd/doshutdown
```

**Comment by bwarden** [comment]
Just to check in, I tried nut again from the current HEAD: https://github.com/networkupstools/nut/commit/3d88a972774f23f3567ed3696745794187e9fa59
As expected, it still has a lot of issues, including depending on libusb-0.1, that preclude packaging it.

**Comment by bwarden** [comment]
Packaged and created new bundle `nut`, which should appear within the next few releases.

**Comment by LaurenceGough** [comment]
> Packaged and created new bundle `nut`, which should appear within the next few releases.

Thanks for bundling this, I've installed it all ok but it seems usbhid-ups is missing. Is this expected?

```
upsc apcups
Error: Driver not connected
```
```
sudo modprobe usbhid-ups
modprobe: FATAL: Module usbhid-ups not found in directory /lib/modules/6.6.9-1394.native
```

I'm sure I am doing something wrong but I am a bit stuck now... NUT won't work due to this driver not being loaded.

**Comment by LaurenceGough** [comment]
So it seems it does not run or build correctly (from source) as libusb-1.0-0-dev is missing which you cannot build and install yourself as it's not signed (well, not without turning off a secure boot and all the rest).

So it seems Clear Linux is so barebones that it cannot support UPS software! Am I the only one thinking this is pure madness for a server OS?

What is everyone else doing, just letting their servers die when the UPS battery runs out? A power generator is really out of the home user's options ;).

**Comment by bwarden** [comment]
> I'm sure I am doing something wrong

Yes. To start with, the UPS drivers *are not* kernel modules. They are user space programs, installed under `/usr/libexec/nut/`, and launched by the nut-driver systemd services according to your configuration.

Start with https://networkupstools.org/docs/user-manual.chunked/Configuration_notes.html#_basic_configuration and create your configuration in `/etc/ups/` (`nut.conf`, `ups.conf`, `upsd,conf`, `upsmon.conf`, etc.).
