### ISSUE TITLE
Preventing desktop freezeups

### ISSUE THREAD

**Issue by jumpinggoofballs** [clearlinux/distribution#1416]
Hello,

Been using Clear on the desktop since August and it has been surprisingly good and stable. But I do have a couple of desktop / laptop usage suggestions:

1) swupd ramps up to 100% CPU usage when applying delta upgrades in the background, meaning it cloggs up all other tasks and freezes up the desktop. This is a bad experience on the desktop and I don't see how this would be beneficial in IoT.

Suggestions: 
- cap CPU usage for swupd to max 50%, or maybe limit it to using only 50% of cores, or perhaps, if it is easier, make it single core only. The user should not notice from the desktop when updates are happening in the background.
- for the desktop perhaps use something like the zen kernel, or adopt some of the scheduling optimisations from the zen kernel which mitigate desktop freezups during 100% CPU usage. 
- would be extra nice to have a GNOME desktop notification when swupd updates have been completed in the background, so I know to give it a restart.
- and while we're here, specifically for laptop use it would be good to have an ondemand governor rather that full performance governor to help with battery life. Clear is chewing through my battery very quickly.

2) May we have Firefox with your black magic optimisations* as a flatpak ++ which also includes the problematic codecs for video playback?

*Firefox in Clear has lower CPU usage for me in YouTube and other video services than Chromium with VAAPI in Arch. It would be a delightful contribution to the entire OSS community if Clear made these optimisations easily available to every other distribution.

**Comment by ahkok** [comment]
@otaviobp can you maybe open a `swupd-client` ticket to see if we can `nice` `swupd` when it runs automatically?

**Comment by ahkok** [comment]
@jumpinggoofballs you're putting too many line items in here. We really can't do anything with requests that have 5+ different parts. In the future, please file separate requests as separate items, so we can quickly close ones that are easily fixable.

**Comment by ahkok** [comment]
@otaviobp > /GNOME desktop notification when swupd updates have been completed/

**Comment by ahkok** [comment]
> It would be a delightful contribution to the entire OSS community if Clear made these optimisations easily available to every other distribution.

We provide the official built-by-`mozilla` builds of firefox. We don't compile them.

**Comment by ahkok** [comment]
> have an ondemand governor rather that full performance governor to help with battery life.

You can change it. There are many ways to change it. `TLP` for instance may help - `sudo swupd bundle-add TLP`

**Comment by ahkok** [comment]
> the zen kernel

probably not. Please try e.g. the `linux-preempt-rt` kernel (not an official kernel we support, but it's available)

**Comment by jumpinggoofballs** [comment]
Thank you for your replies!

If @otaviobp moves the swupd issue to the `swupd-client` as you suggest, I am happy for this thread to be closed. 

I take your point about too many line items, and that for me was the key one. 

__
If I may ask one quick question about the Firefox thing though, since I don't expect this issue to be taken up anywhere else: if the relative performance gains I am seeing in Firefox are not coming from the FF binary itself, where would they be coming from? - the thing about Flatpak is that those other parts of the stack can be packaged in so that when launched, the Flatpak application uses those instead of the normal dependencies in the underlying system.

**Comment by lebensterben** [comment]
>Thank you for your replies! ...

@jumpinggoofballs It has been none that some performance gains on Clear Linux is hard to understand..... Some people tried to apply all the patches to built a custom Kernel for other distros, though performance increased, still not as good as on Clear Linux.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bryteise** [comment]
In some cases performance gains or losses can be from lots of compounding smaller changes that are hard to correlate to task X performance.

**Comment by jumpinggoofballs** [comment]
Okay, so is this being moved to `swupd-client`, or should I close the issue here and open it myself there?

If so, which repo is this specifically?

**Comment by lebensterben** [comment]
>Okay, so is this being moved to `swupd-client`, or should I close the issue here and open it myself there? ...

@jumpinggoofballs you can open an issue in `swupd-client`, refer to  this one, and close it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jumpinggoofballs** [comment]
Moved main issue to #https://github.com/clearlinux/swupd-client/issues/1188 
---
