### ISSUE TITLE
CPU Temperature / Usage

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/distribution#1417]
Please add a package to display cpu temperature, usage, fan speeds, like [Sensors-unity](https://git.launchpad.net/sensors-unity/) or[ Psensors](https://gitlab.com/jeanfi/psensor)

Example: [Screenshot](https://149366088.v2.pressablecdn.com/wp-content/uploads/2016/11/full.jpg)

**Comment by ahkok** [comment]
`sudo swupd bundle-add psensor`
