### ISSUE TITLE
[BBT][dev-utils-dev]missing service networkd-fallback

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1419]
In build 31450, we have an error while checking the quick-perms
This is the error

(from function `Q' in file quick-perms.t, line 8,
  in test file quick-perms.t, line 59)
   `Q find / \( -path /proc -o -path /run/user/\* \) -prune -o -type d \( -perm -0002 -a ! -perm -1000 \) -printf "GEN002500: %p is %m should be 1777\n"' failed
 find: '/sys/fs/cgroup/memory/system.slice/networkd-fallback.service': No such file or directory

looks like that networkd-fallback.service is not present

bbt-worker@dev-utils-dev~ $ ls /sys/fs/cgroup/memory/system.slice/net*
ls: cannot access '/sys/fs/cgroup/memory/system.slice/net*': No such file or directory
bbt-worker@dev-utils-dev~ $

**Comment by ahkok** [comment]
You need to also `-prune /sys` - this is a false positive.
