### ISSUE TITLE
Fiddle with EFI boot section,assuming that this is the only OS installed..heck

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#142]
I do have several distributions in my system, and all boot through EFI, now ClearLinux thinks, it is the only OS to be in the system and fiddle with the boot section.

Do not write or mess with the boot section...at least ask the end user, that you want to update it or want to do it in a proper way??

Sound naive?? Sound stupid?? can't help. That is what bugs me. I tried to bypass it and it is still bugging. 

I am sure, I am certainly missing some arcane details to get on.

------------------------

### What is the issue type?
 Bootloader fiddling 
* [ ] Bug report
* [ ] Enhancement request
Little care needed.
### Describe the problem
It is thought, it is the only OS in the system and does stuff, which is not desired by an end user.

**Comment by iphutch** [comment]
@bwarden We may need to move this to the clr-boot-manager project.

**Comment by bwarden** [comment]
Agreed.
