### ISSUE TITLE
[BBT][devpkg-open-iscsi]/usr/bin/ld: cannot find -liscsiusr

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1420]
In build 31450, we have a regression for devpkg-open-iscsi, fail to compile test, looks like a missing binary

This is the error

 (in test file bat-devpkg-open-iscsi-pkgconfig-compile.t, line 13)
   `echo "int main(int argc, char **argv) { return 42; }" | gcc -x c $CFLAGS $pc_cflags $pc_libs -o foo - 2>&1' failed
 /usr/bin/ld: cannot find -liscsiusr
 collect2: error: ld returned 1 exit status

**Comment by phmccarty** [comment]
This is not a regression, since it was also failing in build `31410` and likely earlier.

**Comment by phmccarty** [comment]
This is an upstream bug.

**Comment by phmccarty** [comment]
I submitted a PR upstream to fix, and I added this patch for open-isci. Should be fixed in build `32060` or newer.

**Comment by phmccarty** [comment]
Fixed in release `32060`.
