### ISSUE TITLE
[BBT][devpkg-libyami]Package 'xt', required by 'trapproto', not found

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1421]
In build 31450, we have a  regression for devpkg-libyami

 This is the error

```
 (in test file bat-devpkg-libyami-pkgconfig-compile.t, line 209)
   `pc_cflags="$(pkg-config --cflags trapproto)"' failed
 Package xt was not found in the pkg-config search path.
 Perhaps you should add the directory containing `xt.pc'
 to the PKG_CONFIG_PATH environment variable
 Package 'xt', required by 'trapproto', not found
```

**Comment by phmccarty** [comment]
This is a bug with the `xorgproto`, so the fix needs to wait until that package can be moved to a newer version. It is currently stuck at version `2018.4`.

**Comment by phmccarty** [comment]
On a second look, this might be revealing a bug with how the autogenerated devpkg bundles are generated. I will investigate.

**Comment by phmccarty** [comment]
There was indeed a bug with the devpkg bundle generation. Issue should be fixed in build `32060` or newer.

**Comment by phmccarty** [comment]
Correction: The bug with devpkg bundle generation was fixed, but this issue remains an open issue. I mistakenly assumed that `libXt` was part of the "super" `libX11` package, but that is not the case. So, `xorgproto-dev` still needs to require `libXt-dev`, ideally via the implicit requires from pkgconfig files.

**Comment by phmccarty** [comment]
I am adding `pkgconfig(xt)` as a build dependency of `xorgproto`, which will enable rpmbuild to add that runtime requirement to `xorgproto-dev`. Should be fixed in build `32090` or newer.

**Comment by phmccarty** [comment]
Fixed in release `32090`.
