### ISSUE TITLE
how to run virutal machine manager in clear linux?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1425]
![image](https://user-images.githubusercontent.com/12841320/67921553-3c015380-fbd0-11e9-9775-473a41555175.png)

what is wrong here?
how to configure libvirtd properly?

no success with reboot of pc

**Comment by bryteise** [comment]
Did you start the libvirtd.service? I am just reading the error message and it looks like you ran the libvirtd daemon as non-root and your user isn't in the kvm group and doesn't have access to /dev/kvm. I would expect folks to use systemd to manage the libvirt service though. Probably libvirt documentation would be more helpful than me guessing though.

**Comment by nazar2sfive** [comment]
```
android@clr~ $ sudo systemctl start libvirtd.service
Password: 

```
problem solved.
thanks @bryteise
