### ISSUE TITLE
oracle virtualbox?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1426]
will oracle virtualbox appear as bundle in clear linux ever?

or should i have to wait for clr-user-bundles support (swupd-3rd-party) to be added and support such app?

**Comment by bryteise** [comment]
Virtualbox is really painful to package and I have so far lost every time I have tried for half a day or so.

**Comment by puneetse** [comment]
Duplicate of https://github.com/clearlinux/distribution/issues/390
