### ISSUE TITLE
Version 24250 kernel panics/fails to boot on existing and new Hyper-V installs

### ISSUE THREAD

**Issue by nicknimchuk** [clearlinux/distribution#143]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

I rebooted my Clear Linux install on a Windows Hyper-V 2016 Server today and got a kernel panic. Thinking I had somehow broken my install, I downloaded the current image to work on recovering and received a similar error with the initial boot. There were no changes on the host side between now and previous successful boots, so it appears to be related to version 24250. This is a fairly recent install, so I was not able to test any backups to see if they would boot. Changing any of the standard options on the Hyper-V virtual machine did not allow the boot to succeed.

The screen on the existing install during the failed boot:
![image](https://user-images.githubusercontent.com/32887909/43750811-b87f8ab8-99bf-11e8-81ac-dd0f1ee5e98c.png)

And the newly downloaded image:
![image](https://user-images.githubusercontent.com/32887909/43750847-e464cfda-99bf-11e8-958d-fa99e23d4580.png)

These are Gen 2 Hyper-V VMs. The host is a Dell T3420 workstation with an I7-6700 Intel processor and 32 GB RAM.

**Comment by Andy2244** [comment]
24260 boots for me again btw

**Comment by nicknimchuk** [comment]
24260 fixes the problem for me as well. Fortunately, Clear Linux makes "migrating" super easy (just copying /var, /etc, /srv, and /home to the new drive in my case).
