### ISSUE TITLE
How to take screenshot of AN AREA WITH right click option displayed.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1431]
I did the following "full screenshot" to capture what is displayed on right click over nazar.gpg file.

![image](https://user-images.githubusercontent.com/12841320/67947566-05e1c500-fc0c-11e9-8309-979ab28786f4.png)
due to fullscreenshot it is capturing all the unnecessary info which i was not planning for it.

I cannot however take screenshot with right mouse click followed by Ctrl+Shift+print to do the same. when i press the hotkey combination the right click option vanishes.

**Comment by lebensterben** [comment]
>I did the following "full screenshot" to capture what is displayed on right click over nazar.gpg file. ...

@nazar2sfive This is not a bug report not a package request. And it's better asked in forum.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nazar2sfive** [comment]
@lebensterben 
i thought gnome screenshot tool requires some tweak to capture my right click for a given area.
