### ISSUE TITLE
iotop

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1432]
http://guichaz.free.fr/iotop/

> Iotop is a Python program with a top like UI used to show of behalf of which process is the I/O going on. It requires Python ≥ 2.7 and a Linux kernel ≥ 2.6.20 with the TASK_DELAY_ACCT CONFIG_TASKSTATS, TASK_IO_ACCOUNTING and CONFIG_VM_EVENT_COUNTERS options on.

![image](https://user-images.githubusercontent.com/12841320/67948612-30348200-fc0e-11e9-9d83-dd399aa1e2ae.png)

**Comment by fenrus75** [comment]
$ swupd search iotop
Component iotop has version 1

Bundle with the best search result:
     iotop                              - Per process I/O bandwidth
monitor. (installed)

This bundle can be installed with:

  swupd bundle-add  iotop

Alternative bundle options are
     performance-tools                  - Run performance and power
measurements.  (132MB) (installed)

hmm looks like we have this already?

**Comment by nazar2sfive** [comment]
@fenrus75 
thanks.
