### ISSUE TITLE
Mesa lacks i686 icd.d vulkan loaders

### ISSUE THREAD

**Issue by sunnyflunk** [clearlinux/distribution#1437]
Currently 32bit vulkan support is broken in CL (which steam/wine has started using for DX to vulkan translation). It turns out all that's lacking are the icd.d loaders for i686.

mesa contains:
```
/usr/share/vulkan/icd.d/intel_icd.x86_64.json
/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
```

but lacks the `intel_icd.i686.json` and `radeon_icd.i686.json` equivalents. If I copy the x86_64 version to the missing name (and update library path to lib32) then all the issues disappeared! Maybe `autospec` is removing them.

To resolve, would expect these files to be added to mesa:
```
/usr/share/vulkan/icd.d/intel_icd.i686.json
/usr/share/vulkan/icd.d/radeon_icd.i686.json
```

I'll take a look Monday (if not solved), but for now I need a break.

**Comment by ahkok** [comment]
In progress.

**Comment by ahkok** [comment]
`mesa-19.2+2470.g163d5fde066-228`

**Comment by K1ngfish3r** [comment]
I've installed version 39970 and have come across this issue.
Output of `ls /usr/share/vulkan/icd.d/` below
```
intel_hasvk_icd.x86_64.json
intel_icd.x86_64.json
lvp_icd.x86_64.json
radeon_icd.x86_64.json
```
Manually adding the files below and pointing them to the lib32 folder fixes the issue
```
intel_hasvk_icd.i686.json 
intel_icd.i686.json
lvp_icd.i686.json
radeon_icd.i686.json
```
