### ISSUE TITLE
Howto install an old Libreoffice version for Libreoffice calc bug

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1440]
Libreoffice calc 6.3.2.2 has a problem opening xlsx files. It tells that the files are corrupt and must be repaired. repair does not succeed. 
If I open the same file in a kvm Debian 10 environment with Libreoffice 6.1.5.2 it can be opened normal. I tested with more xlsx files with the same result. I checked in the web found more with problems like me at  ask.libreoffice.org

**Comment by thiagomacieira** [comment]
Clear does not carry old versions. The only way to downgrade any component is to downgrade the entire distribution, which is not supported. If you REALLY want to try it, you'll need the `swupd verify` command.

If you find out about a fix that we should apply, let us know.

**Comment by anselmolsm** [comment]
Hi @seafrog1 , libreoffice has been updated to 6.3.3.2 which fixes the Calc issue. Will be available in CL >= 31470.

**Comment by anselmolsm** [comment]
A quick heads up, 31470 is out with the updated libreoffice.

**Comment by seafrog1** [comment]
Thx, already installed, working now
