### ISSUE TITLE
Add sxiv to desktop-i3 / desktop-awesome (or a devpkg-imlib2)?

### ISSUE THREAD

**Issue by dtw-waleee** [clearlinux/distribution#1442]
[sxiv](https://github.com/muennich/sxiv) is a image viewer that's common in more minimalis setups.
If you'd prefer not to add `sxiv`, consider adding the headers to `Imlib2` (a local, manual build seems likely to conflict with a possible system installed one right now).

**Comment by bryteise** [comment]
Package in, submitted patch to add to bundles to the ML. Likely be in Tuesday.

**Comment by dtw-waleee** [comment]
Thanks!

**Comment by bryteise** [comment]
Pushed patch.
