### ISSUE TITLE
VMware: kernel module vmmon not loaded

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1443]
Hello,

I installed CL on an Intel Compute Stick STK1AW32SC, to host a Debian VM in VMware Workstation which runs my website. The VM currently runs on my notebook and I like to outsource that to the compute stick.

The VMware Workstation install worked fine based on this sequence:

```
sudo swupd bundle-add linux-dev
sudo swupd bundle-add kernel-native-dkms (errors)
sudo clr-boot-manager update reboot (errors)

sudo sh ./V*.bundle

Use default directory: /etc/init.d (> ? <)

```

I can start VMware Workstation GUI, all looks good, but when I try to start the VM I get a polite message saying: "[..] kernel module vmmon not loaded"

I'm still new to Linux, but manage all tasks with Debian. I think some time ago there was a topic to make a tutorial how to setup VMware Workstation properly in CL ?

What should I do different to get this working ?

Many thanks ! :)

**Comment by puneetse** [comment]
What are the errors when you run these commands?
```
sudo swupd bundle-add kernel-native-dkms (errors)
sudo clr-boot-manager update reboot (errors)
```

The `kernel-native-dkms` adds an important kernel parameter to allow the loading of out-of-tree modules. Check `cat /proc/cmdline`. You should see `mod.sig_unenforce`

**Comment by 0xA1B2** [comment]
moo@compute-stick~/Downloads $ sudo clr-boot-manager update
Password: 
[ERROR] cbm (../src/lib/bootvar.c:L412): efi_generate_file_device_path_from_esp() failed: Function not implemented
[ERROR] cbm (../src/lib/bootvar.c:L412): efi_generate_file_device_path_from_esp() failed: Function not implemented
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L284): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L285): Please manually update your bios to add a boot entry for Clear Linux

**Comment by puneetse** [comment]
Can you check if there is a newer BIOS update available for the compute stick, update to it, and try again?

0044 is the latest I saw for that model.

**Comment by 0xA1B2** [comment]
Hello, I just updated to BIOS 44, and made bundle-remove for kernel-native-dkms, reboot and bundle-add. This time that installed without errors.

Just the clr-boot-manage update still fails with the same errors as above.

I can see "module.sig_unenforce"  when running cat /proc/cmdline

Now I uninstalled VMware and will report back upon reinstall.

**Comment by 0xA1B2** [comment]
sudo vmware-installer -u vmware-workstation is not working. It shows a terminal prompt, but no matter if you choose yes/no the uninstall process hangs at 1% and leave the system uncleaned.

A reinstall attempt says "nothing changed, all good", and Vmware remains broken.

I followed this guide, which helped:

https://kb.vmware.com/s/article/38

After that reboot and attempt to install the bundle file again, however no GUI is shown, just console this time with a progress bar to 100%. Reboot again and VMware Setup GUI shows once clicking on the organe/blue VMware icon. Finally, VMware GUI comes up again.

Try to load the VM .. and the result is the same:

"Could not open /dev/vmmon: No such file or directory. Please make sure that the kernal module 'vmmon' is loaded."

**Comment by 0xA1B2** [comment]
I tried to follow the steps shown here:

https://github.com/mkubecek/vmware-host-modules

But in the end its always the same error message .. Could not open /dev/vmmon: No such file or directory

vmmon.ko and vmnet.ko are build and located in /usr/lib/modules/5.3.8-854.native/misc

**Comment by 0xA1B2** [comment]
Googled around and found some more required steps:

**Comment by 0xA1B2** [comment]
So it runs fine, just after a reboot these things have to be repeated:

sudo insmod/usr/lib/modules/5.3.8-854.native/misc/vmmon.ko
sudo insmod /usr/lib/modules/5.3.8-854.native/misc/vmnet.ko
sudo /etc/init.d/vmware start

How can that be made persistent in CL ?

**Comment by ahkok** [comment]
`man modules-load.d` describes how to auto-load modules.

`init.d` scripts are superseded by `service` files. I assume some are provided. `sudo systemctl enable $unit` makes a unit start automatically at boot.

**Comment by ahkok** [comment]
If you need more help with the above hints, please ask. I'm assuming this is complete.
