### ISSUE TITLE
support for torrent download of the image iso.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1448]
![image](https://user-images.githubusercontent.com/12841320/68104302-abde4980-ff02-11e9-8388-c82842352fcb.png)
its just too slow. i have 50Mbps at home.

**Comment by ahkok** [comment]
Will not happen. We change images too often for torrents to make any sense.

**Comment by ahkok** [comment]
note: CDN slowness is under investigation. But we will not supply torrents.

**Comment by nazar2sfive** [comment]
@ahkok 
![image](https://user-images.githubusercontent.com/12841320/78800793-956d7a00-79db-11ea-9a1d-c7c4bedfa71d.png)

**Comment by nazar2sfive** [comment]
![image](https://user-images.githubusercontent.com/12841320/80819072-07f50280-8bf4-11ea-9cc5-1ffdb901c9c5.png)
 i wish it was faster than that.
