### ISSUE TITLE
Issues with old NetworkManager

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1449]
1) Doesn't works with IWD 1.0 (hotfix in 1.21.3)
2) Can't connect to hidden AP 
3) Wireguard support: a lot of improvements in latest NM releases

Currently provided `v1.16.2` was released in May 2019 :smiley_cat:

**Comment by felixg3** [comment]
I want to support this request. I would really like to see the most recent NM

**Comment by mrkz** [comment]
@paulcarroty I would be updating to the latest stable release (which up to now is `1.20.8`). 

That means that the `iwd` fix wouldn't make it, however, I suppose that the fix that you'd be looking forward to have is [iwd: unbreak iwd-1.0](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/commit/186d22a9634e2bf94658ed6f1cf2b332ecb3a32c) this?

If so, I can work on cherry-picking this fix (sice we're shipping `iwd` version `1.2` anyway.

**Comment by mrkz** [comment]
Looking better at `1.20.8`, this release already includes those changes, so unsure if you're looking for those to be included or if I'm missing other bits (although I couldn't find more updates regarding `iwd` in upstream NM)

**Comment by paulcarroty** [comment]
@mrkz cool, anyway the latest release should include all ^needed stuff.

**Comment by felixg3** [comment]
They updated NM to 1.20.8 with `31930`. Looking forward to the release of the version!
