### ISSUE TITLE
nftables build is aborted due to openjade error when generating man pages

### ISSUE THREAD

**Issue by joselamego** [clearlinux/distribution#145]
Clear Linux 24320

nftables package cannot be build or updated due to an error from openjade (jw) when generating man pages.

after a "make autospec" command execution, the following error in results/build.log:

`...`

`Making all in doc`
`make[2]: Entering directory '/builddir/build/BUILD/nftables-0.9.0/doc'`
`  GEN      nft.8`
`Usage: jw [<options>] <sgml_file>`
`where <options> are:`
`  -f|--frontend <frontend>:`
`...`
`make[2]: Leaving directory '/builddir/build/BUILD/nftables-0.9.0/doc'`
`make[1]: Leaving directory '/builddir/build/BUILD/nftables-0.9.0'`
`  -v|--version:                  Print the version and exit`
`make[2]: *** [Makefile:569: nft.8] Error 1`
`make[1]: *** [Makefile:488: all-recursive] Error 1`
`make: *** [Makefile:397: all] Error 2`
`RPM build errors:`
`error: Bad exit status from /var/tmp/rpm-tmp.ccjgQM (%build)`
`    Bad exit status from /var/tmp/rpm-tmp.ccjgQM (%build)`
`Child return code was: 1`
`EXCEPTION: Command failed. See logs for output.`
`# bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/nftables.spec`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace`
`    result = func(*args, **kw)`
`  File "/usr/lib/python3.7/site-packages/mockbuild/util.py", line 526, in do`
`    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)`
`mockbuild.exception.Error: Command failed. See logs for output.`
`# bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/nftables.spec`
`LEAVE do --> EXCEPTION RAISED`

nftables can be build only when passing the option "--disable-man-doc" through the configure file.

**Comment by bryteise** [comment]
Looking through this, it eventually will attempt to generate man pages once enough dependencies are manually added but even once it has all these it still fails to generate man pages due to using different section tags than the supported parsers. We could add an alternate generator (docbook2X) but it has other problems so this is not going to happen until the upstream changes its ways.
