### ISSUE TITLE
kata-runtime: consider dropping set-docker-default-runtime

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1451]
For better user-experience when using docker let's consider to not have kata-runtime set as the default.

/cc @bryteise

**Comment by bryteise** [comment]
The point was to have kata be default if the kata runtime was installed. Would different bundle arrangements be more reasonable here or do we really want runc by default and opt in to kata on a case by case basis?

**Comment by eadamsintel** [comment]
I would make Kata the opt-in even if the bundle with Kata is installed. The scenario that comes to mind is you install `cloud-native-basic` to get Kubernetes but want to use Kubernetes + Docker which is a common Kubernetes setup. You would have to know to change the default runtime back to runc or some privileged pods won't run the way you expect.

**Comment by mythi** [comment]
>  would make Kata the opt-in even if the bundle with Kata is installed 

opt-is is what I had in mind too. we could keep the `--add-runtime` part for kata but drop `--default-runtime`

**Comment by bryteise** [comment]
> we could keep the `--add-runtime` part for kata but drop `--default-runtime`

Sounds good to me.

**Comment by eadamsintel** [comment]
When will this be changed?  I just discovered that if you install `containers-virt` and then remove it leaving `containers-basic` that docker won't work until you know to go to `/etc/systemd/system/docker.service.d/50-runtime.conf` and change the default runtime back to `runc`, `systemctl daemon-reload`, and then `systemctl restart docker`.

**Comment by mythi** [comment]
@hnanni can you take a look? The task is to rework `0001-Add-Clear-Linux-Docker-integration-for-Kata-Containe.patch` so that only `clearlinux.conf` is installed.

**Comment by puneetse** [comment]
It looks like this was done already https://github.com/clearlinux-pkgs/kata-runtime/commit/10bbc0d3687607ea76987871245cda3461c2ddf0

@hnanni can this issue be closed or is there more work to consider?

**Comment by hnanni** [comment]
I consider it completed. Was expecting to get more details if something else is needed besides the what is in the commit you mentioned

**Comment by mythi** [comment]
> I consider it completed. 

+1
