### ISSUE TITLE
x0vncserver > "XTest extension not present"

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1455]
x0vncserver which I think came with bundle-add vnc-server or os-utils-gui (?), seems to be build without XTest extension.

When I start x0vncserver, it shows the warning: "XTest extension not present" and subsequently the remote connection is view only, its not possible to send back inputs to the server.

**Comment by 0xA1B2** [comment]
I tried the binary "tigervnc-1.9.0.x86_64.tar.gz" from:

https://bintray.com/tigervnc/stable/tigervnc/1.9.0

And x0vncserver works as it should and accepts inputs from mouse and keyboard.

**Comment by pixelgeek** [comment]
Confirmed. 

![image](https://user-images.githubusercontent.com/1402359/68342552-b4b85200-009f-11ea-8ae4-11f5d58163c8.png)

https://github.com/TigerVNC/tigervnc/issues/693 indicates that we should have HAVE_XTEST flag set.

**Comment by ahkok** [comment]
Fixed in `tigervnc-1.9.0-17`
