### ISSUE TITLE
Support to auto shut down KVM guests when using kvm-host bundle

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#146]
### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

👋 Hi there,

I was chatting with `arjan_work` in #clearlinux today and he recommended that I open up an issue regarding this.

I'm using Clear Linux for a KVM host using the [`kvm_host` bundle](https://github.com/clearlinux/clr-bundles/blob/b08659c4f63371f5cdc62c35078d1342fcf3cd9e/bundles/kvm-host). 

I'm looking for a way to shut down the KVM guests automatically when the host is shut down. In researching on the internet, it _seems_ as though the way that this is typically done is via a tool called [libvirt-guests](https://github.com/libvirt/libvirt/blob/master/tools/libvirt-guests.sysconf). 

`arjan_work` pointed out that the service is installed to `/usr/lib/systemd/system/libvirt-guests.service`, but it's not installed into the systemd shutdown target.

I attempted to load the service via:

```
brooks@nuc7i5 ~ $ sudo systemctl enable libvirt-guests
Created symlink /etc/systemd/system/multi-user.target.wants/libvirt-guests.service → /usr/lib/systemd/system/libvirt-guests.service.
```

But it appears to fail with:

```
brooks@nuc7i5 ~ $ journalctl | grep "libvirt-guests"
Aug 11 20:59:21 nuc7i5 libvirt-guests.sh[323]: /usr/libexec/libvirt-guests.sh: line 29: /usr/bin/gettext.sh: No such file or directory
Aug 11 20:59:21 nuc7i5 systemd[1]: libvirt-guests.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 20:59:21 nuc7i5 systemd[1]: libvirt-guests.service: Failed with result 'exit-code'.
```

**Comment by ahkok** [comment]
```
# Hack just call traditional service until we factor
# out the code
```

I guess they didn't bother to remove the junk at all. :)

**Comment by bswinnerton** [comment]
I'm a bit out of my element here, but would adding  `gettext` to the `kvm_host` bundle be a suitable solution?

**Comment by fenrus75** [comment]
that should be out now

**Comment by bswinnerton** [comment]
@fenrus75, this made my day. Thank you so much ❤️.

I've tested that this is working as expected.
