### ISSUE TITLE
How to make .deb or .rpm package to install in clear linux?

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1462]
expandrive is cool app to sync all online drive. (and rclone is no way a proper solution for me for google drive or onedrive or mega sync or anyother drive unless they come with some functional gui solution like expandrive for which i am waiting)

expandrive is availabe in .deb and .rpm

![Screenshot from 2019-11-07 04-06-27](https://user-images.githubusercontent.com/12841320/68359766-49c15680-0145-11ea-9aad-6e33fb2cad8f.png)

**Comment by lebensterben** [comment]
>expandrive is cool app to sync all online drive. (and rclone is no way a proper solution for me for google drive or onedrive or mega sync or anyother drive unless they come with some functional gui solution like expandrive for which i am waiting) ...

@nazar2sfive This is not an issue. You can ask in the forum.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
