### ISSUE TITLE
sendEMail > invalid SSL_version specific ..

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1463]
Using sendEmail (with E) I get the error message below, even with bundle-add perl-extras:

`invalid SSL_version specified at /usr/lib/perl5/vendor_perl/5.28.2/IO/Socket/SSL.pm line 698.`

sendEmail Source:
http://caspian.dotconf.net/menu/Software/SendEmail/
sendEmail-v1.56.tar.gz  

Command run is the Gmail example from the above website to test if it works:

`sendEmail -o tls=yes -f YourEmail@gmail.com -t SomeoneYoureEmailing@domain.com -s smtp.gmail.com:587 -xu YourEmail@gmail.com -xp YOURPASSWORD -u "Hello from sendEmail" -m "How are you? I'm testing sendEmail from the command line."`

Besides that, plz add sendEmail to a bundle. Thx.

**Comment by thiagomacieira** [comment]
Upstream bug in SendEmail.
```perl
        if (! IO::Socket::SSL->start_SSL($SERVER, SSL_version => 'SSLv3 TLSv1')) {
```

https://metacpan.org/pod/IO::Socket::SSL says about "Common usage errors"
> Set 'SSL_version' or 'SSL_cipher_list' to a "better" value.
> IO::Socket::SSL tries to set these values to reasonable, secure values which are compatible with the rest of the world. But, there are some scripts or modules out there which tried to be smart and get more secure or compatible settings. Unfortunately, they did this years ago and never updated these values [...]
> So it is recommended to leave the settings at the secure defaults

SSLv3 is no longer supported.

**Comment by thiagomacieira** [comment]
The files in that tarball are dated 2009-09-29. That's over ten years old.
