### ISSUE TITLE
orca: ModuleNotFoundError: No module named 'pyatspi'

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#1465]
Python exception observed.
Steps to reproduce:

<pre>
$ orca
Traceback (most recent call last):
  File "/usr/bin/orca", line 32, in <module>
    import pyatspi
ModuleNotFoundError: No module named 'pyatspi'
</pre>

**Comment by ahkok** [comment]
`orca-3.34.0-21` has a dependency on `pyatspi-python3` to fix this.
