### ISSUE TITLE
Add runtime dep to lutris

### ISSUE THREAD

**Issue by sunnyflunk** [clearlinux/distribution#1466]
Currently on a slim plasma install, lutris fails to import gi in python with:

`ValueError: Namespace GnomeDesktop not available`

Installing `gnome-desktop-data` is sufficient for it to load (it does then warn about libgnome-desktop being missing), so possibly adding `gnome-desktop` to requires is best as it uses the same deps used by gtk3 anyway (plus bubblewrap).

**Comment by bryteise** [comment]
Hrm this isn't ideal but I'm not super worried about minimizing the games bundle at this point so change submitted.

**Comment by sunnyflunk** [comment]
Just to clarify, by `gnome-desktop` I mean the singular package https://github.com/clearlinux-pkgs/gnome-desktop that would add a MB or 2 (has the same deps as gtk3 so I don't think it would pull in many extra deps) to the requirements rather than the full desktop bundle which I certainly don't want installed!

**Comment by bryteise** [comment]
Ah okay, sorry I misunderstood. Adding things to requires isn't ideal but that's what we are left with in this case it seems. Change pushed and should be in the next release.
