### ISSUE TITLE
Clear Linux Installer Images, can't install ; do not contain install Grub entry or clr-installer

### ISSUE THREAD

**Issue by aenertia** [clearlinux/distribution#147]
* [x] Bug report
* [ ] Enhancement request

### Describe the problem
Using clear-24360 ; both iso and raw installer images. There is no install option present; appears to be a live only environment (prompts for root password change on login - drops to root afterwards).

no clr-installer scripts present in the live environment.

I presume someone has broken image builds to not include the installer bits for the installer images?

**Comment by aenertia** [comment]
I just checked 23550 also has this problem.

**Comment by aenertia** [comment]
and 24370

When was the last time someone actually did a baremetal install that wasn't via ironic etc?

**Comment by aenertia** [comment]
Ahh I think I see the problem. I am installing over serial - and it spawns a root login on serial... this behaviour needs to be fixed so that the installer spawns on ttyS0 rather than login.

**Comment by aenertia** [comment]
Persisting with the 24370 image - 

I notice the following after editing the grub cmd line: 

`` 

         Starting ister graphical installer...``

This image doesn't however let me drop to root after setting a password. 

Is there any way to force ister to launch on ttyS0 via a kernel flag? I've tried disabling framebuffer completely etc. 

This machine only has serial console (rangely based router board)

**Comment by aenertia** [comment]
is there a VNC listener option (like in the rhel/centos/fedora ramdisks?) that you can flag on from the kernel command line to complete install?

**Comment by ahkok** [comment]
You should be able to start the installer manually from the serial port as well.

Try running `ister_gui.py` as root from it.

**Comment by aenertia** [comment]
As mentioned the latest image doesn't allow login on the serial. Other suggestions?

Other distros generally check to see what the kernel command line was and grok console=ttyS0,115200n8 appropriately by any installer scripts triggered during init sequence. Suggest that's probably the approach to take here.

**Comment by bryteise** [comment]
@aenertia I'm unable to reproduce the issue of not being able to login to the installer via serial (I used  qemu launching with -serial to get both a tty console and a serial console at the same time). Are you using the raw image for this?

Our default kernel commandline alway passes a console=ttyS0 so the detection approach won't work for for us in this case.

**Comment by aenertia** [comment]
I forget It might have been the iso - I tried both several builds. I
eventually got a login-able image

**Comment by bryteise** [comment]
Ah okay, thanks!
