### ISSUE TITLE
Cockpit can't create diagnostics report

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/distribution#1471]
Creating diagnostic reports in Cockpit isn't working; it returns an error reading:

```
No archive has been created.

sosreport (version 3.5)

plugin haproxy does not install, skipping: No module named 'urlparse'
no valid plugins were enabled
```

**Comment by bryteise** [comment]
Did you run this as root?

**Comment by ahkok** [comment]
Issue in this bug seems no longer exists. But, I can't figure out how to get *anything* sensible out of `sosreport` myself.
