### ISSUE TITLE
bundle request for this search tool: Drill

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1472]
Considering that FSEARCH (https://github.com/clearlinux/distribution/issues/1403) is beta and the build system is broken, I suggest another good Everything-like search GUI application: Drill. 

Clear Linux lacks a powerful GUI search application.

Source: https://github.com/yatima1460/Drill
Overview: https://www.linuxuprising.com/2019/05/drill-new-desktop-file-search-utility.html

**Comment by lebensterben** [comment]
The heuristics of this program is very interesting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gogazago** [comment]
it works fine on my clearlinux nuc, let me work on this
