### ISSUE TITLE
Command `distro` returns blank values

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#148]
### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

When running `distro`, the following result is seen:
```
Name:
Version:
Codename:
```

The expected results are:
```
Name: Clear Linux OS for Intel Architecture
Version: 24440
Codename: Clear Linux
```

Or something along these lines.

**Comment by fenrus75** [comment]
fixed

I kinda wonder why we ship this thing but sure it does no harm
