### ISSUE TITLE
cannot drag drop over viber, telegram.....

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1481]
![image](https://user-images.githubusercontent.com/12841320/68675849-d5d9e080-0580-11ea-9ebf-2f7ccb0cb770.png)

i cannot drag and drop my files over viber, telegram message.

**Comment by lebensterben** [comment]
Duplicated. See https://github.com/flatpak/xdg-desktop-portal/issues/99


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrkz** [comment]
please follow-up on 

> Duplicate of [flatpak/xdg-desktop-portal#99](https://github.com/flatpak/xdg-desktop-portal/issues/99)
