### ISSUE TITLE
kernel: unable to build upstream kernel (stable v5.3.10) with current toolchain (build 31530)

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#1483]
Used the linux-mainline config with v5.3.10, as tagged from Greg K-H's tree, and here's what I get:

```
  AS      arch/x86/boot/compressed/head_64.o
arch/x86/boot/compressed/head_64.S: Assembler messages:
arch/x86/boot/compressed/head_64.S:647: Error: attempt to move .org backwards
make[2]: *** [scripts/Makefile.build:382: arch/x86/boot/compressed/head_64.o] Error 1
make[1]: *** [arch/x86/boot/Makefile:112: arch/x86/boot/compressed/vmlinux] Error 2
make: *** [arch/x86/Makefile:284: bzImage] Error 2
```

As it stands, it is only possible to build the kernel with [a binutils work-around patch](https://github.com/clearlinux-pkgs/linux/blob/5.3.9-863/0130-add-workaround-for-binutils-optimization.patch).

I assert it's overly burdensome, therefore a bug, to require developers to apply a Clear-specific patch in order to compile upstream kernel code (mainline or stable) with a sane config.

**Comment by vcgomes** [comment]
Just adding a little more information, this also happens with all the upstream trees that I tested, net-next, Linus' tree, rt-devel. I agree with @thac0, having to carry this patch when working with upstream kernels is very annoying.

**Comment by thiagomacieira** [comment]
The default was swapped back off.

**Comment by thac0** [comment]
Upstream kernel builds no longer require a patch to build on Clear as of (roughly) 31660. Closing.
