### ISSUE TITLE
cannot add "appimage" to favorites in dash to dock.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1485]
![image](https://user-images.githubusercontent.com/12841320/68727521-bed0d800-05ec-11ea-8539-bd87ad0d9770.png)

**Comment by lebensterben** [comment]
This is not a bug.

---

The following thread provide one method that creates a shortcut to a directory contains your appimages.
https://forums.linuxmint.com/viewtopic.php?t=273402


Another method is to write a desktop file for the appimage and put the file under ~/.local/share/applications. Then you should be able to see the application in dash, that means you can add it to favorites.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
