### ISSUE TITLE
"info sed" shows the man page instead of the Texinfo documentation

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#1491]
Steps to reproduce: run `info sed`

Expected output:
```
Next: Introduction,  Up: (dir)

GNU 'sed'
*********

This file documents version 4.7 of GNU 'sed', a stream editor.
...
```

Actual output:
```SED(1)                                                          User Commands                                                         SED(1)

NAME
       sed - stream editor for filtering and transforming text

SYNOPSIS
       sed [OPTION]... {script-only-if-no-other-script} [input-file]...

DESCRIPTION
...
```

Reason: /usr/share/info/sed.info is missing.

**Comment by thiagomacieira** [comment]
Also missing:
* /usr/share/info/bash.info
* /usr/share/info/coreutils.info
* /usr/share/info/diffutils.info
* /usr/share/info/find.info
* /usr/share/info/grep.info
* /usr/share/info/libc.info

And more. How can one even develop in C in Clear without the libc texinfo?

**Comment by ahkok** [comment]
I've never missed it and always used `man` pages. Honestly, I've never figured out how to even use `info` since it's navigation confuses the heck out of me. :P

**Comment by ahkok** [comment]
Wrong button, lol.

**Comment by ahkok** [comment]
How would you want to solve this?

- add -info subrpms to an existing bundle
- create a new `info` bundle perhaps?
- `info-basic`  with the info subrpms?

Many of these info files live in `-doc` subrpms which are there, just not included.

**Comment by ahkok** [comment]
Quite a few `-doc` rpms have plenty of other non-info things in them.

**Comment by ahkok** [comment]
https://github.com/clearlinux/autospec/pull/526

**Comment by thiagomacieira** [comment]
Thanks. Re-autospec'ing the affected packages too.
