### ISSUE TITLE
pspp

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1494]
https://www.gnu.org/software/pspp/

GNU PSPP is a program for statistical analysis of sampled data. It is a free as in freedom replacement for the proprietary program SPSS, and appears very similar to it with a few exceptions.

**Comment by ahkok** [comment]
Bundle `pspp` will be available in 1-2 business days.

**Comment by nazar2sfive** [comment]
Something is wrong with `pspp` . As i put some value it constantly crashes.
@ahkok 
```
android@clr~ $ psppire
Segmentation fault (core dumped)
android@clr~ $ 

```
