### ISSUE TITLE
jasp

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1495]
https://github.com/jasp-stats

> JASP, a low fat alternative to SPSS, a delicious alternative to R. Bayesian statistics made accessible.

**Comment by lebensterben** [comment]
>https://github.com/jasp-stats ...

@nazar2sfive  Is it really low fat? It depends on R and needs Qt....

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nazar2sfive** [comment]
@lebensterben 
thats just quoted from the site

actually i need a good opensource alternative to spss

**Comment by nazar2sfive** [comment]
i had no idea that flaptak was available for it. so this makes my job easy.
