### ISSUE TITLE
grpc has orphaned libraries in /usr/lib

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1499]
The following libraries in the grpc package are orphaned:
* /usr/lib/libgrpc++_reflection.so.1.24.2
* /usr/lib/libaddress_sorting.so.8.0.0
* /usr/lib/libgrpc_cronet.so.8.0.0
* /usr/lib/libgrpc++.so.1.24.2
* /usr/lib/libgrpc_unsecure.so.8.0.0
* /usr/lib/libgrpc++_unsecure.so.1.24.2
* /usr/lib/libgrpc++_error_details.so.1.24.2
* /usr/lib/libgrpc.so.8.0.0
* /usr/lib/libgrpcpp_channelz.so.1.24.2
* /usr/lib/libgpr.so.8.0.0

**Comment by gtkramer** [comment]
As mentioned by @salvadorteranochoa in #1510:
> The grpc package has several orphan files in /usr/lib.
> https://github.com/clearlinux-pkgs/grpc/blob/master/grpc.spec#L460
> They must be placed somewhere else
> https://github.com/clearlinux/openBBT/blob/master/any-bundle/clean_FHS.t#L40

**Comment by YinThong** [comment]
Changes make. Pending for review on mailing list.

**Comment by YinThong** [comment]
package already updated. Please review and close it.

**Comment by YinThong** [comment]
@amygilliam1 @gtkramer @salvadorteranochoa Package already updated. Please review and closed.
