### ISSUE TITLE
Unable to play videos with Gstreamer

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/distribution#15]
Playing videos using Gstreamer fails on Clearlinux (`Installed version: 20890`). I have tried using `gst-play-1.0`, `gst-launch-1.0 playbin uri=file:///` and all fail the same way. I'm using an mp4 file downloaded from the Open Movie Project (Sintel).

I have tracked this down to what looks like a `mutter` problem when using the `vaapisink` Gstreamer element. See more on my findings here: https://bugzilla.redhat.com/show_bug.cgi?id=1546759 (although it should perhaps at this stage be filed against Mutter directly?)

Long story short, the behaviour is identical than what I describe on the bug linked above, i.e.
1. Constructing a pipeline manually using `xvimagesink` instead of `vaapisink` works
**OK**: `gst-launch-1.0 filesrc location=/home/gvancuts/Videos/Sintel.mp4 ! qtdemux ! h264parse ! vaapih264dec ! xvimagesink` 
**NOK**: `gst-launch-1.0 filesrc location=/home/gvancuts/Videos/Sintel.mp4 ! qtdemux ! h264parse ! vaapih264dec ! vaapisink`
2. Using `weston` as a nested compositor and display things there works. E.g.
```
$ weston &
$ WAYLAND_DISPLAY=wayland-1 gst-launch-1.0 filesrc location=/home/gvancuts/Videos/Sintel.mp4 ! qtdemux ! h264parse ! vaapih264dec ! vaapisink
```

**Comment by fenrus75** [comment]
does this also fail when using X? (our default env for now)

**Comment by gvancuts** [comment]
I'm not sure what you mean by "using X". I _think_ it's running Wayland with Xwayland. The following environment variables are set:
```
DISPLAY=:0
WAYLAND_DISPLAY=wayland-0
```
This is a fresh installation of Clearlinux (from Wednesday - version 20920) and I just added the GUI option from the installer (don't recall exactly what it was called).

I have tried to change the `display` option of vaapisink to use X11 (option `1`) but that does not work - see below:
```
$ gst-launch-1.0 -v filesrc location=/home/gvancuts/Videos/Sintel.mp4 ! qtdemux ! h264parse ! vaapih264dec ! vaapisink display=1
failed to open /usr/lib64/dri/hybrid_drv_video.so
Failed to wrapper hybrid_drv_video.so
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstVaapiSink:vaapisink0: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Additional debug info:
gstbasesink.c(5264): gst_base_sink_change_state (): /GstPipeline:pipeline0/GstVaapiSink:vaapisink0:
Failed to start
Setting pipeline to NULL ...
Freeing pipeline ...
```

The error I'm getting with a 'standard' gst-play-1.0 is identical to the one thrown when using `display=3` (which corresponds to Wayland)

**Comment by fenrus75** [comment]
My question was more about "without using wayland"

**Comment by gvancuts** [comment]
I haven't tried that. Do you have a pointer on how I can switch to a native X11 environment?

Wayland is not the issue per se, it works fine if I use weston instead of mutter. I have tried that with weston running as a nested compositor or natively.

**Comment by gvancuts** [comment]
Just rebooted using 'GNOME on Xorg' from the logging screen (so pure X11 env) and the `vaapisink` element behaves correctly there (tried both the `x11` and `glx` display option for `vaapisink` and both work).

**Comment by fenrus75** [comment]
ok that points us in a pretty narrow direction; thanks

**Comment by seanvk** [comment]
This issue is known https://bugzilla.gnome.org/show_bug.cgi?id=775698

Being addressed in the driver here:  https://github.com/intel/intel-vaapi-driver/issues/357
(I pinged the driver team to get someone assigned to it)

For the upcoming gstreamer release, vaapisink has been downgraded as marginal unfortunately.

commit c653cb55f9a97d1bf6d3fc1d0ae30dcd958174a5
Author: Víctor Manuel Jáquez Leal <vjaquez@igalia.com>
Date:   Mon Feb 12 17:53:58 2018 +0100

    vaapi: register vaapisink as marginal on wayland
    
    vaapsink, when used with the Intel VA-API driver, tries to display
    surfaces with format NV12, which are handled correctly by
    Weston. Nonetheless, COGL cannot display YUV surfaces, making fail
    pipelines on mutter.
    
    This shall be solved either by COGL or by making the driver to paint
    RGB surfaces. In the meanwhile, let's just demote vaapisink as
    marginal when the Wayland environment is detected, no matter if it is
    Weston.
    
    https://bugzilla.gnome.org/show_bug.cgi?id=775698

The right way to solve this is to get the support in for

**Comment by gvancuts** [comment]
Thanks @seanvk !

**Comment by iphutch** [comment]
@gvancuts Is this still an issue? can I close?

**Comment by gvancuts** [comment]
Hi @iphutch , I haven't tested this lately, I will try to get to it by EOW.

Do you have reasons to believe that this is fixed?

**Comment by gvancuts** [comment]
Mutter has been taken out of the equation (GNOME runs on X by default now)... so we're not hitting this issue anymore. I will close it.
