### ISSUE TITLE
obs-studio contains orphaned libraries

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1501]
The following libraries in the obs-studio package are orphaned:
* /usr/lib/libobs-scripting.so
* /usr/lib/libobs-frontend-api.so.0.0
* /usr/lib/libobsglad.so.0
* /usr/lib/libobs.so.0
* /usr/lib/libobs-opengl.so.0.0

**Comment by ahkok** [comment]
Chelsea is looking into this.

**Comment by gtkramer** [comment]
Fixed with obs-studio-24.0.3-5
