### ISSUE TITLE
lldb contains a broken symlink

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1502]
The following symlink in the lldb package is broken:

/usr/lib64/python3.7/site-packages/lldb/_lldb.so -> ../../../../lib64/liblldb.so

**Comment by thiagomacieira** [comment]
And the python dir is in the wrong place too (should be /usr/lib/pyton)

**Comment by thiagomacieira** [comment]
Fixed in clearlinux-pkgs/lldb 9.0.0-3

**Comment by AthenasJimenez** [comment]
Closing since seems to be fixed. Please reopen if needed
