### ISSUE TITLE
kubernetes services are missing their corresponding binaries

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1505]
The following services:
* kube-apiserver.service
* kube-scheduler.service
* kube-controller-manager.service
* kube-proxy.service

Are missing their corresponding binaries when in a minimal environment installing only the cloud-native-basic bundle:
* /usr/bin/kube-apiserver
* /usr/bin/kube-scheduler
* /usr/bin/kube-controller-manager
* /usr/bin/kube-proxy

**Comment by mythi** [comment]
These are the control plane components and they're not run via systemd. The bug is that the service files exist.

See #203.

**Comment by gtkramer** [comment]
@hnanni ah, so it looks like we don't want these service files at all

**Comment by mythi** [comment]
@gtkramer Some time back @bryteise moved the binaries to `kubernetes-extras` but the service files are still packaged in `kubernetes-services`.

Would adding the service files in extras work with autospec?

```
$ for i in `cat extras`; do echo /usr/lib/systemd/system/`basename $i`.service; done >> extras
$ make autospec
```

**Comment by hnanni** [comment]
> Would adding the service files in extras work with autospec?

Yes. It works and then the service files will get into the -extras rpm along the binaries they refer to. I have this in the oven, just dealing with a complexity that arised with new rpmbuild version and go binaries
