### ISSUE TITLE
vgrive

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#1506]
> VGrive (though referred to as ‘egrive’ within the UI) is pitched as a Google Drive client (both back-end and front-end) that offers a “clean and minimalist GUI”. It is said to automatically detect changes in local and remote files so that it only syncs files when required. As any good cloud storage app should, VGrive also lets you pick the exact local folder to sync your cloud files to. This is handy if you want to sync your files to a removable device or another exotic location on you system.

https://github.com/bcedu/VGrive

> bcedu/VGrive is licensed under the
> GNU General Public License v3.0

**Comment by lebensterben** [comment]
>> VGrive (though referred to as ‘egrive’ within the UI) is pitched as a Google Drive client (both back-end and front-end) that offers a “clean and minimalist GUI”. It is said to automatically detect changes in local and remote files so that it only syncs files when required. As any good cloud storage app should, VGrive also lets you pick the exact local folder to sync your cloud files to. This is handy if you want to sync your files to a removable device or another exotic location on you system. ...

@nazar2sfive it's available as flatpak package.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
