### ISSUE TITLE
Zathura is missing necessary plugins (mupdf or poppler)

### ISSUE THREAD

**Issue by dtw-waleee** [clearlinux/distribution#1508]
Either [zathura-pdf-mupdf](https://pwmt.org/projects/zathura-pdf-mupdf/) and [mupdf](https://mupdf.com/), or [zathura-pdf-poppler](https://pwmt.org/projects/zathura-pdf-poppler/) and poppler (already bundled) is required by zathura to render a pdf. Otherwise all you get is a blank zathura window and the error messages:
> error: could not open plugin directory: /usr/lib64/zathura
> error: Unknown file type: 'application/pdf'

**Comment by phmccarty** [comment]
I will add zathura-pdf-poppler for zathura.

**Comment by phmccarty** [comment]
The upstream zathura project site seems to be unresponsive (504 Gateway Time-out), so I will try again at a later time.

**Comment by phmccarty** [comment]
The upstream site still seems to be down, so I will pull source from the github mirror instead.

**Comment by phmccarty** [comment]
I have added `zathura-pdf-poppler` and confirmed that it's working with zathura. It will be available in the `zathura` bundle.

Changes should be available within a couple of days.

**Comment by dtw-waleee** [comment]
Great! I guess you got it from their gitlab-instance instead? The main page still seems to be down.

**Comment by phmccarty** [comment]
[zathura-pdf-poppler](https://github.com/clearlinux-pkgs/zathura-pdf-poppler) is available in the `zathura` bundle starting with build `31800`.

@dtw-waleee I pulled from the github mirror of the gitlab instance, actually, since I think the gitlab instance was down as well. Appears to be back up now.
