### ISSUE TITLE
grpc package has orphan libraries in /usr/lib

### ISSUE THREAD

**Issue by salvadorteranochoa** [clearlinux/distribution#1510]
The grpc package has several orphan files in /usr/lib.
https://github.com/clearlinux-pkgs/grpc/blob/master/grpc.spec#L460
They must be placed somewhere else
https://github.com/clearlinux/openBBT/blob/master/any-bundle/clean_FHS.t#L40

**Comment by gtkramer** [comment]
Duplicated by #1499
