### ISSUE TITLE
Enable omstdout module for Rsyslog bundle

### ISSUE THREAD

**Issue by electrocucaracha** [clearlinux/distribution#1514]
I'm testing a component that requires to execute rsyslogd from a container. I'm getting the following error during its execution:
 
```
rsyslogd 8.1910.0: running as pid 1, enabling container-specific defaults, press ctl-c to terminate rsyslog                                                  
rsyslogd: could not load module 'omstdout.so', errors: trying to load module /usr/lib64/rsyslog/omstdout.so: /usr/lib64/rsyslog/omstdout.so: cannot open shared object file: No such file or directory [v8.1910.0 try https://www.rsyslog.com/e/2066 ]
rsyslogd: error during parsing file /etc/rsyslog/rsyslog.conf, on or before line 4: errors occured in file '/etc/rsyslog/rsyslog.conf' around line 4 [v8.1910.0 try https://www.rsyslog.com/e/2207 ]
rsyslogd: there are no active actions configured. Inputs would run, but no output whatsoever were created. [v8.1910.0 try https://www.rsyslog.com/e/2103 ]
rsyslogd: run failed with error -2103 (see rsyslog.h or try https://www.rsyslog.com/e/2103 to learn what that number means)  
```
According to the [official documentation](https://rsyslog.readthedocs.io/en/latest/configuration/modules/omstdout.html) this module was created for testing purposes but it's useful to have in container environments.

AFAIK, this enhancement requires to add the `--enable-omstdout` flag in the [spec file](https://github.com/clearlinux-pkgs/rsyslog/blob/8.1910.0-9/rsyslog.spec#L117)

**Comment by mrkz** [comment]
I Just pushed this change into our build infrastructure, this should be available in release **31700** (or later)

**Comment by phmccarty** [comment]
Fixed in release 31700.
