### ISSUE TITLE
Roon package

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/distribution#1516]
At the moment there is no Roon package available in Clearlinux. It would be very appreciated by a lot of music lovers if this package can be added.

More info: https://roonlabs.com/downloads.html

**Comment by lebensterben** [comment]
>At the moment there is no Roon package available in Clearlinux. It would be very appreciated by a lot of music lovers if this package can be added. ...

@JSEHV Roon is not available for Linux. Do you mean Roon Bridge or Roon Server? They could be installed via shell script and they're not open sourced.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
