### ISSUE TITLE
Please update the following R packages

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1518]
- [x] [rms](https://github.com/clearlinux-pkgs/R-rms) 5.1-3.1 to 5.1-4
- [x] [IRkernel](https://github.com/clearlinux-pkgs/R-IRkernel) 0.8.11 to 1.0.2

The following packages are included in R-basic:

- [x] [foreign](https://github.com/clearlinux/clr-bundles/blob/3843118a174166418af1d3c3b599ddf03a98fece/bundles/R-basic#L30) 0.8-71 to 0.8-72
- [x] [KernSmooth](https://github.com/clearlinux-pkgs/R/blob/d8feaef3f4a89a066530be802f6b5b28c5b87b3d/R.spec#L305-L328) 2.23-15 to 2.23-16
- [x] [mgcv](https://github.com/clearlinux-pkgs/R/blob/d8feaef3f4a89a066530be802f6b5b28c5b87b3d/R.spec#L910-L942) 1.8-28 to 1.8-31
- [x] [nlme](https://github.com/clearlinux-pkgs/R/blob/d8feaef3f4a89a066530be802f6b5b28c5b87b3d/R.spec#L943-L989) 3.1-140 to 3.1-142
- [x] [spatstat](https://github.com/clearlinux-pkgs/R-spatstat) 1.60-1 to 1.61-0
- [x] [survival](https://github.com/clearlinux-pkgs/R/blob/d8feaef3f4a89a066530be802f6b5b28c5b87b3d/R.spec#L1195-L1250) 2.44-1.1 to 3.1-7

**Comment by phmccarty** [comment]
@lebensterben R 3.6.2 (not integrated yet) provides several of the updates you need. So bumping the `R` package to 3.6.2 is the first step, since for example, `rms` cannot be updated without moving to the new version of `survival` (provided by the `R` package, as you have noted).

**Comment by phmccarty** [comment]
Also, there appears to be no `R-boot` package in Clear, just `R-bootstrap`, which you linked to. `R-bootstrap` is up-to-date, correct?

**Comment by lebensterben** [comment]
> Also, there appears to be no `R-boot` package in Clear, just `R-bootstrap`, which you linked to. `R-bootstrap` is up-to-date, correct?

I made a mistake here, `boot` and `bootstrap` are two packages.
`swupd search-file /usr/lib64/R/library/boot` shows that it's installed by `R-basic` bundle. But indeed I'm not able to find a `R-boot` package.

**Comment by phmccarty** [comment]
Updates for all the listed packages are merged and should be released in build `32030` or newer.

**Comment by lebensterben** [comment]
>Updates for all the listed packages are merged and should be released in build `32030` or newer.

@phmccarty thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by phmccarty** [comment]
For reference, here are links to the package updates in release `32030` to close this bug:
- [R](https://github.com/clearlinux-pkgs/R/commit/398ccdd3fb04bd61542cdb184eb13adaef5bd4a6) (covers the updates of `foreign`, `KernSmooth`, `mgcv`, `nlme`, and `survival`; `spatstat` was already updated in release `31870`)
- [R-rms](https://github.com/clearlinux-pkgs/R-rms/commit/031b2214ff2fd51f658e31f7449e8191adecd638)
- [R-IRkernel](https://github.com/clearlinux-pkgs/R-IRkernel/commit/c8d1ebbef080f4626211cf6f42c3a3e8a908d859)
