### ISSUE TITLE
`rstudio-server` not added to PATH

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1519]
After installing `R-rstudio-server` bundle, the following binary is not added to PATH:

`/usr/lib64/R/rstudio-server/bin/rstudio-server`

**Comment by bryteise** [comment]
Hrm this looks like it got jammed all in /usr/lib64/R and probably needs to be moved around a bit more as this isn't a typical R package.

**Comment by bryteise** [comment]
It looks like things in /bin shouldn't be in path but the service file should be used to start the server. Updated pushed for the next release.
