### ISSUE TITLE
Consider adding `rstudio-server.service` and `/etc/pam.d/rstudio` by default

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1520]
After installing `R-rstudio-server` bundle, please consider to add a system-wide service `rstudio-server.service` by default, which is available at `/usr/lib64/R/rstudio-server/extras/systemd/rstudio-server.service`.

Without it, when running `rstudio-server start`, an error occur that this file can not  be found. 

Also, please add `/etc/pam.d/rstudio` by default, which is available at `/usr/lib64/R/rstudio-server/extras/pam/rstudio`.

Without it, user cannot successfully login.

---

Actually, user also need to manually create `/etc/rstudio/rserver.conf` and `/etc/rstudio/rsession.conf`. But these two are documented.

But RStudio's documentation doesn't document `rstudio-server.service` and the pam settings. So it'd be really nice if these are installed by default.

**Comment by bryteise** [comment]
I updated the package to put the service and pam file in the correct system location.

**Comment by lebensterben** [comment]
Thanks @bryteise
