### ISSUE TITLE
[BBT][several bundles]undefines symbols under /usr/bin/alsatplg

### ISSUE THREAD

**Issue by arturo-garcia-garcia** [clearlinux/distribution#1525]
In build 31710, several bundles have symbols under /usr/bin/alsatplg

Some of the bundles are

- desktop
- desktop-autostart
- desktop-kde
- network-time-sensitive
- os-utils-gui
- software-defined-cokpit
- vnc-server

This seems to be the root casue

```
Updated packages:
     alsa-lib                            1.1.9-28        -> 1.2.1.1-29     

Changes in package alsa-lib (from 1.1.9-28 to 1.2.1.1-29):
     Arjan van de Ven - alsa-lib: Autospec creation for version 1.2.1.1
```

**Comment by thiagomacieira** [comment]
Fixed with alsa-utils 1.2.1-23.
