### ISSUE TITLE
Change default editor to Nano instead of VI

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1529]
Many Clear Linux tutorials have commands to edit conf files. All of these commands are using either `edit` or `sudoedit`. 

`sudo systemctl edit --full php-fpm.service `

Opens Vi, those who're not familiar with Vi are going to struggle when faced with this:

![Vi-Joys](https://user-images.githubusercontent.com/49221849/69809159-20678800-1224-11ea-8eec-5e1ebc653f44.png)

Vi is just too far `out there` in relation to typical user interactive known methods.
I mean, look, a user i going to try position the cursor and hit the delete key to remove text.

He's going to try to select text and hit delete, he's going to place cursor and control+v to paste in text...

He's going to scratch his head wondering what is going on, nothing is happening. He panics because he's cared he'll destroy the file. 

He's freaking out how to close the damned thing.

Who on earth is going to guess typing `:aq!` is going to quit Vi?

ahahaha OMG that is just too funny.

I suggest Nano as default it's actually rather sane and provides users a menu down the bottom with all the controls he's going to need.

Who even had a PC in 1976 anyway, LOL.
Consider most users, new users, not those weirdo Vi elitists ;-)

So can we consider `purging` `Vi` from distribution, have Nano as main editor, and for those who are so desperately dependant on Vi they can install a bundle?

**Comment by fenrus75** [comment]
we currently have a mixed default; nano is always installed and used,
unless vim is installed, then vim is used.
the idea was (and maybe this is indeed misguided) that if you installed
vim, you wanted vim...

**Comment by ketonik** [comment]
> we currently have a mixed default; nano is always installed and used, unless vim is installed, then vim is used. the idea was (and maybe this is indeed misguided) that if you installed vim, you wanted vim...
> […](#)

Hi Arjan,
Thanks for reply,

This explanation has been helpful, it lead me to examine my system. 

It's apparent now, someone else has installed vim without my authority and with telling me, since it's been installed as a bundle it's hijacked the system and taken over as the default editor.

I supposed you can close the request.

**Comment by lebensterben** [comment]
Either of Emacs and Vi has far more users than nano.
Most IDE supports Emacs and Vi keys, like IntellijIdea, VSCode, Jupyter Notebook, etc.

The line editing feature of bash supports two sets of key bindings, emacs-mode and vi-mode. Yep, there is no nano mode. 

Nano is actually the least sane default, given that most users will not likely to be exposed to nano, or its keybindings.




<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ketonik** [comment]
I think your'e have a different purpose in mind here. As mentioned, editing conf files, a few lines here and there, most users will not be doing anything advanced requiring what use you mentioned. If you're doing much more than conf editing you'll be taking files off the server and editing locally in a real code app not in vim or emacs, come on, let's be real here.

Would you seriously use vim to edit code in repositories on github, LOL I thought not.

**Comment by fenrus75** [comment]
editors are like vegetables, some folks like broccoli, others like
tomatoes.... you can't argue about taste

that's why we ship multiple and made it so that for EDITOR environment
variable, where we have to set some default do "nano unless vim is
installed".

nano is nice and small so it can be in the bare bones OS install always,

**Comment by lebensterben** [comment]
>I think you have a different purpose in mind here. As mentioned, editing conf files, a few lines here and there, most users will not be doing anything advanced requiring what use you mentioned. If you're doing much more than conf editing you'll be taking files off the server and editing locally in a real code app not in vim or emacs, come on, let's be real here. ...

@ketonik
What I said is specifically for users who are not familiar with CLI in general.

Suppose you use shell often, you're very likely to know nano, vi, emacs, ed, and whatever editor.

For users who rarely works in shell, these editors are equally not likely to be used. But Vi and Emacs key bindings are almost everywhere. So even if you never use vi or Emacs, you are more likely to be exposed to them, than to nano.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lebensterben** [comment]
The rule of thumb is, shell programs that use vi keys are easier to use than those who aren't.
Examples are less vs. more, and man vs. info.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ketonik** [comment]
> @ketonik
> What I said is specifically for users who are not familiar with CLI in general.

Responding to this because i'm wasting time not for any other value, because there is nothign of value here.

So, I don't know what's going on dude, either i'm drunk or blind or fail to comprehend the above.

Specifically, users not familiar with CLI in general, right? That's your point yea?

Okay

So given that statement, these users you specify, not familiar with CLI they'd be cool and know what to do when presented with this thing below right?

![Vi-Joys](https://user-images.githubusercontent.com/49221849/69828166-b36ce600-1255-11ea-9ba5-efeb61c5c0d9.png)
 
Got my doubts man, even if I was Chinese, i'm sure i'd never think about `:aq!` to quit! LOL that's just away out there funny.

ahaha, tilde for line ahaha nah man people not familiar with CLI are not going have joy here.

Anyway, this thread ought to be deleted, it's a waste of cells on an SSD.
