### ISSUE TITLE
netcat version shipped does not support -U (unix sockets) option - prevents libvirtd from being remotely managed

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#153]
(copied from https://github.com/clearlinux/common/issues/10)

### What is the issue type?

* [x] Bug report
* [ ] Enhancement request

### Describe the problem

virt-manager relies on the target remote hypervisor to bind to a unix socket via a netcat pipe.

The netcat binary shipped in clearlinux does not support this option. Please rebuild/ship with a version supporting this.

**Comment by fenrus75** [comment]
we've added "real" netcat
next step is making sure this all works together

**Comment by ahkok** [comment]
please use `ncat`

**Comment by hugleo** [comment]
But how? Seems like virt-manager uses a hard-coded command similar to ssh user@192.168.0.1 'nc -U'.

The only way that I can find is to remove nc and use something like to ln -s /usr/bin/ncat /usr/bin/nc
