### ISSUE TITLE
avahi-daemon fails to start

### ISSUE THREAD

**Issue by desvdp** [clearlinux/distribution#1533]
Hi, I've been trying to get the avahi-daemon to work but I'm still running into issues. The errors point to DBUS access policies, but after doing some debugging I ran into some oddities, maybe they're intentional:
- /usr/share/dbus-1/system.conf references a /etc2/ dir ... shouldn't this be /etc ?
- when starting the daemon a chroot happens, it seems to look for /var/lib/avahi (is it referencing avahi's home dir?) which doesn't exist

To reproduce: 
- start from a mint clear linux (I'm using 31770)
- add the avahi-daemon bundle
- start the avahi-daemon service using systemctl
- check the status
debugging: 
- run avahi-daemon --debug ... 
- fix the 2 items above (rename etc2 to etc in the conf file and create the missing dir) 
- again run avahi-daemon --debug ...

**Comment by desvdp** [comment]
How to make it work for now (in such swupd repair doesn't break it): 
- create an /etc2/dbus-1 folder with the desired configuration files. (note this can even be a symbolic link to /etc/dbus-1)  
- create a /var/lib/avahi/services folder with the desired services . 

test using  avahi-daemon --debug

**Comment by ahkok** [comment]
`/etc2` is definitely a bug I will try to address...

**Comment by ahkok** [comment]
`dbus-1.12.16-73` will fix the `/etc2` path - you'll have to move it back to `/etc/` :)

**Comment by ahkok** [comment]
` /var/lib/avahi/services` is empty by default since we wanted to create a very secure default avahi setup, and that means not enabling services by default either.

We can create the folder, but it would be empty.

FWIW what permissions/ownership did you gave it? just `root` / `0755` ?

**Comment by desvdp** [comment]
Hi @ahkok , thanks for fixing /etc. 
It would be good to create an empty folder to prevent the daemon throwing errors. Right now my /var/lib/avahi services has root/755 permission (partially because I didn't pay much attention to it, partially because other distros seems to do same). Since the deamon runs as the avahi user (not root), that will need access for sure.   
Let me know when it's available: I'm happy to test it for you. 

PS: would it be possible to add https://github.com/lathiat/nss-mdns to the avahi-daemon package at some point?
Rationale: the avahi daemon itself registers the service, the nss-mdns makes it locally available to resolve names through nsswitch. In the current distro the systemd-resolved would be capable of resolving mdns, but when enbled there's quite some warnings about 2 name resolution systems being present. Having avahi-deamon + nss-mdns would be a 1-stop solution capable of registering services plus resolving names locally (where systemd-resolved can only resolve them) 

Thanks !

**Comment by ahkok** [comment]
Looks like the folder is already created automatically:

https://github.com/clearlinux-pkgs/avahi/blob/master/avahi.tmpfiles

**Comment by ahkok** [comment]
Please open a separate request for `nss-mdns`.

**Comment by desvdp** [comment]
Will do, thanks !

**Comment by john-belstner** [comment]
I'm up to date with version 33540 and still having the nss-mdns issue.  Was there every any resolution?

avahi-daemon 0.8 starting up.
chroot.c: chroot() helper started
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
dbus_bus_request_name(): Connection ":1.476" is not allowed to own the service "org.freedesktop.Avahi" due to security policies in the configuration file
WARNING: Failed to contact D-Bus daemon.
chroot.c: chroot() helper got command 0d
avahi-daemon 0.8 exiting.

**Comment by hacketiwack** [comment]
> I'm up to date with version 33540 and still having the nss-mdns issue. Was there every any resolution?
> 
> avahi-daemon 0.8 starting up.
> chroot.c: chroot() helper started
> WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
> dbus_bus_request_name(): Connection ":1.476" is not allowed to own the service "org.freedesktop.Avahi" due to security policies in the configuration file
> WARNING: Failed to contact D-Bus daemon.
> chroot.c: chroot() helper got command 0d
> avahi-daemon 0.8 exiting.

I finally managed to make this `avahi-daemon` work.

1. Create the folder `/var/lib/avahi`
2. Create the folder `/var/lib/avahi/services`
3. Create the file `/etc/dbus-1/system-local.conf` with the following content
```
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <policy context="default">
    <allow own="org.freedesktop.Avahi" />
  </policy>
</busconfig>
```
4. Override the configuration of avahi-daemon.service with: `sudo systemctl edit avahi-daemon` with the following content:
```
[Unit]
After=network-online.target
```
5. Comment out the ridiculous default configuration that is in the file `/usr/share/defaults/etc/avahi/avahi-daemon.conf`
The problem with the point 4 is that it will be destroyed whenever the avahi-daemon will be updated.
I didn't find any way yet to override this file.
6. Optionally add your service files into the directory /var/lib/avahi/services
7. Enable the daemon with: sudo systemctl enable avahi-daemon
8. Start the daemon with: sudo systemctl start avahi-daemon

I hope I didn't miss anything and that it will help someone :-)
