### ISSUE TITLE
nfs-server fails to start

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1535]
After the last updates the nfs-server stopped working:

A dependency job for nfs-server.service failed. See 'journalctl -xe' for details.

● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/generator/nfs-server.service.d
           └─order-with-mounts.conf
   Active: inactive (dead)

Dec 01 21:22:03 b1 systemd[1]: Dependency failed for NFS server and services.
Dec 01 21:22:03 b1 systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.

These dependency services failed:

● nfs-mountd.service - NFS Mount Daemon
   Loaded: loaded (/usr/lib/systemd/system/nfs-mountd.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-12-01 21:22:03 WITA; 1min 7s ago
  Process: 2363 ExecStart=/usr/sbin/rpc.mountd (code=exited, status=1/FAILURE)

Dec 01 21:22:03 b1 systemd[1]: Starting NFS Mount Daemon...
Dec 01 21:22:03 b1 rpc.mountd[2363]: Cannot register service: RPC: Authentication error; why = Client credential too weak
Dec 01 21:22:03 b1 rpc.mountd[2363]: unable to register (mountd, 1, udp).
Dec 01 21:22:03 b1 systemd[1]: nfs-mountd.service: Control process exited, code=exited, status=1/FAILURE
Dec 01 21:22:03 b1 systemd[1]: nfs-mountd.service: Failed with result 'exit-code'.
Dec 01 21:22:03 b1 systemd[1]: Failed to start NFS Mount Daemon.

● rpc-statd.service - NFS status monitor for NFSv2/3 locking.
   Loaded: loaded (/usr/lib/systemd/system/rpc-statd.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2019-12-01 21:22:03 WITA; 2min 25s ago
  Process: 2352 ExecStart=/usr/sbin/rpc.statd (code=exited, status=1/FAILURE)

Dec 01 21:22:03 b1 systemd[1]: Starting NFS status monitor for NFSv2/3 locking....
Dec 01 21:22:03 b1 rpc.statd[2354]: Version 2.3.4 starting
Dec 01 21:22:03 b1 rpc.statd[2354]: Flags:
Dec 01 21:22:03 b1 rpc.statd[2354]: Failed to read /run/nfs/state: Success
Dec 01 21:22:03 b1 rpc.statd[2354]: Initializing NSM state
Dec 01 21:22:03 b1 rpc.statd[2354]: Running as root.  chown /run/nfs to choose different user
Dec 01 21:22:03 b1 rpc.statd[2354]: unable to register (statd, 1, udp).
Dec 01 21:22:03 b1 systemd[1]: rpc-statd.service: Control process exited, code=exited, status=1/FAILURE
Dec 01 21:22:03 b1 systemd[1]: rpc-statd.service: Failed with result 'exit-code'.
Dec 01 21:22:03 b1 systemd[1]: Failed to start NFS status monitor for NFSv2/3 locking..

I can do a workaround with:

sudo systemctl stop rpcbind
sudo -i rpcbind -i -w
sudo systemctl start rpcbind
sudo systemctl start nfs-server

but I do not think it a good solution, thx

**Comment by seafrog1** [comment]
Maybe I should add below as possible reason:
● systemd-boot-system-token.service - Store a System Token in an EFI Variable
   Loaded: loaded (/usr/lib/systemd/system/systemd-boot-system-token.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2019-12-02 13:55:21 WITA; 50min ago
     Docs: man:systemd-boot-system-token.service(8)
 Main PID: 455 (code=exited, status=1/FAILURE)

Dec 02 13:55:21 b1 systemd[1]: Starting Store a System Token in an EFI Variable...
Dec 02 13:55:21 b1 bootctl[455]: Couldn't find EFI system partition. It is recommended to mount it to /boot or /efi.
Dec 02 13:55:21 b1 bootctl[455]: Alternatively, use --esp-path= to specify path to mount point.
Dec 02 13:55:21 b1 systemd[1]: systemd-boot-system-token.service: Main process exited, code=exited, status=1/FAILURE
Dec 02 13:55:21 b1 systemd[1]: systemd-boot-system-token.service: Failed with result 'exit-code'.
Dec 02 13:55:21 b1 systemd[1]: Failed to start Store a System Token in an EFI Variable.

**Comment by bryteise** [comment]
The work-around isn't quite making sense to me as the rpcbind daemon you launched outside of systemd seems like it would prevent the rpcbind.socket from being created (this is what happens when I try and do this myself though I had rpcbind running in the foreground). The errors in your log that pop out to me are:

`Dec 01 21:22:03 b1 rpc.mountd[2363]: Cannot register service: RPC: Authentication error; why = Client credential too weak`

`Dec 01 21:22:03 b1 rpc.statd[2354]: unable to register (statd, 1, udp).`

Which make me wonder what the status of the `rpcbind.service` is before and after you try and start the `nfs-server.service` .

**Comment by seafrog1** [comment]
The rpcbind is active before starting the nfs-server
● rpcbind.service - RPC bind service
   Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-12-03 10:40:19 WITA; 54s ago
  Process: 500 ExecStart=/sbin/rpcbind -w (code=exited, status=0/SUCCESS)
 Main PID: 508 (rpcbind)
    Tasks: 1
   Memory: 912.0K
   CGroup: /system.slice/rpcbind.service
           └─508 /sbin/rpcbind -w

Dec 03 10:40:19 b1 systemd[1]: Starting RPC bind service...
Dec 03 10:40:19 b1 systemd[1]: Started RPC bind service.

At this time only the systemd-boot-system-token.service is failing, pls see my 2nd comment

**Comment by bryteise** [comment]
That seems odd it would cause nfs to not start but just a quick test, mind `systemctl mask systemd-boot-system-token.service` and rebooting?

**Comment by seafrog1** [comment]
rpcbind works:
● rpcbind.service - RPC bind service
   Loaded: loaded (/usr/lib/systemd/system/rpcbind.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-12-03 14:01:16 WITA; 4min 58s ago
 Main PID: 493 (rpcbind)
    Tasks: 1
   Memory: 992.0K
   CGroup: /system.slice/rpcbind.service
           └─493 /sbin/rpcbind -w

Dec 03 14:01:16 b1 systemd[1]: Starting RPC bind service...
Dec 03 14:01:16 b1 systemd[1]: Started RPC bind service.

nfs-server fails
● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/generator/nfs-server.service.d
           └─order-with-mounts.conf
   Active: inactive (dead)

Dec 03 14:02:02 b1 systemd[1]: Dependency failed for NFS server and services.
Dec 03 14:02:02 b1 systemd[1]: nfs-server.service: Job nfs-server.service/start failed with result 'dependency'.

nfs-mountd fails (also)
● nfs-mountd.service - NFS Mount Daemon
   Loaded: loaded (/usr/lib/systemd/system/nfs-mountd.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-12-03 14:02:04 WITA; 184ms ago
  Process: 2189 ExecStart=/usr/sbin/rpc.mountd (code=exited, status=1/FAILURE)

Dec 03 14:02:04 b1 systemd[1]: Starting NFS Mount Daemon...
Dec 03 14:02:04 b1 rpc.mountd[2189]: Cannot register service: RPC: Authentication error; why = Client credential too weak
Dec 03 14:02:04 b1 rpc.mountd[2189]: unable to register (mountd, 1, udp).
Dec 03 14:02:04 b1 systemd[1]: nfs-mountd.service: Control process exited, code=exited, status=1/FAILURE
Dec 03 14:02:04 b1 systemd[1]: nfs-mountd.service: Failed with result 'exit-code'.
Dec 03 14:02:04 b1 systemd[1]: Failed to start NFS Mount Daemon.

Thx

**Comment by ahkok** [comment]
if the `-i` option is required or needed, you can always `sudo systemctl edit --full nfs-mountd.service` and add it.

I've spent 30 minutes now attempting to find the origin of the error message `Cannot register service: RPC: Authentication error; why = Client credential too weak` in source code, and I can not locate it yet... yikes.

**Comment by ahkok** [comment]
Note: **I do not recommend passing the `-i` flag**. It is literally named the `insecure` flag for a reason.

**Comment by ahkok** [comment]
Looks like the error messages are returned by `glibc`. I don't see relevant changes anywhere that explain this change in behavior, though.

**Comment by seafrog1** [comment]
I didn't double check for some days as the workaround worked fine, but after checking now the  problem is gone sorry but I can not say by which update. Thx to all and a good 2020.
