### ISSUE TITLE
ipmctl tools

### ISSUE THREAD

**Issue by chiachuanwu** [clearlinux/distribution#1537]
ipmctl show -memoryresources" command show invalid PCD data.
the full log as below:
One or more DIMMs have invalid PCD data. A platform reboot is recommended to restore valid PCD data, then try again.

**Hardware Condition:**
Latest Intel Xeon processor
Second generation Intel Optane DIMM.

**Clear version:**
v31640

**Comment by ahkok** [comment]
https://github.com/intel/ipmctl/issues/123

Let's track this upstream.

**Comment by eadamsintel** [comment]
I know this issue is old but I just ran into it.  I downgraded Clear Linux to 31410 and it worked for me.
