### ISSUE TITLE
conntrack required for Kubernetes and/or crio

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#1538]
On a Clear Linux 31770 installation of Kubernetes with the bundles "cloud-native-basic containers-basic" I just found this warning:
```
$ cat /tmp/crio.pmem-csi-pmem-govm-worker3.root.log.WARNING.20191203-071943.9938 
Log file created at: 2019/12/03 07:19:43
Running on machine: pmem-csi-pmem-govm-worker3
Binary: Built with gc go1.13.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1203 07:19:43.304570    9938 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
```

This is from https://github.com/kubernetes/kubernetes/blob/95a3cd54cf739019b1211163add7247bd31c0ed7/pkg/kubelet/dockershim/network/hostport/hostport_manager.go#L69

Upstream Kubernetes added conntrack as dependency of their packages in https://github.com/kubernetes/kubeadm/issues/1287

I'm not sure how this messages ended up in a cri-o (?) log file in /tmp and `journalctl -u kubelet` does not show it, but nonetheless it seems useful to include `conntrack` in the cloud-native-basic bundle to avoid these "failures in network connection cleanup".

Alternatively, the network-basic bundle can be installed, but it's relatively big and cloud-native-basic should be fully functional out-of-the-box.

**Comment by ahkok** [comment]
@CraigSterrett is this something we can add to `cloud-native-basic`? @mythi ?

Package is `conntrack-tools`

**Comment by hnanni** [comment]
I've added conntrack-tools as a kubernetes runtime req (in requires_add)
