### ISSUE TITLE
GNU Info directory node missing (statelessness problem)

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#1539]
Problem: running `info` with no arguments fails to show the list of manuals. When using Emacs's Info viewer (`M-x info` or `C-h i`), it says "Can't find the Info directory node". Indeed, /usr/share/info/dir is missing.

Packages installing TexInfo sources to /usr/share/info need to run /sbin/install-info to update this file.

Obviously for Clear, this file shouldn't be modified. A simple solution would be to make it a symlink to /var/lib/info/dir, which does get updated. But how to make it be updated?

**Comment by ahkok** [comment]
Does emacs invoke `info` or does it have its own code to read indices? We might need to patch...

**Comment by thiagomacieira** [comment]
It has its own code.

**Comment by thiagomacieira** [comment]
Duh, I'd already reported this. #1111
