### ISSUE TITLE
f2fs support

### ISSUE THREAD

**Issue by jannisch** [clearlinux/distribution#154]
### What is the issue type?

* [ ] Bug report
* [x] Enhancement request

### Describe the problem
f2fs is the fastest file system in most benchmarks on SSDs and has been out for a while. Furthermore, it has the same file-encryption features as ext4 so it is a great choice for most setups. I guess in order to support it
1. kernel config would have to be changed
2. [f2fs-tools](https://git.kernel.org/pub/scm/linux/kernel/git/jaegeuk/f2fs-tools.git/) would need to be packaged

**Comment by jannisch** [comment]
Oh sorry I totally forgot to reply!
Apparently the performance of ext4 has been significantly improved since I checked the last time and the fastest filesystem now varies from benchmark to benchmark on Phoronix ([example benchmark](https://www.phoronix.com/scan.php?page=article&item=linux-416-fs)).
[This benchmark](https://www.phoronix.com/scan.php?page=article&item=linux-900p-fs) on an Intel Optane SSD however concludes that f2fs is the overall winner.
So to be honest I now think that this not a big deal any more if you want to limit the number of supported filesystems.

**Comment by puneetse** [comment]
I also hadn't realized how far ext4 performance has come but I'd like to see F2FS enabled too based on [Phoronix's Linux 5.0 File-System Benchmarks: Btrfs vs. EXT4 vs. F2FS vs. XFS](https://www.phoronix.com/scan.php?page=article&item=linux-50-filesystems)

**Comment by miguelinux** [comment]
@jannisch, @puneetse 

F2FS is set as module in CL kernel. you can test the performance now.

**Comment by ahkok** [comment]
We did not have the tools properly bundled yet. It'll go into the `storage-utils` bundle.
