### ISSUE TITLE
package and add "xss-lock" to desktop-i3 bundle

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#1541]
xss-lock seems to be the preferred way of using i3lock to lock the screen on system sleep / suspend

https://wiki.archlinux.org/index.php/Session_lock#xss-lock

Would it be possible to package xss-lock and add it to the desktop-i3 bundle please?

https://packages.debian.org/jessie/x11/xss-lock

**Comment by curantes** [comment]
I have packed it and sent for review to clearlinux devs. This project is not very active and latest commit was back in 2014. So not sure they will accept it since they usually want active upstream.

**Comment by bryteise** [comment]
This should have been added a bit ago, sorry just getting back to the issue X(.
