### ISSUE TITLE
Suddenly Clearlinux stuck at boot (desktop init) 

### ISSUE THREAD

**Issue by s77rt** [clearlinux/distribution#1547]
Hi,
Suddenly Clearlinux is stuck at boot ( it does not start the gui ) 
All what i can see is the mouse cursor (can't be moved) and the _ symbol at the top corner. 
I tried removing the 'quite' command from kernel and booting into bash, but nothing i can do from there (tried startx, but got a no connection to host problem) 
Any help is appreciated. 
Thanks

![IMG_20191206_101622](https://user-images.githubusercontent.com/16493223/70311555-222bdf80-1812-11ea-8229-cd89073c99f3.jpg)
(sorry for image quality)

**Comment by andrejp-nuc** [comment]
Some info about this bug there:
https://github.com/clearlinux/distribution/issues/1543

**Comment by andrejp-nuc** [comment]
as workaround you can do this:
https://github.com/clearlinux/distribution/issues/1543#issuecomment-562295221

**Comment by s77rt** [comment]
@andrejp-nuc Thanks!
