### ISSUE TITLE
terminal displaying wrong date format in reference to locale date_fmt

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1551]
A nagging annoyance I have for some time, is on Clear Linux Live Server install.
I'm in Australia, there was never an Australian region to select in the installer.

So I'm stuck with this illogical date format on the terminal.

My macOS machine was smart enough to change `locale` to `en_AU.UTF-8`

My Clear Linux Server `locale` is all `en_US.UTF-8`

Yet I run:
 `locale date_fmt`
it reveals:
`%a %d %b %Y %r %Z`
human readable this is:
`%a` weekday
`%d` day of month
`%b` abbreviated month
`%Y` year including century
`%r` a.m or p.m
`%Z` timezone 

`Mon 09 Dec 2019 08:30:04 p.m AEST`

(according to IBM Date and time format reference - strftime)

My terminal after ssh to Clear Linux date format is not this at all:
`Mon Dec 09`

Day, Month, Date,

I think it is reasonable to suggest that, human readable logical date format should be the sequence of frequency, but this isn't really the point of conversation.

The point is, trying to establish the missing links between `system locale` and and what terminal displays, it's plain to see, there's no connection.

Second point will be how to change system locale to, well local locale, Australia, and after this is done why doesn't it affect terminal prompt date format.

Probably there is some other tool to control the terminals date format display, All i could find was ANSI standards and none of those had any parameters to alter the date format. 

I run `locale`  
Clear Linux responds with output:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I run `locale`  
macOS responds with output:
```
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
```

It's apparent `locale` settings have no affect on terminal prompt formatting.

So must be something else defining terminal display, i'm unable to discover yet what tool does control terminal. As mentioned i've not read any source providing bash profile codes to change the format.

Not sure what is going on, because I see logs in different formats again, typically YYYY-MM-DD which for data output is logically necessary to allow chronologically correct order. Obviously in this case `locale` isn't globally binding.

I run `date`
I get:
`Mon 09 Dec 2019 08:30:04 PM AEDT`

So it seems there's loads of different date/time formats used al over the place.

Is there a tool to set date/time formats globally?

**Comment by ahkok** [comment]
`man localectl` explains most of this. `sudo localectl set-locale en_AU.UTF-8` followed by a reboot should work.

**Comment by thiagomacieira** [comment]
Please reopen if the localectl command doesn't work.
