### ISSUE TITLE
fwupdmgr get-updates fails to update metadata

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#1552]
```bash
$ sudo swupd bundle-add firmware-update
Loading required manifests...
Downloading packs (6.91 MB) for:
 - firmware-update
 [100%]

Finishing packs extraction...
Validate downloaded files
 [100%]

No extra files need to be downloaded
 [100%]

Installing files...
 [100%]

Calling post-update helper scripts
Successfully installed 1 bundle
$ fwupdmgr get-updates
Firmware metadata has not been updated for 30 days and may not be up to date.

Update now? (Requires internet connection) [y|N]: y
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
Downloading…             [***************************************]
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc

Failed to update metadata for lvfs: Error opening directory “/etc/pki/fwupd-metadata”: No such file or directory
```

@superm1 is this something I have broken myself? or related to #1479 ?

**Comment by superm1** [comment]
@xlfe it looks like according to https://github.com/clearlinux/distribution/issues/1479#issuecomment-553041751 there should have been a tmpfiles snippet that populated `/etc/pki`.

I see it here too: https://github.com/clearlinux-pkgs/fwupd/blob/master/fwupd.tmpfiles

**Comment by ahkok** [comment]
We create `/etc/fwupd/pk`i, not `/etc/pki`. Looks like a path config issue

**Comment by seafrog1** [comment]
after 31930 fwupd daemon fails to start:

● fwupd.service - Firmware update daemon
   Loaded: loaded (/usr/lib/systemd/system/fwupd.service; static; vendor preset: disabled)
   Active: failed (Result: timeout) since Wed 2019-12-18 21:34:26 WITA; 9ms ago
     Docs: https://fwupd.org/
  Process: 237743 ExecStart=/usr/libexec/fwupd/fwupd (code=killed, signal=TERM)
 Main PID: 237743 (code=killed, signal=TERM)

Dec 18 21:32:51 b1 systemd[1]: Starting Firmware update daemon...
Dec 18 21:32:51 b1 fwupd[237743]: ERROR:esys:src/tss2-esys/esys_context.c:69:Esys_Initialize() Initialize default tcti. ErrorCode (0x000a000a)
Dec 18 21:32:51 b1 fwupd[237743]: 13:32:51:0210 FuPluginVliUsbhub    cannot create I²C device: failed to read versions: failed to read I2C: endpoint stalled or request not supported
Dec 18 21:34:21 b1 systemd[1]: fwupd.service: start operation timed out. Terminating.
Dec 18 21:34:26 b1 systemd[1]: fwupd.service: Failed with result 'timeout'.
Dec 18 21:34:26 b1 systemd[1]: Failed to start Firmware update daemon.

Sorry.

**Comment by seafrog1** [comment]
after 31940 fwupd daemon starts, so failure as mentioned above

**Comment by xlfe** [comment]
ping @fenrus75 @superm1 @ahkok 32180 same error :(

Should it have been fixed or have I broken it somehow? 

> Failed to update metadata for lvfs: Error opening directory “/etc/pki/fwupd-metadata”: No such file or directory

**Comment by cdplayer** [comment]
`$ uname -a`
Linux klear 5.4.14-897.native #1 SMP Thu Jan 23 11:17:16 PST 2020 x86_64 GNU/Linux

`$ fwupdmgr --version`
client version:	1.3.4
compile-time dependency versions
	gusb:	0.2.11
	efivar:	36
daemon version:	1.3.4

`$ sudo swupd diagnose`
Password: 
Diagnosing version 32180
Downloading missing manifests...

Checking for missing files
 [100%]


Checking for corrupt files
 [100%]


Checking for extraneous files
 [100%]

Inspected 740217 files

Diagnose successful


`$ fwupdmgr refresh -v`
fwupdmgr:1261): FuCommon-DEBUG: 08:27:41.736: creating path /home/chrisd/.cache/fwupd
(fwupdmgr:1261): Fwupd-DEBUG: 08:27:41.739: looking for os-release at /etc/os-release
(fwupdmgr:1261): FuMain-DEBUG: 08:27:41.739: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz to /home/chrisd/.cache/fwupd/lvfs-metadata.xml.gz
Fetching metadata https://cdn.fwupd.org/downloads/firmware.xml.gz
(fwupdmgr:1261): GLib-GIO-DEBUG: 08:27:41.747: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.747: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.747: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.747: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.747: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.747: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
(fwupdmgr:1261): GLib-GIO-DEBUG: 08:27:41.747: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ‘gio-proxy-resolver’
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.749: watch_established: "/system/proxy/" (establishing: 1)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.749: watch_established: "/system/proxy/http/" (establishing: 1)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.749: watch_established: "/system/proxy/https/" (establishing: 1)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.749: watch_established: "/system/proxy/ftp/" (establishing: 1)
(fwupdmgr:1261): dconf-DEBUG: 08:27:41.749: watch_established: "/system/proxy/socks/" (establishing: 1)
(fwupdmgr:1261): GLib-GIO-DEBUG: 08:27:41.749: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
(fwupdmgr:1261): FuMain-DEBUG: 08:27:41.873: progress: 0%
Downloading…             [-                                      ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.873: progress: 1%
Downloading…             [                                       ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.873: progress: 2%
Downloading…             [                                       ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.873: progress: 4%
Downloading…             [*                                      ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.874: progress: 5%
Downloading…             [*                                      ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.889: progress: 6%
Downloading…             [**                                     ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.889: progress: 7%
Downloading…             [**                                     ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.889: progress: 8%
Downloading…             [***                                    ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.890: progress: 9%
Downloading…             [***                                    ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.890: progress: 10%
Downloading…             [***                                    ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.890: progress: 11%
Downloading…             [****                                   ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.891: progress: 12%
Downloading…             [****                                   ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.906: progress: 16%
Downloading…             [******                                 ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.906: progress: 19%
Downloading…             [*******                                ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.909: progress: 22%
Downloading…             [********                               ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.909: progress: 26%
Downloading…             [**********                             ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.911: progress: 29%
Downloading…             [***********                            ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.911: progress: 32%
Downloading…             [************                           ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.914: progress: 35%
Downloading…             [*************                          ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.914: progress: 39%
Downloading…             [***************                        ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.923: progress: 42%
Downloading…             [****************                       ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.923: progress: 45%
Downloading…             [*****************                      ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.924: progress: 49%
Downloading…             [*******************                    ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.924: progress: 52%
Downloading…             [********************                   ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.926: progress: 55%
Downloading…             [*********************                  ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.926: progress: 59%
Downloading…             [***********************                ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.928: progress: 62%
Downloading…             [************************               ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.928: progress: 65%
Downloading…             [*************************              ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.929: progress: 69%
Downloading…             [**************************             ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.930: progress: 72%
Downloading…             [****************************           ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.931: progress: 75%
Downloading…             [*****************************          ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.931: progress: 78%
Downloading…             [******************************         ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.938: progress: 82%
Downloading…             [*******************************        ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.938: progress: 85%
Downloading…             [*********************************      ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.940: progress: 88%
Downloading…             [**********************************     ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.941: progress: 92%
Downloading…             [***********************************    ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.942: progress: 95%
Downloading…             [*************************************  ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.943: progress: 98%
Downloading…             [************************************** ](fwupdmgr:1261): FuMain-DEBUG: 08:27:41.943: progress: 100%
Downloading…             [***************************************]
(fwupdmgr:1261): FuMain-DEBUG: 08:27:41.950: downloading https://cdn.fwupd.org/downloads/firmware.xml.gz.asc to /home/chrisd/.cache/fwupd/lvfs-metadata.xml.gz.asc
Fetching signature https://cdn.fwupd.org/downloads/firmware.xml.gz.asc
(fwupdmgr:1261): FuMain-DEBUG: 08:27:41.966: progress: 100%

Failed to update metadata for lvfs: Error opening directory “/etc/pki/fwupd-metadata”: No such file or directory

**Comment by ahkok** [comment]
> Failed to update metadata for lvfs: Error opening directory “/etc/pki/fwupd-metadata”: No such file or directory

That path is incorrect, it should be `/etc/fwupd/pki/fwupd-metadata`. I'll need to fix...

**Comment by ahkok** [comment]
Unless it *modifies* it. In that case, this all should go into `/var` and not `/etc` nor `/usr/share`....

**Comment by ahkok** [comment]
Hmm, from the code it doesn't appear to modify it..

**Comment by ahkok** [comment]
`fwupd-1.3.4-42` - tested and this works - We patch the code to read the proper path where the metadata rests.

**Comment by superm1** [comment]
For the out of the box configuration that's absolutely fine. It's when someone sets up their own mirror or repository with its own key that they would need go write to that directory to load their key.
