### ISSUE TITLE
Request podman and slirp4netns

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#1565]
There is a new [guide ](https://github.com/kata-containers/documentation/pull/565)from the Kata team on setting up rootless execution with podman with the kata runtime.   I was able to get this guide to work on Clear Linux but had to build podman and slirp4netns from scratch. 

I tried to do this with autospec and had good luck with slirp4netns using `make autospecnew URL="https://github.com/rootless-containers/slirp4netns/archive/v0.4.2.tar.gz" NAME="slirp4netns"`  I did have to create a `slirp4netns.license` with the GPL v2 listed on their GitHub.  I ran into a lot of go dependencies with `podman` when trying autospec and am not sure how to resolve.

I suggest these packages make the most sense in the `containers-basic` bundle.

**Comment by ahkok** [comment]
Duplicate of #763 ?

**Comment by eadamsintel** [comment]
Yes. I missed that when I checked.  Slirp4netns is also needed for rootless podman with Kata. I can edit the title to make this just for slirp4netns or update the other issue with that request.

**Comment by ganeshmaharaj** [comment]
@eadamsintel a tad bit late, but we should have rootless podman working with latest releases. Mind checking it out and letting me know if this can be closed?

**Comment by eadamsintel** [comment]
Fortunately, I had a clearlinux system around. Unfortunately the 2.x version of Kata does not support Podman or Docker.  See https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md 

However, I did try to see if I could just run podman rootless without Kata following an online guide from the Podman repo. I ran into some issues that are described below.  I was using version 36750.

```
$ sudo swupd bundle-add podman
Loading required manifests...
Downloading packs (29.59 MB) for:
 - podman
 [100%]

Finishing packs extraction...
Validate downloaded files
 [100%]

No extra files need to be downloaded
 [100%]

Installing files...
 [100%]

Calling post-update helper scripts
Successfully installed 1 bundle

$ podman run  quay.io/kata-containers/kata-deploy:latest bash
Trying to pull quay.io/kata-containers/kata-deploy:latest...
Getting image source signatures
Copying blob a7012e0f14b3 done
Copying blob e6a50b627bcb done
Copying blob 1921313a229c done
Copying blob 0e6eeac9cbf8 done
Copying blob a9b447e12ad0 done
Error: writing blob: adding layer with blob "sha256:e6a50b627bcb03d96996bb8e836ecb178eae7425636e3424d9e8d33a918768dd": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid if configured locally: lchown /run/lock/lockdev: invalid argument
```

I tried to follow the guide at https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md  I did not have a /etc/subuid file which might be related to the problems I was having.  The commands below are from the guide. 

```
$ sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 eadams
usermod: /etc/subuid does not exist, you cannot use the flags -v or -V
```

I tried to create the file and got past that error but still am having issues.

```
$ sudo touch /etc/subuid

$ sudo touch /etc/subgid

$ sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 eadams

$ sudo cat /etc/subuid
eadams:100000:65536

$ sudo cat /etc/subgid
eadams:100000:65536

$ podman run  quay.io/kata-containers/kata-deploy:latest bash
Trying to pull quay.io/kata-containers/kata-deploy:latest...
Getting image source signatures
Copying blob 1921313a229c done
Copying blob 0e6eeac9cbf8 done
Copying blob e6a50b627bcb done
Copying blob a9b447e12ad0 done
Copying blob a7012e0f14b3 done
Error: writing blob: adding layer with blob "sha256:e6a50b627bcb03d96996bb8e836ecb178eae7425636e3424d9e8d33a918768dd": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:54 for /run/lock/lockdev): Check /etc/subuid and /etc/subgid if configured locally: lchown /run/lock/lockdev: invalid argument
```

I tried searching for a subuid binary as I think I need this installed on the system.

```
$ sudo swupd-search subuid
Search failed, no reasonable results found

$ sudo swupd-search newuid
Search failed, no reasonable results found

$ sudo swupd-search lchown
Search failed, no reasonable results found
```

I am not sure exactly what is missing just to run a normal rootless podman container image. The slirp4netns binary was installed on my system as an FYI.

**Comment by ganeshmaharaj** [comment]
@eadamsintel I just spun up a VM to test podman out and these were the steps I had to do to get rootless podman running.

```
sudo swupd update
sudo swupd bundle-add podman
sudo touch /etc/subuid
sudo touch /etc/subgid
sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 clear
```
Since it is a vagrant VM, the username is `clear` for that system. Also since it is a vagrant VM, it came up with the kvm kernel. I switched over to the native kernel to get overlayfs functionality. (native should be the default for all baremetal installations).

```
sudo swupd bundle-add kernel-native
sudo clr-boot-manager list-kernels
sudo clr-boot-manager set-kernel org.clearlinux.native.5.18.16-1165
```

After all this, podman works without any problems.
```
clear@clr-01~ $ podman ps                                           
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
clear@clr-01~ $ podman pull mirror.gcr.io/library/busybox
Trying to pull mirror.gcr.io/library/busybox:latest...
Getting image source signatures                                     
Copying blob 50783e0dfb64 done                                      
Copying config 7a80323521 done                                      
Writing manifest to image destination
Storing signatures                                                  
7a80323521ccd4c2b4b423fa6e38e5cea156600f40cd855e464cc52a321a24dd
clear@clr-01~ $ podman run -it --rm --entrypoint sh mirror.gcr.io/library/busybox
/ # uname -r                                                        
5.18.16-1165.native                                                 
/ # ls -l                                                           
total 40                                                            
drwxr-xr-x    2 root     root         12288 Jul 29 01:32 bin
drwxr-xr-x    5 root     root           340 Aug  8 18:08 dev
drwxr-xr-x    1 root     root          4096 Aug  8 18:08 etc
drwxr-xr-x    2 nobody   nobody        4096 Jul 29 01:32 home
dr-xr-xr-x  175 nobody   nobody           0 Aug  8 18:08 proc
drwx------    1 root     root          4096 Aug  8 18:08 root
drwxr-xr-x    2 root     root          4096 Aug  8 18:08 run
dr-xr-xr-x   12 nobody   nobody           0 Aug  8 18:08 sys
drwxrwxrwt    2 root     root          4096 Jul 29 01:32 tmp
drwxr-xr-x    1 root     root          4096 Aug  8 18:08 usr
drwxr-xr-x    4 root     root          4096 Jul 29 01:32 var
/ # cat /etc/os-release                                             
cat: can't open '/etc/os-release': No such file or directory
/ # exit                                                            
```

**Comment by eadamsintel** [comment]
@ganeshmaharaj  It seems to be working for me now.  My guess is that I had to log out of the shell session and relogin to actually  get the updated subuids and subgids enabled.  When you rebooted that step was done automatically.   I will close this issue since rootless podman is working, and I can't test with Kata because Kata currently doesn't support Podman.  Users will still have to enable `/etc/subuid` and `/etc/subgid` to get this to work after installing the bundle.   Thanks!
