### ISSUE TITLE
Constantly log spamming from Flatpak 1.4.3 bundled in CL

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1566]
Flatpak version 1.4.3 bundled in CL is spamming this once every minute:

`xdg-desktop-por[43541]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag`

A quick search reveals that this is a well known problem [[1]](https://bugzilla.redhat.com/show_bug.cgi?id=1744416)[[2]](https://github.com/flatpak/xdg-desktop-portal/issues/336) that has been fixed in version 1.5.4 [[3]](https://github.com/flatpak/xdg-desktop-portal/commit/a3fd03f852a27ac45fbaf740a965ce45af5f5390#diff-83f8b459230c0d0acd2ad2186ccc1b03).

**Comment by ahkok** [comment]
I assume this is fixed with the release of `1.6.0`. If not, reopen.
