### ISSUE TITLE
Kernel error at boot

### ISSUE THREAD

**Issue by felixg3** [clearlinux/distribution#1575]
Dear CL team, currently I am experiencing an error message at boot just before LUKS decryption. The errors do not appear in dmesg or the systemd journal. Web search was mostly unsuccessful except for some highly professional LKML discussions. Current kernel log level is 2.

`[ 0.087492] rcu: rcu_organize_nocb_kthreads: No-CB GP kthread CPU 0:`
`[ 0.087492] rcu: 1`
`[ 0.087494] rcu: rcu_organize_nocb_kthreads: No-CB GP kthread CPU 2:`
`[ 0.087495] rcu: 3`
`[ 0.087492] rcu: rcu_organize_nocb_kthreads: No-CB GP kthread CPU 0:`
`[ 0.087492] rcu: 1`
`[ 0.087494] rcu: rcu_organize_nocb_kthreads: No-CB GP kthread CPU 2:`
`[ 0.087495] rcu: 3`

Thanks for your hep and for all the work you guys are doing on CL. It's powering my workstation every day! Glad you updated NM to 1.20.8 :)

**Comment by mmetak** [comment]
https://lkml.org/lkml/2019/10/4/819

**Comment by Jacalz** [comment]
I am seeing theses errors too. Would be good to see them fixed :I

**Comment by ahkok** [comment]
Looks like this is cosmetic. Since it appears to be in review, we'll wait for the kernel folks to merge it.

**Comment by miguelinux** [comment]
I'll take the patch from https://git.kernel.org/pub/scm/linux/kernel/git/paulmck/linux-rcu.git/commit/?h=dev&id=610dea36d3083a977e4f156206cbe1eaa2a532f0

**Comment by miguelinux** [comment]
The error message is fixed

**Comment by felixg3** [comment]
Thank you, @miguelinux!
