### ISSUE TITLE
Java Performance Enancements

### ISSUE THREAD

**Issue by AugustNagro** [clearlinux/distribution#1576]
I recently saw the great benchmarks on Phoronix (https://www.phoronix.com/scan.php?page=article&item=clear-linux-2019&num=2), which says "One of the areas Clear Linux did focus on in 2019 was optimizing their Java performance."

I wrote some benchmarks for MacOS showing the improvement when changing the OpenJDK build flags (http://august.nagro.us/optimized-openjdk.html), so I'm curious as to what flags ClearLinux is using, and whether there are additional optimizations to the build.

Regards,

August

**Comment by ahkok** [comment]
You can inspect the build code for java here:

https://github.com/clearlinux-pkgs/openjdk

Note: this does inherit default compile flags from the `clr-rpm-macros` and `filesystem` packages at minimum.
