### ISSUE TITLE
kubernetes: kubelet.service: wrong crio.sock path

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#158]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

```kubelet.service``` has ```--container-runtime-endpoint=unix:///var/run/crio.sock``` but CRI-O today seems to set ```/var/run/crio/crio.sock```

**Comment by iphutch** [comment]
this should be `/run/crio/crio.sock`

**Comment by mythi** [comment]
@iphutch why is that? ```/var/run``` is a symlink to ```../run``` but the code creates the file in ```/var/run/crio/crio.sock```

**Comment by iphutch** [comment]
Change merged. Closing issue
