### ISSUE TITLE
docker builds using 'FROM clearlinux/golang:latest' started failing on Ubuntu

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1580]
Since yesterday, our CI jobs that build container images using `FROM clearlinux/golang:latest` have failed with:
`swupd: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory`

```
RUN swupd update --no-boot-update ${CLEAR_LINUX_VERSION}

...

RUN mkdir /install_root \
    && swupd os-install \
    ${CLEAR_LINUX_VERSION} \
    --path /install_root \
    --statedir /swupd-state \
    --bundles=os-core \
    --no-boot-update \
    && rm -rf /install_root/var/lib/swupd/*
```

Looks same as #524. 

Ubuntu Server 16.04-LTS.

**Comment by mythi** [comment]
Dockerfiles: https://github.com/intel/intel-device-plugins-for-kubernetes/tree/master/build/docker

**Comment by hongzhanchen** [comment]
@mythi, I also met this issue on Actions CI yesterday.
Please refer to https://github.com/clearlinux/distribution/issues/1107, use workaround suggested by bryteise.
 sudo modprobe -r overlay && sudo modprobe overlay redirect_dir=off
sudo systemctl restart docker
I can use this workaround to fix the issue.

**Comment by mythi** [comment]
> I can use this workaround to fix the issue.

I'm not able to control the build host. Until this week we had not seen this at all and now all builds are failing which to me indicates the distro has something wrong.

**Comment by hongzhanchen** [comment]
@mythi , you can try to add "ls  -la /lib64/libsystemd*" before swupd to check if the file that soft link libsystemd.so.0 point to does not exist after  swupd update --no-boot-update ${CLEAR_LINUX_VERSION} and find out the root cause.  And then please type "docker info" to check if  Native Overlay Diff set false on your build system. If  Native Overlay Diff : false on your build system, it should be same issue with #1107.

**Comment by ahkok** [comment]
@DnPlas

**Comment by ahkok** [comment]
@bryteise

**Comment by bryteise** [comment]
@mythi the suggestion from @hongzhanchen is what I would start with. It is my suspician that the symlink changed between releases and your system hadn't been exposed to the bug with overlayfs before.

**Comment by mythi** [comment]
@bryteise Is the right host config setting ` redirect_dir=off` in `overlay` params to avoid this in the future?

@chuyd is the setting above something we can add?

FWIW, we build with both docker and buildah and the latter was working OK all the time.

**Comment by mythi** [comment]
This was working for some time but started failing again last week:

```
Step 6/18 : RUN ldconfig
 ---> Running in bc5956ed6056
standard_init_linux.go:211: exec user process caused "no such file or directory"
The command '/bin/sh -c ldconfig' returned a non-zero code: 1
```

(this step follows a `swupd update`: `Update successful - System updated from version 32480 to version 32550`)

**Comment by mythi** [comment]
OK, this was likely a glitch in our CI setup yesterday. By adding the overlayfs module parameter (`redirect_dir=off`) to our Jenkins VM template it works again.
