### ISSUE TITLE
linux-tools fails to build

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1581]
Attempting to do a `make build` with packages from current releases produce the following error:
```
.gnu.debuglto_.debug_macro' referenced in section `.gnu.debuglto_.debug_macro' of util/scripting-engines/perf-in.o: defined in discarded section `.gnu.debuglto_.debug_macro[wm4.debug.h.4.04b1a15b0df29174bfe1c5a91ffc5e70]' of util/scripting-engines/perf-in.o
```
causing the build to fail.

**Comment by dorileo** [comment]
Just push a new build (linux-tools-5.3-378) fixing the issue. Thanks.

**Comment by vedangpatel1** [comment]
This bug still exists on the latest mainline kernel(v5.5 at the time of writing). It's being reported out by maintainers (https://lkml.org/lkml/2020/1/16/474). We should try to upstream a solution so someone trying to build perf on their clearlinux dev system does not face the issue.

**Comment by dorileo** [comment]
Hi @vedangpatel1, yeah the issue still exists upstream, I wrote a patch making it work for us, not sure if/how upstream is supposed to properly fix it. See my solution [here](https://github.com/clearlinux-pkgs/linux-tools/blob/master/0001-Filter-out-link-time-optimization.patch)

**Comment by vedangpatel1** [comment]
Yes, I saw the solution. But, I believe we should also submit a patch upstream to fix it. Is it some bug in the compiler/linker?

**Comment by dorileo** [comment]
Yep, we can send it upstream.

**Comment by marxin** [comment]
I've just created an upstream bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99618.
