### ISSUE TITLE
Enabling CONFIG_MICROCODE_AMD in kernel

### ISSUE THREAD

**Issue by jquagga** [clearlinux/distribution#1583]
Good day,

I believe I’ve seen the topic come up in another thread I can’t seem to find, but I was hoping to get the CONFIG_MICROCODE_AMD flag enabled in the kernel. The firmware files are already included as part of linux-firmware; I believe this flag just needs to be flipped on for the kernel to do the actual loading. 

For comparison, this flag is presently =y in ArchLinux, Fedora and I’m assuming most distributions these days.

**Comment by ahkok** [comment]
@miguelinux

**Comment by miguelinux** [comment]
I'll add it for the next public release

**Comment by miguelinux** [comment]
the change is already public

**Comment by jquagga** [comment]
Thanks!  Rebooted and it seems to be loading firmware nicely! :-)
