### ISSUE TITLE
Using native kernel in with openstack and KVM does not have network

### ISSUE THREAD

**Issue by dlpottra** [clearlinux/distribution#1587]
When using openstack and the cloudguest-native.img in KVM there is no networking once the instance is up.  Reboot the instance and network is working.

@ahkok  looked at the journalctl file and saw that both systemd-networkd and NetworkManger are active.  I have attached the log.

[journalctl.log](https://github.com/clearlinux/distribution/files/3995556/journalctl.log)

**Comment by qzheng527** [comment]
From the log, looks systemd-networkd and NetworkManager were both active and managing the network. Could you try disable the systemd-networkd and let NetworkManager handle the network alone?

systemctl stop  systemd-networkd.socket
systemctl disable systemd-networkd
systemctl stop systemd-networkd

Remove /etc/NetworkManager/conf.d/systemd-networkd-unmanaged.conf

systemctl restart NetworkManager

**Comment by dlpottra** [comment]
@qzheng527 will you disable networkd in the image?

**Comment by ahkok** [comment]
@qzheng527 This isn't a good solution as this breaks new cloud instances without a way to gain access to the node (except rebooting remotely). It also breaks the choice that users may want or prefer systemd-networkd. This has to *just work* out of the box. A workaround is not OK.

**Comment by dlpottra** [comment]
@qzheng527 Hummmm.......  So, I have to reboot the system to get the network working, but you are saying that it breaks the network to have it turned off?!?!  Seems the network is already broken.  I don't follow.  What testing and cloud systems work with both on for the first boot???

Is there a way to disable systemd-networkd when buildling the image?  I am fine with building images to use, but by default both are on and causing me networking issues.

**Comment by qzheng527** [comment]
@dlpottra Could the workaround fix your issue?
From the https://cdn-alt.download.clearlinux.org/releases/32090/clear/config/image/cloudguest-native.yaml, looks only systemd-networkd is installed, which is different from the live.imag ( NetworkManager installed only). I don't know why NetworkManager was working together with systemd-networkd in your cloudguest-native image.

@ahkok @bryteise  Do you know the history/detail of the transition from systemd-networkd to NetworkManager in Clear?

**Comment by lebensterben** [comment]
>@dlpottra Could the workaround fix your issue? ...

@qzheng527 networkd was replaced by NetworkManager last summer. There was some issues that networkd wasn't disabled after the transition and some people had reported issues regarding losing network connection, but then a hot-fix fixed the problem.

The fix you post before was the ones I used when I had that issue before the hot-fix was applied.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fenrus75** [comment]
this is only true for the desktop side

servers really ought to be ok with networkd, since NM pulls in a pretty
darn deep amount of the gnome stack

**Comment by dlpottra** [comment]
@qzheng527 I will try building an image without the bundle systemd-networkd-autostart in the yaml file.

**Comment by dlpottra** [comment]
@qzheng527 removing the bundle systemd-networkd solves the issue.
