### ISSUE TITLE
There is long pause with no infomation between pack download and apply 

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#159]
-----------------------

### What is the issue type?

* [ ] Bug report

Is that only me, that after downloading the pack it takes hell lot of time to apply them and there is in between pauses with no information spitting on terminal make me wondering what the hell going on in the behind.
### Describe the problem

While running swupd update 

There is silence between the get the pack and applying them, time is quite long without any indication of what is going on in the background.

**Comment by mrkz** [comment]
@phmccarty

**Comment by ahkok** [comment]
The announcements are done when downloading starts, not when they finish. Some may take a long time, as packs can be large.

It might be nice to have some download progress displayed. I think swupd can predict the download sizes and at least regularly update the user on progress, but it's not trivial. The code also is being modified to support parallel downloads to further accelerate downloads, making it even more complex.

**Comment by iphutch** [comment]
@matthewrsj this issue may need to migrate to Swupd repo.

**Comment by tpleavitt** [comment]
@ahkok , please migrate to swupd-client issue

**Comment by puneetse** [comment]
I'm closing this issue as the swupd-client has been since updated to report progress better throughout the process.
