### ISSUE TITLE
Files in /usr/bin are not executable for mono

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1593]
The following files from the mono package are not executable:
```
# /usr/bin/mono-sgen-gdb.py
# /usr/bin/mono-gdb.py
```

**Comment by phmccarty** [comment]
These two scripts do not have a shebang or a main entry point, so we should probably not mark them executable. Do we have a blacklist for the executable bit tests?

**Comment by ahkok** [comment]
Just fixing it is easy enough (`mono-5.12.0.226-6`)
