### ISSUE TITLE
Update GNOME boxes

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1599]
The current version doesn't support UEFI so it is broken for me. The latest does. Thanks in advance.

**Comment by romulasry** [comment]
https://github.com/clearlinux/distribution/issues/1383 This is the same issue I assume.

**Comment by romulasry** [comment]
https://github.com/clearlinux/distribution/issues/1603

**Comment by phmccarty** [comment]
gnome-boxes was updated to 3.34.3 in release `32050`. Did that update fix your issue?

**Comment by ahkok** [comment]
CLosing. If there is a bug with the new version, open a new ticket please.

**Comment by romulasry** [comment]
Stable release | 3.36.2[1] (4 May 2020; 17 days ago)
