### ISSUE TITLE
Missing OpenVPN client/server scripts for systemd

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#16]
While I was able to find the OpenVPN binary within Clear Linux, I was unable to determine the appropriate way to invoke OpenVPN in the server or client context during startup. Admittedly, I'm somewhat new to systemd based distributions, am I missing something obvious? How would I automatically invoke the server or client on boot?

**Comment by iphutch** [comment]
@ahkok

**Comment by AthenasJimenez** [comment]
@omkhar, already enable systemd services on OpenVPN. 

You can finde them as openvpn-client@.service and openvpn-server@.service
