### ISSUE TITLE
Update qemu

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1603]
Component qemu has version 3.1.1.1
https://download.qemu.org/qemu-4.2.0.tar.xz

**Comment by paulcarroty** [comment]
Agree, v4 has serious performance boost.

**Comment by ahkok** [comment]
I'm looking into this. Due to the amount of components this is used in, and that this is a major version change, it may take a bit as we need to do extra testing.

**Comment by romulasry** [comment]
Qemu 5.0 stable is coming this month.

**Comment by romulasry** [comment]
5.0 was just released:
https://wiki.qemu.org/ChangeLog/5.0

**Comment by romulasry** [comment]
@ahkok Any update?

**Comment by mdhorn** [comment]
Updated to 5.1.0 in Clear Linux OS release 33670.
