### ISSUE TITLE
Update GNOME Software

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1604]
This is the latest as of today:
https://download.gnome.org/sources/gnome-software/3.35/LATEST-IS-3.35.2

**Comment by curantes** [comment]
3.35 branch is a development branch which will be 3.36 when released. I don't think the clearlinux devs is going to use development versions.

**Comment by phmccarty** [comment]
My understanding is that we want to remain on 3.34.x versions for all GNOME components until 3.36 is released.

Assigning to @mrkz to confirm and disposition.

**Comment by mrkz** [comment]
@romulasry Thanks for taking the time to look into this.

As already pointed out by @curantes and @phmccarty. Odd versions (e.g: `3.33`, `3.35`, etc) tend to be development versions, hence not really recommended for stable systems and we would not look for integrating `3.35` but the stable release of `3.35` (which would become `3.36` in a few months).

In summary, we would be updating the GNOME stack once a new stable release is ready from the GNOME folks :smiley:
