### ISSUE TITLE
Include autospec

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1605]
That would be nice to have that and any updates would be handled quite nicely, Thanks in advance.

**Comment by bryteise** [comment]
autospec doesn't really fit a release model at this time. It is definitely a project to use the git master branch and keep updating as our [guidelines](https://github.com/clearlinux/common#keep-up-to-date-with-latest-changes) suggest.

**Comment by romulasry** [comment]
I see, maybe in the future sometime.

**Comment by rossburton** [comment]
Quoting William: "It is definitely a project to use the git master branch".  Closing.
