### ISSUE TITLE
kvm "no hardware support" text on boot

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1608]
I have it enabled in the UEFI settings. Bug?

**Comment by ahkok** [comment]
If this would be a bug, it would be a bug in the upstream Linux kernel.

**Comment by ahkok** [comment]
> I have it enabled in the UEFI settings

What is the name in the BIOS screen for this setting? (screenshot?)

Can you post the output of the following command: `grep flags /proc/cpuinfo |head -n1`

**Comment by ahkok** [comment]
Will close if no further reply.

**Comment by romulasry** [comment]
You can close I changed to Ubuntu for now.
