### ISSUE TITLE
GDM only lists X.Org and Fallback sessions

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#161]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

Clear Linux Version: 24620

Installed Bundles:

- bootloader
- desktop
- desktop-apps
- desktop-assets
- desktop-autostart
- desktop-gnomelibs
- desktop-locales
- iproute2
- kernel-native
- libX11client
- openssl
- os-core
- os-core-update
- p11-kit
- python3-basic
- sudo
- sysadmin-basic
- telemetrics
- which
- wpa_supplicant
- xemacs

When I power on my computer, and GDM launches, the only available sessions listed are "GNOME on X.Org" and "GNOME Fallback." "GNOME on Wayland" and "Weston" are not listed. This is on a fresh install.

I have an AMD HD 7750 GPU and an i5 4690k CPU.

If I restart GDM with ``sudo systemctl restart gdm.service``, then "GNOME on Wayland" and "Weston" appear suddenly.

HOWEVER, once restarted, GDM crashes when selecting either "GNOME on X.Org" or "GNOME on Wayland". I did not try Flashback or pure Weston.

**Comment by mrkz** [comment]
@OpenSourceAnarchist  I don't have that piece of hardware to test, but I did test with a Radeon RX 580 Series card, unable to reproduce the bug.

Have you installed any additional software or this happens with stock CLR?

also, could you please enable the debug output of gdm, and later on share the journalctl output for your boot?

```
# mkdir -p /etc/gdm
# cat > /etc/gdm/custom.conf << EOF
[debug]
Enable=true
EOF

# reboot
```

once you managed to reproduce the fail, please save the journalctl into a log file.
```
# journalctl -b > log.txt
```

Thanks!

**Comment by OpenSourceAnarchist** [comment]
I'm pretty sure this is an upstream bug because this has happened on Antergos, Arch, Gentoo, etc. for me. Is it possible to use LightDM as a DM in the future for GNOME (like Solus does)? LightDM has never been an issue for me. As for GNOME graphical glitches, I think this is upstream too, but there might be useful info in the logs anyway.

Currently, I don't have Clear Linux installed as I am using Solus until Plasma is ready on Clear (due to these bugs with GNOME on my system). However, when I do install Clear, I'll install both GNOME and Plasma and upload the info you asked for above if I can reproduce the bugs.

**Comment by fenrus75** [comment]
we're in need to look at the DM situation soon anyway.  might hurry that up

**Comment by OpenSourceAnarchist** [comment]
Update: on Clear Linux 24890, I can confirm switching to the AMDGPU driver fixed these issues for me (as opposed to the radeon driver). So, it must be an upstream bug of the radeon driver on my hardware with GNOME. Closing because it is not related to Clear Linux, and has affected me on other distros.
