### ISSUE TITLE
Upgrade to the latest Pango version

### ISSUE THREAD

**Issue by JDNightwalker** [clearlinux/distribution#1610]
While I know it's somewhat controversial due to the dropping of ancient bitmap fonts and the tweaking of some of the really old fonts, would it be possible to see Pango receive an upgrade to a more current version in one of the upcoming builds? As I understand it, the current version is now using Harfbuzz for glyph shaping, which both reduces memory usage and (depending on your point of view) improves the style and spacing of fonts on the screen. I know this from personal experience using Fedora 31 which has employed Pango 1.44.7 (currently) while Clear Linux is currently employing Pango 1.42.4, as of Build 31990.

Thank you for your time and consideration!!

**Comment by eadamsintel** [comment]
For further reference there is a discussion in the forums about this at https://community.clearlinux.org/t/custom-fonts-in-clear-linux/2442/

**Comment by ahkok** [comment]
@mrkz any idea why we still have the older version?

**Comment by phmccarty** [comment]
The package needs to be converted from autotools to meson, but other than that, I think we can upgrade pango.

**Comment by ahkok** [comment]
`pango-1.44.7-66`

Seems to work OK (I restarted my own GNOME session with it).

**Comment by JDNightwalker** [comment]
Just to confirm the process, does this mean the new version will be in the next released build update?

Thank you for the hard work!!

**Comment by phmccarty** [comment]
Yes, the updated `pango` will be in release `32060`.
