### ISSUE TITLE
package request: Microsoft teams

### ISSUE THREAD

**Issue by karthikprabhuvinod** [clearlinux/distribution#1611]
Microsoft just released the MS teams for linux, an office 365 tool for collaboration, file sharing etc. I think its good to have it for CL

https://teams.microsoft.com/downloads#allDevicesSection

Can we please consider this package?

**Comment by ahkok** [comment]
Is it open source? I can only find binary blob downloads (we have to compile it!).

**Comment by karthikprabhuvinod** [comment]
@ahkok I couldn't find source code as well, Looks like its not really open sourced. Sorry I did not check well. I will close the request.
