### ISSUE TITLE
 "BROWSE LOCAL FILES..." in Steam doesn't work

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#1612]
Using default configuration.

**Comment by lebensterben** [comment]
>Using default configuration.

@romulasry Is it flatpak steam?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romulasry** [comment]
@lebensterben 
Yes. Thanks.

**Comment by lebensterben** [comment]
Download and install this one:
http://repo.steampowered.com/steam/archive/precise/steam_latest.tar.gz

**Comment by romulasry** [comment]
I am going to try sudo swupd bundle-add games first.

**Comment by lebensterben** [comment]
>@lebensterben  ...

@romulasry that's not steam....

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romulasry** [comment]
I am going to report the bug to flatpak steam.

**Comment by romulasry** [comment]
@lebensterben 
steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on clear-linux-os 31990 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Error: You are missing the following 32-bit libraries, and Steam may not run:
libGL.so.1
libdrm.so.2
/home/ryan/.local/share/Steam/ubuntu12_32/steam
Installing breakpad exception handler for appid(steam)/version(1576550254)
Installing breakpad exception handler for appid(steam)/version(1576550254)
Installing breakpad exception handler for appid(steam)/version(1576550254)
Failed to load steamui.so - dlerror(): libGL.so.1: wrong ELF class: ELFCLASS64
Installing breakpad exception handler for appid(steam)/version(1576550254)
Installing breakpad exception handler for appid(steam)/version(1576550254)
[2019-12-31 17:14:56] Startup - updater built Dec 16 2019 16:48:42
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2019-12-31 17:14:56] Checking for update on startup
[2019-12-31 17:14:56] Checking for available updates...
[2019-12-31 17:14:56] Downloading manifest: client-download.steampowered.com/client/steam_client_ubuntu12
[2019-12-31 17:14:57] Download skipped: /client/steam_client_ubuntu12 version 1576550254, installed version 1576550254
[2019-12-31 17:14:57] Nothing to do
[2019-12-31 17:14:57] Verifying installation...
[2019-12-31 17:14:57] Performing checksum verification of executable files
[2019-12-31 17:14:57] Verification complete
[2019-12-31 17:15:00] Shutdown

**Comment by lebensterben** [comment]
@romulasry 
This is not a bug. You're using it wrong.
Download and extract the `tar.gz`. `cd` into that directory, and run `sudo make install`.
This is written in the `README` file.

**Comment by romulasry** [comment]
@lebensterben I did that, is there any way to uninstall it and start over?

**Comment by lebensterben** [comment]
There's no need to uninstall. Run it again and you're reinstalling.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romulasry** [comment]
Did that same error.

**Comment by lebensterben** [comment]
FYI, `libGL.so` is available in `lib-opengl` bundle.
Did you do anything to your GPU driver?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by romulasry** [comment]
I did a sudo swupd clean, did nothing to the gpu driver.

**Comment by lebensterben** [comment]
Run this `sudo swupd verify --fix --quick --bundles=lib-opengl`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahkok** [comment]
Looks like this is outside what we can control on clearlinux. The flatpak steam app is sandboxed. If you manually install steam, you will not have this problem.
