### ISSUE TITLE
Unable to install docker on a 64GB USB bootable live desktop, how to free space

### ISSUE THREAD

**Issue by vairamsvsjdo** [clearlinux/distribution#1614]
clrlinux@clr-live~ $ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0         7:0    0   2.5G  1 loop 
sda           8:0    1  57.3G  0 disk 
└─sda1        8:1    1  57.3G  0 part 

clrlinux@clr-live~ $ sudo swupd bundle-add containers-basic
Loading required manifests...
Error: Bundle too large by 635M
NOTE: currently, swupd only checks /usr/ (or the passed-in path with /usr/ appended) for available space
To skip this error and install anyways, add the --skip-diskspace-check flag to your command
Failed to install 1 of 1 bundles

**Comment by ahkok** [comment]
What does `df -h` say? Is your drive nearly full?

**Comment by ahkok** [comment]
I think the live bootable image does not have the required size to install anything this large (docker is 1gb?), @mdhorn ?

**Comment by vairamsvsjdo** [comment]
No its not full,  the install is looking for an uninstalled partition I guess
The USB is 64GB and it should let it install , seems like an issue

**Comment by vairamsvsjdo** [comment]
Where is the code module that actually does create different volumes when it formats the usb drive? I want to find out if that can be changed so rufus can use it correctly

**Comment by mdhorn** [comment]
@vairamsvsjdo The ISO images are created using squashfs. When the image is booted, an overlay and tmpfs are used for the running file system. By this design, we can't just use the rest of the USB stick for the file system -- this was never the intent of the live image.

If the live image does not meet your needs for testing, you can use boot from a small USB with the ISO image, and then install Clear Linux OS onto your larger (64GB) USB as the target. Then you can boot the newly installed USB target making full use of the space.
