### ISSUE TITLE
Gparted: segmentation fault

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1616]
`/usr/bin/gparted: line 202:  6192 Segmentation fault      (core dumped) $BASE_CMD` on partition resize.

**Comment by ahkok** [comment]
Did you do anything specific?

**Comment by paulcarroty** [comment]
I've tried to resize EFI partition several times.

**Comment by ahkok** [comment]
> I've tried to resize EFI partition several times.

Which is `FAT`. You can't resize that as far as I know. `ext4` yes, `btrfs` also, but for `FAT` filesystems I suggest just copying out the data and reformatting it after you erase and make the new partition larger.

**Comment by ahkok** [comment]
Note, `parted` shouldn't segfault in this case and tell you a proper error code...
