### ISSUE TITLE
VLC and MP4a codec

### ISSUE THREAD

**Issue by lsatenstein** [clearlinux/distribution#1617]
I receive many mp4a files which, with alternative distributions, I am able to watch and play.

Not so with vlc and clear linux 

I am envoking vlc via firefox.

**Comment by thiagomacieira** [comment]
We are unable to provide the MP4 codecs for software decoding in Clear. This is unfortunately not up for discussion.

Are you sure VLC is using hardware decoding for those files?

**Comment by ahkok** [comment]
Please read the discussion on the forums (https://community.clearlinux.org/) for alternatives and explanation why some codecs are not provided (and won't be).

Closing this as this is a duplicate of several similar bugs.
