### ISSUE TITLE
Bundle Request: Plasma Desktop

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#162]
GNOME is the default DE for the ``desktop`` bundle. However, GNOME is not everyone's preference, and since Plasma (and other KDE packages) are already up on https://github.com/clearlinux-pkgs/, I would strongly support separating the ``desktop`` bundle into ``desktop-gnome`` and ``desktop-plasma``. ``desktop-gnome`` would be exactly the same as the current ``desktop`` bundle. ``desktop-plasma`` would bundle the core desktop packages but remove everything GNOME, and instead provide packages such as ``plasma-desktop`` and ``sddm`` as well as existing bundles such as ``desktop-kde-apps``.

GNOME does not play nicely on my hardware (see #161 ) but Plasma always has. This would also benefit many users who prefer a KDE/Plasma workflow over GNOME.

**Comment by fenrus75** [comment]
thanks for asking, I always wanted an excuse to make this happen

**Comment by fenrus75** [comment]
tomorrow we'll have a very first stab at a "desktop-kde" bundle. it's currently still additive on top of the gnome desktop bundle (I'll detangle that once it works a bit better).

it's a work in progress and will need a round or two of bugfixes

**Comment by OpenSourceAnarchist** [comment]
@fenrus75 I've been looking over the new releases and I couldn't believe how quickly you were able to package the KDE Desktop! So many applications! I really appreciate it, and I can't wait to test it out when it's ready.

I've always used either GNOME or Budgie when working in Linux, and even though Budgie has always worked well, GNOME is particularly buggy recently. Odd graphics glitches and login problems. But Plasma is finally a strong competitor to rival GNOME, and I'm more than happy to use Plasma as it works well and is well supported.

When it's ready as a bundle, I'd suggest releasing an announcement or blog post of some kind. It might boost Clear Linux's popularity if Phoronix or DistroWatch writes a post about Plasma availability on Clear!

**Comment by ahkok** [comment]
Working well. Tested with lightdm login manager that's now also available.
