### ISSUE TITLE
dlib core dumped on python 3.8

### ISSUE THREAD

**Issue by Fatinnadiah** [clearlinux/distribution#1621]
To whom it may concern,

Hi, I'm Fatin and I now currently running some project on Clear Linux. Recently, I'm trying to install dlib on Clear Linux. Since Clear Linux using Python 3.8, so I build it from source.

My installation process,
1. git clone https://github.com/davisking/dlib.gi (get the dlib repo)
2. python3 setup.py bdist_wheel (to build whl file on ntel® Atom™ Processor E3950)
3. pip3 install dlib-19.19.99-cp38-cp38-linux_x86_64.whl

Referring to pip (pip3_shoe_dlib.png), dlib is there but I cannot call dlib module. It shows core dumped when I want to check in I have installed it correctly.(see attachment 'dlib_error.png'). Can anyone help me on installing this module correctly?
Thank you.

Regards,
Fatin Nadiah

![pip3_show_dlib](https://user-images.githubusercontent.com/59385438/71650815-bdea3600-2d53-11ea-941c-28eb0f4b4f32.png)
![dlib_error](https://user-images.githubusercontent.com/59385438/71650816-bfb3f980-2d53-11ea-86b8-e1a5c1d2689a.png)

**Comment by ahkok** [comment]
`dlib` as you installed it is an upstream project. Please report your bug to the upstream project. I'm not sure this is a ClearLinux bug, and upstream may be receptive to help resolve this:

 https://github.com/davisking/dlib/issues/new

**Comment by Fatinnadiah** [comment]
Hi ahkok,

Thank you for your response. But I already try it on ubuntu with python 3.8 and there is no issue with it. So, I have a doubt there might be some path issue with clearlinux. 

Thank you

**Comment by ahkok** [comment]
> So, I have a doubt there might be some path issue with clearlinux.

Unlikely. This would give a file not found error, not a segfault. 

A segmentation fault indicates that (most likely) there is a bug in the C components of `dlib` that are not exposed because the upstream project isn't testing with newer compilers, or flags.

**Comment by ahkok** [comment]
Oh, actually

I'm not reading your screenshots properly, you have an `Illegal Instruction` error.

What CPU are you running on? `cat /proc/cpuinfo` ?

**Comment by Fatinnadiah** [comment]
Hi ahkok,
I will up an issue about this on dlib github as well and since I want to deploy my project using edge devices, here the cpu info:

> 
processor	: 0

vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Atom(TM) Processor E3950 @ 1.60GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 1991.989
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2
bogomips	: 3187.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Atom(TM) Processor E3950 @ 1.60GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 1992.006
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2
bogomips	: 3187.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Atom(TM) Processor E3950 @ 1.60GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 1992.000
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2
bogomips	: 3187.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 92
model name	: Intel(R) Atom(TM) Processor E3950 @ 1.60GHz
stepping	: 9
microcode	: 0x38
cpu MHz		: 1992.000
cache size	: 1024 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 21
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts md_clear arch_capabilities
bugs		: spectre_v1 spectre_v2
bogomips	: 3187.20
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

>

**Comment by ahkok** [comment]
I think what is happening here is that during the installation of `dlib` from source, it somehow generates `avx512` (or `avx2`?) instructions. Since you have an `Atom` processor, there are a lot of instructions that are not supported by your CPU.

If you can attach the compile logs from the `dlib` program, that may help identify the root cause. (Note: it's possible but unlikely that ClearLinux somehow "added" invalid compiler flags for your CPU, since the default flags are supposed to work on Atom at all times).

**Comment by ahkok** [comment]
Meanwhile, I noticed that `dlib` is being added to clearlinux as we speak, which may be a quick solution for this issue as well - you'll just be able to use the version provided by clearlinux.

**Comment by bryteise** [comment]
I am very interested that the binary you built yourself is being built for a target arch other than your system. I shall try and replicate the behavior but I do note that this is not how Clear Linux builds and installs python content. Could you see what `python3 setup.py build` gives you as far as binaries go in comparison to what files are in `~/.local`?

**Comment by Fatinnadiah** [comment]
> I think what is happening here is that during the installation of `dlib` from source, it somehow generates `avx512` (or `avx2`?) instructions. Since you have an `Atom` processor, there are a lot of instructions that are not supported by your CPU.
> 
> If you can attach the compile logs from the `dlib` program, that may help identify the root cause. (Note: it's possible but unlikely that ClearLinux somehow "added" invalid compiler flags for your CPU, since the default flags are supposed to work on Atom at all times).

Hi ahkok,
Is this okay for you to inspect? I only can find this from the output of compiling the dlib.

running install
running bdist_egg
running egg_info
writing dlib.egg-info/PKG-INFO
writing dependency_links to dlib.egg-info/dependency_links.txt
writing top-level names to dlib.egg-info/top_level.txt
package init file 'dlib/_init_.py' not found (or not a regular file)
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'tools/python/build*'
writing manifest file 'dlib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Building extension for Python 3.8.0 (default, Dec 27 2019, 13:34:36) 
Invoking CMake setup: 'cmake /home/clear_linux/dlib/tools/python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/clear_linux/dlib/build/lib.linux-x86_64-3.8 -DPYTHON_EXECUTABLE=/usr/bin/python -DCMAKE_BUILD_TYPE=Release'
-- pybind11 v2.2.2
-- Using CMake version: 3.16.2
-- Compiling dlib version: 19.19.99
-- SSE4 instructions can be executed by the host processor.
-- AVX instructions can be executed by the host processor.
-- Enabling AVX instructions
-- Found system copy of libpng: /usr/lib64/libpng.so;/usr/lib/lib64/libz.so
-- Found system copy of libjpeg: /usr/lib64/libjpeg.so
-- Searching for BLAS and LAPACK
-- Searching for BLAS and LAPACK
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Checking for module 'lapack'
--   No package 'lapack' found
-- Found OpenBLAS library
-- Using OpenBLAS's built in LAPACK
-- C++11 activated.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/clear_linux/dlib/build/temp.linux-x86_64-3.8
Invoking CMake build: 'cmake --build . --config Release -- -j4'
[ 68%] Built target dlib
[100%] Built target dlib_python
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/dlib.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for dlib.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/dlib.py to dlib.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying dlib.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/dlib-19.19.99-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing dlib-19.19.99-py3.8-linux-x86_64.egg
removing '/usr/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg' (and everything under it)
creating /usr/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg
Extracting dlib-19.19.99-py3.8-linux-x86_64.egg to /usr/lib/python3.8/site-packages
dlib 19.19.99 is already the active version in easy-install.pth

Installed /usr/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg
Processing dependencies for dlib==19.19.99
Finished processing dependencies for dlib==19.19.99

**Comment by Fatinnadiah** [comment]
> I am very interested that the binary you built yourself is being built for a target arch other than your system. I shall try and replicate the behavior but I do note that this is not how Clear Linux builds and installs python content. Could you see what `python3 setup.py build` gives you as far as binaries go in comparison to what files are in `~/.local`?

Hi byteise,

I looked on my PC and find out no files or folder located inside `~/.local/lib/python3.8/site-packages`. The installed `dlib` was located in `/usr/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg`
Here are the files and folders located inside /usr/lib/python3.8/site-packages/dlib-19.19.99-py3.8-linux-x86_64.egg`:

![image](https://user-images.githubusercontent.com/59385438/72043789-1047cb80-32ed-11ea-8a63-69ca7a207d90.png)

**Comment by sunnyflunk** [comment]
> -- AVX instructions can be executed by the host processor.
> -- Enabling AVX instructions

Your CPU doesn't support AVX (no Atoms do I believe), hence it is unable to run AVX code and aborts with Illegal Instruction. The issue is that during the build, it believes that it can!

**Comment by Fatinnadiah** [comment]
Hi all!
I tested to install dlib on clearlinux using i-core processor and it's work well. 
I missed out about the Atom processor do not have AVX support. After including `--no USE_AVX_INSTRUCTIONS` instruction during building and installing dlib on Atom processor, the dlib works well.

Thank you for your support. I will close this issue.
