### ISSUE TITLE
mariadb config no effect

### ISSUE THREAD

**Issue by jh10001** [clearlinux/distribution#1623]
Copy /usr/share/defaults/mariadb to /etc/mariadb
change /etc/mariadb/my.cnf.d/server.cnf bind-address
systemctl restart mariadb, bind address not change
change /usr/share/defaults/mariadb/my.cnf.d/server.cnf bind-address
systemctl restart mariadb, bind address changed

**Comment by ahkok** [comment]
Looks like a documentation issue.

Put the `server.cnf` you created in `/etc/mariadb/` instead (no subfolders), then try again. Please revert the changes you made under `/usr` or use `swupd repair` to fix them, as future updates will erase those changes automatically at some point.

**Comment by jh10001** [comment]
Create new /etc/mariadb and put server.cnf, change bind-address in it, still no effect.

**Comment by jh10001** [comment]
$cat /etc/mariadb/server.cnf
#
# These groups are read by MariaDB server.
# Use it for options that only the server (but not clients) should see
#
# See the examples of server my.cnf files in /usr/share/mysql/
#

# this is read by the standalone daemon and embedded servers
[server]

# this is only for the mysqld standalone daemon
[mysqld]

#
# * Galera-related settings
#
[galera]
# Mandatory settings
#wsrep_on=ON
#wsrep_provider=
#wsrep_cluster_address=
#binlog_format=row
#default_storage_engine=InnoDB
#innodb_autoinc_lock_mode=2
#
# Allow server to accept connections on all interfaces.
#
bind-address=0.0.0.0
#
# Optional setting
#wsrep_slave_threads=1
#innodb_flush_log_at_trx_commit=0

# this is only for embedded server
[embedded]

# This group is only read by MariaDB servers, not by MySQL.
# If you use the same .cnf file for MySQL and MariaDB,
# you can put MariaDB-only options here
[mariadb]

# This group is only read by MariaDB-10.4 servers.
# If you use the same .cnf file for MariaDB of different versions,
# use this group for options that older servers don't understand
[mariadb-10.4]

**Comment by ahkok** [comment]
That is an incorrect config file. The `bind-address` you set is in the `[galera]` section. You want to have it in the `[server]` section or the `[mariadb]` section.

The only thing needed in the file should be this:

```
[server]
bind-address=0.0.0.0
```

**Comment by jh10001** [comment]
> 
> 
> That is an incorrect config file. The `bind-address` you set is in the `[galera]` section. You want to have it in the `[server]` section or the `[mariadb]` section.
> 
> The only thing needed in the file should be this:
> 
> ```
> [server]
> bind-address=0.0.0.0
> ```

Still no effect

$  cat /etc/mariadb/server.cnf
'''
[server]
bind-address=0.0.0.0
'''

**Comment by ahkok** [comment]
@jh10001 that's unfortunate, as it works for me - please check the following:

- did you edit or modify any of the files under `/usr/share/defaults`? did you `sudo swupd repair` to undo those changes?
- did you verify your system updated to `32080` - I did fix an issue in this release

**Comment by ketonik** [comment]
> Looks like a documentation issue.
> 
> Put the `server.cnf` you created in `/etc/mariadb/` instead (no subfolders), then try again. Please revert the changes you made under `/usr` or use `swupd repair` to fix them, as future updates will erase those changes automatically at some point.

ahkok>
I've copied mariadb directory from `/usr/share/defaults/mariadb` to `/etc/`

You mention above put `server.cnf` inside `/etc/mariadb/` not leave inside /etc/mariadb/`my.cnf.d`

What about all those other files inside sub folder `my.cnf.d`, do they need also be directly in `mariadb` folder in `/etc` and should we do this with same files in the `/usr/share/defaults/mariadb`:

`client.cnf`
`enable_encryption.preset`
`mysql-clients.cnf`

Here is what currently looks like both 
`/usr/share/defaults/`
`/etc`

![etc_mariadb_config_structure](https://user-images.githubusercontent.com/49221849/80560596-1be20e00-8a14-11ea-9ded-f2672a696bad.png)
