### ISSUE TITLE
FATAL fail while booting in USB

### ISSUE THREAD

**Issue by 01dk** [clearlinux/distribution#1624]
[FAIL] FATAL: Detected Missing Required CPU features: Carry-less Multiplication extensions (pclmulqdq)

My CPU: Core I5 450 4 cores
GPU: Intel Ironlake Mobile
RAM: 4gb and 6gb fatal 
Laptop name: Dell Inspiron N7010

Photo here: https://drive.google.com/file/d/11qquqJtg3NBiKNbdTzVIDz5ofhql5NN6/view?usp=drivesdk

**Comment by ahkok** [comment]
It appears your system is missing a required CPU instruction.

**Comment by ahkok** [comment]
@thiagomacieira @mdhorn comments?

**Comment by mdhorn** [comment]
That system is not meeting the minimum requirements for Clear Linux OS:
https://docs.01.org/clearlinux/latest/reference/system-requirements.html

The installer will intentionally fail to start unless all CPU requirements are met.

**Comment by ahkok** [comment]
@01dk it appears this is not a bug, unfortunately, you may have actually have an unsupported CPU variant.

**Comment by 01dk** [comment]
Oh, thanks for answering @ahkok @mdhorn 
So it was bad that Clear Linux doesn't support CPU

**Comment by thiagomacieira** [comment]
PCLMULQDQ isi required by zlib. So it's a hard requirement.

Checking Wikipedia, looks like Nehalem added SSE4.2 but PCLMULQDQ didn't come until the one after: Westmere (the "1½ generation" of the Intel Core processors that didn't get a marketing brand name). Westmere (2010) is our minimum requirement on Core and Goldmont (2016) for Atom.

**Comment by thiagomacieira** [comment]
Actually, I'm seeing CPUID checks for PCLMULQDQ in zlib. @jtkukunas can you confirm that your zlib from https://github.com/jtkukunas/zlib will run on pre-WSM just fine?

**Comment by thiagomacieira** [comment]
Actually, I'm seeing CPUID checks for PCLMULQDQ in zlib. @jtkukunas can you confirm that your zlib from https://github.com/jtkukunas/zlib will run on pre-WSM just fine?

**Comment by jtkukunas** [comment]
@thiagomacieira PCLMUL is not a hard requirement for my zlib. It works fine pre-WSM.

**Comment by thiagomacieira** [comment]
So I don't think PCLMULQDQ is a hard requirement for Clear. That said, we do compile with `-march=westmere` so we cannot claim Nehalem will work.

**Comment by danintel** [comment]
This also fails when installing on the latest VirtualBox (6.0 and 6.1). Even though my laptop supports PCLMULQDQ, VirtualBox does not support (propagate) the feature bit.
