### ISSUE TITLE
Package request: acme.sh

### ISSUE THREAD

**Issue by jh10001** [clearlinux/distribution#1625]
https://github.com/Neilpang/acme.sh

**Comment by lebensterben** [comment]
Just `curl https://get.acme.sh | sh` and `acme.sh --auto-upgrade` should work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahkok** [comment]
We already bundle `certbot` in the `letsencrypt-client` bundle. If you need this script, I would follow the above method.
