### ISSUE TITLE
How to load custom EDID (monitor) firmare at boot time?

### ISSUE THREAD

**Issue by gurtonbuster** [clearlinux/distribution#1626]
I am trying to load a custom edid file using the kernel parameters `drm_kms_helper.edid_firmware=edid/your_edid.bin` or 
`drm.edid_firmware=edid/your_edid.bin` but it's not working. 

I think it's because the drm and drm_kms_helper modules are not loading because when I run 
`lsmod | grep -i drm` I get no output and when I run `modinfo drm` I get `modinfo: ERROR: Module drm not found.` and same error for drm_kms_helper.

**Comment by lebensterben** [comment]
>I am trying to load a custom edid file using the kernel parameters `drm_kms_helper.edid_firmware=edid/your_edid.bin` or  ...

@gurtonbuster where do you add the kernel parameters? Clear Linux uses systemd-boot instead of GRUB so many guides online are not applicable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gurtonbuster** [comment]
@lebensterben I followed `man clr-boot-manager` and added them to `/etc/kernel/cmdline.d/edid.conf` and then ran `sudo clr-boot-manager update`.

**Comment by ahkok** [comment]
The reason you can't load these modules is because they are builtin.

**Comment by ahkok** [comment]
Changed the title to reflect the actual question.

**Comment by gurtonbuster** [comment]
@ahkok Whoops sorry. I just assumed they should load because in Manjaro lsmod shows drm and drm_kms_helper. Is there any way to load a custom edid then?

**Comment by ahkok** [comment]
> Is there any way to load a custom edid then?

I assume the method with boot options should still work, which is why I modified the title and left it open. perhaps @dorileo can look into answering that question?

**Comment by dorileo** [comment]
> @lebensterben I followed `man clr-boot-manager` and added them to `/etc/kernel/cmdline.d/edid.conf` and then ran `sudo clr-boot-manager update`.

I want to check that clr-boot-manager is doing the right thing, when you do this what is the resulting `/proc/cmdline` ?

**Comment by gurtonbuster** [comment]
@dorileo Here's the output of `cat /proc/cmdline` : 
`initrd=\EFI\org.clearlinux\freestanding-00-intel-ucode.cpio initrd=\EFI\org.clearlinux\freestanding-i915-firmware.cpio.xz root=PARTUUID=000ed52b-8e0a-496b-9745-b350ece2c9c2 quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcu_nocbs=0-64 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs tsc=reliable rw module.sig_unenforce drm.edid_firmware=eDP-1:edid/edid103.bin nvidia-drm.modeset=1`

**Comment by dorileo** [comment]
@gurtonbuster where are you installing the edid file (`edid103.bin`)?

**Comment by dorileo** [comment]
@gurtonbuster try creating your own initrd file with your edid file in it, then you add this initrd file to `/etc/kernel/initrd.d/`, run `cbm` again, your edid file should be inside `/usr/lib/firmware/edid/`, your kernel parameter should remain the same.

**Comment by gurtonbuster** [comment]
> @gurtonbuster where are you installing the edid file (`edid103.bin`)?

I put the file in `/usr/lib/firmware/edid`.
I'm following this : https://wiki.archlinux.org/index.php/kernel_mode_setting#Forcing_modes_and_EDID

**Comment by gurtonbuster** [comment]
> @gurtonbuster try creating your own initrd file with your edid file in it
I'm sorry but I don't know how to create this file. Can you explain how to create it?

**Comment by knlgdgl** [comment]
> try creating your own initrd file with your edid file in it 

@dorileo Can you please explain how to create this file?

**Comment by bryteise** [comment]
@gurtonbuster, @knlgdgl you can create an initrd by making a folder with your filesystem layout inside it you want in the initrd and then inside the directory run `find . | cpio -H newc -o | gzip >> ../my-initrd.img`

**Comment by gurtonbuster** [comment]
@dorileo, @bryteise Thanks a lot for the reply. Your solution worked. 

The first problem was that the drm.edid_firmware parameter wasn't enabled but that has been enabled now. But even after it was enabled I was getting this error in dmesg : ` Direct firmware load for edid/edid103.bin failed with error -2`. Then I tried your solution and it works now. 

I'll write the detailed steps for anyone else facing the same issue : 

1.  I created the following folders in my home directory : 
`sudo mkdir -p ~/test/usr/lib/firmware/edid`

2. Copy the edid.bin file to the folder : `cp ~/edid.bin ~/test/usr/lib/firmware/edid` and to `/usr/lib/firmware/edid/` : `cp ~/edid.bin /usr/lib/firmware/edid`

3. CD into test directory : `cd ~/test` and run this : `find . | cpio -H newc -o | gzip >> ../my-initrd.img`
The `my-initrd.img` file will be created in the home directory.

4. Create initrd.d folder : `sudo mkdir -p /etc/kernel/initrd.d`

5. Copy the initrd img file to initrd.d folder : `sudo cp ~/my-initrd.img /etc/kernel/initrd.d` and also add the kernel parameter `drm.edid_firmware=eDP-1:edid/edid.bin` to `/etc/kernel/cmdline.d/edid.conf`

6. Update clr-boot-manager : `sudo clr-boot-manager update` and reboot.

**Comment by ahkok** [comment]
Yes, even with the kernel option enabled, you still have to create your own initrd image - we can't make this for you.

**Comment by gurtonbuster** [comment]
> Yes, even with the kernel option enabled, you still have to create your own initrd image - we can't make this for you.

Yes but using an initrd file to load a custom edid file isn't required for other Linux distros.

**Comment by ahkok** [comment]
Not every distribution is the same.

**Comment by ahkok** [comment]
I believe you can disable the initrd too, not sure if that may work. From `man clr-boot-manager`:
```
       /etc/kernel/initrd.d/*
           A set of files that will be used as additional user's freestanding initrd files.  Additional initrd arguments will be  added  to
           the  kernel  argument  list,  if  desired  the user may mask out system installed initrd files by creating symbolic links within
           /etc/kernel/initrd.d pointing to /dev/null with same name of system installed files.
```

**Comment by miguelinux** [comment]
> Yes but using an initrd file to load a custom edid file isn't required for other Linux distros.

Well, others distros creates/generates the initrd every time you update the kernel with dracut ;-)
