### ISSUE TITLE
Zabbix Agent

### ISSUE THREAD

**Issue by rwattogl** [clearlinux/distribution#1627]
We deploy micro-services to Clear Linux, and wish to monitor these servers from our central Zabbix Server. To do so we need a Zabbix bundle, but only the agent aspect. Zabbix comes as a single source bundle comprising server and agent, but can be configured and compiled with only the agent, which has relatively few dependencies.

**Comment by ahkok** [comment]
Working on it...

**Comment by ahkok** [comment]
`zabbix` (server and tools) and `zabbix-agent` bundles will be available in 1-2 days.

I've excluded java/golang support. I suspect for the golang client (v5 forward) we may need a separate build for that.

**Comment by rwattogl** [comment]
Fantastic work, I got it working manually yesterday, but it's not a great solution for mass deployment.

v5 support may not be a major issue for many, most people will be on 4.4 or the 4.0 LTS version for a good while yet and in any case the agent parts tend to be very compatible (you can use a v1.4 agent with a v5 server according to https://www.zabbix.com/documentation/5.0/manual/appendix/compatibility)

**Comment by ahkok** [comment]
Available now, give it a try and file issues for anything you see missing (service units may be, for instance).

**Comment by jerry3k** [comment]
Adding the zabbix-agent bundle doesn't add any /etc/zabbix folder, also running 'systemctl start zabbix-agent' returns 'Failed to start zabbix-agent.service: Unit zabbix-agent.service not found.'
