### ISSUE TITLE
Please add libpcap0.8-dev, libuv1-dev 

### ISSUE THREAD

**Issue by gut5** [clearlinux/distribution#1629]
libpcap0.8-dev
libuv1-dev

(these were the Ubuntu names for the packages)

**Comment by fenrus75** [comment]
devpkg-libpcap
is not what you want?

**Comment by gut5** [comment]
Yes that package you mention seems to be something that could work for what I'm doing.
Trying to add libuv forces me to download about 8GB of additional software which is not really helpful at all.

**Comment by fenrus75** [comment]
I'm adding a devpkg-libuv

**Comment by gut5** [comment]
Thanks
