### ISSUE TITLE
Enable pre-GCN 1.2 AMDGPU driver support

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#163]
### What is the issue type?

* [ ] Bug report
* [X] Enhancement request

### Describe the problem

I made a pull request (see clearlinux-pkgs/linux#7) so that Southern Islands and Sea Islands GPUs can utilize the AMDGPU driver is desired (instead of the usual radeon driver). This choice is available in other distros, like Solus and Fedora 28.

**Comment by fenrus75** [comment]
thanks for the contribution.
as I put in the other PR it's in the cooker now should be available very shortly

**Comment by OpenSourceAnarchist** [comment]
Thank you! I never submitted a pull request before (new to actually contributing to projects) and I wasn't aware that Clear used "config-fragment" to generate the config file, as you noted in the PR. Now I know!

**Comment by fenrus75** [comment]
it's really new.... maybe a week or so.
