### ISSUE TITLE
Request for saltstack (minion and master) packages

### ISSUE THREAD

**Issue by jlmeeker** [clearlinux/distribution#1630]
**Description:** Salt is a new approach to infrastructure management built on a dynamic communication bus. Salt can be used for data-driven orchestration, remote execution for any infrastructure, configuration management for any app stack, and much more.

**Comment by ahkok** [comment]
How does this compare with `ansible`?

**Comment by jlmeeker** [comment]
Similar to Chef, Puppet, Ansible in that it can be used to define various aspects of server configuration (file contents, packages installed, service states, users etc.).  But, unlike the others (AFAIK) it is also a mass-communication method so running commands across multiple machines is also extremely useful.

**Comment by ahkok** [comment]
So we can package `salt` (`salt-ssh`) without problems. Since I don't know how to use it or what kind of split there needs to be, I'm going to throw it all into one `salt`  bundle for now. If you do have enhancements you'd like to see, please propose them in a different issue one by one!

**Comment by ahkok** [comment]
`salt` bundle will be available in 2 days or so.
