### ISSUE TITLE
Package TLP missing default config file

### ISSUE THREAD

**Issue by JDNightwalker** [clearlinux/distribution#1635]
The powersave and tunables package TLP is missing its default config file, which should be located in /usr/share/defaults/tlp. The program works, but launching it as a service results in the error:

Error: TLP power save is disabled. Set TLP_ENABLE=1 in /usr/share/defaults/tlp.

The config file normally has a long list of tunables and explanations for each, including power options for CPU governor states, devices, storage, etc.

If the default config file with all the explanations / examples could be added, it would be most appreciated!!

Discussion on the Clear Linux forum can be found here:
https://community.clearlinux.org/t/tlp-default-configuration-file/2574

**Comment by ahkok** [comment]
`TLP-1.2.2-2`

The `/usr/share/defaults/tlp` file now exists. It can be copied to `/etc/tlp` and then modified if you wish to change any of the values. A note at the top of the file indicates this as well.

Should be in a release in 1-2 days.
