### ISSUE TITLE
Please update Firefox

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1636]
There are known and already used vulnerabilities

**Comment by lebensterben** [comment]
>There are known and already used vulnerabilities 

@seafrog1 Firefox is self-maintained, it would be updated whenever there's one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anselmolsm** [comment]
Besides that, the version included in CL releases was updated to 72.0.1 (latest as of now) on 32060 published yesterday:

https://download.clearlinux.org/releases/32060/clear/RELEASENOTES

**Comment by seafrog1** [comment]
Hi, thanks but my Clr version is 32070 and my Firefox Version is 71.0. So its not updated automatically.

It is possible to update manually but there should be a clear statement by Clr which programs are updated automatically like (close to all including Mozilla Thunderbird) and which we have to take care of ourselves.

**Comment by lebensterben** [comment]
> Hi, thanks but my Clr version is 32070 and my Firefox Version is 71.0. So its not updated automatically.
> 
> It is possible to update manually but there should be a clear statement by Clr which programs are updated automatically like (close to all including Mozilla Thunderbird) and which we have to take care of ourselves.

This is a problem of how Firefox is rolling out their updates. I've same OS version my Firefox is on 72.0.

Usually there could be some delay before your Firefox is updated, but it won't take long.

**Comment by eadamsintel** [comment]
Mine automatically updated yesterday while using it.  I just tried the [manual update instructions](https://support.mozilla.org/en-US/kb/update-firefox-latest-release) just now on a different computer and it started updating right away.

**Comment by ahkok** [comment]
Not in our control. Use the linked manual method if you're still not seeing the update.
