### ISSUE TITLE
Please add a package for libgconf-2

### ISSUE THREAD

**Issue by tvst** [clearlinux/distribution#1638]
I'm using [Cypress](https://www.cypress.io/) to test JS code, but when I run it in Clearlinux I get the following error:

```
error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

So resolve this, I had to install a 700MB bundle called `games`. However, I have no interest in any of these games, and would rather not have them on my machine.

Is it possible to package libgconf2 separately?

**Comment by thiagomacieira** [comment]
A package exists already, it's "GConf" (but packages are not installable directly by swupd). What you're asking for is that it be added to a smaller bundle. It's only available as dependencies of larger things, like GNOME, which it's a part of.

There's "devpkg-GConf". Does that help you? I assume you're building something from sources, so you probably need the headers for GConf anyway.

**Comment by tvst** [comment]
Yup, that probably works. Funny that swupd didn't tell me about it when I did a search... So maybe we should file a swupd bug?

Either I'll just mark this as closed. Thanks!

**Comment by phmccarty** [comment]
@tvst Sure, feel free to file a swupd bug. If you can list the search term (or multiple search terms) you tried, that would help the swupd team diagnose.
