### ISSUE TITLE
"Switch User" Option Missing

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#1639]
When Selecting my user on Gnome in the top-right, I should have the option to "switch user" (I run multiple user accounts on the same system).

Currently nothing is displayed as per the screenshot below.

![User Switch Screenshot from 2020-01-14 22-04-29](https://user-images.githubusercontent.com/1720468/72339457-5bf9db00-371a-11ea-861b-3001825a6599.png)

**Comment by rossburton** [comment]
Switch User isn't present for me until I added a second user when it appeared.  Can you confirm that this is still a problem with the latest Clear?  Can you verify that you can see the other users in Settings->Details->Users?

**Comment by pceiley** [comment]
Thanks for following up. The issue was actually resolved a few days after I logged the issue. I was going to post a thanks but forgot about it.

It was definitely fixed by someone (the functionality had been broken for some time before I reported it) - but looks like the issue was never closed.
