### ISSUE TITLE
crio: incomplete build configuration

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#164]
CRI-O's build gets the following build configuration ```btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove exclude_graphdriver_btrfs containers_image_ostree_stub   containers_image_ostree_stub``` as the result of ```BUILDTAGS```checks.

This results that at least seccomp, devicemapper, btrfs are missing.

Consider adding the necessary dependencies in autospec files  (```pkgconfig_add```?)

**Comment by iphutch** [comment]
@joselamego could you please take a look.

**Comment by joselamego** [comment]
On the backlog.

**Comment by DnPlas** [comment]
@mythi when you say that at least seccomp and devicemapper are missing, you mean they're not fully functional (for instance on the CLI: the "--seccomp-profile <path to seccomp-profile.json>" and "--storage-opt devicemapper" options)? A use case or a particular way to reproduce this issue will be useful.

**Comment by AntonioMeireles** [comment]
fwiw and specifically for the `devicemapper` part the mod in the buildReqs was already suggested by me in IRC to @joselamego. last tuesday, and according to him it should be consumable soonish :)

**Comment by mythi** [comment]
I have the changes implemented. Let me submit the patch.

**Comment by DnPlas** [comment]
@joselamego and I were talking about this change yesterday and implemented it the same way @mythi did, so it is a +1. I will close the issue when the commit gets on Github.
Thanks!

**Comment by DnPlas** [comment]
Commit 4b14ab5a1c87ad979746635f73179ed26f8405b7 fixes the issue.
