### ISSUE TITLE
Package request: ZoneMinder

### ISSUE THREAD

**Issue by ljmccarthy** [clearlinux/distribution#1640]
Strangely, this package is listed on the website: https://clearlinux.org/software/bundle/zoneminder

But when I tried to install, it says the package does not exist.

```
$ sudo swupd bundle-add zoneminder
Loading required manifests...
Warning: Bundle "zoneminder" is invalid, skipping it...
Failed to install 1 of 1 bundles
```

**Comment by ahkok** [comment]
We dropped it due to it not meeting our general security requirements, sorry. It will not be added back for the same reason.

**Comment by ljmccarthy** [comment]
What security requirements does it not meet? I suppose I'll have to run it in Docker then.

**Comment by ahkok** [comment]
It bundles outdated components with known issues. The list of open CVE's also was too large. It also runs all the various daemons and scripts as root, further making it a risk.

**Comment by ljmccarthy** [comment]
OK I haven't looked in to it too much. That's a bit disappointing but not that unexpected. I will only be running it on a local network firewalls from the internet anyway.

**Comment by ahkok** [comment]
I understand - I myself ran it for a very long time (several years actually).

I haven't found a good solution either. I tried `shinobi` which looked great but also is a fragile `nodejs` bunch that broke many times for me (unacceptable for any sort of security purpose). Currently I'm directly recording the `rtsp` streams with a `systemd.timer` unit that runs gstreamer/ffmpeg which gives me the thing I need - If there is a secure and non-fragile way of doing your own CC recording that doesn't require interpreted languages with package salads, then, I'd be all ears.... :)
