### ISSUE TITLE
Missing man pages for ipmctl and ndctl utilities

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#1643]
If you try to do `$man ipmctl` or `$man ndctl` you get an error of "No manual entry for ..."  I installed these tools on Fedora 30 and they include the man pages.

**Comment by phmccarty** [comment]
Looks like [asciidoctor](https://asciidoctor.org/) is needed to build man pages for both of those packages.

**Comment by ahkok** [comment]
Which is problematic, and the reason we don't have those man pages atm.

**Comment by ahkok** [comment]
oh, looks like we can use `asciidoc` instead.

**Comment by ahkok** [comment]
The manuals for ipmctl are in `txt` format? I don't see any man page format for it in the sources. From the ipmctl links I checked fedora and suse spec files and those do not have any man pages either for ndctl.

**Comment by ahkok** [comment]
@eadamsintel are you sure about the `man ipmctl` working on fedora?

**Comment by ahkok** [comment]
Looks like a branch issue. We're shipping `v2` which does not have manual pages. Somehow `v1` releases (that fc32 has) does have them. This appears to be an upstream bug then.

**Comment by ahkok** [comment]
ok, so I can get it almost working for `ipmctl` however, it b0rks on this:

```
/usr/bin/asciidoc.py --backend docbook -a "a2x-format=manpage"  --doctype manpage --attribute "mansource=ipmctl" --attribute "manmanual=ipmctl" --attribute "ipmctl_version=01.00.00.9999" --attribute "os_build=1" --attribute "manpage=1"  --out-file "/builddir/build/BUILD/ipmctl-02.00.00.3694/output/debug/manpage/ipmctl-show-error-log.tmp.xml" "/builddir/build/BUILD/ipmctl-02.00.00.3694/output/debug/manpage/ipmctl-show-error-log.tmp.txt"
asciidoc: ERROR: ipmctl-show-error-log.tmp.txt: line 103: [blockdef-example] missing closing delimiter
```

So, currently blocked by upstream issue with the doc pages...

**Comment by eadamsintel** [comment]
@ahkok Yes I am sure. I just tried again. Below is a part of the output when scrolling back.  I should note that the 32050 (IIRC) release of Clear Linux with ipmctl and ndctl are buggy with the `ipmctl show -memoryresources` command not properly working.  Version 31410 of Clear Linux does work which has an older ndctl utility/library.  This was previously [reported](https://github.com/clearlinux/distribution/issues/1537).

```
eadams@fedorakata ~> man ipmctl
IPMCTL(1)                                                        ipmctl                                                        IPMCTL(1)

NAME
       ipmctl - Utility for managing Intel Optane DC persistent memory modules (DCPMM)

SYNOPSIS
       ipmctl COMMAND [OPTIONS] [TARGETS] [PROPERTIES]

OPTIONS
       -h, --help
           Run ipmctl help command.

DESCRIPTION
       Utility for managing Intel Optane DC persistent memory modules (DCPMM)
```

**Comment by ahkok** [comment]
`ndctl` man pages will be fixed soon, `ipmctl` we'll see what upstream does about it.

**Comment by ahkok** [comment]
Fixed! already released.
