### ISSUE TITLE
irqbalance ships with sub optimal service file

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#1645]
Hi all!

out of the box, in a clean install, (up to latest 32090) the `irqbalance` systemd service does not fully behave as expected. 

service is ranting `/usr/bin/irqbalance[750]: Daemon couldn't be bound to the file-based socket.`.

AFAICS CL is shipping with a oldish service file (from https://github.com/clearlinux-pkgs/irqbalance/blob/master/irqbalance.service) which does not meet current shipping code expectations (namely the ones introduced by [this](https://github.com/Irqbalance/irqbalance/commit/f5ca2eb481ac76b799c8efef5a7b7469bb368fd5) specific commit). At sight fix would be to ship either plain upstream service file (https://github.com/Irqbalance/irqbalance/blob/master/misc/irqbalance.service) or something way closer to it.

Thanks in Advance && Best Regards

(edited to make things clearer as the service isn't technically 'failing' )

**Comment by ahkok** [comment]
I think we want to remain having it run as a oneshot service by default. Users who want to override it can `sudo systemctl edit` the unit to change the mode. Other than that minor change, I assume the upstream unit is working properly. If this comes out in 1-2 days and doesn't work, please re-open.

**Comment by ahkok** [comment]
`irqbalance-1.6.0-16`

**Comment by bryteise** [comment]
I think the issue is that the socket directory isn't created, I added a tmpfile to do so and the error went away for me (should be in tomorrow's release).
