### ISSUE TITLE
jwm and pcmanfm package request

### ISSUE THREAD

**Issue by davidpaulos** [clearlinux/distribution#1647]
i am here to kindly request jwm as an alternative desktop to i3wm or awesome as it is one of the staples of the linux desktop found on many a distro like the popular puppy linux 

and to request pcmanfm as a separate bundle from lxde or lxqt as it is a great file manager and many people like to use it instead of thunar or dolphin

please do add these 2 packages thanks in advance for the time and consideration

**Comment by ahkok** [comment]
Added `pcmandm` bundle. Should be in a release in 1-2 working days.

**Comment by ahkok** [comment]
I'm closing this. There are already enough window managers available to cover and act as a decent low end WM - even `xfwm4` would suffice.
