### ISSUE TITLE
RAPIDS for data science

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1649]
an alternative to numpy and pandas, it runs on nvidia gpu, claims faster than numpy and panda.
https://rapids.ai/start.html

**Comment by ahkok** [comment]
Is this even OSS? It depends, apparently, on proprietary and non-open source NVIDIA components. I am doubtful this meets our package inclusion requirements therefore.

**Comment by lebensterben** [comment]
>Is this even OSS? It depends, apparently, on proprietary and non-open source NVIDIA components. I am doubtful this meets our package inclusion requirements therefore.

@ahkok it requires python 3.6 or 3.7. are we on python 3.8 now?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by phmccarty** [comment]
Yes, we have updated to python 3.8

**Comment by ahkok** [comment]
`3.8`...

**Comment by stokhos** [comment]
Yes it is opensource software. It's on the GitHub.

**Comment by lebensterben** [comment]
>Yes it is opensource software. It's on the GitHub.

@stokhos This software breaks license agreement of things it depends on. As one example, part of it is a direct port of scipy, where the latter one has a different license and that permits modifications but requires inclusion of the original license. But this software didn't. When it breaks the license requirements, it's no longer granted the rights from scipy.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
