### ISSUE TITLE
kata-runtime: CRI-O runtime selection

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#165]
https://github.com/clearlinux-pkgs/kata-runtime/commit/d9a9e12eddb254344adc6c33af461a387b991758 is problematic because:

1. it runs on every boot
2. does not check if kata-runtime can be run on a platform
3. changes distro's policy on ```default_workload_trust```

**Comment by joselamego** [comment]
For point 1, I agree that the service trigger could be improved performance wise.

Point 2 also sounds reasonable, although I'm wondering if leaving untouched the default runtime would be enough for non-supported platforms (considering they would still have kata containers installed).

For point 3, I need more background regarding that policy and, given that the cri-o default runtime selection was implemented following what was done for docker default runtime I'd like to hear William's feedback.
All that said, I believe this request can be considered an enhancement, not a bug.

 @bryteise: Thoughts on this?

**Comment by joselamego** [comment]
@DnPlas: FYI

**Comment by joselamego** [comment]
Thanks @bryteise . What about setting the `default_workload_trust` as `untrusted`?

**Comment by bryteise** [comment]
@joselamego runtime_untrusted_workload and default_workload_trust should be set at the same time to matching values. The mechanism should mirror how docker is setup and should behave as follows:
1) Check if a configuration has already been created in /etc and stop if it has (this running every boot is okay).
2) Verify if kata is able to be used (available and usable and this should be able to run every boot since it should be just file existence checks).
3) Insert the needed components into /etc to override the default behavior (this should only be run once).

**Comment by DnPlas** [comment]
@bryteise I wonder if the second (verifying if kata-runtime is available and usable) should be applied on the docker setup as well.

**Comment by bryteise** [comment]
@DnPlas Ah sorry, I wasn't paying attention to what package this was being applied to X(. Step 2 isn't needed for this (or docker) because we assume given the package is the runtime, if it is installed it will work (given step 1's check succeeds).

**Comment by DnPlas** [comment]
@bryteise yeah, makes a bit more sense not to include a check because the package making changes is the actual runtime, it should exist and be usable. We were kind of figuring out what @mythi referred on 2.

**Comment by joselamego** [comment]
@mythi: I'm assuming you refering in point 2 to the verification made with `kata-runtime kata-check`, correct? If so, do you believe that we may expect users with non-supported platforms installing the `containers-virt` bundle?

**Comment by bryteise** [comment]
@joselamego @DnPlas Ah I was being a little confusing, you still need to test if /dev/kvm exists (that is done in my earlier docker runtime change [here](https://github.com/clearlinux-pkgs/kata-runtime/blob/master/0002-Add-Clear-Linux-Docker-integration-for-Kata-Containe.patch#L52) but you don't need to verify if kata-runtime itself works beyond that I don't think.

**Comment by bryteise** [comment]
So you essentially need two path exists checks like my change had in the service to satisfy @mythi points 1 and 2 I think (but you need to make crio support a fallback configuration location in /usr in addition to the /etc config as part of that).

**Comment by DnPlas** [comment]
> Yes. 1. is to check whether the config override already exists, and 2. that /dev/kvm is available. Currently, if user wants to install kubernetes, they automatically get containers-virt without knowing their platform can run Kata.
Please check the last [patch ](http://kojiclear.jf.intel.com/cgit/packages/kata-runtime/commit/?id=de65cf5da305d7c0f695d930349300e83e10a1c9) I sent to kata-runtime, we are now ensuring the config file doesn't exist and /dev/kvm does.

>CRI-O does not seem to support passing untrusted runtime setting command line (this would be good to add, btw) so likely the way to config kata-runtime now would be pass something like kata-enabled-crio.conf to crio --config.
The service we add when installing containers-virt creates a config file in /etc/crio, which is the default path crio --config looks for. I think we are also covering this on the patch I mentioned before.

**Comment by egernst** [comment]
@joselamego - just catching up on this issue backlog.  Regarding comment [1], I would not recommend setting default as untrusted.  I would keep the default in CRIO as trusted, allowing the user to opt-in to using a more secure sandbox.

Please note, these annotations will start to be deprecated in the 1.12 time frame via the runtimeClass alpha feature of Kubernetes.

[1] -  https://github.com/clearlinux/distribution/issues/165#issuecomment-416712066

**Comment by DnPlas** [comment]
@egernst If I understood correctly, leaving the default as trusted will setup runc for trusted workloads and kata-runtime for untrusted ones, so it doesn't really matter if we've got kata-runtime installed, the most secure approach is always runc for trusted workloads. I'll send a patch making the proper changes.

**Comment by DnPlas** [comment]
> 3. changes distro's policy on default_workload_trust
@egernst @mythi the latest change in kata-runtime should fix the third comment.

**Comment by mythi** [comment]
@DnPlas Thanks! The idea here is that the trusted/untrusted selection comes from kubernetes.

**Comment by DnPlas** [comment]
Commits 1e2a1d655a856c328f160b0408776b430376a4b9 and de65cf5da305d7c0f695d930349300e83e10a1c9 solve this issue.

**Comment by pohly** [comment]
Daniela Plascencia <notifications@github.com> writes:
> Commits 1e2a1d655a856c328f160b0408776b430376a4b9 and
> de65cf5da305d7c0f695d930349300e83e10a1c9 solve this issue.

In which repo?

**Comment by joselamego** [comment]
@pohly in Clear Linux's kata-runtime package repo.

**Comment by phmccarty** [comment]
Repo: https://github.com/clearlinux-pkgs/kata-runtime

@DnPlas I do not see commit 1e2a1d655a856c328f160b0408776b430376a4b9 in that repo? Perhaps that change has not made it into a published release yet?

**Comment by DnPlas** [comment]
@phmccarty It is not yet on the public repo, but on the private one (kojiclear cgit). I think it will take a while to be reflected on Github.
