### ISSUE TITLE
How to install Tensorflow 2.1.0 or Nightly

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#1652]
How do you get Tensorflow 2.1.0 or Nightly into CL ?

pip3 install --user --upgrade tensorflow-gpu==2.1.0

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.1.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu==2.1.0

pip3 install --user --upgrade tf-nightly
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly

Download:
tensorflow_cpu-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl
pip3 install t*.whl

ERROR: tensorflow_cpu-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl is not a supported wheel on this platform.

**Comment by lebensterben** [comment]
This is not an issue of this distribution.

You can find the official guide here
https://www.tensorflow.org/install/pip

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahkok** [comment]
Relabelled - this is a feature request (for a non-stable release to be included) or a documentation request.

**Comment by phmccarty** [comment]
Tensorflow was removed from Clear Linux OS in November, so we can close this request.
