### ISSUE TITLE
Please add package for gifsicle

### ISSUE THREAD

**Issue by MarkRose** [clearlinux/distribution#1653]
gifsicle is a GPLv2-licensed tool for optmizing animated GIFs.

Perhaps it could be included in a new graphic-optimization bundle along with jpegoptim and pngcrush?

https://github.com/kohler/gifsicle

**Comment by bryteise** [comment]
Hrm graphic-optimization bundle seems a little too fuzzy for a bundle concept. Do you view these 3 as always going together or would putting each into their own bundle be a reasonable approach?

**Comment by ahkok** [comment]
We should glob these and `optipng` into a bundle, for sure (since we already have that one).

**Comment by bryteise** [comment]
The optipng is only in -dev bundles at the moment. So still would need a broader home for them. Are there other packages we'd want in something graphics-optimization like? Just trying to figure out what that really means. I am somewhat more in favor of making individual package bundles and letting a larger organizing bundle come into form later on.

**Comment by ahkok** [comment]
tbh this would fit really well with ImageMagick...

**Comment by fenrus75** [comment]
pixel-mongers

**Comment by bryteise** [comment]
I'm going to add them to ImageMagick for now, they are about 1M total in new content.

**Comment by MarkRose** [comment]
Thanks for adding these!
