### ISSUE TITLE
DPDK 19.11 LTS

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1658]
Our current version is slightly outdated. 

https://doc.dpdk.org/guides/rel_notes/release_19_11.html#

**Comment by ahkok** [comment]
This update breaks all the SONAMEs.. is that normal?

**Comment by mythi** [comment]
@ahkok I could help with this but did you run into problems with the build?

**Comment by mythi** [comment]
verified using `dpdk-test-crypto-perf`:

`EAL: RTE Version: 'DPDK 19.11.0'`
