### ISSUE TITLE
Can not change I/O scheduler

### ISSUE THREAD

**Issue by cornerot** [clearlinux/distribution#1659]
Clear Linux version: Linux clr-4b39c1be98974a6280bdd3d4736adfcc 5.4.13-895.native
Platform: proxmox 6.1-3
Loader config:

> title Clear Linux OS
linux /EFI/org.clearlinux/kernel-org.clearlinux.native.5.4.13-895
initrd /EFI/org.clearlinux/freestanding-00-intel-ucode.cpio
initrd /EFI/org.clearlinux/freestanding-i915-firmware.cpio.xz
options root=PARTUUID=c630bae1-b59b-48f0-83c5-fd048a183aad quiet elevator=none console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcu_nocbs=0-64 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs tsc=reliable rw 

But after rebooting, I see "bfq" instead "none":

> cat /sys/block/sda/queue/scheduler
mq-deadline kyber [bfq] none

**Comment by ahkok** [comment]
`sudo systemctl mask clr-power-tweaks`.

Caveat: you will need to manage all the other tunings that `clr-power-tweaks` as well.

**Comment by cornerot** [comment]
Thanks!
Correct comand:
```
sudo systemctl mask clr-power
```

But it’s more correct to do it through a custom unit
