### ISSUE TITLE
PHP 7.4.1 -> 7.3.13, updated bundle/packages ETA?

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1664]
PHP is up to 7.4.1 now.

Anyone have any idea when there will be a bundle with current version, as we are still on 7.3.13
or idea what the Clear Linux prerequisites for moving bundle to major releases?

thanks

**Comment by anselmolsm** [comment]
7.3.14 and 7.4.2 released today.

**Comment by ahkok** [comment]
I'm looking at rebasing the patches atm...

**Comment by ahkok** [comment]
Looks like a fairly large update where a lot of things need to be addressed.... this may take a few days longer.

**Comment by ahkok** [comment]
About to be released!
