### ISSUE TITLE
Add OpenCL to wine 

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#1671]
`0039:err:opencl:init_opencl Failed to open library libOpenCL.so.1: libOpenCL.so.1: cannot open shared object file: No such file or directory`

Fixed with ` opencl-clang opencl-clang-lib ocl-icd ocl-icd-lib`.

**Comment by ahkok** [comment]
Ill check into this when I have time to look at the 5.0 update.

**Comment by ahkok** [comment]
`wine-5.0-51` fixes this - out in 1-2 days.
