### ISSUE TITLE
Lua-basic and devpkg-lua doesn't provide luajit.pc pkgconfig

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1672]
Installing lua-basic and devpkg-lua doesn't provide the appropriate pkgconfig file luajit, even though it is referenced for installation in the pkg spec: https://github.com/clearlinux-pkgs/LuaJIT/blob/master/LuaJIT.spec

EDIT: it seems devpkg-lua is not providing the headers as well

**Comment by ahkok** [comment]
`lua` and `luajit` are not the same package (they're very different things). We just need to add `LuaJIT` to the list for `devpkg` so that you can `sudo swupd bundle-add devpkg-LuaJIT`.

**Comment by ahkok** [comment]
it'll be lower case - `devpkg-luajit`. Should be in the next release.

**Comment by phmccarty** [comment]
The devpkg bundles are named after the packages, so it should be `devpkg-LuaJIT`. But we will know soon enough :-P

**Comment by fenrus75** [comment]
swupd bundle-add pkgconfig(luajit)

should then work

**Comment by insilications** [comment]
sudo swupd bundle-add pkgconfig(luajit)
bash: syntax error near unexpected token `('

**Comment by insilications** [comment]
sudo swupd bundle-add devpkg-LuaJIT worked perfectly.

Thanks for all the work.
