### ISSUE TITLE
Add clearlinux-pkgs/ffmpegthumbs as a separate bundle

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1673]
Add [clearlinux-pkgs/ffmpegthumbs](https://github.com/clearlinux-pkgs/ffmpegthumbs) as a separate bundle for kde-frameworks5 and/or dolphin. It is outside dolphin-plugins, but could be its own bundle.

**Comment by fenrus75** [comment]
eh why would this need to be separate instead of just in kde-frameworks5?

**Comment by insilications** [comment]
It was just a suggestion. Whatever you think makes more sense is fine. I just want to add it somehow, along with dolphin. Thanks for all your work.

**Comment by insilications** [comment]
@fenrus75 Can you add this into kde-frameworks5 so we can have thumbnail generation in Dolphin with ffmpeg? Thanks for all the work.
