### ISSUE TITLE
crio: update to 1.11.2

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#168]
### What is the issue type?

* [X] Bug report
* [ ] Enhancement request

### Describe the problem

1.11.1 we run has nasty regression in storing container state in ```/var/run``` that disappears in reboot. This means, e.g., kubernetes control plane  containers do not start after a reboot.

**Comment by AntonioMeireles** [comment]
AFAICT [24740](https://download.clearlinux.org/releases/24740/clear/RELEASENOTES) will have it :-)

**Comment by mythi** [comment]
yes, thanks @bryteise!
