### ISSUE TITLE
Miniconda for python envs and packages management

### ISSUE THREAD

**Issue by CuriousCocainist** [clearlinux/distribution#1681]
I think Miniconda would be a useful addition to one of the python related bundles. This could be connected with adding Spyder (issue #896 ) to python-data-science bundle

**Comment by lebensterben** [comment]
Miniconda and anaconda manages themselves and are installed under /opt/conda when they're installed via RPM/DEB. This is different from other packages in swupd that they are installed under /usr.

swupd manages files installed under /usr and ignores /opt. So to add conda, we will need to make many changes to swupd-client.

In addition, according to Filesystem Hierarchy Standard, /usr is install path of package manager. While /opt is large managed by user. So I'm against adding conda to swupd.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bryteise** [comment]
I agree with @lebensterben that conda is more something a user installs themselves rather than is distro provided. That said having content that is distro provided (living in /usr) that manages installation of content into /opt isn't problematic to me. I also note that we already had this packaged but just didn't put it into a bundle. I added the conda bundle for now (should be in the next release or so) and we can decide if this form is useful for folks or if it is best left to end users installing. So I'll be looking for your feedback @CuriousCocainist =).

**Comment by fenrus75** [comment]
what does conda bring that pypi doesn't?
doesn't pypi basically provide "all of python" ?

**Comment by CuriousCocainist** [comment]
Thanks for rapid responses :)
I think it's to go solution to conveniently manage python virtual environments. It combines functionality of few other packages (https://docs.conda.io/projects/conda/en/latest/commands.html#conda-vs-pip-vs-virtualenv-commands), allows easily use different versions of python in different environments and pip (per environment) can be used anyway :)

**Comment by CuriousCocainist** [comment]
After a very brief test it appears that:
* conda can be activated, but 
* VS code (OSS) doesn't see it (interestingly it sees python 3.7.4 instead 3.8...?)
 * I can't create an environment with conda (terminal output below)

```
(base) Person@home~ $ conda create test_1

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/lib/python3.8/site-packages/conda/cli/main_create.py", line 10, in <module>
        from .install import install
      File "/usr/lib/python3.8/site-packages/conda/cli/install.py", line 21, in <module>
        from ..core.solve import DepsModifier, Solver
      File "/usr/lib/python3.8/site-packages/conda/core/solve.py", line 14, in <module>
        from .link import PrefixSetup, UnlinkLinkTransaction
      File "/usr/lib/python3.8/site-packages/conda/core/link.py", line 43, in <module>
        from ..resolve import MatchSpec
      File "/usr/lib/python3.8/site-packages/conda/resolve.py", line 9, in <module>
        from tqdm import tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ /usr/bin/conda create test_1`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/usr/bin/conda
             CONDA_PREFIX=/usr
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/usr/bin/python
               CONDA_ROOT=/usr
              CONDA_SHLVL=1
                  LA_PATH=/usr/lib64/
                 MPI_PATH=/usr/lib64/
                     PATH=/usr/bin:/usr/bin:/usr/condabin:/usr/bin/haswell:/usr/local/bin:/usr/l
                          ocal/sbin:/usr/bin:/opt/3rd-party/bin
         PYTHONIOENCODING=utf-8:surrogateescape
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /usr
            shell level : 1
       user config file : /home/Person/.condarc
 populated config files : 
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.8.1.final.0
       virtual packages : __glibc=2.31
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/pkgs
                          /home/Person/.conda/pkgs
       envs directories : /home/Person/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.8.1 Linux/5.5.7-916.native clear-linux-os/32550 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by lebensterben** [comment]
@CuriousCocainist 
VS Code from flatpak cannot see things outside of the sandbox. It's not a bug.

**Comment by CuriousCocainist** [comment]
@lebensterben 
You're very right and I saw people complaining about it...
So using VS Code this (flatpack) way defeats the purpose (unless I can freely update e.g. python version inside flatpack?... sorry I'm a noob here :). I also don't see it in any of the bundles, which would be a preferred option (access to system "layer"). Spyder is present but other IDEs not really... so I understand that people use Spyder or finda a way to harness PyCharm/VS Code/other in a flatpack prison?

**Comment by lebensterben** [comment]
>@lebensterben  ...

@CuriousCocainist Google and install VSCode tarball.
