### ISSUE TITLE
mysql-client librarie

### ISSUE THREAD

**Issue by shtirlic** [clearlinux/distribution#1683]
Since Clearlinux used in many scenarios, installation whole Mariadb server package looks like a little bit overhead for simple querying remote databases.
Ref: https://github.com/clearlinux/dockerfiles/issues/294

**Comment by ahkok** [comment]
That's a good point, we should have those split out.

**Comment by ahkok** [comment]
Done. bundle `mariadb-clientlibs`

**Comment by ahkok** [comment]
Out in ~2 days as usual.

**Comment by thiagomacieira** [comment]
There should be no need for a bundle: RPM dependencies will include the libs (which aren't big) in any package that requires them.

**Comment by shtirlic** [comment]
While it might be true for some packages,  but for languages like ruby, node.js, go with own package systems and needs to build  packages with native extensions.
