### ISSUE TITLE
nginx-mainline failed to start due to out of date nginx-mainline-extras

### ISSUE THREAD

**Issue by ljmccarthy** [clearlinux/distribution#1687]
An automatic update has caused my nginx-mainline web server to go offline due to out of date nginx-mainline-extras.

I would recommend to synchronise the release of these 2 packages to avoid this situation in the future.

**Comment by phmccarty** [comment]
Sorry for the breakage. I am rebuilding all of the modules for nginx-mainline now.

**Comment by ahkok** [comment]
I posted a test to `openBBT` that could spot this error.
