### ISSUE TITLE
docs: image signature verify fails

### ISSUE THREAD

**Issue by tpepper** [clearlinux/distribution#169]
It looks like the build signing process and associated docs might have recently changed in https://github.com/clearlinux/distribution/issues/85
and something trivial got missed.

As it stands today https://clearlinux.org/documentation/clear-linux/guides/maintenance/validate-signatures#image-content-validation appears incorrect.  It states:

```
Important

The ./ in the file name must be included because it is part of the SHA512 sum of the image. Without it, the validation of the signature of the image will fail.
```

But if you look at for example https://download.clearlinux.org/image/clear-24750-vmware.vmdk.xz-SHA512SUMS the "./" is not in the file.  Signature validation fails if "./" is included by the user when doing:

```
shasum -a 512 ./clear-24750-vmware.vmdk.xz > sha512sum.out
```

It appears the documentation should have the suggested command as:
```
sha512sum clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz > sha512sum.out
```
and a note like:

```
Important

Path information such as "./" or "/home/myuser/Downloads/" MUST NOT be included in this command line for the image file, because it becomes part of the SHA512 sum of the image. Without an exact filename match versus the downloaded SHA512SUMS contents, the validation of the signature of the image will fail.
```

As of today's 24750 images none of the SHA512SUMS files have a "./" inside them.

**Comment by ahkok** [comment]
Can I get you to post this at:

https://github.com/clearlinux/clear-linux-documentation/issues/new

instead?

**Comment by ahkok** [comment]
Related #85 ?

**Comment by ahkok** [comment]
Moved to https://github.com/clearlinux/clear-linux-documentation/issues/224 , thanks @tpepper !
