### ISSUE TITLE
collectd is not including python.so

### ISSUE THREAD

**Issue by dlpottra** [clearlinux/distribution#1691]
collectd bundle should have a plugin of python.so built and install in /usr/lib64/collectd/ as part of the package.  This used to be in the bundle.  I don't know when it stopped working.  It stopped working recently.  I am currently using version 32210.

**Comment by bwarden** [comment]
python.so was lost in https://github.com/clearlinux-pkgs/collectd/commit/740733403d23a0ef5e143fde95d0297d7580c235

**Comment by bryteise** [comment]
Issue is with collectd and was [fixed](https://github.com/collectd/collectd/commit/071af20ddcde3b58ddceacfd6eb95b6756af4323) just after they made their last release. Patch applied and should be in the next release.
