### ISSUE TITLE
gvfs missing admin backend

### ISSUE THREAD

**Issue by damianatorrpm** [clearlinux/distribution#1692]
Hope this is the right place to report this.
gvfs is missing the admin backend admin:///

```
tux@homed~/cache $ dnf repoquery --releasever=current --whatprovides /usr/libexec/gvfs-admin
Last metadata expiration check: 0:00:30 ago on Sun 02 Feb 2020 06:32:45 PM EET.
tux@homed~/cache $ dnf repoquery --releasever=current --whatprovides /usr/libexec/gvfsd-admin
Last metadata expiration check: 0:00:30 ago on Sun 02 Feb 2020 06:32:45 PM EET.

```

**Comment by bryteise** [comment]
It has always been disabled at configure, I'll see how it looks when I try a build with it enabled.

**Comment by bryteise** [comment]
Ugh and now gvfs pulls in polkit...

**Comment by bryteise** [comment]
Well everywhere gvfs is polkit already is so in it goes. Should be in the next release or so.

**Comment by damianatorrpm** [comment]
@bryteise Awesome, thank you!

**Comment by fenrus75** [comment]
btw can you explain what this is for in terms of usage?
adding more libraries at runtime ends up adding bloat and we really want to
only do that for high value things

**Comment by damianatorrpm** [comment]
@fenrus75 It is the only recommended way on wayland of using a gvfs filemanager with administrative privileges. sudo -E fileManager is unsupported from gnome and may work with nautilus but not other gvfs file managers
