### ISSUE TITLE
Please add ntopng (community edition)

### ISSUE THREAD

**Issue by seafrog1** [clearlinux/distribution#1697]
ntopng - ntop new generation
https://github.com/ntop/ntopng
is a network traffic probe to monitor network flows

**Comment by ahkok** [comment]
I had this on my own list of things for a while. Not the easiest, unfortunately - took quite some convincing to properly package it. I even left an upstream bugreport.

`ntopng` bundle should be available in 1-2 days.

**Comment by ahkok** [comment]
Quick note: you'll want to manually create the `ntopng` user, start redis.service, and create `/var/lib/ntopng` and `chown ntopng` it. In the future we can automate that, but, I feel it's self-evident from the logs that this isn't a big hurdle for something like ntopng.

**Comment by seafrog1** [comment]
Thanks a lot for your efforts
