### ISSUE TITLE
Consider adding wireguard

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#17]
As an alternative to openvpn, wireguard seems interesting to consider including in one of the network basic bundles.

**Comment by iphutch** [comment]
@miguelinux @bwarden can you explore

**Comment by bwarden** [comment]
Investigating.

**Comment by bwarden** [comment]
I was able to take a first look at this today. Currently, Wireguard's kernel module is still out-of-tree, but the project is working to upstream it. We'll have to consider whether it makes more sense to carry it as patches against our kernel package, or wait for it to be available upstream.

**Comment by bwarden** [comment]
Currently waiting for upstream.

**Comment by bwarden** [comment]
Project submitted PR to upstream: https://lkml.org/lkml/2018/7/31/790

**Comment by fenrus75** [comment]
done
