### ISSUE TITLE
Please make live and installer images with less free space

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#170]
Both the installer and live images downloaded from https://download.clearlinux.org/current/ require 8 GB USB sticks to be used. That's because they contain a 5 GB root filesystem. However, they don't need to be that big, as they only have 1.2 GB of content:

```
$ ls -lh clear-live.img
-rw-r--r-- 1 tjmaciei users 5.1G Aug 31 13:38 clear-live.img
$ du -h clear-live.img
1.2G clear-live.img
# losetup -P /dev/loop0 clear-live.img 
# mount /dev/loop0p2 /mnt
# df -h /mnt
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop0p2    4.9G  1.2G  3.5G  25% /mnt
```

**Comment by miguelinux** [comment]
* The propose of **live image** is that you can install bundles, so it needs space to install.
   Maybe padding near to 8G.
* The installer, maybe we should shrink it.

**Comment by ahkok** [comment]
we can enlarge with `ucd`, it has this builtin. We'd only need the os-cloudguest bundle to be added, I think.
