### ISSUE TITLE
linux-preempt-rt, CONFIG_REMOTEPROC is boolean for kernels 5.4+

### ISSUE THREAD

**Issue by mmetak** [clearlinux/distribution#1701]
https://github.com/clearlinux-pkgs/linux-preempt-rt/blob/ba3aeb68c23687de2a2f2edce20852b7ad93091e/config#L6336

**Comment by ahkok** [comment]
@miguelinux

**Comment by miguelinux** [comment]
This will be fixed for the next release

**Comment by miguelinux** [comment]
The fix is already public
