### ISSUE TITLE
kvm broken on amd cpu's

### ISSUE THREAD

**Issue by damianatorrpm** [clearlinux/distribution#1702]
gnome-boxes does not work with amd cpu fx 8320.
After `sudo usermod -a -G kvm $USER` it works on my Intel machine.

It works with amd on all other distributions. (svm is the virt extension of 8320, not vmx).
Not sure if this is an issue with the kernel build or kvm.
> tux@homed~ $ sudo dmesg | grep kvm 
> [    0.894716] kvm: no hardware support

EDIT: must be kvm as I go vmware player running.

**Comment by ahkok** [comment]
No way to fix.

If the kernel reports `kvm: no hardware support` then that's the end of it. Check your BIOS and see if there are options disabled. VMware player is most likely running in emulation mode (without VT/KVM) and gnome-boxes relies on `qemu-system-x86_64` which requires `kvm`.

**Comment by ahkok** [comment]
Looking back on this, perhaps you need to `sudo modprobe kvm_amd` first?

**Comment by damianatorrpm** [comment]
@ahkok Thanks, I did load that and user was added to corresponding group.
I currently can no longer troubleshoot there as I removed CL from that computer.
kvm works fine with openSUSE.

**Comment by ZVNexus** [comment]
> Looking back on this, perhaps you need to `sudo modprobe kvm_amd` first?

This is what I'm curious about though, why would KVM say there's no hardware support if I have it enabled in my BIOS "SVM Enabled", and kvm_amd loads successfully after the fact?

[  216.514001] kvm: Nested Virtualization enabled
[  216.514009] kvm: Nested Paging enabled
[  216.514010] SVM: Virtual VMLOAD VMSAVE supported
[  216.514010] SVM: Virtual GIF supported

**Comment by ZVNexus** [comment]
Oh OK it looks like it might be because KVM_AMD is being built as a module but IDK.
