### ISSUE TITLE
Rlwrap for clojure

### ISSUE THREAD

**Issue by bhougland18** [clearlinux/distribution#1705]
Rlwrap is need for the standard clojure install.  The tools.deps.alpha library needs it for the repl.

**Comment by bryteise** [comment]
I believe this is the upstream source https://github.com/hanslub42/rlwrap?

**Comment by chrysophylax** [comment]
Yep! It'd be very much appreciated. Clojure is already rather ClearLinux friendly be auto-installing to /usr/local so it would make a nice experience if we could just get this package included.

**Comment by bryteise** [comment]
rlwrap should be in the next release or so.

**Comment by chrysophylax** [comment]
Thanks @bryteise - is there any interest in packaging clojure with it and Java? Clojure comes with its own basic dependency manager and all you need for running it is rlwrap, java and the jars.

https://github.com/clojure/clojure is upstream and I don't think there's any conflicting license wrt ClearLinux.

**Comment by bryteise** [comment]
@chrysophylax Unfortunately building clojure looks like it requires mvn which we don't support in Clear Linux.

**Comment by chrysophylax** [comment]
Is there a rationale for mvn not being included in the distribution? In my experience it's the de-facto standard dependency manager for basic java projects (although gradle is also popular) and is under an OK license (e.g. fedora base pkgs include mvn).

**Comment by bryteise** [comment]
The java ecosystem as a whole we largely removed from Clear Linux due to the amount of time we were needing to spend to maintain it, that included mvn and gradle.

**Comment by bhougland18** [comment]
For a clojure dev, I don't think it matters if clojure is included in the
Clear Linux package manager, as the shell script available on Clojure.com
will work as long as rlwrap is there.
