### ISSUE TITLE
Lensfun

### ISSUE THREAD

**Issue by omen70** [clearlinux/distribution#1709]
Please add Lensfun (including lensfun-tools aka liblensfun-bin in Fedora/Debian terms). LGPL licenced lens corrections database/utility for already available RawTherapee and darktable bundles

https://lensfun.github.io/

**Comment by bwarden** [comment]
I've enabled building `lenstool` and created a new `lensfun` bundle. This should show up in a few days.

**Comment by omen70** [comment]
Thank you for bundle. It needs a bit more care.

```
omen@clrlnx~ $ sudo swupd bundle-add lensfun
Loading required manifests...
No packs need to be downloaded
 [100%]

Validate downloaded files
 [100%]

No extra files need to be downloaded
 [100%]

Installing files...
 [100%]

Calling post-update helper scripts
Successfully installed 1 bundle
omen@clrlnx~ $ sudo lensfun-update-data 
Traceback (most recent call last):
  File "/usr/bin/lensfun-update-data", line 46, in <module>
    import lensfun
ModuleNotFoundError: No module named 'lensfun'
omen@clrlnx~ $ 
```

Seems equivalents of following files are missing:
```
/usr/lib/python3/dist-packages/lensfun-0.3.2.egg-info
/usr/lib/python3/dist-packages/lensfun/__init__.py
```

**Comment by bwarden** [comment]
Being able to download new lens definitions will be a two-part operation. First, fixing the bug in the upstream cmake/distutils interaction that doesn't comprehend installing under a build root, and second, reworking it to use/store the downloaded lens database in an appropriate, non-Clear-managed path such as /var.

**Comment by bwarden** [comment]
OK, looks like the project handles the second part nicely -- `/var/lib/lensfun-updates` for system-wide updates, and `~/.local/share/lensfun/updates/` for user-owned updates. I fixed the bug that fails to install the Python module, so that should make it into a release within the next couple of days.

**Comment by bwarden** [comment]
Should be in https://github.com/clearlinux-pkgs/lensfun/commit/3eb2442939388849369f6f1f56421d2d32ca3a9e, when it's released.
