### ISSUE TITLE
please add pm-graph package to clear

### ISSUE THREAD

**Issue by tebrandt** [clearlinux/distribution#171]
I'd like to have the pm-graph package available for install on clear so we can perform suspend/resume testing. The tool has already been made into a debian package, so it should be a relatively simple import.

Package: pm-graph
Source: https://github.com/01org/pm-graph.git
Maintainer: Todd Brandt <todd.e.brandt@linux.intel.com>
Build-Depends: cdbs (>= 0.4.49),
               debhelper (>= 9),
               python:any
Homepage: https://github.com/01org/pm-graph

Architecture: i386 amd64
Depends: ${misc:Depends},
         ${python:Depends},
         python-requests
Description: Power Management performance analysis
 This package is designed to assist kernel and OS developers in optimizing
 their linux stack's boot and suspend/resume time. It includes two tools:
 bootgraph and sleepgraph, which use dmesg and ftrace data to create
 timelines of kernel boot and suspend/resume respectively. The timelines
 provide a detailed view of which devices/subsystems are taking the most
 time in boot and suspend/resume.

**Comment by ahkok** [comment]
Can't be autopackaged. The install creates absolute links to files which are in a buildroot in our builder, and are invalid outside of it. Please make the symlinks relative or guard against DESTDIR usage to avoid this.

```
error: Symlink points to BuildRoot: /usr/bin/bootgraph -> /builddir/build/BUILDROOT/pm-graph-5.1-1.x86_64/usr/lib/pm-graph/bootgraph.py
error: Symlink points to BuildRoot: /usr/bin/sleepgraph -> /builddir/build/BUILDROOT/pm-graph-5.1-1.x86_64/usr/lib/pm-graph/sleepgraph.py
```

**Comment by fenrus75** [comment]
yeap saw the same thing


in addition that package pulls in legacy python, which is about to EOL soon
and is being phased out in the distro.... please convert to python3 asap!

**Comment by ahkok** [comment]
Since it's all python, can this be a pip package instead? It would be wonderful if this ends up being nicely standard pip3 installable... We've got plenty of folks that can help with that too.

**Comment by fenrus75** [comment]
that won't work...it still makes absolute symlinks

**Comment by ahkok** [comment]
We're not adding any new python2 packages anymore. 

Can't you do something like this instead:

https://github.com/clearlinux/kernel-config-checker/blob/master/setup.py

**Comment by thac0** [comment]
Colleagues: please assign this to me. Thanks!

**Comment by thiagomacieira** [comment]
> Colleagues: please assign this to me. Thanks!

GitHub does not accept you as an assignable person.

**Comment by thac0** [comment]
Upstream port to python3 being tracked here:
- [Bug 201385 - upgrade pm-graph to python3.0 before python2 is end-of-lifed](https://bugzilla.kernel.org/show_bug.cgi?id=201385)

**Comment by thac0** [comment]
Just got a note that master branch of pm-graph is python3-ready. Awaiting a release tag, and I'll package it. In the meantime, I'll be messing around with the bleeding edge.
