### ISSUE TITLE
Maybe ping (command/util) should include in sysadmin-basic bundle? 

### ISSUE THREAD

**Issue by 0x808** [clearlinux/distribution#1711]
Subj

The common used (and turned on even livecd desktop installation) utility lives separately in the backyards of other bundle (clr-network-troubleshooter)... why not in sysadmin-basic?

**Comment by bryteise** [comment]
ping (iputils) sits in the network-basic bundle. I can see arguments that many network-basic bundles could be in sysadmin-basic but generally we see them as two distinct bundles. I could see getting iputils its own bundle but I do want to keep sysadmin and network basic bundles as more distinct still at this point.
