### ISSUE TITLE
pls include polybar into the bundle "desktop-i3"

### ISSUE THREAD

**Issue by thyeun** [clearlinux/distribution#1713]
Reason need it to be include because polybar can be use 

1. For others tiling windows manager such as awesome, dwm, qtile and etc.
2. More interactive
3. Easy to use and have ton of module/script for configuration.
 
And it more toward the ideal of clear linux `designed for customization, and manageability`.

**Comment by fmlatghor** [comment]
No, but I wish that the only thing that was installed in desktop-i3 was i3 and perhaps the wizard. It's annoying that I have to find other ways to get i3 wo urxvt.

**Comment by thiagomacieira** [comment]
deskdop-i3 is being removed. See https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/R5G5U4XYFRWMJKEPU3YBPSQYPO7DOQHX/
