### ISSUE TITLE
Please update the following R packages

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1718]
Since R is expecting to receive a major upgrade soon, many packages have been upgraded recently.

- [x] [AER](https://github.com/clearlinux-pkgs/R-AER) 1.2-8 to 1.2-9
- [x] [analogue](https://github.com/clearlinux-pkgs/R-analogue) 0.17-3 to 0.17-4
- [x] [checkmate](https://github.com/clearlinux-pkgs/R-checkmate) 1.9.4 to 2.0.0
- [x] [dendextend](https://github.com/clearlinux-pkgs/R-dendextend) 1.13.2 to 1.13.3
- [x] [Ecfun](https://github.com/clearlinux-pkgs/R-Ecfun) 0.2-0 to 0.2-2
- [x] [Hmisc](https://github.com/clearlinux-pkgs/R-Hmisc) 4.3-0 to 4.3-1
- [x] [joineR](https://github.com/clearlinux-pkgs/R-joineR) 1.2.4 to 1.2.5
- [x] [knitr](https://github.com/clearlinux-pkgs/R-knitr) 1.27 to 1.28
- [x] [Matching](https://github.com/clearlinux-pkgs/R-Matching) 4.9-6 to 4.9-7
- [x] [mixtools](https://github.com/clearlinux-pkgs/R-mixtools) 1.1.0 to 1.2.0
- [x] [optimx](https://github.com/clearlinux-pkgs/R-optimx) 2020-1.31 to 2020-2.2
- [x] [PerformanceAnalytics](https://github.com/clearlinux-pkgs/R-PerformanceAnalytics) 1.5.3 to 2.0.4
- [x] [RandomFields](https://github.com/clearlinux-pkgs/R-RandomFields) 3.3.7 to 3.3.8
- [x] [RcppProgress](https://github.com/clearlinux-pkgs/R-RcppProgress) 0.4.1 to 0.4.2
- [x] [RProtoBuf](https://github.com/clearlinux-pkgs/R-RProtoBuf) 0.4.14 to 0.4.15
- [x] [rstudioapi](https://github.com/clearlinux-pkgs/R-rstudioapi) 0.10 to 0.11
- [x] [spatstat.utils](https://github.com/clearlinux-pkgs/R-spatstat.utils) 1.15-0 to 1.17-0

The following R packages are included in [R](https://github.com/clearlinux-pkgs/R)
- [x] `boot` 1.3-23 to 1.3-24
- [x] `foreign` 0.8-72 to 0.8-75
- [x] `MASS` 7.3-51.4 to 7.3-51.5
- [x] `nlme` 3.1-142 to 3.1-144

---

- [x] [rncl](https://github.com/clearlinux-pkgs/R-rncl) 0.8.3 to 0.8.4

**Comment by phmccarty** [comment]
All of the packages listed above (except those included in `R`) should have updates land in build `32280`. I will keep an eye on progress tomorrow just to be sure.

**Comment by lebensterben** [comment]
Everything except those included in `R` were updated in `32280`. Please also update `rncl`.

**Comment by phmccarty** [comment]
`rncl` 0.8.4 should land in `32290`, as well as `styler` 1.3.0.

**Comment by phmccarty** [comment]
The R update to `3.6.3` landed in release `32660` last week, which satisfies the remaining package update requests above.

(Note that the [package repo](https://github.com/clearlinux-pkgs/R) was not being updated until a couple hours ago, but we have resolved that issue.)
