### ISSUE TITLE
Please add `languageserver` library for `R`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1719]
[languageserver](https://github.com/REditorSupport/languageserver) is a library that implements language-server-protocol for R language. It can be utilised by various text editors.

- Currently we have `rstudio`, which is a great IDE for R. But it's a bit heavy weight for people who don't frequently program in R.
- This R library would provide many editor functionalities for various editors, including `vim`, `neiovim`, `emacs`, and `jupyterlab`.

**Comment by bryteise** [comment]
These are handy, I don't love the super generic package name but oh well, I'll see how it goes.

**Comment by bryteise** [comment]
Nice and easy. Is this something you think belongs in R-basic or is R-extras appropriate?

**Comment by lebensterben** [comment]
> Nice and easy. Is this something you think belongs in R-basic or is R-extras appropriate?

This package itself is very young and it mainly serves users who don't want `rstudio`. I think it shall go to both `R-basic` and `machine-learning-basic`. I can imagine these scenarios:

- For R programmers they mostly likely has `R-basic` and `R-extras`, so this which one of them has `languageserver` doesn't matter to them.
- For a Python programmer who has `machine-learning-basic` and `jupyter`, then this package is included already and he only needs to add extension to `jupyter` via `pip`.
- For others, who have `vim`, `emacs` or other editors, then putting  this in `R-basic` is better since first-time user may just want to take a try and don't want to download the larger `R-extras`.

**Comment by bryteise** [comment]
I just put it into R-basic for now as I agree it is a general utility helpful regardless of what R content is being manipulated.
