### ISSUE TITLE
Use Cuppa for tracking upstream updates

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#172]
I'm not sure how the Clear Linux dev team tracks upstream updates, but one of the dev team members of Solus made this program (Cuppa) to fully track upstream releases in a centralized manner. If this is of no use to the Clear Linux team, you can close this issue as it's really just a suggestion, not a request _per se_.

GitHub link: [https://github.com/DataDrake/cuppa](https://github.com/DataDrake/cuppa)

**Comment by ahkok** [comment]
@bryteise @phmccarty

**Comment by ahkok** [comment]
Maybe you just want this:

```
diff --git a/Makefile.common b/Makefile.common
index 0fb94ca..b1246b8 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -336,6 +336,13 @@ $(TOPLVL)/repo:
        mkdir $(TOPLVL)/repo
        $(MAKE) localrepocreate
 
+cuppa:
+       @test -x /usr/bin/cuppa
+       @URL=`grep '^url = ' options.conf | cut -c7-`; echo "+cuppa q $$URL"; RES=`cuppa q $$URL | awk '{print $$2}'`; echo $$RES;\
+       if [ "$$RES" != "$$URL" ]; then \
+               make autospec URL=$$RES; \
+       fi
+
 #help repoadd: Adds locally-built RPMs for this package to the local RPM
 #help repository. If this repository does not yet exist, it is created and
 #help enabled.
```

TBF, cuppa misses out on a lot of packages. Our current tooling can scan any HTTP like repo for updates. Cuppa can't even scan things like samba releases.

**Comment by OpenSourceAnarchist** [comment]
@ahkok When I made this issue, I wasn't aware Clear Linux had a single system for tracking updates. I'll close the issue. And I'll look into using it for local RPM update management. Thanks!
