### ISSUE TITLE
Takes time to start download from Download center

### ISSUE THREAD

**Issue by methuselahin** [clearlinux/distribution#1720]
Using 
Clear Linux OS
GNOME 
Intel® Core™ i7-4720HQ CPU @ 2.60GHz × 8 
Intel® HD Graphics 4600 (HSW GT2)
Device ASUS ROG GL552JX

It takes so much time to install big softwares. You have wait like so many minutes before the download get started. My internet connection is stable enough. I mean It can download 25 MB kinda early. But with here downloading software takes a while. 
![Screenshot from 2020-02-10 11-01-20](https://user-images.githubusercontent.com/10970138/74174660-3635f800-4c2c-11ea-8778-08dafceac8c0.png)

**Comment by lebensterben** [comment]
>Using  ...

@methuselahin I guess you just installed your OS. The flatpak package needs to download extra stuff.

**Comment by methuselahin** [comment]
Its been a while since i downloaded it. But yeah it takes a lot of time to download.

**Comment by methuselahin** [comment]
> > Using  ...
> 
> @methuselahin I guess you just installed your OS. The flatpak package needs to download extra stuff.

See here. Now i have got updates in the software center, i clicked on update all option. But as picture showing in the resource manager, nothing is happening. 
![Screenshot from 2020-02-11 08-37-48](https://user-images.githubusercontent.com/10970138/74208552-0decde80-4caa-11ea-984b-e226a69a26dd.png)
as the image shows the data transfer is not happening. When I opened the browser only then the data transfer started. Software doesn't use the internet even when i clicked on update option.

**Comment by lebensterben** [comment]
> > > Using  ...
> > 
> > 
> > @methuselahin I guess you just installed your OS. The flatpak package needs to download extra stuff.
> 
> See here. Now i have got updates in the software center, i clicked on update all option. But as picture showing in the resource manager, nothing is happening.
> ![Screenshot from 2020-02-11 08-37-48](https://user-images.githubusercontent.com/10970138/74208552-0decde80-4caa-11ea-984b-e226a69a26dd.png)
> as the image shows the data transfer is not happening. When I opened the browser only then the data transfer started. Software doesn't use the internet even when i clicked on update option.

What if you execute `flatpak update -y`?

**Comment by methuselahin** [comment]
> > > > Using  ...
> > > 
> > > 
> > > @methuselahin I guess you just installed your OS. The flatpak package needs to download extra stuff.
> > 
> > 
> > See here. Now i have got updates in the software center, i clicked on update all option. But as picture showing in the resource manager, nothing is happening.
> > ![Screenshot from 2020-02-11 08-37-48](https://user-images.githubusercontent.com/10970138/74208552-0decde80-4caa-11ea-984b-e226a69a26dd.png)
> > as the image shows the data transfer is not happening. When I opened the browser only then the data transfer started. Software doesn't use the internet even when i clicked on update option.
> 
> What if you execute `flatpak update -y`?

literally nothing. I just opened in software center and clicked update all. 
But yeah i updated from terminal with command 
**sudo swupd check-update** , and it worked just fine. Now there aren't new software updates in software center. 
![Screenshot from 2020-02-11 09-00-13](https://user-images.githubusercontent.com/10970138/74209322-43df9200-4cad-11ea-9602-b83b920e0fd5.png)

**Comment by lebensterben** [comment]
>> > > > Using  ... ...

@methuselahin surely there's nothing to be updated because you just updated them....

Can you try flatpak update -y some time later and check whether there's any network activities going on?

(On my system, I just tried excuted this command and there was a very brief peak in network traffic during update.)

**Comment by methuselahin** [comment]
> > > > > > Using  ... ...
> 
> @methuselahin surely there's nothing to be updated because you just updated them....
> 
> Can you try flatpak update -y some time later and check whether there's any network activities going on?
> 
> (On my system, I just tried excuted this command and there was a very brief peak in network traffic during update.)

i will surely. I guess it will work though.  :)

**Comment by methuselahin** [comment]
> > > > > > Using  ... ...
> 
> @methuselahin surely there's nothing to be updated because you just updated them....
> 
> Can you try flatpak update -y some time later and check whether there's any network activities going on?
> 
> (On my system, I just tried excuted this command and there was a very brief peak in network traffic during update.)

it worked. And i tried to download telegram from software center. It was again stuck to start. 
![Screenshot from 2020-02-11 19-23-23](https://user-images.githubusercontent.com/10970138/74242517-196cf380-4d04-11ea-8772-b007dd41c543.png)

**Comment by lebensterben** [comment]
I mostly worked in terminal and both `swupd update ` and `flatpak update` work. I also noticed that software center is not very responsive when downloading.

Still don't what causes the problem. But at least we narrowed down it to software center.

**Comment by methuselahin** [comment]
> I mostly worked in terminal and both `swupd update ` and `flatpak update` work. I also noticed that software center is not very responsive when downloading.
> 
> Still don't what causes the problem. But at least we narrowed down it to software center.

yeah. So you can work on this issue. I hope this bug will be solved in the next version. :)

**Comment by sofar** [comment]
> So you can work on this issue.

@lebensterben is a community member and, despite being extremely capable and most helpful, not tasked to fix bugs.

**Comment by methuselahin** [comment]
> > So you can work on this issue.
> 
> @lebensterben is a community member and, despite being extremely capable and most helpful, not tasked to fix bugs.

then i mean whosoever see these bugs :+1:

**Comment by sofar** [comment]
When you install your first 2-3 flatpak applications, flatpak needs to download the `runtime` to support them. These are sometimes 2-3gb and may take a while to download.

For software available in a `bundle` through `swupd` things are better - these are likely smaller, but, still not trivially small.

However, the software store is absolutely slow and not properly responsive, and, we don't know at this point why. This could be an upstream issue. It unfortunately isn't a high priority for us at the moment to dig into.

**Comment by methuselahin** [comment]
> When you install your first 2-3 flatpak applications, flatpak needs to download the `runtime` to support them. These are sometimes 2-3gb and may take a while to download.
> 
> For software available in a `bundle` through `swupd` things are better - these are likely smaller, but, still not trivially small.
> 
> However, the software store is absolutely slow and not properly responsive, and, we don't know at this point why. This could be an upstream issue. It unfortunately isn't a high priority for us at the moment to dig into.

alright then. Reporting it was my contribution. Well when you guys has got time then work on these issues. I hope these issues don't left behind. Because when a normal user like me uses a linux, he/she wants to use it like out of the box. And a layman always want to go to the software center to download the apps he/she wants, like telegram or something like that. But yeah its alright :) . i will keep on reporting bugs

**Comment by ahkok** [comment]
Upstream flatpak identified a big download issue. Fix will be in flatpak-1.6.2 which should be out in 1-2 days in a release as well. Hopefully that helps a lot.

**Comment by methuselahin** [comment]
> Upstream flatpak identified a big download issue. Fix will be in flatpak-1.6.2 which should be out in 1-2 days in a release as well. Hopefully that helps a lot.

thanks i hope it will fix the issues.
