### ISSUE TITLE
NVME shutdown kernel panic.

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#1721]
32270 - CLR
Cannot be reproduced with all NVME drives, but my drive is a Samsung 970 EVO 256GB.
Excepted outcome is system shutdowns successfully, without a kernel panic. My system kernel panics, THEN shuts off. Happens on every Linux distro and is an upstream problem with Linux. However it's persisted for quite some time and I haven't found any progress recently on it so until they fix it I was wondering if a patch could be brought in, I compiled Solus' kernel a little while ago with this patch and the panic went away.

https://lists.infradead.org/pipermail/linux-nvme/2019-April/023258.html

**Comment by bryteise** [comment]
Hrm reading [this](https://lists.infradead.org/pipermail/linux-nvme/2019-April/023277.html) makes me think it is an incomplete fix. I understand this is improving the situation though. Maintaining these kinds of patches tends to be difficult as it may need to live in a few of our kernels and can be made irrelevant effectively unannounced. @miguelinux I'd like your opinion about adding this one.

**Comment by ZVNexus** [comment]
I checked Bugzilla to see if someone had already submitted it as a bug, but nope apparently no one has inquired about it for a year. Submitted it to Bugzilla and received a quick response saying that it "will get an appropriate patch sent to suppress it" which is great. So it seems it will be fixed upstream sometime soon then. :)
