### ISSUE TITLE
Terminator

### ISSUE THREAD

**Issue by straps** [clearlinux/distribution#1724]
The only real piece of software that make me not switch from Ubuntu to Clearlinux
https://gnometerminator.blogspot.com/p/introduction.html

Is it possible?

Thanks, great project indeed

**Comment by lebensterben** [comment]
It requires python 2 according to its INSTALL file, and python 2 is not available on Clear Linux.

**Comment by straps** [comment]
WOW, fast as clearlinux ;)

Thanks for reply, I've asked to Terminator developers and will let you know in case...

Francesco

**Comment by curantes** [comment]
> WOW, fast as clearlinux ;)
> 
> Thanks for reply, I've asked to Terminator developers and will let you know in case...
> 
> Francesco

You might look into tilix which is similar to Terminator and already included in clearlinux

**Comment by takov** [comment]
The latest version is using python3 (3.9.) I am using it as well. 
Is it possible to add it as bundle ?
