### ISSUE TITLE
Include ADB and FASTBOOT by default.

### ISSUE THREAD

**Issue by methuselahin** [clearlinux/distribution#1726]
Please add adb and fastboot android drivers in software center or by default into the clear Linux. For users like me who don't have too much knowledge about how things works is pain to make it work. Somehow i am manage to switch on the file transfer menu on My nubia Red Magic 8.1 oreo device(nx609j). When i was on manjaro, the adb and fastboot use to work out of box on xfce even. So why not clear linux can make it happen?

**Comment by ahkok** [comment]
Android development is not a high priority at the moment.. If someone contributes the work, we'd be happy to merge. Assuming it meets our inclusion guidelines.

**Comment by methuselahin** [comment]
> Android development is not a high priority at the moment.. If someone contributes the work, we'd be happy to merge. Assuming it meets our inclusion guidelines.
its not about development. There are so many people on XDA and other forums who flash custom ROMs. Like people who just want to flash GSI's and other stuff. Having android under the hood means that i don't have to fall back onto other distros or windows for rescuing while helping developers when somethings goes wrong with the phone.

**Comment by ahkok** [comment]
All the android software is downloadable as a self-supported archive that just works everywhere. I understand the desire to make it even easier than that, there's nothing wrong being lazy in these things, but the cost of including/maintaining it is disproportional because these are highly complex pieces of software.

**Comment by ZVNexus** [comment]
I agree with @ahkok , I work on AOSP all the time and I did not submit a package request for their platform tools because it makes no sense. All I do is download the tools, and throw it in PATH, bam done. At most you'll need to set up your udev rules but that's it.

**Comment by methuselahin** [comment]
> I agree with @ahkok , I work on AOSP all the time and I did not submit a package request for their platform tools because it makes no sense. All I do is download the tools, and throw it in PATH, bam done. At most you'll need to set up your udev rules but that's it. I would close this as it's way more effort to make a package for this than it's actually worth.

can u show me the way you put patch for adb tools. Because i don't natively use linux. Thats the biggest thing. In manjaro it use to work right out the box.

**Comment by methuselahin** [comment]
> All the android software is downloadable as a self-supported archive that just works everywhere. I understand the desire to make it even easier than that, there's nothing wrong being lazy in these things, but the cost of including/maintaining it is disproportional because these are highly complex pieces of software.

Its not being lazy. if there are some instuctions or a video somwhere, i would have done myself. I read somewhere how to make it work. But was unable to exactly know how to do that.

**Comment by ttzeng** [comment]
@methuselahin You can go to the [Android Studio downloads](https://developer.android.com/studio#downloads) page, download and unzip the Android SDK tools for Linux in a directory (e.g. ``~/android-sdk-linux/``). You can then install the [platform-tools](https://developer.android.com/studio/releases/platform-tools) component using this command ``~/android-sdk-linux/tools/bin/sdkmanager --install "platform-tools"``. The ``adb`` and ``fastboot`` commands will be available under ``~/android-sdk-linux/platform-tools/`` folder.

**Comment by ZVNexus** [comment]
> 
> 
> @methuselahin You can go to the [Android Studio downloads](https://developer.android.com/studio#downloads) page, download and unzip the Android SDK tools for Linux in a directory (e.g. `~/android-sdk-linux/`). You can then install the [platform-tools](https://developer.android.com/studio/releases/platform-tools) component using this command `~/android-sdk-linux/tools/bin/sdkmanager --install "platform-tools"`. The `adb` and `fastboot` commands will be available under `~/android-sdk-linux/platform-tools/` folder.

For just having access to ADB that's a bit much. Instead what I do is just go here: https://developer.android.com/studio/releases/platform-tools and download the latest Linux release.

**Comment by methuselahin** [comment]
> > @methuselahin You can go to the [Android Studio downloads](https://developer.android.com/studio#downloads) page, download and unzip the Android SDK tools for Linux in a directory (e.g. `~/android-sdk-linux/`). You can then install the [platform-tools](https://developer.android.com/studio/releases/platform-tools) component using this command `~/android-sdk-linux/tools/bin/sdkmanager --install "platform-tools"`. The `adb` and `fastboot` commands will be available under `~/android-sdk-linux/platform-tools/` folder.
> 
> For just having access to ADB that's a bit much. Instead what I do is just go here: https://developer.android.com/studio/releases/platform-tools and download the latest Linux release.

I have that folder with me. And I can use the "./adb" commands with this thing if i remember. But isn't it possible that i can have command just like "adb install  ***" normally

**Comment by ttzeng** [comment]
@methuselahin Yes, you can, once you add that folder to your $PATH, you can run ``adb devices``, ``adb install xxx`` as usual.
