### ISSUE TITLE
Unable to compile external modules

### ISSUE THREAD

**Issue by spokV** [clearlinux/distribution#1728]
While building a patched module i'm receiving the following error:
$ make -C /lib/modules/`uname -r`/build M=$PWD
make: Entering directory '/usr/lib/modules/5.5.2-903.native/build'
  CC [M]  /home/user/Documents/surface_sam/surface_sam_ssh.o
as: unrecognized option '-mbranches-within-no-boundaries'
make[1]: *** [scripts/Makefile.build:266: /home/user/Documents/surface_sam/surface_sam_ssh.o] Error 1
make: *** [Makefile:1693: /home/user/Documents/surface_sam] Error 2
make: Leaving directory '/usr/lib/modules/5.5.2-903.native/build'

**Comment by bwarden** [comment]
Same error message as #1725
