### ISSUE TITLE
Building Linux with Clang

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#1729]
Has this been discussed? I've seen it yield some performance boost, seems like it'd be worth it.

**Comment by lebensterben** [comment]
the result is mixed comparing to gcc

**Comment by bryteise** [comment]
Some projects do better with one compiler or the other, there isn't a good rule in general though at this point gcc is the winner more often then not the last time we looked and so remains the default for Clear Linux.

As an aside some things don't build with clang (or gcc) and it tends to be a major undertaking to rebuild all the content to make this test across the entire distro worthwhile. We would prefer to make changes like this on a package by package basis with data behind making the change.

**Comment by ZVNexus** [comment]
> 
> 
> Some projects do better with one compiler or the other, there isn't a good rule in general though at this point gcc is the winner more often then not the last time we looked and so remains the default for Clear Linux.
> 
> As an aside some things don't build with clang (or gcc) and it tends to be a major undertaking to rebuild all the content to make this test across the entire distro worthwhile. We would prefer to make changes like this on a package by package basis with data behind making the change.

Makes sense, GCC seems to be good then.

**Comment by thiagomacieira** [comment]
If you are aware of a package that does benefit from building with Clang, let us know. It's a single change to options.conf to make it happen.
