### ISSUE TITLE
Unable to login into online Google Account

### ISSUE THREAD

**Issue by methuselahin** [clearlinux/distribution#1731]
I am unable to login into google account. It just asks me to login and then when  I insert my details nothing happens. After waiting a while when I click on google once again to check it shows nothing and once again takes me to gmail to long. I had gave all permissions though.
![Screenshot from 2020-02-12 12-14-05](https://user-images.githubusercontent.com/10970138/74309624-313e8900-4d91-11ea-8d01-2a3b945ad80b.png)

**Comment by lebensterben** [comment]
Duplicate as #599
