### ISSUE TITLE
bug while opening file from a code editor

### ISSUE THREAD

**Issue by chapagaiashim** [clearlinux/distribution#1732]
https://imgur.com/a/biDHE46
I got this problem while opening folder from code editor. It shows 2 gb only while I have 1TB in my computer.

**Comment by ahkok** [comment]
Flatpak applications do not have full access to all the files. This is not a bug we can fix.

**Comment by chapagaiashim** [comment]
How can we fix this?

**Comment by lebensterben** [comment]
>How can we fix this?

@chapagaiashim no it cannot. That's the limitation of flatpak.

**Comment by thiagomacieira** [comment]
To be clear: an *intentional* limitation.
