### ISSUE TITLE
Provide a propietry NVidia package in swupd

### ISSUE THREAD

**Issue by mdedetrich** [clearlinux/distribution#1733]
Although there is great documentation on how to install NVidia proprietary packages here https://docs.01.org/clearlinux/latest/tutorials/nvidia.html it would be great if Clear Linux could provide the NVidia proprietary packages in swupd which would provide the following benefits

* Don't have to deal with conflicts with nvidia's package vs standard package (i.e. `libGL.so` in mesa)
* Easier to track changes between nvidia and the rest of the clear linux ecosystem
* Make DKMS more seamless
* Provide default configuration for nvidia which just works™
* Automatically allow the dynamic linker in X to use NVidia

You can even make an Nvidia custom bundle to handle this. Similar distributions (such as Nixos) also repackage the NVidia proprietary driver in their package manager for similar reasons.

**Comment by ahkok** [comment]
We can not.

**Comment by mdedetrich** [comment]
Is there a concise explanation?

**Comment by lebensterben** [comment]
>Is there a concise explanation? 

@mdedetrich it's proprietary

**Comment by ahkok** [comment]
The NVIDIA driver does not meet our package inclusion rules. Software must be Open Source to be included.

**Comment by mdedetrich** [comment]
Thanks

**Comment by leiniercs** [comment]
Hello, @mdedetrich 

I'm having a bad time installing the NVIDIA driver on ClearLinux. Can you please provide me with insightful recommendations to a hieve this:
- Deal with conflicts with nvidia's package vs standard package (i.e. libGL.so in mesa)
- Provide default configuration for nvidia which just works™
- Automatically allow the dynamic linker in X to use NVidia

Thank you in advance for any answer.

ClearLinux, you are doing a great job and are providing to the Linux with an outstanding distro that achieve extraordinary speeds and you are the preferred distro for a lot of people... but you are throwing all those good things to the ground with that bullshit of only open source. Life is too short to live it constrained. Please, provide your community with the required tools and packages that make us achieve our goals.
