### ISSUE TITLE
Installation Media Distribution: Request for Bittorrent

### ISSUE THREAD

**Issue by f35f0ef9d0e827dae86552d3899f78fc** [clearlinux/distribution#1738]
I find it odd that there is no option to download the [Clear Linux installation media](https://clearlinux.org/downloads) via Bittorrent. I wouldn't make this issue except that my download speed is only ~300KBps last night and this afternoon. I can download about 9MBps from other places. This could be solved by distributing the installation media via Bittorrent. You wouldn't need to set up your own trackers either. Sites like [linuxtracker.org](https://linuxtracker.org/index.php?page=torrents&category=2253) and [DistroWatch.com](https://distrowatch.com/dwres.php?resource=upload-torrent) are options.

**Comment by lebensterben** [comment]
For BitTorrent to work, it requires a sufficient number of users to have the installer image available. But this distro is on a rolling release, so the image you download would be soon outdated.

**Comment by ahkok** [comment]
Duplicate of #1448

**Comment by ahkok** [comment]
> This could be solved by distributing the installation media via Bittorrent

That is one solution, but bittorrent isn't very good for content that changes every day (like, clearlinux images).

We've chosen the CDN solution. The CDN is having issues with bandwidth, and we are working with the vendor to get that resolved.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
Makes sense.

Being a rolling release, I imagine there would be less demand for downloads because the audience would be mostly newcomers. In that light, can't the download speed be boosted? I don't think anyone should have to wait an hour and a half to download an ISO these days.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
> > This could be solved by distributing the installation media via Bittorrent
> 
> That is one solution, but bittorrent isn't very good for content that changes every day (like, clearlinux images).
> 
> We've chosen the CDN solution. The CDN is having issues with bandwidth, and we are working with the vendor to get that resolved.

Ah, OK. I just saw this now because I didn't refresh the screen before my last comment. I'll close the issue. Thanks for the info!
