### ISSUE TITLE
Adding macvlan kernel support

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#174]
### What is the issue type?

* [ ] Bug report
* [x] Enhancement request

### Describe the problem

Hi there! I'm trying to get macvlan support working in Docker, but noticed that it's not available:

```
brooks@nuc7i5 ~ $ modprobe macvlan
brooks@nuc7i5 ~ $ lsmod | grep macvlan
```

Would it be possible to add support for it?

**Comment by fenrus75** [comment]
CONFIG_MACVLAN=y

it's already enabled, just built in and not as a module!

**Comment by bswinnerton** [comment]
Ah, thanks for the clarification, @fenrus75!
