### ISSUE TITLE
Don't report "CPU does not support MWAIT" for intel_powerclamp on AMD processors.

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#1740]
Heyo I was wondering if it would be possible to add a check to see if it's an AMD processor when starting intel_powerclamp and then not report an error, maybe just info that says "Intel PowerClamp not supported on AMD processors". The error is inaccurate anyways since Ryzen does support MWAIT.

**Comment by ahkok** [comment]
This needs to go to the kernel - if this is a bug, report it to the right place. probably here:
https://github.com/torvalds/linux/blob/master/MAINTAINERS#L13366

**Comment by ahkok** [comment]
Oh, I just saw the patch, yes, that's nice!
