### ISSUE TITLE
dkms build issues : error "-mbranch-within-no-boundaries"

### ISSUE THREAD

**Issue by SicLuceatLux** [clearlinux/distribution#1741]
Some users experience issues with dkms - error is unrecognized flag "-mbranches-within-no-boundaries" and it is not only related to the latest Kernel. 

Tracking down the issue leads us to binutils.

Looking up the history of Clear Linux binutils 
https://github.com/clearlinux-pkgs/binutils/
reveals that binutils was upgraded to 2.34 and patch 
https://github.com/clearlinux-pkgs/binutils/blob/master/0004-i386-Add-mbranches-within-32B-boundaries.patch
was dropped
https://github.com/clearlinux-pkgs/binutils/commit/0543d206909b7f778b934b990146dc5c7ca6bea5#diff-d882c3a22699bb0fad7968a753263586

This patch 004 supposed to add "-mbranch-within-32B-boundaries" and this is now part of 2.34 
But "-mbranches-within-no-boundaries" was also added with patch 004 to /gas/tc-386.c but now it is not part of binutils 2.34 

Therefore it is missing.

sorry for the mess it is my first bug report on github.

**Comment by GonerGenesis** [comment]
would it be possible to downgrade the single binutils package to 2.33.1?

**Comment by GonerGenesis** [comment]
I found a rpm package [binutils-2.34-4.mga8 RPM for x86_64](http://fr2.rpmfind.net/linux/RPM/mageia/cauldron/x86_64/media/core/release/binutils-2.34-4.mga8.x86_64.html)

* Thu Feb 13 2020 tmb <tmb> 1:2.34-4.mga8
  + Revision: 1513435
  - PR 25447: fix a potential illegal memory access when parsing PE binaries
* Mon Feb 10 2020 tmb <tmb> 1:2.34-3.mga8
  + Revision: 1488632
  **- Mention x86 assembler options to align branches**
  - aarch64: Fix MOVPRFX markup for bf16 conversions
  - x86: Accept Intel64 only instruction by default
...

but I'm hesitating to abuse rpm to install

**Comment by SicLuceatLux** [comment]
binutils 2.34 ../gas/config/tc-i386.c (also on git://sourceware.org/git/binutils-gdb.git) does not contain:

...
+#define OPTION_MBRANCHES_WITH_NO_BOUNDARIES (OPTION_MD_BASE + 31) 
...
+  {"mbranches-within-no-boundaries", no_argument, NULL, OPTION_MBRANCHES_WITH_NO_BOUNDARIES},
...
+    case OPTION_MBRANCHES_WITH_NO_BOUNDARIES:
+      align_branch_power = 0;
+      break;
...
The reason is that Patch 004 used by Clear Linux with 2.33 is the version of 08.2019
The patch mainlined into binutils 2.34 wirtten by the same author was created 12.2019 and doesnt contain this lines anymore defining the "mbranches-within-no-boundaries". Unfortunately I cant tell why.

Furthermore I don't know were Clear Linux has some residuals of this flag "mbranches-within-no-boundaries" in configs. Maybe a complete rebuild of CL might solve it because it was set automatically and latest CL updates have partial pkg-builds of 2.33 and 2.34?

One dirty workaround might be patching this missing code snippets to 2.34 with Clear Linux's autospec and install this with the very same toolchain manually (make install local -afaik). Presumable this might break something else and any use of swupd repair will purge it. 

Maybe some Clear Linux maintainer can help here?

**Comment by SicLuceatLux** [comment]
**Dirty Workaround! Warning it may cause issues - which of course is in your responsibility ;)** 

This is only a temporary solution - problem must be fixed upstream.

Set up an autospec environment according to this guide
https://docs.01.org/clearlinux/latest/guides/clear/autospec.html

once this is done go to the base folder of autospec ..presumably clearlinux/
`make clone_binutils`
`cd packages/binutils`

in this Folder replace binutils.spec with my version
Add NastyPatch.patch to this folder
then 
`make build`
`sudo make install-local`

reboot ...now nvidia-drivers etc. can be build
[DirtyWorkaround.zip](https://github.com/clearlinux/distribution/files/4203751/DirtyWorkaround.zip)

**Comment by GonerGenesis** [comment]
Thanks for your effort! I'll wait some more days for the devs to respond and stay with nouveau for the time being.

**Comment by miguelinux** [comment]
@GonerGenesis the fix is available now

https://github.com/clearlinux-pkgs/linux/commit/7304803c5673c6395c22392102ab9a77a5788bfb

Please update to the latest Clear Linux release.

**Comment by SicLuceatLux** [comment]
> @GonerGenesis the fix is available now
> 
> [clearlinux-pkgs/linux@7304803](https://github.com/clearlinux-pkgs/linux/commit/7304803c5673c6395c22392102ab9a77a5788bfb)
> 
> Please update to the latest Clear Linux release.

Works

**Comment by GonerGenesis** [comment]
> > @GonerGenesis the fix is available now
> > [clearlinux-pkgs/linux@7304803](https://github.com/clearlinux-pkgs/linux/commit/7304803c5673c6395c22392102ab9a77a5788bfb)
> > Please update to the latest Clear Linux release.
> 
> Thx, works

Yep. Thanks!
