### ISSUE TITLE
add qt5ct 

### ISSUE THREAD

**Issue by unmellow** [clearlinux/distribution#1744]
i'm trying to theme the qt apps on my desktop i will also accept another way to theme them with out qt5ct but i do not know one
i am an ex manjaro user btw and the way i've been told to theme qt is with qt5ct

**Comment by unmellow** [comment]
https://sourceforge.net/projects/qt5ct/
this is the soure i think

**Comment by thiagomacieira** [comment]
Will add.

**Comment by unmellow** [comment]
thank you

**Comment by thiagomacieira** [comment]
Packaged, waiting for machinery now.

**Comment by thiagomacieira** [comment]
Done, will be in tomorrow's release, hopefully, with a bundle called "qt5ct"

**Comment by unmellow** [comment]
thanks you so much
