### ISSUE TITLE
Synaptic

### ISSUE THREAD

**Issue by drpeppercan** [clearlinux/distribution#1746]
https://pkgs.org/download/synaptic

This is my 1st time requesting a package. Please let me know if I'm missing anything

**Comment by lebensterben** [comment]
why would you want a GUI APT manager on a system that doesn't use APT

**Comment by drpeppercan** [comment]
Alright, is there an equivalent in CL?

**Comment by lebensterben** [comment]
>Alright, is there an equivalent in CL?

@drpeppercan no

**Comment by ahkok** [comment]
Use the `gnome-software` application.
