### ISSUE TITLE
add mako wl-paste and clipman

### ISSUE THREAD

**Issue by unmellow** [clearlinux/distribution#1749]
wl-clipboard and clipman can go in a bundle called "wayland-clipboard"
and pls add mako to the sway bundle

**Comment by curantes** [comment]
I have packaged mako and sent it for review to clearlinux devs. Hopefully they will accept it and it will get included soon.

**Comment by unmellow** [comment]
thank you

**Comment by unmellow** [comment]
i am no longer a clear linux user will close this for now if someone wants to open it again for clipman just say so
