### ISSUE TITLE
Add "ipmctl" to Clear

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#175]
The ixpdimm_sw tool has been deprecated and is now called "ipmctl" (https://github.com/intel/ipmctl).  
Please add it to Clear.

**Comment by ahkok** [comment]
@juston-li is this ready for general consumption? can we remove ixpdimm* entirely now?

**Comment by juston-li** [comment]
Yes, ixpdimm can be removed entirely now along with invm-frameworks

**Comment by juston-li** [comment]
@ahkok Not behaving from a packaging perspective?

I'll look into making it optional but no guarantees =/

**Comment by bryteise** [comment]
ipmctl is in and ixpdimm and ivnm_frameworks has been removed.
