### ISSUE TITLE
KDE 5.18: Error loading QML file (org.kde.plasma.notifications)

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1752]
Installing KDE using only the desktop-kde bundle (and without desktop-kde-apps) breaks the notification icon. See the attached screenshot.

I solved the problem only after installing [https://github.com/clearlinux-pkgs/kqtquickcharts](https://github.com/clearlinux-pkgs/kqtquickcharts) and [https://github.com/KDE/kquickcharts](https://github.com/KDE/kquickcharts). It seems installing KDE and avoiding the desktop-kde-apps bundle (bloated, IMO) is not enough for full plasma desktop functionality?

![2020-02-17_04-36](https://user-images.githubusercontent.com/55766834/74633681-eb8f1100-5140-11ea-9f75-ee845e23daff.png)

**Comment by thiagomacieira** [comment]
@anselmolsm add the package to the bundle?

**Comment by anselmolsm** [comment]
Yes, plasma needs kquickcharts and this is missing. Fix in progress.

**Comment by anselmolsm** [comment]
It's in 32360 just released.
