### ISSUE TITLE
Website insecure?

### ISSUE THREAD

**Issue by TheZLabs** [clearlinux/distribution#1755]
This likely isn't the best place for this but I wasn't able to find a way to report an issue with the website.
![image](https://user-images.githubusercontent.com/59536236/74673397-18611980-517d-11ea-8d38-7c1de27747d1.png)
I am not sure why this is the case, but your website shows as insecure even with https://
If you are running an nginx reverse proxy why wouldn't you have an ssl cert on your website?

**Comment by mdhorn** [comment]
Moved to distribution. 

Please report the URL, OS, and version of web browser. 
I don’t see this error from the few platforms I checked.

**Comment by thiagomacieira** [comment]
Confirmed. Firefox says there is one image via http:

http://clearlinux.org/modules/custom/clearlinux_org/themes/clearlinux_theme/clear_linux_logo.svg

**Comment by maxohio** [comment]
I see the same for https://clearlinux.org 
(Linux, last google-chrome -> Your connection to this site is not fully secure) 
Certificate is valid, I think some pictures/content in html loaded from untrusted connection.

**Comment by ahkok** [comment]
@mdpitterle can likely trace this down and get it addressed.

**Comment by mdpitterle** [comment]
I have filed a ticket internally to have this looked at.

**Comment by TheZLabs** [comment]
I see the same result in Chrome and Firefox. It appears the certificate is valid, however it indicates: Your connection to this site is not fully secure.

**Comment by iphutch** [comment]
Fix now applied! Thanks!!
