### ISSUE TITLE
vifm 

### ISSUE THREAD

**Issue by todfox** [clearlinux/distribution#1756]
This would make my life that much better. I don't know others live without it.

**Comment by ahkok** [comment]
I assure you we're mostly breathing pretty reasonably well. (I've never heard of `vifm`... ignorance is bliss?)

**Comment by ahkok** [comment]
Added. Should be available in 1-2 days.

**Comment by todfox** [comment]
@ahkok Thanks! You really should give it a shot. If you know your vi shortcuts, it make exploring and handling files easy. Thanks again!
