### ISSUE TITLE
Which repo is Clear Sans font file located?

### ISSUE THREAD

**Issue by danny-loh** [clearlinux/distribution#1757]
I can locate the font file in Clear Linux but I can't find it in GitHub.

**Comment by ahkok** [comment]
We don't have it on github - you can grab it from the `src.rpm` files from each release if you need the files separately.

e.g. https://download.clearlinux.org/releases/32350/clear/source/SRPMS/clear-font-1-13.src.rpm

**Comment by thiagomacieira** [comment]
We (Clear Linux) don't, but we (Intel) do: https://01.org/clear-sans

Direct link:https://01.org/sites/default/files/downloads/clear-sans/clearsans-1.00.zip
