### ISSUE TITLE
filesystems GParted

### ISSUE THREAD

**Issue by spktkpkt** [clearlinux/distribution#1758]
GParted should come with as many supported filesystems as possible.

Today, i was in need to format a stick with FAT32 but it wasn't available in GParted. I solved this by installing the `storage-utils` bundle. I don't know the licenses for all of the supported filesystems, but GParted should support at least all filesystems that do not conflict with the Clear Linux policy without the need to install a extra bundle.

**Comment by bryteise** [comment]
I "fixed" this by default storage-utils to be added (as an optional dependency) with gparted. At some point I'll split out the filesystem utilities more but this is reasonable enough for now. Should be in the next release or so.

**Comment by mdhorn** [comment]
Note, this adds 96MB to the live desktop image and ISO sizes.
