### ISSUE TITLE
Use VLC-provided libav rpms to enable MP4/H.264 playback in Firefox

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#176]
Currently, Firefox has broken playback of MP4/H.264 content on Clear Linux (see clearlinux/clr-bundles#43 and clearlinux/clr-bundles#62). OpenSUSE has the same problem due to patent restrictions. They provide an easy solution, however, that can be readily implemented into Clear Linux. VLC provides libav rpms that Firefox automatically uses (if detected). They are available publicly at this repo: [http://download.videolan.org/pub/vlc/SuSE/Tumbleweed/x86_64/](http://download.videolan.org/pub/vlc/SuSE/Tumbleweed/x86_64/)

The instructions, as per OpenSUSE's documentation (available at [https://en.opensuse.org/SDB:Firefox_MP4/H.264_Video_Support](https://en.opensuse.org/SDB:Firefox_MP4/H.264_Video_Support)), says that the following rpms are required: libavcodec{VER#}, libavformat{VER#}, and libavdevice{VER#}. Currently, the VER# is 58.

I believe these rpms are patent-encumbered, so perhaps packaging them into Clear Linux as a bundle is not going to be an option. However, providing a guide on how to use them, or setting up the VLC repo as a part of dnf OOTB, might be possible options. This is definitely an issue, though, and seeing as OpenSUSE provides a reasonable solution (adding an additional repository) for their users, Clear Linux should seek to implement a similarly reasonable solution as well.

Implementing this would resolve a few GitHub issues, as noted in this post (see above).

**Comment by OpenSourceAnarchist** [comment]
Alternatively, ffmpeg could be packaged separately, which would resolve this issue in a less hacky way. I assume ffmpeg isn't being packaged due to patent issues, but if it could be provided as a separate package/pundle/bundle, I believe this would be the most clean, appropriate resolution to this issue.

**Comment by ahkok** [comment]
Blocked.

**Comment by pixelgeek** [comment]
Codecs can be added to Firefox using 3rd party repos - see https://github.com/clearfraction/distribution#clear-fraction---3rd-party-repository-for-clear-linux
