### ISSUE TITLE
Add requirements for netdata / dbengine

### ISSUE THREAD

**Issue by jptuomi** [clearlinux/distribution#1761]
Netdata is currently available as a bundle, although a little bit broken as it doesn't get added as a unit in systemctl.

However their auto-updating installer kickstart.sh works great when compiling for CL which is the last way out provided you have installed the requirements for that, most of which are available through swupd.

One prominent feature of netdata is being able to store the data collected in dbengine, for their implementation Judy-devel is required. [This was available earlier but was removed last year as a bundle depending on them were removed.](https://github.com/clearlinux/autospec/issues/220)

I'm not well versed in how a bundle comes to be however here is a [link to the Judy-project.](https://sourceforge.net/projects/judy/)

**Comment by bryteise** [comment]
Created a bundle for devpkg-Judy. Should be in the next release or so.
