### ISSUE TITLE
liblcms2-devel

### ISSUE THREAD

**Issue by tsumme1** [clearlinux/distribution#1768]
This is required to install ICC-brightness, which controls brightness for OLED displays.

**Comment by ahkok** [comment]
Does `devpkg-lcms2` not work?

**Comment by tsumme1** [comment]
It actually does work. When I searched the clear linux software, I was not able to find the appropriate package and assumed it was not there. Thank you for pointing me to the correct package.

**Comment by thiagomacieira** [comment]
You're welcome, closing.
