### ISSUE TITLE
darktable update is required

### ISSUE THREAD

**Issue by rudrab** [clearlinux/distribution#1776]
Current darktable version in clerlinux (native) is :
```
darktable --version
this is darktable archive-c3b900172e0fe88fc6c47050983bd97bcea994a0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org
```
Upstream is: 3.0

Personally, if you have dt-3 database (I am shifting from fedora, so I have it), you cant use old dt, with error:
```
[init] database version of `$HOME.config/darktable/data.db' is too new for this build of darktable. aborting
ERROR : cannot open database
```

I agree there is a flatpak version, but given the source is so much cpu-hungry, its better if you can kindly give a native version.

**Comment by ahkok** [comment]
I looked into this but the problem is that with 3.0.0 and 3.0.1 that I can't make this work with opencl enabled - we'd have to disable opencl support.

**Comment by bryteise** [comment]
I'm poking it, needs a cmake patch for reasons I don't quite understand (IN is keyword part in foreach).

**Comment by mdhorn** [comment]
Updated to 3.0.1 in Clear Linux OS release 32680.
Most recently updated to 3.2.1 in Clear Linux OS release 33620.
