### ISSUE TITLE
Consider enabling VGA_SWITCHEROO in the kernel

### ISSUE THREAD

**Issue by Raimu-san** [clearlinux/distribution#1777]
Good day,
Would you please enable vga_switcheroo in the kernel config. Currently on clear Linux, users of laptop with  hybrid graphics are unable to turn off their dedicated GPU for power saving without some proprietary driver or out-of-tree kernel driver.
To put things in perspective, this flag (CONFIG_VGA_SWITCHEROO) is enabled on ArchLinux, Fedora, Ubuntu and I assume on a lot more linux distributions

Refer to:
- https://www.kernel.org/doc/html/v5.0/gpu/vga-switcheroo.html

**Comment by bryteise** [comment]
Ping @miguelinux, this seems like a good inclusion to me.
