### ISSUE TITLE
VBoxGuestAdditions installer removes Xorg vboxvideo driver from filesystem

### ISSUE THREAD

**Issue by bwarden** [clearlinux/distribution#178]
Running `install-vbox-lga` to install VirtualBox Guest Additions, the underlying installer deletes the distribution-provided Xorg vboxvideo driver `/usr/lib64/xorg/modules/drivers/vboxvideo_drv.so`. We need to patch the installation scripts to protect /usr.

**Comment by bwarden** [comment]
Looks like the vboxadd init script might be deleting the driver on boot, too.

**Comment by bwarden** [comment]
deffiles in the installer directory contains lists of files that could possibly have been installed by a prior version, including `/usr/lib64/xorg/modules/drivers/vboxvideo_drv.so`.

We could patch out this explicit filename, or perhaps strip out all /usr entries from it, since those are managed by swupd anyway, and would be cleaned more appropriately with `swupd verify --picky --fix`.

**Comment by bryteise** [comment]
Not letting it put files in /usr would seem appropriate to me.

**Comment by bwarden** [comment]
Fixed (last September) in https://github.com/clearlinux-pkgs/linux-lts/commit/c552dfc5f2622c474bd64a7bb69be7f7360c9cba
