### ISSUE TITLE
add packages for qt5 examples and documentation 

### ISSUE THREAD

**Issue by GonerGenesis** [clearlinux/distribution#1781]
I want to run qt-creator with the bundled version. But some essential parts (at least for me) are still missing. The examples and the complete documentation. This is not related to qt-creator itself but to the qt5 bundle.
Since I formerly used Fedora and/or Ubuntu the corresponding packages would be something like:

- qt5-doc
- qt5-doc-html
- qtbase5-examples
- qtbase5-doc-html

**Comment by lebensterben** [comment]
>I want to run qt-creator with the bundled version. But some essential parts (at least for me) are still missing. The examples and the complete documentation. This is not related to qt-creator itself but to the qt5 bundle. ...

@GonerGenesis They are freely available online...

**Comment by thiagomacieira** [comment]
I guess the point is to have them offline. I'll take a look soon.

**Comment by GonerGenesis** [comment]
> I guess the point is to have them offline. I'll take a look soon.

Yep this is the point. Ẃould be great to have the documentation available inside qt-creator. For now I copied everything from the third-party-installation into the install dirs.

**Comment by thiagomacieira** [comment]
Working on this.

**Comment by thiagomacieira** [comment]
autospec#601

**Comment by gzmorell** [comment]
Still no qt doc

**Comment by thiagomacieira** [comment]
Qt documentation can't be included because of circular dependencies. The tool to build the docs (qdoc) is very far down the Qt build chain.
