### ISSUE TITLE
saa7164 tuner doesn't work

### ISSUE THREAD

**Issue by KyleSanderson** [clearlinux/distribution#1786]
Coming from a Gentoo/Arch/Debian distro I expected my saa7164 tuner to work. Nothing is present in dmesg related to downloading the firmware for my 2250 hauppage tuner... How do I fix this bug with Clear Linux? It's all mainlined...

**Comment by ahkok** [comment]
You need to download it. The driver is open source, but the firmware is not and has not been upstreamed to `linux-firmware`, so, unfortunately the only way to get this is to fetch it yourself.

It's covered here, and I used this method myself to make this card work:

https://www.linuxtv.org/wiki/index.php/Hauppauge_WinTV-HVR-2200

**Comment by ahkok** [comment]
> Nothing is present in dmesg related to downloading the firmware

That's surprising, though, I clearly saw the firmware errors when I did this a while back for the last time.

**Comment by ahkok** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/

checked and still clearly missing `saa7164` firmwares... it's not upstream.

**Comment by KyleSanderson** [comment]
@ahkok why was this closed...

```
root@clr-e377563e8a594e5aab68077a8e958c11/lib/modules/5.5.7-268.hyperv/kernel # modprobe saa7164                                     modprobe: FATAL: Module saa7164 not found in directory /lib/modules/5.5.7-268.hyperv
```

Not sure what much more is expected, the module clearly is not there.

**Comment by KyleSanderson** [comment]
@ahkok yup...

root@clr-e377563e8a594e5aab68077a8e958c11/lib/modules/5.5.7-268.hyperv/kernel # swupd search saa7164.ko
Search failed, no reasonable results found

What's up? Why was this closed???

**Comment by ahkok** [comment]
`5.5.7-268.hyperv`

We don't support this use in the hyperv kernel. Use the native kernel. `swupd search` doesn't search in kernel modules.

```
$ uname -r
5.5.3-905.native
$ sudo modprobe saa7164
$ lsmod | grep saa7164
saa7164               131072  0
tveeprom               28672  1 saa7164
dvb_core              143360  1 saa7164
videodev              233472  4 saa7164,videobuf2_v4l2,uvcvideo,videobuf2_common
```

**Comment by KyleSanderson** [comment]
Thanks bud, I was going with SR-IOV for our farm and legal reasons but we'll re-evaluate this based on Intel's harsh stance. Thank you for letting me know.

**Comment by fenrus75** [comment]
the hyperv kernel is optimized for size for the typical hyperv use case.

if you want to do "put random PCI card in" it's likely better to run the
regular kernel there.

**Comment by ahkok** [comment]
Also, the regular kernel should work in almost all environments, including virtualization environments. Try that first and let us know if that doesn't work.
