### ISSUE TITLE
another ugly workaround for nvidia driver

### ISSUE THREAD

**Issue by GonerGenesis** [clearlinux/distribution#1788]
I gave the nvidia driver another try :-) and got another issue after `swupd repair`
while the repair some files are fixed which shouldn't be fixed regarding the nvidia modules:
```
Repairing corrupt files
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.alias -> fixed
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.alias.bin -> fixed
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.dep -> fixed
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.dep.bin -> fixed
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.symbols -> fixed
 -> Hash mismatch for file: /usr/lib/modules/5.5.6-914.native/modules.symbols.bin -> fixed
 -> Hash mismatch for file: /usr/lib32/libGL.so.1 -> fixed
 -> Hash mismatch for file: /usr/lib64/libGL.so.1 -> fixed
 [100%]
```
so I copied all module*-files after rerunning the driver installer and before the repair into an extra dir `/opt/nvidia/modules/$(uname -r)/`and added the bash file link_modules.sh:
```
#!/usr/bin/bash
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.alias /usr/lib/modules/$(uname -r)/modules.alias
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.alias.bin /usr/lib/modules/$(uname -r)/modules.alias.bin
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.dep /usr/lib/modules/$(uname -r)/modules.dep
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.dep.bin /usr/lib/modules/$(uname -r)/modules.dep.bin
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.symbols /usr/lib/modules/$(uname -r)/modules.symbols
ln -sfv /opt/nvidia/modules/$(uname -r)/modules.symbols.bin /usr/lib/modules/$(uname -r)/modules.symbols.bin
```
in the fix-nvidia-libGL-trigger.service:
```
Unit]
Description=Fixes libGL symlinks for the NVIDIA proprietary driver
BindsTo=update-triggers.target

[Service]
Type=oneshot
ExecStart=/usr/bin/ln -sfv /opt/nvidia/lib/libGL.so.1 /usr/lib/libGL.so.1
ExecStart=/usr/bin/ln -sfv /opt/nvidia/lib32/libGL.so.1 /usr/lib32/libGL.so.1
ExecStart=/usr/bin/ln -sfv /usr/lib/libGL.so.1 /usr/lib64/libGL.so.1
ExecStart=/usr/bin/bash /opt/nvidia/link_modules.sh
```
so that works for now and only this kernel version but is probably ugly.
Is there a way to avoid checking modules directory if nvidia-driver is installed when running swupd repair?

**Comment by lebensterben** [comment]
What's the point of those symbolic links for `.so` files and those in `/usr/lib/modules/`?

Do they fix anything?

**Comment by ahkok** [comment]
This is by design and not a bug. We unfortunately can not allow 3rd party software to overwrite the system because it would remove a way for users to repair their system to a known-good way.

This is a good documentation point. The Forum contains threads and tools where this should be included. Unfortunately we can't include what you're proposing, but, others can certainly document it and include it in their scripts.

**Comment by GonerGenesis** [comment]
> What's the point of those symbolic links for `.so` files and those in `/usr/lib/modules/`?
> 
> Do they fix anything?

The .so libs are for using OpenGL with nvidia driver and the modules-files are for loading the driver into the kernel at all at system startup.

**Comment by lebensterben** [comment]
>> What's the point of those symbolic links for `.so` files and those in `/usr/lib/modules/`? ...

@GonerGenesis I mean I didn't create the symbolic links, and everything still seems to be working.

**Comment by GonerGenesis** [comment]
> > > What's the point of those symbolic links for `.so` files and those in `/usr/lib/modules/`? ...
> 
> @GonerGenesis I mean I didn't create the symbolic links, and everything still seems to be working.

@lebensterben If I use `sudo swupd repair` my libGL is broken and the driver cannot be loaded after next reboot

**Comment by lebensterben** [comment]
@GonerGenesis 
I just updated my scripts for installing the driver. 
https://github.com/lebensterben/awesome-clear-linux/tree/master/NVIDIA-Driver

Just run
```bash
bash pre_install.bash
# need reboot
bash install.bash
# don't need reboot (usually)
bash post_install.bash
```
WITHOUT `sudo`.

I haven't tested it thoroughly, and let me know if it's not working.

**Comment by GonerGenesis** [comment]
> @GonerGenesis
> I just updated my scripts for installing the driver.
> https://github.com/lebensterben/awesome-clear-linux/tree/master/NVIDIA-Driver
> 
> Just run
> 
> ```shell
> bash pre_install.bash
> # need reboot
> bash install.bash
> # don't need reboot (usually)
> bash post_install.bash
> ```
> 
> WITHOUT `sudo`.
> 
> I haven't tested it thoroughly, and let me know if it's not working.

@lebensterben 
Thanks! I'll give it a try.
So the ..modprobe option will handle the issue with the module files I think. Since I don't plan to use CUDA so far, that should be ok for me. I'll still need  `swupd repair` to run. 
I think you're README.org still needs an update.

**Comment by lebensterben** [comment]
>> @GonerGenesis ...

@GonerGenesis I updated readme. And you don't need swupd repair.
