### ISSUE TITLE
<usb.h> file missing

### ISSUE THREAD

**Issue by Kishimi** [clearlinux/distribution#1790]
I'd like to include the **usb.h** file in my c++ project, but it's missing.
I searched the **usr/include** directory after it, but couldn't find the file.
The only thing I found was **gusb/gusb.h**, but I don't know wether it has anything to do with **usb.h**, or not, which doesn't matter, since I can't include that one too :/
I tried reinstalling **devpkg-libusb**, with no results.

**Comment by bryteise** [comment]
The include directory is `/usr/include/libusb-1.0/libusb.h`. I'd recommend using pkg-config though `pkg-config --cflags libusb-1.0`.
