### ISSUE TITLE
Update to glibc 2.31 stable?

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1791]
The glibc package was [reverted from 2.31 to 2.30](https://github.com/clearlinux-pkgs/glibc/commit/ec69f0689ebbb1049483869629b14d1ea0aef51a) a few days ago because it breaks ssh (1)(2):

(1): [https://bugs.archlinux.org/task/65386](https://bugs.archlinux.org/task/65386) (OpenSSH)
(2): [https://bugs.gentoo.org/708224](https://bugs.gentoo.org/708224) (OpenSSH)

However, [OpenSSH 8.2/8.2p1 (2020-02-14](https://www.openssh.com/releasenotes.html)) seems to solve the problem. Update to glibc 2.31 may now be safe:

```
* sshd(8): multiple adjustments to the Linux seccomp sandbox:
   - Non-fatally deny IPC syscalls in sandbox
   - Allow clock_gettime64() in sandbox (MIPS / glibc >= 2.31)
   - Allow clock_nanosleep() in sandbox (recent glibc) bz3093
```

**Comment by ahkok** [comment]
We already have `OpenSSH_8.2p1`

**Comment by ahkok** [comment]
But, we haven't rolled out `glibc-2.31` yet.

**Comment by ahkok** [comment]
@bryteise maybe time to retest that update.

**Comment by bryteise** [comment]
I believe the tester @VictorRodriguez is still running into issues. I may take a looksee though next week.

**Comment by VictorRodriguez** [comment]
I am trying to generate an image with the new version of opensshd and glibc, but i am having some problems with makelocal image . A bit of help with that will be really apreciated.

**Comment by phmccarty** [comment]
Release `32530` has glibc 2.31
