### ISSUE TITLE
Evince cannot open Postscript files contrary to bundle description

### ISSUE THREAD

**Issue by grayswandyr** [clearlinux/distribution#1793]
Hi,
Evince cannot open Postscript files, contrary to the bundle description, which says `GNOME document viewer for multiple formats (PDF, Postscript, djvu, tiff, dvi, XPS, etc)`. AFAIK there is nothing else to open Postscript files on CLR, which is a pity as one can still find plenty of old files in this format. I guess the inability to open PS files with Evince comes from a building configuration: if this is the case, could the maintainers enable this feature in Evince?

**Comment by bryteise** [comment]
Yep since `--enable-ps` needed for configure. Should be in the next release or two.
