### ISSUE TITLE
cups-bjnp

### ISSUE THREAD

**Issue by molmedo1** [clearlinux/distribution#1795]
I have tried installing with dnf method and i can see printer but i cannot add.

**Comment by ahkok** [comment]
I would think compiling from source would be the easiest - can you try?

http://downloads.sourceforge.net/sourceforge/cups-bjnp/cups-bjnp-2.0.3.tar.gz

**Comment by ahkok** [comment]
I'll just add it to the `hardware-printing` bundle, this is trivial.

Should be in a a release in 1-2 days or so.

**Comment by molmedo1** [comment]
> I'll just add it to the `hardware-printing` bundle, this is trivial.
> 
> Should be in a a release in 1-2 days or so.



> I would think compiling from source would be the easiest - can you try?
> 
> http://downloads.sourceforge.net/sourceforge/cups-bjnp/cups-bjnp-2.0.3.tar.gz

did try to build from source and got header issues. I see you will add to hardware-printing bundle. Awesome!! and thanks for quick response. So
