### ISSUE TITLE
avahi-daemon dev bundle request

### ISSUE THREAD

**Issue by zehnm** [clearlinux/distribution#1796]
Please make the development package of `avahi-daemon` available which was added in #714.

I'm developing a Qt open source application which requires the libavahi-client and libavahi-common libraries and header files. All my attempts to compile avahi-daemon myself failed so far due to missing dependencies and missing Clear Linux knowledge. E.g. `libdaemon` is nowhere to be found as mentioned [in this issue comment](https://github.com/clearlinux/distribution/issues/714#issuecomment-492064527). 

Thanks

**Comment by ahkok** [comment]
@bryteise you want to take a quick stab at this? Think it needs a manual dev bundle.

**Comment by bryteise** [comment]
Sure.

**Comment by bryteise** [comment]
devpkg-avahi should be in the next release or so.
