### ISSUE TITLE
ISO installer failed: KeyError: 'getpwuid(): uid not found: 0'

### ISSUE THREAD

**Issue by keelung-yang** [clearlinux/distribution#18]
![virtualbox_clearos_26_02_2018_10_10_39](https://user-images.githubusercontent.com/20385450/36650437-76d6be20-1ade-11e8-9f61-b01c28be295b.png)

Both in version 20910 and 20940

**Comment by ahkok** [comment]
@bryteise looks like more py2/3 issues from a quick glance.

**Comment by iphutch** [comment]
This should be fixed now. Could you please test again @keelung-yang
