### ISSUE TITLE
Generic detector for operating systems missing?

### ISSUE THREAD

**Issue by vilvo** [clearlinux/distribution#180]
Trying to compile ROS2 on Clear Linux 24870, rospkg raises
`File "/usr/lib/python3.7/site-packages/rospkg/os_detect.py", line 630, in detect_os
    raise OsNotDetected("Could not detect OS, tried %s" % attempted)
rospkg.os_detect.OsNotDetected: Could not detect OS, tried ['windows', 'ubuntu', 'slackware', 'rhel', 'qnx', 'osx', 'tizen', 'opensuse', 'opensuse', 'opensuse', 'neon', 'mint', 'linaro', 'gentoo', 'funtoo', 'freebsd', 'fedora', 'elementary', 'elementary', 'debian', 'cygwin', 'centos', 'manjaro', 'arch', 'alpine']
`
[rospkg indicates](https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py#L170) that Clear Linux does not support FreeDesktop os-release spec under `/etc/*release`

Optionally, any other long-term, backward compatible mechanism to read Clear Linux OS name, version and codename identification could be implemented by inheriting OSIdentifier under rospkg.

**Comment by AntonioMeireles** [comment]
humm ... on boot you should get `/etc/os-release -> /usr/lib/os-release` (or are using chroots? as if so expected that /etc/os-release missing as the symlink is systemd magic ...)
```
clear@node-1 ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS for Intel Architecture"
VERSION=1
ID=clear-linux-os
VERSION_ID=24830
PRETTY_NAME="Clear Linux OS for Intel Architecture"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 can you paste output of `sudo swupd bundle-list`?

**Comment by vilvo** [comment]
Thanks. Not using chroot.
```
# swupd bundle-list
bootloader
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
editors
emacs
ethtool
git
iproute2
joe
kernel-native
kvm-host
libX11client
mail-utils
network-basic
openssh-server
openssl
os-core
os-core-dev
os-core-update
p11-kit
perl-basic
perl-basic-dev
python2-basic
python3-basic
shells
storage-utils
storage-utils-dev
sudo
sysadmin-basic
telemetrics
user-basic
vim
which
wpa_supplicant
xemacs
```

**Comment by miguelinux** [comment]
Looks like ROS does not follow os-release documentation.

It said

```
$ man os-release

NAME
       os-release - Operating system identification

SYNOPSIS
       /etc/os-release

       /usr/lib/os-release

DESCRIPTION
       The /etc/os-release and /usr/lib/os-release files contain operating
       system identification data.

```

Please just create a symlink to /etc/

```
$ sudo ln -s ../usr/lib/os-release /etc/os-release
```

This is a bug from the upstream ROS.


On Thu, Sep 06, 2018 at 05:11:43AM -0700, Ville Ilvonen wrote:
> Thanks. Not using chroot.
> ```
> # swupd bundle-list
> bootloader
> desktop
> desktop-apps
> desktop-assets
> desktop-autostart
> desktop-gnomelibs
> desktop-locales
> dev-utils
> dev-utils-dev
> editors
> emacs
> ethtool
> git
> iproute2
> joe
> kernel-native
> kvm-host
> libX11client
> mail-utils
> network-basic
> openssh-server
> openssl
> os-core
> os-core-dev
> os-core-update
> p11-kit
> perl-basic
> perl-basic-dev
> python2-basic
> python3-basic
> shells
> storage-utils
> storage-utils-dev
> sudo
> sysadmin-basic
> telemetrics
> user-basic
> vim
> which
> wpa_supplicant
> xemacs
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/clearlinux/distribution/issues/180#issuecomment-419070674

-- 
Regards,

Miguel Bernal Marin                     Open Source Technology Center
https://clearlinux.org                              Intel Corporation

**Comment by vilvo** [comment]
Thanks. There's two separate issues here:
1. rospkg does not have support for OSDetection on Clear Linux but it reads `/etc/release` on registered OS detectors
2. Clear Linux (installer?) does not symlink `/usr/lib/os-release` to `/etc/os-release`

To some extent this can be worked around with ros2 OSX installation instructions so that I can get `colcon build` started.

**Comment by miguelinux** [comment]
The missing of /etc/os-release is not an issue as in the same `man os-release`
said:

The file /etc/os-release takes precedence over /usr/lib/os-release.
Applications should check for the former, and exclusively use its data
if it exists, and only fall back to /usr/lib/os-release if it is
missing. Applications should not read data from both files at the same
time.  /usr/lib/os-release is the recommended place to store OS release
information as part of vendor trees.  /etc/os-release should be a
relative symlink to /usr/lib/os-release, to provide compatibility with
applications only looking at /etc. A relative symlink instead of an
absolute symlink is necessary to avoid breaking the link in a chroot or
initrd environment such as dracut.



On Thu, Sep 06, 2018 at 01:04:26PM +0000, Ville Ilvonen wrote:
> Thanks. There's two separate issues here:
> 1. rospkg does not have support for OSDetection on Clear Linux but it reads `/etc/release` on registered OS detectors
> 2. Clear Linux (installer?) does not symlink `/usr/lib/os-release` to `/etc/os-release`
> 
> To some extent this can be worked around with ros2 OSX installation instructions so that I can get `colcon build` started.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/clearlinux/distribution/issues/180#issuecomment-419085286

-- 
Regards,

Miguel Bernal Marin                     Open Source Technology Center
https://clearlinux.org                              Intel Corporation

**Comment by ahkok** [comment]
Maybe someone can try the following patch and submit upstream it if it works:

```
--- os_detect.py	2018-09-06 08:51:48.528066248 -0700
+++ os_detect.py~	2018-09-06 08:46:00.568069567 -0700
@@ -70,26 +70,18 @@
             return f.read().split()
     return None
 
-def parse_os_release(filename)
-    """
-    :returns: Dictonary of key value pairs from os-release file, with quotes stripped from values
-    """
-    release_info = {}
-    with codecs.open(filename, 'r', encoding=locale.getpreferredencoding()) as f:
-        for line in f:
-            key, val = line.rstrip('\n').partition('=')[::2]
-            release_info[key] = val.strip('"')
-        return release_info
 
 def read_os_release(filename="/etc/os-release"):
     """
-    :parse os-release file, fallback to system os-release when possible
+    :returns: Dictonary of key value pairs from /etc/os-release, with quotes stripped from values
     """
-    fallback="/usr/lib/os-release"
+    release_info = {}
     if os.path.exists(filename):
-        return parse_os_release(filename)
-    else if os.path.exists(fallback):
-        return parse_os_release(fallback)
+        with codecs.open(filename, 'r', encoding=locale.getpreferredencoding()) as f:
+            for line in f:
+                key, val = line.rstrip('\n').partition('=')[::2]
+                release_info[key] = val.strip('"')
+            return release_info
     return None
 
```

**Comment by vilvo** [comment]
Proposed symlink from `/usr/lib/os-release` to `/etc/os-release` did not work with `rospkg`though there's an issue https://github.com/ros-infrastructure/rospkg/pull/88 open for generic OS detection which would help rospkg maintainers to remove OS specific detection.

Nevertheless, I created an issue to `rospkg` with pull request to fix the OS detection - https://github.com/ros-infrastructure/rospkg/issues/157

**Comment by miguelinux** [comment]
A member from Clear Linux team already opened a PR:

https://github.com/ros-infrastructure/rospkg/pull/156

On Fri, Sep 07, 2018 at 01:02:44AM -0700, Ville Ilvonen wrote:
> Proposed symlink from `/usr/lib/os-release` to `/etc/os-release` did not work with `rospkg`though there's an issue https://github.com/ros-infrastructure/rospkg/pull/88 open for generic OS detection which would help rospkg maintainers to remove OS specific detection.
> 
> Nevertheless, I created an issue to `rospkg` with pull request to fix the OS detection - https://github.com/ros-infrastructure/rospkg/issues/157
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/clearlinux/distribution/issues/180#issuecomment-419357306

-- 
Regards,

Miguel Bernal Marin                     Open Source Technology Center
https://clearlinux.org                              Intel Corporation

**Comment by forwardtape** [comment]
@vilvo The fix is merge into https://github.com/ros-infrastructure/rospkg

**Comment by miguelinux** [comment]
https://github.com/ros-infrastructure/rospkg/commit/975cea6459019cb3b10a4de4486856a790d114e2
