### ISSUE TITLE
It's possible to include the Valve fsync patch on the kernel native?

### ISSUE THREAD

**Issue by bkdwt** [clearlinux/distribution#1800]
Hey guys, how is going? I used the fsync patch for a while on Gentoo (compiling manually) and Fedora using a pre-compiled kernel available in the extra repositories.

I would like to know if it would be possible to include the patch in the native Clear Linux kernel or not. If not, is the kernel compilation method on Clear Linux similar to Fedora? Because I could never understand how to compile a kernel on Fedora unlike Gentoo which is quite simple and more "vanilla".

https://steamcommunity.com/games/221410/announcements/detail/2957094910196249305
https://steamcommunity.com/app/221410/discussions/0/3158631000006906163/
https://lkml.org/lkml/2019/7/30/1399
Patch updated: https://aur.archlinux.org/packages/linux-fsync/

Thanks in advance! :D

**Comment by bryteise** [comment]
Hey =). It seems like the patch has taken a lot of hits from upstream review so I don't think we'd feel comfortable including it at this time in our own releases. Customizing your kernel is a documented [process](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html). You can also just do a normal kernel build in a source tree (you'll want to build the bzImage, modules and do a make modules_install) and then copy the bzImage into the efi partition and create a config to load it.

**Comment by bkdwt** [comment]
> Hey =). It seems like the patch has taken a lot of hits from upstream review so I don't think we'd feel comfortable including it at this time in our own releases. Customizing your kernel is a documented [process](https://docs.01.org/clearlinux/latest/guides/kernel/kernel-development.html). You can also just do a normal kernel build in a source tree (you'll want to build the bzImage, modules and do a make modules_install) and then copy the bzImage into the efi partition and create a config to load it.

Oh, no problem. I'll try include the patch on my system. Thanks a bunch! 😊
