### ISSUE TITLE
journalctl -u sshd No entry found

### ISSUE THREAD

**Issue by ketonik** [clearlinux/distribution#1803]
**systemd version the issue has been seen with**
> ...
`244`

**Used distribution**
 > …
`Clear Linux 32510`
**Expected behaviour you didn't see**
 > …
`printed log sshd entries`
**Unexpected behaviour you saw**
 > …
`No entry found`
**Steps to reproduce the problem**
`journalctl -u sshd`
`journalctl -u sshd.service`

systemd github devs suggest it should work and that Clear Linux Distribution must have made changes:

https://github.com/systemd/systemd/issues/15015#issuecomment-594435823

**Comment by ahkok** [comment]
Thanks for opening this. I've been annoyed that this stopped working, and, we should at least try and root cause this.

**Comment by ketonik** [comment]
Let's hope the systemd guys assist in find a solution, after all, they should be thankful for everyone falling over themselves to implement their svchost.exe 'like' init system ;-)

**Comment by ahkok** [comment]
I wrote some of those parts.

**Comment by ahkok** [comment]
I've done a regression test all the way back to 2018, and I cannot reproduce the behavior that I thought there was. While frustrating that is, I can't keep this bug open as-is - there is no bug as far as I can see. Sorry.
