### ISSUE TITLE
ACPI Error

### ISSUE THREAD

**Issue by JakubBirnbach** [clearlinux/distribution#1805]
Can anyone help me to fix the issue? I read that ACPI errors aren't a huge thing, also the system is booting normally.

Dell Vostro 15 3000 series
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4
Clear Linux OS; Build ID: 32510

![88120330_2913050268756075_624062244212178944_n](https://user-images.githubusercontent.com/33956927/75928598-0bc40d00-5e6f-11ea-88a2-8e1b374ba4c2.jpg)

**Comment by lebensterben** [comment]
Does updating BIOS solve this?

**Comment by JakubBirnbach** [comment]
> Does updating BIOS solve this?

Unfortunately not.

**Comment by lebensterben** [comment]
Looks like this one
https://bugzilla.kernel.org/show_bug.cgi?id=194031

Currently "closed documented"

**Comment by ahkok** [comment]
Contact the board vendor - I realize they may just say that "linux is not supported" but that's the only thing you can really do - let them know.
