### ISSUE TITLE
Gnome to support more languages than just English

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#181]
Clear Linux Gnome desktop should support more languages than just `English`

The locale files are correctly generated for a bunch of the Clear Linux* apps shipped, but currently, we're unable to change the language via `gnome-settings -> Region & Language`

![Clear Linux OS* gnome-settings screenshot](https://user-images.githubusercontent.com/978752/45184847-c8db9780-b1ed-11e8-8072-2841a282edde.png)

**Comment by fenrus75** [comment]
there is support for more-than-english now.

it's not perfect yet, but it's not just english anymore either
