### ISSUE TITLE
Please update spice 0.14.2 to 0.14.3 stable

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1812]
[https://www.spice-space.org/download/releases/spice-server/spice-0.14.3.tar.bz2](https://www.spice-space.org/download/releases/spice-server/spice-0.14.3.tar.bz2)
[https://github.com/clearlinux-pkgs/spice/blob/master/spice.spec](https://github.com/clearlinux-pkgs/spice/blob/master/spice.spec)

Thanks for all the work!

**Comment by anselmolsm** [comment]
Thanks for the report. It's in progress now.
