### ISSUE TITLE
Update libvirt and libvirt-python latest

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1813]
[https://github.com/clearlinux-pkgs/libvirt](https://github.com/clearlinux-pkgs/libvirt)
[https://github.com/clearlinux-pkgs/libvirt-python](https://github.com/clearlinux-pkgs/libvirt-python)

[https://libvirt.org/news.html](https://libvirt.org/news.html)
[https://libvirt.org/sources/libvirt-6.1.0.tar.xz](https://libvirt.org/sources/libvirt-6.1.0.tar.xz)
[https://github.com/libvirt/libvirt-python/archive/v6.1.0.tar.gz](https://github.com/libvirt/libvirt-python/archive/v6.1.0.tar.gz)

Thanks!

**Comment by GonerGenesis** [comment]
With libvirt 5.8.0 its not possible to install a VM running UEFI. At least not for me. See here:
[https://bugzilla.redhat.com/show_bug.cgi?id=1782778](https://bugzilla.redhat.com/show_bug.cgi?id=1782778)

**Comment by insilications** [comment]
Yeah, it seems this is fixed in 6.1.0

**Comment by romulasry** [comment]
https://libvirt.org/sources/libvirt-7.0.0.tar.xz
https://github.com/libvirt/libvirt-python/archive/v7.0.0.tar.gz

**Comment by bswinnerton** [comment]
👋 @insilications, it might be worth retitling this to something more broad like "update libvirt" as I believe the latest version is now 7.0.0.

@mdhorn, I see you've assigned yourself to this issue. Is there anything the open source community can do to help with this?

**Comment by mdhorn** [comment]
@fenrus75 updated these packages to the latest 7.0.0 releases. 
They should appear in the first build next week; likely Tuesday.

**Comment by mdhorn** [comment]
Released in build 34310
