### ISSUE TITLE
Gnome 3.36

### ISSUE THREAD

**Issue by Tornado-Tim** [clearlinux/distribution#1817]
Gnome 3.36 is much improved over 3.34 and includes many bug fixes which make Gnome Shell run fast and buttery smooth.

Would be good if we could get this update sooner rather than later :)

**Comment by fenrus75** [comment]
it's not due out until.. tuesday ? ;)

**Comment by ahkok** [comment]
> GNOME 3.36 will be released on March 11, 2020

Wednesday.

We'll likely need 1-2 weeks - these aren't easy updates. Many components trail the release or need bugfixes right after a release.

**Comment by phmccarty** [comment]
Assigning to @mrkz

**Comment by nazar2sfive** [comment]
@mrkz 
any update?

**Comment by nodanero** [comment]
For Gnome 3.34 upgrade there was no PR linked. Can we have the commit/branch/PR for this upgrade?

**Comment by bryteise** [comment]
@nodanero likely not because the clearlinux-pkg repos are a special mirror process and not how we make changes.

**Comment by nazar2sfive** [comment]
@mrkz any update?
eagerly waiting during this lockdown period

**Comment by nodanero** [comment]
It was already published. Should this be closed?

**Comment by rossburton** [comment]
Yes.
