### ISSUE TITLE
autofs can't find `nsswitch.conf`

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#182]
I'm having trouble getting autofs working with Clear Linux, and I _think_ it may have something to do with where it's looking for configuration files.

I'm new to autofs, so I'm sure there are mistakes that I'm making, but I've enabled the `autofs.service`, and dropped the following files into place:

```
brooks@nuc7i5a ~ $ cat /etc/auto.master
/mnt /etc/autofs/auto.backups --timeout=60 --ghost

```

```
brooks@nuc7i5a ~ $ cat /etc/auto.backups
backups -fstype=cifs,username=username,password=password,sec=ntlm,vers=1.0 ://backups.brooks.network/nuc-backups

```

But when starting the `autofs.service`, I see the following in the logs:

```
Sep 07 01:02:37 nuc7i5a automount[11638]: failed to to open config /etc/autofs.conf
Sep 07 01:02:37 nuc7i5a automount[11638]: failed to to open old config /autofs
Sep 07 01:02:37 nuc7i5a automount[11640]: nsswitch_parse:172: couldn't open /etc/nsswitch.conf
Sep 07 01:02:37 nuc7i5a automount[11640]: lookup_nss_read_master: can't to read name service switch config.
```

And it's not auto mounting the appropriate directories.

I mentioned this in the IRC channel and @ahkok had mentioned there might be a bug:

> the error about /etc/nsswitch.conf is a bug in clearlinux, please open an issue for that

In debugging, I came across a patch to autofs that _might_ be helpful, I'm not really sure, but it addressed the double "to to" in the error message, and seemed to fix a bug related to configuration loading. It's available here: http://cdn.kernel.org/pub/linux/daemons/autofs/v5/patches-5.1.5/autofs-5.1.4-tiny-patch-for-autofs-typo-and-possible-bug.patch.

**Comment by ahkok** [comment]
I had a hunch that we never patched this properly to account for the OS `nsswitch.conf` that we ship in `/usr/share/defaults/etc`. The patch is trivial, and I've posted it to the ML. It should be ready to be merged.

**Comment by ahkok** [comment]
`autofs-5.1.4-18`

**Comment by bswinnerton** [comment]
That release fixed it! Thanks @ahkok.

**Comment by danboid** [comment]
Hi @bswinnerton 

I'm trying to get autofs to work under Clear Linux. It doesn't seem to be installed by default (at least there is no autofs.service on my install) and when I built 5.1.5 from source I got a

```
couldn't open /etc/nsswitch.conf
```

Error so how did you install or build autofs/automount?

**Comment by bswinnerton** [comment]
👋 @danboid,

It's available in the [`storage-utils`](https://github.com/clearlinux/clr-bundles/blob/dec9938570b649e6b3a8a3296e3817e6a5d49ad0/bundles/storage-utils#L10) bundle. You should be able to get it with `sudo swupd bundle-add storage-utils`.

**Comment by danboid** [comment]
I already have storage-utils ad storage-utils-dev installed but there is no sign of an autofs.service. There is however proc-sys-fs-binfmt_misc.automount but I don't think that is the same thing.

**Comment by thiagomacieira** [comment]
FYI, /etc is always empty in Clear unless **you** created the file. The default nsswitch.conf file is in /usr/share/defaults/etc. You shouldn't edit that file, just create it in /etc if you need to make modifications.

The tool in question needs a fix to find the default copy.
