### ISSUE TITLE
Default instructions for installing Nvidia drivers breaks CUDA

### ISSUE THREAD

**Issue by aluo-x** [clearlinux/distribution#1820]
The [instructions from clear linux](https://docs.01.org/clearlinux/latest/tutorials/nvidia.html) on installing proprietary Nvidia GPU drivers suggests installing with options `--no-nvidia-modprobe`.

This unfortunately breaks CUDA, as noted [here](https://community.clearlinux.org/t/bash-scripts-to-automate-installation-of-nvidia-proprietary-driver/368) and [here](https://community.clearlinux.org/t/help-building-pytorch-from-source-for-anaconda/3682). I think for general usage this line should be removed.

**Comment by puneetse** [comment]
There is an open issue in the docs repo (and previously linked discussion) about why this is and looking for volunteers to update the CUDA doc:
https://github.com/clearlinux/clear-linux-documentation/issues/1029

**Comment by aluo-x** [comment]
Thanks for the follow up. Closing it now.
