### ISSUE TITLE
Media SDK library path setting

### ISSUE THREAD

**Issue by weiseng-yeap** [clearlinux/distribution#1821]
Hi Support Team,

From the normal linux support the mediaSDK export path like below:
export LD_LIBRARY_PATH=/usr/lib/media-libva:/opt/intel/mediasdk/samples/_bin/x64:/opt/intel/mediasdk/lib64/;

For ClearLinux how to configure it path? 
And how to install Mediasdk?

Appreciate

**Comment by ahkok** [comment]
Clear Linux doesn't set a default `LD_LIBRARY_PATH`. We won't ever do that. If your application needs it, it should do so, or you should do so.

`mediasdk` is part of many bundles. `vlc`, `desktop`, `os-utils-gui`, `devpkg-mediasdk`, and `gstreamer`. The last one is probably a good bundle to use.

**Comment by chivakker** [comment]
@weiseng-yeap that sounds like the old way of using mediasdk, they don't recommend that when using their library.  See here: https://github.com/Intel-Media-SDK/MediaSDK
