### ISSUE TITLE
Requesting Intel Embree

### ISSUE THREAD

**Issue by aluo-x** [clearlinux/distribution#1822]
Embree is very useful for working with a variety of collision / ray tracing tasks. I believe the clear linux team already maintains RPM packages, would request also for clear linux as well.

**Comment by ahkok** [comment]
Our `blender` bundle includes this (by dependency).

**Comment by aluo-x** [comment]
I see, much appreciated! 
Would be nice to have more documentation on this.
Closing this issue now.
