### ISSUE TITLE
Swupd post-update (ldconfig) scripts are creating files under /usr/

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/distribution#1829]
**Describe the bug**
Swupd runs ldconfig after multiple operations. Ldconfig is creating files under /usr/ that are considered extra files by swupd. We should create those files in other location or consider them part of the system.

**To Reproduce**
```
# swupd repair --extra-files-only 
# ls /usr/lib64/p11-kit-trust.so # file should be there
# rm /usr/lib64/p11-kit-trust.so
# swupd repair --extra-files-only
# ls /usr/lib64/p11-kit-trust.so # file was recreated
# swupd repair --extra-files-only # repair list that file as an extra file
```
or using ldconfig
```
# rm /usr/lib64/p11-kit-trust.so
# ldconfig
# ls /usr/lib64/p11-kit-trust.so # file was recreated
# swupd repair --extra-files-only # file is listed as an extra file
```

Reported by @gtkramer on  clearlinux/swupd-client#1346

**Comment by bryteise** [comment]
This isn't something I'd want swupd-client to do handle. The content should be complete and in this case it is not.

**Comment by ahkok** [comment]
```
echo 'INPUT(/usr/lib64/pkcs11/p11-kit-trust.so)' > libnssckbi.so
```

perhaps?

**Comment by ahkok** [comment]
I'm dropping the whole thing from the package. It's neither needed by CLR packages, nor do I think any software needs it. If I'm wrong, then the symlink is easily created manually.
