### ISSUE TITLE
cloud-native updates

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1831]
- kubernetes v1.17.4
- CRI-O v1.17.2
- Docker 19.03.7

**Comment by miguelinux** [comment]
I'll update these packages

**Comment by KyleSanderson** [comment]
kubeadm doesn't work at all with the current setup @miguelinux - can you fix the instructions too?

**Comment by mythi** [comment]
@KyleSanderson 

> kubeadm doesn't work at all with the current setup

What's the error?

**Comment by KyleSanderson** [comment]
@mythi just never deploys. Kubelet starts and everything and then hangs waiting for the API server to come up (dns?). I did notice in other documentation cri-o and Kubernetes should be in version lockstep. Tried on metal and hyper-v, consistently fails out of the box. Deployed prod with Docker-ce but was looking to get rid of the madness.

**Comment by bryteise** [comment]
Updates should be out in the next day or so.
