### ISSUE TITLE
Add insync to package manager

### ISSUE THREAD

**Issue by LenglBoy** [clearlinux/distribution#1832]
As a user of cloud share points like OneDrive/GoogleDrive/.... I would like the most common sync-client for client-file synchronization.
Therefore I would really like getting the packages of insync added to the supported applications.

Currently, it's possible to run it fully ok with manual extractions. This need to be done for every update and is not a nice job.
Can surely be improved soon.

[Current solution inside Insync-Forum](https://forums.insynchq.com/t/installation-guide-for-clear-linux/15263)

**Comment by ahkok** [comment]
We ship `rclone` which fits that requirement already. Insync isn't even open source!
