### ISSUE TITLE
Fails to build nvidia latest 440.60 dkms driver in CL 32600 under kernel-native-dkms

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#1835]
CL 32600 ships with GCC version 9.3.1, but the kernel-native-dkms module is still compiled with gcc 9.2.x. The default nvidia-installer command line performs a gcc version check between the kernel and the provided dkms module and complains when they diverge:

_--no-cc-version-check
The NVIDIA kernel module should be compiled with the same compiler that was used to compile the currently running kernel. The layout of some Linux kernel data structures may be dependent on the version of gcc used to compile it. The Linux 2.6 kernel modules are tagged with information about the compiler and the Linux kernel's module loader performs a strict version match check. nvidia-installer checks for mismatches prior to building the NVIDIA kernel module and aborts the installation in case of failures. Use this option to override this check._

**Temporary fix**: add the --no-cc-version-check option in the installer command line to forcefully compile the driver.

```
DKMS make.log for nvidia-440.64 for kernel 5.5.9-918.native (x86_64)
Fri Mar 13 19:54:22 -03 2020
make[1]: Entering directory '/usr/lib/modules/5.5.9-918.native/build'
  SYMLINK /var/lib/dkms/nvidia/440.64/build/nvidia/nv-kernel.o

Compiler version check failed:

The major and minor number of the compiler used to
compile the kernel:

gcc version 9.2.1 20200311 gcc_9_2_0_release-746-gc9858be2e7 (Clear Linux OS for Intel Architecture)

does not match the compiler used here:

cc (Clear Linux OS for Intel Architecture) 9.3.1 20200312 releases/gcc-9.3.0-9-gde8e3b71c8
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


It is recommended to set the CC environment variable
to the compiler that was used to compile the kernel.

The compiler version check can be disabled by setting
the IGNORE_CC_MISMATCH environment variable to "1".
However, mixing compiler versions between the kernel
and kernel modules can result in subtle bugs that are
difficult to diagnose.

*** Failed CC version check. Bailing out! ***

make[2]: *** [/var/lib/dkms/nvidia/440.64/build/Kbuild:191: cc_version_check] Error 1
```

```
nvidia-installer log file '/var/log/nvidia-installer.log'
installer version: 440.64

nvidia-installer command line:
    ./nvidia-installer
    --utility-prefix=/opt/nvidia
    --opengl-prefix=/opt/nvidia
    --compat32-prefix=/opt/nvidia
    --compat32-libdir=lib32
    --x-prefix=/opt/nvidia
    --x-module-path=/opt/nvidia/lib64/xorg/modules
    --x-library-path=/opt/nvidia/lib64
    --x-sysconfig-path=/etc/X11/xorg.conf.d
    --documentation-prefix=/opt/nvidia
    --application-profile-path=/etc/nvidia
    --no-precompiled-interface
    --no-distro-scripts
    --force-libglx-indirect
    --glvnd-egl-config-path=/etc/glvnd/egl_vendor.d
    --dkms
    --silent

-> Installing DKMS kernel module:
ERROR: Failed to run `/usr/bin/dkms build -m nvidia -v 440.64 -k 5.5.9-918.native`:
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j12 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.5.9-918.native IGNORE_CC_MISMATCH='' modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.5.9-918.native (x86_64)
Consult /var/lib/dkms/nvidia/440.64/build/make.log for more information.
```

**Comment by lebensterben** [comment]
This is very unfortunate. I literally installed Nvidia driver yesterday and everything works fine.

**Comment by insilications** [comment]
@lebensterben Yes, and I use your script (https://github.com/lebensterben/awesome-clear-linux) to facilitate driver installation :) Had to change it because of that.

**Comment by puneetse** [comment]
Thanks for the mismatch report. I briefly talked to @bwarden about this who bumped the version for the native kernel to match in the next release.

**Comment by SicLuceatLux** [comment]
@insilications thank you for forwarding this issue and giving a fix. @lebensterben Thankyou for your installer it really makes the live easier ...but this nvidia driver always comes up with a new issue :D

**Comment by lebensterben** [comment]
@insilications Added a section to check the GCC version compatibility to my scripts. So at least from now on they'd be notified about the problem before making any changes to the system.
https://github.com/lebensterben/awesome-clear-linux/commit/edcc872a834691a8bf6c898322c3554c7dae5dbd

**Comment by bwarden** [comment]
This should be resolved by https://github.com/clearlinux-pkgs/linux/commit/3718d220698310d1ecc7c257503d77009a902408

**Comment by mns6070** [comment]
Just tried this today and I am getting the following message from the NVIDIA scripts: "The GCC used for compiling the kernel, 9.3.1 20200317, is different from the current GCC version, 9.3.1 20200319".  Is there a way to resolve this mismatch?

**Comment by lebensterben** [comment]
> Just tried this today and I am getting the following message from the NVIDIA scripts: "The GCC used for compiling the kernel, 9.3.1 20200317, is different from the current GCC version, 9.3.1 20200319". Is there a way to resolve this mismatch?

I just updated the script and fixed the bug.

**Comment by mns6070** [comment]
Thank you! I will test it shortly.

**Comment by puneetse** [comment]
I'm closing this as the mismatched versions are fixed now.

**Comment by walidjabari** [comment]
I am getting the same error 
> cat /var/lib/dkms/nvidia/<version>/build/make.log
... 
the major and minor number of the compiler used to compile the kernel : 
gcc version 9.3.1 ...
does not match the compiler used here
cc(Clear Linux OS for Intel Architecture) 10.1.1...

**Comment by insilications** [comment]
The GCC version included in CL has been recently updated to 10.1. But nvidia's kernel-native-dkms module was compiled using 9.3.x. Same problem as before. You need to add add the --no-cc-version-check option in the installer command line to forcefully compile the driver.

For example, add --no-cc-version-check after --dkms to compile it:
https://github.com/lebensterben/awesome-clear-linux/blob/master/NVIDIA-Driver/install.bash


`--egl-external-platform-config-path=/etc/egl/egl_external_platform.d \
    --dkms \
    --no-cc-version-check \
    --silent; then`

**Comment by aluo-x** [comment]
This flag worked for me previously when there was the gcc 9.2/9.3 mismatch. Failing with a dkms error this time, related to `CONFIG_SECTION_MISMATCH_WARN_ONLY=y`

**Comment by walidjabari** [comment]
Anything I can do about it as an end-user ?

**Comment by lebensterben** [comment]
>Anything I can do about it as an end-user ? 

@walidjabari Wait until NVIDIA updated the driver

**Comment by chaoyi** [comment]
and boot with an old kernel in the mean time
or compile kernel with flag set (works for me)

**Comment by insilications** [comment]
New temporary fix: https://github.com/clearlinux/distribution/issues/1994
