### ISSUE TITLE
Please add `rr` package

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1836]
> rr is a lightweight tool for recording, replaying and debugging execution of applications (trees of processes and threads). Debugging extends gdb with very efficient reverse-execution, which in combination with standard gdb/x86 features like hardware data watchpoints, makes debugging much more fun.

This is a great tool for debugging and please add this. https://github.com/mozilla/rr

And btw, it mentions that 
> /proc/sys/kernel/perf_event_paranoid must be <= 1 for rr to work efficiently (i.e. be able to use perf counters)

while Clear Linux uses the default value 2 for `perf_event_paranoid`, do you think it reasonable to modify this default value for all Clear Linux system?

**Comment by ahkok** [comment]
> while Clear Linux uses the default value 2 for perf_event_paranoid, do you think it reasonable to modify this default value for all Clear Linux system?

No.

However it's a runtime changeable option. So there's nothing wrong with leaving its value by default as is, and when you need to debug something with `rr`, you change the value according to your needs.

**Comment by ahkok** [comment]
Looks like it was previously already packaged. Perhaps not ever properly bundled separately.... looking into it.

**Comment by ahkok** [comment]
It was removed at some point because at the time it had a hard dependency on `py2`. Fortunately recently they made a version that no longer has this problem. `rr` bundle, in a few days.
