### ISSUE TITLE
Folding@home (FAH) package

### ISSUE THREAD

**Issue by JSEHV** [clearlinux/distribution#1837]
In the current worldwide search for a Coronavirus vaccin, the help from every Linux distribution is very welcome.

For this reason a folding@home (FAH) package for Clear Linux (that can use GPU and CPU) would be very appreciated.

Certainly as Clear Linux is (and wants to be) the fastest distribution for these cases (machine learning, algorithmic calculation, solving complex data challenges)

**Comment by lebensterben** [comment]
https://foldingathome.org/alternative-downloads/
It doesn't seem to be open-sourced so they cannot package it.

**Comment by jurobystricky** [comment]
It seems to me it is open source (GPL licenses), at least after a cursory look here:
https://github.com/FoldingAtHome

**Comment by lebensterben** [comment]
>It seems to me it is open source (GPL licenses), at least after a cursory look here: ...

@jurobystricky some of them are not softwares. Some need scons build tool that is not supported. Some need Chrome browser that's not available on Clear Linux...

**Comment by jurobystricky** [comment]
@lebensterben thanks for the clarification.
OTOH Clear Linux has boinc-client bundle, so users with idle CPU cycles should be able to use them with similar project, such as rosetta@home:
https://unraid.net/blog/help-take-the-fight-to-covid-19-with-boinc-or-folding-home

**Comment by ahkok** [comment]
The `rpm` files are unusable IMHO, they link against an old `openssl` library - I couldn't get them to work. The possible alternatives are `wine` and `flatpak`. No `flatpak` exists yet, so I tried to run the windows 32bit executable with ClearLinux' `wine` and guess.... it works! I'm now folding.

So, if you have cycles, yes, this isn't optimal, but it's better than 0. :)

**Comment by JSEHV** [comment]
@ahkok, indeed it runs with Wine, but it doesn't see the GPU. Any suggestions?

Still any change we will get a native Clearlinux bundle?

**Comment by ahkok** [comment]
This is so far off course, this belongs in a 3rd party repo or a flatpak.
