### ISSUE TITLE
Installer user feedback.

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#184]
I like the UI presentation of your installer but below shortcoming are very vivid and annoying at times.

The installer doesn't have file system selection section.
The installer depends on the internet connection.
The installer doesn't have explicit package selection area.
The installer should be more expressive and clear, think about the end-user who doesn't have enough technical knowledge.

**Comment by bryteise** [comment]
@unixbhaskar You might want to take a look at our in development installer replacement https://github.com/clearlinux/clr-installer and give early feedback on improvements. Some things like offline installation aren't going to be supported anytime soon though.

**Comment by ahkok** [comment]
We appreciate candid and honest feedback. However, can we please keep the language at a professional level and focus on the technical content?

**Comment by unixbhaskar** [comment]
Spot on @ahkok  and thanks for reminding me for the slip...my bad...

**Comment by mdhorn** [comment]
These were addressed in the replacement https://github.com/clearlinux/clr-installer
Visible in the live installer images: https://clearlinux.org/downloads
