### ISSUE TITLE
Application Updates (KDE  APPLICATION PLATFORM) never goes away

### ISSUE THREAD

**Issue by methuselahin** [clearlinux/distribution#1840]
The software center always says there are software updates. No matter what i use terminal to manually to update Clear Linux, this KDE  APPLICATION PLATFORM updates notification never goes away. When i click update it says installing. But there is no cpu usage in the system monitor also. So, what exactly is going on here. 
the software center shows this **runtime/org/kde.Platform/x86_64/5.14** in the description
![Screenshot from 2020-03-18 20-00-04](https://user-images.githubusercontent.com/10970138/76971919-e4337100-6953-11ea-88e4-4fa10a6b385e.png)

**Comment by anselmolsm** [comment]
This softwre center's update notifications is about a flatpak content, this is not related to Clear Linux updates.

If software center is failing to do the update and not reporting its status properly, you could try running "flatpak update" on a console to get more detailed information about what is going on under the hood.

**Comment by methuselahin** [comment]
> This softwre center's update notification is about a flatpak content, this is not related to Clear Linux updates.
> 
> If software center is failing to do the update and not reporting its status properly, you could try running "flatpak update" on a console to get more detailed information about what is going on under the hood.

ethuselah@clr-e0e91aaa0bc54b999724766ab1cdce82~ $ flatpak update
Looking for updates…


        ID                                Branch Op Remote  Download
 1. [✗] org.freedesktop.Platform.openh264 19.08  i  flathub 593.6 kB / 593.4 kB

Warning: org.freedesktop.Platform.openh264 not installed
Installation complete.

**Comment by anselmolsm** [comment]
Hm, At first it looks like an upstream bug.
Does "ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/" show versions older than 5.14?

**Comment by methuselahin** [comment]
> Hm, At first it looks like an upstream bug.
> Does "ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/" show versions older than 5.14?

can you more specific with the command, i mean what you are asking

**Comment by ahkok** [comment]
He wants you to execute it directly, like this:

```
$ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
5.11  5.12  5.13  5.9
```

**Comment by methuselahin** [comment]
> He wants you to execute it directly, like this:
> 
> ```
> $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
> 5.11  5.12  5.13  5.9
> ```

not native linux user. So don't mind. i am getting this 

`mah@clr-e0ce82~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
meah@clr-e0e91aa~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
meh@clr-e0e91~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
meh@clr-e0~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11': No such file or directory
meh@clr-2~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/ 5.11
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
ls: cannot access '5.11': No such file or directory
meh@clr-e0e9~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
meh@clr-e0e91~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64': No such file or directory
meh@clr-e0e~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/ 5.11 5.12 5.13 5.9
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
ls: cannot access '5.11': No such file or directory
ls: cannot access '5.12': No such file or directory
ls: cannot access '5.13': No such file or directory
ls: cannot access '5.9': No such file or directory
meh@clr-e0e912~ $ ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory
meh@clr-e0e~ $ 5.11  5.12  5.13  5.9
`

**Comment by ahkok** [comment]
that's not correct. You shouldn't execute something starting with `$`. I merely showed you what was on my screen including shell prompt character and example output. Ooof.

You should execute this:

```
ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
```

Only once. If there's an error, fine, we want to know.

**Comment by methuselahin** [comment]
> that's not correct. You shouldn't execute something starting with `$`. I merely showed you what was on my screen including shell prompt character and example output. Ooof.
> 
> You should execute this:
> 
> ```
> ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
> ```
> 
> Only once. If there's an error, fine, we want to know.

ls /var/lib/flatpak/runtime/org.kde.Platform/x86_64/
**ls: cannot access '/var/lib/flatpak/runtime/org.kde.Platform/x86_64/': No such file or directory**

**Comment by methuselahin** [comment]
@ahkok 
 Is this screen shot revelant

![Screenshot from 2020-03-20 21-19-04](https://user-images.githubusercontent.com/10970138/77180870-930cb400-6af0-11ea-81c8-1039ccfdf33e.png)
