### ISSUE TITLE
Update c-extras-gcc8 from gcc 8.3.1 to 8.4.1

### ISSUE THREAD

**Issue by aluo-x** [clearlinux/distribution#1842]
Requesting an update for the c-extras-gcc8 packages from gcc 8.3.1 to 8.4.1. 
Currently the GCC 8.x branch is on 8.4, while clear linux still has 8.3.

**Comment by phmccarty** [comment]
I just merged an update for `gcc8` to 8.4.1 (8.4.0 plus latest stable branch updates). Should be available in 1-2 days.

**Comment by aluo-x** [comment]
Closing this issue. Many thanks!
