### ISSUE TITLE
darktable needs to be updated

### ISSUE THREAD

**Issue by rudrab** [clearlinux/distribution#1845]
hi,
darktable needs to be updated.
clear version:
darktable --version
this is darktable archive-c3b900172e0fe88fc6c47050983bd97bcea994a0
copyright (c) 2009-2020 johannes hanika
darktable-dev@lists.darktable.org

upstream:
3.0.1

**Comment by ahkok** [comment]
duplicate of #1845

**Comment by ahkok** [comment]
dupe of #1776 sorry

**Comment by rudrab** [comment]
correct..and both are created by me....as there were no comment on that ticket

**Comment by ahkok** [comment]
There's no need to file multiple requests for the same update, that just means we're spending more time closing duplicate items - time we may have otherwise spent on ... updating something useful.
