### ISSUE TITLE
Clion 

### ISSUE THREAD

**Issue by purpl3F0x** [clearlinux/distribution#1847]
I would like to request JetBrains' Clion package.
I see that pycharm and rider are available.

**Comment by lebensterben** [comment]
Neither PyCharm nor Rider is available in `swupd`, but they're provided by `flathub` as `flatpak` package.
Clear Linux doesn't ship proprietary software so you can either ask JetBrain to publish `Clion` on `flathub`, or download the tarball release from JetBrain.

**Comment by purpl3F0x** [comment]
Ok, thank for your response

**Comment by ahkok** [comment]
As noted, this isn't open source, therefore, we can't include it.
