### ISSUE TITLE
fio: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by zhijianli88** [clearlinux/distribution#185]
**Describe the bug**
Illegal instruction (core dumped)

**To Reproduce**
platform: ivb

and skylake platform is good.

**log**
11:35:00 AM - zhijian: Looks the fio shipped by clear-23430 is broken
11:35:00 AM - zhijian: {code}
11:35:00 AM - zhijian: root@ivb44 /# swupd bundle-add fio
11:35:00 AM - zhijian: Downloading packs...
11:35:00 AM - zhijian: Extracting fio pack for version 23430
11:35:00 AM - zhijian: 	...100%
11:35:00 AM - zhijian: Starting download of remaining update content. This may take a while...
11:35:00 AM - zhijian: 	...100%
11:35:00 AM - zhijian: Finishing download of update content...
11:35:00 AM - zhijian: Installing bundle(s) files...
11:35:00 AM - zhijian: 	...100%
11:35:00 AM - zhijian: Calling post-update helper scripts.
11:35:00 AM - zhijian: Successfully installed 1 bundle
11:35:00 AM - zhijian: root@ivb44 /# fio
11:35:00 AM - zhijian: Illegal instruction (core dumped)

12:21:10 PM - zhijian: root@ivb44 ~# /usr/bin/fio-btrace2fio
12:21:10 PM - zhijian: /usr/bin/fio-btrace2fio: [options] <blktrace bin file>
12:21:10 PM - zhijian: 	-t	Usec threshold to ignore task
12:21:10 PM - zhijian: 	-n	Number IOS threshold to ignore task
12:21:10 PM - zhijian: 	-f	Fio job file output
12:21:10 PM - zhijian: 	-d	Use this file/device for replay
12:21:10 PM - zhijian: 	-r	Ignore jobs with less than this KiB/sec rate
12:21:10 PM - zhijian: 	-R	Set rate in fio job (def=0)
12:21:10 PM - zhijian: 	-D	Cap queue depth at this value (def=256)
12:21:10 PM - zhijian: 	-c	Collapse "identical" jobs (def=0)
12:21:10 PM - zhijian: 	-u	Depth difference for collapse (def=1)
12:21:10 PM - zhijian: 	-x	Random difference for collapse (def=5)
12:21:10 PM - zhijian: 	-a	Additional fio option to add to job file

**Comment by sofar** [comment]
Confirmed. `Illegal Instruction` with `24920` on a `Intel(R) Celeron(R) CPU J3455 @ 1.50GHz`

**Comment by sofar** [comment]
```
$ avxjudge.py /usr/bin/fio
Analyzing /usr/bin/fio
Top SSE functions by instruction count
    fio_md5_init@@Base            	50.0 %s
    calc_lat@@Base                	37.84 %s
    gauss_init@@Base              	37.78 %s
    update_rusage_stat@@Base      	36.0 %s
    fio_sha1_init@@Base           	33.33 %s

Top SSE functions by value
    calc_clat_percentiles@@Base   	384.47
    __dprint@@Base                	63.17
    td_zone_free_index@@Base      	60.12
    steadystate_check@@Base       	46.76
    fio_server_send_ts@@Base      	46.48

Top AVX2 functions by instruction count
    file_hash_init@@Base          	47.62 %s
    fio_sha512_init@@Base         	30.77 %s
    file_hash_exit@@Base          	26.55 %s
    fio_sha256_init@@Base         	22.22 %s
    fio_sha1_final@@Base          	21.67 %s

Top AVX2 functions by value
    mutex_cond_init_pshared@@Base 	207.92
    fio_sha1_final@@Base          	41.85
    get_global_options@@Base      	32.25
    sum_thread_stats@@Base        	23.24
    zipf_init@@Base               	18.16

Top AVX512 functions by instruction count

Top AVX512 functions by value


File total (SSE):  5856 instructions with score 1647
File total (AVX2):  1847 instructions with score 445
File total (AVX512):  0 instructions with score 0
```

**Comment by thiagomacieira** [comment]
Fixed in fio release 36.

**Comment by phmccarty** [comment]
fio 3.9-36 was merged for 24960
