### ISSUE TITLE
go-basic bundle update

### ISSUE THREAD

**Issue by shtirlic** [clearlinux/distribution#1853]
Please update Go to 1.14.1 or 1.13.9

**Comment by mdhorn** [comment]
I'd prefer 1.13.9 for now as there have been reports of compatibility issues with gotk3 and 1.14.x.
For example, https://github.com/gotk3/gotk3/issues/541

**Comment by phmccarty** [comment]
I will update it to `1.13.9`.

**Comment by phmccarty** [comment]
The build finished. Should be available in 1-2 days.

**Comment by phmccarty** [comment]
Released in `32680`.
