### ISSUE TITLE
systemctl poweroff: kernel panic

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#186]
I am running clear-24950-kvm.img.xz under QEMU. In contrast to previous releases, `shutdown down` and `systemctl poweroff` (I tried both) no longer shut down cleanly. Instead I get a kernel panic:
```
clr-5d1d205ba40944b89d4b29ebbc3bd110 login: [  245.446528] reboot: Power down
[  245.451299] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
[  245.451299] 
[  245.452761] CPU: 0 PID: 1 Comm: systemd-shutdow Not tainted 4.18.7-279.kvm #2
[  245.453866] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 0.0.0 02/06/2015
[  245.455165] Call Trace:
[  245.455561]  dump_stack+0x5c/0x90
[  245.456085]  panic+0xd2/0x220
[  245.456557]  do_exit.cold.4+0xb5/0xbd
[  245.457135]  ? printk+0x43/0x53
[  245.457631]  __se_sys_reboot+0x130/0x1e0
[  245.458254]  ? vfs_writev+0x8a/0xd0
[  245.458803]  ? do_writev+0x47/0xd0
[  245.459338]  do_syscall_64+0x56/0x180
[  245.459922]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  245.460722] RIP: 0033:0x7fe6f0157ab6
[  245.461272] Code: Bad RIP value.
[  245.461777] RSP: 002b:00007ffd51ad4ea8 EFLAGS: 00000202 ORIG_RAX: 00000000000000a9
[  245.462939] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007fe6f0157ab6
[  245.464026] RDX: 000000004321fedc RSI: 0000000028121969 RDI: 00000000fee1dead
[  245.465112] RBP: 00007ffd51ad4f50 R08: 0000000000000000 R09: 0000000000000005
[  245.466201] R10: 00007fe6f0400a3d R11: 0000000000000202 R12: 0000000000000000
[  245.467290] R13: 0000000000000000 R14: 0000000000000000 R15: 00007ffd51ad5038
[  245.468396] Kernel Offset: 0x29000000 from 0xffffffff81000000 (relocation range: 0xffffffff80000000-0xffffffffbfffffff)
[  245.476414] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000000
[  245.476414]  ]---
```

**Comment by pohly** [comment]
I learned that this is a known issue that will be fixed shortly. Will you also add a testcase that covers this to avoid future regressions?

We could use this issue here to track the development of such a testcase.

**Comment by ahkok** [comment]
@miguelinux can you include a tag or reference with the fix in here so we can close?

**Comment by miguelinux** [comment]
The fix was: 
https://github.com/clearlinux-pkgs/linux-kvm/commit/0fdfe0a1e72814467b57ac7cb723c5faad439a94

The explanation.
https://github.com/clearlinux-pkgs/linux-kvm/commit/24e2e7e44cb4f3f8631f6f51fd12b9f69b36ad61

the origin of the issue
https://github.com/clearlinux-pkgs/linux-kvm/commit/eac391a82ec8a0cba513b24982b59d0f6a0d827c


On Thu, Sep 13, 2018 at 09:11:03AM -0700, ahkok wrote:
> @miguelinux can you include a tag or reference with the fix in here so we can close?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/clearlinux/distribution/issues/186#issuecomment-421062681

-- 
Regards,

Miguel Bernal Marin                     Open Source Technology Center
https://clearlinux.org                              Intel Corporation

**Comment by pohly** [comment]
Nothing in those links tells me why this kernel change caused a kernel panic. But that isn't important (sometimes harmless looking changes have surprising side effects), more important IMHO is to ensure that such breakage doesn't go unnoticed before releasing to users. Do you track such gaps in the QA?

**Comment by miguelinux** [comment]
we have a patch that do 
```
-acpi-$(CONFIG_ACPI_REDUCED_HARDWARE_ONLY) += evged.o
+acpi-y				+= evged.o
```
so I enable that feature on kconfig to remove the patch.
**That brings a broken image**

the fix is to bring back the patch and disable that feature.

**Comment by miguelinux** [comment]
We are working on a QA test now

**Comment by ahkok** [comment]
status? @miguelinux

**Comment by miguelinux** [comment]
A test was added to our internal bundle validation: fc3a3c5fe914 ("Update tests to turn off the VM")
