### ISSUE TITLE
alacritty

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#1862]
Dear clearlinux dev team:

Would you consider adding [alacritty](https://github.com/alacritty/alacritty) to clearlinux please.

Alacritty: A cross-platform, GPU-accelerated terminal emulator

Best regards
Stokhos

**Comment by lebensterben** [comment]
They don't support Rust package for now.

**Comment by stokhos** [comment]
Ok,  but how so?

**Comment by lebensterben** [comment]
>Ok,  but how so?

@stokhos We need `autospec` to build packages, which currently doesn't support golang and Rust.

**Comment by stokhos** [comment]
Got it! Thanks
