### ISSUE TITLE
ImageMagick dev libraries

### ISSUE THREAD

**Issue by Ralim** [clearlinux/distribution#1864]
Hey,

It would be fantastic if we could package the ImageMagick dev libraries for things that need to be linked against ImageMagick. 
For example when trying to install the `gem rmagick` it complains that `MagickCore` is not available. On debian the `-dev` packages contain this. 
At the moment I'm installing the rpm's and all of their dependencies manually which is a bit of a mess to resolve.

:heart: 
- Ralim

**Comment by ahkok** [comment]
Will be `devpkg-ImageMagick`.
