### ISSUE TITLE
nodejs-basic update to latest LTS (12.15.0 -> 12.16.1)

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1870]
Node.JS released a new LTS version (12.16.1) on 2020-02-18, it would be useful to update the nodejs-basic bundle. See the changelog [here](https://nodejs.org/en/blog/release/v12.16.1/).

Thanks.

**Comment by xRiot** [comment]
Currently you can workaround this issue by installing [Node manually](https://github.com/nodejs/help/wiki/Installation) or by using a version manager such as [NVM](https://github.com/nvm-sh/nvm#installing-and-updating) _(just make sure to source ~/.bashrc after installation)._

**Comment by mdhorn** [comment]
Updated to 12.18.3 Clear Linux OS release 33660
Most recently updated to 14.15.0 in Clear Linux OS release 33920
