### ISSUE TITLE
Update fish-shell to 3.1

### ISSUE THREAD

**Issue by felixg3** [clearlinux/distribution#1872]
Dear CL team, in times of Covid-19, please stay safe. Wish you all the best.

However, could you update the fish shell to 3.1? It comes with a bunch of bugfixes I am waiting for. I compiled it myself, but it is always overwritten by the system during updates.

Current version in CL: 3.0.2, Latest stable release: 3.1
See at https://github.com/fish-shell/fish-shell 

Thanks a lot!

**Comment by phmccarty** [comment]
I was looking to update fish the other day. Thanks for the notice.

**Comment by phmccarty** [comment]
I just submitted the update to 3.1.0. Should be available within a couple of days.

**Comment by felixg3** [comment]
Thank you, @phmccarty! This should resolve the systemd autocompletion bug aswell.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by felixg3** [comment]
It is coming with `32760`. Thanks!
