### ISSUE TITLE
Warning: same module names found, vboxvideo.

### ISSUE THREAD

**Issue by mmetak** [clearlinux/distribution#1873]
When building the latest kernels for arch I noticed this warning message:
```
[ 4205s] warning: same module names found:
[ 4205s]   drivers/misc/vboxvideo/vboxvideo.ko
[ 4205s]   drivers/gpu/drm/vboxvideo/vboxvideo.ko
```
I guess that's due to the added virtualbox patches?

**Comment by ahkok** [comment]
> the latest kernels for arch

We don't support archlinux.

**Comment by mmetak** [comment]
@ahkok Shouldn't that warning still be valid even for clear? I checked the built rpm package and there are two modules with that same name.

https://download.clearlinux.org/current/x86_64/os/Packages/linux-5.5.15-930.x86_64.rpm

**Comment by phmccarty** [comment]
@mmetak I just checked the build log, and yes, that warning also shows up for the current `linux` package.

**Comment by ahkok** [comment]
@miguelinux

**Comment by miguelinux** [comment]
Thanks it is fixed

**Comment by mmetak** [comment]
@miguelinux It's also present in `linux-clear-lts2019`.

**Comment by miguelinux** [comment]
Thanks, i fixed for all the kernels :), you will see in the next release.
