### ISSUE TITLE
unable to find org.clearlinux.blender

### ISSUE THREAD

**Issue by Exospheric** [clearlinux/distribution#1877]
New install, new user. I went to the Software Center to install blender (it does not say which version) and it replies: 
unable to find org.clearlinux.blender

that's it. no useful message.

I search this problem and land at https://clearlinux.org/software?search_api_fulltext=blender&field_bundle_category=All

and i take the advice: sudo swupd bundle-add blender
: Loading required manifests...
: Warning: Bundle "blender" is already installed, skipping it...
: 1 bundle was already installed

--
this is a dumb user experience.

**Comment by ahkok** [comment]
There's nothing to fix, you have blender installed. Software Center is likely just having a network issue.
