### ISSUE TITLE
Perl modules are missing YAML::Tiny

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#1879]
os-testsuite had its bundle-definition minimized in order to create a cleaner test environment that does not accidentally satisfy missing dependencies in other bundles.  This involved removing the perl-YAML-Tiny package because it is not used as a part of the testing process.  As a result, the following modules cannot be used with the `perl  -M<module name> -e 1` command:

- Locale::Po4a::Yaml
- TAP::Harness::Archive

This is seen in a minimal environment for each of the following bundles:

- software-testing
- po4a

**Comment by bwarden** [comment]
Adding runtime dependency `perl(YAML::Tiny)` to `perl-TAP-Harness-Archive` and `po4a`.
