### ISSUE TITLE
Kubernetes Update

### ISSUE THREAD

**Issue by CraigSterrett** [clearlinux/distribution#1881]
Can we update to 1.18.0
https://github.com/kubernetes/kubernetes/releases/tag/v1.18.0
and
https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.18.0

**Comment by bryteise** [comment]
I'll let cri-o 1.17.2 make it into a build and then try this out.

**Comment by AntonioMeireles** [comment]
hi all!

@CraigSterrett 
fwiw, way too early to jump into 1.18.x ...

@bryteise 

OTOH, could you plz bump cni-plugins to a more fresh version? upstream is on [0.8.5](https://github.com/containernetworking/plugins/releases) already. this will fix a fair chunk of issues, afaict...

re: cri-o, if the bump to 1.17.x takes long (i saw it landing in 32770 and getting reverted in 327870) could you plz bump, in the meantime, to the the latest of the 1.16.x stream (1.16.5) ?  

All the Best, 

António

**Comment by bryteise** [comment]
cri-o 0.17.2 didn't get out because the 0.17 bug fixes didn't fix an issue where it failed to start if the hooks_dir didn't exist. Upstream patched awhile ago, I just had to backported the change. Should be in the next release.

cni-plugins I can update but will wait and see if cri-o gets out the door first.

**Comment by AntonioMeireles** [comment]
@bryteise 

hi again! 

thanks for the update. In order to get back `containers-basic` fully internally consistent, when bumping `cri-o` consider also refreshing `cri-tools` to `1.17.0` at same time :-) 

thanks in advance!

**Comment by AntonioMeireles** [comment]
@bryteise 

fwiw, `cri-o/0.17.2`  still not behaving in `32790` . (error is `conmon: option parsing failed: Unknown option --persist-dir`) . fix is to just bump `conmon` pkg to a more recent version ( `cri-o/0.17.2`  works with `conmon/2.0.15` - checked here)

**Comment by AntonioMeireles** [comment]
`cri-o/0.17.3` is out btw :-) rouds a few more edges.

**Comment by bryteise** [comment]
Well updates all around, changes should be in the next release. @AntonioMeireles thank you very much for all the help =).

**Comment by CraigSterrett** [comment]
@AntonioMeireles  @bryteise 
I know that K8s 1.18.0 is early and not necessarily stable, it depends on whether we want to begin evaluation of K8s 1.18.0 yet. Tied back to the idea of some that Clear stays on the bleeding edge

**Comment by bryteise** [comment]
@CraigSterrett I think the goal is we want it to be useful and we want to be using the newest upstream code when we can. We don't have an evaluation channel, just the packager testing the update and making a decision based on those results. Has your team gotten an idea of the 1.18 upgrade is something we should do on Clear Linux based on a manual installation perhaps?

**Comment by AntonioMeireles** [comment]
@bryteise 

hi again!

just to let you know that bumped cri-o stack is generally working as expected.  **THANKS**!

Now a side note: the update to **systemd 245** broke most (only ipv4) inter pod comms in most CNI implementations, (vd as an example https://github.com/cilium/cilium/issues/10645). 
FWIW, i'd ship the fix with clear out of the box (either by reverting offending patch in systemd or fixing  its hot path by injecting `net.ipv4.conf.lxc*.rp_filter = 0` somewhere under `/etc/sysctl.d/` by default).

All the best, 

António

**Comment by bryteise** [comment]
Ugh I don't like reverting that patch since it has a fix in it. @ahkok what do you think about another systemd patch adding the specific configuration for lxc to that file and prodding upstream (I didn't see with a quick scan an issue that looked like this one on their tracker)?

**Comment by AntonioMeireles** [comment]
@bryteise, technically there's nothing wrong with the systemd change of behaviour, it's just that it brokes userland previous assumptions. you don't see too much noise about it because few ppl are running yet 245 :-) . and the symptoms are subtle. in k8s i spotted it because pods running in non master nodes were having issues when updating to late CL revs. by bissecting i spotted that latest behaving rev of CL was 32730 ... which placed systemd as main suspect. more digging and culprit found. so, yes - just shipping `net.ipv4.conf.lxc*.rp_filter = 0` may be the right thing to do :-)

**Comment by ahkok** [comment]
I'd prefer shipping a distro file under `/usr/lib/sysctl.d` with kubernetes. That's the safest and least invasive.

**Comment by AntonioMeireles** [comment]
> I'd prefer shipping a distro file under `/usr/lib/sysctl.d` with kubernetes. That's the safest and least invasive.

@ahkok, 

would you consider shipping it together with `cni`(or `cni-plugins`) pkg instead as that ones ships in `containers-basic` bundle ? (as i - and i suspect most - am not using - CL for production duties are not using CL's  shipping k8s blobs and by placing distro file in `containers-basic`  all use cases angled  :-) ) 

thanks in advance

**Comment by ahkok** [comment]
I have no idea what you're talking about.

**Comment by AntonioMeireles** [comment]
@ahok, 

sorry,  but now i got confused, by your confusion. As of now CL / swupd hard-locks a given k8s release with each CL release, which forces the end-user to make some hard-choices - either keeps CL updated and risks gambling on the state of k8s in CL or gets locked in an oldish CL release with a k8s rev that suits its needs.  The "workaround" is just to not rely in shipping CL's k8s blobs (`cloud-native-basic`) and use upstream ones (or whatever), which gives the user almost total flexibility assuming that the stuff underlying and on  which k8s has a direct runtime dependency (the one that ships in `containers-basic`) is in a sane state. this is **why** shipping the distro file you refered [here](https://github.com/clearlinux/distribution/issues/1881#issuecomment-613006819) would make sense to be not in something that goes only in `cloud-native-basic` but into something that goes both into it and `containers-basic`.

**Comment by ahkok** [comment]
Clearly, you understand much better than me what the better place would be for such a sysctl.d override file. I would just defer to that.

**Comment by gtkramer** [comment]
> The "workaround" is just to not rely in shipping CL's k8s blobs (cloud-native-basic) and use upstream ones (or whatever), which gives the user almost total flexibility assuming that the stuff underlying and on which k8s has a direct runtime dependency (the one that ships in containers-basic) is in a sane state.

@AntonioMeireles this is pretty much all we can test, that there is basic sanity in single and multi node configurations in perhaps crio and containerd (and maybe someday docker).  I'm in favor of giving users more flexibility and removing components we ship that end up getting containerized anyway from a normal k8s setup process.

**Comment by mythi** [comment]
> this is why shipping the distro file you refered here would make sense to be not in something that
> goes only in `cloud-native-basic` but into something that goes both into it and `containers-basic`.

I agree `cni-plugins` is better than `kubernetes`.

**Comment by AntonioMeireles** [comment]
just for context, the meta-issue about the usability, in production workloads, of the (in-distro) shipping kubernetes bits (basically `kube{adm,kubelet}`) is far from new - was raised and debated deeply in this [issue](https://github.com/clearlinux/distribution/issues/203) in late 2018.

**Comment by bryteise** [comment]
Change to cni-plugins should be in the next release.

**Comment by evankanderson** [comment]
1.18 has been out for a while now.

While packaging 1.18, it would be great if the beta Volume Snapshot API could be bundled: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

**Comment by mdhorn** [comment]
Clear Linux OS is now certified on Kubernetes v1.19.

[Certified Kubernetes Distributions & Platforms](https://docs.google.com/spreadsheets/d/1LxSqBzjOxfGx3cmtZ4EbB_BGCxT_wlxW_xgHVVa23es)

**Comment by evankanderson** [comment]
Hi! It looks like Clear Linux jumped from 1.17 to 1.19. Unfortunately, `kubeadm` enforces that upgrades cover only a single minor version upgrade at a time:

```
# kubeadm upgrade plan
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade/config] FATAL: this version of kubeadm only supports deploying clusters with the control plane version >= 1.18.0. Current version: v1.17.13
```

Note that the [upgrade instructions](https://docs.01.org/clearlinux/latest/tutorials/kubernetes-bp.html#update-the-control-plane) suggest simply running `sudo swupd update`, which will install the 1.19 `kubeadm`.

Furthermore, if automatic updates are enabled, **kubelets will get upgraded before the control plane**, which is opposite the instructions here: https://docs.01.org/clearlinux/latest/tutorials/kubernetes-bp.html#update-the-control-plane

If Clear Linux is likely to keep making these multi-version jumps, I may end up replacing my Clear Linux nodes with a different distribution.

**Comment by evankanderson** [comment]
In particular, if you run into this issue (1.19 kubelets with 1.17 control plane), you'll find that all your kubelets can't start pods with the error message:

```
k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: the server could not find the requested resource
```

What you'll need to do is to download the 1.18 node bundle (kubelet, kubeadm, etc) and run an upgrade from those binaries, which will introduce the `storage.k8s.io/v1` API for CSIDriver, which 1.19 depends on.

**Comment by mythi** [comment]
> Unfortunately, kubeadm enforces that upgrades cover only a single minor version upgrade at a time:

`kubeadm upgrade plan v0.18.15` first and then to v0.19. AFAICS kubernetes version skew allows kubelets to be up to two minor versions older

> kubelets will get upgraded before the control plane, 

the nodes still have old kubelet versions running. `swupd` does not restart them automatically. it adds a message-of-the-day warning that kubelet minor version was updated.

**Comment by evankanderson** [comment]
> > kubelets will get upgraded before the control plane,
> 
> the nodes still have old kubelet versions running. `swupd` does not restart them automatically. it adds a message-of-the-day warning that kubelet minor version was updated.

I had a power-off event that restarted the nodes unexpectedly. 😬

**Comment by mdhorn** [comment]
We have added a migration bundle to Clear Linux OS which has the 1.18 binaries to enable migration from 1.17.x --> 1.18.15 --> 1.19.x.
Here is the migration guide
https://docs.01.org/clearlinux/latest/guides/clear/k8s-migration.html
