### ISSUE TITLE
bsd-2 clause license not accepted autospec

### ISSUE THREAD

**Issue by ksaltik** [clearlinux/distribution#189]
**Describe the bug**
When I try to build custom rpm from a source code with make autospecnew it doesn't accept bsd-2 clause license. When I change it with for example with gnu license it is accepted.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by ahkok** [comment]
The license code needs an exact match, therefore, you have to write it like this: `BSD-2-Clause`

**Comment by ahkok** [comment]
For reference, autospec uses SPDX identifiers (https://spdx.org/licenses/) only.
