### ISSUE TITLE
Package for libc++

### ISSUE THREAD

**Issue by mkviatkovskii** [clearlinux/distribution#1894]
I have installed Clang and other LLVM stuff using package **devpkg-llvm**. However it seems like libc++ is not installed. Could you please add a package for it? Thank you!

**Comment by bryteise** [comment]
@thiagomacieira would you mind turning on -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" for the llvm update you are doing?

**Comment by thiagomacieira** [comment]
Yes, I can look into libc++ too.

**Comment by thiagomacieira** [comment]
Do you also need libc++abi?

**Comment by mkviatkovskii** [comment]
> 
> 
> Do you also need libc++abi?
Yes, I think so. Clang either uses libstdc++ or libc++ with libc++abi, so only libc++ is not enough.

**Comment by thiagomacieira** [comment]
Clang doesn't care which ABI library libc++ is using.

**Comment by mkviatkovskii** [comment]
OK, sorry, I'm not a big specialist in how things are organized on such low level. The project that I want to build and run using Clearlinux links with both libc++ and libc++abi libraries. And on some other Linux distributions I interact with, `libc++.so` is always linked to `libc++abi.so`.

So, in my perspective, it seems to be a pretty standard way to do.

**Comment by thiagomacieira** [comment]
That's how I see other distros too.

The problem is that the two libraries depend on each other. Dependency cycles are a PITA to work with when the updates happen. So if you don't need libc++abi, I would rather not have it at all and allow libc++ to link to libstdc++.

**Comment by thiagomacieira** [comment]
libcxx is out. Let us know if it works for you!
