### ISSUE TITLE
Update LLVM to 10.0.0

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#1898]
https://releases.llvm.org/download.html#10.0.0

**Comment by phmccarty** [comment]
@thiagomacieira

**Comment by thiagomacieira** [comment]
Update pushed. See https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/NZIQLPKMNOLWV3FQ4JZIF3C7ETXWXNCJ/ for details.

clearlinux-pkgs/llvm#10.0.0-116
