### ISSUE TITLE
WPS office update

### ISSUE THREAD

**Issue by AleksandrLCW** [clearlinux/distribution#1899]
Official package name: com.wps.Office

License (OSI approved and Open Source): Not free (I use Russian localization don't know correct type)

Download URL of latest release: https://linux.wps.com/#

Latest release date: 11.1.0.9505

Description: installed at 15. April and application asks for update.

**Comment by lebensterben** [comment]
It's not open sourced

**Comment by ahkok** [comment]
Open Source license is required.
