### ISSUE TITLE
Consider not including /usr/local and /usr/local/share directories as part of the OS

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#19]
Right now os-core includes these two directories with root:root ownership, which always reset any custom ownership for those directories ~~in every update~~ when using `verify --fix`. Given Clear Linux doesn't install anything on those, maybe just remove them from the Manifest.

Filesystem package creates those: https://github.com/clearlinux-pkgs/filesystem/blob/master/filesystem.spec#L157

**Comment by cmarcelo** [comment]
One alternative is to use one of the swupd flags that create the directory but then doesn't touch it anymore.

**Comment by ahkok** [comment]
`root.root` and `0755` permissions seems entirely correct ownership. I think you're trying to be inventive by putting non-root compiled software without `sudo` into `/usr/local`, but that doesn't seem like a safe thing to do, as `/usr/local` is part of the default shell path of every user on the system. You should probably therefore not do this.

I consider what you want to be a security concern, and not something that we want any code to be supportive of?

**Comment by cmarcelo** [comment]
Your explanation makes sense to me. I’ve ignored the fact that /usr/local was being picked up by default, and the security aspect of this default ownership. Thanks!
