### ISSUE TITLE
Eclipse for c++

### ISSUE THREAD

**Issue by AleksandrLCW** [clearlinux/distribution#1902]
Official package name: Eclipse IDE for C/C++ Developers (includes Incubating components)

License (OSI approved and Open Source):

Download URL of latest release: https://www.eclipse.org/downloads/packages/release/2020-03/r/eclipse-ide-cc-developers-includes-incubating-components

Latest release date:2020-03-R

Description:

**Comment by ahkok** [comment]
Eclipse distributes official Linux tarballs that just work. There is no reason to package it - just download the official release for Linux in ZIP format....
