### ISSUE TITLE
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop"

### ISSUE THREAD

**Issue by isalgueiro** [clearlinux/distribution#1906]
I've got this error when running `update-desktop-database`

```
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)
The databases in [/home/isaac/.local/share/flatpak/exports/share/applications, /var/lib/flatpak/exports/share/applications, /usr/local/share/applications, /usr/share/applications] could not be updated.
```

I'm having some issues trying to set plasma-desktop default applications and I think this may be related to this `update-desktop-database` error.

I'm on version 32850

Edit: still happening in 32870

**Comment by ahkok** [comment]
Does temporarily removing the `/usr/share/applications/org.kde.kdeconnect_open.desktop` file and rerunning `update-desktop-database` resolve the issue?

**Comment by lebensterben** [comment]
This problem comes from upstream and this "*/*" mime type is hard coded.
See https://invent.kde.org/kde/kdeconnect-kde/-/blob/master/data/org.kde.kdeconnect_open.desktop

Also, this problem is recently reported in Arch. https://bugs.archlinux.org/task/65865

I've reported the bug to upstream
https://bugs.kde.org/show_bug.cgi?id=420431

**Comment by isalgueiro** [comment]
> Does temporarily removing the `/usr/share/applications/org.kde.kdeconnect_open.desktop` file and rerunning `update-desktop-database` resolve the issue?

I removed the invalid mime type entry and now `update-desktop-database` works. I still can't define default apps in plasma settings tho. No error messages, it just ignores what I select as default mail app.

**Comment by lebensterben** [comment]
>> Does temporarily removing the `/usr/share/applications/org.kde.kdeconnect_open.desktop` file and rerunning `update-desktop-database` resolve the issue? ...

@isalgueiro This is a separate issue. I suggest you to open another issue report.

**Comment by lebensterben** [comment]
Fixed in upstream
https://invent.kde.org/network/kdeconnect-kde/-/merge_requests/327

**Comment by phmccarty** [comment]
Thanks. This was fixed when we updated to kdeconnect-kde 20.12.0 back in December 2020 (release 34090)

**Comment by sebma** [comment]
@staudey Your solution of replacing `MimeType=*/*;` to `MimeType=application/octet-stream;` into `/usr/share/applications/org.kde.kdeconnect_open.desktop` worked :+1: 

Thanks.

**Comment by DonLarry** [comment]
> @Staudey Your solution of replacing `MimeType=*/*;` to `MimeType=application/octet-stream;` into `/usr/share/applications/org.kde.kdeconnect_open.desktop` worked 
> 
> Thanks.

Worked for me, thanks!

**Comment by justmlssky** [comment]
> @Staudey Your solution of replacing `MimeType=*/*;` to `MimeType=application/octet-stream;` into `/usr/share/applications/org.kde.kdeconnect_open.desktop` worked +1
> 
> Thanks.

This works
