### ISSUE TITLE
Display resolution limited to one

### ISSUE THREAD

**Issue by waraz** [clearlinux/distribution#1908]
![image](https://user-images.githubusercontent.com/1691461/79473705-1827b200-8038-11ea-9c87-c01f8cc77c68.png)

Hello, 
other resolutions disappeared after changing to this one. 
Any clue if able to revert to full resolution in this case?

**Comment by ahkok** [comment]
Not enough information to troubleshooot this issue:
- hardware information
- clearlinux version before, after issue found
- using wayland or Xorg
Additionally, what have you tried to resolve the issue yourself? Used xrandr? rebooted? Checked and booted an older kernel?

**Comment by waraz** [comment]
Have not tried older kernel. 
Possibly could try upgrading to the latest OS version.

Built-in display. 
Laptop LCD on Asus u32vd 
Intel Integrated graphics 
Nvidia Geforce GT 620M
How do I get you any other hardware info necessary?

On x11. 
Issue occured and persisted in current version. Same after reboot.

Current OS version: 32850
Latest server version: 32860
There is a new OS version available: 32860

$ xrandr --listproviders 
Providers: number : 1
Provider 0: id: 0x46 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 3 outputs: 4 associated providers: 0 name:modesetting

/sys/class/graphics/fb0 $ cat mode
/sys/class/graphics/fb0 $ cat modes
U:1920x1080p-0
/sys/class/graphics/fb1 $ cat mode
/sys/class/graphics/fb1 $ cat modes
U:640x480p-59

**Comment by waraz** [comment]
Seems to have been resolved with current version 33060.
