### ISSUE TITLE
Add sshpass to ansible bundle

### ISSUE THREAD

**Issue by szollin** [clearlinux/distribution#191]
Please add the sshpass program to the ansible bundle. It's needed so Ansible can perform logins with password protected servers. If the program isn't installed, you get the an error. Information below.

Command: `ansible-playbook new_vm.yml -k -l <host>`

Flag Information:
`-k, --ask-pass      ask for connection password`
`-l SUBSET, --limit=SUBSET       further limit selected hosts to an additional pattern`

Error Message:
`"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"`

**Comment by fenrus75** [comment]
ok done
