### ISSUE TITLE
desktop-kde missing kirigami

### ISSUE THREAD

**Issue by a-lakhani** [clearlinux/distribution#1910]
I installed all the clear linux bundles related to KDE:
 - desktop-kde
 - desktop-kde-apps
 - desktop-kde-libs
 - kde-frameworks5
 - kde-frameworks5-dev
 - kdebugsettings

Still, System Settings has problems with several menus related to Appearance:
![kde_bug3](https://user-images.githubusercontent.com/56142442/79490175-5342ca80-7fd1-11ea-9222-f1ff6b746565.png)
![kde_bug4](https://user-images.githubusercontent.com/56142442/79490179-53db6100-7fd1-11ea-9199-bed646e79b13.png)
![kde_bug1](https://user-images.githubusercontent.com/56142442/79490190-58077e80-7fd1-11ea-870e-74d0629937c7.png)
![kde_bug2](https://user-images.githubusercontent.com/56142442/79490193-5938ab80-7fd1-11ea-8860-b660240fa1c5.png)
 
The common denominator is 'org.kde.kirigami' not installed. Is this a package/bundle issue? I didn't get any errors during installation of the bundles and I restarted after installation.

Operating System: Clear Linux OS 32850
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.6.4-937.native
OS Type: 64-bit

**Comment by anselmolsm** [comment]
kirigami2 is part of desktop-kde-libs bundle, so that is not the issue.
However it seems like the update of kirigami2 to 5.69 lost the boat for 32850. but it's in for 32860.
