### ISSUE TITLE
Add CUPS dev headers somewhere 

### ISSUE THREAD

**Issue by Ralim** [clearlinux/distribution#1917]
Official package name: CUPS

Description:

Clear Linux ships CUPS but does not ship any form of the dev headers from what I can see.
This causes issues when compiled drivers need to be used such as [brlaser](https://github.com/pdewacht/brlaser).

Not sure if there is some magic i dont know to download these other than being a bundle that can be installed?

**Comment by bryteise** [comment]
cups headers are in a few bundles already (`swupd search-file /usr/include/cups/array.h` for instance will show them).

**Comment by Ralim** [comment]
Ah cool, bit of a pest that the smallest one appears to be `dev-utils-dev` at 1G for just the header files (and the mirror download rate of 100KB/sec). But thank you, that does work :)

I'll close this once the download finishes and i confirm it works for brlaser :D

**Comment by AugustNagro** [comment]
I don't think this issue should be closed. It shouldn't require a 1gb bundle that includes Postgres database to get this small library w/ headers.

Cups is important for building a lot of software, including OpenJDK.

**Comment by AugustNagro** [comment]
A workaround of course is to manually install cups following the INSTALL.md.

https://github.com/apple/cups/releases

use `./configure --prefix=<some temp directory>`, then `make install`. You can then manually specify the cups headers for the software you're building.

**Comment by thiagomacieira** [comment]
Will create a devpkg-cups.

**Comment by thiagomacieira** [comment]
Will appear in 32990
