### ISSUE TITLE
hwclock -s does not work and tells settimeofday() failed: Invalid argument

### ISSUE THREAD

**Issue by xinzhanz** [clearlinux/distribution#1919]
Description:
     “hwclock -s” is simple command to set the system time from the RTC. It run well on clear linux  32060. But it failed on 32840 with same kernel config, etc.
      
The failed message is: hwclock: settimeofday() failed: Invalid argument
     
Ubuntu has no such issue.
 
    Reproduce steps:
     1. Boot up to kernel
    2. hwclock -s
 
Good clear linux:
Distribution:      Clear Linux OS
Installed version: 32060
Bad clear linux:
Distribution:      Clear Linux OS
Installed version: 32840

Auke Kok answered:
This is an expected breakage, and `hwclock` should have patched the call to settimeofday() to use clock_settime() instead.

Upstream hwclock.c from util-linux already has this:

https://github.com/karelzak/util-linux/commit/cd781c405be82540484da3bfe3d3f17a39b8eb5c#diff-0ba721e0b4d88d4296552c06b999ad5b

But, no release has been made upstream after this release yet (Feb21 fix, last release Jan31).

Create the issue to track this issue

**Comment by xinzhanz** [comment]
The fix patch is included and will be in a release soon.

**Comment by ahkok** [comment]
This is part of `32870` and newer.
