### ISSUE TITLE
Engines check doesn't work with Node from nodejs-basic bundle

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#1921]
Engines check for Node in `package.json` doesn't work, it says that the required version is not installed even though the version strings matches the expected version?

I'm using manually installed [Yarn](https://classic.yarnpkg.com/en/docs/install/#alternatives-stable) `v1.22.4` for this since neither `nodejs-basic` nor `yarn` bundles provides it (#962) at the moment _(in release 32870)_. This issue doesn't occur if you manually install Node or use NVM.

package.json
````json
{
  "name": "example",
  "license": "GPL-3.0",
  "engines": {
    "node": "12.50.0"
  }
}
````
result
```bash
$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/5] Validating package.json...
error example@: The engine "node" is incompatible with this module. Expected version "12.50.0". Got "12.15.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by lebensterben** [comment]
@xRiot I just installed `yarn` myself.
Could you show me what's is the project you're working on when you see the error?
So I can try to reproduce the bug.

**Comment by xRiot** [comment]
> 
> 
> @xRiot I just installed `yarn` myself.
> Could you show me what's is the project you're working on when you see the error?
> So I can try to reproduce the bug.

You can replicate the issue by installing `nodejs-basic` _(which currently provides Node 12.15.0)_ and then creating a `package.json` file with this content:
```json
{
  "name": "example",
  "license": "GPL-3.0",
  "engines": {
    "node": "12.50.0"
  }
}
```
When you do `yarn install` inside the directory where this `package.json` resides, you'll get a error saying:
```bash
... Expected version "12.50.0". Got "12.15.0" ...
```
This only happens with Node from Clear Linux repository, if you uninstall the `nodejs-basic` bundle and use manually installed Node or even easier [NVM](https://github.com/nvm-sh/nvm) to install `12.50.0`, it works flawlessly...

Maybe the version string in Clear Linux's Node has the wrong datatype?

**Comment by lebensterben** [comment]
50 != 15

The package.json requires 12.50, but your node is 12.15.
This is not a bug. You need to fix the typo in package.json.

**Comment by xRiot** [comment]
I beg pardon, my eyes tricked me. Thanks for pointing it out @lebensterben!
