### ISSUE TITLE
openshot-qt

### ISSUE THREAD

**Issue by SJBERTRAND** [clearlinux/distribution#1922]
The bundle openshot-qt doesn't work. The application doesn't start.

When launching openshot-qt in a terminal you get hte following error:

ModuleNotFoundError: No module named 'PyQt5'

Installing python-qt didn't help

**Comment by ahkok** [comment]
And PyQt5 isn't in any reasonable bundle atm. I've added it as part of the openshot-qt bundle, it should be available in 1-2 days or so as part of an update.

**Comment by SJBERTRAND** [comment]
Thanks you
