### ISSUE TITLE
Strange flags in default shell profile

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1928]
In the default shell profile,
- `/usr/share/defaults/etc/profile` for `bash`
- `/usr/share/defaults/etc/zshenv` for `zsh`

there are the following compile flags: `CFLAGS`, `FFLAGS`, `CFFLAGS`, and `CXXFLAGS`.

I believe that `CFFLAGS` is a typo and it should be `CPPFLAGS` instead.

The `CFFLAGS` is not documented AFAIK anywhere.

See: https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

**Comment by ahkok** [comment]
It's supposedly for fortran (gfortran). Could still be a typo, though.

**Comment by ahkok** [comment]
`FCFLAGS     Fortran compiler flags`

Looks like it's a simple transpose error.

**Comment by lebensterben** [comment]
>`FCFLAGS     Fortran compiler flags` ...

@ahkok Yes, this is more likely than CPPFLAGS.

According to https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Fortran-Compiler.html

FFLAGS and FCFLAFS are for legacy and modern Fortran respectively.

**Comment by ahkok** [comment]
Yep, I'm changing it to FCFLAGS

**Comment by ahkok** [comment]
`filesystem-3.0.14-204`

**Comment by xaverh** [comment]
It is still CFFLAGS in /usr/share/defaults/etc/zshenv (release 33940).
