### ISSUE TITLE
crictl: does not use same socket default as crio daemon

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#193]
The crio daemon listens on `/var/run/crio/crio.sock`, but crictl uses `/var/run/dockershim.sock` as default. Therefore one has to remember to pass the right socket:
```
crictl -r unix:///var/run/crio/crio.sock images
```

Shouldn't crictl use `/var/run/crio/crio.sock` by default if Clear Linux doesn't have `/var/run/dockershim.sock`?

**Comment by ahkok** [comment]
@joselamego

**Comment by joselamego** [comment]
fix merged in commit b5ddc338432a50f49a58816c6c37997d37ace787

**Comment by joselamego** [comment]
@ahkok please close this report.

**Comment by joselamego** [comment]
fix merged in commit b5ddc338432a50f49a58816c6c37997d37ace787
