### ISSUE TITLE
SU password breaks after install on VM

### ISSUE THREAD

**Issue by addeps3** [clearlinux/distribution#1931]
Ive reinstalled Clear in a VirtualBox VM nine times today, and every time I reboot the root password is "incorrect". Im using the most basic password possible: and use the same for the user account but the root password produces "Incorrect" *every* single time after reboot. 

I even attempt to test the password after installation by signing out the root account, and back in, and it works, no problem. I dont mess around with keyboard layout, I leave everything at default. 

edit: I just tried again, and root password works before reboot, post-istallation, but not once rebooted in to the new system. 

forgot to mention that attempting "su" command while signed in as user produces "incorrect" as well.

Changing "passwd" after installation I have tried as well.

**Comment by addeps3** [comment]
I might have selected the wrong .ISO by DL'ing the OS server image, but that's what the instructions said.

**Comment by mdhorn** [comment]
If you are installing with one of the ISOs, we require there to be an administrative account (which will have sudo privileges), and the root account is disabled. 

Have a root account with a password is a security risk.

If you want a root login with a password, log into the adminstrative account, and unlock root
`sudo usermod --unlock root`
Then please set a password:
`sudo passwd root`

**Comment by addeps3** [comment]
Very good, thank you and please forgive my ignorance. 

Solved and closing.
