### ISSUE TITLE
kernel-native enable CONFIG_SND_HDA_PATCH_LOADER

### ISSUE THREAD

**Issue by gregor160300** [clearlinux/distribution#1933]
On my laptop (HP ZBOOK Studio G5 x360) and on other HP laptops by default, only 2 out of the 4 integrated speakers work in Linux. This can be fixed by enabling some pins (different for every model) with hdajackretask. However enabling these pins while the operating system is in use can cause issues, the application allows for setting these patches on boot, but on clearlinux the needed config is disabled, therefore I request CONFIG_SND_HDA_PATCH_LOADER to be enabled in the kernel.

**Comment by bwarden** [comment]
Change will be in linux-5.6.8-945
