### ISSUE TITLE
alsa-tools package request

### ISSUE THREAD

**Issue by gregor160300** [clearlinux/distribution#1934]
**Official package name:** alsa-tools

**License (must be an OSI approved Open Source license):** GPL2

**Download URL of latest release:** https://github.com/alsa-project/alsa-tools/archive/v1.2.2.tar.gz

**Latest release date (must be recent):** 19-02-2020

**Description:**

The Advanced Linux Sound Architecture (ALSA) - tools
This contains multiple programs that offer advanced users more control over their audio. It especially includes hdajackretask which is needed for some laptops, mainly HP ones, to enable all hardware audio devices. See also [this bug report](https://bugzilla.kernel.org/show_bug.cgi?id=189331#c258)

**Comment by bwarden** [comment]
Making progress on this; I need to find a bundle to add it to.

**Comment by bwarden** [comment]
Look for the alsa-tools bundle sometime in the next couple of releases.

**Comment by gregor160300** [comment]
I will, thank you
