### ISSUE TITLE
Update Blender to 2.79b

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#194]
**List the package(s) you would like to see updated**

Blender 2.78 --> 2.79b
Link to tarball: https://www.blender.org/download/Blender2.79/blender-2.79b-linux-glibc219-x86_64.tar.bz2/

Most distributions have already packaged Blender 2.79b, including Solus, Ubuntu, Fedora 28, and OpenSUSE Tumbleweed.

**Does this update provide any significant new features that may be needed**

- Denoiser
- PBR Shader
- Shadow Catcher
- Filmic Color Management
- Faster AMD OpenCL
- Over 700 bugs fixed

**Comment by ahkok** [comment]
We don't have blender packaged, so, technically, you can't ask for it to be updated :).

However, please note, that there is a very decent flatpak version of blender on `flathub.org`.

I do believe, and I'm sure @fenrus75 would agree, that we should just package it so you can potentially benefit from clr's compiler optimizations.

**Comment by OpenSourceAnarchist** [comment]
What's this then? Unmaintained?

https://github.com/clearlinux-pkgs/blender

**Comment by fenrus75** [comment]
eh to make this simple
I put blender back and am updating it

**Comment by fenrus75** [comment]
I’m still having a argument with it.

It does not want to compile

I disagree

**Comment by OpenSourceAnarchist** [comment]
@fenrus75 Haha, I like that analogy. While it would be nice to use (and benefit from Clear's optimizations), there is a flatpak version that works, so don't spend too much time on it. I'd rather the time be spent on keeping up with the core packages... and maybe working on ffmpeg/codecs so we can watch more videos in Firefox and through media players :)

**Comment by phmccarty** [comment]
blender was updated to 2.79b back in December 2018. Closing.
