### ISSUE TITLE
Add ffmpeg

### ISSUE THREAD

**Issue by fmlatghor** [clearlinux/distribution#1941]
Official package name: ffmpeg

License (must be an OSI approved Open Source license): LGPL; some files have MIT/X11/BSD-style licenses.

Download URL of latest release: https://www.ffmpeg.org/download.html

Latest release date (must be recent): 10/5/19

Description: CLI to convert media files between formats.

**Comment by thiagomacieira** [comment]
Sorry, we can't honour this request. We already have ffmpeg, but since it's very stripped down (we removed all non-free codecs), it's called "not-ffmpeg". It's unlikely to be useful to you.
