### ISSUE TITLE
Add xwallpaper

### ISSUE THREAD

**Issue by fmlatghor** [clearlinux/distribution#1942]
Official package name: xwallpaper

License (must be an OSI approved Open Source license): ISC

Download URL of latest release: https://github.com/stoeckmann/xwallpaper

Latest release date (must be recent): 4/13/20

Description: CLI to set wallpaper

**Comment by ahkok** [comment]
No.

We've recently announced that we will not be supporting desktops outside Gnome, Kde and Xfce4. Those all come with desktop wallpaper software. So, there is no longer a need or a place for custom wallpaper software.
