### ISSUE TITLE
Ungoogled Chromium

### ISSUE THREAD

**Issue by fmlatghor** [clearlinux/distribution#1944]
Official package name: 
ungoogled-chromium

License (must be an OSI approved Open Source license):
BSD 3-Clause "New" or "Revised" License

Download URL of latest release:
https://github.com/laamalif/ungoogled-chromium-binaries/releases/download/80.0.3987.149-2/ungoogled-chromium_80.0.3987.149-2_linux.tar.xz

Latest release date (must be recent):
4/8/2020

Description:
Chromium with all the Google components removed

**Comment by ahkok** [comment]
Unlikely that we'll merge this due to the fact that this is a binary. Not much better for the source, either since this is a fork and we tend to avoid forks in case of an upstream project that's well maintained and considered the authoritative source.

**Comment by fmlatghor** [comment]
I think this is a well maintained project. It's well known and included in trustworthy repos (e.g. RPM Fusion).

**Comment by ahkok** [comment]
We're not including chromium either. So a fork of chromium is definitely not on the table right now.

**Comment by fmlatghor** [comment]
I've seen other distros avoid chromium/chrome -- may I know the reasoning? Chromium is fully licensed as open-source. Do you guys like to avoid multi-licensed software?

**Comment by fmlatghor** [comment]
What was the reasoning for getting rid of alternative desktops? Less maintenance?

**Comment by ahkok** [comment]
Chrome/Chromium contains codec software that we cannot include.

**Comment by ahkok** [comment]
Let's try and keep things on topic in this github. I've answered your other question in our forum announcement post a few days back.

**Comment by fmlatghor** [comment]
Forum announcement post? The only other place I've asked questions has been the IRC.

**Comment by ahkok** [comment]
https://community.clearlinux.org/t/changes-coming-to-clear-linux-direction/4337/68

**Comment by fmlatghor** [comment]
Not me.

**Comment by fmlatghor** [comment]
Ok, the announcement post was a sufficient explanation. I'll check there next time.
