### ISSUE TITLE
Allow for packages to be installed seperate of bundles

### ISSUE THREAD

**Issue by fmlatghor** [clearlinux/distribution#1945]
The bundle approach is neat, but it sometimes gets in your way. Bundles have two major pros and cons:
Pro: easy to get stuff up and running by installing bundles; good for a server or a specific enviroment
Con: you don't end up using all the packages in the bundle; i.e. bloat

Clearlinux is making an effort to incude packages for the user, so why are things still like this? I'm sure someone has brought this up before, but I'd like some info.

**Comment by ahkok** [comment]
What is your specific question?

**Comment by thiagomacieira** [comment]
We are making smaller bundles, sometimes with the contents of a single package.
