### ISSUE TITLE
Add DWM

### ISSUE THREAD

**Issue by fmlatghor** [clearlinux/distribution#1947]
Official package name: 
DWM

License (must be an OSI approved Open Source license):
MIT/X Consortium license

Download URL of latest release:
https://dl.suckless.org/dwm/dwm-6.2.tar.gz

Latest release date (must be recent):
2019-02-03

Description:
Minimalist TWM.

I know DWM is more meant to be built from source (because that's how it's configured), but it'd be nice to be able to easily install it from tty or the commandline.

**Comment by ahkok** [comment]
We've decided no longer to include alternative desktop environments.
