### ISSUE TITLE
Epson print drivers

### ISSUE THREAD

**Issue by chrysophylax** [clearlinux/distribution#1948]
Official package name: epson-escpr (?)

License (must be an OSI approved Open Source license): GPL v3

Download URL of latest release:
http://download.ebz.epson.net/dsc/du/02/DriverDownloadInfo.do?LG2=EN&CN2=&DSCMI=104918&DSCCHK=f4af1a8de19da08e2e1da28e9fbddefc949c9eed#

Latest release date (must be recent):
12-26-2019

Description:
Printer configuration drivers and C filter program for CUPS

Would add support for a large portion of SEIKO Epson printers that are currently not supported in ClearLinux (e.g. Ecotank ET-7x series). 

Comes with rpm, deb, tar.gz source and instructions for building on non-LSB compliant distributions.
Note that building by default using `--prefix=/usr/local` leads to CUPS trying to find the filter program in `/usr/lib/cups/filter` and failing instead of searching where `make install` chucks it (`/usr/local/lib/cups/filter`).

**Comment by bwarden** [comment]
In progress:
https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/FMZJEWAE4YISCBB5U2Y3RJGHKQO467TP/

**Comment by chrysophylax** [comment]
Thank you!
