### ISSUE TITLE
ruby-basic: Ruby update 2.6.5 -> 2.7.1 (new major release + security patch)

### ISSUE THREAD

**Issue by chrysophylax** [clearlinux/distribution#1950]
Ruby was updated to a new major version back in december 2019.
There has been a recent patch now in march (2.7.1) that fixes some security issues.

It would be nice if the version in ruby-basic was updated.

https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-7-1-released/

**Comment by phmccarty** [comment]
`ruby` was updated to 2.7.1 in release `33500` from July. Closing.
