### ISSUE TITLE
clang-9: fails to find builtin includes

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#1954]
I'm building Envoy on Clear Linux. Envoy defaults to clang 9 so I need to set

```
build:clang --action_env=CC=clang-9
build:clang --action_env=CXX=clang++-9
```

Building with clang-9 triggers a build error:

```
==== Building LuaJIT 2.1.0-beta3 ====
make -C src
make[1]: Entering directory '/tmp/tmp.7P20yAoDLO/com_github_luajit_luajit/src'
HOSTCC    host/minilua.o
/usr/sbin/clang-9  -O2 -fomit-frame-pointer -Wall -DLUAJIT_ENABLE_LUA52COMPAT  -I. -DLUAJIT_TARGET=LUAJIT_ARCH_x64 -DLJ_ARCH_HASFPU=1 -DLJ_ABI_S
host/minilua.c:31:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
1 error generated.
```

Notes:
- the build succeeds if I build LuaJit with clang-10 and the rest of Envoy with clang-9
- this works on Clear Linux 32880 which has clang 9 only

**Comment by thiagomacieira** [comment]
I thought I'd fixed this. Will investigate Monday.

The issue is a missing symlink because I moved the compiler from /usr/bin to /usr/lib644/clang/<version>/bin

**Comment by thiagomacieira** [comment]
I can't reproduce anymore. I think I did indeed fix it, with https://github.com/clearlinux-pkgs/llvm9/releases/tag/9.0.1-2

**Comment by mythi** [comment]
I can confirm it works with 33070. It was still failing last week... Thanks!

**Comment by thiagomacieira** [comment]
I guess I fixed it with the rebuild (LLVM 9 compiled with LLVM 10), which I did stage last week. So when I tested on Monday, it was already there.
