### ISSUE TITLE
 MATE Desktop Environment

### ISSUE THREAD

**Issue by josephmoresena** [clearlinux/distribution#1958]
Official package name: MATE Desktop Environment

License (must be an OSI approved Open Source license):  GPLv2, LGPLv2

Download URL of latest release: https://pub.mate-desktop.org/releases/1.24/

Latest release date (must be recent): 2020-02-10

Description:
The MATE Desktop Environment is the continuation of GNOME 2. It provides an intuitive and attractive desktop environment using traditional metaphors for Linux and other Unix-like operating systems.

**Comment by ahkok** [comment]
Negative. Our current goals are to maintain GNOME, Xfce and KDE(Plasma) and that's it. We're not adding new desktops.
