### ISSUE TITLE
Black screen on NVIDIA as of recent update

### ISSUE THREAD

**Issue by aluo-x** [clearlinux/distribution#1968]
GCC got updated to GCC 10.1, while the kernel is still compiled with GCC 9. Appending ignore-cc does not allow for NVIDIA drivers to install.

**Comment by aluo-x** [comment]
Tagging @ahkok 
Seems like a repeat of bug #1835

**Comment by bwarden** [comment]
You don't have to tag anyone; we do check bugs regularly :)

Kernel [5.6.13-952](https://github.com/clearlinux-pkgs/linux/tree/5.6.13-952) is already compiled with gcc 10.1 and should be in the next release. Unfortunately, you're likely to run into things like this any time you use DKMS, and _especially_ with NVIDIA drivers, any time the kernel or compiler is updated. We do rebuild the kernel after upgrading the compiler, but it can lag a release or two if the kernel itself requires patching to work with the new gcc.

**Comment by aluo-x** [comment]
Thanks! Closing the bug now.

**Comment by aluo-x** [comment]
As an aside, can we get a gcc-9 package, similar to the [c-extras-gcc8](https://clearlinux.org/software/bundle/c-extras-gcc8) package that we currently have?

Also the 5.6.13-952 tag is invalid, maybe a private or internal repo?

**Comment by bwarden** [comment]
The gcc9 package is already underway, The 5.6.13-952 tag will be valid once the kernel is released.
