### ISSUE TITLE
kernel-lts-dkms need to be rebuild with new gcc

### ISSUE THREAD

**Issue by hnanni** [clearlinux/distribution#1970]
NVIDIA's setup driver script fails with the following log:

```
cat /var/lib/dkms/nvidia/440.82/build/make.log
DKMS make.log for nvidia-440.82 for kernel 5.4.40-38.lts2019 (x86_64)
Fri May 15 12:01:13 CDT 2020
make[1]: Entering directory '/usr/lib/modules/5.4.40-38.lts2019/build'
  SYMLINK /var/lib/dkms/nvidia/440.82/build/nvidia/nv-kernel.o

Compiler version check failed:

The major and minor number of the compiler used to
compile the kernel:

gcc version 9.3.1 20200507 releases/gcc-9.3.0-217-g7790399265 (Clear Linux OS for Intel Architecture)

does not match the compiler used here:

cc (Clear Linux OS for Intel Architecture) 10.1.1 20200513 releases/gcc-10.1.0-36-gf2b77b928a
```
Please rebuild the kernel-lts-dkms bundle with the new compiler so the modules-kernel version match

**Comment by bwarden** [comment]
@miguelinux has already built linux-lts2019-5.4.41-39, that will resolve this when it makes it into a release.

**Comment by hnanni** [comment]
linux-lts2019-5.4.41-39 is not yet in 33110. Can it be pushed or may I have the rpm?

**Comment by bwarden** [comment]
> linux-lts2019-5.4.41-39 is not yet in 33110. Can it be pushed or may I have the rpm?

Looks like the build may have failed due to lingering gcc10 issues :(

**Comment by hnanni** [comment]
is having a sort of gcc-9 lts-ish bundle may be an option?
