### ISSUE TITLE
Failed to start systemd-importd.service: Unit systemd-importd.service not found.

### ISSUE THREAD

**Issue by rbucker** [clearlinux/distribution#1973]
I'm trying to deploy clearlinux in it's own nspawn. I'm using example clearlinux/clr-bundles#1 from the `nspawn` man page and even though I started `systemd-machined` that seemed to not be enough.

Some docs suggested I needed the importd service which I could not start because it was not installed.

```
# systemctl start systemd-importd
Failed to start systemd-importd.service: Unit systemd-importd.service not found.
```

So, please add it if it's missing and if not please explain how to launch nspawn.

thanks

**Comment by bryteise** [comment]
What bundles do you have installed on your system? (this works for me so I'm unsure what would be missing). Also what is the error you getting running the `systemd-nspawn` command as root?

**Comment by rbucker** [comment]
This is the command I ran - 

```
root@clr~ # machinectl pull-raw --verify=no                  https://cdn.download.clearlinux.org/releases/33110/clear/clear-33110-kvm.img.xz                  ClearLinux33110
Failed to transfer image: The name org.freedesktop.import1 was not provided by any .service files
```

**Comment by bryteise** [comment]
So looking around with swupd search-file, the systemd-importd.service file is available in a few bundles. Likely the smallest one for you to install would be polkit.

@ahkok do you know the reason why this was split off?

**Comment by rbucker** [comment]
@bryteise thanks for that... I see that I could import polkit... but then I inherit all sorts of cruft from the KDE packages and more... What's worse is that I'm console only. No desktop and so I'll bet I get all those Crufty X11 libs too... so how to install that file without the cruft?

**Comment by ahkok** [comment]
Our `polkit` bundle only contains `polkit` itself and the system libraries it requires. Nothing like X11.

It's still large due to the JS component in there, which is why that binary is not part of core systemd and split out.

solution: `sudo swupd bundle-add polkit`.

**Comment by rbucker** [comment]
Thanks.  It's working well.... Next step it to learn me some nspawn
networking and best practices.
