### ISSUE TITLE
'swupd diagnose --picky' gives different corrupted files

### ISSUE THREAD

**Issue by ju5tevg3niy** [clearlinux/distribution#1975]
Running `swupd diagnose --picky` multiple times shows different corrupted files.

<details>
  <summary>First run:</summary>
Diagnosing version 33110
Downloading missing manifests...
    
Checking for missing files
 [100%]

Checking for corrupt files
 -> Hash mismatch for file: /usr/lib64/clang/10.0.0/lib/linux/libclang_rt.xray-x86_64.a
 -> Hash mismatch for file: /usr/lib64/samba/libsamdb-common-samba4.so
 [100%]

...
</details>

<details>
  <summary>Second run:</summary>
Downloading missing manifests...
    
Checking for missing files
 [100%]

Checking for corrupt files
 [100%]

...
</details>

<details>
  <summary>Third run:</summary>
Diagnosing version 33110
Downloading missing manifests...
    
Checking for missing files
 [100%]

Checking for corrupt files
 -> Hash mismatch for file: /usr/lib32/libicudata.so.64.2
 -> Hash mismatch for file: /usr/share/fonts/noto/NotoSans-ExtraCondensedExtraBoldItalic.ttf
 [100%]

...
</details>

<details>
  <summary>Fourth run:</summary>
Diagnosing version 33110
Downloading missing manifests...
    
Checking for missing files
 [100%]

Checking for corrupt files
 -> Hash mismatch for file: /usr/share/locale/nn/LC_MESSAGES/mutter.mo
 [100%]

...
</details>

In `journalctl` there are no errors related to ext4, malfunctioning device or anything else.
The rest of the system works fine.

Clear Linux 33110
Kernel: 5.4.40-38.lts2019

**Comment by ahkok** [comment]
This is a known issue. There are 2 problems:
- `fc-cache` / font-config creating .uuid files under `/usr`
- `ldconfig` creating symlinks.

**Comment by JustEvgeniy** [comment]
No, I'm talking about the `Hash mismatch` lines under `Checking for corrupt files`

I edited the logs for clarity.

**Comment by ahkok** [comment]
Ah, I missed that part, that certainly is unexpected.

**Comment by ahkok** [comment]
@otaviobp

**Comment by ju5tevg3niy** [comment]
Can't reproduce in `33360` / `5.4.45-44.lts2019`
I don't know what was it, but now it seems to be fixed.
