### ISSUE TITLE
Gnome keyring issues at boot

### ISSUE THREAD

**Issue by jumpinggoofballs** [clearlinux/distribution#1976]
This is going to be a pain in the rear to track down, but on my current install of Clear (about 4 days old) I have already had about 5-10 boots where the keyring fails to start and my desktop gets taken over by the keyring password prompt - several times in succession if I try to cancel.

Probably relevant: 
- Using the Wayland session and GDM auto-login. 
- Typically goes away after a reboot or two.
- Seems completely random, so it is likely that it is a problem of timing of services startup in systemd. 

I would speculate that systemd might be attempting to start the keyring independently of some other service the keyring depends on. And sometimes that service is started before the keyring, as is necessary, but sometimes is started only after. I'm by no means an expert in systemd, but given the randomness, a service dependency issue seems to be the most likely cause.

**Comment by rossburton** [comment]
Are you really using the Wayland session?  Since the 3.36 upgrade I don't have a Wayland option in the greeter?

**Comment by jumpinggoofballs** [comment]
Will do. 

Has not happened in the past two days, and there have been a couple of updates since. I'm keeping the tab with this open, and if it does not happen again in the next two weeks, I will close the issue.

**Comment by jumpinggoofballs** [comment]
Okay, so I have not had the issue again for about a week and through 3ish system updates. Very puzzling behaviour, but I will close this issue for now and only re-open it if it pops up again.
