### ISSUE TITLE
Unzip misconfigured

### ISSUE THREAD

**Issue by citron** [clearlinux/distribution#1977]
Hello
On clearlinux 33110, download [Oracle Instantclient](https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip) and unzip it.
As you forgot to compile "unzip" with the -DNO_LCHMOD flag, we get errors like these :

foo@bar~/oracle $ unzip  ~/Downloads/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip 
Archive:  /home/bar/Downloads/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip
  inflating: instantclient_19_6/adrci  
  inflating: instantclient_19_6/BASIC_LICENSE  
  inflating: instantclient_19_6/BASIC_README  
  inflating: instantclient_19_6/genezi  
  inflating: instantclient_19_6/libclntshcore.so.19.1  
    linking: instantclient_19_6/libclntsh.so  -> libclntsh.so.19.1 
    linking: instantclient_19_6/libclntsh.so.10.1  -> libclntsh.so.19.1 
    linking: instantclient_19_6/libclntsh.so.11.1  -> libclntsh.so.19.1 
    linking: instantclient_19_6/libclntsh.so.12.1  -> libclntsh.so.19.1 
    linking: instantclient_19_6/libclntsh.so.18.1  -> libclntsh.so.19.1 
  inflating: instantclient_19_6/libclntsh.so.19.1  
  inflating: instantclient_19_6/libipc1.so  
  inflating: instantclient_19_6/libmql1.so  
  inflating: instantclient_19_6/libnnz19.so  
    linking: instantclient_19_6/libocci.so  -> libocci.so.19.1 
    linking: instantclient_19_6/libocci.so.10.1  -> libocci.so.19.1 
    linking: instantclient_19_6/libocci.so.11.1  -> libocci.so.19.1 
    linking: instantclient_19_6/libocci.so.12.1  -> libocci.so.19.1 
    linking: instantclient_19_6/libocci.so.18.1  -> libocci.so.19.1 
  inflating: instantclient_19_6/libocci.so.19.1  
  inflating: instantclient_19_6/libociei.so  
  inflating: instantclient_19_6/libocijdbc19.so  
  inflating: instantclient_19_6/liboramysql19.so  
   creating: instantclient_19_6/network/
  inflating: instantclient_19_6/ojdbc8.jar  
  inflating: instantclient_19_6/ucp.jar  
  inflating: instantclient_19_6/uidrvci  
  inflating: instantclient_19_6/xstreams.jar  
   creating: instantclient_19_6/network/admin/
  inflating: instantclient_19_6/network/admin/README  
finishing deferred symbolic links:
  instantclient_19_6/libclntsh.so -> libclntsh.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libclntsh.so.10.1 -> libclntsh.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libclntsh.so.11.1 -> libclntsh.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libclntsh.so.12.1 -> libclntsh.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libclntsh.so.18.1 -> libclntsh.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libocci.so -> libocci.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libocci.so.10.1 -> libocci.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libocci.so.11.1 -> libocci.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libocci.so.12.1 -> libocci.so.19.1
lchmod (file attributes) error: Function not implemented
  instantclient_19_6/libocci.so.18.1 -> libocci.so.19.1
lchmod (file attributes) error: Function not implemented

May you please fix it ?

**Comment by ahkok** [comment]
We're not building with manual build flags and the auto configure code used was incorrectly relying on lchown() being functional, and I think it's been deprecated for a while now.

I've patched this and it will be fixed in an update in a few days.
