### ISSUE TITLE
Enable `Emacs Dynamic Modules` feature for `emacs`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1978]
Currently, `emacs` is not built with dynamic module support, which is needed by certain `emacs` packages, e.g. `emacs-libvterm`, a faster terminal emulator based on C library `libvterm`, which is also used by `neovim`'s terminal emulator.

This can be enabled by appending `--with-module` option to `configure`.

**Comment by thiagomacieira** [comment]
Adding the option is easy. Is there a simple way to check that the functionality works?

**Comment by lebensterben** [comment]
>Adding the option is easy. Is there a simple way to check that the functionality works?

@thiagomacieira In Emacs, check value of `module-file-suffix`, it's non `nil` when this feature is enabled. Alternatively, value of `system-configuration-features` contains all enabled features, and "MODULES" represents this one.

**Comment by thiagomacieira** [comment]
Then that isn't sufficient
```
$ emacs -batch --eval="(prin1 system-configuration-features)"; echo
"GPM DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB THREADS LIBSYSTEMD"
$ emacs -batch --eval="(prin1 module-file-suffix)"; echo
nil
```

**Comment by thiagomacieira** [comment]
```
configure: WARNING: unrecognized options: --disable-static, --with-module
```

**Comment by thiagomacieira** [comment]
Looks like it's `--with-modules`. Rebuilding.

**Comment by thiagomacieira** [comment]
```
$ emacs -batch --eval="(prin1 system-configuration-features)"; echo
"GPM DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB MODULES THREADS LIBSYSTEMD"
$ emacs -batch --eval="(prin1 module-file-suffix)"; echo
".so"
```

**Comment by lebensterben** [comment]
>``` ...

@thiagomacieira This should be the correct output. Thx!
