### ISSUE TITLE
Please update `R` to 4.0.0

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#1979]
`R` has been updated to 4.0.0 recently. https://cran.r-project.org/src/base/R-4/

**Comment by phmccarty** [comment]
I will be updating it today, as announced last week: https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/QJ4OSBI6EIZB6I4SH27APIZHBCWGXDRM/

**Comment by lebensterben** [comment]
>I will be updating it today, as announced last week: https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/QJ4OSBI6EIZB6I4SH27APIZHBCWGXDRM/

@phmccarty Thanks.

**Comment by phmccarty** [comment]
I have finished the task of updating `R` and confirmed that all CRAN packages have been rebuilt with it.

The changes should land in build `33180` or newer.

**Comment by phmccarty** [comment]
Released in `33180`.
