### ISSUE TITLE
GnuTLS knows no system CA certificates

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#198]
```shell
$ gnutls-cli clearlinux.org
Error setting the x509 trust file
Resolving 'clearlinux.org:443'...
[...]
- Status: The certificate is NOT trusted. The certificate issuer is unknown. 
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.
*** handshake has failed: Error in the certificate.
```

The reason for this is that the GnuTLS library is configured without knowing where the system certificates are. Disassembly to prove:

```
(gdb) disass
Dump of assembler code for function gnutls_x509_trust_list_add_system_trust:
=> 0x00007ffff7e81960 <+0>:     mov    $0xfffffb1e,%eax
   0x00007ffff7e81965 <+5>:     retq   
End of assembler dump.
```

This function does not add anything and does return an error code to the caller. That error code results in the "Error setting the x509 trust file" message.

**Comment by bryteise** [comment]
@busykai We didn't have a default pkcs11 trust store file configured but after adding anchors directory and this issue went away. Would you expect us to do something different or is this a good fix?

**Comment by busykai** [comment]
@bryteise, clearlinux-pkgs/gnutls@e62caf245d is a good fix. Ideally, gnutls should prefer pkcs11 backend (which brings over trust info from pkcs11-kit, too). I'm not sure where `unix://` garbage config came from.

**Comment by thiagomacieira** [comment]
We tried pcks11 and it failed to find anything.

**Comment by tpleavitt** [comment]
Closing as fixed, per @ahkok
