### ISSUE TITLE
GIMP: X Window System and GEGL error

### ISSUE THREAD

**Issue by isabelomakhanya** [clearlinux/distribution#1981]
Gimp has been crashing since about last week not sure on the exact CLx version, I first noticed this when trying to crop/cut images amongst other activities. This is the error message (both Wayland and Xorg, even with the Flatpak app):

> Warning: Unknown input_id: -1 for input: surfacemap_x
Warning: Unknown input_id: -1 for input: surfacemap_x
GIMP-Message: Some fonts failed to load:
-/usr/share/gimp/2.0/fonts/
The program ‘gimp’ received an X Window System error.
This probably reflects a bug in the program.
The error was ‘BadWindow (invalid Window parameter)’.
(Details: serial 56812 error_code 3 request_code 18 minor_code 0)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)
(script-fu:2165): LibGimpBase-WARNING **: 00:41:26.516: script-fu: gimp_wire_read(): error

After I had updated to Clear Linux 33140 it stopped running all together! 

> GEGL operation missing!
GIMP requires the GEGL operation "gegl:alien-map". This operation cannot be found. Check your GEGL install and ensure it has been compiled with any dependencies required for GIMP.'

Now on 33170; still persists.

**Comment by iphands** [comment]
Still the case on 33180
> GIMP requires the GEGL operation "gegl:alien-map".

**Comment by iphands** [comment]
@isabelomakhanya 
FYI you can `$ flatpak install org.gimp.GIMP && flatpak run org.gimp.GIMP`
And unblock yourself here

**Comment by fingerblaster** [comment]
**I** just installed Clear Linux to check it out and can **confirm this issue.** It has **nothing to do with _"The X Window system"_**, though.  It is just that gegl library files are located in /usr/lib64/gegl-0.4  while The Gimp is looking for them at /usr/lib64/haswell/gegl-0.4.

As a dirty workaround (supposing you need Gimp ASAP!) you can log in as root and:
```
cd /usr/lib64/haswell/gegl-0.4
find ../../gegl-0.4/ -type f -exec ln -s {} . \;
```
**Please confirm!**

This would be easily solved by setting the appropriate path at _./configure --[options]; make_ time.

**Comment by iphands** [comment]
Yeah I just got by with `ln -s /usr/lib64/gegl-0.4 /usr/lib64/haswell`

**Comment by isabelomakhanya** [comment]
> cd /usr/lib64/haswell/gegl-0.4
> find ../../gegl-0.4/ -type f -exec ln -s {} . \;

Failed with:
`ln: failed to create symbolic link './grey2.json': File exists`

However, 
`export GEGL_PATH=$usr/lib64/gegl-0.4`
works if I run it before I run GIMP (workaround)

**Comment by fenrus75** [comment]
I just tried to convince our gegl package not insane... should be much
better in next release

**Comment by isabelomakhanya** [comment]
**Clear Linux** 33210 and `GIMP` now launches successfully! Thank you!!
