### ISSUE TITLE
kmail not showing mail message content

### ISSUE THREAD

**Issue by gzmorell** [clearlinux/distribution#1995]
kmail installed through kdesktop-kde-apps bundle (which include grantlee and grantlee-theme packages)

What happens: Mail message content is not displayed.
What is expected: Being able to read mail content.

Starting kmail from konsole shows the next messages:

    grantlee.template: "Plugin library 'grantlee_scriptabletags' not found."
    org.kde.pim.messageviewer: "Plugin library 'grantlee_scriptabletags' not found." . Searched in subdir mimetreeparser/themes/default in these locations ("/home/user/.local/share", "/home/user/.local/share/flatpak/exports/share", "/var/lib/flatpak/exports/share", "/usr/local/share", "/usr/share")

There are some bug reports with similar error:
https://bugzilla.redhat.com/show_bug.cgi?id=1807183

The issue seeems to be solved in grantlee 5.2 adding missing dependency (see bug report)
"+BuildRequires: pkgconfig(Qt5Qml)"

Using the library from "https://download-ib01.fedoraproject.org/pub/fedora/linux/updates/testing/32/Everything/x86_64/Packages/g/grantlee-qt5-5.2.0-5.fc32.x86_64.rpm" solves the problem.

ldd on the working library shows:

    libQt5Qml.so.5 => /usr/lib64/libQt5Qml.so.5 (0x00007f656a8e9000)
    Which is missing from clealinux version

**Comment by phmccarty** [comment]
Thanks for the report. I repackaged `grantlee` with latest autospec, and it picked up the missing dependency.

I'm not able to easily test it at the moment, but I will merge the change, since the runtime dependency on `libQt5Qml.so.5` was added. Should be available within a couple of days.

**Comment by gzmorell** [comment]
Hi, I have run autospec on grantlee and checked the new library.
I can confirm that the problem is solved with the new generated spec.

**Comment by phmccarty** [comment]
Thanks for confirming! The changes to clearlinux-pkgs/grantlee will sync out when the next official release occurs (`33200` or newer), so that behavior is normal.

**Comment by phmccarty** [comment]
Released in `33200`.
