### ISSUE TITLE
question: Does clearlinux follows GNU free distribution guidelines?

### ISSUE THREAD

**Issue by delata** [clearlinux/distribution#1996]
https://www.gnu.org/distros/free-system-distribution-guidelines.html

we really want clearlinux listed on free distribution list.

Thanks.

**Comment by thiagomacieira** [comment]
No.

At least two things which we don't do and won't do:
1. Use "GNU/" prefix
1. Remove non-free firmware

I haven't looked at the rest because at that point it's moot.

**Comment by delata** [comment]
i am sorry
