### ISSUE TITLE
auto-complete doesn't work after 'swupd'

### ISSUE THREAD

**Issue by ViZaVi70** [clearlinux/distribution#1997]
Since version 33190 auto-complete after 'swupd' doesn't work.
An error message is given - '_init_completion: command not found'
For example - 'swupd bun_init_completion: command not found'

**Comment by mdhorn** [comment]
Which shell are you using?
Works for me in both bash and zsh in both 33190 and latest (33210).

You can see if there are problems with `swupd diagnose` first, then maybe try `swupd repair` or `swupd repair --picky` and see if that helps.

**Comment by lebensterben** [comment]
This function is provided by bash-completion package, and it's installed by default.

**Comment by thiagomacieira** [comment]
That looks like a zsh message. You have to restart zsh after the completer scripts have changed.

Please confirm the problem goes away after you log in again.

**Comment by lebensterben** [comment]
>That looks like a zsh message. You have to restart zsh after the completer scripts have changed. ...

@thiagomacieira

I wrote this and this function is provided by bash-completion package, though it's not documented in bash's references.

https://github.com/clearlinux/swupd-client/blob/91173f50b28050b374fb4751b7b20d190a58c56c/swupd.bash#L29

**Comment by ViZaVi70** [comment]
Thanks to all.
I was helped by the installation of a shells bundle - `swupd bundle-add shells`
The strange thing is that before version 33190 everything worked without it.

**Comment by lebensterben** [comment]
>Thanks to all. ...

@ViZaVi70 Before that I didn't use this function.
But why was bash-completion not installed in the first place?

**Comment by ViZaVi70** [comment]
@lebensterben I use the server images for kvm and vmware. And so far only for study and tests. Apparently in finished images bash-completion is not installed.
