### ISSUE TITLE
request: Remove google-analytics from clearlinux.org

### ISSUE THREAD

**Issue by milrope** [clearlinux/distribution#1998]
use a free software alternative.

**Comment by milrope** [comment]
there is Fathom https://github.com/usefathom/fathom written in Go.

**Comment by thiagomacieira** [comment]
Thank you for the suggestion, but we'll pass.

**Comment by milrope** [comment]
That's not a good decision. You can't do this to us. Please stop.

**Comment by lebensterben** [comment]
>That's not a good decision. You can't do this to us. Please stop.

@milrope There's no need to get personal...

**Comment by milrope** [comment]
@lebensterben 
No, I am not getting personal.
They can't do this to us. They should understand the concerns.
Why we can't ditch Google's services? And other giant companies.
It makes me sad that most people don't care.

**Comment by fenrus75** [comment]
you're more than welcome to opt out of these things, I can recommend using the "Privacy Badger" plugin from the EFF.

**Comment by thiagomacieira** [comment]
> Why we can't ditch Google's services? And other giant companies.

You do realise you're posting that request on GitHub (owned by Microsoft) on the project of a Linux distribution by Intel, right?

Anyway, we wouldn't use a service that we thought had problems. Our corporate services tells us what services we can and cannot use. You may disagree with our conclusions and that's your prerogative. But that doesn't change what we concluded.

**Comment by SicLuceatLux** [comment]
> you're more than welcome to opt out of these things, I can recommend using the "Privacy Badger" plugin from the EFF.

Well this is not real opting out.. Opting out would be a settings switch provided by the website.

**Comment by milrope** [comment]
> Opting out would be a settings switch provided by the website.

that would be an option. like waht https://devdocs.io does

**Comment by SicLuceatLux** [comment]
> > Why we can't ditch Google's services? And other giant companies.
> 
> You do realise you're posting that request on GitHub (owned by Microsoft) on the project of a Linux distribution by Intel, right?
> 
> Anyway, we wouldn't use a service that we thought had problems. Our corporate services tells us what services we can and cannot use. You may disagree with our conclusions and that's your prerogative. But that doesn't change what we concluded.

This is unrelated. Github might belong to Microsoft. It might be an Intel product. But this does not imply that google has to be involved as well because of this circumstances. 
I'm not arguing against to use or not to use. That is of course yours respectively intels decision.
 
But it is simply the wrong argumentation to tackle privacy concerns. 
e.g. 
If I tell you a secret. You tell the secret to someone else. I get knowledge of it. And you are justifing the betrayal by: But you already told it to X and Y 

I'm sorry but I was expecting a more professional approach to this matter.
