### ISSUE TITLE
missing locales and locale-gen?

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#2]
I'm getting some errors/warnings regarding missing locales like:
smbd `dos charset 'CP850' unavailable - using ASCII`
cockpit `invalid or unusable locale: en_DE.UTF-8`

I guess this could be solved via locale-gen, but its missing from clearlinux?

**Comment by ahkok** [comment]
`en_DE` is pertinently incorrect though, there's no such thing as `german english`.

I'm not yet sure what needs to be done to be able to get more locales though, yet.

**Comment by fenrus75** [comment]
we also have the core bundle only have basic locales

and some other bundles adding the rest

we may need the "rest" to the samba bundles

**Comment by Andy2244** [comment]
Supposedly its fixed this way:
[fix](https://askubuntu.com/questions/710955/how-to-fix-en-de-utf-8-locales-warnings)

The problem is that from windows en_DE is valid, aka english language and german date/time format. The fix uses `locale-gen/localedef ` to generate and remap, which i cant find in clearlinux.

**Comment by iphutch** [comment]
@matthewrsj can you look into adding `localedef`

**Comment by matthewrsj** [comment]
`/usr/bin/localedef` is already provided by both the `c-basic` and `os-core-dev` bundles.

**Comment by phmccarty** [comment]
@matthewrsj is correct. The `localedef` program is provided by two bundles, as discovered by running `sudo swupd search /usr/bin/localedef`.

@Andy2244 There are many locales you *can* define, but of out the box, the only defined locale is `en_US.UTF-8`. I recommend to define the locales you need using `localedef`, and set them using `localectl set-locale ...`

**Comment by ahkok** [comment]
Is this something we need to include in a more logical bundle? like, `sysadmin-basic` ? Having it in `c-basic` and `os-core-dev` is missing the point I think

**Comment by phmccarty** [comment]
Also, for reference, the available locale data from glibc are stored in `/usr/share/i18n/locales/`. You'll see that `en_DE` is not present, so trying to `localedef -i en_DE ...` does not work.

However, you are always free to create locale data for `en_DE`, and then define a new locale using that data:

1. Copy a locale data file from `/usr/share/i18n/locales` to use as a starting point for your new locale. You can store it anywhere, e.g. `/usr/local/share/en_DE`.
2. Modify `/usr/local/share/en_DE` as needed.
3. Run `localedef -i /usr/local/share/en_DE -f UTF-8 en_DE.UTF-8`
4. Set `LANG=en_DE.UTF-8` in `/etc/locale.conf`
5. Log out / log back in

**Comment by Andy2244** [comment]
> Having it in c-basic and os-core-dev is missing the point I think
yeah that's really "strange"

I never had this particular problem on any of the "big" linux distro, so something seems off regarding clear-linux.

**Comment by matthewrsj** [comment]
@ahkok `localedef` is provided by `glibc`which is why it is in those particular bundles. Do we want to add `glibc` to `sysadmin-basic`? Seems like a weird fit. Maybe a new locale-focused bundle?

**Comment by bryteise** [comment]
Well it sits in glibc-locale currently (per the (spec)[https://github.com/clearlinux-pkgs/glibc/blob/master/glibc.spec]). It has a note mentioning spit on the section though. I'm pretty happy to add glibc-locale to sysadmin-basic. @phmccarty do you think opening an issue for localectl would make sense too?

**Comment by Andy2244** [comment]
Oki as noticed "en_DE.UTF-8" does not exist in the default linux world, strangely enough most distro's with a GUI setup, let me setup English language and German formats/time, similar to what Windows does.

So i just did `localedef -i en_DK -f UTF-8 en_DE.UTF-8`, since DK formats are similar and exists.

I'm closing this, since it seems linux in general deems it "strange" that this combination exists, while windows does not. So its not the fault of clear-linux, however "locale-gen/localedef" should exist in the same basic admin package, both handle advanced locales.

**Comment by phmccarty** [comment]
`localedef` is now present in the `sysadmin-basic` bundle, along with all of the locale data from /usr/share/i18n/.

**Comment by ahkok** [comment]
On 04/30/2018 03:12 PM, Matthew Johnson wrote:
> @ahkok <https://github.com/ahkok> |localedef| is provided by
> |glibc|which is why it is in those particular bundles. Do we want to add
> |glibc| to |sysadmin-basic|? Seems like a weird fit. Maybe a new
> locale-focused bundle?

It should probably be in `glibc-extras`.

localedef isn't a tool that *everyone* uses. But, it absolutely belongs 
in a "administrate my basic system" bundle. So perhaps go with the 
-extras and put that in sysadmin-basic.

Auke
