### ISSUE TITLE
Enable rbd module on ClearLinux KVM kernel

### ISSUE THREAD

**Issue by obedmr** [clearlinux/distribution#200]
when running Kubernetes in ClearLinux VMs, it's failing with a distributed storage (Ceph) setup because ClearLinux KVM kernel doesn't have the `rbd` kernel module enabled. Here are the Ceph distribution I'm using in my K8s cluster https://github.com/rook/rook/tree/master/cluster/examples/kubernetes/ceph 

The solution is basically the enablement of `rbd` kernel module. This will be useful for any user that wants to run [rook](https://github.com/rook/rook/) Ceph distribution on top of ClearLinux's VMs at any Cloud provider as Google Cloud, Amazon and Azure.

**Comment by miguelinux** [comment]
Added in https://github.com/clearlinux-pkgs/linux-kvm/commit/f7ea9c05b7f77258b2d5857092b47788b5729a63
