### ISSUE TITLE
33250 php cli is broken on fresh install

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2001]
Just started today. I'm on the rolling release.

```bash
php --version
```

```
PHP Fatal error:  Unable to start pcre module in Unknown on line 0
```

Tested  on fresh install inside vm:
```bash
sudo swupd  bundle-add php-basic
```
```bash
php -S localhost:4000
```
```
[Sat May 30 11:40:02 2020] PHP Fatal error:  Unable to start pcre module in Unknown on line 0
```
And the official docker image
```bash
sudo  docker pull clearlinux/php-fpm
```
```
Using default tag: latest
latest: Pulling from clearlinux/php-fpm
30c7c5b56447: Pull complete 
d53ad32a8386: Pull complete 
c3c523c5f37c: Pull complete 
0b5595f8c6a1: Pull complete 
14482b385674: Pull complete 
f0aeb79afdf4: Pull complete 
Digest: sha256:1dfe421990bbd12bc907ee0ee60dc93ac6c27007ff7bb70e83a36e6f700e31b6
Status: Downloaded newer image for clearlinux/php-fpm:latest
docker.io/clearlinux/php-fpm:latest
```
```bash
sudo docker run --name some-php-fpm clearlinux/php-fpm
```
```
[30-May-2020 15:48:06] NOTICE: PHP message: PHP Fatal error:  Unable to start pcre module in Unknown on line 0
```
@ahkok

**Comment by espositovitor** [comment]
I have the same problem.

Clear Linux OS - Version **33250**

PHP Fatal error:  Unable to start pcre module in Unknown on line 0

But my docker image with PHP still work.

Clear Linux OS - Version **31680**

PHP -v return:

PHP 7.4.5 (cli) (built: Apr 29 2020 22:25:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

**Comment by ahkok** [comment]
Confirmed. The fix has already been pushed, but, it will take until the next release before it'll work again. You can of course manually downgrade your system, I had 2 servers down myself for ~14h, so, I'm a bit disappointed we somehow didn't catch this too.

**Comment by inmanturbo** [comment]
> Confirmed. The fix has already been pushed, but, it will take until the next release before it'll work again. You can of course manually downgrade your system, I had 2 servers down myself for ~14h, so, I'm a bit disappointed we somehow didn't catch this too.

How far back did you have go, and  is it  necessary to rollback the entire os? I've tried to bring all the php bundles back as far as 33100 with no luck.

**Comment by inmanturbo** [comment]
Anyone on is 33250 and needs to get the patch, and your system isn't seeing an update, the fixed  that worked  for me was:
```bash
sudo swupd repair -m 33260 --picky  # --force  should also work here
```

```
  13 files did not match
    13 of 13 files were repaired
```
You can run 
```bash
sudo swupd diagnose -m 33260
```
first see what to expect from the repair.

**Comment by inmanturbo** [comment]
Updated  and fixed  https://cdn.download.clearlinux.org/update/33260/
