### ISSUE TITLE
Swupd hooks

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2002]
Is there a way to get swupd to execute custom scripts before or after a particular event or command, without forking or modifying swupd source code?

**Comment by ahkok** [comment]
You can use triggers - any systemd unit that is part of `update-triggers.target` will get executed after every update. This is what `swupd` uses itself to execute post-update jobs.

Take a look at `/usr/lib/systemd/system/update-triggers.target.wants/` and its contents.
