### ISSUE TITLE
Mesa

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2003]
May 27, 2020

Mesa 20.1.0 is released. This is a new development release. See the release notes for more information about this release.
https://www.mesa3d.org/relnotes/20.1.0.html

**Comment by romulasry** [comment]
https://docs.mesa3d.org/relnotes/20.1.1.html

**Comment by shtirlic** [comment]
Please update, if fixes issues with font subpixel rendereing on Intel IGP

**Comment by thiagomacieira** [comment]
We've been shipping 20.1 since May 8.

**Comment by shtirlic** [comment]
Nope, looks like https://github.com/clearlinux-pkgs/mesa was updated in May 8 and it's far from release date Mesa 20.1.0 Release Notes / 2020-05-27 and Mesa 20.1.1 Release Notes / 2020-06-10
Please update to 20.1.1, current clear linux mesa is unusable in latest intel graphics.

**Comment by lebensterben** [comment]
>Nope, looks like https://github.com/clearlinux-pkgs/mesa was updated in May 8 and it's far from release date Mesa 20.1.0 Release Notes / 2020-05-27 and Mesa 20.1.1 Release Notes / 2020-06-10 ...

@shtirlic Do you see this?

https://github.com/clearlinux-pkgs/mesa/releases/tag/20.1%2B415.g094c7646a3a-248

**Comment by romulasry** [comment]
Yeah but it says Mesa 20.1.0-devel not 20.1.1-devel, etc.

**Comment by shtirlic** [comment]
@lebensterben so what? I don't get it. It's tag from dev branch version of 20.1 from the May 8, the actual Mesa released in May 27, and latest 20.1 branch is 20.1.1 released in June 10.

**Comment by thiagomacieira** [comment]
Mesa was updated today.
