### ISSUE TITLE
Add a modified wslconfig to kernel for WSL2 support

### ISSUE THREAD

**Issue by WSLUser** [clearlinux/distribution#2004]
There's already https://github.com/clearlinux-pkgs/linux-hyperv for an optimized Linux kernel for Hyper-V. I'd like to see it work out of box for WSL2 by including the wslconfig found in https://github.com/microsoft/WSL2-Linux-Kernel. Eventually WSL2 repo could ingest the ClearLinux optimized kernel for use for all Linux distributions unless there's something configured specifically for Clear Linux distro inside the optimizations. If this is the case, then having a custom wslconfig included would help when using WSL2.

**Comment by bwarden** [comment]
That repo targets kernel 4.19.84, while Clear Linux is currently shipping 5.6.17. While we have a kernel-lts2018 bundle, it's not really intended for WSL2 support. Are there specific kernel options you're interested in?

**Comment by WSLUser** [comment]
Well they are shifting to stable. If you check the release page, they do show the 5.6 series. Basically all the perf, security,  etc. optimizations that Clear Linux does, i want to make available for the base WSL2 kernel. This would also benefit other distros. I did send a PR with the Hyper-V optimized config but it would rely on the kernel itself being changed to the Hyper-v kernel. I chose that one as WSL2 is a lightweight version of Hyper-v, so it uses a subset of the Hyper-v features in the backend

**Comment by bwarden** [comment]
Linking your PR for reference:
https://github.com/microsoft/WSL2-Linux-Kernel/pull/115

**Comment by WSLUser** [comment]
Any support from you or the Clear Linux team would be great in getting the config changes made. Also feel free to let me know if some options are unable to be used together. I'm not a kernel dev and I'm unable to test due to the painful process in attempting to compile the kernel. It would be nice if there was some sort of bash script you could just run through to compile layered configuration kernels.

**Comment by WSLUser** [comment]
They now support 5.4x LTS. I don't think they're going full stable. There was a bunch of stuff I had to strip out that are N/A for WSL2 and even some stuff that shouldn't be enabled for Hyper-V either.
