### ISSUE TITLE
python 3.8.3 seg fault with azure-identity

### ISSUE THREAD

**Issue by davegaulke** [clearlinux/distribution#2005]
I get this seg fault when running python on a bare metal install of Clear Linux 33260.  It behaves properly when running in the docker image clearlinux/python.

To reproduce:

- swupd bundle-add azure-cli
- pip install azure-identity==1.4.0b3
- pip install azure-keyvault-secrets
- run the python code below and it will produce the segmentation fault

Note you do not need to login to an azure account to reproduce this.

```
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential

KVUri = 'https://foobar.vault.azure.net/'
credential = DefaultAzureCredential()
client = SecretClient(vault_url=KVUri, credential=credential)
client.get_secret('abc')
```

**Comment by ahkok** [comment]
Can you include the output of the segfault, or a gdb backtrace?

**Comment by davegaulke** [comment]
[gdb.log](https://github.com/clearlinux/distribution/files/4719494/gdb.log)

**Comment by ahkok** [comment]
Most likely an upstream bug in one of the azure modules - have you considered reporting these to the upstream project?

**Comment by davegaulke** [comment]
Yes, I reported to azure python, but it could not be reproduced on ubuntu/python 3.8.3, and I could not reproduce on clearlinux/python container, so figured it was something to do with native python on Clear Linux.

**Comment by davegaulke** [comment]
Further investigation has led me to believe the issue is triggered whenever libsecret is installed, so not a Clear Linux issue.

**Comment by ahkok** [comment]
We're going to pull in these python bits ourselves and take a look at it as well.
