### ISSUE TITLE
OpenShot-v2.5.1-x86_64.AppImage do not work under Centos-8.1

### ISSUE THREAD

**Issue by suroy2005** [clearlinux/distribution#2012]
OS: Centos-8.1
./OpenShot-v2.5.1-x86_64.AppImage
produces the following error
/tmp/.mount_nAKMfv/usr/bin/openshot-qt: Relink `/tmp/.mount_nAKMfv/usr/bin/libQt5Core.so.5' with `/lib64/librt.so.1' for IFUNC symbol `clock_gettime'
Segmentation fault (core dumped)

**Comment by bwarden** [comment]
I'm not sure this has anything to do with Clear Linux, so it might be better to report this here:
https://github.com/OpenShot/openshot-qt/issues
