### ISSUE TITLE
Yandex-browser

### ISSUE THREAD

**Issue by oleg-medovikov** [clearlinux/distribution#2014]
Official package name: Yandex-browser

License (must be an OSI approved Open Source license): Freeware

Download URL of latest release: https://repo.yandex.ru/yandex-browser/rpm/beta/x86_64/

Latest release date (must be recent): 29-May-2020 12:06

Description:  is a freeware web browser developed by the Russian web search corporation Yandex that uses the Blink web browser engine and is based on the Chromium open source project. The browser checks webpage security with the Yandex security system and checks downloaded files with Kaspersky anti-virus. The browser also uses Opera Software's Turbo technology to speed web browsing on slow connections.

**Comment by ahkok** [comment]
Outside of scope - will not consider.
