### ISSUE TITLE
system log flooded by message "g_interface_info_get_n_properties: assertion 'GI_IS_INTERFACE_INFO (info)' failed"

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#202]
**Describe the bug**
The system journal is being continuously flooded by gnome-shell error messages that read:
g_interface_info_get_n_properties: assertion 'GI_IS_INTERFACE_INFO (info)' failed

**Environment (please complete the following information):**
 - Clear Linux OS version: 25070
 - Bundles: R-basic R-datasets R-extras bootloader c-basic containers-basic cryptography darktable desktop desktop-apps desktop-apps-extras desktop-assets desktop-autostart desktop-dev desktop-gnomelibs desktop-kde-apps desktop-kde-libs desktop-locales dev-utils dev-utils-dev editors emacs ethtool gimp git go-basic go-basic-dev iproute2 joe kernel-container kernel-native kernel-pk koji kvm-host libX11client mail-utils mail-utils-dev mixer network-basic network-basic-dev openssh-server openssl os-clr-on-clr os-core os-core-dev os-core-update os-core-update-dev os-core-update-index os-installer p11-kit package-utils perl-basic perl-basic-dev python-basic python-basic-dev python2-basic python3-basic qt-basic storage-utils storage-utils-dev sudo sysadmin-basic sysadmin-basic-dev telemetrics thunderbird vim vlc web-server-basic which wpa_supplicant xemacs xz

**Additional context**
I found the same bug reported directly to gnome-shell:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/545

**Comment by ahkok** [comment]
Confirmed.

**Comment by ahkok** [comment]
@mrkz @AthenasJimenez  This is pretty bad.

**Comment by mrkz** [comment]
yep, this is an [upstream bug](https://gitlab.gnome.org/GNOME/gjs/issues/199#note_316678)

**Comment by mrkz** [comment]
Fixed for release >= 25170

**Comment by ahkok** [comment]
Note: you need to log out and log back in for the fix to be active.
