### ISSUE TITLE
X11 applications not working under Wayland with AMD GPU since 32770

### ISSUE THREAD

**Issue by nodanero** [clearlinux/distribution#2026]
Running a Gnome Wayland session makes applications needing X11 not show. Same applications works under a Gnome X11 session.

Steps
- Login in a Gnome Wayland session
- Execute Terminal: GDK_BACKEND=x11 gedit

Outcome
- The window does not appear
- A rectangle is visible from Gnome overview when mouse-over but there is no content (clear space)

Expected outcome
- Gedit window should appear

Hardware
AMD Radeon Vega 64

Clear Linux
```
cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=33390
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=33390
```

Booted Live CD 33420 and has the same issue.
Booted Live CD 33420 with Virt-Manager and the issue does not happen.

I have tested several Live CDs and this issue starts happening with 32770. Version 32760 still works.

**Comment by romulasry** [comment]
All I get is cannot open display :0

**Comment by nodanero** [comment]
I just updated the command. I think it should be lower case "x11"

**Comment by romulasry** [comment]
Same issue with Firefox. Jujst tested.

**Comment by romulasry** [comment]
Nighly Firefox doesn't run either. Why isn't it running it under Wayland by default?

**Comment by nodanero** [comment]
Are you using an AMD GPU?

**Comment by romulasry** [comment]
Yes. AMD rx 480.

**Comment by nodanero** [comment]
This is again working since 33580.

Do we know what was the root cause?

**Comment by nodanero** [comment]
No reply from maintainers.
