### ISSUE TITLE
Unauthorized changes were made to 'secure boot' firmware/UEFI?

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2027]
UEFI bug?

**Comment by ahkok** [comment]
What version (kernel + clearlinux) are you using? We don't support secure boot right now, did you manually upload your own keys?

**Comment by romulasry** [comment]
The latest iso as of today. How do I upload my own keys?

**Comment by ahkok** [comment]
Are you trying to install for the first time? You have to disable secure boot in the BIOS settings first.

**Comment by romulasry** [comment]
I don't have that option in my UEFI.

**Comment by ahkok** [comment]
Can you answer the other part of the question, too? -> "Are you trying to install for the first time?"

**Comment by ahkok** [comment]
As in, on this particular system (first time).

**Comment by romulasry** [comment]
Fixed by changing to "Other OS"
