### ISSUE TITLE
Gnome update to 3.36.4

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2029]

**Comment by romulasry** [comment]
https://download.gnome.org/sources/gnome-desktop/3.36/LATEST-IS-3.36.3.1

**Comment by romulasry** [comment]
Wait until they make a branch with this nice 4K Intel performance boost: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1324#note_846799

**Comment by romulasry** [comment]
https://download.gnome.org/sources/gnome-desktop/3.36/LATEST-IS-3.36.4

**Comment by paulcarroty** [comment]
[GNOME 3.36.4 Released With Faster Mutter Fix Back-Ported
](https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.36.4-Released)

**Comment by paulcarroty** [comment]
upcoming in v33490, you can close this issue now @romulasry
