### ISSUE TITLE
kubernetes: unused control plane binaries 

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#203]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
kubernetes unnecessarily installs kube-apiserver, kube-scheduler, kube-controller-manager, kube-proxy binaries and the corresponding *.service files. They're not needed in the image by default as the cluster setup procedure (e.g., with kubeadm) pulls them in container images. 

**Describe alternatives you've considered**
The proposal is they're not installed in the image (at the very least they should be in their own package and/or bundle that is targeted for "master node" only. they're not needed in cluster's "worker nodes")

**Additional context**
N/A

**Comment by bryteise** [comment]
So the cloud-native-basic bundle is where the files currently live and we just have a single bundle that isn't master or worker node specific. Looking at the [bundle definition](https://github.com/clearlinux/clr-bundles/blob/master/bundles/cloud-native-basic) I think the only thing that would distinguish a worker node from a master are things inside the k8s package and so we'd need to poke the [spec](https://github.com/clearlinux-pkgs/kubernetes/blob/master/kubernetes.spec) file and move the service files and binaries to the -extras subpackage and make a new client bundle. Does that sound like what you would have in mind?

**Comment by AntonioMeireles** [comment]
@bryteise, there are a bunch of very different, separated, but very interlaced issues here at stake, that range from high level current `swupd` design issues to practical - i mean in the real world - deployment ones. 

they were all already referenced mostly [here](https://clearlinux.slack.com/archives/CCSERUURK/p1536787867000100) where i pasted chat with @fenrus75 on IRC and i'm re-pasting them again bellow, for context ...

> [15:00:28] arjan_work    peeks in
> [15:10:23]  <AntonioMeireles>    arjan_work : hi! assuming a pundle/bundle self-contained (i.e. runtime deps  either  filled by or statically built) would be too much to ask for the ability to pin it in swupd ?... (allow it to no be updated on "swupd update" but assymetrically at a later moment ?) . (have a great weekend too!) 
> [15:10:55]  <AntonioMeireles>    s/filled by/filled by os-core/
> [15:11:32]  <arjan_work>    pinning we cannot do
> [15:11:45]  <arjan_work>    because we allow overlap between bundles
> [15:11:52]  <arjan_work>    and proving that is... very hard.
> [15:12:00]  <arjan_work>    what do you want to achieve by pinning?
> [15:12:11]  <arjan_work>    (really want to understand the use case)
> [15:12:17]  <arjan_work>    is it kernel, or something else
> [15:12:24]  <arjan_work>    (because pinning kernels we can do)
> [15:12:39]  <arjan_work>    well not right now, but architecturally
> [15:14:30]  <arjan_work>    AntonioMeireles: I'd like to understand more... to figure out how
> [15:14:39]  <AntonioMeireles>    use case - kubernetes - specially just two blobs... kubeadm and kubectl. no one in is sane mind use as is pkgd k8s for anything that ressembles production. works but updating is messy. if one wwants to stick as much as possible to in-distro blobs ... workfloow is ... fetch kubeadm ... run it and then one node a time - drain it - update kubectl and move on ...  
> [15:15:31]  <AntonioMeireles>    so both kubeadm and specially kubelet (not kubectl sorry) would be handy to be able to be installable assymetrically
> [15:15:38]  <arjan_work>    ok so you want really a difference between "active kutbectl" and "distro installe kubectl"
> [15:15:41]  <arjan_work>    and chose when you transition
> [15:15:46]  <AntonioMeireles>    right
> [15:16:12]  <arjan_work>    extrapolate thinking would say "similar to kernel" in a way
> [15:16:13]  <AntonioMeireles>    (i may be on grass - but imho this is a reasonable use case ) 
> [15:16:16]  <arjan_work>    meaning
> [15:16:28]  <arjan_work>    oh it's totally reasonable
> [15:16:30]  <arjan_work>    not arguing that
> [15:16:35]  <arjan_work>    just thinking out loud
> [15:16:37]  <arjan_work>    so
> [15:16:44]  <arjan_work>    for kernel, we have a "distro provided" and "active"
> [15:16:46]  <arjan_work>    and they're different
> [15:16:52]  <arjan_work>    and clr-boot-manager manages the difference
> [15:17:08]  <arjan_work>    for kernel you need to reboot to switch (duh)
> [15:17:23]  <arjan_work>    but I can imagine a solution along similar lines
> [15:18:39]  <arjan_work>    I think in our universe that's a more likely path to solution than "pinning" a bundle
> [15:18:53]  <AntonioMeireles>    😊 i'm using CL in production (HCI - k8s/rook/...) and k8s is only thing i have to cheat 😊 (that's why i mantain the vagrant stuff to simulate on the cheap 😊 ) 
> [15:19:31]  <arjan_work>    thinking further
> [15:19:37]  <arjan_work>    lets say there is /var/lib/k8s/bin
> [15:19:48]  <arjan_work>    that, if exists, has your active kubeadm and kubelet
> [15:20:05]  <arjan_work>    that way we can update the OS provided ones at will
> [15:20:30]  <arjan_work>    and then there's some script/tool/whatever that managing transitioning the /var/lib/k8s/bin set to the latest OS provided
> [15:20:34]  <arjan_work>    would something like that work
> [15:21:06]  <AntonioMeireles>    yes.. assuming all manageble at OS level, sure    
> [15:21:26]  <arjan_work>    we need a bunch of glue, but not too much, to make this work I think
> [15:21:45]  <arjan_work>    the interesting thing will be hte script that updates
> (...)
> [15:28:22]  <AntonioMeireles>    ok. that's enough on my side for yet another raid - later! and once again thnxs!!!! 

... so besides besides teaching `swupd` on how to do asymmetric updates for some stuff what we need packaging wise is just ...
- ship `kubectl`, `kubeadm`, and `kubelet{,.service} as individual pundles
- ship   `kube-{apiserver,scheduler,controller-manager}` in a bundle pkg and `kube-proxy` in another.
and that's it. i strongly suspect than in the real world people will only care about  `kubectl`, `kubeadm`, and `kubelet{,.service} ones, as i do ;-) ... 

and then you just get a world class base OS to deploy k8s :-)

**Comment by mythi** [comment]
@AntonioMeireles thanks for the feedback. what problems/challenges you see with the current single bundle? AFAICT, the ```kubeadm upgrade``` workflow should work with the single bundle too (we need to verify and document the steps with ```swupd```).

@bryteise 
>  poke the spec file and move the service files and binaries to the -extras subpackage and make a new client bundle. 

For starters I only had the first part in mind. Based on what I've heard, it's recommended these parts are used via containers.

**Comment by AntonioMeireles** [comment]
@mythi 

AFAIK canonical k8s upgrade path should be ... 
a)  bump `kubeadm`
b) `kubeadm upgrade ...`
c)  for each node, one a time, drain it,  then update  kubelet / kubectl - start it - and rejoin cluster ...

currently you have to update kubelet before having control plane (which are containers) updated which is ... complicated

**Comment by mythi** [comment]
Let me double check a). This kubeadm [doc](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11/) implies you could use "old version" with ```kubeadm upgrade```. kubelet's are guaranteed to work with API server with " v+1" ("For example, kubelets running 1.7.0 should be fully compatible with a 1.8.0 API server, but not vice versa.")

**Comment by AntonioMeireles** [comment]
@mythi, 

you're right, to an extent ... IMHO upstream is being too optimistic. it's not exactly the first time that a previous kubeadm rev had deep issues upgrading to the next k8s one... (but not the reverse)... i'm just suggesting that there should be provided hooks for those who _really_ want to play safe :-)

**Comment by fenrus75** [comment]
so lets get more specific/practical

right now we have one kubernetes main package

it sounds the first thing we need to do is clone that into a few different
main packages with their own independent tarball
for which we can then tailor the content of the package specific for a
purpose

that allows us (and our downstreams) to independently control versions


then we also need to do something like we do for kernel, where to
"activate" a new version a script runs

**Comment by bryteise** [comment]
@fenrus75 would you want to do more than split out content into extras as a first step?

I'm really not sure how activation would go because in theory you'd need to manage all the package's content including systemd units (our only saving point here is that it doesn't have dynmaic libraries it uses otherwise this is a complete nightmare). It'd almost make more sense if swupd installed this content elsewhere and then a script moved into /.

**Comment by mythi** [comment]
@kad FYI

**Comment by kad** [comment]
kubeadm deprecation policy should make sure that kubeadm version 1.X is compatible to deploy/join versions of 1.X-1. If we are going to ship k8s setup which is dependant on kubeadm, I don't see reason why at all other components like api-server or kube-proxy should be shipped.

**Comment by mythi** [comment]
@kad the open was whether kubeadm v1.X guarantees ```kubeadm upgrade``` to v1.X+1

**Comment by bryteise** [comment]
@AntonioMeireles I'm wondering if it is enough for us to have tests for validating the v1.X to v1.X+1 upgrade is happy and just not release v1.X+1 until it is?

**Comment by AntonioMeireles** [comment]
@bryteise 

whatever you feel reasonable... use cases evolve over time... things won't turn round / fully polished in a single iteration anyway :-) 

(&& again thanks for your patience)

**Comment by ahkok** [comment]
On 09/19/2018 10:24 PM, Mikko Ylinen wrote:
> If we're able to independently control version, we can update |kubeadm|
> in one build and the rest in another coming after the |kubeadm| update.
> The former is possible by |swupd update -m <kubeadm-update-build>|, right?.

No, because, users are not forced to take each update individually, and
therefore could miss the "in between update".

Ideally, there is a full conversion path long after the update happens
on the server. If it can't be automated, it may be worth providing a
`motd` snipplet to indicate the manual actions needed to correct the
situation by the end user, by, for instance, running a script or command.

Cheers,

Auke

**Comment by bryteise** [comment]
Looking at the actual implementation for the requested binary splits

> ship kubectl, kubeadm, and kubelet{,.service} as individual pundles
> ship kube-{apiserver,scheduler,controller-manager} in a bundle pkg and kube-proxy in another.

I see this as 5 packages for what are now -bin and -config subpackages with needing to sort documentation bits into their correct locations (thankfully no config or lib). This doesn't align well with autospec and would require making kubernetes a manual package. I'm hesitant to go that route without thinking a little more on the needs here.

@AntonioMeireles I think I'm probably just shaky on how the migration needs to work as I haven't done it. If the kube-* binaries and service files are in their own bundle and everything else is where it is now, where do we run into problems?

**Comment by kad** [comment]
> @kad the open was whether kubeadm v1.X guarantees kubeadm upgrade to v1.X+1

No. You first need to upgrade kubeadm to new minor release, migrate control plane, then update kubelet and then migrate rest of the nodes.

**Comment by mythi** [comment]
@kad thanks, I guess I slightly misread the documentation. This confirms point a) @AntonioMeireles mentioned earlier. 

Currently the failure is if all kube* updates are ```swupd```'d at the same time. To fix it, I can only think of the idea I had about staged update or alternatively asking/guiding users to download the updated kubeadm binary from the kubernetes release page prior to doing ```swupd update``` to update kubelet/kubectl.

If I get the activation idea correct, we'd have old and new kubelet installed at the same time and the new is activated after ```kubeadm upgrade``` is run.

**Comment by mythi** [comment]
> No, because, users are not forced to take each update individually, and therefore could miss the "in between update".

Based on some of the talks I had today, I'm taking back my idea. You're totally right. In fact these missing "in between updates" are a risk even with traditional mechanism where the package repos update all the kube* components (e.g., ```apt-get update && apt-get upgrade``` would potentially break the cluster with the ```kubeadm``` flows.)

**Comment by AntonioMeireles** [comment]
@kad, 

FWIW, there 's still something that with current machinery isn't afaik workaroundable - (with OS provided packaging so far) ...  Let's say CL upstream decides to bump kubernetes stack but for whatever reason one isn't ready _yet_  to consume it ... You're absolutely right that  if `kubelet` isn't restarted old one would still be consumed but... what if, one wants to consume another critical change ? (say a critical kernel security issue). on next reboot - like it or not - _next_ `kubelet` will be consumed ...

**Comment by kad** [comment]
For that scenario, I'd copy here thing that I said @mythi in our offline conversation: I would suggest not to use OS binaries at all. Use the CoreOS part of documentation of Kubeadm to have tight control on all k8s components and manage them outside of OS packaging control.

**Comment by mythi** [comment]
How about we:

1) drop (or move to a separate package) the unused control plane binaries (this issue)
2) move ```kubeadm``` to it's own repo and package and create a pundle for it
3) implement a post-update script for cloud-native-basic bundle that masks ```kubelet.service``` if a minor version change is detected and adds a motd snippet about it.

**Comment by AntonioMeireles** [comment]
@kad, @mythi 

AFAICT regardless of k8s there is an underlying high order issue here - **is there or not *value*, per se, in allowing some sets / classes of packages**, other than the `kernel-*`, **to be pinned and unpinned at will** ?  IMHO, in the real _non theoretical/perfect world_, there is, and a lot.  

k8s deployment and maintenance is just a very visible/mainstream use case where this would be very handy.  Of course, one could not use OS binaries at all (and that is what i'm doing right now as it is the _only_ reasonable way to get things sane) but IMHO there's a very real and seductive use case to have *everything* and i really mean *everything* that isn 't going to end *PODable* to be OS provided/signed... (auditing, compliance, etc)

**Comment by mythi** [comment]
@bryteise @ahkok any feedback to my proposal above?

**Comment by ahkok** [comment]
@mythi I barely understand the complexity, so, I can only follow your logic and assume that's reasonable here....

**Comment by bryteise** [comment]
@AntonioMeireles So in this case would a relatively simplistic end user copies binaries to /usr/local/bin and uses those and references those in /etc service files be an approximation of being able to pin user defined content. Obviously this only really works if the parts in question aren't needing other particular versions of system components.

@mythi I'm okay with dropping unused components from the package (your first point). The other two I'm less inclined to go with as the potential complexity for such scripts to work with the rest of the system in an organized way is quite high. Things like swupd going backwards, managing state of what happens over a revert of the package after an update to the system are not going to behave well.

**Comment by AntonioMeireles** [comment]
@bryteise 

ideally we would come with a clean, scalable design built-in in **swupd** so that it could be smoothly applied to other similar use cases. 

So what about (at high altitude) ? : 
- for pinnable packages blobs are shipped versioned - say foo-${version}
- a `pkgName-pinned` (or whatever) file is created automagically by **swupd**
- if pkg wasn't already installed before (another version)  `pkgName-active` contains `${version}` **and** all blobs are symlinked to unsuffixed ones (foo -> foo-${version})
- if pkg is already installed **swupd** would just pop a warning telling user that albeit it was being installed previous rev was still being in use ... 
- a tool similar in concept to **clr-boot-manager** would exist (or one could add more options to **swupd**) to manage active version / recreate symlinks  / cleanup older versions ...

All the best, 

António

**Comment by bryteise** [comment]
@AntonioMeireles I think the methodology Clear needs to adopt (for this and other components that support multiple versions at the same time) is pretty similar to what you've laid out:

* Binaries will need to be versioned
* Libraries are thankfully already versioned (ignoring badly versioned libraries which would cause issues for now)
* Man pages need to be versioned
* Support files will need to be versioned (usually by having the directory containing them be pkg-ver named as opposed to just pkg named today)

Of course the problem with this is that it means that content can still be lost due to an update removing a no longer supported version. Thoughts on this method? @mythi ?

**Comment by shrmrf** [comment]
But, if you consider having the option of a package manager like `nix` package manager installable globally via `swupd`, people who want fine-grained control over their binaries can choose to use that and it won't burden the clearlinux team with keeping versions too much and they can keep on maintaining the latest and greatest. (now the validity of this theory has to be tested)

**Comment by bryteise** [comment]
@shrmrf I've known about nix for awhile but I haven't really used it. Could you explain to me how nix is namespacing the systemd unit files to make that work (similar for udev and other things that there being only being one init system make it hard to work around)?

**Comment by shrmrf** [comment]
@bryteise I'm not a `nix` expert either unfortunately but everything that you install using `nix-env` is stored inside the `/nix` folder that gets created at install-time. `nix` uses symlinks for every package e.g.:

```console
clear@clearlinux ~ $ ls -l $(which cargo)
lrwxrwxrwx 1 clear clear 67 Jan  1  1970 /home/clear/.nix-profile/bin/cargo -> /nix/store/fa0vf72rk63srmnkas168rdwgni8w0yx-rustup-1.13.0/bin/cargo
```
I don't think `systemd` plays well with `nix` since it never touches global state. So it won't be able to manage everything especially in a foreign distribution like Ubuntu or Clear. But it still is usable for tools like `ansible`, `python` dev environments, `docker-compose` (but _not_ `docker`, or anything managed by `systemd` perhaps)

**Comment by AntonioMeireles** [comment]
@bryteise 

Hi again, and sorry lag in reply ... some notes inline bellow 

> @AntonioMeireles I think the methodology Clear needs to adopt (for this and other components that support multiple versions at the same time) is pretty similar to what you've laid out:
> 
> * Binaries will need to be versioned
> * Libraries are thankfully already versioned (ignoring badly versioned libraries which would cause issues for now)
> * Man pages need to be versioned
> * Support files will need to be versioned (usually by having the directory containing them be pkg-ver named as opposed to just pkg named today)
> 

yes, expected 

> Of course the problem with this is that it means that content can still be lost due to an update removing a no longer supported version. Thoughts on this method? @mythi ?

at sight that's not, IMHO, desired behaviour at all. at any moment (bar packaging issues/bugs) what's in a CL setup should be (dependency/requirements wise) fully satisfied, right ? So assuming `swupd` knows what are the runtime deps/reqs of the pinned pundles that were left behind *if* when updating those would stop being satisfied `swupd` should just stop and pop out an error telling just that. 

for K8S in particular this isn't specially relevant as its' blobs are statically linked but if one wants to design this kind of functionality as a generic feature useable in other use cases AFAICT ensuring at any given moment in time the transitive closure of all deps/reqs of whatever is installed  is something  that needs to be considered...


all the best, 

António

**Comment by mythi** [comment]
@AntonioMeireles  is the expectation for pinning that ```swupd``` would still continue managing the pinned [p|b]undles? If not, dumping the pinned bundle ```/usr/*``` to corresponding ```/usr/local/*``` would already pin the version (some magic would need to happen to make, e.g., systemd to use the right paths).

**Comment by AntonioMeireles** [comment]
@mythi, 

yes, the ideal scenario would be to have all of the lifecycle to be manageable via `swupd`, together perhaps with new helper tools alike `clr-boot-manager`.

**Comment by mythi** [comment]
From my side, this is fixed. @iphutch @bryteise
