### ISSUE TITLE
Use Zstd compression for a nice speed up extraction

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2031]
"zstd and xz trade blows in their compression ratio. Recompressing all packages to zstd with our options yields a total ~0.8% increase in package size on all of our packages combined, but the decompression time for all packages saw a ~1300% speedup."

Source: https://www.archlinux.org/news/now-using-zstandard-instead-of-xz-for-package-compression/

**Comment by fenrus75** [comment]
We are already using zstd for this for at least a year

**Comment by romulasry** [comment]
> We are already using zstd for this for at least a year.

Link?

**Comment by ahkok** [comment]
Just test the download server:

```
~ $ curl -L -O https://download.clearlinux.org/update/33400/pack-sox-from-33350.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 58936  100 58936    0     0  59531      0 --:--:-- --:--:-- --:--:-- 59591
~ $ file pack-sox-from-33350.tar 
pack-sox-from-33350.tar: Zstandard compressed data (v0.8+), Dictionary ID: None
```

**Comment by ahkok** [comment]
It's probably been something like 6-12 months from what I can remember. The change is on the backend configuration, which isn't reflected in git. You can look at the `mixer-tools` logs to see when we enabled the capability to compress with `zstd`, though, which should be roughly the same time frame.

**Comment by romulasry** [comment]
Thanks.

**Comment by thiagomacieira** [comment]
We're all big fans of zstd here, so if you have more suggestions on where we could make use of it, we'll be glad to take a look.

For now, xz remains for long-term storage of huge files. For example, compressing tarballs of frequent releases, where you can get up to 20% improvement, make sense. But then there's also brotli, which compresses even more (and more slowly) than xz...
