### ISSUE TITLE
Kernel enhancement: Add strict confinement snap support

### ISSUE THREAD

**Issue by WSLUser** [clearlinux/distribution#2034]
Basically merge this in as .patch(s) https://github.com/microsoft/WSL2-Linux-Kernel/pull/60. 

This is not the same as requesting the snap package be added but rather enabling better support for those who are building snapd from source since the package is not available in a bundle.

Also I specifically would like to see this added to the Hyper-V kernel but is applicable to all variations.

**Comment by ahkok** [comment]
This would have to be merged upstream (not Microsoft's branch) for us to consider it.

**Comment by thiagomacieira** [comment]
Unless it's a security or important bug fix, or it's one of our performance tuning patches, we don't patch the kernel.

**Comment by WSLUser** [comment]
Strict confinement is the most secure mechanism used by snapd. By not providing support users will only have partial confinement. I would love to see the changes upstream but I think the patch is custom to Ubuntu and was shared for WSL2 consumption.

**Comment by thiagomacieira** [comment]
Then get Ubuntu folks to submit it upstream. We're not opening an exception for a "nice to have".
