### ISSUE TITLE
Removing firefox does not remove ~/firefox

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2035]
It should so that Steam doesn't use it as my default browser. I want Firefox (flatpak) as my default instead.

**Comment by lebensterben** [comment]
Are you able to change PATH for steam so it load flatpak packages first?

**Comment by romulasry** [comment]
> Are you able to change PATH for steam so it load flatpak packages first?

Shouldn't it use it when I installed firefox, also how do I do that?

**Comment by ahkok** [comment]
Currently this isn't possible (removing `~/firefox` when the bundle is uninstalled) and I think we will leave this as is - you'll manually need to remove this to avoid this problem.

**Comment by nobodyatandnothing** [comment]
this is standard behavior for software with files under the users home directory

**Comment by thiagomacieira** [comment]
Agreed. Standard behaviour.
