### ISSUE TITLE
Enable ext4 encryption

### ISSUE THREAD

**Issue by jannisch** [clearlinux/distribution#204]
**Is your feature request related to a problem? Please describe.**
ext4 supports file-level encryption for a while now and Clear already ships the e4crypt utility to use it.
However, `$ e4crypt add_key` just outputs _No salt values available_ so apparently the kernel isn't configured properly yet.
I like to use it in particular because it's very flexible and fast.

**Describe the solution you'd like**
Enable the necessary kernel configuration to use ext4 encryption (I guess CONFIG_EXT4_ENCRYPTION, maybe others).

**Describe alternatives you've considered**
In case you don't want to support ext4 encryption at all (which won't make much sense I guess) it would only be consequent to remove the `e4crypt` utility. 

**Additional context**
There's a nice presentation on the various benefits [in this pdf](kernsec.org/files/lss2014/Halcrow_EXT4_Encryption.pdf).
In order to use/test ext4 encryption it is necessary to enable the _encrypt_ flag for the filesystem with tune2fs first. Otherwise, `e4crypt` also outputs the message mentioned before.
On the Arch Wiki there's also a whole [guide](https://wiki.archlinux.org/index.php/Ext4#Using_file-based_encryption) how to use it.

**Comment by jannisch** [comment]
Great, thank you! I also just found `CONFIG_FS_ENCRYPTION` which could be necessary

**Comment by ahkok** [comment]
@jannisch If this still doesn't work with `4.18.9-635` or later, please reopen this bug.
