### ISSUE TITLE
Unable to boot on an encrypted HDD (LUKS) using latest kernel-native-current

### ISSUE THREAD

**Issue by antoniolopesgomes** [clearlinux/distribution#2040]
Not able to get trough the HDD encryption password prompt on boot. After entering the password I get:
```
device-mapper: table: 252:0 crypt: unknown target type.
```

### Clear linux version
33440

### Steps to reproduce
- Install Clear Linux, choosing a full disk encryption.
- Install bundle `kernel-native-current` (you should get latest kernel: 5.8.0)
- Reboot machine.
- Select latest kernel (5.8.0) on boot manager.
- LUKS password prompt is displayed, input password.

### Expected outcome
Boot should continue normally onto Gnome user selection screen.

**Comment by mdhorn** [comment]
A guess based on the kernel config for the 5.8.0 kernel would be one of these configs:

```
-CONFIG_MD_AUTODETECT=y
+# CONFIG_MD_AUTODETECT is not set
```
or
```
-CONFIG_DM_CRYPT=y
+CONFIG_DM_CRYPT=m
```
@miguelinux Do we know why these settings for the 5.8.0 kernel are different than out mainstream kernel config?

**Comment by miguelinux** [comment]
> @miguelinux Do we know why these settings for the 5.8.0 kernel are different than out mainstream kernel config?
> 

Yes it should be enabled, I'll fix it

**Comment by miguelinux** [comment]
already fixed
