### ISSUE TITLE
Add gmpy2 to python-basic

### ISSUE THREAD

**Issue by analytically** [clearlinux/distribution#2043]
For usage with gmpy2

**Comment by fenrus75** [comment]
we rather add gmpy2 to, say, python-extras

adding a -dev package to a bundle (especially one that is attempting to be
small like python-basic) means adding the whole compiler side of things as
well which is huge

**Comment by analytically** [comment]
Sounds good to me. I'm trying to add gmpy2 to my clearlinux/python image but need to add a huge bundle just go get mpfr-dev (mpfr.h).

**Comment by fenrus75** [comment]
compilers are never small.....

**Comment by analytically** [comment]
Thanks!
