### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by ajitjadhav28** [clearlinux/distribution#2054]
Official package name: vscode

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://update.code.visualstudio.com/1.47.0/linux-x64/stable

Latest release date (must be recent): June 2020

Description: Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and is available for Windows, macOS and Linux. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages (such as C++, C#, Java, Python, PHP, Go) and runtimes (such as .NET and Unity). Please Add it to Clear Linux bundles.

**Comment by romulasry** [comment]
https://github.com/microsoft/vscode/releases/tag/1.47.0

**Comment by lebensterben** [comment]
- VSCode source code is MIT but not MS VSCode. This is well explained by VSCode's FAQ. 
- This request is repetitive and it's well known that this won't be granted.

**Comment by nodanero** [comment]
Any reason to not use the Flatpack from Flathub?

MIT License
https://flathub.org/apps/details/com.visualstudio.code-oss

Microsoft build
https://flathub.org/apps/details/com.visualstudio.code

**Comment by lebensterben** [comment]
Flatpak package are sandboxed and may not find your toolchains properly.

VSCode has a binary release in tarball hiding on the official website but could be found via Google.

**Comment by SicLuceatLux** [comment]
As said by lebensterben - once you need some system commands as calling toolchains it might break. I have had a lot of issues getting plugins to run because of that fact. Sometimes you can hack it if you wrap some commands around the calls in the config but this is a lot of work and is not working always. So VSCodium or VSCode as flatpak is not really a good alternative

**Comment by WSLUser** [comment]
Try VSCodium if licensing is issue. Mostly the same but has a full build that disables "tracking" (even though you can turn telemetry off in normal VS Code, but some people are don't trust it even though it's in the source code).

**Comment by lebensterben** [comment]
>Try VSCodium if licensing is issue. Mostly the same but has a full build that disables "tracking" (even though you can turn telemetry off in normal VS Code, but some people don't trust it even though it's in the source code).

@WSLUser You must haven't tried to build VSCodium. It doesn't build.

**Comment by romanov** [comment]
The main reason because i'm giving up with Clear Linux is VSCode and C# .
Flatpack version can't find dotnet binaries (i've tried many options) and installing deb or rpm version is almost impossible.

**Comment by lebensterben** [comment]
@romanov 
VSCode has a binary release in tarball. Just extract and run.

**Comment by sala91** [comment]
It sure would be nice to have first class experience for it

**Comment by lebensterben** [comment]
@sala91 

https://github.com/clearlinux/distribution/issues/2054#issuecomment-657328139
