### ISSUE TITLE
Flatpak 1.8.2 update

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2057]
https://github.com/flatpak/flatpak/releases/tag/1.8.1

**Comment by romulasry** [comment]
https://github.com/flatpak/flatpak/releases/tag/1.8.2

**Comment by jfexart** [comment]
With this flatpak version we can test Google Chrome (beta)

**Comment by mdhorn** [comment]
Should also update flatpak-builder, xdg-desktop-portal, and xdg-desktop-portal-gtk

**Comment by phmccarty** [comment]
The `flatpak`, `flatpak-builder`, `xdg-desktop-portal`, and `xdg-desktop-portal-gtk` package were updated in release [33960](https://cdn.download.clearlinux.org/releases/33960/clear/RELEASENOTES-33940-to-33960).
