### ISSUE TITLE
Evince crashes when rotating one particular PDF

### ISSUE THREAD

**Issue by cphuntington97** [clearlinux/distribution#2059]
1. Download [this pizzeria menu](http://johnnyspizzeria.net/download/johnnyspizzeriamenu_july2020b.pdf).
2. Open in Evince ("Document Viewer")
3. Rotate

Evince will crash every time on four different systems of mine, including X11 and Wayland, AMD, Intel, and NVidia GPUs, on 32660, 33010, and 33490, while displaying either page of the PDF.

No crashes on Fedora or Ubuntu, and other PDF files I have tried rotate fine on Clear Linux.

I'm wondering if anyone else can reproduce this issue.

I'm including [the PDF file](https://github.com/clearlinux/distribution/files/4915870/johnnyspizzeriamenu_july2020b.pdf) in this bug report as well.

**Comment by joebonrichie** [comment]
Disable PGO in pixman to resolve. Hit the same issue in Solus.

**Comment by cphuntington97** [comment]
This has since been solved and can be closed.
