### ISSUE TITLE
Add Bundle: duplicity

### ISSUE THREAD

**Issue by zachselby** [clearlinux/distribution#2061]
Official package name: duplicity

License (must be an OSI approved Open Source license): [GPL-2.0](https://opensource.org/licenses/GPL-2.0)

Download URL of latest release: [https://launchpad.net/duplicity](https://launchpad.net/duplicity)

Latest release date (must be recent): 04-Jul-2020

Description: Duplicity backs up directories by producing encrypted tar-format volumes and uploading them to a remote or local file server. Because duplicity uses librsync, the incremental archives are space efficient and only record the parts of files that have changed since the last backup. Because duplicity uses GnuPG to encrypt and/or sign these archives, they will be safe from spying and/or modification by the server.

Similar utility restic is available in Clear as [bundle: restic](https://github.com/clearlinux/clr-bundles/blob/master/bundles/restic).

**Comment by thiagomacieira** [comment]
We also have borg-backup.

**Comment by zachselby** [comment]
@thiagomacieira Honestly, I was testing with restic bundle earlier, and I will meet my personal needs at present. I've just had more experience with duplicity on other distros, and know it's quite popular.

Closing this request since there's no rationale for adding duplicity, save for requests from others 😁

Thanks for the reply, and the great distribution!

**Comment by thiagomacieira** [comment]
My point wasn't that there's duplication. It was that we have other backup tools, so the precedent is there.
