### ISSUE TITLE
 - ERROR mismatch in DDB state pipe A plane 2 -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#2062]
**Describe the bug**
[    1.319705] [drm:verify_wm_state] *ERROR* mismatch in DDB state pipe A plane 2 (expected (442,884), found (0,0))

**To Reproduce**
Ubuntu 20.04 SOS
ACRN master branch ( HEAD: 6992d00e45e1ceaf984d461850d5ab73885b3971 )
32G RAM

lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              2
Core(s) per socket:              2
Socket(s):                       1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
Stepping:                        9
CPU MHz:                         3939.474
CPU max MHz:                     4000,0000
CPU min MHz:                     400,0000
BogoMIPS:                        7008.00
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        4 MiB
Vulnerability Itlb multihit:     Processor vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nop
                                 l xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor est tm2 ssse3 fma cx16 xtpr pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xs
                                 ave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdse
                                 ed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

lspci
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers (rev 03)
00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics 650 (rev 06)
00:08.0 System peripheral: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th/8th Gen Core Processor Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-LP Thermal subsystem (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI #1 (rev 21)
00:17.0 SATA controller: Intel Corporation Sunrise Point-LP SATA Controller [AHCI mode] (rev 21)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #1 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #6 (rev f1)
00:1c.7 PCI bridge: Intel Corporation Sunrise Point-LP PCI Express Root Port #8 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point LPC Controller/eSPI Controller (rev 21)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-LP PMC (rev 21)
00:1f.3 Audio device: Intel Corporation Sunrise Point-LP HD Audio (rev 21)
00:1f.4 SMBus: Intel Corporation Sunrise Point-LP SMBus (rev 21)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (4) I219-V (rev 21)
3a:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
3b:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5229 PCI Express Card Reader (rev 01)

NUC7i7BNH

Linux os1 4.19.128-109.iot-lts2018-sos #1 SMP PREEMPT Sat Jun 20 15:06:27 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-4.19.128-109.iot-lts2018-sos root=UUID=2262b75d-9b3f-4993-a0c5-083f4b061cfe ro quiet splash rootwait root=/dev/sda2 console=tty0 console=ttyS0,115200n8 cryptomgr.notests intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw loglevel=1 i915.enable_gvt=1 hvlog=2M@0x1FE00000 vt.handoff=7

**Comment by thiagomacieira** [comment]
> Ubuntu 20.04 SOS
> ACRN master branch ( HEAD: 6992d00e45e1ceaf984d461850d5ab73885b3971 )

That's not a Clear Linux bug. Please file this at https://github.com/projectacrn/acrn-hypervisor or at https://gitlab.freedesktop.org/drm/intel/issues

**Comment by vinibali** [comment]
Do you have the xserver-xorg-video-intel or xf86-video-intel package installed?
