### ISSUE TITLE
add dnssec support for dnsmasq

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#2064]
Official package name: dnsmaq

License (must be an OSI approved Open Source license): GPL-2

Download URL of latest release: http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.81.tar.xz

Latest release date (must be recent): 04/11/2020

Description: Please rebuild dnsmasq with support for DNSSEC

**Comment by bwarden** [comment]
https://github.com/clearlinux-pkgs/dnsmasq/commit/c2e8ed94f69ba54e9dde753b1315398f794d2481

**Comment by bwarden** [comment]
```
$ dnsmasq --version
Dnsmasq version 2.82  Copyright (c) 2000-2020 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-UBus no-i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify dumpfile
```
