### ISSUE TITLE
GNOME - Red Cross blocks GUI after click on "Show Applications"

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#2066]
![20200719_070945](https://user-images.githubusercontent.com/55597745/87867736-65495600-c990-11ea-9f1c-3e57bd148fab.jpg)

After a swupd update maybe a month ago I got a bug which draws a red cross on the top left corner whenever I click on the "Show Applications" button in GNOME to select an app to run. The red cross seems to also randomly appear, sometimes after hours. If I start an app from bash, like "gparted", the app runs fine. Also if I click on an app which is set as a favorite in the GNOME task bar, it runs fine. The bug is directly related to the "Show Applications" button.

The bug was introduced after a swupd update, I did not modify the system otherwise. Newer swupd update's did not fix the issue. Using Wayland or X11 does not matter, same bug. 

Once the red cross show up, any open windows cannot accept mouse input anymore. The system becomes useless to use and only a reboot make the red cross to go away.

**Comment by lebensterben** [comment]
What are the gnome extensions you're using?

**Comment by 0xA1B2** [comment]
Besides the various system extensions I use these ones:

CPU Power Manager
Dash to Panel
Remove Dropdown Arrows

**Comment by lebensterben** [comment]
You can start with disabling these extensions and restart the gnome-shell. If the problem disappeared, then these extensions are to be blamed.

**Comment by 0xA1B2** [comment]
Yep, thx for the hint. It was "Dash to Panel" ..
