### ISSUE TITLE
offlineimap bundle is missing binary

### ISSUE THREAD

**Issue by jrcresawn** [clearlinux/distribution#2067]
It appears that the offlineimap bundle is missing the binary. I am on Clear Linux version 33520. I ran this command to install offlineimap:

```
sudo swupd bundle-add offlineimap
```

To my surprise it appears there is no binary installed!

```
$ which offlineimap
which: no offlineimap in (/usr/bin/haswell:/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/3rd-party/bin)
```

**Comment by phmccarty** [comment]
The `offlineimap` bundle was [deprecated](https://github.com/clearlinux/clr-bundles/commit/8a44ed0f6e581fc1) back in October 2019. Until/unless the project ports its code to Python 3, I expect we cannot add offlineimap back to Clear.

**Comment by jrcresawn** [comment]
Should the bundle be removed?

**Comment by phmccarty** [comment]
It will be automatically removed once we the next format bump. The last format bump occurred in February, and I'm not sure when the next one is scheduled.

**Comment by jrcresawn** [comment]
Ok. Thanks for letting me know. I was a little confused by the presence of the package without the binary, but it makes sense to me now. Would you like me to close this issue?

**Comment by phmccarty** [comment]
Yeah, I agree it's confusing. Thankfully there aren't too many bundles in the Deprecated (or Pending-Delete) state at any given time, but at the present time, offlinemap happens to be one of the affected bundles.

Feel free to close it.
