### ISSUE TITLE
Enable the Netronome NFP driver by default

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#207]
**Is your feature request related to a problem? Please describe.**
The Netronome NFP network card driver is explicitly disabled in a kernel configuration. 

**Describe the solution you'd like**
Let's enable the nfp driver as a kernel module so cards such as Netronome NFP-4000 will be supported. You'll get a support for a wide variety of Netronome cards this way.

https://github.com/clearlinux-pkgs/linux/blob/master/config#L2276

**Describe alternatives you've considered**
There's no alternative ;)

**Additional context**
https://github.com/torvalds/linux/tree/master/drivers/net/ethernet/netronome/nfp

**Comment by fenrus75** [comment]
done
