### ISSUE TITLE
vboxadd-service wont start because we cant disable systemd-timesyncd via systemctl

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#2072]
Did install and prepare VBoxGuestAdditions-6.1.12, which worked fine
```
swupd bundle-add kernel-native-dkms
mkdir /media/cdrom
mount -t iso9660 /dev/sr0 /media/cdrom
/media/cdrom/VBoxLinuxAdditions.run
```
```
systemctl enable vboxadd
systemctl enable vboxadd-service
```

Yet after a reboot vboxadd-service wont start and digging deeper reveals that it conflicts with systemd-timesyncd, yet trying to disable systemd-timesyncd isn't possible.

Try disable NTP and systemd-timesyncd via:
```
timedatectl set-ntp false
systemctl stop systemd-timesyncd
systemctl disable systemd-timesyncd
```
yet after a reboot its enabled and running again.

The problem is that's its still in the `/usr/lib/systemd/system/sysinit.target.wants/`, so to actually disable it you need to manually delete the link `systemd-timesyncd-service`.

So after `rm /usr/lib/systemd/system/sysinit.target.wants/systemd-timesyncd.service` and a reboot, `vboxadd-service` starts now.
Check via `ps axuw | grep -i vbox`

Took me quite some time to figure this out and why `vboxadd-service` wont start.

PS: `Current OS version: 33540`

**Comment by lebensterben** [comment]
Try `systemctl mask` instead

**Comment by Andy2244** [comment]
> 
> 
> Try `systemctl mask` instead

Ah thanks, i missed this systemd option and yes it works via: `systemctl mask systemd-timesyncd`

Still i think this should also work via:
```
timedatectl set-ntp false
systemctl disable systemd-timesyncd
```

**Comment by lebensterben** [comment]
Possibly this is required by other services, so that "disable" alone won't work.

**Comment by Andy2244** [comment]
> Possibly this is required by other services, so that "disable" alone won't work.

Did a quick search, but cant find any other services that depend on systemd-timesyncd.service ?

**Comment by thiagomacieira** [comment]
Why is vbox incompatible with timesyncd?

**Comment by Andy2244** [comment]
> Why is vbox incompatible with timesyncd?

It sets the time via the host so the `vboxadd-service.service` file has this:
```
After=vboxadd.service 
Conflicts=shutdown.target systemd-timesyncd.service
```

**Comment by Andy2244** [comment]
closing this, since masking systemd-timesyncd works
