### ISSUE TITLE
bundle request: VirtualBox Guest Additions

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#2076]
Official package name: VirtualBox Guest Additions
https://www.virtualbox.org/manual/ch04.html

License: GPLv2

Download URL of latest release: https://download.virtualbox.org/virtualbox/6.1.12/VirtualBox-6.1.12a.tar.bz2
* _they are part of the VirtualBox base source_
* _additions are under_ `/src/VBox/Additions/`

* src+binary GuestAdditions only iso with install/dkms scripts
https://download.virtualbox.org/virtualbox/6.1.12/VBoxGuestAdditions_6.1.12.iso

Latest release date: 11-Jul-2020

Description:
> the Guest Additions are designed to be installed inside a virtual machine after the guest operating system has been installed. They consist of device drivers and system applications that optimize the guest operating system for better performance and usability.

Features:
> Mouse pointer integration
> Shared folders
> Better video support
> Seamless windows
> Generic host/guest communication channels
> Time synchronization
> Shared clipboard
> Automated logins

The Shared folders and Time synchronization guest feature, enable automouting support from the HOST via VM settings and correct time synchronization behavior for edge cases (host sleep/resumes).

There are two extra systemd services `vboxadd.service` and `vboxadd-service.service`, also guest user tools include the `VBoxService`, `VBoxControl` bins and mount helper `mount.vboxsf`.

**Comment by lebensterben** [comment]
The tricky part is VirtualBox is under dual license of GPL-2 and CCDL 1.0, and it's announced that they're not compatible.

Then you need to manually make sure the part of VBoxAdditions are under GPL-2....

**Comment by Andy2244** [comment]
Debian had/has it via: `apt-get install virtualbox-guest-utils`

I mainly try to solve #2077, without the need to use dkms and a custom "tainted" kernel image.

**Comment by lebensterben** [comment]
Whether other distro ships this doesn't matter.

https://github.com/clearlinux/autospec/blob/master/autospec/license_translations

CCDL is not here

**Comment by lebensterben** [comment]
The license must be in the SPDX licenses list:
https://spdx.org/licenses/

**Comment by Andy2244** [comment]
Just rechecked and this is explicitly stated under [Licensing_FAQ](https://www.virtualbox.org/wiki/Licensing_FAQ)

> What are “VirtualBox Guest Additions”? 
> 
> The “VirtualBox Guest Additions” are a set of software drivers and utilities that are shipped as a subset of the VirtualBox base package and that are installed inside a virtual machine for better performance and usability. Like the VirtualBox base package, the VirtualBox Guest Additions are licensed under the GPLv2.

So yes they are under normal GPLv2, like the base package. Only the "VirtualBox Extension Pack" is under “PUEL”, which is unrelated to the "VirtualBox Guest Additions".

**Comment by lebensterben** [comment]
This is NOT a correct statement.

From https://www.virtualbox.org/browser/vbox/trunk/COPYING.CDDL

> Some source files in the VirtualBox Open Source Edition (OSE) are
dual-licensed under both the GNU General Public License V2.0 (GPL2, see
the COPYING file) and the Common Development and Distribution License,
Version 1.0 (CDDL), as shown below. This applies only to source files
where this dual-licensing is explicitly worded in the file's header.

A quick search reveals many files under `/src/VBox/Additions` are licensed under both GPL-2 and CDDL.
For example, in https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Additions/common/VBoxGuest/VBoxGuest.cpp

```cpp
/*
* Copyright (C) 2007-2020 Oracle Corporation
*
* This file is part of VirtualBox Open Source Edition (OSE), as
* available from http://www.virtualbox.org. This file is free software;
* you can redistribute it and/or modify it under the terms of the GNU
* General Public License (GPL) as published by the Free Software
* Foundation, in version 2 as it comes in the "COPYING" file of the
* VirtualBox OSE distribution. VirtualBox OSE is distributed in the
* hope that it will be useful, but WITHOUT ANY WARRANTY of any kind.
*
* The contents of this file may alternatively be used under the terms
* of the Common Development and Distribution License Version 1.0
* (CDDL) only, as it comes in the "COPYING.CDDL" file of the
* VirtualBox OSE distribution, in which case the provisions of the
* CDDL are applicable instead of those of the GPL.
*
* You may elect to license modified versions of this file under the
* terms and conditions of either the GPL or the CDDL or both.
*/
```

Since CDDL is not legally compatible with GPL-2, the only option is to
> license modified versions of this file

Now the question is, how?

**Comment by Andy2244** [comment]
All files under `/src/VBox/Additions/linux` are just GPLv2, while only the shared files in `/src/VBox/Additions/common` have the extra CDDL as option. 
It clearly states "may alternatively be used", while the first part clearly states "This file is part of VirtualBox Open Source Edition".

I suspect that's because some code paths in the common files compile also to Windows/OS2/Solaris specific stuff.

**Comment by lebensterben** [comment]
But you cannot deny the fact that CDDL and GPL-2 are incompatible.
So although it's dual licensed, **that's not valid**.

So you have to strip the CDDL part.

**Comment by Andy2244** [comment]
> But you cannot deny the fact that CDDL and GPL-2 are incompatible.

Even this is not 100% clear, see recent ZFS and Ubuntu.

> So although it's dual licensed, **that's not valid**.

Going by [wiki](https://en.wikipedia.org/wiki/Common_Development_and_Distribution_License) thats not true:
> Files licensed under the CDDL can be combined with files licensed under other licenses, whether open source or proprietary.

> So you have to strip the CDDL part.
Why, all files in question either are pure GPLv2 or dual license?

**Comment by lebensterben** [comment]
See this https://www.gnu.org/licenses/license-list.html#CDDL

It's not compatible with GPL. Period.

**Comment by Andy2244** [comment]
> It's not compatible with GPL. Period.

Do i miss something?
All those cases are for mixing GPL and CDDL "only" files, not for files where you can choose to either use GPL or CDDL?

Lets not waste any more time on this, since the kernel's ClearLinux ships already have some of the modules built-in, vboxguest/vboxvideo/vboxsf ?

PS: Maybe someone from the ClearLinux team can resolve this.

**Comment by lebensterben** [comment]
> This is a free software license. It has a weak per-file copyleft (like version 1 of the Mozilla Public License) which makes it incompatible with the GNU GPL. This means a module covered by the GPL and a module covered by the CDDL cannot legally be linked together. We urge you not to use the CDDL for this reason.

There's no such thing as you can "choose to either use GPL or CDDL". This is not valid as I said before.

According to the Virtual Box's COPYING files, this project is mainly under GPL-2 but a few files are also dual-licensed under CDDL.

But also as I said before, since these two licenses are not compatible, this dual-licensing arrangement is invalid.

But since the copyright holder authorises users to "license modified versions ... under the terms and conditions of either the GPL or the CDDL or both", this means we can lawfully use a modified version under GPL.

Everything made in this comment is what I already said. Just read it.
