### ISSUE TITLE
libratbag is needed to make Piper work. 

### ISSUE THREAD

**Issue by Sscratchie** [clearlinux/distribution#2082]
Official package name:libratbag

License (must be an OSI approved Open Source license):Red Hat, Inc

Download URL of latest release:https://github.com/libratbag/libratbag

Latest release date (must be recent):May 18 2020

Description: libratbag is a service required by Piper to use multibutton mice. Piper is in the Clear distribution but doesn't work without libratbag.

**Comment by lebensterben** [comment]
>Official package name:libratbag ...

The license is MIT

**Comment by phmccarty** [comment]
libratbag is already a package in Clear.

`sudo swupd search-file libratbag` shows it is present in the `games` bundle.
