### ISSUE TITLE
Vim issue in Clear Linux version 33590

### ISSUE THREAD

**Issue by kjchmielewski** [clearlinux/distribution#2089]
**Severity:**  major
**System:** Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (HP ZBook 15 g6)
**Description:** vim reports errors to stderr when editing files, here's an example:

> $ vim user-setup.sh                                                                                                                                          
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim:
line  647:
E121: Undefined variable: mmtemplates#config#GetFt
line  686:
E121: Undefined variable: has
line  700:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[708]..function <SNR>36_GetGlobalSetting:
line    3:
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[726]..function <SNR>36_ApplyDefaultSetting:
line    1:
E121: Undefined variable: exists
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[729]..function <SNR>36_GetGlobalSetting:
line    3:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[730]..function <SNR>36_ApplyDefaultSetting:
line    1:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim:
line  745:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[753]..function <SNR>36_GetGlobalSetting:
line    3:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[754]..function <SNR>36_ApplyDefaultSetting:
line    1:
E121: Undefined variable: exists
Search for the newest version number failed.
Using this version (1.3).
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[2456]../home/k********c/.vim/autoload/mmtoolbox/tools.vim:
line  225:
E121: Undefined variable: exists
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim:
line 2456:
E121: Undefined variable: mmtoolbox#tools#NewToolbox
Error detected while processing /home/k********c/.vim/plugin/bash-support.vim[2466]..function <SNR>36_ToolMenu:
line    2:
E121: Undefined variable: has
Press ENTER or type command to continue

After pressing ENTER continues to work. 

**Steps to reproduce:** 1. install vim bundle  2. plugin https://github.com/WolfgangMehner/bash-support , 3. try to edit shell file.
**Workaround:** 
$ sudo swupd repair --bundles=vim --version=33570 --force
after downgrade works as before, without any errors.

**Additional info:**
After upgrade to 33580 or 33590 behavior repeats. 
I'm using this plugin for quite long time on many linux distributions (debian, centos, ubuntu) and never observed such behavior :-)

**Comment by lebensterben** [comment]
clearly this is not a CL issue.
You need to contact the author of the plugin.

**Comment by kjchmielewski** [comment]
Thanks, I will, closing this here.
