### ISSUE TITLE
DNF got error when install *.rpm package

### ISSUE THREAD

**Issue by namm2** [clearlinux/distribution#2097]
Hi, I'd like to install AMD Radeon pro driver for enablling OpenCL, but couldn't install it with `dnf`. Steps I did:
- Download RHEL/Centos 8.1 drivers package from amd.com
- Create dnf local repository
- `dnf install <package>`

but it got errors like:
```
Error: 
 Problem: conflicting requests
  - nothing provides /bin/sh needed by amdgpu-core-20.10-1101037.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```

I couldn't figure out the other way to install these packages. Any help is appreciated.

**Comment by thiagomacieira** [comment]
Clear Linux does not use `dnf`.
