### ISSUE TITLE
nginx-mainline-extras out of sync with nginx-mainline

### ISSUE THREAD

**Issue by ljmccarthy** [clearlinux/distribution#2099]
nginx-mainline is failing to start again as the extention modules in nginx-mainline-extras are out of date:

`nginx-mainline[220292]: 2020/08/16 12:54:42 [emerg] 220292#220292: module "/usr/lib64/nginx-mainline/ngx_http_fancyindex_module.so" version 1017009 instead of 1019002 in /etc/nginx-mainline/nginx.conf:2`

**Comment by phmccarty** [comment]
Thanks for the report. I have rebuilt all of the extension modules, and the fix should be available within a couple of days.

**Comment by phmccarty** [comment]
Fixed in [33650](https://cdn.download.clearlinux.org/releases/33650/clear/RELEASENOTES-33620-to-33650).
