### ISSUE TITLE
Missing codecs?

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2102]
https://www.youtube.com/watch?v=t0sgtQXyNJQ I am having problems playing some videos, such as having this problem: "An error occurred. Please try again later. (Playback ID: Sv7T_4j8az-Oxswt)
Learn More"

**Comment by lebensterben** [comment]
> For example, many Linux distros may not be able to include certain media codecs due to licensing restrictions, but manual installation and third party alternatives are available.

https://docs.01.org/clearlinux/latest/about.html?highlight=codec#is-cl-completely-open-source

**Comment by romulasry** [comment]
Where do I find 3rd party codecs?

**Comment by lebensterben** [comment]
>Where do I find 3rd party codecs?

@romulasry Google ffmpeg

**Comment by romulasry** [comment]
flatpak firefox has the codecs....
