### ISSUE TITLE
Update kernell to 5.8.x

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2103]
Comment when done.

**Comment by 0xA1B2** [comment]
And when the 647 issues are being worked down .. Seems CL has stalled by work overflow.

**Comment by fenrus75** [comment]
We usually wait for the .1

**Comment by WSLUser** [comment]
it's at .3 now

**Comment by phmccarty** [comment]
@miguelinux

**Comment by WSLUser** [comment]
When testing hyper-v kernel. Only patch 118 fails to apply (i used what was already in Linux-current for those that supercede the hyper-v ones) Checking it, it appears the place where it might be applied in the source file has been modified to the point it doesn't have a place to patch to. Also patch command only worked via the spec file.

**Comment by 0xA1B2** [comment]
We are now 5 weeks since 5.8 release .. Can we get an update why this delay is happening or is CL dying a silent death now after first Desktop focus was dropped ?

**Comment by paulcarroty** [comment]
Done.

**Comment by WSLUser** [comment]
Not done completely. Can we get kvm and hyper-v updated too? I assume once the fixes for bare metal are in, it shouldn't be terribly difficult to update the others.
