### ISSUE TITLE
Update pulseaudio to latest stable

### ISSUE THREAD

**Issue by kjchmielewski** [clearlinux/distribution#2106]
Improved SOF driver support

**Comment by mdhorn** [comment]
13.99 is a release candidate for 14.0. Waiting for the final release.

**Comment by romulasry** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tags/v14.0

**Comment by romulasry** [comment]
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/tags/v14.2

**Comment by karthikprabhu17** [comment]
@kjchmielewski : Pulseaudio got bumped to v14.2 starting Release 34270. Please let me know if this can be closed

**Comment by kjchmielewski** [comment]
@karthikprabhu17 : Tested using clear-34270-live-desktop. 
All internal outputs (headphones/speaker) and digital microphone are detected by alsa/pulseaudio and working, using sof-hda-dsp device. 
HDMI sound connected via intel integrated graphics also works without issue.
I think this can be closed. 
Thank You.
