### ISSUE TITLE
libsndfile-dev package included in several bundle misses a critical file

### ISSUE THREAD

**Issue by AnwarShah** [clearlinux/distribution#2108]
I was trying to build pulseeffect which in turn required me to use `sndfile.hh` file which should be provided by libsndfile-dev package which is included in several bundles including `qt-basic-dev`. However, installing the bundles didn't get me the required header file. After inspecting the issue for a while I realized that `sndfile.hh` is missing in the bundle. 

I don't know what causes this. Building sndfile manually fixes the problem. 

Hope the bundles get fixed soon.

**Comment by fenrus75** [comment]
looking
.hh is C++ usually so need to check if we include C++ support

**Comment by fenrus75** [comment]
make install does not install this file

but I made it be manually copied... but users of this.. a bit suspicious imo

**Comment by AnwarShah** [comment]
arch linux `libsndfile` package also has `sndfile.hh` https://www.archlinux.org/packages/extra/x86_64/libsndfile/

**Comment by fenrus75** [comment]
yeah it's not a huge huge deal, just had to fix the package (which is done,
will be in a build soon)

**Comment by AnwarShah** [comment]
Great news! Thank you!

**Comment by phmccarty** [comment]
Fixed in release [33670](https://cdn.download.clearlinux.org/releases/33670/clear/RELEASENOTES) (on September 1).
