### ISSUE TITLE
Overly verbose polkit log: `polkitd[317]: Error opening rules directory: Error opening directory “/etc/polkit-1/rules.d”: No such file or directory (g-file-error-quark, 4)`

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#211]
Polkit is reporting an error in the logs that isn't an error, since /etc/ files can be missing.

```
polkitd[317]: Loading rules from directory /etc/polkit-1/rules.d
polkitd[317]: Error opening rules directory: Error opening directory “/etc/polkit-1/rules.d”: No such file or directory (g-file-error-quark, 4)
```

This error isn't an error, and should be removed.

**Comment by bryteise** [comment]
Seems everything polkit writes is using LOG_NOTICE so if you filter the journal by priority of error these won't show up. Not really sure I'd call this a bug.
