### ISSUE TITLE
FreeCAD

### ISSUE THREAD

**Issue by isabelomakhanya** [clearlinux/distribution#2111]
**Official package name:** FreeCAD

**License (must be an OSI approved Open Source license):** LGPLv2+ license

**Download URL of latest release:** https://github.com/FreeCAD/FreeCAD (active development)

**Latest release date (must be recent):** 0.18.4 / 26 October 2019; 10 months ago | 0.19_pre / 3 November 2019; 9 months ago

**Description:** FreeCAD is a general purpose parametric 3D CAD modeler, whose development is completely open source (LGPL License). FreeCAD is aimed directly at mechanical engineering and product design but also fits in a wider range of uses around engineering, such as architecture, finite element analysis, 3D printing, and other tasks.

FreeCAD features tools similar to Catia, SolidWorks or Solid Edge, and therefore also falls into the category of MCAD, PLM, CAx and CAE. It is a feature based parametric modeler with a modular software architecture which makes it possible to provide additional functionality without modifying the core system.

As with many CAD modelers it has many 2D components in order to sketch planar shapes or create production drawings. However, direct 2D drawing (like Inkscape or AutoCAD LT) is not the focus, neither are animation or mesh edition (like Blender, Maya, 3ds Max, or Cinema 4D). Nevertheless, thanks to its wide adaptability, FreeCAD might become useful in a much broader area than its current focus.

**Comment by fenrus75** [comment]
hmm we have freecad

is there something wrong with it ?

**Comment by isabelomakhanya** [comment]
My oversight. I ended up finding it as a `flatpak`, I was not aware that I had to enable the Flathub repository. So far, it is working well, thank you.

**Comment by fenrus75** [comment]
we have it natively, without flatpak...
it's at least in the maker-cnc bundle if not others

**Comment by phmccarty** [comment]
FreeCAD is available in the `maker-cnc` bundle.

If you run into any issues with FreeCAD on Clear Linux OS, feel free to open a new issue.
