### ISSUE TITLE
Upgrade ModemManager.

### ISSUE THREAD

**Issue by postmannen** [clearlinux/distribution#2115]
We are experiencing problems using the current version of ModemManager with our installations, and the ModemManager provided with CL is old.
Can the CL official package of ModemManager be upgraded to a newer version upstream ?

Modem manager in CL is currently at version 1.10.8.
The current version included with Ubuntu is 1.12.8.
The latest stable available from source 1.14.2.

**Comment by postmannen** [comment]
Is it possible for any help on this one ?

**Comment by phmccarty** [comment]
I've updated it to 1.14.2. It will be available in the next build early next week.

**Comment by postmannen** [comment]
Not sure if I misunderstood something. But checking here https://github.com/clearlinux-pkgs/ModemManager it seems that the packages available still are at 1.10.8.

**Comment by lebensterben** [comment]
> ...

@postmannen See this
https://github.com/clearlinux-pkgs/ModemManager/blob/master/versions

And make sure you haven't disabled auto-update.

**Comment by phmccarty** [comment]
@postmannen The current Clear release is 33780, and the ModemManager update landed in 33780 (see [release notes](https://cdn.download.clearlinux.org/releases/33780/clear/RELEASENOTES-33760-to-33780)).

**Comment by postmannen** [comment]
Thanks a lot for the info.

**Comment by phmccarty** [comment]
Since the package was updated, I will close this issue.
