### ISSUE TITLE
update libva

### ISSUE THREAD

**Issue by ilmarn** [clearlinux/distribution#2116]
current version 2.6
latest 2.8

https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/ZVIXUMBFNGOIUIO7227IV75NOJYKJTZO/

**Comment by paulcarroty** [comment]
Maybe better sent the PR directly to CL github libva repo.

**Comment by ilmarn** [comment]
There is guideline for patches/updates https://github.com/clearlinux/distribution/blob/master/contributing.md#contributing-to-an-existing-software-package
From my previous experience they ignore PRs

**Comment by ilmarn** [comment]
updated to v2.9 in build 33730
