### ISSUE TITLE
3700 - No Boot

### ISSUE THREAD

**Issue by 0xA1B2** [clearlinux/distribution#2118]
Hello,

after the update to 3700 I get a blinking cursor at boot. Using space to boot into previous kernel got the system back.
But it seems kernel 5.8.8 is buggylish integrated.

**Comment by paulcarroty** [comment]
logs?

**Comment by miguelinux** [comment]
I'm able to boot 5.8.8-984.native on encrypted partition.

@0xA1B2 

What is your platform setup?

**Comment by 0xA1B2** [comment]
Fujitsu Q555 Tablet
Intel(R) Atom(TM) CPU  Z3795  @ 1.60GHz
4GB RAM
Boot from 256 GB USB stick (Corsair GTX)

How to I collect the boot logs in CL ?

**Comment by miguelinux** [comment]
Thanks we identify the issue, this will be fixed soon

**Comment by lkmishra** [comment]
> Hello,
> 
> after the update to 3700 I get a blinking cursor at boot. Using space to boot into previous kernel got the system back.
> But it seems kernel 5.8.8 is buggylish integrated.

Hi,
  how exactly are you booting to the old kernel please? If I press spacebar during the booting. Nothing happens for me. I don't get any option and get the same error.

**Comment by lebensterben** [comment]
>> Hello, ...

@lkmishra press and hold

**Comment by 0xA1B2** [comment]
Issue fixed, good job ! Thanks :1st_place_medal:

**Comment by lkmishra** [comment]
> > > Hello, ...
> 
> @lkmishra press and hold

Nope, it's not working for me. I am starting to press from the vaio logo till end. It's normally boot to the error. No difference. I am using an USB keyboard. Is it causing any problem?? I can use the keyboard in the bios.

**Comment by stefanocoding** [comment]
@lkmishra did you try pressing "ESC" instead of the space bar? In my case, I have to press "ESC" a few times until I get the menu.

**Comment by lkmishra** [comment]
> @lkmishra did you try pressing "ESC" instead of the space bar? In my case, I have to press "ESC" a few times until I get the menu.

I tried esc also. No difference. Is there any other way please? My CL is installed on legacy mode, not UEFI.
