### ISSUE TITLE
Kernel panic. Can’t boot to Clear Linux from yesterday evening

### ISSUE THREAD

**Issue by lkmishra** [clearlinux/distribution#2123]
I am running CL from memory stick. It was working fine till day before yesterday. Getting Kernel panic error from yesterday. Can not boot.

![cl err](https://user-images.githubusercontent.com/30885339/93008908-458a7480-f572-11ea-9075-b3941629a9df.jpeg)

Please help.

**Comment by miguelinux** [comment]
this is the same issue as
https://github.com/clearlinux/distribution/issues/2118

We identify the issue and the fix will be available soon

**Comment by miguelinux** [comment]
The fix is already out.

**Comment by lkmishra** [comment]
Hi,
  Can you help me fixing my system please?  Boot interrupt is not working for me. I tried keep pressing spacebar etc. But no difference. It's not giving me any option. Just giving the above error only.

**Comment by mdhorn** [comment]
> Hi,
> Can you help me fixing my system please? Boot interrupt is not working for me. I tried keep pressing spacebar etc. But no difference. It's not giving me any option. Just giving the above error only.

You could download a live image to a USB drive, and boot from that.
https://cdn.download.clearlinux.org/releases/33590/clear/clear-33590-live-server.iso

Once you are logged in as root, you could adjust the boot timeout on the actual installation.

- Mount the boot partition from installed media; likely sda1; use fdisk -l to find the EFI file system
```
mkdir -p /mnt/boot
mount /dev/sda1 /mnt/boot
cat /mnt/boot/loader/loader.conf
```
- Add the timeout to the loader.conf
`echo "timeout 10" | tee -a /mnt/boot/loader/loader.conf
`


- umount boot and reboot; pull the usb after shutdown, before it boots
`umount /mnt/boot
`

Keep in mind this is a guideline, you disk name might be different and EFI could be on a partition other than the default of 1

**Comment by lkmishra** [comment]
> > Hi,
> > Can you help me fixing my system please? Boot interrupt is not working for me. I tried keep pressing spacebar etc. But no difference. It's not giving me any option. Just giving the above error only.
> 
> You could download a live image to a USB drive, and boot from that.
> https://cdn.download.clearlinux.org/releases/33590/clear/clear-33590-live-server.iso
> 
> Once you are logged in as root, you could adjust the boot timeout on the actual installation.
> 
> * Mount the boot partition from installed media; likely sda1; use fdisk -l to find the EFI file system
> 
> ```
> mkdir -p /mnt/boot
> mount /dev/sda1 /mnt/boot
> cat /mnt/boot/loader/loader.conf
> ```
> 
> * Add the timeout to the loader.conf
>   `echo "timeout 10" | tee -a /mnt/boot/loader/loader.conf `
> * umount boot and reboot; pull the usb after shutdown, before it boots
>   `umount /mnt/boot `
> 
> Keep in mind this is a guideline, you disk name might be different and EFI could be on a partition other than the default of 1

![image](https://user-images.githubusercontent.com/30885339/93544126-32eab380-f955-11ea-84c4-5facf9949ee3.png)
I can mount the usb drive to an Ubuntu system. The above is the directory structure. Couldn't find the loader folder. The boot directory is empty. The root directory got a log and yml file.

Be aware I just followed the default installation process mostly and it is a legacy installation, not UEFI.
