### ISSUE TITLE
Unable to disable tallow service

### ISSUE THREAD

**Issue by alekna** [clearlinux/distribution#2126]
`tallow` service is started irrespective of user choice to disable it.

**Environment**:
```
$ swupd info
Distribution:      Clear Linux OS
Installed version: 33700
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
$ uname -a
Linux v5 5.7.19-256.aws #1 SMP Thu Aug 27 04:04:34 PDT 2020 x86_64 GNU/Linux
```

How to reproduce:
```
$ sudo systemctl disable tallow`
$ sudo reboot
```

After a reboot `tallow` service is up and running:
```
$ ps aux | grep tallow
root         158  0.0  1.0  35116  5008 ?        SNs  19:06   0:00 /usr/sbin/tallow
clear        395  0.0  0.1   9596   732 pts/0    R+   19:07   0:00 grep tallow

$ systemctl status tallow
● tallow.service - Tallow Service
     Loaded: loaded (/usr/lib/systemd/system/tallow.service; disabled; vendor preset: disabled)
     Active: active (running) since Sun 2020-09-13 19:06:42 UTC; 45s ago
   Main PID: 158 (tallow)
      Tasks: 1 (limit: 544)
     Memory: 2.5M
     CGroup: /system.slice/tallow.service
             └─158 /usr/sbin/tallow

Warning: some journal files were not opened due to insufficient permissions.
```

P.S. workaround is to use `mask`

**Comment by alekna** [comment]
Same issue with `pacdiscovery` service.

**Comment by fenrus75** [comment]
this is a weird systemd-ism... mask is really what you need to not start
something.
"disable" does not disable, it only makes it not start by default, BUT if
some other service has a dependy on the service, it will still be started.

**Comment by ahkok** [comment]
This service is enabled by default in the distribution, you may have to `systemctl mask tallow` to fully disable it. While there is no dependency on tallow from others, simply `disable`ing it won't work in clearlinux for distro-wide enabled services.

**Comment by thiagomacieira** [comment]
There is a dependency and it's /usr/lib/systemd/system/multi-user.target.wants/tallow.service.

If you mask it, you can't start tallow even manually. An alternative to that is to do `sudo ln -s /dev/null /etc/systemd/system/multi-user.target.wants/tallow.service`.

systemctl disable should do that but doesn't. It's a bug.
```
$ ls -l /etc/systemd/system/network.target.wants/tallow.service
lrwxrwxrwx 1 root root 38 Sep 14 15:45 /etc/systemd/system/network.target.wants/tallow.service -> /usr/lib/systemd/system/tallow.service
$ sudo systemctl disable tallow                                
Removed /etc/systemd/system/multi-user.target.wants/tallow.service.
Removed /etc/systemd/system/network.target.wants/tallow.service.
```

Just removing the files is insufficient.
