### ISSUE TITLE
ElasticSearch bundle is empty

### ISSUE THREAD

**Issue by superdav42** [clearlinux/distribution#2127]
Just installed the `elasticsearch` bundle on Clear Linux Desktop and it appears to have no files and just be an empty package. I find no evidence of elastic search being installed anywhere in the filesystem and bundle-info seems to indicate it has 0 bytes:
```
swupd bundle-info elasticsearch
________________________________
 Info for bundle: elasticsearch
________________________________

Status: Explicitly installed

Bundle elasticsearch is up to date:
 - Installed bundle last updated in version: 33250
 - Latest available version: 33250

Bundle size:
 - Size of bundle: 0.00 Bytes
 - Size bundle takes on disk (includes dependencies): 69.13 MB
```

```
swupd info
Distribution:      Clear Linux OS
Installed version: 33710
```
Please advise

**Comment by mdhorn** [comment]
It was set to "depreciated" earlier in the year, which means it will be dropped in the next Format bump.
The content was dropped as part of the depreciation process.

Sorry, I don't have the context as to why.

**Comment by mdhorn** [comment]
Found some context here: https://github.com/clearlinux/distribution/issues/1489

**Comment by phmccarty** [comment]
Elasticsearch was removed as part of the effort to reduce Java footprint.

Background: https://community.clearlinux.org/t/clear-linux-os-will-be-reducing-its-java-footprint/2454
