### ISSUE TITLE
Update gnome to 3.38

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2128]
https://www.phoronix.com/scan.php?page=news_item&px=GNOME-3.38.0-Released

gnome-shell --version
GNOME Shell 3.36.5

**Comment by fenrus75** [comment]
the 3.38 update went a bit more rough than we had liked
(gnome stopped basically being able to be both 64 and 32 bit, which then
broke wine and some other things and we had to redo a lot more of the OS
than we had liked)
