### ISSUE TITLE
Adding libvirt-python

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#213]
👋 Hi there,

I'm using the `kvm-host` bundle with Clear Linux and trying to script the ability to set KVMs up via [Ansible](https://www.ansible.com/). The `virt` module that's required to do this - [virt](https://docs.ansible.com/ansible/2.6/modules/virt_module.html) - depends on `python >= 2.6` (which I have), and [libvirt-python](http://rpmfind.net/linux/rpm2html/search.php?query=libvirt-python), which I don't have. Would it be possible to add that RPM to the kvm-host-dev bundle? 🙏

**Comment by miguelinux** [comment]
Try to install `virt-manager` bundle.

```
$ sudo swupd search libvirt-python
Searching for 'libvirt-python'

Downloading Clear Linux manifests
   47.12 MB total...

Completed manifests download.

Bundle virt-manager	(304 MB to install)
	/usr/share/doc/libvirt-python/COPYING.LESSER
	/usr/share/doc/libvirt-python/COPYING

Bundle desktop-apps-extras	[installed]	(6403 MB on system)
	/usr/share/doc/libvirt-python/COPYING.LESSER
	/usr/share/doc/libvirt-python/COPYING
```

**Comment by bswinnerton** [comment]
Hi @miguelinux, 

`virt-manager` is a [GUI-based](https://virt-manager.org/) application, my server doesn't have X11. If I were to install that (or `desktop-apps-extras`), I'd end up with libX11client and all of its dependencies, which I'd prefer not to have on this server.

**Comment by mrkz** [comment]
I wonder if a `kvm-host-extras` bundle would make sense which `include(kvm-host)` and also python-libvirt and other bindings (if available).

@bryteise what do you thing? sounds good to me.

**Comment by bryteise** [comment]
I just want to make sure I understand this correctly, is Ansible is running its virt module which is needed for the system doing the provisioning or the system being deployed? sysadmin-hostmgmt is our bundle providing Ansible (and other utilities for managing clusters) so we could add it there but it looks to me like this needs to be on the target system.

In that case I think @mrkz is correct in making an extras bundle since we don't want to pull in python into kvm-host which has a number of other users (we could get creative and add it as a buildreq for something in kvm-host but that's isn't what we want to do with -dev bundles). Are there any other utilities that you would want to have in a libvirt/qemu/provision target use case to make deployment better?

**Comment by bswinnerton** [comment]
> it looks to me like this needs to be on the target system.

👍 this is my understanding. The Ansible provisioning is happening from my MacBook Pro, but as I understand of the [virt module](https://docs.ansible.com/ansible/devel/modules/virt_module.html#requirements), the target system is what requires the module. I can try to get clarity on this from the #ansible room in IRC.

> Are there any other utilities that you would want to have in a libvirt/qemu/provision target use case to make deployment better?

Not that I can think of right now 😄

**Comment by bswinnerton** [comment]
Yes, I've confirmed in IRC that it is indeed needed on the target (by default):

> 17:06 <@bcoca>  bswinnerton: depends, the modules normally execute on the target, unless you 'delegate_to: localhost' or similar
> 17:06 <@bcoca>  that is what that phrase means
> 17:06 <bswinnerton>  bcoca: ah, okay. That's good to know. I'm not using `delegate_to`. Thank you!
> 17:06 <@bcoca>  if you execute it at the target (default behaviour) you'll need the requirements there

**Comment by bryteise** [comment]
Alrighty, thanks for checking on that. I'll put the new bundle together.

**Comment by bryteise** [comment]
The new bundle definition is submitted for review: https://lists.clearlinux.org/pipermail/dev/2018-September/001876.html @bswinnerton.

**Comment by bswinnerton** [comment]
I just noticed this come through in https://github.com/clearlinux/clr-bundles/commit/7d91a09fa7dc893727e1e4f08501a768f6bb8d54. Thank you @bryteise!
