### ISSUE TITLE
Add service wrapper to systemctl

### ISSUE THREAD

**Issue by WSLUser** [clearlinux/distribution#2131]
I prefer to use the service command as it's faster and easier to type out than systemctl. I created an alias in my profile but I had to do this for root and I would prefer root didn't have a defined profile for security purposes. So I propose to do what Fedora does and add a service wrapper to systemctl. You could probably do mostly a copy/paste from their source code for this wrapper.

**Comment by lebensterben** [comment]
if you don't like a root profile, why not just add a shell script in your PATH that wraps "systemctl"

**Comment by WSLUser** [comment]
I'm pretty sure that's exactly what Fedora does. Since they do it, I expect Clear Linux to as well.

**Comment by thiagomacieira** [comment]
Won't do. Two letters more is not worth the hassle, plus shell completion solves all the problems.
