### ISSUE TITLE
#33740 crash at boot

### ISSUE THREAD

**Issue by ilmarn** [clearlinux/distribution#2133]
journalctl attached
[journalctl.log](https://github.com/clearlinux/distribution/files/5269927/journalctl.log)

**Comment by jumpinggoofballs** [comment]
Can confirm. 

The wayland session will crash to gdm, which will then try to fall back to the x session. This then crashes with an "oh no. something went wrong" message on the white screen. 

The Metacity Fallback session works. But if I try to start GDM by itself, GDM will also give me the "oh no" message.

Tried downgrading to 33720 with `--force --picky`, but the whole thing is still borked. The gnome sessions do the exact same thing. Strangely though, GDM now works to allow me to get into the Fallback session without having to drop to an alternative tty.

**Comment by Israelbarzel** [comment]
Update 33740 failed to boot.

**Comment by paulcarroty** [comment]
Same problem - doesn't works:

* GNOME X&Wayland sessions
* Sway

**Comment by avanderm** [comment]
Downgrading to 33720 did work for me luckily.

**Comment by jumpinggoofballs** [comment]
> Downgrading to 33720 did work for me luckily.

33720 did not work for me, but 33710 did. Go figure. 

In either case, this is a pretty serious issue.

**Comment by inmanturbo** [comment]
Same issue here. Haven't tried dowgrading yet.

**Comment by inmanturbo** [comment]
looks like the core issue here is the gnome upgrade. switching to console and `startx` gives me gnome 3.38 without any of my theming. May be some incompatible shell extensions and theming

**Comment by inmanturbo** [comment]
https://community.clearlinux.org/t/33740-killing-desktop/5397

**Comment by romulasry** [comment]
sudo swupd repair -m 33710 shoulld work no?

also remember to:
sudo swupd autoupdate --disable

until this is fixed.

**Comment by inmanturbo** [comment]
```bash
gnome-tweaks  # or any shell extension
```
```
WARNING : Shell not installed or running
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 217, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
WARNING : Shell not running
NoneType: None
```

**Comment by jumpinggoofballs** [comment]
> sudo swupd repair -m 33710

`sudo swupd repair -m 33710 --force` and probably also a good idea to have `--picky` as well.

**Comment by inmanturbo** [comment]
Would recommend first running 
```
sudo swupd diagnose -m 33710
```
To see what changes will be made
example output (abbreviated):
```
-> Missing file: /usr/lib/modules/5.8.9-986.native/kernel/sound/pci/echoaudio/snd-indigoiox.ko
...
...
-> Hash mismatch for file: /usr/share/yelp-xsl/xslt/mallard/html/mal2html-page.xsl
 [100%]

Inspected 495040 files
  5371 files were missing
  8316 files did not match

Use "swupd repair" to correct the problems in the system

Diagnose successful

```

**Comment by amonforstmann** [comment]
Picky downgrade to 33720 worked for me.

`sudo swupd autoupdate --disable`
`sudo swupd repair -m 33720 --picky`

gjs dumped core with 33740

**Comment by romulasry** [comment]
Comment/Close this issue when they push a working update. Thanks in advance.

**Comment by inmanturbo** [comment]
@ahkok has anyone looked at this yet?

**Comment by nodanero** [comment]
I got the crash screen from GDM, looks like the same issue?

I can see in the logs a segfault for Gnome Shell

`[    4.320669] gnome-shell[695]: segfault at 29a6000029ce ip 00007f5e4f386e98 sp 00007ffcf93fc4c0 error 6 cpu 3 in libgjs.so.0.0.0[7f5e4f353000+8e000]
[    6.042665] gnome-shell[948]: segfault at 3e ip 00007f45fa353e98 sp 00007fff3b717fa0 error 6 cpu 15 in libgjs.so.0.0.0[7f45fa320000+8e000]`

**Comment by phmccarty** [comment]
GNOME 3.38 was integrated in release 33740, and this crash is certainly related to that update.

After initial investigation, I suspect that gjs 1.66.0 is not compatible with glib 2.66.0; some of its unit tests fail when built with glib 2.66.0 (but not with glib 2.64.5), and some of the test error messages are identical to the ones we are seeing at bootup beginning with release 33740. If I rebuild gjs with glib 2.64.5 as a build dependency, those errors disappear, and all unit tests pass. Similar unit test result improvements appear for gnome-shell with it is built with the rebuilt gjs in the environment.

I will do some testing on a live Clear Linux system tomorrow, and if my suspicion is correct, we will downgrade glib to 2.64.5 (and do any rebuilds, likely for gjs followed by gnome-shell at a minimum).

**Comment by 0xA1B2** [comment]
Testing should be done before any release on at least 20+ different hardware systems. We had several of these no-boot issues now with CL over the past months, you need to implement a proper release test plan to prevent such avoidable situations in the future ..

**Comment by namm2** [comment]
I tried the repair command but it also break other stuffs like: module for RTL8822BE USB wireless adapter can't be loaded, fonts rendering broke, USB DAC doesn't work. The good thing is this isn't a work machine.

**Comment by ilmarn** [comment]
> I tried the repair command but it also breaks other stuffs like: module for RTL8822BE USB wireless adapter can't be loaded, fonts rendering broke, USB DAC doesn't work. The good thing is this isn't a work machine.

try swupd repair --picky

**Comment by namm2** [comment]
> try swupd repair --picky

I tried the same commands in https://github.com/clearlinux/distribution/issues/2133#issuecomment-697991500

**Comment by chrysophylax** [comment]
Yep. Same on two machines with wildly different setups (one Intel-only hw, one with Intel+NVIDIA) both borked, both work machines. This is a pretty critical issue. 

Aren't the failing tests supposed to be a red flag for pushing this kind of stuff?

**Comment by amonforstmann** [comment]
> I tried the repair command but it also breaks other stuffs like: module for RTL8822BE USB wireless adapter can't be loaded, fonts rendering broke, USB DAC doesn't work. The good thing is this isn't a work machine.

@namm2 please check that you are still running the correct kernel `uname -a` one of my systems switched to the lts kernel and had no networking either

**Comment by namm2** [comment]
@amonforstmann I'm using lts2019 kernel version 5.4.65

**Comment by namm2** [comment]
I checked the logs and it 

> I tried the repair command but it also breaks other stuffs like: module for RTL8822BE USB wireless adapter can't be loaded, fonts rendering broke, USB DAC doesn't work. The good thing is this isn't a work machine.

On the fonts issue, I checked the command's output and it looks like it removed a lot of files in `/usr/lib`, `/usr/lib64`, `/usr/share` and more. But can't explain some kernel modules broke.

**Comment by random-user-00** [comment]
I am facing the exactly same issue and I can see that it has generated core dumps for 3 binaries.
/usr/bin/Xwayland
/user/bin/gnome-shell
/usr/bin/gjs-console

**Comment by xlfe** [comment]
also hit this. downgrade fixed it

**Comment by nodanero** [comment]
33760 is working
`swupd repair -V 33760 --picky`

**Comment by 0xA1B2** [comment]
33760 still not booting on USB drive with Luks. I noticed when pressing e during boot, that the kernel version still is listed as 5.8.9-* and not 5.8.11-?? for 33760, so something is still broken ..

**Comment by Israelbarzel** [comment]
> 33760 is working
> `swupd repair -V 33760 --picky`

sudo swupd check-update
Password: 
Current OS version: 33760
Latest server version: 33740
Thanks nodanero.

**Comment by amonforstmann** [comment]
33760 does indeed boot and load a desktop.
gnome-terminal (ctrl+alt+t) is still not working properly though...

![image](https://user-images.githubusercontent.com/1593803/94267474-f3ffc380-ff3b-11ea-9fba-e833a37837e7.png)
****

**Comment by amonforstmann** [comment]
gnome-photos still dumps core

```
Sep 25 14:36:30 workstation-essen systemd-coredump[8899]: Process 8800 (gnome-photos) of user 1000 dumped core.
                                                          
Stack trace of thread 8800:
#0  0x00007f8a25bc3fae n/a (libglib-2.0.so.0 + 0x86fae)
#1  0x00007f8a25bc40dc g_log_default_handler (libglib-2.0.so.0 + 0x870dc)
#2  0x00007f8a25bc9d28 g_logv (libglib-2.0.so.0 + 0x8cd28)
#3  0x00007f8a25bc9fd9 g_log (libglib-2.0.so.0 + 0x8cfd9)
#4  0x00007f8a25802beb n/a (libgio-2.0.so.0 + 0x14dbeb)
#5  0x00007f8a25cf5fdc n/a (libgobject-2.0.so.0 + 0x29fdc)
#6  0x00007f8a25cf71b4 g_object_new_valist (libgobject-2.0.so.0 + 0x2b1b4)
#7  0x00007f8a25cf7c1e g_object_new (libgobject-2.0.so.0 + 0x2bc1e)
#8  0x000056463bafdcac n/a (gnome-photos + 0xcbcac)
#9  0x000056463ba93a66 photos_base_manager_get_all_filter (gnome-photos + 0x61a66)
#10 0x000056463bae91da n/a (gnome-photos + 0xb71da)
#11 0x000056463bae9cb5 photos_query_builder_global_query (gnome-photos + 0xb7cb5)
#12 0x000056463bab7ed7 photos_fetch_ids_job_run (gnome-photos + 0x85ed7)
#13 0x000056463bae8438 n/a (gnome-photos + 0xb6438)
#14 0x00007f8a24370652 ffi_call_unix64 (libffi.so.6 + 0x7652)
#15 0x00007f8a2436fdf3 ffi_call (libffi.so.6 + 0x6df3)
#16 0x00007f8a25cea642 g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x1e642)
#17 0x00007f8a25ce4a8c g_closure_invoke (libgobject-2.0.so.0 + 0x18a8c)
#18 0x00007f8a25d290b9 n/a (libgobject-2.0.so.0 + 0x5d0b9)
#19 0x000056463ba81938 n/a (gnome-photos + 0x4f938)
#20 0x00007f8a25846ad2 n/a (libgio-2.0.so.0 + 0x191ad2)
#21 0x00007f8a25821b26 n/a (libgio-2.0.so.0 + 0x16cb26)
#22 0x00007f8a25bbb63c g_main_context_dispatch (libglib-2.0.so.0 + 0x7e63c)
#23 0x00007f8a25c4574f n/a (libglib-2.0.so.0 + 0x10874f)
#24 0x00007f8a25bb9aba g_main_context_iteration (libglib-2.0.so.0 + 0x7caba)
#25 0x00007f8a257eca5d g_application_run (libgio-2.0.so.0 + 0x137a5d)
#26 0x000056463ba6deee main (gnome-photos + 0x3beee)
#27 0x00007f8a244ce51d __libc_start_main (libc.so.6 + 0x2a51d)
#28 0x000056463ba6e03e _start (gnome-photos + 0x3c03e)

Stack trace of thread 8870:
#0  0x00007f8a245c8b20 syscall (libc.so.6 + 0x124b20)
#1  0x00007f8a25c3e8c6 g_cond_wait (libglib-2.0.so.0 + 0x1018c6)
#2  0x00007f8a25a683eb n/a (libgegl-0.4.so.0 + 0x2a3eb)
#3  0x00007f8a25bf5d0e n/a (libglib-2.0.so.0 + 0xb8d0e)
#4  0x00007f8a2438081f start_thread (libpthread.so.0 + 0x981f)
#5  0x00007f8a245ce963 __clone (libc.so.6 + 0x12a963)

```

**Comment by Israelbarzel** [comment]
> 33760 does indeed boot and load a desktop.
> gnome-terminal (ctrl+alt+t) is still not working properly though...
> 
> ![image](https://user-images.githubusercontent.com/1593803/94267474-f3ffc380-ff3b-11ea-9fba-e833a37837e7.png)

No problem here, starting gnome-terminal with ctrl+alt+t works properly.

**Comment by amonforstmann** [comment]
> No problem here, starting gnome-terminal with ctrl+alt+t works properly.

Indeed, switching to a different gtk style/theme resolved this.

**Comment by jumpinggoofballs** [comment]
Can confirm that the update to 33760 mostly fixes the shell. But I am also having some glitches with my non-standard theme: in my case, Arc.

**Comment by lebensterben** [comment]
>Can confirm that the update to 33760 mostly fixes the shell. But I am also having some glitches with my non-standard theme: in my case, Arc. 

@jumpinggoofballs Also check update for your theme.

**Comment by romulasry** [comment]
Working now.

**Comment by jumpinggoofballs** [comment]
> > Can confirm that the update to 33760 mostly fixes the shell. But I am also having some glitches with my non-standard theme: in my case, Arc.
> 
> @jumpinggoofballs Also check update for your theme.

The theme files are copied over from a flatpak installation of the theme (not available in the repo), and I think it hasn't been updated in any case since 3.22

But I don't see why a theme should give visual artefacting. I understand styling classes going awry and such, but the kind of artefacting that you get from buggy graphics drivers? Why would that have anything to do with a particular css theme?

**Comment by lebensterben** [comment]
@jumpinggoofballs 
If you manually run `flatpak update` in shell, it will report some runtime it installed as end-of-life or deprecated. For the new gnome, for example, the old icon theme for example is deprecated.
Also, gnome would disable extensions if it's not declared as compatible. For example, the popular dash-to-panel.

**Comment by ilmarn** [comment]
im closing it as its resolved in 33760
terminal issue can be resolved by swithing to adwaita theme or manually updating your current theme

**Comment by frostysnowman2** [comment]
> im closing it as its resolved in 33760
> terminal issue can be resolved by swithing to adwaita theme or manually updating your current theme

Is it safe to enable auto update after 33760?

**Comment by ilmarn** [comment]
> > im closing it as its resolved in 33760
> > terminal issue can be resolved by swithing to adwaita theme or manually updating your current theme
> 
> Is it safe to enable auto update after 33760?

only CL team knows :)
personally i prefer to update manually after a day or two after release and checking issues on github

**Comment by frostysnowman2** [comment]
I am a little disappointed CL team not checking out updates more carefully
this last 33740 update for me required a reinstall of Clear Linux with a
disable of auto update I guess gnome  desktop is not top priority for CL
team. I think for me on my PC a usb bluetooth dongle I use was not handled
properly by 33730 and then 33740 broke everything.

**Comment by 0xA1B2** [comment]
33760 did not fix my broken installation, followed all instructions given here. Result: another dead server which has to be reinstalled .. impressive !

**Comment by frostysnowman2** [comment]
> 33760 did not fix my broken installation, followed all instructions given here. Result: another dead server which has to be reinstalled .. impressive !

33760 worked perfectly on my PC??

**Comment by chrysophylax** [comment]
update to 33760, problem persists, gnome-shell still crashes for me. Going back to 33710...

```
Sep 28 00:27:14 glorfindel systemd-coredump[1267]: Process 1190 (gnome-shell) of user 1000 dumped core.
                                                   #1  0x000055a3a09d3f21 dump_gjs_stack_on_signal_handler (gnome-shell + 0x2f21)
                                                   #5  0x000055a3a09d3cbb default_log_handler (gnome-shell + 0x2cbb)
                                                   #25 0x00007f3b822fdfb7 gnome_shell_plugin_start (libgnome-shell.so + 0x24fb7)
                                                   #29 0x000055a3a09d38ae main (gnome-shell + 0x28ae)
                                                   #31 0x000055a3a09d3ace _start (gnome-shell + 0x2ace)
Sep 28 00:27:14 glorfindel systemd-coredump[1288]: Process 1269 (gnome-shell) of user 1000 dumped core.
                                                   #1  0x0000557c12c53f21 dump_gjs_stack_on_signal_handler (gnome-shell + 0x2f21)
                                                   #5  0x0000557c12c53cbb default_log_handler (gnome-shell + 0x2cbb)
                                                   #25 0x00007f6348a6efb7 gnome_shell_plugin_start (libgnome-shell.so + 0x24fb7)
                                                   #29 0x0000557c12c538ae main (gnome-shell + 0x28ae)
                                                   #31 0x0000557c12c53ace _start (gnome-shell + 0x2ace)
billy@glorfindel ~ $ 
```
