### ISSUE TITLE
ISO desktop image isn't current in Downloads section of the website

### ISSUE THREAD

**Issue by hsehdar** [clearlinux/distribution#2134]
### What was the activity?

Click Download link under **Clear Linux* OS Desktop** on the website.

### What was observed?

1. Previously the current version was downloaded, for example: clear-32760-live-desktop.iso
2. Today it is downloading older version, for example at the time of writing this issue it downloaded clear-33590-live-desktop.iso

### What was expected?

Current version is downloaded.

**Comment by ksmigrod** [comment]
Leave current version alone, a working version is good enough.
I've edited links to download 33740, but I was unable to boot due to missing rootfs (on Dell Precision 7530 laptop with EFI boot).

**Comment by DroneZzZko** [comment]
You can find all releases including the latest here: https://cdn.download.clearlinux.org/releases/

**Comment by hsehdar** [comment]
> You can find all releases including the latest here: https://cdn.download.clearlinux.org/releases/

As described in the issue, new comers or Linux distro explorers most of the time hit website and not content delivery network. Hence this issue was raised.

**Comment by lebensterben** [comment]
>> You can find all releases including the latest here: https://cdn.download.clearlinux.org/releases/ ...

@hsehdar https://docs.01.org/clearlinux/latest/about.html#id5
> Clear Linux OS is not intended to be a general-purpose Linux distribution, suitable for novice end-users.

**Comment by paulcarroty** [comment]
v33760 desktop image is broken, maybe it's the reason.

**Comment by rosti-il** [comment]
@paulcarroty 
> v33760 desktop image is broken, maybe it's the reason.

How do you know? Is there some service to check that for any version of installation image?

**Comment by lebensterben** [comment]
>@paulcarroty  ...

@rosti-il Obviously when it's broken you will know.

**Comment by hsehdar** [comment]
@lebensterben I'm fully aware that it is rolling **rolling-release Linux distribution**. What I'm saying in this issue is what was easily available earlier, isn't the same today. There could be different reasons on why latest isn't available today. May be view point/stand point recently changed within release team or it could be a bug.

Looking forward for a firm reply from Intel team. Let it take it's due course of action.

> > > You can find all releases including the latest here: https://cdn.download.clearlinux.org/releases/ ...
> 
> @hsehdar https://docs.01.org/clearlinux/latest/about.html#id5
> 
> > Clear Linux OS is not intended to be a general-purpose Linux distribution, suitable for novice end-users.

@lebensterben Thanks for the link to **About** page. I'm fully aware that it is **rolling-release Linux distribution** and all those explanations in the _About_ page.

What I'm saying in this issue is the latest ISO was easily available earlier and it isn't the same today. There could be different reasons on why it isn't available today. May be view point/stand point recently changed within release team or it could be a bug in the built page.

Looking forward for a firm reply from Intel team. Let it take it's due course of action.

**Comment by rosti-il** [comment]
> @rosti-il Obviously when it's broken you will know.

It's a pity that you can't know this in advance, before you try to install and got into a trouble, like unbootable computer or something else. Currently I have 33760 server originally installed as 33590 on a VertualBox and then upgraded by swupd. It works properly and now I'm thinking about installing the latest 33760 desktop on a real computer. This is how I came into this issue.

Don't the Clear Linux project have some automatic sanity tests of the built installation images? And if it have where can I see the status?

**Comment by pixelgeek** [comment]
Latest releases of Clear Linux should now be correctly listed on the Downloads page of the website.
