### ISSUE TITLE
33760 gnome-shell crash on boot

### ISSUE THREAD

**Issue by chrysophylax** [clearlinux/distribution#2136]
Had this issue on 33740 as part of #2133, downgraded to 33710 with picky repair as suggested - worked ok. Now rolled forward to 33760 and gnome-shell crashes again. 

journalctl output is attached as boot.log

Previous issue #2133 

[boot.log](https://github.com/clearlinux/distribution/files/5289374/boot.log)

**Comment by hsehdar** [comment]
@chrysophylax Could you try upgrade 33710 -> 33720 -> 33760? It worked for most. It's a guess. This shouldn't have happened to your computer.

**Comment by lebensterben** [comment]
seems like you have installed Wacom tablet support. Probably you need to reinstall it.
You can also try "swupd repair"

**Comment by chrysophylax** [comment]
@lebensterben why would I have to reinstall wacom table support? I haven't added it - it is out of the base install - I have an OLED touchscreen as my laptop screen.

I have done repairs already with swupd.

@hsehdar is there anything in particular that would alleviate? I thought clear was basically atomic for the OS layer.

**Comment by lebensterben** [comment]
I suspect that you've installed software in /usr that doesn't come from swupd. So I suggest "swupd repair".
I saw some errors about Wacom, though this may not be the sole reason or reason at all for the failure.
I also saw NVIDIA GPU but it seems like you didn't install the proprietary driver so that could not be the cause either.

**Comment by hsehdar** [comment]
> @lebensterben why would I have to reinstall wacom table support? I haven't added it - it is out of the base install - I have an OLED touchscreen as my laptop screen.
> 
> I have done repairs already with swupd.
> 
> @hsehdar is there anything in particular that would alleviate? I thought clear was basically atomic for the OS layer.

Hi @chrysophylax I was guessing if any residue left so. I do agree on what you thought about _Clear Linux_.

**Comment by chrysophylax** [comment]
Fixed as of _Clear Linux_ version 33780
