### ISSUE TITLE
Update the Nim programming language

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#2138]
Nim version on clear repos is 1.0; 

the latest stable version is 1.2.6,

it would be great if we had the latest version!

Thanks!

**Comment by romulasry** [comment]
https://nim-lang.org/download/nim-1.2.6.tar.xz
https://nim-lang.org/download/nim-1.2.6.tar.xz.sha256

**Comment by phmccarty** [comment]
I updated nim to 1.2.6. It should land in a release soon.
