### ISSUE TITLE
linux-firmware missing after installing

### ISSUE THREAD

**Issue by lpereira** [clearlinux/distribution#214]
**Describe the bug**
Installed Clear Linux on a computer with network connectivity only over WiFi.  (Wireless connection has been setup manually with wpa_supplicant and systemd-networkd before progressing with the installer.) On reboot, the system was without connectivity, due to missing firmware package.

**To Reproduce**
1. Install Clear Linux on a computer with hardware that requires linux-firmware (e.g. anything using iwlwifi module)
2. Reboot without installation media
3. Can't use WiFi adapter once system boots

**Expected behavior**
linux-firmware to be installed, especially if it was needed during installation.    Detecting which firmware is being used might be tricky, but an approximation may be obtained with a command like `lsmod |grep -v "Module " | awk '{print $1}' | xargs -n1 modinfo | grep '^firmware:'|cut -d: -f2 | sort -u`.

**Environment (please complete the following information):**
 - Clear Linux OS version: 25180
 - Bundles: Clean installation, only bundles installed by the installer

**Comment by dorileo** [comment]
probably adding ```linux-firmware-wifi``` to the bundle ```kernel-native``` should fix the problem. @bryteise what do you think?

**Comment by bryteise** [comment]
I'm okay with that, seems the smallest impact to bundle sizing. Should be in kernel-native and kernel-lts I think, @miguelinux @bwarden any others?

**Comment by bwarden** [comment]
It's already pulled in by wpa_supplicant; was that also not installed even though it was used by the installer? That might be the underlying problem to fix.

**Comment by lpereira** [comment]
I'll check if wpa_supplicant has been installed. I don't remember.

**Comment by fenrus75** [comment]
we should consider making a "wifi support" bundle

**Comment by fenrus75** [comment]
I've added a "hardware-wifi" bundle

the installer can even optionally install this if it detects wifi
