### ISSUE TITLE
where is dunst? supposedly installed as part of desktop-i3 but not on my system?

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#2142]
```bash
user@computer/ $ sudo find / -name 'dunst*'
/usr/share/package-licenses/dunst
user@computer/ $ swupd-search dunst
Bundle with the best search result:
     desktop-i3                         - Run the i3 desktop environment.  (32MB) (installed)

This bundle can be installed with:

  swupd bundle-add  desktop-i3

user@computer/ $ which dunst
which: no dunst in ([all my paths])
user@computer/ $ sudo swupd bundle-add desktop-i3
Loading required manifests...
Warning: Bundle "desktop-i3" is already installed, skipping it...
1 bundle was already installed
```

its listed under the desktop-i3 package
https://clearlinux.org/software/bundle/desktop-i3

Have I done something wrong?

```bash
user@computer/ $ sudo swupd diagnose --verbose
Diagnosing version 33780
Downloading missing manifests...
    
Checking for missing files
 [100%]

Checking for corrupt files
 [100%]

Checking for extraneous files
 [100%]

Inspected 178286 files

Diagnose successful
```

Also, I just noticed https://github.com/clearlinux/clr-bundles/commit/c17066b1ca3fde95a98210607fe90e46a7056489
Deprecate alternative desktop environments. 
 :( :(

**Comment by phmccarty** [comment]
Thanks for the report. It looks like the `dunst` package in Clear Linux is broken, as it does not install the binary, service files, etc. I will work on fixing this.

**Comment by phmccarty** [comment]
I fixed the install, and I updated it to the latest release (1.5.0). The changes should be integrated for a build within a couple days.

**Comment by xlfe** [comment]
thanks @phmccarty - much appreciated
