### ISSUE TITLE
Install leaves diff output in use-private-network.service

### ISSUE THREAD

**Issue by catleeball** [clearlinux/distribution#2145]
**Describe the bug**

- Installed OS with `clear-33590-live-server.iso` image
- Notice a few hours after install in journalctl that `use-private-network.service` won't start
    - `systemctl status use-private-network.service` -->
        - `Loaded: bad-setting (Reason: Unit use-private-network.service has a bad unit file setting.) \n Active: inactive (dead)`
    - `journalctl -u use-private-network.service`
        - [log](https://gist.github.com/catleeball/44daf97646435601e55d995a13de995a)
- Check when this file was modified
    - [stat timestamps](https://gist.github.com/catleeball/543a5d0aff8d02875579e890a663e968) shows it was last modified during install
- File contents are patch notes and a `diff --git`
    - [use-private-network.service](https://gist.github.com/catleeball/90c0413a263d25740bb4ffaf5fa4948a)

Here's the installer log and and yaml files:
- [clr-installer.yaml](https://gist.github.com/catleeball/1603ec3c20ba9f1d4b52d15b4ffce427)
- [clr-installer.log](https://gist.github.com/catleeball/f9e46ce9151b59acbcf9fcafabbeb4a2)

**To Reproduce**
1. Install OS from `clear-33590-live-server.iso`
2. Use settings [clr-installer.yaml](https://gist.github.com/catleeball/1603ec3c20ba9f1d4b52d15b4ffce427)
3. Post-install see errors in journald about `use-private-network.service`
4. File has patch notes and a diff in it: [use-private-network.service](https://gist.github.com/catleeball/90c0413a263d25740bb4ffaf5fa4948a)

**Expected behavior**
File wouldn't exist, or would have valid defaults.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 33780
 - Installer Version 2.7.0, built on 2020-07-21_21:43:15_UTC
 - Platform: Intel Skylake, [parts list](https://docs.google.com/spreadsheets/d/1lIlZ_OYXOURL2VhYCJr03b6iWKPYZAG_f-bMsFBaCnQ/edit?usp=sharing)

**Additional context**
Thanks! Please let me know if you need any additional info.

**Comment by phmccarty** [comment]
use-private-network.service should not be listed as a patch. If you remove the `series` and re-autospec, that will fix the issue.

**Comment by mdhorn** [comment]
> use-private-network.service should not be listed as a patch. If you remove the `series` and re-autospec, that will fix the issue.

@phmccarty I believe the problems the opposite, what is listed as a service file is actually a patch. I’ve sent a for-review contener to the internal mailing list for approval.

**Comment by phmccarty** [comment]
Ah, you're right... never mind my last comment :-)

**Comment by mdhorn** [comment]
Updated submitted which will remove the bogus service file.

The fix should be in the next release of Clear Linux OS; >= 33810 in the next few days.

Closing.

**Comment by catleeball** [comment]
Thanks for the quick response and fix! 💯  🥳
