### ISSUE TITLE
Document custom kernel modifications

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/distribution#215]
**Is your feature request related to a problem? Please describe.**
Documentation which describes (tutorial style perhaps) modification of the Linux kernel, adding and signing kernel modules is missing.

**Describe the solution you'd like**
- Tutorial on how with best-practices for Linux Kernel modification
- Kernel module signing documentation etc.
- Compiling a kernel module to run against Clear Linux

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by iphutch** [comment]
@tpleavitt

**Comment by tpleavitt** [comment]
@shrmrf , Thanks for submitting this request.  This is a documentation task that we have been discussing and once we have something to share I will let you know.
