### ISSUE TITLE
gsm-lib disappeared

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2150]
Not available anymore in [current](https://download.clearlinux.org/current/x86_64/os/Packages/).

**Comment by phmccarty** [comment]
I [removed](https://github.com/clearlinux/common/commit/5a5bac8596) `gsm` from the repo recently, because it is not present in any Clear Linux bundle or pulled in via dependency.

Do you require it for a mix?

**Comment by paulcarroty** [comment]
Yeah, ffmpeg [needs](https://github.com/clearfraction/ffmpeg/blob/master/ffmpeg.spec#L140) it, so will be nice to keep.

**Comment by phmccarty** [comment]
Okay, I will add `gsm` back to the repos.
