### ISSUE TITLE
gmsh build with Blossom

### ISSUE THREAD

**Issue by DevinCharles** [clearlinux/distribution#2151]
Is it possible to rebuild the gmsh bundle with the blossom algorithm? This is typically turned on by default:

`opt(BLOSSOM "Enable Blossom algorithm (needed for full quad meshing)" ${DEFAULT})`

**Comment by phmccarty** [comment]
Not sure why that option was disabled, so I will enable it. I also updated it to version 4.6.0, since 4.5.5 was not building successfully with GCC 10.

The changes should land in a build early next week.

**Comment by phmccarty** [comment]
The update landed in release [33830](https://cdn.download.clearlinux.org/releases/33830/clear/RELEASENOTES).
