### ISSUE TITLE
Update kernel to 5.9

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2155]
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.9-Released

**Comment by romulasry** [comment]
> With Linux 5.9 comes the ability to compress the Linux kernel image / initrd with Zstd
> https://phoronix.com/scan.php?page=news_item&px=Linux-Zstd-Compression-Close
> 
> Source: https://www.phoronix.com/scan.php?page=news_item&px=Zstd-Firmware-Compress-Patch

**Comment by paulcarroty** [comment]
Available in `33830`.

**Comment by romulasry** [comment]
@paulcarroty How about the zstd compressed kernel image?
