### ISSUE TITLE
Update gnome-software to the latest

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2156]
https://en.wikipedia.org/wiki/GNOME_Software

https://gitlab.gnome.org/GNOME/gnome-software/-/tags/3.38.0

**Comment by KaeLL** [comment]
The GNOME update broke CL ~1 month ago with a white Something Went Wrong screen which led to a lot of complaints in the forums, and people were advised to revert the update. I'm looking for info on whether the CL devs finished the transition to 3.38 and fixed the bugs.

**Comment by 0xA1B2** [comment]
Every update can break you system, thats the risk we have to take with CL ..

**Comment by romulasry** [comment]
Update?

**Comment by romulasry** [comment]
Update?

**Comment by romulasry** [comment]
Update? Software is currently at 3.34.2

**Comment by phmccarty** [comment]
I am updating gnome-software to 40.0. But note that the swupd plugin will disappear from the install, since the patch is both unmaintained at the moment and it needs a refresh.

**Comment by phmccarty** [comment]
Updated to gnome-software 40.0 in release [34560](https://cdn.download.clearlinux.org/releases/34560/clear/RELEASENOTES).
