### ISSUE TITLE
Update to LLVM 11.1.0

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2157]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.0

**Comment by fenrus75** [comment]
the primary user of llvm for us is mesa

and it often takes mesa a couple of days to adjust....

**Comment by lebensterben** [comment]
>the primary user of llvm for us is mesa ...

@fenrus75 Rust has recently migrated to LLVM 11. Though LLVM >9 are all supported, it's best if latest LLVM is supported on CL.

**Comment by romulasry** [comment]
Mesa 20.2,  LLVM 11.0+ and Linux 5.9+ are required for Radeon RX 6000 enablement. Mesa 20.3 for better support. Source: https://www.phoronix.com/scan.php?page=news_item&px=NGG-Culling-Enabled-GFX-10.3

**Comment by romulasry** [comment]
Linux 5.9+, Mesa 20.2+, LLVM 11, and the Sienna Cichlid firmware files for having RX 6800 series support.
https://www.phoronix.com/scan.php?page=news_item&px=Radeon-Software-Linux-20.45

**Comment by romulasry** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=54c797a694d3830ef93f349ec25e1d96d4b88102 here is the firmware

**Comment by romulasry** [comment]
You will also need the latest git untli they release one with sienna cichlid firmware.

**Comment by romulasry** [comment]
Update?

**Comment by romulasry** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.0.1
LLVM 12 will be out in roughly two months.

**Comment by insilications** [comment]
lastest mesa 20.3.2 is building fine with my llvm 11 on CL

**Comment by romulasry** [comment]
LLVM 12.0.0 should be out around the start of March.
Source:
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-12.0-RC1-Released

**Comment by thiagomacieira** [comment]
I'm the person who used to do the LLVM update but since I've moved to a different team, I guess it stopped being a priority.

**Comment by romulasry** [comment]
https://github.com/llvm/llvm-project/releases/tag/llvmorg-11.1.0

**Comment by phmccarty** [comment]
@romulasry I think it's okay to keep the subject as `Update to LLVM 11`, since for Clear Linux OS this implies the latest LLVM 11 release.

**Comment by KaeLL** [comment]
So, any chance of this happening or the plug has been pulled permanently? Should we bite the bullet and go with 3rd-party repos for LLVM? Is Mesa the only thing dictating the LLVM update cadency on CL? I guess so, since there could be a separate Mesa-specific package and a regular clang/llvm that gets updated ASAP, but there isn't. Are the Intel folks too busy to get this done? Do you need help? Can you at least keep us in the loop? What's happening?

**Comment by paulcarroty** [comment]
@insilications any binary repos?

**Comment by insilications** [comment]
I will try to provide a binary repo or full autospec configs

**Comment by eero-t** [comment]
Any updates?

Mesa git has required LLVM v11 since last week.

Intel graphics compiler (for compute runtime / OpenCL / Level Zero) has had LLVM v11 support for a while, but its releases are still built with LLVM 10.

**Comment by thiagomacieira** [comment]
Attempt 1 to add package "llvm10":
```
: in function `parseSpecConstOpt(llvm::StringRef, SPIRV::TranslatorOpts&)':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:380: undefined reference to `llvm::getSpecConstInfo(std::istream&, std::vector<std::pair<unsigned int, unsigned int>, std::allocator<std::pair<unsigned int, unsigned int> > >&)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `operator()':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:258: undefined reference to `SPIRV::convertSpirv(std::istream&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `convertSPIRV()':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:(.text.main+0x1268): undefined reference to `SPIRV::convertSpirv(std::istream&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, bool)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `convertSPIRVToLLVM(SPIRV::TranslatorOpts const&)':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:206: undefined reference to `llvm::readSpirv(llvm::LLVMContext&, SPIRV::TranslatorOpts const&, std::istream&, llvm::Module*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `regularizeLLVM()':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:298: undefined reference to `llvm::regularizeLlvmForSpirv(llvm::Module*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `main':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:543: undefined reference to `llvm::getSpecConstInfo(std::istream&, std::vector<std::pair<unsigned int, unsigned int>, std::allocator<std::pair<unsigned int, unsigned int> > >&)'
/usr/bin/ld: CMakeFiles/llvm-spirv.dir/llvm-spirv.cpp.o: in function `convertLLVMToSPIRV(SPIRV::TranslatorOpts const&)':
/builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:183: undefined reference to `llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: /builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:185: undefined reference to `llvm::writeSpirv(llvm::Module*, SPIRV::TranslatorOpts const&, std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
/usr/bin/ld: /builddir/build/BUILD/llvm-10.0.1.src/projects/SPIRV/tools/llvm-spirv/llvm-spirv.cpp:176: undefined reference to `SPIRV::SPIRVUseTextFormat'
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by thiagomacieira** [comment]
That function is defined in `lib/SPIRV/SPIRVReader.cpp`

**Comment by eero-t** [comment]
Is it this / does LLVM contain its own copy of it: https://github.com/KhronosGroup/SPIRV-LLVM-Translator

At least Intel Graphics Compiler instructions tell to build that separately...

**Comment by thiagomacieira** [comment]
That's the one I'm trying to compile. Applying a patch so it will link.

**Comment by thiagomacieira** [comment]
Attempt 2: success! Let's see if I need to adjust any of the paths it created...

**Comment by paulcarroty** [comment]
@thiagomacieira congrats, maybe this [repository](https://github.com/insilications/llvm12) will be useful for you.

**Comment by thiagomacieira** [comment]
@paulcarroty can't update to LLVM12 yet, since there's no SPIR-V release for it. In any case, I need to get 11 compiled.

**Comment by mdhorn** [comment]
Thank you for helping with this @thiagomacieira

**Comment by thiagomacieira** [comment]
Attempt 2: bootstrap llvm built fine. The main cmake failed:
```
CMake Error at projects/SPIRV/CMakeLists.txt:35 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11.0.0".
  The following configuration files were considered but not accepted:
    /builddir/build/BUILD/llvm-11.1.0.src/clr-bootstrap-build/lib64/cmake/llvm/LLVMConfig.cmake, version: 11.1.0
    /usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 10.0.1
    /lib64/cmake/llvm/LLVMConfig.cmake, version: 10.0.1
-- Configuring incomplete, errors occurred!
```

**Comment by thiagomacieira** [comment]
No SPIR-V 11.1. 

I'll just patch it, unless @eero-t has other suggestions.

**Comment by thiagomacieira** [comment]
Following Fedora's lead and using the latest commit from the release_110 branch.

**Comment by thiagomacieira** [comment]
- [x] create llvm10
- [ ] update llvm to 11
- [ ] rebuild bcc
- [ ] rebuild bpftrace
- [ ] rebuild clamav
- [ ] rebuild darktable
- [ ] rebuild dldt
- [ ] rebuild embree
- [ ] rebuild intel-graphics-compiler
- [ ] rebuild ldc
- [ ] rebuild libclc
- [ ] rebuild lldb
- [ ] rebuild mesa
- [ ] rebuild mono
- [ ] rebuild octave
- [ ] rebuild opencl-clang
- [ ] rebuild pyside2-setup
- [ ] rebuild qt-creator
- [ ] rebuild suricata
- [ ] hardcode clang-11 in llvm10 and rebuild

**Comment by thiagomacieira** [comment]
Attempt 3: round 1 succeeded (bootstrap, main, 32-bit); round 2 failed due to wrong paths in extras files.

**Comment by thiagomacieira** [comment]
Attempt 4: build succeeded. Adding to localrepo and trying to build stuff with it to see if it works.

**Comment by thiagomacieira** [comment]
llvm10 and bcc rebuilt fine using llvm 11. I'm launching the rest in a script overnight and we'll see tomorrow how far it's fared.

**Comment by thiagomacieira** [comment]
darktable failed:
```
[FATAL] Cannot resolve dependency name: libXxf86misc-dev                                                                                       
```
dldt failed:
```
[FATAL] Cannot resolve dependency name: dldt-dev                                                                                               
[FATAL] Cannot resolve dependency name: ngraph-dev                                                                                             
[FATAL] Cannot resolve dependency name: progress                                                                                               
```
Will investigate tomorrow (probably just a stale autospec).

**Comment by eero-t** [comment]
I have no idea how ClearLinux bundles are built, but that's an odd name:
`[FATAL] Cannot resolve dependency name: libXxf86misc-dev`

ClearLinux packages are named differently:
```
# swupd bundle-info devpkg-libXxf86misc
______________________________________
 Info for bundle: devpkg-libXxf86misc
______________________________________

Status: Explicitly installed

Bundle devpkg-libXxf86misc is up to date:
 - Installed bundle last updated in version: 34320
 - Latest available version: 34320

Bundle size:
 - Size of bundle: 0.00 Bytes
 - Size bundle takes on disk (includes dependencies): 1.88 GB
```
And RPM development package names end in "-devel", only Debian based development packages end in "-dev"...

> dldt failed:
> `[FATAL] Cannot resolve dependency name: dldt-dev `

Circular build dependency???

**Comment by thiagomacieira** [comment]
libclc build failed. lldb I forgot to upgrade to 11.1 (but built).

Octave and everything after that failed because the machine ran out of disk space.

**Comment by thiagomacieira** [comment]
@eero-t looks like it was indeed an autospec bug. After updating it, darktable built fine. 

dldt still presents those errors that make no sense.

**Comment by thiagomacieira** [comment]
libclc built after upgrading to 11.1 from <random commit>.

**Comment by eero-t** [comment]
Looking at IGC build notes (see bottom of the page): https://github.com/intel/intel-graphics-compiler/blob/master/documentation/build_ubuntu.md

LLVM v11 support sounds a bit more experimental than I would have thought[1].  Might be safer to tell IGC to use v10 with IGC_OPTION__LLVM_PREFERRED_VERSION option.

[1] I've built it only with v10, but I've seen notes about v11 support for a long time in release notes, so I thought it to have been further along / better tested in releases, but last verified working IGC version commit listed on that page is from *October*. Sorry about that.  :-/

As to "vc-intrinsics" version listed in the table, I've always used just git head with igc git head, and haven't had any problems, but maybe it can interact badly with v11, or other components...

**Comment by thiagomacieira** [comment]
Octave rebuilt and updated to 6.2.0 (only 1h35 to do that...)

**Comment by thiagomacieira** [comment]
@eero-t we can't build something against llvm10 after the upgrade. The only option is to keep the old build without updating. Please confirm we should stop all updates to igc.

**Comment by thiagomacieira** [comment]
opencl-clang latest does not build:
```
CMake Error at CMakeLists.txt:26 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "11.0.0".
  The following configuration files were considered but not accepted:
    /usr/lib64/cmake/llvm/LLVMConfig.cmake, version: 11.1.0
    /lib64/cmake/llvm/LLVMConfig.cmake, version: 11.1.0
```

Trying same trick as SPIR-V

**Comment by thiagomacieira** [comment]
Didn't work. Patching to force accepting 11.1.0.

**Comment by thiagomacieira** [comment]
@fenrus75 fixed ldc by upgrading to 1.25.

**Comment by eero-t** [comment]
> @eero-t we can't build something against llvm10 after the upgrade. The only option is to keep the old build without updating. 

Why?  ClearLinux still provides even LLVM v8 and v9...

> Please confirm we should stop all updates to igc.

I don't really know.  From HW support point of view it would be better to continue building latest IGC versions with whatever LLVM version works with it.

However, with latest Mesa needing LLVM v11, and latest IGC not supporting that properly yet, I'm not sure which has more priority.

* If IGC really cannot continue to be built with v10, and Mesa is more important, best option could be building latest IGC with LLVM v10 before upgrading to LLVM v11.

* If IGC is more important, I would first contact upstream (maybe also internally at Intel) and ask them when they get LLVM v11 properly supported and post-pone LLVM upgrade if they give some reasonable answer...  Maybe file also Mesa bug about LLVM v10 support.

**Comment by thiagomacieira** [comment]
We support using Clang 8, 9, 10, and now 11. We do not support building against libLLVM.so older versions, especially libclang (the files are nowhere).

There was a build failure I didn't investigate when upgrading. I'm just going after what you said that LLVM 11 was experimental.

**Comment by thiagomacieira** [comment]
Reported intel/intel-graphics-compiler#176 and intel/intel-graphics-compiler#177.

**Comment by thiagomacieira** [comment]
Ok, we're in good shape. The new bundle has also been created and should be coming in a future version soon.

Work left to do: update intel-graphics-compiler, once the blocking build issues are fixed by upstream. IGC is required for intel-compute-runtime, which is required by dldt. dldt also requries an EOL package (ngraph).

Existing build should still work, so there's probably no harm in leaving the stale builds for the moment. But unless there's action by upstream to fix those issues, we'll consider dropping the packages.

**Comment by thiagomacieira** [comment]
And before anyone asks: we'll look into LLVM 12 soon, after SPIRV and opencl-clang have released updates compatible with version 12.

**Comment by ArchangeGabriel** [comment]
@thiagomacieira For IGC you can build 1.0.5435. It works with LLVM 11.

**Comment by fenrus75** [comment]
"For IGC you can build 1.0.5435. It works with LLVM 11." for a very twisted version of "works" maybe.
or maybe 11.0.0 not 11.0.1

**Comment by ArchangeGabriel** [comment]
I’ve just verified right now, and it works even with 11.1.0. If you have issues building it, please tell me more about them.

**Comment by fenrus75** [comment]
-- [IGC] Using system LLVM 11.1.0
CMake Error at IGC/CMakeLists.txt:3302 (message):
  [IGC] Could not find the LLVM dylib.  Aborting.
-- Configuring incomplete, errors occurred!


fun

**Comment by ArchangeGabriel** [comment]
How did you build LLVM 11? You need `-DLLVM_BUILD_LLVM_DYLIB=ON` and `-DLLVM_LINK_LLVM_DYLIB=ON` at least.

**Comment by eero-t** [comment]
> igc 1.0.3771 worked, but attempt to upgrade to https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.7041 failed. 

1.0.3771 release commit is from early April 2020.

> For IGC you can build 1.0.5435. It works with LLVM 11.

Ok, that's the release following the commit documented as being tested working on IGC Ubuntu page.

The release commit is from end of October 2020 i.e. lacking half a year of potential HW enabling changes, but it's still 1/2 year newer than the 1.0.3771 Thiago mentioned...

**Comment by ArchangeGabriel** [comment]
> > For IGC you can build 1.0.5435. It works with LLVM 11.
> 
> Ok, that's the release following the commit documented as being tested working on IGC Ubuntu page.
> 
> The release commit is from end of October 2020 i.e. lacking half a year of potential HW enabling changes, but it's still 1/2 year newer than the 1.0.3771 Thiago mentioned...

Yes I know, and it turned out it was actually pure luck that somehow a LLVM 11 compatible version was out at the time LLVM 11 itself was released. They broke it right after, and getting them to fix it has been… complicated. I’m not even sure they won’t break LLVM 12 right after merging the PR fixing LLVM 11&12…

Also I know Intel is a very large company, but I find it funny that different parts of it can’t work together. ;p

**Comment by thiagomacieira** [comment]
We need a patch in igc because of the way our libLLVM is named. Like OpenSUSE, we patch llvm so that the library has a *proper* name: libLLVM.so.11, not libLLVM-11.so. Our packaging system gets confused otherwise: all files ending in ".so" are development files and would cause the entire -dev sub-package (including .a and headers) to be installed just for the use of the library.

Anyway, having applied this patch:
```patch
From c42b4c0fcffec6cbd6273e5a2df9dd2f172a2279 Mon Sep 17 00:00:00 2001
From: Thiago Macieira <thiago.macieira@intel.com>
Date: Tue, 20 Apr 2021 12:57:49 -0700
Subject: [PATCH] Fix LLVM library name

We patch LLVM so it produces regularly-named libraries.
---
 IGC/CMakeLists.txt | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/IGC/CMakeLists.txt b/IGC/CMakeLists.txt
index 8518ffe4..e4321ce4 100644
--- a/IGC/CMakeLists.txt
+++ b/IGC/CMakeLists.txt
@@ -3293,10 +3293,10 @@ if(LLVM_LINK_LLVM_DYLIB)
     # SET_LLVM_LIB_PATH is a CMake variable that can be passed in to specify the location
     # to look for the LLVM .so. In some cases this is useful if multiple LLVM versions are installed
     if(SET_LLVM_LIB_PATH)
-        set(IGC_BUILD__LLVM_LIBS_TO_LINK "${SET_LLVM_LIB_PATH}/libLLVM-${LLVM_VERSION_MAJOR}.so")
+        set(IGC_BUILD__LLVM_LIBS_TO_LINK "${SET_LLVM_LIB_PATH}/libLLVM.so")
         message(STATUS "[IGC] Link against specified LLVM dylib ${IGC_BUILD__LLVM_LIBS_TO_LINK}")
     else()
-        find_library(IGC_BUILD__LLVM_LIBS_TO_LINK "libLLVM-${LLVM_VERSION_MAJOR}.so")
+        find_library(IGC_BUILD__LLVM_LIBS_TO_LINK "libLLVM.so")
         if(IGC_BUILD__LLVM_LIBS_TO_LINK)
           message(STATUS "[IGC] Link against found LLVM dylib ${IGC_BUILD__LLVM_LIBS_TO_LINK}")
         else()
-- 
2.31.1
```

we do get past cmake for version 1.0.5435, and the build does go very far (the furthest I've ever seen so far), but fails right at 100%:
```
[100%] Linking CXX shared library Release/libigc.so
/usr/bin/ld: Release/libVCIGCDeps.a(TranslationInterface.cpp.o): in function `vc::translateBuild(TC::STB_TranslateInputArgs const*, TC::STB_TranslateOutputArgs*, TC::TB_DATA_FORMAT, IGC::CPlatform const&, float)':
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.5435/IGC/VectorCompiler/igcdeps/src/TranslationInterface.cpp:247: undefined reference to `vc::createDefaultShaderDumper()'
/usr/bin/ld: /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.5435/IGC/VectorCompiler/igcdeps/src/TranslationInterface.cpp:271: undefined reference to `vc::ParseOptions(llvm::StringRef, llvm::StringRef, bool)'
/usr/bin/ld: /builddir/build/BUILD/intel-graphics-compiler-igc-1.0.5435/IGC/VectorCompiler/igcdeps/src/TranslationInterface.cpp:296: undefined reference to `vc::Compile(llvm::ArrayRef<char>, vc::CompileOptions const&, vc::ExternalData const&, llvm::ArrayRef<unsigned int>, llvm::ArrayRef<unsigned long>)'
/usr/bin/ld: Release/libVCIGCDeps.a(TranslationInterface.cpp.o): in function `vc::make_error_code(vc::errc)':
/builddir/build/BUILD/intel-graphics-compiler-igc-1.0.5435/IGC/VectorCompiler/include/vc/Support/StatusCode.h:69: undefined reference to `vc::err_category()'
collect2: error: ld returned 1 exit status
```

I had tried:
* 1.0.3041
* 1.0.3771
* 1.0.4155
* 1.0.4427
* 1.0.4944
* 1.0.5585
* 1.0.7041 (latest)

None of those built.

**Comment by thiagomacieira** [comment]
```
$ cat Makefile 
PKG_NAME := intel-graphics-compiler
URL = https://github.com/intel/intel-graphics-compiler/archive/igc-1.0.5435/intel-graphics-compiler-1.0.5435.tar.gz
ARCHIVES = https://github.com/intel/vc-intrinsics/archive/eabcd2022cf868a658b257b8ea6ad62acbbe7dc5.tar.gz ../vc-intrinsics

include ../common/Makefile.common
```

According to https://github.com/intel/intel-graphics-compiler/releases/tag/igc-1.0.5435, that's the right commit.

PS: also asked the IGC team to make finding the matching commit an automatable task.

**Comment by ArchangeGabriel** [comment]
Yeah, that’s the one I’ve used too. Where can I see all your build recipes to check for differences in the way all dependencies from the tree are built?

**Comment by thiagomacieira** [comment]
This is the .spec for master branch of both IGC and vc-intrinsics: https://gist.github.com/thiagomacieira/e9e78455c109447b97a5204cdec2d2cd

Ditto for 5435 and vc-intrinsics of the commit above: https://gist.github.com/thiagomacieira/de710d6ee64a7d129039201be87f9087

Neither spec has the %files listing because the build failed before autospec could get the file listing.

The `%cmake` RPM macro expanded to:
```
cmake -G 'Unix Makefiles' -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_SBINDIR=/usr/bin -DCMAKE_INSTALL_LIBDIR=/usr/lib64 -DLIB_INSTALL_DIR=/usr/lib64 -DLIB_SUFFIX=64 -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib ..
```

**Comment by ArchangeGabriel** [comment]
Only looking at the 5435 one for now, did not had time to look at the merged change in master yet.

I’m not sure why this line
```
cp -r %{_builddir}/vc-intrinsics-eabcd2022cf868a658b257b8ea6ad62acbbe7dc5/* %{_builddir}/intel-graphics-compiler-igc-1.0.5435/../vc-intrinsics
```
is not just
```
cp -r %{_builddir}/vc-intrinsics-eabcd2022cf868a658b257b8ea6ad62acbbe7dc5/* %{_builddir}/vc-intrinsics
```
but anyway, to me what you’re missing is this cmake option: `-DVC_INTRINSICS_SRC="%{_builddir}/vc-intrinsics"`.

**Comment by thiagomacieira** [comment]
This is a generated file, which is why it has some weirdness in paths.

The cmake option is not necessary. I placed the intrinsics at the path that IGC looks for it by default.

We're in contact with the IGC team and they're trying to fix these issues. Meanwhile, IGC is disabled on Clear.

The LLVM 11 upgrade has been released.
