### ISSUE TITLE
ceph: deprecation warning for "import rados"

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#216]
**Is your feature request related to a problem? Please describe.**

I'm trying to set up Ceph according to http://docs.ceph.com/docs/master/install/manual-deployment/

When running commands like `ceph --help`, all output starts with a warning:
```
/usr/bin/ceph:128: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  import rados

 General usage: 
...
```

**Describe the solution you'd like**

Whatever is causing this warning probably should be changed to use the new syntax.

**Comment by iphutch** [comment]
@ahkok please ping ceph maintainer

**Comment by ahkok** [comment]
@ganeshmaharaj any chance you could work your magic?

**Comment by ganeshmaharaj** [comment]
@ahkok will take a look at this.

**Comment by ganeshmaharaj** [comment]
@ahkok @iphutch patch up for review to address this issue.

**Comment by ahkok** [comment]
Given that it's broken, and looking at your patch, I think we just need to merge and get on with it. Especially since we have 2 more ceph issues open.

**Comment by ganeshmaharaj** [comment]
Patch is merged. Should be included in the next release of clear.

**Comment by ganeshmaharaj** [comment]
Fix should be in clear release 25450 and above. @iphutch
