### ISSUE TITLE
ssh-copy-id fails due to shell incompatibility

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2166]
OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020

Steps to Reproduce:
1. ssh-copy-id somehost.domain.tld

Actual results:
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
/usr/bin/ssh-copy-id: line 251: warning: here-document at line 251 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 250: warning: here-document at line 250 delimited by end-of-file (wanted `EOF')
/usr/bin/ssh-copy-id: line 254: /dev/null`: Permission denied
/usr/bin/ssh-copy-id: line 260: EOF: command not found
password:

After giving the password, it states that the key is added, but nothing happens.

Expected results:
* no shell errors
* key is copied

This is a simple parenthesis at the wrong place. Simply moving the closing parenthesis behind the EOF marker solves the issue.
There is a pull request upstream to fix the issue
https://github.com/openssh/openssh-portable/pull/206/files

**Comment by lebensterben** [comment]
It's already been included in the upstream
https://gitlab.com/phil_hands/ssh-copy-id/-/tree/main

So we only need to update this file.

**Comment by phmccarty** [comment]
Fixed in release [33910](https://cdn.download.clearlinux.org/releases/33910/clear/RELEASENOTES).

**Comment by AkhilJalagam** [comment]
until you get new release, use this

sudo wget -O `which ssh-copy-id` 'https://raw.githubusercontent.com/Fallmay/openssh-portable/66f16e5425eb881570e82bfef7baeac2e7accc0a/contrib/ssh-copy-id' && sudo chmod +x `which ssh-copy-id`
