### ISSUE TITLE
ceph-volume failing: TypeError: memoryview: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#217]
I'm following http://docs.ceph.com/docs/master/install/manual-deployment for setting up ceph on Clear Linux.

I got the monitor up and running, but adding OSDs with ceph-volume fails:
```
# ceph-volume lvm create --data /dev/vdb
Running command: /bin/ceph-authtool --gen-print-key
Running command: /bin/ceph --cluster ceph --name client.bootstrap-osd --keyring /var/lib/ceph/bootstrap-osd/ceph.keyring -i - osd new 7162b8c5-3a69-49e6-a08d-3344b7c10772
-->  TypeError: memoryview: a bytes-like object is required, not 'str'
```

Looks like the migration to Python3 isn't complete yet.

Is this supposed to work at the moment? Is there some Clear Linux specific documentation for setting up ceph? Google leads to https://clearlinux.org/documentation/ceph-deploy.html, but that isn't available anymore.

As part of fixing this issue, can an integration test be added that ensures that ceph keeps working in Clear Linux?

**Comment by pohly** [comment]
This is on a virtual machine with the following bundles installed: cloud-native-basic storage-cluster

Running other `ceph-volume` commands shows that LVM and cryptsetup are missing?
```
# ceph-volume lvm zap /dev/vdb --destroy
--> Zapping: /dev/vdb
 stderr: WARNING: Failed to connect to lvmetad. Falling back to device scanning.
 stderr: Operation prohibited while global/metadata_read_only is set.
 stderr: Recovery of standalone physical volumes failed.
 stderr: Cannot process standalone physical volumes
--> Absolute path not found for executable: cryptsetup
--> Ensure $PATH environment variable contains common executable locations
Running command: cryptsetup status /dev/mapper/
-->  FileNotFoundError: [Errno 2] No such file or directory: 'cryptsetup': 'cryptsetup'
```

They can be installed via `storage-utils`, but if they are needed by ceph, then they probably should be in the `storage-cluster` bundle, too.

After installing `storage-utils` and enabling LVM (via `systemctl enable lvm2-lvmetad.socket && systemctl start lvm2-lvmetad.socket`) the zap operation gets further, but still fails at the end:
```
# ceph-volume lvm zap /dev/vdb --destroy
--> Zapping: /dev/vdb
 stderr: Operation prohibited while global/metadata_read_only is set.
 stderr: Recovery of standalone physical volumes failed.
 stderr: Cannot process standalone physical volumes
Running command: /bin/cryptsetup status /dev/mapper/
 stdout: /dev/mapper/ is inactive.
--> Skipping --destroy because no associated physical volumes are found for /dev/vdb
Running command: /bin/wipefs --all /dev/vdb
Running command: /bin/dd if=/dev/zero of=/dev/vdb bs=1M count=10
-->  TypeError: endswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by pohly** [comment]
Upstream issue, with links to patches which probably fix the problems (haven't tried them yet):
https://tracker.ceph.com/issues/24993

**Comment by ganeshmaharaj** [comment]
@pohly can you confirm the version of ceph you are running? Clear has 13.2.2 version of ceph and this patch has already been backported to it. 
cc @ahkok

**Comment by ganeshmaharaj** [comment]
@pohly Just tested this on the latest version of ceph from clear. 

```
root@clr-620709278518407b9ada42dd9bc1400f ~ # ceph-volume lvm zap /dev/vdb --destroy
Running command: /bin/cryptsetup status /dev/mapper/
 stdout: /dev/mapper/ is inactive.
--> Zapping: /dev/vdb
 stderr: WARNING: Failed to connect to lvmetad. Falling back to device scanning.
 stderr: Operation prohibited while global/metadata_read_only is set.
 stderr: Recovery of standalone physical volumes failed.
 stderr: Cannot process standalone physical volumes
--> Destroying physical volume /dev/vdb because --destroy was given
Running command: /bin/pvremove -v -f -f /dev/vdb
 stderr: WARNING: Failed to connect to lvmetad. Falling back to device scanning.
 stdout: Labels on physical volume "/dev/vdb" successfully wiped.
Running command: /bin/wipefs --all /dev/vdb
Running command: /bin/dd if=/dev/zero of=/dev/vdb bs=1M count=10
 stderr: 10+0 records in
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0311892 s, 336 MB/s
--> Zapping successful for: /dev/vdb
```

**Comment by pohly** [comment]
I can confirm that this is working in the current version in Clear Linux.

**Comment by adityamaru** [comment]
hey @pohly, im trying to setup a ceph client on clear linux. I'm struggling to install the correct bundles to get this working. I've installed `cloud-native-basic` and  `storage-cluster` but neither seem to contain the required ceph binaries.

**Comment by pohly** [comment]
Sorry, I am no longer involved with Clear Linux.
