### ISSUE TITLE
Consider changing `emacs-x11` configuration option

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2172]
I have just compiled `emacs` with the following configuration options:
```
./configure --disable-static --without-m17n-flt \
--without-xaw3d \
--with-xpm=yes \
--with-gif=no \
--with-tiff=yes \
--with-imagemagick \
--with-modules \
--with-cairo \
--enable-link-time-optimization
```

Comparing to the current [config](https://github.com/clearlinux-pkgs/emacs-x11/blob/720f0baee79e458e6e6d80a53d4f6c89090209a7/configure), the notable differences are:

- Use the default new `pdump` instead of the legacy one
- Enabled LTO
- Removed the unknown option `--disable-static`
- `libotf`, `tiff`, `cairo` are enabled (`cairo` is enabled for debugging ligature support)

The 3rd and 4th changes are not significant.
What I found is with LTO `emacs` becomes more responsive.
Also I do not see any issue with `pdump` on my machine.

**Comment by phmccarty** [comment]
@lebensterben Thanks for the feedback. I'll investigate the emacs/emacs-x11 configuration more carefully and see what was going wrong with pdump.

**Comment by phmccarty** [comment]
I enabled pdump and LTO for both `emacs` and `emacs-x11` packages, and these changes will be part of the next release (34270 or newer).

**Comment by lebensterben** [comment]
Thanks!
