### ISSUE TITLE
udisks

### ISSUE THREAD

**Issue by hacketiwack** [clearlinux/distribution#2177]
Official package name:
udisks

License (must be an OSI approved Open Source license):
GPLv2 and LGPLv2

Download URL of latest release:
https://github.com/storaged-project/udisks

Latest release date (must be recent):
2020-08-12

Description:
The UDisks project provides a daemon, tools and libraries to access and manipulate disks, storage devices and technologies.

**Comment by thiagomacieira** [comment]
https://github.com/clearlinux-pkgs/udisks2 was added in 2017

**Comment by hacketiwack** [comment]
Thanks @thiagomacieira I was not looking into the right bundles. Sorry for the disturbance.
