### ISSUE TITLE
ceph: mgr systemd unit files

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#218]
For the version of ceph in Clear Linux (currently 13.x), ceph-mgr is required (http://docs.ceph.com/docs/mimic/mgr/). Without it, a cluster health warnings is triggered which (if I remember correctly) prevents creating new volumes in the cluster.

Clear Linux has no systemd units for ceph-mgr. Not sure whether upstream ships none or Clear Linux simply doesn't install them. Either way, please add them.

Here are the ones I copied from Debian to get around the issue for now:
`ceph-mgr.target`:
```
[Unit]
Description=ceph target allowing to start/stop all ceph-mgr@.service instances at once
PartOf=ceph.target
Before=ceph.target
[Install]
WantedBy=multi-user.target ceph.target
```

`ceph-mgr@.service`:
```
[Unit]
Description=Ceph cluster manager daemon
After=network-online.target local-fs.target time-sync.target
Wants=network-online.target local-fs.target time-sync.target
PartOf=ceph-mgr.target

[Service]
LimitNOFILE=1048576
LimitNPROC=1048576
EnvironmentFile=-/etc/default/ceph
Environment=CLUSTER=ceph

ExecStart=/usr/bin/ceph-mgr -f --cluster ${CLUSTER} --id %i --setuser ceph --setgroup ceph
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
StartLimitInterval=30min
StartLimitBurst=3

[Install]
WantedBy=ceph-mgr.target
```

**Comment by ganeshmaharaj** [comment]
patch up for review. Hoping it will land in the next release.

**Comment by ganeshmaharaj** [comment]
Fix should be in clear release 25470 and above. @iphutch
