### ISSUE TITLE
Please Update go-basic bundle

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2180]
It's falling a bit behind. Thank you.

<pre><font color="#05979A"><b>☁ </b></font><font color="#4D9A05"><b> [</b></font><font color="#05979A"><b>master</b></font><font color="#4D9A05"><b>]</b></font><font color="#3464A3"><b> </b></font><font color="#4D9A05">go</font> run <u style="text-decoration-style:single">make.go</u>
Your version of Go (go version go1.13.15 linux/amd64
) is too old. Current build requires Go 1.15 or later.
exit status 1
</pre>

**Comment by fenrus75** [comment]
the problem we had was that K8S did not work with go 1.15

**Comment by inmanturbo** [comment]
Hmm ... ouch. thanks for the response.  Won't a bump to [v0.5.0](https://github.com/kubernetes/release/releases/tag/v0.5.0) fix that?

Looks like everything was fixed, bumped and merged before [#1421](https://github.com/kubernetes/release/issues/1421#issue-662142735) was closed . . .

**Comment by phmccarty** [comment]
The `go` package was updated to 1.15.5 in release [33960](https://cdn.download.clearlinux.org/releases/33960/clear/RELEASENOTES-33940-to-33960).

**Comment by inmanturbo** [comment]
Great news! Thanks for the update
