### ISSUE TITLE
fwupd update 1.5.5

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2184]
https://github.com/fwupd/fwupd/releases/tag/1.5.1

**Comment by romulasry** [comment]
https://github.com/fwupd/fwupd/releases/tag/1.5.2

**Comment by romulasry** [comment]
https://github.com/fwupd/fwupd/releases/tag/1.5.3

**Comment by romulasry** [comment]
https://github.com/fwupd/fwupd/releases/tag/1.5.4

**Comment by romulasry** [comment]
https://github.com/fwupd/fwupd/releases/tag/1.5.5

**Comment by nobodyatandnothing** [comment]
https://github.com/fwupd/fwupd/releases/tag/1.7.2

**Comment by bryteise** [comment]
Will be updated in the next release
