### ISSUE TITLE
Please update tzdata

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2185]
Currently not aware of daylight savings time.

**Comment by phmccarty** [comment]
tzdata is up-to-date in Clear Linux... 2020d is the latest release.

**Comment by phmccarty** [comment]
Are you experiencing similar issues as described in https://github.com/clearlinux/distribution/issues/2168?

**Comment by inmanturbo** [comment]
> Are you experiencing similar issues as described in #2168?

Yes. Same issue. I'm sorry I thought it was tzdata,  since a similar issue on a RHEL system was fixed for me in an update  which included update of tzdata rpm. Strange though, that was  a "real issue" though as it was making file syncing software go all wonky, this one just appears to be a gnome bug.

Thanks for pointing it out.
Closing as Duplicate of https://github.com/clearlinux/distribution/issues/2168

**Comment by inmanturbo** [comment]
Actually this was the same issue, but the Fedora team patched it downstream on their end.
