### ISSUE TITLE
Update intel-microcode package

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#2195]
Intel microcode was updated due to a security vulnerability ([PLATYPUS](https://platypusattack.com)) . Please update kernel packages to include the [new microcode](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files).

**Comment by fenrus75** [comment]
the update was already done...
but the microcode goes into the firmware packages not the kernel ones :)

**Comment by omkhar** [comment]
Thank you, happy for this to be closed out. 

--oa

**Comment by mdhorn** [comment]
This change should be in release 33960 or newer later this week.
