### ISSUE TITLE
Update openssh-server bundle documentation [was: Can't modify OpenSSH port]

### ISSUE THREAD

**Issue by mignz** [clearlinux/distribution#220]
I need to change the OpenSSH port to something like 2222. Adding `Port 2222` to `/etc/ssh/sshd_config` changes nothing. However, I know that the file is being read because `PermitRootLogin yes` works.

Is this a bug? Or does Clear Linux handle OpenSSH's port differently? Either way, how do I change it?

**Comment by mignz** [comment]
After some help from mrkz on IRC (many thanks!), I got a workaround by copying clear's sshd.socket into /etc/systemd/system and change the port there. That one is then picket on boot.

1. `# cp /usr/lib/systemd/system/sshd.socket /etc/systemd/system/sshd.socket`
1. `# sed -i 's/ListenStream=22/ListenStream=2222/g' /etc/systemd/system/sshd.socket`

**Comment by sofar** [comment]
This is documented explicitly in `man stateless`:

```
   sshd
          sshd(8) sshd_config(5)

       The SSH daemon has all of its configuration built in and no template configuration file is present on the file system. The man page for sshd_config(5) explains the for‐
       mat, and it suffices to put only a single option in the file
          /etc/sshd/sshd_config

       For example, to enable X11 forwarding through sshd all one has to do is add one line containing X11Forwarding yes. Other often used options include PermitRootLogin  yes
       to allow root ssh login access, and the following 3 lines to disable password authentication entirely:
          ChallengeResponseAuthentication no

          PasswordAuthentication no

          UsePAM no

       To modify the listening port of sshd, one needs to determine whether sshd.socket or sshd.service is enabled first, since the methods for changing the port number depend
       on whether sshd(8) is controlling the port number, or whether systemd(1) is:
          systemctl is-enabled sshd.socket

       If enabled, the sshd.socket unit should be edited to modify the port:
          systemctl edit --full sshd.socket

       And, the user should modify the port number at ListenStream= to the desired new port number.

       If sshd.service is enabled, the user should create, and edit a new /etc/ssh/sshd_config file:
          mkdir -p /etc/ssh/ vi /etc/ssh/sshd_config

       And add a line in that file that reads:
          Port 10022

       to, for instance, change the port number sshd.service will listen on to port 10022.

       Root login over SSH is disabled by default and should remain disabled for most systemd. However, in some cases this is acceptable and it can be easily enabled by adding
       the following line to /etc/ssh/sshd_config that reads:
          PermitRootLogin yes

```

**Comment by sofar** [comment]
Note, this is not a workaround. This is *the supported method* for modifying a default listening port for socket activated services.

**Comment by mrkz** [comment]
@sofar perhaps would be nice to document how our default ssh works in https://clearlinux.org/documentation/clear-linux/reference/bundles/openssh-server, we do have some documentation there already, so may be worth to actually let the 'how-it-works' clear

**Comment by sofar** [comment]
Just open an issue in the documentation project, then?

**Comment by gvancuts** [comment]
> The socket should be active

Does it need a reboot (that's about the only thing I haven't tried), else it's disabled by default after I install the `openssh-server` bundle.

**Comment by sofar** [comment]
Just a start of the sshd.socket unit should be enough. You might need to daemon-reload as well if you made modifications.

**Comment by gvancuts** [comment]
My bad, it works out of the box after a reboot. I think it would be good to add these details to the documentation, i.e.:
* `sshd.socket` is active by default but needs a reboot (or be started manually)
* One needs to either create a user account to login remotely or allow root login (the latter being already described in the doc)

And obviously that the way to change the port is via the socket file.

**Comment by ahkok** [comment]
https://github.com/clearlinux/clear-linux-documentation/pull/262#pullrequestreview-162596220
