### ISSUE TITLE
PHP should include sodium extension

### ISSUE THREAD

**Issue by superdav42** [clearlinux/distribution#2200]
The PHP sodium extension should be included with the PHP package. It is in neither php-basic or php-extras. Sodium was added to PHP core in 7.2 and replaced the mcrypt extensions. It should be a simple matter to add --with-sodium to the configure command to build it.

**Comment by phmccarty** [comment]
Fixed in release [33970](https://cdn.download.clearlinux.org/releases/33970/clear/RELEASENOTES) ([commit](https://github.com/clearlinux-pkgs/php/commit/e2e786836dfd9b487c5c43a14aab9d67c97265df))
