### ISSUE TITLE
Enable the CAKE qdisc

### ISSUE THREAD

**Issue by raggi** [clearlinux/distribution#2207]
Please set `CONFIG_NET_SCH_CAKE=y` in the kernel config, as in https://github.com/clearlinux-pkgs/linux/pull/17/commits/89e4632d017852e863fa6c9db59c3dc0b732ccd6

This qdisc is useful for routers as it performs well with congestion control as described here: https://www.bufferbloat.net/projects/codel/wiki/Cake/

**Comment by miguelinux** [comment]
The change is already done, please wait 2 or 3 days to be released.

**Comment by raggi** [comment]
Thanks!

Does that get exported to github.com/clearlinux-pkgs/linux after the release rolls?

**Comment by raggi** [comment]
It appears to have rolled. Thanks again!
