### ISSUE TITLE
Image content validation failed on Fedora27

### ISSUE THREAD

**Issue by jox98** [clearlinux/distribution#221]
**Describe the bug**
I follow https://clearlinux.org/documentation/clear-linux/guides/maintenance/validate-signatures to validate the image contents but get:

`Verification failure
139839101372224:error:21075075:PKCS7 routines:PKCS7_verify:certificate verify error:crypto/pkcs7/pk7_smime.c:285:Verify error:unsupported certificate purpose
`

**To Reproduce**
1. curl -O https://download.clearlinux.org/current/clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz
2. curl -O https://download.clearlinux.org/current/clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz-SHA512SUMS.sig
3. curl -O https://download.clearlinux.org/releases/$(curl https://download.clearlinux.org/latest)/clear/ClearLinuxRoot.pem
4. sha256sum ClearLinuxRoot.pem
Check ist OK and equals to 4b0ca67300727477913c331ff124928a98bcf2fb12c011a855f17cd73137a890 
5. sha512sum clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz > sha512sum.out
6. openssl smime -verify -in clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz-SHA512SUMS.sig 
get `Error reading S/MIME message
139976905738048:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:crypto/asn1/asn_mime.c:391:
`

**Expected behavior**
The output should contain Verification successful. 

**Environment (please complete the following information):**
$ cat /etc/fedora-release 
Fedora release 27 (Twenty Seven)
$ openssl version
OpenSSL 1.1.0h-fips  27 Mar 2018

**Additional context**
The issue has been reported on 2018-10-04 at IRC channel #clearlinux

**Comment by phmccarty** [comment]
Can you try verifying the signature with OpenSSL 1.0.x instead? OpenSSL 1.1.x is not available in Clear Linux OS yet, so we have not tested it yet (AFAIK).

**Comment by tmarcu** [comment]
The (internal) API is quite different between 1.0.# and 1.1, so it's unlikely this will work unless you downgrade. The core verification in swupd itself will not work with 1.1 either at this time. I'm curious to see the results if you use the version we provide in Clear.

**Comment by jox98** [comment]
It seems not be easy to downgrade openssl on fedora27:

$ sudo dnf install compat-openssl10-devel --allowerasing
....
$ openssl version
OpenSSL 1.1.0f-fips  25 May 2017
$ openssl smime -verify -in clear-$(curl https://download.clearlinux.org/latest)-installer.img.xz-SHA512SUMS.sig
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     6  100     6    0     0      3      0  0:00:02  0:00:02 --:--:--     2
Error reading S/MIME message
139948953749312:error:0D0D40D1:asn1 encoding routines:SMIME_read_ASN1:no content type:crypto/asn1/asn_mime.c:391:

:(

**Comment by tmarcu** [comment]
@jox98 having (crudely) downgraded openSSL manually on a different OS myself, I sympathize with you, it's really not a nice process because the libraries need to be munged around and it breaks everything.
If you really depend on the openssl validation of this on Fedora, I would just try a docker container of Clear and use that to verify content, either in a mounted folder or directly ADD-ing the image contents to the container in the Dockerfile. Then you could just do a docker run -it openssl verify etc etc etc etc.

**Comment by iphutch** [comment]
Removing "bug" label and adding the "invalid" label as this is not a bug *in* Clear.

**Comment by jox98** [comment]
Thanks to all of you; the limitation regarding the openssl version should be documented to avoid similar issues like this in the future. A command line hint for the Docker solution would also be good ;-)

I think this issue can be closed, don't you?
