### ISSUE TITLE
less cannot preview .tar .tar.gz .gz .zip etc.

### ISSUE THREAD

**Issue by xuancong84** [clearlinux/distribution#2213]
On almost all Linux distributions nowadays, the `less` command can preview .tar .tar.gz .gz .zip etc. directly, except for clearlinux.

**Comment by lebensterben** [comment]
>On almost all Linux distributions nowadays, the `less` command can preview .tar .tar.gz .gz .zip etc. directly, except for clearlinux.

Enlighten me. I've no idea what other distros you are talking about.

> Less is a pager. A pager is a program that displays text files.
http://www.greenwoodsoftware.com/less/faq.html

**Comment by xuancong84** [comment]
For example, in Ubuntu, Debian, MX Linux, Deepin, etc., the `less` command can view .tar .tar.gz .gz .zip .iso etc. archive files directly.

**Comment by lebensterben** [comment]
You can build this package
https://github.com/wofr06/lesspipe

Making it the default behavior of LESS doesn't make any sense.

**Comment by xuancong84** [comment]
Thanks! Well, of course I know how to do it. But as an elite Linux Distro, shouldn't ClearLinux have it by default?

**Comment by mdhorn** [comment]
Closing as there is a workaround and unlikely to implement. This would require a new package.

**Comment by xuancong84** [comment]
I don't quite understand why whenever it requires a new package, then you tend to not implement. Is adding a new package very difficult?
I wish Clear Linux to become more popular, rather than something like this: [https://fossbytes.com/best-linux-distros-choosing-guide/](url), [https://www.tecmint.com/top-most-popular-linux-distributions/](url), [https://www.journaldev.com/33762/top-best-linux-distros](url)
