### ISSUE TITLE
weechat 3

### ISSUE THREAD

**Issue by KaeLL** [clearlinux/distribution#2225]
Current CL version: 2.9
Latest: 3.0 (1 month old)

**Comment by romulasry** [comment]
https://weechat.org/files/src/weechat-3.0.tar.xz
https://weechat.org/download/checksums/weechat-3.0-sha512.txt/

**Comment by mdhorn** [comment]
In the latest release of Clear Linux OS [34100](https://download.clearlinux.org/releases/34100/clear/RELEASENOTES)
