### ISSUE TITLE
Package update: Lua 5.4.2

### ISSUE THREAD

**Issue by xaverh** [clearlinux/distribution#2226]
Version 5.4.2 of Lua has been released: https://www.lua.org/versions.html
It would be great to have it available.

**Comment by romulasry** [comment]
https://www.lua.org/ftp/lua-5.4.2.tar.gz

**Comment by phmccarty** [comment]
The update to Lua 5.4.2 has been integrated, so it is expected to land in the next release, 34370 or newer.

**Comment by phmccarty** [comment]
The update landed in release [34370](https://cdn.download.clearlinux.org/releases/34370/clear/RELEASENOTES). Closing.
