### ISSUE TITLE
Update kernel to 5.10.5

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2227]
You shoud also consider adding zstd support, see: https://github.com/clearlinux/distribution/issues/2182

https://github.com/torvalds/linux/releases/tag/v5.10

**Comment by romulasry** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.1.tar.xz

**Comment by romulasry** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.2.tar.xz

**Comment by romulasry** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.3.tar.xz

**Comment by romulasry** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.4.tar.xz

**Comment by phmccarty** [comment]
@romulasry Thanks, we've started the updates to 5.10.x.

**Comment by bwarden** [comment]
Kernel update to 5.10.4 has been submitted; expect it to make it into a release in the next few days, assuming it passes testing.

**Comment by romulasry** [comment]
https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.5.tar.xz

**Comment by bwarden** [comment]
Don't worry; we know where to find the kernel ;) Things just ran a little bit slower while most of us were out of office for the holidays.

Also, @miguelinux already built 5.10.5 yesterday morning: https://github.com/clearlinux-pkgs/linux/commit/9041b39cf6c5652e9d9a5bc782d2a48120c7ba5f

**Comment by thiagomacieira** [comment]
Note 5.10.4 and 5.10.5 have a deadlock on snd-hda-codec-hdmi, so you may experience lockups on graphical systems. Upgrading to 5.10.6 is recommended.

**Comment by WSLUser** [comment]
This does not include KVM or Hyper-V, just bare Linux. Also 5.10.10 is out now. Please bring all kernels to the newest kernel.
