### ISSUE TITLE
Update firmware to latest to support latest AMD cards/Intel bluetooth

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2229]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20201218.tar.gz
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/snapshot/linux-firmware-20201218.tar.asc

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/

**Comment by phmccarty** [comment]
In progress. The update should land in release 34110 or newer.

**Comment by phmccarty** [comment]
Updated in release [34130](https://cdn.download.clearlinux.org/releases/34130/clear/RELEASENOTES-34100-to-34130).
