### ISSUE TITLE
For ClearLinux How to check GPU Usage and Video Usage

### ISSUE THREAD

**Issue by weiseng-yeap** [clearlinux/distribution#2232]
Hi Team,

Just like to check from here.
How to check the GPU and Video usage performance data?

Because we using the gstreamer to playback the 4K  video source like to check the GPU and Video Usage performance data.

Thanks!

**Comment by lebensterben** [comment]
https://github.com/Syllo/nvtop

**Comment by weiseng-yeap** [comment]
Actually we like to get the benchmark data on ClearLinux. Can you help to provide us how to get the GPU and Video Usage benchmark data?

Thanks!

**Comment by lebensterben** [comment]
>Actually we like to get the benchmark data on ClearLinux. Can you help to provide us how to get the GPU and Video Usage benchmark data? ...

@weiseng-yeap You can directly query the stats via NVML interface: http://docs.nvidia.com/deploy/nvml-api/index.html

**Comment by weiseng-yeap** [comment]
Actually, we using the Intel build GPU., not the using external GPU.

Any suggestion for this ?

**Comment by lebensterben** [comment]
check intel-gpu-tools

**Comment by weiseng-yeap** [comment]
We're using the ClearLinux, will ClearLinux have parameters to read out for the GPU and Video Usage benchmark data?

**Comment by lebensterben** [comment]
>We're using the ClearLinux, will ClearLinux have parameters to read out for the GPU and Video Usage benchmark data?

@weiseng-yeap I already answered.

**Comment by karthikprabhu17** [comment]
@weiseng-yeap:  Can this we closed as this is answered?

**Comment by weiseng-yeap** [comment]
Yes, this can close

**Comment by paulcarroty** [comment]
```
$ sudo swupd bundle-add igt-gpu-tools
$ intel_gpu_top
```
