### ISSUE TITLE
Docker 20.10.1

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#2233]
Please update Docker to the current release, 20.10.1.

**Comment by mdhorn** [comment]
Note: The release for source has moved with v20.x 
https://github.com/docker/docker-ce
⚠️ This repository is now deprecated and will be archived ⚠️

Starting with the Docker 20.10 release, packages for the Docker Engine and Docker CLI are built directly from their respective source repositories instead of from this repository.

**Comment by romulasry** [comment]
https://github.com/moby/moby/releases/tag/v20.10.2
https://github.com/docker/cli/releases/tag/v20.10.2

**Comment by romulasry** [comment]
https://github.com/moby/moby/releases/tag/v20.10.3 engine
https://github.com/docker/cli/releases/tag/v20.10.3 cli

**Comment by mdhorn** [comment]
Looking at the required changes due to the split of repos.
v20.10.5

**Comment by mdhorn** [comment]
Docker 20.10.5 now in latest release 34380.

**Comment by neben** [comment]
Could you please update to the current 20.10.6 release? Thanks!

**Comment by phmccarty** [comment]
@neben Looks like @mdhorn is working on it. In the future, feel free to open a new package update request. This helps with tracking, since this issue is already closed.

**Comment by mdhorn** [comment]
> Could you please update to the current 20.10.6 release? Thanks!

Released in Clear Linux OS 34600.

As @phmccarty  mentioned, please open a new Issue in the future rather than commenting on a Closed Issue.
If needed, you can reference an older Closed Issue in a New Issue.

**Comment by neben** [comment]
Will do, thanks for the update.
