### ISSUE TITLE
extremely high CPU temperature

### ISSUE THREAD

**Issue by beaverbusy** [clearlinux/distribution#224]
Hi all. Fresh install of clear linux. Doing any minor activity (firefox, editing files in terminal etc) the CPU temperature raises very fast up to 85C. Same machine under Arch linux/fedora/nixos, the temperature stays below 50C no matter what. Fan is blowing more than on other distros even when doing nothing.
Tried both standard and LTS kernel. Tried stopping thermald. Both didn't help. Any suggestions?

Clear Linux OS version: [cat /usr/lib/os-release] 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
VERSION_ID=25430
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"

    Bundles: 
bootloader                                                                                    
desktop                                                                                       
desktop-apps                                                                                  
desktop-assets                                                                                
desktop-autostart                                                                             
desktop-gnomelibs                                                                             
desktop-i3                                                                                    
desktop-locales                                                                               
ethtool                                                                                       
iproute2                                                                                      
kernel-lts                                                                                    
kernel-native                                                                                 
libX11client                                                                                  
network-basic                                                                                 
openssl                                                                                       
os-core                                                                                       
os-core-update                                                                                
p11-kit                                                                                       
perl-basic                                                                                    
python3-basic                                                                                 
sudo                                                                                          
sysadmin-basic                                                                                
vim                                                                                           
which                                                                                         
wpa_supplicant
xemacs

lspci:
00:00.0 Host bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31)
00:15.0 Signal processing controller: Intel Corporation Sunrise Point-H Serial IO I2C Controller #0 (rev 31)
00:15.1 Signal processing controller: Intel Corporation Sunrise Point-H Serial IO I2C Controller #1 (rev 31)
00:16.0 Communication controller: Intel Corporation Sunrise Point-H CSME HECI #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Sunrise Point-H SATA Controller [AHCI mode] (rev 31)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #3 (rev f1)
00:1c.3 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #4 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #5 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-H LPC Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-H PMC (rev 31)
00:1f.3 Multimedia audio controller: Intel Corporation Sunrise Point-H HD Audio (rev 31)
00:1f.4 SMBus: Intel Corporation Sunrise Point-H SMBus (rev 31)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)
06:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
07:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

**Comment by fenrus75** [comment]
Any chance you can run

powertop --html

And collect the output file?

**Comment by beaverbusy** [comment]
here two measurments under i3 and gnome. They are html files, but I renamed them to .txt as git wouldn't let me attach it otherwise.

[powertop.txt](https://github.com/clearlinux/distribution/files/2455672/powertop.txt)
[powertop3.txt](https://github.com/clearlinux/distribution/files/2455673/powertop3.txt)

**Comment by ahkok** [comment]
Are you using the same video adapter under the other OS's? Do you have the proprietary NVIDIA drivers installed in the other OS's?

**Comment by beaverbusy** [comment]
yes, I'm using nouveau driver under all the OSes. The lspci -k gives me the same list of drivers on all distros.
[lscpi.txt](https://github.com/clearlinux/distribution/files/2457165/lscpi.txt)

**Comment by ahkok** [comment]
Only thing I can think of is that we set the CPU governor to `performance` by default. Maybe it's worth setting it back to `powersave` or whatever the value is under the other OS's. Honestly, I'm asking "for a friend", as well ;).

**Comment by fenrus75** [comment]
11.4%  20.9  Process  [PID 1969] /usr/bin/NetworkManager

it kind of looks like NM is using 11% of cpu always?

can you check in "top" to see if there's processes with always high cpu utilization

if those exist that more than anything explains the high temp (more than cpu governors potentially, since those don't matter while idle)

**Comment by beaverbusy** [comment]
> Only thing I can think of is that we set the CPU governor to `performance` by default. Maybe it's worth setting it back to `powersave` or whatever the value is under the other OS's. Honestly, I'm asking "for a friend", as well ;). 

Great, that lowered the temperature to 55C. Thanks. I used:
`` echo powersave > /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor``
to change the governor, but after an hour it went back to `performance`, and the Temp jumped up again.
Is there a way to make the change permanent?

**Comment by mrkz** [comment]
@ahkok @fenrus75  perhaps would be nice to either go powersave/auto the same way we do with thermald? (depending on battery device). I'm experiencing also high temps on a dell xps. Will test with powersave next.

**Comment by beaverbusy** [comment]
> @ahkok @fenrus75 perhaps would be nice to either go powersave/auto the same way we do with thermald? (depending on battery device). I'm experiencing also high temps on a dell xps. Will test with powersave next.

It seems to depend on the machine: on my desktop there's no issue, on anther laptop (with bigger air vent) temp is ok too.
