### ISSUE TITLE
Please add radvd (Router Advertisement Daemon, IPv6)

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#2243]
Official package name: radvd

License (must be an OSI approved Open Source license): https://fedoraproject.org/wiki/Licensing/radvd_License

Download URL of latest release: http://www.litech.org/radvd/dist/radvd-2.19.tar.xz

Latest release date (must be recent): 2.19 

Description: The router advertisement daemon (radvd) is run by Linux or BSD systems acting as IPv6 routers. It sends Router Advertisement messages, specified by RFC 2461, to a local Ethernet LAN periodically and when requested by a node sending a Router Solicitation message. These messages are required for IPv6 stateless autoconfiguration.

**Comment by lebensterben** [comment]
Not a compatible license: https://spdx.org/licenses/

**Comment by fenrus75** [comment]
It's unfortunate about the license but there's no good way for us to comply with clause 4 so we'll not be able to include this software.

**Comment by omkhar** [comment]
Is there an alternative that can be used for ipv6 router advertisement? This seems to be the de facto used by many distributions

**Comment by thiagomacieira** [comment]
https://git.openwrt.org/?p=project/odhcpd.git

Unfortunately, it's deeply linked to the OpenWRT runtime (ubox and uci).
