### ISSUE TITLE
"Unable to install Darktable - Error: Bundle too large by 85m"

### ISSUE THREAD

**Issue by jasonbrown1965** [clearlinux/distribution#2248]
Previewing CL via USB 32gb and get this error when trying to install Darktable photo app:
"Unable to install Darktable - Error: Bundle too large by 85m"

Is this a USB limitation or something else?

**Comment by mdhorn** [comment]
The live image does not expand to use the entire USB media. This has been discussed for the installer but has not been prioritized.

If you do not want to install it on to hard drive, I'd suggest installing from a smaller USB onto the 32GB USB for experimentation.
