### ISSUE TITLE
imagemagick fails to convert file due to missing configuration file

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/distribution#225]
**Describe the bug**
When using ImageMagick to convert a `.jpg` to `.png` I get the following error.
```
$ convert ~/.backgrounds/nasa.jpg ~/.backgrounds/nasa.png
convert: unable to access configure file `magic.xml' @ warning/configure.c/GetConfigureOptions/714.
```
The same error is reported by `mogrify`:
```
$ mogrify -format png ~/.backgrounds/nasa.jpg 
mogrify: unable to access configure file `magic.xml' @ warning/configure.c/GetConfigureOptions/714.
```

Running as privileged results in the same error.

**To Reproduce**
1. get a .jpg file
2. run the above commands

**Expected behavior**
I expect it to convert the .jpg to .png

**Environment (please complete the following information):**
 - Clear Linux OS version: 25430
 - Bundles: this is from the ImageMagick bundle

**Comment by ahkok** [comment]
Yes, I've seen this before, it's essentially a `stateless` gap, and I need to fix this.

**Comment by ahkok** [comment]
`ImageMagick-7.0.8.12-24` will fix this in the next day or so.
