### ISSUE TITLE
Clear Linux Website - Broken Links and Lock-ups

### ISSUE THREAD

**Issue by froginperil** [clearlinux/distribution#2255]
I am not sure if this is the right place. If not, I apologize.

First problem is that under documentation (starting with "Concept") all three links are 404'd.

The software page locks up. My profile:
Google Chrome over Fedora 33. HW is late model Inspiron i-7.

**Comment by mdhorn** [comment]
We can investigate if you can provide the specific page and the link that gives the 404.

**Comment by paulcarroty** [comment]
* https://clearlinux.org/documentation/clear-linux/concepts
* https://clearlinux.org/documentation/clear-linux/get-started
* https://clearlinux.org/documentation/clear-linux/reference/how-to-clear-overview

**Comment by lebensterben** [comment]
This is reported in documentation repo.

**Comment by phmccarty** [comment]
Yep, it looks there are a couple issues reported about this already. Please track those issues.

https://github.com/clearlinux/clear-linux-documentation/issues/1211
https://github.com/clearlinux/clear-linux-documentation/issues/1218
