### ISSUE TITLE
34000 installer will not permit btrfs or root partition

### ISSUE THREAD

**Issue by froginperil** [clearlinux/distribution#2257]
After partitioning CLR_ROOT as btrfs and then exiting gparted, the installer displays a message that ext* or xfs is required. The installation media **does** include btrfs-convert but one has to create a root password then su then lsblk then btrfs-convert -L /dev/xxx. It seems like unnecessary additional work.

**Comment by fenrus75** [comment]
we are currently not comfortable yet with btrfs as main partition for
server usage.

**Comment by thiagomacieira** [comment]
But do we have to enforce it?

My pre-CLR server has been running with btrfs for 3 years.

**Comment by mdhorn** [comment]
Yes, we intentionally enforce this otherwise we would need to support it. 
Sorry, we can not support this request at this time.
