### ISSUE TITLE
Can't to install Linux built from sources due to /usr/bin/installkernel

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#226]
Cloned linux from Linus tree, `make defconfig`, `make`, `sudo make modules_install`, then finally `sudo make install` which fails:

```
$ sudo make install
sh ./arch/x86/boot/install.sh 4.19.0-rc7-CAIO+ arch/x86/boot/bzImage \
	System.map "/boot"
Failed to start boot.mount: Unit boot.mount not found.
Cound not find boot loader
make[1]: *** [arch/x86/boot/Makefile:155: install] Error 1
make: *** [arch/x86/Makefile:293: install] Error 2
```

The `./arch/x86/boot/install.sh` is correctly calling the installkernel distributed with Clear Linux. The script tries to start the `boot.mount` unit with `systemctl` but fails since I don't have one. See https://github.com/clearlinux/kernel-install/blob/master/installkernel#L196

**Comment by cmarcelo** [comment]
Digging into past IRC logs, it seems the boot.mount should've been automatically generated by one of the systemd generators.

For the record, my boot partition seems of the correct type:

```
$ sudo sgdisk -i 1 /dev/nvme0n1
Partition GUID code: C12A7328-F81F-11D2-BA4B-00A0C93EC93B (EFI System)
```

**Comment by cmarcelo** [comment]
If you have files in /boot, systemd doesn't pick it up, so no boot.mount.

I had some fwupd content, maybe from past mistakes on fwupd package ended up writing things there.

/usr/bin/installkernel should probably diagnose this case.

**Comment by cmarcelo** [comment]
Doesn't boot, fails with message about the vmlinuz-XXXX being Unsupported. Also `start_image: ... unsupported`.

**Comment by ahkok** [comment]
Does `defconfig` turn on `CONFIG_EFI_STUB` ?

**Comment by cmarcelo** [comment]
> Does defconfig turn on CONFIG_EFI_STUB ?

Thanks! It doesn't. Enabling it let the kernel boot but then panic later related to scheduler on I'll dig more.

For the record, I managed to boot using a copy of the current config, and that was enough for debugging the real issue I needed to :-)

**Comment by cmarcelo** [comment]
> /usr/bin/installkernel should probably diagnose this case.

Created https://github.com/clearlinux/kernel-install/issues/1 for this. Otherwise instalkernel seems to be working just fine so closing this bug.
