### ISSUE TITLE
powerdns version 4.1.x is end of life

### ISSUE THREAD

**Issue by toppk** [clearlinux/distribution#2260]
the included powerdns has been marked EOL since december 2020.  recommend to move to the new 4.4.0 or at least 4.3.x

**Comment by mdhorn** [comment]
@ahkok Objections or concerns about this update?

**Comment by ahkok** [comment]
I'll update this. I just did pdns-recursor, this one needs a little more work.

**Comment by ahkok** [comment]
Done, should be in the next release.
