### ISSUE TITLE
Update Cockpit

### ISSUE THREAD

**Issue by inmanturbo** [clearlinux/distribution#2261]
Please. It is broken. Update will fix. Fixed upstream. Just give it a bump.

**Comment by fenrus75** [comment]
I had already bumped it to 236 before I saw this... I assume 236 has the
fix you want, if not please holler with more information ;)

**Comment by inmanturbo** [comment]
Yep that's the one. Thank you. Just waiting on a release now I guess. Thanks again

**Comment by inmanturbo** [comment]
It is still not working.

https://github.com/cockpit-project/cockpit/pull/13300#issue-353675349

https://community.clearlinux.org/t/cant-select-memory-size-when-creating-vm-cockpit/5608

**Comment by romulasry** [comment]
Open an upstream bug: https://github.com/cockpit-project/cockpit/issues

**Comment by inmanturbo** [comment]
> Open an upstream bug: https://github.com/cockpit-project/cockpit/issues

This has already been fixed upstream.
