### ISSUE TITLE
Update GNU Binutils to 2.36

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2262]
https://www.phoronix.com/scan.php?page=news_item&px=GNU-Binutils-2.36-Released

GNU Binutils 2.36 is out today as the latest version of this collection of binary utilities for Linux/open-source systems.

As usual the x86_64 space for today's Binutils update is fairly eventful around supporting new CPU instructions. There is now support for AVX VNNI, HRESET, UINTR, TDX, AMX and Intel Key Locker instructions. All these additions are fairly notable for new and upcoming CPUs, especially the likes of the Advanced Matrix Extensions (AMX) and AVX (non-AVX-512) VNNI. Intel's open-source developers continue doing a good job on ensuring timely support for new CPU features in the Linux space.

On the ARM front is support for Arm's Cortex A78, A78AE, X1, R82 cores and Neoverse V1 and N2 cores. There is also support for new ARMv8.7-A extensions.

Outside of CPU specific work, the ELF linker can now handle support for the x86-64 baseline feature levels for marking the ISA level as needed. Meanwhile if using Binutils for creating PE format DLLs, it now defaults to a more secure set of DLL characteristics.

GNU Binutils 2.36 also has a variety of other new features like support for displaying the contents of LTO symbol table sections, a new option for enabling the demangling of symbol names, and other updates.

Binutils 2.36 is available from GNU.org.

https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.xz
https://ftp.gnu.org/gnu/binutils/binutils-2.36.tar.xz.sig

**Comment by phmccarty** [comment]
The update was integrated in release [34210](https://cdn.download.clearlinux.org/releases/34210/clear/RELEASENOTES).
