### ISSUE TITLE
OpenSSL man pages not found

### ISSUE THREAD

**Issue by random-user-00** [clearlinux/distribution#2264]
This is a little bit strange, but I can't find man pages for OpenSSL. 
```
$ man openssl
No manual entry for openssl
$ 
```
I am using latest version 33900. But I was not able to see the man pages with previous versions either. 
Am I missing something or I need to install another package for man pages?

**Comment by lebensterben** [comment]
`openssl-doc` is not installed by any bundle.

**Comment by phmccarty** [comment]
Thanks for the report. I will make `openssl-doc` a dependency of `openssl`. If the package was autospecced, that dependency would already be set, though the subpackage would be `openssl-man` instead of `openssl-doc`...

Should be fixed in the next release.

**Comment by phmccarty** [comment]
Fixed in release 34220
