### ISSUE TITLE
Webgpu demos do not render in Firefox (85.0 or latest nightly)

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2267]
https://webkit.org/demos/webgpu/
I set both enabled (both current firefox and nightly)

dom.webgpu.enabled = true
gfx.webrender.all = true

Same issue: it won't render (in either with above settings):

![Screenshot from 2021-01-29 17-10-08](https://user-images.githubusercontent.com/19944656/106305669-df6a6980-6254-11eb-92f3-369f7e4767cf.png)

**Comment by romulasry** [comment]
Tell me if I should upstream this bug to Mozilla.

**Comment by romulasry** [comment]
WebGL demos work fine, https://www.khronos.org/webgl/wiki/Demo_Repository

**Comment by romulasry** [comment]
Seems this is a platform specific bug: https://github.com/gpuweb/gpuweb/issues/1443

**Comment by giraphics** [comment]
Same issue 93.0b9 (64-bit) Linux Nightly Build.

**Comment by rudimvik** [comment]
Same problem here. Windows 10, Firefox 94.0.2 (64-bit). 
Flags 
dom.webgpu.enabled = true
gfx.webrender.all = true
But WebGPU not working.
![image](https://user-images.githubusercontent.com/5003821/145308306-b967068a-a88f-4899-9fed-dbef116f8826.png)

**Comment by bryteise** [comment]
Seems like this is unrelated to Clear at this time. Given the upstream efforts, I'll close this one.

**Comment by Trass3r** [comment]
Hint: check `about:support`.
