### ISSUE TITLE
"nmap" not able to find "openssl" if used with "ssl-enum-ciphers" script 

### ISSUE THREAD

**Issue by takov** [clearlinux/distribution#2271]
I am using the following command to determine all cipher suits for given server

nmap -sV --script ssl-enum-ciphers -p 21 10.10.10.10

But for unknown reason the "nmap" trows warning that "openssl" is not available. I've installed bundels "openssl", "devpkg-openssl". 
See the image below: 

![nmap-ssl](https://user-images.githubusercontent.com/3611602/106558412-57be7c80-652c-11eb-83c5-5854906dd060.png)

**Comment by ahkok** [comment]
OpenSSL support is explicitly disabled in nmap. If you want nmap with OpenSSL support, you will have to compile it manually yourself.
