### ISSUE TITLE
Mosquitto 2.0.6

### ISSUE THREAD

**Issue by KaeLL** [clearlinux/distribution#2272]
https://mosquitto.org/blog/2021/01/version-2-0-6-released/

**Comment by romulasry** [comment]
https://mosquitto.org/files/source/mosquitto-2.0.6.tar.gz
https://mosquitto.org/files/source/mosquitto-2.0.6.tar.gz.asc

**Comment by mdhorn** [comment]
This is already been updated in Clear Linux OS release 34240 or later.
