### ISSUE TITLE
Add browsers

### ISSUE THREAD

**Issue by ZemaCode** [clearlinux/distribution#2273]
I'm switching form popOs to clearLinux I used these browsers intensively I would like to use them on my new distro 
Brave
Opera
Edge

**Comment by lebensterben** [comment]
You should close this it's duplicated. And it's made clear that they won't be added.

**Comment by romulasry** [comment]
The best you can do is request them on flatpak: https://discourse.flathub.org/c/requests/5

**Comment by mdhorn** [comment]
Please use flatpak or local install for any browser except the supported Firefox.
