### ISSUE TITLE
Enable kprobes and uprobes in the kernel

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#228]
`CONFIG_KPROBE_EVENTS` and `CONFIG_UPROBE_EVENTS`. Those allow more powerful tracing and should have low to none performance impact when not used.

Used by tools like bcc (https://github.com/iovisor/bcc) and bpftrace (https://github.com/iovisor/bftrace).

Note: I'm working on packaging those tools. Even if we don't change the default kernel, they are still useful when running custom kernels with Clear.

**Comment by cmarcelo** [comment]
@miguelinux @VictorRodriguez what's a good way to verify these won't damage the performance?

As suggested on IRC, would also be good to have someone from security team to evaluate those.

**Comment by cmarcelo** [comment]
Update: `CONFIG_UPROBE_EVENTS` is now set.

**Comment by thac0** [comment]
Relates to https://github.com/clearlinux/distribution/issues/863

**Comment by thac0** [comment]
I had a chat with @fenrus75 . It doesn't look like Kprobes can, reasonably, be enabled in Clear's shipping kernel, primarily for security reasons. If a kernel developer really, truly needs Kprobes enabled, they can re-build their own kernel.

Uprobes have been enabled for a while now. Kprobes are a "no-go" for Clear. Recommend this issue be closed.
