### ISSUE TITLE
Add `xf86-input-synaptics` to `desktop-kde` or provide a separate `xf86-input-drivers` bundle

### ISSUE THREAD

**Issue by jack23247** [clearlinux/distribution#2280]
After setting up a Plasma desktop via the `desktop-kde` bundle on top of a Clear Linux server image, I am unable to install the Synaptics xf86 driver and `synclient` utility, as they are provided by the `xf86-input-synaptics` package. 

Said package is buried into `os-utils-gui`, which contains a lot of GTK software that would simply pollute the Qt environment: because of this configuration, it is currently impossible to properly use the features of a Synaptics touchpad in a Qt-only environment like KDE Plasma.

A possible solution would be adding `xf86-input-synaptics` (and possibly other XFree86 input drivers) to the `desktop-kde` package or providing a separate bundle for the Synaptics utilities and/or XFree86 input drivers.

**Comment by lebensterben** [comment]
It's no longer updated. You'd better use libinput.

**Comment by jack23247** [comment]
Thanks, that solves my issue, although it raises another. 
Is there a way to tell which packages are deprecated from `swupd` and perhaps mark them?

**Comment by lebensterben** [comment]
Not via swupd. But it's easy to find its repo, and it was last updated in 2015.
https://github.com/jiixyj/xf86-input-synaptics
