### ISSUE TITLE
Libvirt Update

### ISSUE THREAD

**Issue by bswinnerton** [clearlinux/distribution#2281]
Hello,

Libvirt was last bumped up to 5.8.0 in https://github.com/clearlinux/distribution/issues/1280. Would it be possible to update it to the latest version, [7.0.0](https://libvirt.org/news.html)?

**Comment by romulasry** [comment]
https://github.com/clearlinux/distribution/issues/1813

**Comment by mdhorn** [comment]
Duplicate https://github.com/clearlinux/distribution/issues/1813
