### ISSUE TITLE
gedit-plugins

### ISSUE THREAD

**Issue by artemas0** [clearlinux/distribution#2282]
Official package name: gedit-plugins

License (must be an OSI approved Open Source license): GPLv2

Download URL of latest release: https://gitlab.gnome.org/GNOME/gedit-plugins/-/archive/gnome-3-38/gedit-plugins-gnome-3-38.tar.bz2

Latest release date (must be recent): 2020-11-20

Description: Additional plugins for gedit. It is not very useful without them.

**Comment by fenrus75** [comment]
added

**Comment by mdhorn** [comment]
Fixed in release 34280 of Clear Linux OS
