### ISSUE TITLE
Kernel 5.11 update

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#2283]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/

**Comment by mdhorn** [comment]
We do monitor the release of new kernels and update them as frequently as we can.
A new GitHub Issue is not needed for each new kernel. thank you.

**Comment by ZVNexus** [comment]
> We do monitor the release of new kernels and update them as frequently as we can.
> A new GitHub Issue is not needed for each new kernel. thank you.

However it's been over two months, were there any problems with updating, regressions?

**Comment by ZVNexus** [comment]
@mdhorn It's understandable that an issue shouldn't be raised for each minor revision but the latest release is now 5.12.x and 5.10.x is now marked as "longterm", 2 major revisions have gone by. Could the native package please be updated?

**Comment by fenrus75** [comment]
it got updated a few days ago and the release will go out shortly assuming
QA passes

**Comment by ZVNexus** [comment]
Great news, thanks.
