### ISSUE TITLE
libmozjs-78.so takes 511MB!

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2287]
```bash
$ du -sh /usr/lib64/libmozjs-78.so
511M    /usr/lib64/libmozjs-78.so
```

This is insane, guess there's some debug data inside. Installed version: `34290`

**Comment by phmccarty** [comment]
The spec file instructs rpm to not strip debug symbols: https://github.com/clearlinux-pkgs/mozjs78/blob/eb6021e217/mozjs78.spec#L42. So, your observation is correct.

Not sure why we don't strip the symbols... Looks like we started doing so in the `mozjs38` with https://github.com/clearlinux-pkgs/mozjs38/commit/01a800bc42. So, a while ago :-)

**Comment by paulcarroty** [comment]
@phmccarty why stripping isn't enabled yet? Any pitfalls?

**Comment by phmccarty** [comment]
Looks good, will push. In the next build, libmozjs-78.so will shrink to 31MB :-)
