### ISSUE TITLE
add support for CONFIG_STMMAC_PCI in clear linux server and clear linux pxe

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#2289]
Hi Clear Linux Team,

I need this module to start some network cards in clear linux.

CONFIG_STMMAC_PCI: STMMAC PCI bus support
STMMAC PCI bus support found in drivers/net/ethernet/stmicro/stmmac/Kconfig

CONFIG_STMMAC_ETH: STMicroelectronics Multi-Gigabit Ethernet driver
STMicroelectronics Multi-Gigabit Ethernet driver found in drivers/net/ethernet/stmicro/stmmac/Kconfig

Thanks.

**Comment by ionutnechita** [comment]
is there any new update?

**Comment by fenrus75** [comment]
made the change; will be in the next release

**Comment by ionutnechita** [comment]
thanks.

**Comment by mdhorn** [comment]
Released in Clear Linux OS 34340

**Comment by ionutnechita** [comment]
Hi @mdhorn,

cat config-5.10.19-1030.native  | grep STMMAC
# CONFIG_STMMAC_ETH is not set

Is not integrated?

root@clr-live/usr/lib/modules/5.10.19-1030.native # cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=34340
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
BUILD_ID=34340

**Comment by ionutnechita** [comment]
Hi @fenrus75,

Please reopen this ticket and verify this latest image.

**Comment by phmccarty** [comment]
This was the config change meant to fix the issue:

https://github.com/clearlinux-pkgs/linux/commit/4aa7ac9d2626f96b2a7bc08ed8785c70d850b03a

So it looks like `CONFIG_STMMAC_ETH` would need to be explicitly enabled as well?

**Comment by ionutnechita** [comment]
Hi @phmccarty,

CONFIG_STMMAC_ETH=m

It's fine for me for this configuration.

**Comment by bwarden** [comment]
Enabled CONFIG_STMMAC_ETH, should show up in a few days.

**Comment by phmccarty** [comment]
CONFIG_STMMAC_ETH added in the [34350](https://cdn.download.clearlinux.org/releases/34350/clear/RELEASENOTES) release. (See above for link to the commit.)

**Comment by ionutnechita** [comment]
Now I see the interfaces on the motherboard.

Thanks for support.
