### ISSUE TITLE
OpenVPN

### ISSUE THREAD

**Issue by tixoi** [clearlinux/distribution#2290]
Hello,
OpenVPN 2.5.1 was released on 24 February, 2021.

thank you for the update in advance

**Comment by phmccarty** [comment]
I integrated openvpn 2.5.1 on Friday, so it will be in the next release.

**Comment by phmccarty** [comment]
Merged in the [34340](https://cdn.download.clearlinux.org/releases/34340/clear/RELEASENOTES-34320-to-34340) release.

**Comment by tixoi** [comment]
Thanx
