### ISSUE TITLE
mic not recognized on Lenovo t14

### ISSUE THREAD

**Issue by da0ist** [clearlinux/distribution#2293]
Version: BUILD_ID=34340

Reproduce: Install Clear Linux

Expected: working mic

Seems everything works but the mic. Any ideas?

jeward@clr-c56a1b4ce0524f619bc6d17dc701d160 ~ $ lspci|grep -i audio
07:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 1637
07:00.5 Multimedia controller: Advanced Micro Devices, Inc. [AMD] Raven/Raven2/FireFlight/Renoir Audio Processor (rev 01)
07:00.6 Audio device: Advanced Micro Devices, Inc. [AMD] Family 17h (Models 10h-1fh) HD Audio Controller

**Comment by bwarden** [comment]
Enabled SND_SOC_AMD_RENOIR_MACH; should show up in a few days.

**Comment by phmccarty** [comment]
Merged in the [34350](https://cdn.download.clearlinux.org/releases/34350/clear/RELEASENOTES) release. (See above for link to the commit.)
