### ISSUE TITLE
stmmac - intel-eth-pci - Tx DMA map failed

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#2295]
Hi Clear Linux Team,

After integrating the 2 modules; which are now present in the build.

After booting, in dmesg I see a lot of error messages. 
And after a few seconds the messages reappear, which floods the series and dmesg.
...
intel-eth-pci 0000:00:1d.2 enp0s29f2: Link is Up - 1Gbps/Full - flow control rx/tx
intel-eth-pci 0000:00:1d.2: swiotlb buffer is full (sz: 90 bytes), total 32768 (slots), used 32768 (slots)
intel-eth-pci 0000:00:1d.2 enp0s29f2: Tx DMA map failed
intel-eth-pci 0000:00:1d.2: swiotlb buffer is full (sz: 90 bytes), total 32768 (slots), used 32768 (slots)
intel-eth-pci 0000:00:1d.2 enp0s29f2: Tx DMA map failed
intel-eth-pci 0000:00:1d.2: Fail to register stmmac-clk
intel-eth-pci 0000:00:1d.2 enp0s29f2: PHY [stmmac-3:01] driver [Marvell 88E1510] (irq=POLL)
...

[dmesg.txt](https://github.com/clearlinux/distribution/files/6090206/dmesg.txt)
[journalctl.txt](https://github.com/clearlinux/distribution/files/6090213/journalctl.txt)

Is there a issue with the intel-eth-pci driver?

**Comment by mdhorn** [comment]
@miguelinux Can you look at this or have any insight?

**Comment by ionutnechita** [comment]
Hi @mdhorn, @miguelinux,

I tested with kernel version 5.12.0-rc3 from linux-next / kernel/git/torvalds/linux.git.
I didn't notice those error messages.
But I'll test again to be sure.

**Comment by Krishnendhu-Prakasan** [comment]
Is this still persistent? Whilst booting the latest clearlinux on a EHL , I get the same issue

**Comment by ionutnechita** [comment]
I try to testing now with 5.15.15.

Will be check and write feedback on this ticket.

Thanks.

**Comment by ionutnechita** [comment]
Kernel 5.15.5:

[  123.488142] ================================================================================
[  123.489403] UBSAN: shift-out-of-bounds in drivers/net/ethernet/stmicro/stmmac/dwmac4_core.c:224:12
[  123.490645] shift exponent 40 is too large for 32-bit type 'unsigned int'
[  123.492122] ================================================================================
[  128.382565] sof-audio-pci-intel-tgl 0000:00:1f.3: error: cl_copy_fw: timeout HDA_DSP_SRAM_REG_ROM_STATUS read
[  128.384078] sof-audio-pci-intel-tgl 0000:00:1f.3: error: extended rom status:  0x80000012 0x2c 0x0 0x0 0x0 0x0 0x25401c8 0x0
[  128.385384] sof-audio-pci-intel-tgl 0000:00:1f.3: error: load fw failed ret: -110
[  128.386758] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to reset DSP
[  128.388077] sof-audio-pci-intel-tgl 0000:00:1f.3: error: failed to boot DSP firmware -110
[  128.440070] sof-audio-pci-intel-tgl 0000:00:1f.3: error: hda_dsp_core_reset_enter: timeout on HDA_DSP_REG_ADSPCS read
[  128.441480] sof-audio-pci-intel-tgl 0000:00:1f.3: error: dsp core reset failed: core_mask 1
[  128.443630] sof-audio-pci-intel-tgl 0000:00:1f.3: error: sof_probe_work failed err: -110


[dmesg-5.15.15-android-lowlatency-1.txt](https://github.com/clearlinux/distribution/files/7906943/dmesg-5.15.15-android-lowlatency-1.txt)

**Comment by ionutnechita** [comment]
Not i notice this issue with this kernel.

I think this is resolved.

**Comment by ionutnechita** [comment]
I close this ticket, is resolved in 5.15+ version.

A good day.
