### ISSUE TITLE
Cannot open GNOME settings.

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#2297]
Here is a report from dmesg:

[ 4887.781852] traps: gnome-control-c[76206] trap int3 ip:7fb6f099cdb1 sp:7ffd55bf7860 error:0 in libglib-2.0.so.0.6600.7[7fb6f092b000+f0000]
[ 4887.874283] crashprobe[76249]: segfault at 10 ip 00007fa5ada94728 sp 00007ffd103378d0 error 4 cpu 6 in libdw-0.183.so[7fa5ada56000+45000]
[ 4887.874290] Code: ff c0 48 39 45 18 75 e9 eb e3 31 c0 80 7d c4 02 75 18 2e 2e 49 8b 14 c0 48 0f ca 49 89 14 c4 48 ff c0 48 39 45 18 75 ea eb c3 <49> 8b 14 c0 49 89 14 c4 48 ff c0 48 39 45 18 75 ef eb b0 b0 01 48
[ 4887.874302] Process 76249(crashprobe) has RLIMIT_CORE set to 1
[ 4887.874303] Aborting core

**Comment by ZVNexus** [comment]
Mar 05 10:06:25 prism gnome-photos[73694]: Settings schema 'org.freedesktop.Tracker.Miner.Files' is not installed
Mar 05 10:06:25 prism gnome-control-c[73786]: The program 'gnome-control-center' received an X Window System error.

Seems to be the reason

**Comment by ZVNexus** [comment]
Full log here: https://gist.githubusercontent.com/ZVNexus/998e649f3f03066481ea03158d5d4f9f/raw/9101e729728ec624a0ba8d29775b5919cf490341/gistfile1.txt

**Comment by mdhorn** [comment]
What version of Clear Linux OS are you using?
```
$ swupd info
Distribution:      Clear Linux OS
Installed version: 34370
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

```
Anything useful if you attempt to start it from the command line?
`$ gnome-control-center`

**Comment by mdhorn** [comment]
Besides the version of Clear Linux OS, it would be helpful to have the output of
`gnome-control-center --verbose
`

**Comment by ZVNexus** [comment]
Seemingly only happens with custom changes to environment, in any case doesn't seem like a CLR issue.
