### ISSUE TITLE
devpkg-libglade bundle is missing

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2299]
Please add devpkg-libglade bundle.

**Comment by phmccarty** [comment]
Normally we autogenerate bundles with the `devpkg-` prefix, but we skip autogeneration in the case where a package's development files (usually in a `-dev` subpackage) are not present in any other bundle.

This condition applies to the libglade development files, so we would have to add the bundle manually.

However, looking at the request from a different angle, isn't libglade deprecated upstream? I think all GNOME packages have migrated away from using libglade, which would explain why no other bundle includes it. The state of upstream appears to be inactive; the last release was from 2009. It looks like `xscreensaver` was the last package in Clear to require it, but it recently dropped the dependency...

**Comment by marioroy** [comment]
Oh! That explains why ```devpkg-libglade``` isn't there. I installed ```libglade``` using RPM files in order to build ```cairo-clock```. It was a suggestion in a GNOME forum to run ```cairo-clock``` with the second hand enabled as a way to keep mutter 3.38.3 stable. Fortunately, this suggestion is not necessary with the next Clear Linux build. Mentioned [here](https://github.com/clearlinux/distribution/issues/2302), that will include mutter 3.38.4.

Thank you.

**Comment by phmccarty** [comment]
Okay, thanks for clarifying. I will close this request, since it looks like your issue should be fixed in the latest release
