### ISSUE TITLE
Not able to use redsocks anymore

### ISSUE THREAD

**Issue by yongfengdu** [clearlinux/distribution#230]
**Describe the bug**
I was using redsocks+iptables rules as transparent proxy for internet access, that works fine at version 24420, but doesn't work on 25170/25180. Not sure which is the first version having this problem.
I noticed the auto proxy feature, https://clearlinux.org/features/autoproxy
However, that only works for curl, I still need to set the proxy for wget/pip etc.

**To Reproduce**
1. swupd bundle-add network-basic
2. edit /etc/redsocks.sh
3. configure iptables rules like this:
iptables -t nat -N REDSOCKS || true
iptables -t nat -F REDSOCKS
iptables -t nat -A REDSOCKS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A REDSOCKS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A REDSOCKS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A REDSOCKS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A REDSOCKS -p tcp -j DNAT --to-destination 127.0.0.1:7777
iptables -t nat -A REDSOCKS -p udp -j DNAT --to-destination 127.0.0.1:8888
iptables -t nat -A OUTPUT -p tcp -j REDSOCKS
iptables -t nat -A PREROUTING -p tcp -j REDSOCKS

4. using curl or wget to access a url, the redsocks doesn't get connection request.

**Expected behavior**
Should be able to use redsocks transparent proxy

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
VERSION_ID=25530
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by bryteise** [comment]
@yongfengdu What is the status of the redsocks service? Do you the logs show any problems with redsocks or something that looks abnormal compared to its usual output?

**Comment by yongfengdu** [comment]
redsocks is up and running, there is no error message reported.

When I initially installed redsocks with 24420, everything is OK, but after I did a "swupd update" and reboot, make sure that redsocks is running and iptables is set, the transparent proxy doesn't work anymore.

Usually the redsocks will print a log in the log file for new internet connection, I didn't see the logs at version 25170 and later, looks like iptables  didn't forward the traffic to redsocks.

**Comment by puneetse** [comment]
If you do an `iptables -L` does it show your REDSOCKS chain as expected? iptables rules not being saved properly has tripped me up in the past.

**Comment by yongfengdu** [comment]
Yes, the "iptables -t nat -L" shows expected REDSOCKS chain.
I've also tried to put log into iptables with "-j LOG --log-prefix", but didn't find the clearlinux message file :)

**Comment by yongfengdu** [comment]
After upgrade to version 25620 this morning, the redsocks works again.
I think we can close this issue unless you need further info to debug.
====================
swupd info
Installed version: 25620
Version URL:       https://download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

# tail /var/log/redsocks.log
1539656917.023727 notice main.c:165 main(...) redsocks started, conn_max=512
1539656929.901387 info redsocks.c:1243 redsocks_accept_client(...) [10.0.0.30:60314->61.135.169.121:80]: accepted
1539656929.992278 debug redsocks.c:341 redsocks_start_relay(...) [10.0.0.30:60314->61.135.169.121:80]: data relaying started
1539656930.087333 info redsocks.c:671 redsocks_drop_client(...) [10.0.0.30:60314->61.135.169.121:80]: connection closed

**Comment by yongfengdu** [comment]
BTW, need to comment out the user=nobody in service file to avoid this start error:
----------------------
Oct 16 03:05:34 clear-2 systemd[1]: Starting Transparent redirector of any TCP connection to proxy using your firewall...
Oct 16 03:05:34 clear-2 systemd[1]: redsocks.service: Control process exited, code=exited status=1
Oct 16 03:05:34 clear-2 systemd[1]: redsocks.service: Control process exited, code=exited status=1
Oct 16 03:05:34 clear-2 systemd[1]: redsocks.service: Failed with result 'exit-code'.
Oct 16 03:05:34 clear-2 systemd[1]: Failed to start Transparent redirector of any TCP connection to proxy using your firewall.
----------------------
/lib/systemd/system/redsocks.service
# User=nobody
