### ISSUE TITLE
Cannot launch gnome-photos from the live image and installation

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2301]
Gnome-photos core dumps in Clear Linux 34350 and 34370. Did not test earlier Clear Linux releases.
```
$ gnome-photos 

(org.gnome.Photos:1769): Tracker-CRITICAL **: 03:28:57.295: Could not create proxy on the D-Bus session bus, Error calling StartServiceByName for org.gnome.Photos.Tracker1.Miner.Files: Failed to execute program org.gnome.Photos.Tracker1.Miner.Files: No such file or directory

(org.gnome.Photos:1769): Tracker-CRITICAL **: 03:28:57.296: Could not create proxy on the D-Bus session bus, Error calling StartServiceByName for org.gnome.Photos.Tracker1.Miner.Extract: Failed to execute program org.gnome.Photos.Tracker1.Miner.Extract: No such file or directory

(org.gnome.Photos:1769): GLib-GIO-ERROR **: 03:28:57.297: Settings schema 'org.freedesktop.Tracker.Miner.Files' is not installed
Trace/breakpoint trap (core dumped)
```
I also installed the tracker-miners bundle and ran tracker3 -s.

**Comment by phmccarty** [comment]
Thanks for the report. We will investigate.

**Comment by fenrus75** [comment]
devpkg wavpack was added on Feb 24th

**Comment by marioroy** [comment]
I searched for `devpkg-wavpack` in the list of bundles. The bundle went hiding. I forgot about the original request #2559. The recent request #2671 is a duplicate.
[https://docs.01.org/clearlinux/latest/reference/bundles/bundles.html](https://docs.01.org/clearlinux/latest/reference/bundles/bundles.html)

**Comment by marioroy** [comment]
I see the `devpkg-wavpack` bundle. Thank you. I will update ffmpeg-on-clear-linux to install it.
