### ISSUE TITLE
GNOME frame timings issues resulting in stuck clients in certain situations

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2302]
I experience these issues running GNOME in Clear Linux, mentioned in [general discussions](https://community.clearlinux.org/t/gnome-developers-resolved-an-annoying-bug-with-fix-frame-timings/6105). What a relief to know that GNOME developers resolved this.
```text
Mar 12 00:31:30 clr-linux /usr/libexec/gdm-x-session[4602]: (EE) event4  - Kinesis Freestyle Edge Keyboard: client bug: event processing lagging behind by 16ms, your system is too slow

Mar 12 00:31:30 clr-linux /usr/libexec/gdm-x-session[4602]: (EE) event4  - Kinesis Freestyle Edge Keyboard: client bug: event processing lagging behind by 16ms, your system is too slow

Mar 12 03:20:06 clr-linux /usr/libexec/gdm-x-session[1276]: (II) event11 - Logitech M705: SYN_DROPPED event - some input events have been lost.

Mar 12 03:20:07 clr-linux /usr/libexec/gdm-x-session[1276]: (EE) event11 - Logitech M705: client bug: event processing lagging behind by 12ms, your system is too slow

lots of these
```

This is more or less a place-holder so not forgotten for the fix: [Fix frame timings resulting in stuck clients in certain situations](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1754).

**Comment by lebensterben** [comment]
So this is a package update request?

**Comment by marioroy** [comment]
Yes.

**Comment by marioroy** [comment]
I tried the patches Red Hat applied recently for Fedora 33. I captured the steps taken [here](https://community.clearlinux.org/t/gnome-developers-resolved-an-annoying-bug-with-fix-frame-timings/6105/3?u=marioroy) on getting mutter reliable on my system with a NVIDIA GPU and proprietary driver.

**Comment by clojj** [comment]
+1 for this fix.. I think it's ok not having the bleading-edge kind of Gnome support in CL anymore (ref. to that announcement in the Forums), but easy(?) fixes and basic support for 3.38 would be very nice

**Comment by marioroy** [comment]
Yeah! GNOME [mutter 3.38.4.tar.xz](https://download.gnome.org/sources/mutter/3.38/mutter-3.38.4.tar.xz) has been released containing the fixes. Can you update mutter to 3.38.4, please. Thank you.

**Comment by phmccarty** [comment]
We updated to mutter 3.38.4 earlier today, so it will land in the next build.

**Comment by phmccarty** [comment]
The update to mutter 3.38.4 landed in release 34420 from today. If the update still doesn't resolve your issue, please reopen, or file a new issue.
