### ISSUE TITLE
(solved) Wifi not detected on Clear - Intel Stick STK1AW32SC - Card Intel 7265

### ISSUE THREAD

**Issue by Shogu** [clearlinux/distribution#2313]
Hi

Clear OS do not detect wifi on my Intel Stick.

The card is Intel 7265

I already pasted the official driver (downloaded on Intel website) in /etc/firmware without any success. Same fail with the /var/firmware folder.

A cannot use swupd to install network-manager or hardware-wifi etc cause the Intel Stick do not have Ethernet port. 

Any advice for me?

Thanks a lot.

Ogu

Solved after reset of Bios parameters (except 32 bit option turn on 64 bits) and pasting drivers to some /firmware folder (do not remember precisely which place)

**Comment by paulcarroty** [comment]
>  turn on 64 bits

Guess this one, the same wifi chipset works out the box in my laptop.

**Comment by phmccarty** [comment]
The reporter updated the issue description with the resolution. Quoted below:

> Solved after reset of Bios parameters (except 32 bit option turn on 64 bits) and pasting drivers to some /firmware folder (do not remember precisely which place)

Closing
