### ISSUE TITLE
libc-client-devel

### ISSUE THREAD

**Issue by aqdun** [clearlinux/distribution#2317]
Libc client devel is not available in clearlinux and needs help.

**Comment by lebensterben** [comment]
https://cdn.download.clearlinux.org/releases/34440/clear/x86_64/os/Packages/glibc-dev-2.31-344.x86_64.rpm

Is this what you need?

**Comment by thiagomacieira** [comment]
Can you explain what "libc client devel" should contain? Please compare that to the "c-basic" bundle and comment on what needs to change there.
