### ISSUE TITLE
Please add `kdiagram-dev` package

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2319]
`kdiagram` package is already included: https://github.com/clearlinux-pkgs/kdiagram
But I need the headers to build something.

Thanks.

**Comment by phmccarty** [comment]
To clarify, are you requesting a new bundle (not a package), like `devpkg-kdiagram`, that would provide the headers?

I'm asking because `kdiagram-dev` is already a subpackage of `kdiagram` and provides the headers.

**Comment by lebensterben** [comment]
Yes `devpkg-kdiagram` please.

**Comment by phmccarty** [comment]
Great, thanks for clarifying. I added a new `devpkg-kdiagram` bundle. It should be available within a couple days.

**Comment by lebensterben** [comment]
Thanks
