### ISSUE TITLE
The GNU C Library version 2.33 is now available

### ISSUE THREAD

**Issue by aqdun** [clearlinux/distribution#2323]
/usr/lib64/haswell/libc.so.6: version `GLIBC_2.33' not found
I request to update Glibc2.33.

**Comment by thiagomacieira** [comment]
Already in the works, but a glibc update takes a lot of time to test since it basically affects everything except statically-linked packages. Your request is not a bug report.

**Comment by aqdun** [comment]
Thank you for your answer, I have found a solution! Thank you again for your help!
