### ISSUE TITLE
GNOME 40

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#2324]
The current stable branch is now on GNOME 40, released on March 24th.

**Comment by fenrus75** [comment]
We have made the decision to wait a bit on this big change until the
ecosystem has caught up with this big change.
(think +- 4 to 6 weeks at least)

**Comment by phmccarty** [comment]
> The current stable branch is now on GNOME 40, released on March 24th.

Despite the release announcement, not all GNOME packages in Clear Linux OS have made v40 (or 3.40.0 (?) ) releases yet, so it is best for us to wait a while before updating the environment.

**Comment by lebensterben** [comment]
Could we have libgtk-4.0 first?

**Comment by fenrus75** [comment]
sure we have the package; we should turn it into a bundle

**Comment by phmccarty** [comment]
A `devpkg-gtk4` bundle will be available in 34350 or newer.

**Comment by lebensterben** [comment]
Thanks!

**Comment by phmccarty** [comment]
We updated packages for GNOME 40 in the 34550 release.
