### ISSUE TITLE
Add MongoDB community 

### ISSUE THREAD

**Issue by debendraoli** [clearlinux/distribution#2327]
Official package name:

License (must be an OSI approved Open Source license):
Server Side Public License
Download URL of latest release:
https://www.mongodb.com/download-center/community/releases
Latest release date (must be recent):
 Feb 16, 2021
Description:

**Comment by fenrus75** [comment]
Server Side Public License --- that's not OSI approved

**Comment by lebensterben** [comment]
Read the license requirement.
SSPL is not approved.

**Comment by phmccarty** [comment]
We cannot add this package, for reasons mentioned in the previous comments.
