### ISSUE TITLE
Set I/O scheduler to get better disk I/O performance for Hyper-V guests

### ISSUE THREAD

**Issue by v-pham** [clearlinux/distribution#233]
**Describe the solution you'd like**
For Microsoft Hyper-V VMs, I would like to add a kernel parameter to set the I/O scheduler to NOOP (elevator=noop). This is the Microsoft recommendation to get better disk I/O performance for Linux guests. 

(Ref: https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-for-running-linux-on-hyper-v#use-io-scheduler-noop-for-better-disk-io-performance).

**Describe alternatives you've considered**
I set this on all Linux VMs by running a script during the provisioning process that mounts the EFI boot partition and appends "elevator=noop" to the kernel parameter cmdline via sed. It's not that big of a deal but I thought it would be nice for this be included so everyone could benefit.

**Additional context**
This described change was submitted as a pull request (https://github.com/clearlinux-pkgs/linux-hyperv/compare/master...v-pham:patch-1) but I was asked to re-direct the request here.

**Comment by fenrus75** [comment]
yeah good idea.

but rather than a kernel command line... the default scheduler is set in the kernel config file, so
I just put the following into our build system

-CONFIG_DEFAULT_CFQ=y
-# CONFIG_DEFAULT_NOOP is not set
-CONFIG_DEFAULT_IOSCHED="cfq"
+# CONFIG_DEFAULT_CFQ is not set
+CONFIG_DEFAULT_NOOP=y
+CONFIG_DEFAULT_IOSCHED="noop"

**Comment by iphutch** [comment]
@fenrus75, @v-pham  is there anything else pending after this change, or can I close as fixed?

**Comment by v-pham** [comment]
I'm good so it can be closed from my end. Thanks, guys!
