### ISSUE TITLE
proj and proj-dev are part of maker-gis. They should be available as their own bundles.

### ISSUE THREAD

**Issue by random-user-00** [clearlinux/distribution#2334]
Official package name: proj, proj-dev

License (must be an OSI approved Open Source license): X/MIT open source license

Download URL of latest release: https://proj.org/download.html

Latest release date (must be recent): 2021-03-01

Description: PROJ is a generic coordinate transformation software that transforms geospatial coordinates from one coordinate reference system (CRS) to another. This includes cartographic projections as well as geodetic transformations.

**Note**:  `proj`, `proj-dev` bundles already available as a package inside `maker-gis` (https://clearlinux.org/software/bundle/maker-gis), but it can't be installed independently. I have to install entire bundle `maker-gis`, which is not a problem but it makes sense to make it available as their own bundles.

**Comment by mdhorn** [comment]
We could create a bundle with these two packages, but it would be held at 7.2.1 as there is an incompatibility with 8.0.0 currently. Several packages which are built with proj in Clear Linux failed to build with 8.0.0.

**Comment by phmccarty** [comment]
We just added a new `devpkg-proj` bundle. It will be available in release 34530 or newer.

**Comment by phmccarty** [comment]
The `devpkg-proj` bundle was added in the 34350 release from today.
