### ISSUE TITLE
Possible issue with madvise-bss.patch in glibc package

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#2338]
As reported in a [comment](https://github.com/clearlinux-pkgs/glibc/commit/dc8b8460ba2a1d428dbe84a9e2236162d13edb53#commitcomment-49565096) at the package repo, feedback is requested about the patch `madvise-bss.patch` to glibc:

> @fenrus75 FYI We're not clear on the security implications of this post-Spectre. https://bugzilla.mozilla.org/show_bug.cgi?id=1705045#c1

**Comment by fenrus75** [comment]
it's not a security issue.. this madvise is still honoring system policy.

we can drop the patch on glibc rebase if it causes issues

**Comment by gcp** [comment]
We have a patch for Firefox that will return EPERM in this case. For reasons hinted in the bug, allowing the syscall seems like it would allow Spectre-like attacks via KSM, which we'd never want between sandboxed processes.

**Comment by phmccarty** [comment]
We ended up disabling madvise-bss.patch (reference: https://github.com/clearlinux-pkgs/glibc/commit/bfd947abd79cd956bc8a64623a6db67ae1a454fb) when in updated to glibc 2.33 in release 34560. Closing.
