### ISSUE TITLE
Power beats 3 headset mic not detected.

### ISSUE THREAD

**Issue by lkmishra** [clearlinux/distribution#2339]
Power beats 3 mic not detected in sound settings. Only headphone is detected and sound is great. But can't use the mic. Windows on the same machine works fine and other Bluetooth Sony headphones works fine.

Thanks

**Comment by mdhorn** [comment]
Is this device known to work on any other Linux distribution?

**Comment by lkmishra** [comment]
> Is this device known to work on any other Linux distribution?

Not tried yet. Will let you know.

**Comment by thiagomacieira** [comment]
You may need to switch the mode in Pulseaudio to HFP in order to get the microphone.
![Screenshot_20210507_113803](https://user-images.githubusercontent.com/4109772/117494085-b2e77d00-af28-11eb-9a7a-fe4c58d601a4.png)

Bluetooth devices cannot transmit microphone over A2DP.

**Comment by lkmishra** [comment]
![Screenshot from 2021-05-08 00-23-54](https://user-images.githubusercontent.com/30885339/117517478-0e028980-af94-11eb-97aa-e008198ebcb6.png)

Handsfree Head unit is not visible for beats headphone. Please reopen the case.

Thanks
