### ISSUE TITLE
clr-k8s-example swapfile

### ISSUE THREAD

**Issue by mmoerz** [clearlinux/distribution#2340]
preflight does not remove /var/swapfile.swap created by systemd.
Problem exists on any clearlinux version >= 34000. (don't know if problem started lower)

/usr/share/clr-k8s-examples/setup_system.sh checks for device based swap:
swapcount=$(sudo grep '^/dev/\([0-9a-z]*\).*' /proc/swaps | wc -l)

I'd suggest to ask systemctl directly for the correct service like:
systemctl --type swap -o json | sed -ne 's/.*"unit":"\([a-zA-Z0-9\._-]\+\)".*/\1/p'

**Comment by mdhorn** [comment]
This was already fixed in the upstream, but no new release has been cut yet. 
https://github.com/clearlinux/cloud-native-setup/pull/333

I'll request a new release to update the distro.

**Comment by mdhorn** [comment]
New release should be in the next Clear Linux OS release 34550 or higher next week.

**Comment by mdhorn** [comment]
Updated in release 34550.
