### ISSUE TITLE
[Samba] Error loading module streams_xattr.so

### ISSUE THREAD

**Issue by hacketiwack** [clearlinux/distribution#2341]
Current situation
In the logs of Samba, I get the following error message:
```
[2021/04/23 05:35:08.744472,  0] ../../source3/smbd/vfs.c:185(vfs_init_custom)
  error probing vfs module 'streams_xattr': NT_STATUS_UNSUCCESSFUL
[2021/04/23 05:35:08.744491,  0] ../../source3/smbd/vfs.c:397(smbd_vfs_init)
  smbd_vfs_init: vfs_init_custom failed for streams_xattr
[2021/04/23 05:35:08.744500,  0] ../../source3/smbd/service.c:637(make_connection_snum)
  make_connection_snum: vfs_init failed for service IPC$
[2021/04/23 05:35:08.746047,  0] ../../lib/util/modules.c:49(load_module)
  Error loading module '/usr/lib64/samba/vfs/streams_xattr.so': /usr/lib64/samba/libsamba-debug-samba4.so: version `SAMBA_4.14.3' not found (required by /usr/lib64/samba/vfs/streams_xattr.so)
```

Expected situation
I expect to have the library streams_xattr.so to be available, so it doesn't fill the logs with this error.

Versions
Clear Linux version: 34540
Samba: 4.14.3

**Comment by mdhorn** [comment]
Samba was updated to version 4.14.3 in Clear Linux OS release 34540.

You may have to restart samba to clear this problem:
`systemctl restart samba.service`

**Comment by hacketiwack** [comment]
Rebooting the system seems to have it solved.
But now, I have this error message:
```
[2021/04/23 19:26:28.842149,  0] ../../source3/lib/adouble.c:2153(ad_open_rsrc)
  ad_open_rsrc: SMB_VFS_CREATE_FILE failed
```

**Comment by mdhorn** [comment]
> Rebooting the system seems to have it solved.
> But now, I have this error message:
> 
> ```
> [2021/04/23 19:26:28.842149,  0] ../../source3/lib/adouble.c:2153(ad_open_rsrc)
>   ad_open_rsrc: SMB_VFS_CREATE_FILE failed
> ```

Are you seeing a functional issues releated to this error message?
What occurring when the error is generated?

**Comment by hacketiwack** [comment]
I can't notice anything.
Actually, I came to look at the logs because when copying large amount of files - thousands of files - I got files mixed up with others and some being copied with a size of 0 ko. I'm copying files from a macOS machine.
So, you can imagine that I wasn't really confident on the reliability of the setup.

The configuration I have is the following:

```
[Global]
vfs objects = btrfs fruit streams_xattr
fruit:metadata = stream
fruit:model = RackMac
fruit:posix_rename = yes
fruit:veto_appledouble = no
fruit:wipe_intentionally_left_blank_rfork = yes
fruit:delete_empty_adfiles = yes
mangled names = no

[Common]
path = /mnt/storage/common
read only = no
guest ok = no
browsable = yes
valid users = @share
force group = +share
```

**Comment by hacketiwack** [comment]
The problem seems to be solved for now.
I'm closing the issue.

However, I still got these messages from time to time:

`_mdssvc_open: Couldn't create policy handle for Common`

Does anyone know what could cause it?
