### ISSUE TITLE
Blog errors out with 403 Forbidden

### ISSUE THREAD

**Issue by Oberfail** [clearlinux/distribution#2342]
When you visit https://clearlinux.org/about and click on "Our blogs keep you in touch with our latest releases and thinking » " You get redirected to https://stg.clearlinux.org/announcements which throws out a 403 Forbidden Error.

I think it should redirect to https://clearlinux.org/news-blogs nowdays.

**Comment by mdhorn** [comment]
Escalated to documentation team; this is now corrected.
