### ISSUE TITLE
GVFS for smb/CIFS no longer working in Gnome 40 

### ISSUE THREAD

**Issue by mns6070** [clearlinux/distribution#2345]
My system auto updated to Gnome 40 and now files/nautilus will not load the gvfs module to access smb/CIFS shares. Prior to Gnome 40 this worked perfectly. The gvfs module appears to be working correctly because I successfully mount a sftp share without an issue. Any ideas on how to restore the functionality?

**Comment by mdhorn** [comment]
The next release of Clear Linux OS (34570 or higher) will have the latest releases of Samba and GVFS built against the new glibc (which was also in 34560).  Please test after the next release and if problems persist please include any samba errors from the journal to help provide so more insight.

**Comment by mns6070** [comment]
Updated and still have the same problem.

Here's what I see in the log:
 
`May 05 02:12:40 mitchell-1950x gvfsd[1697]: Kerberos auth with 'mitchell@WORKGROUP' (WORKGROUP\mitchell) to access '192.168.1.1' not possible`

Not sure what Gnome 40 is doing differently because this worked up until then.

**Comment by mns6070** [comment]
For reference, I am following the documentation found here: [https://docs.01.org/clearlinux/latest/tutorials/smb-desktop.html](url)

**Comment by mns6070** [comment]
I updated to 34730 and it is now working again.

**Comment by phmccarty** [comment]
Thanks for the update. If you run into the problem again in the future, feel free to open a new issue.
