### ISSUE TITLE
Error in loading nano's RC

### ISSUE THREAD

**Issue by ZVNexus** [clearlinux/distribution#2350]
Error in /usr/share/defaults/nano/nanorc on line 147: Unknown option "smooth"

https://github.com/clearlinux-pkgs/nano/commit/46cf038628f76ae33eac269605e093cda3c5b01b

"options: retire the obsolete 'smooth', 'morespace', and 'nopauses'"

I can just remove the bit that sets smooth manually but it should be removed on the update automatically

**Comment by fenrus75** [comment]
fixing this now

thanks for the report

**Comment by phmccarty** [comment]
Fixed in the [34590](https://cdn.download.clearlinux.org/releases/34590/clear/RELEASENOTES) release.
