### ISSUE TITLE
Add Atlantic kernel module for Aquantia AQtion based ethernet controllers

### ISSUE THREAD

**Issue by justinphelps** [clearlinux/distribution#2360]
Aquantia modules have been been merged with the linux kernel but are not available in the Clear kernels. 
There is also not native support from Aquantia for building their own module for Clear linux (they have tooling for redhat/debian based distrubtions). 
It would be nice if the Clear kernels came with support for AQtion atlantic modules.

**Comment by fenrus75** [comment]
done for the next release

**Comment by mdhorn** [comment]
Verified present in 34900
