### ISSUE TITLE
Rdfind

### ISSUE THREAD

**Issue by hacketiwack** [clearlinux/distribution#2362]
Official package name: Rdfind

License (must be an OSI approved Open Source license): GPLv2

Download URL of latest release: https://github.com/pauldreik/rdfind

Latest release date (must be recent): 1.4.1

Description:
Rdfind is a command line tool that finds duplicate files. It is useful for compressing backup directories or just finding duplicate files. It compares files based on their content, NOT on their file names.

**Comment by lebensterben** [comment]
rdfind is very slow.
try fclones, about 10 times faster

**Comment by hacketiwack** [comment]
Thanks for the tip. I will check it out.
I couldn't find fclones in the Clear Linux repository, however.

**Comment by hacketiwack** [comment]
I will replace this request for another command: aka fclones.
