### ISSUE TITLE
fclones

### ISSUE THREAD

**Issue by hacketiwack** [clearlinux/distribution#2363]
Official package name: fclones

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/pkolaczk/fclones

Latest release date (must be recent): https://github.com/pkolaczk/fclones/releases/tag/v0.11.0

Description:
Sometimes you accidentally copied your files in too many places - fclones will find them even if the duplicates got different names. It can also be used to find unique or under-replicated files, e.g. to check if your backups contain the required files.

**Comment by fenrus75** [comment]
eh this is written in a language that makes our life very hard.. at least
20 direct ecosystem dependencies we don't have yet, an who knows how many
more indirect... I don't think we'll package this.

**Comment by lebensterben** [comment]
I don't think autospec supports Rust packages.

**Comment by hacketiwack** [comment]
OK. I close this one as well.
