### ISSUE TITLE
gst-python (GStreamer Python Bindings Supplement)

### ISSUE THREAD

**Issue by tixoi** [clearlinux/distribution#2364]
Official package name: gst-python

License (must be an OSI approved Open Source license): LGPL v2.1

Download URL of latest release: https://gstreamer.freedesktop.org/modules/gst-python.html

Latest release date (must be recent): 2021-03-15

Description: GStreamer Python Bindings Supplement

**Comment by tixoi** [comment]
... and looks like gst-python should belong to the devpkg-gstreamer bundle, right?

**Comment by phmccarty** [comment]
A new bundle named `gst-python` was added in release 34660.
