### ISSUE TITLE
SVT-AV1 v0.8.7

### ISSUE THREAD

**Issue by tixoi** [clearlinux/distribution#2367]
Hello,

I found that SVT-AV1 was bumped to v0.8.7:
https://gitlab.com/AOMediaCodec/SVT-AV1/-/tags/v0.8.7

This kind of issue was also addressed in https://github.com/clearlinux/clr-bundles/issues/210

thank you

**Comment by mdhorn** [comment]
hello @tixoi 

The 'package-update' template is for requesting an update to a package if it has fallen behind and needs a manual update.

It appears this package was already recently updated to the latest release, so I'm going to close this request.
