### ISSUE TITLE
Update KDE Plasma to 5.22 (better wayland support, usability enhancements)

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2373]
Please update the KDE packages.

https://www.phoronix.com/scan.php?page=news_item&px=KDE-Plasma-5.22

**Comment by phmccarty** [comment]
Thanks for the notice. I will begin staging the updates for Plasma 5.22 and also the updates for Apps 21.04.1 and Frameworks 5.82.0.

**Comment by phmccarty** [comment]
ETA on integration will likely be later this week or early next week.

**Comment by insilications** [comment]
Thank you very much for your work @phmccarty

**Comment by phmccarty** [comment]
I merged the Plasma 5.22.0 updates today, as well as the Apps 21.04.2 and Frameworks 5.82.0 updates. Expect the changes for the first build next week.

**Comment by phmccarty** [comment]
Updates landed in the 34740 release from today.
