### ISSUE TITLE
[Mesa enhancement request] Add Zink driver to mesa

### ISSUE THREAD

**Issue by original-tinozza** [clearlinux/distribution#2379]
Greetings ClearLinux team,
is there the possibility to add the ZINK driver to the mesa package?

Mesa library Zink docs URL: https://docs.mesa3d.org/drivers/zink.html
Extensive Zink infos URL: https://www.collabora.com/news-and-blog/blog/2018/10/31/introducing-zink-opengl-implementation-vulkan/

Additional remarks: There are a lot of movements in Zink development lately, mostly carried out by Mike Blumenkrantz. Most of the latest impressive improvements are still to be merged to Mesa master branch but starting to have ZINK added to the mesa package SPEC file will give us the possibility to benefit from them as soon as they are officially merged (which shouldn't be that far out).

Mike Blumenkrantz blog URL: https://www.supergoodcode.com/

Many thanks in advance :)

**Comment by WSLUser** [comment]
So Zink is part of the upstream Mesa. Clear Linux makes use of the `auto` option for Gallium drivers. What you need to check is if Zink is included with `auto` or if it needs to be explicitly enabled.

**Comment by original-tinozza** [comment]
That is true. Looking at the [spec](https://github.com/clearlinux-pkgs/mesa/blob/master/mesa.spec) file the "gallium-drivers" switch is set to "auto". But i believe, as you noted, it needs to be explicitly enabled.

I believe the zink driver is still probably considered under "heavy" development and excluded from the "auto" option.
Looking at the content of /usr/lib64/dri directory is in fact missing.

**Comment by WSLUser** [comment]
@fenrus75 Any plans to add this one as well?

**Comment by WSLUser** [comment]
@original-tinozza https://github.com/clearlinux-pkgs/mesa/commit/1af9a82f531169cef43e55e55e30b4ce60752e50 adds Zink so you can close this issue now.

**Comment by original-tinozza** [comment]
@WSLUser many thanks for the heads-up. I was eagerly waiting for it.
Closing the issue and thanks @fenrus75 for the effort.
