### ISSUE TITLE
update sof-bin to support intel tigerlake sound 

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#2380]
Could we have an update to v1.7 - for tigerlake support please?
https://github.com/thesofproject/sof-bin

Current version appears to be 1.4.2.
https://github.com/clearlinux-pkgs/sof-bin/blob/master/sof-bin.spec

Thank you

**Comment by phmccarty** [comment]
I updated the package to 1.7. It will be in the next build.

**Comment by xlfe** [comment]
thanks @phmccarty
