### ISSUE TITLE
Error build linux-gce kernel:  thunk_64.o: warning: objtool: missing symbol table

### ISSUE THREAD

**Issue by pffont** [clearlinux/distribution#2388]
The building process cancels after got the message `thunk_64.o: warning: objtool: missing symbol table`.
Adding this patch to **linux-gce** tree solve this issue.

[objtool-patch.zip](https://github.com/clearlinux/distribution/files/6718092/objtool-patch.zip)

**Comment by phmccarty** [comment]
The `linux-gce` kernel is very out-of-date. We should likely update to an LTS release at minimum.

**Comment by phmccarty** [comment]
I updated `linux-gce` to the latest 5.10.x release. It will be available early next week.

**Comment by mcybz** [comment]
> I updated `linux-gce` to the latest 5.10.x release. It will be available early next week.

Fantastic news. Thank you kindly

**Comment by phmccarty** [comment]
`linux-gce` was updated to 5.10.46 in release [34800](https://cdn.download.clearlinux.org/releases/34800/clear/RELEASENOTES).
