### ISSUE TITLE
Engineer pls advise on compatibility issue between Docker-Kubernetes 

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/distribution#239]
**Is your feature request related to a problem? Please describe.**
See: https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes
Section: Run Kubernetes for the first time; Step 2a)

sudo -E kubeadm init --pod-network-cidr 10.244.0.0/16 --ignore-preflight-errors=SystemVerification

Either remove the `--ignore-preflight-errors...` flag or explain why it’s used. [Currently, I believe that our Docker version is one ahead of what Kubernetes allows by default.] If the above flag is omitted, then Kubernetes with Docker runc will fail to start. The current full command, in a sense, partially masks this incompatibility. 

**Describe the solution you'd like**
We need to know the correct way to resolve compatibility issue between Docker and Kubernetes. We request that an Engineer determines how to assure that the correct and compatible Docker version—used with Kubernetes –appears in the bundle.  In the end, if the compatibility issue were resolved (or at least noted), we can keep the documentation clean and accurate -- given that future versions may necessitate a similar review. 

**Additional context**
For history on current PRs for the Kubernetes Tutorial, see: 
https://github.com/clearlinux/clear-linux-documentation/pull/255

**Comment by joselamego** [comment]
@bryteise: currently, k8s with Docker + runc does not work without the flag, because the Docker version in Clear Linux is not recognized as compatible (although it does work). I believe this request can be split into two steps:

1. Request k8s upstream to recognize Clear Linux Docker version (18.06.1?) as compatible to get rid of the Verification Error
2. Remove the flag from the tutorial instructions once step 1 is done

Thoughts?

**Comment by bryteise** [comment]
@joselamego My happiness that you are here and can be the expert is very high =). I'm perfectly fine with this though I imagine this will be a rolling problem so to speak on upstream k8s being slower than Clear Linux in updating docker and so we would be requiring to either add the flag back, patch k8s or require k8s to move before Clear Linux can update docker.

**Comment by mvincerx** [comment]
Closed. Resolved per https://github.com/clearlinux/clear-linux-documentation/pull/255.
