### ISSUE TITLE
Install sassc, Unable to detect release version (use '--releasever' to specify release version)

### ISSUE THREAD

**Issue by akhyar93** [clearlinux/distribution#2390]
Hello, Sorry I'm a newbie in linux.
Btw I'd like to install `sassc` package, but it's failed
What am I missing?

```sh
sudo dnf install sassc
Password: 
Unable to detect release version (use '--releasever' to specify release version)
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

**Comment by fenrus75** [comment]
I'm sorry but CLear Linux is not using RPMs for distributing content so DNF
is not going to work.

Our tool is called "swupd" instead, and I would suggest the "search"
function to find the ":bundle" to install for what you want

**Comment by akhyar93** [comment]
Ahh, I see thank you @fenrus75 for the answer.

I'm going to close this issue then 🙏  sorry
