### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by raymondlanger** [clearlinux/distribution#2393]
I used a docker image of Clear Linux (version 34790) and installed GCC 11.1.1 with:

```sh
swupd bundle-add c-basic wget
```

GCC was not able to compile c++ source code that includes headers from the eigen library if `-Ofast` is enabled :
```sh
wget https://gitlab.com/libeigen/eigen/-/archive/3.4-rc1/eigen-3.4-rc1.tar.bz2
tar -xf eigen-3.4-rc1.tar.bz2
printf "#include <Eigen/Core>\n int main(int,char const*[]){}\n" > eigen_bug.cpp
g++ eigen_bug.cpp -Ieigen-3.4-rc1/ -Ofast 
```
The expected output from the last command is:
```
In file included from eigen-3.4-rc1/Eigen/Core:171,
                 from eigen_bug.cpp:1:
eigen-3.4-rc1/Eigen/src/Core/MathFunctions.h:1036:71: internal compiler error: in maybe_default_option, at opts.c:332
 1036 | template<> EIGEN_TMP_NOOPT_ATTRIB bool isnan_impl(const long double& x) { return __builtin_isnan(x); }
      |                                                                       ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
```

Using O3 instead of Ofast works fine:
```
g++ eigen_bug.cpp -Ieigen-3.4-rc1/ -O3 
```

I reported the bug to GCC, but it was suggested to report the bug here as the following output [makes no sense](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101241):
```
gcc --version

gcc (Clear Linux OS for Intel Architecture) 11.1.1 20210617 releases/gcc-11.1.0-303-ge86ad5ad01
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by phmccarty** [comment]
Hi, we encountered some ICEs with GCC 11 recently after switching from `-O3` to `-Ofast`, but I don't think we filed a bug report yet, so thank you for doing so.

> I reported the bug to GCC, but it was suggested to report the bug here as the following output makes no sense:
>> gcc --version
>>```
>> gcc (Clear Linux OS for Intel Architecture) 11.1.1 20210617 releases/gcc-11.1.0-303-ge86ad5ad01
>> Copyright (C) 2021 Free Software Foundation, Inc.
>> This is free software; see the source for copying conditions.  There is NO
>> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
>>```

I do see commit e86ad5ad01 on the releases/gcc-11 stable branch: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=e86ad5ad011573121291bccb88d3a6fdb933469c.

**Comment by phmccarty** [comment]
If the issue might be related to the patches we carry, here's a link to the package state at that revision:

https://github.com/clearlinux-pkgs/gcc/tree/27e84b4a58ae778b06a2faa363555732da476da1

**Comment by phmccarty** [comment]
For completeness, some of those patches are not actively applied during the build. Here are the ones actually applied (in order) at the same revision:

* gcc-stable-branch.patch
* 0001-Fix-stack-protection-issues.patch
* openmp-vectorize-v2.patch
* fortran-vector-v2.patch
* optimize.patch
* ipa-cp.patch
* optimize-at-least-some.patch
* gomp-relax.patch
* arch-native-override.patch
* 0001-Ignore-Werror-if-GCC_IGNORE_WERROR-environment-varia.patch
* 0001-Always-use-z-now-when-linking-with-pie.patch
* tune-inline.patch

**Comment by raymondlanger** [comment]
The GCC folks could not reproduce the bug that I reported and inquired more details about [how GCC was configured](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101241). I was not able to provide further information. Maybe they can reproduce and fix the bug if you provide the above information in [bug report 101241](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101241).

**Comment by hjl-tools** [comment]
If all patches are not applied, can you still reproduce the ICE?

**Comment by raymondlanger** [comment]
How can I not apply the patches? I'm not familiar with patches, but if you provide the commands, I can run them in the docker container.

**Comment by fenrus75** [comment]
I'm going to spend today bisecting this; it'll take some time, gcc does not
build quick ;)

**Comment by hjl-tools** [comment]
Something like this
```
diff --git a/gcc.spec b/gcc.spec
index ee8b097..c009c55 100644
--- a/gcc.spec
+++ b/gcc.spec
@@ -208,24 +208,24 @@ GNU cc and gcc C compilers.
 %setup -q -n %{gccpath}
 %patch0 -p1
 
-%patch1 -p1
-%patch2 -p1
-%patch3 -p1
-%patch5 -p1
-%patch6 -p1
-%patch8 -p1
-%patch9 -p1
+#%patch1 -p1
+#%patch2 -p1
+#%patch3 -p1
+#%patch5 -p1
+#%patch6 -p1
+#%patch8 -p1
+#%patch9 -p1
 #%patch11 -p1
 
 #%patch12 -p1
 
-%patch14 -p1
+#%patch14 -p1
 
-%patch15 -p1
-%patch16 -p1
+#%patch15 -p1
+#%patch16 -p1
 #%patch17 -p1
 # %patch18 -p1
-%patch19 -p1
+#%patch19 -p1
 
 
 

```
should skip these patches.

**Comment by phmccarty** [comment]
To rule out an upstream issue, I compiled the test example code both gcc 11.1.0 (no patches), and gcc 11.1.0 (with gcc-stable-branch.patch), and I don't encounter the ICE for either case.

So, one of the Clear Linux patches for gcc must be to blame...

**Comment by phmccarty** [comment]
@fenrus75 discovered that the `optimize-at-least-some.patch` is to blame. We will disabling that patch for gcc.

**Comment by phmccarty** [comment]
Fixed in release 34810.
