### ISSUE TITLE
postgresql 13

### ISSUE THREAD

**Issue by chriseomi** [clearlinux/distribution#2394]
Official package name:
postgresql13

License (must be an OSI approved Open Source license):
https://opensource.org/licenses/postgresql

Download URL of latest release:
https://www.postgresql.org/ftp/source/

Latest release date (must be recent):
2021-05-10

Description:
Any chance we can see pg13 added to swupd?

PS pgsql14 is already in beta and will be release soon. Clearlinux still still on pgsql12

**Comment by phmccarty** [comment]
This is a duplicate request. See #2346

**Comment by Phyllo** [comment]
It is indeed and although I requested it on May 1st, nothing happened so far and postgreSQL is about to release version 14 already. I've moved on from clearlinux and am happy with debian now. Too bad that Intel seems to have lost interest in clearlinux.
