### ISSUE TITLE
Can't connect airpods via bluetooth

### ISSUE THREAD

**Issue by muhammetarslan** [clearlinux/distribution#2395]
I tried to connect my air pods on the desktop version but it didn't even see it.

**Comment by mdhorn** [comment]
Did you put them in pairing mode before trying to connect to them via Bluetooth?
Works on my Dell laptop.

**Comment by Boulotaur2024** [comment]
Hello, I'm also getting a problem connecting bluetooth earbuds (Huawei Freebuds 4i)
But I definitely can see them paired and waiting to connect.
It does get connected like a few seconds and then disconnects quickly after.
After checking out a little the logs, I've been able to find the error and search the net and...

And now we know why : there is a known *BUG* in BlueZ v5.59 which prevents some earbuds to properly connect :
https://github.com/bluez/bluez/issues/157

I'm pretty sure this bug affects a lot of us.
If you could please merge this and make v5.60 available for us ClearLinux users.
That would be awesome 👍 

Thanks.

**Comment by mdhorn** [comment]
Bluez 5.60 was added in Clear Linux OS release 34850 and later.

**Comment by Boulotaur2024** [comment]
> Bluez 5.60 was added in Clear Linux OS release 34850 and later.

Yep, saw that yesterday !

Thank you so much, earbuds are working like a charm now 👍
