### ISSUE TITLE
Please update `libyaml`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#2399]
Currently we have `libyaml` 0.2.2
https://github.com/clearlinux-pkgs/yaml/blob/130d8d36e095c18d3474f6f7ee190691aa1de2ba/yaml.spec#L8

As of Today, July 14 2021, the latest release is 0.2.5.

**Comment by phmccarty** [comment]
Thanks for the notice. I will update the package.

**Comment by phmccarty** [comment]
Done. The update will land in the next build.
