### ISSUE TITLE
Aquantia atlantic kernel driver missing in release 34860

### ISSUE THREAD

**Issue by guojx1998** [clearlinux/distribution#2400]
The atlantic kernel module is presented in version 34820. (/lib/modules/5.12.14-1051.native/kernel/drivers/net/ethernet/aquantia/atlantic/atlantic.ko)
But it seems missing in kernel 5.12.16-1054.native after upgrade to 34860. Is it removed on purpose? I haven't read about this on any documentations.

Thanks for any help!

**Comment by phmccarty** [comment]
Thanks for the report. It looks like that kernel driver was disabled on accident. We will investigate.

**Comment by phmccarty** [comment]
Fixed in release 34900.
