### ISSUE TITLE
34820 fails ssse3 check on kvm vps

### ISSUE THREAD

**Issue by cphuntington97** [clearlinux/distribution#2401]
I purchased an SSD512 plan here: https://virmach.com/compare-vps-plans/ on the Buffalo NY node. I had support mount this iso: https://cdn.download.clearlinux.org/releases/34820/clear/clear-34820-live-server.iso but upon boot, the ssse3 check failed.

It should work, though. The following output is from Ubuntu on the same vps:

<details>
  <summary># ./clear-linux-check-config.sh host</summary>

Checking if host is capable of running Clear Linux* OS

SUCCESS: 64-bit CPU (lm)
SUCCESS: Supplemental Streaming SIMD Extensions 3 (ssse3)
SUCCESS: Streaming SIMD Extensions v4.1 (sse4_1)
SUCCESS: Streaming SIMD Extensions v4.2 (sse4_2)
SUCCESS: Carry-less Multiplication extensions (pclmulqdq)
</details>

<details>
  <summary># cat /proc/cpuinfo</summary>

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
stepping	: 4
microcode	: 0x1
cpu MHz		: 2999.998
cache size	: 4096 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb lm constant_tsc arch_perfmon nopl cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm pti ssbd ibrs ibpb stibp fsgsbase smep xsaveopt
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
</details>

Unfortunately I have no idea how reproducible this bug is, but if I can be of any assistance, please let me know.

**Comment by mdhorn** [comment]
The ISO does the check in a limited environment and uses the following to check:

`cat /proc/cpuinfo | awk 'BEGIN { RS = "" ; } { printf ("%s\n", $0); exit(0); }' | egrep -q "^flags.*\<ssse3\>"
`

But we've not ever had a report of this failing before. Is this consistently repeatable? Can you share a screenshot of the error?

**Comment by cphuntington97** [comment]
Thanks for chiming in, @mdhorn. Try not to roll your eyes too far back in your head; I had support remount the iso and it worked this time. 💪🏼
