### ISSUE TITLE
Time for Kubernetes update again?

### ISSUE THREAD

**Issue by evankanderson** [clearlinux/distribution#2403]
https://kubernetes.io/releases/

> The Kubernetes project maintains release branches for the most recent three minor releases (1.21, 1.20, 1.19). Kubernetes 1.19 and newer receive approximately 1 year of patch support. Kubernetes 1.18 and older received approximately 9 months of patch support.
> ...
> 1.19
>
> Latest Release: 1.19.12 (released: 2021-06-16)
> End of Life: 2021-09-30

Note that Kubernetes expects minor version upgrades to happen sequentially, and sometimes skipping a version can break things (ref https://docs.01.org/clearlinux/latest/guides/clear/k8s-migration.html for what needed to happen the last time)

**Comment by pixelgeek** [comment]
Clear Linux is now shipping kubernetes-1.20.13-124
