### ISSUE TITLE
R error: cons memory exhausted (limit reached?)

### ISSUE THREAD

**Issue by yangchino1** [clearlinux/distribution#2405]
When reading a binary file of only 20M in either rds or rdata format, R breaks with error: `cons memory exhausted (limit reached?)`, although the machine has 128G memory. `readLines()` for text file has the same problem. However, R works well in Debian on the same machine.

**Comment by phmccarty** [comment]
Can you post (or link to) a short example script to reproduce this issue?

**Comment by yangchino1** [comment]
After I upgraded the system to 34900, such errors didn;t happen anymore. :)
