### ISSUE TITLE
Disk Partition: Validation Error: "Missing /boot partition"

### ISSUE THREAD

**Issue by kingdjf** [clearlinux/distribution#2406]
Hi:
        when i use "sudo mixer build image " , i get a error in JSON file (release-image-config.log).
anyone can help me .
email:kingdjf@foxmail.com
![image](https://user-images.githubusercontent.com/20849778/126745611-dff7da40-7fe7-4070-a9b9-6627e8d048fe.png)

![image](https://user-images.githubusercontent.com/20849778/126745462-653ce11c-3211-4cfb-9b4f-ea33d4d5dbc8.png)

**Comment by mdhorn** [comment]
can you share your YAML file?
release-image-config.yaml

Did you change the file from the initial template generated?

/boot partition is required unless you are booting in legacy mode by adding:
`legacyBios: true`
to you .yaml file.

**Comment by kingdjf** [comment]
yes, please look at my .yaml file content.
![image](https://user-images.githubusercontent.com/20849778/127078883-e694c62b-4fc9-44f5-95e1-bca6a403239b.png)

**Comment by mdhorn** [comment]
> yes, please look at my .yaml file content.
> ![image](https://user-images.githubusercontent.com/20849778/127078883-e694c62b-4fc9-44f5-95e1-bca6a403239b.png)

/boot partition is required unless you are booting in legacy mode by adding:
`legacyBios: true
`
to your .yaml file.

Looks like you intentionally removed the /boot partition, so you'll need to set legacy boot mode as noted above.

**Comment by kingdjf** [comment]
> > yes, please look at my .yaml file content.
> > ![image](https://user-images.githubusercontent.com/20849778/127078883-e694c62b-4fc9-44f5-95e1-bca6a403239b.png)
> 
> /boot partition is required unless you are booting in legacy mode by adding:
> `legacyBios: true `
> to your .yaml file.
> 
> Looks like you intentionally removed the /boot partition, so you'll need to set legacy boot mode as noted above.
> 
> Here is a link to the syntax for the YAML:
> https://github.com/clearlinux/clr-installer/blob/master/scripts/InstallerYAMLSyntax.md

Thank you for your help.Just as your said, when i add boot partition and build again it works fine.
