### ISSUE TITLE
Add ability to have full combined ca-certs file in alternate locations

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#241]
**Is your feature request related to a problem? Please describe.**

Reopen of an issue filed here: https://github.com/clearlinux/clrtrust/issues/19

`clrtrust` places the combined certs under `/var/cache/ca-certs/compat` . 

Some scripts and programs are created to expect the ca-certificates in a specific location - [steamCMD ](https://developer.valvesoftware.com/wiki/SteamCMD) for example looks at the Ubuntu/Debian location `/etc/ssl/certs/ca-certificates.crt` (FreeBSD and other distro users encounter a similar issue here)

**Describe the solution you'd like**
Software packaged from the Clear upstream is  modified to point to the right place. However, sometime programs from other sources are needed. 

Ideally programs have a more robust method for searching the system locations for trusted certificates, but perhaps this functionality to place a .crt in alternate locations can be added or a change to the way symlinking is done to allow customization like this with where `clrtrust` places certificates.

**Describe alternatives you've considered**
A temporarily work around is by doing a `ln -s /var/cache/ca-certs/compat/ca-roots.pem /etc/ssl/certs/ca-certificates.crt` However when `clrtrust generate` runs again it will be overwritten because the /var/cache/ca-certs/ directory is overwritten .

**Comment by bryteise** [comment]
The work around which doesn't require manually updating the symlink would be for the user to modify the dynamic-trust-store.service (systemctl --edit so the changes go in /etc) to add PostExecStart commands to symlink as needed. In fact I'd go so far as to say that's the recommended way to handle this for now.

**Comment by puneetse** [comment]
Thanks. This works for me. 

P.S. ExecStartPost, not PostExecStart

**Comment by seanvk** [comment]
This works for me as well.

Sean

**Comment by bryteise** [comment]
@iphutch I'd say this is the way we should document it until there is an obvious problem. Pokaing @busykai in case he wants to weigh in on this.

**Comment by busykai** [comment]
@iphutch, Clear does not rely on any locations other than the ones managed by `clrtrust`. All software that is provided by Clear does need anything done/added. This is a workaround for people who bring binary apps from other distros. It might become a "real" problem if software we (Clear Linux) make available via other channels (e.g. flatpak) rely on such locations. So far, the use case is not entirely clear to me and I'm not sure if we need to do anything at all.

**Comment by puneetse** [comment]
I'm closing this issue for now because it's out of scope for Clear Linux. This issue can be searched for and used as reference for users that encounter software that is not flexible for cert locations.
