### ISSUE TITLE
34900: The GCC used for the compiling the kernel, 11.1.1, is different from the current GCC version 11.2.1.

### ISSUE THREAD

**Issue by mns6070** [clearlinux/distribution#2410]
My system updated to 34900.  When I rebooted, my system no longer would bring up my GUI on my NVIDIA video cards.  When I went to run the NVIDIA installation script, I received the message that the dkms build command would not work.  When I used the NVIDIA bash automation script, it told me that the GCC version used to build the kernel is different than current version of GCC install on my system.  Is it possible to rebuild the kernel with the same GCC version upstream or is there a way I can fix this on my system?

**Comment by fenrus75** [comment]
bump done; will be in the next build

**Comment by mns6070** [comment]
Thank you!

**Comment by phmccarty** [comment]
Should be fixed in release 34930. If not, please re-open.

**Comment by mns6070** [comment]
Yep. Fixed.
