### ISSUE TITLE
The hyper-v kernel seems don't have ipv6 support

### ISSUE THREAD

**Issue by guojx1998** [clearlinux/distribution#2414]
A fresh install vm in Hyper-V (with kernel-hyperv) do not have ipv6 address on its interface, no matter whether ipv6 is set to auto or manual in NetworkManger, even no link-local ipv6 address. I suspect that there is no ipv6 support in kernel-hyperv, because there is nothing related to ipv6 when running "sysctl -a". Also, the same setting has no issue on a vm with kernel-native.

Is this absence of ipv6 support on hyperv kernel on purpose? I am not sure because there is nothing related to this on any documentations.

Thanks for any help or explanations.

**Comment by fenrus75** [comment]
at the time we made hat config choice, Azure did not support IPv6 and this
would cause long boot delays as ipv6 was attempted anyway

**Comment by guojx1998** [comment]
Thanks for explaining the reason behind this. I would probably use kernel-native when ipv6 is necessary.
