### ISSUE TITLE
Update 34930 broke firefox browser

### ISSUE THREAD

**Issue by soo-shan** [clearlinux/distribution#2416]
In terminal I only get following error
```
user@clearsu~ $ firefox
###!!! [Parent][MessageChannel] Error: (msgtype=0x390079,name=PContent::Msg_DestroyBrowsingContextGroup) Channel error: cannot send/recv
```

I installed vivaldi browser using rpm. It is also not working
```
sushan@clearsu~ $ vivaldi-stable 
Fontconfig error: Cannot load default config file: No such file: (null)
[9929:9929:0806/160755.608641:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
[9890:9890:0806/160755.952823:ERROR:vivaldi_ui_web_contents_delegate.cc(42)] UI Process abnormally terminates with status 3 after running for 1.06733 seconds!
[9890:9890:0806/160755.964814:ERROR:vivaldi_ui_web_contents_delegate.cc(73)] Quiting Vivaldi
```

Not sure whether both are related.

Thanks

![Screenshot from 2021-08-06 16-04-41](https://user-images.githubusercontent.com/39080326/128497970-35bbdef1-aefa-4b09-8a94-b3e3758500f4.png)

**Comment by foxiumcode** [comment]
Chrome and Brave are also broken by 34930.

Gives "Aw, snap" error 159 when trying to load a page. Even the about and settings pages.

**Comment by wheerdam** [comment]
Confirmed on Firefox and Chrome, it looks like due to the update of glibc from 2.33 to 2.34 on 34920.

You can run Firefox 90.2 and latest Chrome without content sandbox with:
MOZ_DISABLE_CONTENT_SANDBOX=1 environment variable for Firefox
and --no-sandbox option for Chrome

But, as you may think, this is far from ideal.

**Comment by thiagomacieira** [comment]
You need to get updated versions of those browsers that do allow the new system calls that glibc issues on behalf of the application.

**Comment by wheerdam** [comment]
How do I install the Firefox 91 beta on Clearlinux 34930?

**Comment by mdhorn** [comment]
Firefox 91 beta is in the Clear Linux OS release 34930 due to the glibc change.

Firefox is installed in your home directory.
If it does not auto-update, use the following from the command line terminal:

```
/bin/rm -rf ~/.firefox
firefox

```

**Comment by monik3r** [comment]
Can confirm: chrome and Firefox are broken locally

**Comment by soo-shan** [comment]
Resolution mentioned by @mdhorn in [comment](https://github.com/clearlinux/distribution/issues/2416#issuecomment-894360923)
```
/bin/rm -rf ~/.firefox
firefox
```
