### ISSUE TITLE
Update 34930 Breaks Chrome Browser

### ISSUE THREAD

**Issue by monik3r** [clearlinux/distribution#2419]
An [issue (#2416)](https://github.com/clearlinux/distribution/issues/2416) addresses this behavior with Firefox and mentions Chrome, however the workaround in that thread disables the Chrome sandbox, which is unsafe. My current local version is  92.0.4515.131. 

I guess the best measure in the case of Chrome will either be for users to downgrade Clear Linux versions (something like `sudo swupd repair -V 34700 --picky --force`), or to use different browsers until Chrome supports glibc 2.34?

**Comment by monik3r** [comment]
Here is the [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1235772&q=glibc&can=2) for glibc 2.34 on the Chromium bug tracker.

**Comment by paulcarroty** [comment]
Discussion & workaround in https://github.com/clearlinux/distribution/issues/2416

**Comment by phmccarty** [comment]
@monik3r Can you re-test on release 34940?

We disabled the clone3 syscall wrapper in glibc for release 34940, which hopefully fixes Chrome.

**Comment by monik3r** [comment]
It works, thanks! It also appears that there is a fix from the Chromium side which may be mainlined soon. I'll close this now.
