### ISSUE TITLE
Enable TPM2 support in systemd

### ISSUE THREAD

**Issue by iavael** [clearlinux/distribution#2422]
When I try to use systemd-enrollcrypt with TPM2 it returns this
```
# systemd-cryptenroll --tpm2-device=list
TPM2 not supported on this build.
```

Could you enable TPM2 support in systemd build, please?

**Comment by fenrus75** [comment]
I'll take a look

it'll kind of depend also on how much extra "stuff" this pulls into the
small images to be honest

**Comment by Leptopoda** [comment]
Hi @fenrus75,
Any news? Otherwise I'll start looking into building it myself.

**Comment by fenrus75** [comment]
I added this last week, an extra .so got generated,,, should be in a
release soon if not already
