### ISSUE TITLE
[MESA PACKAGE BUG] Mesa compilation flag -Ofast causing graphical artifacts

### ISSUE THREAD

**Issue by original-tinozza** [clearlinux/distribution#2424]
Greetings Clearlinux team.

i've just discovered a little bug affecting the Vulkan driver in mesa that shows up only when compiled with the -Ofast optimization switch as used in the current [mesa.spec](https://github.com/clearlinux-pkgs/mesa/blob/master/mesa.spec) file.
Compiling with -O3 seems to be solving the issue.

I'm still investigating and bisecting but something weird is indeed happening. The artifacts are not showing up in every single application/game but they are indeed very frequent. The issue seems to be exclusive to Vulkan. Any native OpenGL application/game seems to be fine (at least from my early investigation).

Here my system spec:
>CPU: INTEL i9-10900k
>GPU: AMD RX5700XT
>RAM: 32GB
>OS: Clearlinux 34850

Here the environment variables i used to recompile mesa:
>CFLAGS="$CFLAGS -O3 -pipe -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -mprefer-vector-width=256 -m64 -march=native -mtune=native "

>FCFLAGS="$CFLAGS -O3 -pipe -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -mprefer-vector-width=256 -m64 -march=native -mtune=native "

>FFLAGS="$CFLAGS -O3 -pipe -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -mprefer-vector-width=256 -m64 -march=native -mtune=native "

>CXXFLAGS="$CXXFLAGS -O3 -pipe -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -mprefer-vector-width=256 -m64 -march=native -mtune=native "

Here the meson command line i used to recompile mesa:
>meson --libdir=lib64 --prefix=$prefix_dir --buildtype=release -Dplatforms=x11,wayland" \
>-Ddebug=false \
>-Ddri3=enabled \
>-Ddri-drivers=i915,i965 \
>-Dgallium-drivers=radeonsi,swrast,swr,iris,zink \
>-Dcpp_std=gnu++14 \
>-Dgallium-va=enabled \
>-Dgallium-vdpau=enabled \
>-Dgallium-xa=disabled \
>-Dgallium-opencl=icd \
>-Dvulkan-drivers=intel,amd,swrast \
>-Dshared-glapi=enabled \
>-Dgles1=enabled \
>-Dgles2=enabled \
>-Dgbm=enabled \
>-Dopengl=true \
>-Dglx=dri \
>-Degl=enabled \
>-Dglvnd=false \
>-Dasm=true \
>-Dllvm=enabled \
>-Dshared-llvm=enabled \
>-Dselinux=false \
>-Dosmesa=true \
>-Dgallium-xvmc=disabled \
>-Dvulkan-icd-dir=$prefix_dir/vulkan/icd.d \
>-Dgallium-omx=disabled \
>-Dprefer-iris=true \
>-Dlmsensors=disabled \
>-Dgallium-nine=true \
>-Dopencl-spirv=false \
>-Dzstd=enabled \
>-Db_ndebug=true $(pwd)/build`

Here just 2 very clear images (subnautica game):
![-O3](https://user-images.githubusercontent.com/73397608/131257979-8291e01a-6b8b-48d5-aa54-22f3c36a4af5.jpg)
![-Ofast](https://user-images.githubusercontent.com/73397608/131257981-3a5a0c37-2d7e-4042-9d06-3dfe47f82116.jpg)

**Comment by original-tinozza** [comment]
For the images attached i was using a version of MESA not already available in Clearlinux (21.2.1) but i can confirm that the same issue is showing up with the version available (21.1.4).

**Comment by phmccarty** [comment]
Thanks for the report. I have the update to 21.2.1 in progress and will turn off `funroll-loops`, which removes `-Ofast` from the spec file.

**Comment by original-tinozza** [comment]
Goodmorning Mr. McCarty, many thanks to you for the super fast answer.
I will give it a try as soon as the new release comes available and report back here.

In the meantime i wish you a nice day :)

**Comment by phmccarty** [comment]
@original-tinozza The mesa package update (and disabling `-Ofast`) landed in release 35000. Hopefully this fixes the problem you were seeing.

**Comment by original-tinozza** [comment]
@phmccarty Many thanks. I'll update to release 35000 later this night and give it at try. I'll report back here any result/outcome.
Meanwhile many thanks again for the super fast solution.

Have a nice day.

**Comment by original-tinozza** [comment]
@phmccarty I can confirm the graphical artifacts are gone. The change in the optimization flags did the trick.
Many thanks again for the help and the fast solution.

P.S.
Just as a side note, updating to release 35000 from 34850 messed up the Xorg server configuration. I get an undefined symbol error when loading the amdgpu_drv.so. Something wrong with the modules loading order probably, but its too late to troubleshoot. If necessary i will open a separate bug report tomorrow.

**Comment by phmccarty** [comment]
The symbol error could be related to the recent package update: https://github.com/clearlinux-pkgs/xf86-video-amdgpu/commit/4e4a3f1c7dbbd26d5208876ea725c04c1f95029a
