### ISSUE TITLE
update neovim from 0.4.4 to 0.5.0

### ISSUE THREAD

**Issue by azazazgwerbv** [clearlinux/distribution#2429]
https://github.com/neovim/neovim/releases/tag/v0.5.0

**Comment by phmccarty** [comment]
I tried to update neovim a few days ago but ran into a build failure and didn't investigate. Revisiting the issue, I see that neovim 0.5.0 has a new dependency on `tree-sitter`, so I added that package first.

The update should be available within a couple days.

**Comment by azazazgwerbv** [comment]
has been updated
