### ISSUE TITLE
npm: illegal instruction

### ISSUE THREAD

**Issue by matbech** [clearlinux/distribution#2439]
I'm running Clear Linux OS on a relatively old CPU:
```
model name      : Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer rdrand lahf_lm 3dnowprefetch epb ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat md_clear
```
https://ark.intel.com/content/www/us/en/ark/products/81071/intel-celeron-processor-n2830-1m-cache-up-to-2-41-ghz.html

With the latest update, I get the following error when running npm:
/usr/bin/npm
Illegal instruction (core dumped)

Distribution:      Clear Linux OS
Installed version: 35090

This might be related to this issue:
https://github.com/clearlinux/distribution/issues/2438

**Comment by anemicsoftware** [comment]
Relevant commit seems to be: 

https://github.com/clearlinux-pkgs/nodejs/commit/8d61baaba7fac4da193712dce86b5776c1dd80aa#diff-876a670055dda36ce5795365a32622ef6c5d59a22a3ad8c0bd57b0749a5e22e0R137-R140

in nodejs.spec lines 137-140 sets -march=x86-64-v3 which I think uses avx and avx2 instructions which your cpu doesn't support.

But as far as I see your cpu is still within the minimum requirements listed.

**Comment by fenrus75** [comment]
we were starting to assume server applications could use 2013 level
instructions but based on this and a few other reports... that's not
without problems.
we're reverting the assumption

**Comment by phmccarty** [comment]
Fixed in release 35100
