### ISSUE TITLE
Default /usr/share/defaults/ister/ister.json file has the labels incorrect

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/distribution#244]
**Is your feature request related to a problem? Please describe.**
I don't know if it's a problem but it's at least something odd to see. The default /usr/share/defaults/ister/ister.json file in Clear Linux (which looks like it comes from [here](https://github.com/bryteise/ister/blob/master/ister.json)) has the labels not mapped correctly in the `FilesystemTypes` section. Specifically, the label assigned to the swap partition is called `root` and the one assigned to the rootfs partition is called `swap`.

**Describe the solution you'd like**
Re-order them so they match

**Describe alternatives you've considered**
No alternative :)

**Additional context**
N/A

**Comment by gvancuts** [comment]
A somewhat related question: wouldn't it be more appropriate to put https://github.com/bryteise/ister/blob/master/release-image-config.json in the Clear Linux rootfs by default? If nothing else, it would at least make the documentation more consistent: https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer#create-an-image.

**Comment by bryteise** [comment]
I probably should have just named it installation sample.json X(. Well I'll fix up the fs types.

**Comment by puneetse** [comment]
I'm closing this issue as ister has since been deprecated and documentation has been updated to use the new [clr-installer](https://github.com/clearlinux/clr-installer/).
