### ISSUE TITLE
swupd update behaves erratically (curl http/2 - related?)

### ISSUE THREAD

**Issue by mmorini** [clearlinux/distribution#2468]
Since a dozen releases or so (earlier than 35060) issuing the swupd update results in repeated failures.

swupd repair doesn't seem to help either.

From the "swupd update" command output:
[...]
Curl - Resuming download for 'https://cdn.download.clearlinux.org/update/35170/files/0a4764840509477e3b7ad53a0944ea790ab1eaec801fb3a99b4b1727faabed13.tar'
Curl - Starting download retry #2 for https://cdn.download.clearlinux.org/update/35140/files/050744aadb49dfe2e32bf4e8b14d82fade72913e48d959560ba02e70b1bffcaa.tar
Curl - Resuming download for 'https://cdn.download.clearlinux.org/update/35140/files/050744aadb49dfe2e32bf4e8b14d82fade72913e48d959560ba02e70b1bffcaa.tar'
Curl - Starting download retry #2 for https://cdn.download.clearlinux.org/update/35090/files/03d5579551406f4a8499c21f9b9009b8b9b7310a58c38410e28dbe9cdea90372.tar
Curl - Resuming download for 'https://cdn.download.clearlinux.org/update/35090/files/03d5579551406f4a8499c21f9b9009b8b9b7310a58c38410e28dbe9cdea90372.tar'
Warning: Error for 1339d8ae0bcf46634ee36a1c87d6bf1aed4e83ff9bc79b62662a0eb7c3811f12 tarfile extraction, (check free space for /var/lib/swupd?)
Installing files...
Error: File staging failed: /usr/bin/bazel
Update took 2186.8 seconds, 2651 MB transferred
Update failed
 [100%]

Interestingly, the failed free space requirement seems to be bogus:

Filesystem      Size  Used Avail Use% Mounted on
/dev/root       469G   95G  350G  22% /
devtmpfs         32G     0   32G   0% /dev
tmpfs            32G   48K   32G   1% /dev/shm
tmpfs            13G  2.9M   13G   1% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs            32G     0   32G   0% /tmp
/dev/sda        3.7T  2.4T  1.4T  65% /datawarehouse
/dev/sda        3.7T  2.4T  1.4T  65% /var/lib/docker
tmpfs           6.3G     0  6.3G   0% /run/user/1001
clr_debug_fuse  469G   95G  350G  22% /usr/src/debug
clr_debug_fuse  469G   95G  350G  22% /usr/lib/debug

The final failure on "file staging" happens on different files on different consecutive runs.

Browsing around, random people suggested taking an incremental approach (update 35050 to 35060 and so on), but it didn't turn out to have any impact.

Other possibly relevant pieces of output: timeout + stream error

Error: Curl - Communicating with server timed out - 'https://cdn.download.clearlinux.org/update/35190/files/4df26d3d4d349929c2af14c0d99825f8ac84e2b1156216fc690b5d93b31c2ea5.tar'

Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer

**Comment by mmorini** [comment]
Update: the following error seems related.
A swdpd upgrade -v 35100 command run from 35060 returns

Update started
Error: Curl - Communicating with server timed out
Error: Failed to connect to update server: 35100/version/format30/latest
Possible solutions for this problem are:
	Check if your network connection is working
	Fix the system clock
	Run 'swupd info' to check if the urls are correct
	Check if the server SSL certificate is trusted by your system ('clrtrust generate' may help)
Error: Unable to determine the server version
Update failed

Following the last suggestion ( clrtrust generate ) returns:

Error rehashing the anchors.

**Comment by eero-t** [comment]
I've been trying to update ClearLinux install for weeks, from 35050 to version 35350, 35360, 35380 and 35390, but they have all eventually failed after spending 3-6 hours and showing hundreds / thousands of errors like these:
```
Error: Curl - File incompletely downloaded - 'https://cdn.download.clearlinux.org/update/35370/files/da83ff95c1696972470f05c6f701330f732f71a687d74f3d6314da32fc1c6612.tar'
Error: Curl - File incompletely downloaded - 'https://cdn.download.clearlinux.org/update/35370/files/8e14c57238e0d73c36546a18fd6733124842ef8fe94d828519d75cc7c012f909.tar'
Error: Curl - File incompletely downloaded - 'https://cdn.download.clearlinux.org/update/35370/files/1c41d6a418db0e66b77eca7c010361e6230244ed9b26dff846d4e5b104f491a4.tar'
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
```

To result like this:
```
Installing files...
Error: File staging failed: /usr/include/bpf/bpf_helper_defs.h
Update took 5443.8 seconds, 2366 MB transferred
Update failed
 [100%]
```

Note: I'm doing this from Intel intranet, so one would assume bandwidth not to be an issue...

**Comment by eero-t** [comment]
> swdpd upgrade -v 35100

The correct command would be: `swupd update -V 35100` (note capital V)

**Comment by bryteise** [comment]
@mdpitterle is something you might be able to look into?

**Comment by eero-t** [comment]
Even a lot smaller updates fail.

I tried upgrading 35050 to 35090 and 35080, until update to 35070 finally succeeded despite the errors:
```
# swupd update -V 35070
Update started
Preparing to update from 35050 to 35070
Downloading packs for:
 - xterm
 - zenity
 [100%]

Finishing packs extraction...
    
Statistics for going from version 35050 to version 35070:

    changed bundles   : 186
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 6981
    new files         : 5757
    deleted files     : 5136

Validate downloaded files
 [100%]

Starting download of remaining update content. This may take a while...
Error: Curl - File incompletely downloaded - 'https://cdn.download.clearlinux.org/update/35070/files/21c9141caa20e761f74f309a221f01dc45d92e4dab73ada8c309e6f0ae0bf6b3.tar'
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
...
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
 [100%]

Curl - Reducing number of parallel downloads to 1
Curl - Starting download retry #1 for https://cdn.download.clearlinux.org/update/35070/files/e76fd94c5cd8a99f55971fac4502bf1c41b8a2704dc00b21a226d8e3f10efce6.tar
...
Curl - Resuming download for 'https://cdn.download.clearlinux.org/update/35070/files/21c9141caa20e761f74f309a221f01dc45d92e4dab73ada8c309e6f0ae0bf6b3.tar'
Installing files...
 [100%]

Update was applied
Calling post-update helper scripts
...
Update took 1182.8 seconds, 154 MB transferred
687 files were not in a pack
Update successful - System updated from version 35050 to version 35070
```

(For some reason post-update helper scripts took tens of minutes, maybe because I was running the latest drm-tip kernel git build instead of old ClearLinux kernel?)

**Comment by fenrus75** [comment]
are you by chance behind some evil and broken HTTP proxy ?

**Comment by eero-t** [comment]
If doing the update from within (European) Intel intranet is classified as having evil & broken HTTP proxy, then yes...

Btw. doing next a smaller version update, that had more content, worked without *any* errors:
```
# swupd update --max-parallel-downloads=1 --version=35080
...
Statistics for going from version 35070 to version 35080:

    changed bundles   : 163
    new bundles       : 2
    deleted bundles   : 0

    changed files     : 8897
    new files         : 5892
    deleted files     : 8003

Validate downloaded files
 [100%]
...

```

No idea whether 35050 -> 35070 update fixed something in ClearLinux, or was disabling parallel downloads the key to the success...

**Comment by eero-t** [comment]
Parallel downloads do not seem to play a role because this huge update after 35080 with the defaults gave only a single error:
```
# swupd update
...
Statistics for going from version 35080 to version 35390:

    changed bundles   : 614
    new bundles       : 3
    deleted bundles   : 0

    changed files     : 475136
    new files         : 222204
    deleted files     : 175416

Validate downloaded files
 [100%]

Starting download of remaining update content. This may take a while...
Error: Curl - Download error - (92) Stream error in the HTTP/2 framing layer
 [100%]

Curl - Reducing number of parallel downloads to 1
Curl - Starting download retry #1 for https://cdn.download.clearlinux.org/update/35370/files/938ef15294d9a768e5f05c6b24337f669dc8a536b116becf18fb8c2902a0dec9.tar
Curl - Resuming download for 'https://cdn.download.clearlinux.org/update/35370/files/938ef15294d9a768e5f05c6b24337f669dc8a536b116becf18fb8c2902a0dec9.tar'
Installing files...
 [100%]

Update was applied
```

=> Something broken in CL updates around release 35050?

**Comment by fenrus75** [comment]
we changed something after 050 that made packs a bit bigger, but needed
less individual file downloads... so it might just be a probability / how
many requests kind of thing
some proxies don't do well with deeply pipelined connections like swupd uses

**Comment by mmorini** [comment]
Fwiw, cdn.download.clearlinux.org resolves to 104.91.29.26 for me (Switzerland/Northern Italy); would giving it a try on an extra-EU ip help diagnose?

**Comment by eero-t** [comment]
35390 to 35440 upgrade (2GB) with the defaults shows also quite a few download errors, but goes through eventually (in little over hour).

**Comment by cminter** [comment]
was this resolved?  I ran into same issue starting with a fresh VM on Hyper-V (started from clear-**35000**-azure-hyperv.*).

An additional problem is that "autoupdate" is on by default and just fails.  As a user I need to then disable it and then try to find some small increment that works.  I was able to go to 35100 and now I can't seem to even get to 35130.  There is nothing wrong with my connection.  I updated a separate Fedora machine needing 1.5GB of downloads just fine.

**Comment by eero-t** [comment]
For the past few hours, I've been running update from 35650 to version 35940:
```
Statistics for going from version 35650 to version 35940:

    changed bundles   : 619
    new bundles       : 3
    deleted bundles   : 0

    changed files     : 623028
    new files         : 93888
    deleted files     : 16769
```
and that shows a lot of errors too, both "File incompletely downloaded" and "Stream error in the HTTP/2 framing layer".

=> I do not think the error is on the local side of the distro, unless ClearLinux has managed to break curl around 35050.

I'm running this on Broxton (=Atom) platform, and if ClearLinux upstream testing is done on more recent Core devices, it's theoretically possible that some SIMD / compilation optimization is subtly breaking the things.  I'd think issue on CDN side is more likely though.

**Comment by mmorini** [comment]
Closing since the problem seems to have solved itself many moons ago.
