### ISSUE TITLE
cant mount android device

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2476]
clear linux 35280
device doesnt show up with `lsblk`, and when i try to mount it with nautilus i get the following:

![Screenshot from 2021-11-14 14-37-56](https://user-images.githubusercontent.com/91722596/141696026-783b7656-a6fb-4b78-89f2-c1f1ef737e15.png)

on the android usb is set to file transfer, not photo transfer.

**Comment by thiagomacieira** [comment]
It's not supposed to show up on lsblk because it's not a block device. But it should show up in lsusb.

**Comment by nobodyatandnothing** [comment]
> It's not supposed to show up on lsblk because it's not a block device. But it should show up in lsusb.

doesnt show up with lsusb either

**Comment by thiagomacieira** [comment]
What does show up in `dmesg` when you plug it?

**Comment by thiagomacieira** [comment]
Here:
```
[97399.308288] usb 2-3: new SuperSpeed USB device number 17 using xhci_hcd
[97399.331452] usb 2-3: New USB device found, idVendor=04e8, idProduct=6860, bcdDevice= c.00
[97399.331461] usb 2-3: New USB device strings: Mfr=7, Product=8, SerialNumber=9
[97399.331465] usb 2-3: Product: SAMSUNG_Android
[97399.331467] usb 2-3: Manufacturer: SAMSUNG
```
Then it shows up on `lsusb -t`
```
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 10000M
    |__ Port 3: Dev 17, If 0, Class=Imaging, Driver=, 5000M
```
"Imaging" is the correct class for MTP. and it's listed in `lsusb -v`

**Comment by nobodyatandnothing** [comment]
thank you
it shows up in `dmesg` and with `lsusb -t` but doesnt show up with `lsusb -v` 
the device used to work as a storage device 
when set to photo transfer, the device is doesnt show up in nautilus
why is it class imaging if my device is set to file transfer?
why is it not a block device if my device is set to file transfer?
why cant nautilus mount it?
is there a way i can interact with the device through the usb connection?

**Comment by thiagomacieira** [comment]
Android devices always show up as MTP (Imaging) for file transfer. They do not show up as block storage because that would require the device to completely cede control of the filesystem to the host computer. That hasn't been done for 10 years.

ModemManager might be telling the USB device to switch modes and enter a modem mode instead of file transfer mode. Check on your device if there's a way to switch what it presents to the host computer.

**Comment by nobodyatandnothing** [comment]
> ModemManager might be telling the USB device to switch modes and enter a modem mode instead of file transfer mode. Check on your device if there's a way to switch what it presents to the host computer.

yeah, thats probably it. though i have no idea how to fix it.
