### ISSUE TITLE
Kernel 5.15 rebase broke some important things

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2477]
Kernel config with CONFIG_SYSFB_SIMPLEFB and CONFIG_DRM_SIMPLEDRM enabled breaks LUKS and NVIDIA users.

https://bugzilla.kernel.org/show_bug.cgi?id=214723
https://bugs.archlinux.org/task/72658
https://bugs.archlinux.org/task/72645
https://gitlab.alpinelinux.org/alpine/aports/-/issues/13165#note_190795

**Comment by original-tinozza** [comment]
I can confirm. I'm on a system with a complicated partition structure using LUKS and i am experiencing the same issues described at the links attached by @insilications.

**Comment by insilications** [comment]
"LUKS

LUKS / encrypted setups, namely for those affected by the changes in the kernel in 5.14.11. I have been manually changing CONFIG_FB_SIMPLE back from m to y to ensure it is compiled in-kernel and not as a separate loadable module. The change to m in 5.14.11 seemed to have resulted in breakages for LUKS-based install when those installs used NVIDIA proprietary graphics. As of 5.15, CONFIG_FB_SIMPLE can no longer be enabled if DRM_SIMPLEDRM is, so we'll have to choose between one or the other. I have not seen any indication that it affects non-NVIDIA graphics solutions (or at the very least non-proprietary graphics) and so I'm following the advice of one of the kernel developers responsible for these changes and using this as an opportunity to test if DRM_SIMPLEDRM is a viable option. It is intended to be a drop-in replacement for CONFIG_FB_SIMPLE. Right now it is set to m, however setting it as an in-kernel module is an option and I may try that if NVIDIA testing doesn't provide positive results. It is quite likely I'll need to do that, but hey let us find out"
https://dev.getsol.us/T10006

**Comment by insilications** [comment]
It seems the tentative fix is to include simpledrm.ko in the initrd. And load it (modules-load.d)?

**Comment by insilications** [comment]
> It seems the tentative fix is to include simpledrm.ko in the initrd. And load it (modules-load.d)?

The fix does not work for NVIDIA.

**Comment by insilications** [comment]
"While simpledrm will work for many systems at this time, it seems to have issues with nvidia drivers at least."


https://www.spinics.net/lists/fedora-devel/msg293743.html

**Comment by fenrus75** [comment]
looks like there aren't any easy simple answers here; I'll try enabling the FB_SIMPLE and see how it goes.
I'll also be honest about the priorities
1) Fix LUKS
2) Fix nouveau
3) Binary nvidia driver works or doesn't

historically nvidia catches up with such upstream changes within a month or two in their binary driver... but it's up to them to do that.

**Comment by paulcarroty** [comment]
NVidia provides a developer forum where you can ask, doubt Linux is on #top10 of their priority list.

**Comment by insilications** [comment]
I've lost too many hours because of nvidia linux driver problems... Too bad I'm forced to work with CUDA :(

**Comment by original-tinozza** [comment]
Just updated to CLR 35310 and i can confirm the issue with LUKS seems to be solved.

**Comment by insilications** [comment]
@fenrus75 thank you very much. 35310 solved my issue with nvidia binary blobs... Happy but frustrated after losing so much time trying to fix this.

**Comment by fenrus75** [comment]
if you need stability with the binary blob you are likely better off using
the LTS kernel,
that one seems better/faster supported by Nvidia unlike the more recent
upstreams where nvidia
at times takes time (same here, we reverted a config backwards which is not
great and likely temporary
until luks is sorted out better)
