### ISSUE TITLE
cdn.download.clearlinux.org/current symlinks to wrong repodata breaking mock and autospec

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2483]
We can see that https://cdn.download.clearlinux.org/current/x86_64/os/repodata/repomd.xml references all the wrong repodata for dnf: 

`sudo /usr/bin/dnf --installroot /var/lib/mock/clear-mock/root/ --releasever clear --setopt=deltarpm=False --allowerasing --disableplugin=local --disableplugin=versionlock groupinstall build srpm-build`

  - Status code: 404 for https://cdn.download.clearlinux.org/current/x86_64/os/repodata/52a3585ca7339463d87030e85d2a3727770759ac016b0e385b1049b814ee87c6-filelists.xml.gz (IP: 23.75.141.222)
  - Status code: 404 for https://cdn.download.clearlinux.org/current/x86_64/os/repodata/38ac32f275515e12c206bc4443129646bd65b34c25a7e777a4f27bf4c9798ced-primary.xml.gz (IP: 23.75.141.222)
Error: Failed to download metadata for repo 'clearlinux': Yum repo downloading error: Downloading error(s): repodata/38ac32f275515e12c206bc4443129646bd65b34c25a7e777a4f27bf4c9798ced-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/52a3585ca7339463d87030e85d2a3727770759ac016b0e385b1049b814ee87c6-filelists.xml.gz - Cannot download, all mirrors were already tried without success

Looking at https://cdn.download.clearlinux.org/releases/35310/clear/x86_64/os/repodata/ (35310, currently published at the moment) and https://cdn.download.clearlinux.org/releases/35320/clear/x86_64/os/repodata/ (35320, unpublished), these are referencing correct links to existing repodata.

**Comment by insilications** [comment]
Changing the baseurl of all clear dnf repos to https://cdn.download.clearlinux.org/releases/35310/clear/x86_64/os/ https://cdn.download.clearlinux.org/releases/35310/clear/x86_64/debug/ temporarily fixes mock and autospec, as expected.

**Comment by fenrus75** [comment]
this should now be fixed

something went wrong in syncing the internal repo (where we create it) to
the CDN

**Comment by insilications** [comment]
Fixed! Thank you.
