### ISSUE TITLE
Mixer, fails to build ISO image when certain packages or amount of packages are added. 

### ISSUE THREAD

**Issue by postmannen** [clearlinux/distribution#2489]
Hi.

I experience problems building the release.iso file.

With the following content in a mix bundle:

```text
bootloader
clr-installer
curl
dosfstools
findutils
glibc-locale
iproute2
jq
kbd
kernel-lts
kernel-lts2020
less
lib-openssl
lib-samba
libglib
libstdcpp
linux-firmware
linux-firmware-extras
linux-firmware-wifi
nfs-utils
openldap
openssh-client
openssh-server
os-core
os-core-plus
os-core-update
os-core-webproxy
p11-kit
parted
perl-basic
pmdk
python3-basic
samba
shells
smartmontools
sshfs
storage-utils
syslinux
vim
wpa_supplicant
xfsprogs
zsh
```

And with the following in my release.yaml file

```yaml
bundles: [
    bootloader,
    os-core,
    os-core-update,
    shells,
    vim,
  ]
```

Then both iso and img files builds fine.

---

If I bump the version number and add for example either `clr-installer` og `NetworkManager` to the mix it creates the img  image, but no longer creates the iso. There are no errors that I can find in the log files, and it says that all was done successfully.
I've also tried both with and without specifying the bundle in the release yaml file, but the problem seems the same.
Also tried setting `skipValidationSize: true`.

Not sure if this is the bundles themselves that are causing the problem, or if there is a certain size limit for the iso image that kicks in ? For the record I'm just using upstream bundles added to the mix for this test, no custom packages or bundles.

Any ideas or help are appreciated.

**Comment by postmannen** [comment]
It seems that there is a space issue when making the ISO. Found this in the log file.
```
2021/12/02 07:25:41 [DBG] ISO Initrd: : Setting indeterminate progress for task extract_packs
2021/12/02 07:25:44 [DBG] { "type" : "warning", "msg" : "Write failed" },
2021/12/02 07:25:44 [DBG] { "type" : "warning", "msg" : "No space left on device" },
```

Since the img file use the `target media` in the release yaml, are there any specific settings in regards to the size of the iso ?

**Comment by fenrus75** [comment]
iirc iso has a 4gb limit as well

**Comment by postmannen** [comment]
Thanks.
Just did a test, and lowered the total size to 3,5GB. The image builds fine, but the iso fails with lines like below in log:
```
2021/12/02 12:06:30 [DBG] cp: error copying '/tmp/clrEfi-404118089/./loader/entries/iso-checksum.conf' to '/tmp/clrCdroot-047320419/./loader/entries/iso-checksum.conf': No space left on device
```

I've booted the img file and when I check space used, it is far below 4GB:
```
root@clr-bbd6590b803241d49674b9e9b7ce3a25~ # df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       2.9G  1.6G  1.2G  58% /
devtmpfs        334M     0  334M   0% /dev
tmpfs           340M     0  340M   0% /dev/shm
tmpfs           136M  968K  135M   1% /run
tmpfs           4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs           340M     0  340M   0% /tmp
tmpfs            68M     0   68M   0% /run/user/0
tmpfs            68M     0   68M   0% /run/user/1000
```
Also pasting in the current release.yaml file used in case I've done something wrong:
```
#clear-linux-config
# switch between aliases if you want to install to an actuall block device
# i.e /dev/sda
block-devices: [
   {name: "bdevice", file: "release.img"}
]

targetMedia:
- name: ${bdevice}
  size: "3.54G"
  type: disk
  children:
  - name: ${bdevice}1
    fstype: vfat
    mountpoint: /boot
    size: "512M"
    type: part
  - name: ${bdevice}2
    fstype: swap
    size: "32M"
    type: part
  - name: ${bdevice}3
    fstype: ext4
    mountpoint: /
    size: "3G"
    type: part

bundles: [
    bootloader,
    os-core,
    os-core-update,
    shells,
    vim,
    #clr-installer,
  ]

  #swupdMirror: http://10.0.0.103:10080

autoUpdate: false
postArchive: false
postReboot: false
telemetry: false
iso: true

copySwupd: true

keyboard: us
language: en_US.UTF-8
kernel: kernel-lts

#version: 30
```

**Comment by postmannen** [comment]
Could also mentioned that the `version: 30` that is commented out there, is the last mix that works for building an ISO image. 30+ is where I added the clr-installer and sudo to the mix, and then it no longer works to build ISO image. Img image works fine.

**Comment by mdhorn** [comment]
Your config worked for me building without using mixer, clr-installer directly under Clear Linux OS 35080.

For sizes, it is usually safest to leave one size undefined; either define the size on each partition and do not put the total image size OR put the total image size and then one of the partitions can be left undefined and it will use the remaining space. [See the syntax for YAML](https://download.clearlinux.org/current/config/image/). But likely this is not the problem you're having.

Can you share more or all of the log file, perhaps as a gist? There might be something happening during the mount for creating the ISO image and hence seeing the write error?

Also, it would be helpful to know what the release of Clear Linux OS you are using on the system used to run mixer.

**Comment by postmannen** [comment]
@mdhorn Thanks a lot.

I will try to just set the boot partition to a fixed size, and let others be undefined.

Here is the log file [gist](https://gist.github.com/postmannen/e7021616a0bdecc5aaaf145e4912f89b)

Release info:
```
#  swupd info
Distribution:      Clear Linux OS
Installed version: 35380
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```

**Comment by mdhorn** [comment]
> I will try to just set the boot partition to a fixed size, and let others be undefined.

Just to clarify, all BUT one item must have a size. You can either leave the whole image without a size OR a single partition without a size.

I was able to update a host system to 35380 and still generate an image and ISO with your yaml file.

Reading through the full log, it looks like the problem is running out of space in the `/tmp` file system of the system where the clr-installer (mixer) is being executed.  Please check your `/tmp` size and usage.

The write failure happens for the directory in `/tmp` where the content is created to be used for the ISO generation by `xorriso`. You were probably closed to out of space in '/tmp', and just adding a new bundle pushed the size to be larger than available.

**Comment by postmannen** [comment]
You are absolutely right.

I noticed that error, but I related it to the mounted loop device. But of course it is locally on the server, which I should have checked.
Didn't notice the the default installation created a separate small /tmp partition alongside /root.But now I do!

Thanks a lot for the help @mdhorn

**Comment by mk-rl** [comment]
@mdhorn  

It looks to me that this error was related to the 100M efiboot.img
https://github.com/clearlinux/clr-installer/commit/1bdd4ec174995560095eb38691ed8f3b8b1e27ad

@djklimes  I agree that this would be great to have exposed in the clr installer yaml file. Is there a time estimate if/when that might happen?

**Comment by djklimes** [comment]
> @mdhorn
> 
> It looks to me that this error was related to the 100M efiboot.img [clearlinux/clr-installer@1bdd4ec](https://github.com/clearlinux/clr-installer/commit/1bdd4ec174995560095eb38691ed8f3b8b1e27ad)
> 
> @djklimes I agree that this would be great to have exposed in the clr installer yaml file. Is there a time estimate if/when that might happen?

There is some other work that we are trying to finish with clr-installer that may affect this.  If people become blocked by the issue noted we will revisit timelines but I did recently build an 80G image so it's not about the amount of packages added (just if larger things go in that particular partition).
