### ISSUE TITLE
cmake/autotools return `/usr/local` as prefix but ldconfig doesn't search under `/usr/local` by default

### ISSUE THREAD

**Issue by keerockl** [clearlinux/distribution#249]
/usr/local/lib64 is not included in default library path.

**To Reproduce**
1. use CMAKE_INSTALL_LIBDIR in cmake install which returns as /usr/local/lib64
2. run installed executable file and check to see if system finds libs installed in default lib dir "/usr/local/lib64"
3. system fails as it doesn's include path /usr/local/lib64 as default. it only checks in /usr/lib64

please include /usr/local/lib64 as default library path.

**Comment by ahkok** [comment]
Note: the fact that autotools etc. use `/usr/local` as default prefix is customary, and even `autotools` will print out warnings when you run `make install` to warn you that you may need to run `ldconfig` or modify linker properties to use the software.

**Comment by ahkok** [comment]
Keeping this as-is.
