### ISSUE TITLE
clr_power segfault at boot

### ISSUE THREAD

**Issue by elektrolytik** [clearlinux/distribution#2491]
OS Version 35390

At system startup, clr_power segfaults and dumps core:
kernel: clr_power[254]: segfault at 1 ip 00007f37700ffa8a sp 00007fff572665d8 error 4 in libc-2.34.so[7f3770067000+1a4000]

I have included a core dump if it is at all useful.

This system was previously on 35310 which did not have any issues.

Please let me know if you need any more information to help troubleshoot this.

[core.clr_power.zst.zip](https://github.com/clearlinux/distribution/files/7678180/core.clr_power.zst.zip)

**Comment by insilications** [comment]
I can confirm this with the default clr_power provided by 35390. With my self-compiled custom clr_power, it does not happen.

**Comment by wojfr** [comment]
on OS version 35410 the same issue on system startup
![png](https://user-images.githubusercontent.com/80601432/146467674-092b5e31-02cf-4311-8a93-53f0b21d2014.png)

**Comment by fenrus75** [comment]
we fixed this yesterday... hopefully will go out in a release early tomorrow

**Comment by phmccarty** [comment]
Fixed in release [35440](https://cdn.download.clearlinux.org/releases/35440/clear/RELEASENOTES-35410-to-35440).
