### ISSUE TITLE
udisks2 daemon fails to load configuration file. Stateless patch in the udisks2 package needs a fix

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2493]
> Dec 14 06:23:49 insilications dbus-daemon[568]: [system] Activating via systemd: service name='org.freedesktop.UDisks2' unit='udisks2.service' requested by ':1.21' (uid=1000 pid=1454 comm="/usr/bin/plasmashell")
> Dec 14 06:23:49 insilications udisksd[1502]: udisks daemon version 2.9.4 starting
> Dec 14 06:23:49 insilications udisksd[1502]: Can't load configuration file /usr/share/defaults/udisks2.conf

The correct path should be /usr/share/defaults/udisks2/udisks2.conf: https://github.com/clearlinux-pkgs/udisks2/blob/master/0001-Add-support-for-a-stateless-configuration-file.patch

The patch fix: https://github.com/insilications/udisks2/blob/master/0001-Add-support-for-a-stateless-configuration-file.patch

**Comment by bryteise** [comment]
Thanks for the fix, should be in the next release.
