### ISSUE TITLE
login command not working

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2499]
![download](https://user-images.githubusercontent.com/91722596/146787583-7b5aae7a-fe88-49d1-aaaf-ddddc2f3a3af.gif)
```log
$ gdb -q login
Reading symbols from login...
Reading symbols from /usr/lib/debug/.build-id/c6/7cba2291e31fb535e03b718da5c6b36a3af864.debug...
(gdb) run
Starting program: /usr/bin/login 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[Inferior 1 (process 8816) exited with code 01]
```

**Comment by fenrus75** [comment]
hmm what did you expect it to do?  I've only ever implicitly used login/etc
(to log into ttys) never like this.. not sure what it is even supposed to do

**Comment by nobodyatandnothing** [comment]
> hmm what did you expect it to do?

If no argument is given, login prompts for the username.
and it doesnt work with explicit username and/or host either
when i run it as root the terminal  prompts for the password even when username is not given and when the correct password is entered the terminal immediately shuts down.
