### ISSUE TITLE
FreeCAD bundle maker-cnc will not work 

### ISSUE THREAD

**Issue by ruetherlinux** [clearlinux/distribution#2501]
FreeCAD bundle maker-cnc since CL version 35290 the FreeCAD app will not work.

in the last update 35460 it will also not work 

Terminal i can not find:
----------------------------------------
xxx$ which FreeCAD
which: no FreeCAD in (/usr/local/bin:/usr/bin:/opt/3rd-party/bin)

-------------------------------------

$ sudo    swupd  bundle-info  maker-cnc  --dependencies 
Passwort: 
____________________________
 Info for bundle: maker-cnc
____________________________

Status: Explicitly installed

Bundle maker-cnc is up to date:
 - Installed bundle last updated in version: 35420
 - Latest available version: 35420

Bundle size:
 - Size of bundle: 50,65 MB
 - Size bundle takes on disk (includes dependencies): 4,52 GB

Direct dependencies (6):
 - inkscape
 - maker-basic
 - openscad
 - os-core
 - pygobject
 - python-extras

Indirect dependencies (21):
 - Babel
 - Sphinx
 - cloud-api
 - findutils
 - fonts-basic
 - graphviz
 - lib-imageformat
 - lib-opengl
 - lib-openssl
 - libX11client
 - libglib
 - libstdcpp
 - minicom
 - openblas
 - p11-kit
 - perl-basic
 - python3-basic
 - python3-tcl
 - qt-basic
 - qt-core
 - tcl-basic
--------------------------------
neofetch            BBB                install@tower-asrock-crutial-250 
       BBBBBBBBB             -------------------------------- 
     BBBBBBBBBBBBBBB         Linuxversion: Clear Linux OS x86_64 
   BBBBBBBBBBBBBBBBBBBB      Kernelversion: 5.15.10-1109.native 
   BBBBBBBBBBB         BBB   Betriebszeit: 2 hours, 22 mins 
  BBBBBBBBYYYYY              Packages: 20 (rpm) 
  BBBBBBBBYYYYYY             Shell: bash 5.1.12 
  BBBBBBBBYYYYYYY            Anzeige Einstellung: 3840x2160 
  BBBBBBBBBYYYYYW            Fenstermanager: awesome 
 GGBBBBBBBYYYYYWWW           Thema: Adwaita [GTK3] 
 GGGBBBBBBBYYWWWWWWWW        Icons: Adwaita [GTK3] 
 GGGGGGBBBBBBWWWWWWWW        Terminal: xfce4-terminal 
 GGGGGGGGBBBBWWWWWWWW        Terminal Font: Monospace 12 
GGGGGGGGGGGBBBWWWWWWW        CPU-Prozessorversion: Intel i7-2600K (8) @ 3.800GHz [37.0°on] 
GGGGGGGGGGGGGBWWWWWW         GPU-Grafikkarte: NVIDIA GeForce GTX 1050 Ti 
GGGGGGGGWWWWWWWWWWW          RAM Speichergröße Benutzt / Frei: 1888MiB / 7897MiB 
GGWWWWWWWWWWWWWWWW           CPU Usage, Auslastung: 4% 
 WWWWWWWWWWWWWWWW            Festplattenspeicherplatz (/): 36G / 56G (68%) 
      WWWWWWWWWW             Font: Clear Sans 10 [GTK3] 
          WWW                Lokale IP Adresse: xxxx
                             Public IP: xxxxx
                             Benutzer: install, root 
                             Lokale Tastatur: de_DE.UTF-8 
                             cpu Temperatur: on

**Comment by pixelgeek** [comment]
FreeCAD was deprecated in November 2021 from Clear Linux due to increasing challenges with build dependencies https://github.com/clearlinux/clr-bundles/commit/92bb5af5c7fd0b719a064e5f02170e4d67b1f475
It should still be installable from a flatpak - https://clearlinux.org/software/flathub/freecad
