### ISSUE TITLE
include a preconfigured inputrc

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2504]
in the bash manual [8.4.6](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Completion.html#index-menu_002dcomplete-_0028_0029) :

menu-complete ()

  Similar to complete, but replaces the word to be completed with a single match from the list of possible completions. Repeated execution of menu-complete steps through the list of possible completions, inserting each match in turn. At the end of the list of completions, the bell is rung (subject to the setting of bell-style) and the original text is restored. An argument of n moves n positions forward in the list of matches; a negative argument may be used to move backward through the list. ***This command is intended to be bound to TAB, but is unbound by default.***  :point_left: 

can `~/.inputrc` be included by default with the following line : `"\t": menu-complete`

**Comment by phmccarty** [comment]
Do you think this change of default would be useful for packages that use `readline` in general, or just for `bash` (which is built to statically link its own private `readline` library)?

**Comment by nobodyatandnothing** [comment]
i dont know

**Comment by nobodyatandnothing** [comment]
i think menu-complete () in general is more useful than the default. the default is more useful as a search function than a comletion function
