### ISSUE TITLE
devpkg-libhandy

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2506]
Official package name: not a package; i am requesting a bundle for libhandy-1.pc

Description: .pc files may be added with devpkg-* bundles. i need a libhandy-1.pc file, but there is no devpkg-libhandy
there is a libhandy-dev package in the desktop-dev bundle but the desktop-dev bundle is 3484MB

**Comment by fenrus75** [comment]
adding libhandy-1 to the list for generated devpkgs

**Comment by nobodyatandnothing** [comment]
thank you

**Comment by nobodyatandnothing** [comment]
devpkg-libhandy has been added
