### ISSUE TITLE
glibc is still using DWARF 4?

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2508]
Is there a current reason for glibc being compiled with dwarf 4? https://github.com/clearlinux-pkgs/glibc/commit/7757e3c2110224799911adbf0c1a9e8d8ebe4bc5#diff-2b9c26af7c2bf024a808656971595776fb6dc56aedb170bf9a255eaa5fb24937

Thanks.

**Comment by fenrus75** [comment]
for some time several tools in the distro really did not deal well with
dwarf5, including some of the rpm debug info tools.

it's probably time to try again I suppose

**Comment by insilications** [comment]
It seems at least debugedit is now able to deal with dwarf5 https://sourceware.org/git/?p=debugedit.git&a=search&h=HEAD&st=commit&s=dwarf5
