### ISSUE TITLE
WiFi drivers for Realtek 8188

### ISSUE THREAD

**Issue by uudruid74** [clearlinux/distribution#251]
**Describe the bug**
Attempting to install on a laptop with Realtek 8188 based WiFi and can't get past the network config screen since the system doesn't seem to recognize the WiFi hardware.

**Expected behavior**
Expected to be able to install since this is a fairly old system and all other Linux distros have worked without a hitch.

**Comment by ahkok** [comment]
The driver is enabled in `linux-native`. It may be due to missing firmware, but we need to know what firmware is needed. Can you check e.g. `dmesg | grep firmware` ?

Note that wifi and installation are currently not supported. It's possible to shell out and manually configure wifi, but it's difficult and a manual process (set up wpa_supplicant etc).

**Comment by miguelinux** [comment]
Could you tell us what version of kernel are you running?

$ uname -r 

We added many rtl drivers at linux-4.18.16-646.

or what clear linux version are you running?

$ cat /usr/lib/os-release

**Comment by ahkok** [comment]
@uudruid74 can you provide the requested information?

**Comment by uudruid74** [comment]
It's kind of hard to do since I'm not running clearlinux. If the installer won't install... But doesn't leave me with a whole lot of incentive to get this done. Well I have a chance to read my laptop and spend a while getting this information, I will attempt to do so. Hopefully your installer will let me get to a shell prompt, and has these tools pre-loaded. The phone later I'll get there as soon as I get home if I have time tonight using my existing installation

**Comment by miguelinux** [comment]
> firmware is rtlwifi/rtl8188efw.bin (on another distro).  I'll post the other info in a second (booting clear installer now)
> 

We have it already

$ sudo swupd search rtl8188ee.ko
Searching for 'rtl8188ee.ko'

Bundle linux-dev	(308 MB to install)
	/usr/lib/modules/4.18.16-650.native/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8188ee/rtl8188ee.ko

Bundle kernel-native	[installed]	(434 MB on system)
	/usr/lib/modules/4.18.16-650.native/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8188ee/rtl8188ee.ko



and the firmware too


$ sudo swupd search rtlwifi/rtl8188efw.bin
Searching for 'rtlwifi/rtl8188efw.bin'

Downloading Clear Linux manifests
   51.65 MB total...

Completed manifests download.

Bundle hardware-wifi	(220 MB to install)
	/usr/lib/firmware/rtlwifi/rtl8188efw.bin

Bundle wpa_supplicant	[installed]	(223 MB on system)
	/usr/lib/firmware/rtlwifi/rtl8188efw.bin

Bundle games-dev	(2509 MB to install)
	/usr/lib/firmware/rtlwifi/rtl8188efw.bin

**Comment by tpleavitt** [comment]
If this is still an issue, please reopen
