### ISSUE TITLE
Support ElanTech (and possibly other) touchpads

### ISSUE THREAD

**Issue by jannisch** [clearlinux/distribution#252]
**Is your feature request related to a problem? Please describe.**
The ElanTech touchpad on my notebook is not recognized, instead the kernel falls back to a virtual Logitech mouse. Therefore I can not use two-finger scrolling and other features.
Apparently this is because the ElanTech drivers are not enabled in the kernel yet even though these touchpads are widely used (especially in Asus notebooks). In contrast, the Asus hotkey driver (volume, backlight etc) is already supported as you can see at the end of this post.

**Describe the solution you'd like**
Please enable `CONFIG_MOUSE_PS2_ELANTECH` and drivers for other relevant touchpad models in the desktop kernel.

**Describe alternatives you've considered**
\-

**Additional context**
My output of the `xinput` command:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ PS/2 Logitech Wheel Mouse               	id=12	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ Asus WMI hotkeys                        	id=10	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=11	[slave  keyboard (3)]
```

**Comment by ahkok** [comment]
@miguelinux

**Comment by miguelinux** [comment]
It is enabled at linux-4.18.16-650

**Comment by jannisch** [comment]
Thank you, works perfectly now!

**Comment by alessiodallapiazza** [comment]
Good morning,
with the latest release of the Kernel 5.4.2 (https://github.com/clearlinux-pkgs/linux/commit/c8d338a552639b552ff9faa13e47e809dea6d810) the touchpad is not working anymore. 

Xinput output:
`source@source~ $ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech Wireless Keyboard PID:4023     	id=11	[slave  pointer  (2)]
⎜   ↳ Logitech Wireless Mouse                 	id=12	[slave  pointer  (2)]
⎜   ↳ ELAN1010:00 04F3:3012 Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=19	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=13	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=15	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=16	[slave  keyboard (3)]
    ↳ DELL Wireless hotkeys                   	id=17	[slave  keyboard (3)]
    ↳ Logitech Wireless Keyboard PID:4023     	id=18	[slave  keyboard (3)]
`

Looking forwards. 

Thanks !

**Comment by thiagomacieira** [comment]
xinput is still listing your Elantech touchpad (looks like a Dell XPS, laptop). Can you check at what level this is failing? Please use the `xinput test-xi2` tool (with devices 14 and 19) and the `evtest` tool on the same two devices (find them by name). Let us know which of the two tools reports no events.

**Comment by alessiodallapiazza** [comment]
Good morning, here you have the results. 
I am using a Dell Inspirion. 
`
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 Mouse	id=12	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 Consumer Control	id=13	[slave  pointer  (2)]
⎜   ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 Consumer Control	id=15	[slave  pointer  (2)]
⎜   ↳ ETPS/2 Elantech Touchpad                	id=19	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0	id=11	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 System Control	id=14	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=16	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=17	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=18	[slave  keyboard (3)]
    ↳ DELL Wireless hotkeys                   	id=20	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 Consumer Control	id=21	[slave  keyboard (3)]
    ↳ Microsoft Microsoft® 2.4GHz Transceiver v7.0 Consumer Control	id=22	[slave  keyboard (3)]
`
No activities registered for xinput:
`
source@source~ $ xinput test-xi2 19
ETPS/2 Elantech Touchpad                	id=19	[slave  pointer  (2)]
	Reporting 9 classes:
		Class originated from: 19. Type: XIButtonClass
		Buttons supported: 12
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right" None None None None None
		Button state:
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 0:
		  Label: Rel X
		  Range: 0.000000 - 3220.000000
		  Resolution: 31000 units/m
		  Mode: relative
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 1:
		  Label: Rel Y
		  Range: 0.000000 - 2422.000000
		  Resolution: 31000 units/m
		  Mode: relative
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 2:
		  Label: Rel Horiz Scroll
		  Range: 0.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 3:
		  Label: Rel Vert Scroll
		  Range: 0.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 4:
		  Label: Abs MT Touch Major
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 19. Type: XIValuatorClass
		Detail for Valuator 5:
		  Label: Abs MT Pressure
		  Range: -1.000000 - -1.000000
		  Resolution: 0 units/m
		  Mode: relative
		Class originated from: 19. Type: XIScrollClass
		Scroll info for Valuator 2
		  type: 2 (horizontal)
		  increment: 80.000000
		  flags: 0x0
		Class originated from: 19. Type: XIScrollClass
		Scroll info for Valuator 3
		  type: 1 (vertical)
		  increment: 80.000000
		  flags: 0x0

`

Evtest:

`
I: Bus=0011 Vendor=0002 Product=000e Version=0000
N: Name="ETPS/2 Elantech Touchpad"
P: Phys=isa0060/serio1/input0
S: Sysfs=/devices/platform/i8042/serio1/input/input39
U: Uniq=
H: Handlers=event21 
B: PROP=5
B: EV=b
B: KEY=e420 10000 0 0 0 0
B: ABS=661800011000003

`

No feedback:

`
source@source~ $ sudo evtest /dev/input/event21
Password: 
Input driver version is 1.0.1
Input device ID: bus 0x11 vendor 0x2 product 0xe version 0x0
Input device name: "ETPS/2 Elantech Touchpad"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 325 (BTN_TOOL_FINGER)
    Event code 330 (BTN_TOUCH)
    Event code 333 (BTN_TOOL_DOUBLETAP)
    Event code 334 (BTN_TOOL_TRIPLETAP)
    Event code 335 (BTN_TOOL_QUADTAP)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max     3220
      Resolution      31
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max     2422
      Resolution      31
    Event code 24 (ABS_PRESSURE)
      Value      0
      Min        0
      Max      255
    Event code 28 (ABS_TOOL_WIDTH)
      Value      0
      Min        0
      Max       15
    Event code 47 (ABS_MT_SLOT)
      Value      0
      Min        0
      Max        4
    Event code 48 (ABS_MT_TOUCH_MAJOR)
      Value      0
      Min        0
      Max     2415
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max     3220
      Resolution      31
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max     2422
      Resolution      31
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max    65535
    Event code 58 (ABS_MT_PRESSURE)
      Value      0
      Min        0
      Max      255
Properties:
  Property type 0 (INPUT_PROP_POINTER)
  Property type 2 (INPUT_PROP_BUTTONPAD)
Testing ... (interrupt to exit)

`
