### ISSUE TITLE
rxvt-unicode 256 color

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2524]
please compile rxvt-unicode with `--enable-256-color` configured, or at least provide an alternate bundle rxvt-unicode with 256 color support

**Comment by fenrus75** [comment]
eh I checked and we have that option enabled

something must not be working for you to ask for it ;)

do you ahve more details of something that should work but isn't ?

**Comment by nobodyatandnothing** [comment]
```
$ cat ~/.Xresources
URxvt*termName: rxvt-unicode-256color
URxvt.color12: rgb:5c/5c/ff
*customization: -color
```
```
$ echo $TERM
rxvt-unicode-256color
$ tput colors
256
```
```
 for i in {0..255} ; do
    printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i" 
    if (( i == 15 )) || (( i > 15 )) && (( (i-15) % 6 == 0 )); then
        printf "\n";
    fi
done
```
![Screenshot from 2022-01-18 16-40-17](https://user-images.githubusercontent.com/91722596/150023112-9ffed859-8afc-4ef5-b09c-47cebdf976bf.png)
