### ISSUE TITLE
the fluidsynth bundle should come with soundfonts

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2525]
```log
$ fluidsynth -a alsa ~/Downloads/achilles_chip_export.mid 
FluidSynth runtime version 2.2.3
Copyright (C) 2000-2021 Peter Hanappe and others.
Distributed under the LGPL license.
SoundFont(R) is a registered trademark of Creative Technology Ltd.

fluidsynth: error: fluid_sfloader_load(): Failed to open '/usr/share/soundfonts/default.sf2': File does not exist.
fluidsynth: error: Unable to open file '/usr/share/soundfonts/default.sf2'
fluidsynth: error: Failed to load SoundFont "/usr/share/soundfonts/default.sf2"
```
https://github.com/FluidSynth/fluidsynth/tree/master/sf2
https://github.com/FluidSynth/fluidsynth/blob/master/sf2/COPYRIGHT.txt
would clear linux include digital content that is not completely "free" ?

**Comment by insilications** [comment]
As a fluidsynth user, I can suggest a few soundfonts and their respective licenses:

https://github.com/dosbox-staging/dosbox-staging/wiki/MIDI#soundfonts

FluidR3 is one of the most used soundfonts, very complete and beautiful for all kinds of sounds. It uses a MIT license. It is the soundfont included in arch's fluidsynth (AUR) and debian. 

I don't know how the CL would proceed to bundle this. In its own packages or inside fluidsynth itself? I can provide the patches.

**Comment by nobodyatandnothing** [comment]
in fluidsynth so fluidsynth would be able to be used to play midi files without additional downloads.

thanks for the link
