### ISSUE TITLE
Misspelled PGO flags in openssl package

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2528]
Misspelled PGO flags in openssl package:

```
export CFLAGS="${CFLAGS_USE}  -mno-vzeroupper -march=x86-64-v3" 
export CXXFLAGS="${CXXFLAGS_USE}  -mno-vzeroupper -march=x86-64-v3" 
export FFLAGS="${FFLAGS_USE} -mno-vzeroupper -march=x86-64-v3" 
export FCFLAGS="${FCFLAGS_USE} -mno-vzeroupper -march=x86-64-v3" 
export LDFLAGS="${LDFLAGS_USA}"

```

https://github.com/clearlinux-pkgs/openssl/blob/26e3ed1319d2777e7cc3b44891aa22323b3b91d9/openssl.spec#L162

**Comment by pixelgeek** [comment]
It's being fixed.  Should show up when the repo is next refreshed.

**Comment by pixelgeek** [comment]
https://github.com/clearlinux-pkgs/openssl/commit/219d3fd4ac2ed43adf437879f0253404d21d4535#diff-b72470fbfcb8ec814616287c1c32094b50ff4b5daaf654677f4d3d99803735cd
