### ISSUE TITLE
qemu-bridge-helper losts setuid permission after a system upgrade.

### ISSUE THREAD

**Issue by hksdpc250** [clearlinux/distribution#2529]

**Comment by hksdpc250** [comment]
```bash
chmod u+s /usr/libexec/qemu-bridge-helper
```

**Comment by phmccarty** [comment]
@hksdpc250 Can you provide more details about the issue, like what version of Clear Linux OS you updated *from* and *to*?

**Comment by hksdpc250** [comment]
The latest version, I guess. I turned on auto upgrade.

**Comment by fenrus75** [comment]
ok I see what's up... fixing

**Comment by hksdpc250** [comment]
Thank you for your work. :)

**Comment by marioroy** [comment]
Ditto for /usr/libexec/dbus-daemon-launch-helper without sticky bit u+s enabled. I wasn't able to add an HP printer. The permission of the setuid helper is not correct.

And subsequently not able to determine which bundle has the Python module. ModuleNotFoundError: No module named 'cupshelpers'.

**Comment by hksdpc250** [comment]
It seems this issue has been fixed.
