### ISSUE TITLE
gnuplot not loading `~/.gnuplot`

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2530]
this is very bad
```
$ gnuplot
gnuplot> show loadpath

        loadpath is empty
        gnuplotrc is read from /usr/share/gnuplot/5.4
        no XAPPLRESDIR found in the environment,
            falling back to "@X11_APPDEFAULTS_DIR@"

**Comment by fenrus75** [comment]
so gnuplot can load from current directory but that is flagged as insecure
in the documentation -- likely a bad idea ;)

trying to chase where this should come from instead

**Comment by fenrus75** [comment]
a strace on my machine shows it does try
openat(AT_FDCWD, "/home/arjan/.gnuplot", O_RDONLY) = -1 ENOENT (No such
file or directory)
so... weird

**Comment by nobodyatandnothing** [comment]
it is loading my ~/.gnuplot, i just thought it wasn't because it printed "Terminal is now 'qt'" 
 
i apologize for wasting your time. please forgive me.
