### ISSUE TITLE
LXC does not work "out of the box"

### ISSUE THREAD

**Issue by bogen85** [clearlinux/distribution#2535]
After installing the needed container and libvirt packages was able to create an LXC container via libvirt.
However, it would not start, I ran into a ```failed with NoMachineForPID Error``` error.

I tracked the issue down and found a link to the fix here: https://bugs.archlinux.org/task/70174
```
-options root=PARTUUID=01ad87f8-f4cc-44ff-b3fb-bb28ed15b6ae quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw
+options root=PARTUUID=01ad87f8-f4cc-44ff-b3fb-bb28ed15b6ae quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw systemd.unified_cgroup_hierarchy=1
```
Basically had to add ```systemd.unified_cgroup_hierarchy=1``` to the Linux comand line, and now I can start containers.

A much more in depth discussion can be found here: https://bugzilla.opensuse.org/show_bug.cgi?id=1183247
and here: https://gitlab.com/libvirt/libvirt/-/issues/182#note_763329557

Is there a way to add extra linux command line arguments that automatically get picked up?

Or I will have have to resort to using something like ansible to apply the addition to the loader configuration files?

**Comment by fenrus75** [comment]
man clr-boot-manager has this documented:

       /etc/kernel/cmdline.d/*.conf
           A set of files that will be used to modify the kernel commandline. The files can also be used to mask the vendor cmdline if the filename matches a vendor configuration file and is linked to /dev/null. The  vendor  configuration  files  are  /usr/lib/ker‐
           nel/cmdline-* and /usr/share/kernel/cmdline.d/*.conf.

           The files should be in plain text format and each line will be appended directly to the kernel commandline.
