### ISSUE TITLE
Update qtbase 5.15.2 with the opensource Qt5 Patch Collection

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2537]
https://community.kde.org/Qt5PatchCollection

`Here we have a version of Qt 5 that includes fixes for the issues we have found impacted the use of open source products
`
It could be as easy as: 

How do I get this integrated in my distribution?
```
These patches can be obtained with the following command:
   git format-patch origin/5.15.2..origin/kde/5.15
They can then be integrated using the tooling specific to your distribution.
```

What OpenSUSE is doing:
`The KDE project provides unofficial support for Qt 5.15 in the form of a collection of bugfix patches, most of which are backported from Qt 6.[50] As KDE has a policy of not assigning version numbers to their patches, Linux distributions use ad-hoc schemes when using this fork of Qt5: OpenSUSE, for example, calls its June 2021 version "5.15.2+kde200".[51]`
https://en.wikipedia.org/wiki/Qt_version_history

**Comment by insilications** [comment]
I'm labeling this as a very tentative suggestion for the CL team, because in the end the fixes might not be so significant or important. I know the team has a lot to deal already.

**Comment by thiagomacieira** [comment]
We should definitely do it.

**Comment by phmccarty** [comment]
I think we have added automation to add patches to the qt* packages. If we missed any patches, please reopen.
