### ISSUE TITLE
[Package update] Wayland-protocols

### ISSUE THREAD

**Issue by original-tinozza** [clearlinux/distribution#2538]
Current version in CLR repository: 1.23 (Sep 13, 2021)
Latest version available: [1.25](https://wayland.freedesktop.org/releases/wayland-protocols-1.25.tar.xz) (Jan 28, 2022)

Announcement and changelog [here](https://lists.freedesktop.org/archives/wayland-devel/2022-January/042102.html)

Many thanks in advance :)

**Comment by fenrus75** [comment]
done (and set to auto-update in the future since this has proven itself to
be well behaving)

**Comment by original-tinozza** [comment]
@fenrus75 many thanks :)
As always super fast.
