### ISSUE TITLE
containerd v1.2.0

### ISSUE THREAD

**Issue by mythi** [clearlinux/distribution#254]
**List the package you would like to see updated**
containerd

**Does this update provide any significant new features that may be needed**
- CRI plugin that enables to use it with kubernetes directly
- RuntimeClass implementation that works with kubernetes 1.12 (benefits kata)

**Note(s):**
- Clear's docker has a dependency to containerd. The update shall be done so that docker still works
- deprecate cri-containerd (https://github.com/containerd/cri/blob/master/README.md)

**Comment by ahkok** [comment]
@eljuarez is this something you can help with?

**Comment by eljuarez** [comment]
@mythi I am just checking this, so you wish to update this package to the latest version 1.2.0??

**Comment by mythi** [comment]
1.2.0 is the target, yes. However, to get there is involves more than just containerd upgrade.

**Comment by mythi** [comment]
cleaning old bugs. we have v1.2.6 now.
