### ISSUE TITLE
Please update `gdal`

### ISSUE THREAD

**Issue by lnicola** [clearlinux/distribution#2541]
It's currently on 3.2.1, from July 2020.

**Comment by fenrus75** [comment]
the gdal world seems to be a forest of incompatible ABI changes which
caused us to have to revert an upgrade earlier

maybe the ecosystem is ready now for the new gdal but.... shudder

**Comment by lnicola** [comment]
Oh, feel free to close this if it's too hard. I've only started playing with Clear Linux, so I couldn't even figure out how to check what depends on `gdal`.

**Comment by phmccarty** [comment]
`gdal` was updated in release [35900](https://cdn.download.clearlinux.org/releases/35900/clear/RELEASENOTES-35860-to-35900).
