### ISSUE TITLE
notmuch manpages missing

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2542]

**Comment by phmccarty** [comment]
This package change resulted in the man pages no longer being built:

https://github.com/clearlinux-pkgs/notmuch/commit/ce2b7ef40e366ae08e03cce2b0dd51b4ee72948b

@fenrus75 @bryteise Was the motivation here to remove Sphinx as a build dependency? I guess I'm not finding enough context here :-)

**Comment by phmccarty** [comment]
We restored the `pypi-sphinx` build dependency (formerly packaged as `Sphinx`), and removed `--without-docs` from the configure call. Those two steps restore the notmuch man pages.

The changes should land in the next release.
