### ISSUE TITLE
KDE: qqc2-desktop-style is missing that library again

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2549]
Same problem happened again, probably because of the "ordering in which the KDE packages were updated" (https://github.com/clearlinux/distribution/issues/2526#issuecomment-1025076373)

qqc2-desktop-style package (https://github.com/clearlinux-pkgs/qqc2-desktop-style/blob/master/qqc2-desktop-style.spec), which is included in the desktop-kde bundle, is not including an essential library: /usr/lib64/qt5/plugins/kf5/kirigami/org.kde.desktop.so. My heavily modified autospec installs this under lib subpackage. Lack of this file leads to crashes and wrong QML design in the systemsettings5, specially in the "Appearance" tab. If you change Colors or Style to anything else different than the default Light Breeze (e.g. Dark), the systemsettings5 cannot import those alternative non-default settings into the QML design.

I also installed this as a package, after verifying that systemsettings5 is performing correctly. Just to make sure: https://download.kde.org/stable/plasma/5.24.0/qqc2-breeze-style-5.24.0.tar.xz

**Comment by phmccarty** [comment]
Thanks for the report. It was the build ordering issue as you suspected. Will be fixed in the next release.

**Comment by phmccarty** [comment]
This issue is fixed in release [35920](https://cdn.download.clearlinux.org/releases/35920/clear/RELEASENOTES).
