### ISSUE TITLE
Openssl update to 1.1.1.

### ISSUE THREAD

**Issue by halars** [clearlinux/distribution#255]
**List the package you would like to see updated**
Ideally, provide us with the name and version of the package. An upstream tarball URL also may help.

**Does this update provide any significant new features that may be needed**
If this package adds any significant features that you're currently missing, please list them.

Are there any plans to migrate to openssl 1.1.1 (lts) in the near future?

**Comment by fenrus75** [comment]
we're working on it

it's not a super trivial change due to the various compatibility issues
openssl version changes have
