### ISSUE TITLE
Cannot install working kubernetes on new OS install

### ISSUE THREAD

**Issue by pwm320** [clearlinux/distribution#2553]
The [instructions](https://docs.01.org/clearlinux/latest/tutorials/kubernetes.html) for creating a new k8s cluster don't seem to mesh with this version of CL:

Distribution:      Clear Linux OS
Installed version: 35900
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

I put together this script after a clean install and update:

    #!/bin/bash
    
    sudo swupd bundle-add cloud-native-basic
    sudo /usr/share/clr-k8s-examples/setup_system.sh
    sudo systemctl stop docker 
    sudo systemctl stop containerd
    sudo swupd bundle-add git
    sudo /usr/share/clr-k8s-examples/create_stack.sh minimal

Wind up with this:

     $ kubectl get pods -A
     NAMESPACE     NAME                              READY   STATUS                   RESTARTS       AGE
     kube-system   canal-kndpt                       0/2     Init:ImageInspectError   0          10m
     kube-system   coredns-558bd4d5db-d5hjq          0/1     Pending                  0          10m
     kube-system   coredns-558bd4d5db-x6l76          0/1     Pending                  0          10m
     kube-system   etcd-nuc                          1/1     Running                  0          10m
     kube-system   kube-apiserver-nuc                1/1     Running                  0          10m
     kube-system   kube-controller-manager-nuc       1/1     Running                  0          10m
     kube-system   kube-proxy-5lwvf                  1/1     Running                  0          10m
     kube-system   kube-scheduler-nuc                1/1     Running                  0          10m
     kube-system   metrics-server-5889d4b758-5l6tp   0/1     Pending                  0          10m
 

And a describe for the canal pod shows this:

    Name:                 canal-kndpt
    Namespace:            kube-system
    Priority:             2000001000
    Priority Class Name:  system-node-critical
    Node:                 nuc/100.1.1.13
    Start Time:           Wed, 16 Feb 2022 19:03:15 +0000
    Labels:               controller-revision-hash=6dc6d4d4d8
                          k8s-app=canal
                          pod-template-generation=1
    Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
    Status:               Pending
    IP:                   100.1.1.13
    IPs:
      IP:           100.1.1.13
    Controlled By:  DaemonSet/canal
    Init Containers:
      install-cni:
        Container ID:  
        Image:         calico/cni:v3.10.4
        Image ID:      
        Port:          <none>
        Host Port:     <none>
        Command:
          /install-cni.sh
        State:          Waiting
          Reason:       ImageInspectError
        Ready:          False
        Restart Count:  0
        Environment:
          CNI_CONF_NAME:         10-canal.conflist
          CNI_NETWORK_CONFIG:    <set to the key 'cni_network_config' of config map 'canal-config'>  Optional: false
          KUBERNETES_NODE_NAME:   (v1:spec.nodeName)
          SLEEP:                 false
        Mounts:
          /host/etc/cni/net.d from cni-net-dir (rw)
          /host/opt/cni/bin from cni-bin-dir (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-75qgs (ro)
      flexvol-driver:
        Container ID:   
        Image:          calico/pod2daemon-flexvol:v3.10.4
        Image ID:       
        Port:           <none>
        Host Port:      <none>
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Environment:    <none>
        Mounts:
          /host/driver from flexvol-driver-host (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-75qgs (ro)
    Containers:
      calico-node:
        Container ID:   
        Image:          calico/node:v3.10.4
        Image ID:       
        Port:           <none>
        Host Port:      <none>
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Requests:
          cpu:      250m
        Liveness:   exec [/bin/calico-node -felix-live] delay=10s timeout=1s period=10s #success=1 #failure=6
        Readiness:  http-get http://localhost:9099/readiness delay=0s timeout=1s period=10s #success=1 #failure=3
        Environment:
          DATASTORE_TYPE:                     kubernetes
          USE_POD_CIDR:                       true
          WAIT_FOR_DATASTORE:                 true
          NODENAME:                            (v1:spec.nodeName)
          CALICO_NETWORKING_BACKEND:          none
          CLUSTER_TYPE:                       k8s,canal
          FELIX_IPTABLESREFRESHINTERVAL:      60
          IP:                                 
          CALICO_IPV4POOL_CIDR:               192.168.0.0/16
          CALICO_DISABLE_FILE_LOGGING:        true
          FELIX_DEFAULTENDPOINTTOHOSTACTION:  ACCEPT
          FELIX_IPV6SUPPORT:                  false
          FELIX_LOGSEVERITYSCREEN:            info
          FELIX_HEALTHENABLED:                true
        Mounts:
          /lib/modules from lib-modules (ro)
          /run/xtables.lock from xtables-lock (rw)
          /var/lib/calico from var-lib-calico (rw)
          /var/run/calico from var-run-calico (rw)
          /var/run/nodeagent from policysync (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-75qgs (ro)
      kube-flannel:
        Container ID:  
        Image:         quay.io/coreos/flannel:v0.11.0
        Image ID:      
        Port:          <none>
        Host Port:     <none>
        Command:
          /opt/bin/flanneld
          --ip-masq
          --kube-subnet-mgr
        State:          Waiting
          Reason:       PodInitializing
        Ready:          False
        Restart Count:  0
        Environment:
          POD_NAME:          canal-kndpt (v1:metadata.name)
          POD_NAMESPACE:     kube-system (v1:metadata.namespace)
          FLANNELD_IFACE:    <set to the key 'canal_iface' of config map 'canal-config'>  Optional: false
          FLANNELD_IP_MASQ:  <set to the key 'masquerade' of config map 'canal-config'>   Optional: false
        Mounts:
          /etc/kube-flannel/ from flannel-cfg (rw)
          /run/xtables.lock from xtables-lock (rw)
          /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-75qgs (ro)
    Conditions:
      Type              Status
      Initialized       False 
      Ready             False 
      ContainersReady   False 
      PodScheduled      True 
    Volumes:
      lib-modules:
        Type:          HostPath (bare host directory volume)
        Path:          /lib/modules
        HostPathType:  
      var-run-calico:
        Type:          HostPath (bare host directory volume)
        Path:          /var/run/calico
        HostPathType:  
      var-lib-calico:
        Type:          HostPath (bare host directory volume)
        Path:          /var/lib/calico
        HostPathType:  
      xtables-lock:
        Type:          HostPath (bare host directory volume)
        Path:          /run/xtables.lock
        HostPathType:  FileOrCreate
      flannel-cfg:
        Type:      ConfigMap (a volume populated by a ConfigMap)
        Name:      canal-config
        Optional:  false
      cni-bin-dir:
        Type:          HostPath (bare host directory volume)
        Path:          /opt/cni/bin
        HostPathType:  
      cni-net-dir:
        Type:          HostPath (bare host directory volume)
        Path:          /etc/cni/net.d
        HostPathType:  
      policysync:
        Type:          HostPath (bare host directory volume)
        Path:          /var/run/nodeagent
        HostPathType:  DirectoryOrCreate
      flexvol-driver-host:
        Type:          HostPath (bare host directory volume)
        Path:          /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
        HostPathType:  DirectoryOrCreate
      kube-api-access-75qgs:
        Type:                    Projected (a volume that contains injected data from multiple sources)
        TokenExpirationSeconds:  3607
        ConfigMapName:           kube-root-ca.crt
        ConfigMapOptional:       <nil>
        DownwardAPI:             true
    QoS Class:                   Burstable
    Node-Selectors:              beta.kubernetes.io/os=linux
    Tolerations:                 :NoSchedule op=Exists
                                 :NoExecute op=Exists
                                 CriticalAddonsOnly op=Exists
                                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                                 node.kubernetes.io/not-ready:NoExecute op=Exists
                                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                                 node.kubernetes.io/unreachable:NoExecute op=Exists
                                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
    Events:
      Type     Reason         Age                  From               Message
      ----     ------         ----                 ----               -------
      Normal   Scheduled      18m                  default-scheduler  Successfully assigned kube-system/canal-kndpt to nuc
      Warning  Failed         16m (x12 over 18m)   kubelet            Error: ImageInspectError
      Warning  InspectFailed  3m4s (x72 over 18m)  kubelet            Failed to inspect image "calico/cni:v3.10.4": rpc error: code = Unknown desc = short-name "calico/cni:v3.10.4" did not resolve to an alias and no containers-registries.conf(5) was found

Pretty clearly it can't resolve to get the image, but I'm unclear on how to solve.

Note that this was working as expected prior to my upgrade.   

How to fix?

**Comment by ganeshmaharaj** [comment]
The newer version of cri-o no longer chooses to assume `docker.io` as a default name to search containers with and expects the user to populate a list of possible searchable registries in `/etc/containers/regitries.conf` file. Downloading https://github.com/cri-o/cri-o/blob/main/test/registries.conf and leave it at `/etc/containers` followed by a deletion of the canal pod (the exponential backoff would have hit quite the delay by now) should get the cluster moving along. We have also patched the cri-o package in the meantime to include a `registries.conf` at `/usr/share/defaults/crio` location and once tagged should no longer have this issue.
