### ISSUE TITLE
fwupd requires udisks

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2556]
```
 $ sudo fwupdmgr get-upgrades         
WARNING: UEFI ESP partition not detected or configured
  See https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found for more information.
```
https://github.com/fwupd/fwupd/wiki/PluginFlag:esp-not-found
https://github.com/clearlinux-pkgs/udisks2
https://github.com/clearlinux/clr-bundles/blob/master/bundles/firmware-update

**Comment by marioroy** [comment]
As a temporary workaround, I did the following to update my Logitech Unifying Receiver using `fwupdmgr`. The following actions were done as root i.e. `sudo su`.

```text
swupd bundle-add firmware-update      # install the firmware update bundle if not yet installed
systemctl start boot.mount            # mount the boot partition

vi /etc/fwupd/uefi_capsule.conf       # uncomment the OverrideESPMountPoint line and set to /boot/EFI
systemctl restart fwupd.service       # restart the firmware update service

fwupdmgr get-devices
fwupdmgr refresh

fwupdmgr get-updates
fwupdmgr update
```

In my case, I experienced the [Logitech Restart Failure](https://github.com/fwupd/fwupd/wiki/LVFS-Triaged-Issue:-Logitech-Restart-Failure). It's a known issue. So I ran `fwupdmgr update` again to finish the update. It may take a couple tries. That all went well.

Afterwards, optionally stop the service and remove the bundle. I needed to update the Logitech Unifying Receiver only.

```text
systemctl stop fwupd.service
swupd bundle-remove firmware-update
vi /etc/fwupd/uefi_capsule.conf       # revert change by commenting the OverrideESPMountPoint line
```

Next is complementary information if you have a Logitech mouse. The `hires-smooth-resolution` setting may not be enabled by default. The following are the steps taken to enable hires smooth resolution. Your Logitech mouse model may be different than mine. Look for the model in the `solaar show` output and use that. I have the M705 model.

```text
swupd bundle-add Solaar Solaar-gui         # there's a GUI bundle as well (optional bundle)
solaar show
solaar config M705 hires-smooth-resolution True
```

When I first started using Clear Linux, the desktop experience was awkward with regards to scrolling, especially in Firefox. Enabling hires smooth resolution resolved the issue.

**Comment by nobodyatandnothing** [comment]
has been fixed 
https://github.com/clearlinux-pkgs/fwupd/commit/75e75b17ac7738355ebf883cc5882ad507147200#diff-1f936a01a6d62f1ab3a961413a7f6abeacdfd5be8cc0e98365fffa480c236126

thank you
