### ISSUE TITLE
Please add devpkg-Vulkan-Headers

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2557]
The devpkg-Vulkan-Loader bundle is there. But missing is devpkg-Vulkan-Headers.

**Comment by fenrus75** [comment]
hrmpf has no .pc
added anyway :)

**Comment by marioroy** [comment]
Thanks. I didn't know about the developer-gpu bundle. Interestingly, `swupd search vulkan` doesn't mention it. The `developer-gpu` bundle has the header files from `Vulkan-Headers-dev`.

Running `swupd search glslang` mentions the developer-gpu bundle. Unfortunately, the developer-gpu bundle lacks the headers from glslang-dev.

Wish list: Please add missing glslang-dev and SPRIV-Cross-dev to the developer-gpu bundle.

**Comment by fenrus75** [comment]
oh that's easy :)
done for the next build

thanks for the suggestions

**Comment by fenrus75** [comment]
fwiw I think we want developer-gpu to be useful for general GPU
development as a "install this one thing and get all you need",
rather than someone having to go through a dozen different devpkg-*
so I'm all in favor of making developer-gpu better

**Comment by marioroy** [comment]
Thank you, Arjan.

This is exciting! Day by day, I'm learning and learning.
https://github.com/clearlinux/clr-bundles/blob/master/bundles/devpkg-Vulkan-Headers

Both glslang-dev and SPIRV-Cross-dev are now included in developer-gpu. This is awesome.
https://github.com/clearlinux/clr-bundles/blob/master/bundles/developer-gpu

This coming weekend, I will make an update to my FFmpeg for Clear Linux repo.

**Comment by marioroy** [comment]
Done. I updated the repo and fetch the `developer-gpu` bundle on CL 35930 and higher. Thanks again.
https://github.com/marioroy/ffmpeg-on-clear-linux/commit/c09f7f6fa259dcc35d184b6b629de57e6f890eab

Why the repo is archived? Unfortunately, I lack the time to maintain this for a short while. If anything, it's a working reference. One day I will prune the README file i.e. create a "doc" folder with multiple files.

**Comment by marioroy** [comment]
This is completed. I pruned the [README](https://github.com/marioroy/ffmpeg-on-clear-linux/blob/main/README.md) file. One day, I'd enable `wavpack` in `FFmpeg` once able to install header files via a bundle i.e. `devpkg-wavpack`.

I unarchived the repo, instead adding a comment to the top of the README.
