### ISSUE TITLE
vpp bundle doesn't contain dpdk_plugin.so

### ISSUE THREAD

**Issue by thubble** [clearlinux/distribution#2560]
The vpp bundle doesn't contain the DPDK plugin - it should be located with the rest of the plugins in /usr/lib64/vpp_plugins/dpdk_plugin.so.

This makes the clear linux VPP bundle pretty much unusable for many purposes, because DPDK is often used by VPP to access the network interfaces.

It looks like it was removed in version 21.01: https://github.com/clearlinux-pkgs/vpp/commit/3167b372af1a82128823206ae75d30605dfde0b3

Is there a reason this was removed, or is it in another package? I tried searching but couldn't find anything. The vpp bundle automatically pulled in dpdk, but the plugin doesn't exist.

**Comment by fenrus75** [comment]
-- EXPERIMENTAL: DPDK plugin without dlopen mode
-- -- libibverbs.a library not found - dpdk plugin disabled
-- -- libnl3 headers not found - linux-cp plugin disabled

it needs some static libraries.

this thing is ... grmbl static libraries are evil

**Comment by fenrus75** [comment]
the rdma-core folks really don't like making libibverbs.a ... this is not
your fault but the VPP folks are not being reasonable here in their code ;)
I'll get it sorted .. with enough violence a square peg does go through the
round hole but ...

**Comment by thubble** [comment]
It looks like the plugin is present in the latest version of the package (21.10.1), but I get the following error on startup:
`plugin/load: /usr/lib64/vpp_plugins/dpdk_plugin.so: undefined symbol: rte_pktmbuf_init`

**Comment by thubble** [comment]
I wonder if it's related to this issue? https://lists.fd.io/g/vpp-dev/topic/32312159

If I'm reading that correcly, DPDK needs to be compiled with `-fPIC` in order for VPP to link it statically.

**Comment by fenrus75** [comment]
static linking is evil

**Comment by thubble** [comment]
I finally managed to build a working version of the latest VPP using (mostly) the Clear linux build flags. I'm not sure how to adapt this into an actual spec file, especially with DPDK due to the issues I'll note at the end, but hopefully this information helps.

I did the builds on my local desktop (Gentoo testing), then tar'd up the install directory and copied to the Clear linux router (Protectli FW4B, Celeron J3160).

First, I built dpdk (21.11) and rdma-core (38.0) using the default Clear linux flags plus the ones from the .spec files, plus `-fPIC`. I installed these (including static libraries and pkgconfig files) into an external directory. I used the `PKG_CONFIG_PATH` environment variable (for dpdk) and the `-DCMAKE_PREFIX_PATH` (for vpp) to use this directory.

Then I built vpp (22.02) the same way. I needed to remove a few build flags in order for VPP to build and run properly:
- First, `-fno-semantic-interposition` caused this bug during compile: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101270
- VPP built and started successfully after removing that flag, but constantly segfaulted.
- I then removed `-flto=auto`, `-ffat-lto-objects`, and `-mtune=skylake`. VPP internally builds some - but not all - of itself with `-flto -fno-fat-lto-objects` (as long as you pass `-DCMAKE_BUILD_TYPE="release"`), so I thought that might be interfering with it. I also removed the `-mtune` because VPP's build system links together dynamic code paths with different `-march`/`-mtune` options, and I thought it might be interfering with alignments or something.
- I'm not sure which of those changes was necessary, but it worked - VPP 22.02 is running and seems to be stable!

The biggest issue I ran into is that DPDK's build system likes to find system shared libs via pkgconfig and link their symbols into its static libraries. This doesn't cause compile errors in either DPDK or VPP, but it results in unresolved symbol errors when loading `dpdk_plugin.so` because it's not dynamically linked to those required libraries. The 4 pkgconfig files that caused issues for me were `jansson.pc`, `libarchive.pc`, `libelf.pc` and `libpcap.pc`. For libpcap, it actually somehow linked it anyway even though the pkgconfig file wasn't there - I had to temporarily move `/usr/lib64/libpcap.so.1.10.1`.

VPP does work for me after all that, but I imagine that would be difficult to get working on an actual rpm build.

**Comment by thubble** [comment]
I did notice something else, it looks like in version 21.06, VPP added the cmake option `-DVPP_USE_SYSTEM_DPDK`. I haven't tried that, but maybe it would work? https://github.com/FDio/vpp/commit/f15a5791ba870a98a2ab7dec101bbbb9b6e266c1

**Comment by thubble** [comment]
I managed to build VPP with a dynamically-linked `dpdk_plugin.so` with the following options. The `ldd` output looks OK but I haven't actually tested it yet.

- Build DPDK with `--default-library=shared -Dibverbs_link="dlopen"`
- Build VPP with `-DCMAKE_BUILD_TYPE="release" -DVPP_USE_SYSTEM_DPDK=ON -DDPDK_RTE_IBVERBS_LINK_DLOPEN=true`
- Also, as per my previous comment, for the the VPP build I still got rid of the LTO flags from the .spec. Based on other fixes I had to make while building this locally, I suspect VPP also needs `-fno-fat-lto-objects -fsemantic-interposition` to override some of the default clear linux build flags. It may also need to strip out `-mtune=skylake` from the default flags if having that in turns out to cause segfaults (I'm not sure if it was that or LTO).

As I said, I haven't tested this, but I think it looks promising. The only issue is that VPP seems to be sensitive to the DPDK version it's built with, so those probably need to be kept in sync. The latest released VPP (22.02) bundles DPDK 21.11, which built fine for me using the commands from the DPDK .spec.

**Comment by thubble** [comment]
I created PRs for both DPDK and VPP (linked to this issue) to update these packages and apply some fixes. More detailed notes are in the PRs themselves, but the packages I built with them fix all the issues I was having with VPP.

**Comment by fenrus75** [comment]
thanks for the contribution!

I've merged your changes into our automation and this should be in our next release

**Comment by thubble** [comment]
I installed the vpp bundle from release 36570, and it's working perfectly. Thanks!
