### ISSUE TITLE
Clear tells user to "Run `sudo clr-service-restart -a -n` to view them." but nothing shows up

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#257]
Example:

user-hostname:~ user$ ssh clear@192.168.1.25
Password: 
 * Some system services need a restart.
   Run `sudo clr-service-restart -a -n` to view them.
user@clr-os ~ $ sudo clr-service-restart -a -n
Password: 

Nothing appears...

**Comment by tpleavitt** [comment]
@bktan8 , can this issue be closed?

**Comment by bktan8** [comment]
@ahkok - can we put a linefeed between each service listed by 'sudo clr-service-restart -a -n'?  I lost track of where I was at when I was going to through the list and restarting each one.

**Comment by tpleavitt** [comment]
@ahkok , please take a look at this again

**Comment by ipuustin** [comment]
I'm seeing this bug on fresh install on `clear-29440-kvm.img.xz` image. Please reopen.

**Comment by gladykov** [comment]
Also seeing that... So not sure why it was closed
