### ISSUE TITLE
please add `--with-insults[=disabled]` to sudo configure options

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2572]

**Comment by fenrus75** [comment]
eh who why what??

**Comment by nobodyatandnothing** [comment]
https://github.com/clearlinux-pkgs/sudo/pull/1

**Comment by nobodyatandnothing** [comment]
is there any chance you are going to add this?

**Comment by nobodyatandnothing** [comment]
debian has insults   https://salsa.debian.org/sudo-team/sudo/-/blob/master/debian/OPTIONS#L3

**Comment by nobodyatandnothing** [comment]
arch has insults https://github.com/archlinux/svntogit-packages/blob/e44d50c09f169b0dd7974b91fced7c68967e4558/trunk/PKGBUILD#L50

**Comment by bryteise** [comment]
It is a super small binary size increase, I'm not sure what the value is though.

**Comment by phmccarty** [comment]
I am confused about the ask here... Is the request to disable or enable the insults?

**Comment by phmccarty** [comment]
... because the issue subject says to add `--with-results[=disabled]`

**Comment by nobodyatandnothing** [comment]
> I am confused about the ask here... Is the request to disable or enable the insults?

`--with-insults` enables insults by default
`--with-insults=disabled` adds insults library but does not enable it by default

https://github.com/sudo-project/sudo/blob/main/INSTALL.md

**Comment by nobodyatandnothing** [comment]
> I'm not sure what the value is though.

it has value to some people, at least. other wise it would not be an available option, and other distros would not enable it.

**Comment by bryteise** [comment]
> it has value to some people, at least. other wise it would not be an available option, and other distros would not enable it.

Well fair enough, no particular reason not to as it adds about 1k to the binary sizes from my not too hard eyeballing.

**Comment by phmccarty** [comment]
> > I am confused about the ask here... Is the request to disable or enable the insults?
> 
> `--with-insults` enables insults by default `--with-insults=disabled` adds insults library but does not enable it by default
> 
> https://github.com/sudo-project/sudo/blob/main/INSTALL.md

Thanks for clarifying. I only checked the output of `./configure --help`, which does not document the `disabled` value...

**Comment by nobodyatandnothing** [comment]
thank you
