### ISSUE TITLE
Package Request: linux-lts2021

### ISSUE THREAD

**Issue by hksdpc250** [clearlinux/distribution#2580]
Official package name: Linux

License (must be an OSI approved Open Source license): multiple license

Download URL of latest release: https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.27.tar.xz

Latest release date (must be recent): https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.15.27.tar.xz

Description: Please add the latest LTS release (5.15) of linux kernel.

**Comment by nobodyatandnothing** [comment]
duplicate of https://github.com/clearlinux/distribution/issues/2570

**Comment by phmccarty** [comment]
Closing as a duplicate of #2570
