### ISSUE TITLE
nginx 1.20.2

### ISSUE THREAD

**Issue by tixoi** [clearlinux/distribution#2584]
Hi,
nginx has stable and mainline versions (branches).
"Stable" means that no new features are added (the feature set is stable) and only major bug fixes are committed to this version. Stable does not mean more reliable or more bug‑free, but changes in the stable branch are very unlikely to affect third‑party modules.
Meanwhile in the "mainline" version new features and all bug fixes are developed. In general "mainline" is recommended for the deployment.

So, are you not updating the stable version on purpose? If not, 1.16.1 is outdated and 1.20.2 the current stable version.

**Comment by phmccarty** [comment]
I think we were not monitoring `nginx` as closely as `nginx-mainline`.

Looks like nginx 1.20.2 has been integrated, so it should be available in the next release.

**Comment by nobodyatandnothing** [comment]
has been updated

**Comment by phmccarty** [comment]
nginx 1.20.2 was integrated for the [36020](https://cdn.download.clearlinux.org/releases/36020/clear/RELEASENOTES) release.
