### ISSUE TITLE
Allow clr-boot-manager to switch kernel types for user

### ISSUE THREAD

**Issue by szollin** [clearlinux/distribution#259]
**Is your feature request related to a problem? Please describe.**
When you install a different kernel type (ie: install lts kernel when native is installed), you must go through a process to switch the kernel and clean up residual files.

**Describe the solution you'd like**
To make it easier to switch between the different kernel types, clr-boot-manager could have an option to do the switch for you, give you an option to uninstall the other kernel type, and cleanup the anything that isn't needed anymore.

**Describe alternatives you've considered**
The alternative is to mount `/boot` and manually change the kernel type. If you want to remove the other kernel type, you need to use swupd to remove it and then search the system for remnants of the old kernel type.

**Additional context**
If you do not cleanup the kernel full after removing with swupd, Running `swupd verify --fix --picky` will at times complain about the old kernel not being available and the command isn't completed fully.

**Comment by puneetse** [comment]
It sounds like this may be  the same request here: https://github.com/clearlinux/clr-boot-manager/issues/109

**Comment by ahkok** [comment]
Closing in favor of tracking this at the linked enhancement request. CBM is the proper place to open a new issue regardless.
