### ISSUE TITLE
Package request for CoreFreq

### ISSUE THREAD

**Issue by cyring** [clearlinux/distribution#2594]
Official package name: **_CoreFreq_**

License (must be an OSI approved Open Source license): GPL2

Download URL of latest release: [`1.90.1`](https://github.com/cyring/CoreFreq/releases/tag/1.90.1)

Latest release date (must be recent): Mar 5, 2022

Description:

Hello,

May you please make [_CoreFreq_](https://github.com/cyring/CoreFreq) available through the `swupd` command ?

CoreFreq is a CPU monitoring software with BIOS like functionalities.
Intel Processors from Core2 up to the latest Alder Lake architecture are supported.

For your information I'm providing a [wiki](https://github.com/cyring/CoreFreq/wiki/CoreFreq-for-Clear-Linux) to build it from source in Clear Linux

**Thank you**

CyrIng

**Comment by cyring** [comment]
* Screenshot for your information

![2022-03-19-154002_1024x768_scrot](https://user-images.githubusercontent.com/11563789/159126142-81af1a92-99ff-46b0-8d99-a28b9b3a15e3.png)

**Comment by fenrus75** [comment]
Hmm this seems to include a kernel module that's not upstream... we really really don't like doing those

(and it's surprising, since all this information is also just available from userspace .. for example the turbostat and powertop tools manage pretty much the same information without kernel module)

**Comment by fenrus75** [comment]
(I understand that likely the kernel module lets you have somewhat higher accuracy.. but from a distro integration perspective... if it can run without the module using the normal userspace MSR read stuff, and has the kernel module as an option to get improved accuracy... then we could ship the userspace agent in the distro.. and if the user really wants the improved accuracy, he/she can add the kernel module themselves)

**Comment by cyring** [comment]
> (I understand that likely the kernel module lets you have somewhat higher accuracy.. but from a distro integration perspective... if it can run without the module using the normal userspace MSR read stuff, and has the kernel module as an option to get improved accuracy... then we could ship the userspace agent in the distro.. and if the user really wants the improved accuracy, he/she can add the kernel module themselves)

Thank you for your answer.

As you have notice, MSR are no more writable from userspace within latest kernel: one now need a boot kernel parameter.

PCI CSR, SMU & Chipset, Memory Controller & Timings and various other registers are not available from userspace.

Think about major manufacturers releasing closed source kernel module shipped with their GPU board: their blobs are blindly released in most repos.
In the contrary, CoreFreq is offering an unique opportunity to the Users to investigate (and maybe contribute) to a low level software; before giving a shot.

I respect your point of view

Best regards,

Cyril

**Comment by fenrus75** [comment]
I think your tool for sure looks cool...  to the point that I'm pondering
helping out with it somewhat upstream ;)
(long long time ago I worked on something called powertweak that did also
chipset writing/etc)

because if most of what it does can be done (even less accurate) without
the kernel module, it's still a very cool tool
to report where things are at at least... and for that I suspect reading
will get you at least part of the way there.

**Comment by cyring** [comment]
> I think your tool for sure looks cool... to the point that I'm pondering helping out with it somewhat upstream ;) (long long time ago I worked on something called powertweak that did also chipset writing/etc) because if most of what it does can be done (even less accurate) without the kernel module, it's still a very cool tool to report where things are at at least... and for that I suspect reading will get you at least part of the way there.

Thank you very much for any future help.

I chose Clear Linux because as far as I know it was provided by Intel and I am still hoping for any contribution, advice, help from their experts.

Linux users being the winners of all this: _surprisingly_, their feature requests push _CoreFreq_ even further every day.
