### ISSUE TITLE
systemd-resolve (version 249) related crashes

### ISSUE THREAD

**Issue by mmorini** [clearlinux/distribution#2595]
Hard locks observed sporadically since a few releases; can't pinpoint exactly, and got apparently worse since 36030, systemd-resolve keeps dumping core untill a hard freeze happens.

coredumpctl :
Mon 2022-03-21 15:52:29 CET    832  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               773.1K
Mon 2022-03-21 15:52:33 CET    581  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               772.1K
Mon 2022-03-21 15:52:35 CET    884  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               774.2K
Mon 2022-03-21 15:52:42 CET   1155  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               774.6K
Mon 2022-03-21 15:52:54 CET   1230  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               773.7K
Mon 2022-03-21 16:52:42 CET   1319  98  98 SIGABRT present  /usr/lib/systemd/systemd-resolved                               776.7K
[...]

excerpt from journalctl:
Mar 22 10:57:35 robin2 systemd-resolved[27636]: Assertion '(_error) != 0' failed at src/resolve/resolved-etc-hosts.c:112, function parse_line(). Aborting.
Mar 22 10:57:35 robin2 systemd[1]: Started Process Core Dump (PID 27775/UID 0).
Mar 22 10:57:35 robin2 systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Mar 22 10:57:35 robin2 systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
Mar 22 10:57:36 robin2 systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 27.
Mar 22 10:57:36 robin2 systemd[1]: Stopping Proxy AutoConfig discovery service...
Mar 22 10:57:36 robin2 systemd[1]: pacdiscovery.service: Deactivated successfully.
Mar 22 10:57:36 robin2 systemd[1]: Stopped Proxy AutoConfig discovery service.
Mar 22 10:57:36 robin2 systemd[1]: Stopped Network Name Resolution.
Mar 22 10:57:36 robin2 systemd[1]: Starting Network Name Resolution...
Mar 22 10:57:36 robin2 systemd-coredump[27778]: [🡕] Process 27636 (systemd-resolve) of user 98 dumped core.
                                                
                                                Found module linux-vdso.so.1 with build-id: 59c0fb6eafbe38e80ca66b5adda8844cc878a66b
                                                Found module libdl.so.2 with build-id: 04a5640b927e9a1401a652d03e89290a3d9a61b6
                                                Found module libffi.so.7 with build-id: 64165ef4135c63c0756f19382fb2d390fbffab24
                                                Found module libpthread.so.0 with build-id: 24f47139d58e72434fe8fc93bb40cd761ad3ee11
                                                Found module libgmp.so.10.4.1 with build-id: 5b698b32f9d3301eb42c08bffd55d175dd9ffb6c
                                                Found module libhogweed.so.6.4 with build-id: fadb230d46b6b39d0255590974e4bdac7f050dbd
                                                Found module libnettle.so.8.4 with build-id: d1499e4bb969bc05941672d78c637562e8485f4f
                                                Found module libtasn1.so.6 with build-id: 056d36ce48f5cd9df054a194ba3f382c86a22ca6
                                                Found module libunistring.so.2 with build-id: 888747ba00d8dbc20eea6606efb3311b45727aa2
                                                Found module libidn2.so.0 with build-id: 84e1577a1adba3dfaed4a1ac909f8c6cd9007dda
                                                Found module ld-linux-x86-64.so.2 with build-id: 4f44d81ad295a7b1324d72356b3faf436ad6280f
                                                Found module libzstd.so.1.5.2 with build-id: 668906c10849f231064064cedee8a1ddefb035d1
                                                Found module libseccomp.so.2 with build-id: 75e4d93f6da43553cd05fdad3be150a713f90967
                                                Found module libpam.so.0 with build-id: fa1c7eba3c657667151393085ce39092df29541b
                                                Found module libp11-kit.so.0 with build-id: 1c35246adbe8cc8cd222399619ce1d0ad519f16a
                                                Found module libcrypto.so.1.1 with build-id: 6d8ea9f6017a1ee385bfba0922ac3cd033ace6f5
                                                Found module libmount.so.1 with build-id: 7b5373099fd73e2729d982a327bbedc2284d81b2
                                                Found module liblz4.so.1.9.3 with build-id: ffd54d982279c1ee854e5add736fbac6c9829dc7
                                                Found module libkmod.so.2 with build-id: a7c42f7a4a100cfa0d26e23bbab486a122ab25b4
                                                Found module libip4tc.so.2 with build-id: b406d34b9e8baaf1baac6c14bca8a15acf5b5038
                                                Found module libcrypt.so.1 with build-id: 90bda8e7d8cef10d1708877948608097ac6271ed
                                                Found module libcap.so.2 with build-id: b53f75beb43a2d6d9afe27dcaf4d61f1a18d7444
                                                Found module libblkid.so.1 with build-id: 2041824f480ec89178523cb4ab5dde7203a22c3f
                                                Found module libacl.so.1 with build-id: 016e060f9c549bf101f1f18ae90897a346a5f2ec
                                                Found module libc.so.6 with build-id: dc707e6d7d9f9c59defa70e0ed119c2cee1ec5d4
                                                Found module libgcc_s.so.1 with build-id: 5fe857134b775d9e9f238c67e4c8aa2beac3bf54
                                                Found module libgcrypt.so.20 with build-id: eeb943861c7e488efe3622f30ee2ab52ad0e7dad
                                                Found module libgnutls.so.30 with build-id: d1f77caf93a5593cb279ae6fb1a16c38bec6e576
                                                Found module libgpg-error.so.0.32.2 with build-id: e8d3a9def4046e6ac3c7d5d581fb265ebb582b21
                                                Found module libsystemd-shared-249.so with build-id: 80858414f36e9193d324643b8d00885a97ec65cb
                                                Found module systemd-resolved with build-id: 67c0db314139f34f78ef75b6bbb02e537c676f7d
                                                Stack trace of thread 27636:
                                                #0  0x00007f85636a838c __pthread_kill_implementation (libc.so.6 + 0x9b38c)
                                                #1  0x00007f8563653276 __GI_raise (libc.so.6 + 0x46276)
                                                #2  0x00007f85636397f1 __GI_abort (libc.so.6 + 0x2c7f1)
                                                #3  0x00007f8563c63813 log_assert_failed (libsystemd-shared-249.so + 0x75813)
                                                #4  0x000055ff67fb89b0 parse_line (systemd-resolved + 0x389b0)
                                                #5  0x000055ff67fb94ff manager_etc_hosts_read (systemd-resolved + 0x394ff)
                                                #6  0x000055ff67f9c0c9 dns_query_try_etc_hosts (systemd-resolved + 0x1c0c9)
                                                #7  0x000055ff67fca4ce vl_method_resolve_hostname (systemd-resolved + 0x4a4ce)
                                                #8  0x00007f8563d1eca4 varlink_dispatch_method (libsystemd-shared-249.so + 0x130ca4)
                                                #9  0x00007f8563d1f626 defer_callback (libsystemd-shared-249.so + 0x131626)
                                                #10 0x00007f8563e10c71 source_dispatch (libsystemd-shared-249.so + 0x222c71)
                                                #11 0x00007f8563e111ed sd_event_dispatch (libsystemd-shared-249.so + 0x2231ed)
                                                #12 0x00007f8563e119e8 sd_event_run (libsystemd-shared-249.so + 0x2239e8)
                                                #13 0x00007f8563e11bc7 sd_event_loop (libsystemd-shared-249.so + 0x223bc7)
                                                #14 0x000055ff67f8fa77 run (systemd-resolved + 0xfa77)
                                                #15 0x00007f856363ad5e __libc_start_call_main (libc.so.6 + 0x2dd5e)
                                                #16 0x00007f856363ae20 __libc_start_main_impl (libc.so.6 + 0x2de20)
                                                #17 0x000055ff67f8fb75 _start (systemd-resolved + 0xfb75)
Mar 22 10:57:36 robin2 systemd[1]: systemd-coredump@26-27775-0.service: Deactivated successfully.
Mar 22 10:57:36 robin2 systemd[1]: Started Network Name Resolution.
Mar 22 10:57:36 robin2 systemd-resolved[27785]: Positive Trust Anchors:
Mar 22 10:57:36 robin2 systemd-resolved[27785]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Mar 22 10:57:36 robin2 systemd-resolved[27785]: Negative trust anchors: home.arpa 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa >
Mar 22 10:57:36 robin2 systemd[1]: Started Proxy AutoConfig discovery service.
Mar 22 10:57:36 robin2 pacdiscovery[27856]: PAC url: http://localhost/wpad.dat
Mar 22 10:57:36 robin2 pacdiscovery[27856]: Registered config: /org/pacrunner/configuration28
Mar 22 10:57:36 robin2 pacrunner[780]: pacrunner[780]: Failed to retrieve PAC script
Mar 22 10:57:36 robin2 pacrunner[780]: Failed to retrieve PAC script
Mar 22 10:57:36 robin2 systemd-resolved[27785]: Using system hostname 'robin2'.
[...]

**Comment by mmorini** [comment]
Possibly related to https://github.com/systemd/systemd/issues/22178

**Comment by bryteise** [comment]
Ah looks quite like it, thanks for the sleuthing! I've backported the patch while we await the systemd upgrade. Won't quite be the next release but should be the one after.

**Comment by bryteise** [comment]
Ah this was already added to 249.11 so should be fixed in the next release after all.

**Comment by mmorini** [comment]
Awesome, much appreciated! In the meanwhile, in case someone happened to stumble here, removing ipv6 addresses from /etc/hosts seems to fix things for the time being.
