### ISSUE TITLE
Add i40evf driver to KVM image

### ISSUE THREAD

**Issue by imswynne** [clearlinux/distribution#260]
Need SR-IOV VF support on Intel 10Gbps interfaces (x722 in my case). There does not appear to be any support for the Intel VF interfaces in the KVM image, though they have been successfully passed through to my Clear KVM instance.

Please add the i40evf driver to KVM image.

**Comment by imswynne** [comment]
It's there and works with the x722. Thanks!

**Comment by miguelinux** [comment]
Added at https://github.com/clearlinux-pkgs/linux-kvm/commit/570c4eed7e7d36a46c37e95a7217e31bc194e219
