### ISSUE TITLE
fzf

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2611]
https://github.com/junegunn/fzf

**Comment by nobodyatandnothing** [comment]
Official package name: fzf

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/junegunn/fzf/releases/download/0.30.0/fzf-0.30.0-linux_amd64.tar.gz

Latest release date (must be recent): Apr 04, 2022

Description: fzf is a general-purpose command-line fuzzy finder.

**Comment by bryteise** [comment]
fzf is probably not going to be picked up right away as it doesn't provide a source archive with dependencies that we can build without doing the vendor work ourselves.

**Comment by nobodyatandnothing** [comment]
i dont understand. 
the releases provided are binaries, such as the download link above.
fzf README says that there is no dependencies, (the only dep. is go)
and the source code is also available for download: https://github.com/junegunn/fzf/archive/refs/tags/0.30.0.tar.gz
