### ISSUE TITLE
Support 32bit UEFI

### ISSUE THREAD

**Issue by 1nikolas** [clearlinux/distribution#262]
**Is your feature request related to a problem? Please describe.**
Can't boot (the USB with the install image is not being recognized by the bios)

**Describe the solution you'd like**
Add a bootia32.efi file to the EFI partition

**Additional context**
I have a BayTrail Laptop (Lenovo 100S-11IBY) with a 64bit Intel Atom CPU but it only supports booting from 32bit UEFI. I've tried using a [generic bootia32.efi file](https://github.com/hirotakaster/baytail-bootia32.efi/blob/master/bootia32.efi) which works with Ubuntu arm64 (64bit) on this Laptop but it didn't work on Clear Linux.  Thanks in advance!

**Comment by ahkok** [comment]
I'm unsure we want to support this. This would have to be supported by CBM first, and given the rarity this may be something we decide not to spend time on (you can get a 32bit build from various sources already, and it doesn't preclude clearlinux from running at all).

**Comment by phuclv90** [comment]
To run 64-bit Linux on a 32-bit UEFI a [thunking layer](https://kernelnewbies.org/Linux_3.15#EFI_64-bit_kernels_can_be_booted_from_32-bit_firmware) is needed to convert things between the 32 and 64-bit ABIs. However the kernel [needs to be built with `CONFIG_EFI_MIXED=y`](https://unix.stackexchange.com/a/180966/44425)

Unfortunately as mentioned in #39

> Old cruft has been fixed and underped (unused parameters, etc) and **support for `CONFIG_EFI_MIXED` removed** as systemd doesn't actually support it still.

**Comment by 1nikolas** [comment]
@phuclv90 so is there any chance bringing that back in the future?

**Comment by phuclv90** [comment]
I'm not sure. You need to wait for the answer from Intel

**Comment by ahkok** [comment]
It depends, but, given that systemd-boot doesn't support it, there is no reason to bring it back until it does.

**Comment by 1nikolas** [comment]
@ahkok Thanks. I tested Clear Linux on my main PC (i3) and it was very snappy compared to other distros. I thought it would be nice to install this on my low spec laptop. Anyway I might just get a new one...

**Comment by klHaribo** [comment]
I hoped that I would find a stable linux distro for baytrail-Processors.
linuxium-ubuntu works after configuring sound etc
So Intel leaves linux users alone with baytrail-processors :(
I think supporting the first intel atom Processors for linux would be great.
Aber my experience with linux and baytrail I am very careful in selecting my hardware...

**Comment by ahkok** [comment]
FTR almost all the baytrail processors are supported, with the exception of a few that:

- don't support the AES instruction
- use 32bit UEFI

This should really be a very small amount of systems that are 5 or more years old at this time.

**Comment by Afsalmc** [comment]
> baytrail processors

The widely used Baytrail processor Z3735f across low spec netbooks and tablets has a 32bit UEFI . By unsupporting 32bit UEFI in clear linux intel prevents and missing a large number of Baytrail users  in clear linux .

**Comment by ahkok** [comment]
You can do this manually, we're not preventing any user from doing this themselves.

**Comment by Afsalmc** [comment]
> You can do this manually, we're not preventing any user from doing this themselves.

from my experience with a 5 month old clear Linux iso , adding bootia32.efi file didnt work while Ubuntu and all debian based distros works .
is this issue fixed in a later uso file ?

**Comment by ahkok** [comment]
This is the "extra" work that we're declining to do - make it "work". Yes, it starts with adding `bootia32.efi` as well as likely compiling a 32bit grub, and manually installing all that.

You're on your own, sorry, this is not a feature we will implement.
