### ISSUE TITLE
docker-compose is gone - bundle docs don't reflect this

### ISSUE THREAD

**Issue by kmpeterson** [clearlinux/distribution#2621]
A routine upgrade of Clear Linux caused issues with the  sudden disappearance of `docker-compose`.   

Commit [d9e03b5](https://github.com/clearlinux/clr-bundles/commit/d9e03b588ca2d9473264538aaf945a0303319813) (github: /clr-bundles/bundles/docker-compose) indicates that prebuilt binaries are available and should be used instead.  

I'd submit that breaking something like this and making it difficult to understand what happened and why isn't optimal, thus two possible steps could be taken to mitigate the impact of this change:

1. The documentation on [Bundles page](https://clearlinux.org/software/bundle/docker-compose) could be corrected to indicate the current state of support for this application.
2. A pointer could be provide (such as to the [upstream](https://docs.docker.com/compose/install/)) to make access to the prebuilt binary a bit easier.  If not via the Bundles page, then the contents of the "installed" bundle (solely: /usr/share/clear/bundles/docker-compose) could contain explanatory text rather than the string "filesystem".  

(I'm partly also filing this to record this issue explicitly and possibly save someone else some some laps around the Internet.)

**Comment by foureight84** [comment]
I was wondering what was going on with my clean server install. Bundle-add docker-compose installs the package but no binary no execute. 

`which: no docker-compose in (/usr/local/bin:/usr/bin/haswell:/usr/bin:/opt/3rd-party/bin)`

**Comment by nobbysheep** [comment]
Thanks for raising this - thought I was going mad(er). Breaking bug needs fixing

**Comment by fenrus75** [comment]
should be fixed now in the live update

**Comment by phmccarty** [comment]
Fixed in release [36200](https://cdn.download.clearlinux.org/releases/36200/clear/RELEASENOTES).
