### ISSUE TITLE
flatpak breaks all third-party app launchers

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2624]
By shipping `/usr/share/gdm/env.d/flatpak.env`, which completely rewrites the `XDG_DATA_DIRS` environment variable:

```
XDG_DATA_DIRS=$HOME/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/var/cache/:/usr/share/
```

**Comment by thiagomacieira** [comment]
What's wrong with this environment variable?

**Comment by paulcarroty** [comment]
All desktop entries from `/opt/3rd-party/*` are ignored.

**Comment by thiagomacieira** [comment]
Ah, right. It should use the existing variable if it is set.

**Comment by paulcarroty** [comment]
Related:

- https://github.com/flatpak/flatpak/issues/4692
- https://github.com/flatpak/flatpak/pull/3679
- https://github.com/flatpak/flatpak/pull/3693
