### ISSUE TITLE
Set default branch to 'main' when browsing https://github.com/clearlinux-pkgs/

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2625]
Now that 'main' is the default branch, browsing the packages at https://github.com/clearlinux-pkgs/ shouldn't open the outdated 'master' branch as default.

**Comment by bryteise** [comment]
I was just waiting to confirm out package sync went well yesterday, the switch is now complete for all current repositories (some package repos aren't active and so do not have a main branch internally and we aren't touching those at this time).
