### ISSUE TITLE
mtpfs

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2627]
Official package name: mtpfs

License (must be an OSI approved Open Source license): GPL-3.0-only

Download URL of latest release: https://github.com/cjd/mtpfs.git

Latest release date (must be recent): no releases

Description: 
MTPFS is a FUSE filesystem based on libmtp that allows a mtp device
to be browsed as if it were a normal external harddisk

**Comment by nobodyatandnothing** [comment]
updated

**Comment by bryteise** [comment]
Both projects look a little dead to me. Is gvfs not acceptable?

**Comment by nobodyatandnothing** [comment]
does gvfs have a cli?

**Comment by bryteise** [comment]
I haven't used it but in theory yes the `gio` command should allow you operate on the device.

**Comment by nobodyatandnothing** [comment]
thanks
