### ISSUE TITLE
Kernel enable loading compressed fw (CONFIG_FW_LOADER_COMPRESS)

### ISSUE THREAD

**Issue by mmetak** [clearlinux/distribution#2633]
https://github.com/clearlinux-pkgs/linux/pull/19

@miguelinux  @fenrus75

**Comment by fenrus75** [comment]
thanks for linking it here; we don't generally get email notifications from
PRs on individual packages due to some github funk

I'll take a look to enable this today

**Comment by mmetak** [comment]
https://github.com/clearlinux-pkgs/linux/commit/e49914e2217b483ee155b78c18fdca7147a85592
