### ISSUE TITLE
Please Package Waydroid for Clear Linux

### ISSUE THREAD

**Issue by MrJinx123** [clearlinux/distribution#2637]
Official package name: Waydroid

License (must be an OSI approved Open Source license):GPL

Download URL of latest release:https://docs.waydro.id/usage/install-on-desktops

Latest release date (must be recent):03.15.2022

Description: Installs and runs Android applications as native linux applications (containerized) Requires Wayland and desktop gui supporting wayland.

**Comment by bwarden** [comment]
Done:
https://github.com/clearlinux-pkgs/waydroid/commit/b7e069416893fad4854b06696a1a1cf66f2d4d90
https://github.com/clearlinux/clr-bundles/commit/8f5a9c6c772392947735180504cd80c74e3683e5
