### ISSUE TITLE
Failed to install in Parallels VM

### ISSUE THREAD

**Issue by dvska** [clearlinux/distribution#264]
**Describe the bug**
Cannot install CL into the Parallels VM.

**To Reproduce**

1. MacOS 10.14.1, Parallels Desktop Version 14.0.1 (45154)
2. Trying to install from mounted ISO clear-26030-installer.iso.xz
3. 
![screen shot 2018-11-05 at 18 04 40](https://user-images.githubusercontent.com/1125170/48006456-88819280-e126-11e8-9749-3ec26f34e110.png)

**Expected behavior**
Successful install 

**Environment (please complete the following information):**
 - Clear Linux OS version: 26030
 - Bundles: none

**Comment by phuclv90** [comment]
I've tried both the vmdk image and installation image in both VMware Player and Virtualbox. None of them are working

[Clear Linux desktop doesn't start in a virtual machine](https://unix.stackexchange.com/q/450302/44425)

**Comment by alexjch** [comment]
ISO for version 26030 is defective. I believe this image was not officially released, to download the latest validated images you should download them from https://download.clearlinux.org/image/
I know there is a source of confusion because the images are available under https://download.clearlinux.org/current/ as well, but those images are not guaranteed to work.

**Comment by alexjch** [comment]
The ISO is meant to be used for VMs and we strongly recommend the use of the installer image for bare metal installation.

**Comment by alexjch** [comment]
@phuclv90: please provide version for vmdk and live images. 
I just booted 26050 live using VirtualBox in OSX following [this](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox) documentation. Make sure you have enabled EFI in settings.

**Comment by phuclv90** [comment]
Of course I know that Clear Linux requires UEFI. I've even read each line in the documentation many times. I tried with various version up to 23040 and didn't try it again after too much frustration. In Virtualbox console apps can run normally but the GUI failed to start. In VMware the OS couldn't even start

But it looks like the documentation has been updated. I've just tried v26050 and run `startx` successfully

**Comment by dvska** [comment]
@alexjch No .ISO currently listed at  https://download.clearlinux.org/image/

(Mac Parallels VM) clear-26090-installer.iso - started installation - downloaded all bundles needed, but didn't start after reboot.
<img width="679" alt="screen shot 2018-11-06 at 15 05 26" src="https://user-images.githubusercontent.com/1125170/48063238-77dc2580-e1d5-11e8-8299-dcbbe5dc6322.png">

![screen shot 2018-11-06 at 15 00 41](https://user-images.githubusercontent.com/1125170/48063130-216ee700-e1d5-11e8-8d7c-a68c5e77d258.png)

![screen shot 2018-11-06 at 15 01 12](https://user-images.githubusercontent.com/1125170/48063129-216ee700-e1d5-11e8-90ac-aba5f73d52d1.png)

![screen shot 2018-11-06 at 15 01 44](https://user-images.githubusercontent.com/1125170/48063127-216ee700-e1d5-11e8-8cd8-7f8e84eb53c5.png)

**Comment by ahkok** [comment]
@bktan8 

We're going to try and see if we can improve the documentation at least to make using parallels and clearlinux better, and explore alternatives or better solutions that may come up.

**Comment by alexjch** [comment]
@dvska : I followed your steps and additionally I enabled EFI 64 (after 2nd screen capture)

![efi-boot](https://user-images.githubusercontent.com/1099605/48085559-77309880-e1af-11e8-9b98-d9c06f0a52f8.png)

**Comment by dvska** [comment]
@alexjch  Thanks, it helped!

For the parallels versions 13+

![screen-shot-2018-11-08-at-14 56 48](https://user-images.githubusercontent.com/1125170/48197552-1f3c9200-e367-11e8-9454-a119e5adcd31.png)

**Comment by dvska** [comment]
Updated, Next reboot after weekend and...
<img width="1077" alt="screen shot 2018-11-12 at 17 04 56" src="https://user-images.githubusercontent.com/1125170/48352189-2f24e080-e69d-11e8-9ad1-060db8a6fff1.png">

**Comment by dvska** [comment]
also, please include in the Docs -- how to install Parallels Tools, as CL didn't allow me to mount an .iso.

**Comment by puneetse** [comment]
I'm closing this since it has since been documented here https://docs.01.org/clearlinux/latest/get-started/virtual-machine-install/parallels.html
