### ISSUE TITLE
libdeflate

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2646]
Official package name: libdeflate

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.12.tar.gz

Latest release date (must be recent): yesterday

Description: libdeflate is a library for fast, whole-buffer DEFLATE-based compression and decompression.

**Comment by thiagomacieira** [comment]
zlib implements DEFLATE. Can you add a few words on why this other implementation is interesting?
