### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#265]
**Is your feature request related to a problem? Please describe.**
The lack of popular applications such as Chromium, Opera, ffmpeg (being worked on I think, but still easier as a snap), and Brave limit the use of Clear Linux as a desktop/workstation. Supporting snaps and the snapcraft store would bring Clear Linux in line with Debian, Arch, Fedora, etc.

**Describe the solution you'd like**
Like flatpak support in Clear Linux, I'd like to see snaps be supported for applications that are not available as flatpaks or in Clear Linux. Solution would be to package snapd and set it up for use.

**Describe alternatives you've considered**
Flatpak is nice, but does not have every popular application. Many libraries and applications are available only as snaps and Clear Linux may not be able to package all of them easily (license issues, not enough interest in the package, etc.)

**Additional context**
If this is out of the scope of Clear Linux's goals, then feel free to let me know and close the issue.

**Comment by ahkok** [comment]
Unlikely that we'll ever do this. Our goal isn't to make desktop applications less optimized and include these in clearlinux natively (as much as possible).

If software is only available as snap and not as source code, than that is a problem on the upstream side of things.

**Comment by OpenSourceAnarchist** [comment]
@ahkok That makes sense. Might want to close clearlinux/clr-bundles#60 then too. I guess this really only affects those that try to use Chromium instead of Firefox. I'll switch to Clear Linux again as soon as ffmpeg support is achieved (with playing back non-free codecs online and in video players). And I think libffmpeg-stub (new pundle?) is supposed to help with this. Currently on Solus.

**Comment by probonopd** [comment]
@OpenSourceAnarchist also check out [AppImage](https://appimage.org/). Clear Linux OS does not need to change much (besides enabling FUSE by default, which is a good idea anyway) to make AppImages a flawless experience, complementing what is already in place, and giving the user additional options to get application software. There are AppImages for Chromium and [many other applications](https://appimage.github.io/apps/) available.

**Comment by lf-araujo** [comment]
@ahkok please reconsider the use of snaps in the system, how are snaps all that different from flatpaks anyways? Snaps were designed to facilitate distribution of software, just like flatpaks.

Thanks for clearlinux, it is such an interesting OS.

**Comment by KathrynMorgan** [comment]
Sorry to bump a closed FRE
PSA: Admittedly I'm biased as a part of Canonical.

Snapd & snappy packages differ greatly from flatpak's paradigm in that it is very useful for non-GUI server type software distribution. 

I would very much like to switch my bare metal over to clear linux but absolutely require snap packages for things like microk8s / LXD / juju / kubectl / helm and other such snap packages.

**Comment by miguelinux** [comment]
> I would very much like to switch my bare metal over to clear linux but absolutely require snap packages for things like microk8s / LXD / juju / kubectl / helm and other such snap packages. 
> 

If you need that packages just open a new issue for a package request

https://github.com/clearlinux/distribution/issues/new/choose

some of them are already on CL.

**Comment by vargose** [comment]
Closed source projects are common on snaps and there is one in particular that is a show stopper for me without. They distribute on snap only, for convenience I am sure. This will only become more prevalent as snaps adoption becomes wider spread.

**Comment by WSLUser** [comment]
I think snap support should be added as well. VS Code for example is available as a snap but it's not in Clear Linux though Atom is. Instead of waiting for someone to contribute to making a bundle, we should be able to install snaps just like we can do flatpaks. Please don't do the flatpak vs snap like Red Hat does with the rpm distros. Provide user choice and flexibility. That would make this the go-to distro as it's already pretty great due to performance of it.

**Comment by thiagomacieira** [comment]
Sorry, but we don't have the resources to maintain Snap and AppImage and Flatpak. We chose one, the one that seemed to have most traction and biggest software availability.

Please ask VS Code community to package as a Flatpak instead.

**Comment by vargose** [comment]
> Sorry, but we don't have the resources to maintain Snap and AppImage and Flatpak. 

Seems like a distribution backed by a corporation (Intel) could add additional resources to add a feature that potential customers would want and are asking for

**Comment by vargose** [comment]
> Sorry, but we don't have the resources to maintain Snap and AppImage and Flatpak. 

I understand the difficulty of limited resources, thanks. Would Intel be willing to add resources to add a feature that potential users might want and are asking for? In the meantime I will ask the maintainer of my show stopper to add Flatpak support.

**Comment by vargose** [comment]
The more attractive features you have, the more users you will have, the more users you have the more potential testers, and possible contributors you will have. Overall more users will increase the visibility of Clear Linux increasing its potential to compete.

**Comment by thiagomacieira** [comment]
I don't know how much experience you have with big companies, but adding resources is never easy.

Remember our first focus right now is to make the best for server environments. Snap is a desktop component, which means it's already secondary.

**Comment by fabiohl** [comment]
It all is a matter of objectives of the project, based on opinions from its crew.
thiagomacieira said above that [flatpak] "seemed to have most traction and biggest software availability", which obviously is a mistake. By "most traction", one should read "red hat and gnome foundation funds it".
Red Hat and Gnome are obviously important, but they are not THE whole community itself. Ubuntu and cannoical represent most part of the userbase (desktop and server, mostly clould ones).
"Software availability" I don't have numbers here (as flatpaks are uncentrealized repos, flathub is just the most popular). But anyone can easily see that snaps managed to bring the most important software - many of them cited by folks above.
And I point it out that's not true that "snap is a desktop component" - today I consider snap by far the best way to easily install mantain thing like lxd, kubernetes, web, dns, nextcloud, iot and other. When you install ubuntu server, the installer offers you many of them.
And one could also argue that It's flatpak who is better suited for desktop once It's maintaned as a freedesktop.org project.
Finnaly I suppose it would not be a lot difficult to integrate snaps once it uses components usuals to containers, vm and flatpaks as such. And the source code is available - cannonical even bakes the integration to other distros.

**Comment by fabiohl** [comment]
But at the end of the day, that's all a matter of objectivers. Clear Linux is not intended to be a mainstream distro, but just a lab for Intel.
And don't get me wrong. There's just no problem on that at all. It's something very important and useful for the whole ecosystem. This lab is spreading advances that are benefiting everyone.
Last year we've heard words of clear bringing desktop/dev/powerusers components and we've warmed expectations - not confirmed ahead by stepbacks of the project by focusing back on servers/cloud.
This once again remind us of the limited resources (thiagomacieira noted that above on "adding resources is never easy" - which I totally agree as someone who also work for a corporation).
And that resources are managed by inner strategic objectives and opinions by its crew.
But again, the clearlinux inner value is its innovations spreading community-wide. So this is not the end of the world.
