### ISSUE TITLE
KDE plasma crash

### ISSUE THREAD

**Issue by zpataki** [clearlinux/distribution#2650]
Hello all,

First of all, I apologize for the incomplete English and any weak error report.

I have been using Clearlinux for a long time. my configuration according to neofetch:

OS: Clear Linux OS x86_64
Kernel: 5.18.2-1157.native
Uptime: 59 mins
Packages: 149 (rpm)
Shell: zsh 5.9
Resolution: 3840x2160
Terminal: / dev / tty3
CPU: AMD Ryzen 7 2700 (16) @ 3.200GHz
GPU: NVIDIA GeForce GTX 1080
Memory: 6114MiB / 64231MiB

Clear Release 36500.
Nvidia Driver Version: 515.48.07 

I have been using KDE for a long time under Xorg and the nvidia driver as described in clearlinux (/ opt install).
Everything in the clearlinux version 35330 worked smoothly with KDE.
With the 33340 version a partial KDE update came, it started to crash the plasma.

The bar appears about twice, it seems that the icons of the pinned applications are stacked on top of each other.
The wallpaper appears for a while, then after the plasma bar it also disappears, only a black screen with the mouse cursor appears.
But you can exit with Alt-Ctl-Del using the KDE menu.

Since there have been KDE issues in the past, I have been patiently waiting for any KDE updates that will resolve this issue as well.
Now with the 36500 version comes another KDE upgrade, I installed it, but the plasma crash still persists.

Before I submitted this report, I even ran a repair:
"swupd repair -m 36500 --force"

I can't decide if this is a Clearlinux or KDE bug.

I have attached the KDE bug report.
If you need any more info, if they describe how to extract it, I would also be happy to send it to help solve the problem.

Thanks
Zoltán Pataki

[plasmashell-20220616-193343.kcrash.txt](https://github.com/clearlinux/distribution/files/8921947/plasmashell-20220616-193343.kcrash.txt)

**Comment by zpataki** [comment]
I also tried it on my laptop, neofetch info:

OS: Clear Linux OS x86_64
Host: GL752VW 1.0
Kernel: 5.18.2-1157.native
Uptime: 14 mins
Packages: 8 (rpm)
Shell: bash 5.1.16
Resolution: 1920x1080
Terminal: mc
CPU: Intel i7-6700HQ (8) @ 3.500GHz
GPU: NVIDIA GeForce GTX 960M
GPU: Intel HD Graphics 530
Memory: 3006MiB / 31528MiB


Although the laptop has an nvidia card, it only uses the intel video card for Xorg config resource utilization, so no nvidia driver is installed.
I also tried to add a new user on both machines so that existing user configurations would not interfere.

The error phenomenon is the same as above.

[plasmashell-20220616-234020.kcrash.laptop.txt](https://github.com/clearlinux/distribution/files/8922694/plasmashell-20220616-234020.kcrash.laptop.txt)

**Comment by zpataki** [comment]
I also tried the default 36500 clearlinux kvm image after installing the desktop-kde bundle.
The error message is similar, attached to the plasma crash file.

[plasmashell-20220617-205914.kvm.kcrash.txt](https://github.com/clearlinux/distribution/files/8931343/plasmashell-20220617-205914.kvm.kcrash.txt)

**Comment by zpataki** [comment]
I put in an official kvm screenshot of the version I experienced 36330.

I just tested the 36570 version, the bug is the same as before, flickering screen in two states, blank and KDE official wallpaper backend.
To this I attach a journactl --user backup, the KDE crash report does not give up the error, but htop says the use of the plasmashell CPU is increasing.
I still choose X11 on the SDDM screen instead of Wayland because of its immaturity.
![Screenshot from 2022-06-28 19-05-31](https://user-images.githubusercontent.com/11769927/176256785-a2499be7-977e-4f51-8a5f-dfa0fc49122f.png)
![Screenshot from 2022-06-28 19-12-26](https://user-images.githubusercontent.com/11769927/176256839-e3432d64-11aa-4d86-8969-d6e5e759845f.png)
![Screenshot from 2022-06-28 19-12-26](https://user-images.githubusercontent.com/11769927/176256860-9272cd97-0064-4435-bb33-43750b7b3e4c.png)
[kvmjournal.txt](https://github.com/clearlinux/distribution/files/9004858/kvmjournal.txt)

**Comment by djbokka** [comment]
I have experienced the same issues with three different machines (all non-nvidia). All are fresh installs. 

As I've done many times before, I boot into gnome, run `swupd update`, then `swupd bundle-add desktop-kde desktop-kde-apps`. Once I reboot into plasma, it crashes immediately.

I've submitted the bug reports to KDE as well and they've marked them as duplicates of your bug @zpataki

**Comment by bryteise** [comment]
I'm poking a few packages that might be related to the issue (we did have some issues with shipping optimized plugins). We'll see if I get anywhere.

**Comment by zpataki** [comment]
djbokka , bryteise 
Thanks!

I tested the kvm image version 36580, same error.

**Comment by zpataki** [comment]
Looks like we've fixed the error. Thank you very much for the work of those involved.

**Comment by zpataki** [comment]
Thanks.
