### ISSUE TITLE
Kernal too old error

### ISSUE THREAD

**Issue by kausrga** [clearlinux/distribution#2657]
Hello,

I have been using clearlinux/golang image for a while now. Suddenly any new image that we are building is throwing this error:

    Step 7/40 : RUN swupd bundle-add --no-progress htop wget unzip cryptography
    ---> Running in bad4ec19dfb2
    FATAL: kernel too old

Our linux docker hosts are on kernel Linux 3.10

**Comment by fenrus75** [comment]
with 3.10 being EOL for a while now, we bumped the minimum kernel in glibc
up...
... but that broke people so we reverted that and it'll be reverted in the
next release

**Comment by kausrga** [comment]
great, do you have an ETA on the new release?

**Comment by kausrga** [comment]
I can confirm that its working now.
Thank you for the quick turnaround.

**Comment by paulcarroty** [comment]
Still doesn't work on Heroku and Linux 4.4.
