### ISSUE TITLE
Desktop applications unable to connect to the network

### ISSUE THREAD

**Issue by joshuagl** [clearlinux/distribution#266]
**Describe the bug**
Gnome desktop applications can't connect to the network, i.e. Gnome Software is unable to fetch software repository data.

**To Reproduce**
1. On a Clear Linux system connected via wifi to a network without a proxy connection
2. Attempt to connect to the network from a program which uses _glib-networking_ such as _gnome-software_, i.e. `flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
3. Observe glib-networking error:
```
joshuagl@clrmnd ~ $ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

(flatpak remote-add:17553): GLib-Net-WARNING **: 17:33:18.964: Could not start proxy autoconfiguration helper:
    Error calling StartServiceByName for org.gtk.GLib.PACRunner: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit glib-pacrunner.service not found.
Proxy autoconfiguration will not work

(flatpak remote-add:17553): GLib-GIO-WARNING **: 17:33:18.964: Invalid proxy URI 'use-proxy:': Invalid URI ‘use-proxy:’
Can't load uri https://dl.flathub.org/repo/flathub.flatpakrepo: Unknown error on connect
``` 
4. Switching network proxy from Automatic to Disabled in System Settings -> Network -> Network Proxy was a sufficient workaround.

**Expected behavior**
Programs are able to successfully perform network operations. Gnome Software should be able to refresh software repository information without error.

**Environment (please complete the following information):**
 - Clear Linux OS version: 26090
 - Bundles: 

> bootloader
> c-basic
> desktop
> desktop-apps
> desktop-assets
> desktop-autostart
> desktop-gnomelibs
> desktop-kde
> desktop-kde-apps
> desktop-kde-libs
> desktop-locales
> dev-utils
> emacs
> ethtool
> git
> iproute2
> kernel-native
> libX11client
> network-basic
> openssh-server
> openssl
> os-core
> os-core-dev
> os-core-update
> p11-kit
> perl-basic
> python-basic
> python2-basic
> python3-basic
> qt-basic
> software-testing
> sudo
> sysadmin-basic
> telemetrics
> vim
> which
> wpa_supplicant
> x11-server
> x11-tools
> xemacs

**Additional context**
glib-pacrunner.service isn't shipped in desktop bundles, it's required by applications using glib-networking but appears to be mostly shipped in _\-dev_ bundles.

```
joshuagl@clrmnd ~ $ sudo swupd search glib-pacrunner.service
Searching for 'glib-pacrunner.service'

Bundle cockpit	(131 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle firmware-update	(272 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle qt-basic-dev	(1999 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle games-dev	(2506 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle kvm-host-dev	(2913 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle software-defined-cockpit-dev	(3175 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle desktop-dev	(3681 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service

Bundle os-utils-gui-dev	(3903 MB to install)
	/usr/lib/systemd/user/glib-pacrunner.service
```

**Comment by joshuagl** [comment]
I think we probably want to make _glib-networking-lib_ `Requires: glib-networking-config`, which is where the service file lives.

Trying to figure out how to reverse engineer a packages repo now.

**Comment by mrkz** [comment]
Already fixed by @fenrus75, fix should be available soon-ish.

will close once I confirm this is fixed.

**Comment by ahkok** [comment]
I traced back to `glib-networking` and our bundles and dependencies are properly set to `glib-networking` and not `glib-networking-lib`, and so, the `-config` subrpm was already in the dependency chain as far as I can see.

@mrkz what is the fix?

**Comment by mrkz** [comment]
@ahkok @fenrus75 included the whole glib-networking package (which pulls in `*-config`) into the desktop bundle. the `*-config` is not included on the manifests as the swupd search in the report reveals.

perhaps dnf going funky with dependencies?

**Comment by ahkok** [comment]
hmmm, I tracked the `flatpak` bundle. Perhaps he got the `desktop` bundle without the `flatpak` bundle then

**Comment by joshuagl** [comment]
@ahkok that's right, I didn't explicitly install a flatpak bundle but I did have flatpak available with the bundle list I included in my original report. I don't know if this is considered to be buggy behaviour? Should all bundles including flatpak instead be including the flatpak bundle, to provide the full set of contents required to run flatpak?

I've updated from 26090->26130 and can confirm that _flatpak_ and _gnome\-software_ are both working. Furthermore a swupd search shows me that `/usr/lib/systemd/user/glib-pacrunner.service` is now part of the desktop bundle.

**Comment by ahkok** [comment]
FWIW I didn't intend the `flatpak` bundle to be the bundle that provides flatpak support, because as far as I was concerned it just needed flatpak (the package). The reason I added the flatpak bundle was to (1) be able to add flatpak-builder somewhere, and (2) to provide it to non-gnome desktops. The fact that there are issues with gnome as a desktop without this bundle was... strange :)

**Comment by bryteise** [comment]
I'd generally say that flatpak isn't a feature of the gnome desktop we were really testing stand alone. @ahkok probably we should include the flatpak bundle into desktop.
