### ISSUE TITLE
`/usr/bin/gcc-ar` vs `/usr/bin/ar`

### ISSUE THREAD

**Issue by yesudeep** [clearlinux/distribution#2675]
Hello,

I’m wondering about the difference between `/usr/bin/gcc-ar` and `/usr/bin/ar`.
When using them with [bazel](https://bazel.build/), they exhibit different behavior. 
One supports reading parameters from ‘@file’ and another doesn’t appear to: 
bazel complains about this because when it uses the binary at `/usr/bin/gcc-ar`. 
As soon as I sym-link `/usr/bin/gcc-ar` -> `/usr/bin/ar`, bazel works as expected).

Why are there 2 ‘ar’ binaries and can `/usr/bin/gcc-ar` be a symlink to 
whatever we're using at `/usr/bin/ar`? I'm asking because as soon as there is 
a system update the symlink is replaced automatically and I have to redo the 
sym-linking.

Cheers,
Y.

**Comment by fenrus75** [comment]
gcc-ar is a wrapper around ar that adds support for LTO....

odd that there's any other difference at all beyond LTO support
