### ISSUE TITLE
Please add support for |( CONFIG_MEMTEST )| memtest it is really very useful!

### ISSUE THREAD

**Issue by sparkillay** [clearlinux/distribution#2678]
Hello, can you please add CONFIG_MEMTEST=y to config for kernels?
It does not change default behaviour, but enables user to add memtest=4 option to kernel command line in order to do brief RAM test during boot. It is done directly by kernel without need for external tool like memtest86+, results can then be found in dmesg.

memtest=        [KNL,X86,ARM] Enable memtest
                        Format: <integer>
                        default : 0 <disable>
                        Specifies the number of memtest passes to be
                        performed. Each pass selects another test
                        pattern from a given set of patterns. Memtest
                        fills the memory with this pattern, validates
                        memory contents and reserves bad memory
                        regions that are detected.

**Comment by WSLUser** [comment]
This was added. See https://github.com/clearlinux-pkgs/linux/commit/38bff9168e645683aa68cb04e00a87f60875c581

**Comment by fenrus75** [comment]
done; will be in the next release
