### ISSUE TITLE
Pair of swupd diagnose / swupd repair ...repairs nothing

### ISSUE THREAD

**Issue by serveriukai** [clearlinux/distribution#2689]
Using Clear Linux as native operating system on three computers. On every of them
swupd diagnose
finds some "problems" - missing files, o some files with mismatching signatures and proposes to use "swupd repair".
swupd repair
reports problems fixed. Diagnose again founds the same problems, repair'ing reports fixing.

The same on native and stable kernel branches
$ swupd info
Distribution:      Clear Linux OS
Installed version: 36700l

**Comment by Senary6** [comment]
That sounds like issue [https://github.com/clearlinux/distribution/issues/2454](https://github.com/clearlinux/distribution/issues/2454)

**Comment by bryteise** [comment]
It does, I'm going to use #2825 as the tracking for this particular issue though as the other was closed.
