### ISSUE TITLE
Automounting of removable media is enabled in gnome

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#269]
**Describe the bug**
Gnome-shell enables removable media automounting.

**To Reproduce**
1. Insert USB stick with partition table and filesystems

**Expected behavior**
Explicit user interaction should be required to mount any removable filesystem

**Comment by danboid** [comment]
I regard that as a useful feature personally and I'm sure others do too so I should hope this remains as an option if not enabled by default.

Windows, macOS and most desktop Linux distros automount (at least) FAT drives by default so its the behaviour most users expect.

**Comment by tpleavitt** [comment]
Use the gnome-tweaks utility 
@phmccarty , please take a look and advise how best to attack this problem

**Comment by ahkok** [comment]
example:

Having gnome automount an ESP (`UEFI System Partition`) on a bootable USB stick is a sure way to create problems for users and should never be a default mounted partition. That's FAT.

**Comment by rossburton** [comment]
Wouldn't it be relatively easy to not automount the ESP by looking at the partition table?

**Comment by phmccarty** [comment]
Sounds like a reasonable approach to look at. I am not actively working on this issue, so I will unassign myself.

**Comment by rossburton** [comment]
I just plugged in a Clear live USB stick: it automounted the root filesystem on `/run/media/ross/CLR_ISO` but didn't mount the ESP too.

I'm firmly in the camp that automounting is useful and should be enabled out of the box, and it looks like the automounter isn't doing plainly stupid things.

I propose we close this. Auke, as the reporter, do you disagree?
