### ISSUE TITLE
Issue with swupd breaking the NVIDIA proprietary installation

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2690]
This is an edge case seeing `swupd update` re-installing or updating same kernel version `5.18.14-1162.native` from 36680 to 36700.

1. Install Clear Linux 36680
2. Install NVIDIA proprietary driver (builds/installs modules plus updates kernel modules.dep and map files)
3. Run `swupd update --version=36700`. The update includes kernel-native, kernel-native-dkms, linux-dev even though the same kernel version `5.18.14-1162.native`.

What happens is that DKMS `/usr/bin/dkms-new-kernel.sh` exits early due to the same kernel version. Unfortunately, the kernel modules.dep and map files were restored. Thus removing NVIDIA symbols in modules.dep and map files from step 2. Running `depmod` resolved the issue and was able to run the graphical target without having to rebuild the NVIDIA kernel drivers.

Proposal: Add `depmod -A $(uname -r)` to `/usr/bin/dkms-new-kernel.sh`. The `-A` or `--quick` option to `depmod` scans to see if any modules are newer than the `modules.dep` file before any work is done: if not, it silently exits rather than regenerating the files.

```bash
#!/bin/sh

CUR="`uname -r`"
SUF="`uname -r| sed 's/.*[.]//'`"
DEF="/usr/lib/kernel/default-$SUF"

if [ ! -e $DEF ]; then
        exit 0
fi

NEW="`readlink $DEF | sed 's/org.clearlinux.\([a-z][a-z0-9_-]*\).\(.*\)/\2.\1/'`"

if [ "$CUR" != "$NEW" ]; then
        echo "Running DKMS for new kernel $NEW"
        dkms autoinstall -k "${NEW}"
else
        echo "Refreshing modules.dep and map files for kernel $CUR"
        depmod -A "$CUR"
fi
```

**Comment by marioroy** [comment]
I created an automation how-to for installing the NVIDIA driver on Clear Linux. There I added `depmod -A` to the `fix-nvidia-libGL-trigger.service` file.

**Comment by bwarden** [comment]
Applied; this should show up in an upcoming release. I'm pondering whether we should do it when $CUR != $NEW as well, in case dkms didn't need to rebuild, but swupd still overwrote the depfiles.

**Comment by marioroy** [comment]
> I'm pondering whether we should do it when $CUR != $NEW as well, in case dkms didn't need to rebuild, but swupd still overwrote the depfiles.

I vote yes... especially if another edge case exists where swupd overwrote the depfiles outside of dkms.

**Comment by marioroy** [comment]
@bwarden , are you suggesting doing this? ++ and think that this will address remaining edge cases.
```bash
if [ "$CUR" != "$NEW" ]; then
        echo "Running DKMS for new kernel $NEW"
        dkms autoinstall -k "${NEW}"
        depmod -A "${NEW}"
else
        echo "Refreshing modules.dep and map files for kernel $CUR"
        depmod -A "${CUR}"
fi
```

**Comment by bwarden** [comment]
Or move depmod completely out of the if/fi:

```
if [ "$CUR" != "$NEW" ]; then
        echo "Running DKMS for new kernel $NEW"
        dkms autoinstall -k "${NEW}"
fi

echo "Refreshing modules.dep and map files for kernel $NEW if needed"
depmod -A "${NEW}"
```

**Comment by marioroy** [comment]
That is elegant and beautiful. That will ensure the state of DKMS modules are intact no matter the edge case. Thank you very much.

**Comment by bwarden** [comment]
Implemented in https://github.com/clearlinux-pkgs/dkms/commit/708e3bdea3eafe8e0aad3cb45decff990677c0b1 (will be published once it's in a release)

**Comment by marioroy** [comment]
Fixed in Clear Linux 36740. Thanks again.
