### ISSUE TITLE
btop: Resource monitor that shows usage and stats for processor, memory, disks, network and processes.

### ISSUE THREAD

**Issue by audiomuze** [clearlinux/distribution#2692]
Official package name: btop

License (must be an OSI approved Open Source license): Apache License 2.0

Download URL of latest release: https://github.com/aristocratos/btop

Latest release date (must be recent): Jun 29, 2022

Description: Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
Provides much more useful information than the likes of htop etc.

**Comment by FrozzDay** [comment]
Maybe you can try this https://github.com/clearfraction/distribution

**Comment by bryteise** [comment]
Fairly straightforward to package, should be available in the next release or so.
