### ISSUE TITLE
Ensure -O3 is default option for all archs in 5.19 kernel

### ISSUE THREAD

**Issue by WSLUser** [clearlinux/distribution#2693]
See https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.19-O3-March-Native and this patch series: https://lore.kernel.org/lkml/20220621133526.29662-1-mikoxyzzz@gmail.com/ . Found in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/init/Kconfig?h=v5.19

Noticed https://github.com/clearlinux-pkgs/linux/blob/main/0133-novector.patch has -O2 listed, not sure if related or not but would guess -O3 would need to be added there and/or replace the -O2.

**Comment by fenrus75** [comment]
I'll take a look ;)

**Comment by insilications** [comment]
> Noticed https://github.com/clearlinux-pkgs/linux/blob/main/0133-novector.patch has -O2 listed, not sure if related or not but would guess -O3 would need to be added there and/or replace the -O2.

This is exactly what I do when building my own CL mix after reading the recent Phoronix benchmark. No problems so far.

**Comment by WSLUser** [comment]
> No problems so far.

Did you update the kernel too? The repo currently shows on 5.18 still. While it appears most patches haven't needed updating, I wouldn't be surprised if a patch or 2 needed some slight adjustments when upgrading to 5.19 outside of simply switching a compilation option.

**Comment by fenrus75** [comment]
we did the o3.
for new kernels we generally wait for the .1 release

**Comment by insilications** [comment]
> Did you update the kernel too? The repo currently shows on 5.18 still. While it appears most patches haven't needed updating, I wouldn't be surprised if a patch or 2 needed some slight adjustments when upgrading to 5.19 outside of simply switching a compilation option.

Yes, I'm running 5.19. All clr patches were easily rebased, except for https://github.com/clearlinux-pkgs/linux/blob/main/0132-prezero-20220308.patch, so I disabled it. I also needed to disable some support tweaks for it in clr-power-tweaks. It was too complicated to investigate it further, especially if it somehow interacts with the multi-gen LRU patches I'm using (https://codeberg.org/pf-kernel/linux/src/branch/mglru-5.19).

The only other thing I'm using is bbr2 (https://codeberg.org/pf-kernel/linux/src/branch/bbr2-5.19).

**Comment by insilications** [comment]
Also, 5.19 introduces CONFIG_RCU_EXP_CPU_STALL_TIMEOUT (default 20). For some reason the nvidia blobs are generating `timeout expedited RCU CPU stall warnings` if CONFIG_RCU_CPU_STALL_TIMEOUT and CONFIG_RCU_EXP_CPU_STALL_TIMEOUT are too low.  I needed to set rcupdate.rcu_cpu_stall_timeout and rcupdate.rcu_exp_cpu_stall_timeout both to 120 to stop it. I haven't investigated it further.

**Comment by fenrus75** [comment]
I'm less inclined to make life worse for everyone due to an nvidia
binary module bug.. they'll fix it I'm sure.

**Comment by insilications** [comment]
> I'm less inclined to make life worse for everyone due to an nvidia binary module bug.. they'll fix it I'm sure.

Definitely. Just reporting because I'm sure people will complain.

**Comment by WSLUser** [comment]
I see that 5.19.1 has been added now. Was the -O3 included with that?

**Comment by WSLUser** [comment]
Nvm found it: https://github.com/clearlinux-pkgs/linux/commit/71fbe0406686178c6a209a515c174df7ef77e4e4
