### ISSUE TITLE
kernel-lts-dkms not auto-updating to latest kernel-lts*-dkms similarly to kernel-lts

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2694]
Edge case: I'm running Clear Linux 36700 and have both `kernel-lts` and `kernel-lts-dkms` installed. Running `swupd update --version 36710` runs like one would expect, installing kernel-lts2021. But not installed is `kernel-lts2021-dkms` even though I have `kernel-lts-dkms` installed. Shouldn't that pick up `kernel-lts2021-dkms` automatically, similarly to `kernel-lts`?

The [36710 Release Notes](https://cdn.download.clearlinux.org/releases/36710/clear/RELEASENOTES) mentions `kernel-lts`.

```text
Updated bundles:
     kernel-lts: -linux-lts2020 +linux-lts2021
```

Not mentioned in the notes is the update for `kernel-lts-dkms`.

```text
Updated bundles:
     kernel-lts-dkms: -linux-lts2020-dkms +linux-lts2021-dkms
```

Wish list: ++ for safety check ensuring `kernel-lts` and `kernel-lts-dkms` remain synchronized or updated together.

**Comment by marioroy** [comment]
I noticed something amiss in the `swupd update` output. Can you see it?

```text
Downloading packs for:

 - kernel-lts2021
 - kernel-install
 - kernel-lts
 - kernel-lts-dkms
 - kernel-lts2020
 - kernel-lts2020-dkms
 - linux-lts2020-dev
```

I have `kernel-lts` installed and so understandably see `kernel-lts2021`. But I also have `kernel-lts-dkms` installed and asked, "Why are the associated bundles `kernel-lts2021-dkms` and `linux-lts2021-dev` not installing automatically"?

And so the reason for this issue request...

**Comment by phmccarty** [comment]
Thanks for the report. It will be fixed in the next release.

**Comment by marioroy** [comment]
Fixed in Clear Linux 36720. Thanks.
