### ISSUE TITLE
Add "ldconfig" to swupd post-update, is it needed?

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2696]
Hi, I'm creating this request in the event an edge case exists.

Scenario: Install Clear Linux OS including NVIDIA driver. I'm having to call  [ldconfig](https://github.com/marioroy/nvidia-driver-on-clear-linux/blob/main/pre-install-driver#L176) inside the trigger script. Else, an edge case (reproducible) breaks Firefox. The `/usr/lib/libGL.so.1` file is a symbolic link to `/opt/nvidia/lib64/libGL.so.1` and not affected before/after running `swupd`.

Firefox emits an error after installing `devpkg-mesa` without the `ldconfig` entry.

```text
$ firefox 
XPCOMGlueLoad error for file /home/mario/.firefox/libmozgtk.so:
libGL.so.1: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
```

To reproduce, simply remove the `devpkg-mesa` bundle and associated dependencies.

```bash
$ sudo swupd bundle-remove devpkg-mesa \
    devpkg-libdrm devpkg-valgrind devpkg-base devpkg-libpciaccess \
    devpkg-libX11 devpkg-xorgproto

$ sudo swupd bundle-add devpkg-mesa
$ firefox
```

Running `ldconfig` after `swupd` resolves the issue. Or in my case, I added [ldconfig](https://github.com/marioroy/nvidia-driver-on-clear-linux/blob/main/pre-install-driver#L176) to the trigger script.

Should swupd post-update call ldconfig instead?

**Comment by fenrus75** [comment]
we do run an (incremental) ldconfig near the end of each swupd.

but ldconfig does not clobber /usr in incremental mode since our /usr is
assumed immutable and owned by swupd; it does write the cache in /var

**Comment by marioroy** [comment]
I think now okay leaving `ldconfig` inside the `fix-nvidia-libGL-trigger` service as the NVIDIA libs are outside swupd control. Thank you for the clarification.
