### ISSUE TITLE
Bundle update: please add glslang and SPIRV-Cross to the hardware-gpu bundle

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2698]
Some time ago [issue 2557](https://github.com/clearlinux/distribution/issues/2557), `glslang-dev` and `SPIRV-Cross-dev` were added to the developer-gpu bundle. At the time, I missed mentioning the associated hardware-gpu bundle.

Scenario: After building FFmpeg, I tried removing developer-gpu and devpkg-* bundles. The reason is mainly to lessen the amount of time and network bandwidth for future OS updates via `swupd update`.

Unfortunately, the ffmpeg binary will fail due to missing libraries. Wish list: Please add `glslang-lib`, `glslang-license`, `SPIRV-Cross-lib-moltenvk`, and `SPIRV-Cross-license-moltenvk` to the hardware-gpu bundle.

```text
$ ldd libavfilter.so
	libglslang.so.11 => not found
	libSPIRV.so => not found
```

**Comment by marioroy** [comment]
I made a [kind request](https://community.clearlinux.org/t/clear-fraction-the-third-party-repository-for-clear-linux/7243/21?u=marioroy) to @paulcarroty. The `ffmpeg` binary in Clear Fraction is one step from `nvdec` support.

**Comment by bryteise** [comment]
Hrm I feel like this isn't that helpful as if you ever want to update ffmpeg you are now missing those libraries again. I'd expect 3rd party things can interact at the package level to provide the dependencies as needed.

**Comment by marioroy** [comment]
I'm thinking about archiving/deprecating the `ffmpeg-on-clear-linux project`. The 3rd-party path is nice as it doesn't require folks to build things. Unfortunately, `nvdec` support is missing in Clear Fraction (ffmpeg).

Regarding missing `{gslang, SPIRV-Cross}` libs in hardware-gpu (although dev libs exist in developer gpu), I'd not enable Vulcan support in the project for the time being. So that folks can have the option of removing developer-gpu, devpkg-* bundles.

**Comment by marioroy** [comment]
Thank you for reaching out. I [disabled Vulkan support](https://github.com/marioroy/ffmpeg-on-clear-linux/commit/1d176b) for the time being.
