### ISSUE TITLE
libsamplerate to 2.2

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2699]
https://github.com/libsndfile/libsamplerate/releases/tag/0.2.2
http://libsndfile.github.io/libsamplerate/download.html
http://libsndfile.github.io/libsamplerate/
http://libsndfile.github.io/libsamplerate/history.html
http://www.mega-nerd.com/SRC/history.html

**Comment by fenrus75** [comment]
done
