### ISSUE TITLE
Podman 4.0.3 -> 4.1.1

### ISSUE THREAD

**Issue by brasie** [clearlinux/distribution#2701]
A newer Podman is available:

https://github.com/containers/podman/releases/tag/v4.1.1

Can it be updated?

Thanks,

**Comment by aerphanas** [comment]
its on version 4.2.0, see on [here](https://github.com/clearlinux-pkgs/podman/blob/main/versions) you can close this issue

**Comment by brasie** [comment]
Cool.  Next up, I suppose: #2772
