### ISSUE TITLE
Add WSLU bundle

### ISSUE THREAD

**Issue by WSLUser** [clearlinux/distribution#2704]
Official package name: wslu

License (must be an OSI approved Open Source license): GPLv3

Download URL of latest release: https://github.com/wslutilities/wslu/releases/tag/v3.2.4

Latest release date (must be recent): Mar 19, 2022

Description: This is a collection of utilities for Windows 10 Linux Subsystem, such as retrieving Windows 10 environment variables or creating your favorite Linux GUI application shortcuts on Windows 10 Desktop.

A third party bundle now officially exists for wslu. See https://blog.wslutiliti.es/2022/08/08/wslu-now-available-on-clearlinux/

I'd like to see the wslu bundle made officially part of the repo now.

**Comment by bryteise** [comment]
Should be in a release later this week.

**Comment by WSLUser** [comment]
WSLu just released 4.0 so be sure that's the version provided as there were some breaking changes in order to provide better enhancements, bugs, and increase performance.
