### ISSUE TITLE
Duplicate entries in XDG_DATA_DIRS environment variable

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2709]
```text
$ echo $XDG_DATA_DIRS
/home/mario/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/cache/:/home/mario/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/cache/
```
```text
/home/mario/.local/share/flatpak/exports/share/
/var/lib/flatpak/exports/share/
/usr/local/share/
/usr/share/
/var/cache/
/home/mario/.local/share/flatpak/exports/share/
/var/lib/flatpak/exports/share/
/usr/local/share/
/usr/share/
/var/cache/
```

**Comment by marioroy** [comment]
The duplication persists on a clean 36890 desktop installation.

1. From testing, the duplication has nothing to do with /usr/share/defaults/etc/profile or profile.d/flatpak.sh as I temporarily moved flatpak.sh away.
2. I searched /usr/lib/systemd and not seeing anything odd in flatpak-system-helper.service.
3. Next, I searched /usr/share/gdm/env.d. The duplication occurs in flatpak.env. Perhaps, flatpak.env is read twice?

Further testing: One cannot remove `$XDG_DATA_DIRS:` as it will cause the initial desktop login to exit after each reboot, though subsequent logins work and no duplication.
```bash
XDG_DATA_DIRS=$XDG_DATA_DIRS:$HOME/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/cache/
```

Not to bother due to login abnormally.

**Comment by marioroy** [comment]
Here is a solution to rid of duplication in XDG_DATA_DIRS, without login abnormally.

1. Add the XDG_DATA_DIRS definition to /usr/share/defaults/etc/profile, next to XDG_CONFIG_DIRS.
```bash
XDG_DATA_DIRS=$HOME/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/cache/
```
2. Remove /usr/share/gdm/env.d/flatpak.env

```bash
$ echo $XDG_DATA_DIRS
/home/mario/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/cache/
```
```bash
/home/mario/.local/share/flatpak/exports/share/
/var/lib/flatpak/exports/share/
/usr/local/share/
/usr/share/
/var/cache/
```

**Comment by bryteise** [comment]
Should be in a release later this week.

**Comment by bryteise** [comment]
Ah yep, that's a good catch thanks. Adding.

**Comment by marioroy** [comment]
One more thing to reach 100%. Do you see a trailing slash? /usr/share/
```bash
XDG_DATA_DIRS="$HOME/.local/share/flatpak/exports/share":/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/cache
```

**Comment by marioroy** [comment]
Please disregard my prior comment. @paulcarroty alerted me to `man environment.d`. The example show XDG_DATA_DIRS with trailing slash.
