### ISSUE TITLE
Local path should come first in the swupd trigger that creates /opt/3rd-party/bin files

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2710]
PATH: Please have `/opt/3rd-party/bundles/clearfraction/usr/local/bin` come first.

LD_LIBRARY_PATH: Please have `/opt/3rd-party/bundles/clearfraction/usr/local/lib64` come first.

Or if you want to handle it this way, if launching the bin file from the local/bin path /opt/3rd-party/bundles/clearfraction/usr/local/bin, please ensure the local paths comes first.

```text
export PATH=/opt/3rd-party/bundles/clearfraction/usr/local/bin:/opt/3rd-party/bundles/clearfraction/bin:/opt/3rd-party/bundles/clearfraction/usr/bin:$PATH
export LD_LIBRARY_PATH=/opt/3rd-party/bundles/clearfraction/usr/local/lib64:/opt/3rd-party/bundles/clearfraction/usr/lib64:$LD_LIBRARY_PATH
```

**Comment by marioroy** [comment]
@paulcarroty has `.../clearfraction/usr/bin` before `.../clearfraction/usr/local/bin` in his [fix](https://github.com/clearfraction/distribution/commit/f0ebe27). Please disregard this issue request.

**Comment by fenrus75** [comment]
btw the reason system paths are before others is one of security policy....
not something we're eager to compromise on

**Comment by marioroy** [comment]
Thanks and certainly makes sense. I wrongly hoped for consistency between the OS and 3rd-party. Currently, /usr/local/bin comes before /usr/bin in /usr/share/defaults/etc/profile line 24.

PATH="/usr/local/bin:$PATH"

echo $PATH
/usr/bin/haswell:/usr/local/bin:/usr/bin:/opt/3rd-party/bin

**Comment by marioroy** [comment]
Thanks again. I enjoy CL a lot and have been experimenting with it. Regarding bin paths, the choice of which comes first at the OS level and then different at the 3rd-party level is what made me wonder.
