### ISSUE TITLE
The spice-vdagent package is quite useful, but missing in Clear Linux

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2714]
Official package name: spice-vdagent

License (must be an OSI approved Open Source license): GPLv3+

Download URL of latest release:
https://fedora.pkgs.org/rawhide/fedora-x86_64/spice-vdagent-0.22.1-2.fc37.x86_64.rpm.html

Latest release date (must be recent): Jul 23, 2022

Description:
Spice agent for Linux guests offering the following features:
* Support of copy and paste (text and images) between the active X-session
  and the client
* Enable/disable mouse messages. When enabled absolute mouse events can travel this way instead of using an USB or Virtio tablet device for that. Default is on.

Testing:
* Virt-Manager configures the channels automatically when making a VM. For QEMU, I added the following arguments (extracted from running Virt-Manager and checked ps -auxww output).
```text
-device virtio-serial-pci \
-chardev socket,id=charchannel0,server=on,wait=off \
-device virtserialport,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 \
-chardev spicevmc,id=charchannel1,name=vdagent \
-device virtserialport,chardev=charchannel1,id=channel1,name=com.redhat.spice.0 \
```

Clipboard copying+pasting works bi-directional :slightly_smiling_face:  I'm not the first making the request. Please refer to community forum.

https://community.clearlinux.org/t/share-clipboard-and-file-transfer-between-host-and-kvm-qemu-guest/4689

See also: https://www.kraxel.org/blog/2021/05/qemu-cut-paste/

**Comment by fenrus75** [comment]
actually i packaged it earlier today

**Comment by marioroy** [comment]
@fenrus75 Blessings and grace! Thank you!

**Comment by marioroy** [comment]
I tried the spice-vdagent bundle. It doesn't work, unfortunately. The rpm file mentioned above works fine. The following files are missing in the bundle.
* /usr/lib/systemd/system/spice-vdagentd.service
* /usr/lib/systemd/system/spice-vdagentd.socket
* /usr/lib/systemd/user/spice-vdagent.service
* /usr/lib/tmpfiles.d/spice-vdagentd.conf
* /usr/lib/udev/rules.d/70-spice-vdagentd.rules

Post steps from `rpm -qlp --scripts spice-vdagent-0.22.1-2.fc37.x86_64.rpm`.
```text
postinstall scriptlet (using /bin/sh):

if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then 
    # Initial installation 
    /usr/lib/systemd/systemd-update-helper install-system-units spice-vdagentd.service spice-vdagentd.socket || : 
fi

preuninstall scriptlet (using /bin/sh):

if [ $1 -eq 0 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then 
    # Package removal, not upgrade 
    /usr/lib/systemd/systemd-update-helper remove-system-units spice-vdagentd.service spice-vdagentd.socket || : 
fi

postuninstall scriptlet (using /bin/sh):

if [ $1 -ge 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then 
    # Package upgrade, not uninstall 
    /usr/lib/systemd/systemd-update-helper mark-restart-system-units spice-vdagentd.service spice-vdagentd.socket || : 
fi
```

**Comment by marioroy** [comment]
Ah, I see. The spice-vdagent bundle is missing a couple packages.
```text
spice-vdagent
spice-vdagent-config    # missing
spice-vdagent-services  # missing
```

**Comment by marioroy** [comment]
If helpful, the Fedora spice-vdagent-0.22.1-2.fc37.x86_64.rpm package works, no tweaking needed or extra steps.

**Comment by kemelzaidan** [comment]
Well, I'm looking for a way to install it today and `swupd search spice-vdagent` returns no bundle.

**Comment by fenrus75** [comment]
odd -- the bundle is called spice-vdagent
