### ISSUE TITLE
Wish list: Enable SDL for QEMU via --enable-sdl

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2718]
Not all graphics work with `qemu --display gtk,gl=on`, which is the case for NVIDIA. Fortunately, `--display sdl,gl=on` works. See [info](https://community.clearlinux.org/t/info-for-qemu-using-nvidia-graphics-coming-soon/7900) at the Clear Linux Forums.

Configure options:

```text
replace --disable-sdl with --enable-sdl in the SPEC file
--audio-drv-list='pa,alsa,oss,sdl'   # please, add sdl to the audio drv list
```

Build Dependencies: SDL2-dev and SDL2_image-dev.

Runtime Requires: SDL2-lib and SDL2_image-lib.

**Comment by marioroy** [comment]
One can use the following script to test QEMU+SDL.
```bash
#!/bin/bash

IMAGE="clear.img" FORMAT="raw"
UEFI_BIOS="-bios OVMF.fd"

if [ -f OVMF_VARS.fd -a -f OVMF_CODE.fd ]; then
    UEFI_BIOS=" -drive file=OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on "
    UEFI_BIOS+=" -drive file=OVMF_VARS.fd,if=pflash,format=raw,unit=1 "
fi

VMN=${VMN:=1}

export SDL_ALLOW_ALT_TAB_WHILE_GRABBED=0
export SDL_MOUSE_FOCUS_CLICKTHROUGH=1
export SDL_RENDER_DRIVER=opengl
export SDL_RENDER_VSYNC=0

qemu-system-x86_64 \
    -name 'clearlinux' \
    ${UEFI_BIOS} \
    -enable-kvm \
    -machine pc-q35-7.0,accel=kvm,usb=off,vmport=off,smm=on,dump-guest-core=off \
    -cpu host -smp 4,sockets=1,cores=4,threads=1 -m 8192 \
    -no-user-config -nodefaults -no-hpet \
    -rtc 'base=utc,driftfix=slew' \
    -global 'kvm-pit.lost_tick_policy=delay' \
    -global 'ICH9-LPC.disable_s3=1' \
    -global 'ICH9-LPC.disable_s4=1' \
    -boot strict=on \
    -parallel none -serial none -k en \
    -display sdl,gl=on,window-close=off \
    -device virtio-vga-gl,max_outputs=1 \
    -device usb-ehci -device usb-tablet \
    -netdev user,id=net0,hostfwd=tcp::${VMN}0022-:22 \
    -device virtio-net-pci,netdev=net0 \
    -object iothread,id=io0 \
    -drive if=none,id=disk0,cache=none,format="$FORMAT",aio=threads,file="$IMAGE" \
    -device virtio-blk-pci,drive=disk0,scsi=off,iothread=io0 \
    -object rng-random,id=rng0,filename=/dev/urandom \
    -device virtio-rng-pci,rng=rng0 \
    -audiodev sdl,id=snd0 \
    -device intel-hda -device hda-output,audiodev=snd0 \
    "$@"
```

**Comment by thiagomacieira** [comment]
Out of curiosity, what's wrong with the Gtk support on NVidia?

**Comment by marioroy** [comment]
Running with `-display gtk,gl=on -device virtio-vga-gl` exhibits a black screen.

Running with `-display gtk,gl=off -device virtio-vga` works fine, but no OpenGL.

**Comment by marioroy** [comment]
Compiling QEMU takes a long time. So, for quick testing, one can disable-docs and shorten target-list. Also installed to /usr/local.

```bash
#!/bin/bash

export CFLAGS="-O3 -m64 -march=x86-64-v3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="-O3 -m64 -march=x86-64-v3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="-O3 -m64 -march=x86-64-v3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="-O3 -m64 -march=x86-64-v3 -ffat-lto-objects -flto=auto -fstack-protector-strong -fzero-call-used-regs=used "

./configure \
  --prefix='/usr/local' \
  --disable-docs \
  --enable-sdl \
  --enable-opengl \
  --enable-virglrenderer \
  --enable-system \
  --enable-modules \
  --enable-gtk \
  --enable-kvm \
  --target-list='x86_64-softmmu x86_64-linux-user' \
  --enable-spice \
  --enable-vnc \
  --enable-rbd \
  --extra-cflags="-O3" \
  --enable-attr \
  --enable-cap-ng \
  --enable-virtfs \
  --enable-vhost-net \
  --enable-usb-redir \
  --python=/usr/bin/python \
  --enable-linux-aio \
  --audio-drv-list='pa,alsa,oss,sdl' \
  --disable-curses \
  --enable-lto \
  --enable-linux-io-uring
```

Then, add the following lines in the QEMU launch script.

```bash
export PATH=/usr/local/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib64:/opt/nvidia/lib64
```

**Comment by marioroy** [comment]
I built v7.1.0, released on August 30, and ran ldd on libs. The build dependency SDL2_mixer-dev and runtime SDL2_mixer-lib are not needed. 

```bash
$ ldd /usr/local/lib64/qemu/ui-sdl.so | grep SDL2
libSDL2-2.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libSDL2-2.0.so.0 (0x00007f6ef81d5000)
libSDL2_image-2.0.so.0 => /usr/local/lib64/libSDL2_image-2.0.so.0 (0x00007f6ef818b000)

$ ldd /usr/local/lib64/qemu/audio-sdl.so | grep SDL2
libSDL2-2.0.so.0 => /usr/lib64/glibc-hwcaps/x86-64-v3/libSDL2-2.0.so.0 (0x00007feb29270000)
```

```text
Build Dependencies: SDL2-dev and SDL2_image-dev.
Runtime Requires: SDL2-lib and SDL2_image-lib.
```

**Comment by marioroy** [comment]
There is a cool [Quickemu](https://github.com/quickemu-project/quickemu) project for QEMU, defaulting to SDL for the output and sound. Wish list: Yet another reason to enable SDL. Do not forget to append sdl to audio-drv-list.

```text
--enable-sdl
--audio-drv-list='pa,alsa,oss,sdl'
```
Below, extracts from the quickemu script. Note sdl audio_dev selection for sdl output.

```bash
# Map Quickemu OUTPUT to QEMU -display
case ${OUTPUT} in
  gtk)        DISPLAY_RENDER="${OUTPUT},grab-on-hover=on,zoom-to-fit=off,gl=${gl}";;
  none|spice) DISPLAY_RENDER="none";;
  sdl)        DISPLAY_RENDER="${OUTPUT},gl=${gl}";;
  spice-app)  DISPLAY_RENDER="${OUTPUT},gl=${gl}";;
  *)          DISPLAY_RENDER="${OUTPUT}";;
esac

# Setup the appropriate audio device based on the display output
case ${OUTPUT} in
  none|spice|spice-app) AUDIO_DEV="spice,id=audio0";;
  sdl) AUDIO_DEV="sdl,id=audio0";;
  *) AUDIO_DEV="pa,id=audio0";;
esac
```

Thank you.

Off-topic: I shared with the quickemu devs on how to automatically grab-on-hover for SDL, similarly to GTK, via an environment variable.

```bash
export SDL_MOUSE_FOCUS_CLICKTHROUGH=1
```

**Comment by marioroy** [comment]
Thus far, I have tried Virt-Manager, Gnome-boxes, and now Quickemu+Quickgui. The latter is amazing. I shared how I made a couple wrapper scripts, defaulting to SDL. The issue is that Quickgui hardcodes `--display spice`, but I prefer SDL output. It all works well. I will put in a package/bundle request for zsync.

See https://github.com/quickemu-project/quickemu/issues/541

**Comment by marioroy** [comment]
Reconsider this request, please. Only SDL2-dev and SDL2_image-dev are needed to enable SDL support. Dependency runtimes are SDL2-lib and SDL2_image-lib. Another option is making QEMU for the server image without SDL and QEMU for the desktop image with SDL support.

```bash
--enable-sdl \
--audio-drv-list='pa,alsa,oss,sdl' \
```

Anyway, the following is a Windows 11 KVM via QEMU running on top of Clear Linux 37000.

![image](https://user-images.githubusercontent.com/7031085/188602271-89a3e7ef-980e-471a-bb20-cccaee6425a4.png)

**Comment by marioroy** [comment]
Met to reopen on the prior comment.

**Comment by marioroy** [comment]
I received an email as to why: the issue with dependencies only; that is will pull in an enormous amount of extra deps for a server package.

**Comment by marioroy** [comment]
Thank you. SDL is enabled in QEMU since CL 37060. It also updates virglrenderer from 0.9.1 to 0.10.1, which breaks support for OpenGL 3.1 and GLES 3.0 using NVIDIA graphics.

https://gitlab.freedesktop.org/virgl/virglrenderer/-/issues/286

**Comment by marioroy** [comment]
The virglrenderer maintainer merged two fixes upstream, PRs 922 and 923, closing issue 286.

https://gitlab.freedesktop.org/virgl/virglrenderer/-/merge_requests?scope=all&state=merged
