### ISSUE TITLE
Long wait for login due to wait for entropy rng (AWS t2.micro on 26170)

### ISSUE THREAD

**Issue by thatsamguy** [clearlinux/distribution#272]
After upgrading to 26170 on an AWS t2.micro instance and rebooting, it takes 3-5 minutes before login succeeds.

Similar to #97 and #129 

1. Create an AWS EC2 t2.micro instance with AMI ami-0e586a40bef8775da (clear-24710-awsc8ea4ea3-4d505f99-1c49-45c1-b574-a59747ec19d6-ami-0ef4b66c38040aa88.4)
2. Login
3. sudo swupd update;
4. reboot
5. wait for reboot (about 15 seconds)
6. attempt ssh connection (with -vvv)
7. ssh connection succeeds, but waits for 3-5 minutes before completing the login

Workaround:
Install rng-tools and rng-autostart via the cryptography bundle
Login after restart has no delay

**Comment by fenrus75** [comment]
thanks for the report

historically the kernel apparently had just enough entropy, and now apparently it doesn't...
I've added the rng tools/autostart to the aws bundle definitions
