### ISSUE TITLE
Is "swupd bundle-info python-extras --files" accurate?

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2726]
CL 37000

The PyYAML package is included in the python-extras bundle. So, I wonder why `--files` does not produce any /usr/lib/python3.10/site-packages/yaml/* listing. It appears to be a bug.

```bash
sudo swupd bundle-info python-extras --files | grep -i yaml
```

The following is what I see.
```text
 - /usr/lib/python3.10/site-packages/dask/dask.yaml
 - /usr/lib/python3.10/site-packages/dask/dask-schema.yaml
 - /usr/share/package-licenses/PyYAML/3b8919c7f020e71fc3e97cfd724f9463bbac1177
 - /usr/share/package-licenses/PyYAML
 - /usr/lib/python3.10/site-packages/networkx/readwrite/tests/test_getattr_nxyaml_removal.py
 - /usr/lib/python3.10/site-packages/networkx/readwrite/tests/__pycache__/test_getattr_nxyaml_removal.cpython-310.pyc
 - /usr/lib/python3.10/site-packages/networkx/readwrite/nx_yaml.py
 - /usr/lib/python3.10/site-packages/networkx/readwrite/__pycache__/nx_yaml.cpython-310.pyc
```

Missing in the output are the site-packages PyYAML files, which exists on the system.
```text
/usr/lib/python3.10/site-packages/PyYAML-6.0-py3.10.egg-info
/usr/lib/python3.10/site-packages/PyYAML-6.0-py3.10.egg-info/PKG-INFO
/usr/lib/python3.10/site-packages/PyYAML-6.0-py3.10.egg-info/SOURCES.txt
/usr/lib/python3.10/site-packages/PyYAML-6.0-py3.10.egg-info/dependency_links.txt
/usr/lib/python3.10/site-packages/PyYAML-6.0-py3.10.egg-info/top_level.txt
/usr/lib/python3.10/site-packages/_yaml/__init__.py
/usr/lib/python3.10/site-packages/_yaml/__pycache__/__init__.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__init__.py
/usr/lib/python3.10/site-packages/yaml/__pycache__/__init__.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/composer.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/constructor.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/cyaml.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/dumper.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/emitter.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/error.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/events.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/loader.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/nodes.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/parser.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/reader.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/representer.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/resolver.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/scanner.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/serializer.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/__pycache__/tokens.cpython-310.pyc
/usr/lib/python3.10/site-packages/yaml/_yaml.cpython-310-x86_64-linux-gnu.so
/usr/lib/python3.10/site-packages/yaml/composer.py
/usr/lib/python3.10/site-packages/yaml/constructor.py
/usr/lib/python3.10/site-packages/yaml/cyaml.py
/usr/lib/python3.10/site-packages/yaml/dumper.py
/usr/lib/python3.10/site-packages/yaml/emitter.py
/usr/lib/python3.10/site-packages/yaml/error.py
/usr/lib/python3.10/site-packages/yaml/events.py
/usr/lib/python3.10/site-packages/yaml/loader.py
/usr/lib/python3.10/site-packages/yaml/nodes.py
/usr/lib/python3.10/site-packages/yaml/parser.py
/usr/lib/python3.10/site-packages/yaml/reader.py
/usr/lib/python3.10/site-packages/yaml/representer.py
/usr/lib/python3.10/site-packages/yaml/resolver.py
/usr/lib/python3.10/site-packages/yaml/scanner.py
/usr/lib/python3.10/site-packages/yaml/serializer.py
/usr/lib/python3.10/site-packages/yaml/tokens.py
```

**Comment by bryteise** [comment]
The content is also in the cloud-api bundle which python-extras includes in its bundle definition. This means the files in cloud-api are subtracted from the python-extras bundle which is why you don't see them listed.

**Comment by marioroy** [comment]
Thank you for the explanation. I'd missed seeing cloud-api.

**Comment by marioroy** [comment]
I wrongly assumed that `--files` would output all the files associated with the bundle. Thanks for the clue, the python-extras bundle includes the cloud-api bundle. Unfortunately, it doesn't output those files as well. Do we need a new argument `--files-all` to `swupd`?

Not being able to see the full list means that one has to clone clr-bundles and search through the bundles folder. That isn't obvious sometimes, because of dependencies configured in the package SPEC file. For example, it's not obvious looking at the cloud-api definition file.
```text
include(python3-basic)
include(libstdcpp)
awscli
amazon-efs-utils
pypi-boto
boto3
botocore
```

**Comment by bryteise** [comment]
Yea, that'd be an option. What are you looking to do with this information by the way? The find what files are recursively included isn't an operation most package managers support that I'm aware of so I'd like to get a motivation.

**Comment by marioroy** [comment]
> To find what files are recursively included isn't an operation most package managers support that I'm aware of so I'd like to get a motivation.

The motivation is that I like to know if the OS contains the requirements for a development project.

Bundles in Clear Linux are a collection of one or more packages. I wrongly assumed `swupd bundle-info --files` to provide a list including sub-bundles. Being able to ask `swupd` which bundle a given file belongs to is helpful, similarly to `rpm -qf /usr/bin/cat`. Is this feasible?

**Comment by bryteise** [comment]
> Being able to ask `swupd` which bundle a given file belongs to is helpful, similarly to `rpm -qf /usr/bin/cat`. Is this feasible?

`swupd search-file /usr/bin/cat` though I should tell you the operation isn't fast as it must download all the manifests but will tell you which bundles you have installed (all of them as there can be more than one) that the file is found in.
