### ISSUE TITLE
Official website, software section doesn't work

### ISSUE THREAD

**Issue by 0cool-f** [clearlinux/distribution#2733]
It says "`No results.`" no matter what category I select from sidebar menu

**Comment by 0cool-f** [comment]
I've closed issue because I thought it was solved, but then I found that when you search for something it gives this error (sometimes it appears even by clicking on page navigation numbers):
`The website encountered an unexpected error. Please try again later.`

You can see it by searching something, ex:
https://clearlinux.org/software?search_api_fulltext=test&field_bundle_category=All

**Comment by aerphanas** [comment]
it work but not showing bundle like podman
