### ISSUE TITLE
Clear Linux Samba And Kerberos

### ISSUE THREAD

**Issue by sbharvey** [clearlinux/distribution#2735]
swupd info
Distribution:      Clear Linux OS
Installed version: 37160
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

uname -a
Linux clr-linuxHost 5.19.8-1187.native #1 SMP Thu Sep 8 07:39:18 PDT 2022 x86_64 GNU/Linux

samba -V
Version 4.15.6

Both of my installs of Clear Linux were update yesterday and the samba-lib was was one of the many modules that were updated.
Today I could not start the samba service successful,   There is an issue with the kdc service see.   The Samba AD will not work.
Here is the log entry. 

Sep 14 12:26:05 clr-linuxHost krb5kdc[2443](Error): Database module does not match KDC version - while initializing database for realm SAMDOM.EXAMPLE.NET
-----------------------------------------
This is part of what the journal entry reports:
:
Sep 13 18:09:45 clr-linuxHost swupd[8135]:  - lib-samba
Sep 13 18:09:45 clr-linuxHost swupd[8135]:  - libX11client
Sep 13 18:09:45 clr-linuxHost swupd[8135]:  - libarchive
Sep 13 18:09:45 clr-linuxHost swupd[8135]:  - libglib
: 
I re-provisioned the the AD with samba-tool same issue Samba will not run.

**Comment by fenrus75** [comment]
I think I figured out what is going on;
we updated openssl to 3.0, which required us to upgrade krb5 to 1.20.
the openssl change required us to rebuild sssd, but sssd unfortunately has a hardcoded (at built time) list of krb5 versions it wants to know, and 1.20 wasn't on that list yet, and it silently disabled kerberos support as a result

this should be fixed now in the 37180 build
(it's either already released or you can go to it with "swupd update --format staging" )

**Comment by sbharvey** [comment]
Thank you fixing the issue.  It was a show stopper.   I notice that samba has been taking up to version 4.17
xxxx@clr-xxxx/home/xxxxx # samba -V
Version 4.17.0
I am having some issues with the dnsupdater in samba, that is beyond the scope of the issue.   I am going to try
some configuration changes in /etc/samba/smb.conf

**Comment by sbharvey** [comment]
Adding suupd info to this for information, again thanks for turning around the fix, looking for the thumbs up emoji can't find it.
Update version: 
root@clr-linuxHost/home/sbharvey # swupd info
Distribution:      Clear Linux OS
Installed version: 37180
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

**Comment by sbharvey** [comment]
This issue is closed later version of Sama and Clear Linux function as expected see version listed below:
# swupd  info ; echo ""; uname -a ; echo ""; samba -V ; echo "";  krb5-config --all
Distribution:      Clear Linux OS
Installed version: 40030
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

Linux netserver03 6.5.5-1366.native #1 SMP Sat Sep 23 02:49:28 PDT 2023 x86_64 GNU/Linux

Version 4.18.5

Version:     Kerberos 5 release 1.21.2
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
