### ISSUE TITLE
AWS AMI not available for newer Intel instances

### ISSUE THREAD

**Issue by kermado** [clearlinux/distribution#2737]
Would it be possible to make the AMI available for the newer [M5zn](https://aws.amazon.com/about-aws/whats-new/2020/12/introducing-amazon-ec2-m5zn-instances/) and [I4i](https://aws.amazon.com/ec2/instance-types/i4i/) instance types? These are currently not listed as being supported by the AMI.

**Comment by bryteise** [comment]
@djklimes would you be able to check those boxes?

**Comment by mdpitterle** [comment]
Finally got AWS to approve the additions of the m5zn and i4i types, I added a few others that were eligible as well.
