### ISSUE TITLE
Samba Internal DNS does not appear to Operate Correctly

### ISSUE THREAD

**Issue by sbharvey** [clearlinux/distribution#2738]
At this version the DNS lookup function for Samba appears broken.

root@clr-linuxHost/home/xxxxxx # swupd info
Distribution:      Clear Linux OS
Installed version: 37190
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

The systemctl status samba reports the following it has started but there is a crash when dns update starts see below:

             ├─3077 /usr/bin/samba --foreground --no-process-group
             ├─3078 /usr/bin/samba --foreground --no-process-group
             ├─3079 /usr/bin/samba --foreground --no-process-group
             ├─3080 /usr/bin/samba --foreground --no-process-group
             ├─3081 /usr/bin/samba --foreground --no-process-group
             ├─3082 /usr/bin/samba --foreground --no-process-group
             └─3083 /usr/bin/samba --foreground --no-process-group

             ├─3079 /usr/bin/samba --foreground --no-process-group
             ├─3080 /usr/bin/samba --foreground --no-process-group
             ├─3081 /usr/bin/samba --foreground --no-process-group
             ├─3082 /usr/bin/samba --foreground --no-process-group
             └─3083 /usr/bin/samba --foreground --no-process-group

Sep 16 18:02:51 clr-linuxHost samba[3056]: [2022/09/16 18:02:51.508718,  0] ../../lib/util/util_runcmd.c:355(samba_runcmd_io_handler)
Sep 16 18:02:51 clr-linuxHost samba[3056]:   /usr/bin/samba_dnsupdate:     elif not check_dns_name(d):
Sep 16 18:02:51 clr-linuxHost samba[3056]: [2022/09/16 18:02:51.509042,  0] ../../lib/util/util_runcmd.c:355(samba_runcmd_io_handler)
Sep 16 18:02:51 clr-linuxHost samba[3056]:   /usr/bin/samba_dnsupdate:   File "/usr/bin/samba_dnsupdate", line 299, in check_dns_name
Sep 16 18:02:51 clr-linuxHost samba[3056]: [2022/09/16 18:02:51.509388,  0] ../../lib/util/util_runcmd.c:355(samba_runcmd_io_handler)
Sep 16 18:02:51 clr-linuxHost samba[3056]:   /usr/bin/samba_dnsupdate:     raise Exception("Timeout while waiting to contact a working DNS server while loo>
Sep 16 18:02:51 clr-linuxHost samba[3056]: [2022/09/16 18:02:51.509816,  0] ../../lib/util/util_runcmd.c:355(samba_runcmd_io_handler)
Sep 16 18:02:51 clr-linuxHost samba[3056]:   /usr/bin/samba_dnsupdate: Exception: Timeout while waiting to contact a working DNS server while looking for A>
Sep 16 18:02:51 clr-linuxHost samba[3056]: [2022/09/16 18:02:51.554217,  0] ../../source4/dsdb/dns/dns_update.c:85(dnsupdate_nameupdate_done)
Sep 16 18:02:51 clr-linuxHost samba[3056]:   dnsupdate_nameupdate_done: Failed DNS update with exit code 1

Samba version:
root@clr-linuxHost/home/xxxxx # samba -V
Version 4.17.0

Kerbose version for  reference

root@clr-linuxHost/home/xxxxx # swupd info
Distribution:      Clear Linux OS
Installed version: 37190
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

As a result of this behavior no Windows clients can join the domain.  This is catastrophic.

**Comment by marioroy** [comment]
1. Disable updates for the time being until Samba-Kerberos issues become resolved.
```bash
sudo swupd autoupdate --disable
```

2. Roll back to a prior Clear Linux release. Mesa is broken in 37120, 37130, and 37140. So, do not roll back to these versions. Rollback to 37150 or further back 37110.
```bash
sudo swupd repair -m 37150 --force   (or)
sudo swupd repair -m 37110 --force
```

**Comment by sbharvey** [comment]
The revert was a bust for both version. Please let me know when the issue is solved with the latest build.
I have Clear Linux running on a desktop AMD system different errors with revert but it did not work with either revert 
version.
From Vmware install:

swupd info
Distribution:      Clear Linux OS
Installed version: 37150
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

krb5-config --all
Version:     Kerberos 5 release 1.20
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr

samba -V
Version 4.15.6

Samba starting up in interactive mode just dies as shown:
samba -i
samba version 4.15.6 started.
Copyright Andrew Tridgell and the Samba Team 1992-2021
GENSEC backend 'gssapi_spnego' registered
GENSEC backend 'gssapi_krb5' registered
GENSEC backend 'gssapi_krb5_sasl' registered
GENSEC backend 'spnego' registered
GENSEC backend 'schannel' registered
GENSEC backend 'naclrpc_as_system' registered
GENSEC backend 'sasl-EXTERNAL' registered
GENSEC backend 'ntlmssp' registered
GENSEC backend 'ntlmssp_resume_ccache' registered
GENSEC backend 'http_basic' registered
GENSEC backend 'http_ntlm' registered
GENSEC backend 'http_negotiate' registered
GENSEC backend 'krb5' registered
GENSEC backend 'fake_gssapi_krb5' registered
register_process_model: PROCESS_MODEL 'single' registered
register_process_model: PROCESS_MODEL 'standard' registered
register_process_model: PROCESS_MODEL 'prefork' registered
AUTH backend 'sam' registered
AUTH backend 'sam_ignoredomain' registered
AUTH backend 'anonymous' registered
AUTH backend 'winbind' registered
AUTH backend 'name_to_ntstatus' registered
ldb: module version mismatch in ../../modules/asq.c : ldb_version=2.6.1 module_version=2.4.2
ldb: failed to initialise module /usr/lib64/ldb/modules/ldb/asq.so : Unavailable
exit_daemon: daemon failed to start: Samba failed to prime database, error code 22

**Comment by marioroy** [comment]
Hi. I had met to say that I am not affiliated with Intel. I read your message and the reason offered to help. Before replying, I tested rolling back from 37190 to 37150 and from 37190 to 37110 but was not aware of ldb. In your case, you cannot rollback beyond 37180 as the db data was updated to newer version. The ldb libraries were updated in 37180 from 2.4.2 to 2.6.1. :(

You will need to update the OS to 37180 minimally and export the data.

https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-admin/Dumping-a-Kerberos-Database-to-a-File.html

https://web.mit.edu/kerberos/krb5-1.5/krb5-1.5.4/doc/krb5-admin/Restoring-a-Kerberos-Database-from-a-Dump-File.html

Rolling back to an older OS release, once you have your backup, means having to rebuild/restore the kerberos data anew so matching the libraries on the system.

**Comment by sbharvey** [comment]
I would like to close this issue.  There were some software updates that affected samba at the time this issue was reported.  Samba running as an AD domain controller role now works, that included the DNS functions.  Here are the relevant current versions:

date
Wed Nov  2 05:01:26 PM PDT 2022

Distribution:      Clear Linux OS
Installed version: 37560
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

samba -V
Version 4.17.1

$ krb5-config --all
Version:     Kerberos 5 release 1.20
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
