### ISSUE TITLE
Support UEFI-less BIOS boot

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#274]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a system requires UEFI, since machines like the otherwise still plentiful capable Dell Optiplex 780 from less than 10 years ago (a fine machine even today if loaded with RAM and SSD) cannot boot the system.

**Describe the solution you'd like**
As a fallback for machines without UEFI, Clear Linux OS should either (also) support booting through something like GRUB (even if this means that it will be less optimized than a `systemd-boot`, or use a software-based UEFI implementation (e.g., from TianoCore or the [Clover EFI bootloader](https://sourceforge.net/projects/cloverefiboot/)). The normal BIOS could load the software-based UEFI implementation which in turn would proceed booting Clear Linux OS just as normal.

**Describe alternatives you've considered**
Throw a perfectly capable machine away just to buy a new one with UEFI and otherwise practically identical specs.

**Additional context**
Let's be environmentally friendly. Don't deprecate hardware "just because".

**Comment by ahkok** [comment]
The Dell Optiplex 780 is an unsupported CPU (core 2 duo).

Clearlinux does have a special installer for non-UEFI systems. AWS and other cloud providers do not support UEFI, for instance.

**Comment by probonopd** [comment]
Thanks for the clarification.

> Clearlinux does have a special installer for non-UEFI systems

Where can I learn about it?

**Comment by Raj2032** [comment]
With this KVM addition, what is going to be different about it other than support for legacy bios?

**Comment by miguelinux** [comment]
It is the same, just with legacy BIOS boot loader.
It is targeted to be used for private cloud without EFI boot support.

**Comment by desgua** [comment]
I would love to change my distro to Clear Linux but I can't figure out how to use the info above. Is it possible to get a straight forward instructions like: 1. Download this iso, 2. Extract this file, 3. Change this file, 4. Burn your DVD?

**Comment by jbrepogmailcom** [comment]
I would recommend to prepare UEFI-less ISO for easy download. Many people will choose to go with other distro if they can not install this one. I have several other distros installed and I do not want to change my boot base

**Comment by thiagomacieira** [comment]
This is unlikely to change.

**Comment by fenrus75** [comment]
the challenge is not the iso itself. the challenge is the bootloader and
automatic updates thereof...

**Comment by pdxjohnny** [comment]
> The Dell Optiplex 780 is an unsupported CPU (core 2 duo).

Does this mean that if people do jury-rig a BIOS image, the compiler settings Clear Linux uses while building package would result in invalid instruction errors on an "unsupported CPU"?

**Comment by probonopd** [comment]
Well, it's Intel, so I can understand they don't have a high priority to support CPUs such as

```
model name	: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
bugs		: cpu_meltdown spectre_v1 spectre_v2
```

even though it runs other Linux distros just fine...

**Comment by pdxjohnny** [comment]
Similarly-ish to gentoo part of the value add of Clear Linux is the optimization of packages via compiler settings to take advantage of CPU features in newer CPUs. Unlike gentoo Clear Linux distributes pre-compiled packages with an `-march=...` (I'm not sure what it is) which means that compilers would generate machine code for an architecture newer than Core 2 duo (is what I'm gathering from "not supported").

However, a really cool thing about Clear Linux is that you can use [mixer](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer) to create your own distro based on Clear Linux (akin to Ubuntu being based on Debian).

Theoretically you could use mixer to create a "mix" of Clear Linux which supports these older architectures. Your mix could also include the software UEFI environment (or however best to do BIOS boot).

**Comment by ahkok** [comment]
Although `mixer` is great, you'd have to `bootstrap` the entire OS from scratch, almost. I'm not saying it's impossible, but, `mixer` is only half the work needed to make a version of Clear Linux OS work on a pre-core CPU.

**Comment by martinezcristian141** [comment]
I managed to install clear linux on a UEFI-less laptop using clover, so it is installed on the disk, and it works very fast compared to zorin os, which was what I was installing on my laptop. the problem is that, clover does not recognize the OS, and every time I turn on the laptop I have to manually choose the file from which it has to boot. I just need a way to tell clover to automatically boot from that file.

**Comment by ahkok** [comment]
@martinezcristian141 please don't "necrobump". File a new ticket instead.
