### ISSUE TITLE
swupd cleanup is broken

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2740]
Got [this](https://community.clearlinux.org/t/cl-too-lenient-wrt-storage/7953) problem several times, please add post-install cleanup.

**Comment by marioroy** [comment]
Is the following needed to prune or purge the optimized-elf directory?
```bash
dir="/usr/share/clear/optimized-elf"
if [ -d "$dir" ]; then
  echo "Purging $dir of symlinks and unlinked files"
  pushd "$dir" >/dev/null

  # symlinks
  files=$(ls -l | awk '/->/ { print $9 }')
  [ -n "$files" ] && sudo rm -f $files

  # unlinked files
  files=$(ls -l | awk '$2 == 1 { print $9 }')
  [ -n "$files" ] && sudo rm -f $files

  unset files
  popd >/dev/null
fi
```

**Comment by marioroy** [comment]
No problem at all. Please, ignore whatever is not necessary. All symbolic links were broken on my Clear Linux and the reason purged from the optimized-elf directory. What about the unlinked files e.g. $2 == 1 in `ls -l` output?

**Comment by fenrus75** [comment]
we should fix the server side to not have symlinks there to begin with...
swupd will clean up the rest afterwards automatically

**Comment by marioroy** [comment]
I wish for the swupd tool to not install or update-download SSE4.2 optimized-elf files that will never be used on systems supporting AVX2. Imagine the reduction in web traffic and bandwidth. Are SSE4.2 optimized-elf files used on systems supporting AVX2?

**Comment by fenrus75** [comment]
the reality is a bit more complicated and currently we need all the
files here to make sure swupd operates correctly

all files here are sort of the "master copy"; say there's a file
/usr/bin/foo, the master copy for the different CPU versions of that
file lives here....  /usr/bin/foo is just a hardlink to one of them
(so not taking extra space on disk or during download)
this is where the binary deltas as part of swupd are done etc etc.
by deleting these files, binary deltas no longer work which means you
end up downloading full files instead which is worse by far.


we are pondering how to tweak swupd to not need this at all, but it's
complicated and we'll need to make decisions for delta packs that are
likely including all architecture files regardless.

**Comment by marioroy** [comment]
With this new knowledge comes responsibility :bow:  I commented out the code at the top above. Moreover, I deleted my post in the CL forum so that folks do run my purge script in the future.

**Comment by paulcarroty** [comment]
>  /usr/bin/foo is just a hardlink to one of them
(so not taking extra space on disk or during download)

Clear provides double libraries in ` /usr/lib64` and `/usr/lib64/glibc-hwcaps/`. Will it be improved too?

**Comment by thiagomacieira** [comment]
For some people, having both is a benefit (same image on multiple machines). For some others, that's a drawback due to increased disk usage.

**Comment by marioroy** [comment]
I wish there was an option that one can set during installation or post configuration to not install optimized-elf SSE4.2 files as they are not used on systems supporting AVX2. One concerning aspect is network utilization from ISP providers. Some plans may have limits. I'm thinking about folks using 5g home internet, not Cable or Fios.

Off-topic: Some time ago, I tried converting from swupd to dnf system wide update. Oh the joy I experienced running `dnf search`. To ensure that all files are accounted for, I ran m4 against clr-bundles/bundles/desktop to obtain an initial list of packages. Installing the packages then picked up all the dependencies. I'm going to try this again someday and take notes, comparing two VMs. One updated via swupd, the other via dnf update. There are few post-update steps after running dnf update but is manageable and can be scripted.

**Comment by marioroy** [comment]
There is infinite-recursion inside clr-bundles/bundles. To break the perpetual recursion, I needed to comment out an include line in 4 files.
```text
# NetworkManager-tui, comment out include(NetworkManager)
# aspell-de, comment out include(aspell)
# aspell-es, comment out include(aspell)
# aspell-fr, comment out include(aspell)
```
I ran m4 to obtain an initial list of packages. Basically, I added additional m4 until not seeing `also-add` in the output.
```bash
m4 desktop | egrep -v "^#" | sort -u | sed 's/^also-add/include/g' |\
        m4 | egrep -v "^#" | sort -u | sed 's/^also-add/include/g' |\
        m4 | egrep -v "^#" | sort -u
```

**Comment by phmccarty** [comment]
@marioroy The Clear Linux team uses `unbundle` for processing bundle definitions these days. It is available from https://github.com/clearlinux/unbundle. Will that tool suffice for your needs?

**Comment by marioroy** [comment]
Yes! I will give `unbundle` a try. Thank you for the tip.

**Comment by marioroy** [comment]
++ for `unbundle` :)  Ah, it includes `os-core` which is what I was missing at the time of the `swupd` to `dnf` conversion.

```bash
./unbundle desktop ../clr-bundles | sort -u >/tmp/list1

( grep -v '^#' os-core
  m4 desktop | grep -v '^#'
) | grep -v '^also-add' | sort -u >/tmp/list2

# outputs a blank-line as the only difference, not filtered above
diff /tmp/list1 /tmp/list2
```

To include the `also-add` entries, which will output gnome-text-editor, gnome-photos, and 55 additional packages, one must first break the infinite recursion in the four files mentioned above or grep out `also-add` prior to sorting. The following works for me. The `unbundle` script, if later supporting `also-add` entries, will need to detect for infinite recursion or it will never end. :)

```bash
( grep -v '^#' os-core
  m4 desktop | grep -v '^#' | sed 's/^also-add/include/' |\
          m4 | grep -v '^#' | sed 's/^also-add/include/' |\
          m4 | grep -v '^#'
) | grep -v 'also-add' | sort -u >/tmp/list3

diff /tmp/list2 /tmp/list3 | grep -c '^<'    # 0
diff /tmp/list2 /tmp/list3 | grep -c '^>'    # 57
```

The extra `also-add` entries output 57 additional packages.
```text
diff /tmp/list2 /tmp/list3 | grep '^>' | awk '{ print $NF }'
aspell
aspell-de
aspell-es
aspell-fr
baobab
cheese
connections
ctags
cups-bjnp
dbus-glib-lib
emacs-x11
eog
eog-plugins
epson-inkjet-printer-escpr
evince
evolution
evolution-ews
firefox
flatpak
flatpak-builder
geary
gedit
gedit-plugins-gnome
ghostscript
gimp
git
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-online-accounts-lib
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-text-editor
gnome-todo
gnome-weather
gnupg
gobject-introspection-lib
gvim
hplip
hub
libadwaita-lib
moreutils
nautilus
NetworkManager-extras
pulseaudio
sane-backends
thermal_daemon
thermal_daemon-autostart
totem
vim
vim-fugitive
vim-gnupg
```

One day, time permitted, I will try again `swupd` to `dnf` one-time conversion and document the steps.

**Comment by fenrus75** [comment]
also-add isn't a dependency
its a suggestion to the cli to install optional pieces

**Comment by marioroy** [comment]
Yes, understood. However, I want many of the packages picked up from processing `also-add` e.g. firefox, gnome-text-editor, gnome-photos, lots more; packages typically installed using the desktop installer.

**Comment by marioroy** [comment]
Since the list is small, I can cherry pick the packages typically installed using the desktop installer.
