### ISSUE TITLE
consider changing cups systemd unit files from cupsd.{path,socket,service} to cups.{path,socket,service}

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#2745]
Other distributions such as [Ubuntu](https://packages.ubuntu.com/jammy/amd64/cups-daemon/filelist), [Fedora](https://src.fedoraproject.org/rpms/cups/blob/rawhide/f/cups.spec#_604), [Open Suse](https://build.opensuse.org/package/view_file/Printing/cups/cups.spec?expand=1) and [Arch linux](https://archlinux.org/packages/extra/x86_64/cups/) have its systemd unit files named as `cups.{path,service,socket}`.

Having cups daemon renamed as `cups` instead of `cupsd` on clearlinux would simplify multi-distro automation setup scripts as it would match a more-generic setup rather than being a specially-handled case 😃

**Comment by fenrus75** [comment]
hmm we follow the upstream names .. more or less
will poke more

**Comment by phmccarty** [comment]
It looks like the current upstream repo is https://github.com/OpenPrinting/cups ... not sure if that will address the issue, but the repo are currently pulling from (https://github.com/apple/cups) seems more stale.

**Comment by phmccarty** [comment]
The latest release from https://github.com/OpenPrinting/cups (v2.4.2) contains the requested service file name changes.

I'm working on that update.

**Comment by phmccarty** [comment]
The update to cups v2.4.2 will be available in the next release.

**Comment by phmccarty** [comment]
Fixed in release [37340](https://cdn.download.clearlinux.org/releases/37340/clear/RELEASENOTES-37320-to-37340).
