### ISSUE TITLE
Bundle request for kernel-native-current-dkms

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2747]
https://community.clearlinux.org/t/missing-kernel-source-for-kernel-native-currents-linux-current/7969

I miss being able to `dnf install/update`. Because one can easily install the missing kernel source package with dnf. So now, the OP must be kindly instructed to open a bundle request or wait magically for a Clear Linux team member to take notice.

I updated my [nvidia-driver-on-clear-linux](https://github.com/marioroy/nvidia-driver-on-clear-linux) repo. It guides the user to open a bundle request or install the associated dev package.

Blessings and Grace

**Comment by fenrus75** [comment]
we deliberately don't provide this; this kernel is a wild west kind of
thing that really has no place for external kernel modules like nvidia...
they'll break all the time
and that makes it a bad experience (and nasty bugreports asking us not to
go fast while the point of this kernel to go fast)

**Comment by marioroy** [comment]
Folks using NVIDIA graphics should use the latest LTS kernel. The LTS kernel has been great.

Off-topic: I was simply helping the OP. What you wrote makes a lot of sense. Thanks a bunch.
