### ISSUE TITLE
qalculate-gtk to 4.4

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#2755]
some functions added

**Comment by fenrus75** [comment]
I'll take a look but qalculate breaks ABI (changes soname) very frequently
so it's not a friendly/easy thing for us to do

**Comment by marioroy** [comment]
Nice app !!  Clicking on the Help menu and Contents does nothing. Oh, I see why. The qalculoate-gtk bundle lacks qalculate-gtk-man and qalculate-gtk-doc. These exists:

https://cdn.download.clearlinux.org/releases/37640/clear/x86_64/os/Packages/
