### ISSUE TITLE
Cannot shut down from XFCE session

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#276]
**Describe the bug**
Cannot shut down the machine from a running XFCE session.

**To Reproduce**
1. Install the XFCE desktop
2. Try to shut down the machine without using the terminal and without going to GDM

**Expected behavior**
It should be possible to shut down and restart the machine right from the XFCE menu, without using the terminal and without going to GDM.

![](https://user-images.githubusercontent.com/2480569/48314280-34abf900-e5bf-11e8-9e82-f049830ec1fa.png)

**Environment (please complete the following information):**

```
user@clr-... ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

user@clr-... ~ $ sudo swupd bundle-list
Password: 
bootloader
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
editors
emacs
ethtool
iproute2
joe
kernel-native
libX11client
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
python3-basic
sudo
sysadmin-basic
vim
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop
```

**Comment by ahkok** [comment]
This may well be an upstream bug, as Xfce4 largely predates and avoids polkit etc.. You may need to be a `wheel` user to be allowed shutdown or reboot privileges.

**Comment by probonopd** [comment]
This is what I get when I try to log out for the first time:

![](https://user-images.githubusercontent.com/2480569/48376488-fb5cb180-e6c2-11e8-963f-56ff19c69f2a.png)

**Comment by ahkok** [comment]
Current status: `lightdm` and `xfce4-desktop` - 31470

- `log out` button appears in Xfce4, logs the user out without further prompts
- whiskermenu isn't enabled by default. The "logout" button logs me out immediately

This puts you back into lightdm. It has a `power off` button.

This seems reasonable for now. Things work maybe less efficiently but all the functionality is there.

**Comment by probonopd** [comment]
> This seems reasonable for now. Things work maybe less efficiently but all the functionality is there.

Why not do it like on e.g, Xubuntu?

**Comment by ahkok** [comment]
> Why not do it like on e.g, Xubuntu?

I'd love to, but I lack the time to figure out what's wrong. If someone does, that would be a great help.
