### ISSUE TITLE
postgresql12 not available

### ISSUE THREAD

**Issue by wheerdam** [clearlinux/distribution#2761]
Is postgresql 15 the only supported version of PostgresSQL in Clearlinux from now on? The packages that provide the older binaries have been removed from the postgresql bundle and postgresql11/12/13/14 bundles do not provide anything. I'm unable to migrate my databases to 15 without those binaries and I can not run the older databases with the new OS version.

Thanks.

**Comment by bryteise** [comment]
Can you revert to 37470 or earlier as the binaries exist there to do your migration?

**Comment by wheerdam** [comment]
> Can you revert to 37470 or earlier as the binaries exist there to do your migration?

That's what I did, but I think dropping support for <15 only a couple of weeks after 15 is released is a bit abrupt!

Closing issue.
