### ISSUE TITLE
`sig_unenforce` kernel patch for the AWS kernel

### ISSUE THREAD

**Issue by VivekPanyam** [clearlinux/distribution#2768]
Hello!

The documentation says to use the `sig_unenforce` kernel command line parameter to disable signature checking of kernel modules. This works correctly on the LTS kernel, but not on the AWS one.

It looks like the [kernel patch](https://github.com/clearlinux-pkgs/linux/blob/main/0114-add-boot-option-to-allow-unsigned-modules.patch) that enables this parameter is not part of the [AWS kernel build](https://github.com/clearlinux-pkgs/linux-aws).

Is there a reason it's not included in the AWS kernel? If not, can that patch be added? Thank you!

---

References:

- https://clearlinux.github.io/clear-linux-documentation/guides/kernel/kernel-modules.html#load-kernel-module
- https://clearlinux.github.io/clear-linux-documentation/guides/kernel/kernel-modules-dkms.html#install-dkms

**Comment by bwarden** [comment]
Looks like that was inadvertently dropped in a patch cleanup a while back. I'll add it back in. This issue will be tagged when the fix has landed in a release.

**Comment by VivekPanyam** [comment]
Thank you! Do you have a rough estimate of how long that'll take?

**Comment by bwarden** [comment]
Within a week, possibly less than that. I think we do releases about twice a week, but only publish them if they pass testing. I tagged this issue in the commit, so when it's published to https://github.com/clearlinux-pkgs/linux-aws (automatic, shortly after release) this issue will be tagged/closed.

**Comment by bwarden** [comment]
Fixed in releases >=37630
