### ISSUE TITLE
top is a symlink to htop

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#277]
**Describe the bug**
When typing in `top`, I unexpectedly get something very different from what I get on about every other distribution. At least in XFCE and using an Apple keyboard, it can't even be closed (since F10 opens the File menu).

**To Reproduce**
1. Install the XFCE desktop
2. open `xfce-terminal`
3. open `top`
4. Try to close it

**Expected behavior**
`top` should not be a symlink to `htop`.

**Environment (please complete the following information):**

```
user@clr-... ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

user@clr-... ~ $ sudo swupd bundle-list
Password: 
bootloader
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
editors
emacs
ethtool
iproute2
joe
kernel-native
libX11client
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
python3-basic
sudo
sysadmin-basic
vim
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop
```

**Comment by ahkok** [comment]
We had a discussion about this and the f10 item you mentioned.

I am tempted to say that we won't likely change top back to the old top. htop is sufficient and can be configured properly to mimic the old top enough that there is little value in adding old top back.

The gnome terminal captures f10 by default, and I agree that it is highly cumbersome. However, it can also be disabled in the settings and the setting is really easy to find as it's on one of the top pages in the gnome-terminal settings panel.

Given the above workaround and plan for htop to remain the default top, I'd like to close this issue for now.

**Comment by phmccarty** [comment]
Also note that in Clear Linux OS, the original `top` program is named `top2`, so it is still available, just with a alternate name.

**Comment by probonopd** [comment]
> Also note that in Clear Linux OS, the original top program is named top2, so it is still available, just with an alternate name.

That kind of reshuffling this is what makes "Linux" "hard". Why not keep the `top` and `htop` names like on other distributions, e.g., Ubuntu.

**Comment by eero-t** [comment]
> > Also note that in Clear Linux OS, the original top program is named top2, so it is still available, just with an alternate name.
> 
> That kind of reshuffling this is what makes "Linux" "hard". Why not keep the `top` and `htop` names like on other distributions, e.g., Ubuntu.

Exactly.  While I do like HTop because of its extra features, those also make it larger & slower than the real Top, which matters when machine is in swap hell and one wants to know what process caused that before it gets OOM-killed.  One doesn't remember in hurry that "oh, on Clear Linux I need to use this weird top2 command name to get a top that starts fast enough to catch the culprit".

(Sometimes I've even used Busybox top instead of GNU top, because that's even faster to start, to see what caused swapping with our complex & dynamic cgroups policies. That was last decade though, on slowish ARM machines.)

**Comment by ahkok** [comment]
> when machine is in swap hell

I strongly suggest not relying on any ncurses application when you're in swap hell, and instead rely on `ps aux --sort rss` or something like that.

**Comment by tpleavitt** [comment]
@phmccarty , please review and solve this please

**Comment by pevik** [comment]
> > when machine is in swap hell
> 
> I strongly suggest not relying on any ncurses application when you're in swap hell, and instead rely on `ps aux --sort rss` or something like that.

Yes, but renaming `htop` to `top` and `top` to `top2` is really silly. Why?
We got in LTP patch trying to fix it: https://patchwork.ozlabs.org/patch/1146709/

**Comment by eero-t** [comment]
> I strongly suggest not relying on any ncurses application when you're in swap hell, and instead rely on ps aux --sort rss or something like that.

FYI: Real top doesn't use ncurses library, even in ClearLinux, only HTop does.  Top links just to "tinfo":
```
$ readelf -d /usr/bin/top | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libncursesw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libtinfow.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 $ readelf -d /usr/bin/top2 | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libprocps.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libtinfo.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
$ readelf -d /usr/bin/ps | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libprocps.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

(tinfo is originally part of libtermcap, which nowadays happens to be provided (also) by ncurses package.  I think the slower wide char version of tinfo came only with ncurses, but as seen from above, Top doesn't use that either, only HTop does.)

Unfortunately "libprocps" seems to nowadays bring in "libsystemd" which brings in lot of other things, so that's also quite heavy dependency:
```
$ ldd /usr/lib64/libprocps.so.7
	linux-vdso.so.1 (0x00007fff7c9f9000)
	libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007fbaa18fc000)
	libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007fbaa18f6000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007fbaa1702000)
	librt.so.1 => /usr/lib64/librt.so.1 (0x00007fbaa16f7000)
	libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007fbaa15fc000)
	libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fbaa15e1000)
	libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007fbaa15bc000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007fbaa1a28000)
	libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007fbaa15a1000)
```

=> I think I'll prefer relying on Busybox or ToyBox top/ps in that kind of situations.  Neither of them seems to be in ClearLinux though.


> renaming htop to top and top to top2 is really silly.

I don't think it funny, just gratuitous differentiation.  Or did I miss the real joke?

**Comment by pevik** [comment]
> > renaming htop to top and top to top2 is really silly.
> 
> I don't think it funny, just gratuitous differentiation. Or did I miss the real joke?

I also wonder what was the reason and whether it was worth of problems it caused.

@fenrus75 @phmccarty any change, you start using real names?
