### ISSUE TITLE
Add missing {dev} package to the devpkg-openblas bundle definition

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2771]
openblas-dev

e.g. resolves the issue openblas.pc pkgconfig file missing

**Comment by fenrus75** [comment]
hm will need to investigate.. the devpkg-* stuff is script generated (so
hand edits get clobbered)... so need to figure out why the scripts get this
not right

**Comment by marioroy** [comment]
What about the following? The bundle definition pulls in "filesystem" only.
```text
devpkg-atk
devpkg-at-spi2-atk
devpkg-compat-gegl
devpkg-mozjs52
devpkg-mozjs78
```

**Comment by marioroy** [comment]
This issue is resolved in Clear Linux 37650. Cool !!
