### ISSUE TITLE
Kernel Version Above 6.0.3-1202.native Crashes ASUS AMD Server

### ISSUE THREAD

**Issue by sbharvey** [clearlinux/distribution#2773]
Happy Thanksgiving

The system is:
1.) ASUS ROG STRIX B550-F GAMING AM4 AMD B550 SATA 6Gb/s ATX AMD Motherboard
2.) AMD Ryzen 9 5950X - Ryzen 9 5000 Series Vermeer (Zen 3) 16-Core 3.4 GHz Socket AM4 105W Desktop Processor
3.) 32 GB of ram
4.) The main root disk is: M.2 2280 1TB PCI-Express 3.0 x4, NVMe v1.4 TLC Internal Solid State Drive (SSD) ...
5.) Sata WD Red Pro WD221KFGX 22TB 7200 RPM hard disk.
6.) Video card: ASUS GeForce GT 1030 DirectX 12 GT1030-SL-2G-BRK 2GB 64-Bit GDDR5 PCI Express 3.0 HDCP Ready Video Card

I had an update November 22 see below.

journalctl -u swupd-update.service --since 'Nov 22 00:00:00' > software_update_2022-1122.log
-----
Nov 22 12:39:38 netserver03 systemd[1]: Starting Update Software content...
Nov 22 12:39:38 netserver03 swupd[279433]: Update started
Nov 22 12:39:39 netserver03 swupd[279433]: [49B blob data]
Nov 22 12:39:53 netserver03 swupd[279433]: [449B blob data]
Nov 22 12:39:53 netserver03 swupd[279433]:  - NetworkManager
Nov 22 12:39:53 netserver03 swupd[279433]:  - NetworkManager-extras
Nov 22 12:39:53 netserver03 swupd[279433]:  - Sphinx
Nov 22 12:39:53 netserver03 swupd[279433]:  - alsa-utils
Nov 22 12:39:53 netserver03 swupd[279433]:  - ansible
Nov 22 12:39:53 netserver03 swupd[279433]:  - binutils
Nov 22 12:39:53 netserver03 swupd[279433]:  - blivet-gui
Nov 22 12:39:53 netserver03 swupd[279433]:  - c-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - cloud-api
Nov 22 12:39:53 netserver03 swupd[279433]:  - darktable
Nov 22 12:39:53 netserver03 swupd[279433]:  - desktop
Nov 22 12:39:53 netserver03 swupd[279433]:  - desktop-apps
Nov 22 12:39:53 netserver03 swupd[279433]:  - desktop-dev
Nov 22 12:39:53 netserver03 swupd[279433]:  - desktop-gnomelibs
Nov 22 12:39:53 netserver03 swupd[279433]:  - desktop-kde-libs
Nov 22 12:39:53 netserver03 swupd[279433]:  - dev-utils
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-NetworkManager
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-Vulkan-Headers
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-Vulkan-Loader
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-avahi
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-cryptsetup
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-cups
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-flatpak
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-gdk-pixbuf
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-gnome-software
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-harfbuzz
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-libXpm
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-libgphoto2
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-libpng
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-mediasdk
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-mutter
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-pango
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-systemd
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-vala
Nov 22 12:39:53 netserver03 swupd[279433]:  - devpkg-xorg-server
Nov 22 12:39:53 netserver03 swupd[279433]:  - emacs-x11
Nov 22 12:39:53 netserver03 swupd[279433]:  - firefox
Nov 22 12:39:53 netserver03 swupd[279433]:  - flatpak
Nov 22 12:39:53 netserver03 swupd[279433]:  - fonttools
Nov 22 12:39:53 netserver03 swupd[279433]:  - gdb
Nov 22 12:39:53 netserver03 swupd[279433]:  - gedit
Nov 22 12:39:53 netserver03 swupd[279433]:  - gimp
Nov 22 12:39:53 netserver03 swupd[279433]:  - gnome-calculator
Nov 22 12:39:53 netserver03 swupd[279433]:  - gnome-disk-utility
Nov 22 12:39:53 netserver03 swupd[279433]:  - gpgme
Nov 22 12:39:53 netserver03 swupd[279433]:  - gphoto2
Nov 22 12:39:53 netserver03 swupd[279433]:  - gvim
Nov 22 12:39:53 netserver03 swupd[279433]:  - hardware-uefi
Nov 22 12:39:53 netserver03 swupd[279433]:  - kde-frameworks5
Nov 22 12:39:53 netserver03 swupd[279433]:  - kernel-native
Nov 22 12:39:53 netserver03 swupd[279433]:  - lib-imageformat
Nov 22 12:39:53 netserver03 swupd[279433]:  - lib-opengl
Nov 22 12:39:53 netserver03 swupd[279433]:  - lib-samba
Nov 22 12:39:53 netserver03 swupd[279433]:  - libX11client
Nov 22 12:39:53 netserver03 swupd[279433]:  - libstdcpp
Nov 22 12:39:53 netserver03 swupd[279433]:  - linux-tools
Nov 22 12:39:53 netserver03 swupd[279433]:  - llvm
Nov 22 12:39:53 netserver03 swupd[279433]:  - openblas
Nov 22 12:39:53 netserver03 swupd[279433]:  - os-core
Nov 22 12:39:53 netserver03 swupd[279433]:  - os-core-dev
Nov 22 12:39:53 netserver03 swupd[279433]:  - os-core-plus
Nov 22 12:39:53 netserver03 swupd[279433]:  - os-core-update
Nov 22 12:39:53 netserver03 swupd[279433]:  - perl-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - polkit
Nov 22 12:39:53 netserver03 swupd[279433]:  - psensor
Nov 22 12:39:53 netserver03 swupd[279433]:  - python-extras
Nov 22 12:39:53 netserver03 swupd[279433]:  - python3-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - qt-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - samba
Nov 22 12:39:53 netserver03 swupd[279433]:  - seahorse
Nov 22 12:39:53 netserver03 swupd[279433]:  - spice-gtk
Nov 22 12:39:53 netserver03 swupd[279433]:  - storage-utils
Nov 22 12:39:53 netserver03 swupd[279433]:  - stress-ng
Nov 22 12:39:53 netserver03 swupd[279433]:  - sysadmin-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - sysadmin-basic-dev
Nov 22 12:39:53 netserver03 swupd[279433]:  - tcl-basic
Nov 22 12:39:53 netserver03 swupd[279433]:  - vim
Nov 22 12:39:53 netserver03 swupd[279433]:  - virt-manager
Nov 22 12:39:53 netserver03 swupd[279433]:  - vlc
Nov 22 12:39:53 netserver03 swupd[279433]:  - x11-server
Nov 22 12:39:53 netserver03 swupd[279433]:  - xfce4-desktop
Nov 22 12:39:53 netserver03 swupd[279433]:  - xterm
Nov 22 12:40:14 netserver03 swupd[279433]: Finishing packs extraction...
Nov 22 12:40:44 netserver03 swupd[279433]: Statistics for going from version 37640 to version 37650:
Nov 22 12:40:44 netserver03 swupd[279433]:     changed bundles   : 82
Nov 22 12:40:44 netserver03 swupd[279433]:     new bundles       : 0
Nov 22 12:40:44 netserver03 swupd[279433]:     deleted bundles   : 0
Nov 22 12:40:44 netserver03 swupd[279433]:     changed files     : 8819
Nov 22 12:40:44 netserver03 swupd[279433]:     new files         : 5363
Nov 22 12:40:44 netserver03 swupd[279433]:     deleted files     : 6069
Nov 22 12:40:44 netserver03 swupd[279433]:     largest pack      : devpkg-vala 17963Kb
Nov 22 12:40:44 netserver03 swupd[279433]: Validate downloaded files
Nov 22 12:40:46 netserver03 swupd[279433]: No extra files need to be downloaded
Nov 22 12:40:46 netserver03 swupd[279433]: Installing files...
Nov 22 12:40:47 netserver03 swupd[279433]: Update was applied
Nov 22 12:40:47 netserver03 swupd[279433]: Calling post-update helper scripts
Nov 22 12:40:47 netserver03 swupd[279433]: External command: none
Nov 22 12:40:48 netserver03 swupd[279433]: External command: Warning: The kernel is still using the old partition table.
Nov 22 12:40:48 netserver03 swupd[279433]: External command: The new table will be used at the next reboot or after you
Nov 22 12:40:48 netserver03 swupd[279433]: External command: run partprobe(8) or kpartx(8)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: The operation has completed successfully.
Nov 22 12:40:48 netserver03 swupd[279433]: External command: clr_debug_fuse.service: restarted (the binary was updated)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: Failed to try-restart pacdiscovery.service: Unit systemd-resolved.service is masked.
Nov 22 12:40:48 netserver03 swupd[279433]: External command: Failed to restart: pacdiscovery.service (systemctl returned error code: 256)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: sh: line 1: /usr/bin/telem-record-gen: No such file or directory
Nov 22 12:40:48 netserver03 swupd[279433]: External command: pacdiscovery.service: restarted (the binary was updated)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: tallow.service: restarted (the binary was updated)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: pacrunner.service: restarted (the binary was updated)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: systemd-journald.service: restarted (the binary was updated)
Nov 22 12:40:48 netserver03 swupd[279433]: External command: systemd-timesyncd.service: restarted (the binary was updated)
Nov 22 12:41:56 netserver03 swupd[279433]: Update took 137.8 seconds, 145 MB transferred
Nov 22 12:41:56 netserver03 swupd[279433]: Update successful - System updated from version 37640 to version 37650
Nov 22 12:41:56 netserver03 systemd[1]: swupd-update.service: Deactivated successfully.

System was up for:

09:22:31  up 27 days 17:15,  1 user,  load average: 0.36, 0.16, 0.0

Performed a hardware reboot to latest build: 37650

The system was bricked.    Would not proceed pass the initial kernel messages to the console.
I had to use the DVD of the ISO build to restore the system back to an earlier version
Tried to go back to  37640  did not work.   Note I had not tried to do a full reboot since 27 days ago.

I went back to  build 37500 
swupd repair 37500 -S /mnt/boot_drv1/var/lib/swupd --force --path /mnt/boot_drv1

The system was able to reboot again 

uname -a
Linux netserver03 6.0.3-1202.native #1 SMP Fri Oct 21 05:48:09 PDT 2022 x86_64 GNU/Linux

samba -V
Version 4.17.1

swupd info
Distribution:      Clear Linux OS
Installed version: 37500
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

Something is out of bed with how the boot loader app clr-boot-manager is suppose to work
This system is up and running output of clr-boot-manager show up to a later kernel
Command issued after system had been rebooted.

clr-boot-manager list-kernels
* org.clearlinux.native.6.0.9-1213
  org.clearlinux.native.6.0.9-1209
  org.clearlinux.native.6.0.3-1202

This /usr/lib/kernel indicates what the default kernel displays in it's version report
The default kernel shows the -1202 version, something wrong their.

ls -l /usr/lib/kernel
total 40872
-rw-r--r-- 1 root root      267 Oct 25 11:07 cmdline-6.0.3-1202.native
-rw-r--r-- 2 root root      267 Nov 16 08:38 cmdline-6.0.9-1209.native
-rw-r--r-- 1 root root      267 Nov 22 12:40 cmdline-6.0.9-1213.native
-rw-r--r-- 1 root root   241410 Oct 25 11:07 config-6.0.3-1202.native
-rw-r--r-- 2 root root   241399 Nov 16 01:31 config-6.0.9-1209.native
-rw-r--r-- 1 root root   241388 Nov 22 12:40 config-6.0.9-1213.native
lrwxrwxrwx 1 root root       32 Oct 21 05:54 default-native -> org.clearlinux.native.6.0.3-1202
drwxr-xr-x 2 root root     4096 Nov 23 18:10 install.d
-rwxr-xr-x 1 root root 13657248 Oct 21 05:50 org.clearlinux.native.6.0.3-1202
-rwxr-xr-x 2 root root 13724672 Nov 16 01:31 org.clearlinux.native.6.0.9-1209
-rwxr-xr-x 1 root root 13723136 Nov 21 12:27 org.clearlinux.native.6.0.9-1213

I have stopped auto updating with swupd.

**Comment by sbharvey** [comment]
I added the start of the dmesg log to find out what kernel is being booted.   I cannot figure out how the boot kernel is selected/set.   

[    0.000000] Linux version 6.0.3-1202.native (mockbuild@6e61b5b804b9487083a6fcd4929f79b7) (gcc (Clear Linux OS for Intel Architecture) 12.2.1 20221017 releases/gcc-12.2.
0-144-gfe7d743137, GNU ld (GNU Binutils) 2.39.0) #1 SMP Fri Oct 21 05:48:09 PDT 2022
[    0.000000] Command line:  BOOT_IMAGE=org.clearlinux.native.6.0.3-1202 root=PARTUUID=be70439f-a96b-4e7a-9ea6-c8c5f37efcd4 quiet console=tty0 console=ttyS0,115200n8 crypt
omgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1**
 rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw 
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x200: 'Protection Keys User registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: xstate_offset[9]:  832, xstate_sizes[9]:    8
[    0.000000] x86/fpu: Enabled xstate features 0x207, context size is 840 bytes, using 'compacted' format.
[    0.000000] signal: max sigframe size: 3376
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009d3ff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009d400-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000e0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x0000000009d1efff] usable
[    0.000000] BIOS-e820: [mem 0x0000000009d1f000-0x0000000009ffffff] reserved
[    0.000000] BIOS-e820: [mem 0x000000000a000000-0x000000000a1fffff] usable
[    0.000000] BIOS-e820: [mem 0x000000000a200000-0x000000000a20dfff] ACPI NVS
[    0.000000] BIOS-e820: [mem 0x000000000a20e000-0x000000000affffff] usable
[    0.000000] BIOS-e820: [mem 0x000000000b000000-0x000000000b01ffff] reserved
[    0.000000] BIOS-e820: [mem 0x000000000b020000-0x00000000c3dedfff] usable
-

**Comment by sbharvey** [comment]
Closed issue by accident sorry.

**Comment by bryteise** [comment]
The following lines seem unexpected to me.
```
Nov 22 12:40:48 netserver03 swupd[279433]: External command: Warning: The kernel is still using the old partition table.
Nov 22 12:40:48 netserver03 swupd[279433]: External command: The new table will be used at the next reboot or after
```

That said, it isn't likely related to the problem.

As far as 1202 being the default kernel, that symlink is defined by the os-version I believe but clr-boot-manager has its own state for kernels it has booted and will use the latest last booted kernel of a type (1213 it looks like) unless manually set (via clr-boot-manager's commandline option).

You can see the details of the config for what is booting by default by inspecting your boot partition and looking at the systemd-boot configs as well to verify.

**Comment by sbharvey** [comment]
Thank you for getting back.

My system is booting an image called /usr/bin/initra-desktop.  Snippet from dmesg log:

[ 0.000000] Command line: BOOT_IMAGE=org.clearlinux.native.6.0.3-1202 root=PARTUUID=be70439f-a96b-4e7a-9ea6-c8c5f37efcd4 quiet console=tty0 console=ttyS0,115200n8 crypt
omgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1**
rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw

I can't see where that is being configured with what I believe is the command systemd-boot this does not exist in my build.
Also there is this URL 
https://github.com/bedrocklinux/bedrocklinux-userland/issues/124
That talks about how to go boot something other than the /usr/bin/inita-desktop.   Do I have to something similar to start booting later kernels that are being rolled out in the later builds

**Comment by bryteise** [comment]
The init= isn't the kernel but the userspace program that the kernel launches. Is that command line from the live image? Seeing the BOOT_IMAGE portion seems odd to me otherwise. clr-boot-manager should be able to control what kernel is booting.

**Comment by sbharvey** [comment]
This the BOOT_IMAGE statement is from the system as installed on the system

swupd info
Distribution:      Clear Linux OS
Installed version: 37500
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

cat /proc/cmdline 
BOOT_IMAGE=org.clearlinux.native.6.0.3-1202 root=PARTUUID=be70439f-a96b-4e7a-9ea6-c8c5f37efcd4 quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests init=/usr/bin/initra-desktop initcall_debug intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp page_alloc.shuffle=1 rcupdate.rcu_expedited=1 rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw

uname -r
6.0.3-1202.native

oot@netserver03~ # clr-boot-manager list-kernels
* org.clearlinux.native.6.0.9-1213
  org.clearlinux.native.6.0.3-1202

Cannot get beyond kernel version 6.0.3-1202.native.   If I re-enable auto update I will not be able to boot my system.
Do the kernels beyond 6.0.3-1202.native not support AMD processors?   

cpu info:
obtained from cat /proc/cpuinfo

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 25
model		: 33
model name	: AMD Ryzen 9 5950X 16-Core Processor
stepping	: 2
microcode	: 0xa201204
cpu MHz		: 3400.000
cache size	: 512 KB
physical id	: 0
siblings	: 32
core id		: 0
cpu cores	: 16
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 16
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm
bugs		: sysret_ss_attrs spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 6787.17
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]

**Comment by sbharvey** [comment]
I used clear-36010-live-server.iso to create a boot/root drive for my AMD system so as keep my system able to boot from internal drive.  (swupd is still disabled for internal drive).   Following the swupd update on the USB flash drive, I got up to:

swupd info
Distribution:      Clear Linux OS
Installed version: 37290
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

uname -r
5.16.13-1132.native

There was another build number build revision to go through in the swupd update 37710
The kernel that goes along with that update is:  6.0.10-1215.native
The kernel failed to boot.  

I renew my question is the AMD Rayzen processor not supported after a kernel 6.0.3-1202?

**Comment by bwarden** [comment]
> I renew my question is the AMD Rayzen processor not supported after a kernel 6.0.3-1202?

None of the changes we've made should have affected this, to my knowledge. You can review them like this:
https://github.com/clearlinux-pkgs/linux/compare/6.0.3-1202...main

When it appeared to hang, did you try to reach an alternate console, via Alt+F2 or Alt+F3, for example? Sometimes the main console stops responding for some reason but the system is actually running. Also, if you have SSH login enabled, that would be good to check.

**Comment by sbharvey** [comment]
The system has halted and or crashed.  I tried Alt-F2 Alt-F3 no response.  When the system boots correctly it runs a Windows Primary Domain Controller, serves as a router and file server.  None of that works.  I took a picture of what appears on the Console screen.  The first systlinux boot message then ends with repeated kvm_amd disabled in bios messages and stalls.
See the screen shot.   This USB flash drive boots an older Intel I7 machine just fine.  When I boot with a build with something at kernel version 6.0.3-12027 or below it boots as expected.  

![20221206_164339](https://user-images.githubusercontent.com/10262485/206061081-4e75ed5f-4c8c-4bf1-9b25-6f3c26555c67.jpg)

**Comment by bwarden** [comment]
Try removing `quiet` and adding `debug` to the kernel command line (hit space repeatedly while booting to get into the menu, hit 'e' to edit the highlighted boot entry). Hopefully there'll be more useful output.

**Comment by sbharvey** [comment]
Boot parameters changed removed the quiet and adding the debug directive.   Screen shot shows when the console screen stopped.  
![20221207_095330](https://user-images.githubusercontent.com/10262485/206262134-1aaad1ff-b4cf-4c1f-8b84-883e945b44d2.jpg)

**Comment by bryteise** [comment]
Hrm I think you may have some other hardware problem though I'm not sure what it is. I was able to confirm that clear is booting on an AMD system with the 6.0.11-1216.native kernel at least.

Might be worth seeing what lspci shows on the working kernel.

**Comment by sbharvey** [comment]
I have added post failed boot analysis.

[lspci_status_6.0.3-1202.native.txt](https://github.com/clearlinux/distribution/files/10179610/lspci_status_6.0.3-1202.native.txt)
[6.0.11-1216.native.journal_dmesg_format.txt](https://github.com/clearlinux/distribution/files/10179612/6.0.11-1216.native.journal_dmesg_format.txt)

**Comment by sbharvey** [comment]
> Hrm I think you may have some other hardware problem though I'm not sure what it is. I was able to confirm that clear is booting on an AMD system with the 6.0.11-1216.native kernel at least.
> 
> Might be worth seeing what lspci shows on the working kernel.

Do you have more details on the AMD system?  For example, do know what GPU chip set is installed?  
In my case I have been able to isolate it down to the VGA.  The VGA is based on a GeForce GT 1030 chip set.  According to site https://nouveau.freedesktop.org/CodeNames.html the driver nouveau should support the card I have, but for some reason any kernel release above 6.0.3-1202 does not work. 

A post kernel dump reveals a few sub components are failing at boot time in kernels above 6.0.3-1202.
 
Dec 08 12:06:03 USB-BootDrv kernel: nouveau 0000:0a:00.0: acr: firmware unavailable
Dec 08 12:06:03 USB-BootDrv kernel: nouveau 0000:0a:00.0: pmu: firmware unavailable
Dec 08 12:06:03 USB-BootDrv kernel: nouveau 0000:0a:00.0: gr: firmware unavailable
Dec 08 12:06:03 USB-BootDrv kernel: nouveau 0000:0a:00.0: sec2 ctor failed: -38
Dec 08 12:06:03 USB-BootDrv kernel: nouveau: probe of 0000:0a:00.0 failed with error -38
Dec 08 12:06:03 USB-BootDrv kernel: ------------[ cut here ]------------

lspci probes run on working booted system:

Sun Dec 11 11:45:30 AM PST 2022

lspci -v | grep -Ei VGA
0a:00.0 VGA compatible controller: NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1) (prog-if 00 [VGA controller])

lspci -vs 0a:00.0
0a:00.0 VGA compatible controller: NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. Device 85f4
	Flags: bus master, fast devsel, latency 0, IRQ 93, IOMMU group 14
	Memory at fb000000 (32-bit, non-prefetchable) [size=16M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	Memory at e0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at f000 [size=128]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: nouveau
	Kernel modules: nvidiafb, nouveau

**Comment by sbharvey** [comment]
date: Mon Dec 18 10:43:49 AM PST 2023
Current versions of relevant software.   Issued with video driver problem are solved.

swupd  info ; echo ""; uname -a ; echo ""; samba -V ; echo "";  krb5-config --all
Distribution:      Clear Linux OS
Installed version: 40030
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

Linux netserver03 6.5.5-1366.native #1 SMP Sat Sep 23 02:49:28 PDT 2023 x86_64 GNU/Linux

Version 4.18.5

Version:     Kerberos 5 release 1.21.2
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr

**Comment by sbharvey** [comment]
Versions documented in previous post do not have the issues documented by this bug report problem solved...
