### ISSUE TITLE
xdg-open (and other XDG tools) missing

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#278]
**Describe the bug**
```
$ xdg-open
bash: xdg-open: command not found
```

Many scripts assume the XDG tools to be present on any desktop system.

**To Reproduce**
1. Install the XFCE desktop
2. open `xfce-terminal`
3. open `xdg-open`
4. Try to close it

**Expected behavior**
`xdg-open` should be expected to be present on every desktop system.

**Environment (please complete the following information):**

```
user@clr-... ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

user@clr-... ~ $ sudo swupd bundle-list
Password: 
bootloader
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
editors
emacs
ethtool
iproute2
joe
kernel-native
libX11client
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
python3-basic
sudo
sysadmin-basic
vim
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop
```

**Comment by fenrus75** [comment]
+Kok, Auke-jan H <auke-jan.h.kok@intel.com> we need to think this one
through; os-utils-gui has all the xfce4 tools including xdg-open, but
xfce4-desktop does not...  should we extend xfce4-desktop ? make a
desktop-xfce4 that's more complete?

**Comment by probonopd** [comment]
Make `*-desktop` depend on `os-utils-gui`?

**Comment by ahkok** [comment]
Took me a while. Added the needed utils to `xfce4-desktop`. This is still pretty bare bones - e.g. `x11server` isn't part of `xfce4-desktop` meaning it could be useful for remote display activites.
