### ISSUE TITLE
Smart Card / Common Access Card Support Working!

### ISSUE THREAD

**Issue by greysonofusa** [clearlinux/distribution#2782]
Clear Linux does not currently support smart cards. This is difficult for users that need to connect to the Dept of Defense Email systems and use microsoft teams based web applets that require a common access card sign in.

Please add packages to your official or third party repository such as:
pcsc-ccid
pcsc-tools
perl-pcsc
perl-pcsc
OpenSC
gscriptor

**Comment by bwarden** [comment]
I started looking into this and adding some of the packages. The card drivers are part of OpenSC. One of the dependencies of OpenSC is openpace, which doesn't seem to compile against OpenSSL 3.0. The upstream project may need some help to fix that.

**Comment by bwarden** [comment]
I was able to get the latest, *unreleased* code from openpace to build against OpenSSL 3.0, so I've put together a bundle with hopefully enough to get started. If we don't run into issues, you could see a `smartcard` bundle in a few releases.

**Comment by greysonofusa** [comment]
> I was able to get the latest, _unreleased_ code from openpace to build against OpenSSL 3.0, so I've put together a bundle with hopefully enough to get started. If we don't run into issues, you could see a `smartcard` bundle in a few releases.

bwarden,
Thank you for responding and for your efforts in building against Open SSL 3.0. This is great news as a user of clear linux for years. It is still by far my favorite distro and is my daily driver. This will hopefully allow me and my colleagues to use it at work.

**Comment by greysonofusa** [comment]
Let me know if you need me to test functionality of smart cards. 
I have used this guides in the past and I have gotten it working with arch and Fedora
https://wiki.archlinux.org/title/Smartcards.

**Comment by bwarden** [comment]
> Let me know if you need me to test functionality of smart cards.

Please do and let us know how it goes. We don't have any hardware (readers or cards) on hand.

**Comment by greysonofusa** [comment]
Brett,

I tested it with my cac and yes it works!!! Thanks so much!

**Comment by greysonofusa** [comment]
> > Let me know if you need me to test functionality of smart cards.
> 
> Please do and let us know how it goes. We don't have any hardware (readers or cards) on hand.

Smart Card 100% works in Firefox after loading the security device. Will try with chrome based browsers next.

Thank you so much for your development efforts! I will finally be able to use CL at work!

**Comment by greysonofusa** [comment]
Update! I was able to get DOD smart cards working with google chrome via install from terminal. Chromium based browsers installed via flatpak are another story.

**Comment by bwarden** [comment]
Might be a jumping-off point for flatpak support (see other linked issues in comments): https://github.com/flatpak/flatpak/issues/4723
