### ISSUE TITLE
dkms false-positive error, since 37740, installing kernel module the first time

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2792]
I met to submit an issue at the time and remembered today.

37740 change log:
```text
dkms  3.0.8-22  ->  3.0.9-23
```

I now pass the `--force` argument to dkms to rid of the false-positive. For the NVIDIA installer, I now output standard-error output to `/dev/null` to rid of the false-positive. dkms worked wonderfully before.

```text
-> Would you like to register the kernel module sources with DKMS? This will allow DKMS to automatically build a new module, if your kernel changes later. (Answer: Yes)
-> Registering the kernel modules with DKMS:
ERROR: Failed to run `/usr/bin/dkms install --no-depmod -m nvidia -v 520.61.05 -k 5.15.84-27.lts2021`:
nvidia.ko:
Running module version sanity check.
Module version 520.61.05 for nvidia.ko
exactly matches what is already found in kernel 5.15.84-27.lts2021.
DKMS will not replace this module.
You may override by specifying --force.
   
nvidia-uvm.ko:
Running module version sanity check.
Module version 520.61.05 for nvidia-uvm.ko
exactly matches what is already found in kernel 5.15.84-27.lts2021.
DKMS will not replace this module.
You may override by specifying --force.
   
nvidia-modeset.ko:
Running module version sanity check.
Module version 520.61.05 for nvidia-modeset.ko
exactly matches what is already found in kernel 5.15.84-27.lts2021.
DKMS will not replace this module.
You may override by specifying --force.
    
nvidia-drm.ko:
Running module version sanity check.
Module version 520.61.05 for nvidia-drm.ko
exactly matches what is already found in kernel 5.15.84-27.lts2021.
DKMS will not replace this module.
You may override by specifying --force.
    
nvidia-peermem.ko:
Running module version sanity check.
Module version 520.61.05 for nvidia-peermem.ko
exactly matches what is already found in kernel 5.15.84-27.lts2021.
DKMS will not replace this module.
You may override by specifying --force.
Error! Installation aborted.
-> Error.
WARNING: Failed to register the NVIDIA kernel modules with DKMS. The NVIDIA kernel modules were installed, but will not be automatically rebuilt if you change your kernel.
```

Fortunately, the NVIDIA installer continues to completion and exits with a status of 0. The automation script subsequently runs dkms with the `--force` argument.

**Comment by marioroy** [comment]
The `/usr/bin/dkms-new-kernel.sh` script, without the `--force` argument, works fine when a new kernel is installed. The false-positive occurs the first time installing the kernel module.

**Comment by marioroy** [comment]
This too, is a false-positive in the NVIDIA installer log.
```text
WARNING: Failed to register the NVIDIA kernel modules with DKMS. The NVIDIA kernel modules were installed, but will not be automatically rebuilt if you change your kernel.
```

The NVIDIA modules are re-built during `swupd update` when a new kernel is installed. No issues with `/usr/bin/dkms-new-kernel.sh`.

**Comment by marioroy** [comment]
The issue persists in CL 37850. The NVIDIA driver automation succeeds regardless, described above.

Off-topic: I typically close my issues immediately to rid of the silent treatment. Creating issues is the last thing I want to do. Maintaining the "nvidia-driver-on-clear-linux" as well. I will re-release the repository once CL 37850 or a later CL release becomes current.

Blessings and Grace

**Comment by cr0wg4n** [comment]
fedora 6.1.12-200.fc37, same issue

**Comment by fenrus75** [comment]
Something is VERY wrong in your report there since we havent had a kernel
version starting with a 4 in a long time, and even kernel versions with a 5
are well behind us (except for the LTS-1 release)
Are you sure the clr-boot-manager agent is working correctly?

**Comment by ddsmith2-eprod** [comment]
My bad, you are correct.  I found this post with Google and thought this issue tracker was for dkms.  My OS is RHEL so you can just ignore my response.
