### ISSUE TITLE
Update to more current CL release at https://clearlinux.org/downloads

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2793]
No problem if that is not possible at this time. The reason is that `swupd update` breaks the NVIDIA driver installation, [fixed in CL 36740](https://github.com/clearlinux/distribution/issues/2690). The [downloads](https://clearlinux.org/downloads) page points to CL 36010.

I will note in the [README](https://github.com/marioroy/nvidia-driver-on-clear-linux) to install-or-update to a recent CL release before installing the NVIDIA driver. Unfortunately, many folks install CL 36010 not knowing to obtain a recent CL release. [Merlin](https://en.wikipedia.org/wiki/Merlin), the magician, is no longer with us. So, tricky choosing a release that is stable with regards to Mesa.

**Comment by bryteise** [comment]
@djklimes mind prodding the download page?

**Comment by marioroy** [comment]
There is a [regression](https://github.com/clearlinux/distribution/issues/2797) with CL 37850 using AMD graphics.

**Comment by marioroy** [comment]
No X on my Intel NUC box. I wished I had taken the time to test on the NUC, which I barely use. :(

**Comment by marioroy** [comment]
Confirmed the undefined symbols resolved in CL 37860; on an Intel NUC box and an AMD desktop using NVIDIA proprietary driver.

**Comment by djklimes** [comment]
Updated downloads to 37860
