### ISSUE TITLE
Many rcu_sched detected expedited stalls running Kernel 6.* and NVIDIA driver

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2795]
https://termbin.com/pwakm

I'm not sure if this is isolated to my machine. The NVIDIA graphics appears to work fine (desktop and all) running the native kernel.

In the README file, I will mention not recommended running the native kernel. However, no issues on Fedora 37 running Kernel 6.0.* or 6.1.* and NVIDIA proprietary 520 or 525 drivers.

**Comment by dasouza** [comment]
I'm seeing the same rc_sched messages and I'm using an AMD gpu so this is probably unrelated to the NVIDIA driver.

**Comment by marioroy** [comment]
I experienced the following today using the live ISO image. I booted into run-level 3, via passing "3" to kernel options.
```text
rcu: INFO: rcu_sched detected expedited stalls on CPUs/tasks: { 2-.... } 21 jiffies s: 1137 root: 0x1/.
rcu: blocking rcu_node structures (internel RCU debug): l=1:0-15:0x4/.
rcu: INFO: rcu_sched detected expedited stalls on CPUs/tasks: { 2-.... } 21 jiffies s: 1141 root: 0x1/.
rcu: blocking rcu_node structures (internal RCU debug): l=1:0-15:0x4/.
```

**Comment by original-tinozza** [comment]
Same here with AMD gpu on an Intel cpu.
I even tried to fine tune the "RCU stall detector" without success. [here](https://www.kernel.org/doc/Documentation/RCU/stallwarn.txt) a good starting point.

**Comment by marioroy** [comment]
I compared rcupdate against Clear Linux Kernel 6.1.1 and Fedora 37 Kernel 6.0.14.

Clear Linux:  `rcupdate.rcu_exp_cpu_stall_timeout=20`

Fedora 37: `rcupdate.rcu_exp_cpu_stall_timeout=21000`

The following rids of the `rcu_sched detected expedited stalls` kernel messages.

```bash
sudo mkdir -p /etc/kernel/cmdline.d
sudo tee /etc/kernel/cmdline.d/rcupdate.conf >/dev/null <<'EOF'
rcupdate.rcu_exp_cpu_stall_timeout=21000
EOF
sudo clr-boot-manager update
```

I also compared rcutree against Clear Linux and Fedora 37.

Clear Linux 2-core box: `rcutree.rcu_nocb_gp_stride=2`
Clear Linux 32-core box: `rcutree.rcu_nocb_gp_stride=11`

Fedora 37: `rcutree.rcu_nocb_gp_stride=-1`

That is all the differences (rcupdate and rcutree) I saw comparing Clear Linux 6.1.1 against Fedora 37 6.0.14.

**Comment by marioroy** [comment]
Re: [PATCH 1/1] rcu: Introduce CONFIG_RCU_EXP_CPU_STALL_TIMEOUT
https://www.spinics.net/lists/rcu/msg07073.html

The default `20` milliseconds is too low. Fedora 37 configures `rcu_exp_cpu_stall_timeout` to the maximum value `21000`. Vlad Rezki, in a follow up [post](https://www.spinics.net/lists/rcu/msg07079.html) mentions, "There will be needed an addition adjustment later on to find some better floor value."

**Comment by marioroy** [comment]
@fenrus75

Several systems experience rcu_sched stalls. This is unrelated to the NVIDIA proprietary driver.

Does the 6.x kernel `CONFIG_RCU_EXP_CPU_STALL_TIMEOUT` parameter need changing from default `20` milliseconds to `0` or a greater value? From kernel [patch](https://patchwork.kernel.org/project/linux-crypto/patch/20221006223151.22159-2-elliott@hpe.com/), "A zero value causes the CONFIG_RCU_CPU_STALL_TIMEOUT value to be used, after conversion to milliseconds, limited to maximum of 21 seconds."

From Fedora rawhide kernel [config](https://src.fedoraproject.org/rpms/kernel/blob/rawhide/f/kernel-x86_64-fedora.config).
```text
CONFIG_RCU_EXP_CPU_STALL_TIMEOUT=0
```

**Comment by marioroy** [comment]
Thanks. This issue is resolved in Clear Linux 37940.
