### ISSUE TITLE
Uninstalling a kernel leaves artifacts in /boot, /var/lib/kernel, and /var/lib/dkms

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2796]
I subsequently tried the Native 6.1 kernel and now want to remove it. But artifacts remain.

Steps to reproduce:

1. Install Clear Linux choosing the LTS Kernel during installation
2. Reboot and install kernel-native and kernel-native-dkms via swupd
3. /boot, /lib/modules, and /var/lib/kernel have LTS and Native kernels
4. Uninstall kernel-native-dkms, linux-dev, and kernel-native via swupd
5. Native is removed from /lib/modules, but artifacts exists in /boot and /var/lib/kernel

Is there a clean way to properly uninstall a kernel and not leave artifacts? I removed the artifacts manually.

1. /var/lib/kernel/k_booted_6.1.1-1228.native
2. /boot/EFI/org.clearlinux/kernel-org.clearlinux.native.6.1.1-1228
3. /boot/loader/entries/Clear-linux-native-6.1.1-1228.conf
4. Verify /boot/loader/loader.conf defaulting to LTS or other kernel (not the one which was removed)

In addition, I removed artifacts in /var/lib/dkms.

1. /var/lib/dkms/nvidia/kernel-6.1.1-1228.native-x86_64
2. /var/lib/dkms/nvidia/520.61.05/6.1.1-1228.native

**Comment by bryteise** [comment]
Unfortunately there isn't a way to do the remove without manual intervention. I am investigating adding a `remove-kernel` option for clr-boot-manager to use (and in theory `swupd bundle-remove` could reuse that).

**Comment by bryteise** [comment]
Should be able to use the `clr-boot-manager remove-kernel` command with the next release or so.

**Comment by marioroy** [comment]
Not well thought out, unfortunately. I uninstalled the `kernel-native` bundle first before running the `clr-boot-manger remove kernel`. In other words, the `remove-kernel` option is of no use.

Should `swupd bundle-remove kernel-native` call the `clr-boot-manager` utility. Else, one must call the utility before running clr-boot-manager remove kernel. Have I done the steps backwards - lol?

**Comment by bryteise** [comment]
Yea, until I figure out a way for `bundle-remove` to correctly identify the kernels it should remove, running `clr-boot-manager remove-kernel` and then `swupd bundle-remove` is the only order that would work.

**Comment by bryteise** [comment]
As an aside you should be able to `swupd bundle-add` the kernel back and redo the `clr-boot-manager remove-kernel` and then `swupd bundle-remove again` to remove the contents from `/boot` and `/usr/lib`.

**Comment by marioroy** [comment]
All is well. I removed the artifacts manually and tried again.

> running clr-boot-manager remove-kernel and then swupd bundle-remove is the only order that would work

Confirmed working. :)

**Comment by marioroy** [comment]
For NVIDIA user's, I have a [check-kernel-dkms](https://github.com/marioroy/nvidia-driver-on-clear-linux/blob/main/check-kernel-dkms) script in the repo. That installs the NVIDIA kernel modules via dkms. The script ensures the NVIDIA driver exist, else builds-installs the modules with ease.

**Comment by marioroy** [comment]
This is working as described above, by bryteise. Thank you.

**Comment by bryteise** [comment]
Was that using `clr-boot-manager remove-kernel` that left behind the initrds?

**Comment by thiagomacieira** [comment]
No, just normal swupd updates.

**Comment by bryteise** [comment]
Are only the initrds being left behind after it looks like you `swupd bundle-remove`'d the lts and mainline kernels (I don't know how they'd have been installed otherwise)?

**Comment by marioroy** [comment]
I used the option today and works great. What a relief not having to go into the boot partition and remove artifacts by hand. Thank you, @bryteise.
