### ISSUE TITLE
37810: VMWare/Virtualbox Kernel Modules fail to compile: __x86_indirect_thunk undefined

### ISSUE THREAD

**Issue by wheerdam** [clearlinux/distribution#2798]
Since version 37810, VMware workstation 17 and Virtualbox 6.x/7.0 kernel modules failed to compile during modpost with __x86_indirect_thunk undefined error.

37780 is the last version I was able to compile their kernel modules with kernel 6.1.0-1221

**Comment by fenrus75** [comment]
hmmm we had a report that the x850 build had this fixed

**Comment by fenrus75** [comment]
https://github.com/clearlinux/distribution/issues/2791#issuecomment-1362442708
for cross reference

**Comment by wheerdam** [comment]
Ah, okay, I'm unable to use 37850 right now because of the Xorg amdgpu problem. Once I can confirm it fixed I'll close this bug.

**Comment by wheerdam** [comment]
Confirmed fixed in 37850
