### ISSUE TITLE
Special keys on keyboard do not work

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#280]
**Describe the bug**
Special keys (e.g., multimedia: volume up, volume down) on an attached Apple USB keyboard do not work.

**To Reproduce**
1. Attach an Apple USB keyboard and launch Xfce
2. Press the "volume up" key (may need to press it while holding down the "fn" key as well)
3. No result (on e.g., Ubuntu it works) 

**Expected behavior**
Volume goes up and an overlay on the screen informs you about this.

**Screenshots**

Something like this (note that I did not take this screenshot in an actual Xfce session but Xfce has something like this:)

![](https://user-images.githubusercontent.com/2480569/48313859-e21c0e00-e5b9-11e8-99bc-fc28d28cfd0a.jpg)

**Environment (please complete the following information):**

```
user@clr-... ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

user@clr-... ~ $ sudo swupd bundle-list
Password: 
bootloader
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
editors
emacs
ethtool
iproute2
joe
kernel-native
libX11client
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
python3-basic
sudo
sysadmin-basic
vim
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop

```

**Comment by ahkok** [comment]
that's a gnome thing overlaid over xfce, I'm fairly sure (that's how the gnome volume changes show). I do not think we want to start gnome services in the Xfce4 desktop, by default, but it is possible - just go to the xfce4 autostart applications and services setup panel, and you should be able to enable most and get this to work.

Please try this, and let us know.

**Comment by iphutch** [comment]
@ahkok - how far do we go with xfce given Gnome is our primary desktop experience?

**Comment by probonopd** [comment]
@iphutch please make it top-notch (like the rest of your distribution) or drop it entirely. Providing something half-baked is not going to give users the positive impression this project deserves.
(By the way, the reason I tried Clear Linux in the first place was https://clearlinux.org/blogs/clarity-desktop - I don't think Gnome fits the bill described there particularly well, but certainly not better than Xfce.)

**Comment by ahkok** [comment]
Closing this. We'd fix this on GNOME if it doesn't work, since it is an included upstream feature. But afaict Xfce doesn't have any solution, and I do not have the bandwidth to make custom changes to it (and all other non-default desktops).

We mostly ship them as-is.

If there's an easy "add this thing" change, I'd be happy to merge or enable it. But from what I can see, that is not the case here (correct me if I'm wrong though).

**Comment by probonopd** [comment]
What I can say is that in Xfce on Xubuntu it works out of the box.
