### ISSUE TITLE
(destructive) Installation is failed after deleting all the old partitions

### ISSUE THREAD

**Issue by AbyssWaIker** [clearlinux/distribution#2806]
I boot from ventoy in grub2 mode in laptop HP probook 640 g4

First I thought it's an ssd problem (https://community.clearlinux.org/t/clear-linux-isnt-installing-on-nvme-solved/7915) but changing usb boot options + kernel to lts version didn't lead to succesful instalation

Then assumed it's a ventoy problem, checked compatibility. The latest succesfuly tested release was 36010. So I tried to use it instead of the latest (37860) but that also wasn't a succes.

To check "is this usb software side problem or laptop hardware side problem?" tried installing linux mint. It was installed successfully.

But clear linux is failing to install each time
 
I hope the log file will help to figure out the real roadblock
[clr-installer.log](https://github.com/clearlinux/distribution/files/10328925/clr-installer.log)

**Comment by bryteise** [comment]
Is that log from 37860? Looks like the loop device name is corrupt (which should be fixed in 37960+) if you can try and install from the server [image](https://download.clearlinux.org/image/clear-37960-live-server.iso).

**Comment by AbyssWaIker** [comment]
That was actually a log from 36010 since I was getting kinda desperate and posted whatever I had at the moment 

Your image still worked and was installed properly

Thank you
