### ISSUE TITLE
Firewalld not working in clear-37960-live-server releases

### ISSUE THREAD

**Issue by GithubServers** [clearlinux/distribution#2807]
FirewallD is not running
--------------------------
guests@Server~ $ sudo systemctl status firewalld.service
× firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2023-01-02 21:33:02 CST; 1min 27s ago
   Duration: 169ms
       Docs: man:firewalld(1)
    Process: 235 ExecStart=/usr/bin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=1/FAILURE)
   Main PID: 235 (code=exited, status=1/FAILURE)

Jan 02 21:33:00 Server systemd[1]: Starting firewalld - dynamic firewall daemon...
Jan 02 21:33:02 Server systemd[1]: Started firewalld - dynamic firewall daemon.
Jan 02 21:33:02 Server systemd[1]: firewalld.service: Main process exited, code=exited, status=1/FAILURE
Jan 02 21:33:02 Server systemd[1]: firewalld.service: Failed with result 'exit-code'.

**Comment by fenrus75** [comment]
will need to look into this; by default firewalld shouldn't be starting
(we don't listen to ports b default, and users who want firewalld will
need to configure it for what they want)

**Comment by GithubServers** [comment]
@fenrus75 
sudo firewalld --nofork --debug
==456==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
Please tell me how to configure firewalld. Previous versions did not have this problem.
