### ISSUE TITLE
Boot error message - driver 'idxd' unable to register

### ISSUE THREAD

**Issue by mfdemicco** [clearlinux/distribution#2808]
`[    0.416187] Driver 'idxd' was unable to register with bus_type 'dsa' because the bus was not initialized.`

Appears on the console screen before the greeter shows. Happens on every boot since I installed CL some weeks ago. 

```
[    0.416186] calling  idxd_init_module+0x0/0xf6 @ 1
[    0.416187] Platform does not have ENQCMD(S) support.
[    0.416187] Driver 'idxd' was unable to register with bus_type 'dsa' because the bus was not initialized.
[    0.425737] initcall idxd_init_module+0x0/0xf6 returned -22 after 9550 usecs
[    0.425738] calling  dsa_bus_init+0x0/0x1c @ 1
[    0.425740] initcall dsa_bus_init+0x0/0x1c returned 0 after 1 usecs
```

**Comment by luisalvarado** [comment]
Looks like it depends on usb port speed and usb drive speed.

I changed it from the front usb port to the back which has a usb 3.1 and also changed it from a 2.0 usb flash drive to an actual 3.0 one and it booted properly.

But that's my case. Test it yourself wnd and let me know if it works and loads the welcome screen.

**Comment by mfdemicco** [comment]
This seems to be fixed as I'm not seeing this message any more on boot.

**Comment by cpmech** [comment]
This problem persists in clear-37860-live-desktop
