### ISSUE TITLE
Subnormals are zero in Python/Perl

### ISSUE THREAD

**Issue by krdav** [clearlinux/distribution#2809]
I recently updated numpy and found that it was throwing a warning about subnormals when running on Linux Clear (apparently, this warning is a new development).

There was some recent [writing](https://moyix.blogspot.com/2022/09/someones-been-messing-with-my-subnormals.html) about this being due to packages using the `-ffast-math` compiler flag.
However, without any packages imported both python and perl (those preinstalled) has flush to zero behavior as tested by the following both evaluating to 0:
`python -c "print(0.25*(2**-1022))"`
`perl -le "print(0.25*(2**-1022))"`

So it would seem that python/perl have been compiled with the `-ffast-math` or an associated flag causing FTZ. Is this expected behavior under Linus Clear or an error?

**Comment by fenrus75** [comment]
we do use ftz as default for the is (not fastmath as a whole)

**Comment by krdav** [comment]
Thanks for the quick answer, this is good to know.
