### ISSUE TITLE
Use command-not-found to show how to install things

### ISSUE THREAD

**Issue by probonopd** [clearlinux/distribution#281]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to run a (common) command and the system says `bash: hello: command not found`.

**Describe the solution you'd like**
Have the `command-not-found` package installed and set up by default, so that the system tells me which `swupd bundle-add` I have to run to get the missing command installed. Ubuntu does this out of the box, for example:

```
me@host:~$ hello

Command 'hello' not found, but can be installed with:

sudo apt install hello            
sudo apt install hello-traditional
```

**Additional context**
Related to https://github.com/clearlinux/swupd-client/issues/531.

**Comment by ahkok** [comment]
We've agreed that something like this would be helpful, just needs to be done.

**Comment by probonopd** [comment]
Just noticed that there is a command

```
sudo swupd search hello
```

I really wonder why it needs a) so much time b) root

```
user@host ~ $ swupd search hello
This program must be run as root..aborting.
```

**Comment by probonopd** [comment]
The syntax here is somewhat different though; `sudo swupd search hello` does not find executables on the `$PATH` named `hello` (as `command-not-found` would do) but any files with `hello` in their name.

```
user@host ~ $ sudo swupd search /usr/bin/hello
Searching for '/usr/bin/hello'

Search term not found.
```

It's probably close enough in functionality that a `command-not-found` replacement could be cobbled together based on this.

**Comment by fenrus75** [comment]
I have a prototype for the command not found handler .. just need time to
finish

**Comment by puneetse** [comment]
I'm closing this issue because this has since been added by https://github.com/clearlinux-pkgs/cnf
