### ISSUE TITLE
The boot partition fills up over time due to having kernel-lts and kernel-native installed 

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2822]
Given the following scenario, the boot partition will eventually run out of space.

1. Install kernel-lts
2. Install kernel-native and make it the default boot kernel
3. Simulate periodic updates over time

What happens is that the older "native" kernel is removed automatically. Unfortunately, not the lts kernel. This will cause the boot partition to run out of space. It requires manual intervention by the user to remove the older lts kernel.

Is the behavior with `swupd update` working as expected? The older "native" kernel (or boot kernel) is removed automatically, upon reboot. Why not the older "lts" kernel?

**Comment by bryteise** [comment]
None of the lts kernel's get cleaned up? Over the course of say a month you have all the older lts kernels in your /boot?

**Comment by marioroy** [comment]
Correct. Only the boot-kernel is cleaned up. If I set the boot kernel to lts and use that, then the lts kernel is cleaned up over time and not the native one.

**Comment by wheerdam** [comment]
I can confirm this, I've been manually clearing LTS kernels from boot partition for a while after a system update (I'm always on native)

**Comment by fenrus75** [comment]
clearly the logic that is trying to NOT delete things that aren't from
the distro ... is too aggressive in deciding that the LTS kernel isn't
the interesting bits

**Comment by marioroy** [comment]
> is too aggressive in deciding that the LTS kernel isn't
the interesting bits

Or vice versa... If one boots into LTS always and not native, then the old native kernels are not removed.

**Comment by marioroy** [comment]
Oh how nice not having to manually clear artifacts in /boot. :1st_place_medal: Fixed in 38220.

**Comment by marioroy** [comment]
Created part two: https://github.com/clearlinux/distribution/issues/2829

**Comment by bryteise** [comment]
I have some doubts this is fixed as I didn't do anything yet.

**Comment by marioroy** [comment]
> I have some doubts this is fixed as I didn't do anything yet.

That's interesting. I ran swupd update today, which updated native and lts kernels to newer versions. The older lts kernel was removed automatically during the update.
