### ISSUE TITLE
desktop livecd iso image isn't available anymore

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2830]
https://download.clearlinux.org/current/

**Comment by bryteise** [comment]
Seems we had an issue with image creation. It is getting a little too big so I'm trying out removing the c-basic bundle from the live-desktop image.

**Comment by paulcarroty** [comment]
Seems like fixed in 38280.

**Comment by paulcarroty** [comment]
Same story in 38400.

**Comment by marioroy** [comment]
The live-desktop.iso and live-desktop.img are broken since removal of the x11-server bundle. Moreover, the gnome-session attempts x11 as well. The latter can be fixed with the following, but still needs x11-server for some reason.

This will have the clrlinux user default to gnome-wayland.

```bash
# Default to "gnome-wayland" for the clrlinux login session.
sudo mkdir -p   "/var/lib/AccountsService/users"
sudo chown 0700 "/var/lib/AccountsService/users"

userconf="/var/lib/AccountsService/users/clrlinux"
sudo tee "$userconf" >/dev/null <<"EOF"
[User]
Session=gnome-wayland
SystemAccount=false
EOF
```

**Comment by marioroy** [comment]
There was a typo in my prior reply (now fixed); chown was met to be chmod. The following are the steps taken to have a workable live USB image, defaulting to gnome-wayland for the "clrlinux" user.

Insert a USB stick (minimize size 16 GB). Unmount file systems associated with the USB stick, if any.

```bash
sudo umount /dev/sdb1
```

Copy the live desktop image to the USB stick, mount, and chroot.

```bash
xzcat clear-38410-live-desktop.img.xz |\
sudo dd of=/dev/sdb bs=64K conv=fsync oflag=direct status=progress

sudo mount /dev/sdb3 /mnt
sudo mount -t proc /proc /mnt/proc/
sudo mount --rbind /sys /mnt/sys/
sudo mount --rbind /dev /mnt/dev/
sudo cp /etc/resolv.conf /mnt/etc/

sudo chroot /mnt
```

The x11-server is needed or the desktop environment will not work (e.g. xkbcommon failing). Add the x11-server bundle and have GNOME default to gnome-wayland for the clrlinux user.

```bash
swupd bundle-add x11-server

sudo mkdir -p   "/var/lib/AccountsService/users"
sudo chmod 0700 "/var/lib/AccountsService/users"
userconf="/var/lib/AccountsService/users/clrlinux"
sudo tee "$userconf" >/dev/null <<"EOF"
[User]
Session=gnome-wayland
SystemAccount=false
EOF
```

Exit the chroot session and undo the mounts.

```bash
exit

sudo rm /mnt/etc/resolv.conf
sudo umount /mnt/dev
sudo umount /mnt/sys
sudo umount /mnt/proc
```

**Comment by marioroy** [comment]
I updated the steps as umount was failing.

**Comment by AlessandroFasse** [comment]
Are there any attempts to recreate the `clear-XXXXX-live-desktop.iso` in the future? I would really appreciate it

**Comment by marioroy** [comment]
Ping :)

Can someone update the download ISO link to 38640 on the main download page.

https://clearlinux.org/downloads

**Comment by fenrus75** [comment]
we're trying to get to something that works..... few steps to go still it
seems.

also increasingly we need to assess if the purpose is really a "live cd" or
if it's really "the thing you run the gui installer from".. the trend
really is more towards the later just for space reasons, the gui components
have been growing and growing and that's a problem.

**Comment by marioroy** [comment]
The live USB image worked for me. Though, I needed to fix it (steps provided above).

Once having a working USB live image, the experience that I recall was that the OS installation took a long time. Moreover, I needed to run `swupd clean` to free up ~ 3 GB after booting into the newly installed OS.

**Comment by paulcarroty** [comment]
It's very useful as fresh & fast sw/hw playground. 

> growing and growing and that's a problem

Removing unnecessary stuff and junk from `/usr/share/clear/optimized-elf` should fix it.

> installation took a long time

Might be worth trying the offline install (IDK if it works now) to avoid the possible slow mirror problem.

**Comment by marioroy** [comment]
The irony of it all, is how are the Vendors or Open Source developers to try their software on Clear Linux without the means to feasibly install the OS. Hats off to the CL team sorting this all out.

The ISO aside, the live desktop (img) has been broken for some time.

**Comment by marioroy** [comment]
What about a hybrid or text-mode USB image? A blend of the server image containing the desktop packages for fast installation, not having to fetch gigabytes of data over the internet. (installer USB image)

**Comment by fenrus75** [comment]
before we get creative.... we hope to get it to at least function in
the basic known setups.

I do tend to wonder how much the actual "iso" is useful (meaning, how
many people will burn it to a DVD or use it in a place that actually
needs an ISO filesystem that cannot just use the USB image).. I kind
of assume most folks just use USB sticks for physical usage nowadays
(the ISO side is messy -- we solved it before but it remains messy --
because of the read only nature of the iso9660 filesystem)

**Comment by Aqua1ung** [comment]
I've had no problems installing CL using the [last few ISOs](https://cdn.download.clearlinux.org/releases/)--starting with 38640 all the way to 38700.

**Comment by fenrus75** [comment]
may I ask why you used the ISO and not the USB image ? Is there a
specific usage that requires ISO format that we are not understanding?

**Comment by Aqua1ung** [comment]
> may I ask why you used the ISO and not the USB image ? Is there a specific usage that requires ISO format that we are not understanding?

I have had trouble booting .img files with [Ventoy](https://www.ventoy.net/en/index.html), even renamed as .iso. Please issue ISOs for the foreseeable future.
