### ISSUE TITLE
Update to more current CL release at https://clearlinux.org/downloads

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2834]
Clear Linux provides the libglvnd package since 38270. This is great news. The issue is running < 38270 and updating to 38270+ causes the NVIDIA proprietary driver to fail. It requires re-installation of the driver to detect libglvnd.

I updated the README file for the [nvidia-driver-on-clear-linux](https://github.com/marioroy/nvidia-driver-on-clear-linux) repo.

*Starting fresh? Obtain a recent Clear Linux image, 38280 or later, from the [release archive](https://cdn.download.clearlinux.org/releases/). Currently running < 38270 and updating the OS >= 38270? Please refer to the [community article](https://community.clearlinux.org/t/cl-38270-good-news-the-bad-news-and-solution-for-nvidia-graphics/8466) on getting NVIDIA graphics working again.*

The live desktop ISO image is back starting with 38280.

**Comment by marioroy** [comment]
Ping.  Very please, do not forget this issue when having the next good ISO image or as you see fit. At the very least, I mention CL 38280 minimally in the README file.

**Comment by bryteise** [comment]
Should happen next week once the great @djklimes returns.

**Comment by marioroy** [comment]
Ping.
