### ISSUE TITLE
SR-IOV not working in clear-<38320-38340>-live-server releases

### ISSUE THREAD

**Issue by GithubServers** [clearlinux/distribution#2839]
Virt-Manager-gui
VT-x/VT-d intel_iommu=on iommu=pt is turned on
unsupported configuration:host doesn't support passthrough of host pci devices
unsupported configuration: pci backend driver 'default' is not supported
clear-38310-live-server releases is no problem

**Comment by fenrus75** [comment]
I went through all the 6.1->6.2 kernel config changes/new settings and
found that iOMMUFD was not set (a new setting)
I'll try to figure out to to test your use case with the updated kernel
settings

**Comment by GithubServers** [comment]
nouveau 0000:03:00.0: bus: MMIO read of 00000000 FAULT at 3e6684 [ PRIVRING ]
problem is found here

**Comment by GithubServers** [comment]
@fenrus75
Honey, did you find the problem?

**Comment by GithubServers** [comment]
@fenrus75
Honey, did you find the problem?
