### ISSUE TITLE
International Keyboard Layout not Working

### ISSUE THREAD

**Issue by AlessandroFasse** [clearlinux/distribution#2845]
I updated today ClearLinux on my laptop from version `38390` to `38430` and have an issue with my `English (intl. with AltGr dead keys)` keyboard layout. On the previous version (and all versions before that I used) it worked perfectly. As an example, with this layout if I press `AltGr + p` I get the German `ö` and other signs as well. Currently this combination will only output a `p`. 

Any ideas which updates caused this issue and how to fix it?

**Comment by AlessandroFasse** [comment]
Also as a further remark. After I used `swupd repair -m 38390 --force` the keyboard layout works again.

**Comment by thiagomacieira** [comment]
Looking at /usr/share/X11/xkb/symbols/us for layout "altgr-intl", I don't see anything on the p key. Maybe this is an upstream change? https://cgit.freedesktop.org/xkeyboard-config/log/symbols/us shows a lot of recent changes, but I don't see changes affecting "altgr-intl".

In any case, changes to those files should affect system-wide, not just a few applications.

**Comment by AlessandroFasse** [comment]
I can confirm that the problem is resolved in version `38520`
