### ISSUE TITLE
Multiple refreshes needed before Installer recognized Update Server

### ISSUE THREAD

**Issue by jfstroman** [clearlinux/distribution#285]
Installer claims the update server is not available (connection cannot be established, install will fail).   I had to “refresh” several times before it recognized a connection.  Perhaps the timeout is set too short for installs in Asia…

**Comment by ahkok** [comment]
Most likely obsolete as the whole installer will be replaced with a new gen installer soon.

**Comment by ahkok** [comment]
@mdhorn do you want to check that the new installer has adequate timeouts for checking?

**Comment by mdhorn** [comment]
The new installer has a 5 second timeout on requests; which is almost twice as long as ister was using.
We could extend it if ncessary.

**Comment by iphutch** [comment]
When the new installer is live, can you let the submitter know so they can test
