### ISSUE TITLE
typo in qt6 paths

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2858]
https://github.com/clearlinux-pkgs/qt6base/blob/5b979edf3c3e9d22820e15c10b1ce77141713e22/cmake_args#L19

**Comment by fenrus75** [comment]
ok I think I spotted the typo (but it's pre-coffee time in the morning)
fixed by adding a space and redoing the automation

**Comment by fenrus75** [comment]
thanks for the report!

**Comment by paulcarroty** [comment]
☕🍵
