### ISSUE TITLE
install doesn't when I selected any non-default packages

### ISSUE THREAD

**Issue by jfstroman** [clearlinux/distribution#286]
During actual install, notifications of packages being installed scrolled off the bottom of the screen, thereby making it impossible to see install progress (or lack thereof).  A simple progress bar would be more useful.  Also, I never actually got an install to work correctly when I selected *any* non-default packages (see 3).

**Comment by iphutch** [comment]
Does the new installer fix this already?

**Comment by mdhorn** [comment]
The new installer only uses progress bars.
