### ISSUE TITLE
Upgrade podman 4.3.1 -> 4.4.3

### ISSUE THREAD

**Issue by melanopsis** [clearlinux/distribution#2860]
Please upgrade podman from 4.3.1 to 4.4.3.

https://github.com/containers/podman/releases/tag/v4.4.3

Thank you.

**Comment by melanopsis** [comment]
It looks like there is a new patch release https://github.com/containers/podman/releases/tag/v4.4.4.

**Comment by fenrus75** [comment]
Date:   Mon Mar 27 23:13:00 2023 +0000

    podman: Autospec creation for update from version 4.4.3 to version 4.4.4

already done )

**Comment by melanopsis** [comment]
Thanks a bunch!
