### ISSUE TITLE
qt libs in audio-pipewire and ceph bundles

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2862]
AFAIR both are far away from graphics:

```
 swupd search-file /usr/lib64/libQt5Core.so
...
Bundle audio-pipewire (2671 MB to install)
	/usr/lib64/libQt5Core.so.5.15.2
	/usr/lib64/libQt5Core.so.5.15
	/usr/lib64/libQt5Core.so.5

Bundle ceph (1643 MB to install)
	/usr/lib64/libQt5Core.so.5.15.2
	/usr/lib64/libQt5Core.so.5.15
	/usr/lib64/libQt5Core.so.5
```

**Comment by fenrus75** [comment]
I'll take a look.. but ceph drags in half the world (sadly)  .. but if
nothing else can use an include()
pipewire is more minimal so should be solvable

**Comment by fenrus75** [comment]
for audio-pipewire, qt is pulled in by the avahi extras, which is
pulled in by avahi-lib (!!) which is pulled in by pipewire-lib

avahi-lib shouldnt pull in extras, but also probably pipewire
shouldn't pull in avahi; poking

**Comment by fenrus75** [comment]
ceph issue was in the "thrift" package which has QT bindings but those
weren't in optional parts
(it also had some other fun gunk)

**Comment by paulcarroty** [comment]
More bundles with qt5 core library:

- clr-installer (depends on gtk3, maybe also avahi-related?)
- file-roller (gtk3 or gtk4, the default GNOME app)

These two related to ceph/pipewire:
- kvm-host
- xdg-desktop-portal
