### ISSUE TITLE
Upgrade linux-aws to the latest LTS - 6.1.x

### ISSUE THREAD

**Issue by melanopsis** [clearlinux/distribution#2863]
Please consider upgrading `linux-aws` from 5.15.x to 6.1.x. 

Thank you.

**Comment by coolydudey60** [comment]
Hi, are there any updates you can share about this upgrade?

**Comment by melanopsis** [comment]
Hi @fenrus75, any news on this?

**Comment by fenrus75** [comment]
ok update done, should be in the next build assuming it passes QA

**Comment by melanopsis** [comment]
Thank you @fenrus75. I can see that 6.1 is now available.
