### ISSUE TITLE
Downloading 5172 files, but 4861 files were not in a pack... Bug?

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2864]
Hi. I have been wondering about swupd downloading many files, only to report most of them were not in a pack. What does it mean? Thanks.

```text
Statistics for going from version 38640 to version 38680:

    changed bundles   : 79
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 7962
    new files         : 1107
    deleted files     : 657

Validate downloaded files
 [100%]

Starting download of remaining update content. This may take a while (5172 files)...
 [100%]

Installing files...
 [100%]

Update was applied
Calling post-update helper scripts
External command: pacdiscovery.service: restarted (the binary was updated)
External command: tallow.service: restarted (the binary was updated)
External command: pacrunner.service: restarted (the binary was updated)
External command: systemd-journald.service: restarted (the binary was updated)
External command: systemd-resolved.service: restarted (the binary was updated)
External command: (Took 7 seconds)
External command: systemd-timesyncd.service: restarted (the binary was updated)
Update took 137.7 seconds, 491 MB transferred
4861 files were not in a pack
Update successful - System updated from version 38640 to version 38680
```

**Comment by fenrus75** [comment]
it means that for your A->B we did not have a premade pack (tar file) but
swupd fell back to individual files to download... not a functional thing
but could be a performance thing

(we make these packs a few versions back but not infinite)

**Comment by marioroy** [comment]
Thanks for clarifying.

**Comment by marioroy** [comment]
Wow! I'm seeing a big increase in file sizes between 38640 and 38700. The increase is 153% just for gnome-terminal.

**Before:**
```text
$ ls -l /data1/backup/usr/bin/gnome-* | grep -v '>' | wc -l
30

$ ls -l /data1/backup/usr/bin/gnome-* | grep -v '>' | awk '{ t = t + $5 } END { print t }'
16231236

$ ls -l /data1/backup/usr/bin/gnome-terminal 
-rwxr-xr-x 1 root root 101728 Feb  1  2019 /data1/backup/usr/bin/gnome-terminal

$ du -sb /data1/backup/usr
12334067035	/data1/backup/usr
```

**After:**
```text
$ ls -l /usr/bin/gnome-* | grep -v '>' | wc -l
30

$ ls -l /usr/bin/gnome-* | grep -v '>' | awk '{ t = t + $5 } END { print t }'
20240823

$ ls -l /usr/bin/gnome-terminal
-rwxr-xr-x 1 root root 155568 Feb  1  2019 /usr/bin/gnome-terminal

$ du -sb /usr
13182646074	/usr
```

I'm trying to understand why the fps dropped significantly between 38640 and 38690 running a demo glxspheres64 from [VirtualGL](https://virtualgl.org/) 3.1 rpm. Before 7,300 fps; After 4,800 fps. So, I made a backup before updating to 38700.

**Comment by marioroy** [comment]
I'm back to 38640 for the time being. The performance loss is puzzling. Nothing stands out. I even re-installed the NVIDIA driver 525, also tried 530. All looks okay with regards to Mesa / NVIDIA files. I will try a complete OS installation in the near future.

Side note: I'm not sure if it has something to do with the OS at GNOME 44 and the 3rd-party having older libs. I use the kitty terminal application from 3rd-party. But the glxspears64 demo is installed in /opt/VirtualGL. The GNOME 44 update should not have affected that. Before 7,300 fps; after 4,800 fps. 

I have only the default environment variables set. Nothing out of the ordinary, nor is LD_LIBRARY_PATH set. /opt/cuda/bin is on the end of the PATH env.

**Comment by marioroy** [comment]
It's not related to NVIDIA graphics. I created 38640 and 38700 live desktop ISOs onto USB sticks to factor out NVIDIA graphics. The performance lost also occurs using Intel graphics on an Intel NUC box.

How I tested: Boot into the live ISO image. The OS installation is not required. I copied over [VirtualGL](https://virtualgl.org/) from my desktop machine after enabling Wi-Fi connection via GNOME settings.

```text
cd /tmp
scp mario@192.168.1.34:/usr/bin/rsync .
./rsync -aH mario@192.168.1.34:/opt/VirtualGL/ VirtualGL/

vblank_mode=0 ./VirtualGL/bin/glxspheres64
```

Intel Graphics:
```text
38640:  700 fps
38700:  530 fps
```

**Comment by marioroy** [comment]
Okay, GNOME 44 mutter may be running with higher priority. Please disregard the performance lost.

Ensuring steady frame rates with GPU-intesive clients
https://blogs.gnome.org/shell-dev/2023/03/30/ensuring-steady-frame-rates-with-gpu-intensive-clients/

Phew! The performance lost is just something I noticed. And now found the reason, possibly. And it makes perfect sense.
