### ISSUE TITLE
Install using "Desktop-Autostart" -- Install works but desktop does not start

### ISSUE THREAD

**Issue by jfstroman** [clearlinux/distribution#287]
When selecting "desktop-autostart" during install, the install seemed to work, but, the desktop would not start (the login screen showed up, but after typing in a correct password, it seemed the desktop startup crashed and it dumped me back to the login screen).   I was able to log in via a text console, so the install seems to otherwise have worked.  This does not seem to be a graphics issue, since if I did NOT select install of this package (or any other…) during install, but installed “desktop” after install and did “sudo systemctl enable gdm” manually, it worked fine.   I did not try installing “desktop-autostart” after (my next) install, so I’m not sure it was the installer or the bundle that was the problem.

**Comment by tpleavitt** [comment]
@jairglez , please reproduce and if unable to please close

**Comment by jairglez** [comment]
Not able to reproduce the issue after testing on two different machines with the following configuration:

Clear Version: 28390
**Tested use cases:**
- Selecting to install the desktop-autostart bundle and not configuring an user from within the installer. **Result:** GDM started correctly and the gnome-initial-setup wizard was launched automatically.
- Selecting to install the desktop-autostart bundle and configuring an user from within the installer. **Result:** GDM started correctly and the login screen was shown with the configured user in the user list.

**Comment by farazmir** [comment]
I downloaded the HyperV disk image (clear-29450-hyperv) and setup a VM. Then i installed desktop-autostart and rebooted but i never see the gnome-initial-setup wizard launch. Is this a bug or am i missing something?

**Comment by miguelinux** [comment]
> I downloaded the HyperV disk image (clear-29450-hyperv) and setup a VM. Then i installed desktop-autostart and rebooted but i never see the gnome-initial-setup wizard launch. Is this a bug or am i missing something?
> 

It is launched when a user is not created.

So, currently you don't have a non-root user.

**Comment by farazmir** [comment]
i did create a not root user :( let me delete and retry

**Comment by farazmir** [comment]
ok that didnt work
I even started with a fresh hyperv image. logged in to root, installed desktop-autostart and reboot. it still keeps asking me for login in shell

**Comment by tpleavitt** [comment]
@farazmir , do a ```cat /etc/passwd``` file so I know what your users are.  In your previous message you said you started with a fresh hyperv image and logged into root and installed desktop-autostart.  Do you have a user that is not root but is a member of the wheel group?  If so, type ```groups``` to let me know what groups your user is associated with.

**Comment by dougal83** [comment]
Hey @tpleavitt 
I think that I have just run into the same issue.  I've used HyperV image, booted, login as root > set new password > installed desktop bundle and desktop-autostart bundle and have no joy after restart(prompted for login as before).

Quite unimpressed at the moment... I hope it is just me being a fool.

Answers to your queries:
`cat /etc/passwd` -> `cat: /etc/passwd: No such file or directory`
`groups` -> `root`

Grateful for any advice that you can offer.  Might it be best to drop the HyperV image and install manually?

**Comment by jairglez** [comment]
@dougal83, I've reproduced your issue using a clear-32310-hyperv.vhdx image. To be able to install desktop-autostart, though, I had to extend the image size using the Hyper-V disk manager, parted and resize2fs. Could you confirm if you had to use a similar approach to achieve this?

Regarding the desktop not starting automatically, I could confirm that /dev/dri/card0 was not present, indicating a missing video driver in the hyperv kernel. I've created a new issue item to document this: https://github.com/clearlinux/distribution/issues/1742

**Comment by dougal83** [comment]
> @dougal83, I've reproduced your issue using a clear-32310-hyperv.vhdx image. To be able to install desktop-autostart, though, I had to extend the image size using the Hyper-V disk manager, parted and resize2fs. Could you confirm if you had to use a similar approach to achieve this?
> 
> Regarding the desktop not starting automatically, I could confirm that /dev/dri/card0 was not present, indicating a missing video driver in the hyperv kernel. I've created a new issue item to document this: #1742

Hey @jairglez, Thank you for the reply.

- Attached fresh image above and expanded to 40GB.
- Followed your lead ([expanded image](https://docs.01.org/clearlinux/latest/guides/maintenance/increase-virtual-disk-size.html)).. not sure how that was meant to known otherwise.
- Added bundle `sudo swupd bundle-add desktop-autostart`
- Then `reboot` followed by a few blinks and scratch of the head as the original prompt returned.

What am I missing?  Please refer me to a new user guide by all means! 👍
