### ISSUE TITLE
UI crash --releases 38750-38800

### ISSUE THREAD

**Issue by GithubServers** [clearlinux/distribution#2872]
1.Firefox startup crash
2.Settings crash

**Comment by GithubServers** [comment]
@fenrus75
Is this related to the default use of cgroupfs v2?

**Comment by GithubServers** [comment]
@fenrus75
Dear, server version did you hear my feedback.

**Comment by fenrus75** [comment]
there's effectively no information in this bug report so I am not sure what you expect to happen?
are there any error messages when you start these things from the command line? is there anything in the journal? etc

**Comment by GithubServers** [comment]
@fenrus75
server version
sudo swupd bundle-add desktop
Firefox startup crash
Settings crash
Don't others have this problem?

**Comment by GithubServers** [comment]
@fenrus75
Honey I found the problem I'm sorry to bother you
