### ISSUE TITLE
EFI mess after upgrade

### ISSUE THREAD

**Issue by mmorini** [clearlinux/distribution#2875]
`# clr-boot-manager update ` _[same with swupd repair]_
```
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L284): Cannot create EFI variable (boot entry)
[ERROR] cbm (../src/bootloaders/shim-systemd.c:L285): Please manually update your bios to add a boot entry for Clear Linux

```
Already tried the  /boot umounted partition cleanup (as seen in https://github.com/clearlinux/clr-boot-manager/issues/179 ) and /sys/firmware/efi/efivars/ cleanup (seen here https://github.com/NixOS/nixpkgs/issues/27821#issuecomment-330174962 ) therapies to no avail.

Now on
```
# swupd info
Distribution:      Clear Linux OS
Installed version: 38800
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

```
but had to boot older kernel Linux robin2 6.0.11-1216.native #1 SMP Fri Dec 2 09:14:14 PST 2022 x86_64 GNU/Linux
 to have a working console.

**Comment by mmorini** [comment]
Yessir, confirm both; `efibootmgr` is somewhat happy:
```
BootCurrent: 0004
No BootOrder is set; firmware will attempt recovery
```
Not sure what to do with this. I promise, cross my heart, I didn't touch anything with the BIOS settings.

**Comment by mmorini** [comment]
And, FWIW,
```
# clr-boot-manager list-kernels
* org.clearlinux.native.6.2.11-1296
  org.clearlinux.ltscurrent.6.1.23-1282
  org.clearlinux.native.6.0.11-1216
  org.clearlinux.iot-lts2018-sos.4.19.195-115

```

**Comment by mmorini** [comment]
Found these folks tinkering with a similar issue: https://github.com/rhboot/efibootmgr/issues/115 - (since my mobo is not completely dissimilar, I thought it may not be related with CL after all:
```
Base Board Information
        Manufacturer: ASUSTeK COMPUTER INC.
        Product Name: PRIME B450-PLUS
        Version: Rev X.0x
 
```

**Comment by bryteise** [comment]
> Sure, thanks, will do. Re: [#2875 (comment)](https://github.com/clearlinux/distribution/issues/2875#issuecomment-1511752146),
> 
> ```
> # ls /boot/EFI/org.clearlinux/ -lart
> total 71435
> drwxr-xr-x 4 root root      512 Aug 10  2020 ..
> -rwxr-xr-x 1 root root 14345824 Sep 20  2021 kernel-org.clearlinux.iot-lts2018-sos.4.19.195-115
> -rwxr-xr-x 1 root root 13724960 Dec  7 00:08 kernel-org.clearlinux.native.6.0.11-1216
> -rwxr-xr-x 1 root root 13819104 Apr 12 10:50 kernel-org.clearlinux.ltscurrent.6.1.23-1282
> -rwxr-xr-x 1 root root  2492796 Apr 12 10:50 freestanding-i915-firmware.cpio.xz
> -rwxr-xr-x 1 root root 12151296 Apr 12 10:50 freestanding-00-early-ucode.cpio
> -rwxr-xr-x 1 root root 15263616 Apr 16 18:41 kernel-org.clearlinux.native.6.2.11-1296
> -rwxr-xr-x 1 root root  1202593 Apr 17 17:40 bootloaderx64.efi
> -rwxr-xr-x 1 root root   144859 Apr 17 17:41 loaderx64.efi
> drwxr-xr-x 2 root root     2048 Apr 17 17:41 .
> ```

That looks healthy to me at least. Sorry I am not more help. Hopefully you can find something helpful in that thread. Bios land can be quite weird.
