### ISSUE TITLE
nouveau causes crash

### ISSUE THREAD

**Issue by GithubServers** [clearlinux/distribution#2877]
@fenrus75
In the latest version nouveau is no longer compatible with nvidia graphics cards causing Firefox and UI crashes and screens
--releases 38750-38880-live-server

**Comment by GithubServers** [comment]
@fenrus75
Honey, I didn't express myself clearly enough before, how exactly do I solve this problem?

**Comment by GithubServers** [comment]
@fenrus75
There is still one known bug that is not fixed
[https://github.com/systemd/systemd/commit/de8409ac43f6e4596de4cecce8dbbb5f1f2a18b1](url)
/usr/lib/udev/rules.d/60-evdev.rules
rules: add missing line continuation

**Comment by krdav** [comment]
I too got issues with a recent update.
Downgrading to 38710 fixes it:
`sudo swupd repair -m 38710 --force`

**Comment by GithubServers** [comment]
@krdav
Thanks and I hope the problem will be fixed soon.

**Comment by GithubServers** [comment]
@fenrus75
I replaced the nvidia driver problem was solved, please forgive my haste and harassment
