### ISSUE TITLE
WiFi not working after install -- possible firmware issue 

### ISSUE THREAD

**Issue by jfstroman** [clearlinux/distribution#288]
**Describe the bug**

WiFi did not work after install.  I received the notification:  "no WiFi hardware to enable."  I have an Intel 3165 which uses a version of the firmware (https://wireless.wiki.kernel.org/_media/en/users/drivers/iwlwifi-7265-ucode-25.30.14.0.tgz).

This firmware was not pre-installed.  However, according to lspci, it was present.  I then downloaded and copied the firmware to /lib/firmware, then rebooted.  I was then able to enable WiFi.

Note: I’m not 100% sure about this one.  The problem may be that I may not have been enabling WiFi correctly.

FYI -- I may try deleting the firmware and see if it breaks WiFi when I take it out.  WiFi worked during install.

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by tpleavitt** [comment]
This issue should be fixed. If this still exists, please reopen

**Comment by flopun** [comment]
I have same model of WiFi adapter (Intel 3165) and I have similar issue. When I connect to my WiFi, everything is normal, but after some time (it can be 45 or 15 minutes, it is random), iwlwifi just crash and I have to restart to get back online. This is also happening when I boot from live usb, so installing Clear Linux is sometimes difficult.
