### ISSUE TITLE
Default dnsmasq config is unusable

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#2881]
The default dnsmasq config (installed via `swupd bundle-add dhcp-server`) is not usable.

`systems-resolved` binds to `localhost:53` and `localhost:54` which results in:

```
Apr 23 14:08:55 clearlinux-test systemd[1]: Started dnsmasq.service.
Apr 23 14:08:55 clearlinux-test dnsmasq[22249]: dnsmasq: failed to create listening socket for port 53: Address already in use
Apr 23 14:08:55 clearlinux-test dnsmasq[22249]: failed to create listening socket for port 53: Address already in use
Apr 23 14:08:55 clearlinux-test dnsmasq[22249]: FAILED to start up
Apr 23 14:08:55 clearlinux-test systemd[1]: dnsmasq.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 23 14:08:55 clearlinux-test systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
Apr 23 14:08:55 clearlinux-test systemd[1]: dnsmasq.service: Scheduled restart job, restart counter is at 1.
Apr 23 14:08:55 clearlinux-test systemd[1]: Stopped dnsmasq.service.
```

This can be resolved by adding the following to the default `dnsmasq.conf`:

`bind-dynamic`

dnsmasq also likes to store it's dhcp leases in  `/var/lib/misc/dnsmasq.leases` The  `/var/lib/misc/` directory is not created by default. It is a reasonable assumption that someone installing the dhcp-server should have the necessary folder structures created during the bundle installation

**Comment by bwarden** [comment]
I'll fix the leases path (make it `/var/lib/dnsmasq/dnsmasq.leases`, add a `_dnsmasq` system user to own the directory, and make the systemd unit create the directory on startup).

As for the `bind-dynamic` suggestion, I'm strongly opposed. I know we ship the example config file as a fallback for when there's no `/etc/dnsmasq.conf`, but given how easy it is to create problems for network adminstrators by launching rogue DHCP servers, I think it's reasonable to require someone to explicitly configure how dnsmasq should bind an interface. Obviously you can copy the default config to `/etc/dnsmasq.conf`, but you could instead use `systemctl edit dnsmasq.service` to add `--bind-dynamic` if that's what you truly want, but either way you'd certainly want to add `--interface=X` or `--listen-address=X` along with that.

Enabling `--bind-dynamic` by itself will bind to all available interfaces, and is almost never what you really want. We can't guess effectively enough what interface you'd actually want to use for the sake of a default config.

**Comment by omkhar** [comment]
lgtm

**Comment by bwarden** [comment]
Release 39090 includes this fix.
