### ISSUE TITLE
mutter 44.1

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2882]
Let me tell you. Mutter 44.0, was the reason I ventured away for a while. Which is fine, because I saw some wonderful things trying Nobara Linux 37 and Fedora Linux 38.

Please keep mutter on the radar. Mutter 44.1 resolves issues around mutter-x11-frames affecting NVIDIA graphics, possibly other graphics too.

```text
mutter 44.1
====
* Fall back to the default, not the unknown color space [Sebastian W.; !2915]
* Fix resizing windows via keyboard [Florian; !2908]
* Fix possible screen freeze after resume with multiple monitors [Daniel; !2933]
* Fix anchor position when dragging window [Carlos; !2942]
* Fix applying XSettings to decorations on X11 [Marco; !2948]
* Allow clipped redraws for headless backend [Salman; !2775]
* Improve screencast support [Georges; !2804]
* Fix focus-on-click for server-side decorated windows [Carlos; !2954]
* Fix initial fullscreen state of server-side decorated windows [Carlos; !2961]
* Fix feedback loop triggering bursts of excessive CPU load [Robert; !2823]
* Enable modifiers by default on non-native backend [Robert; !2972]
* Check EDID for supported sink Colorimetry [Sebastian W.; !2919]
* Fix artifacts in titlebars on some hardware [Carlos; !2976]
* Fix map transitions for X11 windows on wayland [Carlos; !2975]
* Fixed crashes [Jonas Å., Sebastian K., Carlos, Michel, Daniel, Robert;
  !2932, !2930, !2945, !2956, !2962, !2968, !2967, !2960, !2963]
* Plugged leaks [Sebastian K., Jonas Å.; !2922, !2926, !2957]
* Misc. bug fixes and cleanups [Daniel, Ivan, Emmanuele, Simon, Jonas D.,
  Jonas Å., Chris, Florian, Corentin, msizanoen1, Sebastian K.; !2918, !2904,
  !2928, !2929, !2900, !2856, !2944, !2935, !2947, !2949, !2951, !2940, !2953,
  !2964, !2934, !2902, !2971]
  ```

**Comment by marioroy** [comment]
Off-topic: The main reason I ventured away was due to swupd update downloading 5 GB of data. I was watching /var/lib/swupd grow and grow unbelievably. One of the directories previously around 100 MB grew to 5 GB during the update. So this and mutter 44.0 were the reasons I thought the time has come to try something else.

**Comment by fenrus75** [comment]
as it happens, I just did the update to 44.1 about 45 minutes ago

we are working on the swupd download sizes by restructuring how we do
multiarch support, big chunks are landing this week for that

**Comment by fenrus75** [comment]
(also note that /var/lib/swupd in part contains most of the OS files
hardlinked, so it's not "simple" additive space used

swupd first downloads a new file into its area, verifies the cryptographic
integrity/etc/etc and only when all files are clean, it hardlinks them to
their final resting spot in /usr ... but hardlinks don't take up extra
space_

**Comment by marioroy** [comment]
> as it happens, I just did the update to 44.1 about 45 minutes ago

Greatly appreciated. Please know that I like CL a lot. I developed my Mandelbrot demo on it, while learning Python, Numba, PyOpenCL, PyCUDA, and Python parallel processing.

> we are working on the swupd download sizes by restructuring how we do
multiarch support, big chunks are landing this week for that

Hurray! The swupd tool eventually got to me and on top of that, mutter 44.0. Yikes! I'm so glad that I ventured away for a bit and witnessed the GNOME pop-shell extension (tiling on GNOME). These GNOME extensions elevate the GNOME desktop experience to a whole new level.

```text
# dependencies
gnome-shell-extension-common-44.0-1.fc38.noarch
gnome-shell-extension-user-theme-44.0-1.fc38.noarch

# gnome extensions
gnome-shell-extension-pop-shell-shortcut-overrides-1.2.0^10.dcf17f3-1.fc38.noarch
gnome-shell-extension-pop-shell-1.2.0^10.dcf17f3-1.fc38.noarch
gnome-shell-extension-arc-menu-44-2.fc38.noarch
gnome-shell-extension-blur-my-shell-45-1.fc38.noarch
gnome-shell-extension-custom-accent-colors-6-1.fc38.noarch
gnome-shell-extension-dash-to-panel-56-1.fc38.noarch
```

Typically, I search for the extension in pkgs.org (Fedora 38, it not there) then [Nobara Linux builds](https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara/builds/).

**Comment by fenrus75** [comment]
we used to ship a set of gnome shell extensions.. but the gnome people
don't really keep them updated which made going to new gnome versions a
nightmare for us... we ended up with no choice but to stop doing that

**Comment by marioroy** [comment]
Ah, no problem. Just getting mutter 44.1 and a sensible swupd are enough to elevate the user experience :)

**Comment by marioroy** [comment]
Fyi: The issues around mutter-x11-frames is not yet fully resolved, unfortunately. Wayland also not 100%, looking at the issues. What a fun time it is.

https://gitlab.gnome.org/GNOME/mutter/-/issues/2673
