### ISSUE TITLE
remove clang from default desktop

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2885]
```
# swupd bundle-info lib-opengl --files | grep clang | wc -l
1755
```

A lot of headers inside, make sense to create `devpkg-lib-opengl`. 

I can't remove this bundle 'cause

```
Bundle "lib-opengl" is required by the following bundles:
 - alsa-utils
 - audio-pipewire
 - fonts-basic
 - gstreamer
 - lib-imageformat
 - lib-poppler
 - libX11client
 - libva-utils
 - sway
 - wayland-server
 - webkitgtk
 ```

**Comment by fenrus75** [comment]
I'll check where the headers come from, but they're tiny compared to
the rest of llvm...
... and mesa pulls in llvm for several drivers

**Comment by thiagomacieira** [comment]
But it should pull only the shared libraries (libLLVM.so itself), not the massive static libraries for libclang and the rest.

**Comment by fenrus75** [comment]
yeah there';s a bit of a dependency mismatch happening that I'm trying to
clean up in the packaging

llvm does not build quick tho.

**Comment by fenrus75** [comment]
shuffle in llvm packaging done.. should now not have the headers/etc in
this bundle

**Comment by paulcarroty** [comment]
fixed in 39030, thx!
