### ISSUE TITLE
Clear does not support screen recording in Wayland

### ISSUE THREAD

**Issue by worldofgeese** [clearlinux/distribution#2892]
Clear Linux version 39050. I have tried three different screen recording methods: GNOME's native screen recording tool summonable with `Ctrl-Alt-Shift-R`, Kooha installed from Flatpak, and OBS both from Flatpak and Clear's own package repositories.

Is `xdg-desktop-portal` built with Pipewire support? It looks like the `ScreenCast` portal is included at least

```
strings /usr/libexec/xdg-desktop-portal | grep ScreenCast
org.freedesktop.portal.ScreenCast
```

Kooha fails with

```
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x55d7f8007000, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

OBS installed with `sudo swupd bundle-add obs` and run with `QT_QPA_PLATFORM=wayland obs`  doesn't expose the expected `Screen Capture (Pipewire)` when adding a source

![image](https://user-images.githubusercontent.com/59834693/236777469-32ab4e86-417c-4fdb-a0fc-3b6568db84b4.png)

Expected

![image](https://user-images.githubusercontent.com/59834693/236777516-fd157254-22fe-4772-a3df-58ea4b925407.png)

**Comment by paulcarroty** [comment]
> Is xdg-desktop-portal built with Pipewire support? 

It [is](https://github.com/clearlinux-pkgs/xdg-desktop-portal/blob/main/xdg-desktop-portal.spec#LL32C1-L33C1).

**Comment by Aqua1ung** [comment]
https://github.com/rustdesk/rustdesk/issues/4164

**Comment by Aqua1ung** [comment]
[Rumor has it](https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1537105758) that we need [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/) in order to get ScreenCast to show up.

**Comment by worldofgeese** [comment]
Screensharing and screen recording both work now in a GNOME on Wayland session. Thank you! 🙏🏼
