### ISSUE TITLE
xdg-desktop-portal-gnome please!

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#2898]
Official package name: [xdg-desktop-portal-gnome](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome)

License (must be an OSI approved Open Source license): same as Gnome?

Download URL of latest release: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/releases

Latest release date (must be recent): March 2023

Description: A backend implementation for [xdg-desktop-portal](http://github.com/flatpak/xdg-desktop-portal) that is using GTK and various pieces of GNOME infrastructure, such as the org.gnome.Shell.Screenshot or org.gnome.SessionManager D-Bus interfaces. [Appears to be required by Rustdesk under Wayland.](https://github.com/rustdesk/rustdesk/issues/4276#issuecomment-1537105758)

**Comment by fenrus75** [comment]
added; it'll show up in the next release (well the next one that passes QA)

**Comment by Aqua1ung** [comment]
@fenrus75: You da man!
