### ISSUE TITLE
add ceph-mgr to storage-cluster bundle

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#29]
http://docs.ceph.com/docs/master/install/manual-deployment/#manager-daemon-configuration says:
`On each node where you run a ceph-mon daemon, you should also set up a ceph-mgr daemon.`

But the ceph-mgr binary isn't available in any bundle. It probably belongs into storage-cluster, together with the rest of  the ceph binaries.

I can confirm that the lack of a manager leads to a warning:
```
# ceph --status
  cluster:
    id:     f2d86659-be79-405e-adef-565a23322b22
    health: HEALTH_WARN
            no active mgr
...
```

I don't know what practical implications this has, but it's probably wise to follow the recommendation.

Right now I see that commands like "rbd ls" hang, but that could also be caused by an incomplete ceph-ods setup (I only have one node and a single ods).

**Comment by pohly** [comment]
Adding a second ods did not help. Neither did lowering `osd pool default min size = 1`.

I don't know Ceph, therefore it would be nice to get some kind of HOWTO for setting up Ceph on Clear Linux.

**Comment by ganeshmaharaj** [comment]
Newer versions of ceph have created another component, manager (mgr) which is mandatory. One of it's main functions is to maintain the health of the cluster. Including mgr as part of the packaging would definitely help here. Let me see if i can help out with that.

**Comment by iphutch** [comment]
@nesiusra

**Comment by ganeshmaharaj** [comment]
@iphutch @nesiusra I am working on a patch for this and should be pushing it up to the mailing list shortly. Will comment here once that is done.

**Comment by ganeshmaharaj** [comment]
Enabling ceph-mgr on luminous (12.2.5) while the default python is version 3.X ends up being a bit more complicated and us adding loads of patches to get things working. Mimic which has all the changes for python3 and can run all modules on python3.X is scheduled to be released end of the month.  It would be ideal to wait for that and upgrade the package to mimic.

@iphutch @nesiusra does this seem reasonable to you?

**Comment by nesiusra** [comment]
Sounds good.

**Comment by ganeshmaharaj** [comment]
mimic got released a week ago and we have a patch now that should get ceph running in python3 with all the fittings. once we merge the patch we should be able to close this issue.

**Comment by ganeshmaharaj** [comment]
ceph has been updated to mimic v13.1.0. Have verified that it can be built with all python3 and tested it to be working fine on clear. You can chose this bug. I believe build 22380 should have all the packages in place for ceph to work properly.
