### ISSUE TITLE
mumble-server: missing libSSL

### ISSUE THREAD

**Issue by sofar** [clearlinux/distribution#2900]
I noticed the packaging had changed and instead now the package ships a `mumble-server` binary.

However, it now fails at startup with:

```
mumble-server[2453]: qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_ssl
mumble-server[2453]: qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_crypto
mumble-server[2453]: qt.network.ssl: QSslSocket: cannot resolve ASN1_STRING_get0_data
<<snip>>
mumble-server[2453]: <F>2023-05-24 10:47:55.524 SSL: this version of Murmur is built against Qt without SSL Support. Aborting.
```

**Comment by bryteise** [comment]
Hrm, not sure why. QT works in mysterious ways but mumble seems to think it seems openssl when it builds.

**Comment by sofar** [comment]
Only libqt5webengine*.so seems to link against libssl.so.* on my system.

**Comment by fenrus75** [comment]
I've tried to convince Qt to link to openssl a few times in the last few
days, with no luck so far.
its really ssl resistant

now also Qt likes to rather dlopen openssl rather than link to it (license
stuff) so ldd and friends aren't really going to show that

**Comment by thiagomacieira** [comment]
The {{-openssl-linked}} argument to configure should make it link to OpenSSL instead of trying to dlopen it.

**Comment by sofar** [comment]
Confirmed fixed with `System updated from version 38860 to version 39230`
