### ISSUE TITLE
[PATCH qhull] qhull: package static libraries

### ISSUE THREAD

**Issue by schiele** [clearlinux/distribution#2901]
Qhull comes with a C++ interface libqhullcpp. So far the header files
are packaged but the library is missing since the upstream project
provides it only as a static library due to the non-stability of the
API.

As such I changed the package to keep the static libraries to make this
interface usable.

Additionally, I added a qhull.license file to make the current version of
autospec happy.

All the remaining changes originate from autospec.

Patch: [for-review.txt](https://github.com/clearlinux/distribution/files/11558276/for-review.txt)

**Comment by bryteise** [comment]
Looks good, note this puts the libraries in a staticdev subpackage which wouldn't show up in a bundle by default. qhull-dev is in desktop-dev, do you want me to add the static libs there or is another bundle preferable?

**Comment by schiele** [comment]
I personally would have preferred to see at least the libqhullcpp.a in the regular dev package, the others might be ok in staticdev. Since I am not yet familiar enough with autospec I didn't see how to achieve this easily. I could have done it by manually edit the spec file but assumed this is not what the project aims for. Therefore if you could adapt the patch accordingly I could learn from that for future patches.

**Comment by schiele** [comment]
Great! Just updated to the latest version and things look good now.
