### ISSUE TITLE
failure to mount ntfs partition via file manager GUI (resolved)

### ISSUE THREAD

**Issue by zeekisthename** [clearlinux/distribution#2909]
This is a known issue previously maniftested in Fedora, Gentoo, and Arch linux.  

Now an issue with Clear Linux.

Fully described here:
https://bugzilla.redhat.com/show_bug.cgi?id=2189241 

This has already been resolved in numerous other distros and am surprised to see it crop up with Clear Linux this late.

**Comment by bryteise** [comment]
Looks like the fix is in an patch that hasn't made it into an upstream release of util-linux yet.

**Comment by fenrus75** [comment]
https://github.com/util-linux/util-linux/commit/f94a7760ed7ce81389a6059f020238981627a70d

is supposedly the commit; we likely should backport that for a few days
until upstream releases

**Comment by bryteise** [comment]
Yep.

**Comment by fenrus75** [comment]
ok added to the package

**Comment by zeekisthename** [comment]
Ok, thanks to devs.

Ntfs issue appears to be corrected as of the following update
