### ISSUE TITLE
SVT-AV1-lib compiled with AVX2 only

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2915]
Which caused the [issue](https://github.com/clearfraction/distribution/issues/32#issuecomment-1607657351) with   old CPU.

**Comment by fenrus75** [comment]
this is... distinctly odd. We really build it twice while the sse build
section does not seem to have anything avx2 in it

**Comment by fenrus75** [comment]
argh found it

very broken upstream CMake file
