### ISSUE TITLE
GDM fails to start, probably an issue with GDM/Wayland

### ISSUE THREAD

**Issue by rfkspada** [clearlinux/distribution#2916]
First, I am on a XPS 13 notebook with "00:02.0 VGA compatible controller: Intel Corporation Iris Plus Graphics G1 (Ice Lake) (rev 07)" (from lspci).

Yesterday, I believe autoupdate made an update and after the reboot, gdm failed to start delivering a black screen. I could login using multi-user.target as runlevel. 

From there, I installed lightdm and got a login screen. Lightdm could launch gnome on xorg and i3wm, but could not launch gnome on wayland and sway. 

And most weird, I just found out that "sudo dbus-run-session -- gnome-shell  --display-server --wayland", "sudo startx" and "sudo gdm" don't work, resulting in the black screen, but "sudo systemctl start gdm.service" works. I believe the last starts gdm on xorg, since I can only choose gnome on xorg and i3wm in the gear, there are no wayland options.

It seems that there are more people with a similar issue, since there is already a post on CL forum:

[https://community.clearlinux.org/t/help-computer-wont-log-in/4687/18](https://community.clearlinux.org/t/help-computer-wont-log-in/4687/18)

 EDIT: Forgot to say that the version is 39450.

EDIT 2: Since update to 39540, setting WaylandEnable=False in /etc/gdm/custom.conf makes runlevel graphical.target works (on Xorg).

**Comment by dasouza** [comment]
Looks like I have the same issue here with KDE and Wayland. I can see the desktop wallpaper and move the mouse cursor after logging in, but everything else is missing/unresponsive. Reverting to 39490 fixes the issue.

**Comment by mfdemicco** [comment]
39540 breaks my system too except that I'm using SDDM and KDE. I'm presented with a black screen  upon boot (no SDDM login screen). I rolled back to version 39520 and all is well there. I think it may be related to the new kernel but haven't tried to troubleshoot further (see https://community.clearlinux.org/t/39540-broken-kde-5-27-6/8928/3).

**Comment by dasouza** [comment]
> 39540 breaks my system too except that I'm using SDDM and KDE. I'm presented with a black screen upon boot (no SDDM login screen). I rolled back to version 39520 and all is well there. I think it may be related to the new kernel but haven't tried to troubleshoot further (see https://community.clearlinux.org/t/39540-broken-kde-5-27-6/8928/3).

Similar issue here using SDDM, KDE and Wayland. SDDM seems to work fine but I can only see the desktop wallpaper after logging in, can move the mouse cursor but that's it.

**Comment by dasouza** [comment]
39590 seems to have fixed the issue.

**Comment by rfkspada** [comment]
Thank you, I will give it a try this weekend.
