### ISSUE TITLE
39530+ -> no USB drives

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#2917]
Starting w/39530 my CL no longer detects USB drives. Anyone else noticed that?

Could this be due to the new 6.3.10 kernel introduced in 39530?

**Comment by flexoron** [comment]
Yes and No.

No: CL does detect USB drives.
Yes: It stopped mounting filesystems(on these USB drives) automatically  for a user: 

Broken: /run/media/'username'/usb-drive-name
```
Workaround: /etc/fstab entries (here for ntfs-3g usb drives)

UUID=7ACE1A6ACE1A1F47 /a1 ntfs-3g uid=1000,gid=1000,umask=0022 0 0
UUID=C6CE94C4CE94ADE5 /a2 ntfs-3g defaults,noauto 0 0
```
Note: I decided to  mount /a2 manually: sudo mount /a2

**Comment by fenrus75** [comment]
does anyone happen to remember a last working version number? easier for us
to go look at what changed ;)

**Comment by Aqua1ung** [comment]
@fenrus75: unfortunately, the only versions I have been able to install are the ones that show up [here](https://cdn.download.clearlinux.org/latest). This being said, I am pretty sure both 39530 and 39540 suffer from this. Last one I can say for sure that it works fine is 39470, so you should start by looking at 39490, 39520, and 39530.

@flexoron: funny thing is that, before posting this thread, I did my due diligence and tried opening "Disks" to see if the drives show up (in 39540), and it just wasn't opening up (or was crashing upon opening). That's when I decided to revert to 39450. Is "Disks" working for you in 39540? Can you launch that application (before applying your workaround, that is)?

**Comment by flexoron** [comment]
@fenrus75 Not sure but I think it was 39470.

@Aqua1ung Opening "Disks" ? Don't know what this means.

**Comment by Aqua1ung** [comment]
> @fenrus75 Not sure but I think it was 39470.
> 
> @Aqua1ung Opening "Disks" ? Don't know what this means.

gnome-disk-utility
![Screenshot from 2023-06-30 11-00-18](https://github.com/clearlinux/distribution/assets/12104779/0b6ae997-4a74-4ef0-8bcc-13686fd68136)

**Comment by flexoron** [comment]
```
$ gnome-disks

(gnome-disks:2169): GNOME-Disks-ERROR **: 19:59:18.430:
Error getting udisks client: Error calling StartServiceByName for org.freedesktop.UDisks2:
Failed to activate service 'org.freedesktop.UDisks2': timed out (service_start_timeout=25000ms)
Trace/breakpoint trap (core dumped)

$
```

**Comment by paulcarroty** [comment]
Probably something wrong with the udisks2 update.

**Comment by Aqua1ung** [comment]
> Probably something wrong with the udisks2 update.

Yeah, that happened in 39530, which is consistent w/my experience (see title thread).

**Comment by fenrus75** [comment]
yeah we're currently poking at this udisks update (it has some tentacles in
a few others places on how all this fits and doesn't fit together)

**Comment by bryteise** [comment]
Looks like upstream libblockdev failed to update their API version for the default plugins (which is fine *if* the plugin configuration file is used which does have the right API version in it but Clear does not ship that file, thus the issue). Next release should have this resolved.

**Comment by x-sublime** [comment]
20.141146] traps: udisksd[1090] trap int3 ip:55ee616539b4 sp:7fff76493870 error:0 in libglib-2.0.so.0.7600.1[55ee615dc000+107000] and after 20 s. the boot continues in graphical mode.

If I do :
sudo systemctl disable udisks2.service my USB wifi dongle USB stops to work.

**Comment by Aqua1ung** [comment]
> Looks like upstream libblockdev failed to update their API version for the default plugins (which is fine _if_ the plugin configuration file is used which does have the right API version in it but Clear does not ship that file, thus the issue). Next release should have this resolved.

I am guessing 39550+ fixes this, right?
