### ISSUE TITLE
39540 Docker problems

### ISSUE THREAD

**Issue by moroznah** [clearlinux/distribution#2918]
Multiple VMs updated to 39540, Docker version 24.0.2 no longer starts any containers with port mapping ("-p" option).
Ex. error:
ERROR: for webapp Cannot start service webapp: driver failed programming external connectivity on endpoint webapp (8b4185c591f7adeba74997fdc78b78bff436dc5cb3bb8efd5b80a4b2f33f8982): Error starting userland proxy: listen tcp [::]:8000: bind: address already in use
All these ports are not used and multiple containers worked prior to update.

**Comment by fenrus75** [comment]
unfortunately upstream docker changed their syntax for this

see also https://community.clearlinux.org/t/docker-issue-on-clear-linux/8927
for discussion/solutions

**Comment by moroznah** [comment]
Adding host addresses fixed the issue.
Thanks!

**Comment by ljmccarthy** [comment]
OK thanks. Sorry for creating a duplicate issue (I did a search, but couldn't find anything on it).

**Comment by bryteise** [comment]
No worries, search is hit or miss.

**Comment by apwiggins** [comment]
What's the source for upstream change?  Is this an actual directed change or an upstream reportable bug?  Docker release notes for v24 make no mention of changes to the ports specfication -- which is a pretty signifcant change given that it would break most docker-compose YAMLs and bash scripts.
https://docs.docker.com/engine/release-notes/24.0/

Docker documentation (which I'm assuming is current) shows that a plain port specification is valid.  It only mentions using an IP address as an optional improvement
https://docs.docker.com/network/
The Clear Linux forum post and workaround doesn't really clear the air and doesn't show that upstream changed port specification behaviour intentionally.  This is still a problem and seems to deviate from upstream Docker's intentions.
