### ISSUE TITLE
[BUG] SMM not supported by the Hypervisor

### ISSUE THREAD

**Issue by original-tinozza** [clearlinux/distribution#2919]
Hello there ClearLinux team,
i'm trying to setup a Windows10 virtual machine with secure boot and TPM2.0 support but i am hitting a stonewall with the SMM (System Management Mode) support necessary to activate secure boot support within the OVMF uefi bios image.

I am using the virt-manager GUI and here an extract with the relevant infos of the Domain XML:

```html
<os firmware="efi">
   <type arch="x86_64" machine="pc-q35-7.2">hvm</type>
   <loader readonly="yes" secure="yes" type="pflash">/qemu/OVMF/OVMF_CODE.secboot.fd</loader>
   <nvram template="/qemu/OVMF/OVMF_CODE_VARS.secboot.fd">/qemu/WIN10_OVMF_VARS.fd</nvram>
   <boot dev="hd"/>
   <bootmenu enable="yes"/>
   <smbios mode="sysinfo"/>
</os>
<features>
   [...]
   <smm state="on"/>
   [...]
</features>
[...]
<pm>
<suspend-to-mem enabled="no"/>
   <suspend-to-disk enabled="no"/>
</pm>
``` 

and this is the error i'm getting:
`libvirt.libvirtError: internal error: QEMU unexpectedly closed the monitor (vm='Windows10'): 2023-07-09T07:28:01.926147Z qemu-system-x86_64: System Management Mode not supported by this hypervisor.`

To be sure that there isn't something wrong with my hardware configuration i tried the run the same VM with exactly the same Domain XML and the same OMVF UEFI bios image with the latest FEDORA distro. No problem whatsoever.

Any idea on how to solve the issue?

**Comment by fenrus75** [comment]
yeah we had this off in the config -- thinking nobody would want this

I just turned it on for the next release

**Comment by original-tinozza** [comment]
Great, many thanks @fenrus75 :+1: 
I must be really blind. I looked for the config flag in the github repo but i missed it completely.

**Comment by original-tinozza** [comment]
SMM enable starting from CLR [39610](https://download.clearlinux.org/releases/39610/clear/RELEASENOTES-39590-to-39610).

> Changes in package linux (from 6.4.2-1331 to 6.4.3-1333):
>     [...]
>     Arjan van de Ven - enable SMM

Awesome :+1:
