### ISSUE TITLE
`sof-bin` update please

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#2924]
@fenrus75: I am not sure if [my issues](https://github.com/clearlinux/distribution/issues/2923) happen because [`sof-bin`](https://cdn.download.clearlinux.org/repo/clear_dev/Packages/sof-bin-2.2.1-10.x86_64.rpm) has not been updated in a while, or is completely missing from the `linux-firmware-extras` bundle, but would you mind checking what happens, and if an update is needed, update `sof-bin` to the [latest version](https://github.com/thesofproject/sof-bin/releases/tag/v2.2.6) please? Many thanks!

**Comment by fenrus75** [comment]
yeah I was looking at it earlier this week when I saw the audio issues..
something is wonky with sof-bin and it needs more than just an update..
I'll poke some more

**Comment by bryteise** [comment]
They had changed the install so our autoupdate didn't consume it nicely. Updated the config for the package so the next update should have the latest sof-bin version.

**Comment by Aqua1ung** [comment]
Many thanks! You guys rock!

**Comment by Aqua1ung** [comment]
I can confirm: latest 39640 update fixes sof-bin, so now I got sound!
