### ISSUE TITLE
Failing "Test autospec package in a Clear Linux OS virtual machine" , documentation error or me?

### ISSUE THREAD

**Issue by MickeJ-GitHub** [clearlinux/distribution#2931]
Following the documentation [Test in a Clear Linux OS virtual machine](https://clearlinux.github.io/clear-linux-documentation/guides/clear/autospec.html#test-packaged-software) but failing to test my package.

_Download the Clear Linux OS KVM image into the ~/clearlinux directory as clear.img. The location and name clear.img.xz is important for the tooling to work:_
```
cd ~/clearlinux
curl -o clear.img.xz https://download.clearlinux.org/image/$(curl https://download.clearlinux.org/image/latest-images | grep '[0-9]'-kvm)
unxz -v clear.img.xz
```
This instruction fails, download code must be broken because the download is fast, the img is small and fails to unpack. I get:
> unxz: Compressed data cannot be read from a terminal

So instead manually download a kvm, [clear-39630-kvm.img.xz](https://download.clearlinux.org/image/clear-39630-kvm.img.xz) renaming it to clear.img.xz and continuing following the guide
_Run make install from the package’s autospec directory. The make install command mounts the downloaded Clear Linux OS KVM image and installs the autospec-created RPM into it:_
```
cd ~/clearlinux/packages/<package-name>
make install
```
and script tells me my package becomes a device cpio without errors.

When starting the kvm there is nothing in it. Not sure what to expect but the "failed to load Boot0001" boot message makes me think something is not right.
```
BdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00003 " from PciRoot(0x0)/Pci(0x1,0x1)/Ata(Secondary,Master,0x0): Not Found
BdsDxe: loading Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x4,0x0)
BdsDxe: starting Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x4,0x0)
[    0.034894] RETBleed: WARNING: Spectre v2 mitigation leaves CPU vulnerable to RETBleed attacks, data leaks possible!
[    0.224716] sgx: There are zero EPC sections.
[    0.346005] intel_powerclamp: CPU does not support MWAIT
systemd-bootchart: sample time overrun 12 times

clr-50fb28da14d04d67bc1c19133d76afa8 login: root
You are required to change your password immediately (administrator enforced).
New password: 
Retype new password: 
root@clr-50fb28da14d04d67bc1c19133d76afa8 ~ # ls
root@clr-50fb28da14d04d67bc1c19133d76afa8 ~ # 
```
I am failing to see what do wrong,  if documentation needs an update. How can i test package in a kvm?

**Comment by bryteise** [comment]
Ah looks like the `latest-images` plaintext file was replaced with `https://download.clearlinux.org/image/latest-images.json`.

I'm not sure what you mean by nothing is on the image though? That looks pretty normal as far as the boot goes.

What are the contents for the package you installed? Can you check those paths exist on the image?
