### ISSUE TITLE
ThinkMLI Linux kernel module

### ISSUE THREAD

**Issue by MickeJ-GitHub** [clearlinux/distribution#2935]
### Official package name:
Linux ThinkMLI kernel module https://github.com/lenovo/thinklmi
_ThinkLMI is now integrated upstream into the Linux kernel (5.17 onwards) using the firmware-attributes class. As long as it is included by your distro you can do sudo modprobe think-lmi and then access the WMI attributes under /sys/class/firmware-attributes/thinklmi_

### License (must be an OSI approved Open Source license):
GPL-2.0 WITH Linux-syscall-note
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/COPYING

### Download URL of latest release:
In Linux since 5.11 (5.17)

### Description:
For Lenovo platforms that support a WMI interface to the BIOS add
support, using the firmware-attributes class, to allow users to access
and modify various BIOS related settings.

**Comment by fenrus75** [comment]
fair enough -- fixed in next build
