### ISSUE TITLE
Error: Bundle too large by 18446744073686M in c-basic

### ISSUE THREAD

**Issue by kazan417** [clearlinux/distribution#2938]
Impossible error Bundle too large by 18446744073686M in c-basic bundle. I can do --skip-diskspace-check, but this is bad. Bundle shouls ask for correct size.

**Comment by bryteise** [comment]
What version are you getting this on?

**Comment by kazan417** [comment]
Distribution:      Clear Linux OS
Installed version: 39720.
But now i tryred again   and it shows correct size and installed succesfully.
Maybe reboot helped. Now can close.
