### ISSUE TITLE
Website Documentation Links Incorrect

### ISSUE THREAD

**Issue by DevinStrom** [clearlinux/distribution#2939]
From the website, trying to access the Documentation page gives 404 error. Link is "https://clearlinux.org/clear-linux-documentation/index.html"

From the main https://clearlinux.org/ page, links for:
&nbsp;&nbsp;"Guides" https://clearlinux.github.io/clear-linux-documentation/guides/index.html
&nbsp;&nbsp;"Tutorials" https://clearlinux.github.io/clear-linux-documentation/tutorials/index.html
&nbsp;&nbsp;"References" https://clearlinux.org/clear-linux-documentation/reference/index.html
&nbsp;&nbsp;Documentation "VIEW ALL" https://clearlinux.github.io/clear-linux-documentation
direct website user to page not found.

**Comment by pixelgeek** [comment]
clearlinux.org now redirects to clearlinux.github.io, and the links on the home page have been fixed.  
Please update any bookmarks you may have for subdirectories in clearlinux.org, and substitute clearlinux.github.io. 

Thanks, 
Chris
