### ISSUE TITLE
Add kio-admin to desktop-kde bundle

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2952]
Official package name: kio-admin
Download URL of latest release:  https://invent.kde.org/system/kio-admin/-/archive/master/kio-admin-master.tar.bz2

Description:

This allows to edit and view (Dolphin, Kate, etc) root files under the KDE ecosystem by appending `admin://` to the path.  It is working perfectly by compiling and installing locally with the latest clearlinux version.

According to Nate Graham (https://invent.kde.org/frameworks/kio/-/merge_requests/1004#note_717749):
```
You can use kio-admin to do it until and unless this work is merged merged. That works today; just install it from your distro's package repos. If your distro doesn't pre-install it, ask them to. If your distro doesn't ship it at all, ask them to.
```

https://invent.kde.org/frameworks/kio/-/tags
https://invent.kde.org/system/kio-admin

# Requirements

- Must be installed to /usr! Polkit and DBus hardcode /usr as source for policies and system services
- KIO 5.98 (master at the time of writing)

# Functionality

kio-admin implements a new protocol `admin:///` which gives administrative access to the entire system. This is achieved
by talking, over dbus, with a root-level helper binary that in turn uses existing KIO infrastructure to run file://
operations in root-scope. Or simply put: `admin://` is exactly like `file://` but redirected over dbus to gain
administrative privileges.

```shell
dolphin admin:///
```

**Comment by fenrus75** [comment]
https://download.kde.org/stable/kio-admin/  shows a pretty old stable
release

will poke more if this is actually something stable/maintained/etc

(given the security exposure of "admin" stuff we do have to care about that)

**Comment by fenrus75** [comment]
https://download.kde.org/stable/release-service/23.08.0/src/kio-admin-23.08.0.tar.xz

ok it's part of the normal release train -- much better for us to support

**Comment by insilications** [comment]
> https://download.kde.org/stable/release-service/23.08.0/src/kio-admin-23.08.0.tar.xz ok it's part of the normal release train -- much better for us to support On Thu, Sep 14, 2023 at 8:05 AM Arjan van de Ven ***@***.***> wrote:

Nice, I couldn't find the correct source download for the latest tag on the upstream git (23.08.0).

**Comment by insilications** [comment]
Thanks for supporting it
