### ISSUE TITLE
python3 package generates wrong pkg-config configuration

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2959]
python3 needs to create `site-packages` in `/usr/lib/` for pure-Python modules, but it also needs to use `/usr/lib64/` for `libpython3.11.so`  (for packages that need to link to it for extension modules).

If programs request pkg-config to link to python3 using `pkg-config python-3.11-embed --libs` (/usr/lib64/pkgconfig/python3-embed.pc), it returns the following on clearlinux:
`-L/usr/lib -lpython3.11`

There is no `libpython3.11.so` in `/usr/lib/`, so many builds that rely exclusively on pkg-config to keep track of python3 shared libraries currently fail on clearlinux.

The package (https://github.com/clearlinux-pkgs/python3/blob/main/python3.spec) sets `--libdir=/usr/lib`, but it seems that the correct configuration should be `--with-platlibdir=/usr/lib` (https://docs.python.org/3/using/configure.html#cmdoption-with-platlibdir) and then `--libdir=/usr/lib64`

**Comment by fenrus75** [comment]
I'll take a look but /usr/lib64 is the default library path and never needs
a -L

**Comment by insilications** [comment]
Yes, /usr/lib64 is the default library path, the %make_install macro section in the .spec manually (I think this package is not autospec'd?) makes sure it is.

https://github.com/clearlinux-pkgs/python3/blob/main/python3.spec:
```
%make_install
mkdir -p  %{buildroot}/usr/lib64/  %{buildroot}-v3/usr/lib64/
mv %{buildroot}/usr/lib/libpython*.so* %{buildroot}/usr/lib64/
mv %{buildroot}-v3/usr/lib/libpython*.so* %{buildroot}-v3/usr/lib64/
```

But the "damage" is already done because `/usr/lib64/pkgconfig/python-3.11-embed.pc` ends up obeying `--libdir=/usr/lib`

**Comment by fenrus75** [comment]
btw is tehre a pypi or so package that shows this issue (so that I can
fixes)

we package a whole lot of pypi and haven't seen this before

**Comment by insilications** [comment]
> btw is tehre a pypi or so package that shows this issue, so that I can fixes, we package a whole lot of pypi and haven't seen this before

Yes, but the problem should probably appear whenever python is embedded into a native application package. For example, it shows up when I try to build pyside6 locally because it needs to build shiboken6, which uses python libs to create C/C++ binding wrappers (https://doc.qt.io/qtforpython-6/gettingstarted/index.html).

See the latest instructions on embedding python into C/C++ (https://docs.python.org/3/extending/embedding.html#compiling-and-linking-under-unix-like-systems). This is the output on CLR:
```
python3.11-config --ldflags --embed
 -L/usr/lib -lpython3.11 -ldl  -lm
```

If a build configuration relies on this it will probably fail. Another way to get the correct configuration is using sysconfig:
```
Python 3.11.5 (main, Aug 24 2023, 16:54:01) [GCC 13.2.1 20230824 releases/gcc-13.2.0-140-g74e3194675] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_config_var('LIBDIR')
'/usr/lib'
```

For example, pyside2 (for Qt 5.12.x), which is probably not being build in CLR anymore, uses the same kind of patch I use for my local build of pyside6: https://github.com/clearlinux-pkgs/pyside2-setup/blob/main/0001-Fix-build-in-Clear.patch
```
--- a/build_scripts/main.py
+++ b/build_scripts/main.py
@@ -515,7 +515,7 @@ class PysideBuild(_build):
         py_executable = sys.executable
         py_version = "{}.{}".format(sys.version_info[0], sys.version_info[1])
         py_include_dir = get_config_var("INCLUDEPY")
-        py_libdir = get_config_var("LIBDIR")
+        py_libdir = "/usr/lib64"
         py_prefix = get_config_var("prefix")
         if not py_prefix or not os.path.exists(py_prefix):
             py_prefix = sys.prefix
```

It removes `get_config_var("LIBDIR")` precisely because the python3 package gives the wrong build configuration. I have no idea whether there are other native applications that embed python in CLR that face this same problem but I bet their builds are being patched to avoid the same error.

**Comment by insilications** [comment]
It seems that this is fixed by recent: https://github.com/clearlinux-pkgs/python3/blob/main/python3.spec#L198

Thanks!
