### ISSUE TITLE
Power management on SSD samsung 970 pro when bare metall installation

### ISSUE THREAD

**Issue by stegamjay** [clearlinux/distribution#296]
Hello,
i've got a SSD **samsung 970 pro** in a **Dell XPS 9350** laptop.

In the latest clearlinux bare metal, i've got 2 power state **non operational** when i run the command: 
**sudo nvme id-ctrl /dev/nvme0**
NVME Identify Controller:
vid       : 0x144d
ssvid     : 0x144d
sn        : S463NF0K912522X     
mn        : Samsung SSD 970 PRO 512GB               
fr        : 1B2QEXP7
rab       : 2
ieee      : 002538
cmic      : 0
mdts      : 9
cntlid    : 4
ver       : 10300
rtd3r     : 30d40
rtd3e     : 7a1200
oaes      : 0
ctratt    : 0
rrls      : 0
oacs      : 0x37
acl       : 7
aerl      : 3
frmw      : 0x16
lpa       : 0x3
elpe      : 63
npss      : 4
avscc     : 0x1
apsta     : 0x1
wctemp    : 354
cctemp    : 354
mtfa      : 0
hmpre     : 0
hmmin     : 0
tnvmcap   : 512110190592
unvmcap   : 0
rpmbs     : 0
edstt     : 35
dsto      : 0
fwug      : 0
kas       : 0
hctma     : 0x1
mntmt     : 352
mxtmt     : 354
sanicap   : 0
hmminds   : 0
hmmaxd    : 0
nsetidmax : 0
sqes      : 0x66
cqes      : 0x44
maxcmd    : 0
nn        : 1
oncs      : 0x5f
fuses     : 0
fna       : 0x5
vwc       : 0x1
awun      : 1023
awupf     : 0
nvscc     : 1
acwu      : 0
sgls      : 0
subnqn    : 
ioccsz    : 0
iorcsz    : 0
icdoff    : 0
ctrattr   : 0
msdbd     : 0
ps    0 : mp:6.20W operational enlat:0 exlat:0 rrt:0 rrl:0
          rwt:0 rwl:0 idle_power:- active_power:-
ps    1 : mp:4.30W operational enlat:0 exlat:0 rrt:1 rrl:1
          rwt:1 rwl:1 idle_power:- active_power:-
ps    2 : mp:2.10W operational enlat:0 exlat:0 rrt:2 rrl:2
          rwt:2 rwl:2 idle_power:- active_power:-
ps    3 : mp:0.0400W **non-operational** enlat:210 exlat:1200 rrt:3 rrl:3
          rwt:3 rwl:3 idle_power:- active_power:-
ps    4 : mp:0.0050W **non-operational** enlat:2000 exlat:8000 rrt:4 rrl:4
          rwt:4 rwl:4 idle_power:- active_power:-

I think the default parameter of **nvme_core.default_ps_max_latency_us** in the kernel is not correct for this SSD

It would be great if those powerstates where operational (for the power consumption on battery)

It is possible to do something to activate those 2 powerstates ?

Tanks you

**Comment by ahkok** [comment]
Quick note: the above workaround needs a reload with `clr-boot-manager update`  and a reboot, of course.
