### ISSUE TITLE
oxygen-sounds has become absent

### ISSUE THREAD

**Issue by insilications** [clearlinux/distribution#2960]
Official package name: oxygen-sounds

Download URL of latest release: https://download.kde.org/stable/plasma/5.27.8/oxygen-sounds-5.27.8.tar.xz

Description:
For some reason, it seems that during recent KDE Plasma updates on Clear Linux, oxygen-sounds (https://invent.kde.org/plasma/oxygen-sounds) has become lost (/usr/share/sounds/), so KDE Plasma has no sounds at all.

**Comment by bwarden** [comment]
Fixed by https://github.com/clearlinux/clr-bundles/commit/091a5a4aea6c2eaf355d43adfe151cd046c6ad23
