### ISSUE TITLE
Is chrt broken for normal users?

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#2962]
I finished automation for the XanMod kernel on Clear Linux project. Completing the documentation is all that remains. One part of the documentation mentions `chrt`. But, I'm unable to make `chrt` work as a normal user. No problems for super-user. I did the pam configuration, limits.conf and realtime group.

```bash
$ /usr/bin/chrt -r 20 ls
chrt: failed to set pid 0's policy: Operation not permitted
```

Setting capability on the chrt binary does work but unsure if this is ideal. Can you help, please? Is `chrt` forbidden for normal users? If yes, then I will not mention it.

```bash
sudo mkdir -p /usr/local/bin
sudo cp -a /usr/bin/chrt /usr/local/bin/.
sudo setcap cap_sys_nice+ep /usr/local/bin/chrt
```

The `/usr/local/bin` path comes before `/usr/bin` in `$PATH`. This works, finally.

```bash
$ chrt -r 20 echo "Thank, you!"
Thank, you!
```

**Comment by marioroy** [comment]
My apologies if I pinged too early. If anything, I like to know if okay describing the work around above. Or have I missed something?

**Comment by fenrus75** [comment]
I've been poking at this a bit today and on first look I'm not a fan of
adding privileges to something like chrt (it's not setuid but it's in the
same vain).

You can do it yourself no problem -- you know your security ... but as
general thing for us I'm not convinced yet

**Comment by marioroy** [comment]
Okay, thanks for trying. I experienced the kernel/desktop freezing momentarily some time ago, attempting parallel (learning things). And it happened again some later, and yet again. This is what inspired me to try XanMod.

For desktop use at home, I find the `chrt` utility handy. I use `taskset` and `chrt` together for launching Chromium e.g. `taskset -c 8-15 chrt -r 20 "/path/to/chromium"`. It will not overtake the computer. The process is isolated using `taskset`. No matter if compiling, or toying around with parallel programming, it's surreal seeing the real-time aspect of the kernel in action. Even the LTS kernel performs admirably -- and surely 6.5.3 with the scale.patch uplift. Thus far, Chromium has not misbehaved.

Recently, I learned about `~/.rpmmacros` and have set `%_smp_mflags` to a sane value.

**Comment by fenrus75** [comment]
there was a reason we turned that off, but I just don't remember it... so
will have to poke again at this thing and see if we can enable this

thanks for the poke

**Comment by marioroy** [comment]
@fenrus75 The `sched_autogroup_enabled` does make the desktop more zippy, but may decrease performance somewhere else. I will update the README file in the ClearMod (XanMod on Clear Linux project) for this to be optional, not necessary.

I resolved an issue with a stress test failing with XanMod. Now passing without `sched_autogroup_enabled`. I will mention the fix in the README in the next update.

**Comment by marioroy** [comment]
@fenrus75 , `/usr/bin/chrt` is working for my userid. I need to backtrack to verify, but unsure if `pam_limits.so` looks at `/etc/security/limits.conf` or `/etc/security/limits.d/*.conf`. In the meantime, I appended options `conf=/etc/security/limits.conf debug`.

Helpful content which helped me sort this out.

[How to change linux scheduling policy for user systemd file?](https://unix.stackexchange.com/questions/589175/how-to-change-linux-scheduling-policy-for-user-systemd-file)

[Setting of realtime scheduler for user service fails](https://github.com/systemd/systemd/issues/4851)

**Comment by marioroy** [comment]
@fenrus75 I removed the option `conf=/etc/security/limits.conf` and verified `pam_limits.so` not checking `/etc/security/limits.conf`. This is a bug.

```text
reading settings from '/usr/share/defaults/etc/security/limits.conf'
```

**Comment by marioroy** [comment]
One can work around the bug by giving the `conf` option. I copied `common-session` and `systemd-user` from `/usr/share/pam.d/` to `/etc/pam.d/`.  Then, changed or added `pam_limits.so` (inserted after the `pam_loginuid.so` line).

```text
session required pam_loginuid.so
session required pam_limits.so conf=/etc/security/limits.conf
```

Not to forget the `/etc/security/limits.conf` file. The `realtime` group does not exist in Clear Linux. So, one must create the group.

```text
@audio      -     rtprio    98
@audio      -     memlock   unlimited

@realtime   soft  cpu       unlimited
@realtime   -     rtprio    95
@realtime   -     priority  95
@realtime   -     nice      -19
@realtime   -     memlock   unlimited
```
