### ISSUE TITLE
add xdg-desktop-portal-wlr

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#2963]
Must have to screen sharing for Sway and wlr-based compositors
RPM spec is [here](https://github.com/clearfraction/xdg-desktop-portal-wlr/blob/main/xdg-desktop-portal-wlr.spec).

Official package name: xdg-desktop-portal-wlr

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/emersion/xdg-desktop-portal-wlr/releases/tag/v0.7.0

Latest release date (must be recent): April 2023

**Comment by fenrus75** [comment]
added -- will be in the next build (out once it passes QA/etc)

thanks for the suggestion
