### ISSUE TITLE
[Package Update] Solaar 1.1.10 is out

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#2969]
Please update Solaar to the [latest stable release (1.1.10)](https://github.com/pwr-Solaar/Solaar/releases/tag/1.1.10)!

Many thanks!

**Comment by fenrus75** [comment]
interesting timing -- I just had to untag our 1.1.10 update since it fails
QA and blocked a release ;)

now to poke as to why that is exactly (QA complained about dbus-python
dependencies)

**Comment by Aqua1ung** [comment]
40030's got it. Closing. Kudos @fenrus75!!!!
