### ISSUE TITLE
GNOME theme change

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#298]
**Is your feature request related to a problem? Please describe.**
The default theme when using the GNOME desktop, "Arc," is quite old and not being updated anymore (as far as I know). Subjectively, I also find Arc to be somewhat ugly, so users should have some degree of choice without having to install themes outside of the package manager. Additionally, a more modern icon set like Paper or Papirus could be supported as well.

**Describe the solution you'd like**
Switch the default theme to an updated one like Adapta.

**Describe alternatives you've considered**
Default to GNOME's default theme and provide alternative themes as supplementary pundles/bundles.

**Comment by Thisuu** [comment]
@OpenSourceAnarchist FYI Arc theme is actually under a new maintainer now, https://github.com/NicoHood/arc-theme

**Comment by mrkz** [comment]
I just took a quick glance at updating for the new upstream, it likely requires to package Inkscape from our side.

**Comment by fenrus75** [comment]
I’m close to having Inkscape packaged

**Comment by curantes** [comment]
I would highly recommend to add [plata-theme](https://gitlab.com/tista500/plata-theme) its the latest Material design theme from the creator of the well known [adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme). This in combination of [paper-icon-theme](https://github.com/snwh/paper-icon-theme) or [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) would be awesome.

**Comment by OpenSourceAnarchist** [comment]
Plata theme is my absolute favorite. Sleek, modern, and original. I'd love to see it included or even made the default.

**Comment by ikeyd** [comment]
Current default is set to Materia with the Paper icon theme. Multiple icon and GTK/Shell themes are now available in the `desktop` bundle as of latest updates. I believe this resolves this issue?
