### ISSUE TITLE
firewall-cmd python script returns : AttributeError: 'NoneType' object has no attribute 'Get'

### ISSUE THREAD

**Issue by valchevv** [clearlinux/distribution#2990]
here is the full error:

root@cl~ # firewall-cmd 
Error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/firewall/client.py", line 51, in _impl
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/firewall/client.py", line 3170, in get_property
    return dbus_to_python(self.fw_properties.Get(
                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'Get'

**Comment by bryteise** [comment]
Is firewalld running?

**Comment by sandwormusmc** [comment]
I got this today and was confused... it would be more user friendly and intuitive to check if the dependency is running, and present an error that someone could action.
