### ISSUE TITLE
New sof-bin available: 2023.09.1 (2.7.1?)

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#2991]
Please update sof-bin: https://github.com/thesofproject/sof-bin/releases/latest

**Comment by Aqua1ung** [comment]
Looks like it's been done.

**Comment by fenrus75** [comment]
yeah I tried to get this to work yesterday -- they changed a bunch of file
system layout pieces that I hope will work out fine but we'll see

**Comment by Aqua1ung** [comment]
> yeah I tried to get this to work yesterday -- they changed a bunch of file system layout pieces that I hope will work out fine but we'll see

Well, it works fine as far as I can tell. I haven't noticed any issue so far. Hence thanks for devoting your attention to this!
