### ISSUE TITLE
CIFS mount issues in 40330

### ISSUE THREAD

**Issue by TiddaA** [clearlinux/distribution#2995]
CIFS mounts fail for me in version 40330, in  40320it's still working.
I'm getting the following in the journal:

Nov 09 23:05:14 clear2 systemd[1]: mnt-floradisk-backup.automount: Got automount request for /mnt/floradisk/backup, triggered by 2017 (mount.cifs)
Nov 09 23:05:14 clear2 systemd[1]: Mounting mnt-floradisk-backup.mount...
Nov 09 23:05:14 clear2 kernel: CIFS: Attempting to mount //floradisk/backup
Nov 09 23:05:14 clear2 mount[2019]: mount error(126): Required key not available
Nov 09 23:05:14 clear2 mount[2019]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)
Nov 09 23:05:14 clear2 systemd[1]: mnt-floradisk-backup.mount: Mount process exited, code=exited, status=32/n/a
Nov 09 23:05:14 clear2 systemd[1]: mnt-floradisk-backup.mount: Failed with result 'exit-code'.
Nov 09 23:05:14 clear2 systemd[1]: Failed to mount mnt-floradisk-backup.mount.

**Comment by fenrus75** [comment]
any chance you can look in dmesg to see if there's something interesting
there?

**Comment by TiddaA** [comment]
Not much of interest in dmesg:
[   39.867744] calling  init_cifs+0x0/0xfc0 [cifs] @ 1978
[   39.868048] Key type cifs.idmap registered
[   39.868164] initcall init_cifs+0x0/0xfc0 [cifs] returned 0 after 370 usecs
[   39.868443] CIFS: No dialect specified on mount. Default has changed to a more secure dialect, SMB2.1 or later (e.g. SMB3.1.1), from CIFS (SMB1). To use the less secure SMB1 dialect to access old servers which do not support SMB3.1.1 (or even SMB3 or SMB2.1) specify vers=1.0 on mount.
[   39.912204] CIFS: Attempting to mount //floradisk/backup

This is the message I get when doing mount -a:
$ sudo mount -a
Couldn't chdir to /mnt/floradisk/backup: No such device

**Comment by strangecargo** [comment]
I'm having a similar issue in 40360 where SMB mounts that used to work now fail. I don't know when it last worked because this VM had been running without a reboot for several weeks and the mounts had been mounted the whole time:

> # /sbin/mount.cifs "//server/share" /mnt/blargle/ -o guest
> mount error(126): Required key not available
> Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) and kernel log messages (dmesg)

Corresponding dmesg lines:
> [ 1304.897163] CIFS: Attempting to mount //server/share
> [ 1304.904005] vers=2.0 mount not permitted when legacy dialects disabled
> [ 1304.912468] vers=1.0 (cifs) mount not permitted when legacy dialects disabled

The SMB host is a QNAP NAS configured to allow SMB versions between 2.0 and 3 (inclusive).

**Comment by strangecargo** [comment]
Any guidance on what I can do to fix or debug this? If I can't figure this out, I'm just going to have to move this workload off to another OS.

**Comment by TiddaA** [comment]
I switched to NFS to access my NAS as a mitigation.

**Comment by fenrus75** [comment]
I turned the insecure-but-compatible kernel config on in the hope that
would fix this...

**Comment by strangecargo** [comment]
I'm still running into the same issue in 40410. Should your changes be in that version?

**Comment by strangecargo** [comment]
Seems to be working again in 40430.

**Comment by TiddaA** [comment]
I can confirm it is working again as well.
Thanks team!
