### ISSUE TITLE
default install security configurations

### ISSUE THREAD

**Issue by K2** [clearlinux/distribution#30]
I re-read the website and it specifies this repository for issues.  Please see clearlinux/tallow#6 as it was default install in-box with clear at the time of filing.  @matthewrsj  ping.

As an option, consider default install with no services at all.

**Comment by matthewrsj** [comment]
For now it has been removed from the `openssh-server` bundle so will not be on user systems (or default installs) when the next OS version is released. It will be added back when the issue is fixed.

**Comment by ahkok** [comment]
Issue closed upstream, update posted to clearlinux as well.

**Comment by ahkok** [comment]
FTR we put it back in the bundle as well, so there should not be a gap in between releases.
