### ISSUE TITLE
cri-o: cherry-pick upstream host IP fix

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#300]
We are running into https://github.com/kubernetes-sigs/cri-o/issues/1895

Can someone integrate the fix from https://github.com/kubernetes-sigs/cri-o/pull/1924 into Clear Linux or update to a version of cri-o which has the fix?

**Comment by AntonioMeireles** [comment]
Hi all, 

FWIW 1.12.3 is already [tagged](
https://github.com/kubernetes-sigs/cri-o/releases/tag/v1.12.3) since yesterday so that could be a good one to ship :-)

**Comment by mythi** [comment]
@AntonioMeireles thanks for pointing that out. It did not exist by the time @pohly submitted this issue but that'd certainly be easier to move to (just wondering if that will be the next official release).

**Comment by AntonioMeireles** [comment]
@mythi AFAICT "official" releases are done when "major" distros are going to consume them. Otherwise they get just tagged  ... IMHO there should be no big side effects from consuming 1.12.3 until next official one is out (albeit i wouldn't be surprised that given the context 1.12.3 may end being one)

**Comment by AntonioMeireles** [comment]
FWIW - pasted from CRI-O's # at kubernete's slack
<img width="911" alt="image" src="https://user-images.githubusercontent.com/743527/49090524-d127f980-f255-11e8-9b50-9365e46166b9.png">

**Comment by mythi** [comment]
@AntonioMeireles thanks! I'll update asap

**Comment by AntonioMeireles** [comment]
@mythi fwiw - per https://github.com/kubernetes-sigs/cri-o/releases 1.12.3 *official* now

**Comment by mythi** [comment]
@AntonioMeireles pushed, thanks!

**Comment by AntonioMeireles** [comment]
afaict this can no be closed :-)
