### ISSUE TITLE
[Bug] Chromium-based browsers GPU acceleration broken.

### ISSUE THREAD

**Issue by Cueropedo** [clearlinux/distribution#3012]
Using OS version 40540, and Microsoft Edge Version 120.0.2210.91 (Official build) (64-bit), the browser starts corrupting graphics if GPU acceleration is enabled. This happens using the browser normally, ater some sessions, it will bug out. 
The two workarounds for this are either delete all GPUCache related files, or to disable completely GPU acceleration.
This didn't happen in the past, heard is related to a Mesa bug.

**Comment by Aqua1ung** [comment]
https://community.clearlinux.org/t/latest-cl-releases-break-chrome/9075/5

**Comment by Cueropedo** [comment]
> https://community.clearlinux.org/t/latest-cl-releases-break-chrome/9075/5

I saw what you posted on the forums now. Just a question, had this bug been fixed for you? In my case Edge keeps corrupting graphics after a while. I do delete the GPUCache folder, but eventually graphics will be messed up again.

**Comment by Aqua1ung** [comment]
The only thing that "fixes" this is to disable Chrome's hardware acceleration.

Somebody needs to do something about this!

**Comment by Cueropedo** [comment]
I think this was fixed, my Chromium apps/Electron are not having issues anymore!
