### ISSUE TITLE
mime.cache not updated when new packages installed

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#302]
/usr/share/mime/mime.cache is a static file and does not get updated when new files are created in /usr/share/mime/packages. Example:
```
$ ls -l /usr/share/mime/mime.cache /usr/share/mime/packages 
-rw-r--r-- 2 root root 134468 Jul  1 17:43 /usr/share/mime/mime.cache

/usr/share/mime/packages:
total 2444
-rw-r--r-- 1 root root 2280389 Jul  1 17:43 freedesktop.org.xml
-rw-r--r-- 1 root root    5732 Mar 27  2018 gcr-crypto-types.xml
-rw-r--r-- 1 root root  211996 Nov 10 08:18 kde5.xml
```

By using the Qt5 `QMimeDatabase` class, access both databases. It prints:

```
$ ./qmimetest 
There are 779 MIME types in the database.
$ QT_NO_MIME_CACHE=1 ./qmimetest
There are 847 MIME types in the database.
```

**Comment by fenrus75** [comment]
Since usr is read only, need to move this to /var somehow

**Comment by thiagomacieira** [comment]
If I run `update-mime-database`, it updates this file, but it also creates a bunch of other files in /usr/share/mime (other than /usr/share/mime/packages).

**Comment by josuedhg** [comment]
is there an XDG variable where KDE and GNOME search for mime cache folder  XDG_DATA_DIRS, we add /var/cache/ to this in flatpack repo which define the variable and there is a patch for glib-compile-schemas that create the mime.cache in /var/cache/applications/ folder

**Comment by thiagomacieira** [comment]
Not for the cache alone. We could set XDG_DATA_DIRS to `/usr:/var/cache/xdg:/usr/local` but everything that depends on XDG_DATA_DIRS would start looking for things there too.

And that's not how the cache is supposed to work. I believe there's one mime.cache per dir, so placing it in /var/cache/mime (or /var/cache/xdg/mime) won't help for source files placed in /usr/share/mime/packages.

No, I think symlinking like the one I prototyped is the only solution.
```
$ ls -ld /usr/share/mime /var/cache/mime/packages 
lrwxrwxrwx 1 root root 20 Nov 27 10:23 /usr/share/mime -> ../../var/cache/mime
lrwxrwxrwx 1 root root 32 Nov 27 10:25 /var/cache/mime/packages -> ../../../usr/share/mime-packages
 ``

**Comment by thiagomacieira** [comment]
25660 should fix this.

**Comment by ahkok** [comment]
I think @thiagomacieira means `26560`

**Comment by thiagomacieira** [comment]
26660 had it but was missing one thing. 26670 should be fine.
