### ISSUE TITLE
FreeRDP 3.2.0

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3024]
Official package name: FreeRDP

License (must be an OSI approved Open Source license): Apache License 2.0

Download URL of latest release: https://github.com/FreeRDP/FreeRDP/releases/tag/3.2.0

Latest release date (must be recent): Jan 19, 2024

**Comment by fenrus75** [comment]
this one seems to have gained some... evil depedencies like wekitgtk gen 4 (we're at gen 6)

**Comment by fenrus75** [comment]
And of course it breaks compatibility with itself (soname change) with is kind of rude ;(
