### ISSUE TITLE
rclone update to 1.65 introduced bug

### ISSUE THREAD

**Issue by schiele** [clearlinux/distribution#3026]
With the rclone update to 1.65 you introduced the bug described upstream in https://forum.rclone.org/t/onedrive-fails-to-list-certain-files-1-65/43104, making rclone practically unusable with Microsoft OneDrive. The mentioned upstream bug report includes a fix to the problem. Please consider including the fix with ClearLinux.

**Comment by thiagomacieira** [comment]
They've deleted the branch that contained the fix. Do you know the link to the commit or the PR with the fix?

**Comment by fenrus75** [comment]
they did a 1.6.5.1 release which we're rebasing to

**Comment by schiele** [comment]
Problem is resolved now with rclone-1.65.1-70.
