### ISSUE TITLE
Updating to 40690 (and 40700) shows "get_mempolicy: Function not implemented" in many cases.

### ISSUE THREAD

**Issue by lars-whta** [clearlinux/distribution#3028]
After updating to 40690, from 40680, "get_mempolicy: Function not implemented" is shown when running various programs and functions.
E.g. the Intel oneAPI "setvars.sh":

```
get_mempolicy: Function not implemented

:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments:
:: compiler -- latest
get_mempolicy: Function not implemented
:: debugger -- latest
get_mempolicy: Function not implemented
:: mkl -- latest
get_mempolicy: Function not implemented
:: mpi -- latest
get_mempolicy: Function not implemented
:: tbb -- latest
get_mempolicy: Function not implemented
:: oneAPI environment initialized ::
```

Downgrading to 40680 (swupd repair -m 40680 --force) fixes this problem:
```
:: initializing oneAPI environment ...
   -bash: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments:
:: compiler -- latest
:: debugger -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: oneAPI environment initialized ::
```

I think Matlab (R2023a) also showed the same "get_mempolicy: Function not implemented", but it is not limited to those two programs.

This is running under WSL (Windows 11 Build 23619.1).

**Comment by fenrus75** [comment]
trying to figure out where this comes from --

**Comment by fenrus75** [comment]
get_mempolicy was added in linux 2.6.7... that's a long time ago.
Clearly something in the OS started to be more numa aware..... but somehow
WSL does not support this and it seems that it is WSL that prints this not
something in our stack -- at least grep on this text is not very successful
for me yet

**Comment by nrk-akjaer** [comment]
Just wanted to chime in and say that it's happening to me on WSL+Arch too.

Shouldn't be related to WSL Kernel, as that hasn't changed so my guess would be systemd...? Or maybe even Defender.

**Comment by EkriirkE** [comment]
Getting this on arch as well, doesn't seem to affect anything just lots of annoying error popup messages

**Comment by mk-fg** [comment]
Seem to be an issue with libnuma.so issuing that warning on init whenever anything loads it.
Should be fixed in upstream git by https://github.com/numactl/numactl/issues/212 I think, though there's no release incorporating the change atm, will probably be in 2.0.18+.

**Comment by lars-whta** [comment]
Fixed as of 40830 (or slightly earlier)
