### ISSUE TITLE
improve https://download.clearlinux.org/releases/ useability

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#303]
Hi all!, 

the recent changes on the infra that hosts https://download.clearlinux.org/releases/ had a _side effect_ that resulted in the _loss_ of the previous '_template_' which allowed to sort/browse releases by date, a feature that IMHO, is very handy and that i, at least, miss a lot. hereby the suggestion to bring back that feature when possible.

Thanks in advance!

**Comment by ahkok** [comment]
Noted, I had the same feeling about this myself.

**Comment by ahkok** [comment]
@nesiusra  is this something we can get enabled?

**Comment by iphutch** [comment]
This is a WIP!

**Comment by iphutch** [comment]
@diaung could you please comment when this work is complete so we can close.

**Comment by AntonioMeireles** [comment]
while on this ... 

at sigh *everything* under https://download.clearlinux.org/releases/ is now served with `Content-Type: application/octet-stream` which is IMHO clearly sub-optimal. `*RELEASENOTES*` and `*.log$` files should, at least, be served with `Content-Type: text/plain`, so that they could be read via browser normally...   

All the Best, 

António

**Comment by AntonioMeireles** [comment]
meanwhile, a quick  _workaround_ can be found **[here]( https://dev.to/antoniomeireles/easily-track-clear-linux-releases-from-your-shell-1bi7)**...

**Comment by mrkz** [comment]
@AntonioMeireles there's no click to sort yet, but they've been recently sorted by date again, you may want to check if that's helpful enough.

**Comment by nesiusra** [comment]
I just verified RELEASENOTES is readable in the browser. I think this issue has largely been resolved as best as it can be. I'm going to close this.
