### ISSUE TITLE
Update npm to the latest stable release: 10.4.0

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3030]
https://github.com/npm/cli/releases/tag/v10.4.0

**Comment by fenrus75** [comment]
npm actually comes from nodejs for us -- but yeah we can update that to a
current LTS

looking at that now

**Comment by Aqua1ung** [comment]
> looking at that now

Thank you! While you're at it, you may want to look into [this one](https://github.com/clearlinux/distribution/issues/3024) as well please.
