### ISSUE TITLE
Silent jump from 40950 to 40960?

### ISSUE THREAD

**Issue by lars-whta** [clearlinux/distribution#3039]
When updating to 40950, the system suddenly reports itself as 40960:

```
Update started
Preparing to update from 40830 to 40950
Downloading packs for:
 - FreeRDP
 - binutils
 - c-basic
 - dev-utils
 - devpkg-bash-completion
 - devpkg-taglib
 - linux-tools
 - os-core
 - os-core-update
 [100%]

Finishing packs extraction...

Statistics for going from version 40830 to version 40950:

    changed bundles   : 9
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 6
    new files         : 0
    deleted files     : 0

Validate downloaded files
 [100%]

No extra files need to be downloaded
 [100%]

Installing files...
 [100%]

Update was applied
Calling post-update helper scripts
Update took 21.9 seconds, 4 MB transferred
Update successful - System updated from version 40830 to version 40950
Update started
Version on server (40960) is not newer than system version (40960)
Update complete - System already up-to-date at version 40960
```

**Comment by fenrus75** [comment]
this is an interesting way of how we do "format bumps" -- which are a way
for us to make sure people updating from older versions "visit" a specific
version before going to newer versions.
(this is something we need to be able to do for cases where some
incompatibility happens -- where the last version of the old "format"
supports the new world, which is then a new version)

so 40850 and 40860 are the same content wise -- but 40850 is the last
version in the saga of the old format, while 40860 is the first of the new
format.

**Comment by lars-whta** [comment]
Aha, ok. I've seen the intermediate updates when updating from old images, but never that the versions actually relabel themselves.
