### ISSUE TITLE
PLEASE PLEASE PLEASE READD SWAY PLEASE

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/distribution#3044]
Official package name:

License (must be an OSI approved Open Source license):

Download URL of latest release:

Latest release date (must be recent):

Description:

**Comment by fenrus75** [comment]
woops
added it back

it was not the intent to remove this -- going to chase down which part of
the automation did this

**Comment by Polish-Civil** [comment]
Also, the i3 is gone :/ It would be really nice if someone upgraded wlroots and the sway version along with this fix.
