### ISSUE TITLE
wlroots 0.16.2 to 0.17.1

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3049]
Official package name: wlroots

License (must be an OSI approved Open Source license): MIT License

Download URL of latest release: https://gitlab.freedesktop.org/wlroots/wlroots/-/releases/0.17.1

Latest release date (must be recent): Dec 22, 2023

**Comment by K1ngfish3r** [comment]
since wlroots.pc still reports itself as 0.16.2 reopened this issue, related issue https://github.com/clearlinux/distribution/issues/3045

**Comment by fenrus75** [comment]
so it turns out wlroots was updated, but it broke compatibility in the 0.17
release so we had to undo this -- we can't break the primary user of it
(sway) after all

**Comment by K1ngfish3r** [comment]
Update to sway? https://github.com/swaywm/sway/releases/tag/1.9
It suggests supporting wlroots 0.17

**Comment by fenrus75** [comment]
yeah did that Saturday when I saw the new sway and well I know folks cared

**Comment by paulcarroty** [comment]
Nice, came here to request the update :D Seems like it's available in 41130, so this issue can be closed.
