### ISSUE TITLE
Unable to add RPMs to mixin

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#305]
**Describe the bug**
Following the wiki page on mixin, unable to successfully had RPMs that I built

**To Reproduce**
1. mkdir ~/myrepo
2. cp ~/clearlinux/packages/blender/rpms/*.rpm ~/myrepo
3. cd ~/myrepo; createrepo_c .
4. sudo mixin repo add mylocalrepo file:///home/seanvk/myrepo/
5. sudo mixin package add blender --bundle blender-bundle

Where blender packages are like blender-2.79b-3.x86_64.rpm, blender-bin-2.79b-3.x86_64.rpm, etc...

ERROR: no such package

**Expected behavior**
Adds the rpms for the bundle

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`current`]

**Additional context**

**Comment by ahkok** [comment]
`flatpak install flathub org.blender.Blender`

`mixin` bugs should be filed against github.com/clearlinux/mixer-tools preferably.

**Comment by seanvk** [comment]
My goal is not to add blender as a flatpack, my goal is to actually add blender to Clear.  So I'll file the bug with mixer-tools.

**Comment by ahkok** [comment]
the correct spelling is `flatpak`, though. Adding blender to clear should be done by fixing the unfinished package we have in git :)

**Comment by ahkok** [comment]
Using the upstream RPM is definitely not preferred over flatpak. Using mixin may cause stuff to break. Flatpak gives your application good separation from OS files.

**Comment by seanvk** [comment]
See me for details if interested @ahkok I have a new one.
