### ISSUE TITLE
Mesa has correct libraries but missing the i686 loaders

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3053]
CL Version as of time of writing: 41120
See related issue: https://github.com/clearlinux/distribution/issues/1437#issuecomment-1728243842
Manually adding the missing files fixes the issue
```
i@clr~ $ sudo swupd search-file /usr/share/vulkan/icd.d/
Downloading all Clear Linux manifests
 [100%]

Searching for '/usr/share/vulkan/icd.d/'

Bundle lib-opengl [installed] (2733 MB on system)
	/usr/share/vulkan/icd.d/radeon_icd.x86_64.json
	/usr/share/vulkan/icd.d/lvp_icd.x86_64.json
	/usr/share/vulkan/icd.d/intel_icd.x86_64.json
	/usr/share/vulkan/icd.d/intel_hasvk_icd.x86_64.json
```
should report like so
```
i@clr~ $ ls /usr/share/vulkan/icd.d/
intel_hasvk_icd.i686.json    intel_icd.i686.json    lvp_icd.i686.json    radeon_icd.i686.json
intel_hasvk_icd.x86_64.json  intel_icd.x86_64.json  lvp_icd.x86_64.json  radeon_icd.x86_64.json

i@clr~ $ cat /usr/share/vulkan/icd.d/radeon_icd.i686.json 
{
    "ICD": {
        "api_version": "1.3.277",
        "library_path": "/usr/lib32/libvulkan_radeon.so"
    },
    "file_format_version": "1.0.0"
}

i@clr~ $ cat /usr/share/vulkan/icd.d/radeon_icd.x86_64.json 
{
    "ICD": {
        "api_version": "1.3.277",
        "library_path": "/usr/lib64/libvulkan_radeon.so"
    },
    "file_format_version": "1.0.0"
}
```

**Comment by fenrus75** [comment]
I'll check but...
are there actually games using vulkan that are 32 but? on the face if it
one would think 32 bit games are legacy and thus not vulkan
but obviously that assumption could be wrong

**Comment by K1ngfish3r** [comment]
Any wine games that on lutris seem to fail instantly (Starcraft II on Battlenet launcher) and I am unable to play
`Required Vulkan extension VK_KHR_surface not supported`

Steam also has a similar error message that vulkan is unable to initialize, but games seem to run fine (dota2), 
```
Vulkan missing requested extension 'VK_KHR_surface'.
Vulkan missing requested extension 'VK_KHR_xlib_surface'.
BInit - Unable to initialize Vulkan!
```
[Full logs](https://gist.github.com/K1ngfish3r/e454a493ac131a99cdd55c4089582eb6)
