### ISSUE TITLE
[Missing Instructions] mpv bundle "/usr/lib64/libSvtAv1Enc.so.1: CPU ISA level is lower than required"

### ISSUE THREAD

**Issue by Cueropedo** [clearlinux/distribution#3055]
As of Clear Linux 41120, the mpv swupd bundle doesn't work on my CPU Intel Celeron N2808 due to missing instructions.
I believe the bundle has to be recompiled with older instructions so it is backwards compatible with older/basic processors like mine?

**Comment by fenrus75** [comment]
in theory the way this is supposed to work is that we compile for multiple
iSA versions and then we install on the system only the "best for this CPU"
version.

but it seems mpv does not get this correct and is overeager in this during
its build process -- will look

**Comment by fenrus75** [comment]
found the cause of this -- the STV-AV1 package has an interestingly broken
makefile and (long story short) the next release should have this fixed

**Comment by Cueropedo** [comment]
Awesome, thank you!
