### ISSUE TITLE
xwayland support for wlroots

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3056]
I receive the following error when trying to build [gamescope](https://github.com/ValveSoftware/gamescope) whilst trying to use wlroots from clear linux 

```src/meson.build:146:4: ERROR: Problem encountered: Cannot use wlroots built without xwayland support```

Is it possible to add support for this?

**Comment by fenrus75** [comment]
I'll take a look -- I thought it was there but....

**Comment by fenrus75** [comment]
ok it was in the buildroot but wlroots changed how they detected xwayland
-- fixed for the next build
