### ISSUE TITLE
linux-kvm kernel doesn't support conntrack zones

### ISSUE THREAD

**Issue by yongfengdu** [clearlinux/distribution#306]
the linux-kvm config:
https://github.com/clearlinux-pkgs/linux-kvm/blob/master/config#L936
the linux config has this option set:
https://github.com/clearlinux-pkgs/linux/blob/master/config#L1088

CONFIG_NF_CONNTRACK_ZONES is not set for linux-kvm kernel, this is needed for openstack kolla support.
refer to this for how openstack use the conntrack zone feature:
https://specs.openstack.org/openstack/neutron-specs/specs/liberty/conntrack-zones.html

**Comment by fenrus75** [comment]
ok fair enough, just fixed this, will be in the next release (pending QA)

**Comment by yongfengdu** [comment]
Verified this works fine at latest version.
root@clear-3 ~/kolla-clearlinux # uname -a
Linux clear-3 4.19.5-298.kvm #2 SMP Sun Dec 2 06:16:56 UTC 2018 x86_64 GNU/Linux
root@clear-3 ~/kolla-clearlinux # swupd info
Installed version: 26650
