### ISSUE TITLE
AWS marketplace page has outdated URLs and email link on it

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/distribution#3060]
https://aws.amazon.com/marketplace/pp/prodview-etajttzzjzs24
In the section 
Additional Resources
[Clear Linux Project Website](https://clearlinux.org/) 
[Clear Linux OS Documentation](https://docs.01.org/clearlinux)

Should be 
[Clear Linux Project Website](https://www.clearlinux.org/) 
[Clear Linux OS Documentation](https://www.clearlinux.org/clear-linux-documentation/index.html)

And remove the email support link to the dead dev@clearlinux.org email address

**Comment by pixelgeek** [comment]
@bryteise -  We can substitute 'dev@clearlinux.discoursemail.com' for 'dev@clearlinux.org' now.

**Comment by djklimes** [comment]
looks like this is completed.  Verify an close?

**Comment by pixelgeek** [comment]
Completed, closed - Thanks!
