### ISSUE TITLE
The clr-power service may not enable autogroup automatically

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#3065]
I have the entry commented out in `/etc/clr-power-tweaks.conf`, and expected it to be enabled automatically.
```text
# /proc/sys/kernel/sched_autogroup_enabled 1
```

It seems the clr-power-tweaks service may not realize running the client OS. Therefore, not enable the autogroup knob automatically. The service does run, at least, as other settings in `/etc/clr-power-tweaks.conf` are configured.

https://github.com/clearlinux/clr-power-tweaks/commit/e77b6c564899dc9e935674a58ad41723e3335773

**Comment by fenrus75** [comment]
hmm the algorithm for detecting client is not fool proof but it kinda works
like this

1) check if it's a known server CPU ID (Xeon etc)
...

3) Check the ACPI table of what the bios says it is

which comes from

cat /sys/firmware/acpi/pm_profile

can you check what your machine is reporting there?

**Comment by marioroy** [comment]
```bash
$ cat /sys/firmware/acpi/pm_profile
1
```

**Comment by marioroy** [comment]
Fixed in 41180. Many thanks :)
