### ISSUE TITLE
UxPlay 

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3066]
Official package name: UxPlay

License (must be an OSI approved Open Source license): GPL3

Download URL of latest release: https://github.com/FDH2/UxPlay, https://github.com/FDH2/UxPlay?tab=readme-ov-file#building-an-installable-rpm-package

Latest release date (must be recent): very recent 😁

Description: Mirror iPad onto Linux

**Comment by bwarden** [comment]
Bundle `UxPlay` coming soon

**Comment by Aqua1ung** [comment]
> Bundle `UxPlay` coming soon

You guys ARE ON FIRE!!! 🥰

How about trying your hand at Rustdesk? 🤔

https://github.com/clearlinux/distribution/issues/2903
