### ISSUE TITLE
The entirety of https://www.clearlinux.org/ is in the header of https://community.clearlinux.org/

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3067]
I think the header can be safely removed.
[Screencast from 2024-03-06 15-03-29.webm](https://github.com/clearlinux/distribution/assets/26593485/dd6d712f-4c85-4023-bfae-2ef28afed2f6)

**Comment by pixelgeek** [comment]
Interesting.  Can you provide a bit more information?  What OS, which browser are you using, what's your resolution, and are you logged in to the community forum?  
I'm not seeing this behaviour on my laptop (Microsoft Edge or Firefox) under Windows....

**Comment by K1ngfish3r** [comment]
> Interesting. Can you provide a bit more information? What OS, which browser are you using, what's your resolution, and are you logged in to the community forum, and if so, which theme are you using? I'm not seeing this behaviour on my laptop (Microsoft Edge or Firefox) under Windows....

CL 41170
Firefox 123.0.1
1920x1080

My bad for not providing basic info

But anyway it looks perfectly fine now! I'll close this issue

**Comment by marioroy** [comment]
@pixelgeek This may be hard to see. The image is shown in the center of the region initially, upon loading the page. Then left justified. It looks annoying seeing the image jump from the center to left side.

**Comment by marioroy** [comment]
@pixelgeek This may be hard to see running Firefox; more noticeable in Chrome/Chromium.

The image is shown in the center of the region initially, upon loading the page. Then left justified. Well, it looks annoying seeing the image jump from the center to the left side. Perhaps Chrome defaults to center, when a CSS rule is not specified.

**Comment by pixelgeek** [comment]
I've seen it. I don't know there's much I can do to change the way that the
browser loads and displays the logo, short of making a small PNG instead of
an SVG, but I don't want to have to deal with sizing it for different
resolutions....

**Comment by marioroy** [comment]
Thank you for checking. It turns out not to be the image. The image location is fine. What is happening is the text **Clear Linux* Project** appears centered momentarily, inside the div area. One way to resolve the issue is specifying the HTML div align attribute.

https://www.geeksforgeeks.org/html-div-align-attribute/

**Comment by marioroy** [comment]
Yikes! My apologies. The div align attribute is not supported by HTML5. It has been a while :) Well then, CSS text-align.

https://www.freecodecamp.org/news/how-to-align-text-in-html/
