### ISSUE TITLE
Missing libwinecrt0.a in wine bundle

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3069]
With reference to: https://community.clearlinux.org/t/nvidia-libs-in-wine/9493

I tried building the package in question and ended up running into the following error
`/usr/bin/ld: cannot find -lwinecrt0: No such file or directory`
`swupd search-file` doesn't seem to find this, 
```bash
i@clr~ $ sudo swupd search-file libwine
Downloading all Clear Linux manifests
 [100%]

Searching for 'libwine'

Bundle wine [installed] (6050 MB on system)
	/usr/lib64/wine/libwinevulkan.a
	/usr/lib64/wine/libwinegstreamer.delay.a
	/usr/lib64/wine/libwined3d.a
	/usr/lib32/wine/libwinevulkan.a
	/usr/lib32/wine/libwinegstreamer.a
	/usr/lib32/wine/libwined3d.a
```
nor is it available in the CL dnf repository.
The file in question is `libwinecrt0.a` and can be found in [wine-devel](https://fedora.pkgs.org/rawhide/fedora-x86_64/wine-devel-9.1-1.fc40.x86_64.rpm.html) packages of the fedora repo and in [libwine-dev](https://packages.debian.org/search?mode=exactfilename&suite=bookworm&section=all&arch=any&searchon=contents&keywords=libwinecrt0.a) in the debian repo

**Comment by fenrus75** [comment]
there should be a wine-dev bundle in the next release that has these files
in it
