### ISSUE TITLE
no network if VM defined with other network adapter type

### ISSUE THREAD

**Issue by amitaysh** [clearlinux/distribution#307]
Under VM (ex. VirtualBox) you MUST define your network adapter as "Intel PRO/1000 MT Desktop"
in any other case you won't have network (ex. leaving it as default "PCnet-PCI II")

1. import .vmdk to your favorite hypervisor OR create new machine with .iso installation file
2. set your machine's network adapter type to any type different than "Intel PRO/1000 MT Desktop"

Expected: all should work, and you should have network connection
Actual: if you imported .vmdk - you'll get an error that "Curl error: (6) couldn't resolve host name"
            if you are trying to install new machine via .iso - installation will fail with same error

screenshot attached, the ones that prefixed with "no_net" are the ones with other adapter, the ones that are prefixed with "net" are the ones with "correct" adapter.

![net_installation_done](https://user-images.githubusercontent.com/43682836/49325619-5d843600-f54e-11e8-998f-62a0c83284cc.PNG)
![net_interface](https://user-images.githubusercontent.com/43682836/49325620-5d843600-f54e-11e8-80f6-4788daad4b42.PNG)
![no_net_installation_failed](https://user-images.githubusercontent.com/43682836/49325621-5e1ccc80-f54e-11e8-8137-89495744872d.PNG)
![no_net_log](https://user-images.githubusercontent.com/43682836/49325622-5e1ccc80-f54e-11e8-9c18-f17ef6efaabf.PNG)
![no_net_no_interface](https://user-images.githubusercontent.com/43682836/49325623-5e1ccc80-f54e-11e8-8038-0930e9a4f8ad.PNG)

 - Clear Linux OS version: [`cat /usr/lib/os-release`] - VERSION 1
 - Bundles: [e.g. `sudo swupd bundle-list`] - I wasn't able to install any bundles yet due to the network issue.

**Comment by amitaysh** [comment]
I see now that the files names are gone, sorry for that, so the first 2 screenshots are with "correct" adapter type and the last 3 are with any other adapter type.

**Comment by ahkok** [comment]
`linux-kvm-4.19.5-298` has this enabled (so ONLY the -kvm kernel has this driver). Clear Linux version `26610` or later has this.
