### ISSUE TITLE
clear-26580-installer.img boot hang on HP Skylake server

### ISSUE THREAD

**Issue by EthanZHF** [clearlinux/distribution#308]
**Describe the bug**
Failed to boot clear-26580-installer.img on HP Skylake server 

**To Reproduce**
1.  load clear-26580-installer.img with iLo 
2.  boot into img
3.  hang on following message.

**Expected behavior**

Boot okay :)

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by EthanZHF** [comment]
lspci and dmidecode log see attached file.


[lspci -tvvv.txt](https://github.com/clearlinux/distribution/files/2637840/lspci.-tvvv.txt)

**Comment by EthanZHF** [comment]
Access to the server 
Ilo: 10.239.48.106
USER: Administrator
PW: R7TDJ57B

Just leave a message to me via skype or mail if you are trying to booting it with Clear linux iso(img)

**Comment by EthanZHF** [comment]
Tried an old clear-25000-installer.iso.xz  build,  the same result

![25000](https://user-images.githubusercontent.com/44890887/49361498-2ca32d00-f717-11e8-8942-0c69b3466741.jpg)

**Comment by miguelinux** [comment]
@EthanZHF please do not expose internal data

**Comment by ahkok** [comment]
For `iLo` specifically, we publish the ISO images. Can you try the ISO images we publish?

**Comment by EthanZHF** [comment]
> For `iLo` specifically, we publish the ISO images. Can you try the ISO images we publish?

I tried "clear-26580-installer.img ", iLo could load this img via "img from other media", and I could
see the boot process.
Any other ISO to try ?

**Comment by ahkok** [comment]
> I tried "clear-26580-installer.img ", iLo could load this img via "img from other media", and I could
see the boot process.

If it boots, what is the problem? Does this work now?

**Comment by tpleavitt** [comment]
@EthanZHF , is this still an issue?  Please close if not

**Comment by EthanZHF** [comment]
Okay ， close it。
