### ISSUE TITLE
SDDM Breeze Theme Shows Errors

### ISSUE THREAD

**Issue by mfdemicco** [clearlinux/distribution#3084]
Release 41350. The KDE distribution SDDM Breeze theme shows error messages and the wrong theme screen as per the attached screen shot:
![ae78617086359951c08006695fab9248010a794b_2_1332x1000](https://github.com/clearlinux/distribution/assets/121449512/e4e372a4-bb98-4859-a51f-e9436d6e3629)

The Maldives theme works without issue, however.

**Comment by thiagomacieira** [comment]
That message hasn't existed in Qt since 5.15, so this shouldn't be happening.
qt/qtdeclarative@1eb20d70619cc896fc283bd6605b257a8750c518

**Comment by mfdemicco** [comment]
I see that SDDM is up to version 0.21. Arch Linux is using that version. Maybe include that version in the next release?

**Comment by mfdemicco** [comment]
I also noticed that sddm and sddm.conf are missing their man pages. Please correct.

**Comment by mfdemicco** [comment]
Bug fixed with CL version 41560.
