### ISSUE TITLE
missing Qt5 qmake binary

### ISSUE THREAD

**Issue by schiele** [clearlinux/distribution#3086]
With commit

```
commit 879dcf288d273c116e31a8fcb18cfa6103578cbb (HEAD -> main, tag: 5.15.2-134, origin/main, origin/HEAD)
Author: Arjan van de Ven <arjan@linux.intel.com>
Date:   Tue Mar 26 15:51:59 2024 +0000

    qtbase: Autospec creation for version 5.15.2
```

you removed the packaging of `/usr/bin/qmake` (among others) without pointing out any reason.

The problem with that is that it essentially makes the package unusable for most Qt5 builds since `qmake` is an essential tool for the process and is still referenced in the package by `/usr/lib64/cmake/Qt5Core/Qt5CoreConfigExtras.cmake`

As a result Qt5 builds now get errors like this:
```
CMake Error at /usr/lib64/cmake/Qt5Core/Qt5CoreConfig.cmake:26 (message):
  The imported target "Qt5::Core" references the file

     "/usr/bin/qmake"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib64/cmake/Qt5Core/Qt5CoreConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib64/cmake/Qt5Core/Qt5CoreConfigExtras.cmake:9 (_qt5_Core_check_file_exists)
  /usr/lib64/cmake/Qt5Core/Qt5CoreConfig.cmake:244 (include)
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package)
  CMakeLists.txt:532 (find_package)
```

**Comment by schiele** [comment]
The same applies to the binaries `/usr/bin/qdbuscpp2xml` and `/usr/bin/qdbusxml2cpp`.

**Comment by fenrus75** [comment]
we have/had a bit of a mess with qt5 and qt6 claiming the same names
I'm moving the qt5 ones to their own directory properly now so that at
least things that use cmake/etc still work correctly

**Comment by schiele** [comment]
Thanks, this is working now with your latest update.
