### ISSUE TITLE
Remote Login settings grayed out

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3089]
@fenrus75: Currently on CL #41430 Remote Login (new in GNOME 46) does not work: its settings are grayed out--see screenshot below.

![Screenshot from 2024-04-08 16-56-23](https://github.com/clearlinux/distribution/assets/12104779/c532566a-3a70-4a50-a422-8131b3146f36)

**Comment by fenrus75** [comment]
That's ... xdmcp

I'm not so sure I want to enable that from a security posture standpoint

**Comment by Aqua1ung** [comment]
> That's ... xdmcp I'm not so sure I want to enable that from a security posture standpoint
I frankly doubt that it has anything to do with xdmcp. This is a [new feature introduced with GNOME 46](https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/merge_requests/139), and I very much doubt that the GNOME devs. would allow for anything insecure in remote sessions.

**Comment by fenrus75** [comment]
ok that's not a gdm feature but remote desktop -- will look over there ;)

**Comment by Aqua1ung** [comment]
"GNOME’s remote desktop experience has been significantly enhanced for version 46, with the introduction of a new dedicated remote login option. This allows remotely connecting to a GNOME system which is not already in use. Connecting in this way means that the system’s display can be configured from the remote side, resulting in a better experience for the remote user."

**Comment by pixelgeek** [comment]
Targeted for the build after 41530.
