### ISSUE TITLE
Current kernels don't boot any longer on bare metal installations.

### ISSUE THREAD

**Issue by schiele** [clearlinux/distribution#3091]
On my bare metal ClearLinux installation, the latest kernels no longer boot the system since they fail to load the initrd since they cannot decompress xz any longer.
Some inspections revealed that in the kernel config, any xz/lzma option was disabled with
```
commit 9ae4fbaae2f2eb29c20bf91b043985afe9be7483
Author: Arjan van de Ven <arjan@linux.intel.com>
Date:   Fri Mar 29 19:21:30 2024 +0000

    box in lzma
```
But initrd still seems to get compressed using xz:
```
rschiele@probook~/clearlinux/packages/linux (main) $ file ~/efiboot/EFI/org.clearlinux/initrd*
/home/rschiele/efiboot/EFI/org.clearlinux/initrd-org.clearlinux.native.6.8.1-1418: XZ compressed data, checksum CRC32
/home/rschiele/efiboot/EFI/org.clearlinux/initrd-org.clearlinux.native.6.8.4-1422: XZ compressed data, checksum CRC32
```
I haven't tested whether it does the same with fresh installations but at least with my automatically updated installation, it seems to continue using xz for compression of initrd, which current kernels can't deal with then.
Was that probably a rushed reaction to the xz backdoor incident?
Is there an option to change the compression method that did not get updated properly or does it fail in general? In the latter case, I am surprised I didn't find another bug report from someone else.

**Comment by fenrus75** [comment]
hmm we did update all our initrd to not use xz compression -- or so we
thought

will investigate what we missed

**Comment by schiele** [comment]
If you need some information from my affected system feel free to ask for it. I keep it running unmodified, just booting with the older kernel version for the time being.

**Comment by fenrus75** [comment]
I just found "one more place" -- will poke more to make sure we had them all

**Comment by schiele** [comment]
This is one place I found: `/usr/lib/kernel/initrd-org.clearlinux.native.6.8.4-1422`

Originating from:
```
rschiele@probook~/clearlinux/packages/linux (main) $ grep -B3 -A3 initrd linux.spec 
    (
      cd cpiofile
      find . | cpio --create --format=newc \
        | xz --check=crc32 --lzma2=dict=1024KiB > ${KernelDir}/initrd-org.clearlinux.${Target}.%{version}-%{release}
    )
}

--
/usr/share/package-licenses/linux

%files cpio
/usr/lib/kernel/initrd-org.clearlinux.%{ktarget}.%{version}-%{release}

%files dev
%defattr(-,root,root)
rschiele@probook~/clearlinux/packages/linux (main) $ 
```

If this is not the same you found then you should add it to your list.

**Comment by schiele** [comment]
FYI: Recompressing the mentioned initrd above to gzip (-n -9) makes the new kernel bootable and fully functional on my system again. Therefore at least for my system there are no other pending issues with the change.

**Comment by schiele** [comment]
Looks good now with the latest kernel update.
