### ISSUE TITLE
GNOME devs fixed mutter 46.0 sync issue for NVIDIA graphics

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#3092]
Re: https://community.clearlinux.org/t/gnome-developers-fixed-mutter-46-0-sync-issue/9563

Mutter is the reason for brokenness, last two major GNOME releases. There's no telling when mutter 46.1 will be released. This is the commit containing the fix.

https://gitlab.gnome.org/GNOME/mutter/-/commit/22689d722ab4e13ab272c3534f5d18a55c94084f

That fixes the lag issues. Also fixes resizing qt windows. Currently, resizing qt windows does not always work using NVIDIA graphics.

I tried compiling Mutter on Clear Linux to no avail... Bundles versus packages woes... Bah... I'm not in the mood to installing gigabytes of bundles just to build Mutter.  So, the reason I copied only mutter-x11-frames from the Arch binary.

Arch Linux cherry picked the mutter fix, seen here.

https://gitlab.archlinux.org/archlinux/packaging/packages/mutter/-/blob/main/PKGBUILD?ref_type=heads#L106

Arch Linux also applies a fix for nouveau, if that matters.

https://gitlab.archlinux.org/archlinux/packaging/packages/mutter/-/blob/main/0001-drm-buffer-gbm-Do-not-call-ensure_fb_id-from-lock_fr.patch

Note: Once mutter 46.1 is released (no telling when), it will require updating the spec file to remove the cherry pick commit as mutter 46.1 will contain the fix.

**Comment by fenrus75** [comment]
I'll take a look

we have a way to flag a patch as a backport so that our automation will
drop it if it sees it's now applied upstream -- so that's no worry for us

**Comment by fenrus75** [comment]
I've put the Arch fix into our build as well -- should show up in the next
couple of days

**Comment by marioroy** [comment]
CL 41540. Mutter is behaving using NVIDIA graphics. Likewise, Gnome terminal is usable.

Thank you @fenrus75, much appreciated. :-)

**Comment by marioroy** [comment]
Re-opening. Right now, the gnome terminal lag issue is still there, (I commented out the workaround). I see the one patch added. Thank you. Missing is the important one. Should I make a patch?

https://gitlab.gnome.org/GNOME/mutter/-/commit/22689d722ab4e13ab272c3534f5d18a55c94084f

Arch Linux cherry picks that one, which fixes mutter.

https://gitlab.archlinux.org/archlinux/packaging/packages/mutter/-/blob/main/PKGBUILD?ref_type=heads#L106

**Comment by marioroy** [comment]
I made a patch file `backport-compositor-sync-ring-Allow-the-gpu_fence-to-be-moved.patch`

```diff
diff -uar a/src/compositor/meta-sync-ring.c b/src/compositor/meta-sync-ring.c
--- a/src/compositor/meta-sync-ring.c
+++ b/src/compositor/meta-sync-ring.c
@@ -544,20 +544,29 @@
 meta_sync_ring_insert_wait (void)
 {
   MetaSyncRing *ring = meta_sync_ring_get ();
+  MetaSync *sync;

   if (!ring)
     return FALSE;

   g_return_val_if_fail (ring->xdisplay != NULL, FALSE);

-  if (ring->current_sync->state != META_SYNC_STATE_READY)
+  sync = ring->current_sync;
+
+  if (sync->state == META_SYNC_STATE_WAITING)
+    {
+      meta_gl_delete_sync (sync->gpu_fence);
+      sync->gpu_fence = 0;
+      sync->state = META_SYNC_STATE_READY;
+    }
+  else if (sync->state != META_SYNC_STATE_READY)
     {
       meta_warning ("MetaSyncRing: Sync object is not ready -- were events handled properly?");
       if (!meta_sync_ring_reboot (ring->xdisplay))
         return FALSE;
     }

-  meta_sync_insert (ring->current_sync);
+  meta_sync_insert (sync);

   return TRUE;
 }
```

**Comment by marioroy** [comment]
I made a patch file `backport-compositor-sync-ring-Allow-the-gpu_fence-to-be-moved.patch`

```diff
# Severe keyboard input lag/pauses on Mutter 46.0, X11, NVIDIA
# https://gitlab.archlinux.org/archlinux/packaging/packages/mutter/-/issues/3
# https://gitlab.gnome.org/GNOME/mutter/-/issues/3384
# https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3685

diff -uar a/src/compositor/meta-sync-ring.c b/src/compositor/meta-sync-ring.c
--- a/src/compositor/meta-sync-ring.c
+++ b/src/compositor/meta-sync-ring.c
@@ -544,20 +544,29 @@
 meta_sync_ring_insert_wait (void)
 {
   MetaSyncRing *ring = meta_sync_ring_get ();
+  MetaSync *sync;

   if (!ring)
     return FALSE;

   g_return_val_if_fail (ring->xdisplay != NULL, FALSE);

-  if (ring->current_sync->state != META_SYNC_STATE_READY)
+  sync = ring->current_sync;
+
+  if (sync->state == META_SYNC_STATE_WAITING)
+    {
+      meta_gl_delete_sync (sync->gpu_fence);
+      sync->gpu_fence = 0;
+      sync->state = META_SYNC_STATE_READY;
+    }
+  else if (sync->state != META_SYNC_STATE_READY)
     {
       meta_warning ("MetaSyncRing: Sync object is not ready -- were events handled properly?");
       if (!meta_sync_ring_reboot (ring->xdisplay))
         return FALSE;
     }

-  meta_sync_insert (ring->current_sync);
+  meta_sync_insert (sync);

   return TRUE;
 }
```

**Comment by marioroy** [comment]
I made a patch file `backport-compositor-sync-ring-Allow-the-gpu_fence-to-be-moved.patch`

```diff
Subject: Severe keyboard input lag/pauses on Mutter 46.0, X11, NVIDIA

When the compositor inserts two waits in a frame, such as [1],
the second insertion shouldn't break the ring's state machine as easily
as it does. We can instead merge the two GL waits into one by simply moving
the GL fence to the latest insertion. Each insertion still does its own X11
sync though.

1. https://gitlab.gnome.org/vanvugt/mutter/-/commit/f606a4424a5afc71672566b15f56971bfb7fa4db

# https://gitlab.archlinux.org/archlinux/packaging/packages/mutter/-/issues/3
# https://gitlab.gnome.org/GNOME/mutter/-/issues/3384
# https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3685

diff -uar a/src/compositor/meta-sync-ring.c b/src/compositor/meta-sync-ring.c
--- a/src/compositor/meta-sync-ring.c
+++ b/src/compositor/meta-sync-ring.c
@@ -544,20 +544,29 @@
 meta_sync_ring_insert_wait (void)
 {
   MetaSyncRing *ring = meta_sync_ring_get ();
+  MetaSync *sync;

   if (!ring)
     return FALSE;

   g_return_val_if_fail (ring->xdisplay != NULL, FALSE);

-  if (ring->current_sync->state != META_SYNC_STATE_READY)
+  sync = ring->current_sync;
+
+  if (sync->state == META_SYNC_STATE_WAITING)
+    {
+      meta_gl_delete_sync (sync->gpu_fence);
+      sync->gpu_fence = 0;
+      sync->state = META_SYNC_STATE_READY;
+    }
+  else if (sync->state != META_SYNC_STATE_READY)
     {
       meta_warning ("MetaSyncRing: Sync object is not ready -- were events handled properly?");
       if (!meta_sync_ring_reboot (ring->xdisplay))
         return FALSE;
     }

-  meta_sync_insert (ring->current_sync);
+  meta_sync_insert (sync);

   return TRUE;
 }
```

**Comment by fenrus75** [comment]
I was going to look at this (but a patch cut and psted into github is not too useful in that github mangles all whitespace etc...

**Comment by marioroy** [comment]
Hi @fenrus75,

I forked the Clear mutter repo.
https://github.com/marioroy/mutter

The mutter 3685 patch 3 for the spec file. This applies cleanly to mutter. (downloadable here)
https://github.com/marioroy/mutter/blob/main/backport-compositor-sync-ring-Allow-the-gpu_fence-to-be-moved.patch

So this is patch number 3 for the mutter.spec file.
Patch3: backport-compositor-sync-ring-Allow-the-gpu_fence-to-be-moved.patch

**Comment by marioroy** [comment]
Seeing the comment at the top of the spec file _"This file is auto-generated. DO NOT EDIT, Generated by: autospec.py"_ is the reason not making a pull-request.

The patch file is downloadable and not need to worry about mangled whitespace.

Thanks,

**Comment by fenrus75** [comment]
excellent
pulling it in now

**Comment by marioroy** [comment]
Thank you, much appreciated.

**Comment by marioroy** [comment]
Thank you for fixing mutter! CL 41560. Keyboard lag issue gone :)
