### ISSUE TITLE
Revert Blender, OBS-Studio, Krita, sshfs removal

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#3093]
This software is super important and works better with Clear performance optimizations.

And this is only a part of the story - the full  41530 changelog is [here](https://download.clearlinux.org/releases/41530/clear/RELEASENOTES).

**Comment by bryteise** [comment]
See the sshfs [readme](https://github.com/libfuse/sshfs) but is barely in maintenance mode. Recommend using rclone instead via its [mount](https://rclone.org/commands/rclone_mount/). Krita and OBS-Studio are coming back but were victims of how we did the KDE6 upgrade.

**Comment by paulcarroty** [comment]
Is OBS planned to re-add anytime soon?
https://community.clearlinux.org/t/autospec-and-submodules/9692

**Comment by fenrus75** [comment]
OBS has been a bit painful to get/keep building, but I'll take a look again
