### ISSUE TITLE
bemenu: empty package

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#3094]
https://github.com/clearlinux-pkgs/bemenu/blob/main/bemenu.spec#L119

**Comment by fenrus75** [comment]
+ gpg --homedir .gnupg --status-fd 1 --verify
/builddir/build/SOURCES/bemenu-0.6.21.tar.gz.asc
/builddir/build/SOURCES/bemenu-0.6.21.tar.gz
gpg: Signature made Wed 13 Mar 2024 02:28:36 AM UTC
gpg:                using RSA key 16B6B7CACAF339DECE9F154729317348D687B86B
gpg: Good signature from "Bemenu Upstream" [expired]
gpg: Note: This key has expired!


ah gpg sig verification fails
