### ISSUE TITLE
Need to update BUG_REPORT_URL in /etc/os-release

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/distribution#3095]
@bryteise 

cat /etc/os-release
 includes....
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"

This should now be 

BUG_REPORT_URL="mailto:dev@clearlinux.discoursemail.com"

(and anywhere else that uses the old email addresses.....)

**Comment by bryteise** [comment]
Should be in the nextish release.
