### ISSUE TITLE
CL 41570, 41580 performance regression 

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#3098]
Is the performance regression due to GCC 14 or glibc update? I'm running an AMD system. Do you guys see performance regression on your side, on Intel systems?

Compiling the kernel is taking much longer. Also, programs run slower.

CL 41560: `time LOCALMODCONFIG=1 ./xm-build edge`  1m41.554s

CL 41580: `time LOCALMODCONFIG=1 ./xm-build edge`  2m15.327s

I rolled back to 41560 to verify.

**Comment by fenrus75** [comment]
our perf data has a few things at -5% and a bunch of things at +5% (but
most are pretty much flat)

will need to check gcc build performance next

**Comment by marioroy** [comment]
Trying something:

I installed GCC-14 from CL 41580 { gcc-14, gcc-dev, gcc-doc, gcc-jit, gcc-libs-math, gcc-libubsan, and gcc-staticdev } onto CL 41560 (extracted the files, copied V3/usr/* usr/*, and moved usr/* to /opt/gcc-14/). I have a post installation script to create a few symbolic links and set the default RPATH. This works well, mitigates setting LD_LIBRARY_PATH.

```bash
#!/bin/bash

# Create symbolic links to system libstdc++.so and glibc-dev files

(
  cd /opt/gcc-14/lib64 || exit 1
  # ln -sf /usr/lib64/libstdc++.so . # undef ref to __cxa_call_terminate
  ln -sf libstdc++.a libstdc++.so    # solution: link to the static file
  for n in crt1 crti crtn gcrt1 grcrt1 Mcrt1 rcrt1 Scrt1; do
    ln -sf /usr/lib64/${n}.o .
  done
)

# Set RPATH default to /opt/gcc-14/lib64

(
  cd /opt/gcc-14/bin || exit 1
  for p in $(file * | grep "ELF 64-bit" | cut -f1 -d:); do
    patchelf --force-rpath --set-rpath /opt/gcc-14/lib64 ${p}
  done
)

(
  cd /opt/gcc-14/lib64/gcc/x86_64-generic-linux || exit 1
  for p in $(find . \( -name cc1 -o -name cc1plus -o -name collect2 \)); do
    patchelf --force-rpath --set-rpath /opt/gcc-14/lib64 ${p}
  done
  for p in $(find . \( -name f951 -o -name lto1 -o -name lto-wrapper \)); do
    patchelf --force-rpath --set-rpath /opt/gcc-14/lib64 ${p}
  done
  for p in $(find . \( -name g++-mapper-server -o -name gengtype \)); do
    patchelf --force-rpath --set-rpath /opt/gcc-14/lib64 ${p}
  done
)
```

The GCC-14 compiler in /opt/gcc-14 works fine, both gcc and g++. I set the PATH to have /opt/gcc-14/bin come first. Building the kernel takes similar time as GCC-13. This is all on CL 41560. What could be causing GCC-14 on 41580 to take longer (> 2m15s) versus (1m42s on 41560)? Could it be changes to CFLAGS or RPM build flags? I did not check for CFLAGS changes when on 41580 yesterday.

**Comment by marioroy** [comment]
It seems GCC-14 is incomplete. Ah, interesting. We now have an experimental gcc as the default in CL 41570+.

```text
gcc (Clear Linux OS for Intel Architecture) 14.0.1 20240416 (experimental) releases/gcc-13.2.0-1003-g3cf5423c55
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Well, I can install GCC 13 from 41560 to /opt/gcc-13 using similar strategy described above.

**Comment by marioroy** [comment]
The CPU firmware update is not happening (nothing in dmesg output). Could this be the reason? I'm on 41610.

**Comment by marioroy** [comment]
I searched for microcode and so that appears to be working.
```text
[    0.296974] microcode: Current revision: 0x0830107b
[    0.296975] microcode: Updated early from: 0x0830104d
```
