### ISSUE TITLE
ceph-volume: fails to run - no module named pkg_resources

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#31]
I'm now trying to get Ceph running on a single node by following
http://docs.ceph.com/docs/master/install/manual-deployment/

At the step where it shows how to invoke ceph-volume I'm running into
this issue:
```
# ceph-volume -h
Traceback (most recent call last):
  File "/usr/bin/ceph-volume", line 3, in <module>
    from ceph_volume import main
  File "/usr/lib/python2.7/site-packages/ceph_volume/main.py", line 4,
in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

Originally reported via email (https://lists.clearlinux.org/pipermail/dev/2018-March/001348.html). The suggestion there was to port the script to Python3. Note that there are probably several more Python2 scripts in Ceph.

**Comment by bryteise** [comment]
The ceph package was updated to resolve this specific issue. Should be fixed in the next release.
