### ISSUE TITLE
Bundle request for dkms and init-rdahead-extras

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#3101]
Re: https://community.clearlinux.org/t/qa-session-removing-the-main-clear-kernel/9616

I'm a ClearMod user and trying to save bandwidth from `swupd` updates. The only way to get `dkms` and `init-rdahead-extras` is by installing a Clear kernel, which I do not use. Can we have a bundle for `dkms` and `init-rdahead-extras`? Or add to the `hardware-uefi` bundle?

Thank you.

There is also, `swupd` should not wipe out `/usr/lib/modules` if other kernels exists on the box i.e. ClearMod.

**Comment by fenrus75** [comment]
this needed 3 changes
1) new bundle for dkms
2) new bundle for initrd-ahead
3) move ownership for the /usr/lib/modules directory away from the kernel
bundles so that deleting the kernel bundles doesn't remove that directory
as well

all three should get into the next release

**Comment by marioroy** [comment]
Thanks Arjan. I will attempt to uninstall the Clear kernel.
1. Update to 41660 from 41560
2. Install the native kernel via swupd (currently, I do not have one installed)
3. Install the new dkms and initrd-ahead bundles
4. For safety measure, backup `/usr/lib/modules` and `/usr/bin/initra-desktop`
5. Uninstall the native kernel via swupd
6. Check `/usr/lib/modules/*xm*` ClearMod modules and `/usr/bin/initra-desktop` (should exist, hopefully)
7. Report back findings

**Comment by marioroy** [comment]
I made a typo and corrected; init-rdahead

**Comment by marioroy** [comment]
Pass :)

One must not roll back to an older Clear release lacking the dkms and init-rdahead bundles.
