### ISSUE TITLE
swupd or clr-boot-manager broken, leaving artifacts in /boot partition after kernel uninstall

### ISSUE THREAD

**Issue by marioroy** [clearlinux/distribution#3106]
CL 41660

Run another kernel before proceeding, LTS or something else.

* install native kernel
`sudo swupd bundle-add kernel-native kernel-native-dkms`
* uninstall the kernel
`sudo swupd bundle-remove linux-dev kernel-native-dkms kernel-native`

The native artifacts exists in the /boot partition. Though, the files in /lib/kernel are removed.

Running `clr-boot-manager update` doesn't clear the artifacts. It requires manual intervention to mount the boot partition and carefully remove the native artifacts.

**Comment by marioroy** [comment]
There are no issues with the ClearMod project. I can install and uninstall kernels. No artifacts remain. So, maybe a swupd issue.

* xm-install bore
* xm-uninstall bore

**Comment by bryteise** [comment]
Not ideal but intentional. clr-boot-manager really wants to avoid somebody swupd bundle-remove on the active kernel and needing to do do a system restore.

**Comment by bryteise** [comment]
We also have a slight problem of knowing what kernel is actually used on the system so if a kernel gets installed it is "tracked" even if it isn't used after booting with it once.

**Comment by bryteise** [comment]
I suppose we could add a clr-boot-manager command that would cleanup all kernels of a given type but it wouldn't be terribly high on my priority list atm.

**Comment by marioroy** [comment]
The issue for users is that the native entry exists in the boot menu, but native files no longer in /lib/kernel folder.

Due to artifacts left behind, users should not remove the swupd installed kernel.

**Comment by marioroy** [comment]
It's not the active kernel. The description mentions using another kernel such as LTS or something else before proceeding.

**Comment by marioroy** [comment]
Please disregard. It's not worth the trouble.
