### ISSUE TITLE
Clear AWS image doesn't update kernel properly

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#311]
When I updated my Clear AWS instance to a newer kernel, the kernel file was installed fine, but got a CBM error and /boot/syslinux.cfg was still configured for the older kernel.  I had to manually edit syslinux.cfg to point to the new kernel.

**Comment by ahkok** [comment]
May have to migrate this to `clr-boot-manager`

**Comment by bktan8** [comment]
Migrated to clr-boot-manager and closed.

**Comment by bktan8** [comment]
Reopened. See https://github.com/clearlinux/clr-boot-manager/issues/132.

**Comment by tpleavitt** [comment]
bug moved, will be closed
