### ISSUE TITLE
bcachefs-tools

### ISSUE THREAD

**Issue by Gorian** [clearlinux/distribution#3114]
### Official package name:
bcachefs-tools

### License (must be an OSI approved Open Source license):
[GPL-2.0 license](https://github.com/koverstreet/bcachefs-tools#GPL-2.0-1-ov-file)

### Download URL of latest release:
https://github.com/koverstreet/bcachefs-tools/releases/tag/v1.7.0

### Latest release date (must be recent):
2024-04-17

### Description:
> Userspace tools and docs for bcachefs

**Comment by bwarden** [comment]
Should be provided in bundle `storage-utils` now.
