### ISSUE TITLE
add dhcp_release command

### ISSUE THREAD

**Issue by xxinran** [clearlinux/distribution#312]
1. OpenStack uses dnsmasq DHCP server to manage its network, it need use dhcp_release command to release a DHCP lease on a the local dnsmasq DHCP server. 
2. On other operating systems like Centos, Ubuntu etc, there is a package named dnsmasq-utils which provides this command. We need to add this to ClearLinux too.

**Comment by ahkok** [comment]
`dnsmasq` is included in several bundles, such as `kvm-host` and `dhcp-server`.

**Comment by ahkok** [comment]
While checking out the code I see that @fenrus75 beat me to it and patched this in. The extra tools in these bundles will be:

```
/usr/bin/dhcp_lease_time
/usr/bin/dhcp_release
/usr/bin/dhcp_release6
```

Give it ~ 2 days for a release to come out with these new tools.

**Comment by fenrus75** [comment]
done, will be in the next release

**Comment by yongfengdu** [comment]
verified that dnsmasq package include dhcp_release
