### ISSUE TITLE
clear-41760-live-server.img won't start on NUC5CPYB

### ISSUE THREAD

**Issue by cphuntington97** [clearlinux/distribution#3121]
I wrote clear-41760-live-server.img to an SD card per the instructions at https://www.clearlinux.org/clear-linux-documentation/get-started/bootable-usb.html#advanced-linux-cli after verifying the SHA sum which passed.

I booted to the SD card in UEFI mode and let Clear Linux try to start, but it crashes.

![PXL_20240526_213423682](https://github.com/clearlinux/distribution/assets/2453866/e7666db5-013b-4c05-a82d-a647cc91024c)

Alternatively, I tried writing the image to a USB flash drive, but it stalled on "waiting for root device" - possibly related to https://github.com/clearlinux/distribution/issues/3090 ?

![PXL_20240526_211441521](https://github.com/clearlinux/distribution/assets/2453866/d5c0097b-133d-4b87-b12d-894c92739340)

I experienced similarly unexpected results with the ISO file, which verified, but also failed to start. I have limited hardware to test on, but wanted to share here in case it's not just me. I have successfully installed earlier versions of Clear Linux many times on this hardware before.

Please let me know if it's possible to record these crash logs in text format, if that would be helpful.

**Comment by paulcarroty** [comment]
Maybe something with SSD drive? Can you test with another one or just detach it?

**Comment by cphuntington97** [comment]
I got the live image to start by checking the box labeled "Boot USB Devices First" under Boot > Boot Configuration > UEFI Boot, and restarting.

I'm not sure why that option should behave any differently than pressing F10 at startup to open the Boot menu and then selecting "UEFI : USB : USB DISK 3.0 PMAP : PART 0 : OS Bootloader," but apparently, it does.

Thanks for commenting @paulcarroty
