### ISSUE TITLE
Suggestions for multiple versions of a package

### ISSUE THREAD

**Issue by flowerseacar** [clearlinux/distribution#3130]
Can you explain this further? Can a Linux system contain multiple versions of dependencies, just like Windows has different versions of .net?

Otherwise, for example, if someone does not redevelop a game from 10 years ago, then it will not be usable in current dependencies.

**Comment by thiagomacieira** [comment]
What does this have to do with Clear Linux? It does contain multiple versions of some packages where useful, but not the entire catalogue.

**Comment by thiagomacieira** [comment]
A Linux system can have two versions of different libraries.
