### ISSUE TITLE
Fastfetch

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3148]
Official package name: Fastfetch

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.16.0.tar.gz

Latest release date (must be recent): Jun 19, 2024

Description: Fastfetch is a [neofetch](https://github.com/dylanaraps/neofetch)-like tool for fetching system information and displaying them in a pretty way.

### Autospec notes:
Requires:
ddcutil (NEW)
chafa (NEW)

### [ddcutil](https://github.com/rockowitz/ddcutil)
tarball URL: https://github.com/rockowitz/ddcutil/archive/refs/tags/v2.1.4.tar.gz
License: GPL-2.0
Release Date: Feb 20, 2024
Description: ddcutil is a Linux program for querying and changing monitor settings, such as brightness and color levels.
changes needed: none, autospec found all deps.

### [chafa](https://github.com/hpjansson/chafa)
tarball URL: https://github.com/hpjansson/chafa/releases/download/1.14.1/chafa-1.14.1.tar.xz
signature: https://github.com/hpjansson/chafa/releases/download/1.14.1/chafa-1.14.1.tar.xz.asc
License: LGPL-3.0 GPL-3.0
Release Date: Jun 18, 2024
Description: Chafa is a command-line utility that converts image data, including animated GIFs, into graphics formats or ANSI/Unicode character art suitable for display in a terminal.
changes needed:
**pkgconfig_add**
```
libavif
libtiff-4
libwebp
libwebpdemux
```

### [fastfetch](https://github.com/fastfetch-cli/fastfetch)
**make_command:** `cmake --build . --target fastfetch --target flashfetch`
**install_macro:** `DESTDIR=%{buildroot} cmake --install .`
**pkgconfig_add**
```
vulkan
wayland-client
xcb-randr
xcb
xrandr
x11
libdrm
gio-unix-2.0
dconf
dbus-1
libxfconf-0
sqlite3
rpm
ImageMagick
zlib
chafa
dri
gbm
osmesa
OpenCL
libnm
libpulse
ddcutil
DirectX-Headers
```

**Comment by bwarden** [comment]
Watch for a new bundle named `fastfetch`.

**Comment by K1ngfish3r** [comment]
Working in 41970
![image](https://github.com/clearlinux/distribution/assets/26593485/24f5fce5-4b49-4524-b114-5e9b8e0acaaf)
