### ISSUE TITLE
Pacman package changed and needs now "netavark" but is not provided

### ISSUE THREAD

**Issue by Pamalosebi** [clearlinux/distribution#3149]
Hello,

I updated my machines to the latest version of CL (VERSION_ID=41960). And now Podman jumped from 4.9.3 to 5.1.1.
Since that update I get this message when trying to work with podman:

> Error: could not find "netavark" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.

So... following the suggestion I am changing my `containers.conf` to use CNI. But that results in:

> Error: cni support is not enabled in this build, only netavark. Got unsupported network backend "cni"

When I want to install "netavark" using swupd I also get an error:

> sudo swupd search netavark
> Password: 
> Search failed, no reasonable results found

Can you provide a package for "netavark" or update the podman build to allow using CNI?
Thank you!

**Comment by bryteise** [comment]
Updated podman to bring in the dependencies and in theory enabled cni networking support. Should be in the next release or so.
