### ISSUE TITLE
Wifi support at install time

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/distribution#315]
A general problem with Clear Linux **installation** is that it only seems to support wired ethernet last I checked. I cannot install Clear at all in a minimal state if I dont have a network. Given it has a hard requirement to perform the installation over the network it means it effectively locks out Clear Linux on a raft of WIFI only systems (yes I know this isn't something a USB dongle cant fix, but it makes it inconvenient enough to deter a lot of use cases - like what if I don't have access to the ethernet ports of the network at work?). 

It should either: 
- Install a minimal system (with wifi drivers baked in) without needing a network and allow one to configure wpa_supplicant later to add more packages. A few Linux distros already do this I believe (like debian minimal install e.g.)
- AND/OR Support Wifi at the outset at install time. This is probably harder to do (UI changes, hardware vagaries, etc) but makes it easier to roll out new Clear based systems.

**Comment by puneetse** [comment]
I'm closing this issue as this has since been added to the new installers. There is documentation available here: https://docs.01.org/clearlinux/latest/get-started/index.html#install
