### ISSUE TITLE
fd

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3153]
Official package name: fd

License (must be an OSI approved Open Source license): Apache-2.0 MIT

Download URL of latest release: https://github.com/sharkdp/fd/archive/refs/tags/v10.1.0.tar.gz

Latest release date (must be recent): May 8, 2024

Description: `fd` is a program to find entries in your filesystem. It is a simple, fast and user-friendly alternative to [`find`](https://www.gnu.org/software/findutils/). While it does not aim to support all of `find`'s powerful functionality, it provides sensible (opinionated) defaults for a majority of use cases.

Autospec notes: [for-review.txt](https://gist.github.com/K1ngfish3r/a0bd158a3bb01202efff09fe4b354a77)
**options.conf**
cargo_vendor = true

EDIT: Realized that the Makefile can be used to install fd
**build_pattern** = make

**series**
add the following patch to change prefix from /usr/local -> /usr
```
diff --git a/Makefile b/Makefile
index b351271..9f8eb04 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 PROFILE=release
 EXE=target/$(PROFILE)/fd
-prefix=/usr/local
+prefix=/usr
 bindir=$(prefix)/bin
 datadir=$(prefix)/share
 exe_name=fd
```

this way, it also installs the bash-completions
```
%files bin
%defattr(-,root,root,-)
/usr/bin/fd

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/fd
/usr/share/fish/vendor_completions.d/fd.fish
/usr/share/zsh/site-functions/_fd

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fd.1
```

**Comment by paulcarroty** [comment]
Would be nice to have, definitely.

**Comment by K1ngfish3r** [comment]
the `fd` bundle released in 42080 is currently broken, recommend the above changes

**Comment by paulcarroty** [comment]
Yep, only licences in `%files`.

**Comment by K1ngfish3r** [comment]
bundle `fd` working properly in 42090, closing
