### ISSUE TITLE
Replace Cheese with Snapshot

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3156]
Official package name: Snapshot

License (must be an OSI approved Open Source license): GNU General Public License v3.0

Download URL of latest release: https://gitlab.gnome.org/GNOME/snapshot/-/releases

Latest release date (must be recent): May 2024

Description: Camera application developed by GNOME, destined to replace Cheese, which is no longer developed. As such, please replace Cheese with Snapshot.

**Comment by K1ngfish3r** [comment]
Autospec notes: [for-review.txt](https://gist.github.com/K1ngfish3r/e659dd52f7ef5fb6ddba12563e6891bd)
URL = https://download.gnome.org/sources/snapshot/46/snapshot-46.3.tar.xz
**build_pattern** = `meson`
**buildreq_add** = `rustc`
note: source comes pre-vendored

**Comment by K1ngfish3r** [comment]
bundle `snapshot` added in 42050, I don't have a camera so...
![image](https://github.com/user-attachments/assets/d519b8c2-eda6-4328-9efe-ab5ed27c653a)

**Comment by paulcarroty** [comment]
Added few weeks ago so this issue can be closed. @Aqua1ung
