### ISSUE TITLE
Desktop Live Beta Image boots to command line on Dell XPS 13

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#316]
**Describe the bug**
Downloaded 26700 of the Desktop live image and it booted only to the command prompt

**To Reproduce**
1. Flash image to stick
2. Boot XPS 13 to stick
3. See command prompt
4. 

**Expected behavior**
See Gnome desktop

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [26700]
 - Bundles: [live image]

**Additional context**
Systemctl status gdm reports it doesn't even exist.  This live image appears to be just a plain headless boot image.

**Comment by ahkok** [comment]
@mrkz

**Comment by seanvk** [comment]
This issue was previously addressed by the Bolt fix.  If you wait long enough it will come up
