### ISSUE TITLE
Replace old NTFS-3G with NTFS3 

### ISSUE THREAD

**Issue by libboj** [clearlinux/distribution#3160]
Hello,

Clear Linux is currently using the userspace NTFS-3G for NTFS drives, but it is no longer updated (https://github.com/tuxera/ntfs-3g) and is slower than Paragon Software's NTFS3 kernel module.

Can the Clear team to enable `NTFS3_FS, NTFS3_LZX_XPRESS `and `NTFS3_FS_POSIX_ACL` in their native kernel please ?

Thanks

**Comment by marioroy** [comment]
Extract from the XanMod configs, if helpful.

https://github.com/xanmod/linux/tree/6.9/CONFIGS/xanmod/gcc

```text
CONFIG_NTFS3_FS=m
# CONFIG_NTFS3_64BIT_CLUSTER is not set
CONFIG_NTFS3_LZX_XPRESS=y
CONFIG_NTFS3_FS_POSIX_ACL=y
```

**Comment by marioroy** [comment]
Extract from the XanMod configs, if helpful.

https://github.com/xanmod/linux/tree/6.9/CONFIGS/xanmod/gcc

```text
CONFIG_NTFS3_FS=m
# CONFIG_NTFS3_64BIT_CLUSTER is not set
CONFIG_NTFS3_LZX_XPRESS=y
CONFIG_NTFS3_FS_POSIX_ACL=y
```

**Comment by fenrus75** [comment]
thanks -- changes made in the kernel , will be in next release

**Comment by marioroy** [comment]
Because you guys do awesome QA, you may have caught that release 42040 NTFS3 is not enabled in the config (extracted linux-6.9.9-1448.src.rpm) even though mentioned in the release notes.

**Comment by fenrus75** [comment]
there are many things we test. NTFS is not one of those.

I'll check

**Comment by libboj** [comment]
Can you give us a date for when it's going to be usable ?

**Comment by bwarden** [comment]
Will be in https://github.com/clearlinux-pkgs/linux/releases/tag/6.9.9-1449 or later -- this should update when it's actually released.
