### ISSUE TITLE
libva: error: failed to resolve wl_drm_interface(): /usr/lib64/libEGL_mesa.so.0: undefined symbol: wl_drm_interface

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#3166]
```
$ vainfo
Trying display: wayland
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva error: /usr/lib64/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_20
error: failed to resolve wl_drm_interface(): /usr/lib64/libEGL_mesa.so.0: undefined symbol: wl_drm_interface
libva error: /usr/lib64/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```

**Comment by fenrus75** [comment]
hmmmm. odd.

will need to figure out where this is supposed to come from .. and then
make it come from there ;-)

**Comment by fenrus75** [comment]
Trying display: wayland
Trying display: x11
error: can't connect to X server!
Trying display: drm
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_21
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.21.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 24.2.4 ()
vainfo: Supported profile and entrypoints


is what I get. not quite the same

**Comment by paulcarroty** [comment]
There are two drivers:

- i965 for libva-intel-driver
- iHD for intel-media-driver

libva picked the iHD driver in your case probably 'cause detected never hardware. Try to set `LIBVA_DRIVER_NAME=i965`.

**Comment by paulcarroty** [comment]
Probably related to https://github.com/intel/intel-vaapi-driver/issues/419
More info: https://www.reddit.com/r/archlinux/comments/1eeqsbv/libva_error_usrlibdrii965_drv_videoso_init_failed/?rdt=53458

**Comment by paulcarroty** [comment]
@fenrus75, can you apply this patch? https://github.com/intel/intel-vaapi-driver/pull/566
Success story in the comments.

Workaround: extract this [package](https://download.clearlinux.org/releases/41890/clear/x86_64/os/Packages/libva-lib-2.21.0-72.x86_64.rpm), rename `/2100/2200/` and move content to `/usr/lib64/`.

**Comment by fenrus75** [comment]
yup will do after my morning coffee

**Comment by fenrus75** [comment]
(and done)

**Comment by paulcarroty** [comment]
still not shipped to release?
