### ISSUE TITLE
Admin user unable to `sudo su` if no root password is set

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#317]
**Describe the bug**
When an administrative user (non-root account) wants to become root with the `sudo su` command, it fails with the following message:
```
% whoami
mesiment
% sudo su
You are required to change your password immediately (administrator enforced)
su: Authentication token manipulation error
```

However, the following works:
```
% whoami
mesiment
% sudo -i
# whoami
root
```

**To Reproduce**
1.  Make sure `root` user has not password (no `root` entry in `/etc/shadow`)
2. With an administrative user (part of the `wheel` group) try to become root with `sudo su`
3. Check failure 

**Expected behavior**
Administrative user should be able to become `root` with both `sudo su` and `sudo -i` commands.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS version: 26720
 - Bundles:
```
# swupd bundle-list 
boot-encrypted
bootloader
bootloader-extras
c-basic
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
ethtool
git
iproute2
kernel-native
libX11client
network-basic
openssh-server
openssl
os-core
os-core-update
p11-kit
perl-basic
postgresql
python3-basic
qt-basic
sudo
synergy
sysadmin-basic
telemetrics
tzdata
vim
which
wpa_supplicant
x11-server
xemacs
zsh
```

**Additional context**
If the root password is correctly set, this problem goes away.

Likely Stateless issue.

**Comment by bryteise** [comment]
@mrkz I think that's what the wheelnopw group does differently than wheel, could you confirm?

**Comment by mrkz** [comment]
@bryteise nope, same behavior, either it's `wheel` or `wheelnopw`:
```
% whoami
mesiment
% groups
wheelnopw mesiment
% sudo su
You are required to change your password immediately (administrator enforced)
su: Authentication token manipulation error
% sudo -i
# whoami
root
```

Problem it's related to `root` account not having a password set, because when I `passwd` the `root` account, this issue goes away.

Still, a bit uncomfortable, because if one uses `clr-installer` and creates an Administrative user from there, the user belogs to the `wheel <user>` groups. and since the root account hasn't been used, no password has been set, hence user is very likely to hits this issue on a fresh install.

**Comment by fenrus75** [comment]
The installer should set a random password..

He issue so biting in many places including pistgresql setup

**Comment by mdhorn** [comment]
This is new because if the graphical desktop environment?

If the user running the installer does not choose to create an admin user, will the GUI login process prompt for the first time root password like the terminal login?

**Comment by bryteise** [comment]
Ugh, random root password seems so wrong. Does disabling root login cause the problem to go away (`passwd --lock root)?

**Comment by mrkz** [comment]
> The installer should set a random password..

I agree with @bryteise that a random password would give us more issues (e.g: admin users removes it's admin capabilities and root gets locked down)

> This is new because if the graphical desktop environment?

Not really, the thing is that `clr-installer` (not sure if ister too) exposes this issue when an account is created from the installer

> If the user running the installer does not choose to create an admin user, will the GUI login process prompt for the first time root password like the terminal login?

No, if no user is created when installing CLR, the GNOME initial setup will be run instead in order to create a new user. Haven't tried this path btw.

> Ugh, random root password seems so wrong. Does disabling root login cause the problem to go away (`passwd --lock root)?

Not really, actually I was not able to run the command, here's the output:
```
# passwd --lock root
passwd: user 'root' does not exist in /etc/passwd
```

**Comment by mdhorn** [comment]
> @mdhorn @bryteise @fenrus75 One solution may be to actually make the user to setup a root password on the `clr-installer`, either a user is created or not on the installer.

This was my initial thoughts a while ago, but it seemed to go against the set-root-password-at-first-login method that had been long standing. But this may be the most sensible solution going forward; at least for a GUI Desktop environment. 

This could be a problem when generating images or installing from a configuration file though.

**Comment by ahkok** [comment]
Let's fix passwd first, and go from there...

**Comment by thiagomacieira** [comment]
Show about using `sudo -s` ?

**Comment by mrkz** [comment]
> Show about using `sudo -s` ?

this also works :+1: 

```
% whoami 
mesiment
% sudo su
You are required to change your password immediately (administrator enforced)
su: Authentication token manipulation error
% sudo -s
# whoami
root
```

**Comment by mrkz** [comment]
@tpleavitt was this effectively fixed or why did it get closed with no feedback of fixes?

**Comment by mdhorn** [comment]
@mrkz This was fixed by
https://github.com/clearlinux/clr-installer/pull/213

If an Admin user is created, we disable root logins which fixed the problem asking to set a root password.
