### ISSUE TITLE
wlrobs

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3180]
Official package name: wlrobs

License (must be an OSI approved Open Source license): GPL-3.0-only

Download URL of latest release: https://hg.sr.ht/~scoopta/wlrobs/archive/tip.tar.gz

Latest release date (must be recent): Aug 7th, 2024

Description: obs plugin for enabling capture from wlroots based wayland compositors such as sway

Autospec Notes: [for-review.txt](https://gist.github.com/K1ngfish3r/b8cef940b61f88777dca1877e901a271)

no intervention needed, autospec picks it up

**Comment by bwarden** [comment]
Already added; will be in obs-studio bundle shortly.

**Comment by K1ngfish3r** [comment]
available in 42330
