### ISSUE TITLE
wlroots 0.17.4 -> 0.18.0

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3183]
URL= https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/0.18.0/wlroots-0.18.0.tar.gz

Autospec Notes - [for-review.txt](https://gist.github.com/K1ngfish3r/f85c59be9acaad982ccfd72a6eeffacb)

**buildreq_add** ++
```
Vulkan-Headers-dev
glslang-bin
```

**Comment by fenrus75** [comment]
we have this guy on autoupdate so it already updated -- but I added the
buildreq_add ones to it as well now

**Comment by fenrus75** [comment]
... and undoing this since sway is not ready for this

**Comment by K1ngfish3r** [comment]
Might be best to update to 0.19.0 and skip 0.18.0, since the next release of sway is looking like [that](https://github.com/swaywm/sway/commit/274a5fcb73b1252e05543669c956a370516f052c), will close this for now.
