### ISSUE TITLE
Winetricks

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3186]
Official package name: winetricks

License (must be an OSI approved Open Source license): LGPL-2.1

Download URL of latest release: https://github.com/Winetricks/winetricks/archive/20240105/winetricks-20240105.tar.gz

Latest release date (must be recent): Jan 5, 2024

Description: Winetricks is an easy way to work around problems in Wine.
It has a menu of supported games/apps for which it can do all the workarounds automatically. It also allows the installation of missing DLLs and tweaking of various Wine settings.

Mainly for use with WineGUI

Autospec Notes - [for-review.txt](https://gist.github.com/K1ngfish3r/f1cc77e3a58fd51d1c12a6aba83a0c34)

No changes required. Autospec picks it up.

**Comment by bwarden** [comment]
Since WineGUI already downloads the latest version of winetricks locally, and winetricks itself downloads arbitrary binary files from the internet, we're not going to package it at this time.

**Comment by K1ngfish3r** [comment]
Ah, I really wanted arbitrary binary downloader in CL, oh well
