### ISSUE TITLE
Cannot trim encrypted root partitions on SSDs

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#319]
**Describe the bug**
SSD performance degrades if the contained file system is not trimmed regularly. This is taken care of by the `fstrim.timer` included in the os-core bundle (installed by default). Trimming, however, does not work on encrypted (root) filesystems, because `rd.luks.options=discard` is missing from the kernel cmdline. 

**To Reproduce**
1. Boot into system with encrypted root filesystem
2. Call `fstrim -a`
3. Notice that the root file system is not trimmed 

**Expected behavior**
The file system should be trimmed.

**Environment (please complete the following information):**
VERSION_ID=26730

**Additional context**
Adding `rd.luks.options=discard` to `/boot/loader/entries/Clear-linux-native-4.19.6-669.conf` and rebooting solves this issue.

**Comment by thiagomacieira** [comment]
> SSD performance degrades if the contained file system is not trimmed
> regularly. This is taken care of by the `fstrim.timer` included in the
> os-core bundle (installed by default). Trimming, however, does not work on
> encrypted (root) filesystems, because `rd.luks.options=discard` is missing
> from the kernel cmdline.

This is intentional, which is why it is the default. Trimming encrypted 
storage can reveal which blocks contain content and which ones don't.

I recommend against doing it by default. You can always enable for your own 
systems, understanding what the security implications are.

**Comment by neben** [comment]
AFAIU these security/privacy concerns apply to a small subset of desktop users that need a sort of plausible deniability (along the lines of 'no, I don't have any data stored on this encrypted disk'). And even in this case, it is unclear to an attacker when TRIM was issued the last time (for the default periodic TRIM). If an attacker has repeated access to an encrypted disk without TRIM, they can also determine which blocks have changed.

My understanding is that ClearLinux' primary target are server systems (be it dedicated servers, cloud or on-premises), and IMO the main reason for LUKS here is protection of user data/IP in case of disk replacement/theft/etc, i.e., confidentiality and not plausible deniability. IMO performance and disk life should be more important in this use case.

Anyhow, I don't have any strong opinions on this, so feel free to close this issue. Would be great though, if this was documented, even if it's the default setting on other Linux distributions (which, again, are also frequently chosen by desktop users).

**Comment by thiagomacieira** [comment]
We are targetting servers first, but we also have desktop as a target. I need to get one of our security experts to review this to see if we want to change our default.

AFAIK, the issue is that at any point in time (with no repeated access), you can use the fact that the a good portion of your disk is TRIMmed, it reduces the amount of data that the attacker needs to sift through to find something useful. What I don't know is whether this is a feasible attack: if you can break one portion of the disk, is the fact that even 75% of it TRIMmed a challenge? Or is it the other way around, that having TRIMmed sections makes attacking easier?

**Comment by tpleavitt** [comment]
Can be configured by user by creating a file in /etc/kernel/cmdline.d and add rd.luks.options=discard to the file.

**Comment by neben** [comment]
Thanks, I can confirm it works after creating the file, running `clr-boot-manager update` and rebooting!
```
# cat /etc/kernel/cmdline.d/discard.conf 
rd.luks.options=discard
```
