### ISSUE TITLE
add fstrim.timer

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#3190]
The `util-linux-extras-uuid-services` package contains `fstrim.timer`, so adding this package to `os-core` bundle will benefit all bare metal Clear instances with SSD.

**Comment by paulcarroty** [comment]
⬇️

**Comment by bwarden** [comment]
Fixed by https://github.com/clearlinux-pkgs/util-linux/commit/98cf05b1a613afe5e58bfcfa526de90d020d7da9, in Clear Linux release 42470.
