### ISSUE TITLE
Update nautilus to 47.x to match xdg-desktop-portal-gnome

### ISSUE THREAD

**Issue by Aqua1ung** [clearlinux/distribution#3191]
It appears that mixing xdg-desktop-portal-gnome **47.x** with Nautilus (and GNOME) **46.x** in CL42400 might not be a very good idea: [Dialog boxes for “Move to…” and “Copy to…” in Gnome Files no longer show up](https://photos.app.goo.gl/sup4tmJVDseXjohW7), and, occasionally, Files/Nautilus crashes.

**Comment by bwarden** [comment]
The update to nautilus 47.x tripped and fell onto its face, leaving the older 46.2 build in place, instead of rolling forward with the rest of GNOME.

**Comment by bwarden** [comment]
https://github.com/clearlinux-pkgs/nautilus/commit/b59183586affef64fe22586f5bd78f7b3862874b

**Comment by Gui2Barbieri** [comment]
May be related to my issue, but nautilus is completely broken here, it makes accessing my files a really big pain :(

**Comment by bwarden** [comment]
> May be related to my issue, but nautilus is completely broken here, it makes accessing my files a really big pain :(

You've gotta give us more to go on here :) Did you update to our release with nautilus 47.0? If so, open a new bug and give us  an example of something failing, and launch it from the console so you can easily get to the error messages.

**Comment by Gui2Barbieri** [comment]
```
$ sudo swupd update
Password: 
Update started
Version on server (42440) is not newer than system version (42440)
Update complete - System already up-to-date at version 42440
$ nautilus
** Message: 17:51:02.944: Connecting to org.freedesktop.Tracker3.Miner.Files

(org.gnome.Nautilus:1905): GLib-GIO-ERROR **: 17:51:03.342: Settings schema 'org.freedesktop.Tracker3.Miner.Files' is not installed
Trace/breakpoint trap (core dumped)
```


Tried to update, and says I'm in the latest version. The other stuff is what happens when I try to run nautilus.

**Comment by bwarden** [comment]
> Tried to update, and says I'm in the latest version. The other stuff is what happens when I try to run nautilus.

Yes, this is a different issue. Open a new bug please.
