### ISSUE TITLE
.iso download links missing (42470+)

### ISSUE THREAD

**Issue by K1ngfish3r** [clearlinux/distribution#3196]
live-server.iso missing from 42470 onwards https://cdn.download.clearlinux.org/releases/42470/clear/
live-desktop.iso missing from 42480 onwards https://cdn.download.clearlinux.org/releases/42480/clear/

last stable release 42440 https://cdn.download.clearlinux.org/releases/42440/clear/

**Comment by K1ngfish3r** [comment]
live-desktop.iso returns in 42520
live-server.iso still missing

**Comment by alexjch** [comment]
The fix is WIP

**Comment by K1ngfish3r** [comment]
Fixed in 42540
