### ISSUE TITLE
How to add encrypted swap with the installer?

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#320]
**Is your feature request related to a problem? Please describe.**
I would like an installer option to set up an encrypted swap partition, especially if I choose to encrypt my root file system.

**Describe the solution you'd like**
This can be achieved manually by creating the following two files:
```
# cat /etc/crypttab 
# <name> <device>         <password>    <options>
swap     LABEL=cryptswap  /dev/urandom  swap,offset=2048,cipher=aes-xts-plain64,size=512,discard

# cat /etc/fstab 
# <filesystem>    <dir>  <type>  <options>  <dump>  <pass>
/dev/mapper/swap  none   swap    defaults   0       0
```

**Comment by ahkok** [comment]
Possibly an item for the new installer. @mdhorn ?

**Comment by thiagomacieira** [comment]
I did this post-installation on my system. The swap is another LV inside the volume group.

**Comment by mdhorn** [comment]
This option already exists in the current installer. Just check the Encrypt box when editing the swap partition in the partitioning interface.  

@dorileo we need to work with the documention team to update the online documents for this new feature.

**Comment by neben** [comment]
I used this image for a test install in virtualbox: `clear-26700-installer.iso`. Is this not the right one?

**Comment by thiagomacieira** [comment]
Once again we're bitten by that .iso... I had the same problem. Try the .img file instead.

**Comment by dorileo** [comment]
@neben as far as I remember the current installer (ister) doesn't support that, we have implemented that feature in the new installer. You can try the new installer with the the live-desktop-beta image.

**Comment by fenrus75** [comment]
we need to rename the iso to something like "only-use-for-virtual-box" or
something like that

**Comment by thiagomacieira** [comment]
Hmm... I added the swap after the first boot. Just create a new partition and use `cryptsetup luksFormat` with the same password, then `cryptsetup luksOpen` + `mkswap` on it. Or, if you use an encrypted LVM Volume Group, simply create a new Logical Volume and mkswap on it.

```
# lsblk 
NAME                                          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                                             8:0    0 953.9G  0 disk  
├─sda1                                          8:1    0   512M  0 part  /boot
├─sda2                                          8:2    0     6G  0 part  
│ └─luks-84ee31da-10cd-4e9e-8c80-bf66662e7c7e 252:0    0     6G  0 crypt /
└─sda4                                          8:4    0   512G  0 part  
  └─cr_sda4                                   252:1    0   512G  0 crypt 
    ├─vg0-stuff                               252:2    0   200G  0 lvm   /home
    └─vg0-swap                                252:3    0    64M  0 lvm   [SWAP]
```

In this setup, both sda2 and sda4 are encrypted with the same password, so I only have to type once at boot. But sda4 is a Physical Volume for the Volume Group and contains both my `stuff` volume and the swap, minimal as it is.

**Comment by neben** [comment]
@thiagomacieira adding encrypted swap manually post-install works (see the issue description), but it'd be great to have the installer do this automatically.

**Comment by mdhorn** [comment]
@neben The new clr-installer supports encrypted swap.  This is currently the default installer in the desktop-beta image, and will soon be the default installer in the default clear-xxxxx-installer image as well.

**Comment by dorileo** [comment]
I assume we can close this one. Please feel free to reopen it if needed. Thanks.
