### ISSUE TITLE
AVX10.2-512 support?

### ISSUE THREAD

**Issue by romulasry** [clearlinux/distribution#3201]
https://www.phoronix.com/news/Intel-Diamond-Rapids-APX-AVX10

Intel software engineers have been very busy recently with upstreaming various elements of support into the Linux kernel, open-source compilers and more for the next-generation Xeon [Diamond Rapids](https://www.phoronix.com/search/Diamond+Rapids) processors. Following the recent [GCC prep patches for Diamond Rapids](https://www.phoronix.com/news/Intel-GCC-Diamond-Rapids-ISA) to work on the ISA additions around AMX-AVX512, AMX-FP8, AMX-FP32, and others, a new patch was posted today for actually exposing the "-march=diamondrapids" compiler target and in turn confirming all of the new ISA capabilities.

Intel Diamond Rapids is looking quite exciting on the CPU ISA front. In addition to the many Advanced Matrix Extensions (AMX) additions coming with Diamond Rapids, we now have solid confirmation with today's patch that Diamond Rapids will be supporting AVX10.2-512 as the latest of [AVX10](https://www.phoronix.com/search/AVX10).

The patches can be found on the [GCC mailing list](https://gcc.gnu.org/pipermail/gcc-patches/2024-November/667139.html). These patches in turn will be found with [GCC 15](https://www.phoronix.com/search/GCC+15) that will see its stable release in the form of GCC 15.1 around March~April, well ahead of Xeon Diamond Rapids processors shipping and allowing time for this major compiler update to be packaged up by various Linux distribution vendors.

**Comment by K1ngfish3r** [comment]
https://community.clearlinux.org/t/apx-and-avx10-compiled-binaries-coming-to-clear-linux-this-week/9421

**Comment by thiagomacieira** [comment]
What's your request with this issue?

**Comment by romulasry** [comment]
Just knowledge about 10.2-512

**Comment by thiagomacieira** [comment]
https://cdrdv2-public.intel.com/784343/356368-intel-avx10-tech-paper.pdf
