### ISSUE TITLE
update vkd3d to 1.14

### ISSUE THREAD

**Issue by paulcarroty** [clearlinux/distribution#3211]
The latest update happened [a year ago](https://github.com/clearlinux-pkgs/vkd3d/commit/fe3ad2b5eae3074b849ebfbaff3eb5047e2427ec).

https://www.winehq.org/news/2024112101

**Comment by K1ngfish3r** [comment]
autospec notes - [for-review.txt](https://gist.github.com/K1ngfish3r/a3c57b9951e859f5a29a2a4f5d2408f4)

**buildreq_add**
```
texlive-bin
mingw-binutils
```
**pkgconfig-ban** - `32opengl`

[.spec file](https://gist.github.com/K1ngfish3r/bbeede330efb7d580eb813aefba9dd4d)
