### ISSUE TITLE
libversion

### ISSUE THREAD

**Issue by Zopolis4** [clearlinux/distribution#3218]
Official package name: libversion

License (must be an OSI approved Open Source license): MIT

Download URL of latest release: https://github.com/repology/libversion/archive/refs/tags/3.0.3.tar.gz

Latest release date (must be recent): Jan 14, 2023

Description: Advanced version string comparison library.

**Comment by fenrus75** [comment]
while we don't mind adding libraries -- what would be using the library?

**Comment by Zopolis4** [comment]
The library is required for the ruby-ilbversion gem, which is a required development dependency of https://github.com/chromebrew/chromebrew. (Also, the library comes with a fully functional binary for command-line version comparison)

**Comment by bwarden** [comment]
Watch for https://github.com/clearlinux/clr-bundles/commit/cdf099adce3dcae61e51822c8e0aa398a31702b3
