### ISSUE TITLE
Add official NVIDIA driver support/documentation

### ISSUE THREAD

**Issue by pldelisle** [clearlinux/distribution#324]
**Is your feature request related to a problem? Please describe.**
Proposing to add official NVIDIA GPU driver support to Clear Linux. 
Adding NVIDIA GPU support could enable a lot more deep learning use cases and Clear Linux could be the OS of choice to train/serve deep learning models.

**Describe the solution you'd like**
The distribution supports TensorFlow and Caffe framework, and both frameworks can have GPU acceleration. There is no official documentation on how to install official proprietary NVIDIA GPU drivers and support seems inexistant. 

**Describe alternatives you've considered**
I tried installing manually the NVIDIA drivers, but failed to install _nvidia-drm_ kernel module.

**Additional context**
I understand this is a distribution designed for Intel platforms, but to benefit from both Intel optimization and GPU acceleration would be great. This distribution could be used for training and serving deep learning models using GPU inference.

At least, if Installing NVIDIA drivers is possible, provide sufficient documentation.

**Comment by ahkok** [comment]
Can you elaborate where the following documentation fails:

https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules#contents

**Comment by ahkok** [comment]
I'm going to treat this as a documentation-only issue. For now, we won't be adding these drivers, the only thing we can do is make installation easy, which is through better documentation.

**Comment by pldelisle** [comment]
Thanks ahkok for your reply.

So I did exactly what's on [the page](https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules#contents) you referred. 

Kernel is 4.19.9-671.**native**

Installed ` linux-dev` bundle.

Disabled the kernel signature checking. 

Ran the first time the NVIDIA-Linux-x86_64-390.87.run file. Installer says Le Nouveau driver is active and created necessary blacklist files to unload module at next reboot.

Rebooted the machine.

Re-ran the NVIDIA installer. Says `The nvidia-drm kernel module was not created. This module is required for the proper operation of DRM-KMS. If you do not need to use DRM-KMS, you can try to install this driver package again with the '--no-drm' option.
ERROR: Installation has failed.`

Any idea ?

Thank you very much.

**Comment by ahkok** [comment]
There are hints in the `nvidia-installer.log` that indicate that the NVIDIA driver does not properly support `4.19` kernels and people are seeing this same problem (according to a quick google).

I don't think I can offer further relief, this needs to be fixed by NVIDIA I think.

**Comment by pldelisle** [comment]
Thanks a lot !

**Comment by ahkok** [comment]
So, from my personal experience in the past, it's likely this will remain a problem due to the nature of Clear Linux kernel updates. You may want to see if you should consider using the -lts kernel. Unfortunately, we don't ship kernel headers for the -lts kernel, which means you will likely just want to compile it entirely. Not trivial, but an option if you really need this.

**Comment by pldelisle** [comment]
Thanks.

But using the latest NVIDIA Driver (415.23), installation completes. However, the installer failed to update X configuration file so Nvidia X driver cannot be used when restarting. File /etc/X11 is not found.

**Comment by sanych10** [comment]
did this work for you?

**Comment by pldelisle** [comment]
> did this work for you?

Finally switched to Ubuntu. For Machine Learning development Ubuntu 18.04 LTS is way more flexible and less complicated to deploy.

**Comment by sanych10** [comment]
i guess in my case, I will have stay on Ubuntu.. :) thanks for reply.

**Comment by thiagomacieira** [comment]
Aside from the driver, we'd be interested in any other aspects that you found that made Clear less flexible or less attractive than Ubuntu.

**Comment by sanych10** [comment]
Yes. Here is quick scenario:  attempted to install ClearLinux on bare metal. All went well up until the point when it wanted to connect to its servers to start pulling packages. I could not pass the screen where you need to connect to linux clear servers. That was when active ethernet  interface was identified and detected.  Still a mystery. Message said could not connect to Clear linux ... smth server, installation may not be successful.

**Comment by pldelisle** [comment]
And would also add that for compiling machine learning librairies like TensorFlow or PyTorch, fetching dependencies is simpler on Ubuntu since these libs and their respective documentation are made for Ubuntu. Installing on Bare Metal is also simpler on Ubuntu. I'm sure ClearOS has a lot of advantages when serving ML models (if one can achieve to install the NVIDIA driver and compile the necessary libs with their respective dependencies) since it can surely process faster due to internal optimization, but for a ML researcher and developper, Ubuntu is more convenient to setup and faster to get productive.

**Comment by thiagomacieira** [comment]
Why do you want to compile those libraries again? Clear already has TensorFlow and PyTorch and a lot of others, compiled with aggressive optimisations. Are you making changes to those libraries themselves?

We know about the problem with the driver, but our hands are tied in actually providing it. We have made it somewhat easier, by providing DKMS in Clear and automatically disabling the module signature requirement. Documentation definitely needs to be improved, we agree.

**Comment by bryteise** [comment]
I did notice that https://www.reddit.com/r/ClearLinux/comments/b1gbbz/nvidiacuda_in_clear_linux_success_howto/ had some instructions some great person was able to get working but that is more complex than we'd like.

**Comment by tpleavitt** [comment]
This is documented on the website https://clearlinux.org/documentation/clear-linux/tutorials/nvidia

**Comment by rstrube** [comment]
@tpleavitt could you confirm that this is only useful for CUDA acceleration?  It looks like the documentation has the user explicitly *not* install the nvidia OpenGL drivers - so this couldn't be used for playing games, etc.

As a second question, does Clear Linux plan on  shipping **libglvnd**, which would allow mesa opengl libGL and nvidia opengl libGLES to coexist on the same system? I'm really not a fan of Nvidia, but unfortunately, despite my best efforts and countess hours compiling and patching kernels, I've only been able to get their GPUs configured correctly as an eGPU, so I'm married to them for now.

**Comment by thiagomacieira** [comment]
We do not have plans to use libglvnd. The indirection layer is a performance penalty, albeit small. And since it's only useful for people who need software we can't ship anyway, the burden on them will not lessen if we shipped libglvnd.

**Comment by bwarden** [comment]
The installer supports various options for controlling where libraries are installed. If they're routed to e.g. /opt/nvidia/lib64, then you could help applications find them properly like this:
```
mkdir -p /etc/ld.so.conf.d
echo /opt/nvidia/lib64 > /etc/ld.so.conf.d/nvidia.conf
ldconfig
```
