### ISSUE TITLE
Please add Python "requests" to the installer image(s)

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#325]
**Is your feature request related to a problem? Please describe.**
Clear installer requires network access to complete installation. In very restricted networks, sometimes it's necessary to request firewall exclusions for that to proceed.

**Describe the solution you'd like**
The Python "requests" module would help for a certain script.

**Describe alternatives you've considered**
Unpack the contents of the installation (and dependencies) directly onto the installer image. This is error-prone.

**Additional context**

**Comment by mdhorn** [comment]
How often is this truly needed?
The clr-installer bundler does not contain python, so this could be a significant size bump for the image to accommodate this.

**Comment by ahkok** [comment]
alternatively, if the functionality has a solid API, perhaps this could be supported in `golang` itself.

**Comment by thiagomacieira** [comment]
The problem is when we don't control the script. Certain organisations may need you to run some scripts before networking is functional.

Let's make sure the live installer has those bits.

**Comment by mdhorn** [comment]
Offline installs added in release 2.3.0 of the clr-installer
https://github.com/clearlinux/clr-installer/releases/tag/2.3.0
