### ISSUE TITLE
libcap.so.2 not found error in locally builded CL docker image updated to version > 26790

### ISSUE THREAD

**Issue by joselamego** [clearlinux/distribution#326]
**Describe the bug**
Several commands (if not any) including swupd can not be executed inside a container running a locally build Clear Linux image that is being updated to latest CL version. An error messages states that libcap.so.2 cannot be found.

**To Reproduce**
1. Create a dockerfile to build locally a CL docker image:
`echo "FROM clearlinux RUN swupd update CMD \'bash\'" | tee "my_jenkinsfile"`
2. Build the image:
`docker build - < my_jenkinsfile --build-arg <may be proxies> -t clear_test_version`
3. Run the builded image inside a container:
`docker run -it clear_test_version`
4. Execute a comand inside the container:
`swupd info`

**Expected behavior**
commands can be executed inside the container

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: Tested versions 26790 and 26800. Both present the issue.

Error message:
`# /usr/libexec/git-core/git-remote-http: error while loading shared libraries: libcap.so.2: cannot open shared object file: No such file or directory`

**Comment by thiagomacieira** [comment]
26780 has just updated libcap. The manifest says for os-core says:

```
L...    1f9d4dba4245cdf68fbfdd85462793e2b6bd390de9cf510574d3127035fcdad9        26780   /usr/lib64/libcap.so.2
.d..    0000000000000000000000000000000000000000000000000000000000000000        26780   /usr/lib64/libcap.so.2.25
F...    9bcf5fec55bb62d54f64e1304fb2e556b91fe38ba45af6fdb408ca69e73d0b66        26780   /usr/lib64/libcap.so.2.26
```

Can you check if the symlink /usr/lib64/libcap.so.2 is present and what it points to?

**Comment by joselamego** [comment]
@thiagomacieira: I can not execute "ls" command (same error), however, with the "tab" I can see that there are libcap.so.2 and libcap.so.26 there. Trying to figure out other ways to see where they're pointing to.

**Comment by thiagomacieira** [comment]
Try this: `python -c 'import os; print(os.readlink("/usr/lib64/libcap.so.2"))'`

Also, try erasing /var/cache/ldconfig (mv links to libcap.so.2, so you can't rename...). ln also links to libcap.so.2, so you can't ln -sf, but you might be able to do the python trick too (`os.symlink`).

**Comment by joselamego** [comment]
Had to modify the jenkinsfile to build the image with python before updating to 26800 (otherwise it fails). The output to print(os.readlink("/usr/lib64/libcap.so.2")) is `libcap.so.2.25`

**Comment by joselamego** [comment]
so, removing `/usr/lib64/libcap.so.2`, then creating a symlink with `os.symlink("/usr/lib64/libcap.so.2.26", "/usr/lib64/libcap.so.2")` worked (all inside python).
After this, commands can be executed.

**Comment by thiagomacieira** [comment]
Ok, so the question is how the wrong symlink was left around. Because on my system the link was right, we know swupd on most circumstances is updating the link correctly. What's different about your build?

**Comment by fenrus75** [comment]
docker images run update triggers different than real systems.. so it's a
little complicated

**Comment by joselamego** [comment]
Latest Clear Linux version in the docker image has been updated to 26790. The reported issue is not present using this image, so I'm closing this report now. Thanks.
