### ISSUE TITLE
compiling SPDK on target

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#33]
Please advice how on-target compilation of SPDK[1] should be done with Clear Linux. This is relevant for a "cloud cluster in a box" experiment with Clear Linux as bare metal OS where development of SPDK happens directly on the target device, i.e. developers will need to do quick edit-compile-run cycles.

The open issue is how it can be ensured that the Clear Linux installation has the necessary development files. It happens to work right now with `swupd bundle-add os-core-dev storage-utils-dev desktop-dev`, but that pulls in a lot of extra stuff and makes updating the OS much slower. `desktop-dev` is needed because it is the only bundle containing `libiscsi-dev`.

The SDPK setup script [2] has a list of expected packages for Debian/Ubuntu and Fedora. Not all of them are actually needed for compilation. I got it built after looking for and installing just the real -dev packages, without the auxiliary source code formatting tools. Those are only needed when submitting code changes.

[1] https://github.com/spdk/spdk
[2] https://github.com/spdk/spdk/blob/master/scripts/pkgdep.sh

**Comment by ahkok** [comment]
Adding `libiscsi-dev`to `storage-utils-dev` bundle. Probably doesn't resolve the issue but it should help.

**Comment by pohly** [comment]
I agree, this helps, please make that change. The underlying issue (installing arbitrary development files for on-target development) however remains.

**Comment by ahkok** [comment]
actually, it turns out we have nothing in clearlinux that even needs libiscsi, except for udisks2. This is the reason that it's not in any other bundle, and that's a legitimate reason, so, the -dev bundle will get autogenerated without it again and my change gets clobbered out. We're looking at a way to solve that.

**Comment by puneetse** [comment]
I'm closing this issue as `libiscsi-dev` has since been made available in the `devpkg-libiscsi` bundle.
