### ISSUE TITLE
Vmware player copy/paste and resize not working on Windows 10 host

### ISSUE THREAD

**Issue by bryteise** [clearlinux/distribution#330]
**Describe the bug**
From https://github.com/clearlinux/clr-bundles/issues/94 pasted below:

Host:

    Win10
    vmware workstation 15 player

copy paste from host doesnt work, neither does resizing the window/autofit. I have open-vm-tools installed on many other distros and it always works except here.
I also tried the steps here but it still didnt work: vmware/open-vm-tools#150 (comment)

The service open-vm-tools is running.

**To Reproduce**
1. Run Vmware Workstation Player on a Windows 10 host
2. 
3. 
4. 

**Expected behavior**
Copy/paste and resize/autofit window works.

**Comment by Meai** [comment]
with os-cloudguest-vmware-gui installed, resize seems to work but still no copy/paste. Havent tried shared folder yet.

Plugins:
```
pc@clr-2094c0a5be0d49168b2bab050f74c100 ~ $ ps aux | grep vm
root        338  0.0  0.0      0     0 ?        I<   16:36   0:00 [nvme-wq]
root        339  0.0  0.0      0     0 ?        I<   16:36   0:00 [nvme-reset-wq]
root        340  0.0  0.0      0     0 ?        I<   16:36   0:00 [nvme-delete-wq]
root        470  0.0  0.0      0     0 ?        S    16:36   0:00 [irq/16-vmwgfx]
root        543  0.0  0.0 122800 11340 ?        Ssl  16:36   0:00 /usr/bin/vmtoolsd
pc         2316  0.0  0.0   6488   832 pts/0    S+   16:38   0:00 grep vm

pc@clr-2094c0a5be0d49168b2bab050f74c100 ~ $ sudo lsof -p 543 | grep plugins
Password: 
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
vmtoolsd 543 root  mem       REG                8,3    38920 384160 /usr/lib64/open-vm-tools/plugins/vmsvc/libvmbackup.so
vmtoolsd 543 root  mem       REG                8,3    22536 384159 /usr/lib64/open-vm-tools/plugins/vmsvc/libtimeSync.so
vmtoolsd 543 root  mem       REG                8,3    22552 384158 /usr/lib64/open-vm-tools/plugins/vmsvc/libresolutionKMS.so
vmtoolsd 543 root  mem       REG                8,3    14416 384157 /usr/lib64/open-vm-tools/plugins/vmsvc/libpowerOps.so
vmtoolsd 543 root  mem       REG                8,3    40008 384156 /usr/lib64/open-vm-tools/plugins/vmsvc/libguestInfo.so
vmtoolsd 543 root  mem       REG                8,3    30728 384155 /usr/lib64/open-vm-tools/plugins/vmsvc/libgrabbitmqProxy.so
vmtoolsd 543 root  mem       REG                8,3   125032 384153 /usr/lib64/open-vm-tools/plugins/common/libvix.so
vmtoolsd 543 root  mem       REG                8,3    14344 384152 /usr/lib64/open-vm-tools/plugins/common/libhgfsServer.so
vmtoolsd 543 root  mem       REG                8,3    18440 384154 /usr/lib64/open-vm-tools/plugins/vmsvc/libdeployPkgPlugin.so

```

**Comment by Meai** [comment]
seems like the issue is that libdndcp.so isnt even built?

**Comment by Meai** [comment]
ok adding these: 

add to buildreq_add:
gtkmm3-dev
gtkmm2-dev

remove from configure: 
--without-gtkmm
--without-gtkmm3 

then it is building the libdndcp.so
But I cant figure out how to make it build into one of the .rpm packages in the end

**Comment by AntonioMeireles** [comment]
@bryteise 

AFAICT here's what's needed to be done to get this sorted:

- `/usr/bin/vmware-user-suid-wrapper`*really* **has to** be shipped setuid (`7755`)
- we have to ship `/usr/share/xdg/autostart/vmware-user.desktop` (which is just a symlink to `/usr/share/defaults/open-vm-tools/xdg/autostart/vmware-user.desktop`) bundled into `open-vm-tools-extras`
- as stated above by @Meai `--without-gtkmm` and `--without-gtkmm3` need to be droped from configure arguments (and `buildreq_add` updated accordingly). The resulting extra `/usr/lib64/open-vm-tools/plugins/vmusr/libdndcp.so` should then be bundled also in `open-vm-tools-extras`
- finally, we need to ship a `vmware-vmblock-fuse.service` file along ...
   ```
  [Unit]
  Description=Open Virtual Machine Tools (vmware-vmblock-fuse)
  ConditionVirtualization=vmware

  [Service]
  Type=simple
  RuntimeDirectory=vmblock-fuse
  RuntimeDirectoryMode=755
  ExecStart=/usr/bin/vmware-vmblock-fuse -d -f -o subtype=vmware-vmblock,default_permissions,allow_other /run/vmblock-fuse
  
  [Install]
  WantedBy=multi-user.target
  ```
  ... and have it enabled by default. 

All the best, 

António

**Comment by bryteise** [comment]
@AntonioMeireles Alrighty, I'll look at fixing this today then. Thanks so much for the detailed instructions!

**Comment by bryteise** [comment]
Should be in the next release.

**Comment by AntonioMeireles** [comment]
@bryteise *THANKS* !!! ...

just one note - there was a small pkging typo remaining -  `/usr/share/xdg/autostart/vmware-user.desktop` symlink went wrong - see bellow

```shell
clear@gnome.clearlinux.local ~ $ ls -al /usr/share/xdg/autostart/vmware-user.desktop
lrwxrwxrwx 1 root root 65 May 28 18:41 /usr/share/xdg/autostart/vmware-user.desktop -> ../../../defaults/open-vm-tools/xdg/autostart/vmware-user.desktop
clear@gnome.clearlinux.local ~ $ ls /usr/share/defaults/open-vm-tools/xdg/autostart/vmware-user.desktop
/usr/share/defaults/open-vm-tools/xdg/autostart/vmware-user.desktop
clear@gnome.clearlinux.local ~ $ cat  /usr/share/xdg/autostart/vmware-user.desktop
cat: /usr/share/xdg/autostart/vmware-user.desktop: No such file or directory
clear@gnome.clearlinux.local ~ $ swupd info
Installed version: 29680
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
```

(doing a `sudo ln -sf  /usr/share/defaults/open-vm-tools/xdg/autostart/vmware-user.desktop /usr/share/xdg/autostart/vmware-user.desktop` over a clean `29680` and rebooting is enough to show that this is indeed the last thing left :-) ) 

All the Best, 

António

**Comment by AntonioMeireles** [comment]
@bryteise 

actually ...

we can just drop https://github.com/clearlinux-pkgs/open-vm-tools/blob/master/open-vm-tools.spec#L247 
and replace it by ... 
``` 
mv %{buildroot}/usr/share/defaults/open-vm-tools/xdg/autostart/vmware-user.desktop %{buildroot}/usr/share/xdg/autostart/
```
dropping en passant https://github.com/clearlinux-pkgs/open-vm-tools/blob/master/open-vm-tools.spec#L288. spares a few bits in the end rpm. 

OTOH probably `/usr/share/xdg/autostart/vmware-user.desktop` and `/usr/lib64/open-vm-tools/plugins/vmusr/libdndcp.so` should _really_ bellong to `-extras` as having them (specially the later) end pulling unwanted gfx deps in text based installs (since libdndcp.so has a long tail and is currently in `-lib`. 

All the best, 

António

**Comment by bryteise** [comment]
@AntonioMeireles Oh okay. I'll toss them into extras. Thanks for the advice here!

**Comment by sirk390** [comment]
Is this fixed? I just installed Clearlinux 30110 and couldn't get it to work.

**Comment by citron** [comment]
Still having the cut and paste issue running Clearlinux 30450 on VMware ESX 6.5
