### ISSUE TITLE
Installer doesn't show second nvme drive 

### ISSUE THREAD

**Issue by Coretool** [clearlinux/distribution#331]
Hello there

I'm trying to install clear linux on a system with two nvme ssds of which one (seen as nvme0 in the uefi) contains windows 10. Both drives are visible as drives to boot from in the uefi but the clear linux installer only shows the windows drive as a possible drive to install clear linux to. 

The uefi is set to AHCI mode which has fixed issues with other distros in the past but I'm at loss with clear linux.

Am I missing something or is this a bug? Thanks for your time and help :)

**Comment by mdhorn** [comment]
@Coretool which image are you using?
If you aren't already, can you try the live-desktop-beta image?
https://download.clearlinux.org/image/

**Comment by Coretool** [comment]
Just tried the image you mentioned and now it works, thank you!

In the mean time, I used the 'drop to shell' functionality and mounted the other drive manually, which worked as well.
