### ISSUE TITLE
makeinfo --version spews junk

### ISSUE THREAD

**Issue by markgross** [clearlinux/distribution#334]
run "makeinfo --version"

makeinfo --version
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^\s+@([[:alnum:]][[:alnum:]\-]*)({ <-- HERE })?\s*/ at /usr/share/texinfo/Texinfo/Parser.pm line 5481.
Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/^\s+@([[:alnum:]][[:alnum:]\-]*)({ <-- HERE })?\s*(\@(c|comment)((\@|\s+).*)?)?/ at /usr/share/texinfo/Texinfo/Parser.pm line 5485.
texi2any (GNU texinfo) 6.5

Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

The 2 lines starting with "unescaped"  probably should not be there.

**Comment by fenrus75** [comment]
yup

create a regression test for this
fixed  the code in our build system, hopefully will be out in an update
within 1 day

**Comment by ahkok** [comment]
fixed in `27050`
