### ISSUE TITLE
Issues with Gnome Desktop Manager

### ISSUE THREAD

**Issue by garethtdavies** [clearlinux/distribution#335]
**Describe the bug**
After `swupd updates` or certain `swupd bundle-add` commands a working Gnome deskop boots to the terminal and requires a manual restart via `sudo systemctl restart gdm`. 

**To Reproduce**
1. Install from the desktop live image for a working desktop environment
2. Install a few bundles via `swupd bundle-add`
3. Reboot the machine and you are presented with the console and forced to restart the gdm service to get the desktop to launch (even though `desktop-autostart` bundle is present)

I'm yet to identify if this is related to a certain update and/or bundle but it happens regularly enough that it is repeatable - I've had this occur on all three installs I have completed (on different hardware)

**Expected behavior**
Gnome desktop automatically restarts and are not forced to manually restart it.

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
```
~ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26930
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

 - Bundles: [e.g. `sudo swupd bundle-list`]
```
~ sudo swupd bundle-list                 
Password: 
ansible
atom
boot-encrypted
bootloader
bootloader-extras
c-basic
cloud-api
cloud-control
darktable
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-dev
desktop-gnomelibs
desktop-locales
dev-utils
ethtool
flatpak
gimp
git
ipmitool
iproute2
kernel-native
kvm-host
libX11client
mercurial
network-basic
openssh-server
openssl
os-core
os-core-dev
os-core-update
p11-kit
perl-basic
perl-basic-dev
pxe-server
python3-basic
qt-basic
sudo
sysadmin-basic
sysadmin-basic-dev
sysadmin-hostmgmt
telemetrics
tzdata
vim
vlc
which
wpa_supplicant
x11-server
xemacs
xz
zip
zsh
```

**Additional context**
Here is the output of `sudo systemctl status gdm` after I managed to log in - I am always seeing these Child process xxx was already dead messages. I can occasionaly get it to work through a non-reproducible process of enabling the systemctl gdm service and removing/adding the desktop-autostart bundle.

```
● gdm.service - GNOME Display Manager
   Loaded: loaded (/usr/lib/systemd/system/gdm.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2018-12-29 08:34:04 PST; 2min 2s ago
 Main PID: 704 (gdm)
    Tasks: 3 (limit: 4915)
   Memory: 4.4M
   CGroup: /system.slice/gdm.service
           └─704 /usr/bin/gdm

Dec 29 08:34:04 clr systemd[1]: Starting GNOME Display Manager...
Dec 29 08:34:04 clr systemd[1]: Started GNOME Display Manager.
Dec 29 08:34:15 clr gdm-password][966]: pam_unix(gdm-password:session): session opened for user gareth by (uid=0)
Dec 29 08:34:26 clr gdm[704]: Child process -724 was already dead.
```
As above I have three machines in this state that require manually restarting `gdm` so happy to provide any more debugging output if needed.

**Comment by ikeyd** [comment]
Perhaps some `journalctl` and `dmesg` output could help here - checking for segfaults etc. GDM in debug mode could yield additional information.

**Comment by garethtdavies** [comment]
Thanks for the tips, that indeed lead me to spot the failure on boot to aid some further debugging via `sudo journalctl -b` namely:

```
Dec 31 07:50:54 clr gnome-shell[478]: Failed to create backend: Could not find a primary drm kms device
Dec 31 07:50:54 clr gnome-session[470]: gnome-session-binary[470]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
Dec 31 07:50:54 clr gnome-session-binary[470]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
Dec 31 07:50:54 clr gnome-session-binary[470]: Unrecoverable failure in required component org.gnome.Shell.desktop
```

**Comment by garethtdavies** [comment]
And that helped me identify it is an issue with my GPU(s). Tried using the inbuilt graphics and it works as it should. Weird that this only happens after an update, as in it does work perfectly from an initial install. Also this is happening on two of my machines one with an AMD GPU and the other a NVIDIA GPU.

**Comment by garethtdavies** [comment]
For AMD I replaced my AMD R9295x2 with a 480 and it works. I believe the former uses fglrx and latter amdgpu which might explain why one works and the other doesn't. Anyway, long story short this seems to be a GPU driver issue.

**Comment by tpleavitt** [comment]
If issue still exists, reopen

**Comment by jmberutich** [comment]
I'm having the same problem! any news on how to solve it?
