### ISSUE TITLE
vmware guests: host volume mounting not working out of the box (with bonus fix) 

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#336]
**the bug**

on a vmware guest with `os-cloudguest-vmware` installed, and `open-vm-tools` _service_ started, mounting volumes from the host on the guest does not work out of the box.

---
**To Reproduce**

`vmrun enableSharedFolders (...)/ClearLinux.vmx` when called in the host should just work, but is b0rking instead. 

---
**the why**

`open-vm-tools`'s `vmware-hgfsclient` and `mount.vmhgfs` now rely on **fuse** to be available to work, unlike in the past where a specific kmod was used.

---
**the fix**

Two things need to done so that things just work out of the box

- **`fuse` kmod needs to be loaded in advance** 

  one way to achieve that is in the `open-vm-tools` package (to not patch upstream service files) to add the following _drop-in_:
  ```
  # /etc/systemd/system/open-vm-tools.service.d/fuse.conf
  [Service]
  ExecStartPre=/usr/bin/modprobe fuse
  ```

- **`fuse`'s  userland needs to be installed**

    adding `fuse` to `os-cloudguest-vmware` gets us it 

---

**Thanks** in advance _&&_ **HAPPY NEW YEAR for ALL**!

António

**Comment by fenrus75** [comment]
thanks for the detailed report; I've made these fixes

**Comment by AntonioMeireles** [comment]
Closing as this got fixed and is already shipping!

**thanks** @fenrus75 !

**Comment by micrat** [comment]
Hello, please reopen: mounting the host shares is not working automatically on version 28640. In order to see the shares I need to issue the command (in the host): `vmrun enableSharedFolders (...)/ClearLinux.vmx` each time I start the guest.
