### ISSUE TITLE
please include Squid

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#338]
Can you please include Squid? While ngnix is present, I'm looking for something to function as a forward proxy / caching for clients accessing the web.

**Comment by ahkok** [comment]
In progress.

**Comment by ahkok** [comment]
Merged, but a build issue was found and this might not yet work for you, depending on your CPU.

`sudo swupd bundle-add squid` - A fix for the build issue should be available in 1-2 work days.

**Comment by omkhar** [comment]
I get core dumps with today’s build. Will check again in a couple of days.

**Comment by ahkok** [comment]
Yes, I already fixed it, but please wait 2 days to update to a release that has the fix.

**Comment by ahkok** [comment]
Fixed in `27310`.
