### ISSUE TITLE
Add haskell-platform package

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#339]
https://www.haskell.org/platform/

**Comment by bryteise** [comment]
Bootstrap you a haskell for much pain =P.

**Comment by cmarcelo** [comment]
Would importing the haskell-platform binary package first (release 1), then using it to create a new package from the sources (release 2) be acceptable? We would not publish release 1 in the distro. I think that would be the easiest route. And would be the same strategy for future updates (but using our own release N to produce release N+1), except no more external binary packages involved.

@bryteise @ahkok

**Comment by cmarcelo** [comment]
For the record, this one might help us move forward with adding ShellCheck https://github.com/clearlinux/distribution/issues/271

**Comment by bryteise** [comment]
@cmarcelo that update strategy is acceptable though a bit on the painful side. Of course we get to see if it actually works in practice still which is sometimes a bit uncertain.

**Comment by cmarcelo** [comment]
After digging a bit I feel that is better just pick the individual main packages (ghc, cabal-install, etc), and have them in the distro instead of the bundled haskell-platform.

**Comment by gtkramer** [comment]
ghc has been packaged and added to the haskell-basic bundle.  Need to work on getting the other packages required as a part of the haskell-platform.
