### ISSUE TITLE
Logging into locked and sleeping Gnome session triggers segfault in libmutter : build 21530

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#34]
Mar 28 08:53:23 clr-ashland-svkelley kernel: gnome-shell[18710]: segfault at 38 ip 00007f49deabb1f1 sp 00007ffede20c610 error 4 in libmutter-1.so.0.0.0>
Mar 28 08:53:23 clr-ashland-svkelley evolution-alarm[18912]: Error reading events from display: Broken pipe
Mar 28 08:53:23 clr-ashland-svkelley kernel: rfkill: input handler enabled
Mar 28 08:53:23 clr-ashland-svkelley at-spi-bus-launcher[18720]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Mar 28 08:53:23 clr-ashland-svkelley at-spi-bus-launcher[18720]:       after 21 requests (21 known processed) with 0 events remaining.
Mar 28 08:53:23 clr-ashland-svkelley gnome-session[18692]: gnome-session-binary[18692]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal>
Mar 28 08:53:23 clr-ashland-svkelley gnome-session-binary[18692]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Mar 28 08:53:23 clr-ashland-svkelley org.gnome.Shell.desktop[18710]: (EE)
Mar 28 08:53:23 clr-ashland-svkelley org.gnome.Shell.desktop[18710]: Fatal server error:
Mar 28 08:53:23 clr-ashland-svkelley org.gnome.Shell.desktop[18710]: (EE) failed to read Wayland events: Broken pipe
Mar 28 08:53:23 clr-ashland-svkelley org.gnome.Shell.desktop[18710]: (EE)
Mar 28 08:53:23 clr-ashland-svkelley unknown[19026]: Error reading events from display: Broken pipe

**Comment by seanvk** [comment]
What follows then is everything else getting killed:

**Comment by seanvk** [comment]
All seemed to happen at precisely when I woke my desktop from sleep and attempted to unlock the display.

**Comment by iphutch** [comment]
@seanvk is this still an issue? @mrkz could you please re-produce this issue?

**Comment by seanvk** [comment]
I can no longer reproduce this issue.

**Comment by AthenasJimenez** [comment]
@iphutch This cannot be reproduced anymore, so it can be closed.
