### ISSUE TITLE
Add tilix package

### ISSUE THREAD

**Issue by curantes** [clearlinux/distribution#340]
It would be great if you could add [Tilix](https://github.com/gnunn1/tilix) a tiling terminal emulator using GTK+3. I feel like I miss a great tiling terminal emulator. This would simplify for me as sysadmin who constantly have tons of ssh sessions active.

**Comment by fenrus75** [comment]
meson.build:1:0: ERROR:  Could not find any supported D compiler.


D.

ho hum.

**Comment by curantes** [comment]
Sorry should add that its written in dlang. So need a D compiler, I would recommend [LDC](https://github.com/ldc-developers/ldc) compiler. Also [GtkD](https://github.com/gtkd-developers/GtkD/) is a dependency.

**Comment by ahkok** [comment]
`tmux` can already tile any terminal, and is already present. is this really needed?

**Comment by curantes** [comment]
many package requests are not "really needed". As most of them are software that we think would be a great complement to this distribution. 

Since Clear Linux have started to focus more on the desktop and have Gnome as default DM I think tilix would make a good addition as a power full tool for power users.Also it integrate nicely with Gnome 3 and gnome-shell. 

But as you stated, similar functionality can be used with `tmux` so if you indeed don't think the effort in adding tilix to the repos is worth it feel free to close this issue. Otherwise I can help with some of the initial packaging if you are willing to accept such contributions.

**Comment by ahkok** [comment]
I often like to make sure that people know about alternatives that are already available :)

**Comment by curantes** [comment]
> we're intrigued ;)
>
> if it wasn't for D it'd be done days ago but now it's suddenly a bit complex
@fenrus75 Is this something you are planning to work on in the near future to have tilix included? otherwise I might look into this if you accept contributions of packages/bundles.

**Comment by fenrus75** [comment]
we do take contributions..... although our documentation is lacking there

but bootstrapping a new language is not for the faint of heart; I'll see
how far I can get ldc

**Comment by fenrus75** [comment]
ldc added, rest should be easier with this ;)

**Comment by curantes** [comment]
> ldc added, rest should be easier with this ;)

Many thanks for the quick add of ldc, just GtkD left and then we can add tilix :)
:+1:

**Comment by Tornado-Tim** [comment]
Awesome cant wait for it to be added :)

**Comment by Akiyamka** [comment]
Any news here?

**Comment by foureight84** [comment]
> Any news here?

Really waiting for this. Hope it gets support soon.

**Comment by Nirgendsdorf** [comment]
> `tmux` can already tile any terminal, and is already present. is this really needed?

> I often like to make sure that people know about alternatives that are already available :)

There are alternates to almost everything, but sometimes one app has some feature a user cannot do without. Small example: there are native image viewers for Linux, but I wanted Irfanview because drawing a selection rectangle on the displayed image causes I-vew to show rectangle coordinates that ffmpeg's crop filter understands. This makes ffmpeg's crop easy to use, and I need to use it often.

**Comment by curantes** [comment]
I have successfully build tilix locally and also submitted a patch to the dev mailing list. https://lists.clearlinux.org/pipermail/dev/2019-August/003416.html

now we need to see if @fenrus75 @thiagomacieira or any other in dev team is willing to accept it.

**Comment by curantes** [comment]
tilix is now included since version: **30970**

Tilix can be installed through software center or `sudo swupd bundle-add tilix`

**Comment by rudrab** [comment]
Hi, 
Sorry to reopen this, so that the tilix based problem remains in one place. 
Tilix to offer "Open in Tilix " option in nautilus, which is not present here in clearlinux.
