### ISSUE TITLE
pdftex not working

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#341]
```
$ swupd info
Installed version: 27040
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

$ cat > bla.tex
Test

$ pdftex bla.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdftex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt pdftex.fmt
Can't locate mktexlsr.pl in @INC (@INC contains: //tlpkg //texmf-dist/scripts/texlive /home/c/perl5/lib/perl5/x86_64-linux-thread-multi /home/c/perl5/lib/perl5 /usr/local/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.28.1 /usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.28.1 /usr/lib/perl5/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/5.28.1 /usr/lib/perl5/site_perl/5.28.1) at /usr/bin/mktexfmt line 23.
BEGIN failed--compilation aborted at /usr/bin/mktexfmt line 25.
I can't find the format file `pdftex.fmt'!
```

Neither `pdftex.fmt` nor `mktexlsr.pl` can be found with `swupd search`.

**Comment by cmarcelo** [comment]
Possibly related: https://www.tug.org/pipermail/tex-live/2015-May/036855.html

**Comment by cmarcelo** [comment]
It looks like we need texmf (and maybe extras) from

ftp://tug.org/historic/systems/texlive/2018/

or a mirror.

**Comment by cmarcelo** [comment]
Verified we need texmf. For more reference: http://tug.org/texlive/distro.html

**Comment by cmarcelo** [comment]
A better test case:

```
$ cat > bla.tex
Test
\bye
$ pdftex bla.tex
```

should produce a PDF.

**Comment by hnanni** [comment]
seems this issue matches with a one reported sometime ago:
https://github.com/clearlinux/clr-bundles/issues/42

I have a patch for $CLR/packages/texlive/ that alows autospec to build a working LaTeX system. However, I haven't pushed it as I'm not being able to manage the complexity given by the huge amount of licences the package includes

**Comment by tpleavitt** [comment]
Available on Clear

**Comment by nsauzede** [comment]
When I use doxygen to produce PDF documentation, with texlive installed (running CLR 28510), and overriding LATEX_CMD=pdftex, I get the following output :

$ make LATEX_CMD=pdftex
rm -f *.ps *.dvi *.aux *.toc *.idx *.ind *.ilg *.log *.out *.brf *.blg *.bbl refman.pdf
pdftex refman
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdftex)
 restricted \write18 enabled.

>kpathsea: Running mktexfmt pdftex.fmt
>Can't locate mktexlsr.pl in @INC (@INC contains: //tlpkg //texmf-dist/scripts/texlive >/usr/local/lib/perl5/site_perl/5.28.1/x86_64-linux-thread-multi /usr/local/lib/perl5/site_perl/5.28.1 >/usr/lib/perl5/vendor_perl/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.28.1 >/usr/lib/perl5/5.28.1/x86_64-linux-thread-multi /usr/lib/perl5/5.28.1 /usr/lib/perl5/site_perl/5.28.1) at >/usr/bin/mktexfmt line 23.
>BEGIN failed--compilation aborted at /usr/bin/mktexfmt line 25.
>I can't find the format file `pdftex.fmt'!
>make: *** [Makefile:8: refman.pdf] Error 1

Which suggests that the actual issue still stands, and might need to be reopened ?
Thanks

**Comment by DadongZ** [comment]
I have the same issue. Has it been solved?

**Comment by lebensterben** [comment]
>I have the same issue. Has it been solved?

@DadongZ I haven't tested recently. There are other issues with TeX shipped in swupd, eg installed custom TeX packages.
TeX Live officially suggest people to install it by themselves, even if the distribution already ships it.

**Comment by DadongZ** [comment]
@lebensterben It turns out the issue was related to installation of conda texlive-core. I removed the package and it became works properly. I am curious the details behind the issue though.
