### ISSUE TITLE
RFE: consider bumping QEMU to 3.1.0 and properly ship its' guest agent

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#343]
Hi all!, 

currently **2.12.1** is being shipped. **3.1.0** was released early December (**[changelog](https://wiki.qemu.org/ChangeLog/3.1)**). 

Thanks in Advance!

António

**Comment by AntonioMeireles** [comment]
> I don't mind doing the ga thing.. but google so far is not helping me finding what the guest agent actually does. I find a lot of what it COULD do.. but what does it ACTUALLY do ?
> […](#)

AFAIK better/deeper/more reliable integration with libvirt would be a canonical use case. (see [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/chap-qemu_guest_agent) for an example of practical/mainstream usage).

thanks!

**Comment by bryteise** [comment]
Qemu updated, closing.
