### ISSUE TITLE
RFE: consider shipping a way more recent samba release...

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#344]
Hi all!, 

Currently **4.7.11** is being shipped. Current stable release is **[4.9.4](https://www.samba.org/samba/history/)**

Thanks in advance, 

António

**Comment by ahkok** [comment]
Noted. 4.7.x is still supported, but it's probably a good time to switch.

**Comment by AthenasJimenez** [comment]
Updated, should be out tomorrow.

**Comment by AthenasJimenez** [comment]
Samba [update commit](https://github.com/clearlinux-pkgs/samba/commit/e5abda0e9ebee8ff2f44310a4e6fac6da0804e10)
