### ISSUE TITLE
openssl could not load the shared library:crypto/dso/dso_dlfcn.c:117:filename(libz.so)

### ISSUE THREAD

**Issue by omkhar** [clearlinux/distribution#345]
**Describe the bug**
OpenSSL could not load the shared library:crypto/dso/dso_dlfcn.c:117:filename(libz.so)
**To Reproduce**
1. Execute openssl speed -evp aes-128-cbc
(RESULTS BELOW)
Doing aes-128-cbc for 3s on 16 size blocks: 27233911 aes-128-cbc's in 2.98s
Doing aes-128-cbc for 3s on 64 size blocks: 7957357 aes-128-cbc's in 2.99s
Doing aes-128-cbc for 3s on 256 size blocks: 2050482 aes-128-cbc's in 2.98s
Doing aes-128-cbc for 3s on 1024 size blocks: 521073 aes-128-cbc's in 2.99s
Doing aes-128-cbc for 3s on 8192 size blocks: 65362 aes-128-cbc's in 2.99s
Doing aes-128-cbc for 3s on 16384 size blocks: 32713 aes-128-cbc's in 2.99s
OpenSSL 1.1.1a  20 Nov 2018
built on: Fri Dec  7 17:29:54 2018 UTC
options:bn(64,64) des(int) aes(partial) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -O2 -fPIC -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,--copy-dt-needed-entries,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -Wl,--enable-new-dtags -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -flto=8 -ffunction-sections -fsemantic-interposition -O3 -falign-functions=32 -falign-loops=32 -fprofile-use -fprofile-dir=/tmp/pgo -fprofile-correction -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DZLIB -DZLIB_SHARED -DNDEBUG
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
aes-128-cbc     146222.34k   170324.70k   176148.79k   178454.43k   179078.76k   179254.11k
**140174729987008:error:25066067:DSO support routines:dlfcn_load:could not load the shared library:crypto/dso/dso_dlfcn.c:117:filename(libz.so): libz.so: cannot open shared object file: No such file or directory
140174729987008:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto/dso/dso_lib.c:162:**
**Expected behavior**
I expect not to have errors

**Environment (please complete the following information):**
 - Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27040
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
acpica-unix2
bc
bootloader
cloc
cpio
cryptography
curl
dev-utils
dhcp-server
diffutils
docutils
ethtool
file
findutils
gdb
git
gzip
htop
icdiff
inotify-tools
iproute2
irssi
kbd
kernel-install
kernel-native
less
linux-tools
llvm
nasm
network-basic
nginx
nmap
openssh-server
openssl
os-core
os-core-update
p11-kit
parallel
patch
perl-basic
powertop
python3-basic
strace
sudo
sysadmin-basic
sysstat
tmux
tzdata
unzip
valgrind
vim
weechat
which
wpa_supplicant
xz
znc
zstd

**Additional context**

**Comment by fenrus75** [comment]
hmmm openssl is really being evil here... but I'll fix our zlib package to
always include the development file openssl expects at runtime

**Comment by ahkok** [comment]
Seems fixed today already.

**Comment by ahkok** [comment]
`27050`

**Comment by omkhar** [comment]
Confirmed fixed

**Comment by MichaelCurrie** [comment]
```
penssl genrsa -des3 -out myCA.key 2048 -passin pass:asdfasdf
Extra arguments given.
genrsa: Use -help for summary.
```
Gives this error:

```
21276:error:25078067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(providers.dll)
21276:error:25070067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:162:
21276:error:0E07506E:configuration file routines:module_load_dso:error loading dso:crypto\conf\conf_mod.c:224:module=providers, path=providers
21276:error:0E076071:configuration file routines:module_run:unknown module name:crypto\conf\conf_mod.c:165:module=providers
```

**Comment by fenrus75** [comment]
works for me in clear linux release 36520
