### ISSUE TITLE
OpenVPN-AS server unable to start inside docker container - service failed to start due to unresolved dependencies

### ISSUE THREAD

**Issue by tuxmeister** [clearlinux/distribution#347]
**Describe the bug**
Using linuxserver/openvpn-as image in docker, I am unable to start the server once inside the admin panel. 

Receiving the following error block: https://pastebin.com/eZ6ghUQn

**To Reproduce**
1. Create container with following command: docker create --name openvpn --hostname GateKeeper -v openvpn-data:/config -e TZ="Europe/Stockholm" -e INTERFACE=eno1 --net=host --privileged linuxserver/openvpn-as:latest
2. Log into admin panel via http://ipAddress:943/admin
3. Start the server

**Expected behavior**
The server should start correctly without any issues.

**Environment:**
 - Clear Linux OS version: 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27050
 - Bundles: 
acpica-unix2
bootloader
containers-basic
curl
diffutils
dosfstools
enterprise-login
ethtool
file
findutils
git
gzip
htop
iftop
iproute2
irssi
kbd
kernel-install
kernel-native
kvm-host
kvm-host-extras
less
libX11client
linux-tools
network-basic
nfs-utils
nmap
openssh-server
openssl
os-core
os-core-update
p11-kit
parallel
patch
performance-tools
perl-basic
pmdk
powertop
python3-basic
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
sysstat
tcl-basic
telemetrics
tmux
tzdata
unzip
vim
weechat
which
wpa_supplicant
xfsprogs
xz
znc
zsh
zstd

**Additional context**
This container works perfectly on latest debian-stable, with no modifications in run / create command. I googled around for this issue but I couldn't find a matching result. Contacted LinuxServer.io about their image but referred me to you since the image works fine on other systems.

**Comment by fenrus75** [comment]
containers generally can't load kernel ,modules

you might need to load the iptables kernel modules on the host side first

**Comment by tuxmeister** [comment]
OpenVPN-AS requires these modules to be available but I cannot find the last two:

modprobe tun, ipt_mark, ipt_MARK

It seems some necessary modules are missing from your kernel. I couldn't find instructions on how to build these individually, can you provide guidance?

Thanks!

**Comment by fenrus75** [comment]
CONFIG_NETFILTER_XT_MARK=y

we have that one not as a module but built into the binary

**Comment by tuxmeister** [comment]
Forgive my ignorance here but I assume this is a line I need to add to the kernel .config file, yet ClearLinux delivers pre-built kernels for security. Can I build my own? Or am I missing where to put the line you mentioned?

**Comment by fenrus75** [comment]
sorry no that is already in our kernel, so you should not need to do
anything
