### ISSUE TITLE
support DKMS

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#349]
we should see if we can support dkms to make it easier to maintain out of tree drivers.

**Comment by ahkok** [comment]
@btwarden maybe something we can look into?

**Comment by thiagomacieira** [comment]
Not sure we want to make this easy, since kernel modules need to be signed in order to be loaded. Disabling the signature check is a security hole.

**Comment by bwarden** [comment]
Bundle created: `kernel-native-dkms`. Documentation in progress.

**Comment by bwarden** [comment]
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules-dkms
