### ISSUE TITLE
vfio and macvlan kernel module?...

### ISSUE THREAD

**Issue by KyungWon-Park** [clearlinux/distribution#350]
Hello 

I want to try Clear Linux for my virtualization host

But I've found that vfio and macvlan kernel module do not come with Clear Linux install

These modules are commonly used in virtualization environment

So I hope Clear Linux will support these modules in the future 

Thank you

**Comment by KyungWon-Park** [comment]
Oh I've found that macvlan is built in

**Comment by ahkok** [comment]
VFIO is builtin all kernels.

**Comment by ahkok** [comment]
Actually, in the -kvm kernel it's a module, but all kernels have it nonetheless.
