### ISSUE TITLE
Consider replacing iptraf with iptraf-ng

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#352]
**Is your feature request related to a problem? Please describe.**
The current source URL for iptraf (ftp://iptraf.seul.org/pub/iptraf/iptraf-3.0.0.tar.gz) does not resolve, so a working mirror is needed for that tarball or replacement should be found. I could not find a mirror.

**Describe the solution you'd like**
There is a fork of iptraf, iptraf-ng, that could replace iptraf. See https://github.com/iptraf-ng/iptraf-ng.

**Comment by fenrus75** [comment]
iptraf-ng is not exactly the pinnacle of development activity either afaics

**Comment by phmccarty** [comment]
Let's track this is #1212
