### ISSUE TITLE
tmux is not reading $HOME/.tmux.conf

### ISSUE THREAD

**Issue by markgross** [clearlinux/distribution#354]
Recently TMUX might have been updated and broke mouse selections / copy 

After some asking around it seems that I NOW have to hold the shift key when sellecting text to get the selection to work and be copied to the clipboard.

However; center mouse click doesn't seem to paste.

Further I found out the TMUX changed some of its config options for mouse behavior.  So, I updated my .tmux.conf file 

I then saw no change.
Then I got a copy of a Sean's (coworker) $HOME/.tmux.conf tile and attempted to use it and I saw no change in behavior.

finally I ran 
strace -o tmux.trace -ff tmux
to see if its even reading the .tmux.conf
its not.

To test add a .tmux.conf file to your $HOME and change it to set the status bar to green and then restart TMUX.  
set-option -g status-bg green  

Notice it stays yellow.

**Expected behavior**
I expect tmux to read and apply my local conf settings.

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
mgross@mtgdev ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27160
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
  1 acpica-unix2                                                                    
  2 bc                                                                              
  3 bootloader                                                                      
  4 c-basic                                                                         
  5 cabextract                                                                      
  6 cloc                                                                            
  7 cloud-api                                                                       
  8 clr-devops                                                                      
  9 cockpit                                                                         
 10 computer-vision-basic                                                           
 11 computer-vision-models                                                          
 12 containers-basic                                                                
 13 cpio                                                                            
 14 curl                                                                            
 15 dev-utils                                                                       
 16 dev-utils-dev                                                                   
 17 diffoscope                                                                      
 18 diffutils                                                                       
 19 docutils                                                                        
 20 dosfstools                                                                      
 21 editors                                                                         
 22 emacs                                                                           
 23 ethtool                                                                         
 24 file                                                                            
 25 findutils                                                                       
 26 gdb                                                                             
 27 git                                                                             
 28 global                                                                          
 29 go-basic                                                                        
 30 gzip                                                                            
 31 htop                                                                            
 32 httpd                                                                           
 33 icdiff                                                                          
 34 inotify-tools                                                                   
 35 iproute2                                                                        
 36 irssi                                                                           
 37 java-basic                                                                      
 38 joe                                                                             
 39 kbd                                                                             
 40 kernel-install                                                                  
 41 kernel-native                                                                   
 42 koji                                                                            
 43 kvm-host                                                                        
 44 less                                                                            
 45 libX11client                                                                    
 46 linux-tools                                                                     
 47 llvm                                                                            
 48 machine-learning-basic                                                          
 49 machine-learning-mycroft                                                        
 50 machine-learning-tensorflow                                                     
 51 mail-utils                                                                      
 52 mail-utils-dev                                                                  
 53 make                                                                            
 54 mixer                                                                           
 55 mkosi                                                                           
 56 nasm                                                                            
 57 network-basic                                                                   
 58 network-basic-dev                                                               
 59 nfs-utils                                                                       
 60 nginx                                                                           
 61 openssh-server                                                                  
 62 openssl                                                                         
 63 os-clr-on-clr                                                                   
 64 os-core                                                                         
 65 os-core-dev                                                                     
 66 os-core-update                                                                  
 67 os-core-update-dev                                                              
 68 os-installer                                                                    
 69 p11-kit                                                                         
 70 package-builder                                                                 
 71 package-utils  
 72 parallel                                                                                               
 73 patch                                                                                                  
 74 perl-basic                                                                                             
 75 perl-basic-dev                                                                                         
 76 pmdk                                                                                                   
 77 postgresql                                                                                             
 78 powertop                                                                                               
 79 python-data-science                                                                                    
 80 python-extras                                                                                          
 81 python2-basic                                                                                          
 82 python3-basic                                                                                          
 83 rust-basic                                                                                             
 84 scm-server                                                                                             
 85 shells                                                                                                 
 86 smartmontools                                                                                          
 87 storage-utils                                                                                          
 88 storage-utils-dev                                                                                      
 89 strace                                                                                                 
 90 sudo                                                                                                   
 91 sysadmin-basic                                                                                         
 92 sysadmin-basic-dev                                                                                     
 93 sysadmin-remote                                                                                        
 94 telemetrics                                                                                            
 95 tmux                                                                                                   
 96 tzdata                                                                                                 
 97 unzip                                                                                                  
 98 user-basic                                                                                             
 99 valgrind                                                                                               
100 vim                                                                                                    
101 web-server-basic                                                                                       
102 weechat                                                                                                
103 which                                                                                                  
104 wpa_supplicant                                                                                         
105 xfsprogs                                                                                               
106 xz                                                                                                     
107 znc                                                                                                    
108 zsh                                                                                                    
109 zstd  

**Additional context**

**Comment by markgross** [comment]
ok now tmux has a green status bar!
and mouse select and paste seems to work.
and its trying to open the tmux.conf

tmux.trace.7295:openat(AT_FDCWD, "/etc/tmux.conf", O_RDONLY) = -1 ENOENT (No such file or directory)
tmux.trace.7295:openat(AT_FDCWD, "/home/mgross/.tmux.conf", O_RDONLY) = -1 ENOENT (No such file or directory)

Add a test to make sure stuff like this doesn't break.  I wasted 4 hrs on this.

**Comment by bryteise** [comment]
@markgross So the same version of tmux would sometimes try to open ~/.tmux.conf and sometimes not?

**Comment by ahkok** [comment]
`o_O`

The tmux package hasn't changed since november. What changed on your system between your opening of the bug, and your second comment?

**Comment by ahkok** [comment]
> `Notice it stays yellow.`

without a `.tmux.conf` my bar is `green` to begin with, so the config change line *does nothing*.

I googled some examples and tried different colors (`red`, `blue`, `colour18`) and that all works.

**Comment by markgross** [comment]
My system had auto updates enabled until this morning.  The changes between my initial bug report and my previous comment was a reboot to use the updated kernel this morning.

Its interesting that tmux has not changed since november.  Something must have change that tmux depends on for correct operation that fixed itself on the reboot.  When I talked to Sean about it yesterday I got the impression that others had experienced.

**Comment by markgross** [comment]
I think swupd auto update corrupted some OS dependency tmux needs to work and after the reboot the problem was gone.  
i.e. auto updates (without reboots) are not good because they have side effects like this.

**Comment by seanvk** [comment]
As I mentioned to Mark offline, ~/.tmux.conf is being read by tmux for me.  I made a simple key binding addition to my .tmux.conf:

bind m set-option mouse\; display-message "Mouse is now #{?mouse,on,off}"

ctrl-b m works fine as a result. So I am unable to reproduce...

Sean
