### ISSUE TITLE
Please package the github "git-hub" script as /usr/bin/git-hub

### ISSUE THREAD

**Issue by joshtriplett** [clearlinux/distribution#358]
github has a script "git-hub" that allows opening pull requests and similar from the command line; please consider packaging it.

**Comment by fenrus75** [comment]
it's called "hub" and we do ship that.

**Comment by joshtriplett** [comment]
@fenrus75 Ah, `swupd search git-hub` didn't turn it up because it's only installed as `/usr/bin/hub`. Could you please install a link `/usr/bin/git-hub`, which allows running it as `git hub ...`?

**Comment by fenrus75** [comment]
should be in the build tomorrow morning

**Comment by miguelinux** [comment]
**hub** is from https://github.com/github/hub

@joshtriplett do you mean https://github.com/ingydotnet/git-hub

hub is from github and as @fenrus75 said we already ship it.
https://hub.github.com/

**Comment by joshtriplett** [comment]
@miguelinux I originally used the unofficial one, and I'm working on switching to the official one. Both can sensibly be installed as `git-hub` though, which allows commands like `git hub clone`.

**Comment by mrkz** [comment]
> @fenrus75 Ah, `swupd search git-hub` didn't turn it up because it's only installed as `/usr/bin/hub`. Could you please install a link `/usr/bin/git-hub`, which allows running it as `git hub ...`?

This enhancement has been completed and confirmed:
```
 % ll /usr/bin/git-hub
lrwxrwxrwx 1 root root 3 Jan 12  2017 /usr/bin/git-hub -> hub
 % cat /usr/share/clear/version
27700  
```

Closing this thread now.
