### ISSUE TITLE
some GTK labels are not being properly displayed

### ISSUE THREAD

**Issue by hnanni** [clearlinux/distribution#359]
**Describe the bug**

After update, some labels in GTK buttons are gone

**To Reproduce**
After updating to 27290, some gnome apps got some new icons, however, there are labels in buttons that are now displayed with an unknown character. Check the attached screenshot for an example

**Screenshots**
![screenshot from 2019-01-16 14-14-02](https://user-images.githubusercontent.com/44509485/51275979-0b319400-1999-11e9-9db0-a1d660c60f18.png)

**Environment (please complete the following information):**
 - Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
VERSION_ID=27290

gtk theme: adwaita-dark

 - Bundles: [e.g. `sudo swupd bundle-list`]
ImageMagick
acpica-unix2
alsa-utils
ansible
atom
bc
bootloader
bootloader-extras
c-basic
cabextract
cloc
containers-basic
cpio
cryptography
curl
darktable
desktop
desktop-apps
desktop-apps-extras
desktop-assets
desktop-autostart
desktop-dev
desktop-gnomelibs
desktop-kde-apps
desktop-kde-libs
desktop-locales
dev-utils
dev-utils-dev
diffoscope
diffutils
docutils
dosfstools
editors
editors-dev
emacs
ethtool
file
findutils
firefox
fuse
fwupdate
gdb
gimp
git
global
go-basic
go-basic-dev
gzip
htop
httpd
icdiff
inotify-tools
ipmitool
iproute2
irssi
joe
kbd
kernel-install
kernel-native
koji
kvm-host
kvm-host-dev
less
libX11client
libva-utils
linux-tools
llvm
mail-utils
mail-utils-dev
make
meld
mixer
mkosi
nasm
network-basic
network-basic-dev
nfs-utils
nginx
openssh-server
openssl
os-clr-on-clr
os-clr-on-clr-dev
os-core
os-core-dev
os-core-update
os-core-update-dev
os-installer
os-utils-gui
p11-kit
package-builder
package-utils
parallel
patch
perl-basic
perl-basic-dev
pidgin
plzip
pmdk
postgresql
powertop
pxe-server
python2-basic
python3-basic
qt-basic
smartmontools
storage-utils
storage-utils-dev
strace
sudo
sysadmin-basic
sysadmin-basic-dev
sysadmin-hostmgmt
telemetrics
thunderbird
tmux
tzdata
unzip
valgrind
vim
virt-manager
vlc
web-server-basic
weechat
which
wireshark
wpa_supplicant
x11-server
x11-tools
xemacs
xfce4-desktop
xfsprogs
xz
znc
zstd

**Comment by ahkok** [comment]
@mrkz

**Comment by hnanni** [comment]
issue is gone in 27410
