### ISSUE TITLE
Invalid LC_CTYPE

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#36]
With today's update I am seeing new bash shells complain about LC_TYPE via the following:
"bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)"

**Comment by fenrus75** [comment]
looks like something weird happened

I just added a BBT regression test for this case at least

**Comment by phmccarty** [comment]
I'm working on this.

**Comment by phmccarty** [comment]
This issue was fixed in 21640.
