### ISSUE TITLE
Please package xterm

### ISSUE THREAD

**Issue by joshtriplett** [clearlinux/distribution#362]
xterm doesn't appear to be packaged. Some third-party software (e.g. Simics) depends on having an `xterm` command available. Please consider packaging it in one of the bundles of X tools.

**Comment by thiagomacieira** [comment]
Specfile posted. It's only 250 kB, but I don't want to add it to any bundle. So a pundle it is.

**Comment by joshtriplett** [comment]
@thiagomacieira A pundle seems useful, but xterm also seems reasonable to include in x11-tools along with things like xrdb.

**Comment by ahkok** [comment]
I'm still waiting for `xkill`, not `xterm` myself. I'd think x11-tools is OK considering the size of most X11 tools

**Comment by ahkok** [comment]
xterm pundle available, already.

**Comment by thiagomacieira** [comment]
Got it, also adding to x11-tools bundle.
