### ISSUE TITLE
Please consider adding neovim

### ISSUE THREAD

**Issue by curantes** [clearlinux/distribution#366]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please consider package neovim as a replacement or compliment to regular vim.

**Describe alternatives you've considered**
vim works, but I think neovim is superior with more clean code base than vim and can act as a drop in replacement. I use a lot of plugins with neovim. Sure there is a neovim flatpak but I think it would be more nice to have it native in the repository.

**Additional context**
https://neovim.io/
https://github.com/neovim/neovim

**Comment by probonopd** [comment]
@curantes did you try the AppImage on Clear Linux OS?
https://github.com/neovim/neovim/wiki/Installing-Neovim#appimage-universal-linux-package

**Comment by mrkz** [comment]
started looking into this, already got some dependencies built, expect to arrive soon-ish (still not highest priority)

**Comment by mrkz** [comment]
Hello @curantes,

A bit late, but I'd  like to update this comment saying that `neovim` bundle is available since release **30620** (or later).

Thanks for the patience (and the request)! :tada: 

Closing this issue now.
