### ISSUE TITLE
Please package gnulib

### ISSUE THREAD

**Issue by joshuagl** [clearlinux/distribution#368]
We use [_gnulib_](https://www.gnu.org/software/gnulib) in various of the [tpm2-software](https://github.com/tpm2-software/) projects for `ld-version-script.m4`

**Comment by ahkok** [comment]
Which package requires this?

**Comment by thiagomacieira** [comment]
https://www.gnu.org/software/gnulib/:
> Gnulib does not make releases. It is intended to be used at the source level.

**Comment by thiagomacieira** [comment]
Distro search:
* Arch Linux: no package
* Debian: does package, dated 20140202 (https://packages.debian.org/source/stretch/gnulib, also in sid)
* Gentoo: Doc-only build (https://packages.gentoo.org/packages/dev-libs/gnulib)
* Fedora: does package, dated 20180720, heavily custom RPM (https://src.fedoraproject.org/rpms/gnulib)
* openSUSE: no package

**Comment by joshuagl** [comment]
Thanks @thiagomacieira for providing these details. I've been working with the upstream to understand why `ld-version-script.m4` was removed and will work on a PR to add it back to tpm2-tss.
