### ISSUE TITLE
connectivity issues to clearlinux's CDN

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#370]
https://download.clearlinux.org doesn't seem to be reachable at all since, at least, 7 hrs ago... 

thanks in advance!

**Comment by AntonioMeireles** [comment]
closing as things look back to normal, again. thanks!

**Comment by AntonioMeireles** [comment]
reopening, as it seems down again :-(

**Comment by emerzon** [comment]
Same issue here, install blocked (Network not working during install attempt)
Even if updating swupd mirror address, main CDN address is still used.
