### ISSUE TITLE
Setup return Panic: exit status 1

### ISSUE THREAD

**Issue by viardot** [clearlinux/distribution#374]
**Describe the bug**

First thing to notice is that the screens do not look like the once on the web site of intel. 

Start Clear Linux setup; choose the required option; Select auto config for disk layout; start install.
Network check goes well. Than confirm overwriting media. Short moment black screen. then:

panic: exit status 1

Error Trace:
errors.Wrap()
      errors/errors.go:91
storage.makeFs()
      storage/ops.go:78

grouting 11 [running]:

**To Reproduce**
1. used setup 27330 
2. used setup 26990
3. tried with advanced options

**Expected behavior**
Setup should install clear linux.

**Screenshots**
not possible jet. Still in installation fase

**Environment (please complete the following information):**
 - Clear Linux OS version: 27330
 - Bundles: none jet still in install fase

**Additional context**
The install is on a NUC6CAYS that should work according to Intel......

**Comment by ahkok** [comment]
The installer you're using is relatively new and the website documentation needs an update. 

@clearlinux/clear-technologies-documentation-maintainers 

@mdhorn Looks like like a fatal bug.

**Comment by mvincerx** [comment]
Yes, I'm working on it. Thanks for the heads-up. 
https://github.com/clearlinux/clear-linux-documentation/pull/358

**Comment by mvincerx** [comment]
@viardot. Thank you for  your patience. In the meantime, you may use this document for the updated interface. https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-beta#id11

Changes to the main installer image document will be updated shortly.

**Comment by mdhorn** [comment]
@viardot On the installation media, there should be the following files in the root home directory:
```
/root/clr-installer.log
/root/pre-install-clr-installer.yaml
```
Could you share the contents?

For extra credit, if you are able to add the following to the kernel boot parameters during startup:
- Hit 'e' to enter Edit mode on the Clear Linux boot screen
- Go to the end of the line (right arrow)
- add `clri.loglevel=4`

The log file will have a lot more details about the installation process.

**Comment by viardot** [comment]
I would, if I could.

insert the USB boot disk into MAC. I can't mount the disk
insert the USB boot disk into Ubuntu. It mounts, but it would let me read the root.

**Comment by mdhorn** [comment]
@viardot On the ubuntu system, can you try
`sudo cat <mount point>/root/pre-install-clr-installer.yaml`

**Comment by viardot** [comment]
[clr-installer.log](https://github.com/clearlinux/distribution/files/2788526/clr-installer.log)
[pre-install-clr-installer.yaml.log](https://github.com/clearlinux/distribution/files/2788527/pre-install-clr-installer.yaml.log)
Thank you @mdhorn,
It worked and both files are attached.

**Comment by mdhorn** [comment]
@viardot Thank you for the files. You're encountering a bug we just recently fixed:
https://github.com/clearlinux/clr-installer/issues/195

The fix is in the sources, but there had not been a bug-fix release since the change.
Let me see if I can generate a release today which will have in it Clear Linux in the next few days.

**Comment by mvincerx** [comment]
@mdhorn, @ahkok, I updated the clearlinux.org documentation for the bare-metal-install (installer image) use case. See: https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install

@viardot, thanks for your patience.

**Comment by mdhorn** [comment]
@viardot Clear Linux OS 27430 has a new release of the Installer 1.1.4 with a fix for the issue reported.

**Comment by viardot** [comment]
many thanks. with version 1.1.4 of the installer I could install clear linux on the NUC.
