### ISSUE TITLE
Possible to have git gui installed in a non-usable state

### ISSUE THREAD

**Issue by joshuagl** [clearlinux/distribution#377]
**Describe the bug**
I'm not sure which of my installed bundles brought git gui in, but it wasn't usable:

foo@jbar ~ $ git gui
/usr/libexec/git-core/git-gui: line 10: exec: wish: not found

I was able to work around the issue by installing the tcl-basic bundle.

**Expected behavior**
Bundles including git gui should also include sufficient dependencies to run git gui, i.e. wish.

**Environment (please complete the following information):**
 - Clear Linux OS version: 27400
 - Bundles:

> acpica-unix2
> alsa-utils
> bc
> bootloader
> c-basic
> cloc
> cpio
> cryptoprocessor-management
> cryptoprocessor-management-dev
> curl
> desktop
> desktop-apps
> desktop-assets
> desktop-autostart
> desktop-gnomelibs
> desktop-locales
> dev-utils
> devpkg-base
> devpkg-dbus
> devpkg-elfutils
> devpkg-expat
> devpkg-glib
> devpkg-libX11
> devpkg-libpthread-stubs
> devpkg-libxkbcommon
> devpkg-libxml2
> devpkg-openssl
> devpkg-pcre
> devpkg-util-linux
> devpkg-xorgproto
> devpkg-xz
> devpkg-zlib
> diffutils
> docbook-utils
> docutils
> doxygen
> editors
> emacs
> enterprise-login
> ethtool
> file
> findutils
> firefox
> fuse
> fwupdate
> gdb
> git
> gzip
> htop
> icdiff
> inotify-tools
> intltool
> iproute2
> irssi
> joe
> kbd
> kernel-install
> kernel-lts
> kernel-native
> less
> libX11client
> libva-utils
> libxslt
> linux-tools
> llvm
> make
> nasm
> network-basic
> openssl
> os-core
> os-core-dev
> os-core-update
> os-core-webproxy
> p11-kit
> parallel
> patch
> perl-basic
> pidgin
> powertop
> python-basic
> python2-basic
> python3-basic
> software-testing
> strace
> sudo
> sysadmin-basic
> telemetrics
> texinfo
> tmux
> tzdata
> unzip
> valgrind
> vim
> weechat
> which
> wpa_supplicant
> x11-server
> xemacs
> xz
> znc
> zstd

**Comment by ahkok** [comment]
I believe this is on purpose.

`git gui` would have to be split into several difficult to maintain bundles. You need `tcl-basic` to get `wish`. We could patch some of these, but it would add 700mb and git should remain a small, basic bundle.

**Comment by joshuagl** [comment]
I can understand the rationale there, I think, though the experience is less than satisfying. 

Presumably for this specific instance we could split git-gui and gitk out of the git package and include that package in (an)other bundle(s) with the tcl-basic dependency included? I suppose that's work you're trying to avoid?

I worry that this hints at a deeper issue... but I don't know how pervasive these kind of runtime dependencies are.

It won't help in this specific instance, but it would be nice to add a bash `command_not_found_handle` or leverage PackageKit's if Clear Linux is intending to support PK?
Perhaps I should file that as a separate issue?

**Comment by fenrus75** [comment]
I'm creating a dev-utils-gui bundle which will have the git-gui/gitk side
of things, and then dev-utils will not have these
(so that command-not-found etc will point at the new bundle)

**Comment by joshuagl** [comment]
> It won't help in this specific instance, but it would be nice to add a bash `command_not_found_handle` or leverage PackageKit's if Clear Linux is intending to support PK?
> Perhaps I should file that as a separate issue?

Ah, there is a `command_not_found_handle` (and it's pretty fast, too). It's just that the two programs I tried (*gitg* and *qgit*) aren't present in any swupd bundles.

**Comment by tpleavitt** [comment]
fixed
