### ISSUE TITLE
KDE Alpha Channel Wrappers on Plasma/KDE Apps

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#378]
**Describe the bug**
Apps have a desktop WM ring rendering 
**To Reproduce**
1. Install KDE
2. Select Plasma in DM of your choice
3. Launch a Terminal
4. PROFIT!!!

**Expected behavior**
N o Rings.

**Screenshots**
https://drive.google.com/file/d/1IZlmxbPrjOYec4fEwlZk7SshllHx2S6H/view?usp=sharing

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by seanvk** [comment]
Replicated with Integrated Graphics and Nvidia GTX 1070 Ti

**Comment by anselmolsm** [comment]
Just to add more info about those rings: They are window shadows, which are enabled by default in the default theme (breeze).

Not a fix, but a temporary way to get rid of the (d)effect:
alt+f2 (to run krunner), type window decoration -> configure Breeze (or other theme) -> shadows -> size None

**Comment by thiagomacieira** [comment]
Even with XRender?

**Comment by anselmolsm** [comment]
Breeze with XRender:

![screenshot_20190123_115457](https://user-images.githubusercontent.com/136474/51633348-4f2b1880-1f06-11e9-8dab-09fc96899d94.png)

I tested Oxygen, and the shadows work fine (XRender, opengl, changing colors and shadow sizes):

![screenshot_20190123_120426](https://user-images.githubusercontent.com/136474/51633694-1a6b9100-1f07-11e9-8a16-e9be55223a8b.png)

**Comment by seanvk** [comment]
An easier work-around, aside from switching completely to something other than breeze, is to simply change Window Decorations in Settings to something like Air-Oxygen.

**Comment by anselmolsm** [comment]
Not reproducible anymore with Intel integrated graphics on Clear Linux 28480 with KDE Frameworks 5.56.0, Qt 5.12.2, X session, rendering backend: Open GL. And Breeze window decoration + shadows on :)


![Screenshot_20190325_143428](https://user-images.githubusercontent.com/136474/54955761-75bbfe80-4f0b-11e9-9d47-4b45597b9ab2.png)

**Comment by anselmolsm** [comment]
Please reopen this if you experience the issue again. Thanks.
