### ISSUE TITLE
gnome-tweak-tool unable to successfully launch

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#38]
Attempting to start the gnome-tweak-tool from the gnome desktop results in nothing apparently happening.  Checking the process table I can see 'python3 /usr/bin/gnome-tweak-tool' is running, so after killing it and starting directly on the command line I can see:

 $ python3 /usr/bin/gnome-tweak-tool 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gtweak/widgets.py", line 164, in __init__
    self.settings = GSettingsSetting(schema_name, **options)
  File "/usr/lib/python3.6/site-packages/gtweak/gsettings.py", line 124, in __init__
    raise GSettingsMissingError(schema_name)
gtweak.gsettings.GSettingsMissingError: org.gnome.nautilus.desktop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/gtweak/app.py", line 43, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python3.6/site-packages/gtweak/tweakview.py", line 59, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python3.6/site-packages/gtweak/tweakmodel.py", line 117, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python3.6/site-packages/gtweak/tweaks/tweak_group_desktop.py", line 26, in <module>
    GSettingsSwitchTweak(_("Home"),"org.gnome.nautilus.desktop", "home-icon-visible", depends_on=dicons, schema_filename="org.gnome.nautilus.gschema.xml"),
  File "/usr/lib/python3.6/site-packages/gtweak/widgets.py", line 276, in __init__
    _GSettingsTweak.__init__(self, name, schema_name, key_name, **options)
  File "/usr/lib/python3.6/site-packages/gtweak/widgets.py", line 173, in __init__
    logging.info("GSetting missing %s" % (e.message))
AttributeError: 'GSettingsMissingError' object has no attribute 'message'

Note that the tool works in 21600.  I can swupd verify back to the old version and see it work, and then update and see it break again

**Comment by rustylynch** [comment]
The problem is that the org.gnome.nautilus.gschema.xml file installed by the nautilus package has removed the desktop schema that the gnome-tweaks-tool requires.

**Comment by mrkz** [comment]
@rustylynch Thanks for the report, I reverted the nautilus update, so gnome-tweak-tool is no longer broken while I look at the fix :-)

**Comment by rustylynch** [comment]
actually... it might be better to pull in on patch from the upstream gnome-tweak-tool

https://gitlab.gnome.org/GNOME/gnome-tweaks/commit/1b7149f8f5f38726822439d6b9c960801ca9ecb2

**Comment by rustylynch** [comment]
I can verify it works for me

**Comment by fenrus75** [comment]
Added a BBT test for this

**Comment by mrkz** [comment]
@rustylynch I cherry-picked the patch you pointed out and verify it works, should be fixed in the following updates. Will close this bug once the fix is released

**Comment by sashaelvira** [comment]
i cant run tweak tool
