### ISSUE TITLE
KDE + SDDM and Desktop-Autostart acts like it is in touch screen mode

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#380]
**Describe the bug**
Switching to KDE + SDDM + Desktop Autostart shows a large keyboard giving the impression it is misconfigured into some sort of touch screen mode on my desktop computer.

**To Reproduce**
1. swupd bundle-add kde for desktop, apps and libs
2. swupd bundle-remove desktop desktop-autostart
3. swupd bundle-add desktop-autostart
4. systemctl mask gdm
5. systemctl enable sddm
6. Reboot

**Expected behavior**
Expected the SDDM login window.  Instead got a large oversized keyboard displayed on my desktop monitor.

**Screenshots**
https://drive.google.com/file/d/1P7Prc5rplHICFdpmG7CClutiLS8cuK-x/view?usp=sharing

**Environment (please complete the following information):**
 - Clear Linux OS version: [Current]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by seanvk** [comment]
You can make the keyboard go away by hitting Enter.

**Comment by seanvk** [comment]
But it comes back when you click on the password field.

**Comment by seanvk** [comment]
If you hit enter again, you can actually type in the password field.

**Comment by anselmolsm** [comment]
That's the default config of sddm, InputMethod=qtvirtualkeyboard. It's annoying with its default theme, but it does not appear with other themes (KDE's one, for example). We should turn that off by setting InputMethod empty.

**Comment by seanvk** [comment]
@anselmolsm I agree.  For now I switched to lightdm.

**Comment by anselmolsm** [comment]
Update on this: New sddm package with changes mentioned above is out.

In addition to that, [sddm-autostart](https://download.clearlinux.org/releases/current/clear/x86_64/os/Packages/sddm-autostart-0.18.0-6.x86_64.rpm) might get into desktop-kde bundle shortly.

**Comment by anselmolsm** [comment]
Closing this as autostart & virtual keyboard fixes got released already. Tks.

**Comment by dannykorpan** [comment]
Issue is present again in Clear Linux OS 36250.
