### ISSUE TITLE
Please Add MongoDB

### ISSUE THREAD

**Issue by seanvk** [clearlinux/distribution#382]
**Is your feature request related to a problem? Please describe.**
* MongoDB is one of the top 5 DB in use today for (No)/SQL databases
  * https://insights.stackoverflow.com/survey/2018/#technology-databases
* It's a part of benchmarks used in the industry

That being said, the SSPL licence has come under fire:
https://www.phoronix.com/scan.php?page=news_item&px=Fedora-No-SSPLv2-License

**Describe the solution you'd like**
Add MongoDB as a package and Bundle

**Describe alternatives you've considered**
Require customers to manually install

**Additional context**
* It's a dependency for some customer use cases for Rendering
* We have customers who make use of it for their Rendering work for CCG
* It's available on Ubuntu and we are being compared to those solutions.

I'm flexible.  Just wanted to test the waters so to speak.

Thank you.

Sean

**Comment by ahkok** [comment]
For now, we won't add this.
