### ISSUE TITLE
Enhance swupd suggestions to specify 'sudo' when/if needed ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#386]
When trying to run a not-yet-installed program, a nice feature of CLR is to suggest the swupd command to install required bundle :
$ hg
hg: command not found
To install hg use:  swupd bundle-add mercurial
This is specially handy for newcomers, that are not yet familiar with bundle names etc..
However, if we execute the specified swupd command as-is, it might not work if the current user (that got the suggestion) eg: is sudoer and not root (standard case), ie:
$ swupd bundle-add mercurial
This program must be run as root..aborting.

What I would like would be for the suggestion system to detect if current user is sudoer, and do like that :
$ hg
hg: command not found
To install hg use:  sudo swupd bundle-add mercurial
$ sudo swupd bundle-add mercurial
...
Successfully installed 1 bundle

For example, on Ubuntu 18.10, we get this kind of sudo/non-sudo suggestions for various users :
(sudoer user) $ aqemu
Command 'aqemu' not found, but can be installed with:
sudo apt install aqemu

(root) # aqemu
Command 'aqemu' not found, but can be installed with:
sudo apt install aqemu

(non-sudoer user) $ aqemu
Command 'aqemu' not found, but can be installed with:
apt install aqemu
Please ask your administrator.

**Comment by ahkok** [comment]
Done, it'll be 1-2 days but then this works as suggested above: root usage is unchanged. If the user is in a sudo group, sudo will be suggested, otherwise a message is displayed that the admin will need to perform an installation.

**Comment by nsauzede** [comment]
Yeah sorry, I made a typo (copy-paste) glitch for the "root" case on Ubuntu 18.10, it goes like this :

(root) # aqemu
Command 'aqemu' not found, but can be installed with:
apt install aqemu

So you're right that CLR root usage should keep unchanged, only for the two other cases (non-root, sudoer/non-sudoer)
