### ISSUE TITLE
Please create a bundle "Stellarium"

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#387]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Stellarium is a popular open source desktop software for astronomers/night sky watchers. It builds/runs under Clear Linux without any problems. Would be nice to have a bundle available, though.

**Describe alternatives you've considered**
Users can build the app themselves, following the instructions:
http://stellarium.sourceforge.net/wiki/index.php/Compilation_on_Linux

**Additional context**
The package is readily available for Ubuntu:
<pre>
$ sudo apt-get install stellarium
</pre>

License:  GPL

**Comment by ahkok** [comment]
In progress.

**Comment by jurobystricky** [comment]
Thanks, much appreciated.

**Comment by ahkok** [comment]
`flatpak install flathub org.stellarium.Stellarium` works on clearlinux.

Still in progress, should take another day or so.
