### ISSUE TITLE
Additinal Qt libraries needed

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#388]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to use "Beyond Compare" package. 
https://www.scootersoftware.com/download.php?zz=kb_linux_install
"Beyond Compare" on CLR is not directly supported, but it should still be possible to install it following the instructions. However, CLR misses some additional Qt libraries:
Please bundle the following:
<pre>
libQtGui.so.4 => not found
libQtNetwork.so.4 => not found
libQtCore.so.4 => not found
</pre>

**Describe alternatives you've considered**
The above libraries can be found in some Fedora RPMs, but installing those on CLR leads to some incompatibility problems (ssl). Not to mention, installing non-CLR RPMs it is not recommended anyway.

**Additional context**
Unfortunately, "Beyond Compare" is not an open source project, preventing a CLR bundle.
However, there may be additional 3rd party software that may need the above libraries.

**Comment by anselmolsm** [comment]
The libs listed above are part of Qt4.

**Comment by jurobystricky** [comment]
I don't think so, I ran:
<pre>
sudo swupd search libQt
</pre>
and did not see them.

**Comment by jurobystricky** [comment]
Oh, I see. CLR has Qt5. Isn't there a compatibility layer?

**Comment by anselmolsm** [comment]
No, there is not.

**Comment by thiagomacieira** [comment]
Sorry, we will not add Qt 4. Those libraries are End-of-Life by upstream and not receiving security updates.
