### ISSUE TITLE
Consider including Roboto font

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#391]
**Is your feature request related to a problem? Please describe.**
The Materia theme used by default in Clear Linux recommends installing the Roboto font. The Gnome shell theme will then utilise this font instead of falling back to Cantarell, which should make the desktop look a little more pleasant.

**Describe the solution you'd like**
Consider packaging Roboto font

**Describe alternatives you've considered**
None.

**Additional context**
This is included in most distro repositories.

**Comment by ahkok** [comment]
@mrkz want to look into this?

**Comment by phmccarty** [comment]
Resolved with https://github.com/clearlinux/clr-bundles/commit/06d14128dee794950f07b265bd723e3daec170fc

**Comment by pceiley** [comment]
Thanks!
