### ISSUE TITLE
WINE will not run even its own internals, produces plenty of error messages

### ISSUE THREAD

**Issue by Nirgendsdorf** [clearlinux/distribution#395]
**Describe the bug**
I tried launching two internals: 'wine notepad' and 'winecfg'. Wine does open an icon in the gnome taskbar, and does sometimes open a window for notepad. Running 'winecfg' also opens a wine icon in the taskbar. Both output lots of error messages to the terminal window.

**To Reproduce**
1. Login as a user, open the gnome terminal.
2. $ wine notepad > wine-notepad.log 2>&1
3. Kill the wine process.
4. $ winecfg > winecfg.log 2>&1
5. Kill the wine process.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
27560
 - Bundles: [e.g. `sudo swupd bundle-list`]
acpica-unix2
alsa-utils
bc
bootloader
c-basic
cloc
cloud-api
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
devpkg-base
devpkg-glib
devpkg-pcre
devpkg-util-linux
diffutils
docutils
dosfstools
editors
emacs
ethtool
file
findutils
firefox
fonts-basic
fuse
fwupdate
gdb
git
gzip
htop
icdiff
inotify-tools
iproute2
irssi
joe
kbd
kernel-install
kernel-native
kvm-host
less
libX11client
libva-utils
linux-dev
linux-tools
llvm
mail-utils
make
mutt
nasm
network-basic
nfs-utils
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
powertop
python-extras
python2-basic
python3-basic
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
thunderbird
tmux
tzdata
unzip
user-basic
valgrind
vim
weechat
which
wine
wpa_supplicant
x11-server
x11-tools
xemacs
xfsprogs
xterm
xz
znc
zsh
zstd

**Additional context**
[winecfg.log](https://github.com/clearlinux/distribution/files/2824913/winecfg.log)
[wine-notepad.log](https://github.com/clearlinux/distribution/files/2824914/wine-notepad.log)

**Comment by ahkok** [comment]
Weird, I installed the wine bundle on saturday and was able to run `winecfg` without issues. It also installed mono/gecko automatically. Also, I was able to download, install, and run, IrfanView without problems.

Did you have a previous `.wine` folder, perhaps?

**Comment by ahkok** [comment]
Note that irregardless, we know the current version of wine is lacking a ton of features still, and many programs are known to not work (all GL apps are likely broken).

**Comment by Nirgendsdorf** [comment]
"Did you have a previous .wine folder, perhaps?"

I doubt it, since I have not tried to run a wine binary from any distribution. Perhaps I can remove the wine bundle, delete the .wine folder, and start over? I guess it wouldn't hurt anything to try it...

"Note that irregardless, we know the current version of wine is lacking a ton of features still, and many programs are known to not work (all GL apps are likely broken)."

The wine devels maintain a database of apps known to work under wine. I started with mp3tag, which is listed as both installable and able to run under wine. When that did not work, I decided to test with the two wine internals I listed above. I redirected the terminal output (both stdout and stderr) to files, which I posted above. Please let me know if there is any other diagnostic I can run to track this down?

**Comment by Nirgendsdorf** [comment]
I tried the following steps:
1. # swupd bundle-remove wine
2. /home/darkmoon # rm -rf .wine
3. # swupd update [ --> OS updated to 27600]
4. reboot system
5. # swupd bundle-add wine
6. $ wine winecfg > winecfg1.log 2>&1
[winecfg1.log](https://github.com/clearlinux/distribution/files/2830020/winecfg1.log)
7. $ rm -rf .wine
8. $ winecfg > winecfg2.log 2>&1
[winecfg2.log](https://github.com/clearlinux/distribution/files/2830041/winecfg2.log)
9. $ wine notepad > wine-notepad.log 2>&1
[wine-notepad1.log](https://github.com/clearlinux/distribution/files/2830053/wine-notepad1.log)

It seems that I get somewhat different results each time I try to run wine. On other occasions, wine complained that it could not find the ncurses library.

I am completely clueless regarding these results. Once again, I have to wonder if it is not something with my system hardware configuration. Or, as you say, it could be a missing bundle, or maybe some specific files. I hope these latest logs offer something.

**Comment by Nirgendsdorf** [comment]
Updated my Clear OS installation to 27700 (includes update to wine).

1. $ winecfg 2>&1 | tee winecfg.log
winecfg displays config dialog, completes successfully
[winecfg.log](https://github.com/clearlinux/distribution/files/2847542/winecfg.log)
2. $ wine Downloads/iview451_setup.exe 2>&1 | tee wine_Irfanview_setup.log
Irfanview installer immediately crashes on startup, needs to close
[wine_Irfanview_setup.log](https://github.com/clearlinux/distribution/files/2847545/wine_Irfanview_setup.log)
3. $ wine Downloads/mp3tagv293setup.exe 2>&1 | tee wine_mp3tag_setup.log
mp3tag installs successfully
[wine_mp3tag_setup.log](https://github.com/clearlinux/distribution/files/2847547/wine_mp3tag_setup.log)
4. $ wine mp3tag.exe 2>&1 | tee wine_mp3tag_run.log
mp3tag launches successfully, displays user interface, crashes
[wine_mp3tag_run.log](https://github.com/clearlinux/distribution/files/2847551/wine_mp3tag_run.log)

**Comment by Nirgendsdorf** [comment]
Clear OS 27790. The Irfanview 451 installer still crashes immediately on startup. Winecfg generates lots of errors, too.

[winecfg.log](https://github.com/clearlinux/distribution/files/2866066/winecfg.log)
[Irfanview_setup.log](https://github.com/clearlinux/distribution/files/2866068/Irfanview_setup.log)

**Comment by Nirgendsdorf** [comment]
Clear OS 27800.

1. Run winecfg.
[winecfg.log](https://github.com/clearlinux/distribution/files/2869454/winecfg.log)
2. Download iview452.zip, extract to .wine/drive_c/Program Files/Irfanview
3. i_view32.exe can be launched from wine 'explorer', gnome 'files', or the command line
4. Irfranview displays its UI, but...
5. Attempting to perform any operation causes it to crash.
[Irfanview.log](https://github.com/clearlinux/distribution/files/2869460/Irfanview.log)

It is noteworthy that the wine internals 'notepad' and 'explorer' do seem to be working to some extent.

**Comment by Nirgendsdorf** [comment]
Currently, there are two Windows apps I rely upon, for which I have not found adequate Linux replacements: mp3tag and Irfanview. Although a "program needs to close" notification pops up shortly after wine launches mp3tag, Mp3tag's file tagging features are available and usable.

Irfanview, OTOH, displays its UI, but immediately crashes on any attempt to open an image file or set preferences. In the wine application database, Irfanview is reported to work. I hope wine debugging is continuing.

[Irfanview.log](https://github.com/clearlinux/distribution/files/2882754/Irfanview.log)

**Comment by ahkok** [comment]
Unfortunately I can't reproduce that. Irfanview properly shows my images.

@Nirgendsdorf what graphics card does your system have?

**Comment by Nirgendsdorf** [comment]
I'm using the integrated graphs onboard the I9-9900K processor.

I may be missing a library, though. According to the wine database entry, Irfanview 4.x requires that mfc42.dll (Visual C runtime library) be available to it. Apparently it is not enough to copy that file from my old Windows XP box, it seems the installer package, http://download.microsoft.com/download/vc60pro/update/1/w9xnt4/en-us/vc6redistsetup_enu.exe, must be run. I have not been able to find that package anywhere. Did you have to install any Windows libraries for your version of Irfanview to run? Which version of Irfanview are you using?

The wine database entry for Irfanview 3.x has nothing about extra libraries required, but I cannot find a zip package version of Irfanview 3.x. I'm stymied at this end, too.

**Comment by ahkok** [comment]
We've since enabled `wine64` and from my own testing I can see everything still works as expected. Are you still having these issues?

**Comment by Nirgendsdorf** [comment]
I still cannot run Irfanview, either the 32-bit or 64-bit version. I can start the 32-bit interface, but attempting any operation causes Iview to crash immediately. Error messages below:

`darkmoon@Nirgendsdorf~/.wine/drive_c/Program Files/Irfanview $ wine i_view32.exe`
`Wine cannot find the ncurses library (libncurses.so.6).`
`wine: Unhandled page fault on read access to 0x00000000 at address (nil) (thread 0009),`
`starting debugger...`
`002b:fixme:dbghelp_dwarf:compute_location Only supporting one reg (ebp/22 -> -2)`
`002b:fixme:dbghelp_dwarf:compute_location Only supporting one reg (ebp/22 -> -2)`
`002b:fixme:dbghelp_dwarf:compute_location Only supporting one reg (ebp/22 -> -2)`
`darkmoon@Nirgendsdorf~/.wine/drive_c/Program Files/Irfanview $ wine iview453_x64/i_view64.exe`
`wine: Bad EXE format for C:\Program Files\Irfanview\iview453_x64\i_view64.exe.`
`darkmoon@Nirgendsdorf~/.wine/drive_c/Program Files/Irfanview $`

**Comment by ahkok** [comment]
> ||
> |darkmoon@Nirgendsdorf~/.wine/drive_c/Program Files/Irfanview $ wine 
> iview453_x64/i_view64.exe|


|you need to use `wine64` for 64bit apps. Note you may also have to 
create separate `~/.wine` folders for 32/64 bit apps and /or set 
`WINE_ARCH` and `WINE_PREFIX`|

**Comment by sunnyflunk** [comment]
The `wine` bundle will be missing several needed libraries as it uses `dlopen` to load many libraries. So core libraries like the 32bit ncurses lib aren't installed with the bundle as no binary dependency exists to pull it in https://github.com/wine-mirror/wine/blob/master/programs/wineconsole/curses.c#L134. Most people also install the `gaming` bundle which includes most/all of the libs `wine` tries to dlopen, but at some point will need to ensure that the `wine` bundle is self sufficient.

**Comment by Nirgendsdorf** [comment]
> The `wine` bundle will be missing several needed libraries as it uses `dlopen` to load many libraries. (...) Most people also install the `gaming` bundle which includes most/all of the libs `wine` tries to dlopen,

_Yes!_ That was the answer! I was wholly convinced my problem was down to missing libraries, but I had no idea which ones. Iview32 now works for at least basic functions, I will try the more advanced ones at a later time.

> but at some point will need to ensure that the `wine` bundle is self sufficient.

I hope that will be arranged in the not-too-distant future, as I have no interest in games, and the ones included in the bundle take up needed space that I can better use elsewhere. Perhaps a `libraries` bundle can be created that both `wine` and `games` pull in?

Thanks for your help!

**Comment by Nirgendsdorf** [comment]
> |you need to use `wine64` for 64bit apps. Note you may also have to create separate `~/.wine` folders for 32/64 bit apps and /or set `WINE_ARCH` and `WINE_PREFIX`|

Thank you, that is useful to know. I thought I might try Iview64, but the apps I want to run or replace are all 32-bit, as the old Windows XP box I hope to eventually replace is a 32-bit machine. Iview32 is very fast, and meets all of my needs for an image viewer/editor. But I may have some questions later about directories and environment settings for wine. Thanks again...

**Comment by ahkok** [comment]
I continue to regularly use wine and see no issues with it. If there are specific apps that don't work, please open a separate issue. For instance, I was able to run the Unigine 4 benchmark on wine with the `d9vk` vulkan library we added last week.
