### ISSUE TITLE
vbox lga drivers fail to load

### ISSUE THREAD

**Issue by bwarden** [clearlinux/distribution#396]
**Describe the bug**
In 4.19.19-415.lts on a VBox guest, modprobe vboxsf fails due to lots of missing symbols.
[screenshot](https://imgur.com/a/2xn9ecV)

**Comment by puneetse** [comment]
Adding the word VirtualBox here for those searching.

**Comment by miguelinux** [comment]
We found the _issue_ and will be fixed **linux-lts-4.19.26-432** and **linux-lts2018-4.19.26-3**

**Comment by bwarden** [comment]
Fix is present in latest Clear Linux release.
