### ISSUE TITLE
clear linux not installed succesfully - build version (27530)

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#398]
**Describe the bug**
clear linux not installed succesfully - latest build (build version 27530)

===== 
panic: signal: aborted (core dumped)

Error Trace:
errors.Wrap()
 errors/errors.go:91
user.(*User).apply()
 user/user.go:195
 
goroutine 23 [running]:
github.com/clearlinux/clr-installer/tui.(*Tui).Run(0xc00006e480, 0xc00006e780, 0xc0000a6ce0, 0x16, 0x100, 0xc0000a6c40, 0x17, 0x0, 0x0, 0x0, ,...)
 /builddir/build/BUILD/clr-installer-1.1.4/.gopath/src/github.com/clearlinux/clr-installer/tui/tui.go:165 +0x6ee
main.main.func4(0xc0000a9320, 0xc00006e780, 0xc0000a6ce0, 0x16, 0xc00024db95, 0xc000091950, 0xc000192070)
 /builddir/build/BUILD/clr-installer-1.1.4/.gopath/src/github.com/clearlinux/clr-installer/main.go:243 +0x168
created by main.main
 /builddir/build/BUILD/clr-installer-1.1.4/.gopath/src/github.com/clearlinux/clr-installer/main.go:243 +0x93d
 

=====

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
build version 27530

INTEL NUC

**Comment by mdhorn** [comment]
There is a known issue when using an older image (27530 is older) when
adding a user.

A fix has been implemented and will be in the next release of the
clr-installer.

Two options:
A. If you need to use that specific version, disable Auto Update in the
Advanced options tab if you are adding a user during installation.
or
B. Download the latest release image: (currently 27650)
https://download.clearlinux.org/image/

--mark

**Comment by phmccarty** [comment]
@mdhorn - is this issue resolved now?

**Comment by mdhorn** [comment]
This was fixed by https://github.com/clearlinux/clr-installer/pull/210
And in clr-installer 1.1.5 first released in Clear Linux OS 27820

**Comment by ionutnechita** [comment]
I installed the last image and the problem no longer appears.
Clear Linux OS 28100

**Comment by mdhorn** [comment]
@ionutnechita thank you for the follow-up.
