### ISSUE TITLE
pacrunner leaks internal addresses in journal [security], also spews into telemetry

### ISSUE THREAD

**Issue by fenrus75** [clearlinux/distribution#40]
Apr 07 15:34:24 clr-arjan-skl pacrunner[539]: pacrunner[539]: done 0x1482b30
Apr 07 15:34:24 clr-arjan-skl pacrunner[539]: done 0x1482b30
Apr 07 15:34:24 clr-arjan-skl pacrunner[539]: pacrunner[539]: done 0x14923d0
Apr 07 15:34:24 clr-arjan-skl pacrunner[539]: done 0x14923d0

**Comment by ahkok** [comment]
pacrunner-0.13-40 will fix this by omitting the message.
