### ISSUE TITLE
Docker missing docker-init and version mismatch

### ISSUE THREAD

**Issue by mjaustin2** [clearlinux/distribution#401]
**Describe the bug**
Docker Bundle seems to be missing some files. Docker usually includes a file named _docker-init_ to handle init-like features inside containers. _docker-init_ is not found by swupd search, nor is it in any of the Docker bundles. Without docker-init, containers that run using the --init option refuse to start, exiting with the error:

> docker: Error response from daemon: exec: "docker-init": executable file not found in $PATH.

Additionally, _docker info_ reports that _docker-init_ is configured as if it exists. It also returns some odd messages indicating that the bundle versions may not match.

root@pi.hole ~ # docker info
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 18.06.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc

**Init Binary: docker-init**
**containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88 (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)**
**runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)**

init version: N/A (expected: )
Kernel Version: 4.20.6-691.native
Operating System: Clear Linux OS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.85GiB
Name: pi.hole
ID: UZ2R:RH3B:O26I:W4KK:67CS:3FZS:O4KH:EHY3:DACV:Y43Y:BYVH:GLLX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**To Reproduce**
1. docker pull jacobalberty/unifi:stable)
2. docker run  -d --net=host --init --restart=unless-stopped -e RUNAS_UID0=false -e UNIFI_UID=998 -e UNIFI_GID=998 -e TZ='America/New_York' -v ~unifi:/unifi --name unifi jacobalberty/unifi:stable

**Expected behavior**
Expected docker container to start without error. 

**Environment (please complete the following information):**
 - Clear Linux OS version: 27660
 - Bundles:
acpica-unix2
bc
binutils
bison
bootloader
c-basic
cloc
containers-basic
cpio
curl
dev-utils
diffutils
docutils
dosfstools
editors
emacs
ethtool
file
findutils
flex
gdb
git
gzip
htop
icdiff
inotify-tools
iproute2
irssi
java-runtime
joe
kbd
kernel-install
kernel-native
kvm-host
less
libX11client
linux-tools
llvm
mail-utils
make
mutt
nasm
network-basic
nfs-utils
nmap
nodejs-basic
openssh-server
openssl
os-cloudguest-vmware
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
powertop
python2-basic
python3-basic
shells
smartmontools
storage-utils
strace
sudo
sysadmin-basic
tmux
tzdata
unzip
user-basic
valgrind
vim
weechat
which
wpa_supplicant
xfsprogs
xz
znc
zsh
zstd

**Additional context**
[Docker documentation on docker-init](https://docs.docker.com/engine/reference/run/#specify-an-init-process)

**Comment by mjaustin2** [comment]
Any ETA on this? I'm having to restart my docker containers periodically due to zombies. Without docker-init, container processes can't get SIGTERM signals, so they never die.

**Comment by anselmolsm** [comment]
Changes in progress.

**Comment by mjaustin2** [comment]
Is the the new tini 0.18 package going to be added to containers-basic bundle?

**Comment by mjaustin2** [comment]
I can see the tini RPM in the [package repo](https://download.clearlinux.org/current/x86_64/os/Packages/) so it seems like we're achingly close to seeing this issue fixed. Unfortunately, it's not clear how Clear's bundle maintenance process works, so there's no way to track status. From the outside it looks like this is stalled, which is unfortunate since it limits Docker's usefulness on Clear Linux.

Is there something that needs to be done? Some testing or other such task that I can assist with to get this issue to resolution?

**Comment by phmccarty** [comment]
@mjaustin2 I just sent a clr-bundles patch for review: https://lists.clearlinux.org/pipermail/dev/2019-June/003064.html

**Comment by AntonioMeireles** [comment]
wait - 🤔 shouldn't `tini` be *inside* the stock CL docker base images instead ? why do we want to ship it on to docker host (which is what will consume `containers-basic`) ?

**Comment by phmccarty** [comment]
The clr-bundles change landed in release 30010, so `containers-basic` installs `tini` now.
