### ISSUE TITLE
Adding custom CA certs via clrtrust does not work with Firefox after rebooting

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#405]
**Describe the bug**
When a user trusts a new CA cert, Firefox does not honor the trust across system reboots, even though other utilities such as curl do.

**To Reproduce**
1. Trust a CA cert not shipped by default
2. Delete $HOME/firefox
3. Start Firefox
4. Browse to website with a cert signed by trusted CA cert, note that it works
5. Reboot
6. Browse to same website and not that it does not work
7. Delete $HOME/firefox
8. Start Firefox
9. Browse to website with a cert signed by trusted CA cert, note that it works

**Expected behavior**
When a user trusts a new CA cert, Firefox should be able to trust it after reboots of the system.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS version: 27660
 - Bundles: desktop-autostart

**Additional context**
N/A

**Comment by jairglez** [comment]
The issue is not reproducible on Clear Linux version 28420.
