### ISSUE TITLE
mount.cifs is installed, but not its man pages ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#409]
**Describe the bug**
When the mount.cifs command is installed and functional, it seems like its related man pages are not, although the command suggest we can read them.

**To Reproduce**
>$ sudo mount.cifs --help
>...
>Options are described in more detail in the manual page
>        man 8 mount.cifs
>...
>$ man 8 mount.cifs
>No manual entry for mount.cifs in section 8

**Expected behavior**
On Ubuntu 18.10 we have :
>$ sudo mount.cifs --help
>...
>Options are described in more detail in the manual page
>        man 8 mount.cifs
>...
>$ man 8 mount.cifs
>(manual page showing up here)

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
$ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27670
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles: [e.g. `sudo swupd bundle-list`]
$ sudo swupd bundle-list
acpica-unix2
alsa-utils
ansible
binutils
bison
bootloader
c-basic
cloud-api
cloud-control
clr-installer
containers-basic
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
dosfstools
doxygen
editors
emacs
ethtool
file
findutils
firefox
flex
fonts-basic
fuse
fwupdate
gdb
git
go-basic
gzip
htop
ipmitool
iproute2
irssi
java-basic
joe
kbd
kernel-install
kernel-native
kvm-host
less
libX11client
libva-utils
llvm
locales
make
nasm
network-basic
nfs-utils
nginx
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
powertop
pxe-server
python2-basic
python3-basic
smartmontools
storage-utils
strace
sudo
sysadmin-basic
sysadmin-hostmgmt
telemetrics
thermal_daemon
tmux
tzdata
unzip
valgrind
vim
weechat
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xterm
xz
zip
znc
zstd

**Additional context**
N/A

**Comment by fenrus75** [comment]
fixing now; should hopefully make the afternoon release

**Comment by nsauzede** [comment]
thanks, will test when available.. (currently running 27700)

**Comment by phmccarty** [comment]
@nsauzede - The man pages are available in release 27710. Can you check again after updating?

**Comment by nsauzede** [comment]
This bug was fixed when I swupd update'd to version 27760, thanks !
