### ISSUE TITLE
Settings->Default Applications: Web not initialized

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#410]
**Describe the bug**

Running CLR desktop I see that Settings->Default Applications: Web is blank (not initialized).
The drop-down list box is empty, so I cannot chose anything (although Firefox is installed)

**To Reproduce**
View Settings->Default Applications

**Expected behavior**
List of all installed Web browsers should be available to the user to chose from

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27690
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
R-basic
acl
acpica-unix2
alsa-utils
atom
bc
big-data-basic
binutils
bison
bootloader
c-basic
cabextract
ccache
cloc
containers-basic
cpio
cryptography
curl
darktable
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-dev
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
dev-utils-gui
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-base
devpkg-cairo
devpkg-cheese
devpkg-clutter
devpkg-clutter-gst
devpkg-cogl
devpkg-curl
devpkg-dbus
devpkg-elfutils
devpkg-evolution
devpkg-evolution-data-server
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-gdk-pixbuf
devpkg-glib
devpkg-gnome-desktop
devpkg-graphite
devpkg-gsettings-desktop-schemas
devpkg-gst-plugins-base
devpkg-gstreamer
devpkg-gtk
devpkg-gtk3
devpkg-harfbuzz
devpkg-icu4c
devpkg-json-glib
devpkg-libX11
devpkg-libXau
devpkg-libXdamage
devpkg-libXdmcp
devpkg-libXext
devpkg-libXfixes
devpkg-libXxf86vm
devpkg-libdrm
devpkg-libepoxy
devpkg-libical
devpkg-libinput
devpkg-libpciaccess
devpkg-libpng
devpkg-libpthread-stubs
devpkg-libsecret
devpkg-libsoup
devpkg-libva
devpkg-libxcb
devpkg-libxkbcommon
devpkg-libxml2
devpkg-libxslt
devpkg-mesa
devpkg-ncurses
devpkg-nspr
devpkg-nss
devpkg-opencv
devpkg-openmpi
devpkg-openssl
devpkg-orc
devpkg-pango
devpkg-pcre
devpkg-pixman
devpkg-qtbase
devpkg-qtdeclarative
devpkg-sqlite-autoconf
devpkg-systemd
devpkg-util-linux
devpkg-wayland
devpkg-wayland-protocols
devpkg-webkitgtk
devpkg-xcb-proto
devpkg-xorg-server
devpkg-xorgproto
devpkg-xz
devpkg-zlib
diffoscope
diffutils
docbook-utils
docutils
dosfstools
doxygen
editors
editors-dev
emacs
ethtool
file
findutils
firefox
flex
fonts-basic
fonttools
fuse
fwupdate
gdb
git
global
go-basic
go-basic-dev
gpgme
gzip
htop
httpd
icdiff
inkscape
inotify-tools
intltool
iproute2
irssi
java-basic
joe
jq
kbd
kernel-install
kernel-native
keychain
koji
kvm-host
kvm-host-dev
less
libX11client
libarchive
libva-utils
libxml2
libxslt
linux-dev
linux-tools
llvm
mail-utils
mail-utils-dev
make
meld
mixer
mkosi
mutt
nasm
network-basic
network-basic-dev
nfs-utils
nginx
openssh-server
openssl
os-clr-on-clr
os-clr-on-clr-dev
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
os-installer
os-testsuite
os-utils-gui
os-utils-gui-dev
p11-kit
package-builder
package-utils
parallel
patch
perl-basic
perl-basic-dev
plzip
pmdk
postgresql
powertop
python2-basic
python3-basic
qt-basic
scons
smartmontools
stellarium
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
tcl-basic
telemetrics
texinfo
texlive
thermal_daemon
thunderbird
tmux
tzdata
unbundle
unzip
valgrind
vim
vnc-server
web-server-basic
weechat
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop
xfsprogs
xz
yasm
zip
znc
zstd

**Additional context**
There are apps that pop-up messages "Failed to execute default Web Browser"
when trying to reach to the web. I believe this is the consequence of the described problem.

**Comment by mrkz** [comment]
This should be fixed with https://github.com/clearlinux-pkgs/clr-desktop-defaults/commit/56bffb9cdb747e91aa45b7e13603a67a7e77171b

Available in release **30440** (or later)

Thanks for the report :tada:
