### ISSUE TITLE
zeal (zealdocs/zeal) needed

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#415]
[zeal](https://github.com/zealdocs/zeal) is a very useful documentation browser. Although it's available on flatpak, but it cannot be installed on Clear Linux as it will tell you it's not supported.

Building it manually is also not easy to do, as it needs deprecated components only available in <= Qt 5.5. And I still failed the `make` process.

It would be greatly helpful if anyone is willing to include zeal in a bundle.

Thanks

**Comment by thiagomacieira** [comment]
If it depends on deprecated components (I'm guessing QtWebKit), then we won't add it.

Zeal developers need to move to non-deprecated components.
