### ISSUE TITLE
Conky bundle

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/distribution#417]
Any possibility of getting a build for conky? Very nice as a desktop based resource monitor to show how efficient this OS is 😀

**Comment by mrkz** [comment]
Hello, 

Conky is available since release **27990**, change introducing the bundle is on the commit https://github.com/clearlinux/clr-bundles/commit/11298151e70ac8ea78ec9e04758fa8cb468d189b.

You can install conky by running:
```
$ sudo swupd bundle-add conky
```

I'm closing this issue now.
