### ISSUE TITLE
gnome-shell flooding journal on each alt-tab

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#42]
Each time the user alt-tab's between windows on a Clear instance running the default gnome desktop, the following dump is made into the journal:
gnome-shell[838]: Object Shell.GenericContainer (0x3f19f40), has been already finalized. Impossible to get any property from it.
org.gnome.Shell.desktop[838]: == Stack trace for context 0x24e0330 ==
org.gnome.Shell.desktop[838]: #0      0x288da00 i   resource:///org/gnome/shell/ui/tweener.js:73 (0x7f29f40c7cd0 @ 9)
org.gnome.Shell.desktop[838]: #1      0x288d980 i   resource:///org/gnome/shell/ui/tweener.js:105 (0x7f29f40c7f78 @ 36)
org.gnome.Shell.desktop[838]: #2      0x288d8f8 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7f29f40c7de0 @ 52)
org.gnome.Shell.desktop[838]: #3      0x288d858 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7f29f40d2918 @ 54)
org.gnome.Shell.desktop[838]: #4      0x288d738 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7f29f40d29a0 @ 1626)
org.gnome.Shell.desktop[838]: #5      0x288d6a8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7f29f40d2a28 @ 100)
org.gnome.Shell.desktop[838]: #6      0x288d630 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7f29f40d2ab0 @ 10)
org.gnome.Shell.desktop[838]: #7 0x7ffc8574bb40 b   resource:///org/gnome/gjs/modules/signals.js:126 (0x7f29f40cff78 @ 386)
org.gnome.Shell.desktop[838]: #8      0x288d5a0 i   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f29f40cf5e8 @ 159)
org.gnome.Shell.desktop[838]: #9 0x7ffc8574c780 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f29f40b4de0 @ 71)
org.gnome.Shell.desktop[838]: #10      0x288d520 i   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f29f40cf560 @ 15)
org.gnome.Shell.desktop[838]: == Stack trace for context 0x24e0330 ==
org.gnome.Shell.desktop[838]: #0      0x288da00 i   resource:///org/gnome/shell/ui/tweener.js:80 (0x7f29f40c7cd0 @ 82)
org.gnome.Shell.desktop[838]: #1      0x288d980 i   resource:///org/gnome/shell/ui/tweener.js:105 (0x7f29f40c7f78 @ 36)
org.gnome.Shell.desktop[838]: #2      0x288d8f8 i   resource:///org/gnome/shell/ui/tweener.js:92 (0x7f29f40c7de0 @ 52)
org.gnome.Shell.desktop[838]: #3      0x288d858 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:203 (0x7f29f40d2918 @ 54)
org.gnome.Shell.desktop[838]: #4      0x288d738 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:332 (0x7f29f40d29a0 @ 1626)
org.gnome.Shell.desktop[838]: #5      0x288d6a8 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:345 (0x7f29f40d2a28 @ 100)
org.gnome.Shell.desktop[838]: #6      0x288d630 i   resource:///org/gnome/gjs/modules/tweener/tweener.js:360 (0x7f29f40d2ab0 @ 10)
org.gnome.Shell.desktop[838]: #7 0x7ffc8574bb40 b   resource:///org/gnome/gjs/modules/signals.js:126 (0x7f29f40cff78 @ 386)
org.gnome.Shell.desktop[838]: #8      0x288d5a0 i   resource:///org/gnome/shell/ui/tweener.js:207 (0x7f29f40cf5e8 @ 159)
gnome-shell[838]: Object Shell.GenericContainer (0x3f19f40), has been already finalized. Impossible to set any property to it.
org.gnome.Shell.desktop[838]: #9 0x7ffc8574c780 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f29f40b4de0 @ 71)
org.gnome.Shell.desktop[838]: #10      0x288d520 i   resource:///org/gnome/shell/ui/tweener.js:182 (0x7f29f40cf560 @ 15)

Every thing appears to be functioning correctly, and is just an annoyance when trying to mine the log for actually useful info.

**Comment by rustylynch** [comment]
Note that this issue has been around for a while.  It just finally bugged me enough to report it.

A quick search yields potential culprits from upstream gnome shell that has yet to be closed:
https://gitlab.gnome.org/GNOME/gnome-shell/issues/1

**Comment by joselamego** [comment]
We have applied Marco Trevisan's patch [1] which avoids the noise at the logs. This patch should be reverted once the change is applied upstream and it soon will be available in a Clear Linux release.

[1] https://gitlab.gnome.org/3v1n0/gnome-shell/commit/e568b79874789a74f9c67c0d6e3f223a7e1e87e3

**Comment by joselamego** [comment]
This change is applied in release 21940
