### ISSUE TITLE
Possible issue with dbus at startup

### ISSUE THREAD

**Issue by harsh-telepathy** [clearlinux/distribution#420]
The symptoms were, when I restart the system, a simple ping to www.google.com used to take an inordinately long time to complete. Ran an strace on it and discovered it seemed to stall on the dbus device socket. If I wait (about 30 seconds) on the ping it seems to resolve itself. But if I just do a systemctl restart dbus, the ping is immediately responsive. I suspect the dbus socket isn't initialized correctly on startup and its likely tied to initialization order in systemd.

This was over a Wifi connection.

**Comment by tpleavitt** [comment]
We have since updated systemd.  Please recheck and if this is still an issue, reopen
