### ISSUE TITLE
After enabling crio.service the /etc/crio/crio.conf file created is missing the manage_network_ns_lifecycle parameter

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#424]
If I follow the guide at https://clearlinux.org/documentation/clear-linux/tutorials/kubernetes and attempt to use CRI-O with Kata runtime a /etc/crio/crio.conf file is created the first time the crio.service is started through systemctl.  That file is missing the manage_network_ns_lifecycle = true parameter under the [crio.runtime] section. 

When you apply the flannel networking yaml file no Kata containers get an eth interface and networking does not work unless this parameter is set.

**Comment by nesiusra** [comment]
A lot of work has been done with kata integration since this was filed.  @eadamsintel  - is this still a problem?

**Comment by mythi** [comment]
kata-runtime adds the config on a fresh install.

**Comment by tpleavitt** [comment]
Reopen if this is still a problem
