### ISSUE TITLE
add xscreensaver-demo to os-utils-gui

### ISSUE THREAD

**Issue by comptekki** [clearlinux/distribution#427]
There is /usr/share/man/man1/xscreensaver-demo.1 on the system after os-utils-gui bundle is installed, but no /usr/bin/xscreensaver-demo.  Could that be added, please.  Thanks.

**Comment by nesiusra** [comment]
@bryteise - or gtk lives in its own bundle?

**Comment by bryteise** [comment]
@bryteise Actually these days we just build it against gtk so this is now resolved.
