### ISSUE TITLE
Add QT webenginewidgets-dev and webengine-dev to qt-basic-dev bundle

### ISSUE THREAD

**Issue by chrbayer** [clearlinux/distribution#428]
Hi,

to be able to compile software depending on QTs webengine and webenginewidgets libraries, it would be necessary to add these packages to a bundle, e.g. to the qt-basic-dev bundle.

The runtime libraries are already build and bundled, so it should be quite easy to add the development parts of the libraries, too.

Thank you very mich in advance!

Best regards,
Christoph

**Comment by thiagomacieira** [comment]
We should add them to devpkg.

**Comment by thiagomacieira** [comment]
Install `devpkg-QtWebEngine` bundle.

**Comment by puneetse** [comment]
I'm closing this issue as the dev packages have since been bundled in `devpkg-QtWebEngine` per @thiagomacieira's comment
