### ISSUE TITLE
Latex Support

### ISSUE THREAD

**Issue by m-mora** [clearlinux/distribution#434]
Any plan to add Latex documentation bundle, that can include TexLive and a editor like TexMaker?

**Comment by nesiusra** [comment]
@hnanni , @AthenasJimenez  - you've been working on TexLive recently I think?  Have we fixed this?

**Comment by cmarcelo** [comment]
Likely related to #341.

**Comment by nsauzede** [comment]
Is it possible to add the 'pdflatex' tool to the currently existing 'texlive' bundle ?
It would allow generating PDF documentation with 'doxygen'
Thanks

**Comment by nsauzede** [comment]
Is it possible to add 'pdflatex' tool to the existing 'texlive' bundle ?
It would allow to generate PDF documentation with the existing 'doxygen' bundle.
As I understand it, the current 'texlive' bundle only provides the 'pdftex' tool, which is not sufficient/relevant for 'doxygen' to use.
Thanks

**Comment by hnanni** [comment]
@ahkok May you please check the exceptions (public domain et.al.) that tagged the texlive package?
The tag was set on the disposition of 28220

**Comment by thiagomacieira** [comment]
The man page for pdflatex is in the texlive package, but there's no binary called "pdflatex". Where should it be coming from?

**Comment by hnanni** [comment]
it is built as part of the texmf utils, sort of texlive-extras. I our parlance, it is built during install_append

**Comment by thiagomacieira** [comment]
Or, as it happens, it's not being built.

**Comment by lebensterben** [comment]
> Or, as it happens, it's not being built.

Hi Thiago, I installed TeX Live following their official instruction [here](https://www.tug.org/texlive/quickinstall.html), which installed the binary `pdflatex`.

**Comment by nsauzede** [comment]
Hello; any chance of getting this pdflatex tool in texlive bundle ?

**Comment by hnanni** [comment]
it is now included in the 28720 release. Please try it and let me know your mileage

**Comment by nsauzede** [comment]
@hnanni I confirm it's available and working in CLR 28720
this is awesome, thank you very much !!
