### ISSUE TITLE
How i can get GL/gl.h and GL/glew.h

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/distribution#436]
I couldn't fınd a way to get opengl and glew development header fıles with bundles,How i can get them?

**Comment by fenrus75** [comment]
devpkg-mesa is not cutting it?

**Comment by nesiusra** [comment]
This is an older ticket that was over in our clr-bundles repo.  Going to close this as either issue is it is stale and likely solved or not relevant.  @tuxutku  - please reopen if necessary. 

@bryteise  - have we disabled issues over on the clr-bundles repo?  Should we add guidance on where to add issues in the readme for that repo?

**Comment by bryteise** [comment]
@nesiusra There are reasonable reasons to post issues to clr-bundles so I'm not inclined to close it off from having issues against it. I'm not sure exactly how I want to point folks to make issues against this repo but a number of them were opened due to this repo not existing at the time.

**Comment by tuxutku** [comment]
I had to build opengl at the time and i don't use clearlinux anymore
