### ISSUE TITLE
Add Apache Cassandra

### ISSUE THREAD

**Issue by ErikOShaughnessy** [clearlinux/distribution#437]
Could Apache Cassandra be added to a bundle please? I searched the repo and couldn't find it mentioned anywhere. I think big-data-basic might be a good fit for it, but obviously I'll be happy to have included where it makes sense.

Thanks!

**Comment by nesiusra** [comment]
@AthenasJimenez  - have you scoped Cassandra in the past?

**Comment by nesiusra** [comment]
@ErikOShaughnessy - thanks for the enhancement request.  We'll discuss internally. Sorry for the slow response - it looks like this was over in our bundles repository. This repo is where we are tracking bugs and enhancement requests.

**Comment by JnyJny** [comment]
It's no longer a concern for me personally.

**Comment by AthenasJimenez** [comment]
I'll put it on my TODO list, but I don't have it in my scope right now
