### ISSUE TITLE
Consider adding bundle "BOINC"

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#439]
The Berkeley Open Infrastructure for Network Computing (BOINC) is an open-
source software platform which supports distributed computing, primarily in
the form of "volunteer" computing and "desktop Grid" computing.  It is well
suited for problems which are often described as "trivially parallel".  BOINC
is the underlying software used by projects such as SETI@home, Einstein@Home,
ClimatePrediciton.net, the World Community Grid, and many other distributed
computing projects.

(It is open source GPL/LGPL)

**Describe alternatives you've considered**
I have managed to build and run boinc package from sources on CLR. 
(https://github.com/BOINC/boinc.git)

(It is worth mentioning it needs wxWidgets libraries, which I had to build on CLR as well. 
This should be probably a separate enhancement request. It is also an open source
project. These libraries are popular with apps that try to keep the same look/feel on
Windows and Linux).

**Additional context**
This is the top app, allowing loading and running many "client-apps"  which will allow your
computer to participate in one or more BOINC projects, using your spare
computer time to search for cures for diseases, model protein folding, study
global warming, discover sources of gravitational waves, and many other types
of scientific and mathematical research. 
It is possible to run the projects via CMD line only, or via a GUI app (boinc-manager), hence
both should be included.

(I tested this with SETI@home)

The BOINC package(s) are commonly distributed by other Linux vendors (Ubuntu, OpenSuse, Fedora)

**Comment by nesiusra** [comment]
@bwarden  - willing to take a swing at this? looks like it builds/runs on Clear already.

**Comment by bwarden** [comment]
I've added wxWindows successfully. Right now, I'm trying to debug the boinc build, specifically libboinc_zip.

**Comment by bwarden** [comment]
Looking at this fresh today, though, I see that I've been trying to build 1.0.4, which may not be ready. I'll try 1.0.3.

**Comment by bwarden** [comment]
Same problem with 1.0.3. Digging in.

**Comment by joeldupontddm** [comment]
I am trying to install boinc again on my clr too.

1 years+ 2 month i have done one CLR install but it very hard for me ...

I have install my CLR again today.

Hope BOINC can be on a bundle for helping science !

THX

**Comment by joeldupontddm** [comment]
Who i can install wxWidgets ?? i try but i cannot do this :s

**Comment by bwarden** [comment]
> 
> 
> Who i can install wxWidgets ?? i try but i cannot do this :s

wxWidgets is not packaged separately. I'm working on the packaging for boinc-client and wxWidgets now, and once they're in good shape, we'll add them to a bundle.

**Comment by bwarden** [comment]
I'm tying up a few loose ends on the implementation, but hoping to have a bundle available in a build this week.

**Comment by joeldupontddm** [comment]
Greats ! I hope that the performance of this implementation will be as good as clear linux, i believe in the developers of CLR like you =).

**Comment by bwarden** [comment]
Bundle boinc-client should be available within the next release or two of Clear Linux.

The structure of the BOINC project is to provide pre-compiled binaries for the client to execute. As a result, we're not completely in control of the performance, but it will be interesting to see.

**Comment by joeldupontddm** [comment]
Hi Clr Devs.

Some performance on my computer.

My computer (i5-8600K 6 cores  / 4Go RAM) 

One day of work with your bundle in CLR (V7.14.2 BOINC): 
Date : 05/03/2019 |   | Time on CPU 0:006:00:26:09  |   | Points : 52.614 |   | Unite send 94

Before i have an Ubuntu(V7.2.42 BOINC): 
Ubuntu : 27/02/2019 |   |  Time on CPU 0:006:00:35:13 |   | Points  63.721 |   | Unite send 99

And before and old CLR (1 year before) where i have install more recent BOINC (V7.14.2 BOINC).
24/11/2018 |   | Time on CPU 0:006:00:43:58 |   | Points  69.281 |   |  Unite send114

I dont understand why 😞  

BOINC Project provide source on github
https://boinc.berkeley.edu/wiki/Installing_BOINC#Building_from_Source

If someone can provide stats too, thx =), it only stats not facts.

**Comment by bwarden** [comment]
Unfortunately, as I mentioned, even though we build the BOINC client itself from source, with optimizations, this client merely downloads pre-compiled compute binaries directly from the projects you choose to participate in. We have no control over the performance of those.

**Comment by thejim** [comment]
fresh install of Clear Linux with all updates, installed BOINC, ran BOINC Manager and it says "Retrieving current status" for a couple minutes then gets the error "The BOINC clint has exited unexpectedly 3 times within the last 3 minutes.  Would you like to restart it again?"

**Comment by jurobystricky** [comment]
Did you do:

$ sudo usermod -a -G boinc ${USER}

https://community.clearlinux.org/t/boinc-client-not-connecting/1116/4

**Comment by thejim** [comment]
progress!  that got me to the choose project screen, but the screen doesn't show any projects.

**Comment by bwarden** [comment]
@thejim The original request here has been resolved and closed. Please do not add comments.

For bugs, please open a new issue (I moved your report to #1240). For discussion or help, please use our forum, either adding to [the thread pointed out by](https://community.clearlinux.org/t/boinc-client-not-connecting/1116/4) @jurobystricky, or by opening a new thread.
