### ISSUE TITLE
Dead links in documentation

### ISSUE THREAD

**Issue by sofar** [clearlinux/distribution#44]
In: https://clearlinux.org/features/telemetry
To: http://www.intel.com/content/www/us/en/privacy/intel-privacy.html

In: https://clearlinux.org/documentation/clear-linux/tutorials/telemetry-backend
To: https://clearlinux.org/documentation/clear-linux/tutorials/telemetry-backend#id1

**Comment by fenrus75** [comment]
we also clearly need a dead link checker

**Comment by pixelgeek** [comment]
Links appear to work for me...

**Comment by bwarden** [comment]
In both cases, the target link should be changed to
https://www.intel.com/content/www/us/en/privacy/intel-privacy-notice.html

**Comment by tpleavitt** [comment]
All changes have been merged

Features/telemetry
tutorials/telemetry-backend
guides/maint/telemetry-enable

should go live 4/17/18 pm
