### ISSUE TITLE
installer: wrong keyboard selection

### ISSUE THREAD

**Issue by FeliceMente** [clearlinux/distribution#440]
**Describe the bug**
If I select the italian keyboard during installation, this is ignored and the us kayboard layout is selected And the locale command actually returns the en_US locale).

**To Reproduce**
1. start the installation process
2. select the italian kayboard layout
3. go on with the installation process

**Expected behavior**
Italian kayboard layout after installation.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: 27460

**Additional context**
I was anyway able to manuall configure the correct keyboard layout with:
localectl set-keymap it

**Comment by mrkz** [comment]
@mdhorn likely a [clr-installer](https://github.com/clearlinux/clr-installer) issue

**Comment by mdhorn** [comment]
@FeliceMente What image did you use to install?

Just tried an interactive installation on 27430 and then again on the latest 27000, and selected the 'it' keyboard.
Booted the newly installed image and I see the keyboard is set:

```
root@clr-3d32038ebd2142f4a65718b428d0e9cb ~ # localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: it
      X11 Layout: n/a
```

The configuration used for the installation should be stored in the root's home directory on your new install. Can you check the value of keyboard?
```
grep keyboard /root/clr-installer.yaml
keyboard: it
```

If you are not the root user, you will have to prefix the command with 'sudo'.

**Comment by FeliceMente** [comment]
I used clear-27460-installer.iso.xz, with both the basic and the custom installation.

**Comment by mdhorn** [comment]
@FeliceMente Okay, I see the issue now. The ISO image was only recently converted over to using the new Clear Linux OS Installer. When I test the old installer (ister_gui.py) in that image, I can confirm it was not properly setting the keyboard in the target image.
But I've also confirmed that the new installer (clr-installer) will properly set the keyboard on the target image.

If you want to download the latest ISO image and confirm this for yourself, I'll leave this open for a day or two.
https://download.clearlinux.org/image/

**Comment by FeliceMente** [comment]
I can confirm it's correctly working.

Thanx.

**Comment by mdhorn** [comment]
@FeliceMente Thank you for verifying.

cheers.
