### ISSUE TITLE
systemd-coredumpd does not compress core dumps

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#443]
**Describe the bug**
systemd's coredumpd service in Clear is not compressing the core dumps. Core files are highly-compressible content, often showing over 100:1 compression rates even with LZ4. Other Linux distributions do compress them. I also created /etc/systemd/coredump.conf with `Compress=yes`, but core dumps are not compressed.

Core dumps are usually big and will fill up your filesystem (or will be rotated too quickly) unless compressed.

**To Reproduce**
1. Let any application crash (or kill it with ABRT or ILL or SEGV)
2. Look into /var/lib/systemd/coredump

**Expected behavior**
Files there should be compressed.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: 27700
 - Bundles: 
```acpica-unix2
bootloader
bootloader-extras
cryptography
curl
diffutils
dosfstools
duperemove
emacs
ethtool
file
findutils
firmware-update
fwupdate
gzip
htop
iproute2
irssi
kbd
kernel-install
kernel-native
less
libX11client
mkosi
network-basic
nfs-utils
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
perl-extras
pmdk
powertop
python3-basic
smartmontools
storage-utils
strace
sudo
sysadmin-basic
telemetrics
tmux
tzdata
unzip
weechat
which
wpa_supplicant
xfsprogs
xz
znc
zstd
```

**Comment by thiagomacieira** [comment]
I've just noticed this in the journal:

```
Feb 11 13:07:42 tjmaciei-desk systemd-coredump[285910]: Failed to compress (unnamed temporary file): Protocol not supported
```

**Comment by phmccarty** [comment]
I suspect this is a systemd packaging bug.

**Comment by thiagomacieira** [comment]
Yep, I'm guessing it's the fact we don't link systemd to liblz4 or liblzma. We can try and patch systemd to use external tools instead of in-memory compression, so runtime capabilities are possible. Not sure upstream will accept it, though.

**Comment by ahkok** [comment]
Fixed. We've enabled `LZ4` in the journal, and coredumps are compressed with this as well.

**Comment by anjali-v** [comment]
How to enable LZ4 or XZ to get build

**Comment by anjali-v** [comment]
> Fixed. We've enabled `LZ4` in the journal, and coredumps are compressed with this as well.

How to do this
