### ISSUE TITLE
after gnome setup wizard the desktop will not be shown

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/distribution#444]
**Describe the bug**
So, I have followed the setup wizard to start using the desktop on Clear Linux 27700 but after choosing all the options it gives me a screen that says:

You're ready to go! 
with a button: Start Using Clear Linux OS.

When I click this button the screen will go black. it seems like a shell but its just black. 

**To Reproduce**
Step 1: make a booting USB in linux with 27690
Step 2: Install NUC with defaults settings and AUTOMATIC installation instructions.
Step 3: Removed the USB and rebooted.
Step 4: Logged into the newly installed CLR with root and changed the password.
Step 5: I swupd updated the NUC to the newer version.
Step 6: added bundles:  “desktop-apps”, ““desktop-autostart”
Step 7: For some reason, don’t know why (usually I have uncoordinated and thoughtless actions),  I pushed the power off button. Causing the NUC to reboot.
Step 8: The NUC booted into graphics mode it showed me a wizard to start setting up my environment.
Step 9: It finally asked me for a user: I entered user:  test, and inputed the password.
Step 10: Towards the end it showed me a screen saying: You're ready to go!, with a button that read: Start Using Clear Linux OS
Step 11: I pressed it.

**Expected behavior**
The desktop to give me a graphical interface where I could input my user and pass, or simply the Desktop user interface to start working.

**Screenshots**
![img_20190211_173726364](https://user-images.githubusercontent.com/36279716/52602513-9c751880-2e28-11e9-81e4-abb22e62bf46.jpg)

Now the screen is just black, I can input commands but they dont work. This will be like so, until I reboot.  users should not have to do this to get the desktop running.

![img_20190211_173915670](https://user-images.githubusercontent.com/36279716/52602527-a139cc80-2e28-11e9-836c-68ab26b1f792.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]

NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27700
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
acpica-unix2
alsa-utils
bootloader
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
editors
emacs
ethtool
file
findutils
firefox
fonts-basic
fuse
fwupdate
gzip
htop
iproute2
irssi
joe
kbd
kernel-install
kernel-native
less
libX11client
libva-utils
network-basic
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
powertop
python3-basic
strace
sudo
sysadmin-basic
telemetrics
thermal_daemon
tmux
tzdata
unzip
vim
weechat
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Additional context**
To get the bundle-list and the CL version I had to switch tty's with the Alt+F1 entered as root. I greped the dmesg, it does not giveme any weird errors, the journalctl -xe does not eighter. 

I checked the systemctl status gdm to my understanding it says it is running a session for user test.

test@clr-6526eeae08254644a16e9a73d15b8d8a ~ $ systemctl status gdm
● gdm.service - GNOME Display Manager
   Loaded: loaded (/usr/lib/systemd/system/gdm.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-02-11 17:36:22 CST; 40min ago
 Main PID: 356 (gdm)
    Tasks: 3 (limit: 4439)
   Memory: 6.6M
   CGroup: /system.slice/gdm.service
           └─356 /usr/bin/gdm

Feb 11 17:36:22 clr-6526eeae08254644a16e9a73d15b8d8a systemd[1]: Starting GNOME Display Manager...
Feb 11 17:36:22 clr-6526eeae08254644a16e9a73d15b8d8a systemd[1]: Started GNOME Display Manager.
Feb 11 17:37:35 clr-6526eeae08254644a16e9a73d15b8d8a gdm-password][807]: pam_unix(gdm-password:session): session opened for user test by (uid=0)

**Comment by jairglez** [comment]
The issue is not reproducible after installing **Clear version 28390** on two different machines and completing the GNOME initial setup steps.

**Result:** After configuring an user, and finishing the initial setup, the user logged on automatically and the desktop screen was shown correctly.
