### ISSUE TITLE
mixer: Prompt when Docker is not running/user is not in docker group.

### ISSUE THREAD

**Issue by c-edw** [clearlinux/distribution#446]
**Is your feature request related to a problem? Please describe.**
I'm trying out the mixer tool, but had issues with `mixer build update` due to two reasons:
- The user is not automatically added to the `docker` group. I ran `sudo usermod -aG docker $USER`, logged out and then back in (to apply group changes) to fix this.
- The Docker daemon is not automatically started. I ran `systemctl start docker` to fix this.

These issues lead to the mixer tool spitting out the following:
```
clear@clr-5929a8464b294d10a245d030a6a6107d ~/mix $ mixer build update
Updating docker image
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2019/02/12 17:13:57 Warning: Unable to pull docker image for format 27. Trying with cached image
Running command in container: "mixer build update"
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Error: Failed to run command in container: failed to execute docker run --runtime=runc -i --network=host --rm --workdir /home/clear/mix --entrypoint mixer -v /home/clear/mix:/home/clear/mix clearlinux/mixer:27 build update --native: exit status 125
```

**Describe the solution you'd like**
I think the Docker daemon should be enabled (`systemctl enable docker`) and started (`systemctl start docker`) when installed with `swupd bundle-add`, or else any mixer commands which use Docker will fail. The user ideally would automatically be added to the `docker` group too, but that could pose risks, so the mixer tool should prompt for this.

**Describe alternatives you've considered**
An alternative would be for the mixer tool to detect if the Docker daemon is running, and whether the user is in the Docker group.

**Additional context**
N/A.

**Comment by bryteise** [comment]
I think the usage of docker in mixer is going away from my memory @rchiossi would know for sure here.

**Comment by rchiossi** [comment]
Hi @c-edw , thank you for your issue report.

As @bryteise said, we are cunrently working on removing the built in docket feature in mixer since it is not needed for automated format bumps anymore. The current plan is to provide a separate docker image for users that need docker for compatibility reasons. As it will be a normal docker image like any other, there is no need for mixer to be aware of it.

**Comment by c-edw** [comment]
I'm not quite clear on how you are using Docker - I assumed that containers were being used ephemerally to build packages/images. If it's being removed then feel free to close this :+1:

**Comment by nesiusra** [comment]
@rchiossi  - closing this - but if you have a feature open for this work then maybe add @c-edw to it?

**Comment by rchiossi** [comment]
We are tracking this change here: https://github.com/clearlinux/mixer-tools/issues/528
