### ISSUE TITLE
Bundle request: NIS client

### ISSUE THREAD

**Issue by dpotapov** [clearlinux/distribution#448]
**Is your feature request related to a problem? Please describe.**
The problem is to share the ClearLinux system across a group of people in NIS _(Network Information Service)_ environment.

**Describe the solution you'd like**
New bundle with NIS client tools available to be installed with `swupd`. The name of the bundle could be something like "nis-client" and it should provide at least _yp-tools_ and _ypbind_ packages.

**Describe alternatives you've considered**
No good alternatives are coming to my mind. Switching to LDAP is not an option for now. Installing missing NIS packages from another Linux distro may work, but it won't be stable.

**Comment by ahkok** [comment]
`NIS` is too far into unmaintained territory for us to pick up. We've considered in the past, and decided not to.

You can easily commpile NIS components yourself and should be able to make it functional locally, but we will not ship it.
