### ISSUE TITLE
Request: Add zram kernel module

### ISSUE THREAD

**Issue by kchan345** [clearlinux/distribution#45]
Hi,

zram in general can have quite a lot of useful applications. Usually it's used in machines with low memory, I use it personally as a ramdrive with compression for applications where disk IO is bottleneck such as on azure. 

For compilation use cases I can achieve ~0.5 compression ratio with LZO. This makes it possible to compile some projects with > 10GB total uncompressed size on ramdrive in a 8gb memory VM.

Really appreciate if you can consider adding zram support especially given that current kernel does not support loading kernel module.

**Comment by fenrus75** [comment]
yup good idea

just fixed the config, should be in tomorrows release

**Comment by fenrus75** [comment]
thanks for your request

**Comment by kchan345** [comment]
Hi Arjan,

I've been using zram with clearlinux about a day after it's in native
kernel - my intended usage is to use it on azure but I think it may be
useful in other kernel types as well.

Thanks for the quick turnaround!

**Comment by iphutch** [comment]
@miguelinux please see if this can be added to the Cloud kernels

**Comment by iphutch** [comment]
@bwarden

**Comment by bwarden** [comment]
Which kernels should we add it to? It's currently enabled in native, linux-hyperv, linux-oracle, and linux-pk414.

**Comment by ahkok** [comment]
kvm, aws, and hyper-v kernels could benefit from it.

**Comment by bwarden** [comment]
aws done; should be in the next release.

**Comment by bwarden** [comment]
kvm done; should be in the next release.

**Comment by bwarden** [comment]
linux-hyperv-lts is now done; should be in the next release. Any others, or is this done?
