### ISSUE TITLE
Can't play video using Gnome MPV Flatpak

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#451]
**Describe the bug**
Video fails to play using the Gnome MPV flatpak

**To Reproduce**
1. Install gnome mpv flatpak
2. Run gnome mpv
3. Select a media file to play

**Expected behavior**
Media file will play

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=27780
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

 - Bundles: [e.g. `sudo swupd bundle-list`]
```
acpica-unix2
alsa-utils
binutils
bison
boot-encrypted
bootloader
bootloader-extras
c-basic
cryptography
curl
darktable
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
ethtool
file
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
games
git
gzip
hardware-printing
htop
iproute2
irssi
kbd
kernel-install
kernel-native
less
libX11client
libstdcpp
libva-utils
llvm
locales
make
nasm
network-basic
nfs-utils
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
os-utils-gui
p11-kit
parallel
patch
perl-basic
powertop
pygobject
python-basic
python2-basic
python3-basic
strace
sudo
sysadmin-basic
thermal_daemon
thunderbird
tmux
tzdata
unzip
vim
weechat
which
wpa_supplicant
x11-server
xemacs
xfce4-desktop
xz
znc
zstd
```

**Additional context**
```
$ flatpak run io.github.GnomeMpv
flatpak run: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs
Gtk-Message: 18:52:13.696: Failed to load module "pk-gtk-module"
Gtk-Message: 18:52:13.698: Failed to load module "pk-gtk-module"
```

It looks like I might not be alone with this issue:
[https://github.com/flatpak/flatpak/issues/2240](https://github.com/flatpak/flatpak/issues/2240)

**Comment by ahkok** [comment]
I can't reproduce. And I use GnomeMPV flatpak a lot. The document portal message is strange, since we ship it and it's functional as far as I can see - I can open videos without issues, and they play (mkv, mp4 etc.). 

The `pk-gtk-module` lines suggest there is a polkit problem, that seems like a larger problem. Are there other polkit messages in `journalctl` ?

**Comment by pceiley** [comment]
Sorry I had to blow my install away as ran into a few other showstoppers as well. This one is easily reproducible though with a fresh install using the live desktop image so if I get a spare moment I'll fire up a VM and let you know.

**Comment by danboid** [comment]
I installed Clear yesterday and got the GNOMEMPV flatpak working fine except for playing files on a samba share. Playing files locally works fine for me.

**Comment by pceiley** [comment]
> I installed Clear yesterday and got the GNOMEMPV flatpak working fine except for playing files on a samba share. Playing files locally works fine for me.

I thought this might have been my issue at first, but I copied the file locally before opening and still got the same error.

**Comment by ikeyd** [comment]
> The `pk-gtk-module` lines suggest there is a polkit problem, that seems like a larger problem. Are there other polkit messages in `journalctl` ?

`pk-gtk-module` is for PackageKit and is non fatal. Can safely be ignored in this instance. You'll see the same on 32-bit games where only the 64-bit variant exists, etc.

**Comment by pceiley** [comment]
Thanks for the suggestions. I don't have this install anymore (and I need #530 fixed before I try it out on my desktop again).

There was almost certainly a broader issue at play here. Gnome was doing some pretty odd things and running some programs produced a number of dbus errors/warnings if I recall correctly. I installed Clear twice within about a month and experienced these issues both times.

For now, it might be best to close this issue until I get a chance to trial it again.

**Comment by pceiley** [comment]
So I just installed Clear on a different system and I'm experiencing the exact same issue! Anyone got any hints as to what I might be doing wrong? I haven't really changed the system at all from a fresh install...

**Comment by pceiley** [comment]
Looks to be an issue loading the fuse module.
```
$ lsmod |grep fuse
$
```
Loading the module manually via `$ modprobe fuse` resolves the issue (until the system is rebooted).
