### ISSUE TITLE
Enable `crypto_user` module and `CONFIG_MODULE_COMPRESS_XZ` in kernel

### ISSUE THREAD

**Issue by mmetak** [clearlinux/distribution#453]
Would that be possible?

**Comment by miguelinux** [comment]
Just enabled **crypto_user** as module, you will see in the next public build.

But @fenrus75 could tell regarding CONFIG_MODULE_COMPRESS_XZ

**Comment by mmetak** [comment]
@miguelinux Thank you for your quick reply and for already enabling `crypto_user`. Now just for @fenrus75  to chime in on compressed modules part. :)

**Comment by fenrus75** [comment]
we wouldn't compress our modules...
maybe can you explain in a sentence or two of what you want to do with this
?

**Comment by mmetak** [comment]
Mostly to reduce the install space. Of course, that's not super important, but compressed modules take 50% less of install space.

**Comment by thiagomacieira** [comment]
Indeed, but we made a choice in Clear not to compress the modules or the man/info pages (you may not have noticed, but take a look at /usr/share/man and /usr/share/info). The reason for that is the gain in storage is small compared to storage sizes, but the gain in delta compression when downloading updates is big enough.

```
as-is$ du -cs info man 
16076   info
125208  man
141284  total
xz -9 compressed$ du -cs info man                                    
3284    info
85012   man
88296   total
zstd -19 compressed$ du -cs info man                                         
3376    info
85120   man
88496   total
```

```
as-is$ du -s /usr/lib/modules/4.20.7-694.native 
128860  /usr/lib/modules/4.20.7-694.native
xz -9$ du -s 4.20.7-694.native
35552   4.20.7-694.native
zstd -19$ du -s 4.20.7-694.native                                          
38512   4.20.7-694.native
```

**Comment by mmetak** [comment]
@thiagomacieira Thank you for your explanation.
