### ISSUE TITLE
"kvm: already loaded the other module" 

### ISSUE THREAD

**Issue by siufung917** [clearlinux/distribution#455]
Describe the bug:
ClearLinux release 27800 installer image failed to install on a baremetal. I am using Lenovo thikpad x1. And I tried to install clearlinux with the existed windows 10.

To Reproduce

1. Download latest live image from official website 

2. Use Rufus to create an usb boot device.

3. In bios, use usb to boot.

4. Stuck in screen with 
"kvm: already loaded the other module" 

Expected behavior
The installation will complete and will prompt to reboot the OS.

**Comment by ahkok** [comment]
The KVM message is probably irrelevant, and therefore the title of this bug is incorrect. It should be something like "27800 installer image fails to boot"

**Comment by iphutch** [comment]
Yep ran into the same issue and error on a NUC.
clear-27880-live-desktop-beta.img.xz

**Comment by gtkramer** [comment]
@siufung917, we offer a number of images: live, installer, and live desktop.  Which image were you working with?

**Comment by siufung917** [comment]
I have tried all these image at version 27800, all the same result. After boot in usb ,  select clear Linux , stuck in the kvm message.
I wonder is that the problem with the existing windows 10 EFI or bios ?
But I can boot with arch Linux using usb.

**Comment by gtkramer** [comment]
@siufung917, same here. I'm able to boot to a console on all of the images mentioned above on a Linux-based system (Clear).  I'm trying graphically with live desktop beta on a USB.

**Comment by siufung917** [comment]
I cannot even load into the console. （Cry

**Comment by ahkok** [comment]
@siufung917 What model year is this Thinkpad X1?

**Comment by gtkramer** [comment]
I was able to boot the installer and live desktop images off a GPT-partitioned USB with both 27800 and 27880 on a Skylake NUC

**Comment by gtkramer** [comment]
I created a bootable USB using Rufus on Windows 10 for the live desktop image.  This also boots :(

**Comment by siufung917** [comment]
@ahkok I am using x1 carbon gen6 (2018) with i5-8250u. ^^

**Comment by siufung917** [comment]
Weird enough. When I use other USB drive to boot, it works!!!!
The previous usb can boot in with arch linux..... So I never thought about the usb problem.
(The previous usb is usb 2.0. The new one is usb 3.0.)
Thank you all guys ❤️ You guys are so helpful.
