### ISSUE TITLE
"sudo" bundle-add suggestion doesn't work if "sudo" doesn't exist 

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#457]
**Describe the bug**
This is an edge case.  

My system doesn't have "sudo" and when I tried to use "sudo", it suggests that I "sudo swupd bundle-add sudo".  

user@clr ~ $ sudo swupd bundle-add mixer
sudo: command not found
To install sudo use:  sudo swupd bundle-add sudo

**To Reproduce**
1. System doesn't have sudo bundle installed.   
2. $ sudo swupd bundle-add mixer

**Expected behavior**
Maybe suggest that have root user add "sudo" bundle to the system.

**Comment by danboid** [comment]
Weird. I installed Clear yesterday and sudo is present.

**Comment by dagbdagb** [comment]
saw the same issue today. VERSION_ID=27910

**Comment by ikeyd** [comment]
I have an interim patch in transit for this, effectively if the user is in wheel/wheelpw groups, with uid != 0, warn that we need sudo installed by the administrator.

**Comment by phmccarty** [comment]
Fix in progress. Here is the diff to the `cnf` package:

```diff
--- a/10-command-not-found.sh
+++ b/10-command-not-found.sh
@@ -2,7 +2,7 @@ command_not_found_handle () {
     echo "$1: command not found"
     if [ "`id -u`" == "0" ]; then
         MSG='$1 == cmd { print "To install " $1 " use:  swupd bundle-add " $2; exit }'
-    elif groups | grep -q -w -e wheel -e wheelnopw ; then
+    elif [ "$1" != "sudo" ] && groups | grep -q -w -e wheel -e wheelnopw ; then
         MSG='$1 == cmd { print "To install " $1 " use:  sudo swupd bundle-add " $2; exit }'
     else
         MSG='$1 == cmd { print "To install " $1 " your system administrator needs to do:  swupd bundle-add " $2; exit }'
```

**Comment by phmccarty** [comment]
Fixed in release 28760.
