### ISSUE TITLE
Enable CONFIG_HIBERNATION to support 'suspend to disk'

### ISSUE THREAD

**Issue by BruceZhang1993** [clearlinux/distribution#458]
**Is your feature request related to a problem? Please describe.**
Using clear linux kernel on Arch Linux. CONFIG_HIBERNATION is not enabled by default, so I cannot suspend to disk / hibernate.

**Describe the solution you'd like**
Would it be better to enable `CONFIG_HIBERNATION` by default ?

**Comment by ahkok** [comment]
We have left this disabled by default on purpose.

**Comment by BruceZhang1993** [comment]
@ahkok hug, thanks anyway. I'll try to enable and compile by myself.

**Comment by thiagomacieira** [comment]
Why is it not enabled in our kernels? The company I work for requires that we suspend to disk (not RAM) when a laptop is leaving a secure environment, like driving home from work.

**Comment by lf-araujo** [comment]
Hibernate is virtually impossible to set up, as most instructions online includes changes to GRUB in order to a successful restore. My aim has been to try to fix suspend at least, which is showing much [harder than expected](https://community.clearlinux.org/t/suspend-and-hibernate/645/5).

**Comment by thiagomacieira** [comment]
Suspend to RAM works. I do it almost every day.

We should enable the kernel config now. Systemd has it disabled, so the stack won't enable it (desktop).

**Comment by nobodyatandnothing** [comment]
i enabled it in systemd, and set `restore=UUID=<uuid of swap partition>` in `/etc/sysctl.d/hibernate.conf`, and when i do `systemctl hibernate` it turns off, but when i turn it back on i get the login screen.
i am using sway with no settings regarding hibernation, and i am using greetd login manager daemon with agreety greeter

**Comment by nobodyatandnothing** [comment]
what is the the status of this? why is it not supported yet?

**Comment by nobodyatandnothing** [comment]
https://community.clearlinux.org/t/hibernate-clearlinux/3632

**Comment by fenrus75** [comment]
config:CONFIG_HIBERNATION=y

so what's missing ?

**Comment by nobodyatandnothing** [comment]
is hibernate supposed to log you out?

**Comment by bryteise** [comment]
Probably configurable looking at [this](https://help.gnome.org/users/gnome-power-manager/stable/preferences-advanced.html.en_GB).
