### ISSUE TITLE
4 copies of Joes' Own Editor

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/distribution#46]
On a default install of Clear Linux, (version 21650 updated to version 21870) there appears to be 4 icons for Joe's Own Editor.  Would only expect one....

**Comment by rustylynch** [comment]
Note that there are also two "Screenshot" icons in the Gnome Shell

**Comment by rustylynch** [comment]
Ends up this is an issue with the text in the desktop icon getting truncated combined with the same icon used by three different "applications".

rusty@rustic /usr/share/applications $ grep -R "Own Editor" .
./jstar.desktop:Name=Joe's Own Editor - WordStar Emulation
./jpico.desktop:Name=Joe's Own Editor - NANO/PICO Emulation
./jmacs.desktop:Name=Joe's Own Editor - EMACS Emulation
./joe.desktop:Name=Joe's Own Editor
rusty@rustic /usr/share/applications $ grep '^Exec=' jstar.desktop jpico.desktop jmacs.desktop joe.desktop 
jstar.desktop:Exec=/usr/bin/jstar %F
jpico.desktop:Exec=/usr/bin/jpico %F
jmacs.desktop:Exec=/usr/bin/jmacs %F
joe.desktop:Exec=/usr/bin/joe %F

... so we are actually providing multiple joe based emulations, but at least on my screen resolution all of the shortcuts look identical.

**Comment by rustylynch** [comment]
Also.... similar thing going on with Screenshot.  We install both a gnome and an xfce based screenshot app, but use identical icons and label text

**Comment by cmarcelo** [comment]
Related upstream potential solution: https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/58

**Comment by fenrus75** [comment]
fixed the joe side of the issue

**Comment by ahkok** [comment]
Only the xfce4-desktop bundle installs the xfce4 screenshot utility, so I'm OK with the duplicated icon and name, having both desktops is not a usual configuration.
