### ISSUE TITLE
Add terminator xterm

### ISSUE THREAD

**Issue by danboid** [clearlinux/distribution#460]
terminator is my fave xterm app because it supports tabs and the grouping of tabs so that you can send commands to multiple tabs / SSH sessions. It would be great to see it bundled.
'
https://launchpad.net/terminator

**Comment by mrkz** [comment]
I just gave this a quick look and it won't be as easy to add (python2 based).

Apparently there are ongoing efforts to port it: https://bugs.launchpad.net/terminator/+bug/1662544

**Comment by ahkok** [comment]
Will not merge until py3 is complete. When it is, please re-open this issue. Otherwise, I'm assuming upstream is dead.

**Comment by takov** [comment]
No terminator is using python3.  :) It would be great if there is bundle for this 

Same as issue: https://github.com/clearlinux/distribution/issues/1724
