### ISSUE TITLE
First impressions of Clear Linux

### ISSUE THREAD

**Issue by danboid** [clearlinux/distribution#461]
As a Linux user of 23 years now I thought you might like to read my review / first impressions of Clear. I realise this may not be the best place for it so feel free to close or move it ASAP. Thanks!

I went to some quite extreme lengths yesterday to test Intels Clear Linux for the first time. Clear Linux has been around for a number of years but up until later last year it was only focusing on being used in the cloud. Last year Intel shifted focus a bit and started to try to make Clear usable on the desktop too. After having seen test after test on Phoronix where Clear soundly wipes the floor with every other distribution of Linux in several benchmarks, curiosity finally got the better of me and I had to find out if I was able to put up with the expected dearth of packages (compared to my faves Ubuntu and Arch) to gain a more finely tuned and performant system, by the guys who designed and produced the bulk of the computing hardware I'm using.

I say I underwent extreme lengths for a couple of reasons. First, Clear Linux only runs on UEFI machines and my laptop, up until yesterday, was only capable of BIOS booting. That's quite rare these days but it was still quite odd about 4/5 years ago when I got it. My laptop vendor, System76, had no updated firmware for my Gazelle Pro but I had read it was a rebranded Clevo laptop so I found out exactly which Clevo model it was based upon and then I flashed the latest firmware available for that onto my laptop. Having not been able to find any reports of anyone else having done this upgrade to my model of laptop I was taking a ~£1K risk that could've killed my laptop but thankfully it went without hitch and after doing so my BIOS gained the ability to enable/disable UEFI booting, as required by Clear. Yeah!

In order to upgrade my BIOS, I first had to create a USB DOS boot disk with at least 12 MB of free space for the firmware files and update apps/scripts. In the past I have either created such a disk with rufus under Windows or I used a customised FreeDOS image that includes extra space for files (unlike the official FreeDOS image) but yesterday I created a bootable FreeDOS USB drive using dosemu to mount the drive and make it bootable with the sys command as documented here https://wiki.gentoo.org/wiki/Bootable_DOS_USB_stick . That guide is for Gentoo but I followed it fine under Arch and it should work under any Linux where you have dosemu installed. That's the way I'll be creating DOS boot disks from now on. Two distinct wins already, but what about Clear?

The non-cloud version of Clear offers 3 different installers - Live Desktop, Installer and Live. I opted for Live Desktop on the grounds that it should let me see a desktop running before installing it to disk, which I always find reassuring. It's probably the exact same installer on all three? The installer is your first taste of a new OS and unfortunately first impressions of Clear via its installer were not good at all. In fact I'd go as far to say its the crappest OS installer I think I've ever seen. The interface is inconsistent and confusing and lacks several options that have been standard in Linux installers for decades. On top of that, it was also buggy and it took me about 10 attempts to learn the pitfalls and get it to install, which resulted in me opening two tickets on github against the installer alone:

https://github.com/clearlinux/clr-installer/issues/223

https://github.com/clearlinux/clr-installer/issues/224

Long story short, if you want to try Clear you currently have to deselect the desktop-autostart bundle (and remember to create a user/password) before you start installation. desktop-autostart, which is required for a graphical desktop, can be safely installed post install using:

sudo swupd bundle-add desktop-autostart

That brings us to the first odd aspect of Clear - bundles. Instead of breaking a distribution up into packages which generally map 1:1 with programs like in every other Linux distribution, Clear operates with bundles which in most cases consist of several apps. I really don't get their motivation or justification for doing this, it just seems horribly inefficient and you often end up having to install several programs when you only actually wanted one app that is part of that bundle. On top of that, there are very few apps in the Clear Linux repos compared to Debian/Ubuntu and Arch etc. Clear does support both flatpak and Appimage so I have been able to find most of my fave apps (KDEnlive, libreffice, filezilla...) in flathub or, as in the case of Chromium, as an Appimage. The Clear packaging tool, swupd, is very slow and lacking in features compared to pacman.

I would very much like to be able to use Clear as my main desktop OS because it is very fast. It boots quickly (not really notably faster than Arch or a minimal Debian installation) but the real difference is to be noted after boot as everything is just faster. Programs open faster, tabs switch faster, files copy faster (as I noted when copying some files from my phone via MTP) nothings ever lags or delays and everything is generally more responsive because its all optimised as far as possible. All of my hardware worked without any issues, wifi, HDMI, sound, suspend works fine and although I've not done any scientific tests it seems I get about double the battery life under Clear vs Arch or Ubuntu. These were the sorts of gains I was promised and it seems to bear out but there are a couple of showstoppers for me currently which mean I'll be returning to Arch/Ubuntu until Clear matures more as a desktop OS.

I can't switch to Clear yet basically due to poor multimedia support. Clear ships with Firefox by default but with no h264 support and this results in many YT videos and videos on other streaming sites not playing. I never in a million years imagined that Chromium wasn't going to be in the Clear repos but its not so to get working browser video playback I had to download an AppImage of Chromium. That fixed YT but Chromium suffered from dodgy font rendering, presumably because Clear didn't have the correct fonts installed. Another app I never expected to be missing from the Clear repos (and flathub) is ffmpeg. When Clear Linux gets ffmpeg, this could fix its Firefox video streaming problem and would also enable thumbnail previews of video files under XFCE/Thunar plus a whole lot more. If I have to rebuild my browser and/or my desktop to make it usable then that distro has failed me.

I'm really quite excited about the work that Intel are doing with Clear Linux to squeeze the best performance possible out of their hardware but its Clearly not ready for widespread use on the desktop yet.

**Comment by fenrus75** [comment]
thank you for your very detailed review. I'm going to print this out and
take this to our regular engineering planning meeting as a list of things
we need to fix.

I'll see what I can fix myself even before that, and I know some things are
hard (the codec issue is not technical)

**Comment by danboid** [comment]
Thanks Arjan!

I realise there are legal difficulties with including certain patented codecs in the Clear repo / installation images but there are several ways you could make such code easier to install for those who do want it without breaking any laws - for example see what Fedora have done to help making the NVIDIA driver and media software easier to install in recent releases.

**Comment by fenrus75** [comment]
on the bundle granularity; we had a technical change several months ago that allowed us to have >> 100 bundles, and since then we've steadily been increasing the number of bundles by splitting the "big" bundles up into smaller pieces. It's not a finished task but it's ongoing at least.

swupd performance personally bugs me, the architecture and design allow for it to be blazing fast, and in the last few years the implementation has lost its performance.... it used to be less than 1 second to update.

on content, we have a few folks adding more, but I realize we have some way to go.

we have a beta level functionality to allow 3rd party applications now, but it's still a bit limited.

on external 3rd part kernel modules, we recently added full support for dkms that should take care of this gap

**Comment by danboid** [comment]
Why was swupd created instead of using an existing set of packaging tools such as pacman? I don't doubt there is a better, existing set of packaging tools than pacman but I use that as an example because it it lightning fast, fully featured, open source and easy to create PKGBUILDs (new package build scripts) for so it ticks all my boxes. pacman, like apt and rpm etc, features meta packages for 'bundles' but maybe clears bundles have extra functionality I'm missing that necessitated a new packaging system?

**Comment by fenrus75** [comment]
the irony was mostly that swupd was created to significantly improve performance, efficiency and reliability.

reliability is still there.

performance irritates me to no end since the current state is pathetic.

**Comment by fenrus75** [comment]
https://blueprints.launchpad.net/lpc/+spec/lpc2012-boot-half-second-update  (original swupd presentation we did at plumbers conference)

**Comment by danboid** [comment]
Currently the user has no idea how big bundles are, how fast they are being downloaded or how far into being installed they are when using the live installer. You get a little more info when using swupd from the terminal but its still not very verbose by default. This makes the live install process vague and uncertain and those with slower connections are likely to lose patience and give up.

**Comment by fenrus75** [comment]
yes totally agreed.

**Comment by puneetse** [comment]
> The installer is your first taste of a new OS and unfortunately first impressions of Clear via its installer were not good at all. 

If you have specific ideas to improve the installer, perhaps add them to this issue: https://github.com/clearlinux/clr-installer/issues/218

**Comment by Bulmer** [comment]
The lack of visual feedback during installation is a real problem. I've been stuck at the "Downloading required packs" page for about 45 minutes at the moment with no movement in the bottom slider. Also I wasn't given a choice of bundles I wanted installed. Although I do have a fast internet connection (30mb/s) I am going to wait this out for an hour or so as the comments on here indicate that something "may" be going on in the background. Unfortunately the person installing has no idea whats going on!

**Comment by gvancuts** [comment]
> Although I do have a fast internet connection (30mb/s)

Your connection is unlikely to be the culprit. I have a fast connection at home (85Mbps (measured)) but I'm usually getting less than a couple of MB/s of download speed. You may see higher download speed but it depends if the CDN has cached it already for you (and that depends on where you are located and if someone in your vicinity has already downloaded that content).

> I am going to wait this out for an hour or so as the comments on here indicate that something "may" be going on in the background. Unfortunately the person installing has no idea whats going on!

It may take a little longer than that unfortunately so please be patient. I agree that visual feedback as to whether things are progressing would be very helpful.

**Comment by Bulmer** [comment]
Thanks @gvancuts . The hdds flickering occasionally, so thats something. Did I miss the bundle selection page or is it missing from the current installer?

**Comment by gvancuts** [comment]
> Thanks @gvancuts . The hdds flickering occasionally, so thats something. Did I miss the bundle selection page or is it missing from the current installer?

Not 100% about all versions of the installer but the GUI installer from the latest version (30040) has the option (under the "Advanced" tab)

**Comment by Bulmer** [comment]
Ok, 4 hours later and the packs seem to have been downloaded, because the installer gui closed. The only thing is its just dumped me onto the desktop with no notification whatsoever. I take it i'm supposed to reboot manually??

**Comment by gvancuts** [comment]
Yes. The installer GUI usually stays up but I _think_ in one instance when I let it run for many hours, it had disappeared when I got back to my desk.

Adding @mdhorn so he can see the feedback and provide further comments.

**Comment by Bulmer** [comment]
I decided to reboot and remove the live-cd and now thre is no boot device. I rebooted the laptop with the live-cd and used "disks" to see if the partitiions were created. They were there (1-boot, 2-swap and 3-root). Its as if there is no boot loader present?

**Comment by gvancuts** [comment]
Can you drop to an EFI shell and see of the `bootloaderx64.efi` is present under `EFI\org.clearlinux\` (typically on `fs0:`)?

**Comment by mdhorn** [comment]
@Bulmer What version of the Installer are you running?  The version string is visbile to the left on the graphical installer?  I'm curious becuase the progress update was fixed quite a while ago.

It might also be helpful to understand the response time from our CDN, if you could share the summart from
`ping -c 20 cdn.download.clearlinux.org.`

**Comment by Bulmer** [comment]
@mdhorn - the installer version is 2.0.6
20 packets transmitted, 20 received, 0% packet loss, time 19030ms
rtt min/avg/max/mdev = 42.726/105.583/236.740/61.994 ms
@gvancuts  - I couldn't bring up the efi shell using ctrl+alt+f2 or via the bios and am trying another installation this morning

**Comment by Bulmer** [comment]
ok, install went without a hitch this morning (about 20 minutes). I can see the stage where the first install failed as it didn't get to the "installing base os and configuring bundles".

**Comment by BenMorel** [comment]
I agree that the new package manager is a weird choice, especially the concept of bundles indeed. I do not understand either why individual packages are not bundled separately: if they require other packages to work, then these extra packages come as dependencies, and will be installed together with the requested package.

I currently see the bundle concept as just a way to install software I won't need. Maybe I missed something, in which case I'd be happy to hear what advantage this concept brings.

Currently, the 3rd party software support is pretty poor, we cannot reuse most of the software packaged for other "standard" OSes (Debian/Ubuntu, Fedora/RHEL/CentOS), and a lot of things are hard to install, or wobbly at best (see these [instructions](https://community.clearlinux.org/t/installing-google-chrome-on-clear-linux/1132) to install Chrome on Clear Linux, asking you to install with `rpm --nodeps`).

It's a pity really, I got really excited by Clear Linux when testing it on my bare metal laptop today, it's really faster than all other distros I could get my hands on, and made me hesitate to switch.

I think that once Clear Linux gets the software aspect right, it may become very usable as main desktop.

And nvidia/optimus support would be nice, too. Upcoming Fedora 31 will start shipping proprietary Nvidia drivers like Ubuntu already does; if Clear Linux could follow, that'd great.

**Comment by ahkok** [comment]
I'm going to close this issue due to the open nature of it - It's fine to have a discussion that elaborates but I feel we've closed on the original post issues in one way or another.

a quick recap of what is going on:
media -> in progress to improve. tracking in other bugs.
packaging -> in progress, we're making bundles mroe fine grained, this is slowly going to make things more predictable for users over the next weeks/months.
