### ISSUE TITLE
SDL dev bundle (version 1 and/or 2)

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#464]
**Is your feature request related to a problem? Please describe.**
It would be nice to get a minimal SDL (version 1 and/or 2) development bundle, to let people develop code for SDL.
Currently, if we do :
`sudo swupd search bin/sdl2-config`
It suggests to add bundle "games" (418Mb) which is quite storage-consequent, and a bit "specialized"

**Describe the solution you'd like**
Maybe some lightweight "swupd bundle-add sdl-dev" could do the trick.

**Describe alternatives you've considered**
Alternative could be to
1) add "games" bundle (heavyweight and possibly not so relevant)
2) download, build and install SDL (1/2) manually..

**Additional context**
N/A

**Comment by ahkok** [comment]
due to our package management, `/usr/bin/sdl2-config` ends up not in the -dev subcomponent. What you need however the headers and link objets, and they're in `games-dev`.

SDL2-dev is somewhat special, so I'll make a special `devpkg-SDL2` bundle for this.

**Comment by nsauzede** [comment]
@ahkok, that's fantastic, the devpkg-SDL2 works like a charm and only installs 3Mb !!!
thank you very much
In fact I wasn't aware of all those (163 !!) devpkg- bundles !
Now I realize that a proper search as a developper would have been :
$ swupd search include/SDL.h
instead of :
$ swupd search bin/sdl2-config
