### ISSUE TITLE
VM support

### ISSUE THREAD

**Issue by manish3kumar** [clearlinux/distribution#466]
I am planning to set-up the infrastructure using CL to make CL builds. My requirement is to support parallel builds for multiple users at a same time. What's the best way to achieve it? 

I have tried using the Docker and installed it and configured it, but I am unable to run the docker machine for the clearlinux image i am getting the error. 
The Error Message :
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup $https_proxy: no such host.
See 'docker run --help'.

then moved to try other options like openstack or virtual box .
It seems to me that OpenStack is some complicated so decided to create the VM using virtual Box on Ubuntu Machine.

Virtual Box not installed earlier on Ubuntu this is fixed by providing the proxy_http ENV in command line.
Once the proxy issue is resolved, then Installed clearLinux with Live Image & created 2 VMs on the Ubuntu and checked with LIVE Image but problem with disk space for the live image. 

I have tried VirtualBox with CL live image but here hard disk is limited & can't extend. Link followed: https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox

I would need to make the set-up ready and working ASAP with requirement to make parallel builds for any users (to avoid mock lock issue).

Kindly suggest the workable solution.

**Comment by AntonioMeireles** [comment]
@puneetse, @manish3kumar 

afaict virtualbox boxes will/would work just great (default size is 40G and easy to change that (see src) ). only  limitation they have versus the VMware and libvirt ones is that they don't suport nested virtualization (so no kvm/kata inside them) - that's a general VBox limitation, not a ClearLinux boxes one.

If you have issues with those just bug me. AFAIK there are a few people within and outside Intel using them with success (there's even built-in hooks for the _proxy_ thing).

**Comment by puneetse** [comment]
@manish3kumar I don't think you're working on this any more but I'm closing this issue with the proposed solutions. If you need help with anything else, feel free to ask here or onthe forums.
