### ISSUE TITLE
How to install legacy-BIOS supported version

### ISSUE THREAD

**Issue by Raj2032** [clearlinux/distribution#467]
I am trying to find a legacy bios image file but I found the KVM version but not too sure how it differs from the normal version.

**Comment by thiagomacieira** [comment]
You're not finding it because we do not support systems without UEFI.

**Comment by thiagomacieira** [comment]
This is a project decision, so I am closing the issue.

**Comment by miguelinux** [comment]
KVM-legacy and Azure images uses Legacy Boot, they are VM environment.
For bare-metal you are on your own, but it is doable.

**Comment by Raj2032** [comment]
@miguelinux Is KVM worse in performance and/or does it lack other useful features since it is not "bare-metal"?

**Comment by Raj2032** [comment]
@thiagomacieira Why wouldn't the project support legacy BIOS as most Linux distros support legacy BIOS?

The only reason I am going for Clear Linux cause of its high performance.

**Comment by Raj2032** [comment]
@miguelinux KVM won't boot on my system unfortunately :(

**Comment by thiagomacieira** [comment]
Because the other aspect of Clear Linux (besides performance) is security. You can't do secure booting with Legacy BIOS.

Granted, we're still trying to get our keys signed by Microsoft, but that's the long-term goal.

**Comment by Raj2032** [comment]
@thiagomacieira Shouldn't there be a separate distro for legacy BIOS support? Even though it will be more vulnerable to attacks?

**Comment by fenrus75** [comment]
bootloader is one of the more complicated things to deal with, especially coexistence with other OSes on the same system

when we started Clear Linux, at that time UEFI was already the default for several years in systems shipping, and UEFI makes the boot loader setup quite a bit simpler and more robust...

later we realized that AWS (and a few similar other clouds) did not support UEFI yet, but for Cloud setups, the coexistence with other OSes does not exist as a problem.

so the current state is that for "real" hardware we support UEFI, and coexistence with other UEFI operating systems. For legacy boot setups, we have a set of code to cope but only if we're the only OS on the system.

I'm surprised you found/have a system that is new enough to run clear linux, but does not support UEFI... but in the last few days suddenly we are getting several reports of this. We'll need to figure out what to do about this; the coexistence is complicated for legacy boot and there's not a lot of people to help test that anymore... UEFI has become the vast majority nowadays

**Comment by Raj2032** [comment]
@fenrus75 My system is old but has good specs as it is a gaming PC.

Its a shame that my PC does not support UEFI. I was really looking forwards to using this OS. I guess I am going to have to look for another Linux distro. Do you know any other distros that are known for high performance?

**Comment by miguelinux** [comment]
@Raj2032 
Yes KVM has KVM kernel, you need to use the native kernel.

You can use mixer to create a new image with native kernel, or hack the image to include the native kernel.  

https://clearlinux.org/search?search=mixer
https://github.com/clearlinux/how-to-clear

**Comment by KrzysiuWojcik** [comment]
Clear Linux on Legacy BIOS?
Nothing easier!
You only need UEFI emulation, which you can get easily with Clover Bootloader.
Just find Clover's ISO image, burn it to CD (or create USB using BootDisk Utility) and then you can boot Clear Linux as easy as Ubuntu.
I'm not sure how to install Clover to hard disk from Linux. But I'm going to achieve it.

I'm pretty sure that it wold be enough if you create ESP partition on hard disk (~200/250 MB?) (also, Clear Linux makes own ESP partition, so if you install it on hard disk, you don't need to create new one), put EFI folder from Clover USB/CD (You will need HFS+ driver to read Clover files, on Windows use BootDisk Utility, on Linux install Hfsprogs (Debian) or Hfsutils (RHEL)) on that ESP and write bootsector. Here is mine, maybe it will work on your PC (it is from GPT disk so you also should have GPT table):
https://github.com/KrzysiuWojcik/CloverLinuxInstaller/blob/master/BOOTSECTOR.img
To install (on Linux):
dd if=BOOTSECTOR.img of=/dev/sdX bs=512 count=1
where sdX is your hard disk (type lsblk to check your disk name), e.g. sda or sdb

After proper bootsector installation, with proper files copied (you should have /EFI/CLOVER/ folder on ESP), it should boot to clover boot selector.

Here you should look for boot entry. It should be called Clear Linux or something similar). It also can be hidden. If so, press F3 to show all entries, and select "UEFI Internal" - this was proper entry in my case.

Tested on Dell Inspiron N5050, a laptop without UEFI and running Clear Linux :)

I hope that this method will work for others

**Comment by mdhorn** [comment]
@KrzysiuWojcik All of that should not be necessary. 
Clear Boot Manager was updated a few months ago to support non-UEFI booting. The Clear Linux OS Installer was then updated and support installing directly from the published ISOs since [clr-installer release 2.4.1](https://github.com/clearlinux/clr-installer/releases/tag/2.4.1) first found in Clear Linux OS release 32510 or higher.
Booth the most recent published ISOs for Desktop or Server should not only boot in legacy mode but will also install Clear Linux SO.

**Comment by turbokrzychu** [comment]
> @KrzysiuWojcik All of that should not be necessary. 
> Clear Boot Manager was updated a few months ago to support non-UEFI booting. The Clear Linux OS Installer was then updated and support installing directly from the published ISOs since [clr-installer release 2.4.1](https://github.com/clearlinux/clr-installer/releases/tag/2.4.1) first found in Clear Linux OS release 32510 or higher.
> Booth the most recent published ISOs for Desktop or Server should not only boot in legacy mode but will also install Clear Linux SO.

OK, my ISO can be outdated so that's why I had to do these steps ;) but if then, someone should post here proper message, but that haven't been done. I had read the topic and I posted answer :) Also this will work for all similar issues with all Linux distros and versions so maybe someone find my answer useful

**Comment by KrzysiuWojcik** [comment]
> @KrzysiuWojcik All of that should not be necessary. 
> Clear Boot Manager was updated a few months ago to support non-UEFI booting. The Clear Linux OS Installer was then updated and support installing directly from the published ISOs since [clr-installer release 2.4.1](https://github.com/clearlinux/clr-installer/releases/tag/2.4.1) first found in Clear Linux OS release 32510 or higher.
> Booth the most recent published ISOs for Desktop or Server should not only boot in legacy mode but will also install Clear Linux SO.

I have to disagree. I don't know what has been added to new installer, but I know that lates 32830 ISO downloaded today, that booted to live desktop, is unable to install bootloader. Installer hangs at "Installing boot loader" step (showing small orange X icon). Progress bar also stopped moving. I'm waiting about hour and nothing. 

If there is any non-UEFI support, it looks like that support is not working.
Clear* booted with Clover installs quickly.

**Comment by lgosselin** [comment]
I second that non-UEFI support is not working: I cannot make an old Proliant DL360p G8 boot a fresh install done with clear-32910-live-server.iso. There is no error during the installation but the server won't boot. 
Running `clr-boot-manager list-kernels` or `clr-boot-manager update` from the live server image will crash with a segmentation fault.
I also tried the advanced partitioning mode and double checked that the LegacyBootBIOS flag was set on the EFI partition. Nothing seems to work for me.
I still need to try the Clover approach described above but I'd like to generate the proper boot sector. What tool could achieve this for me?
