### ISSUE TITLE
devpkg jack / jackd bundles

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#468]
**Is your feature request related to a problem? Please describe.**
Developper files for the "jack" audio library is not available
It even seems like "jackd" (the actual jack daemon) is not available

**Describe the solution you'd like**
I would like :
`$ sudo swupd search include/jack/jack.h`
To suggest adding eg: devpkg-jack,  a lightweight devpkg,
Ideally it would also include the useful GUI tool "qjackctl", and of course draw a dependency to the actual "jackd" bundle

**Describe alternatives you've considered**
Install jack manually ? (ugh)
that might not mix well with other system parts (sound daemon ? systemd ?)

**Additional context**
N/A

**Comment by fenrus75** [comment]
I've looked at Jack before

the hard part is coexistence with pulseaudio

**Comment by nsauzede** [comment]
Yes, I know that the "jack" case is ont easy, even on Ubuntu : it is generally not trivial to get a working state with simultanesouly cooperating pulseaudio/jack :-(

**Comment by puneetse** [comment]
A `devpkg-jack2` bundle has been added since with the headers.

**Comment by nsauzede** [comment]
great ! I confirm I can now _compile_ jack application
now, without a bundle containing the famous "qjackctl", it's not easy to start/manage the jackd server
would it be possible to add such a bundle ?
thanks

**Comment by puneetse** [comment]
Yes, that is still unsolved. There is a duplicate request for that here: https://github.com/clearlinux/distribution/issues/587 

I'm going to close this issue so that the discussion doesn't get split.
