### ISSUE TITLE
Feature request: Add subversion to Clear Linux

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#47]
https://subversion.apache.org/

**Comment by fenrus75** [comment]
hmmmm.
didn't realize that this was still a thing (versus git svnimport)

**Comment by cmarcelo** [comment]
"git svn", in particular "git svn clone" does use svn perl bindings of the subversion libraries to work (so it is currently broken in Clear too).

**Comment by cmarcelo** [comment]
Thanks.
