### ISSUE TITLE
gnome desktop settings will not open (Incompatible processor, missing aes)

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/distribution#471]
**Describe the bug**
On a clean install of 27920, start the gnome desktop and select the settings icon in the upper right hand drop-down.  The setting application starts and then closes.

**To Reproduce**
1. Sign into gnome desktop
2. select the gnome settings app

**Expected behavior**
The settings application will launch and allow me to modify gnome settings

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: 27920
 - Bundles: added desktop-autostart and sysadmin-basic

**Additional context**
journalctl output:
```
Feb 20 22:57:31 clr-24edb650831e4140b755ce56ee512118 gnome-control-center.desktop[649]: Incompatible processor. This Qt build requires the following features:
Feb 20 22:57:31 clr-24edb650831e4140b755ce56ee512118 gnome-control-center.desktop[649]:     aes
Feb 20 22:57:31 clr-24edb650831e4140b755ce56ee512118 gnome-control-center.desktop[649]: Incompatible processor. This Qt build requires the following features:
Feb 20 22:57:31 clr-24edb650831e4140b755ce56ee512118 gnome-control-center.desktop[649]:     aes
```

/proc/cpuinfo:
```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz
stepping        : 9
microcode       : 0x20
cpu MHz         : 1697.389
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave avx f16c lahf_lm cpuid_fault epb pti tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
bogomips        : 3595.64
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by ahkok** [comment]
when you run the hardware compatibility checked on this system, what is the output?

**Comment by mdhorn** [comment]
I'm willing to bet no AES, I don't see it list on the cpu flags.
I have an older laptop that has a similar processor, everything but AES so "most things" work, but anything compiled requiring AES fails -- like gnome desktop settings, gnome initial setup, etc ...

**Comment by thiagomacieira** [comment]
There are a few WSM, SNB, IVB and HSW without AES. I fixed GCC and Clang a few months ago to not enable the feature by default with `-march=` but I don't think that change landed in Clear. It might be GCC 9. Or I'm mistaken about sending the change to GCC...

How weird is it that we're getting a **Qt** error message from **GNOME** settings?

**Comment by tpleavitt** [comment]
@ahkok I'll run this in the morning and post it here.

This is an IVB CPU

**Comment by thiagomacieira** [comment]
Update: I did not send a patch to GCC. But I do remember now speaking to H.J. about this and he said it was an intentional choice on their part to support the most common featureset for WSM and higher. The question to Clear is: do we agree? Or do we believe we should support those systems like @tpleavitt's that don't have AES support?

**Comment by fenrus75** [comment]
does gcc even auto generate AES ?

**Comment by thiagomacieira** [comment]
No, but it predefines `__AES__` and that's what Qt is reacting to. That macro, like `__AVX__` and others, tells the code that the compiler was called with either `-maes` (like `-mavx`) or with an `-march=` that indicates a processor with support for the feature. So the runtime CPUID and the fallback code were removed.

Anyway, a little digging shows I **did** submit the change to GCC. It's SVN revision 263989, but was accidentally reverted in 264052 due to a refactoring. I'll re-submit.

Question to Clear again: do we want to apply the patch locally and support pre-SKL without AES?

**Comment by tpleavitt** [comment]
Output from running ./clear-linux-check-config.sh host

Checking if host is capable of running Clear Linux* OS

SUCCESS: 64-bit CPU (lm)
SUCCESS: Supplemental Streaming SIMD Extensions 3 (ssse3)
SUCCESS: Streaming SIMD Extensions v4.1 (sse4_1)
SUCCESS: Streaming SIMD Extensions v4.2 (sse4_2)
FAIL: Advanced Encryption Standard instruction set (aes)

**Comment by thiagomacieira** [comment]
So this is now a question of policy: do we want to support machines like @tpleavitt's, which have all the processor features we need, except for AES?

**Comment by ahkok** [comment]
Technically we've never supported it. Changing it now is of very little value, I feel.

**Comment by puneetse** [comment]
I'm closing this issue as the AES requirement has since been lifted from Clear Linux. @tpleavitt please reopen if this is still an issue.
