### ISSUE TITLE
nodejs crashes

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#472]
nodejs segfaults in the current 27930 release, during a simple yarn/npm install. This was not the case a week ago. If I replace `node` with the version from  nodejs.org, everything works. This is on a recent NUC, btw.
```
node[15611]: segfault at 0 ip 00000000013166fa sp 00007ffd0dc55330 error 4 in node[1200000+1a1000]
```

**Comment by AthenasJimenez** [comment]
Cannot reproduce it on 28100. @neben are you still facing this issue?

**Comment by neben** [comment]
@AthenasJimenez I'm still experiencing this issue. This is the end of an `strace` run:
```
ben@nuc ~/web $ PATH=/usr/bin:$PATH strace yarn
) = 4(1</dev/pts/10<char 136:10>>, "\33[1G", 4
write(1</dev/pts/10<char 136:10>>, "Done in 0.60s.\n", 15Done in 0.60s.
) = 15
epoll_pwait(3<anon_inode:[eventpoll]>, 

[], 1024, 7560, NULL, 8) = 0
write(8<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```
And this is the system:
```
root@nuc ~ # ls -l /usr/bin/node 
-rwxr-xr-x 1 root root 26101744 Feb 15 19:13 /usr/bin/node
root@nuc ~ # swupd info
Installed version: 28190
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
```
OTOH, the `node` binary is from mid February, so maybe there's an issue with my installation?

**Comment by AthenasJimenez** [comment]
"npm install" works well for me, but "yarnpkg" is definitely misbehaving. Reopening for now.

**Comment by neben** [comment]
`npm install` crashes for me, too.
```
ben@nuc ~/web $ PATH=/usr/bin:$PATH strace npm install
[...]
) = 106</dev/pts/0<char 136:0>>, "[\33[7m       \33[27m\33[90m.........."..., 106[       ...........] | postinstall: sill install executeActions
futex(0x1dd1d4c, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_pwait(3<anon_inode:[eventpoll]>, [{EPOLLIN, {u32=8, u64=8}}], 1024, 0, NULL, 8) = 1
read(8<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 1024) = 8
futex(0x1dd1d4c, FUTEX_WAKE_PRIVATE, 1) = 1
epoll_pwait(3<anon_inode:[eventpoll]>, [{EPOLLIN, {u32=8, u64=8}}], 1024, 7, NULL, 8) = 1
read(8<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 1024) = 8
epoll_pwait(3<anon_inode:[eventpoll]>, [], 1024, 7, NULL, 8) = 0
write(8<anon_inode:[eventfd]>, "\1\0\0\0\0\0\0\0", 8) = 8
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```
The above is using the current `node` from a few days ago:
```
ben@nuc ~/web $ PATH=/usr/bin:$PATH strace -e execve npm -v
execve("/usr/bin/npm", ["npm", "-v"], 0x7ffcfc8c87c8 /* 37 vars */) = 0
execve("/usr/bin/node", ["node", "/usr/bin/npm", "-v"], 0x7fff9d2659e0 /* 37 vars */) = 0
6.4.1
+++ exited with 0 +++

ben@nuc ~/web $ ls -l /usr/bin/node
-rwxr-xr-x 1 root root 26122192 Mar  8 21:13 /usr/bin/node
ben@nuc ~/web $ sha256sum /usr/bin/node 
be51a0a04bc64ee8fe8380d482faf92a2e54591792ec30b30273ca67cd817d34  /usr/bin/node

ben@nuc ~/web $ swupd info
Installed version: 28260
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
```

**Comment by bktan8** [comment]
I'm getting segmentation fault under Clear version 28400.  

```
bktan1@clr-i9990k ~ $ swupd info
Installed version: 28400
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/

bktan1@clr-i9990k ~ $ npm install npm -g
Segmentation fault (core dumped)ailedOptional: verb npm-session 20937fd2341ac2ee
```

@abecastillo - Do we have a BBT test for nodejs-basic/npm install?  It seems we run into this issue periodically.  Would be nice to catch this before releasing...

**Comment by abecastillo** [comment]
@bktan8 looking at it. there is something already. will make sure this specific case is included.

**Comment by bktan8** [comment]
@abecastillo - this issue is easy to reproduce on a HyperV Clear image.  I just tried 28540 and issue persists.

Steps:
1. Boot up a fresh HyperV Clear image
2. $ sudo swupd bundle-add nodejs-basic bundle
3. $ sudo npm install npm -g

**Comment by sofar** [comment]
Confirmed for me. Very broken atm, my jobs crash after 10 seconds in this stack trace:

```
#0  0x0000000001318bea in node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) ()
#1  0x000000000131a023 in node::PerIsolatePlatformData::RunForegroundTask(uv_timer_s*) ()
#2  0x000000000088c006 in uv_run.constprop ()
#3  0x00000000013a2de5 in node::Start(v8::Isolate*, node::IsolateData*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) ()
#4  0x00000000013a3814 in node::Start(int, char**) ()
#5  0x00007ffff772fe73 in __libc_start_main (main=0x868c20 <main>, argc=2, argv=0x7fffffffc4c8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffc4b8) at ../csu/libc-start.c:308
#6  0x0000000000868dbe in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by abecastillo** [comment]
@bktan8 yeap, @AthenasJimenez has been fighting this issue these days.

**Comment by ahkok** [comment]
I bumped/recompiled this to see if that helps. I can also confirm that a plainly compiled `node` from source also doesn't give the problem.

**Comment by ahkok** [comment]
Do we have any long-running `node` jobs we can use for testing easily?

**Comment by ahkok** [comment]
```
$ gdb --args /usr/bin/node /usr/bin/npm install npm -g
Thread 1 "npm" received signal SIGSEGV, Segmentation fault.
0x0000000001318bea in node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) ()
(gdb) 
```

**Comment by ahkok** [comment]
Doesn't even need any job. Ish.

**Comment by AthenasJimenez** [comment]
Well installing ajv has no issues 

$ sudo npm install ajv
npm WARN saveError ENOENT: no such file or directory, open '/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ ajv@6.10.0
added 6 packages from 4 contributors and audited 6 packages in 4.076s
found 0 vulnerabilities

**Comment by AthenasJimenez** [comment]
Maybe related to the size of the installed package? cause foo and some other bigger stuff triggers the error.

**Comment by sofar** [comment]
The crash happens after ~10 seconds, so if the package is small it won't happen. Any job over 10 seconds crashes, this is how I reproduced it with shinobi.

**Comment by AthenasJimenez** [comment]
Fix in the oven, should be available by the end of the day.

**Comment by neben** [comment]
I can confirm everything is working now, thanks a lot @AthenasJimenez for your work!
