### ISSUE TITLE
Add Network Manager openvpn plugin

### ISSUE THREAD

**Issue by Riotvan81** [clearlinux/distribution#475]
Hello, the openvpn plugin seems to be missing from network-manger. I couldn't find the option to import a *.opvn so i tried the commandline and it seems to be missing.
`Error: failed to load VPN plugin: unknown VPN plugin "org.freedesktop.NetworkManager.openvpn"`
Could this be added?
Thanks!

**Comment by fenrus75** [comment]
done

**Comment by Riotvan81** [comment]
Thank you kindly :+1:

**Comment by anselmolsm** [comment]
[networkmanager-openvpn](https://github.com/clearlinux-pkgs/networkmanager-openvpn) is now available in [NetworkManager bundle](https://github.com/clearlinux/clr-bundles/blob/master/bundles/NetworkManager).
