### ISSUE TITLE
Bundle request for devpkg-libboost

### ISSUE THREAD

**Issue by alecz20** [clearlinux/distribution#478]
I am trying to get RStudio server installed on Clear Linux and since there is no bundle for it, I decided to compiling from source, however it seems that the Boost headers are not available on Clear Linux.

I would like to be ale to install the Boost development library via `swupd`.

As an alternative for now, I am considering attempting to compile statically with a downloaded version of Boost from source.

It is also possible that I completely missed the development boost bundle in which case I would appreciate some guidance.

**Comment by fenrus75** [comment]
it'll be called "devpkg-boost" but I just added this
