### ISSUE TITLE
Can't install it from both live version (beta) or standard installer

### ISSUE THREAD

**Issue by logan001** [clearlinux/distribution#479]
For standard installer the wifi adapter shows up but no option to set it up. (has been already reported)
So i've tried live beta which starts up / can connect to wifi but for some strange reason i'm unable to install it.
I have a few hdd (6) in my computer. one of this hdd is an old sata 2 of 1 tb that i keep it for linux only.
Seems that the installer refuse to install without a swap partition which made me shrink one partition in order to create the swap partition. and after creating the swap and press install the installer exits without error or anything.
on second try the installer just shows the name. on 3rd time after reboot same behavior only the name.
replace the img file and start over
decided to clear the entire hdd losing a lot of data just to try clear linux.
i decided to start with auto creation of partition. the installer starts/create partitions and stops
nothing more. just stops. does not exit and does not respond. everything else works except the installer.
So i ended up with an empty hdd.

Is blkid suppose to not work? Cause it does not return at all. It's like it keeps thinking but no hdd is accessed.

**Comment by ahkok** [comment]
@mdhorn I realize this bug is somewhat confusing, is there something the user could try or provide better information?

**Comment by mdhorn** [comment]
It would be helpful if you could attach the `clr-installer.log` and `pre-install-clr-installer.yaml` files from the /root directory of the installation source media.

- WiFi installations are currently not supported from the installer -- [this is work in progress](https://github.com/clearlinux/clr-installer/issues/3) to be resolved for installations from the desktop GUI environment.
- The installed currently requires there be a swap partition to start the installer;[ there is an open GitHub Issue to remove this restriction.](https://github.com/clearlinux/clr-installer/issues/205)
- The installer has a limitation right now that the entire media needs to be used for the installation; pre-existing partition on the installation target will be lost -- hence the final warning before starting the installation. We are actively[ working on removing this restriction](https://github.com/clearlinux/clr-installer/issues/14).

**Comment by logan001** [comment]
sorry, i can't do that anymore. i've put linuxmint back on that hdd so i had to replace the image on the stick

**Comment by ahkok** [comment]
No problem. We continue to address issues in the installer and live images.
