### ISSUE TITLE
Package request: Restic

### ISSUE THREAD

**Issue by castrojo** [clearlinux/distribution#480]
**Is your feature request related to a problem? Please describe.**
Include Restic, a fast backup tool. One of the nicest features is it just has support for the common cloud buckets, making it pretty easy to just drop encrypted backups on a cloud. 

**Additional context**
https://restic.net/

**Comment by nesiusra** [comment]
Pulling in @bwarden here too.

**Comment by bwarden** [comment]
Also golang; will take a while.

**Comment by bwarden** [comment]
Packaged. Looking for a good bundle to put it in.

**Comment by bwarden** [comment]
Will create a `restic` bundle.
