### ISSUE TITLE
Package request: rclone

### ISSUE THREAD

**Issue by castrojo** [clearlinux/distribution#481]
**Is your feature request related to a problem? Please describe.**
Rclone is basically rsync for the cloud, so you can copy things from cloud to cloud without an intermediary step. It can also act as an optional backend for restic backup (which I've filed as issue #480 )  

**Additional context**
https://rclone.org/

**Comment by nesiusra** [comment]
@bwarden  - can take a look?

**Comment by bwarden** [comment]
This is golang; will take a bit longer.

**Comment by bwarden** [comment]
Packaged. Looking for a good bundle to put it in.

**Comment by bwarden** [comment]
Will create an `rclone` bundle.
