### ISSUE TITLE
Package Request: bcache-tools

### ISSUE THREAD

**Issue by castrojo** [clearlinux/distribution#482]
**Is your feature request related to a problem? Please describe.**
bcache is a way to pair a fast SSD with a slow HDD to create a hybrid disk: https://bcache.evilpiepirate.org/

**Describe the solution you'd like**
Intel RST is not available for Linux, so this is how I use an optane stick in my PC. I'm currently building this from source. 

**Describe alternatives you've considered**
One concern is that the upstream author has generally moved on to bcachefs, and as such upstream git hasn't received much love. For example I had to apply [this patch](https://github.com/koverstreet/bcache-tools/pull/2) to get it to compile on Clear Linux.

However the tool works fine once compiled and installed, and is only necessary to create the devices/volumes and also appears to be supported in other distributions and included in some installers like [curtin](https://curtin.readthedocs.io/en/latest/topics/storage.html).

Support for bcache itself is already in the kernel so all that works as intended on Clear. 

**Additional context**
https://github.com/koverstreet/bcache-tools
https://wiki.archlinux.org/index.php/bcache

**Comment by nesiusra** [comment]
@miguelinux @bwarden  - can one of you look at this?

**Comment by bwarden** [comment]
In progress

**Comment by bwarden** [comment]
Packaging done, will bundle for release shortly.
