### ISSUE TITLE
Using 'sudo swupd bundle-remove' to remove the added bundle - All the files/folders under the installed root folder are removed even the files/folders do not belong to this root folder

### ISSUE THREAD

**Issue by xiangquanliu** [clearlinux/distribution#483]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
For example, only '/opt/intel/sgxpsw' is installed by 'swupd bundle-add'. But when using 'swupd bundle-remove' to remove the bundle, the folder /opt is removed. The result should be that only '/opt/intel/sgxpsw' is removed and /opt/intel/sgxsdk should be kept there.

 $tree /opt/intel
/opt/intel

├── sgxpsw

└── sgxsdk

**Environment (please complete the following information):**
 - Clear Linux OS version: 27930
 - Bundles: bundle made by mixin

**Comment by fenrus75** [comment]
swupd is really really set up to only work in /usr......

**Comment by miguelinux** [comment]
AFAIK this is a mixer image, where the software was installed to /opt

**Comment by thiagomacieira** [comment]
What Arjan said is still true: swupd is only set up to work with /usr.

If you told it to manage /opt, then it assumes it can manage ALL of /opt.

**Comment by miguelinux** [comment]
> What Arjan said is still true: swupd is only set up to work with /usr.
> 
> If you told it to manage /opt, then it assumes it can manage ALL of /opt.

So, we need to fix swupd to leave /opt as is or do not touch it.

**Comment by fenrus75** [comment]
we need to fix mixer to not let anything in /opt get into bundles, similar
to how we not let it package /var or /etc

**Comment by ahkok** [comment]
I agree with @fenrus75 - mixer/swupd are behaving according to design. No package should put stuff in `/opt`, exactly like `/usr/local` (since they are identical from a distro perspective).
