### ISSUE TITLE
Unexpected behaviours related to gdm.service

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#484]
**Description**
- I first installed clear linux in Jan 2018 and the first boot after installation works well, but since the second time the `gdm.service` had never successfully started. 
- I was able to run `sudo systemctl restart gdm` to start the it manually in tty, and then the graphical log-in interface would correctly show up.
- I had tried to have a clean reinstall of clear linux, but still the problem remained the same, i.e. `gdm.service` failed and needed to be restarted manually since the second boot after the installation. Note that the re-installation was still based on a same installer image, so my problem might be related to that particular installer and not others.
- During last two days I messed up my `dbus` and the system cannot start the GUI interface as the `dbus.service` was down. Then I deleted the `/var` and `/etc` directories to `reset` my system. I have also ran the `sudo swupd verify -fix` shell command. After a reboot, I found that the system **could** correctly gets into the GUI log-in interface, which means the `gdm.service`\ successfully auto-started.

**To Reproduce**
- It's hard to tell how to reproduce this. But if you also face a tty log-in screen every time, then try running `systemctl | grep failed` or just `systemctl` at tty to see whether the `gdm.service` failed.
- If so, then the next step is to delete both `/var` and `/etc` to perform a reset, and run `sudo swupd verify -fix` to fix any missing/wrong files. This should be done with caution.
- After a reboot, if `gdm.service` no longer fails, then it might confirm my hypothesis that a previous installer introduced a bug but now it's fixed. And the fix needs to take effect by system reset.

**Environment:**
 - Clear Linux OS version: 27970
 - Bundles: At the the first occurrence of the unexpected behaviour, only `clr-os-core` and `desktop` was installed.

**Comment by miguelinux** [comment]
Did you install desktop-autostart bundle?

Can you confirm that you have /dev/dri/card0 device file?

This device file is used to detect Gfx HW to boot to GUI (gdm/gnome).

**Comment by lebensterben** [comment]
@miguelinux The `desktop-autostart` bundle was installed.
The `/dev/dir/card0` file exists. Along with it, there are `card1, card2, renderD128, renderD129, renderD130`.

**Comment by miguelinux** [comment]
That is weird.

Is gdm.patch active?

systemctl status gdm.path

systemctl is-active gdm.path

**Comment by lebensterben** [comment]
```bash
> systemctl status gdm.path
● gdm.path - Rise GDM service automatically if a graphic card exist
   Loaded: loaded (/usr/lib/systemd/system/gdm.path; static; vendor preset: disabled)
   Active: active (running) since Mon 2019-02-25 12:23:16 EST; 1h 18min ago

Feb 25 12:23:16 clr-lucius systemd[1]: Started Rise GDM service automatically if a graphic card exist.
> systemctl is-active gdm.path
active
```

**Comment by lebensterben** [comment]
@miguelinux 
Well, I found something really interesting. I've two NVIDIA 1080 Ti (with SLI) installed, so I can connect the display to either of the discrete graphics or integrated graphics. 

The thing is, when it's connected to integrated graphics, the gdm.service can starts normally. But when the system goes to suspension after being idle for a while, the display won't be lit again, though the system is back on.

And if I connect the display to either of the 1080 Ti, the gdm.service will fails and I've to restart them manually. But in this case, the suspension works well.

**Comment by ahkok** [comment]
This could be a duplicate. We've seen many similar issues with nvidia cards. #353

**Comment by tpleavitt** [comment]
Closing as duplicate to #353
