### ISSUE TITLE
External USB drive boot problems

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#485]
**Describe the bug**
I have a large USB external drive (Seagate Ultra Slim MT 2TB  USB3 interface).
I installed Clear on the drive but it fails to boot. Depending on the image (live or installer),
kernel either panics ("Unable to mount root fs on unknown-block(0,0)" or waits forever for root to mount,  probably due to different rootwait arguments.

**Expected behavior**
Installed image should boot/work without any problems.
The same USB drive boots/works just fine with Fedora 29 Live image.

**Additional context**
After some experimenting I did manage to boot the image: I needed to plug the image into a USB hub.
After the image booted, any disk I/O was painfully slow. Nevertheless, this would suggest there is a USB driver missing in the installer kernel.

**Comment by ahkok** [comment]
Likely: usb mass storage driver. @miguelinux can you check if that one is a module, and not built-in?

**Comment by ahkok** [comment]
Note it should be able to use an initrd to get past this issue, I suspect.

**Comment by miguelinux** [comment]
Can you verify that the PARTUUID from the rootfs is set properly in the
kernel cmdline.

Another solution is to edit the root= flag from the kernel cmdline.

Hit up or down arrow key when your platform boots, then hit "e" key and
go to root= flag and set to root=/dev/sdbX where X is the rootfs
partition.

**Comment by jurobystricky** [comment]
I tried all of those. Yes, PARTUUID is fine. As I mentioned, I did manage to boot the external drive, but I  had to use a USB hub so it was so slow it was not usable. So it would seem it is a case of a missing built-in USB driver in kernel native. (OHCI, EHCI, UHCI...?)

**Comment by miguelinux** [comment]
Certainly CONFIG_USB_OHCI_HCD is not enabled.

But the Open Host Controller Interface (OHCI) is a standard for accessing
USB 1.1 host controller hardware.  It does more in hardware than Intel's
UHCI specification.  If your USB host controller follows the OHCI spec,
say Y.  On most non-x86 systems, and on x86 hardware that's not using a
USB controller from Intel or VIA, this is appropriate.  If your host
controller doesn't use PCI, this is probably appropriate.  For a PCI
based system where you're not sure, the "lspci -v" entry will list the
right "prog-if" for your USB controller(s):  EHCI, OHCI, or UHCI.

Is your device detected as USB1?

EHCI HCD (USB 2.0) support is enabled as built-in
xHCI HCD (USB 3.0) support is enabled as built-in

**Comment by miguelinux** [comment]
Is not a USB type issue, it is a USB specific driver issue.

CL enabled your driver as module as you can install to the external HD.

Can you help me to identify the USB module that is used by your external
HD.

https://unix.stackexchange.com/questions/60078/find-out-which-modules-are-associated-with-a-usb-device

**Comment by miguelinux** [comment]
Hi,

I set USB_UAS as built-in
    
The USB Attached SCSI protocol is supported by some USB
storage devices.  It permits higher performance by supporting
multiple outstanding commands.

Pleas try with linux-4.20.12-707 native kernel

**Comment by jurobystricky** [comment]
@miguelinux 
I built a new simple image with the new native kernel. I used "dd" to transfer the image to the Seagate drive.
The image booted flawlessly.  Thanks for the quick fix.

**Comment by jurobystricky** [comment]
Tested some more images. No problems anymore.
