### ISSUE TITLE
Package request: neomutt

### ISSUE THREAD

**Issue by lucasdemarchi** [clearlinux/distribution#486]
Fork of mutt with some additional features.
https://neomutt.org/about.html
https://neomutt.org/feature.html

**Comment by bryteise** [comment]
Hrm seems like a more active upstream. @phmccarty I think you are a mutt user, any issues with just replacing the current mutt with neomutt?

**Comment by phmccarty** [comment]
Can neomutt be installed side-by-side with mutt? Mutt is also active upstream (8 releases in the past year)...

**Comment by bryteise** [comment]
Ah it appears it can be installed side-by-side, adding...

**Comment by bryteise** [comment]
Should be in the next release as 'neomutt'.

**Comment by lucasdemarchi** [comment]
configure options are wrong. As far as I could check they were added like the ones for mutt, but they are not the same. Major drawback is the lack of support for header_cache.

In Fedora lmdb is used for the cache. Following their spec: https://copr-dist-git.fedorainfracloud.org/cgit/flatcap/neomutt/neomutt.git/tree/neomutt.spec

**Comment by bryteise** [comment]
Hrm well I did pass --enable-hcache, I'll add --enable-lmdb too though, I'll repoen this issue so please let me know if tomorrow's update works better for you.
