### ISSUE TITLE
Package request: remmina

### ISSUE THREAD

**Issue by lucasdemarchi** [clearlinux/distribution#487]
rdp and vnc client.

**Comment by dorileo** [comment]
the bundle ```desktop-apps-extras``` installs remmina.

**Comment by ahkok** [comment]
@bryteise we should just split this app into a bundle as well.

**Comment by lucasdemarchi** [comment]
There's the "Remmina"  with uppercase R

**Comment by miguelinux** [comment]
> There's the "Remmina"  with uppercase R

Yes it is:

https://github.com/clearlinux/clr-bundles/blob/master/bundles/Remmina

Which upstream is

https://github.com/FreeRDP/Remmina
