### ISSUE TITLE
please reconsider shipping an rsync built against system's zlib

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#488]
**Describe the bug**

`rsync` started very recently (as off [this](
https://github.com/clearlinux-pkgs/rsync/commit/a7a81ac93d3c8bb5547b3c5e4af929efb2a9ab0f)) to be built against system's `zlib` which is in this specific case has very unwanted side effects  ...

`rsync` 3.1.x can be shipped with two mutually exclusive compressions ways, "traditional" and "modern". The traditional one (`-z`) relies in an (internal) custom `zlib`, specific to `rsync`, while the modern (`-zz`) uses stock (systems') `zlib`.

As ClearLinux's `rsync` (upwards from 17970) started being built using `--without-included-zlib`, the traditional compress (`-z`) vanished, and if one tries to use it (as a zillion of tools do by default) will get:
> `rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.`

OTOH using `-zz` works but **only** when chatting to other hosts that also have an `rsync` that is also built with system's `zlib`. When trying to connect to a "traditional" one (built with internal `zlib`) one will get  ...
> `rsync: on remote machine: --new-compress: unknown option`

**To Reproduce**

rsync from a pre 27970 ClearLinux setup  release to any newer one (or to *any* other rsync server)  

**Additional context**

this was spotted by @krsna1729 and @ganeshmaharaj while working on top of my Vagrant boxes (workarounded [here](https://github.com/clearlinux/cloud-native-setup/pull/63)) 

the same issue elsewhere ...
- Fedora
  - https://bugzilla.samba.org/show_bug.cgi?id=10372
  - https://src.fedoraproject.org/cgit/rpms/rsync.git/tree/rsync.spec
- upstream 
  - https://bugzilla.samba.org/show_bug.cgi?id=10372

(AFAICT as this turned to be a chicken and egg problem all major distros keep sailing currently with the internal `zlib` these days ...)

**Comment by thiagomacieira** [comment]
The problem is that internal zlib has open security issues and we're unwilling to accept them anymore.

We should patch rsync to suppress the warning.

**Comment by thiagomacieira** [comment]
Actually, you link to upstream indicates that `-z` is actually not compressing now, intentionally so because the `-zz` option requires a new enough rsync on the other side. So the warning is legitimate.

**Comment by anselmolsm** [comment]
It was not posted here but the rsync package has been [reverted](https://github.com/clearlinux-pkgs/rsync/commit/cb2e5621aef1ce2dfa37b9fff20abcbedbedf908) to use the bundled zlib and patches were applied to that zlib in order to fix security issues.

Arch Linux published something interesting about the subject yesterday: https://www.archlinux.org/news/rsync-compatibility/

**Comment by rossburton** [comment]
Yes, rsync-3.1.3-39 onwards uses the internal rsync.  Closing.
