### ISSUE TITLE
Binutils bundle seems to be lacking LTO support

### ISSUE THREAD

**Issue by Nirgendsdorf** [clearlinux/distribution#489]
**List the package you would like to see updated**
Binutils includes the tools to complement gcc that are necessary to build sources into executable binary files.

**Does this update provide any significant new features that may be needed**
Since a number of versions, the GNU Compiler Collection has supported Link-Time Optimization. In order to function fully so that libraries may also be optimized, an LTO plugin must be available for ar, ranlib, and ld to handle the special "gimple" object code that makes gcc's LTO features work.

This plugin is described in the manual pages for the various binutils. Take ar, for example:

-----------
--plugin name

           The optional command-line switch --plugin name causes ar to load
           the plugin called name which adds support for more file formats,
           including object files with link-time optimization information.

           This option is only available if the toolchain has been built with
           plugin support enabled.

           If --plugin is not provided, but plugin support has been enabled
           then ar iterates over the files in ${libdir}/bfd-plugins in
           alphabetic order and the first plugin that claims the object in
           question is used.

           Please note that this plugin search directory is not the one used
           by ld's -plugin option.  In order to make ar use the  linker plugin
           it must be copied into the ${libdir}/bfd-plugins directory.  For
           GCC based compilations the linker plugin is called
           liblto_plugin.so.0.0.0.  For Clang based compilations it is called
           LLVMgold.so.  The GCC plugin is always backwards compatible with
           earlier versions, so it is sufficient to just copy the newest one.
-----------

I am attempting to build ffmpeg with LTO. Multimedia transcoding is a very demanding task; fully optimized software is a must! The ffmpeg configure script includes an '--enable-lto' option. Turning it on, however, produces lots of error messages from ar and ranlib about how they cannot handle LTO objects because the LTO plugin cannot be found. I did a swupd search and 'liblto_plugin.so*' was not found. It would seem the binutils were built without LTO support. I would appreciate it if someone were to review and remidy this situation.

**Comment by fenrus75** [comment]
this is odd since we use LTO a lot ourselves... so the basics work

**Comment by Nirgendsdorf** [comment]
After doing some more digging, I found that much of what I wrote above is in error. I couldn't find a way to delete this ticket, so I'm closing it.
