### ISSUE TITLE
gnome-shell complains about missing /usr/bin/haswell/Xwayland

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#49]
That prevented gnome-shell to work, so logging in with gdm would always failed. I've workarounded by linking /usr/bin/haswell/Xwayland to /usr/bin/Xwayland.

**Comment by iphutch** [comment]
@mrkz could you please take a look at this bug?

**Comment by fenrus75** [comment]
I think I fixed this; telemetry data so far is backing this up


On Mon, Apr 23, 2018 at 1:09 PM, Ianeta Hutchinson <notifications@github.com

**Comment by iphutch** [comment]
fixed
