### ISSUE TITLE
visudo is installed as part of sudo bundle but immediately gives error that  vi editor is not found

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#495]
Either nano needs to be made the default editor or vi should be installed in the default configuration.

**Comment by ahkok** [comment]
alternatively, you can use:

```
export EDITOR=/usr/bin/nano
sudo -E visudo
```

However, as stated before, using`sudo` with `visudo` is not the right way.

**Comment by mdhorn** [comment]
From a user's perspective, I have to agree with @eadamsintel

The command is called **vi**sudo so that implies a requirement of having **vi** on the system. We really should include vi in the bundle that installed visduo OR as Eric suggested change 'visudo' to use the editor that is installed.

Can we really just tell all users the only way to do something is the one way we feel is the best?
`sudo visudo` has been around a lot longer than Clear Linux; what the problem is using that command like other distros?

**Comment by fenrus75** [comment]
even on fedora the wheel group is the way to do it.... for the last 25
years.

**Comment by mdhorn** [comment]
That is A WAY to do it, but using visudo to edit the sudo files is legitimate as well.

**Comment by fenrus75** [comment]
absolutely.. just a really bad idea on clear linux.

just don't expect sudo to preserve your environment.

sudo su -
visudo

works great.

**Comment by thiagomacieira** [comment]
sudo -l visudo

**Comment by eadamsintel** [comment]
sudo -E visudo worked for me as well.  Is there an easy way in Linux to offer hints to people on what command they should run?  If someone ran  "sudo visudo" they would get a message back "Consider using 
usermod -aG wheelnopw <username> instead"   This could be expanded to a ton of different commands and could be a way Clear Linux becomes the most helpful distribution on the CLI and help people run commands the way the CL team thinks is the most appropriate.

**Comment by miguelinux** [comment]
> sudo -E visudo worked for me as well.  Is there an easy way in Linux to offer hints to people on what command they should run?  If someone ran  "sudo visudo" they would get a message back "Consider using 

Sudo was already fixed to works as expected.

> usermod -aG wheelnopw <username> instead"   This could be expanded to a ton of different commands and could be a way Clear Linux becomes the most helpful distribution on the CLI and help people run commands the way the CL team thinks is the most appropriate. 
> 

A Community public forum is been planning to include all of those topics.
