### ISSUE TITLE
br_netfilter.ko not present in kernel_native bundle

### ISSUE THREAD

**Issue by spitfire88** [clearlinux/distribution#496]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
kernel_native bundle is missing a moduel "CONFIG_BRIDGE_NETFILTER: Bridged IP/ARP packets filtering" that is required by k3s (https://k3s.io/) - A lightweight kubernetes fork meant to run on edge devices.

**To Reproduce**
1. Install Clearlinux on Intel NUC i5
2. Download k3s (See Quick Start on https://github.com/rancher/k3s)
3. https://github.com/rancher/k3s/blob/master/install.sh

**Expected behavior**
"sudo k3s server" must complete without errors.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]: 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28070
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
NetworkManager                                                                                                                                                                                                 [33/1924]
acpica-unix2
alsa-utils
baobab
bootloader
cheese
curl
desktop
desktop-apps
desktop-assets
desktop-gnomelibs
desktop-locales
diffutils
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
fonts-basic
fuse
fwupdate
gedit
git
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gvim
gzip
htop
iproute2
iptables
irssi
kbd
kernel-install
kernel-native
less
libX11client
libglib
libstdcpp
libva-utils
nautilus
network-basic
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
pygobject
python3-basic
seahorse
strace
sudo
sysadmin-basic
thermal_daemon
tmux
totem
tzdata
unzip
weechat
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Additional context**

**Comment by ahkok** [comment]
It's built-in. You should not modprobe it.

```
linux (master) $ grep BRIDGE_NET config
CONFIG_BRIDGE_NETFILTER=y
```

This is a bug in `k3s` that fails to account for it being built-in.

**Comment by ahkok** [comment]
https://github.com/rancher/k3s/blob/master/install.sh#L137

seems to nicely have `-/sbin/modprobe br_netfilter` which makes modprobe errors ignored.

**Comment by ahkok** [comment]
@spitfire88 You state:

> "sudo k3s server" must complete without errors.

But, what are the errors that it gives?

**Comment by spitfire88** [comment]
Thanks for the prompt response. 

It seems like bt_netfilter wasn't the problem. I thought otherwise, since it wasn't showing up in lsmod. As you said its built-in.

The second part of the issue was a missing "host-local" binary that can be built from github.com/containernetworking/plugins. Now I am able to run the k3s server successfully.

Closing this issue.
