### ISSUE TITLE
Please consider adding "gparted"

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#497]
Gparted is the GNOME Partition Editor for creating, reorganizing, and
deleting disk partitions.  (https://github.com/GNOME/gparted)

It is a very useful utility. I did not find it via "swupd search", so I assume it has not been
ported to Clear OS yet.  AFAIK it is included with every major Linux distribution (Ubuntu, Fedora, CentOS, OpenSUSE)

Gparted is open source. I did not try to build it locally, but I would not expect any 
problems.

**Comment by thiagomacieira** [comment]
We have parted, but not gparted.

**Comment by mdhorn** [comment]
This will be useful for Desktop installs.

**Comment by miguelinux** [comment]
Arjan already add it.

You will see it in the next builds (28100+).

**Comment by jurobystricky** [comment]
Thanks, Gparted is now available in CLR. One complaint though: The program can only be started via CLI, although it is a GUI app. The program needs root privileges, so I had to run it via sudo from command line. I would speculate the bundles misses a polkit file (in  /usr/share/polkit-1 )

**Comment by jurobystricky** [comment]
Thanks Arjan.
With the CLR build 28180 everything works fine.
