### ISSUE TITLE
spyder3 does not render correctly over X

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#5]
When logged into Clear Linux from an X client, running spyder3 does not render correctly.

Almost all GUI apps on Clear Linux render perfectly fine and incredibly fast over X.

**Steps to reproduce:**
1. Install games-dev, python-basic, and openssh-server bundles
2. Install spyder3 from terminal:
`sudo pip3 install spyder`
3. Run spyder3 from Gnome just to see that spyder3 is working
4. Enable X forwarding in sshd and restart:
`sudo bash -c "echo 'X11Forwarding yes' >> /etc/ssh/sshd_config && echo 'X11UseLocalhost no' >> /etc/ssh/sshd_config && systemctl restart sshd"`
5. Connect to Clear Linux from macOS 10.13.2 using XQuartz 2.7.11.
    1. Download and install XQuartz on macOS
    2. Run XQuartz
    3. Open xterm
    4. `$ ssh -X [username]@[clearlinux IP address]`

6. Run Firefox as a test to see that X forwarding is working:
`$ firefox`
7. Run spyder3
`$ spyder3`

**Expected results:**

spyder3 would load and display properly over X.

It works fine in Fedora, Devuan, and Ubuntu.

**Actual results:**

The splash page displays and the main window is drawn but it is blank.

_Screenshots and logs below._

**Attempted Fixes:**

`swupd bundle-add libX11client games-dev os-utils-gui-dev xfce4-desktop`
`pip3 install pyopengl`

**Ideas:**

I think this may be an issue with PyQt pointing to the correct OpenGL library.

Users with Nvidia cards encountering these errors online were helped by pointing their libGL.so to the correct Nvidia-provided libGL.so, doesn't help me, I'm using Intel graphics.

**Attachments:**

**Firefox rendering perfectly from Clear Linux X server on macOS X client:**

<img width="1319" alt="screen shot 2018-01-07 at 1 21 11 am" src="https://user-images.githubusercontent.com/33820650/34647289-45f53f4c-f34d-11e7-8093-d144654d3020.png">

**spyder3 not rendering properly:**

![screen shot 2018-01-07 at 1 10 37 am](https://user-images.githubusercontent.com/33820650/34647301-8b8a8ee0-f34d-11e7-8081-d345986ec48e.png)

<img width="1272" alt="screen shot 2018-01-09 at 2 18 10 pm" src="https://user-images.githubusercontent.com/33820650/34740353-1ce7b196-f54d-11e7-8679-31e0039f6885.png">

**xterm output (log attached below):**

<img width="492" alt="screen shot 2018-01-07 at 1 20 53 am" src="https://user-images.githubusercontent.com/33820650/34647303-9574d780-f34d-11e7-9d2f-a45d73c286c8.png">

**Log output on macOS X client:**

[xterm output log.txt](https://github.com/clearlinux/distribution/files/1609547/xterm.output.log.txt)

**Comment by fenrus75** [comment]
poking at this now (including adding spyder to clear linux)

has this worked elsewhere? ssh forwarding for 3D apps generally works
poorly so will see what is going on

**Comment by sirredbeard** [comment]
Thank you.

X forwarding of spyder3 works well on Fedora and Devuan, previous distros I have used.

Does it need libgl1-mesa-glx or libgl1-mesa-swx11?

Thank you again for your assistance and your super fast Linux distro .

**Comment by ahkok** [comment]
I can't reproduce. Several things to note:

it's `pip3 install spyder` that installs `spyder2`. `pip3 install spyder3` gives: 
```
Collecting spyder3
  Could not find a version that satisfies the requirement spyder3 (from versions: )
No matching distribution found for spyder3
```

but `spider` works fine.

I used `spyder3` directly, as well as over X11 forwarded over ssh (through `ssh -Y localhost` in my case) and in both cases `spyder3` worked correctly.

**Comment by sirredbeard** [comment]
@ahkok 

You are correct about pip3 install spyder, I edited.

I tested with ssh -Y and that failed too.

Is there any way you can test it on two different machines, not through localhost?

Can I ask if you are using Intel or Nvidia video?

Thank you for your help.

**Comment by ahkok** [comment]
Intel gfx in my case.

**Comment by ahkok** [comment]
I can't quickly test from another machine, but the effect should be the same whether you ssh to localhost or somewhere far on the internet - the only difference is network lag.

does `minetest` work for you (games bundle)? That is a good test to see if OpenGL over X11 forwarding is fully functional. If you start a game, you can see in the window title what OpenGL version supported is, as well as get an idea of the supported frame rate. You won't get more than 1fps even over SSH to localhost, and the OpenGL fallback will drop down to version 2.1 as well, but that is to be expected.

I have to also note that we don't have any testing of the OSX X11 display capabilities - we test on ClearLinux and given my reproduction issues, all we can see is that it's fully functional.

**Comment by sirredbeard** [comment]
> but the effect should be the same whether you ssh to localhost or somewhere far on the internet

One would like to think so but with X I think it really needs to be tested.

> we don't have any testing of the OSX X11 display capabilities

macOS X's client, XQuartz, is stable and open source. I have used this specific workflow with spyder3 over X from XQuartz on Ubuntu, Devuan, and Fedora, which leads me to believe it is not an XQuartz issue. 

> we test on ClearLinux

I am going to do some testing from other X clients, including from other ClearLinux.

**Comment by sirredbeard** [comment]
Running minetest over X crashes with similar messages as spyder3. 

[minetest crash log.txt](https://github.com/clearlinux/distribution/files/1613488/minetest.crash.log.txt)

I ran Clear Linux in VirtualBox on macOS and was able to successfully, on the second try, run spyder3 over X on my other Clear Linux machine.

Try 1: 
<img width="829" alt="screen shot 2018-01-08 at 7 08 28 pm" src="https://user-images.githubusercontent.com/33820650/34698824-3db1e428-f4a8-11e7-838b-8fd9a17f7a23.png">

Try 2: 👍
<img width="850" alt="screen shot 2018-01-08 at 7 10 17 pm" src="https://user-images.githubusercontent.com/33820650/34698815-2fc63f30-f4a8-11e7-8824-7f0cbfbfb4d6.png">

I still suspect there is something amiss in the Mesa/OpenGL setup on Clear Linux because none of the other distros I have tried have a problem with spyder3 over X from XQuartz.

**Comment by ahkok** [comment]
The SSH client also comes into play, as it plays an important role in the X11 forwarding process. Since there is the ClearLinux ssh server and the MacOS ssh client, things could be wrong on either end (except it works clear-to-clear).

**Comment by sirredbeard** [comment]
I would agree and generally close this bug, but for the fact X forwarding spyder3 to XQuartz works fine on other major Linux distros, including Fedora, Ubuntu, and Devuan.

Based on people who have reported similar error messages in other situations, I believe it’s an issue in the configuration of Mesa on Clear Linux. Unforuntately 

These error messages seem to be a common problem when Mesa tries to run Intel Mesa drivers on Nvidia or vice-versa. This is not the issue in my situation, but the remedy is simply correcting some soft links. Perhaps that is all that is required here. See: https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t

Here is my output:

sudo ldconfig -p | grep -i gl.so
Password: 
	libwayland-egl.so.1 (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libwayland-egl.so.1
	libwayland-egl.so.1 (libc6,x86-64) => /usr/lib64/libwayland-egl.so.1
	libwayland-egl.so.1 (libc6) => /usr/lib32/libwayland-egl.so.1
	libwayland-egl.so (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libwayland-egl.so
	libwayland-egl.so (libc6,x86-64) => /usr/lib64/libwayland-egl.so
	libwayland-egl.so (libc6) => /usr/lib32/libwayland-egl.so
	libfltk_gl.so.1.3 (libc6,x86-64) => /usr/lib64/libfltk_gl.so.1.3
	libfltk_gl.so (libc6,x86-64) => /usr/lib64/libfltk_gl.so
	libcogl.so.20 (libc6,x86-64) => /usr/lib64/libcogl.so.20
	libcogl.so (libc6,x86-64) => /usr/lib64/libcogl.so
	libQt5OpenGL.so.5 (libc6,x86-64) => /usr/lib64/libQt5OpenGL.so.5
	libQt5OpenGL.so (libc6,x86-64) => /usr/lib64/libQt5OpenGL.so
	libGL.so.1 (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libGL.so.1
	libGL.so.1 (libc6,x86-64) => /usr/lib64/libGL.so.1
	libGL.so.1 (libc6) => /usr/lib32/libGL.so.1
	libGL.so (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libGL.so
	libGL.so (libc6,x86-64) => /usr/lib64/libGL.so
	libGL.so (libc6) => /usr/lib32/libGL.so
	libEGL.so.1 (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libEGL.so.1
	libEGL.so.1 (libc6,x86-64) => /usr/lib64/libEGL.so.1
	libEGL.so.1 (libc6) => /usr/lib32/libEGL.so.1
	libEGL.so (libc6,x86-64, hwcap: 0x0004000000000000) => /usr/lib64/haswell/libEGL.so
	libEGL.so (libc6,x86-64) => /usr/lib64/libEGL.so
	libEGL.so (libc6) => /usr/lib32/libEGL.so

Second, I am wondering if there is maybe a simple software dependency, a GL or QT related one, that may address this, but this is challenging in the bundle approach. That would be an easy fix.

I feel like I am close to cracking this, I just out of my range here.

**Comment by sirredbeard** [comment]
I set export LIBGL_DEBUG=verbose

and

$ spyder3
libGL: OpenDriver: trying /usr/lib64/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/swrast_dri.so
libGL: Can't open configuration file /home/elitebook/.drirc: No such file or directory.
SWR detected AVX 
libGL: Can't open configuration file /home/elitebook/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
SWR destroy screen!
libGL error: failed to load driver: swrast
function is no-op
Unrecognized OpenGL version
Unrecognized OpenGL version
[2543:2572:0109/143753.114773:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
[2543:2572:0109/143753.114804:ERROR:gpu_info_collector.cc(55)] gl::GLContext::MakeCurrent() failed
[2543:2572:0109/143753.114818:ERROR:gpu_info_collector.cc(118)] Could not create context for info collection.
[2543:2572:0109/143754.484964:ERROR:gl_context_glx.cc(240)] Couldn't make context current with X drawable.
[2543:2572:0109/143754.484992:ERROR:gpu_command_buffer_stub.cc(628)] Failed to make context current.


/usr/lib64/dri/swrast_dri.so is there

**Comment by fenrus75** [comment]
if you install the "os-testsuite-phoronix" bundle you sort of get a
superset of all of things....

**Comment by sirredbeard** [comment]
More attempted fixes through trial-and-error testing:

`$ sudo swupd bundle-add os-testsuite-phoronix`
`$ export LIBGL_ALWAYS_INDIRECT=true`
`$ export LIBGL_ALWAYS_SOFTWARE=true`
`$ export LIBGL_DRIVERS_PATH=/usr/lib64:/usr/lib32/dri:/usr/lib32:/usr/lib64/haswell`
`$ sudo chmod 777 /usr/lib64/dri/swrast_dri.so`
`$ export LIBGL_DRI3_DISABLE=true`

Modifying /usr/lib/python3.6/site-packages/spyder/app/start.py as recommended [here](https://github.com/spyder-ide/spyder/issues/3332#issuecomment-254249729).

Installing mesa and libglvnd from Linuxbrew and pointing LIBGL_DRIVERS_PATH=/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3/lib.

My issue appears similar to this one [here](https://www.centos.org/forums/viewtopic.php?t=57840). [This](https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update) is a good example of people receiving other errors who are having issues with their Nvidia graphics. I have Intel graphics. According to Mesa [documentation](https://www.mesa3d.org/egl.html) EGL should work fine with X and libGL DRI.

I may go back and take some logs on Fedora, which this is known to work on.

**Comment by sirredbeard** [comment]
Closing for now.

**Comment by betterze** [comment]
any solution for this problem? I meet similar problem. I use ssh -cx server to conect to sever, create a virtual environment, pip3 install spyder. then i try path/spyder3  (for python3), it output

Unrecognized OpenGL version

However, when i try spyder, which use the system default spyder (python2), it works fine. 

My code is in python3, so i need spyder with python3. And just change python path from version 2 to version 3 cause kernel in spyder. 

Any solution for this?
