### ISSUE TITLE
Wireless networking stops routing when dhcp lease is renewed

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#50]
I infrequently observe a scenario where my wireless network, setup and managed via NetworkManager using the default GNOME desktop, will fail to route any packets.  Everything appears to be normal (i.e. wifi icon shows the system is connected, ifconfig looks normal, etc), but attempting to ping anything fails (raw ip address or using fully qualified name.)

I can recover networking by restarting systemd-networkd.system, but am not seeing anything in the logs that appear fishy with one exception... I think that each time this has happened there was a dhcp lease that has expired, and then eventually I see various systems start to report networking failures.

This isn't much of a bug report given the hard to reproduce nature of the bug, but I suspect other users might feel they need to reboot the system since using the GUI to disconnect and reconnect doesn't seem to help

**Comment by rustylynch** [comment]
I just observed this again, and can confirm it happened when the dhcp lease expired.  Also I was wrong about my statement saying that the turning wireless off and then on again via the NetworkManager applet does not work around the issue.

**Comment by iphutch** [comment]
@mrkz

**Comment by rustylynch** [comment]
Note that am now seeing this multiple times a day, but not always on dhcp refresh.  If nobody else is seeing this then feel free to ask for some specific data to collect to help better understand what is happening.

**Comment by mrkz** [comment]
@rustylynch heya,
I'm not really sure what would be causing this bug, nor how to proceed,

@ahkok, @bryteise  any idea?

**Comment by rustylynch** [comment]
well... for starters perhaps somebody has a better idea of what commands to run to see what is configured incorrectly when the bug is active.  So far I can say that 'route -n' and ifconfig return identical info before and after restarting systemd-networkd.

Also... other then arbitrary services complaining about network timeouts, there isn't a hint of anything wrong from journalctl.

**Comment by bryteise** [comment]
Hrm do you see any changes to your /etc/resolv.conf between before and after restarting? Other things of interest may be under /run/systemd/netif (leases in particular given the dhcp trigger).

**Comment by mrkz** [comment]
@rustylynch does stopping && disabling systemd-networkd helps somehow?

**Comment by rustylynch** [comment]
how should i disable systemd-networkd?

**Comment by rustylynch** [comment]
Ok, I removed the following systemd files:
/usr/lib/systemd/system/multi-user.target.wants/systemd-networkd.service
/usr/lib/systemd/system/systemd-networkd-wait-online.service
/usr/lib/systemd/system/systemd-networkd.service
/usr/lib/systemd/system/systemd-networkd.socket

... and rebooted my laptop early this morning.  My wifi has been working fine all day, and when I look into the logs I can see that the system successfully updated the dhcp release.  So... it appears that disabling systemd-networkd results in reliable wifi connectivity.  I'll keep running this way over the weekend see if this remains true since I don't know if the condition happens 100% of the time that the dhcp lease is renewed

**Comment by mrkz** [comment]
@rustylynch there's no need to `rm` the files on /usr/lib (as a later swud update/fix will bring those back).

you may want to disable the `systemd-networkd` service/socket by masking them
```
$ sudo systemctl mask systemd-networkd.service
$ sudo systemctl mask systemd-networkd.socket
```

This will effectively disable the services while keeping the files in place.

**Comment by bryteise** [comment]
We just made systemd-networkd no longer attempt to manage wifi devices so this should stop being an issue.
