### ISSUE TITLE
Few lines are not executed in 'make' kind files

### ISSUE THREAD

**Issue by venkcy** [clearlinux/distribution#500]
I am trying to make Foam-extend run on Clear Linux environment.

**Describe the bug**
In AllMake file the following lines are not being executed except for the first four lines i.e echo. It does not print anything. The same file works in Ubuntu.

`echo ========================================
echo Starting ThirdParty AllMake: Stage1
echo ========================================
echo

# Gcc 4.4.5 and companion libraries
#
[ ! -z "$WM_THIRD_PARTY_USE_GCC_445" ] && {
    echo "Building gmp-5.0.1 mpfr-3.0.1 gcc-4.4.5"
    ( rpm_make -p gmp-5.0.1   -s gmp-5.0.1.spec  -u http://ftpmirror.gnu.org/gmp/gmp-5.0.1.tar.gz                  )
    ( rpm_make -p mpfr-3.0.1  -s mpfr-3.0.1.spec -u http://ftpmirror.gnu.org/mpfr/mpfr-3.0.1.tar.gz                )
    ( rpm_make -p gcc-4.4.5   -s gcc-4.4.5.spec  -u http://ftpmirror.gnu.org/gcc/gcc-4.4.5/gcc-4.4.5.tar.gz        )
}

`

**Expected behavior**
The above lines are supposed to download the targeted file and install in the local folder.

**Environment (please complete the following information):**
 - Bundles: [`desktop-dev`]
Thank you!

**Comment by thiagomacieira** [comment]
The first line is not an echo. The first line is a conditional. It probably failed.

**Comment by venkcy** [comment]
' **'echo**' was my typographical error. I link you to the actual file through [here](https://github.com/Unofficial-Extend-Project-Mirror/foam-extend-foam-extend-4.0/blob/master/ThirdParty/AllMake.stage1).

The steps to be followed for building the apps are:
1. sourcing the software's bashrc (no definition for rpm_make is defined)
2. building the third party applications.

A gentle reminder regarding the script works fine on Ubuntu.

**Comment by thiagomacieira** [comment]
This line is the conditional:
```sh
[ ! -z "$WM_THIRD_PARTY_USE_GCC_445" ] && {
```

that is checking if the environment variable `WM_THIRD_PARTY_USE_GCC_445` is not empty. If it is empty (or unset), nothing will be run.

**Comment by venkcy** [comment]
Thanks a lot for your time!!! 

I do not know why this is not working in Clear Linux. I have same set of libraries installed in Ubuntu and the script runs as expected.

 In case if you find time, please try to install foam-extend by using [this](https://openfoamwiki.net/index.php/Installation/Linux/foam-extend-4.0/Ubuntu) link and [this](https://openfoamwiki.net/index.php/Installation/Linux/foam-extend-4.0).

**Comment by gvancuts** [comment]
I've not tried this on Clear Linux but I'm pretty sure you'll run into a couple of issues at least:
* `gcc` version, they seem to rely on `gcc-5` (and they even install it on purpose), Clear Linux comes with gcc 8.x
* Qt version. They expect Qt4, Clear Linux provides Qt5
There are specific reasons (mostly security I believe) why Clear Linux has these versions (and only those). Do you know if the upstream project has any ongoing effort to update their dependencies? That is, in my opinion, the best way forward to get this on Clear Linux.

**Comment by venkcy** [comment]
I am able to run the same in ubuntu 16.04 with `gcc` version 5.4. It is hard to for me to state clearly what the problem is as I am not into developing codes. 

Thanks a lot for your time!!!

**Comment by gvancuts** [comment]
> I am able to run the same in ubuntu 16.04 with `gcc` version 5.4. It is hard to for me to state clearly what the problem is as I am not into developing codes.

That's a problem with the upstream package. It requires an old-ish `gcc` (5.4) and it is not available in Clear Linux. The proper course of action would be for the upstream project to support a more modern toolchain.
