### ISSUE TITLE
live beta image is > 8gb USB sticks.

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#503]
The current live beta image doesn't fit on 8.0GB usb sticks. Extracted, the clear-28070-live-desktop-beta.img image is 8589934592 bytes. My fairly standard USB stick has 8011120640 bytes (this is fairly common with USB sticks).

Because the compressed image is only 1.2gb or so, I think the image is created with too much free space, but this is just a guess. Irregardless, this is too large, and prohibitive.

**Comment by ahkok** [comment]
@iphutch

**Comment by mdhorn** [comment]
@ahkok That around 7.46GB; so you're requesting we drop the size of the image to? 7.4GB?

**Comment by ahkok** [comment]
`8000000000` bytes, yes.

**Comment by thiagomacieira** [comment]
Yeah, I lost several hours on this because I failed to notice the hour-long `dd` command had failed (I went for lunch while it ran) and why it had failed.

**Comment by mdhorn** [comment]
So, even setting to 8000000000 might not be sufficient.

```
$ ls -l live-desktop-beta.img
-rw-r--r-- 1 mhorn mhorn 8000000000 Mar  4 13:54 live-desktop-beta.img
```

Finally found an 8GB USB thumb drive.
```
$ sudo dd if=live-desktop-beta.img of=/dev/sdd bs=4M status=progress
5284823040 bytes (5.3 GB, 4.9 GiB) copied, 2 s, 2.6 GB/s
dd: error writing '/dev/sdd': No space left on device
```
Even though it is label 8GB, we see:
```
$ dmesg | grep sdd
sd 10:0:0:0: [sdd] 15278080 512-byte logical blocks: (7.82 GB/7.29 GiB)

$ lsblk -b /dev/sdd
NAME MAJ:MIN RM       SIZE RO TYPE MOUNTPOINT
sdd    8:48   1 7822376960  0 disk
```

**Comment by mdhorn** [comment]
@ahkok Should we set the size to 7800000000 bytes to maximum compatibility?

**Comment by ahkok** [comment]
Your stick is a measly `7822376960` bytes. It seems prudent to put that as the limit, yes.

**Comment by mdhorn** [comment]
The live beta image is now downsized starting with Clear Linux OS release 28210.

```
$ stat clear-28210-live-desktop-beta.img
  File: clear-28210-live-desktop-beta.img
  Size: 7800000000	Blocks: 13045072   IO Block: 4096   regular file
$ ls -lh clear-28210-live-desktop-beta.img
-rw-r--r-- 1 mhorn mhorn 7.3G Mar  8 09:08 clear-28210-live-desktop-beta.img
```
