### ISSUE TITLE
package-utils bundle contains a desktop file without the required executable

### ISSUE THREAD

**Issue by Steinhagen** [clearlinux/distribution#505]
'storage-utils' and 'package-utils' are containing 'redhat-userinfo.desktop' file. The binary used by that desktop file 'userinfo' is not present in CL.

The question is if those bundles should also deliver the binary in question or just remove the desktop file completely.

 - Clear Linux OS version: 28100

**Comment by fenrus75** [comment]
fixing

thanks for the report!
