### ISSUE TITLE
- qemu-guest-agent (qemu-ga) in clear linux -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#507]
I need a new bundler - qemu-guest-agent (qemu-ga) for view more information in QEMU-KVM.

Clear Linux Project - 28100 - 4.20.13-708.native #1 SMP Wed Feb 27 10:09:06 UTC 2019 x86_64 GNU/Linux

Use resource:
 - http://ftp.gnome.org/ubuntu/ubuntu/pool/universe/q/qemu/qemu-guest-agent_3.1+dfsg-2ubuntu2_amd64.deb
I have used the resources in this .deb.
I unzipped and added all them to the system, everything done manually and it works correctly.

systemctl status qemu*
● qemu-guest-agent.service - QEMU Guest Agent
   Loaded: loaded (/usr/lib/systemd/system/qemu-guest-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2019-03-04 11:42:39 EET; 1 day 11h ago
 Main PID: 402 (qemu-ga)
    Tasks: 1 (limit: 4689)
   Memory: 900.0K
   CGroup: /system.slice/qemu-guest-agent.service
           └─402 /usr/sbin/qemu-ga

It would help if I had a bundler. If a system is reinstalled, I could easily install it from the upstream with swupd.

Thank you for your support.

**Comment by ahkok** [comment]
We build it, but it's incorrectly packaged/bundled. It needs to go into the client VM, not on the host side.

**Comment by AntonioMeireles** [comment]
(i _lobbied_ for this already in the [past](https://github.com/clearlinux/distribution/issues/343#issuecomment-451737872) :-) ) shouldn't this be a simple matter of placing it in a separate sub-pkg and then pundling it ? 

Thanks in advance!

**Comment by ionutnechita** [comment]
Can a new package be made?

Thanks in advance!

**Comment by bryteise** [comment]
We are creating a bundle specific to the guest additions. The guest additions pull in ceph though so this is not a small component. Right now we are trying to decide if the kvm kernel should always pull in the additions or if we should just make the kvm image with the additions in them. Thoughts and opinions welcome if you have other ideas too.

**Comment by AntonioMeireles** [comment]
humm...

a) first things first - given that agent's role is to `run inside guests, which communicates
with the host over a virtio-serial channel named "org.qemu.guest_agent.0"` (sic) ceph/rbd is not supposed to be a runtime dep of it all afaict. A quick look elsewhere also does't show (lib)ceph/rbd being a runtime dep of it (the `qemu-guest-agent` sub-pkg) at  all.

b)  regarding what could or should be pulled by default i think that there are two major angles to have in consideration: 
  1. have sensible/predictable defaults 
  2. allow flexibility for power users.

  so, i 'd suggest something along ...

  - tag all kernels able to/reasonably expected to run on top of kvm/qemu with some sort of flag/virtual provide telling that they support running `qemu-guest-agent` pundle. (`qemu-guest-agent` is a bad example as almost everything should be able to run on top of qemu but you get the idea)

  - have a sort of (as hinted by @fenrus75 in IRC yesterday) a (i just made the name) `clr-hardware-profiles` blob which would come with a reasonable set default combos..
(hw -> required bundles)
where hw could be  pciIds, virt env, etc. (a small (yaml based DSL would have to be defined for this) 

  - have `clr-installer` be able to consume above either automatically (when in live/gui mode) or via config (when in mass install one). Regarding the later add the ability to customize the hw profiles via drop-ins in `/etc/` overriding the distro defaults.  

Hope this helps, and have a great weekend!

**Comment by fenrus75** [comment]
we're building exactly this .... (solved the ceph false dependency earlier
this morning)

**Comment by AntonioMeireles** [comment]
> we're building exactly this .... (solved the ceph false dependency earlier this morning)
> […](#)

**THANKS**!

while on the `qemu` topic please consider building it with support for `block-{iscsi,nfs,ssh,curl}` and multipath (`--enable-mpath`).

**Comment by ionutnechita** [comment]
Now I see that the package has been integrated: qemu-guest-additions.
I'll check if everything's fine now.
Thanks for integrating it.

` swupd update
Update started.
Preparing to update from 28340 to 28400
Downloading packs...
        ...0%
Extracting qemu-guest-additions pack for version 28360

Extracting devpkg-attica pack for version 28350

Extracting fontforge pack for version 28360
        ...4%
Extracting lib-imageformat pack for version 28360

Extracting containers-basic pack for version 28400

Extracting cryptography pack for version 28400
        ...5%
Extracting dev-utils pack for version 28360
        ...6%
Extracting devpkg-NetworkManager pack for version 28360

Extracting devpkg-R pack for version 28360
        ...15%
Extracting devpkg-freeglut pack for version 28360
        ...16%
Extracting devpkg-gdk-pixbuf pack for version 28360
        ...17%
Extracting devpkg-gmime pack for version 28400
        ...18%
Extracting devpkg-gobject-introspection pack for version 28360
        ...20%
Extracting devpkg-gst-plugins-base pack for version 28360
        ...21%
Extracting devpkg-harfbuzz pack for version 28360
        ...25%
Extracting devpkg-libX11 pack for version 28350

Extracting devpkg-libXau pack for version 28350
        ...26%
Extracting devpkg-libXdmcp pack for version 28350
        ...27%
Extracting devpkg-libXft pack for version 28360

Extracting devpkg-libXmu pack for version 28360
        ...28%
Extracting devpkg-libXvMC pack for version 28360
        ...33%
Extracting devpkg-libgd pack for version 28350

Extracting devpkg-libgpg-error pack for version 28400
        ...35%
Extracting devpkg-libinput pack for version 28360
        ...39%
Extracting devpkg-libpcap pack for version 28390

Extracting devpkg-librepo pack for version 28400
        ...42%
Extracting devpkg-libsolv pack for version 28390

Extracting devpkg-libssh2 pack for version 28390
        ...44%
Extracting devpkg-libva pack for version 28360

Extracting devpkg-libvirt pack for version 28390
        ...47%
Extracting devpkg-mesa pack for version 28360
        ...53%
Extracting devpkg-pango pack for version 28360
        ...56%
Extracting devpkg-pulseaudio pack for version 28350

Extracting devpkg-qtbase pack for version 28360

Extracting devpkg-qtdeclarative pack for version 28350
        ...57%
Extracting devpkg-qtsvg pack for version 28350

Extracting devpkg-qttools pack for version 28350

Extracting devpkg-rdma-core pack for version 28390
        ...58%
Extracting devpkg-startup-notification pack for version 28350
        ...61%
Extracting devpkg-vala pack for version 28390
        ...63%
Extracting devpkg-xtrans pack for version 28360
        ...69%
Extracting glibc-locale pack for version 28360
        ...70%
Extracting go-basic pack for version 28360

Extracting gpgme pack for version 28400
        ...72%
Extracting inkscape pack for version 28400
        ...75%
Extracting kvm-host-dev pack for version 28360
        ...77%
Extracting lib-opengl pack for version 28360

Extracting lib-samba pack for version 28400

Extracting libX11client pack for version 28360
        ...80%
Extracting mixer pack for version 28360
        ...82%
Extracting network-basic pack for version 28390
        ...83%
Extracting notmuch pack for version 28400
        ...86%
Extracting os-installer pack for version 28380
        ...87%
Extracting package-builder pack for version 28400

Extracting package-utils pack for version 28360
        ...90%
Extracting python-extras pack for version 28360

Extracting python2-basic pack for version 28360

Extracting python3-basic pack for version 28350
        ...91%
Extracting qt-basic pack for version 28350

Extracting qt-core pack for version 28350

Extracting ruby-basic pack for version 28360
        ...92%
Extracting storage-utils pack for version 28390
        ...93%
Extracting strace pack for version 28400
        ...99%
Extracting zip pack for version 28360
        ...100%

Statistics for going from version 28340 to version 28400:

    changed bundles   : 80
    new bundles       : 4
    deleted bundles   : 0

    changed files     : 3713
    new files         : 30005
    deleted files     : 19624

Starting download of remaining update content. This may take a while...
        ...100%
Finishing download of update content...
Staging file content
Applying update
        ...100%
Update was applied.
Calling post-update helper scripts.
none
rngd.service: needs a restart (a library dependency was updated)
clr_debug_fuse.service: needs a restart (a library dependency was updated)
pacdiscovery.service: needs a restart (a library dependency was updated)
tallow.service: needs a restart (a library dependency was updated)
systemd-udevd.service: needs a restart (a library dependency was updated)
klogscanner.service: needs a restart (a library dependency was updated)
pacrunner.service: needs a restart (a library dependency was updated)
systemd-journald.service: needs a restart (a library dependency was updated)
mcelog.service: needs a restart (a library dependency was updated)
systemd-resolved.service: needs a restart (a library dependency was updated)
systemd-timesyncd.service: needs a restart (a library dependency was updated)
Update took 437.7 seconds, 548 MB transferred
4363 files were not in a pack
Update successful. System updated from version 28340 to version 28400
`

**Comment by ionutnechita** [comment]
you can also update the wiki page with the new bundles?
https://clearlinux.org/documentation/clear-linux/reference/bundles

**Comment by ionutnechita** [comment]
I checked it now and everything looks good.
I like how integration has been done. (ConditionVirtualization=kvm)
Everything works very well from the first install now.
I use now: 28460 - 5.0.3-721.native #1 SMP Thu Mar 21 14:42:47 UTC 2019 x86_64 GNU/Linux

Thanks for support.
