### ISSUE TITLE
Can't mount VirtualBox Guest Addition CDROM as user ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#509]
**Describe the bug**
I can't seem to mount the VirtualBox Guest Addition CDROM as the default user 'clrlinux'

**To Reproduce**
1. run the image : https://download.clearlinux.org/image/clear-28100-live-desktop-beta.img.xz
In VirtualBox, until desktop appears
2. Insert VirtualBox GA CD
3. Open the CLR Files Manager
4. We see a CDROM "VBox_GAs_6.0.4"
5. Click on it, a popup appears : 
>Unable to access "VBox_GAs_6.0.4"
>Error mounting /dev/sr0 at /run/media/clrlinux/VBox_GAs_6.0.4: wrong
>fs type, bad option, bad superblock on /dev/sr0, missing codepage or
>helper program, or other error

**Expected behavior**
Expected to see the CDROM contents.
Note that if we mount it manually, in the Terminal as root, it works:
>root@clr-nsauzede-MOBL4 ~ # mount /dev/sr0 /mnt
>mount: /mnt: WARNING: device write-protected, mounted read-only.
>root@clr-nsauzede-MOBL4 ~ # ls /mnt
>AUTORUN.INF  OS2                      VBoxDarwinAdditionsUninstall.tool  VBoxWindowsAdditions.exe
>autorun.sh   runasroot.sh             VBoxLinuxAdditions.run             VBoxWindowsAdditions-x86.exe
>cert         TRANS.TBL                VBoxSolarisAdditions.pkg
>NT3x         VBoxDarwinAdditions.pkg  VBoxWindowsAdditions-amd64.exe

**Screenshots**
See above for error message in the "Expected behavior"

**Environment (please complete the following information):**
 - CLR linux version
>clrlinux@clr-nsauzede-MOBL4 ~ $ cat /usr/lib/os-release
>NAME="Clear Linux OS"
>VERSION=1
>ID=clear-linux-os
>ID_LIKE=clear-linux-os
>VERSION_ID=28100
>PRETTY_NAME="Clear Linux OS"
>ANSI_COLOR="1;35"
>HOME_URL="https://clearlinux.org"
>SUPPORT_URL="https://clearlinux.org"
>BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
>PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles
clrlinux@clr-nsauzede-MOBL4 ~ $ sudo swupd bundle-list
NetworkManager
acpica-unix2
alsa-utils
baobab
bootloader
cheese
clr-installer
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
dosfstools
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
fonts-basic
fuse
fwupdate
gedit
git
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gvim
gzip
htop
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-native
less
libX11client
libglib
libstdcpp
libva-utils
locales
nautilus
network-basic
nfs-utils
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
pmdk
polkit
powertop
pygobject
python3-basic
samba
seahorse
smartmontools
storage-utils
strace
sudo
sysadmin-basic
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
vim
weechat
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
znc
zstd
clrlinux@clr-nsauzede-MOBL4 ~ $

**Additional context**
Running clear-28100-live-desktop-beta.img image in VirtualBox 6.0.4
Important : I'm using CLR native kernel (not lts)

**Comment by bwarden** [comment]
Trying to reproduce, but I strongly recommend using the LTS kernel so you get the Guest Additions drivers in the first place.

**Comment by bwarden** [comment]
Ah, I see this is the live desktop image. Downloading it now.

**Comment by bwarden** [comment]
Suspicious lack of iso9660 here:

```
# udisksctl dump
/org/freedesktop/UDisks2/Manager:
  org.freedesktop.UDisks2.Manager:
    SupportedFilesystems:       ext2
                                ext3
                                ext4
                                vfat
                                ntfs
                                exfat
                                xfs
                                reiserfs
                                nilfs2
                                btrfs
                                minix
                                udf
                                f2fs
                                swap
    Version:                    2.8.1

```

**Comment by bwarden** [comment]
Mount option `iocharset=utf8` is being passed. Removing that option seems to make the mount succeed.

**Comment by bwarden** [comment]
`mount()` syscall is passed:
```
src: /dev/sr0
target: /run/media/clrlinux/VBox_GAs_6.0.4
type: iso9660
flags: 6 (MS_NOSUID | MS_NODEV)
data: "uid=1001,gid=1000,iocharset=utf8,dmode=0500,mode=0400"
```

**Comment by nsauzede** [comment]
@bwarden I once tried the LTS kernel, but remember having screen issues (black screen after VirtualBox session save-restore and/or from standby wakeup
Don't remember clearly; but then I think I never managed to make a "simple" VBox GuestAdd feature like "shared clipboard" (really useful !) so at the end I ditched the LTS in favor to native, which gives me the topmost feature "graphical screen resize" anyway..
BUT, if you tell me how to "activate" the "shared clipboard" feature, I might have a look again at LTS..

**Comment by nsauzede** [comment]
maybe this present issue could be flagged as "bug" ?

**Comment by bwarden** [comment]
Enabled Joliet extensions in native, lts, lts2018, and lts2017 kernels. Tested live desktop image with kernel 4.20.14-710.native and confirmed that Files can now mount and browse the Guest Additions CD.

**Comment by nsauzede** [comment]
Thanks @bwarden !!
