### ISSUE TITLE
ipv6 and log spam (net-pf-10 2, proxy NDP)

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#51]
ipv6 is disabled via kernel parameter (hyperv kernel), so i get a lot of this spam in the logfiles, every second or so
clr: call_modprobe: net-pf-10 2
eth0: Cannot configure proxy NDP for interface: No such file or directory

Is there a way to stop this spam and keep ipv6 disabled? Its rather annoying, since filtering for "warnings and above" shows thousands of those entries per day.

The later seems to-be fixed by https://github.com/systemd/systemd/issues/7612, yet i guess its not in any official release of systemd?

**Comment by mrkz** [comment]
@Andy2244 this apparently was included since systemd v236, Clear Linux* currently ships systemd v234 but upgrading systemd is a WIP. (cc. @ahkok )

**Comment by ahkok** [comment]
Ack, we're working on updating systemd all the way to v238. Big update, much slow.

**Comment by ahkok** [comment]
just a few more days now...

**Comment by bryteise** [comment]
Since the systemd update has happened is this still showing up for you @Andy2244?

**Comment by Andy2244** [comment]
I don't see this one anymore.
`eth0: Cannot configure proxy NDP for interface: No such file or directory`

Yet the moment i start dockerd and some containers that use the internet i get those every 10 seconds or so, resulting in several 100 log entries per day.

```
Jun 19 09:55:54 clear-vm kernel: clr: call_modprobe: net-pf-16-proto-9   2
Jun 19 09:55:54 clear-vm kernel: clr: call_modprobe: net-pf-16-proto-9   2
Jun 19 09:55:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Jun 19 09:55:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Jun 19 09:55:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Jun 19 09:55:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Jun 19 09:55:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
```

I'm on the hyper-v kernel and i don't need ipv6 support, yet if i google for solution's they all try to disable the kernel modules. As far as i understand the issues, its that ipv6 support is enabled, compiled into the kernel and disabled via boot parameter. So i don't want to enable ipv6, so maybe having it as a real module and use the commands below would help?
```
echo alias net-pf-10 off >> /etc/modprobe.conf
echo alias ipv6 off >> /etc/modprobe.conf
```

**Comment by bryteise** [comment]
@bwarden Thoughts on the above?

**Comment by bwarden** [comment]
The aliases should work, but need to be in a file matching /etc/modprobe.d/*.conf (man modprobe.d).

The IPv6 driver does not need to be compiled as a module to support this; we just need to make sure that the aliases resolve to something invalid (e.g. "off") vs. not existing.

**Comment by Andy2244** [comment]
@bwarden Thanks i tried this, but makes no difference, any other ideas?

/etc/modprobe.d/modprobe.conf
```
alias net-pf-10 off
alias ipv6 off
```

**Comment by bwarden** [comment]
Hmmm. It quelled the modprobe messages on a quiescent system when I tried it under Hyper-V, but my environment doesn't currently allow internet access from that VM, so I didn't try anything with dockerd.

**Comment by Andy2244** [comment]
So no other ideas i can try, still getting around ~2000 log entries per day of this warning.

**Comment by bwarden** [comment]
Can you check your config by attempting to modprobe net-pf-10 manually? Just want to make sure you're getting e.g.:
```
modprobe: ERROR: could not find module by name='off'
modprobe: ERROR: could not insert 'off': Unknown symbol in module, or unknown parameter (see dmesg)
```

and not:
```
modprobe: FATAL: Module net-pf-10 not found in directory /lib/modules/4.17.1-578.native
```

**Comment by Andy2244** [comment]
@bwarden Yes, that's what i get:
```
modprobe net-pf-10
modprobe: ERROR: could not find module by name='off'
modprobe: ERROR: could not insert 'off': Unknown symbol in module, or unknown parameter (see dmesg)

```

**Comment by ahkok** [comment]
`man modprobe.d` says to use:

`blacklist modulename`

instead. Please try this.

Also, there's `sysctl` to the rescue:

```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
```

Try this, and if that works, you can put the part after `-w` into a `/etc/sysctl/ipv6.conf` file for instance, and it should work at boot time.

**Comment by ahkok** [comment]
Reading this one more time, it seems we have the fix for the log spam already through `systemd-239` as well. :)

**Comment by Andy2244** [comment]
> Reading this one more time, it seems we have the fix for the log spam already through systemd-239 as well.

@ahkok Not really, i'm on `systemd 239` yet my log still lists 1400-2400 `clr: call_modprobe: net-pf-10 2 ` warnings per day.

```
Aug 16 01:03:24 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:03:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:03:55 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:04:25 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:04:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:04:56 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:05:26 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:05:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:05:56 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:06:26 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:06:56 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:07:26 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:07:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:07:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:07:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:08:27 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:08:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:09:27 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:09:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:09:57 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:10:27 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:10:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:10:58 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:11:28 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:11:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:11:58 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:12:28 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:12:58 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:13:29 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:13:39 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:13:40 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:13:59 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:14:29 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:14:59 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:15:29 clear-vm kernel: clr: call_modprobe: net-pf-10   2
Aug 16 01:15:40 clear-vm kernel: clr: call_modprobe: net-pf-10   2
```

I also see this after a fresh boot:
```
Aug 16 01:00:50 clear-vm dockerd[245]: time="2018-08-16T01:00:50+02:00" level=error msg="failed to disable IPv6 forwarding for container's interface all: open /proc/sys/net/ipv6/conf/all/disable>
Aug 16 01:00:50 clear-vm dockerd[245]: time="2018-08-16T01:00:50.987149601+02:00" level=warning msg="Failed to disable IPv6 on all interfaces on network namespace \"/var/run/docker/netns/0a292ff>
```

The commands above results in:
```
root@clear-vm ~ # sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/all/disable_ipv6: No such file or directory
root@clear-vm ~ # sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl: cannot stat /proc/sys/net/ipv6/conf/default/disable_ipv6: No such file or directory
```

PS: Btw i run a nearly default clear-linux hyper-v version vhdx, so this should be pretty easy to reproduce, but i get the feeling no one actually tried to reproduce this in hyper-v?

**Comment by Andy2244** [comment]
@ahkok I forgot if i asked this, but why is ipv6 disabled via boot option for hyper-v images?

**Comment by miguelinux** [comment]
The hyper-v kernel is used in Microsoft Azure platform, and regrettably
there has some issues with IPv6

On Mon, Sep 17, 2018 at 03:00:03AM -0700, Andy Walsh wrote:
> @ahkok I forgot if i asked this, but why is ipv6 disabled via boot option for hyper-v images? 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/clearlinux/distribution/issues/51#issuecomment-421951581

-- 
Regards,

Miguel Bernal Marin                     Open Source Technology Center
https://clearlinux.org                              Intel Corporation
