### ISSUE TITLE
Mechanics of Sockets

### ISSUE THREAD

**Issue by victorstewart** [clearlinux/distribution#511]
Sorry not a bug but was told to move this question here from "clear-linux-documentation".

When I push say a 10MB packet over a socket… does the process...

A) push the entire packet of data into the operating system, and then move onto other tasks?

or B) feed the 10MB incrementally to the operating system, as requested?

I'm trying to reason about the order in which operations will occur on contentious sockets all managed by the same process.

**Comment by fenrus75** [comment]
it'll get chunked up, buffer size depends on the type of socket (unix vs
tcp vs ... ), usually in range of several to hundreds of Kb

**Comment by victorstewart** [comment]
@fenrus75  okay cool. and the "send" command won't return until all chunks have been pushed by the process into the kernel?

fyi i'm talking TCP sockets

**Comment by fenrus75** [comment]
depends on if you set O_NONBLOCK or not, you can request either behavior

**Comment by victorstewart** [comment]
@fenrus75  amazing. and if I set O_NONBLOCK, I assume the send would instantly return, with there being no way of knowing at that point whether or not the socket was still fully open at the beginning of the attempted transfer? 

Of course if the transfer were to fail halfway through, that's another story.

Also if there a way to send callbacks on success or on failure?

**Comment by ahkok** [comment]
Further reading: `man 2 socket` and note the `SEE ALSO` section!

**Comment by fenrus75** [comment]
https://www.csd.uoc.gr/~hy556/material/tutorials/cs556-3rd-tutorial.pdf
is also a good place to read, it's pretty to the point with many examples

**Comment by ahkok** [comment]
Note that many programming languages have libraries available that abstract and create useful wrappers and methods to handle sockets. Without knowing what you're programming and what language + libraries, it's hard to give more detailed references to good documentation.
