### ISSUE TITLE
- clr-usb2serial access (libftdi) in clear linux -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#514]
I need a new bundler: clr-usb2serial, to use the serial consoles.

Clear Linux Project - 28100 - 4.20.13-708.native #1 SMP Wed Feb 27 10:09:06 UTC 2019 x86_64 GNU/Linux

For manual setup I used:
libFTDI - https://www.intra2net.com/en/developer/libftdi/download.php
libusb - https://github.com/libusb/libusb/releases
libconfuse - https://github.com/martinh/libconfuse/releases
minicom - https://github.com/Distrotech/minicom
picocom - https://github.com/npat-efault/picocom/releases

It would help if I had a bundler. If a system is reinstalled, I could easily install it from the upstream with swupd.

Thank you for your support.

**Comment by puneetse** [comment]
@ionutnechita try the `sysadmin-basic` bundle. It has minicom and screen.

**Comment by Steinhagen** [comment]
> @ionutnechita try the `sysadmin-basic` bundle. It has minicom and screen.
Indeed, but Ionut's request is mentioning a few other indispensable packages for a workstation (libftdi and libusb). There are a number of applications (including some flashing software) that request them.

**Comment by ahkok** [comment]
We have `libusb-1.so` and `libconfuse.so.2` already, but they're hidden or not properly separately bundled. `libftdi` appears to be missing.

Is `picocom` really needed minicom not sufficient? do you really need both?

**Comment by ionutnechita** [comment]
Yes, I need both to test a new environment.

**Comment by fenrus75** [comment]
added a "maker-basic" bundle with a set of these low level usb/serial tools
(they're all tiny and often used together so a joint bundle for these feels
reasonable)

**Comment by ahkok** [comment]
Everything except `picocom` is in.

**Comment by ahkok** [comment]
picocom will be in the same bundle by tomorrow.

**Comment by ionutnechita** [comment]
I tested it now and it seems that everything is in its place.
