### ISSUE TITLE
systemd-localed segfault

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#522]
I saw a problem in dmesg with systemd.
I made the update from 28100 to 28210.
After the restart, these problems arise.

Clear Linux Project - 28210 - 4.20.14-709.native #1 SMP Wed Mar 6 01:01:30 UTC 2019 x86_64 GNU/Linux

```
[    3.995976] systemd-localed[554]: segfault at a ip 00007fdd6e6bec92 sp 00007ffd8147e6d8 error 4 in libc-2.29.so[7fdd6e55d000+178000]
[    3.995988] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
[    4.544886] systemd-localed[696]: segfault at a ip 00007fcf67997c92 sp 00007fffd11faf78 error 4 in libc-2.29.so[7fcf67836000+178000]
[    4.544893] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
```

[defect-systemd.txt](https://github.com/clearlinux/distribution/files/2948255/defect-systemd.txt)

Is there a problem from glibc?

Thank you for your support.

**Comment by bryteise** [comment]
Hrm so that release window saw a new systemd and a new compile option to glibc so that'll be fun to track down. @ahkok I'll try and narrow the window from the glibc side and reproduce.

**Comment by ahkok** [comment]
Can you share what specific keyboard and locale settings you have on your system?

**Comment by ionutnechita** [comment]
locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL

**Comment by ionutnechita** [comment]
LC_ALL= <<<< is empty

**Comment by ahkok** [comment]
I assume you accidentally cut and pasted incorrectly and left out the `=` there.

```
$ locale | grep LC_ALL
LC_ALL=
```

**Comment by ahkok** [comment]
Oh, just running `localectl` crashes it.

**Comment by ionutnechita** [comment]
`[    3.247874] initcall fuse_init+0x0/0x1b1 [fuse] returned 0 after 122 usecs
[    3.805634] systemd-localed[549]: segfault at a ip 00007fe64ad96c92 sp 00007fffb5a35208 error 4 in libc-2.29.so[7fe64ac35000+178000]
[    3.805646] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
[    4.343897] systemd-localed[695]: segfault at a ip 00007fa08bef8c92 sp 00007fffa7c754c8 error 4 in libc-2.29.so[7fa08bd97000+178000]
[    4.343908] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
[ 2712.046642] systemd-localed[1034]: segfault at a ip 00007f863fe6dc92 sp 00007ffd65715d08 error 4 in libc-2.29.so[7f863fd0c000+178000]
[ 2712.046649] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
[ 2715.072669] systemd-localed[1101]: segfault at a ip 00007f8bd6c92c92 sp 00007ffdcaa531d8 error 4 in libc-2.29.so[7f8bd6b31000+178000]
[ 2715.072676] Code: ff ff e9 21 46 f3 ff 90 f3 0f 1e fa 89 f8 31 d2 c5 c5 ef ff 09 f0 25 ff 0f 00 00 3d 80 0f 00 00 0f 8f 52 03 00 00 c5 fe 6f 0f <c5> f5 74 06 c5 fd da c1 c5 fd 74 c7 c5 fd d7 c8 85 c9 74 7a f3 0f
`
localectl
Could not get properties: Message recipient disconnected from message bus without replying

cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28230
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

4.20.14-710.native #1 SMP Thu Mar 7 22:16:36 UTC 2019 x86_64 GNU/Linux

**Comment by ahkok** [comment]
I think I have root caused this crash to a clearlinux specific patch (`0039`) that includes a problematic extra `va_args` entry that is invalid.

**Comment by ahkok** [comment]
`systemd-241-230`

**Comment by ionutnechita** [comment]
is ok now,
thanks for support.
