### ISSUE TITLE
Something wonky with X libraries

### ISSUE THREAD

**Issue by eero-t** [clearlinux/distribution#523]
I noticed this while investigating what could cause issues with Git built version of XWayland + Weston.

All the libraries have reasonable dates, except (nearly hundred files related to) X11 libraries that are from the last century:
```
$ ls -l /lib64/ | grep ' 19[7-9][0-9] ' 
-rw-r--r--  76 root root        19 Nov 11  1974 libICE.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libICE.so.6
-rw-r--r--  76 root root        19 Nov 11  1974 libSM.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libSM.so.6
-rwxr-xr-x   1 root root   2835520 Nov 11  1974 libX11.so.6.3.0
-rw-r--r--  76 root root        19 Nov 11  1974 libX11-xcb.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libX11-xcb.so.1
...
-rw-r--r--  76 root root        19 Nov 11  1974 libXext.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXext.so.6
-rw-r--r--  76 root root        19 Nov 11  1974 libXfixes.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXfixes.so.3
-rw-r--r--  76 root root        19 Nov 11  1974 libXinerama.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXinerama.so.1
-rw-r--r--  76 root root        19 Nov 11  1974 libXi.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXi.so.6
-rw-r--r--  76 root root        19 Nov 11  1974 libXrandr.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXrandr.so.2
-rw-r--r--  76 root root        19 Nov 11  1974 libXrender.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXrender.so.1
-rw-r--r--  14 root root        19 Nov 11  1974 libxshmfence.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libxshmfence.so.1
-rw-r--r--  76 root root        19 Nov 11  1974 libXxf86vm.so
-rwxr-xr-x   1 root root     13992 Nov 11  1974 libXxf86vm.so.1
```

Are these libraries up to date?  (I'm seeing warning from git-built XCB, that ext would be out of date.)

What are the real version of the libraries?   ClearLinux X libraries show only the first version number, whereas e.g. on Ubuntu, one sees all three version numbers:
```
$ ls -l /usr/lib/x86_64-linux-gnu/libXext.so.*
lrwxrwxrwx 1 root root    16 touko  2  2018 /usr/lib/x86_64-linux-gnu/libXext.so.6 -> libXext.so.6.4.0
-rw-r--r-- 1 root root 73640 loka  25  2014 /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
```

It's also somewhat weird to see these instead of symlinks:
```
$ cat /lib64/libXext.so
INPUT(libX11.so.6)
```
When other ClearLinux libraries use symlinks.

**Comment by ahkok** [comment]
This is due to our X11 library combining all of these sub components into one, which saves significant runtime resources. All the code sits in libX11.so I think @fenrus75 can explain it better.

**Comment by thiagomacieira** [comment]
The dates are because someone forgot a digit in the .spec file, but @fenrus75 fixed it in https://github.com/clearlinux-pkgs/libX11/commit/eee9b6fe18cc819b8123002bab04826caf926f92:
```diff
-export SOURCE_DATE_EPOCH=153420600
+export SOURCE_DATE_EPOCH=1552311600 
```

There's nothing wrong with the libraries. They are wonky, yes.

Are you experiencing problems?

**Comment by eero-t** [comment]
> This is due to our X11 library combining all of these sub components into one, which saves significant runtime resources. All the code sits in libX11.so I think @fenrus75 can explain it better.

Hm. Library files without SO version should required just for building things, so this should be mostly just an issue for things like libtool, CMake, Meson, SCons etc.

I assume that any advantages require binaries to be linked with build files that have been modified to link just libX11 instead of the extra ones. And I do see that all those 1974 dated library files link only libX11 (even XCB ones).

However, something like libQtGui links several of those, so either applying the required build changes hasn't been automated, or that doesn't work fully yet:
```
$ ls -l /lib64/*.so | awk '/ 1974 / {print $9}' | xargs head -1 | grep INPUT | sort | uniq -c
     45 INPUT(libX11.so.6)
$ for i in $(ls -l /lib64/*.so.* | awk '/ 1974 / {print $9}'); do ldd /lib64/libQt5Gui.so.5.12.1 | grep $i; done
	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f7662b74000)
	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f35d80a2000)
	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f385837b000)
	libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f8c608cf000)
	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f78c3fef000)
	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f128f18f000)
	libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f72ad16b000)
	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f781929d000)
```

As to how much gets saved... Saving from combining things to same binary is less than 4K page for each Section in each Library linked to each running Applications (<4K x S x L x A), but most of them link only some of libs.  For ten libraries linked to dozen apps, total saving would be something like 1-2MB of RAM, when *all* the dependent libs get built so that they don't anymore pull those extra libs (like Qt above would do).  It's a clear saving, and was once significant, but not very dramatic anymore, when even phones have >1GB of RAM. :-)


> There's nothing wrong with the libraries.

Besides dates, could the full library version be added to library names like on other distros, so that one can easily see what version they are (as ClearLinux "swpud" is still unable to report that)?

For example, is "libxcb.so.1" v1.1.0, or v1.0 of libxcb?


> Are you experiencing problems?

Yes, but it's probably self inflicted, as I'm running gfx stack built completely  (kernel, weston, X server, Mesa and few deps) from Git in Ubuntu 18.04 on ClearLinux.  Using Ubuntu built binaries on ClearLinux has always (> year) worked fine, but it could be just good luck.

(If we'll get an actual need for ClearLinux and swupd becomes more reasonable, we'll start doing separate builds for ClearLinux, but for now it's not worth the trouble.)

As to my problem: After running (windowed) GpuTest v0.7 tests, some other (fullscreen) 3D tests fail.  These are all X based tests run under Weston with XWayland.  They had worked fine [1] until sometime end of last month.  On quick testing, that combo still works OK with Ubuntu, but it's a bit sporadic issue, so I can't be yet sure whether it's ClearLinux run-time vs. Ubuntu build environment issue, or actual upstream breakage.  At least X server itself didn't have any relevant looking changes around that time [2].

[1] Except for this Weston / XWayland bug that has been there "always": https://bugs.freedesktop.org/show_bug.cgi?id=106734

[2] "Traditionally" X has broken yearly some library ABI without ever updating corresponding library so-version (without any notes in relevant changelogs either), but with X updates slowing down, that hasn't happened for a while.

**Comment by fenrus75** [comment]
Saving from combining things to same binary is less than 4K page for each
Section in each Library linked to each running Applications (<4K x S x L x
A), but most of them link only some of libs.

that's not actually the whole truth, there's also a kernel side cost
(pagetables etc) and cost of missed LTO.. we've measured roughly 28Kb-ish
per lib.
times about a dozen per app times nr of processes...

**Comment by fenrus75** [comment]
as to your bug, we've had this setup for quite a bit longer than when you
say you started seeing issues so more than likely unrelated

**Comment by thiagomacieira** [comment]
> However, something like libQtGui links several of those, so either applying the required build changes hasn't been automated, or that doesn't work fully yet

It requires rebuilding to make use of the linker scripts in the form of .so files and we haven't performed a full system rebuild since we added this feature. I thought we'd rebuilt qtbase (where QtGui library comes from), but it's equally possible it's coming from an indirect dependency that hasn't been rebuilt. I'll investigate tomorrow, after the Qt 5.12.2 release, as I'll have to rebuild anyway.

> Besides dates, could the full library version be added to library names like on other distros, so that one can easily see what version they are (as ClearLinux "swpud" is still unable to report that)?

I'll take a look. It's just one big shell script, so we should be able to `readlink` and use the actual upstream names. As for getting actual version numbers in somewhere centralised, it's in our backlog. `--version` doesn't work for libraries (actually, it does, but only two libraries do that, `libc.so.6` and `libQt5Core.so.5`).

**Comment by eero-t** [comment]
Thanks Thiago!   I guess this could be kept open until X libs & Qt have been updated.

(LTO was good point about perf, I forgot that you're applying LTO so widely.)

**Comment by thiagomacieira** [comment]
Those libraries are empty, so they don't cause a problem. Removing their loading is just a performance improvement, not a bug fix.

**Comment by eero-t** [comment]
I meant: keeping this open until X11 library dates are correct and they have full version numbers, to avoid confusing users, which was the reason why I originally filed this ticket.  Qt loading being more optimal is just a nice non-user-visible  bonus.

**Comment by thiagomacieira** [comment]
The library dates are correct now, after the commit I pointed out. The full soname will be a best-effort basis.

**Comment by eero-t** [comment]
> The library dates are correct now, after the commit I pointed out.

Thanks!   INPUT() files are still old though:
```
$ ls -l /lib64/* | grep ' 19[7-9][0-9] '
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libICE.so
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libSM.so
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libX11-xcb.so
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libXau.so
...
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libXrender.so
-rw-r--r--  14 root root        19 Nov 11  1974 /lib64/libxshmfence.so
-rw-r--r--  76 root root        19 Nov 11  1974 /lib64/libXxf86vm.so
lrwxrwxrwx 2 root root       15 Nov 11  1974 libX11.so -> libX11.so.6.3.0
lrwxrwxrwx 2 root root       15 Nov 11  1974 libX11.so.6 -> libX11.so.6.3.0
```

> The full soname will be a best-effort basis

Sure.  Any improvements are appreciated!

> Qt loading being more optimal is just a nice non-user-visible bonus

To get the benefit, also applications need to be recompiled, not just Qt & other libs using X stuff.  Out of curiosity, do you keep any kind of statistics about when components in ClearLinux disto have last been built?

**Comment by thiagomacieira** [comment]
I'll take a look at the dates, but all files in the package should have got the same dates...

> To get the benefit, also applications need to be recompiled, not just Qt & other libs using X stuff.

Only if they link directly against those libraries. Most Qt applications don't.

**Comment by fenrus75** [comment]
we've had this for several months now, most of our GUI stuff has been
recompiled since.
