### ISSUE TITLE
swupd cannot load libsystemd.so.0 in CL docker image versions above 28140 (incl.)

### ISSUE THREAD

**Issue by DnPlas** [clearlinux/distribution#524]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
After building a docker image based on Clear Linux that updates itself to a version above 28140, 'swupd' fails asking for systemd library.

**To Reproduce**
1.  (host machine) $ docker run --rm -ti clearlinux
2.  (inside the container) $ swupd update -m 28140
3.  (host machine) $ docker commit $container-id  
4. (host machine) docker run -it $new-container-id /bin/bash
5. (inside the container) $ swupd info

**Expected behavior**
swupd will display the CL installed version
 **Actual behaviour**
You'll get the following error message:
swupd: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory

**Comment by ahkok** [comment]
try running `sudo ldconfig`

**Comment by bryteise** [comment]
We have a fix for the next docker image we push to dockerhub if it is a problem with ldconfig like I'm hoping.

**Comment by DnPlas** [comment]
Error is not present in CL ver 28420 anymore.

**Comment by bryteise** [comment]
Yay, thanks!

**Comment by DnPlas** [comment]
Thank you @bryteise !

**Comment by analytically** [comment]
Seeing this as well when building the Redis image using Concourse CI (runc)
