### ISSUE TITLE
OpenCL loader library does not find the installed ICD files

### ISSUE THREAD

**Issue by eero-t** [clearlinux/distribution#525]
```
# swupd search beignet
Bundle with the best search result:
     os-testsuite-phoronix          	- Run the Phoronix testsuite 

This bundle can be installed with:

  swupd bundle-add  os-testsuite-phoronix

Alternative bundle options are
     os-testsuite-phoronix-desktop  	- Run the Phoronix testsuite (desktop version)  (376Mb) 
     machine-learning-basic         	- Build machine learning applications  (618Mb)
     dev-utils-dev                  	- All packages required to build the dev-utils bundle

# swupd bundle-add machine-learning-basic
...
# find /etc/ -iname '*beignet*'
# 
```
ICD file tells the OpenCL API library which backends are available and where they are.  Without it, programs don't know that there's OpenCL implementation available.

Basd on Ubuntu and Fedora beignet package contents, ICD file should go to /etc/OpenCL/vendors/:
https://rpmfind.net/linux/RPM/fedora/29/x86_64/b/beignet-1.3.2-5.fc29.x86_64.html

But according to strace on a program using OpenCL, ICD file is searched from: /usr/share/OpenCL/vendors/

(Vulkan ICD file also goes to /share/.)

Additionally, "clinfo" program to check OpenCL implementation details, isn't in any reasonable bundle, but in:
```
$ clinfo
clinfo: command not found
To install clinfo use:  sudo swupd bundle-add os-testsuite-phoronix-server
```

**Comment by ahkok** [comment]
Unfortunately we can't install files into `/etc/OpenCL/vendors/` as it violates our standards.

**Comment by ahkok** [comment]
Even worse, this currently compile anymore. @seanvk may know what we can do about this, perhaps.

**Comment by eero-t** [comment]
> Unfortunately we can't install files into `/etc/OpenCL/vendors/` as it violates our standards.

The place where the current OpenCL API loader/dispatcher searched for it,  /usr/share/OpenCL/vendors/, is IMHO fine.  The main thing is that there *is* an ICD file that points the loader to the right backend library.

**Comment by ahkok** [comment]
Well right now we can't build beignet at all in clearlinux, so we need someone to fix it up. Until then, we're unlikely to be able to address the issue here.

**Comment by ahkok** [comment]
@chivakker can maybe comment

**Comment by seanvk** [comment]
Beignet  preliminary support for llvm7 but as soon as llvm8 lands it will tank again.  It was building before with llvm7.  @chivakker do you have time to have a look?
ICD will also be necessary if Clover and NEO support is added to differentiate runtime backends.

**Comment by chivakker** [comment]
@eero-t, could you consider using computer-vision-basic bundle and see if it can help your needs.  You may be able to use compute-runtime (NEO) instead.

**Comment by eero-t** [comment]
> @eero-t, could you consider using computer-vision-basic bundle and see if it can help your needs. You may be able to use compute-runtime (NEO) instead.

This bug isn't about specific backend.   Regardless of which OpenCL HW acceleration backend gets installed, it should work out of the box on supported HW.  I.e. its ICD config file should be in correct place, so that OpenCL loader knows about the driver, can load it, and  the OpenCL programs work (without user needing to fix ClearLinux first).

You can test easily whether this is fixed.  Just install a bundle pulling in OpenCL GPU driver, and run "clinfo".  Does it work?

**Comment by fenrus75** [comment]
$ clinfo
Number of platforms                               1
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1
  Platform Profile                                FULL_PROFILE


on my core i7 machine.

(and strace on clinfo shows it's looking correctly in /usr/share for the files)

**Comment by eero-t** [comment]
My only ClearLinux device was busy so I couldn't test this earlier, but this indeed seems to be fixed:
```
$ strace -f -e openat clinfo 2>&1 | grep icd
openat(AT_FDCWD, "/usr/share/OpenCL/vendors/intel.icd", O_RDONLY) = 4</usr/share/OpenCL/vendors/intel.icd>
openat(AT_FDCWD, "/usr/share/OpenCL/vendors/intel-beignet.icd", O_RDONLY) = 4</usr/share/OpenCL/vendors/intel-beignet.icd>
$clinfo | grep -e Number -e Platform -e Version
...
Number of platforms                               2
...
  Platform Name                                   Intel(R) OpenCL HD Graphics
  Device Version                                  OpenCL 1.2 NEO 
  Driver Version                                  1.0.0
  Device OpenCL C Version                         OpenCL C 1.2 

  Platform Name                                   Intel Gen OCL Driver
  Device Version                                  OpenCL 2.0 beignet 1.4
  Driver Version                                  1.4
  Device OpenCL C Version                         OpenCL C 2.0 beignet 1.4
```
(Interestingly Beignet can offer on this device (APL/BXT) OpenCL 2.0, while newer NEO driver only 1.2, so it's good to ship also the older driver for older platforms.)

-> Closing.

PS. According to crl-bundles git repo, "beignet" comes due to "machine-learning-basic" bundle, "clinfo" due to "computer-vision-basic" bundle, but what pulls in the NEO driver?
```
$ head /usr/share/OpenCL/vendors/*
==> /usr/share/OpenCL/vendors/intel-beignet.icd <==
/usr/lib64/beignet/libcl.so
==> /usr/share/OpenCL/vendors/intel.icd <==
/usr/lib64/intel-opencl/libigdrcl.so
$ swupd search libigdrcl.so
Search failed, no reasonable results found
```

**Comment by eero-t** [comment]
Answering myself... "computer-vision-basic" bundle pulls also in "intel-compute-runtime" and "hardware-gpu" pulls in "intel-graphics-compiler" needed by it.
