### ISSUE TITLE
Having both CONFIG_KVM_INTEL and CONFIG_KVM_AMD will cause an error

### ISSUE THREAD

**Issue by ltsdw** [clearlinux/distribution#526]
**Describe the bug**
Compiling the kernel with CONFIG_KVM_INTEL and CONFIG_KVM_AMD enabled will produce the error `kvm: already loaded the other module` on boot start up.

**To Reproduce**
1. Compile and install the kernel
2. Reboot
3. Select the entry for the kernel on grub and start

**Expected behavior**
Start system without error `kvm: already loaded the other module`

**Additional context**
As said on gentoo's documentation this error is due to both CONFIG_KVM_INTEL and CONFIG_KVM_AMD being enabled:
 https://wiki.gentoo.org/wiki/QEMU#.22kvm:_already_loaded_the_other_module.22

Recompiling only with respective option for my processor resolved the error.

**Comment by iphutch** [comment]
@miguelinux @fenrus75 @bwarden  Can we make these live side-by-side properly without stepping on each other?

**Comment by bwarden** [comment]
Changed `CONFIG_KVM_AMD` to `m` in kernel `5.0.1-716.native` to allow more graceful fallback, consistent with the other kernel packages we distribute.

**Comment by ahkok** [comment]
+1, that seems reasonable since CONFIG_KVM_INTEL=y and therefore loads 1st. Did anyone confirm that makes the message disappear, though? And that this doesn't give issues on AMD platforms?

**Comment by bwarden** [comment]
I can confirm that it does make the message disappear, however, I have no AMD platform on which to test.
