### ISSUE TITLE
Kubeadm preflight checks fails using kernel 5.0

### ISSUE THREAD

**Issue by chuyd** [clearlinux/distribution#528]
Kubeadm can not be initialized using the latest clearlinux image (28280), the current kubeadm version 1.13.4 does not support the kernel 5.0. According to the kubernetes [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md) this issue was fixed on the version 1.14:  ```kubeadm: Do not fail preflight checks when running on >= 5.0 Linux kernel (#74355, @brb)```, this issue should be fixed by updating the kubernetes version.

**Steps to reproduce the behavior:**
1. ```kubeadm init --pod-network-cidr=10.244.0.0/16```

**Expected behavior**
Kubeadm deploys a kubernetes master node

**Environment**
 - Clear Linux OS version: 28280
 - Bundles: cloud-native-basic

**Additional context**
Error output:
```"cmd": "kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt", "delta": "0:00:02.396706", "end": "2019-03-13 17:16:50.983872", "msg": "non-zero return code", "rc": 1, "start": "2019-03-13 17:16:48.587166", "stderr": "error execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR SystemVerification]: unsupported kernel release: 5.0.1-312.kvm\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`", "stderr_lines": ["error execution phase preflight: [preflight] Some fatal errors occurred:", "\t[ERROR SystemVerification]: unsupported kernel release: 5.0.1-312.kvm", "[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`"], "stdout": "", "stdout_lines": []}```

**Comment by obedmr** [comment]
Same issue here.

**Comment by bryteise** [comment]
@mythi it seems like we need to update our k8s stack again. @abecastillo just a mention here as this seemed to be something that escaped validation.

**Comment by AntonioMeireles** [comment]
fwiw 1.14 is  not out yet... and this should be fixed in 1.13.5 out soon too.

as a general rule it may make sense to bind kube tooling to lts kernels

**Comment by bryteise** [comment]
@AntonioMeireles I was thinking that too, at the very least making the kube tooling suggest using the lts kernels when initializing the cluster.

**Comment by thiagomacieira** [comment]
You'd think people would know the kernel changes major version numbers every 3 years by now. And as I can see from the patch, we'll have the same problem in 6.0 again.

**Comment by miguelinux** [comment]
@chuyd @obedmr 

Can you test in the next public release.

`kubernetes-1.13.4-65`

**Comment by obedmr** [comment]
@miguelinux sure, will test it in the next Clear Release. thanks

**Comment by abecastillo** [comment]
> @mythi it seems like we need to update our k8s stack again. @abecastillo just a mention here as this seemed to be something that escaped validation.

@bryteise ack. proper validation is WIP and should be in place soon.

**Comment by iphutch** [comment]
@mythi has reported as fixed. @abecastillo please confirm testing is in place so we can close.

**Comment by hnanni** [comment]
the reported issue is fixed. A test is in place running along CLR releases.

**Comment by iphutch** [comment]
Thank you @hnanni
