### ISSUE TITLE
Wired issue with network

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/distribution#53]
Seeing this running swupd update 

Oh btw I can go out to internet with no problem...but this damn thing is not going today....
`
swupd-client software update 3.15.5
   Copyright (C) 2012-2018 Intel Corporation

Error: Network issue, unable to proceed with update

Raw elapsed time stats:
251.2421        ms: Main Update

`

**Comment by Venomtek** [comment]
Glad I'm not the only one.
When I curl https://download.clearlinux.org/update/ I get an error.

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

disclaimer: Just installed CLP for the first time, love it, no clue what i'm doing. 

>:D

**Comment by unixbhaskar** [comment]
Thanks for the heads up. But I prefer to wait , as I know to use the insecure stuff. I want Intel to fix the damn thing and let us do the thing normally. I can not take the risk of their stupidity.

**Comment by Venomtek** [comment]
![image](https://user-images.githubusercontent.com/38853779/39422877-347f41ba-4c24-11e8-8d07-4c14c69188bd.png)

**Comment by unixbhaskar** [comment]
@VictorRodriguez  Hey Victor, can you please check ...what is going on? It seems you, people, to generate new cert and bind with that subdomain. It's impacting the end users.

**Comment by VictorRodriguez** [comment]
@unixbhaskar we are working on, as soon as we ( me and @bryteise ) has a solution , let you know :)

**Comment by VictorRodriguez** [comment]
@unixbhaskar you should see this issue fixed now, thanks for the report and sorry for inconvenience

**Comment by ahkok** [comment]
FTR, in case this happens again in the future, we don't want you to try and work around this type of issue, that would make you insecure. You were correct to say that this needed to be fixed on our end.

**Comment by Venomtek** [comment]
1up!
