### ISSUE TITLE
Build Samba with CTDB/Cluster Support

### ISSUE THREAD

**Issue by trystan-s** [clearlinux/distribution#535]
**Is your feature request related to a problem? Please describe.**
Currently the Samba package isn't built with cluster support ( CTDB ) to allow highly available clustered/distributed fileshares. 

**Describe the solution you'd like**
https://wiki.samba.org/index.php/Getting_and_Building_CTDB#Building_from_source_code

building with `--with-cluster-support` option

**Describe alternatives you've considered**
CephFS is available but no Windows Client exists (samba gateway needed)

**Additional context**
CTDB binary should also be searchable via `swupd search -b ctdb` and lead to samba bundle.

Example of HA Samba via CTDB

```
user@host:~$ sudo ctdb status
Number of nodes:2
pnn:0 172.16.8.1      OK
pnn:1 172.16.8.2     OK (THIS NODE)
Generation:1351455964
Size:2
hash:0 lmaster:0
hash:1 lmaster:1
Recovery mode:NORMAL (0)
Recovery master:0
```

**Comment by puneetse** [comment]
I'm closing this because the samba package has since been changed to build with the required flags for cluster support: https://github.com/clearlinux-pkgs/samba/blob/master/configure#L9-L10

Please let us know if there are any other issues!
