### ISSUE TITLE
Atom update from 1.32.1 to 1.35.1

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#540]
**List the package you would like to see updated**
The `atom` package version 1.32.1 (2018-10-31) has been updated to 1.35.1 (2019-03-13). [Tarball for current release](https://github.com/atom/atom/releases/tag/v1.35.1).

**Does this update provide any significant new features that may be needed**
There are about [4 months of bug fixes and improvements](https://atom.io/releases), and some plugins require the latest release.

**Comment by ahkok** [comment]
Done! will be out shortly in an update.
