### ISSUE TITLE
- ruby update from 2.4.5 to 2.6.2 ( new stable release ) in clear linux -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#543]
Clear Linux Project - 28340- 5.0.2-717.native #1 SMP Wed Mar 13 23:07:41 UTC 2019 x86_64 GNU/Linux

swupd bundle-add ruby-basic
ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux-gnu]

I see you have an old stable version.
Do you think you can use the latest stable version? in ruby-basic bundle

**Comment by bryteise** [comment]
Updating, do you prefer to use the system ruby for most things or do you use things like rbenv to get specifically what versions you want?

**Comment by ionutnechita** [comment]
I use ruby for more things.
But do not use rbenv or rvm, is harder to configure.
I would like to use only what is native.

**Comment by bryteise** [comment]
Okay, cool. That's pretty much how I use python. We haven't had much ruby use in Clear Linux so please keep requesting ruby content you find helpful.

**Comment by bryteise** [comment]
Update to ruby is in our build system, should be in Monday's release.
