### ISSUE TITLE
GDM does not support Wayland sessions

### ISSUE THREAD

**Issue by ferrucciof** [clearlinux/distribution#544]
Starting with release 61 (commit df6d76a: January 11, 2019), GDM package is built without Wayland support (--enable-wayland-support=no), therefore it only lists X.Org and Fallback sessions.

What it the reason for this?
Since Clear Linux does have a Wayland package, how is a GNOME user supposed to start a Wayland session?

So far, I just rolled back to /usr/bin/gdm from release 60 and Wayland starts perfectly on my hardware.

**Comment by thiagomacieira** [comment]
Yes, we've been having problems with GNOME's Wayland compositor and were getting too many reports from users, so we decided to turn it off to let upstream mature it a little more.

The problem is not Wayland itself, so we allowed it and Weston to remain.

**Comment by OpenSourceAnarchist** [comment]
I would rather have the option available than no option at all. Guess KDE Plasma's Wayland session should be disabled too, then (but hopefully not). I have always had a better experience on GNOME's Wayland desktop than Plasma's.

**Comment by ferrucciof** [comment]
What about building GDM with Wayland support, but shipping it with a configuration that disables Wayland sessions by default, e.g. `WaylandEnable=false` in `/etc/gdm/gdm.conf`?
This should cut down on bug reports, at least from unexperienced users that are not familiar with config files.

I think that GNOME is putting a lot of development effort on Wayland; having it hard-disabled this way (no possibility to bring it back, unless rebuilding GDM yourself) feels a bit sad.

**Comment by trystan-s** [comment]
Considering fractional display scaling that landed recently is only available via Wayland I'd second @ferrucciof in the default disable but allowing an override via .conf.

Building GDM without wayland support seems a little harsh.

**Comment by ferrucciof** [comment]
I noticed that Wayland support was enabled on March 18 (release 69, commit 1da9eca) and then disabled again only 4 days later (release 70, commit 3ed6747).

Weird... But at least I could update Clear Linux, then roll back /usr/bin/gdm to release 69 (instead of 60) and enjoy Wayland with GNOME 3.32.0! Fractional scaling works, too.

**Comment by blitzprog** [comment]
I would also love to try Clear Linux + Wayland + GDM, at least to check how it would perform. Having it simply disabled by default seems to make sense.

**Comment by fenrus75** [comment]
I've made some tweaks to make gdm more robust

we're trying wayland again now for a few days, but if we get the same slew of "now nothing works" reports we're going to have to turn it off again ;(

**Comment by ferrucciof** [comment]
GDM has had Wayland support enabled for about 45 days, so I guess it is time to close this issue ;)

Thank you for your great support, the speed with which you react to user requests is really amazing!
