### ISSUE TITLE
Gnome: Can't Use Custom Image for Avatar

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#545]
**Describe the bug**
In Gnome System Settings, I'm unable use a custom image for my profile picture.

**To Reproduce**
1. Visit System Settings > Details > Users
2. Click on your profile pic / avatar
3. Choose "Select a file ..."
4. Browse to any image and select it
5. "Open" is greyed out and I am unable to double-click an image to open it

**Expected behavior**
Once I select an image, it should allow me to open it, which would then allow me to use this image as my profile picture.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]
It's in a VM, I'll provide this later.

**Additional context**
This has been around for some months, but I'm only just getting around to reporting it.

**Comment by ahkok** [comment]
@mrkz @AthenasJimenez 

I can confirm. "file open" dialog shows, but you can never click "open" to finalize the selection.

**Comment by AthenasJimenez** [comment]
Working on this, already make it works so I'll push the patch in the coming days.

**Comment by AthenasJimenez** [comment]
Fix pushed, should be available by the end of the day.

**Comment by pceiley** [comment]
Great. Thanks!

**Comment by AthenasJimenez** [comment]
No problem!

Release with Fix: 28490
Patch: [gnome-desktop](https://github.com/clearlinux-pkgs/gnome-desktop/commit/bd1787b936975ad418fc0007a6e5f060984e6f0c)
