### ISSUE TITLE
Kata-runtime has OCI  runtime error after update from  28300 to 28310

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#547]
When updating to the newer version and trying to launch a docker container with the kata runtime it fails to start and throws an OCI error. The only thing updated in the release notes is that kata kernel. Downgrading back to 28300 works.

https://github.com/kata-containers/runtime/issues/1378 Is the relevant issue filed in kata. To fix Clear Linux now though downgrading the Kata kernel to the previous version should be sufficient.

**Comment by bwarden** [comment]
Pending fix in kata-1.6.1, which will be included in CL >= 28760.

**Comment by Mountainerd** [comment]
@bwarden I tested today and Kata containers worked great. Thank you for getting this one resolved!

**Comment by eadamsintel** [comment]
Works for me also. Thanks for fixing this.

**Comment by bwarden** [comment]
Not me, the Kata Containers team did the work :)
