### ISSUE TITLE
Meld broken - "Meld requires GtkSourceView 3.20.0 or higher"

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#548]
Meld doesn't crash, but displays this message in the terminal as well as in a gtk message window.

**Comment by phmccarty** [comment]
I don't see this error on my system, but it's likely due to `gtksourceview` already being installed :-)

I'm adding a `gtksourceview` dependency for meld.

**Comment by ahkok** [comment]
Seems fixed now. Probably someone bumped something relevant.
