### ISSUE TITLE
Dynamic Volume Attachment Issue on AWS Marketplace Image

### ISSUE THREAD

**Issue by imswynne** [clearlinux/distribution#551]
Using AWS Marketplace Clear Linux image, EBS attachments that show up as NVMe devices do not seem to attach dynamically, f.e. with m5 instances. Requires an instance reboot to show up as block device.

1. Create an m5 instance using Clear Linux ami-0d03786316f3cae4c
2. Create and attach a volume
3. Check output of lsblk for attached volume device
4. Reboot
5. Check output of lsblk for attached volume device

Expect that device would appear in step 3 above, shortly after volume is attached, instead of step 5.

 - Clear Linux OS version: 26520

**Comment by nesiusra** [comment]
We may need to update the package that brings in support for EBS.  Will check.

**Comment by ahkok** [comment]
Does anything show up at all (e.g. `/proc/partitions`, or `dmesg`) ?

**Comment by imswynne** [comment]
No. There should be a /dev/nvme1n1 in this example. Just the root device shows up.

$ dmesg|egrep "nvme[0-9]n1"
[    0.072239]  nvme0n1: p1
[    0.174956] EXT4-fs (nvme0n1p1): mounted filesystem with ordered data mode. Opts: (null)
[    1.905546] EXT4-fs (nvme0n1p1): resizing filesystem from 130816 to 6553100 blocks
[    2.523165] EXT4-fs (nvme0n1p1): resized filesystem to 6553100

$ cat /proc/partitions
major minor  #blocks  name

 259        0   26214400 nvme0n1
 259        1   26212400 nvme0n1p1

**Comment by tpleavitt** [comment]
per @ahkok , suspected kernel config issue

**Comment by bwarden** [comment]
May need to enable `HOTPLUG_PCI_PCIE`

**Comment by bwarden** [comment]
Fix expected in linux-aws-5.0.3-100

**Comment by miguelinux** [comment]
> Fix expected in linux-aws-5.0.3-100

Thanks Brett

**Comment by imswynne** [comment]
Given that this is a kernel issue, how soon will the AMI on AWS Marketplace be updated? It seems kind of unreasonable to have to swupd and then reboot under the new kernel in a CSP environment. The current build is 26520.

**Comment by ahkok** [comment]
> we are in the process of updating it now. We are working on a weekly update schedule for AWS/Azure/Docker

**Comment by bdphipps** [comment]
The version of Clear on AWS Marketplace has been updated to 28680 and should be available now.

**Comment by nesiusra** [comment]
AWS offering has been updated - should be good to go.

**Comment by nesiusra** [comment]
(Should have reloaded my browser tab before responding. :) ) 

Closing.
