### ISSUE TITLE
Let's include the AF_Packet plugin for the Bro package

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#552]
**Is your feature request related to a problem? Please describe.**

With the inclusion of Bro 2.6 into the ClearLinux it makes sense to include plugins that enable high-performance packet capture, like the AF_Packet.

The plugin's code is here.

https://github.com/J-Gras/bro-af_packet-plugin/archive/1.4.0.tar.gz

**Describe the solution you'd like**

I'd like install Bro 2.6.x with the AF_Packet plugin just by adding a bundle.

**Describe alternatives you've considered**
There are no alternatives here, we maintain our own set of spec files to build Bro with plugins.

**Additional context**

The trial and error process gave me the following files to be used with autospec. Feel free to use them and modify as you see fit.

https://gist.github.com/mpurzynski/d4a8f64f3068f17651fa699d835fa60d

There is one hard requirement for this plugin to build. The Bro package itself must be changed and rebuilt with an option to include static libraries.

The following library is necessary for any plugin to built

/usr/lib/libbinpac.a

If you want to test if plugin works, then

bro -N | egrep -i af_packet

bro -i afpacket::<interface name here>

**Comment by fenrus75** [comment]
done
