### ISSUE TITLE
Consider adding Telegram

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#553]
**Describe the solution you'd like**
It would be nice to have [Telegram Desktop](https://github.com/telegramdesktop/tdesktop) available in the optimized swupd repositories. The latest stable release is [here](https://github.com/telegramdesktop/tdesktop/releases/tag/v1.6.0).

**Describe alternatives you've considered**
The package is also available as a [Flatpak](https://flathub.org/apps/details/org.telegram.desktop) or binary.

**Comment by ahkok** [comment]
Does the flatpak implementation suffice, or are there limits to its functionality that would warrant a native packaging?

**Comment by MattiaVerticchio** [comment]
The features are not limited by the Flatpak implementation

**Comment by markstos** [comment]
Since the package is available as a Flatpak, can this be closed?

**Comment by ahkok** [comment]
Ideally we'd offer this natively, but it's blocked due to the required dependency on ffmpeg. There is also the matter of requiring a `api_id` which makes things more complex.
