### ISSUE TITLE
Some parts of the Bro cluster are missing or out of place

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#557]
**Describe the bug**
The bro package does not include some parts of the bro cluster, like broctl. Some other parts of the cluster are in unexpected places. Let's change that so it is possible to run full bro / zeek cluster right after installing the network-monitoring-node bundle and copying configuration files to /etc.

I was able to build a working bro with some cmake definitions

`cmake
-DCMAKE_INSTALL_PREFIX=/usr
-DBRO_ROOT_DIR=/usr
-DBRO_ETC_INSTALL_DIR=/etc
-DINSTALL_BROCTL=true
-DBRO_LOCAL_STATE_DIR=/var
-DBRO_SPOOL_DIR=/var/spool/bro
-DBRO_LOG_DIR=/var/log/nsm/bro
..`

make install DESTDIR=/tmp/bro

I'm not sure why autospec removed things like broctl. I included a full list of files generated by my manual built, for comparison.

1951 files total

**Comment by mpurzynski** [comment]
[bro.log](https://github.com/clearlinux/distribution/files/2986976/bro.log)

**Comment by mpurzynski** [comment]
I created a cmake_args like this

-DCMAKE_INSTALL_PREFIX=/usr -DBRO_ROOT_DIR=/usr -DBRO_ETC_INSTALL_DIR=/etc -DINSTALL_BROCTL=true -DBRO_LOCAL_STATE_DIR=/var -DBRO_SPOOL_DIR=/var/spool/bro -DBRO_LOG_DIR=/var/log/nsm/bro

And the buildreq_add (please note I removed the gperftools from here, as tcmalloc performance is questionable and it might be leaking memory)

libpcap-dev
zlib-dev
flex
bison
swig
swig-abi
swig-bin
swig-data

Make autospec created the bro.spec like attached (and I can see all cluster's parts there).


[bro.spec.txt](https://github.com/clearlinux/distribution/files/2987062/bro.spec.txt)

**Comment by ahkok** [comment]
Seems arjan already did this.
