### ISSUE TITLE
GDM fails to start with Linux kernel 5.0.2-717

### ISSUE THREAD

**Issue by pixelgeek** [clearlinux/distribution#560]
**Describe the bug**
Following a swupd update, on an Intel Ivybridge based laptop, the kernel updated to 5.0.  On reboot, GDM failed to start, leaving the session stuck in text mode, frozen at the login prompt.  Reverting to the previous kernel allowed gdm to boot as expected.  
 
**To Reproduce**
1. swupdate to 28320
2. reboot
3. 
4. 

**Expected behavior**
Expect gdm to start as normal.  

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 
$ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28320
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
Lots of them ....

**Additional context**
Xorg logs available on request

**Comment by ahkok** [comment]
@miguelinux @mrkz this would be revert material

**Comment by iphutch** [comment]
@bwarden could you please check in with Chris.

**Comment by bwarden** [comment]
Most significant difference in Xorg.0.log between passing and failure cases is:
`(EE) modeset(0): failed to set mode: Permission denied` -> `(EE) modeset(0): failed to set mode: Invalid argument`

**Comment by bwarden** [comment]
Not sure whether it's related to https://gitlab.freedesktop.org/xorg/xserver/issues/542, or if I'm just triggering it when I try to reproduce this one.

**Comment by bwarden** [comment]
At this point, having rolled forward to 28560 and kernel 5.0.5, gdm starts successfully, but it fails to start a login session with Xorg. Xwayland works, however. I recommend closing this, and opening a new bug for that issue, and perhaps another for the VT-switching issue linked above.

**Comment by miguelinux** [comment]
A patch to solve this issue was added to Kernel native.

It will be ready for the next public release.

**Comment by mrkz** [comment]
@pixelgeek @miguelinux can we confirm this one got fixed, so we can close this issue?

**Comment by pixelgeek** [comment]
Confirmed  - can now boot into Xorg with kernel 5.0.6-726 on Clear Linux 28640

Thanks!  What was in the patch?
