### ISSUE TITLE
filesystem, llvm: "--copy-dt-needed-entries" only works with ld.bfd

### ISSUE THREAD

**Issue by rakuco** [clearlinux/distribution#562]
The `--copy-dt-needed-entries` option is specific to ld.bfd: ld.gold works only when all (recursively) required libraries are explicitly passed on the command line, and lld does not support it at al.

In practice, this means building a `hello.c` that does nothing can fail in some cases (I'm linking against glib just as an example):
* `gcc hello.c /usr/lib64/libglib-2.0.so`, `gcc -Wl,--copy-dt-needed-entries hello.c /usr/lib64/libglib-2.0.so` and `gcc -fuse-ld=gold hello.c /usr/lib64/libglib-2.0.so` all work fine.
* `gcc -fuse-ld=gold -Wl,--copy-dt-needed-entries` fails with `/usr/bin/ld.gold: error: --copy-dt-needed-entries is not supported but is required for libpthread.so.0 in /usr/lib64/libglib-2.0.so`. The build only passes if I specify all of `libglib-2.0.so`'s dependencies, recursively (in this case, `-pthread /usr/lib64/libpcre.so`).
* The situation is worse with clang because [this patch](https://github.com/clearlinux-pkgs/llvm/commit/3cbe8e79c079c03e0f7844e1268a9738c0d64618#diff-e6a11f05da12a20169bada900a26c65a) forces clang to always pass `--copy-dt-needed-entries` to the linker:
  * `clang -fuse-ld=gold hello.c libglib-2.0.so` fails with `/usr/bin/ld.gold: error: --copy-dt-needed-entries is not supported but is required for libpthread.so.0 in /usr/lib64/libglib-2.0.so`.
  * `clang -fuse-ld=lld hello.c libglib-2.0.so` fails with `ld.lld: error: unknown argument: --copy-dt-needed-entries`.

The LLVM situation in particular is a problem when building packages with clang instead of GCC: there's software that is not even tested with ld.bfd and expects at least gold to be used (in case using lld is not possible), and even if I remove `-Wl,--copy-dt-needed-flags` from `CFLAGS` in my spec file the build will still fail. It also essentially causes lld to be unusable on Clear Linux depending on which libraries are being used.

**Comment by rakuco** [comment]
cc @thiagomacieira

**Comment by thiagomacieira** [comment]
I've been bitten by this option before. I wonder what that option is trying to solve (if a problem) or how it improves performance (if that's what it does).

But is there any software that "mislinks" with ld.bfd instead of ld.gold? I understand upstream not testing, but that's besides the point: linkers should just link.

**Comment by rakuco** [comment]
> I've been bitten by this option before. I wonder what that option is trying to solve (if a problem) or how it improves performance (if that's what it does).

It's not clear to me either. The flag's been there ever since we started setting `CFLAGS` in the profile files.

> But is there any software that "mislinks" with ld.bfd instead of ld.gold? I understand upstream not testing, but that's besides the point: linkers should just link.

No; I think Chromium (which is what usually causes trouble) has forgotten to turn some gold/lld-specific flags only when those linkers are used, but I've just completed a build with ld.bfd today.

**Comment by iphutch** [comment]
In terms of content management, we will need to create a long term solution to reconcile default compiler flags with all tool chains in Clear Linux. Adding a Medium priority label due to work around via modifying flags.

**Comment by sunnyflunk** [comment]
I was actually looking at removing `--copy-dt-needed-entries` from another distribution myself over the previous month to investigate `ld.gold` (and `ld.lld` for clang) for faster linking and look at `identical code folding` (which bfd doesn't support). It doesn't seem to be a flag that would impact performance. 

My understanding is that when you tell the linker to link with only `-la` it will try to resolve symbols in `liba`, and if the symbols aren't resolved when using `--no-copy-dt-needed-entries` it will stop there and the build will fail.

However, with `--copy-dt-needed-entries` it will also search `DT_NEEDED` libraries of `liba`, say `libb` as a dependency of `liba` and see if the symbol can be resolved in `libb`. If it can resolve symbols in `libb`, it will add a `DT_NEEDED` to `libb` to the linked file despite only telling the linker to link against `liba`.

Consensus seemed to be this is a code error and should be fixed to tell it to link with both `-la -lb` when it needs to link with `libb` making `--copy-dt-needed-entries` a workaround of sorts. I am unsure if there are other scenarios that could occur that would be problematic after removing the flag. It does seem to enforce `--as-needed` to ensure it doesn't add all dependencies as `DT_NEEDED`, but only ones with needed symbols.

`--no-copy-dt-needed-entries` has been the default for about 7 years (binutils 2.22 I think), so it's unlikely to cause many issues today. I experienced the same errors as OP after removing the flag globally as remnants of `--copy-dt-needed-entries` remained in packages (where dependencies want to use the same flags they were built with etc). Rebuilding the affected packages without the flag resolved those problems. Assuming you remain with `ld.bfd` as the default, many of the failures wouldn't occur as `ld.bfd` would still support the flag.

In terms of underlinking, I found that `ld.gold` (hence `--no-copy-dt-needed-entries`) actually linked to significantly more libraries than using `ld.bfd` with `--copy-dt-needed-entries` (over 100s of packages, but unsure whether `--as-needed` was being enforced with `ld.gold`). I have no comparison with `ld.bfd` unfortunately.

I also did see someone wanting to add support in `lld` https://reviews.llvm.org/D56647 which seemed to severely overlink in its current state (likely the results were without `--as-needed`)!

**Comment by fenrus75** [comment]
For our packages we default to as-needed.

If you haven’t already, try our libdeps script for fun, it generally tells
you what pulls in which library

A good time for us to drop the flag will be our gcc9 rebuild, which is a
few weeks away

**Comment by rakuco** [comment]
For the record, I've just found out by chance that `filesystem` was fixed in early April by clearlinux-pkgs/filesystem@73a0dea906012b8204d31d2d2ec474b07c0634ca -- it's pretty unfortunate that the commit doesn't reference this issue and nobody noticed it.

The llvm package remains broken: even after the update to 8.0.0 it still carries [a patch](https://github.com/clearlinux-pkgs/llvm/blob/7de3c660f4339ade5d93b111c92cd3d96e64f928/clang-0002-Detect-Clear-Linux-and-apply-Clear-s-default-linker-.patch#L84) that always passes `--copy-dt-needed-entries` to the linker and thus prevents ld.gold and lld from being used in multiple cases.

**Comment by rakuco** [comment]
I've filed #774 to track a related issue: some GCC-specific options are now part of the default `CFLAGS` and `CXXFLAGS` used in RPM builds, which further prevents LLVM builds from working without manual intervention in the spec files.

**Comment by miguelinux** [comment]
@rakuco  can we close this now then?

**Comment by rakuco** [comment]
I don't think so, as I said llvm is still broken.

**Comment by sunnyflunk** [comment]
With the latest llvm 9 update, the patch no longer adds `--copy-dt-needed-entries` by default. Will test it out with the new 2 stage PGO.

May still be there in the `llvm8` bundle

**Comment by thiagomacieira** [comment]
It was. I fixed it last night.

**Comment by rakuco** [comment]
Awesome, thanks for taking care of this!

**Comment by waarmond** [comment]
` error: --copy-dt-needed-entries is not supported but is required for libz.so.1 in /usr/lib/libpng.so`
