### ISSUE TITLE
Should we enable (by default) CUPS when installing desktop?

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#563]
Currently the `cupsd.service` systemd service is present but disabled by default.

**Are users expecting to have CUPS (printing) service enabled and running out of the box** when installing the `desktop` (any variant) bundle?

**Comment by pceiley** [comment]
Yes.

**Comment by fenrus75** [comment]
can we make this socket activated

**Comment by miguelinux** [comment]
We could try:

https://lists.debian.org/debian-printing/2016/09/msg00052.html

**Comment by miguelinux** [comment]
> https://lists.debian.org/debian-printing/2016/09/msg00052.html

Also check: https://github.com/apple/cups/issues/5319

**Comment by ahkok** [comment]
yes, this is expected.

**Comment by phmccarty** [comment]
Yes, having it socket-activated and enabled by default is my expectation.

**Comment by ahkok** [comment]
We already install the `cupsd.socket` units just fine. I've pushed changes to automatically enable this unit by default everywhere.

**Comment by ahkok** [comment]
`cups-2.2.11-40`
