### ISSUE TITLE
Package Request: calc

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#564]
Please consider packaging calc.

Source and releases can be found at:
[https://github.com/lcn2/calc](https://github.com/lcn2/calc)

It's such a simple tool, but I rely on it heavily.

I've had a skim through but couldn't see an obvious bundle this could be included in.

**Comment by ahkok** [comment]
I agree, and `bc` really doesn't cut it for me sometimes, either.

**Comment by pceiley** [comment]
Thanks, @bwarden, for packaging this! I'll close.

I note that it's currently built without readline - I'm not really sure what the benefits are of building with readline support and calc appears to be working fine for me without it. I have, however, found evidence that building with readline support fixes some bugs.
