### ISSUE TITLE
Redis server user-defined configuration

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#565]
**Is your feature request related to a problem? Please describe.**
Currently the redis server (redis-native) bundle is shipped without a default config or template.. 

The service is capable of running without a user-definied config but if a configuration needs to change, research has to be done to figure out configuration style and options.

**Describe the solution you'd like**
It would be nice if Clear Linux:

- Distributed a copy of `redis.conf` template/sample file with the package under `/usr/share` somewhere that can be copied. https://github.com/antirez/redis/blob/5.0/redis.conf

- Made the presence of `/etc/redis/redis.conf` automatically detected and loaded to replace the default configuration, like other Clear services modified for statelessness.

**Describe alternatives you've considered**
- Manually finding the `redis.conf` template and downloading it for reference. 
- Manually modifying the redis.service unit file to reference my customer configuration

**Comment by ahkok** [comment]
`statelessify` request, essentially.

**Comment by ahkok** [comment]
Completed. `/etc/redis.conf` is the file. It can be missing. It overrides all default options in `/usr/share/defaults/etc/redis.conf`.

**Comment by ahkok** [comment]
`redis-3.2.1-41`
