### ISSUE TITLE
Redis should run as a non-root user

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#566]
**Describe the bug**
The systemd unit file for redis currently causes redis to run as root. 

From https://redis.io/topics/security:

> Redis does not requires root privileges to run. It is recommended to run it as an unprivileged redis user that is only used for this purpose.

**To Reproduce**
1.  swupd bundle-add redis-native
2. systemctl start redis
3. ps aux | grep redis

**Expected behavior**
Redis to run as a non-root user

**Comment by ahkok** [comment]
Agreed this is a bug, not a feature.

**Comment by ahkok** [comment]
Will push a large update this afternoon. redis will run as `redis` uid `340` and be much more stateless. You can from now on run it without `/etc/redis.conf` and it'll come with some sane defaults. If you create `/etc/redis.conf` then the settings in that file will override the system wide defaults.

**Comment by ahkok** [comment]
`redis-native-5.0.4-34`
