### ISSUE TITLE
VMware VMDK image should have os-cloudguest-vmware bundle

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#567]
**Is your feature request related to a problem? Please describe.**
The VMDK disk image that is published for VMware does not have the `os-cloudguest-vmware` bundle, which means `open-vm-tools` are not installed and running out-of-the-box.

**Describe the solution you'd like**
Have the  `os-cloudguest-vmware` bundle preinstalled in the VMware VMDK image of Clear Linix.

**Describe alternatives you've considered**
Manually installing the `os-cloudguest-vmware`bundle

**Additional context**
This was on Clear Linux version 28360

**Comment by ahkok** [comment]
@bryteise

**Comment by bryteise** [comment]
@puneetse Is this image meant to be deployed on cloud-hosts I thought this was more similar to our kvm bundle in usage? Or is the os-cloudguest-vmware just a misleading name for a bundle (based on it only having the open-vm-tools package in it)?

**Comment by fenrus75** [comment]
cliudguest us really our namespace for vmm

**Comment by bryteise** [comment]
Hrm well not fully a fan of that naming as some of the bundles are associated with tooling specific to more of what cloudhost it is running on so it gets a little confusing to me. Regardless I understand the solution now, thanks!

**Comment by bryteise** [comment]
@gtkramer has added it for the next build.
