### ISSUE TITLE
- Display Linux Distribution Logo In Terminal, is possible in Clear Linux ? -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#568]
Hi,

Is there a possibility of having a bundler displaying the distribution logo in the terminal plus other features?
e.g: screenfetch, neofetch, archey

if you can not implement one of these, you can write a similar one for clear linux?

clear linux - 28440 -  5.0.3-721.native #1 SMP Thu Mar 21 14:42:47 UTC 2019 x86_64 GNU/Linux

**Comment by DavidKz** [comment]
I suspect there are a long list of package adds with priorities above distro logos, but it might just be a 5 minute task.  Certainly a good exercise for someone learning bundle development on Clear.

**Comment by fenrus75** [comment]
We have neofetch

**Comment by fenrus75** [comment]
but neofetch isn't in any great bundles; adding it now to sysadmin-basic

**Comment by ionutnechita** [comment]
i tested now, and neofetch is exist.

thanks
