### ISSUE TITLE
Fresh GUI install  - pointer frozen until TTY login.

### ISSUE THREAD

**Issue by DavidKz** [clearlinux/distribution#569]
**Describe the bug**
After installing a basic desktop/autostart system, screen is frozen at GUI login with mouse pointer in lower right of screen.  The mouse can move intermittently every 10 seconds or so, but only a few millimeters with wild swipes.  With considerable effort, I was able to get the pointer on the GUI's login bar, but clicking had no effect. 

Switching to TTY 2 (Ctrl-Alt-F2) and logging in, and switching back to TTY 1 (Ctrl-Alt-F1), allows the mouse pointer to move freely again. 

I realize this could be any number of things, as Gnome and the Linux kernel were both updated recently.  When system was installed back at 28200, it functioned normally. If any further steps can help isolate the issue, I would gladly help.

**To Reproduce**
1. Bare metal install, native kernel, select desktop-apps, desktop-autostart
2. At GUI login screen, mouse is frozen/stuck lower right quadrant.
3. Workaround: Ctrl-Alt-F2 to TTY2, login, Ctrl-Alt-F1 back to TTY1.  Mouse pointer moves freely.

**Expected behavior**
Consistent and normal mouse movement and subsequent login on TTY1.

**Environment (please complete the following information):**
 - Clear Linux OS version: 28430
 - Bundles: clean install with only "desktop-apps" and "desktop-autostart" selected

**Comment by mrkz** [comment]
@DavidKz are you still being affected with this issue?

I'm not able to reproduce on **28970**

**Comment by mrkz** [comment]
> @DavidKz are you still being affected with this issue?

Also, having additional info on your hardware specs may help

> I'm not able to reproduce on **28970**

This on a Thinkpad T540p.

**Comment by mrkz** [comment]
Can't reproduce, should you face the same behavior, please create a new issue with additional information on your hardware specs.
