### ISSUE TITLE
Feature request: Add gputop to Clear Linux

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#57]
A GPU profiling tool.

https://github.com/rib/gputop

**Comment by ahkok** [comment]
gputop's compilation also pulls in dependencies over HTTP, this isn't very friendly... this is going to cost some integration time. And yes we'd insist on an actual tagged release.

**Comment by iphutch** [comment]
For now, this is incompatible with Clear Linux tooling. We will re-assess at a later time.
