### ISSUE TITLE
Need window-resize indicator at the edges and bottom-right corner of window in GNOME (Xorg) session

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#572]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but would really help with usability.

**Describe the solution you'd like**
When you hover the mouse over the edge of a window or bottom-right corner, it should have a resize indicator telling the user you're at the right spot to click and resize the window.  Without it, people have a hard time figuring where to click to initiate resizing.  

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by phmccarty** [comment]
I tried reproducing the issue for a few applications, and the results are very mixed. Here are the results.

| Application  | Can Reproduce? |
| ------------- | ------------- |
| gnome-terminal  | Yes  |
| firefox  | No  |
| nautilus | Yes |
| evolution | No |
| gnome-software | Yes |
| inkspace | No |

**Comment by mrkz** [comment]
I've managed to reproduce this, however, this is only happening on a gnome Xorg session, I tried `Gnome on Wayland` session and this is not a problem there.

**Comment by phmccarty** [comment]
@mrkz I can confirm your findings. Works okay for a `GNOME on Wayland` session, but not for `GNOME on Xorg`.
