### ISSUE TITLE
Gnome (XOrg) crashes due to an extension `services-systemd@abteil.org`

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#573]
Thanks to **mrkz** and he found that this problem is due to the extension `services-systemd@abteil.org`.

I'm closing this issue now.

---

**Describe the bug**
Previously there is a known issue that `gdm.service` may need to be started manually on systems with Nvidia GPU, while `desktop-autostart` is already installed. But GDM will works fine if I cannot the display to the integrated GPU, whose manufacturer is Intel.

Around one and half week ago, after a reboot, I found that on top of this bug, now I'm not able to enter the `Gnome (XOrg)` desktop environment. I'm still able to enter `Gnome Flashback`, `Gnome kiosk`, or `Awesome`. And even if I cannot the display to the integrated Intel GPU, I still cannot enter `Gnome (XOrg)`.

**To Reproduce**
1. Turn on the system and press alt+F2 to get to tty2, as tty1 is a black screen with a mouse and cursor and I can do nothing.
2. Run `sudo systemctl restart gdm`.
3. On the login screen, select `Gnome (XOrg)` and enter the credentials. The login itself is successful but it never gets into `Gnome` and after a few system I'm bumped back to the login screen, where I need to log in again.

4. (Option) If `awesome` or other desktop environment is selected, then it works as expected.

**Environment (please complete the following information):**
 - Clear Linux OS version: 
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28460
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```
 - Bundles: I will provide it if it's needed. This doesn't seems to be a problem due to missing bundles.

**Additional context**
Please see the log file attached.
[boot.log](https://github.com/clearlinux/distribution/files/3005956/boot.log)

**Comment by mrkz** [comment]
as @lebensterben  updated in the report; the extension broke with the new gnome 3.32 rollout on clearlinux and gnome-shell was unable to start: https://github.com/petres/gnome-shell-extension-services-systemd
