### ISSUE TITLE
Installer.img errors out during filesystem creation

### ISSUE THREAD

**Issue by DavidKz** [clearlinux/distribution#574]
Error screen attached.  Installer is version 28460.

Hardware:  7980XE, 128GB RAM, 2 x 1080TI, 1TB Samsung NVME 
Auto Partition creates EFI, 250 mb swap, 953GB ext4 root

Installer is interrupted during partition creation, and presents black screen with error message.  Previous installs were successful, prior to the 28460 installer.

![insterr](https://user-images.githubusercontent.com/48547766/54964583-6789d480-4f43-11e9-81c3-29f6ed9b147b.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS version: 28460
 - Bundles: desktop-apps,desktop-autostart

**Comment by DavidKz** [comment]
Further testing on this:

- it only happens on a 7980XE bare metal install when shrinking root partition after auto-partition sets up a default.  Does not happen on a VM, even when shrinking partition.
- tried older installers from a month ago, and error occurs there as well.  Previously, I did only full disk installs, so didn't trigger this.

If the devs can't replicate the error, I'd be happy to provide diags or do necessary testing on my system.  This is a show-stopper for dual booting Clear with another distro

**Comment by DavidKz** [comment]
Correction:  Full disk installs using auto-partition trigger the error screen.  The screen comes up immediately after finishing the ext4 partition.  Being unable to install, and on a flagship 7980XE platform no less, means my Clear experiment is at an abrupt end.

**Comment by mdhorn** [comment]
@DavidKz This might be an issue in matching the NVME device name.
Could you include the following as attachments to enable diagnosis:
	/root/pre-install-clr-installer.yaml
	/root/clr-installer.log
These files are placed on the installation media.

If you are able, enabling additional logging will be helpful in
diagnosing the issue. At the OS Boot screen, hit 'e' to edit the kernel
command line. Add the following to the end of the line:
	clri.loglevel=4

**Comment by DavidKz** [comment]
The requested files.  I redacted user/hostname and changed .yaml to .log, so it would attach:

[clr-installer.log](https://github.com/clearlinux/distribution/files/3040118/clr-installer.log)
[pre-install-clr-installer_yaml_not_log.log](https://github.com/clearlinux/distribution/files/3040119/pre-install-clr-installer_yaml_not_log.log)

Also, unsure if this helps, but no errors occur when using older installer 28200. I don't know if installer version is related, but that img used 1.1.7.

**Comment by mdhorn** [comment]
@DavidKz Very odd. We have another report of a 1TB NVME SSD also hanging on `partprobe`.
How is that Samsung SSD 960 PRO 1TB connected? M2 or SATA? That model might only be M2?

**Comment by hongzhanchen** [comment]
We already met similiar issue on XEON E5 server. 
[clr-installer.log](https://github.com/clearlinux/distribution/files/3052628/clr-installer.log)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/distribution/files/3052629/pre-install-clr-installer.yaml.txt)
![error](https://user-images.githubusercontent.com/42202712/55699044-79677f00-59fb-11e9-9e3f-3a834351658f.png)

**Comment by mdhorn** [comment]
@hongzhanchen Can you confirm that the 2TB NVMe SDD you are using is connected via PCIe?
Trying to isolate if this is just a problem with NVMe SSD >= 1TB, or if it is specific to the interface.

**Comment by hongzhanchen** [comment]
> @hongzhanchen Can you confirm that the 2TB NVMe SDD you are using is connected via PCIe?
> Trying to isolate if this is just a problem with NVMe SSD >= 1TB, or if it is specific to the interface.

It is via SATA.

**Comment by hongzhanchen** [comment]
@mdhorn ,we tested 28200 image, still failed. It is SATA SSD
[clr-installer.log](https://github.com/clearlinux/distribution/files/3057411/clr-installer.log)
[pre-install-clr-installer.yaml.txt](https://github.com/clearlinux/distribution/files/3057412/pre-install-clr-installer.yaml.txt)

**Comment by hongzhanchen** [comment]
@mdhorn ,Following is our test results. We found that both 1.1.7(28200) and 1.1.8 installer work with 160G HDD, but do not work with 2TB HDD or SDD.
Not working:
Seagate ST2000NX0243 2TB
Intel SSD DCP3600 2TB
Working: 
Fujitsu MHZ2160BK 160G

**Comment by DavidKz** [comment]
> @DavidKz Very odd. We have another report of a 1TB NVME SSD also hanging on `partprobe`.
> How is that Samsung SSD 960 PRO 1TB connected? M2 or SATA? That model might only be M2?

My Samsung 1TB is M2.  

What's interesting is that @hongzhanchen and I have nearly identical error screens (only addresses differ slightly), but different error conditions:

1) @hongzhanchen 's clr-installer.log had an error logged in the file, mine did not
2) my error vanishes when going back to 28200(1.1.7), but @hongzhanchen 's remains

Does the installer invoke any code that may change when the installer version does not?  If so, I can test the installers from 28200 forward, and see when the error starts occurring, and whether it is dependent on installer version 1.1.8 being present.  If the installer uses only code that changes with its own versioning, then the test isn't necessary - it must be 1.1.8.

**Comment by DavidKz** [comment]
Are there any updates on this?

**Comment by mdhorn** [comment]
@DavidKz The installed depends upon several external tools for disk manipulation from the os-core: 
`lsblk, parted, partprobe, mkfs, wipefs, sgdisk, mount, umount` as well as dependent upon the kernel and associated drivers.
So even though the version of the installer may not change, we will see changes in behavior with new release of Clear Linux* OS.
We do attempt to have validation coverage to ensure the functionality, but of course, we do not have every possible hardware combination available for regressions.

Is this still occurring with the latest release?

If so, it is helpful to have the logs with Debug enabled either by launching from the command line with `clr-installer -l 4` or from the kernel command line; from the OS Boot screen, hit 'e' to edit the kernel command line. Add the following to the end of the line:
clri.loglevel=4

**Comment by mdhorn** [comment]
@ahkok Please move this to https://github.com/clearlinux/clr-installer

@DavidKz Is this problem still occurring on your hardware with the latest release?
If so, can you attempt to manually change the partition table with `parted` and then immediately after making the change run `partprobe -s` and report your results?

**Comment by hongzhanchen** [comment]
we can not reproduce the issue with installer version 2.0.3
