### ISSUE TITLE
Is Clear Linux a general purpose Operating System?

### ISSUE THREAD

**Issue by Raj2032** [clearlinux/distribution#575]
Is Clear Linux a general purpose Operating System?

If so, do I download the `installer.img.xz` file?

**Comment by DavidKz** [comment]
You need to uncompress the img file, then something like Etcher can write the IMG to a USB.  If you need an ISO, uncompress the iso.xz file.  Read the instructions on clearlinux.org, or the Documentation. It covers how to approach a lot of use cases.

Based only on my experience, I'd answer "no" to the general purpose question.  I believe Clear categorizes itself as an "infrastructure OS", but that doesn't have to constrain anyone's own usage, and a skilled Linux user can mold it to their needs.  See clr-on-clr tools.

**Comment by fenrus75** [comment]
we certainly aim to be an instructure OS as well as a developer / desktop OS. 
on the later we are making improvements but we know we're not ready for general use.

**Comment by Raj2032** [comment]
Thanks for your help.

**Comment by ahkok** [comment]
Please open a new issue if you have additional questions! thanks.

**Comment by Raj2032** [comment]
No worries.
