### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by blitzprog** [clearlinux/distribution#576]
First of all, the installer corrupted my partition table which resulted in a loss of all data:

![Installer failing](https://i.imgur.com/80LgtRc.jpg)

I was about to give up at that point but then restarting the installation on a now empty drive succeeded. I finally have a running Clear Linux now.

I have been using CL since Monday (4 days) now and here are some of the improvements that I noticed could be made (general-purpose OS QoL):

* GDM didn't autostart on boot for me after installing it (manual `systemctl enable gdm` required)
* No Chrome package (managed to run it by extracting the RPM, but fonts don't work)
* No Discord package (installed it via Flathub but it's crashing very often)
* No ffmpeg package (most Youtube videos not playing in Firefox)
* No GNOME extension installation support (I guess it's possible the manual way but if you're targeting the masses you should probably make it user-friendly)
* Given the modern nature of CL, I was surprised that [node](https://nodejs.org/en/) is using the LTS 10.x instead of 11.x
* Default font choice in the GNOME package was not to my liking, I think there are many better fonts out there. Luckily, this is easy to change after the installation.
* When playing music via Firefox, other CPU intensive tasks like compiling a program will interrupt the music play and it stutters. Other systems prevent this via priority assignments for the sound system afaik.
* The "Software" app seemed to never finish an installation task after it reached 100% (command line installation via `swupd` was stable, though)

After these 4 days of using it as my main OS, I can say that I am **pleasantly surprised** how snappy & stable the experience was. All animations rendered smoothly on my 120 Hz monitor and I didn't experience a single crash (aside from the installation). The performance of computations and I/O was amazing, my Go projects seemed to compile a little faster than usual.

All in all I am looking forward to see this project grow and I am going to continue using it for my development work. Best of luck to all the amazing people who contribute to this project!

**Comment by DavidKz** [comment]
You mentioned that the installer error occurred on an already partitioned drive, and it succeeded when it was wiped?  Although it is a different error screen, the issue I reported in #574 also occurred on a pre-partitioned drive.

**Comment by ahkok** [comment]
> When playing music via Firefox, other CPU intensive tasks like compiling a program will interrupt the music play and it stutters. Other systems prevent this via priority assignments for the sound system afaik.

Turns out we never had `rtkit`, which is what `pulseaudio` uses to gain realtime scheduling priority levels. This is being fixed as we speak, thanks to your feedback!

**Comment by ahkok** [comment]
> No GNOME extension installation support

gnome-software supports this. Search for `extension` for instance, and it should show you a ton of them that can be installed.

**Comment by ahkok** [comment]
We've picked out what we can from this feedback that wasn't already listed in other bugs/issues. I'm going to close this, but I would encourage you to continue to file *individual* issues for items that you'd like to give feedback on.

In general, it's really hard to track issues with 7-8+ items in them. And it's difficult for you to get an idea whether progress has been made, too.

**Comment by blitzprog** [comment]
Late reply on my end, but I've read all the replies.

Thank you especially for the tip regarding the GNOME extensions in the software center (I was looking on GNOME Tweaks), that helped me install a workspace grid.

I can fully understand closing it because it has too many items @ahkok, I am doing the very same on issues of my projects if they mention too many things. The goal was only to raise awareness and hopefully solve some of the troubles.

Thanks again, and happy engineering!
