### ISSUE TITLE
gnome-control-center "help" broken

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#578]
open gnome-control-center "settings", select any panel, i.e."background".
Then, in the g-c-c title bar select options->"Help"
You will see the following:
<pre>
Document Not Found
The URI ‘help:gnome-help/look-background’ does not point to a valid page.
Search for packages containing this document
</pre>

This can be replicated for all items.

**Expected behavior**
A help screen should be presented.

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28540
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
Too many to list (570)

**Additional context**
Compare with Ubuntu 18 to see the difference.

**Comment by abecastillo** [comment]
@AthenasJimenez or @josuedhg probably you can take a look at this.

**Comment by sunnyflunk** [comment]
Had a look at this, the `desktop` bundle includes `gnome-user-docs` which is an empty package by the look of it, but the needed files are in `gnome-user-docs-doc` package. So `gnome-user-docs-doc` would need to be added to the bundle for help to work most likely.

**Comment by ahkok** [comment]
Fixed by @fenrus75 in our bundles.
