### ISSUE TITLE
Update the audisp-json plugin to 2.2.4

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#579]
**List the package you would like to see updated**
https://github.com/gdestuynder/audisp-json/releases

**Does this update provide any significant new features that may be needed**
We identified several issues with the 2.2.3 code hence the new release. It's been tested already on CentOS 7 and Ubuntu 14.04 LTS

**Comment by fenrus75** [comment]
thank you for the report. our new version scanner picked this one up in the last hour or so and the updated package is already building as I'm typing this
