### ISSUE TITLE
Wake from suspend failing with 4.16.6-563.native

### ISSUE THREAD

**Issue by rustylynch** [clearlinux/distribution#58]
My Dell XPS is no longer able to successfully resume.  I see the power button light up, but the screen stays off.

From "journalctl -b -1" I see the following new errors:
May 03 17:46:17 rustic kernel: [drm:intel_power_domains_verify_state] *ERROR* power well DDI A/E IO power well state mismatch (refcount 1/enabled 0)
May 03 17:46:17 rustic kernel: [drm:intel_power_domains_verify_state] *ERROR* power well DDI B IO power well state mismatch (refcount 1/enabled 0)
May 03 17:46:17 rustic kernel: [drm:intel_power_domains_verify_state] *ERROR* power well DDI C IO power well state mismatch (refcount 1/enabled 0)
May 03 17:46:17 rustic kernel: [drm:intel_power_domains_verify_state] *ERROR* power well DDI D IO power well state mismatch (refcount 1/enabled 0)
May 03 17:46:18 rustic kernel: [drm:intel_dp_start_link_train] *ERROR* [CONNECTOR:59:eDP-1] Link Training failed at link rate = 540000, lane count = 4
May 03 17:46:28 rustic kernel: [drm:drm_atomic_helper_wait_for_flip_done] *ERROR* [CRTC:37:pipe A] flip_done timed out
May 03 17:46:38 rustic kernel: [drm:drm_atomic_helper_wait_for_dependencies] *ERROR* [CRTC:37:pipe A] flip_done timed out
May 03 17:46:48 rustic kernel: [drm:drm_atomic_helper_wait_for_dependencies] *ERROR* [CONNECTOR:59:eDP-1] flip_done timed out
May 03 17:46:59 rustic kernel: [drm:drm_atomic_helper_wait_for_flip_done] *ERROR* [CRTC:37:pipe A] flip_done timed out
May 03 17:47:09 rustic kernel: [drm:drm_atomic_helper_wait_for_dependencies] *ERROR* [CRTC:37:pipe A] flip_done timed out

**Comment by markgross** [comment]
Does it attempt to resume and crash or just sit there stuck in suspend until you hard press the power button for 10 sec?  (because that's what happens on my t470 until I run linux-stable vanilla kernels.  FWIW 4.16.7 resumes pretty well for me.)

**Comment by rustylynch** [comment]
It looks like it turns off (all lights are off and screen is completely black) and then I press the power button to see the backlight for the button come on as well as the backlight behind the keyboard.  The screen lights up partially (only noticeable in a dark room), and then nothing.

Looking through the logs it appears the system never really shutdown.

**Comment by iphutch** [comment]
@miguelinux @bwarden

**Comment by rustylynch** [comment]
I had some spare cycles to debug this further.  The culprit is the try_load_dmc.patch.  I can rebuild the 4.16.7-567 linux package and if I remove this one patch then the issue goes away.

This patch was introduced since 4.16.5, which was the last working kernel I had before the upgrade that introduced the bug.

commit 367cfd96b0a277e062d5c841091c9a14cb352cb7
Author: Arjan van de Ven <arjan@linux.intel.com>
Date:   Sat Apr 28 16:48:24 2018 +0000

    allow for late loading of the DMC

 config             |  2 +-
 linux.spec         |  6 ++++--
 try_load_dmc.patch | 12 ++++++++++++
 3 files changed, 17 insertions(+), 3 deletions(-)

**Comment by rustylynch** [comment]
Another interesting fact... the offending patch just attempts to load the dmc firmware in the i915_dmc_info debugfs call, so I tried moving the firmware and then booting the offending kernel again.  I can see in dmsg both the original firmware load fail and the additional attempt when the i915_dmc_info file is read, but interestingly the original failure to suspend still happens.

So... just attempting to intel_csr_ucode_init again is all it takes to trigger this bug.

**Comment by rustylynch** [comment]
Release 22860 stopped applying the try_load_dmc.patch and as a result i915 based systems can successfully suspend
