### ISSUE TITLE
Support for hfsplus

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#580]
I would like to be able to mount hfsplus file systems. Currently there is no support.
```
mount: /media/wd2tb: unknown filesystem type 'hfsplus'.
```

**Comment by ahkok** [comment]
@miguelinux Can we enable this as a module? Seems reasonable for the `-native` kernels.

**Comment by miguelinux** [comment]
> Assigned #580 to @miguelinux.
> 
On it

**Comment by miguelinux** [comment]
Integrated at linux-5.0.5-725

**Comment by miguelinux** [comment]
@neben if you found any other issue let us know.

**Comment by neben** [comment]
@miguelinux Thanks a lot, I can confirm it's working! Would it be possible to include `hfsprogs` (i.e., `mkfs`, `fsck`), too?

**Comment by miguelinux** [comment]
@neben Can you open a [new issue ](https://github.com/clearlinux/distribution/issues/new/choose) with this request please.
