### ISSUE TITLE
date format is not correct

### ISSUE THREAD

**Issue by xinzhanz** [clearlinux/distribution#581]
Man date the format is date [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]].
But the date output is Sat 09 Mar 2019 02:49:05 AM UTC.
It is not correct. Correct output should be Sat Mar  9 02:49:13 UTC 2019

1.  date
2.  or date -u

Expect output  Sat Mar  9 02:49:13 UTC 2019

 - Clear Linux OS version: VERSION_ID=28230010

**Comment by miguelinux** [comment]
> Expect output  Sat Mar  9 02:49:13 UTC 2019

Can you elaborate more the issue.

$ date -u
Fri Mar 29 14:08:36 UTC 2019
$ date
Fri Mar 29 08:08:37 CST 2019
$ date -R
Fri, 29 Mar 2019 08:09:52 -0600
$ date -u 03090249
date: cannot set date: Operation not permitted
Sat Mar  9 02:49:00 UTC 2019

The last one is to set the date to your system.

**Comment by thiagomacieira** [comment]
Please paste the output of the `locale` command too.

**Comment by xinzhanz** [comment]
root@p-icl06 ~ # locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
root@p-icl06 ~ # date -u
Sat 09 Mar 2019 02:35:58 AM UTC
root@p-icl06 ~ # date
Sat 09 Mar 2019 02:36:13 AM UTC
root@p-icl06 ~ # date -R
Sat, 09 Mar 2019 02:36:16 +0000
root@p-icl06 ~ # date -u 03090249
Sat 09 Mar 2019 02:49:00 AM UTC

The date output is different from miguelinux's.

**Comment by thiagomacieira** [comment]
```
$ LC_ALL=en_US.UTF-8 date -u   
Mon 01 Apr 2019 10:23:16 AM UTC
$ LC_ALL=C date -u          
Mon Apr  1 10:23:20 UTC 2019
```

This is correct. See https://sourceware.org/git/?p=glibc.git;a=blob;f=localedata/locales/en_US;hb=HEAD#l108 for the definition.
