### ISSUE TITLE
Package request: iotop

### ISSUE THREAD

**Issue by neben** [clearlinux/distribution#583]
How can I install iotop? I see there is an iotop package at
```
https://download.clearlinux.org/current/x86_64/os/Packages/
```
but how can I install it?

**Comment by fenrus75** [comment]
adding to performance-tools bundle; should be in afternoon release

**Comment by neben** [comment]
There is no new update on my machine.
```
root@nuc ~ # swupd update
Update started.
Version on server (28560) is not newer than system version (28560)
Update complete. System already up-to-date at version 28560
```
Shouldn't this change be reflected in https://github.com/clearlinux/clr-bundles/blob/master/bundles/performance-tools ?

**Comment by neben** [comment]
ok, apparently this was pushed tonight, so all good now. thanks!
