### ISSUE TITLE
Can't install alongside windows with the new installer

### ISSUE THREAD

**Issue by ookamix** [clearlinux/distribution#584]
Hi there,
I tried following this https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot tutorial to install clear linux alongside my existing windows installation, however, it doesn't seem to work.
In dev/sda I have already windows installed, so with the media partition tool in the new blue installer, I created a root, a boot and a swap partition from dev/sda3 to dev/sda5 i think (rest is windows).

The problem is, that when i click install, I get the warning that it wants to erase and repartition the whole /dev/sda drive, even though I would like to keep the windows data. How to fix this?
EDIT: here are 2 screenshots:
![20190329_164540](https://user-images.githubusercontent.com/49071336/55244777-2266ea80-5242-11e9-9225-a201c9bfe737.jpg)
![20190329_164532](https://user-images.githubusercontent.com/49071336/55244776-2266ea80-5242-11e9-8c81-15aafc76e1b9.jpg)

**Comment by pixelgeek** [comment]
From the top of the tutorial you're following "The process to install other operating systems for a multi-booting computer is described below. Install Clear Linux OS first, then install other operating systems in any order."
We don't support installing Clear Linux with Windows already pre-installed, although it is a common request, and I'm sure it's on the install team's todo list.

**Comment by ookamix** [comment]
Thanks for the answer!!
I thought I could do what it says under "Install Clear Linux OS" without installing Clear Linux first too.
Wouldn't an option to use the old partition tool in the new installer suffice?
Well I'm a Linux noob, so gonna hope the installer team will add that feature

**Comment by mrkz** [comment]
@mdhorn

**Comment by bktan8** [comment]
@ookamix - we have improved the installer since your initial filing to support installing Clear Linux alongside Windows.  Also, you can find documentation on how to do it here: https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-win.html.  

Please give it a try and let us know.
