### ISSUE TITLE
ethernet is not graphically shown when using a multiport adapter

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/distribution#585]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
Installed clear 28540 Desktop beta, I wanted to see the Ethernet information on the top right hand corner when I connected the multi-port adapter of the brand UGREEN. I saw none, then I opened the SETTINGS windows and navigated to the NETWORK section. I still could not see the information. Opened the console and I "ip address"  I could see the interface name an IP assigned and I can navigate on web.

**To Reproduce**
1. Download the clear-28540-live-desktop-beta.img.xz
2. Install it with network, sysadmin bundles selected
3. Plug in the UGREEN usb+3.0+ethernet+network+adapter+driver
4. Plug in the Ethernet cable to this device.
5. Try to see the network info by the graphical interface (top right hand corner), under settings(network)

**Expected behavior**
I wanted to be able to see the plugged in Ethernet card by graphics. Maybe click on disable, enable, connect, disconnect 

**Screenshots**
this is a picture of the exact UGREEN device I am using
![image](https://user-images.githubusercontent.com/36279716/55265478-285acc80-523e-11e9-957b-fdd88b46d9a9.png)

This is a screenshot of my Ethernet setting after I plugged in the device.  it does not show on the desktop or graphical interface.
![Screenshot from 2019-03-29 16-10-51](https://user-images.githubusercontent.com/36279716/55265551-74a60c80-523e-11e9-867b-f94ca0c69cd3.png)

**Environment (please complete the following information):**
***** -  Hardware Dell XPS laptop
***** -  Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28550
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
***** - Bundles: 
Babel
NetworkManager
Sphinx
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
bootloader
c-basic
cheese
cloc
clr-network-troubleshooter
cpio
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
devpkg-LVM2
devpkg-SDL
devpkg-acl
devpkg-alsa-lib
devpkg-apr
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-attr
devpkg-audit
devpkg-base
devpkg-boost
devpkg-cairo
devpkg-colord
devpkg-compat-enchant-soname1
devpkg-compat-fuse-soname2
devpkg-cryptsetup
devpkg-curl
devpkg-cyrus-sasl
devpkg-dbus
devpkg-dbus-glib
devpkg-e2fsprogs
devpkg-elfutils
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-gdk-pixbuf
devpkg-gflags
devpkg-glib
devpkg-glu
devpkg-gmime
devpkg-gnutls
devpkg-gobject-introspection
devpkg-googletest
devpkg-gperftools
devpkg-graphite
devpkg-gsl
devpkg-gtk-doc
devpkg-gtk3
devpkg-guile
devpkg-harfbuzz
devpkg-hwloc
devpkg-icu4c
devpkg-ipmctl
devpkg-ipset
devpkg-iptables
devpkg-iso-codes
devpkg-json-c
devpkg-json-glib
devpkg-kmod
devpkg-krb5
devpkg-lcms2
devpkg-libX11
devpkg-libXScrnSaver
devpkg-libXcursor
devpkg-libXft
devpkg-libXmu
devpkg-libXpm
devpkg-libXres
devpkg-libXt
devpkg-libXtst
devpkg-libXv
devpkg-libXvMC
devpkg-libXxf86misc
devpkg-libarchive
devpkg-libassuan
devpkg-libcap
devpkg-libcap-ng
devpkg-libcgroup
devpkg-libcroco
devpkg-libdatrie
devpkg-libdrm
devpkg-libepoxy
devpkg-libevdev
devpkg-libevent
devpkg-libffi
devpkg-libgpg-error
devpkg-libgudev
devpkg-libgusb
devpkg-libidn
devpkg-libidn2
devpkg-libinput
devpkg-libjpeg-turbo
devpkg-libmicrohttpd
devpkg-libmnl
devpkg-libnetfilter_conntrack
devpkg-libnetfilter_cthelper
devpkg-libnetfilter_cttimeout
devpkg-libnetfilter_queue
devpkg-libnfnetlink
devpkg-libnftnl
devpkg-libnl
devpkg-libpcap
devpkg-libpciaccess
devpkg-libpipeline
devpkg-libpng
devpkg-libpsl
devpkg-libpthread-stubs
devpkg-librsvg
devpkg-libseccomp
devpkg-libsoup
devpkg-libssh2
devpkg-libtasn1
devpkg-libthai
devpkg-libtirpc
devpkg-libunwind
devpkg-libusb
devpkg-libuser
devpkg-libvirt
devpkg-libxkbcommon
devpkg-libxml2
devpkg-libxslt
devpkg-llvm
devpkg-lua
devpkg-lz4
devpkg-mesa
devpkg-metrics-discovery
devpkg-mozjs52
devpkg-multipath-tools
devpkg-ncurses
devpkg-ndctl
devpkg-nettle
devpkg-nftables
devpkg-nghttp2
devpkg-nspr
devpkg-nss
devpkg-ntfs-3g
devpkg-oath-toolkit
devpkg-open-iscsi
devpkg-openmpi
devpkg-openssl
devpkg-openvswitch
devpkg-orc
devpkg-p11-kit
devpkg-pacrunner
devpkg-pango
devpkg-parted
devpkg-pciutils
devpkg-pcre
devpkg-pcre2
devpkg-pixman
devpkg-pkcs11-helper
devpkg-popt
devpkg-postgresql
devpkg-procps-ng
devpkg-qtbase
devpkg-qttools
devpkg-rdma-core
devpkg-readline
devpkg-rest
devpkg-shared-mime-info
devpkg-sqlite-autoconf
devpkg-startup-notification
devpkg-subunit
devpkg-systemd
devpkg-tiff
devpkg-usbredir
devpkg-userspace-rcu
devpkg-util-linux
devpkg-util-macros
devpkg-vala
devpkg-wayland
devpkg-wayland-protocols
devpkg-xapian-core
devpkg-xcb-proto
devpkg-xkeyboard-config
devpkg-xmlsec1
devpkg-xorgproto
devpkg-xtrans
devpkg-xz
devpkg-zlib
devpkg-zstd
diffutils
docbook-utils
docutils
dosfstools
doxygen
editors
editors-dev
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
gpgme
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
intltool
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-native
kvm-host
kvm-host-dev
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
libxml2
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
mail-utils-dev
make
minicom
mutt
nasm
nautilus
network-basic
network-basic-dev
nfs-utils
notmuch
offlineimap
openblas
openldap
openssh-server
openssl
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
p11-kit
parallel
parted
patch
perl-basic
perl-basic-dev
pmdk
polkit
powertop
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
qt-basic
qt-core
ruby-basic
samba
scons
seahorse
shells
smartmontools
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
texinfo
texlive
thermal_daemon
tmux
totem
tzdata
unzip
user-basic
user-basic-dev
valgrind
vim
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
yasm
znc
zsh
zstd

**Additional context**
So after this happened I plugged in another USB 2.0 Ethernet Adapter to the UGREEN one. Then changed the Ethernet cable to this new adapter. I can now see the un-managed Ethernet on the top right hand corner but not under settings (network)

picture of the exact same adapter
![image](https://user-images.githubusercontent.com/36279716/55265841-9f449500-523f-11e9-9108-0c1c89a2bdca.png)

Screenshot of how I am not able to see the network on GUI.
![Screenshot from 2019-03-29 11-28-10](https://user-images.githubusercontent.com/36279716/55265799-745a4100-523f-11e9-9506-51f53e3a7f37.png)

**Comment by miguelinux** [comment]
> **Describe the bug**
> Installed clear 28540 Desktop beta, I wanted to see the Ethernet information on the top right hand corner when I connected the multi-port adapter of the brand UGREEN. I saw none, then I opened the SETTINGS windows and navigated to the NETWORK section. I still could not see the information. Opened the console and I "ip address"  I could see the interface name an IP assigned and I can navigate on web.
> 

Clear Linux uses systemd-networkd to manage the Ethernet network, so it
is not managed by NetworkManager and is not displayed on top right icon.

CL team is working in a solution of this situation.

So, currently is expected that Ethernet network are not Managed/Showed
by NetworkManager.

**Comment by busykai** [comment]
This has been fixed in the latest release (e.g. 29280).
