### ISSUE TITLE
- fftw3.3 - Fast Fourier Transforms in Clear Linux - 

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#586]
Hi,

I should have the next package: libfftw3
this helps me make an analysis, to generate graphs.

http://www.fftw.org/#documentation

FFTW is a C subroutine library for computing the discrete Fourier transform (DFT) in one or more dimensions, of arbitrary input size, and of both real and complex data (as well as of even/odd data, i.e. the discrete cosine/sine transforms or DCT/DST). We believe that FFTW, which is free software, should become the FFT library of choice for most applications.

```
in other operating system I have:
 - libfftw3-3:amd64
 - libfftw3-bin 
 - libfftw3-dbg:amd64
 - libfftw3-dev:amd64
 - libfftw3-doc
 - libfftw3-double3:amd64
 - libfftw3-long3:amd64
 - libfftw3-mpi-dev:amd64
 - libfftw3-mpi3:amd64
 - libfftw3-quad3:amd64
 - libfftw3-single3:amd64
```

Thank you for your support.

**Comment by fenrus75** [comment]
$ swupd search fftw3
Bundle with the best search result:
     devpkg-fftw                        - All content for pkgconfig file
fftw.pc (installed)

This bundle can be installed with:

  swupd bundle-add  devpkg-fftw
