### ISSUE TITLE
should add fwupd

### ISSUE THREAD

**Issue by fenrus75** [clearlinux/distribution#59]
there's two projects called fwupd, we should add both

this allows you to update the bios and the like transparently

**Comment by phmccarty** [comment]
These have been added, right?

https://github.com/clearlinux-pkgs/fwupd
https://github.com/clearlinux-pkgs/fwupdate

**Comment by fenrus75** [comment]
the pieces exist...

.. but they need to be made to work

**Comment by superm1** [comment]
FWIW fwupdate was merged into fwupd with the [recent 1.1.0](https://github.com/hughsie/fwupd/releases/tag/1.1.0) release.  No need to support fwupdate separately.

**Comment by xlfe** [comment]
Doesn't seem to be working as of today - see #155

**Comment by superm1** [comment]
Please add `--verbose` to the service start and hopefully it will explain what's going wrong.

**Comment by superm1** [comment]
And you should probably open this in a new bug as it's certainly something new.

**Comment by thiagomacieira** [comment]
He did, #155

**Comment by superm1** [comment]
That one is already closed and also conflating multiple issues.
```
Aug 24 03:29:20 clr systemd[1]: fwupd.service: Main process exited, code=exited, status=226/NAMESPACE
```
is not the same as:

```
Apr 08 15:11:41 ck systemd[1]: fwupd.service: Main process exited, code=exited, status=203/EXEC
```

**Comment by xlfe** [comment]
@superm1 sorry new bug lodged #604
