### ISSUE TITLE
Does Clear support Intel Parallel Studio XE?  

### ISSUE THREAD

**Issue by DavidKz** [clearlinux/distribution#590]
We have a site license for IPS XE 2019, and I wondered if anyone on the dev team tried Intel tooling on an Intel OS.  
If so, please share any gotchas or tips that would help during install/usage.

**Comment by DavidKz** [comment]
During installation, it gives a "distribution is not supported" error, but otherwise appears fully functional.

**Comment by thiagomacieira** [comment]
We're working with them to make it not say that, but everything works fine for me.

Well, I only test the compiler, not the rest of the Studio...

**Comment by olegmikul** [comment]
It can't install GUI for some part of Studio. It is strange, I have all relevant libraries installed in /usr/lib64 (e.g. libXss.so), but installer can't find them. Not sure if it is an issue of Clear Linux or Parallel Studio. But it makes Intel Inspector not installed and Intel VtuneAmplifier quite useless. Compilers and libraries are fine.
