### ISSUE TITLE
The pam_loginuid is missing from some PAM configuration files

### ISSUE THREAD

**Issue by mpurzynski** [clearlinux/distribution#595]
The pam_loginuid module sets the loginuid process attribute for the process that was authenticated.
This preserves the original uid across setuid() calls.

Functionality like this is important from the Incident Response point of view. It allows tracing a given process'es ownership down to the original user.

- we see a process kthread running as root
- the original uid of the process is 1001 and that means michal started it and process later called a setuid()

From the "man pam_loginuid"

This PAM module should only be used for entry point applications like: login, sshd, gdm, vsftpd, crond and atd. There are probably other entry point applications besides these. You should not use it for applications like sudo or su as that defeats the purpose by changing the loginuid to the account they just switched to.

This could be accomplished by
- removing the pam_loginuid from the systemd-user
- adding the pam_loginuid to common-session and maybe other places

One more thing that needs to happen is adding the "audit=1" kernel parameter if the auditd service is installed and scheduled to start at boot (I think this is the default already)
There are two reasons to do it:
- correctly auditing the uid of every startup process and each child
- preserving the original uid across the auditd service restart

The original man page tells to enable the loginuid module for cron and atd. We use systemd-timers - how do we make sure the original uid is preserved here?

**Comment by ahkok** [comment]
> removing the pam_loginuid from the systemd-user

Why? This is run either from like `gdm`, or, some unit that has `User=foo`. In both cases, this is like a login (at/cron-like).

**Comment by ahkok** [comment]
My local testing with only adding `pam_loginuid.so` to common-session are good and function as expected for e.g. `sshd`. So I will push that.

**Comment by ahkok** [comment]
`Linux-PAM-1.3.1-38`
