### ISSUE TITLE
gedit unable to load python plugins

### ISSUE THREAD

**Issue by sunnyflunk** [clearlinux/distribution#596]
**Describe the bug**
Gedit is unable to load python plugins due to missing support in `libpeas`.  Other gnome programs with python plugins will also have this issue. From strace:

```
(org.gnome.gedit:14398): libpeas-WARNING **: 10:06:49.005: Failed to load module 'python3loader': /usr/lib64/libpeas-1.0/loaders/libpython3loader.so: cannot open shared object file: No such file or directory
)
(org.gnome.gedit:14398): libpeas-WARNING **: 10:06:49.005: Could not load plugin loader 'python3'
```

**To resolve**
I basically fixed it, but need some more practice with clr packaging:

1. Remove `pygobject-3.0` from `pkgconfig_ban`
2. Add `--disable-python2` to `configure` (or it will try but fail to build python2 extensions as pygobject is python3 only)
3. autospec it

**To Reproduce**
1. Open Gedit
2. Enable 'External Tools' plugin (get red ! as fails to load)

**Expected behavior**
Plugin to load successfully

**Comment by ahkok** [comment]
`libpeas-1.22.0-10`
