### ISSUE TITLE
Clear Linux kernel panics at boot in qemu on macOS results

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#6]
In researching [this issue](https://github.com/clearlinux/distribution/issues/5), I found this.

**Summary**

Booting Clear Linux in qemu on macOS results in a kernel panic on the Clear Linux guest.

**Steps to Reproduce**
1. Install qemu 2.11 via [Homebrew](https://github.com/Homebrew/brew)
2. Configure a hard drive
`$ qemu-img create clearlinux.qcow 5G`
3. Boot Clear Linux iso installer
`qemu-system-x86_64 -hda clearlinux.qcow -cdrom clear-20240-installer.iso -m 4000`

**Expected Results**
Clear Linux can boot within a generic qemu environment, particularly given it's relationship with KVM project.

**Actual Results**
Clear Linux kernel panics on boot.

![screen shot 2018-01-08 at 6 05 49 pm](https://user-images.githubusercontent.com/33820650/34697852-0e2347d8-f4a3-11e7-94d3-054f70052477.png)

**Comment by fenrus75** [comment]
which cpu is qemu trying to emulate?
normally I pass "-cpu host" as option

**Comment by sirredbeard** [comment]
@fenrus75 

I hadn’t specified a cpu, so it was defaulting to either qemu64 or base.

I tried with

`$ qemu-system-x86_64 -hda clearlinux.qcow -cdrom clear-20240-installer.iso -m 4000 -cpu core2duo`
`... -cpu qemu64`
`... -cpu base`

And got similar crashes.

**But**, you were correct, specifying something that matches the host works:

`...-cpu haswell`
`...-cpu max`

though worked well.

I am closing this issue because it seems the bug is in qemu, not Clear Linux.
