### ISSUE TITLE
bundle request : gtkwave

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#603]
**Is your feature request related to a problem? Please describe.**
gtkwave is useful to display signal traces files

**Describe the solution you'd like**
a gtkwave bundle available to install

**Describe alternatives you've considered**
Building gtkwave manually.
But we seem to miss some dependencies, like tcl-devel

**Additional context**
Installed version: 28680

**Comment by ahkok** [comment]
Looks like @fenrus75 already has this packaged, should be 1-2 days before it will be available.

**Comment by nsauzede** [comment]
yup ! it's present in 28720 !!
awesome thanks

*however*, when I was trying to install it, I just did, and got this :
~$ gtkwave
gtkwave: command not found
~$ swupd search gtkwave
Traceback (most recent call last):
  File "/usr/bin/swupd-search", line 578, in <module>
    main()
  File "/usr/bin/swupd-search", line 560, in main
    parse_MOM(get_version())
  File "/usr/bin/swupd-search", line 210, in parse_MOM
    for line in lines:
TypeError: 'NoneType' object is not iterable
This program must be run as root..aborting.

**Comment by nsauzede** [comment]
not pretty
