### ISSUE TITLE
Set focus to newly-opened terminal so you don't have to click it and then type...

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#605]
**Is your feature request related to a problem? Please describe.**
Yes.  When you start a new Terminal window, the focus is not set to it automatically so you can't start typing right away.  You have to manually click into the terminal before you can start typing.  Kind of annoying.  Confirmed on Clear 28710.  

**Describe the solution you'd like**
Set the focus to the newly-opened terminal automatically.  

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by iphutch** [comment]
@mrkz, @AthenasJimenez could you please look into whether this is a quick change?

**Comment by sunnyflunk** [comment]
I dropped Gnome for plasma, so can't test this, but is supposedly this patch to fix https://gitlab.gnome.org/GNOME/mutter/commit/9d49e8abd077941b126685dde3b64753cc4fc916

From the original issue https://gitlab.gnome.org/GNOME/mutter/issues/505

**Comment by mrkz** [comment]
testing it atm

**Comment by mrkz** [comment]
it effectively fixes the issue, so I'm pushing a change cherry-picking the commit pointed out by @sunnyflunk and launching a new build of the package.

I'll close this once a release with the fix is available.

Thanks for your contribution @sunnyflunk :tada:

**Comment by mrkz** [comment]
Closing now, as the fix is available on CLR release **28730**.

Thanks for the report.
