### ISSUE TITLE
Additions to desktop-kde bundle

### ISSUE THREAD

**Issue by sunnyflunk** [clearlinux/distribution#608]
**Is your feature request related to a problem? Please describe.**
Currently `user-manager` is unusable via the `desktop-kde` bundle. It lacks `accountsservice` to show/change user information and the polkit agent to authenticate changes which require password entry (such as adding a new user). 

Bluetooth is missing the services for activation, while the library was most likely there, the `bluez-services` part is vital! I installed `hardware-bluetooth` to remedy (as the smallest bundle to get it installed), but the included extras shouldn't be needed.

Many places using QML (fonts settings) looked awful and could crash plasmashell frequently. I finally figured out it was due to `qqc2-desktop-style` not being installed so buttons/widgets were missing! I think these are only used for the plasma desktop, but may have changed.

**Describe the solution you'd like**
[ ] Autospec this as a new package addition to CLR and add to `desktop-kde` bundle https://download.kde.org/stable/plasma/5.15.4/polkit-kde-agent-1-5.15.4.tar.xz
[ ] Also add `accountsservice`, `bluez` and `qqc2-desktop-style` so they are installed with the `desktop-kde` bundle. This can be whatever method is deemed best, dep of a package, or straight listing in the bundle. `qqc2-desktop-style` is technically a framework.

**Additional context**
This will fix other instances of polkit interaction on plasma, currently it can't prompt for your password via polkit, which breaks many features!

**Comment by sunnyflunk** [comment]
Added another fix :D

**Comment by iphutch** [comment]
@anselmolsm could you please take a look.

**Comment by Drakota** [comment]
@sunnyflunk There's seems to be missing the Open File dialog too, Firefox "Save image as..." or opening file in VSCode both crash the applications.

**Comment by sunnyflunk** [comment]
@Drakota Easy peasy!

```
(crashreporter:26573): GdkPixbuf-WARNING **: 08:19:28.146: Cannot open pixbuf loader module file '/usr/lib64/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory
```

The file belongs to this package `gdk-pixbuf-2.36.12-56.x86_64.rpm` which after extracting the problem is solved (and many, many others such as the minimize/maximize/close buttons now show when you remove the titlebar, which I recall reading another bug report here on that issue). Almost all of gdk-pixbuf is pulled in already as deps of GTK. However, the cache files are separated in the main package and there's no binary relation to pull them in.

Adding `gdk-pixbuf` in some way will resolve most gtk issues currently seen on plasma.

**Comment by anselmolsm** [comment]
Thanks for the info @Drakota and @sunnyflunk . I'll review this and apply the necessary updates.

**Comment by anselmolsm** [comment]
@fenrus75 handled most of it, I pushed the patch linked above (released in 28790) and qqc2-desktop-style in desktop-kde (28910). Closing this one, thanks.
