### ISSUE TITLE
No SMBIOS backends available

### ISSUE THREAD

**Issue by Drakota** [clearlinux/distribution#609]
Hi, when booting into a clean install of Clear Linux with my Dell Inspiron 15 7559 I get those messages: 
`dell_smbios: No SMBIOS backends avalaible`
`dell_smbios: No dell-smbios drivers are loaded`

It doesn't prevent me from booting and using the distro, but this only happens on Clear Linux.

Thanks for helping.

**To Reproduce**
1.  Have an Inspiron 15 7559
2. Update BIOS to newest 1.30
3. Clean install
4. Boot

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
```
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28740
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

```

**Comment by miguelinux** [comment]
CONFIG_DELL_SMBIOS_WMI is not set, fixing it now.

**Comment by miguelinux** [comment]
> CONFIG_DELL_SMBIOS_WMI is not set, fixing it now.
> 

Added at 5.0.7-729, please try by tomorrow release.

**Comment by Drakota** [comment]
Wow, thanks for the fast response, really enjoying the work on the distro, keep it up!
