### ISSUE TITLE
Various fonts have "for Powerline" in their name

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#61]
Examples: Inconsolata, DejaVu and Ubuntu Mono. Not sure if this is by design or is unintended. Would be nice to have those fonts (with their non suffixed names).

**Comment by iphutch** [comment]
@mrkz

**Comment by matthewrsj** [comment]
I believe that is normal. In other distributions I have installed powerline-specific fonts and they always have powerline in their name. Here's a doc on installing powerline fonts. You'll notice "for Powerline" is in the names http://powerline.readthedocs.io/en/master/installation/linux.html

**Comment by tomByrer** [comment]
Powerline is just a few extra gliphs to help with CLI & editor outputs:

https://powerline.readthedocs.io/en/latest/overview.html#screenshots
