### ISSUE TITLE
Make Clear Linux* backgrounds available

### ISSUE THREAD

**Issue by Drakota** [clearlinux/distribution#610]
Hi, I just thought I'd would be nice to make the default Gnome Clear Linux* backgrounds available to all Desktop Environments or make it available through the official site, albeit a small enhancement and I think it would benefit other desktop users.

Thanks and keep up the good work with the distro.

**Comment by ahkok** [comment]
They are now all available here:

https://github.com/clearlinux/clr-wallpapers
