### ISSUE TITLE
epydoc bundle ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#611]
**Is your feature request related to a problem? Please describe.**
"epydoc" is a python tool generate python documentation; it seems not available in CLR

**Describe the solution you'd like**
It would be nice to have it available

**Describe alternatives you've considered**
Build/install it manually ? not ideal

**Additional context**
running CLR 28750

**Comment by miguelinux** [comment]
Arjan already added.

Look for it at > 28770 clear linux release.

at python-extras bundle

**Comment by nsauzede** [comment]
I've tested epydoc, and it seems to fail :
~$ python --version
Python 3.7.2
~$ which python
/usr/bin/python
~$ which epydoc
/usr/bin/epydoc
~$ epydoc
Traceback (most recent call last):
  File "/usr/bin/epydoc", line 12, in <module>
    from epydoc.cli import cli
  File "/usr/lib/python3.7/site-packages/epydoc/cli.py", line 428
    print '\n' + msg.rstrip() + '\n'
             ^
SyntaxError: invalid syntax

**Comment by nsauzede** [comment]
~$ cat /etc/os-release 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28800
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**Comment by sunnyflunk** [comment]
`epydoc` would be written for python 2.5 as last release was 11 years ago, so may need patching to run on the latest python 2 release, let alone python 3.

**Comment by nsauzede** [comment]
Strange, here is what I see in Ubuntu18.10 :

> ~$ lsb_release -a
>No LSB modules are available.
>Distributor ID:	Ubuntu
>Description:	Ubuntu 18.10
>Release:	18.10
>Codename:	cosmic
>~$ python2 --version
>Python 2.7.15+
>~$ head -n1 /usr/bin/epydoc
>#! /usr/bin/python2
>~$ epydoc --version
>Epydoc, version 3.0.1

**Comment by puneetse** [comment]
Given that epydoc is not under active development and that Clear Linux has effectively removed python2 from the distro, epydoc should be removed.

**Comment by bryteise** [comment]
Unfortunate it is abandoned, kicking it out of the distro since it doesn't work anyway without python2.
