### ISSUE TITLE
swupd search return Python Traceback

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#612]
**Describe the bug**
With CLR 28750 it seems like swupd search without root returns a Python Traceback

**To Reproduce**
$ swupd search epydoc
Traceback (most recent call last):
  File "/usr/bin/swupd-search", line 578, in <module>
    main()
  File "/usr/bin/swupd-search", line 560, in main
    parse_MOM(get_version())
  File "/usr/bin/swupd-search", line 210, in parse_MOM
    for line in lines:
TypeError: 'NoneType' object is not iterable
This program must be run as root..aborting.

**Expected behavior**
It is expected to not get Python Traceback but instead a concise error message

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28750
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
 - Bundles: [e.g. `sudo swupd bundle-list`]
$ sudo swupd bundle-list
NetworkManager
acpica-unix2
alsa-utils
ansible
baobab
bc
bcc
binutils
bison
bootloader
c-basic
ceph
cheese
cloc
clr-installer
clr-network-troubleshooter
containers-basic
cpio
curl
cve-bin-tool
ddd
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-gui
devpkg-SDL2
devpkg-atk
devpkg-base
devpkg-cairo
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-gdk-pixbuf
devpkg-glib
devpkg-graphite
devpkg-gtk
devpkg-harfbuzz
devpkg-libX11
devpkg-libdrm
devpkg-libffi
devpkg-libpng
devpkg-libpthread-stubs
devpkg-llvm
devpkg-mesa
devpkg-openssl
devpkg-pango
devpkg-pcre
devpkg-pixman
devpkg-util-linux
devpkg-xorgproto
devpkg-xz
devpkg-zlib
diffutils
dnf
docutils
dosfstools
doxygen
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
go-basic
graphviz
gstreamer
gtkwave
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iotop
ipmitool
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-lts
kernel-lts2018
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
locales
make
man-pages
meld
minicom
nasm
nautilus
network-basic
nfs-utils
nginx
openblas
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
package-utils
parallel
parted
patch
performance-tools
perl-basic
pmdk
polkit
powertop
pulseaudio
pxe-server
pygobject
python2-basic
python3-basic
qemu-guest-additions
qt-basic
qt-core
ruby-basic
samba
seahorse
smartmontools
storage-utils
strace
sudo
sysadmin-basic
sysadmin-hostmgmt
syslinux
sysstat
tcl-basic
telemetrics
texlive
thermal_daemon
tmux
totem
tzdata
unzip
valgrind
vim
webkitgtk
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
zip
znc
zstd

**Comment by ahkok** [comment]
```
$ sudo swupd-search pycryptsetup
Traceback (most recent call last):
  File "/usr/bin/swupd-search", line 578, in <module>
    main()
  File "/usr/bin/swupd-search", line 560, in main
    parse_MOM(get_version())
  File "/usr/bin/swupd-search", line 210, in parse_MOM
    for line in lines:
TypeError: 'NoneType' object is not iterable
```

**Comment by tpleavitt** [comment]
Checking this on version 28880, these errors are not showing.  Closing
