### ISSUE TITLE
swupd bundle-remove improvements

### ISSUE THREAD

**Issue by clsulliv** [clearlinux/distribution#616]
**Is your feature request related to a problem? Please describe.**

swupd bundle-remove prints an excessively large dependency tree and its difficult to actually remove bundles at times.

For reference, I tried to remove 'c-basic' from a machine that has 586 bundles installed (many devpkgs, desktop bundles, -dev bundles, etc). This resulted in bundle-remove spewing 24830 lines into my terminal. Sorting through those lines, there's actually only ~360 bundles that depend on it.

**Describe the solution you'd like**
With high bundle counts it may be wise to not print the entire tree, and instead print a simple dependency list, preferably with leaf nodes printed first, followed by those only depending on the leaf nodes, and so on.

It would also be nice to be able to remove a bundle and anything that depends on it in one command.

**Describe alternatives you've considered**
If I actually wanted to remove c-basic from my system right now, the way I'd do it is 'swupd bundle-remove <those 360 bundles>' in a loop. Its not too pretty but it would work eventually.

**Additional context**

**Comment by phmccarty** [comment]
This type of request should probably be filed at clearlinux/swupd-client.

**Comment by clsulliv** [comment]
Oops, moved it over there.
