### ISSUE TITLE
g++ regression ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#617]
**Describe the bug**
When trying to compile a simple C++ source file, G++ spit an header error

**To Reproduce**
$ g++ --version
g++ (Clear Linux OS for Intel Architecture) 8.3.1 20190411 gcc-8-branch@270270
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ cat main.cpp 
#include <map>
int main() {
	return 0;
}
$ g++ main.cpp
In file included from /usr/include/c++/bits/stl_algobase.h:59,
                 from /usr/include/c++/bits/stl_tree.h:63,
                 from /usr/include/c++/map:60,
                 from main.cpp:1:
/usr/include/c++/x86_64-generic-linux/bits/c++config.h:509:10: fatal error: bits/os_defines.h: No such file or directory
 #include <bits/os_defines.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

**Expected behavior**
G++ should compile the file without error.

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
$ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28800
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
$ sudo swupd bundle-list
Babel
NetworkManager
Sphinx
acpica-unix2
alsa-utils
ansible
baobab
bc
bcc
binutils
bison
bootloader
c-basic
ceph
cheese
cloc
cloud-api
clr-installer
clr-network-troubleshooter
compat-common
containers-basic
cpio
curl
cve-bin-tool
ddd
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-gui
devpkg-SDL2
devpkg-atk
devpkg-base
devpkg-cairo
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-gdk-pixbuf
devpkg-glib
devpkg-graphite
devpkg-gtk
devpkg-harfbuzz
devpkg-libX11
devpkg-libdrm
devpkg-libffi
devpkg-libpng
devpkg-libpthread-stubs
devpkg-llvm
devpkg-mesa
devpkg-openssl
devpkg-pango
devpkg-pcre
devpkg-pixman
devpkg-util-linux
devpkg-xorgproto
devpkg-xz
devpkg-zlib
diffutils
dnf
docutils
dosfstools
doxygen
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
fwupdate
gdb
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
go-basic
graphviz
gstreamer
gtkwave
gvim
gzip
hardware-printing
hardware-uefi
htop
icdiff
inotify-tools
iotop
ipmitool
iproute2
iptables
irssi
joe
kbd
kernel-install
kernel-lts
kernel-lts2018
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
locales
make
man-pages
meld
minicom
nasm
nautilus
net-tools
network-basic
nfs-utils
nginx
openblas
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
package-utils
parallel
parted
patch
performance-tools
perl-basic
pmdk
polkit
powertop
procps-ng
pulseaudio
pxe-server
pygobject
python-extras
python2-basic
python3-basic
python3-tcl
qemu-guest-additions
qt-basic
qt-core
ruby-basic
samba
seahorse
smartmontools
storage-utils
strace
sudo
sysadmin-basic
sysadmin-hostmgmt
syslinux
sysstat
tcl-basic
telemetrics
texlive
thermal_daemon
tmux
totem
tzdata
unzip
valgrind
vim
webkitgtk
weechat
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
zip
znc
zstd

**Comment by mrkz** [comment]
@thiagomacieira

**Comment by ahkok** [comment]
Please run `sudo swupd verify --fix` - this will put the missing files back into place.

**Comment by phmccarty** [comment]
The file disappeared as a result of a swupd bug.

A bug was filed yesterday, and you can track its progress at https://github.com/clearlinux/swupd-client/issues/890

A verify/fix will install the missing file(s), as @ahkok notes.

**Comment by nsauzede** [comment]
Yup, that fixed my issue.
But is it possible for CLR to "automagically" detect such cases where swupd (or anything) messed up the integrity of the system, and suggest this valuable advice in a message ? (DBUS, popup, etc..)
Because I guess I'm not first to have faced this, and probably it can repeat in the future ?
it would spare people to investigate/loose time ?
Thanks

**Comment by phmccarty** [comment]
@nsauzede I thought of a feature request for swupd that might help improve the experience in this scenario in the future. See https://github.com/clearlinux/swupd-client/issues/894
