### ISSUE TITLE
Courtesy question: Load on Clearlinux servers

### ISSUE THREAD

**Issue by DavidKz** [clearlinux/distribution#618]
I'm writing a script that will fetch the Clear Linux patch files for kernel, libc, and major math packages.  Basically, given a kernel or software version #, it would return the ClearLinux release #s that contained it. The goal is to get the patches, not download the entire source, if possible.  Something like the following was suggested on Reddit, to find source RPMs for the 4.8.0 kernel:

wget -nv --spider -r -np https://cdn.download.clearlinux.org/releases/ 2>&1 | grep linux-4.8.0

 I won't use that exactly, due to the transactions involved for only one query. But something similar that can create a table of (Clear release #) x (software/library name), with cells containing the version number.

But I wanted to check with the Clear devs here first, to ensure that this wouldn't put undue loads on the download.clearlinux.org domain, or possible interfere with other resources.

**Comment by clsulliv** [comment]
I can't say whether what you're wanting to do would cause undue stress on the servers, but I think the package-source files would supply the information you're looking for to create the table. E.g., https://cdn.download.clearlinux.org/releases/28800/clear/source/package-sources

**Comment by miguelinux** [comment]
Please do not use old version of any package, it could contains security
holes that was resolved in a newer version.

**Comment by thiagomacieira** [comment]
You may want to use the Git repositories instead:
* https://github.com/clearlinux/distribution/issues/618
* https://github.com/clearlinux-pkgs/linux
etc.

**Comment by DavidKz** [comment]
Excellent!  Thanks @clsulliv and @thiagomacieira.  The package-source file is a consistent one file download that will pair package versions to kernel and release.  The git repos will be icing on the cake.

Thank you for the warning, @miguelinux.  Nothing older is going to get near production.  My main reason for pairing kernels and releases is to track any changes in the Intel patch set, i.e., if they change slightly with upstream changes in the kernel.  I have a feeling git provides this functionality, and I was reinventing wheels with a carpenter's square.. :)

**Comment by DavidKz** [comment]
I've put together a workable script that uses git and has SQL-like user facing options.  Intel's servers are safe... for now!  :)
