### ISSUE TITLE
No exfat support.

### ISSUE THREAD

**Issue by sofar** [clearlinux/distribution#62]
Attempting to use a 64gb SD card from my digital camera (which requires me to use exfat due to the FS size restrictions) results in an unreadable card in Clear Linux OS.

**Comment by miguelinux** [comment]
Is fthe device

**Comment by sofar** [comment]
Its a standard SD card., and I was using `mount` from the console.

**Comment by Andy2244** [comment]
In the past i used this [method](https://github.com/dorimanx/exfat-nofuse) (dkms) to get exfat support, really wish MS would opensource it so it can get into the kernel. Its one of the only simple FS with >4gb file size support, that work well on linux, windows and mac.

**Comment by seanvk** [comment]
@sofar I'd like to add my interest in seeing fuse exfat utilities supported.  I use exfat for sharing data between Linux and other OS and find it handy for backup and restore.

**Comment by ms178** [comment]
I am trying out the new Clear Linux desktop ISO right now and wanted to get some data on the machine from an USB stick which needs exfat support. Is there any progress on this?

**Comment by esurharun** [comment]
Waiting for this issue to get fixed as soon as possible. At the same time i already patched exfat-nofuse kernel module for Linux 5.x kernel and put it to https://github.com/esurharun/exfat . You will just need to bundle it together.

**Comment by esurharun** [comment]
And for the ones whom needs exfat support immediately.. they can reach out for exfat-fuse at https://github.com/relan/exfat

**Comment by rawsh** [comment]
For people trying to compile exfat on clear linux getting this:

```
./configure: line 4101: syntax error near unexpected token `UBLIO,'
./configure: line 4101: `PKG_CHECK_MODULES(UBLIO, libublio,'
```

It turns out I had no pkg.m4 so I just put one into the m4 folder and ran `aclocal -I m4` then `autoreconf -i -f` with `AC_CONFIG_MACRO_DIR([m4])` in my configure.ac

**Comment by zehnm** [comment]
I also wish exfat could be easily installed with swupd.

Thanks to @rawsh I was able to get it running after some try and error.
Here's what I did in Clear Linux 30320:

1. Install dependencies

        sudo swupd bundle-add wget fuse devpkg-compat-fuse-soname2

1. Get exfat sources

        git clone https://github.com/relan/exfat.git
        cd exfat

1. Install into /usr/local/bin instead of /usr/local/sbin:

        find . -name "Makefile.am" -print0 | xargs -0 sed -i 's/sbin_PROGRAMS/bin_PROGRAMS/g'

1. Get pkg.m4 from first Google hit:

        wget -P m4 https://raw.githubusercontent.com/irungentoo/toxcore/master/m4/pkg.m4
        echo "AC_CONFIG_MACRO_DIR([m4])" >> configure.ac
        aclocal -I m4

1. Build & install

        autoreconf -i -f
        ./configure
        make
        sudo make install

**Comment by ms178** [comment]
There are discussions to integrate exFAT support inside the Kernel, see: https://www.phoronix.com/scan.php?page=news_item&px=Linux-exFAT-2019-Discussion 

That would make it even easier. :)

**Comment by jario49** [comment]
Thanks @zehnm  for the step by step guide.
Encountered an error though on step 5. Was able to resolve by changing the sbin directory to bin in the configure script:
`perl -i -pe 's/\/sbin/\/bin/g' configure`

Then after the "sudo make install" command I made a link in the /usr/bin directory for mount.exfat:
    `cd /usr/bin`
    `sudo ln -s /usr/local/bin/mount.exfat`

This made it possible for nautilus to use the mount executable automatically.
Again thanks everyon for this helpful post :)

**Comment by mns6070** [comment]
Microsoft announced today that exFAT can be added to the Linux kernel. https://cloudblogs.microsoft.com/opensource/2019/08/28/exfat-linux-kernel/

**Comment by ahkok** [comment]
Yes, we discussed it on the IRC channel earlier as well. We're totes excite about it.

The kernel patch is for `/staging` and I'll discuss the idea of carrying the patch until it moves into a release. Then we also need to discuss userspace tools, of course.

But it's a nice step forward.

**Comment by miguelinux** [comment]
@ahkok please test our `-native` kernel, it has the ExFAT modules enabled.
