### ISSUE TITLE
network-basic bundle bloated for a minimal install

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#620]
I installed a fresh instance of Clear Linux for a server and was surprised to see weechat in the bundles list, due to it being included in the network-basic bundle.

weechat, irssi, and wpa_supplicant are not something I'd expect/want on a minimal install out of the box For example, I see the network-basic is included in the hyperv, kvm, azure images. Of course, I can remove the network-basic bundle and install individual pieces but seems to defeat the purpose a bit.

Could the network-basic bundle use some slimming? Or maybe a different bundle for irc clients?

**Comment by fenrus75** [comment]
weechat is indeed questionable...
wpa_supplicant is not just for wifi, also for enterprise ethernet
