### ISSUE TITLE
Invalid syntax in /usr/share/applications/org.gnome.font-viewer.desktop 

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#623]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/ttf" is an invalid MIME type ("font" is an unregistered media type)
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/otf" is an invalid MIME type ("font" is an unregistered media type)

**To Reproduce**
1. under gnome wayland  environment
2. install gnome-font-viewer if not present
3. run: sudo update-desktop-database

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by sunnyflunk** [comment]
`desktop-file-utils` needs this upstream patch https://gitlab.freedesktop.org/xdg/desktop-file-utils/commit/92af4108750ceaf4191fd54e255885c7d8a78b70.patch

By 2025, they may tag a new release with it in!

**Comment by phmccarty** [comment]
@sunnyflunk I've imported that patch for `desktop-file-utils`. It should be in a release tomorrow. Thanks for the help!

**Comment by phmccarty** [comment]
Merged in build 28890.

**Comment by abdelrahmangaber93** [comment]
i have the same problem and i cant find solution 
help me

**Comment by phmccarty** [comment]
@abdelrahmangaber93 This issue should be fixed in release 28890. What version of Clear Linux OS are you running?

**Comment by abdelrahmangaber93** [comment]
linux deepin 15.9
