### ISSUE TITLE
cups-browsed broken

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#624]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
The cups-browsed service won't start.

**To Reproduce**
```
$ sudo systemctl start cups-browsed
Failed to start cups-browsed.service: Unit org.cups.cupsd.service not found.
```

**Expected behavior**
Service should start.

**Comment by sunnyflunk** [comment]
https://github.com/clearlinux-pkgs/cups-filters/blob/master/0001-fix-systemd-service-file.patch most likely needs to be updated to the shortened `cupsd.service` after the `org.cups.` prefixes were removed in `cups`

**Comment by bwarden** [comment]
Fixed service unit name in cups-filters-1.22.5-45, although I'm not certain this is the only issue.

**Comment by bwarden** [comment]
Ah, right, discovery itself is probably not going to work without avahi, which is a separate discussion.

**Comment by pceiley** [comment]
Yep. Didn't want to lump that in with this bug 😊
