### ISSUE TITLE
Bundle request for RStudio

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#626]
Please consider to add RStudio bundle.

Previously it needs deprecated components from Qt <= 5.5 to build from the source. In one of the recent release it migrated to newer Qt framework and thus I think we can add an RStudio budnle now.

**Comment by thiagomacieira** [comment]
I'll take a look at what it takes.

**Comment by thiagomacieira** [comment]
Weird package with the need for some bundled dependencies. But I got it built.

**Comment by lebensterben** [comment]
>Weird package with the need for some bundled dependencies. But I got it built.

@thiagomacieira If I remember it correctly, it will put dependencies under /opt directory, would you check whether it's safe to remove them? And if not, shall I just leave them there, not maintained by swupd utility?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thiagomacieira** [comment]
Added, will be in the next release (Monday). The bundle is called `R-rstudio`
