### ISSUE TITLE
Fuse module does not load automatically

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#627]
**Describe the bug**
Fuse module doesn't load automatically. This causes #451, and possibly other issues.

**To Reproduce**
GnomeMpv Flatpak runs, but won't play media
```
$ flatpak run io.github.GnomeMpv
flatpak run: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs
Gtk-Message: 18:52:13.696: Failed to load module "pk-gtk-module"
Gtk-Message: 18:52:13.698: Failed to load module "pk-gtk-module"
```
I checked and the fuse module was not loaded
```
$ lsmod |grep fuse
$
```
Loading the module manually via `$ modprobe fuse` resolves the issue (until the system is rebooted).

**Expected behavior**
Fuse module to be loaded (at boot? or when required?)

**Comment by bwarden** [comment]
FUSE support is built into the kernel as of 5.0.7-730, so this should no longer be an issue. Tested video playback successfully on my system.

**Comment by pceiley** [comment]
Thanks!

**Comment by pceiley** [comment]
hi @bwarden,

Any chance this could also be applied to other kernels, such as lts2018? I tried it using this kernel and it's broken.

**Comment by miguelinux** [comment]
Done,

Test in the next public release.
