### ISSUE TITLE
Build docker with seccomp enabled

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#630]
**Is your feature request related to a problem? Please describe.**
docker [does not appear to be built](https://github.com/clearlinux-pkgs/docker/blob/master/docker.spec) with [seccomp enabled](https://docs.docker.com/engine/security/seccomp/)

**Describe the solution you'd like**
Add __seccomp__ flag to docker in the rpm?

**Describe alternatives you've considered**
I guess I could build and install it myself?

**Comment by fenrus75** [comment]
good catch; fixing this now.
hopefully will make tomorrow's build

**Comment by fenrus75** [comment]
hmm this is slightly odd; ldd implies that docker already had this

**Comment by fenrus75** [comment]
found it; will be fixed
