### ISSUE TITLE
Bundle for ZFS drivers

### ISSUE THREAD

**Issue by darkdragon-001** [clearlinux/distribution#631]
Please add a bundle to mount and manage ZFS volumes in Clear Linux.

**Comment by ahkok** [comment]
Unlikely this will happen. Please consider using `btrfs` which is supported out of the box, or compile the drivers yourself.

**Comment by darkdragon-001** [comment]
Usually, I usually prefer `btrfs` over `zfs`, but this time I want to add an SSD cache to my HDD raid for speed reasons. Sadly, `btrfs` has no easy support for this...

**Comment by ahkok** [comment]
This seems unreasonable to keep open unless licensing concerns are addressed by the copyright owner of this code.

**Comment by redbal** [comment]
I was able to successfully compile ZFS on linux and have the resulting working binaries, but can't get the kernel module to load: modprobe: ERROR: could not insert 'zfs': Required key not available. I'm not sure what this means, but would like to get it sorted out if anyone has some ideas.

**Comment by bryteise** [comment]
@redbal This might be better talked about on the [forums](https://community.clearlinux.org/) but I think you need to pass a special kernel commandline [flag](https://github.com/clearlinux-pkgs/linux-lts2018/blob/master/0119-Add-boot-option-to-allow-unsigned-modules.patch) and use an lts kernel (though I didn't check which of the kernels had this patch so you might see more of them).

**Comment by bryteise** [comment]
@puneetse Do we have documentation that talks about using unsigned kernel modules?

**Comment by fenrus75** [comment]
easiest is to install the dkms bundle for the kernel in question

**Comment by puneetse** [comment]
@bryteise yes, these two documents:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules-dkms

**Comment by redbal** [comment]
@bryteise Wow! we must be on the same wavelength...I just completed the steps in https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules and was able to recompile and load the zfs modules. Now, zfs and zpool works perfectly on clearlinux.  Thanks

**Comment by jimsalterjrs** [comment]
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules 404s now.

Has this document moved? I wasn't able to find it searching the site for "kernel modules".

**Comment by jimsalterjrs** [comment]
@redbal how did you resolve the uuid.h missing problem? Or did you encounter that? I found a web.archive.org snapshot of the removed kernel-modules document and got through that, but when attempting to ./configure the ZFS module, I end up with:

~~~~
configure: error: in `/home/jim/zfs-0.8.3':
configure: error:
           *** uuid/uuid.h missing, libuuid-devel package required
See `config.log' for more details.
~~~~

Haven't been able to figure out _where_ the configure script is looking for uuid.h (which is present on the system itself), so I'm stuck.

**Comment by redbal** [comment]
@jim  sorry, no...I've moved on to another platform.

**Comment by miguelinux** [comment]
> https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules 404s now.
> 
> Has this document moved? I wasn't able to find it searching the site for "kernel modules".

The documentation was moved to:

https://docs.01.org/clearlinux/latest/guides/kernel/kernel-modules.html

**Comment by jimsalterjrs** [comment]
For anybody else going through this—the relevant bundles you need are `linux-lts-dev` if you're on the LTS kernel (which you'll probably need to be) or `linux-dev` for the native kernel, and then `os-core-dev` to resolve the `uuid.h` issue.

**Comment by jimsalterjrs** [comment]
````
root@clearlinux/home/jim # insmod /usr/lib/modules/4.19.103-113.lts2018/extra/zfs/zfs.ko
insmod: ERROR: could not insert module /usr/lib/modules/4.19.103-113.lts2018/extra/zfs/zfs.ko: Unknown symbol in module
````

I don't suppose anybody has any idea who I find out _which_ symbol is the unknown symbol? I appreciate the help so far.

**Comment by jimsalterjrs** [comment]
^^ the answer to the above—or at least, the one I went with—is not to use `insmod` at all, which does not resolve dependencies, and instead use `modprobe`.

Trick there is, `modprobe` won't find the modules where the `make install` command left them, each in its own subdirectory under `/lib/modules/<kernelversion>/extra`.

I went a bit brute-force, and did:
````
root@clear:~# for mod in `find /lib/modules/<kernelversion>/extra
do cp -a $mod /lib/modules/<kernelversion>/ 
done
````
After which I could just `modprobe zfs.ko`, and everything worked fine: although also note, the `zpool` and `zfs` commands are placed in `/usr/local/sbin`, and that directory is not in the default PATH.

**Comment by bwarden** [comment]
> Trick there is, `modprobe` won't find the modules where the `make install` command left them, each in its own subdirectory under `/lib/modules/<kernelversion>/extra`.

`depmod -a`

**Comment by darkdragon-001** [comment]
I just found [a tutorial in the docs](https://docs.01.org/clearlinux/latest/tutorials/zfs.html) using DKMS.

**Comment by inoshy** [comment]
WE NEED ZFS ADD IT INTEL
