### ISSUE TITLE
plz bundle add chromium and ffmpeg please

### ISSUE THREAD

**Issue by robertodellapasqua** [clearlinux/distribution#637]
Firebird has limitations on video codec plugins and extensions and many services don't play, as netflix or whatsapp, facebook videos

**Comment by robertodellapasqua** [comment]
with the power of this linux, the wayland drivers, and plasma shell, a best chromium browser you can play side-by-side with windows and macos (gnome is a little toy)

**Comment by thiagomacieira** [comment]
For ffmpeg, see #429.

As for Chromium, please confirm you'd like *Chromium* not Chrome. We plan to provide a way to easily install Chrome, which means you wouldn't get much of a need for Chromium.

**Comment by robertodellapasqua** [comment]
Chrome should be ok
Actually which lowlevel video GPU H264 H265 VP8 acceleration do you support?
About SDL2 and Vulkan, are supported?
This os with Wayland can be a strong way where build a new beautiful shell.

Il giorno lun 22 apr 2019 alle ore 22:27 Thiago Macieira <
notifications@github.com> ha scritto:

**Comment by ahkok** [comment]
Let's track #422 for chrome.

**Comment by ahkok** [comment]
Please file *new* bugs for each separate feature request, not 1 request for 3+ items.

**Comment by thiagomacieira** [comment]
* Codecs: FFMPEG will support VP8 & VP9. I don't know if we support H.264 in HW only, check needed.
* SDL2: yes
* Vulkan: yes
* Wayland: yes (but not GNOME's Wayland compositor, too buggy)

**Comment by eero-t** [comment]
> Codecs: FFMPEG will support VP8 & VP9. I don't know if we support H.264 in HW only, check needed

Does "HW only" mean iHD intel-media-driver encoding with (compute) shaders, or the low-power (fixed function) encoding?

I'm asking because latter has serious limitations (at least with intel-media-driver).  For bit-rate controls (except for CQP) it needs kernel with GuC support. GuC support isn't yet upstream, and it's only for IceLake.

**Comment by ms178** [comment]
@thiagomacieira Please consider Chromium with VA-API patches applied for hardware video decoding on a wide variety of hardware. Other distros (such as openSUSE Tumbleweed) ship such a patched Chromium by default for some time now and it works great. That would also provide an added benefit over standard Chrome as Google doesn't ship with VA-API support on Linux currently.

**Comment by thiagomacieira** [comment]
Makes sense.

@chivakker ↑

**Comment by chivakker** [comment]
The patch needs some rework as things have changed in the last 1+ year from last submission. It is an experimental approach and I believe it should remain as so.

I know some distributions (or people making it available to distributions) are using variants of that patch and still in the experimental side. And of course, the same code base behaves different as the underlying hardware supports different codecs.

**Comment by ms178** [comment]
@chivakker From the end-user perspective, hardware video decoding is important for quite a few people. Even having it as an experimental option (opt-in) would be great. OpenSUSE and others are enabling it by default (opt-out) and haven't seen too much noise of it breaking things. In an ideal world, the patch would be upstreamed and maintained there. But as you are familiar with the upstream discussion, the Chromium developers didn't want to take over the maintenance burden. As this code has been battle tested in the field now, maybe another push from downstream maintainers could drive things into the right direction?
