### ISSUE TITLE
missing /etc/fonts/font.conf

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#639]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**
I dont know if this really is a bug, but I got nowhere else to ask about this. So I opened this issue here.

fonts.conf is  missing. It is not in the /etc/fonts directory

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28970
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

Babel
NetworkManager
NetworkManager-basic
R-basic
R-datasets
R-extras
R-stan
Sphinx
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
bootloader
c-basic
cabextract
ccache
ceph
cheese
cloc
cloud-api
clr-network-troubleshooter
computer-vision-basic
computer-vision-models
containers-basic
cpio
cryptography
curl
database-basic
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
developer-gpu
devpkg-LVM2
devpkg-NetworkManager
devpkg-R
devpkg-SDL
devpkg-SDL2
devpkg-SDL2_gfx
devpkg-SDL2_image
devpkg-SDL2_mixer
devpkg-SDL2_net
devpkg-SDL2_ttf
devpkg-SDL_gfx
devpkg-SDL_image
devpkg-SDL_mixer
devpkg-SDL_net
devpkg-SDL_ttf
devpkg-acl
devpkg-alsa-lib
devpkg-apr
devpkg-apr-util
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-attica
devpkg-attr
devpkg-audit
devpkg-base
devpkg-bluez
devpkg-boost
devpkg-cairo
devpkg-clutter
devpkg-cmrt
devpkg-cogl
devpkg-colord
devpkg-compat-enchant-soname1
devpkg-compat-fuse-soname2
devpkg-cryptsetup
devpkg-curl
devpkg-cyrus-sasl
devpkg-dbus
devpkg-dbus-glib
devpkg-e2fsprogs
devpkg-elfutils
devpkg-enchant
devpkg-exiv2
devpkg-expat
devpkg-fann
devpkg-fftw
devpkg-flac
devpkg-font-util
devpkg-fontconfig
devpkg-freeglut
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-gcr
devpkg-gdk-pixbuf
devpkg-gflags
devpkg-glib
devpkg-glog
devpkg-glu
devpkg-gmime
devpkg-gnutls
devpkg-gobject-introspection
devpkg-googletest
devpkg-gperftools
devpkg-graphite
devpkg-graphviz
devpkg-gsl
devpkg-gst-plugins-base
devpkg-gstreamer
devpkg-gtk
devpkg-gtk-doc
devpkg-gtk3
devpkg-gtkplus
devpkg-guile
devpkg-harfbuzz
devpkg-hwloc
devpkg-icu4c
devpkg-ipmctl
devpkg-ipset
devpkg-iptables
devpkg-iso-codes
devpkg-json-c
devpkg-json-glib
devpkg-kmod
devpkg-krb5
devpkg-lcms2
devpkg-libX11
devpkg-libXScrnSaver
devpkg-libXau
devpkg-libXcursor
devpkg-libXdamage
devpkg-libXdmcp
devpkg-libXext
devpkg-libXfixes
devpkg-libXft
devpkg-libXmu
devpkg-libXpm
devpkg-libXres
devpkg-libXt
devpkg-libXtst
devpkg-libXv
devpkg-libXvMC
devpkg-libXxf86misc
devpkg-libXxf86vm
devpkg-libabigail
devpkg-libarchive
devpkg-libassuan
devpkg-libcanberra
devpkg-libcap
devpkg-libcap-ng
devpkg-libcgroup
devpkg-libcroco
devpkg-libdatrie
devpkg-libdrm
devpkg-libepoxy
devpkg-libevdev
devpkg-libevent
devpkg-libffi
devpkg-libfontenc
devpkg-libgd
devpkg-libgpg-error
devpkg-libgudev
devpkg-libgusb
devpkg-libical
devpkg-libidn
devpkg-libidn2
devpkg-libinput
devpkg-libjpeg-turbo
devpkg-libmicrohttpd
devpkg-libmnl
devpkg-libmspack
devpkg-libndp
devpkg-libnetfilter_conntrack
devpkg-libnetfilter_cthelper
devpkg-libnetfilter_cttimeout
devpkg-libnetfilter_queue
devpkg-libnfnetlink
devpkg-libnftnl
devpkg-libnl
devpkg-libnotify
devpkg-libogg
devpkg-libpcap
devpkg-libpciaccess
devpkg-libpipeline
devpkg-libpng
devpkg-libpsl
devpkg-libpthread-stubs
devpkg-librepo
devpkg-librsvg
devpkg-libsamplerate
devpkg-libseccomp
devpkg-libsecret
devpkg-libsolv
devpkg-libsoup
devpkg-libssh2
devpkg-libtasn1
devpkg-libthai
devpkg-libtirpc
devpkg-libunwind
devpkg-libusb
devpkg-libuser
devpkg-libva
devpkg-libvirt
devpkg-libwebp
devpkg-libxcb
devpkg-libxkbcommon
devpkg-libxml2
devpkg-libxslt
devpkg-libzip
devpkg-llvm
devpkg-lua
devpkg-lz4
devpkg-mariadb
devpkg-mesa
devpkg-metrics-discovery
devpkg-mozjs52
devpkg-multipath-tools
devpkg-ncurses
devpkg-ndctl
devpkg-nettle
devpkg-newt
devpkg-nftables
devpkg-nghttp2
devpkg-nspr
devpkg-nss
devpkg-ntfs-3g
devpkg-oath-toolkit
devpkg-open-iscsi
devpkg-opencv
devpkg-openmpi
devpkg-openssl
devpkg-openvswitch
devpkg-opus
devpkg-orc
devpkg-p11-kit
devpkg-pacrunner
devpkg-pango
devpkg-parted
devpkg-pciutils
devpkg-pcre
devpkg-pcre2
devpkg-pixman
devpkg-pkcs11-helper
devpkg-pmdk
devpkg-popt
devpkg-postgresql
devpkg-procps-ng
devpkg-protobuf-c
devpkg-pulseaudio
devpkg-qtbase
devpkg-qtdeclarative
devpkg-qtsvg
devpkg-qttools
devpkg-rdma-core
devpkg-readline
devpkg-rest
devpkg-shared-mime-info
devpkg-sqlite-autoconf
devpkg-startup-notification
devpkg-subunit
devpkg-systemd
devpkg-tbb
devpkg-telemetrics-client
devpkg-tiff
devpkg-usbredir
devpkg-userspace-rcu
devpkg-util-linux
devpkg-util-macros
devpkg-vala
devpkg-wayland
devpkg-wayland-protocols
devpkg-xapian-core
devpkg-xcb-proto
devpkg-xcb-util-cursor
devpkg-xkeyboard-config
devpkg-xmlsec1
devpkg-xorgproto
devpkg-xtrans
devpkg-xz
devpkg-zlib
devpkg-zstd
diffoscope
diffutils
dnf
docbook-utils
docutils
dosfstools
doxygen
dpdk
editors
editors-dev
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
fio
firefox
firmware-update
flatpak
flex
fontforge
fonts-basic
fonttools
fuse
fwupdate
gdb
gedit
gimp
git
gjs
glibc-locale
global
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
gnuplot
go-basic
go-basic-dev
gpgme
graphviz
gstreamer
gvim
gzip
hardware-gpu
hardware-printing
hardware-uefi
htop
httpd
hwloc
icdiff
inotify-tools
intltool
iproute2
iptables
irssi
java-basic
joe
jupyter
kbd
kernel-install
kernel-native
koji
kvm-host
kvm-host-dev
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libarchive
libglib
libstdcpp
libva-utils
libxml2
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
machine-learning-basic
machine-learning-mycroft
machine-learning-pytorch
machine-learning-tensorflow
machine-learning-web-ui
mail-utils
mail-utils-dev
make
man-pages
mariadb
minetestserver
minicom
mixer
mkosi
mutt
nasm
nautilus
net-tools
network-basic
network-basic-dev
nfs-utils
nginx
nodejs-basic
notmuch
octave
offlineimap
openblas
openldap
openmpi
openssh-server
openssl
openvswitch
os-clr-on-clr
os-clr-on-clr-dev
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
os-installer
p11-kit
package-builder
package-utils
parallel
parted
patch
perl-basic
perl-basic-dev
php-basic
plzip
pmdk
polkit
postgresql
powertop
procps-ng
pulseaudio
pygobject
python-data-science
python-extras
python2-basic
python3-basic
python3-tcl
qemu-guest-additions
qt-basic
qt-core
redis-native
ruby-basic
runtime-libs-boost
rust-basic
samba
scons
seahorse
smartmontools
spice-gtk
sqlite
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
syslinux
tcl-basic
telemetrics
texinfo
texlive
thermal_daemon
thunderbird
tigervnc
tmux
totem
tzdata
unbundle
unzip
valgrind
vim
vinagre
virt-viewer
vlc
web-server-basic
webkitgtk
weechat
wget
which
wpa_supplicant
x11-server
x11-tools
x11vnc
xemacs
xfsprogs
xterm
xz
yasm
zip
znc
zstd

**Additional context**

**Comment by hnanni** [comment]
it is on /usr/share/defaults/fonts/fonts.conf

It can be created on /etc also, but the default is the one above. I'll kindly point you to to check https://clearlinux.org/features/stateless as it elaborates on the contents of /etc under clearlinux

Anyway, not having fonts.conf in /etc/fonts directory is causing a problem to you?

**Comment by stokhos** [comment]
yes, i'm using alacritty, https://github.com/jwilm/alacritty

When using alacritty with wayland, it searches for fonts.conf in /etc/fonts/. But I dont have such problem in xorg.

**Comment by thiagomacieira** [comment]
Does it search for that file directly, not using libfontconfig? If so, it needs a patch to operate properly on Clear.

**Comment by stokhos** [comment]
Ok, got it, thank you @thiagomacieira

**Comment by thiagomacieira** [comment]
#432 is reporting that Chrome has the same problem finding fonts (and has a workaround).

**Comment by jokeyrhyme** [comment]
@stokhos I created /etc/profile containing `FONTCONFIG_PATH=/usr/share/defaults/fonts`, re-logged, then re-built alacritty, and that seems to have it starting instantly with no fontconfig errors
