### ISSUE TITLE
Hard to position mouse so that resize of window is possible

### ISSUE THREAD

**Issue by Meai** [clearlinux/distribution#642]
The area for when the mouse turns into a draggable mouse is too tiny. Please make the borders more easily resizable. I tried to add my own decoration modifications to `/usr/share/themes/Adwaita/gtk-3.0/gtk.css` but it doesnt seem to do anything. Most of the online suggestions around Gnome 3 seem to reference some kind of MetaCity xml file that doesnt exist here on clearlinux. 
I dont know why Gnome 3 on Centos 7 and Opensuse Leap 15 dont have this problem, maybe because it's an older version.

**Comment by ahkok** [comment]
@markz @ikeyd ?

**Comment by mrkz** [comment]
@Meai Thanks for your your bug report :tada: 

it sounds a lot like a duplicate of https://github.com/clearlinux/distribution/issues/572, mind to verify if this is what you're seeing as well?

**Comment by Meai** [comment]
@mrkz yeah I see that problem too, but mine may not be related or maybe it is likewise solved with that one. It's just generally quite hard to get the corner

**Comment by mrkz** [comment]
@Meai can you confirm if this issue is present only on Xorg GNOME session and not it a Wayland GNOME session?

**Comment by Meai** [comment]
@mrkz yeah I tested Wayland Gnome and it works perfectly there. How do I make this the default?

**Comment by tpleavitt** [comment]
a duplicate of #572, closing
