### ISSUE TITLE
Bundle "virt-manager" depends on bundle "virt-manager-gui" to work, possible to merge the 2 into one?

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#643]
**Is your feature request related to a problem? Please describe.**

I'm not sure what is the reason for having both "virt-manager" and "virt-manager-gui".  
"virt-manager" installs the GUI, but it fails (see screenshot) because it's missing Gtk-vnc.  Once I install "virt-manager-gui" (which contains Gtk-vnc), the issue is resolved.  

**Describe the solution you'd like**
They both perform GUI functions for libvirt.  Why not merge the 2 bundles or add the Gtk-vnc bundle into "virt-manager" to resolve the dependency issue?

![IMG_2464](https://user-images.githubusercontent.com/29260389/56700173-c317c100-66ad-11e9-9e70-4b8ce937ec82.jpg)

**Comment by mrkz** [comment]
If I recall correctly, there was a specific use-case where one wants to run virt-manager stuff directly from commandline (hence, no requiring the UI at all), and that's how functionality difference from the `virt-manager` and `virt-manager-gui` bundles got in place (commit https://github.com/clearlinux/clr-bundles/commit/9801a4c2b5f937669a2b5b48880a5ec2a54aff05).

However I think that it would make more sense to have bundles renamed to
`virt-manager` -> `virt-manager-cli`
`virt-manager-gui` -> `virt-manager`
as I guess using virt-manager on desktop is a more common use-case than relying on CLI-only.

Thoughts @ahkok @fenrus75 ?

**Comment by bryteise** [comment]
I'm not really sure the gui is more common and given that one needs a bundle rename and the other does not I'm inclined to leave it this way.

**Comment by mrkz** [comment]
@bryteise what about changing the virt-manager bundle description to make it explicit that only CLI is available?

i.e:
```diff
diff --git a/bundles/virt-manager b/bundles/virt-manager
index c5d50e48..4bc63753 100644
--- a/bundles/virt-manager
+++ b/bundles/virt-manager
@@ -1,5 +1,5 @@
 # [TITLE]: virt-manager
-# [DESCRIPTION]: Virtualization Management tool.
+# [DESCRIPTION]: Virtualization Management tool (CLI Only)
 # [STATUS]: Active
 # [CAPABILITIES]:
 # [TAGS]: Tools and Utilities

```

**Comment by bryteise** [comment]
Seems like an easy and potentially helpful change. +1

**Comment by mrkz** [comment]
Closed with https://github.com/clearlinux/clr-bundles/commit/42c7f14102868ab098fc2f01cc6f54d7c3f6cff0
