### ISSUE TITLE
[Package request] Alacritty

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#646]
Alacritty is a GPU-accelerated terminal emulator
It works so well with vim and tmux
I can install it manually, but I'm having trouble to create an desktop icon when using wayland

**Comment by lebensterben** [comment]
>**Is your feature request related to a problem? Please describe.** ...

@stokhos After you built Alarcritty, a file named alarcritty.desktop shall also be available. I put it under /use/share/applications and after re-login, it's available.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stokhos** [comment]
@lebensterben have you tried desktop-file-install alacritty.desktop? I tried that several times, it created desktop icon in xorg. But not in wayland.

**Comment by lebensterben** [comment]
>@lebensterben have you tried desktop-file-install alacritty.desktop? I tried that several times, it created desktop icon in xorg. But not in wayland.

@stokhos well I didn't notice it's Wayland. Do you have ~/.config/weston.ini file? If you add a launcher entry there it shall work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stokhos** [comment]
@lebensterben No, there is no  weston.ini in .config.  But i'm having alacritty entry in gnome launcher. Thank you very much!

**Comment by ahkok** [comment]
> I put it under /use/share/applications

this location is maintained by the OS, and you should not put items under there. Instead, create `/usr/local/share/applications` and put it there instead, or `~/.local/share/applications`.

**Comment by lebensterben** [comment]
>> I put it under /use/share/applications ...

@ahkok thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Preisschild** [comment]
Can we reopen the issue regardless? Alacritty would be an awesome addition to the official packages.

**Comment by lebensterben** [comment]
>Can we reopen the issue regardless? Alacritty would be an awesome addition to the official packages.

@Preisschild autospec doesn't support Rust package currently and that's why this cannot be packaged

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Preisschild** [comment]
@lebensterben gotcha, thanks for the reply :)
