### ISSUE TITLE
sane-backends dll configuration?

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#647]
**Describe the bug**
sane-backends usually comes with a whole bunch of config files in /etc. Other distributions will generally have something like `echo hpaio > /etc/sane.d/dll.d/hpaio` in their hplip package script in order to enable scanning for HP devices. Given the stateless nature of CL, how should this be handled?

(I looked and couldn't find any default configs for sane in /usr/share/defaults)

**Comment by mrkz** [comment]
Hello @pceiley,

>  Given the stateless nature of CL, how should this be handled?
(I looked and couldn't find any default configs for sane in /usr/share/defaults)

Stateless does not mean "user can't configure", meaning that if you fill `/etc/` that should be honored.

we could of course provide some default configuration on `/usr/share/defaults`, which apparently we're not shipping at the moment for your specific use-case.

Does configuring `/etc` gets your use-case set as expected?

**Comment by pceiley** [comment]
Hi @mrkz,
Thanks for the reply. No, I haven't managed to get it to work as yet. I tried creating /etc/sane.d/dll.conf with:
```
net
hpaio
```
but this doesn't appear to have worked. Would need deeper troubleshooting. If I get some more time I'll look into it.

**Comment by pceiley** [comment]
The issue is with the hplip package. I've submitted a patch to the mailing list to tweak the stateless support. Once the patch is applied, scanning works by doing:
```
mkdir -p /etc/sane.d/dll.d
echo hpaio >/etc/sane.d/dll.d/hpaio
```
Has anyone got any ideas on how we might make this work by default on CL? I think it's reasonable for users to expect this to work out of the box if hplip is installed.

**Comment by miguelinux** [comment]
> ```
> mkdir -p /etc/sane.d/dll.d
> echo hpaio >/etc/sane.d/dll.d/hpaio
> ```

It should work without /etc files, but if that is not possible, you can
use systemd-tmpfiles.

Look for some examples at /usr/lib/tmpfiles.d

That's for packages out-of-the-box.

**Comment by miguelinux** [comment]
it is doable to do a stateless patch for  `sane-backends` package.

**Comment by pceiley** [comment]
> Look for some examples at /usr/lib/tmpfiles.d

Interesting - thanks!!

> it is doable to do a stateless patch for sane-backends package.

This is probably a bit beyond me at this stage. If someone else were to do this, I'd be more than happy to help test, however.

**Comment by bwarden** [comment]
When the sane-backends stateless fix lands, we should consider having the hpaio package add an entry to /usr/share/defaults/sane/dll.d.

**Comment by mrkz** [comment]
@bwarden I guess that this item can be closed now per your previous commits (https://github.com/clearlinux-pkgs/sane-backends/commit/23940e31b578e034364196895f410c7083bb0477 and https://github.com/clearlinux-pkgs/hplip/commit/fae28845e0cb3eedf295416270e819a8ef113507)?

**Comment by bwarden** [comment]
Yes, should be fixed now.

**Comment by pceiley** [comment]
Fantastic! Thanks, @bwarden!
