### ISSUE TITLE
bundle with yaml-cpp needs to be added

### ISSUE THREAD

**Issue by brad-kelly** [clearlinux/distribution#648]
I want to use yaml-cpp and feel like there should be a devpkg for it.

Oddly enough, whe i do swupd search I do see that swupd appears to know about it, but I cannot install it.

```
% swupd search yaml-cpp
Component yaml-cpp has version 0.6.2

% sudo swupd bundle-add yaml-cpp
Warning: Bundle "yaml-cpp" is invalid, skipping it...
Failed to install 1 of 1 bundles

```

**Comment by ahkok** [comment]
So we can easily make a `devpkg-yaml-cpp`. But you'll get the header stuff as well. Small enough though, I think. Otherwise there is no bundle for it, really.
