### ISSUE TITLE
kernel-aws needs ENA - Elastic Network Adapter

### ISSUE THREAD

**Issue by FireballDWF** [clearlinux/distribution#65]
The kernel in kernel-aws needs to be updated to include https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enhanced-networking-ena-linux then replace
https://aws.amazon.com/marketplace/pp/B075TXF7KJ with an AMI which includes the ENA enabled kernel-aws. This is required in order to be able to launch on C5 and M5 instance types.

**Comment by ahkok** [comment]
@miguelinux

**Comment by ahkok** [comment]
This is open for too long already...

**Comment by ahkok** [comment]
Weird, I show this as being enabled in our AWS kernel since april 2016

**Comment by fenrus75** [comment]
CONFIG_ENA_ETHERNET=y


(don't expect to see a .ko file, the driver is built into the kernel)

On Wed, May 16, 2018 at 4:24 PM, David Filiatrault <notifications@github.com

**Comment by bryteise** [comment]
You can look in /usr/lib/modules/$kernelversion/modules.builtin to see what is enabled too.

**Comment by FireballDWF** [comment]
Ok, by starting with your latest ami which has ena-enabled flag set, I was able to get it to launch on a c5.large.    Note, the version of driver used is 1.2.0k while 1.5.1 is now available per  https://github.com/amzn/amzn-drivers/blob/857b4b8d81a1b3ca2a4af29695acda57cabee9cc/kernel/linux/ena/RELEASENOTES.md

$ ethtool -i enp0s5
driver: ena
version: 1.2.0k
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
clear@clr-3d5ff99de3894b32abaae7756bfa51ef ~ $
