### ISSUE TITLE
crond.service file could not be found

### ISSUE THREAD

**Issue by zmdismai** [clearlinux/distribution#655]
**Describe the bug**
crond.service file could not be found

**To Reproduce**
1. Boot up Live Desktop image
2. Install Clear Linux
3. Upon installation, install cronie:
    $ sudo swupd bundle-add cronie
4. Create a simple job that runs every one minute:
    a) $ sudo crontab -u username -e
    b) Type the following: * * * * * date >/tmp/mydate
5. At this point the scheduled job does not run, as a user I would like to check the status of crond:
    $ sudo systemctl status crond
    Current behavior: Unit crond.service could not be found.

**Expected behavior**
crond.service should be available after cronie is installed.

**Environment (please complete the following information):**
- Clear Linux OS version: [`cat /usr/lib/os-release`]NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29160
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

 - Bundles: [e.g. `sudo swupd bundle-list`]
NetworkManager
acpica-unix2
alsa-utils
ansible
baobab
binutils
bison
bootloader
c-basic
cheese
containers-basic
cronie
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
eog
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
ipmitool
iproute2
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
make
man-pages
meld
minicom
nasm
nautilus
openldap
openssh-server
openssl
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
tigervnc
tmux
totem
tzdata
unzip
vim
vnc-server
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
zstd

**Additional context**
Currently, the scheduled job is able to work after I manually ran crond:
$ sudo /usr/sbin/crond &

As a user I am expecting the crond.service to be available so that I can have better control of crond.

**Comment by ahkok** [comment]
`cron` is mostly obsolete, and replaced by https://www.freedesktop.org/software/systemd/man/systemd.timer.html

**Comment by ahkok** [comment]
You can manually install the `cronie` bundle to get an antique-cron style `crond`.
