### ISSUE TITLE
the bugreport form asks for too much information making it harder to read or act on bug reports

### ISSUE THREAD

**Issue by fenrus75** [clearlinux/distribution#657]
*Please omit irrelevant data and trim the bug report template to only those parts that make sense!*

**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by fenrus75** [comment]
bundle lists are LONG and generally useless

most of the other things asked as well

**Comment by ahkok** [comment]
I've simplified this entirely. Let's start with a clean slate without template text.

**Comment by mdhorn** [comment]
Wait, I think completely removing the template is going too far in the other direction.
We created the template for a good reason, why not just reduce the data clutter?

**Comment by ahkok** [comment]
It was 95% clutter - nobody trimmer it. The text above now has the hint as to what could make a good bug report, and it isn't copied into the bugreport itself.
