### ISSUE TITLE
PAM authentication issues with vlock and i3lock

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/distribution#66]
The `vlock` package does not seem to work in Clear Linux. When invoking `vlock` it immediately starts spamming the following about every second or so, with no actual input from myself.
```
The pts/1 is now locked by mrsj.
Authentication failure.


The pts/1 is now locked by mrsj.
Authentication failure.


The pts/1 is now locked by mrsj.
Authentication failure.


The pts/1 is now locked by mrsj.
Authentication failure.
...
```

`i3lock` also fails. When initiating `i3lock` my screen is locked properly, but I am unable to unlock the screen. I can run `i3lock --debug` and get some more verbose output (after killing `i3lock` from another TTY).
```
<messages that include my password, I *am* typing it right>
Authentication failure
```

I'm guessing this is an issue with PAM configuration in Clear Linux for stateless considerations, but I don't know enough about how PAM works or interacts with these programs to go much further.

**Comment by phmccarty** [comment]
PAM configuration files are not installed for either vlock or i3lock, so PAM falls back to `other`, which on Clear Linux will always log the authentication attempt (via `pam_warn`), and then deny access (via `pam_deny`). See `/usr/share/pam.d/other` for the config details.

To resolve these issues, we should have the vlock package install a `/usr/share/pam.d/vlock` file, and i3lock install a `/usr/share/pam.d/i3lock` file.

**Comment by fenrus75** [comment]
i3lock fixed

**Comment by phmccarty** [comment]
Thanks! I updated my last comment... there is no vlock package; vlock lives in "kbd".

**Comment by phmccarty** [comment]
The i3lock and vlock packages have been fixed in 23060. We can close this issue.

**Comment by xlfe** [comment]
@phmccarty @fenrus75 I'm unable to get either i3lock or vlock working. 

I get the following with i3lock

```
i3lock[]: pam_unix(i3lock:auth): authentication failure; logname=<myusername> uid=<myuid> euid=<myuid> tty=:0 ruser= rhost=  user=<myusername>
```

--debug on i3lock shows my password being entered correctly (I have tried > 10 times very carefully too)

vlock shows

```
Authentication service cannot retrieve authentication info.
```

**Comment by phmccarty** [comment]
@xlfe Can you open a new issue for this, and link to this one for reference?
