### ISSUE TITLE
Problem using networkmanager-openvpn

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#665]
I get this error when attempting to establish the VPN connection via NetworkManager on Gnome

`VPN connection: failed to connect interactively: 'User “nm-openvpn” not found, check NM_OPENVPN_USE>`

It looks like a well known issue. Presumably there should to be a system user created as part of the package.

See:
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797399](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797399)
[https://bugs.archlinux.org/task/46124](https://bugs.archlinux.org/task/46124)
[https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/networkmanager-openvpn&id=9aa4b8be2ea71103197f1bee4e37374b8a0c60cc](https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/networkmanager-openvpn&id=9aa4b8be2ea71103197f1bee4e37374b8a0c60cc)

**Comment by ahkok** [comment]
Adding the user id.

**Comment by ahkok** [comment]
Should be fixed in 1-2 days.
