### ISSUE TITLE
Thunderbird Icon is wrong

### ISSUE THREAD

**Issue by andyross** [clearlinux/distribution#666]
Installing Thunderbird, on 29200, it shows a generic "email" sort of icon in gnome shell instead of the official (blue bird over envelope) icon from Mozilla.

Looking in /usr/share/icons, I do indeed find that image in various themes named "thunderbird.{png,svg}", so I'm guessing this is a policy decision somewhere, maybe in Gnome?

Seems weird and inconsistent, though, as Firefox gets its own icon in Clear and not a generic "web browser".  And other Linux distros similarly package Thundrebird with a properly branded icon.

**Comment by anselmolsm** [comment]
Fixed in release 30000.
