### ISSUE TITLE
- it is possible to have IKCONFIG support? in clear linux project -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#668]
modprobe configs
modprobe: FATAL: Module configs not found in directory /lib/modules/5.0.11-747.native

it would help if I had:
 CONFIG_IKCONFIG=m
 CONFIG_IKCONFIG_PROC=y

```
cat /etc/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

uname -a
Linux lnx-mgmt 5.0.11-747.native #1 SMP Thu May 2 18:01:31 UTC 2019 x86_64 GNU/Linux

cat /proc/cmdline  | tr ' ' '\n'
root=PARTUUID=45ec3317-88c2-49c0-961d-1e207d114e9c
quiet
console=tty0
console=ttyS0,115200n8
init=/usr/bin/initra-desktop

initcall_debug
tsc=reliable
no_timer_check
noreplace-smp
kvm-intel.nested=1
rootfstype=ext4,btrfs,xfs
intel_iommu=igfx_off
cryptomgr.notests
rcupdate.rcu_expedited=1
rcu_nocbs=0-64
rw
loglevel=1

```

**Comment by fenrus75** [comment]
hmm the config is already is /usr/lib/kernel .... 
what is the advantage of having it also in /proc ?

**Comment by ahkok** [comment]
This just consumes memory.

**Comment by ionutnechita** [comment]
would be much safer, and much more comfortable for me, being in /proc.
I will be able to inspect the kernel configuration while running.
"/usr/lib/kernel", the configuration file can be erased by mistake.
it would be good to be "module - CONFIG_IKCONFIG", not "built_in" in kernel; so I can only activate it when I want it

we can try, it does not have a very big impact.

**Comment by ahkok** [comment]
it consumes memory on every installed clearlinux system. It's only useful to a very small set of users. That is a big cost to pay.

`swupd verify --fix` can already recover from an accidentally deleted `/usr/lib/kernel` file.

If you must have it, it is not too difficult to compile your own kernel.
