### ISSUE TITLE
Clr Firefox and the disabled add-ons issue

### ISSUE THREAD

**Issue by Nirgendsdorf** [clearlinux/distribution#669]
A few days ago, all users of the latest Firefox release version (on Linux and Windows, at the least) suddenly found all their extensions to have been disabled. The Mozilla devel team has attempted a temporary patch through the 'Studies' mechanism, but some Firefox builds included in various Linux distros cannot be patched this way. Clear Firefox seems to be one of them.

https://bugzilla.mozilla.org/show_bug.cgi?id=1548973

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

My Firefox installation has not received the "hotfix-update-xpi-signing-intermediate-bug-1548973" referenced in the above cited article.

**Comment by lebensterben** [comment]
> A few days ago, all users of the latest Firefox release version (on Linux and Windows, at the least) suddenly found all their extensions to have been disabled. The Mozilla devel team has attempted a temporary patch through the 'Studies' mechanism, but some Firefox builds included in various Linux distros cannot be patched this way. Clear Firefox seems to be one of them.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
> 
> https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
> 
> My Firefox installation has not received the "hotfix-update-xpi-signing-intermediate-bug-1548973" referenced in the above cited article.

@Nirgendsdorf , after allowing firefox to run studies in the settings, I can the hotfix under `about:studies` page. The real problem is, the add-ons are not fixed. I think this is more of a firefox issue rather than Clear's.

**Comment by fenrus75** [comment]
Mozilla just released 66.0.4 today which has this supposedly fixed; working
on getting htis into an update

**Comment by Nirgendsdorf** [comment]
> Mozilla just released 66.0.4 today which has this _supposedly_ fixed; working on getting htis into an update

Thank you, Arjan, let's hope for the best.

**Comment by fenrus75** [comment]
the build is available in our staging area pending QA

swupd update --format staging

gets you to the 29220 build

**Comment by pceiley** [comment]
I noticed my firefox instance updated itself to 66.0.4 when I opened the about window and asked me to restart the browser. Is this expected behaviour?

**Comment by Nirgendsdorf** [comment]
> the build is available in our staging area pending QA swupd update --format staging gets you to the 29220 build

I tried that, yesterday. A number of updates were installed, and then I restarted my system. Result: my Clr installation no longer boots. Instead of booting into gnome, my system displays a blinking text cursor in the upper left corner of the display for a few minutes, followed by a completely blank screen. I am now booting from a live desktop image on a USB memory stick to write and ask you for help. Is there any way to rescue my installation (possibly by rolling back that last update) without wiping the HDD and starting entirely over from scratch? Thanks!

**Comment by fenrus75** [comment]
there was an.. interesting.. dbus issue.

it shold still boot, but with a 90 or 180 second timeout.

**Comment by Nirgendsdorf** [comment]
I waited longer than that after restarting in case the updates needed time to finish installing correctly, hoping that I would see...something... No, it does not boot. No response to keyboard input. Nothing. I can access some files on the HDD by booting from the latest live desktop image, so I may be able to salvage something, but I had hoped to rescue the installation. Being new with Linux, though, I have no idea how to go about doing that. Can you help at all?

**Comment by fenrus75** [comment]
from the rescue image you can recover this; the 29230 build has this fixed,
or you need to copy 1 file from the rescue image to the disk image

( /usr/share/dbus-1/system.conf )

**Comment by Nirgendsdorf** [comment]
Thanks! Do you have a link for that rescue image? The images on https://cdn.download.clearlinux.org/image/ are still at 29200.

**Comment by fenrus75** [comment]
you can pick any version of the rescue image; 29200 is good enough for this

**Comment by Nirgendsdorf** [comment]
So I managed to copy /usr/share/dbus-1/system.conf from the rescue image to the disk, but the disk image still does not boot. Wow....... :(

**Comment by ahkok** [comment]
The firefox issue is resolved.
