### ISSUE TITLE
Can't close the Terminal after switching it to Full-screen

### ISSUE THREAD

**Issue by sachinmokashi** [clearlinux/distribution#671]
**Description**
Can't close the Terminal after switching it to Full-screen

**To Reproduce**

1) Boot the Live Desktop Image
2) Open terminal, switch to full screen mode
3) Try to close the terminal using Mouse click on UI

**Current behavior**
Unable to find the "Close Tab" on UI

**Expected behavior**
Should be able to Close the Terminal with Mouse

**Environment**:

- Clear Linux OS version: [cat /usr/lib/os-release]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29090
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

- Bundles: [sudo swupd bundle-list]
NetworkManager
Remmina
acpica-unix2
alsa-utils
baobab
binutils
bison
bootloader
c-basic
cheese
clr-installer
clr-network-troubleshooter
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
dnf
dpdk
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
iproute2
iptables
joe
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libreoffice
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
locales
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
package-utils
parallel
patch
perl-basic
pidgin
polkit
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
vim
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Comment by ahkok** [comment]
@mrkz wanna take a look at this?

**Comment by AsharLohmar** [comment]
Hi, 
excuse me, but you are talking about full-screen and not maximize, right ? 
If that's so ... than, in my opinion, that's the correct behavior. Going "full-screen", you get the same "experience" you get when you go full-screen on a move or even a browser(at least Chrome does), there's no task-bar or system menus or anything else.

Also, in order to get out of the full-screen just hit F11 or if you want to close it go with CTRL+SHIFT+q.

**Comment by lebensterben** [comment]
In most terminal emulators, including Gnome terminal, if the last shell process is terminated, the terminal emulator will quit as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sachinmokashi** [comment]
I verified with Ubuntu 18.04 LTS and could atleast find the menu bar when I go full-screen. That helped me to navigate a bit. Expected it would be same in Clear too. 

But I agree that F11 should be good enough to exit full-screen and get along with my work. Closing this issue. Thanks!
