### ISSUE TITLE
Software Market content is blank. 

### ISSUE THREAD

**Issue by HuiTheng124** [clearlinux/distribution#672]
**Description**
The software market content is blank after open.

**To Reproduce**
1. Boot up Live Desktop image
2. Open "Show Applications" from the left tool bar.
3. Select "Software" and open.

**Current behavior**
For software market it shows the error below.
![software-market content is blank](https://user-images.githubusercontent.com/44960524/57205827-e3237a80-6ff3-11e9-87ec-f396f846868b.png)

After sometimes,The software market shows categories but with empty content and an error message: Socket I/O timed out.
![categories are empty](https://user-images.githubusercontent.com/44960524/57205858-182fcd00-6ff4-11e9-9be6-d111d2328b53.png)

**Expected behavior**
The software market should listed the software available.

Environment:

- Clear Linux OS version: [cat /usr/lib/os-release]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29160
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

- Bundles: [e.g. sudo swupd bundle-list]
NetworkManager
acpica-unix2
alsa-utils
ansible
baobab
bc
binutils
bison
bootloader
c-basic
cheese
cloc
clr-network-troubleshooter
containers-basic
cpio
cronie
cryptography
curl
darktable
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-kde-libs
desktop-locales
dev-utils
devpkg-base
devpkg-llvm
diffutils
dnf
docutils
dpdk
education-preschool
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
games
gdb
geany
gedit
gimp
git
gjs
glibc-locale
glmark2
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
hexchat
htop
icdiff
inotify-tools
iperf
ipmitool
iproute2
iptables
kbd
kde-frameworks5
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
make
man-pages
meld
minetest
minetestserver
minicom
nasm
nautilus
net-tools
network-basic
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-legacy
os-core-update
os-core-webproxy
os-utils-gui
p11-kit
package-utils
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
qt-basic
qt-core
seahorse
software-defined-cockpit
strace
sudo
sysadmin-basic
syslinux
telemetrics
texinfo
thermal_daemon
thunderbird
tigervnc
tmux
totem
tzdata
unzip
v4l-utils
valgrind
vim
virt-viewer
vlc
vnc-server
webkitgtk
wget
which
wpa_supplicant
x11-server
x11vnc
xemacs
xfce4-desktop
xz
znc
zstd

Additional Context
Live Desktop Image version: 29160

**Comment by anselmolsm** [comment]
The error messages show there are networking issues.
BTW, are you behind a proxy?

**Comment by clhuitheng** [comment]
> The error messages show there are networking issues.
> BTW, are you behind a proxy?

Yes. Currently, the office network is with proxy set-up. So, it happen to be so for proxy, or this is a bug?

**Comment by zmdismai** [comment]
Just to share my experience with Software Market... I am able to open it with no issue but I can see the same error message:

![softwaremarket](https://user-images.githubusercontent.com/39295394/57351615-17ad4880-7152-11e9-88f4-a7548db24e93.png)

Also, I encountered a situation where the Software Market suddenly stopped responding and I had to kill it manually. I'm thinking that this app is not really stable.

**Comment by josuedhg** [comment]
I sent a patch for the socket i/o timeout issue yesterday I hope it is going to be available in today's release. Regarding the hang, if u see again the issue would be great to have other issue with more info about that.

**Comment by mrkz** [comment]
This should be fixed, please create a new issue if you still face this problem.
