### ISSUE TITLE
Consider Including XPad kernel module

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#677]
Please consider Including xpad kernel module for a wide range of controller / gamepad support.

I believe this will require something like:
```
CONFIG_INPUT_JOYSTICK=y
CONFIG_JOYSTICK_XPAD=m
CONFIG_JOYSTICK_XPAD_FF=y
CONFIG_JOYSTICK_XPAD_LEDS=y
```
for the kernel config.

Refer to:
- https://www.kernel.org/doc/html/v5.0/input/devices/xpad.html
- https://github.com/paroj/xpad

**Comment by ahkok** [comment]
@miguelinux for `linux-native`...

**Comment by miguelinux** [comment]
Please find it at 5.0.13-752 native version.

**Comment by pceiley** [comment]
Works a treat - thanks!
