### ISSUE TITLE
Default EDITOR vs vim bundle status is incoherent

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#679]
Default EDITOR variable seems to be "vim", but vim bundle seems not installed by default ?

The end result is this :
>$ git commit --amend
>hint: Waiting for your editor to close the file... error: cannot run vim: No such file or directory
>error: unable to start editor 'vim'
>Please supply the message using either -m or -F option.
>$ echo $EDITOR
>vim
>$ vim
>vim: command not found
>To install vim use: sudo swupd bundle-add vim

So I guess, either vim bundle should be installed in standard, or EDITOR should point to default editor ? gedit ? (wouldn't work in console mode of course)

>$ swupd info | grep version
>Installed version: 29200

**Comment by fenrus75** [comment]
if [[ -x "/bin/vi" ]]; then
        EDITOR="/usr/bin/vi"                    # needed for packages like
cron
else
        EDITOR="/usr/bin/nano"                  # needed for packages like
cron
fi


is what we do so... confused?

**Comment by nsauzede** [comment]
you're right, I totally forgot I used a legacy user profile script setting EDITOR=vim
