### ISSUE TITLE
Firefox icon missing in KDE

### ISSUE THREAD

**Issue by shelterx** [clearlinux/distribution#681]
NAME="Clear Linux OS"
VERSION=1
VERSION_ID=29250

Firefox icon is not showing in KDE Applications menu, instead it shows a generic icon.

**Comment by sunnyflunk** [comment]
`breeze-icons` doesn't include an icon for firefox, so it is relying on a fallback being shipped in `/usr/share/icons/hicolor/` or `/usr/share/pixmaps/`

So could extract the tarball in the build to add the icons from the source.

**Comment by anselmolsm** [comment]
Fixed in release 30000.
