### ISSUE TITLE
Add redshift

### ISSUE THREAD

**Issue by shelterx** [clearlinux/distribution#682]
Please add redshift from http://jonls.dk/redshift/

**Comment by ahkok** [comment]
Will be in a release in 1-2 days in a `redshift` bundle.

**Comment by miguelinux** [comment]
Also if you are using Gnome, you can enable the Night Light in gnome
settings, and schedule on/off times.

**Comment by shelterx** [comment]
Yes, also in KDE when using wayland, But if you're using anything else you might need redshift. Thanks for adding it.
