### ISSUE TITLE
Add kdeconnect

### ISSUE THREAD

**Issue by sunnyflunk** [clearlinux/distribution#685]
Latest release is https://download.kde.org/stable/kdeconnect/1.3.4/kdeconnect-kde-1.3.4.tar.xz

From memory it autospec'ed cleanly. It requires `sshfs` to be added as a custom addition of the managed bundle so it can mount the phone's storage (as not everyone will have the `storage-utils` bundle installed).

**Comment by ahkok** [comment]
Done, should be in a build in 1-2 days.
