### ISSUE TITLE
Failed to install application (LibreOffice) using flatpak

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#688]
**Description**
Installing application (LibreOffice) using flatpak. Initial before installation, perform the command sudo swupd bundle-add desktop. Once the bundle of desktop installed, an error message prompted when proceed to flatpak installation:" flatpak install --user flathub org.libreoffice.LibreOffice" as below:-

buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a /etc $ flatpak install --user flathub org.libreoffice.LibreOffice
error: Remote "flathub" not found

**To Reproduce**
1.	Install the image
2.	Open terminal
3.	Type sudo swupd bundle-add desktop to install Desktop bundles
4.	Type "flatpak install --user flathub org.libreoffice.LibreOffice" to install Libreoffice using flatpak

**Current behavior:**
1.	Error message: " error: Remote "flathub" not found" prompted when executing command "flatpak install --user flathub org.libreoffice.LibreOffice".
2.	When trying to verbose the command
buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a /etc $ flatpak -vvv --user install flathub org.libreoffice.LibreOffice , below messages shown:
F: Opening user flatpak installation at path /home/buildat/.local/share/flatpak
F: No installations directory in /etc/flatpak/installations.d. Skipping
error: Remote "flathub" not found
Refer to Screenshot A below.

**Expected behavior:**
1.	No error message prompt during executing command "flatpak install --user flathub org.libreoffice.LibreOffice".

**Environment:**
•	buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $
•	Bundles:
NetworkManager
acpica-unix2
alsa-utils
atom
baobab
binutils
bison
bootloader
c-basic
cheese
clr-network-troubleshooter
cronie
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
devpkg-base
devpkg-opencv
diffutils
dpdk
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
iproute2
iptables
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libreoffice
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sysadmin-basic
syslinux
thermal_daemon
tigervnc
tmux
totem
tzdata
unzip
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Screenshots**
Screenshot A
![image](https://user-images.githubusercontent.com/50229294/57356271-9cc04e00-71a2-11e9-8a6f-8be106eb7e17.png)

**Comment by mrkz** [comment]
this is expected, as the flathub repository is set up when a user logins for the first time into the desktop (GNOME) session. (the flathub set-up helper is executed at user-login)
