### ISSUE TITLE
Desktop hang & black screen when waking from suspend

### ISSUE THREAD

**Issue by m0nik3r** [clearlinux/distribution#69]
Hi I'm currently using clear linux as a bare metal OS for my laptop which has a i7-6500U. 

When the system is suspended then woken, the screen stays black, and does not wake up, forcing me to power cycle the system. 

When loading some sites that are slower to load, firefox will hang and then the system will hang a few seconds after, again forcing a power cycle. I've tried disabling addons and hardware acceleration in firefox and this doesn't fix the issue.

These issues have only arisen in the past month or so, I'm not sure exactly which version. I'd be grateful for an troubleshooting assistance, or fixes to these issues.

**Comment by AthenasJimenez** [comment]
Hi m0nik3r, 

It would be really helpful to know the release number you have now (if the issue persists). You can check it running: sudo swupd update -s.

Regarding to Firefox issue, would you mind to share a site as an example?

**Comment by rustylynch** [comment]
Is your laptop using Intel graphics?

**Comment by m0nik3r** [comment]
Yes, very sorry for the late reply. I was using 22510 when both issues were present. I believe that when I downgraded to ~22230 or so the firefox-hang bug went away, but the system would still get stuck in suspension.

Downgrading further to 21700 fixed both of the issues for me.

An example for me (the larger issue) was when checking amazon order statuses

**Comment by rustylynch** [comment]
This could be a duplicate of:
https://github.com/clearlinux/distribution/issues/58

... which is caused by a patch to Intel graphics

**Comment by rustylynch** [comment]
The offending patch from #58 was removed with release 22860.  Try testing this again after updating to see if this was a dup

**Comment by m0nik3r** [comment]
It've updated to 23030, and everything seems to be working. Thank you!
