### ISSUE TITLE
Long PassPhrase able to enter without limit when choosing to encrypt partition

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#690]
**Description**
During installation of the images, encryption is selected for boot, swap & root and there is not limit for the long passphrase if used to encrypt the partition. The installer should be able to limit character amount use to enter for the passphrase. The passphrase confirmation textbox should allow the same amount of characters.
**To Reproduce**
1.	Run the image installer
2.	During the Configure Installation Media, select the harddisk 
3.	Go to the Advanced Configuration
4.	In the Advanced Configuration screen, select to manual partition it
5.	Select the boot partition & Partition Setup Screen will appear.
6.	Highlight the Encrypt column using "Spacebar" key. An encryption screen will prompt out to enter the passphrase.
7.	Enter a long passphrase- "1234567890qwertyuiopasdfghjklzxcvbnm"
8.	Enter the same long passphrase- "1234567890qwertyuiopasdfghjklzxcvbnm"
9.	No warning from the installer mentioning the exceed limit of the character.
10.	Installer should able to limit the character entered in the passphrase column

**Current behavior:**
Able to enter the long passphrase in the encryption screen during installation without warning from the installer mentioning the exceed limit of the character. This encryption can be applied on the boot, swap & root partition.

**Expected behavior:**
Image installer should limit the character to be entered in the passphrase column with warning message on mentioning exceeding characters. This encryption can be applied on the boot, swap & root partition.

**Environment:**

•	buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29210
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $

**Screenshots**
Screenshot not available due to this is during installation process.

**Comment by mdhorn** [comment]
Thank you for your feedback.

Actually, we do have a limit of 94 characters.
Passphrase checking requires a minimum of 8 characters, maximum of 94 characters.

This was selected to be compatible with our LUKS encryption choices:
```
    // EncryptHash use for LUKS encryption
    EncryptHash = "sha256"
    // EncryptCipher use for LUKS encryption
    EncryptCipher = "aes-xts-plain64"
    // EncryptKeySize use for LUKS encryption
    EncryptKeySize = 512
```

**Comment by mrkz** [comment]
Closing as invalid (based on @mdhorn reply).

@izamuin Thanks for the report! :tada:
