### ISSUE TITLE
Unable to run Open CV application.

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#691]
**Description**
After installation of Opencv for image processing, Opencv application is unable to run. When running the command opencv --help, error message of "opencv: command not found" prompt out.
**To Reproduce**
1.	Install the image
2.	Open terminal
3.	Type sudo swupd bundle-add devpkg-opencv
4.	Installation able to completed with no issue.
5.	To verify the installation completion, in the terminal type opencv –help.

**Current behavior:**
Successfully install openCV but unable to run the openCV application. When starting the program by verifying the apps using the opencv -- help commands, message: " opencv: command not found" resulteed from the entered command. Refer to Screenshot A below.

Expected behavior:
A list of related help files for openCV apps will show upon verifying the apps using the opencv -- help commands.

**Environment:**

•	buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
buildat@clr-13a6e9cdec5146b5ab8fd49a8545329a ~ $
•	Bundles:
NetworkManager
acpica-unix2
alsa-utils
atom
baobab
binutils
bison
bootloader
c-basic
cheese
clr-network-troubleshooter
cronie
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
devpkg-base
devpkg-opencv
diffutils
dpdk
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
iproute2
iptables
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libreoffice
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sysadmin-basic
syslinux
thermal_daemon
tigervnc
tmux
totem
tzdata
unzip
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd
Screenshots
Screenshot A 
![image](https://user-images.githubusercontent.com/50229294/57358232-8bc60b80-71a7-11e9-906c-8603b8501f85.png)

**Comment by fenrus75** [comment]
so... opencv is pretty much a library, not an application. not sure how you
expect there to be an "opencv" binary. ?

**Comment by ahkok** [comment]
try using `opencv_version` or even `opencv_interactive-calibration` (requires a webcam)
