### ISSUE TITLE
Gmail with Thunderbird is not working properly

### ISSUE THREAD

**Issue by zakiahmdismail** [clearlinux/distribution#692]
**Description**
Gmail with Thunderbird is not working as expected:

1) I was able to log in with the setting stated in the steps to reproduce, but Thunderbird failed to connect to imap.google.com; therefore, I was not able to receive any email or load Inbox. I was able to send one email from this account with Thunderbird; however, when I attempted to send another email, the connection to smtp.gmail.com now failed:

![smtp-error](https://user-images.githubusercontent.com/39295394/57350021-efbae680-714b-11e9-86af-2ea1573b6728.png)

2) I logged out of the account and attempted to reproduce the issue again, now I am not able to log in. The error message is as below:

![usernamepasswrong](https://user-images.githubusercontent.com/39295394/57350000-cbf7a080-714b-11e9-902e-ca75f7393984.png)
I am confident that my email address and password are correct.

**To Reproduce**

1. Boot up **Live Desktop** image
2. Install Clear Linux
3. Upon installation, open Mozilla Thunderbird
4. Choose to set up a new email
5. Enter your display name
6. Enter your Gmail email address
7. Enter your Gmaill account password
8. Incoming (IMAP):
    Server hostname: imap.gmail.com
    Port: 993
    SSL: SSL/TLS
    Authentication: OAuth2
9. Outgoing (SMTP):
    Server hostname: smtp.gmail.com
    Port: 587
    SSL: STARTLLS
    Authentication: OAuth2
10. Username: Your email address for both Incoming and Outgoing.

**Current behavior**
Not able to receive emails or even load Inbox
Not able to send email (only able to send once)
After log out, not able to log in

**Expected behavior**
Should be able to send & receive email without issue, should be able to load Inbox, should be able to log in again after logging out.

**Environment**:

- Clear Linux OS version: [cat /usr/lib/os-release]
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**Additional Context**
IMAP is enabled for my Gmail account:
![imap](https://user-images.githubusercontent.com/39295394/57350356-5a205680-714d-11e9-8687-03ec8f104848.png)

Reference: http://kb.mozillazine.org/Using_Gmail_with_Thunderbird_and_Mozilla_Suite

**Comment by ahkok** [comment]
We don't modify thunderbird - it is the upstream build. There may be a proxy issue, but other than that, this would be a configuration error or an upstream issue.

**Comment by lebensterben** [comment]
My thunderbird works great with Gmail. Do you have 2-step verification enabled for your Gmail account? If so,  you need to generate a app-specific password first.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by puneetse** [comment]
I'm closing this issue because all signs so far point to a configuration or network issue and we haven't heard back. If you're continuing to have problems, please feel free to reopen.
