### ISSUE TITLE
No systemd unit for cronie

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#693]
**Description**
Failure message: “Failed to start crond.service: Unit crond.service not found.” prompted when running "sudo systemctl status crond" command to check the Crond status after successfully downloaded and installed the swupd bundle-add cronie. 
It seems like the crond services not available after the sudo swupd bundle-add cronie completed installation.

**To Reproduce**
1.	Install the image
2.	Open terminal
3.	Type "sudo swupd bundle-add cronie" to install crond services
4.	Type "sudo systemctl status crond" to check for the services status.
5.	If the services is not running type " sudo systemctl start crond"

**Current behavior:**
After complete install the cronie. the crond services is not available even after trying to start the services using the command "sudo systemctl start crond". Result is showing:  “Unit crond.service could not be found.”
When restarting the services using the command "sudo systemctl start crond"
Result is showing: “Failed to start crond.service: Unit crond.service not found.”
Refer to Screenshot A below.

**Expected behavior:**
There should be no failure message shown after complete installing the cronie. The crond services should be available.
**Environment:**
•	buildat@clr-01 ~ $ cat /usr/lib/os-release
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29210
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
buildat@clr-01 ~ $
•	Bundles:
NetworkManager
NetworkManager-extras
acpica-unix2
alsa-utils
atom
baobab
binutils
bison
bootloader
c-basic
cheese
clr-network-troubleshooter
cronie
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
devpkg-base
devpkg-opencv
diffutils
dpdk
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
iproute2
iptables
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libreoffice
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sysadmin-basic
syslinux
thermal_daemon
tigervnc
tmux
totem
tzdata
unzip
vnc-server
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstd

**Screenshots**
Screenshot A

![image](https://user-images.githubusercontent.com/50229294/57356382-e4df7080-71a2-11e9-89d9-2f2771792481.png)

**Comment by miguelinux** [comment]
To schedule task Cl uses [systemd-timers](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) 

You can find examples in google with the word `systemd timers`

**Comment by ahkok** [comment]
Upstream doesn't even ship a service file :(

**Comment by ahkok** [comment]
Title error: cron runs fine, but needs a service file.

**Comment by ahkok** [comment]
Fixed in `cronie-1.5.4`. Unit file name is `cronie.service` (not **crond**!)
