### ISSUE TITLE
systemd.directives man page missing

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/distribution#698]
On Arch Linux, I often consult the `systemd.directives(7)` man page to discover where configuration directives are documented, but it appears to be missing in Clear Linux OS.

**Comment by sunnyflunk** [comment]
I believe `lxml` needs to be added as a build requires. The source suggests that it won't generate the indices without it https://github.com/systemd/systemd/blob/master/man/meson.build#L102.

**Comment by ahkok** [comment]
`systemd-242-254`
