### ISSUE TITLE
dbus sysconfdir change breaks pacrunner build

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/distribution#699]
make autospec of pacrunner resulted in a new file created under /etc2:
```
 /usr/bin/mkdir -p '/builddir/build/BUILDROOT/pacrunner-0.15-49.x86_64/etc2/dbus-1/system.d'
 /usr/bin/install -c -m 644 src/pacrunner.conf '/builddir/build/BUILDROOT/pacrunner-0.15-49.x86_64/etc2/dbus-1/system.d'
```

/usr/lib64/pkgconfig/dbus-1.pc now contains:
`sysconfdir=/etc2
`
Which was picked up by rebuilding pacrunner.

Not sure if this was intended or not, but I had to add:
`rm -rf %{buildroot}/etc2`
which I stole from the recent change to dbus package.

**Comment by fenrus75** [comment]
your real problem is that both /etc and /etc2 are wrong for this

the dbus files must go into /usr/share/dbus-1 instead

**Comment by ahkok** [comment]
Fixing this in `dbus` atm - the installed `pc` files just have `s/etc2/etc/`.
