### ISSUE TITLE
Nautilus (Gnome Files) not displaying some thumbnails

### ISSUE THREAD

**Issue by pceiley** [clearlinux/distribution#701]
While thumbnails appear to show for PNG files, they don't show for JPG files (and possibly others - but haven't tested).

As a troubleshooting step: Manually running /usr/bin/gdk-pixbuf-thumbnailer against affected JPG files works fine.

**Comment by mariojuniorjp** [comment]
For me, nautilus doesn't show any thumbnails, videos, jpeg, png or whatever.

**Comment by ahkok** [comment]
for me, just JPG XD

**Comment by rpkemp** [comment]
I have a weird situation where thumbnails show up for some files of types TIFF, JPEG (see screenshot below). I haven't got any PNG files with thumbnails (contrary to the original posting). I can't immediately identify any differences between files that would cause some to have thumbnails and others not.

I'm happy to provide further information if anyone knows the right questions to ask!

![screenshot-nautilus](https://user-images.githubusercontent.com/51866469/59557051-8b4f3a80-8fc7-11e9-88ad-1826341b1522.png)

**Comment by lebensterben** [comment]
I have some screenshots under `~/Pictures` which are all in `png` format. Only two of them have thumbnails available.

**Comment by mrkz** [comment]
I have identified the problem when generating image thumbnails. I'm pushing a change to [nautilus package](https://github.com/clearlinux-pkgs/nautilus) that should fix this issue.

Hopefully, the fix should be available for release **29980** (or later)

I will close this once the release is out.

**Comment by mrkz** [comment]
Release **29980** is available now :+1: 

In order to re-create the failed thumbnails, please run the following in a terminal:
```bash
$ rm -rf ~/.cache/thumbnails/fail/gnome-thumbnail-factory/*
```

New installs or new users should not need to run the previous command as those may be unaffected from 29980 and afterward.

Thanks for the bug report! :tada:

**Comment by bkdwt** [comment]
> 
> 
> Release **29980** is available now 👍
> 
> In order to re-create the failed thumbnails, please run the following in a terminal:
> 
> ```shell
> $ rm -rf ~/.cache/thumbnails/fail/gnome-thumbnail-factory/*
> ```
> 
> New installs or new users should not need to run the previous command as those may be unaffected from 29980 and afterward.
> 
> Thanks for the bug report! 🎉

Hell yeah! Thanks for this fix.

**Comment by rpkemp** [comment]
Back to normal now, phew! Thanks for sorting this out.

**Comment by Nestak2** [comment]
@mrkz The command
`$ rm -rf ~/.cache/thumbnails/fail/gnome-thumbnail-factory/*`
doesn't fixes the issue for me. I only see thumbnails for png files, not for jpg.
My Ubuntu version:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Any idea what else I should do?

**Comment by lebensterben** [comment]
>@mrkz The command ...

@Nestak2 This post and all discussions are for Clear Linux and not Ubuntu.
