### ISSUE TITLE
Pink screen with artefacts on Gnome Videos

### ISSUE THREAD

**Issue by ghost** [clearlinux/distribution#702]
**Describe the bug**
After the last update of Clear Linux, I can not play any video using Gnome Video regardless of the type of codec used by the file.
**To Reproduce**
1. Just open any video file with Gnome Video
**Screenshot** 
![Captura de tela de 2019-05-09 12-18-19](https://user-images.githubusercontent.com/11687827/57465239-938fb980-7254-11e9-9317-8c930b52eb62.png)

NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29310
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"

FFmpeg already installed.

**Comment by pceiley** [comment]
I've never had much luck with totem on any distribution. Gnome MPV from flathub looks the same and always works flawlessly for me https://flathub.org/apps/details/io.github.GnomeMpv

**Comment by mariojuniorjp** [comment]
> I've never had much luck with totem on any distribution. Gnome MPV from flathub looks the same and always works flawlessly for me https://flathub.org/apps/details/io.github.GnomeMpv

Thanks! Installed and working.

**Comment by phmccarty** [comment]
@chivakker

**Comment by chivakker** [comment]
@mariojuniorjp can you elaborate on which ffmpeg is installed in your system?  what happens if you remove it locally?

I will take a look and this information can help.

**Comment by mariojuniorjp** [comment]
> @mariojuniorjp can you elaborate on which FFmpeg is installed in your system? what happens if you remove it locally?
> 
> I will take a look and this information can help.

I uninstalled Clear Linux, but I was using the latest stable version of FFmpeg using this method here: https://github.com/clearlinux/distribution/issues/429#issuecomment-489389134

**Comment by chivakker** [comment]
mpv stopped working on x11 backend and was fixed.  In my testing it works fine with codecs available.  Where codecs are not available file won't play at all.
