### ISSUE TITLE
clear-29350-installer does not autostart

### ISSUE THREAD

**Issue by clefrks** [clearlinux/distribution#703]
When booting up the image, it did not go into clr-installer, instead prompt to login.

**Comment by mdhorn** [comment]
Please specify the exact image in question.

Neither clear-29350-live-server.iso.xz nor clear-29350-live-desktop.iso.xz will start the installer by default, by design.

**Comment by clefrks** [comment]
This image: https://cdn.download.clearlinux.org/releases/current/clear/clear-29350-installer.img.xz

**Comment by ionutnechita** [comment]
this issue also appears on 29360.

**Comment by mdhorn** [comment]
The clr-installer service is no longer supported.
Both the clear-xxxxx-installer.iso.xz and clear-xxxxx-installer.img.xz images will be removed in the very near future.

The two supported images going forward are:
clear-xxxxx-live-desktop.iso.xz 
- boots into a live desktop environment
- contains a graphical installer which can be started on demand

clear-xxxxx-live-server.iso.xz
- boots into a live image environment with a login prompt
- provides directions for setting root temp password, configuring the network,  and launching installer
- contains a text-based installer which can be started on demand

**Comment by dorileo** [comment]
I assume this issue is invalid now, @mdhorn can we close it?

**Comment by mdhorn** [comment]
Yes, this can be closed.  Thx
