### ISSUE TITLE
Uninstalled apps still showing in the software center. (not updated in the swupd bundle-list)

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#704]
**Description**
Installed Remmina from the Software Centre.  After the installation, in the Installed tab (Software Centre) Remmina is available to uninstall using uninstall button, remove. After finish uninstall run sudo swupd bundle-list | grep Remmina. Remmina is still showing in the list, even uninstalled from the software Centre.

**To Reproduce**
1.	Install clear linux desktop beta image
2.	Click on the Gnome Sotware inside all Apps
3.	Click on the Other tab/ find  to select Remmina
4.	Install Remmina until it complete
5.	After the complete installation, open terminal & type
•	$ sudo swupd bundle-list ( this will displayed the list of software install. Remmina should be inside the list.
6.	After the confirmation the apps is in the list, uninstall Remmina using the Uninstall button inside the Gnome Software
7.	Open terminal and type “sudo swupd bundle-list | grep Remmina

**Current behavior:**
Remmina is still showing in the list even after it is uninstalled from the Gnome Software Centre.

**Expected behavior:**
Remmina not supposed to be listed in the bundle- list after uninstalling in the Gnome Software.
Environment:
•	Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29260
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**•	Bundles:**
Babel
NetworkManager
NetworkManager-extras
Remmina
Sphinx
acpica-unix2
alsa-utils
baobab
bc
binutils
bison
bootloader
c-basic
cabextract
cheese
cloc
clr-network-troubleshooter
containers-basic
containers-basic-dev
cpio
cronie
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
devpkg-LVM2
devpkg-SDL
devpkg-acl
devpkg-alsa-lib
devpkg-apr
devpkg-at-spi2-atk
devpkg-at-spi2-core
devpkg-atk
devpkg-attr
devpkg-audit
devpkg-base
devpkg-boost
devpkg-cairo
devpkg-compat-fuse-soname2
devpkg-cryptsetup
devpkg-curl
devpkg-cyrus-sasl
devpkg-dbus
devpkg-e2fsprogs
devpkg-elfutils
devpkg-expat
devpkg-fontconfig
devpkg-freetype
devpkg-fribidi
devpkg-fuse
devpkg-gcr
devpkg-gdk-pixbuf
devpkg-glib
devpkg-gmime
devpkg-gnutls
devpkg-gobject-introspection
devpkg-googletest
devpkg-graphite
devpkg-gsl
devpkg-gtk
devpkg-gtk-doc
devpkg-gtk3
devpkg-guile
devpkg-harfbuzz
devpkg-hwloc
devpkg-icu4c
devpkg-ipmctl
devpkg-ipset
devpkg-iptables
devpkg-json-c
devpkg-kmod
devpkg-krb5
devpkg-libX11
devpkg-libXScrnSaver
devpkg-libXau
devpkg-libXcursor
devpkg-libXdamage
devpkg-libXdmcp
devpkg-libXext
devpkg-libXfixes
devpkg-libXft
devpkg-libXmu
devpkg-libXpm
devpkg-libXres
devpkg-libXt
devpkg-libXtst
devpkg-libXv
devpkg-libXvMC
devpkg-libXxf86misc
devpkg-libXxf86vm
devpkg-libarchive
devpkg-libassuan
devpkg-libcap
devpkg-libcap-ng
devpkg-libcgroup
devpkg-libdrm
devpkg-libepoxy
devpkg-libevent
devpkg-libffi
devpkg-libgcrypt
devpkg-libgpg-error
devpkg-libidn
devpkg-libidn2
devpkg-libinput
devpkg-libjpeg-turbo
devpkg-libmicrohttpd
devpkg-libmnl
devpkg-libnetfilter_conntrack
devpkg-libnetfilter_cthelper
devpkg-libnetfilter_cttimeout
devpkg-libnetfilter_queue
devpkg-libnfnetlink
devpkg-libnftnl
devpkg-libnl
devpkg-libpcap
devpkg-libpciaccess
devpkg-libpipeline
devpkg-libpng
devpkg-libpthread-stubs
devpkg-librsvg
devpkg-libseccomp
devpkg-libsecret
devpkg-libssh2
devpkg-libtasn1
devpkg-libtirpc
devpkg-libunwind
devpkg-libusb
devpkg-libuser
devpkg-libva
devpkg-libxcb
devpkg-libxkbcommon
devpkg-libxml2
devpkg-libxslt
devpkg-libzip
devpkg-llvm
devpkg-lua
devpkg-lz4
devpkg-mesa
devpkg-metrics-discovery
devpkg-multipath-tools
devpkg-ncurses
devpkg-ndctl
devpkg-nettle
devpkg-nftables
devpkg-nghttp2
devpkg-nspr
devpkg-nss
devpkg-ntfs-3g
devpkg-open-iscsi
devpkg-openmpi
devpkg-openssl
devpkg-p11-kit
devpkg-pacrunner
devpkg-pango
devpkg-pciutils
devpkg-pcre
devpkg-pcre2
devpkg-pixman
devpkg-pkcs11-helper
devpkg-pmdk
devpkg-popt
devpkg-postgresql
devpkg-procps-ng
devpkg-qtbase
devpkg-qttools
devpkg-rdma-core
devpkg-readline
devpkg-sqlite-autoconf
devpkg-startup-notification
devpkg-subunit
devpkg-systemd
devpkg-talloc
devpkg-telemetrics-client
devpkg-tiff
devpkg-userspace-rcu
devpkg-util-linux
devpkg-util-macros
devpkg-vala
devpkg-wayland
devpkg-wayland-protocols
devpkg-xapian-core
devpkg-xcb-proto
devpkg-xorgproto
devpkg-xtrans
devpkg-xz
devpkg-zlib
devpkg-zstd
diffoscope
diffutils
dnf
docbook-utils
docutils
dosfstools
doxygen
dpdk
editors
emacs
eog
ethtool
evince
evolution
file
file-roller
findutils
fio
firefox
flatpak
flex
fonts-basic
fuse
gdb
gedit
gimp
git
gjs
glibc-locale
glmark2
global
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
go-basic
gparted
gpgme
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
httpd
icdiff
inotify-tools
intltool
iperf
iproute2
iptables
joe
kbd
kernel-install
kernel-iot-lts2018
kernel-native
koji
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libarchive
libglib
libstdcpp
libva-utils
libxml2
libxslt
linux-firmware
linux-firmware-extras
linux-firmware-wifi
linux-tools
llvm
mail-utils
mail-utils-dev
make
man-pages
meld
minicom
mixer
mkosi
mutt
nasm
nautilus
net-tools
network-basic
network-basic-dev
nfs-utils
nginx
nodejs-basic
notmuch
openblas
openldap
openssh-server
openssl
openvswitch
os-clr-on-clr
os-core
os-core-dev
os-core-update
os-core-update-dev
os-core-webproxy
os-installer
p11-kit
package-builder
package-utils
parallel
parted
patch
perl-basic
perl-basic-dev
plzip
pmdk
polkit
postgresql
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
qemu-guest-additions
qt-basic
qt-core
rhythmbox
samba
scons
seahorse
shells
smartmontools
storage-utils
storage-utils-dev
strace
subversion
sudo
sysadmin-basic
sysadmin-basic-dev
syslinux
texinfo
texlive
thermal_daemon
tigervnc
tmux
totem
tzdata
unbundle
unzip
user-basic
valgrind
vim
vnc-server
web-server-basic
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xfsprogs
xz
yasm
znc
zsh
zstd
buildat@CL-02
**Screenshots**
Log file A
 
[remmina.txt](https://github.com/clearlinux/distribution/files/3165569/remmina.txt)

**Comment by josuedhg** [comment]
gnome-software have multi sources, one of them is flatpak then you have to be sure that you are installing the bundle in order to see it with swupd

**Comment by josuedhg** [comment]
check with "flatpak list" if your remina app is there

**Comment by josuedhg** [comment]
sorry I misunderstood the issue, this issue is already fixed in the current version
