### ISSUE TITLE
Cannot Uninstall Vim 

### ISSUE THREAD

**Issue by izamuin** [clearlinux/distribution#705]
**Description**
Removal of Vim using “$ sudo swupd bundle-remove vim” failed as a few additional bundle was added in during image installation. Vim cannot be removed due to the bundle is required by other bundles

**To Reproduce**
1.	Install clear linux desktop beta image.
2.	Upon installation completed, open terminal.
3.	Enter sudo swupd bundle-remove vim

**Current behavior:**
Vim is not removed/uninstalled after applying the command sudo swupd bundle-remove vim.

**Expected behavior:**
Vim expected to be removed after the command applied.
Environment:
•	Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29260
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**•	Bundles:**
NetworkManager
 acpica-unix2
 alsa-utils
 baobab
 binutils
 bison
 bootloader
 c-basic
 cheese
 cloud-api
 cloud-control
 clr-network-troubleshooter
 curl
 desktop
 desktop-apps
 desktop-assets
 desktop-autostart
 desktop-gnomelibs
 desktop-locales
 diffutils
 dnf
 dpdk
 eog
 ethtool
 evince
 evolution
 file
 file-roller
 findutils
 firefox
 flatpak
 flex
 fonts-basic
 fuse
 gedit
 gimp
 git
 gjs
 glibc-locale
 gnome-base-libs
 gnome-calculator
 gnome-characters
 gnome-color-manager
 gnome-disk-utility
 gnome-font-viewer
 gnome-logs
 gnome-music
 gnome-photos
 gnome-screenshot
 gnome-system-monitor
 gnome-todo
 gnome-weather
 graphviz
 gstreamer
 gvim
 gzip
 hardware-printing
 htop
 iperf
 iproute2
 iptables
 kbd
 kernel-install
 kernel-lts
 kernel-lts2018
 kvm-host
 less
 lib-imageformat
 lib-opengl
 lib-openssl
 lib-samba
 libX11client
 libglib
 libstdcpp
 libva-utils
 linux-firmware
 linux-firmware-extras
 linux-firmware-wifi
 llvm
 locales
 make
 man-pages
 minicom
 nasm
 nautilus
 net-tools
 network-basic
 openblas
 openldap
 openssh-server
 openssl
 openvswitch
 os-core
 os-core-update
 os-core-webproxy
 p11-kit
 package-utils
 parallel
 patch
 perl-basic
 polkit
 powertop
 procps-ng
 pulseaudio
 pygobject
 python2-basic
 python3-basic
 seahorse
 sqlite
 strace
 sudo
 sysadmin-basic
 syslinux
 telemetrics
 thermal_daemon
 tmux
 totem
 tzdata
 unzip
 vim
 webkitgtk
 wget
 which
 wpa_supplicant
 x11-server
 xemacs
 xz
 znc
 zstda

**Screenshots**
Log file A
[vim.txt](https://github.com/clearlinux/distribution/files/3165593/vim.txt)

**Comment by phmccarty** [comment]
@izamuin According to your `vim.txt` log file, `editors`, `user-basic`, and `os-clr-on-clr` are installed, but I do not see these 3 bundles in the list of installed bundles from your report?

Are these 3 bundles actually installed on your system?

**Comment by izamuin** [comment]
@phmccarty i am attaching the latest log. which have the bundles is installed

[Vim remove.txt](https://github.com/clearlinux/distribution/files/3170715/Vim.remove.txt)

**Comment by puneetse** [comment]
@izamuin according to that output you have the bundles @phmccarty mentioned that also include vim. So it is actually working according to the way those bundles are designed.

The command `sudo swupd bundle-list --has-dep=vim` can help highlight bundles which have vim as a dependency.

**Comment by fenrus75** [comment]
this request is blocked on the "also-add" feature landing in swupd

**Comment by mrkz** [comment]
This should be fixed by now
