### ISSUE TITLE
Unable to pull Ubuntu container image

### ISSUE THREAD

**Issue by ganweehuang** [clearlinux/distribution#706]
Description
Error message “Timeout exceeded” prompted when pulling the latest Ubuntu container image after Clear Linux v29260 installation.

To Reproduce
1.	Install Clear Linux v29260
2.	Open a terminal to Install Docker
3.	Enable the Docker service
4.	Pull Ubuntu container image $ sudo docker pull ubuntu

Current behavior
Error message “Timeout exceeded” prompted when pulling the latest Ubuntu container image.

Expected Behavior
The docker pull umage-name will download an image to the server from docker registry
Environment:

![log](https://user-images.githubusercontent.com/50228327/57507433-5f3dfb00-7331-11e9-9a5d-23c89e507ebe.JPG)

•	Clear Linux OS version:
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29350
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

•	Bundles:
NetworkManager
acpica-unix2
alsa-utils
baobab
binutils
bison
bootloader
c-basic
cheese
cloud-api
cloud-control
clr-network-troubleshooter
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
dnf
dpdk
eog
ethtool
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
htop
iperf
iproute2
iptables
kbd
kernel-install
kernel-lts
kernel-lts2018
kvm-host
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
locales
make
man-pages
minicom
nasm
nautilus
net-tools
network-basic
openblas
openldap
openssh-server
openssl
openvswitch
os-core
os-core-update
os-core-webproxy
p11-kit
package-utils
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python2-basic
python3-basic
seahorse
sqlite
strace
sudo
sysadmin-basic
syslinux
telemetrics
thermal_daemon
tmux
totem
tzdata
unzip
vim
webkitgtk
wget
which
wpa_supplicant
x11-server
xemacs
xz
znc
zstda

**Comment by puneetse** [comment]
Is your networking otherwise functional?

Are you on a networking requiring an outbound proxy server? If so, you probably need to tell Docker about the proxy like shown in the Docker docs here: https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

**Comment by puneetse** [comment]
I'm closing this issue because all signs so far point to a network/proxy issue and we haven't heard back. If you continue to have problems, please feel free to reopen.
