### ISSUE TITLE
Enable 64-bit support in wine

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#713]
It looks like the wine packaged with Clear Linux is has win64 support disabled: https://github.com/clearlinux-pkgs/wine/blob/master/wine.spec#L169 . It would be nice if this could be enabled.

I usually expect win64 to be the default, and create a separate `WINEPREFIX` for win32 if needed.

When I try to create a new wine location with `WINEARCH=win64` and run a program it says `wine: WINEARCH set to win64 but '/home/user/.wine' is a 32-bit installation.`

**Comment by ahkok** [comment]
wine64 isn't as useful as many applications don't support it. Enabling it was giving me significant problems to make the 32 bit build which I needed for several applications. The default should remain 32bit though.

If you override WINEARCH you must also set WINEPREFIX to a new location, like `~/.wine64` for instance. You likely already have a 32 bit `~/.wine`.

**Comment by puneetse** [comment]
Thanks for the super fast response. 

> wine64 isn't as useful as many applications don't support it. 

On the other hand, there are some applications that only want to run in a 64-bit context. 

> If you override WINEARCH you must also set WINEPREFIX to a new location, like `~/.wine64` for instance. You likely already have a 32 bit `~/.wine`.

To clarify, I did this and it produces the message I posted above. Maybe wine could use a better output when win64 support is disabled and trying to use `WINEARCH=win64`.

**Comment by Awqre** [comment]
As @puneetse says, 64 bit wine is not included in the bundle and it is necessary for certain programs and games such as World of Warcraft, I would really like to see it added as well.

**Comment by ahkok** [comment]
Well, if someone wants to take a poke at it, permitted they don't break 32bit support, I'm all ears and happy to take patches. I might not get to this soon though, there's a ton on my plate atm.

**Comment by sunnyflunk** [comment]
I actually built this the other day, but hadn't gotten around to testing it. It did make me want to make a minor change to `autospec` to make these double builds a bit cleaner and easier to maintain, but that's probably something that would need discussing before doing a PR.
