### ISSUE TITLE
avahi-daemon bundle in clear linux

### ISSUE THREAD

**Issue by nickcj931** [clearlinux/distribution#714]
Hello,

Is there a chance to have the avahi-daemon bundle included in clear linux? I am trying to test hass.io in Clear Linux

Thanks

**Comment by fenrus75** [comment]
avahi is.. interesting in that it's not very active but very network facing
(basically we'd like our security guys to take a look)

**Comment by nickcj931** [comment]
Hey @fenrus75 thanks for the reply.
When you mean not very active, do you mean as in its dev/usage or active as in resource usage? 

In terms of network facing (I am presuming you are talking about the concern around security?) would it not have the same challenges as zeroconf that is bundled [here](https://github.com/clearlinux/clr-bundles/blob/6f7c4cbd7fc060e3b04595278c7fe67b4818a370/bundles/desktop-kde-apps) 

Ref Security agree that is a concern and needs to be addressed accordingly. However if Clear Linux are trying to position some of the offering as per quote "It is a general-purpose, Linux-based distribution focused on cloud, client, and IoT use cases". Then mDNS type discovery services in the IoT space is pretty critical? 

Again I might be adding 1+1 and getting 10 here since I am not a developer or even attempt to claim I know the intricacies of putting all of this together so feel free to put me in my place 😃

**Comment by fenrus75** [comment]
I meant dev active.. the last release was in 2017 for example

**Comment by thiagomacieira** [comment]
@nickcj931 out of curiosity, what do you need Avahi for? If you only need mDNS resolution, systemd-resolved is plenty capable of doing that. You need to create a .network file in /etc/systemd/networkd for your interface with
```
[Network]
MulticastDNS=resolve
```
and possibly in /etc/systemd/resolved.conf too.

If you need to expose services, that's a different story.

**Comment by lebensterben** [comment]
@nickcj931 

I built the avahi just now. 

First, I disabled the mono c# compiler, qt3, qt4 modules. And I specify python2 and cflags for libdaemon during configuration.

And here are the steps:

1. In `/usr/lib64/pkgconfig` directory, put a new file `libdaemon.pc` with those contents
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libdaemon
Description: a lightweight C library that eases the writing of UNIX daemons
Version: 0.14
Libs: -L${libdir} -ldaemon
Cflags: -D_REENTRANT -I${includedir}
```
Note that `libdaemon` is installed by certain clear bundle but there's no `pkgconfig` file. If you don't have `/usr/include/libdaemon` directory, then this doesn't work and you shall install `libdaemon` first.

2. Then in the directory where the source code of `avahi` is located in, run the following:
```
./configure --with-distro=none --disable-qt3 --disable-qt4 PYTHON=/usr/bin/python2 --disable-mono --disable-monodoc
```
The reason why I specified to use python2 interpreter is because the building process needs gdbm module of python, and my python3 doesn't have such module.
Alternatively, you may try to use `--disable-gdbm` or even `--disable-python`.

3. Then,
```
make && sudo make install
```

**Comment by nickcj931** [comment]
@thiagomacieira  sorry for the late in response, somehow missed your post! 

Avahi is a dependency for Hass.io (which is a home automation software) I would like to try and test it on the Clear Linux platform as it seems a perfect fit for something like this, and I love the bundles where it just keeps everything much more simple! 

Office hass.io GitHub link - https://github.com/home-assistant/hassio-installer

@lebensterben I've not had a chance to have a go at your posted solution (hoping to get around to it this weekend).

**Comment by thiagomacieira** [comment]
@lebensterben:
 > Note that libdaemon is installed by certain clear bundle but there's no pkgconfig file.

Fixing, should be in a build soon as bundle `devpkg-libdaemon`.

> The reason why I specified to use python2 interpreter is because the building process needs gdbm module of python, and my python3 doesn't have such module.

I see and can reproduce that. Will investigate how to add the Python3 version of it.

@nickcj931: Thank you for the link. But I can't find much information about what Hass.io needs Avahi for. The installer is just checking that it is installed, but doesn't do anything with it. https://github.com/home-assistant/hassio seems to be the source, but there's no "avahi" and I don't see anything obvious related to DNS-SD.

**Comment by thiagomacieira** [comment]
Ok, looks like there's no Python3 module called "gdbm". The code should use the generic "dbm" instead.

Debian (and thus Ubuntu) have a compat package they themselves added. It's non-standard.

**Comment by nickcj931** [comment]
@thiagomacieira - done some more reading on this. 
So it isn't really referenced for "use" in hass.io. But to explain this I need to provide a bit more background.

Hass.io is build on Home Assistant. Home Assistant is the actual software, HASS.io is like a "dockerised" version which helps simplify the whole system setup (home assistant is a bit more complex where HASS.io is a bit more user friendly).

Hass.io runs a script on the host OS in our case here being Clear Linux. Part of that script runs a Home Assistant Docker Container. Therefore Avahi use is actually used within Home Assistant (I am presuming it needs access at host level?). 

Avahi is therefore referenced here - https://www.home-assistant.io/components/zeroconf/

Not sure if this answers any questions at all? 

Thanks for all the questions by the way and also spending your time helping on this really appreciate it!

**Comment by lebensterben** [comment]
> Ok, looks like there's no Python3 module called "gdbm". The code should use the generic "dbm" instead.
> 
> Debian (and thus Ubuntu) have a compat package they themselves added. It's non-standard.

@thiagomacieira Would you try the `--disable-gdbm` and `--enable-dbm` flag fore `configure`?

**Comment by ahkok** [comment]
note we have `hass` in the `domotica` bundle.

**Comment by nickcj931** [comment]
Thanks @ahkok will check it out!! 

Just for the record I am presuming that is the standard hass and not hass.io version?

**Comment by ahkok** [comment]
@nickcj931 sorry for slow - we have native `homeassistant`, and not a dockerized thing.

**Comment by nickcj931** [comment]
@ahkok thanks for the follow up.

**Comment by ahkok** [comment]
I'm adding an extremely curtailed version of avahi-daemon. It will by default be safe, but fairly useless.

If you need to expose it to external interfaces, you will need to:

- create `/etc/avahi` and put in a config file
- modify (`systemctl edit --full`) the avahi daemon service file and point it to the new config file
- insert service files into /var/lib/avahi/services manually

**Comment by ahkok** [comment]
`avahi-daemon` - should be out in a few days.

**Comment by chat-gpt-detector** [comment]
When GPT 4 Will Release? [gpt 4 release date](https://chatgptdetector.co/when-will-gpt-4-be-released/)</a>
