### ISSUE TITLE
gpm bundle ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#716]
It would be nice to have a gpm (console mouse support) ClearLinux bundle

**Comment by ahkok** [comment]
It'll be available in the `sysadmin-basic` bundle. You will need to `systemctl enable gpm` manually.

**Comment by nsauzede** [comment]
Thanks @ahkok 
I tested this :
>$ swupd info
>Installed version: 29410
>Version URL:       https://cdn.download.clearlinux.org/update/
>Content URL:       https://cdn.download.clearlinux.org/update/
>$ sudo systemctl enable gpm
>Failed to enable unit: Unit file gpm.service does not exist.

**Comment by nsauzede** [comment]
swupdated to 29440, but still no user command "gpm" available, in order to get the mouse in the linux text terminal (eg: ctrl-alt-f3)
> $ gpm
> gpm: command not found
> the command gpm is not available, consider using: xmodmap

I don't see the relation with X11; should I add some other bundle ?

**Comment by anselmolsm** [comment]
It was added to sysadmin-basic, but it was not released yet.
