### ISSUE TITLE
sshd service is inactive(dead)

### ISSUE THREAD

**Issue by junxnone** [clearlinux/distribution#72]
sshd has set enable, when the pc restart, sshd service is inactive(dead) , but i can use ssh connect to the clearlinux.

#systemctl status sshd
● sshd.service - OpenSSH server daemon
Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: disabled)
Active: inactive (dead)

#ps aux|grep sshd
root 542 0.0 0.0 9000 5344 ? Ss 07:07 0:00 sshd: root@pts/0
root 657 0.0 0.0 4896 964 pts/1 S+ 07:38 0:00 grep sshd

#journalctl -u sshd
some logs from reboot the pc:
-- Reboot --
May 15 07:01:00 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Started OpenSSH server daemon.
May 15 07:01:00 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[577]: Server listening on 0.0.0.0 port 22.
May 15 07:01:00 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[577]: Server listening on :: port 22.
May 15 07:01:31 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[582]: Accepted keyboard-interactive/pam for root from 10.239.205.3 port 50225 ssh2
May 15 07:01:31 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[582]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 15 07:01:48 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopping OpenSSH server daemon...
May 15 07:01:48 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopped OpenSSH server daemon.
May 15 07:01:48 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Started OpenSSH server daemon.
May 15 07:01:48 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[606]: Server listening on 0.0.0.0 port 22.
May 15 07:01:48 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[606]: Server listening on :: port 22.
May 15 07:02:09 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[609]: error: Received disconnect from 10.239.205.3 port 50236:14: No supported authentication methods available [preauth]
May 15 07:02:33 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[611]: Accepted publickey for root from 10.239.205.3 port 50241 ssh2: RSA SHA256:YSt2itLnCi6vZrtJhpnGSyrrhXgGkM5A2MFQ8HUuhtI
May 15 07:02:33 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[611]: pam_unix(sshd:session): session opened for user root by (uid=0)
May 15 07:02:54 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[633]: error: Received disconnect from 10.239.205.3 port 50244:14: No supported authentication methods available [preauth]
May 15 07:05:52 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopping OpenSSH server daemon...
May 15 07:05:52 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopped OpenSSH server daemon.
May 15 07:05:52 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Started OpenSSH server daemon.
May 15 07:05:52 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[661]: Server listening on 0.0.0.0 port 22.
May 15 07:05:52 clr-b073e8382d5a4a8dac20ea6004cc1c1f sshd[661]: Server listening on :: port 22.
May 15 07:06:02 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopping OpenSSH server daemon...
May 15 07:06:02 clr-b073e8382d5a4a8dac20ea6004cc1c1f systemd[1]: Stopped OpenSSH server daemon.

#cat /etc/ssh/ssd_config
PermitRootLogin yes
ChallengeResponseAuthentication no
PasswordAuthentication no

**Comment by fenrus75** [comment]
we use socket activation for ssh, so we start sshd only when someone
connects, to save on memory/etc when not in use

**Comment by junxnone** [comment]
ok, so the  status is right, but it is confusing for the people that don't know this.
anyway , thanks for your answer.
