### ISSUE TITLE
Add qsynth package

### ISSUE THREAD

**Issue by Jacalz** [clearlinux/distribution#720]
~~[Fluidsynth](https://github.com/FluidSynth/fluidsynth) is an absolutely great software synthesizer that takes MIDI input from for example a MIDI-file or keyboard and translates them to sounds out through your speakers. It does so by using a soundfont with SF2 or SF3 specification. It is wonderful for getting MIDI-keyoard without Linux support working on Linux. I would recomment looking at the [Solus package](https://dev.getsol.us/source/fluidsynth/browse/master/package.yml) that I maintain, in order to get a good look on how it should be integrated.~~

Fluidsynth is now added to the bundles!

[Qsynth](https://github.com/rncbc/qsynth) is a Qt5 frontent for Fluidsynth that makes it much easier to use and it let's you change sounds on the fly while also controlling settings and so on. It is a great tool! It needs JACK support so it is currently blocked until JACK, JACK2 and qJackCtl are in the repo. See #587

**Comment by bryteise** [comment]
Hrm seems like fluidsynth requires jack support as well just looking over the solus package definition. @fenrus75 I think you looked at adding jack support previously. Does this require a bit of work to enable alongside alsa for us (I believe the answer is yes but I'm not sure if some of the prework was done recently).

**Comment by Jacalz** [comment]
Fluidsynth can be used without JACK but Qsynth needs jack support. Jack really is easier to use than Alsa for fluidsynth in my opinion...

**Comment by ahkok** [comment]
We currently do not have `jackd`, so this is blocked.

**Comment by Jacalz** [comment]
I saw that fluidsynth is available now and I want to say thank you for a very fast inclusion. Now we just need jack support until we can get qsynth in 👍

**Comment by puneetse** [comment]
Linking to https://github.com/clearlinux/distribution/issues/587

**Comment by Jacalz** [comment]
No longer of interest to me. Closing.
