### ISSUE TITLE
Package request: Tensorflow-agents and Tensorflow-graphics

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#721]
Tensorflow-agents is the library for Reinforcement learning. Alternatives are GYM from openai, and trfl (tensorflow reinforcement learning) from deepmind.

I dont use tensorflow-graphics, but I think it won't take much effort to add it. :p

**Comment by fenrus75** [comment]
hmm there doesn't seem tho have been a release of this yet that works with a released version of tensorflow
