### ISSUE TITLE
Add Lutris gaming client

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#722]
Please consider packaging [lutris](https://lutris.net/). It is a gaming client for Linux that makes it easy to download and launch known-good environments+settings for games that are otherwise complicated to get working well.

It has been requested on Twitter: https://twitter.com/CanalOCaraDoTI/status/1099017984285310978 

Repo: https://github.com/lutris/lutris
Releases also here: https://lutris.net/releases/ 

I was able to autospec it and install locally pretty easily.

**Comment by bryteise** [comment]
Ah I have been wanting to try this out. Indeed it packaged nicely. Should be in the next release.

**Comment by puneetse** [comment]
Thanks @bryteise!
I'll make a PR to get it added as an installation option on the lutris website after it gets pushed out the door.

**Comment by KillYourFM** [comment]
> Ah I have been wanting to try this out. Indeed it packaged nicely. Should be in the next release.

You rock sir. Thanks for including this.
