### ISSUE TITLE
`cnf` "suggestions" needs to handle custom mixes that may not have suggested bundles

### ISSUE THREAD

**Issue by bktan8** [clearlinux/distribution#724]
swupd command "suggestions" assumes that it's working with upstream and has the bundles to support the suggested bundles.  But for a custom mix, suggested bundles may not exist in the mix.  Simple making suggestions based on upstream may not be helpful.  Need to somehow account for custom mixes that may or may not have the suggested bundles.  

Here's an example:

```
root@clr-9fe7f68d1df24022a3e7ae5a4c7165ae ~ # swupd info
Installed version: 10
Version URL:       http://172.16.13.5
Content URL:       http://172.16.13.5

root@clr-9fe7f68d1df24022a3e7ae5a4c7165ae ~ # swupd check-update
Current OS version: 10
There are no updates available

root@clr-9fe7f68d1df24022a3e7ae5a4c7165ae ~ # swupd bundle-list -a
bootloader
editors
emacs
findutils
kernel-kvm
lib-openssl
libglib
libstdcpp
my-joe-bundle
os-core
os-core-update
os-core-update-index
os-core-webproxy
p11-kit
perl-basic
python3-basic
qemu-guest-additions
syslinux
vim

root@clr-9fe7f68d1df24022a3e7ae5a4c7165ae ~ # joe
joe: command not found
To install joe use: swupd bundle-add joe

root@clr-9fe7f68d1df24022a3e7ae5a4c7165ae ~ # vlc
vlc: command not found
To install vlc use: swupd bundle-add vlc
```

I don't have `joe` or `vlc` in my mix.  But it suggested them anyway.

**Comment by fenrus75** [comment]
the custom mix likely needs to ship its own copy of the data files for these.

**Comment by ahkok** [comment]
This is not a `swupd` issue. Instead, it's `cnf`.

**Comment by ahkok** [comment]
I don't think we can do anything else but to close it as invalid for now. The cnf data set is semi-manual.
