### ISSUE TITLE
https://clearlinux.org/software - page is slow to load, firefox asks if it should kill scripts

### ISSUE THREAD

**Issue by ahkok** [clearlinux/distribution#729]
This shouldn't happen. Stock clearlinux firefox.

**Comment by ahkok** [comment]
@biapalmeiro

**Comment by busykai** [comment]
FWIW, don't see it on MacOS 6 min after the report (both on and off Intel network). Is it intermittent issue? Or maybe the site is slightly heavy on JS for FF/Clear?

**Comment by krisdale** [comment]
@ahkok thanks for reporting. I've not yet seen this while using stock clearlinux firefox but will start actively monitoring to try to catch the behavior.

**Comment by ahkok** [comment]
Doesn't happen in stock chrome on clearlinux either.

**Comment by ahkok** [comment]
I'm thinking that `noscript` breaks on the code somehow.

**Comment by mrkz** [comment]
Not able to reproduce using stock firefox/clearlinux on intel network.

not using `noscript` fwiw.

**Comment by krisdale** [comment]
I have been monitoring, and I'm still not able to reproduce using stock firefox/clearlinux on Intel network. @ahkok if you are still seeing this behavior, would you please provide some additional details (CL version, steps you take to see the behavior, screenshot).

**Comment by ahkok** [comment]
Still does it today :)

Using `noscript` and `privacy badger`

**Comment by noelianunez** [comment]
@ahkok Can you provide to me the following details:

- Operating System 
- Firefox Version
- NoScript Version and configuration
- Privacy Badger version and configuration

I'm trying to replicate the issue but no success. I installed both add-ons in Firefox on MacOS and it loads correctly.
