### ISSUE TITLE
How can i install the old version clearlinux

### ISSUE THREAD

**Issue by junxnone** [clearlinux/distribution#73]
Sometimes we need the stable version clearlinux to deply our project. So, we disable the autoupdate. 
But the install image  always install the newest version clearlinux. 
our workaround is dd the live image to our disk. 
my question is : Is there any other way  to install the old version clearlinux?

Thanks

**Comment by junxnone** [comment]
yeah, it works. thanks a lot.
Actually , we meet a issue on the newer version clearlinux when run our apps:
it is about the python numpy lib. the apps works on the old version, but not in the newer version  
this is the error log in newer verison clearlinux :
``
RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
ImportError: numpy.core.umath failed to import
Segmentation fault (core dumped)
``

I'm not sure which version it started.
22120 is works fine, 22530 is the version that i am sure it have this issue.

And it is weird:
1. if i downgrade the version from the newest to 22120 , the issue will gone.
2. if i update from 22120 to the newest version, it didn't seen.
3. it is just seen when i use the installed image install the newest version clearlinux.

**Comment by junxnone** [comment]
I get the clear linux version : 22340
behind this version , all get the Segmentation fault.
https://cdn.download.clearlinux.org/releases/22340/clear/RELEASENOTES

**Comment by bryteise** [comment]
Are you getting the error in python2 or python3 for 'import numpy.core.umath'? I'm not seeing an error in 22340 or in latest (22600) on my system.

**Comment by fenrus75** [comment]
(still puzzled on this, we run both numpy and scipy testsuites as part of our per-release QA)

**Comment by junxnone** [comment]
I also get no errors with ' import numpy.core.umath'. will ask the team if they can give an example to reproduce this issue.

**Comment by ahkok** [comment]
I'm considering the original question answered. If the numpy issues persist, please open a separate issue.

**Comment by ShilohS** [comment]
I had this same issue with needing a older version on the OS as requested by a customer (because something broke) and I had to install the newest then downgrade with a --force because package names changed (I think). I wish there was a supported was to just install a older version the first time and not just have the supported way be downgrade... That's just my 2 cents.
