### ISSUE TITLE
Add dislocker bundle to unlock bitlocker-locked drives

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#732]
Recent (corporate ?) Windows 10 tend to encrypt external drives (& USB sticks etc..) with so-called "Bitlocker To Go", which prevents reading them on linux
There seem to be a "dislocker" package, at least on debian/ubuntu :
https://www.ceos3c.com/open-source/open-bitlocker-drive-linux/

It would be nice to have the same feature on CLR as well

**Comment by bryteise** [comment]
It seems like this tool hasn't seen a release in two years with some needed fixes sitting on master but master itself isn't passing their tests from what I can see of their repo. I don't think this software is quite in the state we want to be adding right now.

**Comment by nsauzede** [comment]
got your point
