### ISSUE TITLE
"clr-boot-manager update" does not switch kernels

### ISSUE THREAD

**Issue by junkbustr** [clearlinux/distribution#733]
When following the steps at:
https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox#id6
and Step 1,
after installing the new kernel, the invocation of "clr-boot-manager update" does not switch kernels, as verified after the reboot.

I had to manually mount /dev/sda1 and edit the 'loader/loader.conf' file to change the default kernel:
    default  Clear-linux-lts2018-4.19.42-31

**Comment by pceiley** [comment]
Yeah, it should probably read `$(basename $(realpath /usr/lib/kernel/default-lts2018))` now.

**Comment by junkbustr** [comment]
I actually tried "clr-boot-manager list-kernels" and then "clr-boot-manager set-kernel _kernel-name_", which is what failed.

**Comment by busykai** [comment]
@junkbustr, if you run `sudo clr-boot-manager update` *after* doing `set-kernel`, it would reset your default to currently booted, I believe. So instead, do `sudo clr-boot-manager update`, it will actually install a newer version of lts if available and then `sudo clr-boot-manager set-kernel <kernel-name>` and reboot.

**Comment by mdhorn** [comment]
Yes, I found out too that `sudo clr-boot-manager update` selects the latest kernel -- by design.
If you want an older kernel, use `set-kernel` as @busykai suggests.

**Comment by bryteise** [comment]
As unfriendly as that seems, making ```clr-boot-manager update``` select the latest kernel from the type that is set as default can cause issues where the kernel type is no longer supported (an lts is eol'd) and folks will be left with autoupdate keeping their kernel out of date.
