### ISSUE TITLE
provide pinentry-gnome3

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#738]
Currently we provide `pinentry` (ncurses based), however we DO have pinentry-gnome3 build as well provided by `pintentry-extras` RPM output as shown in https://github.com/clearlinux-pkgs/pinentry/blob/master/pinentry.spec#L103 :
```
%files extras
%defattr(-,root,root,-)
/usr/bin/pinentry-gnome3
```

`pinentry` tool is available only via the `cryptography` bundle, however it's desired that when installing the `desktop` (GNOME)  bundle `pinentry-gnome3` is available too.

**Current workaround**:
download the current pinentry-extras rpms, extract it via rpm2cpio and install it.

 * look for the `pinentry-extras` RPM from https://download.clearlinux.org/releases/current/clear/x86_64/os/Packages/
 * download the RPM
 * extract it via rpm2cpio
 * copy the extracted file to /usr/bin/

Example:
```shell
### previous RPM URL may change depending on clearlinux release
$ curl -LOk  https://download.clearlinux.org/releases/current/clear/x86_64/os/Packages/pinentry-extras-1.1.0-21.x86_64.rpm

$ rpm2cpio pinentry-extras-1.1.0-21.x86_64.rpm  | ( cd / ; sudo cpio -idv )

```

**Expected**:
`pinentry-gnome3` available out of the box.

**Comment by fenrus75** [comment]
added to desktop-gnome bundle, should be in a monday release
