### ISSUE TITLE
[Gnome3] Automatic Login can't be enabled

### ISSUE THREAD

**Issue by RobertBuhren** [clearlinux/distribution#743]
Currently it is not possible to enable the automatic login functionality of gnome.

In "Settings -> Details -> Users" the action "Automatic Login can be set, but it it reset whenever the user leaves the window.

The journal displays the following related errors:
```
Mai 17 12:02:39 clr-ba4be38e3c9f4921ac9166a2abb987e4 accounts-daemon[596]: request by system-bus-name::1.81 [gnome-control-center pid:3018 uid:1000]: enable automatic login for user 'robert' (1000)
Mai 17 12:02:39 clr-ba4be38e3c9f4921ac9166a2abb987e4 gnome-control-c[3018]: SetAutomaticLogin call failed: GDBus.Error:org.freedesktop.Accounts.Error.Failed: failed to change automatic login: No such file or directory
```

**Comment by mariojuniorjp** [comment]
Same problem here.

**Comment by mdhorn** [comment]
Looks like @mrkz is looking into this issue, but a workaround you can use is:

```
mkdir -p /etc/gdm/
cat > /etc/gdm//custom.conf <<CUSTOM_CONF
[daemon]
AutomaticLoginEnable=True
AutomaticLogin=**_YOUR_USER_HERE_**
CUSTOM_CONF
chmod 644 /etc/gdm/custom.conf
```

Replace the `**_YOUR_USER_HERE_**` which the login you've created.
I'm pretty sure this is what that switch will do in the end away, and it is the process we use in the installer image to auto-login to the desktop user account.

**Comment by mrkz** [comment]
Already identified the issue, a fix is in progress, in the meantime you can try @mdhorn suggestion which as he mentions, is what the setting actually does.

**Comment by mrkz** [comment]
This is fixed for release **29520** or later.

Thanks for reporting this issue.
