### ISSUE TITLE
System monitoring tool: Netdata

### ISSUE THREAD

**Issue by namm2** [clearlinux/distribution#744]
Source repo: https://github.com/netdata/netdata

> Netdata is distributed, real-time, performance and health monitoring for systems and applications. It is a highly optimized monitoring agent you install on all your systems and containers.

> Netdata provides unparalleled insights, in real-time, of everything happening on the systems it runs (including web servers, databases, applications), using highly interactive web dashboards. It can run autonomously, without any third party components, or it can be integrated to existing monitoring tool chains (Prometheus, Graphite, OpenTSDB, Kafka, Grafana, etc).

**Comment by bryteise** [comment]
I'm working through another package at the moment but I'll look at adding this next unless somebody gets there first.

**Comment by fenrus75** [comment]
done

**Comment by ahkok** [comment]
`netdata` bundle.
