### ISSUE TITLE
Add libQt5WebKit libraries

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#747]
I'm trying to use a Qt app (TeamViewer) which has a dependency on these libraries.

```
	libQt5WebKitWidgets.so.5 => not found
	libQt5WebKit.so.5 => not found
```

I would think they should be part of this package: https://github.com/clearlinux-pkgs/qtwebkit but don't see them.

**Comment by ahkok** [comment]
@thiagomacieira is this not yet in progress? Do you know?

**Comment by thiagomacieira** [comment]
This is a web engine library that hasn't received updates in years (including security fixes). Sorry, we won't add it to Clear.
