### ISSUE TITLE
Install: Clear linux fails to pass pre-install checks

### ISSUE THREAD

**Issue by enfrte** [clearlinux/distribution#753]
Hi, does your device have to support Virtualisation (vmx) for the install? 

I tried out Clear Linux on a usb stick. Everything worked sweet, and I wanted to install it to my notebook. During the install pre-check I get the error "Failed to find efi firmware".

During the compatibility check for both host and container, it passed everything except for one fail on the container check: "FAIL: Virtualisation support (vmx)"

**More info:**

I used Rufus to create the live USB. The "Target system" was set as "BIOS (or UEFI-CSM)" and couldn't be changed.

The USB could only boot in Legacy mode. Trying to boot in UEFI gave me the error: Generic flash disk has been blocked by he current security policy.

There is nothing in my BIOS that controls Virtualisation support. 

Device hardware: Acer Aspire V-123

So is the install a no go, or is there something else I can try? Thanks.

**Comment by pceiley** [comment]
Try disabling secure boot in your BIOS if that's an option.

**Comment by enfrte** [comment]
> Try disabling secure boot in your BIOS if that's an option.

Thanks for the suggestion, but in my BIOS, Secure boot is only available in UEFI mode and is a hard coded value.

**Comment by pceiley** [comment]
I'm pretty sure clear will only work with EFI boot.

**Comment by mdhorn** [comment]
The Live image will boot in either UEFI or Legacy mode to let you try out Clear Linux* without installing. This is only possible as we've created a Hybrid ISO image to support this.

Clear Linux OS does have a requirement of using UEFI to boot.
This is why the installer has a precheck for the required hardware features as well as checking if UEFI is enabled. If we didn't have this check the install would succeed, but you would not be able to boot the newly installed image.

**Comment by enfrte** [comment]
> Try disabling secure boot in your BIOS if that's an option.

Ok, this is correct. I managed to disable secure boot in my BIOS, but had to set a supervisor password in order to do so (details below).

From this resource https://community.acer.com/en/discussion/268548/how-to-fix-window-boot-manager-has-been-blocked-by-the-current-security-policy%EF%BB%BF-on-acerv5window-8-1 

1. Completely shut down the computer.
2. Power on the system. As soon as the first logo screen appears, immediately press F2 to enter the BIOS.
3. Use the right arrow key to select Security.
4. Use the down arrow key to highlight Set Supervisor Password and press Enter.
5. Create a password and press Enter. Retype the password to confirm and press Enter again.
6. Use the right arrow key to select Boot.
7. Press the down arrow key to select Secure Boot and press Enter.
8. With the arrow key, highlight Disabled and press Enter.
9. Press the F10 key and select Yes to save the changes and exit the BIOS

Thanks for your help.

**Comment by rmlopes** [comment]
Hi, sorry for bumping up a closed issue. I am trying to install ClearLinux on a PC with a MSI X399 sli plus. If I use legacy + UEFI the live usb will boot but the UEFI check fails before installing (as it is hybrid it is booting using the legacy system). If I use only UEFI it is not able to boot using the live usb. I don't have a secure boot option in the BIOS. I have tried to setup the administrator password but it still does not have the secure boot option.

Any ideas as how to workaround this issue?

**Comment by mdhorn** [comment]
@rmlopes It is very likely a BIOS setting. Glancing through the [manual](https://www.msi.com/Motherboard/support/X399-SLI-PLUS#down-bios) have you tried changing the "Windows 10 WHQL Support" setting?

> Windows 10 WHQL Support [Disabled]
> Enables the supports for Windows 10 or disables for other operating systems. Before enabling this item, make sure all installed devices & utilities (hardware & software) should meet the Windows 10 requirements.
> [Enabled] The system will switch to UEFI mode to meet the Windows requirement.
> [Disabled] Disables this function.

**Comment by rmlopes** [comment]
Thanks @mdhorn, I will try that, I immediately wrote off that option as "windows only" thing.
