### ISSUE TITLE
Chrome/Chromium

### ISSUE THREAD

**Issue by DimanNe** [clearlinux/distribution#756]
Today I decided to try ClearLinux, but to my surprise, there is no standard way of installing Chrome/Chromium - either would work. By "standard way" I mean via `swupd` or via GUI application "Software".

The [only available way](https://github.com/clearlinux/distribution/issues/422#issuecomment-437657845) contains not working links, involves downloading of something from some 3rd party sites and running it and looks just ridiculous.

Please, tell me I am wrong and I have just missed something.

**Comment by mariojuniorjp** [comment]
Yeah, Chrome or Chromium needs a bundle.

**Comment by AthenasJimenez** [comment]
Unfortunately, we still don't have a easy/pretty way to install Chromium on Clear. You read old issues, so you already know that we can't ship Chrome.
