### ISSUE TITLE
The first terminal is not available after running two weeks with auto-update on

### ISSUE THREAD

**Issue by jerryrhyu** [clearlinux/distribution#76]
platform: NUC, Swift Canyon 6th Gen i5 Intel NUC [NUC6i5SYH]
The initial version installed: 22290
The last version it was updated to: 22690
The extra bundle installed besides standard installation: containers-basic.

Leaving the system on for about 2~3 weeks, no workload is running. Docker daemon is on but no docker instance is running. The system is doing auto update/upgrade by default. Try to reboot, the system is stuck at the black screen in booting up. 

Didn't try to reproduce it. But this is what happened on my machine. Just raise the issue for tracking purpose in case this is a bug.

**Comment by ahkok** [comment]
Try booting without `quiet` on the kernel command line.
Try checking if alternative vt's are available (alt-f2 etc)
Try booting with `init=/bin/bash`, do you get a root shell?
Does this system have the `desktop` or `desktop-autostart` bundles installed?
Does the server have ssh enabled? is it listening on any remote ports?

**Comment by jerryrhyu** [comment]
I  had a check,  alf-f2 woks fine. The system seems work fine, network works. It seems only the first terminal is not available. 
btw, I used auto installation, desktop and desktop-autostart bundles  are NOT installed. The ssh server is enabled. dmesg log is attached.
[dmesg.log](https://github.com/clearlinux/distribution/files/2069478/dmesg.log)

**Comment by intelkevinputnam** [comment]
I can confirm that I see the same problem with fresh auto install of version 22690 with Intel® NUC Kit D54250WYK. After installation the system reboots to blank screen. 

Manual install with desktop-autostart selected works as expected booting to GUI.

**Comment by bryteise** [comment]
Do either of you have a serial tty on the system? If you create /etc/kernel/cmdline.d/tty.conf with "console=tty0" in it and run clr-boot-manager update and reboot do you happen to still see the same behavior?

**Comment by bryteise** [comment]
@ahkok will be fixing this pretty soon I am guessing. The work around would be to systemctl enable getty@tty1 though.

**Comment by mrkz** [comment]
@bryteise I think this is already fixed?

**Comment by bryteise** [comment]
@mrkz Yes I believe so but there are still various issues around ttys. This is closable though imo.
