### ISSUE TITLE
add extundelete/testdisk packages

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#768]
I cant find any option to undelete, recover a deleted, lost file in clearlinux? 
What recovery tools do exist atm?

**Comment by thiagomacieira** [comment]
Packaging extundelete was easy. The only problem I see is that it hasn't had a release in over 5 years.

**Comment by Andy2244** [comment]
It does not have to-be extundelete, was just googling for "undelete, recovery under linux" and all tools that came up could not be found via `swupd search`. I just would like some tools that can recover files, folders via shell only mainly for ext4 fs.

**Comment by bryteise** [comment]
@thiagomacieira I'm okay with testdisk but we need to be mindful of updating since they don't do releases just a master (and beta) branch.

**Comment by ahkok** [comment]
> PS: I mean if you deleted a script, makefile by accident, how do you recover it under ClearLinux?

For the entire existence of UNIX-like operating systems, the official and only real (cruel, but honest) answer to that question has been: You have backups.

ext2/3/4 has never been designed to support undelete, nor has btrfs or any other file system.

Most file managers maintain a `trashcan` for this reason.

In reality, undelete on ext4 is most likely going to be really unreliable, since files that get deleted are incredibly likely to get rewritten with new content really fast after they are deleted.

So, please consider using a backup tool or snapshot filesystem.

**Comment by Andy2244** [comment]
> since files that get deleted are incredibly likely to get rewritten with new content really fast after they are deleted.

Thats not my experience at all for such cases, neither on Windows or Linux. The backup only helps for mid/longterm data, i have never seen a developer environment that does continuous backups every few minutes.

In those cases where you just "f... up" you know instantly, that you made a mistake. Like pruning your docker volumes, hitting "yes" and than seeing in the list the volumes you wanted to keep, just to realize that you tested a :latest version, removed it and forgot to create the old stable container. Sometimes stuff just happened and you regret it instantly, in such cases there is no new data written and the files are fully intact.

**Comment by ahkok** [comment]
> i have never seen a developer environment that does continuous backups every few minutes.

For projects I code on, I start with `git init` and `git add Makefile`. Every few minutes when I make a reasonable amount of changes, I do `git add Makefile` again. This ensures that an accidental delete of `Makefile` can be undone.

Many editors even keep full undo history as well.

**Comment by Andy2244** [comment]
> For projects I code on, I start with `git init` and `git add Makefile`.

That's nice and all, how many different VM's, Docker containers you use for your projects? My point is, not everyone has the luxury to only have to handle textfiles/code and use git repos for all there work.

I doubt you put your docker volumes into a git project or continuously backup them?

**Comment by thiagomacieira** [comment]
For source code projects, please use Git.

For everything else, I recommend making filesystem snapshots. If you're using btrfs, it can do snapshots on its own and it does per-file COW. If you're using ext4, I recommend LVM Thin Volumes, which do block-level COW. 

There's a tool that can manage that for you: http://snapper.io/ & https://github.com/openSUSE/snapper. We should look into packaging it for Clear, but it won't help much if the installer won't let you make LVM thin volumes, though I don't think openSUSE's does either. I have that for my /home, which I created after installation.

```
# lvs
  LV                 VG     Attr       LSize   Pool  Origin Data%  Meta%  Move Log Cpy%Sync Convert
  home               system Vwi-aotz--  40.00g pool0        62.91                                  
  home-snapshot16113 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot16595 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot16869 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot16978 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17009 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17091 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17180 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17196 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17205 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17212 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17226 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17243 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17258 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17272 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17273 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17274 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17275 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17276 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17277 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17278 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17279 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17280 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17281 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17282 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17283 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17284 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17285 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17286 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17287 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17288 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17289 system Vri---tz-k  40.00g pool0 home                                          
  home-snapshot17290 system Vri---tz-k  40.00g pool0 home                                          
  pool0              system twi-aotz-- 129.60g              65.85  43.30                           
  root               system -wi-ao----  40.00g                                                     
  stuff              system -wi-ao---- 200.00g                                                     
  swap               system -wi-ao----  16.00g                                                     
# snapper -c home ls
     # | Type   | Pre # | Date                     | User | Cleanup  | Description | Userdata
-------+--------+-------+--------------------------+------+----------+-------------+---------
    0  | single |       |                          | root |          | current     |         
16113  | single |       | Fri Mar  1 08:00:23 2019 | root | timeline | timeline    |         
16595  | single |       | Mon Apr  1 00:00:20 2019 | root | timeline | timeline    |         
16869  | single |       | Mon Apr 22 07:35:41 2019 | root | timeline | timeline    |         
16978  | single |       | Mon Apr 29 08:04:25 2019 | root | timeline | timeline    |         
17009  | single |       | Wed May  1 07:49:54 2019 | root | timeline | timeline    |         
17091  | single |       | Mon May  6 07:58:12 2019 | root | timeline | timeline    |         
17180  | single |       | Mon May 13 07:49:16 2019 | root | timeline | timeline    |         
17196  | single |       | Tue May 14 07:13:31 2019 | root | timeline | timeline    |         
17205  | single |       | Wed May 15 07:10:23 2019 | root | timeline | timeline    |         
17212  | single |       | Thu May 16 07:29:23 2019 | root | timeline | timeline    |         
17226  | single |       | Fri May 17 07:35:23 2019 | root | timeline | timeline    |         
17243  | single |       | Sat May 18 09:24:14 2019 | root | timeline | timeline    |         
17258  | single |       | Sun May 19 00:00:09 2019 | root | timeline | timeline    |         
17272  | single |       | Sun May 19 22:00:09 2019 | root | timeline | timeline    |         
17273  | single |       | Mon May 20 08:03:21 2019 | root | timeline | timeline    |         
17274  | single |       | Mon May 20 09:27:50 2019 | root | timeline | timeline    |         
17275  | single |       | Mon May 20 10:00:10 2019 | root | timeline | timeline    |         
17276  | single |       | Mon May 20 11:00:10 2019 | root | timeline | timeline    |         
17277  | single |       | Mon May 20 12:00:31 2019 | root | timeline | timeline    |         
17278  | single |       | Mon May 20 13:00:10 2019 | root | timeline | timeline    |         
17279  | single |       | Mon May 20 14:00:10 2019 | root | timeline | timeline    |         
17280  | single |       | Mon May 20 15:00:10 2019 | root | timeline | timeline    |         
17281  | single |       | Mon May 20 16:00:10 2019 | root | timeline | timeline    |         
17282  | single |       | Mon May 20 17:00:10 2019 | root | timeline | timeline    |         
17283  | single |       | Mon May 20 20:49:31 2019 | root | timeline | timeline    |         
17284  | single |       | Mon May 20 21:00:08 2019 | root | timeline | timeline    |         
17285  | single |       | Mon May 20 22:00:08 2019 | root | timeline | timeline    |         
17286  | single |       | Tue May 21 07:42:52 2019 | root | timeline | timeline    |         
17287  | single |       | Tue May 21 08:00:01 2019 | root | timeline | timeline    |         
17288  | single |       | Tue May 21 09:00:04 2019 | root | timeline | timeline    |         
17289  | single |       | Tue May 21 10:00:31 2019 | root | timeline | timeline    |         
17290  | single |       | Tue May 21 11:00:24 2019 | root | timeline | timeline    |         
```

**Comment by Andy2244** [comment]
> I recommend LVM Thin Volumes

mhh assuming you have a existing ext4 filesystem, what steps are needed to setup this and what steps are needed to recover a deleted file/folder?

**Comment by ahkok** [comment]
> I doubt you put your docker volumes into a git project or continuously backup them?

I'm not a docker fan at all. You will not see me use docker containers anywhere (I tried, and gave up).

For any value projects I make sure it's either in `git` or it's backed up externally (hourly, in most cases). Undelete would only get me "the last version", but backups give me many versions. Sometimes the last version was already bad.

I'm not arguing that we don't add undelete (I'm totally fine with it). I'm arguing that relying on undelete as a backup tool is nonsensical. You asked about recovery tools, so it makes sense to make sure you're aware of `rsync` and other backup tools available in clearlinux.

**Comment by thiagomacieira** [comment]
1. Make sure you have unpartitioned space, then create an LVM Physical Volume there and a Volume Group (if you already have a VG, skip this step)
1. Create a Thin Pool LV. That's the same as creating a normal LV, but pass option -T to `lvcreate`. See https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/logical_volume_manager_administration/thinly_provisioned_volume_creation
1. Create your ext4 filesystem in LV
1. rsync your content onto the new filesystem
1. update /etc/fstab to match
1. Figure out a solution to periodically snapshot and garbage collect the snapshots, like Snapper.

To recover a deleted file, mount a snapshot that contains the file. I use snapper, so `snapper -c home mount <ID>` will mount it in `/home/.snapshots/<ID>/snapshot`

**Comment by Andy2244** [comment]
> I'm arguing that relying on undelete as a backup tool is nonsensical. You asked about recovery tools, so it makes sense to make sure you're aware of `rsync` and other backup tools available in clearlinux.

Actually you guys started to "educate" me about backups, which i appreciate don't get me wrong. The main problem is there is a fundamental difference on using your daily backup solution to recover from a catastrophic failure or just try to recover from a small/stupid human error, so you don't loose several hours of work. In all my "stupid" cases, its just to much work to setup any incremental/continuously backup solution and i also cant really anticipate on what FS/volume i make a error once a month.

So yeah i mainly was looking for a way to recover from a snafu situation, without having to retrace all of my steps on that day.

**Comment by ahkok** [comment]
I will be adding `testdisk` soon (1-2 days). I think that covers the whole request. If you spot other tools, feel free to open a new request.
