### ISSUE TITLE
I want to know clear-29480-vmware‘s password

### ISSUE THREAD

**Issue by penetrater** [clearlinux/distribution#770]
clear-29480-vmware.vmdk

Display on VMware screen is 
`clr-e4d9ab684f4241e894b2a2c2b1c45c58` `login:`
but i don't know username and password.
Please tell me the password, thank you very much.

**Comment by penetrater** [comment]
i known.

**Comment by penetrater** [comment]
how to start GUI desktop?

**Comment by miguelinux** [comment]
You need to install the desktop-autostart bundle

`sudo swupd bundle-add desktop-autostart`

Then, when you start your VM it will launch GDM

**Comment by penetrater** [comment]
First of all, thank you very much for your reply.

But I have encountered some minor problems.
error：faild to connect to update server.


The system prompts the following solutions：
1）fix the system clock
2）run 'swupd info' to check if the urls are correct
3）check if the server SSL certificate is trusted by your system ('clrtrust generate' may be faild updater initialization,exiting now.



I run ‘swupd info’
I tried to ping the version URL and content URL.

I am prompted to install the app ‘swupd bundle-add clr-network-troubleshooter.
But the system again prompted me not to connect to the update server.

Therefore, it is now in an infinite loop.




Method one and two I don't know how to do it.



Finally, thank you again for your reply.

By the way, the clear linux system reacts very fast, it is the fastest Linux system I have ever used.
I like it very much.

Well, I am on another computer ’Install Clear Linux* OS from the live desktop‘.
But I want to install it again in the virtual machine.
I am a beginner of Chinese Linux.
Can't connect to the update server, is it related to the ’wall‘ ?


I am very sorry, my English is not good, so English is translated by Google.



------------------ 原始邮件 ------------------
发件人: "Miguel Bernal Marin"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 晚上11:27
收件人: "clearlinux/distribution"<distribution@noreply.github.com>;
抄送: "杜若"<1098951302@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [clearlinux/distribution] I want to know clear-29480-vmware‘s password (#770)




You need to install the desktop-autostart bundle
 
sudo swupd bundle-add desktop-autostart
 
Then, when you start your VM it will launch GDM

**Comment by ZhongbaoShi** [comment]
@penetrater, you are in China, right? And, are you using Proxy to access https://clearlinux.org/ ?

**Comment by penetrater** [comment]
Yes, I am Chinese.
I have already seen the official website.
Otherwise I won't know the steps.
Thanks again for your reply.



------------------ 原始邮件 ------------------
发件人: "ZhongbaoShi"<notifications@github.com>;
发送时间: 2019年5月21日(星期二) 下午2:11
收件人: "clearlinux/distribution"<distribution@noreply.github.com>;
抄送: "杜若"<1098951302@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [clearlinux/distribution] I want to know clear-29480-vmware‘s password (#770)




@penetrater, you are in China, right? And, are you using Proxy to access https://clearlinux.org/ ?

**Comment by ewanglong** [comment]
First of all, do you confirm you connected into physical network already? Then whether you are behind firewall or corporate network? If so, you need set proxy in /etc/profile. or just quick try it in command line such as below(replace xxx:yyy with your proxy host and port):
$http_proxy=http://xxx:yyy swupd bundle-add clr-network-troubleshooter

**Comment by ewanglong** [comment]
> Yes, I am Chinese. I have already seen the official website. Otherwise I won't know the steps. Thanks again for your reply.
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "ZhongbaoShi"<notifications@github.com>; 发送时间: 2019年5月21日(星期二) 下午2:11 收件人: "clearlinux/distribution"<distribution@noreply.github.com>; 抄送: "杜若"<1098951302@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [clearlinux/distribution] I want to know clear-29480-vmware‘s password (#770) @penetrater, you are in China, right? And, are you using Proxy to access https://clearlinux.org/ ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

First of all, do you confirm you connected into physical network already? Then whether you are behind firewall or corporate network? If so, you need set proxy in /etc/profile. or just quick try it in command line such as below(replace xxx:yyy with your proxy host and port):
$http_proxy=http://xxx:yyy swupd bundle-add clr-network-troubleshooter

**Comment by puneetse** [comment]
@penetrater I'm going to close this issue because it seems limited to your network so far and we haven't heard back in a while. If you're continuing to have issues, please feel free to reopen or ask for help on the fourms https://community.clearlinux.org/
