### ISSUE TITLE
I want to know how to start clear-29480-vmware‘s desktop?

### ISSUE THREAD

**Issue by penetrater** [clearlinux/distribution#771]
i use follow step to install:
`https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/vmw-player-preconf`
i  will thank you very much.

**Comment by ahkok** [comment]
After clearlinux is booted, use `swupd bundle-add desktop` and start `gdm.service`.

**Comment by penetrater** [comment]
First of all, thank you very much for your reply.
# swupd bundle-add desktop-autosart
# sudo swupd bundle-add desktop-autosart
After running the command, the prompt is as follows:
error:bundle too large by 3212M.
note:currently, swupd only checks /usr/(or the passed-in with /usr/appended) for available space.
to skip this error and install anyways, add the --skip-disk-check flag to your command.
failed to install 1 of 1bundles.

#firefox
error:no display enviroment variable specified.


I am a Chinese, English is not good, the translation results come from Baidu.






------------------ 原始邮件 ------------------
发件人: "ahkok"<notifications@github.com>;
发送时间: 2019年5月22日(星期三) 凌晨1:17
收件人: "clearlinux/distribution"<distribution@noreply.github.com>;
抄送: "杜若"<1098951302@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [clearlinux/distribution] I want to know how to start clear-29480-vmware‘s desktop? (#771)




After clearlinux is booted, use swupd bundle-add desktop and start gdm.service.
