### ISSUE TITLE
clr-rpm-config: GCC-specific parameters prevent building packages with LLVM

### ISSUE THREAD

**Issue by rakuco** [clearlinux/distribution#774]
See also: #562.

Starting with https://github.com/clearlinux/clr-rpm-config/commit/91a17a96f65299022301bf2fbf1e5b9624f01af3, `-ffat-lto-objects -flto=4` became part of `CFLAGS` and `CXXFLAGS` by default when building packages.

These are GCC-specific options though (`-ffat-lto-objects` is just ignored because it's not a clang option, but `-flto=4` causes things to fail because clang does have a `-flto` option, but it doesn't accept "4" as a parameter), so any package being built with LLVM needs to work around that by manually changing `CFLAGS` and `CXXFLAGS` (and continuously monitor whether those flags change and new GCC-specific ones are added).

**Comment by chivakker** [comment]
This is related to this as well https://github.com/clearlinux/autospec/issues/378

**Comment by fenrus75** [comment]
apologies I thought I fixed this already but the actual git commit was waiting for a password ;-)

fixed now
