### ISSUE TITLE
Reinstalled system with 29530 desktop ISO doesn't seem to have Intel kvm kernel module

### ISSUE THREAD

**Issue by znmeb** [clearlinux/distribution#776]
I just reinstalled an Intel laptop from `clear-29530-live-desktop.iso` and then updated to 29540. Virtual Machine Manager doesn't seem to be able to create a virtual network. I did a little digging and it looks like the Intel `kvm` kernel module is missing from all kernels except `kernel-aws`.

```
root@ClearDreams ~ # modprobe kvm
root@ClearDreams ~ # lsmod | grep kvm
root@ClearDreams ~ # find /lib/modules/ -name '*kvm*'
/lib/modules/5.0.17-765.native/kernel/arch/x86/kvm
/lib/modules/5.0.17-765.native/kernel/arch/x86/kvm/kvm-amd.ko
```

You have `kvm-amd.ko` but not `kvm-intel.ko`. I did a `swupd search --display-files` and it looks like the only kernel that has `kvm-intel.ko` is the AWS one:

```
# swupd search 'kvm-intel'
Bundle with the best search result:
     kernel-aws                     	- Run the Amazon Web Services (AWS) specific kernel.  (33MB) 

This bundle can be installed with:

  swupd bundle-add  kernel-aws

root@ClearDreams ~ # 
```

**Comment by puneetse** [comment]
It looks like it is enabled in the config:

``
cat /usr/lib/kernel/config-5.0.17-765.native | grep CONFIG_KVM
CONFIG_KVM_MMIO=y
CONFIG_KVM_ASYNC_PF=y
CONFIG_KVM_VFIO=y
CONFIG_KVM_GENERIC_DIRTYLOG_READ_PROTECT=y
CONFIG_KVM_COMPAT=y
CONFIG_KVM=y
CONFIG_KVM_INTEL=y
CONFIG_KVM_AMD=m
CONFIG_KVM_MMU_AUDIT=y
```

**Comment by znmeb** [comment]
Ah - compiled in for Intel KVM, module for AMD KVM.
