### ISSUE TITLE
clr-boot-manager does not support btrfs subvolumes

### ISSUE THREAD

**Issue by RobertBuhren** [clearlinux/distribution#777]
Btrfs allows to specify subvolumes as a mount option. The systemd-fstab-generator allows to pass those to the mount command of the initrd using e.g.:

```
rootfstype=btrfs rootflags=subvol=clear
```
clearlinux boots from the correct subvolume but clr-boot-manager complains:

```
 sudo clr-boot-manager update
Password: 
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:46
Out of memory[FATAL] cbm (../src/bootman/sysconfig.c:L140): sysconfig insane: Missing root device
[ERROR] cbm (../src/bootman/update.c:L225): Failed to repair running kernel
[FATAL] cbm (../src/bootman/sysconfig.c:L140): sysconfig insane: Missing root device
[FATAL] cbm (../src/bootman/update.c:L257): Failed to install default-native kernel: ///usr/lib/kernel/org.clearlinux.native.5.0.17-765
```

**Comment by seanvk** [comment]
It's been an issue for a while...
https://github.com/clearlinux/clr-boot-manager/issues/61

**Comment by bryteise** [comment]
Ugh I really have to get time to go through these cbm issues... btrfs subvolume support is going to need time though because it is low priority and the person who wrote the disk detection code isn't around any more. I'm closing this one in favor of the clr-boot-manager issue though.
