### ISSUE TITLE
how can I get the small bundle for "lspci" command?

### ISSUE THREAD

**Issue by mcao6** [clearlinux/distribution#779]
when I install "lspci" tool under a small storage, just 700 MB left, it asks to install the bundle of basic-system-admin, and it could be too larger; how to install small bundle or just the related package?

**Comment by thiagomacieira** [comment]
We don't usually provide small tools in individual bundles. lspci is indeed part of `sysadmin-basic`.

**Comment by miguelinux** [comment]
> when I install "lspci" tool under a small storage, just 700 MB left, it asks to install the bundle of basic-system-admin, and it could be too larger; how to install small bundle or just the related package?

Can you help us to describe your use case?, so we can find a solution.

**Comment by mcao6** [comment]
I know that, so submit this request; if clearlinux used in IOTG business, in most cases, the storage could be small, better to install what it needs, just like Ubuntu does.

**Comment by mcao6** [comment]
my case is: I want to use "lspci" in GP2.0 service OS, which just has small storage left, it ask me to install bundle of "sysadmin-basic", it is too large for the left storage.

**Comment by bryteise** [comment]
I'm very sympathetic to the desire and putting utilities into package level bundles is a broader goal we are working towards but I can't tell you a timeline for lspci specifically getting into such a bundle.
