### ISSUE TITLE
BroadCom wireless card Driver/BroadCom b43 Driver Missing (BCM4331) in Bundle

### ISSUE THREAD

**Issue by the-blackpirate** [clearlinux/distribution#780]
Using Clear Linux on the MacBook Pro Mid 2012 A1278 I7 Ivy Bridge 3rd Gen.
Reported **htop** on MacOS Mojave 10.14.5
CPU Uses on MacOS - 15% on idle
Ram Uses on idle - 3GB
------------------------------------------------
Reported **htop** on ClearLinux 
CPU Uses on MacOS - 2%-3% on idle
Ram Uses on idle - 1GB on idle
------------------------------------------------
Issue(Enhancement request)
Reported **lspci** on ClearLinux 
Network wireless card Vendor - Broadcom Inc
Network wireless card Model - Broadcom Inc BCM4331
Device Model - MacBook Pro 9,2 I7 Ivy Bridge A1278
-----------------------------------------------
After I see the **htop** results then I completely leave the MacOS My Boot time is 17 Seconds on HDD 5400RPM Vendor Apple and when I only try first time on my machine that time from pen drive Clear Linux boot more faster than Mac. 
-----------------------------------------------
But Wifi Driver is Missing in the bundle Please Add appropriate driver in the bundle for the best performance. I am so happy with the Clear Linux. now I am using TP-Link Wifi external Adapter for Internet Access.

**Comment by ahkok** [comment]
The driver is enabled, but the firmware is not redistributable by Intel due to license restrictions by Broadcom. You can download the firmware yourself and install it to `/etc/firmware`, and it should work.

**Comment by WIZARD-WIZ** [comment]
@the-blackpirate did you solve the problem?

**Comment by the-blackpirate** [comment]
> The driver is enabled, but the firmware is not redistributable by Intel due to license restrictions by Broadcom. You can download the firmware yourself and install it to `/etc/firmware`, and it should work.


@ahkok  **can you please provide the proper instructions for installing or enabling the b43 / wl / broadcom drivers. i am waiting for your positive response please provide proper instructions for wifi problem fix.**

**Comment by lebensterben** [comment]
>> The driver is enabled, but the firmware is not redistributable by Intel due to license restrictions by Broadcom. You can download the firmware yourself and install it to `/etc/firmware`, and it should work. ...

@the-blackpirate https://docs.01.org/clearlinux/latest/tutorials/broadcom.html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by the-blackpirate** [comment]
@lebensterben thank you so much I think I can enjoy the ultimate fast performance of the real beast.
