### ISSUE TITLE
Cannot find installer media

### ISSUE THREAD

**Issue by WSADKeysGaming** [clearlinux/distribution#781]
![20190522_120608](https://user-images.githubusercontent.com/34288820/58194292-c0978f80-7c8a-11e9-9ca6-3c03ced19bf0.jpg)

**Comment by WSADKeysGaming** [comment]
BTW, USB made using Rufus in iso mode.

**Comment by miguelinux** [comment]
@mdhorn

**Comment by mdhorn** [comment]
I can tell from the error messages that this is an older image, could you please try the latest version.
https://clearlinux.org/downloads

**Comment by mdhorn** [comment]
@WSADKeysGaming Also please follow our published directions on creating the USB with Rufus
https://clearlinux.org/documentation/clear-linux/get-started/bootable-usb#bootable-usb-windows

**Comment by WSADKeysGaming** [comment]
Instructions were followed when completing the bootable USB, and it is on the latest version, 29450

**Comment by mdhorn** [comment]
Can you provide the full name of the image you download, please?

**Comment by WSADKeysGaming** [comment]
![20190522_130710](https://user-images.githubusercontent.com/34288820/58197746-8500c380-7c92-11e9-9620-379069dec8c5.jpg)

**Comment by mdhorn** [comment]
Okay. Can you please download the latest image and try again.
https://clearlinux.org/downloads
The latest image is https://cdn.download.clearlinux.org/releases/29540/clear/clear-29540-live-desktop.iso.xz

**Comment by mdhorn** [comment]
If the problem continues, if you could provide some details about the platform/laptop you are using.
Also helpful to know the USB is directly connected to the laptop or going through a hub? Is it USB3?

**Comment by WSADKeysGaming** [comment]
I misread 29450 as 29540. Writing the latest version worked.

**Comment by mdhorn** [comment]
@WSADKeysGaming  That's good to hear.
Closing the issue.

**Comment by WSADKeysGaming** [comment]
Thought it would be better to add to this issue than to start a new one.

After successfully installing on a blank SSD from the live desktop with these instructions (https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install-desktop) my laptop can't find the drive as bootable. Is my bios to be set as uefi or legacy?

**Comment by ahkok** [comment]
> Thought it would be better to add to this issue than to start a new one.

we prefer strongly that you open a new issue instead.

>  Is my bios to be set as uefi or legacy?

UEFI.

Please file a new issue if you need to post further comments.

**Comment by lf-araujo** [comment]
Hi all,

This issue is happening with the current version again. The same error, and I used dd as per the site instruction.

The filename is `clear-31130-live-desktop.iso.xz`.


Best,
lf

**Comment by jwakre** [comment]
> This issue is happening with the current version again. The same error, and I used dd as per the site instruction.

Can you open a new issue for this? Also, it would be helpful to provide additional information, like a screenshot of the errors in the new issue.
