### ISSUE TITLE
/usr/etc exists in a few packages, making Clear not properly stateless

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/distribution#783]
Steps to reproduce:

A quick repoquery reveals the full list of packages that contain content in /usr/etc:
```
$ dnf --config dnf.conf repoquery --whatprovides /usr/etc*
barbican-config-0:8.0.0-10.x86_64
cinder-config-0:14.0.0-46.x86_64
glance-config-0:17.0.0-63.x86_64
ironic-config-0:12.1.0-11.x86_64
keystone-config-0:14.0.1-106.x86_64
ldc-config-0:1.15.0-8.x86_64
mosquitto-config-0:1.6.2-23.x86_64
neutron-config-0:14.0.1-81.x86_64
nova-config-0:19.0.0-160.x86_64
sahara-config-0:10.0.0-24.x86_64
```

Here, the dnf.conf contains a definition referencing the external bin repo for Clear.

**Comment by bryteise** [comment]
@VictorRodriguez Would ^ be things you would know about?

**Comment by VictorRodriguez** [comment]
Ah that little part I forgot when I was doing OpenStack reintegration to clear :) 
Let me take a look, sorry for that, assign to me if you want

**Comment by VictorRodriguez** [comment]
After reviewing the bug this is not due to my changes in trying to add OpenStack back to clear

**Comment by puneetse** [comment]
@gtkramer I'm closing this issue because dnf doesn't show any packages providing `/usr/etc` in the current release (32120). Please feel free to reopen if you think more work is required.
