### ISSUE TITLE
NetworkManager-vpnc packaged but not vpnc itself

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#786]
specter [on the CL community forums points out](https://community.clearlinux.org/t/vpnc-binary-missing/474/3) that the vpnc plugin for NetworkManager (NetworkManager-vpnc) is packaged but not the vpnc binary itself.

Is there a usefulness to having the NM plugin without vpnc itself? If not, should vpnc be added to CL or the NM plugin removed?

I see vpnc itself hasn't been maintained in a while. There is a fork here that tries to keep up with security patches: https://github.com/streambinder/vpnc.

**Comment by specter42** [comment]
I compiled the suggested fork https://github.com/streambinder/vpnc and installed it. Works like charm so far. I can connect to my router (Fritzbox) and hadn't any issues.

**Comment by fenrus75** [comment]
I added the package earlier today so should show up soon inb release

**Comment by specter42** [comment]
It's now in release and works perfect!

Thanx!

**Comment by mrkz** [comment]
Closing now with the [fix applied to the NetworkManager-vpnc package](https://github.com/clearlinux-pkgs/NetworkManager-vpnc/commit/8aa2c4b7fd2c5b3fd6437daf5c58820a6b4d5280#diff-d667e73e68d3fc5652f0ca4024f7358cR18)
