### ISSUE TITLE
Yubikey U2F does not work in browser without adding udev rules for non-root access to /dev/hidraw{2,3}

### ISSUE THREAD

**Issue by xlfe** [clearlinux/distribution#787]
Trying to use my yubikey as a u2f device in Firefox visiting https://www.yubico.com/genuine/ - does not work.

Looking at dmesg
```
[ 3083.803233] hid-generic 0003:1050:0407.0009: input,hidraw2: USB HID v1.10 Keyboard [Yubico Yubikey 4 OTP+U2F+CCID] on usb-0000:00:14.0-6/input0
[ 3083.803962] hid-generic 0003:1050:0407.000A: hiddev96,hidraw3: USB HID v1.10 Device [Yubico Yubikey 4 OTP+U2F+CCID] on usb-0000:00:14.0-6/input1
```

And the permissions associated with the key 
```
crw------- 1 root root 240, 2 May 23 09:32 /dev/hidraw2
crw------- 1 root root 240, 3 May 23 09:32 /dev/hidraw3
```

Yubikey site has this guide
https://support.yubico.com/support/solutions/articles/15000006449-using-your-u2f-yubikey-with-linux

Which suggests adding the udev rules at https://raw.githubusercontent.com/Yubico/libu2f-host/master/70-u2f.rules

The relevant one for the yubikey is 

```
KERNEL=="hidraw*", SUBSYSTEM=="hidraw", ATTRS{idVendor}=="1050", ATTRS{idProduct}=="0113|0114|0115|0116|0120|0200|0402|0403|0406|0407|0410", TAG+="uaccess", GROUP="plugdev", MODE="0660"
```

After adding that rule and a group "plugdev" and reloading udev :- 

```
crw-rw----+ 1 root plugdev 240, 2 May 23 09:45 /dev/hidraw2
crw-rw----+ 1 root plugdev 240, 3 May 23 09:45 /dev/hidraw3
```

Once I add my user to plugdev, I can then use the u2f features of the yubikey in Firefox.

**Comment by puneetse** [comment]
@xlfe Does this process work? https://clearlinux.org/documentation/clear-linux/tutorials/yubikey-u2f

**Comment by xlfe** [comment]
@puneetse yes I think it would, the only difference being that the plugdev group doesn't exist in clearlinux? and so users not in the root group wouldn't be able to access it still?

**Comment by ahkok** [comment]
@phmccarty

**Comment by lebensterben** [comment]
>@puneetse yes I think it would, the only difference being that the plugdev group doesn't exist in clearlinux? and so users not in the root group wouldn't be able to access it still?

@xlfe I created a plugdev group and add my user account into it. Still it doesn't work.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miguelinux** [comment]
I added the `plugdev` group to Clear Linux, it will be available in 1-2 days.

**Comment by miguelinux** [comment]
@lebensterben, @xlfe 

Can you test again, the `plugdev` group is already in CL since `29620`

**Comment by lebensterben** [comment]
>@lebensterben, @xlfe  ...

@miguelinux I'm very sure that there was no 'plugdev' group until I created it yesterday.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by miguelinux** [comment]
Yes, there was not, Now it is in the distro ;-)

**Comment by lebensterben** [comment]
But `gpg --card-status` is still not working...
