### ISSUE TITLE
KDE bundle missing ... something and issues

### ISSUE THREAD

**Issue by MirceaMx** [clearlinux/distribution#789]
The KDE bundle seems broken. It's missing the GTK config. Also missing is the SDDM config. And even after installing those they do not appear. The Firefox fonts (since it is a GTK app) seem broken - they are ugly and jagged. There are issues with screen flickering and such (usually not found in KDE). Thank you.

**Comment by anselmolsm** [comment]
Hi @MirceaMx, what's the version of Clear Linux? 
sddm-kcm and kde-gtk-config are in desktop-kde bundle, the corresponding configuration screens are in System Settings (Startup and Shutdown, Application Style->GNOME/GTK Application Style respectively). These issues with fonts were reported previously and fixed, we need information to understand why you're still facing them. Thanks.

**Comment by MirceaMx** [comment]
Thank you. I understand. Used Linux for several years. Used KDE Plasma for two (2) years. IT specialist for 20 (twenty) years. I know ... but since Clear has issues and KDE works best for me especially since it has file preview capabilities and Clear OS does not then using Firefox has to be OK but Firefox is missing FFMpeg and have to compile it so ... no thanks, anything but Clear, to much hassle for me. Good luck.
