### ISSUE TITLE
Associate .zip files with Archive Manager

### ISSUE THREAD

**Issue by sirredbeard** [clearlinux/distribution#79]
When opening .zip files the first time after installing gnome-autostart nautilus claims there is no application installed that can handle .zip files.

If you click through to see "other apps" though there is archive manager which handles .zip files perfectly.

.zip, .tar.gz, .tar, .rar, etc. files should be associated with archive manager when it is installed.

**Comment by nesiusra** [comment]
@mrkz  - can you look at this please?

**Comment by nesiusra** [comment]
@AthenasJimenez  ...

**Comment by mrkz** [comment]
This is because we don't provide a proper MIME types database cache, we're working on fixing it while honoring our stateless policies, but in the meantime a workaround could be to run the following command:
```
$ sudo update-desktop-database
```

**Comment by ahkok** [comment]
```
$ sudo update-desktop-database
```

This is something we can do in a post-update trigger. Care should be taken to make sure that files are not written to `/usr` but instead go into `/var`.

**Comment by josuedhg** [comment]
this is working in release 23500

**Comment by sirredbeard** [comment]
Thank you.
