### ISSUE TITLE
fwupdmgr doesn't want to start

### ISSUE THREAD

**Issue by superm1** [clearlinux/distribution#792]
I performed a fresh install from `clear-29590-live-desktop.iso` on an XPS 9370, which should support firmware updates from fwupd.  I didn't install any bundles.

When I try to start `# fwupdmgr get-devices` I get an error:
```
Error calling StartServiceByName for org.freedesktop.fwupd: GDBus.Error:org.freedesktop.systemd1.NoSuchUnit: Unit fwupd.service not found
```

I looked around and I don't see `fwupd.service` nor `/usr/libexec/fwupd/fwupd` on the system either.

**Comment by thiagomacieira** [comment]
Do you have the firmware-update bundle installed?

**Comment by seanvk** [comment]
https://github.com/clearlinux/distribution/issues/604#issuecomment-480826992

**Comment by superm1** [comment]
@thiagomacieira, no I didn't install any bundles.  Since `fwupdmgr` command was preinstalled, I figured fwupd is already there.  I'll see if installing `firmware-update` bundle does anything.

**Comment by superm1** [comment]
Nope, installing `firmware-update` bundle I still get the exact same error.  I can't seem to find `fwupd.service` nor `/usr/lib/fwupd/fwupd` still either.

**Comment by ahkok** [comment]
It's been disabled on purpose: it physically made some machines unbootable.

**Comment by superm1** [comment]
I'm coming in from an upstream fwupd perspective; do you have any more details?
My guess is it was this: https://github.com/hughsie/fwupd/commit/57816a7907e5f56c2136af31a4f1ae5186d87565
If it was, that's a kernel driver bug and at working around it by blacklisting the usage when that driver is found helped avoid it.

If it's something else can you please file some details with upstream [fwupd](https://github.com/hughsie/fwupd)?

**Comment by ahkok** [comment]
Yeah, we need to get back to re-enabling this with @fenrus75  :)

**Comment by ahkok** [comment]
I think we may want to go the route where `fwupd` is an optional and non-default component, to prevent the issues we had encountered previously. One of the biggest issues we have right now with `fwupd` is that once it is installed, there is no way to *not* run it because gnome will start it through DBus activation. This is why we nuked the package essentially.

**Comment by ahkok** [comment]
Another thing I'd like to see is some "toothless" way of running fwupd. IOW it doesn't mess around with devices unless explicitly confirmed. The risk of a repeat is high...

**Comment by superm1** [comment]
Well for what it's worth it's a default and active package in most of the other big distros, even including RHEL, Fedora and Ubuntu.

It has a mode where it will shutdown when not in use to avoid needless memory consumption, you may be interested in configuring that.

I'd really like to hear details about your failure. Fwupd has a very extensive test suite and runs on quite a large range of hardware without conflict. The goals are that everything it does at probe time is safe.

**Comment by fenrus75** [comment]
can it probe once and store the results of the probe?

**Comment by superm1** [comment]
It supports a variety of usb devices including docks, Logitech devices, 8bitdo, and others.

Probing only once would mean you couldn't update those devices unless they were plugged in at boot up.

**Comment by superm1** [comment]
Also other than USB devices it does support things that get announced from Udev events such as Thunderbolt controllers.

**Comment by xlfe** [comment]
@fenrus75 @ahkok any updates? fwupd is important for keeping firmware of systems up to date

**Comment by fenrus75** [comment]
It’s been on for quite a while now

**Comment by xlfe** [comment]
I'm getting the following error

```
systemd[3953]: fwupd.service: Failed to set up mount namespacing: No such file or directory
systemd[3953]: fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory
```

Looks to be the same error as reported in #155 ? 

I have both fwupdate and firmware-update bundles installed...

**Comment by superm1** [comment]
@fenrus75 in https://github.com/clearlinux/distribution/issues/604#issuecomment-480826992
you said

> this is currently on purpose; the service is misbehaving on real hardware
and we had to turn it off

Can you turn it back on?

**Comment by xlfe** [comment]
I've been debugging this some more. 

On my system I think the fwupd service fails to start because I don't have my EFI partition mounted anywhere.

The error I'm getting is

> ```
> systemd[3953]: fwupd.service: Failed to set up mount namespacing: No such file or directory
> systemd[3953]: fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory
> ```

If I look at the strace using
```
sudo strace -ff -o /tmp/strace.log -s 2048 -p 1 -e all & sudo systemctl start fwupd
```
Then I can see that the "no such file" error comes from looking for the EFI partition

```
 cat /tmp/strace.log  |grep "No such file"
openat(4</run/systemd/unit-root/boot>, "EFI", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
name_to_handle_at(4</run/systemd/unit-root/boot>, "EFI", {handle_bytes=128}, 0x7ffec6c9dfc4, 0) = -1 ENOENT (No such file or directory)
openat(4</run/systemd/unit-root/boot>, "efi", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
name_to_handle_at(4</run/systemd/unit-root/boot>, "efi", {handle_bytes=128}, 0xXX, 0) = -1 ENOENT (No such file or directory)
openat(5</run/systemd/unit-root>, "efi", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
name_to_handle_at(4</run/systemd/unit-root>, "efi", {handle_bytes=128}, 0xXX, 0) = -1 ENOENT (No such file or directory)
openat(5</run/systemd/unit-root>, "efi", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/run/systemd/unit-root/efi", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = -1 ENOENT (No such file or directory)
openat(5</run/systemd/unit-root/var/lib>, "fwupd", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
name_to_handle_at(4</run/systemd/unit-root/var/lib>, "fwupd", {handle_bytes=128}, 0xXX, 0) = -1 ENOENT (No such file or directory)
sendmsg(3<UNIX:[->]>, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="PRIORITY=3\nSYSLOG_FACILITY=3\nCODE_FILE=../src/core/execute.c\nCODE_LINE=3325\nCODE_FUNC=exec_child\nUNIT=fwupd.service\nINVOCATION_ID=XX\nSYSLOG_IDENTIFIER=systemd\n", iov_len=189}, {iov_base="MESSAGE=", iov_len=8}, {iov_base="fwupd.service: Failed to set up mount namespacing: No such file or directory", iov_len=76}, {iov_base="\n", iov_len=1}], msg_iovlen=4, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 274
sendmsg(3<UNIX:[->]>, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="PRIORITY=3\nSYSLOG_FACILITY=3\nCODE_FILE=../src/core/execute.c\nCODE_LINE=3811\nCODE_FUNC=exec_spawn\nSYSLOG_IDENTIFIER=systemd\n", iov_len=123}, {iov_base="MESSAGE_ID=XX", iov_len=43}, {iov_base="\n", iov_len=1}, {iov_base="UNIT=fwupd.service", iov_len=18}, {iov_base="\n", iov_len=1}, {iov_base="INVOCATION_ID=XX", iov_len=46}, {iov_base="\n", iov_len=1}, {iov_base="MESSAGE=fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory", iov_len=108}, {iov_base="\n", iov_len=1}, {iov_base="EXECUTABLE=/usr/libexec/fwupd/fwupd", iov_len=35}, {iov_base="\n", iov_len=1}], msg_iovlen=11, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 378
```
 
According to [fwupd](https://github.com/fwupd/fwupd/wiki/Determining-EFI-system-partition-location) the EFI partition is required @superm1 ?

Is that just me, or does Clear Linux not include EFI partitions in those that are auto mounted?

Looking at https://clearlinux.org/news-blogs/where-etcfstab-clear-linux CL should mount the boot EFI partition at /boot ?

but when I do  `sudo systemctl list-units *.mount` I do not have a boot-efi.mount service.

I can see the EFI partition if I do a `sudo blkid` so it exists, it's just not getting mounted?

@fenrus75 is CL meant to mount the EFI partition automatically?

**Comment by fenrus75** [comment]
we on purpose do not mount the EFI partition normally, only for short
durations during sofware update when there's a new kernel.

EFI partitions are VFAT, and it's just more robust to not mount those if
you don't need them (no journalling etc)

**Comment by superm1** [comment]
> According to fwupd the EFI partition is required @superm1 ?

What version of fwupd in CL currently?

Older versions of fwupd were not happy to find one missing, but current versions are supposed to show errors in fwupdmgr letting you know EFI updates won't work, but daemon should handle this scenario just fine.

The logic for detecting ESP and setting up errors landed back around 1.1.x I thought (https://github.com/fwupd/fwupd/commit/cfc22a8b90a1a3bfda59c72e6a81312a86596665 IIRC)

@fenrus75 

Conceptually I don't see a problem with mounting ESP on demand.  You're right it's not frequently needed.

But how is the correct EFI partition location supposed to be properly detected by another userspace application to mount it?  Right now current version of fwupd will check for an already mounted ESP in some known locations (https://github.com/fwupd/fwupd/blob/master/plugins/uefi/fu-uefi-common.c#L355) but it won't actually try to mount any of them.

**Comment by superm1** [comment]
> systemd[3953]: fwupd.service: Failed to set up mount namespacing: No such file or directory
systemd[3953]: fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory

That doesn't look like it's even fwupd at this point getting unhappy, it's still in systemd at this point.  Can you post the systemd unit for fwupd in CL?  Is it varying from upstream in atll?

SELinux in use?

**Comment by superm1** [comment]
> openat(5</run/systemd/unit-root/var/lib>, "fwupd", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = -1 ENOENT (No such file or directory)
name_to_handle_at(4</run/systemd/unit-root/var/lib>, "fwupd", {handle_bytes=128}, 0xXX, 0) = -1 ENOENT (No such file or directory)

That specifically looks more damning to me with how it's been configured.

**Comment by xlfe** [comment]
`/usr/lib/systemd/system/fwupd.service`

```
[Unit]
Description=Firmware update daemon
Documentation=https://fwupd.org/
After=dbus.service
Before=display-manager.service

[Service]
Type=dbus
BusName=org.freedesktop.fwupd
ExecStart=/usr/libexec/fwupd/fwupd
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=full
RestrictAddressFamilies=AF_NETLINK AF_UNIX
SystemCallFilter=~@mount
ProtectControlGroups=yes
ProtectKernelModules=yes
RestrictRealtime=yes
ReadWritePaths=/var/lib/fwupd /usr/share/fwupd/fwupd /usr/share/fwupd/fwupd/remotes.d -/boot/efi -/efi/EFI -/boot/EFI
```

Here's the CL Package https://github.com/clearlinux-pkgs/fwupd - version 1.2.9

**Comment by superm1** [comment]
Does /var/lib/fwupd actually exist on your system? Or was it artificially removed when this unit was gimped?

**Comment by xlfe** [comment]
no `/var/lib/fwupd` does not exist on my system

```
/usr/libexec/fwupd:
total 1192
drwxr-xr-x  3 root root   4096 .
drwxr-xr-x 37 root root  20480 ..
drwxr-xr-x  2 root root   4096 efi
-rwxr-xr-x  1 root root 473696 fwupd
-rwxr-xr-x  1 root root  26744 fwupdagent
-rwxr-xr-x  1 root root 108792 fwupdate
-rwxr-xr-x  1 root root  75896 fwupdoffline
-rwxr-xr-x  1 root root 498192 fwupdtool

/usr/lib/fwupd:
total 80
drwxr-xr-x  2 root root  4096 .
drwxr-xr-x 32 root root  4096 ..
-rwxr-xr-x  1 root root 73605 fwupx64.efi

/usr/share/fwupd:
total 44
drwxr-xr-x   7 root root  4096 .
drwxr-xr-x 232 root root 12288 ..
-rwxr-xr-x   1 root root  4383 firmware-packager
drwxr-xr-x   3 root root  4096 fwupd
drwxr-xr-x   2 root root  4096 metainfo
drwxr-xr-x   4 root root  4096 pki
drwxr-xr-x   2 root root  4096 quirks.d
drwxr-xr-x   4 root root  4096 remotes.d

/usr/share/fwupd/fwupd:
total 24
drwxr-xr-x 3 root root 4096 .
drwxr-xr-x 7 root root 4096 ..
-rw-r--r-- 1 root root  689 daemon.conf
-rw-r--r-- 1 root root  302 redfish.conf
drwxr-xr-x 2 root root 4096 remotes.d
-rw-r--r-- 1 root root  372 uefi.conf

/usr/share/fwupd/pki/fwupd:
total 24
drwxr-xr-x 2 root root 4096 .
drwxr-xr-x 4 root root 4096 ..
-rw-r--r-- 1 root root 1702 GPG-KEY-Hughski-Limited
-rw-r--r-- 1 root root 2169 GPG-KEY-Linux-Foundation-Firmware
-rw-r--r-- 2 root root  959 GPG-KEY-Linux-Vendor-Firmware-Service
-rw-r--r-- 2 root root 1679 LVFS-CA.pem

/usr/share/installed-tests/fwupd:
total 40
drwxr-xr-x 2 root root 4096 .
drwxr-xr-x 8 root root 4096 ..
-rw-r--r-- 1 root root 1681 fakedevice123.cab
-rw-r--r-- 1 root root 1691 fakedevice124.cab
-rwxr-xr-x 1 root root 2104 fwupdmgr.sh
-rw-r--r-- 1 root root   78 fwupdmgr.test
-rw-r--r-- 1 root root 4450 fwupd-tests.xml
-rwxr-xr-x 1 root root 7201 hardware.py

/usr/share/package-licenses/fwupd:
total 60
drwxr-xr-x   2 root root  4096 .
drwxr-xr-x 665 root root 20480 ..
-rw-r--r--   1 root root  1314 contrib_debian_signing-template_copyright
-rw-r--r--  33 root root 26530 COPYING
-rw-r--r--   1 root root  1498 data_tests_thunderbolt_COPYING
```

**Comment by superm1** [comment]
Can your try creating it? The systemd unit requires it to start since it's in the first RW path.

**Comment by xlfe** [comment]
That worked!

I now get 

```
systemd[1]: Starting Firmware update daemon...
fwupd[]:  FuPluginUefi         Unable to determine EFI system partition location, override using OverrideESPMountPoint in uefi.conf
systemd[1]: Started Firmware update daemon.
```

fwupdmgr appears to work too

**Comment by superm1** [comment]
Well that's great, it identified part of the problem here.

You'll notice a message that ESP couldn't be detected. That's because it's not mounted. So my question about how to detect it to be able to mount is still valid and something that needs to be sorted for EFI updates to be workable.

**Comment by ahkok** [comment]
> systemd[3953]: fwupd.service: Failed at step NAMESPACE spawning /usr/libexec/fwupd/fwupd: No such file or directory
>
> That doesn't look like it's even fwupd at this point getting unhappy, it's still in systemd at this point.  Can you post the systemd unit for fwupd in CL?  Is it varying from upstream in atll?
the binary is not there (it was explicitly removed)
>
> SELinux in use?
no - clearlinux doesn't support it. At all.

**Comment by superm1** [comment]
Some notes:
* fwupd 1.3.2 contains the stuff to create the state directory automatically mentioned above
* (currently unreleased) fwupd 1.3.3 will have code necessary to automatically mount EFI partitions dynamically when needed (https://github.com/fwupd/fwupd/commit/4062a3566a48ec1994d199761ba769fff6f08cd0)

**Comment by ahkok** [comment]
Updated to `1.3.2`.

**Comment by superm1** [comment]
Does that mean actually functional now? Or are some parts still stripped?

**Comment by fenrus75** [comment]
the only thing we disabled is the hard probing raw into PCI devices.

the rest is as-is

**Comment by superm1** [comment]
I didnt think we did any of that but in general that sounds uncontroversial. Can you link me to a patch so I can see? If it makes sense upstream we can bring it for 1.3.3.

**Comment by superm1** [comment]
Poking around, is it this? https://github.com/clearlinux-pkgs/fwupd/blob/master/no-poking-in-config-space.patch

That actually doesn't run during probing ever.  It's only run if someone calls the "verify" argument to `fwupdmgr` which will verify the checksum the ROM against what is stored in the database.

**Comment by ahkok** [comment]
That's the only "net" patch we carry atm... The other patch is for the `boot.mount` location.

**Comment by superm1** [comment]
OK thanks.  I would recommend you revert that, it's not necessary and will break verify on certain devices.

Once you 1.3.3 is tagged and you move up to 1.3.3 you can drop that `boot.mount` location thing otherwise you can backport https://github.com/fwupd/fwupd/commit/4062a3566a48ec1994d199761ba769fff6f08cd0 and can drop `boot.mount`.

**Comment by ahkok** [comment]
Spotting this:

> Leave them mounted when done (you gotta reboot anyway).

That doesn't make sense? If I have a power failure and the ESP is mounted, I'm likely to hit a problem. Unmounting seems a lot safer, and postponing the unmount just delays it - it must be unmounted before rebooting. If some other process like our bootloader manager is working on the mount, it will finish as soon as that is done.

**Comment by superm1** [comment]
Well it's only mounted when you run the update and you're prompted to reboot immediately after flashing the update.  If you think this is still too risky, I'll file an issue to track unmounting at that time too.

**Comment by bryteise** [comment]
@superm1 thanks, being prompted for reboot and actually rebooting can be different enough times (in my own usage at least) that doing the unmount right away seems safer.

**Comment by superm1** [comment]
Here's a PR for it: https://github.com/fwupd/fwupd/pull/1500

It won't backport as easily now though as it depends on some other 1.3.3 infrastructure, so I would say just wait until 1.3.3.

**Comment by superm1** [comment]
1.3.3 was just released today, so I think once you guys update to that this issue is likely closable.

**Comment by fenrus75** [comment]
updated to 1.3.3

**Comment by superm1** [comment]
> updated to 1.3.3

I just re-installed clear locally and i'm only seeing 1.3.2.  Does it take some time to roll out?

**Comment by fenrus75** [comment]
it takes about 1 workday for a release to go through the QA process/etc
(2 if it fails QA ;-) )

**Comment by superm1** [comment]
Thanks, I think we can close this now.

FYI I opened a PR to your package to fixup your patches; they will cause crashes if someone runs `fwupdmgr verify` on an `optionrom` device.
https://github.com/clearlinux-pkgs/fwupd/pull/1
