### ISSUE TITLE
Download options cant be saved

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/distribution#793]
Description:
When downloading any file in any other distro or OS you would get a pop out window asking if you would like to open or save the file. Also within this pop up you can almost always see an option that reads : "Do this automatically for files like this from now on"

Well on Clear Linux version 29610 when I download a file, the checkbox of the "Do this automatically for files like this from now on" option is not enabled so that I may decide to do the same action with other files. 

![Screenshot from 2019-05-23 20-47-02](https://user-images.githubusercontent.com/36279716/58287808-7bb24c80-7da1-11e9-88ab-0d17d04a4dd6.png)

Steps to reproduce: 

1. Install Clear LInux
2. On the go to the clearlinux download page
3. Download the Desktop image

**Comment by lebensterben** [comment]
@LibertadCruz 
I can reproduce this. But this option is available for most formats.
For example, try download the zip file of the `clearlinux/distribution`, you would see the option "Do this automatically for files like this from now on" is available.
