### ISSUE TITLE
Consider adding Sway

### ISSUE THREAD

**Issue by MattiaVerticchio** [clearlinux/distribution#801]
Since both GNOME and Plasma have their options to enable a Wayland session, it would be nice to have [sway](https://github.com/swaywm/sway) as a Wayland i3-based window manager. It’s fast, minimal, actively developed and solves the [tearing problem in i3](https://community.clearlinux.org/t/how-to-enable-tearfree/1011/3?u=mattiaverticchio), since it incorporates a Wayland compositor. There is also a request for this package [on the forum](https://community.clearlinux.org/t/sway-tiling-window-manger-to-upstream/943?u=mattiaverticchio).

Based on the sway wiki, I’ll list some commonly used packages that could fit in a `desktop-sway` bundle, to make it fully functional:

- [sway](https://github.com/swaywm/sway) which is the compositing window manager itself
- [swaylock](https://github.com/swaywm/swaylock) to manage screen locking
- [swayidle](https://github.com/swaywm/swayidle) as an idle manager
- [swaybg](https://github.com/swaywm/swaybg) for setting wallpapers
- [grim](https://github.com/emersion/grim) and [slurp](https://github.com/emersion/slurp) for taking screenshots
- [wf-recorder](https://github.com/ammen99/wf-recorder) for screen recording
- [brillo](https://gitlab.com/cameronnemo/brillo) for controlling brightness

**Comment by MattiaVerticchio** [comment]
I updated the first comment with my recent findings on sway usage. Also, a `package-request` label may be more appropriate than an `enhancement` one.

**Comment by ahkok** [comment]
I added `sway` and `wlroots`. There will be a new `sway` bundle in a few days.

**Comment by MattiaVerticchio** [comment]
First of all, thank you for the `sway` bundle! :smile:

I installed and tried to start it via GDM. It fails to start and I only get a black screen, then get redirected to GDM.

This is my `swupd bundle-list` output:
```
NetworkManager
NetworkManager-extras
acpica-unix2
alsa-utils
aspell
aspell-es
baobab
binutils
bison
boot-encrypted
bootloader
bootloader-extras
c-basic
cheese
curl
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
diffutils
emacs-x11
eog
evince
evolution
file
file-roller
findutils
firefox
flatpak
flex
fonts-basic
fuse
geary
gedit
gimp
git
gjs
glibc-locale
gnome-base-libs
gnome-calculator
gnome-characters
gnome-color-manager
gnome-disk-utility
gnome-font-viewer
gnome-logs
gnome-music
gnome-photos
gnome-screenshot
gnome-system-monitor
gnome-todo
gnome-weather
graphviz
gstreamer
gvim
gzip
hardware-printing
hardware-uefi
htop
iperf
iproute2
kbd
kernel-install
kernel-native
less
lib-imageformat
lib-opengl
lib-openssl
lib-samba
libX11client
libglib
libstdcpp
libva-utils
linux-firmware
linux-firmware-extras
linux-firmware-wifi
llvm
make
man-pages
minicom
nasm
nautilus
openldap
openssh-client
openssh-server
openssl
os-core
os-core-plus
os-core-update
os-core-webproxy
p11-kit
parallel
patch
perl-basic
polkit
powertop
procps-ng
pulseaudio
pygobject
python3-basic
qemu-guest-additions
seahorse
strace
sudo
sway
sysadmin-basic
syslinux
thermal_daemon
tmux
totem
tzdata
unzip
vim
webkitgtk
which
wpa_supplicant
x11-server
xz
zstd
```

P.S.: Do you prefer that I open new issues for this bundle?

**Comment by ahkok** [comment]
On 9/25/19 3:29 AM, Mattia Verticchio wrote:
> P.S.: Do you prefer that I open new issues for this bundle?

Yes, please.

If possible try and cut&paste relevant sections from `journalctl` - omit 
anything that doesn't seem relevant or doesn't indicate an error.

I mean, we're not going to complain if you don't. But we can't track 
issues properly on the list. And this is likely something we'll get to 
in a few days, but not tomorrow, you get the idea.

Auke

**Comment by brainshave** [comment]
Thanks for getting the `sway` bundle in :-)

I initially had the same problem and it seems like it's not starting if you don't have a sway configuration in your home folder. After I put my config from a previous system in, sway started fine :-)

As a work-around you can get a default config from https://github.com/swaywm/sway/blob/v1.2/config.in but you probably have to replace instances of `@datadir@` with `/usr/share` and remove the last line (`include @sysconfdir@/sway/config.d/*`). It'll probably start with those `@...@` left in though. Put it under `~/.config/sway/config`. Fingers crossed this solves your issue :crossed_fingers:

**Comment by MattiaVerticchio** [comment]
> Fingers crossed this solves your issue :crossed_fingers:

Yes it does, thank you @brainshave for this suggestion! :smile:
