### ISSUE TITLE
Nginx-Mainline bundle has inconsistencies and is collding with Nginx bundle

### ISSUE THREAD

**Issue by xRiot** [clearlinux/distribution#804]
**Nginx-Mainline** bundle _(for latest version)_ is interfering with configuration of **Nginx** bundle _(the stable release)_, this prevents the user from running the stable build alongside of latest for testing.

**Nginx-Mainline**
```diff
+ Executable: `/usr/bin/nginx-mainline/`
+ Default confs: `/usr/share/nginx-mainline/conf/`
- User confs: `/etc/nginx/`
- PID file: `/run/nginx.pid`
```
**Nginx**
```diff
+ Executable: `/usr/bin/nginx/`
+ Default confs: `/usr/share/nginx/conf/`
- User confs: `/etc/nginx/`
- PID file: `/run/nginx.pid`
```
Furthermore both bundles' `nginx.conf.example` is looking for virtual host files in `/etc/nginx/conf.d/*`, therefore the `server.conf.example` should be provided inside `/usr/share/{bundle}/conf/conf.d` to make the setup and configuration more beginner/user friendly.

**Side note**
Lastly it's worth to mention that the bundle does not start after installation due to configuration files not being created automatically (see #686) plus the above inconsistencies and on top of the Mainline process trying to bind to a non-existent file `/run/nginx.pid` (`/run/nginx-mainline.pid` is created but not used in mainline bundle). From my understanding this is because you want to make it possible to run multiple web-servers without interference with each other _(in theory)_. It'd be best if randomized ports were provided natively in the stock configuration to make the installation process more straightforward/work out of the box?

**Comment by ahkok** [comment]
> It'd be best if randomized ports were provided natively in the stock configuration to make the installation process more straightforward/work out of the box?

No, instead, the user must configure one of them to listen on a different port.

Randomized ports are not a mainstream solution, and therefore not something we'll ever do.

**Comment by ahkok** [comment]
The `pid` file is already set to: `nginx pid file: "/run/nginx-mainline.pid"`... how did you get the pid file location for mainline?

**Comment by ahkok** [comment]
I fixed the references to use `/etc/nginx-mainline` which is the only remaining issue.

**Comment by xRiot** [comment]
> The `pid` file is already set to: `nginx pid file: "/run/nginx-mainline.pid"`... how did you get the pid file location for mainline?
@ahkok It's looking for /run/nginx.pid, see this paste: https://pastebin.com/raw/Ei3ehf5C

**Comment by ahkok** [comment]
Ahh thanks, yes, one more fix needed here...!

**Comment by ahkok** [comment]
`nginx-mainline-1.17.0-79`
