### ISSUE TITLE
Clear Linux in VirtualBox no boot when number of CPUs>1

### ISSUE THREAD

**Issue by cgamez** [clearlinux/distribution#807]
Hi,
I have installed Clear Linux in VirtualBox.  It runs OK with one guest processor only.
If I try to increase processors, Clear Linux in VirtualBox will not boot.
I'm attaching VirtualBox logs to see if someone finds why this occurs.  I could not find the issue.
Thanks!
[Linux Clear OS-2019-05-26-00-34-18 One VirtualCPU boot OK.log](https://github.com/clearlinux/distribution/files/3220031/Linux.Clear.OS-2019-05-26-00-34-18.One.VirtualCPU.boot.OK.log)
[Linux Clear OS-2019-05-26-00-36-10 Four VirtualCPUs No boot.log](https://github.com/clearlinux/distribution/files/3220032/Linux.Clear.OS-2019-05-26-00-36-10.Four.VirtualCPUs.No.boot.log)

**Comment by puneetse** [comment]
Can you check that the `I/O APIC` option in the VM settings in checked under System --> Motherboard? 

> Enabling the I/O APIC is required for 64-bit guest OSes, especially Windows Vista. It is also required if you want to use more than one virtual CPU in a virtual machine. 

Reference: https://www.virtualbox.org/manual/ch03.html#settings-processor

**Comment by cgamez** [comment]
@puneetse Thanks for your reply.  I have checked the I/O APIC option and it is on (it is also a requirement for the ICH9 chipset I selected).

I did some full-screen guest tests and I was able to see a new brief flash message appear:

intel_powerclamp: CPU does not support MWAIT.

I did some search and found out this might have to do with an old bug in the kernel where some CPU's are whitelisted to use MWAIT but these do not support the opcode:

(2016 bug): https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1630774
(2016 whitelisting cpus): https://lkml.org/lkml/2016/10/18/356
(what is intel_powerclamp): https://www.kernel.org/doc/Documentation/thermal/intel_powerclamp.txt
(kernel patch that fixed 2016 bug): https://patchwork.kernel.org/patch/9365003/

My Host CPU: i7-2600K

**Comment by bwarden** [comment]
I think the MWAIT message is a red herring. But comparing logs between n=1 and n=4, this jumped out at me:
```
gnome-session[437]: gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.Keyboard.desktop' exited with code 1
gnome-session[437]: gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.XSettings.desktop' exited with code 1
gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.Keyboard.desktop' exited with code 1
gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.XSettings.desktop' exited with code 1
gsd-power[527]: gsd-power: Fatal IO error 11 (Resource temporarily unavailable) on X server :1024.
gnome-session[437]: gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.Power.desktop' exited with code 1
gnome-session-binary[437]: WARNING: App 'org.gnome.SettingsDaemon.Power.desktop' exited with code 1
polkitd[344]: Unregistered Authentication Agent for unix-session:c1 (system bus name :1.31, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
gnome-session[437]: gnome-session-binary[437]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1
gnome-session-binary[437]: Unrecoverable failure in required component org.gnome.Shell.desktop
gnome-session-binary[437]: WARNING: App 'org.gnome.Shell.desktop' exited with code 1


```

**Comment by bwarden** [comment]
I also noticed that I could get a TTY via ctrl-alt-F2, so it's just gdm failing to start.

**Comment by cgamez** [comment]
@bwarden Let me do some more tests and review the logs.  I want to use it as a desktop, the gnome desktop is really fast, but it needs SMP to be fluid. When I try to log in a TTY, it eventually blacks out and does not respond, before I can log in, but I can shut down the machine, as it responds to ACPI shut-off.

**Comment by 11h10** [comment]
It is the same bug with virt-manager-gui and Number CPU>1

**Comment by cgamez** [comment]
Closing issue due to duplicate open bug #749
