### ISSUE TITLE
Add frame interpolation software

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#809]
I am getting a new laptop as I am going to college this fall. As such, I will be leaving my desktop behind and installing Clear Linux on my new computer.

One of my main uses of my computer is to re-encode video files using a higher frame rate (with frame interpolation software). Typically this is done through SVP (SmoothVideo Project) which is freeware for Linux and includes a program called SVPcode that is made specifically for this purpose. Because it requires proprietary codec support, I don't use it on Clear Linux but rather something like Solus or Ubuntu. I'm sure I could set it up but I don't think it's worth the hassle.

AMD also has a proprietary tool to do this called "AMD Fluid Motion". It works wonderfully, even better than SVP, but is Windows only. A third-party tool called A's Video Converter and Bluesky Frame Rate Converter work together to allow for re-encoding video files using AMD's Fluid Motion. Since I'll have a laptop with just Intel integrated graphics, I won't be able to use this software either.

This brings me to my main request which is that Intel should develop or find a way to include software that uses frame interpolation to convert or playback videos with a higher frame rate. Not everyone wants this, but it is extremely annoying to have to switch to a different distribution just for this functionality. Since proprietary codec support is being worked on for Clear Linux users, I was hoping the inclusion of SVP could be evaluated (freeware license available [here](https://www.svp-team.com/wiki/SVP_4_Free_license)), or more ideally, a native solution be developed by Intel like AMD has.

I know this is a long and extremely specific request, but I'm hoping others are interested and that as Clear gains a wider user base, its abilities as a workstation OS expands to include niche use cases such as this. Thank you for your consideration!

**Comment by ahkok** [comment]
There are too many mentions of "this is not open source" in this topic. It also sounds like it's just a gimmick. You're likely better off playing with VSync enabled at the proper frame rate. You'd use less power for sure.

And no, we are *not* working on adding proprietary software codecs, which is what you need for this sort of thing. What we are working on is to enable hardware encode/decode of whatever the Intel HD graphics GPU can do. It's not the same, for obvious reasons.

AFAICS, Intel can not redistribute SVP. So that would be the end of the line for this request. Sorry.

**Comment by OpenSourceAnarchist** [comment]
I am sorry to hear that. It may sound "gimmicky," but I can assure you, there is a strong community of enthusiasts who prefer high frame rate video playback. And syncing the frame rates is not the same thing whatsoever, but thank you for the suggestion.

I also apologize for not wording the proprietary codec part correctly. I misunderstood what you wrote on the ffmpeg issue/thread. I guess what this means is that videos can be encoded/decoded natively, but I am unsure what this means about how software can interact with the GPU. SVP can make use of QSV which I thought is what is being enabled?

I posted on the SVP forums about possibly getting it distributed as a flatpak but I doubt that will happen. I suppose I'll have to keep a minimal Ubuntu install just for this purpose (unless the regular SVP install will somehow work after Clear Linux enables hardware encoding/decoding). Too bad!

**Comment by ahkok** [comment]
SVP's license is really the main problem, please read it for yourself.

Maybe it is really useful to people, or maybe it's a marketing thing ;). I do know that your video hardware will need to render twice the amount of frames, which has a power cost. Plus some of the screen actors' guild seem to be against things like this. Well, that's maybe not as much as a factor ;)

If some open source video processing software implemented the same methodology, it's not patented, and uses VAAPI hardware encode, I see no reason why we couldn't add it to clearlinux. Unfortunately that seems to be a stretch, so, until then, this stays closed - nothing the clearlinux team can really do about it.
