### ISSUE TITLE
docker: some odd log warnings

### ISSUE THREAD

**Issue by Andy2244** [clearlinux/distribution#81]
I get those two warnings over and over:
` level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc5\nspec: 1.0.0\n"`

`
level=warning msg="failed to retrieve docker-init version: exec: \"docker-init\": executable file not found in $PATH"`

The second one is caused since clearlinux ship's without a `docker-init`, is there a reason why?
Upgraded manually to 18.03.x seems to have solved this via [stable bins](https://download.docker.com/linux/static/stable/x86_64/) and renaming/symlinking to clearlinux's naming conventions for the bins, aka `docker-runc -> runc`.

**Comment by nesiusra** [comment]
@bryteise @ahkok

**Comment by bryteise** [comment]
Giving this over to @DnPlas

**Comment by DnPlas** [comment]
Hi @Andy2244 could you please tell me the following:
- Your Clear Linux version (in which version this warning appears)
- Your Docker version
- What command triggers this output?
Could you also post the output of $ sudo docker info?

**Comment by Andy2244** [comment]
@DnPlas Sorry, seem the logs are already gone/rotated out. Probably because i still get thousands of: `kernel: clr: call_modprobe: net-pf-10   2` entries per day via the hyper-v kernel.
I have auto updates on so assume, i had the latest Clear Linux version/docker bins from 14 days ago.

I use cockpit/portainer to manage my system so maybe it was from those, since it sounds like some query info warning.

I tried to reproduce the warning and in doing so seem to have broken my system, via:
`swupd verify -f -Y`
after that cockpit could not login anymore and gives `Wrong user name or password`, which is strange since the root user still exists and works via ssh, so i assume some pam issues again.

`swupd bundle-remove sysadmin-remote`
Now nothing swupd related works anymore...
```
swupd update
Curl error: (35) SSL connect error
Error: Network issue, unable to proceed with update
```
and
```
swupd bundle-add sysadmin-remote
Curl error: (35) SSL connect error
```
```
swupd verify
Verifying version 23090
Curl error: (35) SSL connect error
Error: Network issue, unable to download manifest
Error: Verify did not fully succeed
```

Ping/wget works so i guess its curl related any advice i can try to fix the system now, else than setting it up again?

**Comment by Andy2244** [comment]
Oh just noticed here are the warnings again via journalctl -b
```
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.358655621+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to se>
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.544288636+02:00" level=info msg="Loading containers: done."
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.595588813+02:00" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: kernel has C>
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.647864489+02:00" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc5\nspec: 1.0.0\n"
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.649115389+02:00" level=warning msg="failed to retrieve docker-init version: exec: \"docker-init\": executable file not found in $PATH"
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.649295089+02:00" level=info msg="Docker daemon" commit=19e2cf6259bd7f027a3fff180876a22945ce4ba8 graphdriver(s)=overlay2 version=17.12.1
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.650340988+02:00" level=info msg="Daemon has completed initialization"
Jun 16 11:35:39 clear-vm dockerd[260]: time="2018-06-16T11:35:39.668247280+02:00" level=info msg="API listen on /var/run/docker.sock"
```

**Comment by DnPlas** [comment]
@Andy2244 as you said, Clear Linux is shipped without docker-init. I'm now working on the spec file to add it, that should solve the second warning. Regarding the first one, that's a known issue and as you saw with version 18.03.x, it is solved on such release (18). I'm looking for a workaround for that as Clear Containers, and soon Kata Containers, needs that Docker version.

**Comment by Andy2244** [comment]
@DnPlas Thanks for looking into this, its just something minor i noticed.
