### ISSUE TITLE
cannot synced with my google account

### ISSUE THREAD

**Issue by nobodywithbody** [clearlinux/distribution#810]
Hi all!

I'am trying to connect to my google account from gnome-control-center after installation fresh system. I have internet, but i can't click on "google account" option in "online accounts" section. And i see message "no internet connection - connect to set up new online accounts".

Proxy is turned off. I did not touch network settings after installation.

> swupd info
Installed version: 29620

![image](https://user-images.githubusercontent.com/51095682/58436474-33ab6680-80ce-11e9-888f-ffbb0f7a0716.png)

In setting popup i see that wired connection is not connected(but it is!). If i click on "connect" then nothing happens.

![image](https://user-images.githubusercontent.com/51095682/58437776-2f824780-80d4-11e9-84f9-cfc2c0390183.png)

In "network" section on "gnome settings" there is no any mention about my wired connection.

![image](https://user-images.githubusercontent.com/51095682/58437844-81c36880-80d4-11e9-879f-491f4dd9358f.png)

How can i fix that? Glad for your help

**Comment by pceiley** [comment]
This is likely caused by #735. A fix should be coming soon.

**Comment by lebensterben** [comment]
In the terminal, run 'man stateleas' and you will see some commands in the last section about Network Management. You can use these commands to fix the problem.

Detailes are discussed in issue 735.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nobodywithbody** [comment]
@lebensterben 
> man stateleas
No manual entry for stateleas

**Comment by miguelinux** [comment]
> @lebensterben 
> > man stateleas
> No manual entry for stateleas
> 

man stateless

**Comment by nobodywithbody** [comment]
This helped repairing network. Thanks!

But i still cannot add my google account. Logs not contains any error. After accepted all permission in google account window is closed and nothing happen.

**Comment by lebensterben** [comment]
>This helped repairing network. Thanks! ...

@nobodywithbody
>This helped repairing network. Thanks! ...

@nobodywithbody This is same as #599. You may close this issue if they're indeed identical.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nobodywithbody** [comment]
@lebensterben got it. Thank you.
