### ISSUE TITLE
Vapoursynth

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [clearlinux/distribution#812]
Vapoursynth is a modern alternative to Avisynth. It is used for video manipulation and is also supported by mpv, which, if this package is added, should be configured to have vapoursynth support enabled.

It is licensed under the GPL v2.
Its source code can be found here: https://github.com/vapoursynth/vapoursynth
Its official website is http://www.vapoursynth.com/

It is a popular package available on well-known distros such as Arch, Debian (multimedia), FreeBSD, MX, openSUSE, Solus, and Void. Vapoursynth is python-based and would benefit greatly from Clear Linux's python stack optimizations.

**Comment by ahkok** [comment]
I managed to compile it... what does it even do? :)

**Comment by ahkok** [comment]
Also, should it go into a separate bundle?

**Comment by OpenSourceAnarchist** [comment]
It's used for various video filters when either encoding or deciding video files. I think it would make more sense to put it in a separate bundle but have mpv require it (and change the configuration of mpv to build against it). It really needs to be paired with a video player for it to be useful :)

**Comment by ahkok** [comment]
ah, no, it's dumb and hurts itself.

**Comment by OpenSourceAnarchist** [comment]
I mean I'd rather have it available in a bundle and compile mpv against it myself than not have it packaged at all. But mpv does support it which is why I recommended providing the support out of the box.

**Comment by ahkok** [comment]
https://github.com/vapoursynth/vapoursynth/issues/447

**Comment by OpenSourceAnarchist** [comment]
@ahkok A new version was released and a response was posted at https://github.com/vapoursynth/vapoursynth/issues/447#issuecomment-496878687. Is there any way for this to be packaged? It would be best as a build requirement of the mpv bundle since mpv has built-in functionality for vapoursynth scripts and filters.

VapourSynth Editor is available as a flatpak on Clear Linux... Kinda useless since vapoursynth itself is unavailable :)

**Comment by dubhater** [comment]
> Vapoursynth is python-based and would benefit greatly from Clear Linux's python stack optimizations.

What are these optimizations?

**Comment by OpenSourceAnarchist** [comment]
@dubhater These pages explain it pretty well.

https://clearlinux.org/news-blogs/boosting-python-profile-guided-platform-specific-optimizations

Benchmark: https://www.phoronix.com/scan.php?page=news_item&px=Clear-Linux-2019-Python-Perf

**Comment by K1ngfish3r** [comment]
Autospec notes - [for-review.txt](https://gist.github.com/K1ngfish3r/587bfce11ccd29627872224032bd0287)

URL = https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R69.tar.gz
License = LGPL-2.1

**series** - Use patch from src.fedoraproject.org to fix soversion issue
[vapoursynth-version-info.patch](https://src.fedoraproject.org/rpms/vapoursynth/raw/rawhide/f/vapoursynth-version-info.patch)

**build_pattern** - configure_ac

**buildreq_add** - python3-dev

**pkgconfig_ban** - python-$PYTHON_VERSION-embed

**configure**
```
--enable-x86-asm
--enable-core
--enable-vsscript
--enable-vspipe
--enable-python-module
```

**Comment by bwarden** [comment]
In the pipeline...
