### ISSUE TITLE
Package request: iBus-Unikey IME

### ISSUE THREAD

**Issue by Maxvien** [clearlinux/distribution#813]
iBus-Unikey is a Vietnamese Input Method Engine for IBus using Unikey Engine

It is licensed under the GPL v3.
Its source code can be found here: https://github.com/vn-input/ibus-unikey
Thanks @mrlequoctuan for this project.

It is a popular package available on well-known distros such as Ubuntu, Arch, Debian, Fedora, openSUSE, ...

Vietnamese users will love it. Please help us to bring it to ClearLinux. Thank you!

**Comment by fenrus75** [comment]
hmm does not seem that this has had a release since 2012... are you sure
this is the right homepage for it?

**Comment by Maxvien** [comment]
Hello @fenrus75 

It's ibus-unikey's new home page. The old home page is: https://code.google.com/archive/p/ibus-unikey/downloads

The latest version is 0.6.1 (Feb 29, 2012) on both sites.

You can get more information here:
- https://packages.ubuntu.com/source/eoan/ibus-unikey
- https://www.archlinux.org/packages/community/x86_64/ibus-unikey/

**Comment by lebensterben** [comment]
@Maxvien @fenrus75 
It's reported in #760 that `ibus` cannot input any Chinese characters. I'm wondering whether that will also affect input method for other languages too.

**Comment by Maxvien** [comment]
Hello @lebensterben,

**ibus-unikey** uses [Unikey Engine](https://www.unikey.org/en/linux.html) instead of Pinyin Engine. It may work.

**Comment by amygilliam1** [comment]
@ahkok

**Comment by AnwarShah** [comment]
> @Maxvien @fenrus75
> It's reported in #760 that `ibus` cannot input any Chinese characters. I'm wondering whether that will also affect input method for other languages too.

Yes, I confirm that bengali too can't be input with [ibus-avro](https://github.com/sarim/ibus-avro)
