### ISSUE TITLE
RStudio Server

### ISSUE THREAD

**Issue by znmeb** [clearlinux/distribution#814]
I am trying to migrate all of my workflow to containers, and one package that's missing from Clear Linux is RStudio Server.

**Comment by amygilliam1** [comment]
We will explore the requirements on this request.

**Comment by znmeb** [comment]
If I recall correctly it's a one-line change to a CMAKE command and a few more dependencies relative to the desktop version.

**Comment by lebensterben** [comment]
>If I recall correctly it's a one-line change to a CMAKE command and a few more dependencies relative to the desktop version.

@znmeb And they need to add stateless configuration for setting up the server.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chivakker** [comment]
rstudio server is available from Clear Linux version 29760
