### ISSUE TITLE
Failed to build kernel RPM package 

### ISSUE THREAD

**Issue by mumu209** [clearlinux/distribution#815]
Tried to build a custom kernel(upstream 4.19.46 with no changes), building process terminated due to following error:

.......
Total size: 80 M
Total download size: 74 M
Installed size: 253 M
Downloading Packages:

Error: Error downloading packages:
Cannot download Packages/linux-firmware-20180000-105.x86_64.rpm: All mirrors were tried

make: *** […/common/Makefile.common:95: build] Error 30

I tried to build linux-firmware package separately, seems no issues found:
lin@lin-clear ~/workspace/kernel/clearlinux/packages/linux-firmware/results $ ll

total 336592
-rw-rw-r-- 1 lin lin 14341 May 29 08:20 build.log
-rw-r–r-- 1 lin lin 179591164 May 29 08:19 linux-firmware-20180000-105.src.rpm
-rw-r–r-- 2 lin lin 77430960 May 29 08:20 linux-firmware-20180000-105.x86_64.rpm
-rw-r–r-- 2 lin lin 5844 May 29 08:20 linux-firmware-abi-20180000-105.x86_64.rpm
-rw-r–r-- 2 lin lin 62541 May 29 08:20 linux-firmware-doc-20180000-105.x86_64.rpm
-rw-r–r-- 2 lin lin 13784465 May 29 08:20 linux-firmware-extras-20180000-105.x86_64.rpm
-rw-r–r-- 2 lin lin 73517779 May 29 08:20 linux-firmware-wifi-20180000-105.x86_64.rpm
-rw-rw-r-- 1 lin lin 102616 May 29 08:20 root.log
-rw-rw-r-- 1 lin lin 958 May 29 08:19 srpm-build.log
-rw-rw-r-- 1 lin lin 120669 May 29 08:19 srpm-root.log
-rw-rw-r-- 1 lin lin 1218 May 29 08:20 state.log

**Comment by miguelinux** [comment]
> Tried to build a custom kernel(upstream 4.19.46 with no changes), building process terminated due to following error:
> 

What is the procedure that you followed?

**Comment by mumu209** [comment]
This link:
https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-development



Br,


Lin 


| |
solo
邮箱：mumu209@163.com
|

Signature is customized by Netease Mail Master

On 05/29/2019 22:49, Miguel Bernal Marin wrote:
> Tried to build a custom kernel(upstream 4.19.46 with no changes), building process terminated due to following error:
>

What is the procedure that you followed?

**Comment by puneetse** [comment]
@mumu209 I noticed you cross posted this on the community forums. I'm putting the link here for reference and updates. https://community.clearlinux.org/t/failed-to-build-kernel-rpm/578/.

**Comment by miguelinux** [comment]
As this is a Network issue not related to CL, I'll close this issue.
