### ISSUE TITLE
Gnome desktop does not remember audio mute after restart

### ISSUE THREAD

**Issue by yerbestpal** [clearlinux/distribution#819]
Not a huge issue, but after a restart, Gnome will not remember if your audio was muted.
Current OS version: 29660

**Comment by skewty** [comment]
It would be nice if this investigation also checked into saving and restoring the currently set volume level after restart.

**Comment by puneetse** [comment]
Closing this as duplicate of https://github.com/clearlinux/distribution/issues/696
