### ISSUE TITLE
[Gnome3] Wrong default application for folders

### ISSUE THREAD

**Issue by RobertBuhren** [clearlinux/distribution#820]
Opening a folder from the gnome search opens the gnome disk usage analyzer for the respective folder instead of the file browser: 

```
robert@clear ~ $ xdg-mime query default inode/directory
org.gnome.baobab.desktop
```
Expected behavior:  Open the corresponding folder in nautilus instead.

**Comment by lebensterben** [comment]
This happened to me before but somehow it's resolved.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mrkz** [comment]
@RobertBuhren This should be fixed once release **30420** is available

**Comment by mrkz** [comment]
For the GNOME session this has been fixed, notice however that we still lack a generic "default application list" as a common ground for all Desktop Environments (i.e: `mimeapps.list` file, which xdg-mime consumes).

Closed since this issue since this fix is available in release **30440**
