### ISSUE TITLE
- Package: arp-scan in clear linux -

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/distribution#825]
Package: arp-scan

arp scanning and fingerprinting tool
arp-scan is a command-line tool that uses the ARP protocol to discover and fingerprint IP hosts on the local network. It is available for Linux and BSD under the GPL licence

(https://packages.debian.org/stretch/admin/arp-scan)

**Comment by ahkok** [comment]
this will be part of the `network-security-monitoring` bundle  - where nmap is as well.
