### ISSUE TITLE
Black dot symbol is not allow in user names

### ISSUE THREAD

**Issue by ttzeng** [clearlinux/distribution#829]
The username part of most corporate email addresses have black dot symbol "firstname.lastname@domain", but it seems Clear Linux does not allow create user accounts with black dot symbol in the user name.

Output in Clear Linux:
root@30f1356adb86 / # useradd -m tonny.tzeng
useradd: invalid user name 'tonny.tzeng'

Output in Ubuntu 16.04:
root@efb7de121faf:/# useradd -m tonny.tzeng
root@efb7de121faf:/# 

Since Google Cloud Platform uses the username part of the SSH public key to create an user account, users won't be able to login to the VMs on GCP if their usernames have black dot symbol.

**Comment by ahkok** [comment]
```
CAVEATS
       You may not add a user to a NIS or LDAP group. This must be performed on the corresponding server.

       Similarly, if the username already exists in an external user database such as NIS or LDAP, useradd
       will deny the user account creation request.

       Usernames must start with a lower case letter or an underscore, followed by lower case letters,
       digits, underscores, or dashes. They can end with a dollar sign. In regular expression terms:
       [a-z_][a-z0-9_-]*[$]?

       Usernames may only be up to 32 characters long.
```

**Comment by ahkok** [comment]
In other words: Ubuntu appears to be using a non-standard allowed character list.

**Comment by ahkok** [comment]
Confirmed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=604242

**Comment by ahkok** [comment]
We *could* do this, but there's a long tail of "but" problems that follow this problem if we did this. We're currently looking into it.

**Comment by ahkok** [comment]
This is pending release.

**Comment by mdhorn** [comment]
@ahkok  Has this landed in a released build?

**Comment by ahkok** [comment]
Yes, this is merged and active.
