### ISSUE TITLE
Download problems with "texlive"

### ISSUE THREAD

**Issue by znmeb** [clearlinux/distribution#832]
I keep running into this:

```
Error: Curl - Communicating with server timed out - 'https://cdn.download.clearlinux.org/update/29680/pack-texlive-from-0.tar'
```

I'm trying to do a `swupd bundle-add os-clr-on-clr`, which is huge. But this seems to be the only file that's giving it grief. Is it just the size of the file, or is there something wrong on the servers?

P.S.: I just downloaded it with Firefox - it's only 1 GB and it didn't take very long to download. When the `bundle-add` finishes I'll take another shot at it.

**Comment by lebensterben** [comment]
>I keep running into this: ...

@znmeb `texlive` actually suggests the user to built it from the source even though many distribution has it packaged.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by znmeb** [comment]
Yeah - e.g., TinyTeX https://github.com/yihui/tinytex

**Comment by ahkok** [comment]
You can add this parameter to `swupd bundle-add`:
` -W, --max-parallel-downloads=[n] Set the maximum number of parallel downloads`
It should reduce download issues on extremely slow networks.

@otaviobp whatever changes were made a while back, they are still not effective in preventing network download errors.
