### ISSUE TITLE
Errors while Installing ClearLinux [VirtualBox]

### ISSUE THREAD

**Issue by rbharathkumar** [clearlinux/distribution#834]
Dear Team,
I have been using ClearLinux for some time and have raised a few bugs as well which have been worked upon and closed by the Devs. Thank you very much for that.

Today I am facing yet another set of basic install issues.
1. Today I tried installing ClearLinux from scratch inside a VM.
2. The Live Desktop - clear-29690-live-desktop.iso is not booting at all and goes into a black screen. So I get into a TTY (Alt-F2) logged in using the credentials. The command which is provided over there sudo -E clr-installer gives out an error stating /etc/clr-installer.lock is unable to lock since no space is available. When I tried df -h, it showed that the root (/) has only 512 MB space and all of it has been filled up. Also the filesystem was shown up as none.
3. I had tried installer - clear-29690-installer.iso. On boot up, i logged in as root, set the password and invoked the clr-installer. Installation completed as expected. I had tried the installation twice. once with the bare basics and once with the desktop bundle included.
4. On both instances on reboot, I ended up on a black screen. gdm just would not start even with the systemctl command.
5. The journalctl-b shows several errors especially with the thermal_daemon.
6. So installed lightdm, enabled it and started it. 
7. On start, I was able to login only using the Flashback session, none of the other sessions - gnome on xorg, wayland, weston would work. They would either hang or go back to the same login page.

I hope the details are sufficient to resolve the issue. I would love to see ClearLinux succeed and that is possible when the basics - installation and default setup are properly sorted out.
thank you,

**Comment by ahkok** [comment]
>  Today I tried installing ClearLinux from scratch inside a VM.

Missing information: what sort of VM?

**Comment by rbharathkumar** [comment]
Hi @ahkok , thank you for your response.
I used VirtualBox 6.0.8 installed on an Arch Based System. All updated to date.
I had enabled EFI as mentioned in the instructions.
Please let me know if you need any further information.

**Comment by bwarden** [comment]
We've updated our [guide for installing Clear Linux under VirtualBox](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer).

**Comment by rbharathkumar** [comment]
Thank you very much for your resposne @bwarden 
The process was very well documented. Great Work (y)

Unfortunately the issue still persists.
As per the instructions,
1. Installed the base OS with no extra modules selected.
2. On reboot, the system requested a reboot for a kernel update. As documented, I performed a reboot.
3. After reboot, verified that it was indeed the LTS kernel that was installed.
4. Installed the vbox guest additions as documented and validated using the lsmod command. REbooted and switched to VBoxSVGA.
5. I then installed the desktop-autostart and rebooted again.
6. On reboot, it went to a black screen. Even pressing Alt+F2 did not move to the TTY as it normally does.

So just the base OS and desktop-autostart bundles installed. Not sure where the issue is. Please help.

P.S.
Is there a reason why the installer has been renamed as server.iso ? 
Installer was very apt and self-explanatory. 
No issues anyways since it is properly documented.

**Comment by AntonioMeireles** [comment]
@rbharathkumar @bwarden 

Hi! 

FWIW i got a bit ago, on my [ClearLinux vagrant tooling](https://github.com/AntonioMeireles/ClearLinux-packer), a virtualized fully behaving desktopish ClearLinux setup over VirtualBox (see/follow [here](https://github.com/AntonioMeireles/ClearLinux-packer#what-else-do-you-need-to-know)).
Things of note in no particular order: 
- on VBox side, currently, the video driver really needs to be `vmsvga`.
- for Wayland (the default) you really need also to have 3D enabled along the clipboard sharing and drag and drop ...

see please https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/Vagrantfile.template.rb#L66-L69 for the full relevant flag set on VBox side. 
 
OTOH AFAICT the distro bundled `install-vbox-lga` is not doing all that is expected (specially for a desktop install) on the guest side so i created a simplified guest-side installer (vd https://github.com/AntonioMeireles/ClearLinux-packer/blob/master/vboxguestsetup.sh) that just *seems* to work out of the box. 

Hope this helps :-)

**Comment by rbharathkumar** [comment]
Thank you for your response - @AntonioMeireles 
I already have the below options enabled.

Copy Paste: Bidirectional
Drag and Drop: Bidirectional
Chipset: ICH9
Extended Features: Enable EFI
Processor: 2
PAE Enabled
Have all options enabled on the Acceleration Tab. (Forgot what they were though)
Display - Video Memory - 128 MB
Driver: VBoxSVGA
3D Acceleration Enabled

Maybe I will try toggling between the three options and see.
Will even try your script. 
Losing a lot of data testing this out though :(

**Comment by bwarden** [comment]
> Processor: 2

Hmmm, this might be related to #807

**Comment by rbharathkumar** [comment]
voila...You were indeed spot on..
Setting the Processor Count to 1 did indeed allow me to login.

Also I noticed from that Issue that  I remember seeing some issue with the Power setting and the thermal daemon. Also makes sense that I was able to login with lightdm but again only into the Classic Gnome session and not the Gnome 3 session. I believe that the issue is not limited to GDM but to some other underlying bundle - my guess something to do with power or thermal daemon.

**Comment by jurobystricky** [comment]
> We've updated our [guide for installing Clear Linux under VirtualBox](https://clearlinux.org/documentation/clear-linux/get-started/virtual-machine-install/virtualbox-cl-installer).

Maybe this (one CPU requirement) should be mentioned under the section "Troubleshooting" as well. At least until this is resolved.

**Comment by jurobystricky** [comment]
One more observation:
Selecting the display display controller VMSVGA instead of VBoxSVGA (as recommended) seems to fix the problem: I was able to boot with multiple CPUs.

**Comment by 11h10** [comment]
For multiple CPU see #749. It works well with 29870 release

**Comment by rbharathkumar** [comment]
Confirmed as working on Release 29890.
Processor: 2
Driver: VBoxVGA.

Thank you for your efforts.

**Comment by mrkz** [comment]
Fixed with https://github.com/clearlinux-pkgs/mesa/commit/9117e5fc917fa1af92ef34118d1df7a08172438d as well as #749
