### ISSUE TITLE
Occasionally freezes, requiring hard shutdown

### ISSUE THREAD

**Issue by unpragmatic** [clearlinux/distribution#835]
Occasionally freezes, and requires me to manually shutdown the system.

Where can I find some relevant logs that would allow me to debug this issue?

**Comment by ahkok** [comment]
`journalctl` is the only recourse, of course, in case of a freeze, it's unlikely that any useful logs are retained. The alternatives are really only to hook up a serial console.

**Comment by puneetse** [comment]
@unpragmatic I'm closing this issue for now since it seems limited and we haven't seen any new data. If you have more information, please feel free to reopen!
