### ISSUE TITLE
Bug on network manager

### ISSUE THREAD

**Issue by WIZARD-WIZ** [clearlinux/distribution#836]
I installed Clear Linux OS today on my laptop and then I cannot use my wi-fi. It says no wifi adapter found. I had the same problem before on ubuntu but I ran this command: "sudo apt-get install - - reinstall bcmwl-kernel-source" and it solved the problem. I cannot do the same on Clear Linux. Please help me asap!

**Comment by lebensterben** [comment]
>I installed Clear Linux OS today on my laptop and then I cannot use my wi-fi. It says no wifi adapter found. I had the same problem before on ubuntu but I ran this command: "sudo apt-get install - - reinstall bcmwl-kernel-source" and it solved the problem. I cannot do the same on Clear Linux. Please help me asap! 

@WIZARD-WIZ I'm away from the computer so I can only briefly describe how to solve this.

'bcmwl' stands for broadcom wireless driver, and try to use either 'bcmwl' or 'broadcom wireless driver' as a key word combined with another keyword such as 'rpm' or 'fedora'.

When you find such drivers in 'rpm' format, you may see multiple of them corresponds to different architecture. If your system is 'x86_64', you may find the right 'rpm' with 'x86_64', 'amd64', or 'x64'.

Extract the 'rpm' and copy its content to your system with 'sudo' privilege. This can be done with 'cpio' or manually.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WIZARD-WIZ** [comment]
I think I should have known more about Linux, repositories and dependencies before installing Clear Linux

**Comment by bkdwt** [comment]
test
