### ISSUE TITLE
Add the Nim programming language

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#840]
Nim is a 

>  a statically typed compiled systems programming language. It combines successful concepts from mature languages like Python, Ada and Modula. 

and an upcoming data science language, which I couldn't find with the software updater that comes in clearlinux. 

- Please add a bundle for it.

Thank you

**Comment by ahkok** [comment]
Trying...

It's ... again ... not the easiest software to package. Why is it so hard for scientists to use `autoscan`?

**Comment by ahkok** [comment]
Done, will be available in 1-2 days.

**Comment by ahkok** [comment]
Bundle `nim`

**Comment by lf-araujo** [comment]
Thanks @ahkok, 

This has been very useful, however they have recently updated to 0.20, could you update the bundle too when you get some time?

All the best,
lf
