### ISSUE TITLE
hwinfo requires dmidecode in the performance-tools bundle

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#843]
python-hwinfo is in the performance-tools bundle. 
python-hwinfo has a dependency on dmidecode.
dmidecode is not made available through the performance-tools bundle so hwinfo does not work.

Please add  dmidecode to the performance-tools bundle.

**Comment by miguelinux** [comment]
it is used in `hwinfo/tools/inspector.py`

**Comment by miguelinux** [comment]
meanwhile,  I added dmidecode to python-hwinfo.

**Comment by ahkok** [comment]
https://github.com/rdobson/python-hwinfo

The project is unmaintained and not accepting patches. We should consider removing it from clearlinux.

@ganeshmaharaj

**Comment by bryteise** [comment]
Dropped python-hwinfo
