### ISSUE TITLE
Package Request: Winetricks

### ISSUE THREAD

**Issue by yerbestpal** [clearlinux/distribution#846]
[Winetricks](https://github.com/Winetricks/winetricks) is a useful package for installing packages that may be necessary for certain Windows applications to run under Wine.

**Comment by ahkok** [comment]
This falls unfortunately in the category of software that we can't currently ship.

Note that all it is is a shell script that you could download directly from  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
