### ISSUE TITLE
why no mention about GNU ?

### ISSUE THREAD

**Issue by catastrop** [clearlinux/distribution#847]
clear Linux website doesn't mention anything about **GNU**. 
Why?

**Comment by catastrop** [comment]
closed? why?

**Comment by ahkok** [comment]
The website serves to help users understand Clear Linux and use it. Many critical parts of Clear Linux are not mentioned.

We're not interested either in a potentially heated political debate with people who want to label everything GNU. This doesn't help make Clear Linux better, and just distracts.
