### ISSUE TITLE
Flatpak language (spelling) support.

### ISSUE THREAD

**Issue by RobertBuhren** [clearlinux/distribution#848]
When installing the flatpak for LibreOffice only spellchecking for the English is available.

Do get additional languages a user has to manually execute: 

```
flatpak install --reinstall flathub org.freedesktop.Platform.Locale/x86_64/18.08
```
Imho this should be easier / automated. 
Regards,

Robert

**Comment by ahkok** [comment]
Flatpak software is not maintained by the Clear Linux team. It's features and/or bugs are not something we can help with.
