### ISSUE TITLE
why google analytics?

### ISSUE THREAD

**Issue by catastrop** [clearlinux/distribution#849]
Why clear Linux's website uses *google analytics*?

It should use **free software** like *Matomo* for analytics.

**Comment by biapalmeiro** [comment]
@catastrop I’d love to have a conversation about this. Actually, I’m looking exactly for these alternatives. Would you mind to open a topic about it in our community.clearlinux.org? So, we can continue the discussion. Thanks!

**Comment by catastrop** [comment]
alternative that i know about are

**Fathom** and **Matomo**

Their source code is available on Github.

Fathom is very cool. It uses Golang & Preact.
