### ISSUE TITLE
docs: verify integrity of image hash sums

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#85]
https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install#verify-the-integrity-of-the-clear-linux-image documents how to verify the integrity of the downloaded image file. What's missing is documentation on how to verify the integrity of the SHA512SUMS file.

The files are signed, so presumably some gpg invocation will do that. But what key needs to be trusted?

**Comment by phmccarty** [comment]
I'm not sure where the actual documentation exists for this on clearlinux.org, but this blog post describes how to verify the SHA512SUMS file:

https://clearlinux.org/blogs/security-software-update-clear-linux-os-intel-architecture

```
$ openssl smime -verify -in [image]-SHA512SUMS.sig -inform der -content sha512sum.out -CAfile ClearLinuxRoot.pem -out /dev/null
```

**Comment by pohly** [comment]
Patrick McCarty <notifications@github.com> writes:
> I'm not sure where the actual documentation exists for this on
> clearlinux.org,

The right place to document this IMHO is the link I had in my initial
description. That's also what the download directory links to.

> but this blog post describes how to verify the SHA512SUMS file:
>
> https://clearlinux.org/blogs/security-software-update-clear-linux-os-intel-architecture

Thanks, that does indeed explain it.

**Comment by phmccarty** [comment]
> The right place to document this IMHO is the link I had in my initial description. That's also what the download directory links to.

I agree. I will prepare a PR to update the docs accordingly.

**Comment by phmccarty** [comment]
> Am I the first one who is paranoid enough to try this, or is it related to my version of OpenSSL? ;-}

I see the verification fail with openssl 1.1.0h on Arch Linux, and it succeeds with openssl 1.0.2o on Clear Linux. My guess is that it's an incompatibility between 1.0.x and 1.1.x :-(

**Comment by ahkok** [comment]
Why can't `sha512sum` be used instead? That should hopefully not be affected by openssl versions.

**Comment by pohly** [comment]
`sha512sum` does get used to verify the integrity of the image. But to prevent attacks, one first has to verify the integrity of the checksum file. Otherwise an attacker could modify the image and then update the checksum file accordingly.

I'm not sure how important it is to have these signatures. But apparently they were considered important enough to set up something, so probably it is worth fixing the mechanism.

**Comment by pohly** [comment]
The `sha512sum -c` command from https://clearlinux.org/documentation/clear-linux/get-started/bare-metal-install#verify-the-integrity-of-the-clear-linux-image also no longer works because the SHA512SUMS from release 23290 (current latest) contains an absolute path. It used to contain just the file name:
```
$ sha512sum -c clear-$version-kvm.img.xz-SHA512SUMS
sha512sum: /home/releases/www/23290/clear/clear-23290-kvm.img.xz: No such file or directory
/home/releases/www/23290/clear/clear-23290-kvm.img.xz: FAILED open or read
sha512sum: WARNING: 1 listed file could not be read
```

**Comment by alexjch** [comment]
A change to speed up the build caused the inclusion of the file path. We fixed the issue in the tree and this will be working as documented this afternoon after the late morning build goes out (any valid release version >= 23310 will work as documented)

**Comment by iphutch** [comment]
Closing as docs PR was merged

**Comment by mcastelino** [comment]
@phmccarty @iphutch I see this issue happening again with clear-29690-cloud.img.xz

/cc @pohly

**Comment by phmccarty** [comment]
@mcastelino The verification of `clear-29690-cloud.img.xz-SHA512SUMS.sig` passes for me on Clear. I see from the referenced issue that your environment is Ubuntu 18.04, so that may the reason for verification failure, due to the (likely) different versions of openssl in use.
