### ISSUE TITLE
add plata-theme

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#850]
I would highly recommend to add [plata-theme](https://gitlab.com/tista500/plata-theme) its the latest Material design theme from the creator of the well known [adapta-gtk-theme](https://github.com/adapta-project/adapta-gtk-theme). This in combination of [paper-icon-theme](https://github.com/snwh/paper-icon-theme) or [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) would be awesome.

_Originally posted by @curantes in https://github.com/clearlinux/distribution/issues/298#issuecomment-451318840_

**Comment by Jacalz** [comment]
I would love to see this too! paper-icon-theme is already in the repo but it would be great to get papirus-icon-theme along with Plata :+1:

**Comment by mrkz** [comment]
There's a contribution being added (thanks @curantes :tada: ) at the moment.

More details can be found in the clearlinux mailing list:
https://lists.clearlinux.org/hyperkitty/list/dev@lists.clearlinux.org/thread/AIUW2SKUMRKDSQJI23RARHBRARV3QYAB/

**Comment by mrkz** [comment]
This has been integrated and it's available since release **31110**

Thanks @curantes for the package submision :1st_place_medal:
