### ISSUE TITLE
kmod not patched to look in /usr/lib

### ISSUE THREAD

**Issue by pdxjohnny** [clearlinux/distribution#851]
Hi all @evil-brain and found yesterday that there is a blacklist in `/usr/lib/modprobe.d` however it looks like kmod never got patched to have modprobe.d moved from `/lib` to `/usr/lib`

strace:

```
stat("/etc/modprobe.d", 0x7ffeb5ef0078) = -1 ENOENT (No such file or directory)
stat("/run/modprobe.d", 0x7ffeb5ef0078) = -1 ENOENT (No such file or directory)
stat("/lib/modprobe.d", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
```

https://github.com/clearlinux-pkgs/kmod

**Comment by mdhorn** [comment]
That should be a symlink:
```
$ ls -l /lib
lrwxrwxrwx 1 root root 7 Jan 12  2017 /lib -> usr/lib
```
I'm pretty sure that should work, no?

**Comment by ahkok** [comment]
```
$ cd /lib/modprobe.d
/lib/modprobe.d $ pwd -P
/usr/lib/modprobe.d
```

**Comment by pdxjohnny** [comment]
Ah yes, then I guess what is the function of the blacklist? It seems that /lib/modprobe.d/tpm-blacklist.conf isn't being respected, tpm_tis is getting loaded anyways. Which I want it to, but doesn't make sense that it's getting auto-loaded if it's in the blacklist
