### ISSUE TITLE
Request to support remote decrypting through ssh of fully encrypted drives

### ISSUE THREAD

**Issue by eadamsintel** [clearlinux/distribution#855]
If you do full disk encryption with Clear Linux you have to physically be present at your computer to unlock it. This is a problem if you want to remotely reboot/power on a system as you won't have a way to unlock it unless you setup an expensive KVM over IP solution or possibly redirect output over serial port to another computer that you can ssh in. Many modern computers don't have rs-323 ports. There are guides on the Internet how to set this up using a dropbear ssh server running in initramfs but it is tricky to setup and doesn't seem like it would survive a swupd update to a newer kernel. It would be a really useful feature if Clear Linux could easily support this through a bundle-add and some configuration file in /etc for the pre-boot ssh keys. Even better would be to share the same key between the pre-boot ssh session and post-boot after decryption ssh session if a different ssh server has to be used.

**Comment by ahkok** [comment]
This is so specialized that it doesn't really fit well into the base OS as a deployable package: almost everything you are asking for is custom (initrd) or configuration (keys, scripts etc.).

**Comment by eadamsintel** [comment]
This is a problem I am trying to figure out how to solve for my Clear Linux server at home and a $400 kvm is the best solution I can come up with.  There are guides for Ubuntu on how to setup a dropbear ssh server in initramfs but they are complex and don't apply for how Clear Linux boot works.  I thought this might be a cool feature for Clear Linux if it were possible to add a pre-boot ssh server bundle that did run in initrd that would allow remote unlocking of encrypted drives. Unfortunately my system does not have an rs-232 port which would allow me to use a 2nd computer to get to the serial console to unlock nor does it have any vPro software that could potentially allow me a way to do this as well.  I am also considering a raspberry pi with ssh capabilities that I think I can use usb gadget mode to send keystrokes to unlock or just not fully encrypt my drive.   I've asked multiple experts on Clear Linux on how to solve this problem and so far don't have any real solutions yet.

**Comment by puneetse** [comment]
> I am also considering a raspberry pi with ssh capabilities

FWIW enterprise solutions like iLO and DRAC essentially do this with a separate network connected daughter board. 

It would be complicated (what fun isn't?) but maybe you could do something where the boot partition is remote altogether, for example a PXE/iPXE server: 
* authentication happens between you and the PXE server to start (instead of bootloader being encrypted)
* the PXE server sends a custom boot image with key
* the boot image decrypts the system disk and boots

**Comment by ahkok** [comment]
Believe it or not but I think a BMC or smarter IME would be the right way to do this :)

**Comment by puneetse** [comment]
@eadamsintel I'm closing this issue because I don't think it is in scope for Clear Linux. Plus, I think you already found a solution :)
