### ISSUE TITLE
Rstudio is broken in todays update

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#856]
After the update today, rstudio greets me with:

![image](https://user-images.githubusercontent.com/10139950/58993912-46f0bd00-87c5-11e9-9d1a-53fcfeaa4c01.png)

My current system state is:

![image](https://user-images.githubusercontent.com/10139950/58993961-6d165d00-87c5-11e9-9856-6ac50b5f7612.png)

**Comment by lebensterben** [comment]
This happens to me too. This is severe.

**Comment by znmeb** [comment]
Same here. Also, see https://github.com/clearlinux/distribution/issues/814#issuecomment-498870927. RStudio Server is indeed in this release, but without documentation on how to configure and enable it, it's useless.

**Comment by lebensterben** [comment]
> Same here. Also, see [#814 (comment)](https://github.com/clearlinux/distribution/issues/814#issuecomment-498870927). RStudio Server is indeed in this release, but without documentation on how to configure and enable it, it's useless.

Have you tried the instruction from the `INSTALL` file of its source?

**Comment by znmeb** [comment]
```
$ locate rstudio-server
/usr/lib64/R/rstudio/bin/rstudio-server
/usr/lib64/R/rstudio/extras/systemd/rstudio-server.service
/usr/lib64/R/rstudio/extras/upstart/rstudio-server.conf
$ sudo systemctl enable --now rstudio-server.service
Failed to enable unit: Unit file rstudio-server.service does not exist.
```

**Comment by phmccarty** [comment]
Try copying `rstudio-server.service` first to `/etc/systemd/system` first, since it is installed in a non-standard location apparently.

**Comment by znmeb** [comment]
That helped - the service is started now and listening on localhost:8787 like it's supposed to. But it's stuck at the sign-in page `http://localhost:8787/auth-sign-in` and the rest of the screen in blank. Could this be upstream? RStudio Desktop and Server share a *lot* of code.

**Comment by thiagomacieira** [comment]
@chivakker you mde the last update I think.

**Comment by lf-araujo** [comment]
Still affected after update today:

![image](https://user-images.githubusercontent.com/10139950/59067725-b67bb080-8888-11e9-9495-76213cc7979a.png)

**Comment by ahkok** [comment]
There has not been a fix yet.

**Comment by chivakker** [comment]
I'm looking into this now

**Comment by chivakker** [comment]
An update after looking into this:

Starting from the top:  

`$ LD_LIBRARY_PATH=/usr/lib64/R/lib rstudio`

Segmentation fault occurs when closing rstudio, this may be an upstream issue when making Server and Desktop coexist; needs further investagion

Current packaging doesn't include any www files necessary for this to operate, some analysis has to be made on how this is going to be packaged in Clear Linux.

**Comment by znmeb** [comment]
It's been a long time since I rand both RStudio Desktop and RStudio Server on the same machine but I know it works at least on the distros RStudio supports for the server.

It's been even longer since I built them from source.

**Comment by chivakker** [comment]
We're going to have the regular R-rstudio (Desktop) and we'll introduce a R-rstudio-server (Server) on the following releases.  Trying to make it happen in the next release.

**Comment by chivakker** [comment]
R-rstudio-server will be available starring in version 29880.
