### ISSUE TITLE
Add glxgears and glxinfo into x11-tools bundle

### ISSUE THREAD

**Issue by mrkz** [clearlinux/distribution#857]
Having glxgears, glxinfo and other x11 tools (maybe xrand and friends too) is desirable without having to rely on a full desktop.

**Comment by bwarden** [comment]
https://github.com/clearlinux/clr-bundles/commit/b428941dda05c994280dcbe8be84c92ddc9f89ca

**Comment by mrkz** [comment]
@bwarden thanks for the pointer, I'll should ask for having `glxgears` and `glxinfo` in instead then.

**Comment by mrkz** [comment]
Having those installed in the `x11-tools` bundle will make it the bundle to grow horribly in content size, I'll look at adding them into 'lib-opengl' bundle instead (which already holds mesa)

**Comment by mrkz** [comment]
Additionally, we will stop providing `glxgears` from the distribution.

**Comment by mrkz** [comment]
addressed in https://github.com/clearlinux/clr-bundles/commit/9d328edba491fae35002338a249040759ea3caaf

**Comment by AjitDingankar** [comment]
Sorry about a newbie question, but I just added the bundle `os-test-phoronix-desktop` because I already had `lib-opengl` yet `glxinfo`  was not found. 

I suspect my installation is old but don't know how to map the version number from `swupd info` into a release date.
