### ISSUE TITLE
The runuser command doesn't work

### ISSUE THREAD

**Issue by 93049949** [clearlinux/distribution#859]
useradd test -s /sbin/nologin -M
runuser -u test c "whoami"
runuser: failed to user credentials: Failure setting user credentials

runuser - test -s /bin/bash -c whoami
runuser: failed to user credentials: Failure setting user credentials

no problem on other linux distribution

**Comment by ahkok** [comment]
Does `sudo` not work for you?

**Comment by 93049949** [comment]
sudo doesn't work too. 
sjia@clr-5f56e4945ded4001a16de00eda6139e3 /etc $ sudo runuser -s /bin/bash - test -c "whoami"
Password:
runuser: failed to user credentials: Failure setting user credentials

**Comment by ahkok** [comment]
haha no, that's not what I mean.

`sudo -u test $command` - there's no need to even use the `runuser` command together with it.

**Comment by ahkok** [comment]
Fixed in `dist-pam-configs-1-28`. WIll be available in 1-2 days.
