### ISSUE TITLE
ISO images are very big after decompressing

### ISSUE THREAD

**Issue by baryluk** [clearlinux/distribution#86]
```text
-rw-r--r--  1 baryluk baryluk 1789902848 cze  6 22:26 clear-22830-installer.iso
-rw-r--r--  1 baryluk baryluk  317560232 cze  6 16:08 clear-22830-installer.iso.xz
```

Sorry, but that doesn't make any sense.

It appears to me that there is a lot of very spare data or simply zeros. Anyhow, it just makes it unnecessarily big, cluttering temporary storage on disk, taking time to write to USB device or to DVD disc (and forget about putting it on CD-R), or verifying checksums.

From what I can see, it is probably `EFI/efiboot.img` or `images/rootfs.img` being used as file system images, with base image size way bigger than needed, instead of simply storing actual files in iso9660 file system! One option would be to figure out how big `efiboot.img` and `rootfs.img` need to be and actually create them (`mkfs`), using information about sizes of files, not some arbitrary constant sizes in some script.

**Comment by alexjch** [comment]
This image was created mainly for virtualization platforms for any other use case the recommendation is to transfer clear-xxx-installer.img to USB stick. We would like to go back and improve this image, but there are other priorities on our list.

As far as size of the image a quick comparison:

Clear 22840: 964M
Ubuntu 18: 1.8G
Fedora 28: 1.7G

Additionally checksum verification should be performed before decompression as explained in this [post](https://clearlinux.org/documentation/clear-linux/guides/maintenance/download-verify-uncompress-linux)

```
time shasum -a512 ./clear-22840-installer.iso.xz | diff clear-22840-installer.iso.xz-SHA512SUMS -

real	0m1.578s
user	0m1.466s
sys	0m0.109s
```
1.5 seconds is not too bad.
