### ISSUE TITLE
RFE: please consider packaging `cdrtools` and have it available as a pundle

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#860]
it's  oldish but *still* handy. FWIW my actual use case is that it brings `mkisofs` which is an hard runtime dep of the [`terraform-provider-libvirt`](https://github.com/dmacvicar/terraform-provider-libvirt) terraform plugin. 

Thanks in Advance!

**Comment by fenrus75** [comment]
is there any chance it supports xorrisofs ?
openstack and many others support that and we already have that.
cdrtools has lots of fun on license noise that comes with it (which causes
many other distros to use something else)

**Comment by AntonioMeireles** [comment]
> is there any chance it supports xorrisofs ? openstack and many others support that and we already have that. cdrtools has lots of fun on license noise that comes with it (which causes many other distros to use something else)
> […](#)

thanks for the fast replay! 

actually `xorriso` would do pretty well with a few tweaks :-) ... 
- would need to be pundled. if `swupd search-file` is right it is only available now at in the `clr-installer`, `cloud-control`, `openstack-common` and `os-clr-on-clr`  bundles - all far from slim.
- finally it would also need a few packaging tweaks ...
  according to its man page and quoting *`xorrisofs is actually a command mode of program xorriso, which gets entered either by xorriso command "-as mkisofs" or by starting the program by one of the names "xorrisofs", "mkisofs", "genisoimage", or "genisofs".`* so a few extra symlinks would be needed in order to symlink `mkisofs` (and to cover all angles also `genisoimage` and `genisofs`) to existing `/usr/bin/xorriso`. 

and that AFAICT would do it!

Thanks in advance!

**Comment by ahkok** [comment]
You could make the symlink as `/usr/local/bin/mkisofs` to get everything you need, then.

**Comment by AntonioMeireles** [comment]
Thanks all for getting this sorted. (just tried it in `29820` 👍 ) 

have a great weekend!
