### ISSUE TITLE
kernel-native: enable PMC_CORE driver to enable more granular idle system analysis/debug

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#862]
kernel-native, at least, _should_ enable INTEL_PMC_CORE driver. It exposes valuable information through debugfs for analyzing and debugging platform suspend, resume, and (particularly) idle. I'll submit a patch tomorrow morning.

PS: I'm reasonably certain Google enables it, in production, on Chrome OS. (Don't have a Chrome Book handy or I'd verify).

**Comment by thac0** [comment]
Colleagues: please assign this to me ( @thac0 ). Thanks!

**Comment by thac0** [comment]
Enabled in Clear Linux 29850 .

**Comment by marc-hb** [comment]
Indeed https://chromium-review.googlesource.com/q/intel_pmc_core
