### ISSUE TITLE
Update README-IMAGES.html in https://download.clearlinux.org/image

### ISSUE THREAD

**Issue by tpleavitt** [clearlinux/distribution#865]
The https://download.clearlinux.org/image/README-IMAGES.html is out of date and needs to be updated to reflect the current types (along with their description) of images we produce and store in this location.

**Comment by mdhorn** [comment]
This would be my suggested;

https://gist.github.com/mdhorn/276f122e3e61a7626bc77c23ec6826d4
@gtkramer ?

**Comment by tpleavitt** [comment]
@mdhorn , that would be good since we would only have to maintain one location for the image description, so +1 from me

**Comment by gtkramer** [comment]
@tpleavitt README-IMAGES.html has been removed from the file server in favor of people going to https://clearlinux.org/downloads or visiting the public documentation for image types.  We can close this issue once #532 is closed.
