### ISSUE TITLE
Clear Linux stopped working after one day

### ISSUE THREAD

**Issue by tmlbl** [clearlinux/distribution#867]
I installed Clear yesterday on a machine with an NVIDIA 1070ti GPU and Ryzen 5 CPU. Everything worked great and I rebooted several times to confirm that boot was working.

Today I boot and get a black screen. I can run Ctrl+Alt+F4 and boot into some other DE with `startx`.

The `dmesg` log shows some noveau errors

```
[   67.123329] systemd-journald[574]: Failed to write entry (24 items, 16274067 bytes) despite vacuuming, ignoring: Argument list too long
[   68.829362] nouveau 0000:01:00.0: secboot: error during falcon reset: -110
[   68.836524] nouveau 0000:01:00.0: gr: init failed, -110
...
[  209.138464] gnome-panel[1170]: segfault at c0 ip 00007f75bf235f20 sp 00007fffbcde0068 error 4 in libgio-2.0.so.0.6000.3[7f75bf174000+171000]
```

**Comment by znmeb** [comment]
`nouveau` should be blacklisted - it can't handle the 1070Ti.

**Comment by tmlbl** [comment]
It had worked after several reboots, not sure how. But yes, I followed the instructions at https://clearlinux.org/documentation/clear-linux/tutorials/nvidia and I am back up and running
