### ISSUE TITLE
Dual SATA new Clear Linux install boot error: EFI failed to open file

### ISSUE THREAD

**Issue by cgamez** [clearlinux/distribution#868]
Hi, I installed clearlinux in a second SATA HDD.  Both SATAs have independent EFI partitions, one for each drive, the other SATA SDD has Windows+Fedora.
(Boot message)
Failed to open file: EFI\org.clearlinux\freestanding-00-intel-ucode.cpio
Trying to lad files to higher address
Failed to open file: EFI\org.clearlinux\freestanding-00-intel-ucode.cpio
(computer freeze)
I can boot to Windows and Fedora without issues.
Thanks in advance for advice or help.In my quest of having triple boot.  I reached the same message as single SATA (single UEFI partition) and now dual SATA:
![IMG_20190608_125710094](https://user-images.githubusercontent.com/31857373/59150972-5e13f280-89f1-11e9-8650-c4c64f1fe996.jpg)
![IMG_20190608_131055686](https://user-images.githubusercontent.com/31857373/59151014-c367e380-89f1-11e9-98d5-c7ef0030d172.jpg)
![IMG_20190608_131101193](https://user-images.githubusercontent.com/31857373/59151018-da0e3a80-89f1-11e9-9eb7-1e18ff6b6987.jpg)
![IMG_20190608_131108141](https://user-images.githubusercontent.com/31857373/59151020-e5616600-89f1-11e9-971e-99873508778a.jpg)

**Comment by ahkok** [comment]
Having multiple ESP partitions is not recommended - it will confuse all the bootloaders and possibly the firmware. The easiest way to solve this is likely to move the clearlinux kernel and bootloader entries over to the preexisting windows/fedora ESP, and `wipefs` the clearlinux ESP to make sure it's really gone. Then you can the existing bootloader to boot clearlinux. Since there is no automation to update kernels in clearlinux on non-clearlinux bootloaders, you'd have to do this once in a while to make sure you're booting the latest clearlinux kernels.

**Comment by cgamez** [comment]
@ahkok Thanks, I did reinstalled without any other disks, just left one HDD and no UEFI entries in BIOS NVRAM (cleared BIOS).  I got the same messages.  I think the initrd is for cpu microcode update and for some reason is not created properly or not loaded in the correct memory area.
![IMG_20190609_215726243](https://user-images.githubusercontent.com/31857373/59205786-347dd700-8b69-11e9-9fa5-1323c58aa984.jpg)
.  My motherboard is an Intel DH67BL and i7-2600K CPU.

**Comment by miguelinux** [comment]
How do you boot Windows and Fedora?

**Comment by cgamez** [comment]
@miguelinux I use as bootloader Fedora's Grub2, UEFI, without any intervention, this menu appears:
![IMG_20190610_200655322](https://user-images.githubusercontent.com/31857373/59236506-1db4a000-8bbc-11e9-8ff3-d078d3022c77.jpg)

**Comment by cgamez** [comment]
Upgraded mobo+cpu and now I have triple boot without any issue.  It seems this particular problem for this mobo is that from a 2010/2011 era and UEFI was not needed for Win 7 or Linux at that time.  Could only modify store entries via BCDEDIT.  Latest bios was from 2018 but probably just patched for the Spectre, Meltdown or other recent CPU security&vulnerability issues.
