### ISSUE TITLE
On KDE Plasma, many window elements have a monospaced font, despite all settings pointing to Clear Sans.

### ISSUE THREAD

**Issue by yerbestpal** [clearlinux/distribution#872]
An example is the Firefox window. I have definitely seem this occur on other components as well, but I cannot be sure where. I will update the bug report as and when they occur.

![](https://i.imgur.com/fwKX9sI.png)

**Comment by anselmolsm** [comment]
Could you check if these other components you mentioned are also GTK-based applications? Or please just list them when you face the issue again. Thanks.

**Comment by yerbestpal** [comment]
It does indeed seem that this is only the case on GTK applications.

**Comment by yerbestpal** [comment]
Turns out that the fonts on Gnome Shell had for some reason changed. Resetting them in Tweaks solved this issue. I should have looked there in the first place.
