### ISSUE TITLE
No mouse is available for gpm ?

### ISSUE THREAD

**Issue by nsauzede** [clearlinux/distribution#875]
Now that gpm is available, I tested it but couldn't manage to make it work in the linux console
No mouse device seems available

>$ sudo gpm -D
>*** info [daemon/startup.c(136)]: Started gpm successfully. Entered daemon mode.
>*** debug [daemon/init_mice.c(46)]: finished initialization
>O0o.oops(): [daemon/old_main.c(54)]: Please use -m /dev/mouse -t protocol
>*** debug [daemon/gpm_exited.c(30)]: Removing files /var/run/gpm.pid and /dev/gpmctl
>$ ls /dev/mouse
>ls: cannot access '/dev/mouse': No such file or directory

Of course, there is a mouse connected to the system : (and working on Xorg)
>$ sudo lsusb|grep -i mouse
>Bus 002 Device 004: ID 03f0:1198 HP, Inc HID-compliant mouse

Are we missing an automatic symbolic link '/dev/mouse' ?

>$ cat /etc/os-release 
>NAME="Clear Linux OS"
>VERSION=1
>ID=clear-linux-os
>ID_LIKE=clear-linux-os
>VERSION_ID=29850
>PRETTY_NAME="Clear Linux OS"
>ANSI_COLOR="1;35"
>HOME_URL="https://clearlinux.org"
>SUPPORT_URL="https://clearlinux.org"
>BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
>PRIVACY_POLICY_URL="http://www.intel.com/privacy"

**Comment by thiagomacieira** [comment]
We are missing /dev/mouse, but that's not just Clear. That symlink is just not created in modern Linux distributions using evdev input. Mostly because you have more than one mouse (touchpad, stick, USB connected, touch screen).

**Comment by ahkok** [comment]
Try pointing it at one of the `/dev/input` device nodes. AFAICS we can't automatically make this work without rewriting the code, which I don't think we should.

**Comment by nsauzede** [comment]
Ok, I see..
I tried :
> $ sudo gpm -k ; sudo gpm -D -m /dev/input/by-path/*mouse >& log

The output is then full of errors as soon as we move/click the mouse (ie: events are coming) :
>*** debug [daemon/add_mouse.c(50)]: adding mouse device: /dev/input/by-path/pci-0000:00:14.0-usb-0:3.2:1.0-event-mouse
>*** debug [daemon/init_mice.c(39)]: initialize /dev/input/by-path/pci-0000:00:14.0-usb-0:3.2:1.0-event-mouse with proto (null)
>*** debug [daemon/init_mice.c(46)]: finished initialization
>*** debug [daemon/get_console_size.c(45)]: Screen size: 240 - 67
>*** debug [daemon/get_console_size.c(62)]: x 10, y 22
>*** debug [daemon/old_main.c(158)]: selected 1 times
>*** err [daemon/getmousedata.c(47)]: Error in read()ing first: Invalid argument
>*** debug [daemon/old_main.c(158)]: selected 1 times
>*** err [daemon/getmousedata.c(47)]: Error in read()ing first: Invalid argument
>*** debug [daemon/old_main.c(158)]: selected 1 times
>...

The thing is I'm not sure what (default ?) protocol is used by modern USB laser mices
I tried with several "-t type" options (evdev, ps2, imps2, ms, etc..) but always get the same errors..
Not sure if I have to try all the possible protocols listed in "-t help", or forget the idea to have a working gpm in CLR...
Do you know if the situation is the same if we install a bare/server CLR ? (ie: no Xorg)
gpm/mouse setup for virtual linux console must be done manually like this ?

**Comment by thiagomacieira** [comment]
I'm not surprised, given that this is gpm we're talking about. It hasn't seen serious updates in well over a decade.

Anyway, /dev/input is evdev. You can confirm by using the evtest tool. For example, on my machine I have just the one:
```
$ sudo evtest /dev/input/by-path/*mouse
Input driver version is 1.0.1
Input device ID: bus 0x3 vendor 0x46d product 0x400a version 0x111
Input device name: "Logitech M325"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
    Event code 274 (BTN_MIDDLE)
    Event code 275 (BTN_SIDE)
    Event code 276 (BTN_EXTRA)
    Event code 277 (BTN_FORWARD)
    Event code 278 (BTN_BACK)
    Event code 279 (BTN_TASK)
    Event code 280 (?)
    Event code 281 (?)
    Event code 282 (?)
    Event code 283 (?)
    Event code 284 (?)
    Event code 285 (?)
    Event code 286 (?)
    Event code 287 (?)
  Event type 2 (EV_REL)
    Event code 0 (REL_X)
    Event code 1 (REL_Y)
    Event code 6 (REL_HWHEEL)
    Event code 8 (REL_WHEEL)
    Event code 11 (?)
    Event code 12 (?)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
```

If you move the mouse, you can see the coordinates changing.

**Comment by nsauzede** [comment]
I confirm evtest works fine with the same device
I also confirm that gpm might be a bitrot freak (notice the same error behaviour in my ubuntu 19.04 VM)
*facepalm*
thanks for your support as usual
and let's close this issue
*sigh*

**Comment by thiagomacieira** [comment]
Interestingly, on my openSUSE machine, I have an extra device node per mouse:
```
$ ls -l /dev/input/by-path/*mouse
lrwxrwxrwx 1 root root  9 jun 11 19:41 /dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.2-event-mouse -> ../event1
lrwxrwxrwx 1 root root  9 jun 11 19:41 /dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.2-mouse -> ../mouse0
lrwxrwxrwx 1 root root 10 jun  9 15:21 /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-event-mouse -> ../event11
lrwxrwxrwx 1 root root  9 jun  9 15:21 /dev/input/by-path/pci-0000:00:15.1-platform-i2c_designware.1-mouse -> ../mouse2
```

On Clear, we only have the "event-mouse" nodes. I don't know why that is.
