### ISSUE TITLE
Missing md_mod from /lib/modules/5.1.7-128.aws

### ISSUE THREAD

**Issue by florinpapa** [clearlinux/distribution#877]
Using Clear Linux 29810 on AWS.

I am installing the `storage-utils` bundle to provide the `mdadm` command and I am running into this error:
```
sudo mdadm --create /dev/md0 --level=stripe --raid-devices=4 /dev/nvme0n1 /dev/nvme1n1 /dev/nvme2n1 /dev/nvme3n1
STDOUT: 
STDERR: modprobe: FATAL: Module md_mod not found in directory /lib/modules/5.1.7-128.aws
```

It seems that the `md_mod` module is missing from `/lib/modules/5.1.7-128.aws`. Is it possible to add it there?

**Comment by thiagomacieira** [comment]
@miguelinux

**Comment by ahkok** [comment]
Does this actually make sense, though? This feels like a bit of an experiment, and not something that actually gives any value - the underlying storage should be giving you the best performance anyway (IOW, upgrade your storage to a better performing level).

**Comment by florinpapa** [comment]
This is used as part of the fio benchmark in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/perfkitbenchmarker/linux_benchmarks.

@HarpPDX is using the stripe disks feature in his team, maybe he can give a bit more context.

**Comment by HarpPDX** [comment]
The stripe feature is used to stripe the local disks (those physically attached to the machine on which the VM resides) for better storage performance (e.g. m5d.24xlarge has 4 900GB NVMe drives physically attached). Workloads that use/bottleneck on storage can benefit.  
For network-based storage, as noted by @ahkok, performance is determined by choice of service.

**Comment by miguelinux** [comment]
They will be available in 1 or 2 days.

**Comment by florinpapa** [comment]
Works for me after the changes.
