### ISSUE TITLE
The Firefox bundle does not contain enough packages to run.

### ISSUE THREAD

**Issue by halars** [clearlinux/distribution#88]
After installing the Firefox bundle (swupd bundle-add firefox), and running firefox, it complains:
XPCOMGlueLoad error for file /root/firefox/libmozgtk.so:
libgtk-3.so.0: cannot open shared object file: No such file or directory

And as reported, libgtk-3 is not included in the firefox bundle, and therefore not installed.
Other packages might be missing as well.

ver.: 22980

**Comment by fenrus75** [comment]
poking at this; a few deps were indeed missing;l it might take 2 rounds to
get this fixed if there's something very subtle

**Comment by danboid** [comment]
Seems this can be closed now - FF launches fine.

**Comment by tpleavitt** [comment]
@jairglez , can you verify and close this issue

**Comment by jairglez** [comment]
Firefox tested and launching correctly on Clear Linux 28270. Tested on GNOME, KDE and Xfce desktop environments.
