### ISSUE TITLE
power tweaks: add a rule to enable autosuspend for 04f3:2234 (touchscreen)

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#880]
This reference platform has an Elan (idVendor == 0x04f3) HID/touchscreen (idProduct==0x2234) connected over USB. If this device is not put into autosuspend, the reference platform cannot achieve residency in PkgCstates below PkgC8 while idle.

Desired outcome(s):
- Enable autosuspend for idVendor==0x04f3, idProduct==0x2234

**Comment by thac0** [comment]
Colleagues: go ahead and assign this to me. Thanks!

**Comment by fenrus75** [comment]
we shold introduce you to clr power tweaks

udev rules are pretty expensive so many things are better off as a power
tweak

**Comment by thac0** [comment]
> we shold introduce you to clr power tweaks udev rules are pretty expensive so many things are better off as a power tweak

Noted!

**Comment by thac0** [comment]
Added to clr-power-tweaks 199-128. Appears in Clear Linux 29980. Closing.
