### ISSUE TITLE
RTL8812 Driver support

### ISSUE THREAD

**Issue by CaptSilver** [clearlinux/distribution#881]
I would love to see a bundle that includes the RTL8812 driver. I know it's not in the upstream kernel, but it's a fully open source driver that includes packet injection. The most up to date and "supported" version of this driver is provided by aircrack-ng, which is something else that would be nice to be added in. ;)

https://github.com/aircrack-ng/rtl8812au

Thanks for making Clear OS!!

**Comment by CaptSilver** [comment]
Closing issue at this time due to Clear Linux's policy of not including out of tree drivers.

**Comment by fenrus75** [comment]
can we ask Greg KH to include this driver into his staging tree?

**Comment by thiagomacieira** [comment]
Why don't the upstream devs send it?
