### ISSUE TITLE
Missing `pthread_cond_wait(3)` and some of the other pthreads man pages

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#882]
`pthreads(7)` refer to various man pages that are missing, e.g. `pthread_cond_wait(3)`, `pthread_cond_signal(3)`. Note that some of the man pages are present, e.g. `pthread_create(3)` and `pthread_exit(3)`.

**Comment by thiagomacieira** [comment]
Looks like the man-pages package doesn't have this at all, in any distro. But there's a copy of the POSIX manual that does. On openSUSE:

```
$ rpm -qf /usr/share/man/man3*/pthread_cond_timedwait.*
man-pages-posix-2013a-4.2.noarch
$ rpm -qf /usr/share/man/man3*/pthread_create.*  
man-pages-posix-2013a-4.2.noarch
man-pages-5.01-1.2.noarch
$ LC_ALL=C man pthread_create
Man: find all matching manual pages (set MAN_POSIXLY_CORRECT to avoid this)
 * pthread_create (3)
   pthread_create (3p)
Man: What manual page do you want?
```

We don't have man-pages-posix.

**Comment by ahkok** [comment]
Note that our `man 3` section are in `devpkg` bundles only. In other words - not part of the normal bundles that `libs` end up in. At least, this is valid for autospec packages. Which glibc is not, but, binutils is I believe. In short: this may be confusing and unintuitive.

**Comment by thiagomacieira** [comment]
Should be fixed in 29930 or 40
