### ISSUE TITLE
Consider adding "po4a"

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#883]
Used for example  to convert manpages to PO format (for i18n).

**Comment by ahkok** [comment]
Do you want to take a stab at it yourself?

**Comment by jurobystricky** [comment]
sure, I can give it a go.

**Comment by jurobystricky** [comment]
I managed to autospec/build  the po4a RPM locally. There were some additional missing dependencies that needed to be aotospeced/built as well:

perl-SGMLSpm
perl-Text-CharWidth
perl-Text-WrapI18N
perl-Unicode-LineBreak

**Comment by ahkok** [comment]
Awesome, send patches to me or @btwarden, or the list?

**Comment by jurobystricky** [comment]
I sent 5 patches for review to clr-dev@eclists.intel.com.

**Comment by puneetse** [comment]
I'm closing this issue because you packaged `po4a` and made it available as bundle in Clear Linux shortly afterwards. Nice job!
