### ISSUE TITLE
Stuck with `gnome-initial-setup` loop

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#887]
Two days ago, for unknown reason I was not able to login the system. Every time when the system boots, `gnome-initial-setup` turns up and ask me to create a user account.

At that time, the OS version was **29880** and even if I tried to create a new user account, I was still not able to log in because the screen just freezes.

I was able to login via tty and from their I rolled back the OS version and tried to see which update introduced the issue. Unfortunately, it didn't work and when I got to **29830**, I was not even able to login via tty. The journal says cannot execute `/bin/login` as it's not found. But it's actually just there!

I tried to create an account in `gnome-initial-setup` and for unknown reason I was able to login. But after log-out or restart, I will yet again see the `gnome-initial-setup` as if no user account is ever created. Also, in the `Detials-Users` tab of `gnome-control-center`, it says that no user account is found.

I googled a lot but nothing helped. But one of the post mentioned `/etc/passwd` so I took a look. I turns out that, something messed up this file with it contents like
```
foo:x:1005:1006::/home/foo:/bin/zsh
bar:x:1006:1007::/home/bar:/bin/bash
```
That is, each user is not in his own group.

Also I recall that I modified `/etc/shells` because I was testing my patch for some `zsh` completions, but it doesn't seems to be related. Nevertheless I deleted this file.

I'm not sure whether either of `/etc/passwd` or `/etc/shells` is related the issue I had, but fixing that manually did enable me to login via tty, though the `gnome-inital-setup` loop is not yet fixed.

But today when I turned on the computer, somehow this is fixed, that I'm able to login normally!

I attached the journal below and hopefully this won't occur again.

[journal](https://gist.githubusercontent.com/lebensterben/dce0071363b67fa2a8d021da9e611e15/raw/e624c1d31ebab997d3e967d56c4717fee949c344/journal)

**Comment by puneetse** [comment]
I'm closing this because after talking to you, it has not happened since sounds like a point-in-time issue. Of course, if it happens again please open a bug.
