### ISSUE TITLE
Document legacy-kvm in the README-IMAGES.html

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/distribution#89]
https://download.clearlinux.org/image/README-IMAGES.html

**Comment by alexjch** [comment]
Adding "clear-*-legacy-kvm.img.xz -- Image for booting in a simple VM using legacy BIOS, if using start_qemu.sh make sure to remove -bios parameter" to README-IMAGES.

**Comment by phmccarty** [comment]
@alexjch Should we make the start_qemu.sh smarter so that users don't have to modify the script? Maybe we could add option parsing for it?

**Comment by alexjch** [comment]
@phmccarty excellent Idea different issue. I will work on that though.

**Comment by dpotapov** [comment]
Hi,
What is the difference between legacy-kvm and kvm? Is it only a matter of partitioning? If yes, can we have a single image with hybrid MBR-GPT ?

**Comment by ahkok** [comment]
The difference is that the `kvm` image only supports UEFI booting, and the `legacy-kvm` image only supports booting in legacy boot mode. We do not make a hybrid image.
