### ISSUE TITLE
Allow toggle to update when connected to AC

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#893]
This is a clearly useful OS for corp and more so to research labs. But it is not as battery efficient as Ubuntu on laptops. 

For this reason, it would be nice to have a toggle that conditions swupd to update only when the laptop is connected to AC.

- Please consider such an option.

Thanks

**Comment by bwarden** [comment]
```
$ sudo systemctl edit swupd-update.service
```
and set:
```
[Unit]
ConditionACPower=true
```

**Comment by miguelinux** [comment]
from [systemd.unit](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) documentation:


`ConditionACPower= ` may be used to check whether the system has AC power, or is exclusively battery powered at the time of activation of the unit. This takes a boolean argument. If set to "true", the condition will hold only if at least one AC connector of the system is connected to a power source, or if no AC connectors are known. Conversely, if set to "false", the condition will hold only if there is at least one AC connector known and all AC connectors are disconnected from a power source.
