### ISSUE TITLE
Dell Studio xps 8700 i7 not acceptable

### ISSUE THREAD

**Issue by donaldw4** [clearlinux/distribution#899]
Clear OS test claim the i7 not acceptable.

**Comment by thiagomacieira** [comment]
Did it give any more information why it thinks the system is not acceptable?

**Comment by ahkok** [comment]
You likely booted in BIOS mode. Please boot in UEFI mode instead.

**Comment by donaldw4** [comment]
I am getting the following message:  Missing required CPU Feature: Advance
Encryption.

How do I solve this problem?

Thanks,
Donald

**Comment by ahkok** [comment]
Duplicate of #785

**Comment by thiagomacieira** [comment]
For the record, can you tell us what processor that machine has?

**Comment by donaldw4** [comment]
All I can tell you is that it is an i7.  Please tell me how to find out the
processor number?  Is it possible that I need an update?

Thanks,
Donald

**Comment by thiagomacieira** [comment]
From a Linux system that runs on it, `cat /proc/cpuinfo`.

It's possible that a BIOS update or configuration will turn AES back on. But you might have one of the processors that don't have the feature.

**Comment by donaldw4** [comment]
By chance, do you know with site I need to go to in order to check for an update for my BIOS?

Thanks,
Donald

**Comment by donaldw4** [comment]
See if this information helps:

**Comment by thiagomacieira** [comment]
I get my Dell BIOS upgrades from https://www.dell.com/support/home/us/en/4/product-support/. Type your service tag and it'll show the downloads for your machine. Most of them are Windows executables, even the BIOS and firrmware upgrades, unfortunately.
