### ISSUE TITLE
Latam keyboard not available

### ISSUE THREAD

**Issue by cgamez** [clearlinux/distribution#900]
Hi, Clear Linux installer detects correctly my language (es/mx) but the keyboard is not following (remains us keyboard).  Tried to look for latam keyboard and found many latin variants but none corresponds to spanish/latin america.  I think there is not even spanish/spain entry.  It would be a nice to have or if someone knows how to set it up, please let me know.

**Comment by miguelinux** [comment]
Hi @cgamez 

Are you using Gnome or  other desktop?

![region&language](https://user-images.githubusercontent.com/1160989/59644646-6aa3f380-9133-11e9-8a25-4f7c2cb2ab7b.png)

**Comment by cgamez** [comment]
@miguelinux Thanks Miguel, I selected the keyboard in Gnome, its just it was not there in the installer.  Probably something nice to have in the installer, but this works fine.
