### ISSUE TITLE
GStreamer MSDK plugin playback H265 abnormally fast

### ISSUE THREAD

**Issue by litcoder** [clearlinux/distribution#902]
MSDK decoder playback abnormally fast for H265 encoded videotestsrc with logs of "_Frame doesn't have a valid pts yet, Use gst_video_decoder_get_oldest_frame()with out considering the PTS for selecting the frame to be finished_". 
This issue happens when msdk h265 decoder is used and okay with playbin.

**Steps**
1. Encode H265 from videotestsrc pattern 18.
 $ gst-launch-1.0 videotestsrc pattern=18 ! msdkh265enc ! filesink location=output.h265
2. Playback using msdkh265 decoder.
 $ LIBVA_DRIVER_NAME=iHD GST_DEBUG=msdk*:5 gst-launch-1.0 filesrc location=output.h265 ! h265parse ! msdkh265dec ! autovideoconvert ! autovideosink

**Comment by ahkok** [comment]
Question: would this be an upstream bug? Do you know if this happens with other distro's perhaps?

@chivakker

**Comment by chivakker** [comment]
It is not an upstream bug, It looks like @litcoder wants to play a raw h.265 file.  Since it is not within a container, fps has to be provided in the gstreamer pipeline.  GStreamer documentation is the way to look into this.
