### ISSUE TITLE
gnome-software installation and update progress appears to hang

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#905]
We're seeing reports surface in the CL forums about the gnome-software progress bar appearing to hang and not do anything during installation or updates of software. I've seen this behavior a couple of time too but installation eventually completed after a while.

Running a `flatpak update` manually works fine and shows progress.

https://community.clearlinux.org/t/software-app-pending-installation/759
https://community.clearlinux.org/t/software-not-updating/785
https://community.clearlinux.org/t/software-centre-for-gnome-stuck-on-pending/811

**Comment by Mountainerd** [comment]
Potentially the same issue as #901

**Comment by bryteise** [comment]
Yea this is a dup of #901, closing.
