### ISSUE TITLE
Desktop installer (clr-installer-gui) should support manual disk partitioning

### ISSUE THREAD

**Issue by Comevius** [clearlinux/distribution#907]
![](https://clearlinux.org/sites/default/files/_images/bare-metal-install-desktop-08.png)

There is no **Advanced Configuration** under **Select Installation Media**, so you cannot create and select partitions, file systems and mount points.

Automatic partitioning creates a /boot fat32 partition, a 256 MB swap partition and uses the rest of the disk for a / ext4 partition.

I have to use clr-installer, which has an Advanced Configuration. It also has some minor issues:
- If you select a / and /boot partition first, the disk is considered already configured and you have to revert everything to be able to configure additional partitions.
- Forcing an existing partition to maximum size marks the partition as free space that cannot be configured anymore. You have to revert everything.

**Comment by mdhorn** [comment]
Hello. This is already being tracked in the Clear Installer repo:
https://github.com/clearlinux/clr-installer/issues/410

This is one of the next enhancement we are working on in the coming weeks.
