### ISSUE TITLE
Add new initrd with support for LVM 

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/distribution#912]
Please add a new initrd and bundle, similar to the one for LUKS, which adds support for LVM. This will enable the use of LVM for the entire media allowing the root file system to be stored in the LVM.

This is an enable pre-step to support LVM in the Clear Linux installer.

**Comment by thiagomacieira** [comment]
Yes, please!

If the same initrd can be made to support RAID too, would be great.

**Comment by mrkz** [comment]
cc @josuedhg

**Comment by mdhorn** [comment]
Added in 33430
