### ISSUE TITLE
Please add sublime text bundle

### ISSUE THREAD

**Issue by lf-araujo** [clearlinux/distribution#913]
Hi team,

Could you please add a sublime text bundle? 

It is a  mature text editor, and may be useful for other clearlinux users. The flatpak version cannot access binaries  from the system, which makes several extensions unusable.

Keep up with the great work.

**Comment by mrkz** [comment]
@lf-araujo Sorry,

Unfortunately, we can't ship Sublime text due to its proprietary nature.

However, we got other editors such as gedit or atom.
Last resort; you can grab their X64 binary download and place it into /opt. I just tested and works correctly.

**Comment by lf-araujo** [comment]
Thank you, will do that
