### ISSUE TITLE
ClearLinux and static IP issues

### ISSUE THREAD

**Issue by ganeshmaharaj** [clearlinux/distribution#915]
i am drafting this issue as an overarching one that should probably trigger a few more bugs across various bits including documentation.
I setup a new server box yesterday with clearlinux server edition (no GUI), installed using defaults and all was well. The machine got a DHCP leased IP address and i was later provided a static IP by the local administrators.
I followed the instructions at https://clearlinux.org/documentation/clear-linux/guides/maintenance/assign-static-ip and restarted `systemd-networkd` and the network interface got the static IP.

Fast-forward today, i had to reboot the system and i am no longer able to login. More debugging and it seems that the machine went and got itself a DHCP IP and ignored the static IP it was assigned. Thanks to loads of help from @bryteise , we noticed that `NetworkManager` is the dominant one and `systemd-networkd` does not take effect on reboot unless restarted manually. i tried adding the static settings to `/etc/network/interfaces` and that didn't help. i tried to set the static IP using `nmcli` command line (no GUI cause of server install) with the below commands
```
366  sudo nmcli con mod 'Wired connection 1' ipv4.address "value/cidr"
 368  sudo nmcli con mod 'Wired connection 1' ipv4.gateway "value"
  369  sudo nmcli con mod 'Wired connection 1' ipv4.netmask "value"
  371  sudo nmcli con mod 'Wired connection 1' ipv4.dns "value"
  372  sudo nmcli con mod 'Wired connection 1' ipv4.dns-search "value"
```
and that didn't work either. I finally masked `NetworkManager` and `systemd-networkd` is my default now and things work as expected.

Thanks for listening to the story. i believe these are the things that might need to be looked at.
1. Choose either `NetworkManager` or `systemd-networkd` as default and probably disabled the other one.
2. Figure out why `NetworkManager` does not honor information sitting at `/etc/network/interfaces`
3. Fix documentation on what is the right way to set static IP.

**Comment by mdhorn** [comment]
The Installer ISO images, both Desktop and Server, now always use the NetworkManager as the default as that is now the preferred default for Clear Linux.

That documentation you referenced needs to be updated as those directions are only for system--networkd, not NetworkManager.  Network manager will store interface files with different names in /etc/NetworkManager/system-connections.

I'd also advise using the nmtui which provides a user interface which is generally easier to understand and use than the command line nmcli.

**Comment by ganeshmaharaj** [comment]
@mdhorn ohh that is good to know. i did not know about the existence off nmtui. It would be good to update that documentation with steps to use that would be good. Does this also mean that contents of `/etc/network/interfaces` will not be absorbed by NetworkManager?

**Comment by mdhorn** [comment]
> Does this also mean that contents of `/etc/network/interfaces` will not be absorbed by NetworkManager?

Yes, unfortunately, systemd-networkd and NetworkManager have completely independent data models for storing interface details. `/etc/network/interfaces` is only for systemd-networkd.

NetworkManager configuration files are described here:
https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html

But using nmtui will just create the files in the right location with the correct content.

When you boot the server ISO, there should be a message on the screen directing the user to run `nmtui` if you need to configure a static IP or setup WiFi before starting the installation:

```
To configure the network run:

  nmtui
```

We will get the documentation updates.

**Comment by puneetse** [comment]
I've updated the documentation on this subject here: https://clearlinux.org/documentation/clear-linux/guides/maintenance/assign-static-ip

Thanks for flagging the issue @ganeshmaharaj

**Comment by jairov4** [comment]
@puneetse the link is broken now, maybe it was relocated, do you know how to find the new location?

**Comment by bryteise** [comment]
https://clearlinux.github.io/clear-linux-documentation/guides/network/assign-static-ip.html I believe.
