### ISSUE TITLE
Cannot use AnyConnect VPN with wired connection

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/distribution#916]
I am running Clear Linux 29940 and have observed that I cannot connect the VPN AnyConnect when my connection is Ethernet. It works fine when I have a wireless connection. I suspect it has to do with the `systemd-networkd` vs. `NetworkManager` story. Both are running on my system and the NetworkManager applet indicates Ethernet as "Wired Unmanaged".

I was under the impression that we now wanted to have NetworkManager manage **all** connections, including wired connections. If true, is it expected that I still have `systemd-networkd` running?

How can I make sure that I can always establish the VPN AnyConnect session regardless of my connection type?

**Comment by lebensterben** [comment]
```
   Network interface management
       Clear Linux has switched the network interface management model to be fully managed by NetworkManager when installed on real hardware. Previ‐
       ously, Ethernet interfaces were managed by systemd-networkd whereas Wi-Fi and others were managed by NetworkManager. Clear Linux cloud images
       continue to use systemd-networkd.

       When  updating  from  previous  versions of Clear Linux, the installation will be reconfigured to continue with systemd-networkd managing the
       Ethernet interfaces.  Since the connectivity could be lost during the procedure, physical access to the system is required. To switch to Net‐
       workManager for all the interfaces, the user should disable and stop systemd-networkd:
          sudo systemctl disable systemd-networkd sudo systemctl stop systemd-networkd

       Then, remove the file /etc/NetworkManager/conf.d/systemd-networkd-unmanaged.conf

       Finally, restart NetworkManager
          sudo systemctl restart NetworkManager
```

Have you tried to disable `systemd-networkd`?

**Comment by ahkok** [comment]
Above post of @lebensterben is correct. Once you follow this procedure, you can use the wired connection for VPN as normal.

**Comment by gvancuts** [comment]
> Above post of @lebensterben is correct. Once you follow this procedure, you can use the wired connection for VPN as normal.

Not quite in my case, `systemd-networkd` is automatically restarted after I restart `NetworkManager`, I'm assuming this is because of `systemd-networkd.socket`. I'll look a little deeper into this later but there seems to be something missing in the instructions (or something unusual on my system but I can't think of what that'd be).

**Comment by gvancuts** [comment]
It works after a reboot
