### ISSUE TITLE
[Package request] Keybinder 3

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#918]
keybinder is a library for registering global keyboard shortcuts. Keybinder works with GTK-based applications using the X Window System

https://github.com/kupferlauncher/keybinder

**Comment by thiagomacieira** [comment]
Which applications will benefit from this?

**Comment by lebensterben** [comment]
@thiagomacieira 
https://github.com/Ulauncher/Ulauncher

**Comment by bryteise** [comment]
I wish Ulauncher would create releases for non-rc/beta things =P. Usually we don't take package requests for libraries unless somebody wants a them for their own development. Is this a package request for Ulauncher or is this a request for a devpkg for keybinder?

**Comment by lebensterben** [comment]
>I wish Ulauncher would create releases for non-rc/beta things =P. Usually we don't take package requests for libraries unless somebody wants a them for their own development. Is this a package request for Ulauncher or is this a request for a devpkg for keybinder?

@bryteise Well, I was testing Ulauncher which needs keybinder.
I did some research and found most projects requiring keybinders are related to BSD. 
It would be nice if it's packaged but I can understand if it isn't. 
As for Ulauncher, I was just testing it and I'm not sure whether I will use it. So at this point I'm not requesting it.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thiagomacieira** [comment]
Like @bryteise said, we'd wait to package the library until something needs it, unless you tell us you want to use it in your own application development (which you're doing on Clear).

**Comment by lebensterben** [comment]
@thiagomacieira I agree with you and I'm closing this issue now.
