### ISSUE TITLE
SquashFS support

### ISSUE THREAD

**Issue by dpotapov** [clearlinux/distribution#92]
Hello,

I'd like to have smaller ClearLinux-based images to distribute them on USB sticks. Having a root filesystem on squashfs would be a perfect solution.

It seems the current kernel configuration missing it:

```
# CONFIG_SQUASHFS is not set
```

**Comment by fenrus75** [comment]
I've just turned this on; for the narrow request of the kernel change this
is done.

the broader "make squashfs work" is likely other items but I'd like to
request opening just new issues for other items that pop up to keep this
issue simple

**Comment by dpotapov** [comment]
Awesome, thanks!

**Comment by dpotapov** [comment]
Just want to say that I've got squash fs mounted from the dracut-generated initramfs. Works as expected!

**Comment by hunger** [comment]
I can't mount a squashfs using clearlinux 23180.
Do I need some special bundle to enable this?

**Comment by bryteise** [comment]
Ah the tooling for managing squashfs was missing, this should be added in the next release.

**Comment by hunger** [comment]
OK, found my issue: squashfs in clearlinux only supports gzip while my squashfs is built using lz4.
I opened #104 about that.
