### ISSUE TITLE
X fails to start

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#93]
I added the desktop and desktop-autostart bundles and rebooted. The screen flickered a couple of times, but no UI showed up.

This is on a thinkpad T460s, which is machine based on skylake.

The Xorg.log.0 file can be found here: https://gist.github.com/hunger/1e4cd13827e71c6764c57585c0e4046b . Feel free to contact me if you need more information.

**Comment by josuedhg** [comment]
Hi Tobias, I have a some questions, what release are u running? if did u do a swupd update what was the source release? what kind of kernel are u using? these questions in order to try to reproduce the issue.

Thank you in advance!

**Comment by hunger** [comment]
Oh, sorry, I am using a bare-metal installation at version 23070. I installed using clear-23000-live.img.
The only bundle I have installed that looks kernel-related is kernel-native.

**Comment by josuedhg** [comment]
just a couple of things, could u send the output of journalctl -u gdm.path? and check the existence of /dev/dri/ and its content, I thing I got a similar behavior, this is just to confirm that are the same issues

**Comment by josuedhg** [comment]
also the journalctl -u gdm.service output please

**Comment by hunger** [comment]
gdm.path is empty except for the usual "Systemd starts this" message

This is gdm.service starting from the last reboot:

-- Reboot --
Jun 15 16:14:38 clr-xxx systemd[1]: Starting GNOME Display Manager...
Jun 15 16:14:39 clr-xxx systemd[1]: Started GNOME Display Manager.
Jun 15 16:14:39 clr-xxx gdm[342]: GdmDisplay: display lasted 0.345658 seconds
Jun 15 16:14:41 clr-xxx gdm[342]: GdmDisplay: display lasted 1.773234 seconds
Jun 15 16:14:41 clr-xxx gdm[342]: Child process -455 was already dead.
Jun 15 16:14:41 clr-xxx gdm[342]: Child process 385 was already dead.
Jun 15 16:14:41 clr-xxx gdm[342]: Unable to kill session worker process
Jun 15 16:14:41 clr-xxx gdm[342]: GdmDisplay: display lasted 0.830861 seconds
Jun 15 16:14:41 clr-xxx gdm[342]: Child process -564 was already dead.
Jun 15 16:14:41 clr-xxx gdm[342]: Child process 548 was already dead.
Jun 15 16:14:41 clr-xxx gdm[342]: Unable to kill session worker process
Jun 15 16:14:42 clr-xxx gdm[342]: GdmDisplay: display lasted 0.830578 seconds
Jun 15 16:14:42 clr-xxx gdm[342]: Child process -617 was already dead.
Jun 15 16:14:42 clr-xxx gdm[342]: Child process 599 was already dead.
Jun 15 16:14:42 clr-xxx gdm[342]: Unable to kill session worker process
Jun 15 16:14:43 clr-xxx gdm[342]: GdmDisplay: display lasted 0.880640 seconds
Jun 15 16:14:43 clr-xxx gdm[342]: Child process -671 was already dead.
Jun 15 16:14:43 clr-xxx gdm[342]: Child process 653 was already dead.
Jun 15 16:14:43 clr-xxx gdm[342]: Unable to kill session worker process
Jun 15 16:14:44 clr-xxx gdm[342]: GdmDisplay: display lasted 0.847214 seconds
Jun 15 16:14:44 clr-xxx gdm[342]: GdmLocalDisplayFactory: maximum number of X display failures reached: check X server log for errors
Jun 15 16:14:44 clr-xxx gdm[342]: Child process -725 was already dead.

**Comment by hunger** [comment]
Just re-tested with 23090: Desktop comes up now. Thanks for your work!
