### ISSUE TITLE
The lastest release of Tensorflow_Probability is 7.0

### ISSUE THREAD

**Issue by stokhos** [clearlinux/distribution#932]
Hi dear clearlinux team:
Tensorflow probability has released 7.0 version
Best

**Comment by fenrus75** [comment]
I'll be updating the whole tensorflow stack this weekend since there's also
a new tensorflow/tensorboard/...

**Comment by fenrus75** [comment]
so far I've updated
bazel
tensorflow
tensorflow-probability
tensorflow-estimator

I'm currently having a bit of an argument with tensorboard but that'll have to get done tomorrow

(note to self: tensorflow does not build quick. on a beefy core i9.)
