### ISSUE TITLE
30030 breaks VirtualBox 6.0.8 3D Acceleration (i965_drv.so.avx2)

### ISSUE THREAD

**Issue by wheerdam** [clearlinux/distribution#935]
Updating to 30030 with native kernel:
```
kernel 5.1.12-785.native #1 SMP Wed Jun 19 07:09:10 UTC 2019 x86_64 GNU/Linux 
```
breaks 3D acceleration in VirtualBox 6.0.8 r130520 with Windows 8 and Windows 10 x64 guests and VBoxSVGA display driver. The guest VM will be aborted once the guest drivers (Guest Additions) are loaded.

In VirtualBox, there was a segfault related to i965_drv.so.avx2 dumped to kernel messages:
```
[ 4261.830293] vboxdrv: 000000003fa35046 VMMR0.r0
[ 4261.924035] vboxdrv: 00000000902574ae VBoxDDR0.r0
[ 4262.015391] vboxpci: created IOMMU domain 000000003aa84df8
[ 4287.170591] VMSVGA FIFO[15624]: segfault at 0 ip 00007f85692eb770 sp 00007f8514633200 error 4 in i965_dri.so.avx2[7f8568d55000+a5c000]
[ 4287.170598] Code: 97 c1 84 ca 0f 84 90 09 00 00 83 ff 0f 0f 86 87 09 00 00 41 89 f8 48 89 c2 48 89 f1 41 c1 e8 04 49 c1 e0 08 49 01 c0 0f 1f 00 <c5> fe 6f 39 c5 fe 6f 71 20 48 81 c2 00 01 00 00 48 81 c1 00 01 00
[ 4287.291698] vboxpci: freeing IOMMU domain 000000003aa84df8
```
Disabling guest 3D acceleration allows the VM to run. This configuration worked previously.

Not sure if this is related and/or useful, but I also tested VMWare with 3D acceleration enabled by allowing it to use the i965 driver (it's blacklisted by default) in .vmware/preferences:
```
mks.gl.allowBlacklistedDrivers = "TRUE"
```
I installed Windows 10 with Easy Install (which also installs the guest drivers). If 3D acceleration is turned off the guest VM will boot normally, but performance is subpar. Using 3D acceleration will crash the VM once the UI is started:
```
2019-06-22T06:35:29.866+07:00| svga| I125: Started Shim3D
2019-06-22T06:35:29.866+07:00| svga| I125: MKS-RenderMain: Started GLRenderer
2019-06-22T06:35:29.866+07:00| svga| I125: GLWindow: successfully started by HWinMux to do window composition.
2019-06-22T06:35:29.866+07:00| svga| I125: MKS-HWinMux: Started GL presentation backend
2019-06-22T06:35:29+07:00[+0.000]| svga| W115: Caught signal 11 -- tid 12133 (addr 0)
2019-06-22T06:35:29+07:00[+0.000]| svga| I125: SIGNAL: rip 0x7fce397fd770 rsp 0x7fce391f8b00 rbp 0x7fce391f8b50
2019-06-22T06:35:29+07:00[+0.000]| svga| I125: SIGNAL: rax 0x7fcd294f14b0 rbx 0x7fce391f8bf0 rcx 0x0 rdx 0x7fcd294f14b0 rsi 0x0 rdi 0x294b
2019-06-22T06:35:29+07:00[+0.000]| svga| I125:         r8 0x7fcd2951a8b0 r9 0x294c r10 0x0 r11 0xffffffffffffff28 r12 0x7fcd294db910 r13 0x7fcd294db3c0 r14 0x0 r15 0x7fcd292bd640
```
I am unable to confirm if VMWare 3D acceleration worked previously as I was not using it and setup this VM just for testing.

Edit: I'm using VMWare Workstation Pro 15 version 15.1.0 build-13591040 and default desktop bundle (Gnome 3 xorg)

My hardware is i5-8400 running on a H310 board using the integrated graphics (no video card)

**Comment by thiagomacieira** [comment]
@chivakker is this when LTO was turned back on?

**Comment by chivakker** [comment]
@thiagomacieira yes, it is when mesa re-enabled LTO. I am not sure it is related to this issue as @wheerdam  says he didn't enable 3D acceleration before.

**Comment by wheerdam** [comment]
> @thiagomacieira yes, it is when mesa re-enabled LTO. I am not sure it is related to this issue as @wheerdam says he didn't enable 3D acceleration before.

I did use 3D acceleration before in VirtualBox and it worked before 30030. It only started crashing after the update and I had to disable it to run my VM.

Is there any way to use non-LTO i965 driver just for testing to isolate the problem?

**Comment by chivakker** [comment]
Release 30100 has mesa with no-lto

**Comment by wheerdam** [comment]
> Release 30100 has mesa with no-lto

I have updated to 30100 and 3D acceleration in VirtualBox works again.

3D Acceleration in VMware also works now.

**Comment by chivakker** [comment]
Closing as VMWare issue is not happening
