### ISSUE TITLE
devpkg-SDL_ttf seems to be missing SDL_ttf.h

### ISSUE THREAD

**Issue by madmagi** [clearlinux/distribution#938]
Trying to compile against code that requires the SDL2.0 TTF libraries, after installing the SDL libraries, including the devpkg-SDL_ttf packages, still no joy.

**Comment by fenrus75** [comment]
did you mean devpkg-SDL2_ttf or devpkg-SDL_ttf ?
(one is SDL1 other is SDL2.. unfortunately both are still in use so we end
up having both)

**Comment by madmagi** [comment]
Ah thanks for the quick reply; gotta love the sdl mess !  wasn't clear I needed to add devpkg-SDL2-ttf, problem solved.  closing issue.
