### ISSUE TITLE
Resume from suspend is not possible: Power button is ignored

### ISSUE THREAD

**Issue by hunger** [clearlinux/distribution#94]
I have version 23070 installed on a thinkpad T460s (skylake) and running systemctl suspend does the suspend. The power button starts to slowly blink like it usually does during suspend.

Unfortunately the power button no longer turns on the machine. The blinking continues, there is no discernible disk activity or any other sign of the system having registered the wake-up attempt.

Pressing the power button for several seconds turns of the machine, without any attempt to actually start again.

**Comment by hunger** [comment]
I installed version 23000 of the live-image yesterday. The only kernel-related thing in swupd is kernel-native. Not sure about the kernel version, I have booted a different Linux flavor right now.

**Comment by hunger** [comment]
Just tested this again: The issue is still visible in 23090.

**Comment by ahkok** [comment]
@mrkz I don't think we test suspend/resume, do we? Did we perhaps by chance disable the power button functionality?

@hunger does WoL work to bring the machine out of suspend?

**Comment by josuedhg** [comment]
@ahkok we don't test suspend/resume at this moment and the power button functionality is working if I press it it go to suspend but if I press it again never returns

**Comment by hunger** [comment]
I don't know whether WOL works, sorry. UEFI bios has that disabled.

**Comment by josuedhg** [comment]
this is not an issue with the power button, if u set a RTC timer to wake up the suspended system it is still not working, apparently it is an BIOS bug https://bugzilla.redhat.com/show_bug.cgi?id=1164937 for thinkpad machines, there is a work around that probably will be available in the next release.

**Comment by hunger** [comment]
Thanks!
Suspend/resume now work for me.
