### ISSUE TITLE
Borg backup fails self-test

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/distribution#941]
```
$ borg init -e none borg                                           
self test test_identical_creation (borg.testsuite.hashindex.HashIndexDataTestCase) FAILED:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/borg/testsuite/hashindex.py", line 324, in test_identical_creation
    assert self._serialize_hashindex(idx1) == self.HASHINDEX
AssertionError

self test failed
This is a bug either in Borg or in the package / distribution you use.
```

Same version (1.1.10) works in other distros.

**Comment by fenrus75** [comment]
Bbt test?

**Comment by thiagomacieira** [comment]
Well, first we fix Borg. According to my investigation, this is caused by our zlib being different from everyone else's. The test is trying to compare some compressed data with an expected byte stream. It fails. I can't find a level that produces the expected result.

**Comment by puneetse** [comment]
@thiagomacieira I'm closing this issue because you submitted a patch upstream to address this issue and it is resolved. Please correct me if I am mistaken.
