### ISSUE TITLE
linux: cmdline: add libahci.ignore_sss=1

### ISSUE THREAD

**Issue by thac0** [clearlinux/distribution#942]
The headline says it all. Perhaps it's time to ignore the firmware's "staggered spin-up" flag on bare metal installations. This can decrease boot time on platforms with multiple AHCI devices.

**Comment by miguelinux** [comment]
Do you see if it is used on your platform?

```
$ dmesg | grep SSS 
$
```

on my they are not used

**Comment by miguelinux** [comment]
oh, multiples AHCI devices.
