### ISSUE TITLE
please make a spotlight for clear linux

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#946]
clear linux is the way to go for desktop linux.

mac has done good job with spotllight
i use search everything in windows
in linux i use albert/file search , fsearch for fast search.
but somehow they are lacking all the feature that spotlight provides.
i want linux to index all my ext, ntfs every partition .. and instantly show up my documents/files.

![image](https://user-images.githubusercontent.com/12841320/60200123-3207c680-9865-11e9-8b44-749e95844ecb.png)

![image](https://user-images.githubusercontent.com/12841320/60200171-4ba90e00-9865-11e9-9e26-d83dc1fad97c.png)

![image](https://user-images.githubusercontent.com/12841320/60200205-5d8ab100-9865-11e9-8300-1fa8847de767.png)

**Comment by lebensterben** [comment]
You can use `locate` and use `cronie` to update the database.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nazar2sfive** [comment]
Desktop linux must be all about GUI.

**Comment by lebensterben** [comment]
> Desktop linux must be all about GUI.

If you have some package in mind that provides the functionality you want, you may make a **package request**.
Otherwise it seems to me that you're requesting Clear Linux dev team to develop such a functionality with GUI interface. It's unlikely that this would be achieved very soon.

**Comment by nazar2sfive** [comment]
i would suggest [https://github.com/albertlauncher/albert](url) , its filesearch functionality to best suite my needs. Please add this in your bundle package.

**Comment by nazar2sfive** [comment]
can it be implemented to  Ext3/Ext4 or other file systems to have something like the USN Journal that allows immediate indexing (as Search Everything does with NTFS)?

![image](https://user-images.githubusercontent.com/12841320/60520610-6c5de180-9d05-11e9-92e6-ed22b2705c25.png)
