### ISSUE TITLE
swupd-update inconsistency

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/distribution#948]
On one of my Clear Linux systems I have swupd autoupdate disabled.
I perform the update periodically manually. Today I saw some strange outcome:
<pre>
$ sudo swupd update
Update started.
Preparing to update from 29690 to 29740
Downloading packs (418.54 Mb) for:
 - database-basic-dev
 - desktop-dev
 - devpkg-gtk3
 - kvm-host-dev
 - os-clr-on-clr-dev
 - os-core
 - os-core-update
 - os-utils-gui-dev
	...99%
Finishing packs extraction...

Statistics for going from version 29690 to version 29740:

    changed bundles   : 8
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 6
    new files         : 3377
    deleted files     : 0

No extra files need to be downloaded
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Update took 95.7 seconds, 419 MB transferred
Update successful. System updated from version 29690 to version 29740

$ sudo swupd info
Installed version: 29750
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update

$ sudo swupd update
Update started.
Preparing to update from 29750 to 30110
Downloading packs (4220.87 Mb) for:
 - xorriso
 ...
 <snip>
 ...
 - xfsprogs
 - xterm
 - xz
 - zip
 - znc
	...99%
Finishing packs extraction...

Statistics for going from version 29750 to version 30110:

    changed bundles   : 353
    new bundles       : 2
    deleted bundles   : 0

    changed files     : 18183
    new files         : 85437
    deleted files     : 25000

No extra files need to be downloaded
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
none
rngd.service: restarted (the binary was updated)
clr_debug_fuse.service: restarted (the binary was updated)
pacdiscovery.service: restarted (the binary was updated)
tallow.service: restarted (the binary was updated)
systemd-udevd.service: restarted (the binary was updated)
klogscanner.service: restarted (the binary was updated)
nginx.service: restarted (the binary was updated)
pacrunner.service: restarted (the binary was updated)
systemd-journald.service: restarted (the binary was updated)
mcelog.service: restarted (the binary was updated)
systemd-resolved.service: restarted (the binary was updated)
systemd-timesyncd.service: restarted (the binary was updated)
Update took 1308.3 seconds, 4293 MB transferred
Update successful. System updated from version 29750 to version 30110

</pre>
So I see three problems:
1. Update updated from 29690 to version 29740 (instead of 30110)
2. Reported installed version 29750
3. I needed to run swupd update again to update to 30110

I only ran swupd update again only because I *** knew *** that 29750 was not the latest version.. 
I would expect swupd update would update OS from the current version to the latest in one step.

**Comment by anselmolsm** [comment]
Sounds related to https://github.com/clearlinux/swupd-client/issues/482

**Comment by jurobystricky** [comment]
Yes, it is very likely caused by updating across a format bump.

**Comment by ahkok** [comment]
@otavio Maybe `swupd` itself can print out some info in case it crosses a formatbump.

**Comment by fenrus75** [comment]
It is supposed to exec itself again to update to the end

That worked for me earlier today

**Comment by ahkok** [comment]
It works, it's just not clear and leaves a gap of 10 in the console logs.

**Comment by puneetse** [comment]
I'm closing this issue because the tooling has since been updated to be aware of the latest version, including those crossing format versions.
