### ISSUE TITLE
Add papirus-icon-theme

### ISSUE THREAD

**Issue by Jacalz** [clearlinux/distribution#950]
Papirus is in my opinion the best looking icon theme out there for Linux and it features one of the best or the best amount of icons for software. Seems like they have an icon for just about every app you throw at it and it just looks great!

Link to repository: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

**Comment by pceiley** [comment]
+1

**Comment by mrkz** [comment]
Hey  @pceiley, your contribution was integrated into our build system a few days ago and the addition on the `desktop-assets` bundle was accepted as well, so this should be available in release **30810** or later.

Will close this issue once the content is available via an update.

Thanks for making Clear Linux better with your requests and contributions :tada:

**Comment by pceiley** [comment]
Thanks @mrkz, it looks like this has come through now.

**Comment by mrkz** [comment]
Yea, release **30810** is available now and it effectively addresses this issue, so I'm closing now.

Thanks again for your contribution!
