### ISSUE TITLE
Remove emacs-x11 from desktop-apps

### ISSUE THREAD

**Issue by Jacalz** [clearlinux/distribution#951]
We all need to have the desktop-apps bundle installed for our gnome desktop but it includes the emacs text editor and I think it is completely useless to have in that bundle. The desktop-apps bundle already includes gedit as a basic (but very functional editor) and there isn't any need to have two sets of apps installed by default that do almost the same thing.

Throw out emacs-x11 and let those who want it install it if they so desire, that is my proposal.

**Comment by thiagomacieira** [comment]
Makes sense.

**Comment by miguelinux** [comment]
> Throw out emacs-x11 and let those who want it install it if they so desire, that is my proposal.

Well, I'm not a emacs users but a vim user.

Should we remove gvim as well?

**Comment by bryteise** [comment]
Yes because it isn't supposed to an include but eventually an optional.

**Comment by fenrus75** [comment]
Where are we at with alsoadd in terms of schedule/code

**Comment by bryteise** [comment]
I think we are still waiting for the client side changes at this point.

**Comment by Jacalz** [comment]
> Throw out emacs-x11 and let those who want it install it if they so desire, that is my proposal.
> Well, I'm not a emacs users but a vim user. Should we remove gvim as well?

I would suggest removing it and having gedit as the graphical text editor  and nano as the terminal text editor. They are the simplest and most easy to use editors in my opinion and I think that they are the easiest to understand, just a sane approach to defaults...

**Comment by Jacalz** [comment]
Any news on this?

**Comment by fenrus75** [comment]
emacs-x11 is now already an optional in this bundle

**Comment by Jacalz** [comment]
Thanks @fenrus75!
