### ISSUE TITLE
Software Center Installation fails on any flatpak

### ISSUE THREAD

**Issue by nsgnn** [clearlinux/distribution#954]
Reposting an issue I saw posted [here](https://github.com/clearlinux/clr-bundles/issues/133) that was also on my machine. I get the error on anything that is on the flathub repo. I better describe my case within the comment on the original issue.

> The IDE Text Editor 'Brackets' gives error and fails to install. See screenshot.
> 
> To Reproduce:
> 
>     1. Open Software app
> 
>     2. Search for 'Brackets'
> 
>     3. Click install button
> 
>     4. See failure and notification error message
> 
> 
> ![bracket-error](https://user-images.githubusercontent.com/18618930/60306693-05e85600-98f6-11e9-8d55-9a78bc8ce97e.png)

**Comment by josuedhg** [comment]
I have some questions.

1- are you still seeing this issue? (I wasn't able to reproduce it)
2- what is the version of the issue, we saw a similar issue some weeks age, then if don't have the latest version please update and if it is still there let me know.
3- are you under a special network configuration (VPN, Proxy or anyother) if it is the case let me know

**Comment by nsgnn** [comment]
@josuedhg 

- Still seeing this issue on gnome-software. Flatpak installation works within KDE Discover and command line. 
- Version is 30290. 
- Network is setup completely normally excluding the fact I am using cloudflare DNS.

**Comment by josuedhg** [comment]
could you run these commands please?
```pkill gnome-software && gnome-software --verbose > log.txt```
and send me the first 10 lines of the log.txt file please

**Comment by afhpayne** [comment]
I'm experiencing this issue too.  I noticed it installing Audacity and posted [here](https://community.clearlinux.org/t/audacity-flatpak-fails-to-install-from-software-app/1028).

Here are first 10 lines for mine:
02:11:33:0074 GLib-GIO _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
02:11:33:0146 Gtk Connecting to session manager
02:11:33:0150 GLib-GIO _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
02:11:33:0150 dconf watch_fast: "/system/proxy/" (establishing: 0, active: 0)
02:11:33:0151 dconf watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
02:11:33:0151 Gs  set http_proxy http://:8080
02:11:33:0151 dconf unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
02:11:33:0151 dconf watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
02:11:33:0151 Gs  set https_proxy http://:0
02:11:33:0151 dconf unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)

**Comment by afhpayne** [comment]
In my case gnome is 3.32.2

**Comment by nsgnn** [comment]
14:47:45:0651 Gtk Connecting to session manager
14:47:45:0652 Gtk Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
14:47:45:0652 Gtk Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
14:47:45:0656 GLib-GIO _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
14:47:45:0676 GLib-GIO _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
14:47:45:0676 dconf watch_fast: "/system/proxy/" (establishing: 0, active: 0)
14:47:45:0677 dconf watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
14:47:45:0677 Gs  set http_proxy http://:8080
14:47:45:0677 dconf unwatch_fast: "/system/proxy/http/" (active: 0, establishing: 1)
14:47:45:0677 dconf watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
14:47:45:0677 Gs  set https_proxy http://:0
14:47:45:0677 dconf unwatch_fast: "/system/proxy/https/" (active: 0, establishing: 1)
14:47:45:0677 dconf watch_fast: "/org/gnome/software/" (establishing: 0, active: 0)
14:47:45:0677 dconf watch_established: "/system/proxy/" (establishing: 1)
14:47:45:0677 GLib-GIO Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
14:47:45:0677 dconf watch_established: "/system/proxy/http/" (establishing: 0)
14:47:45:0677 dconf watch_established: "/system/proxy/https/" (establishing: 0)
14:47:45:0677 dconf watch_established: "/org/gnome/software/" (establishing: 1)
14:47:45:0680 GLib-GIO _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ‘gio-network-monitor’
14:47:45:0680 Gs  network status change: online [unmetered]

**Comment by josuedhg** [comment]
thank you, this is going to be fixed today, you are going to see the fix in tomorrow's release

**Comment by josuedhg** [comment]
please update you computer and let me know if the issue have been fixed to close it

**Comment by nsgnn** [comment]
Fixed for me
