### ISSUE TITLE
Bluetooth Mouse (MX Master) does not work

### ISSUE THREAD

**Issue by zeeshan595** [clearlinux/distribution#956]
I have been using LogitechI have been using Logitech MX master mouse in pop OS perfectly. I thought I would try out clear linux and I can't get the mouse to do work. It does pair but receives no input from the mouse. 

However plugging in a wired USB mouse I can use the system fine which makes me thing there is some issue with wireless mice.

**Comment by ephut** [comment]
@mrkz , can you order one of these mice to test?

**Comment by imcecil** [comment]
I'm able to reproduce this with my MX Master mouse
checking the bluetooth service status with
`systemctl status bluetooth.service `
I'm seeing the following message
> Jul 03 18:02:33 computer bluetoothd[802]: input-hog profile accept failed for XX:XX:XX:XX:XX:XX

**Comment by lebensterben** [comment]
>I have been using LogitechI have been using Logitech MX master mouse in pop OS perfectly. I thought I would try out clear linux and I can't get the mouse to do work. It does pair but receives no input from the mouse.  ...

@zeeshan595 Similar issues have been opened previously. It seems that Logitech mouse doesn't works with Bluetooth connection, but works well with unifying receiver.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by znmeb** [comment]
I have a still-unresolved problem with Logitech wireless USB mouse and keyboard https://github.com/clearlinux/distribution/issues/796

**Comment by imcecil** [comment]
I've managed to get this working using bluetooth by loading the **uhid** module.

`sudo modprobe uhid`

It's already built as a module in the [native kernel package](https://github.com/clearlinux-pkgs/linux/blob/171f3fc25fec8fcf3335324ef35284de56ba1a0a/config#L5434) so I don't think any changes are necessary.

There are some instructions in the doc for [loading modules on boot](https://clearlinux.org/documentation/clear-linux/guides/maintenance/kernel-modules-dkms#contents)

**Comment by miguelinux** [comment]
@mrkz  a kernel with the following config  

* for bluetooth media buttons
  CONFIG_INPUT_UINPUT=y
* for UHID devices to work correctly once paired.
  CONFIG_UHID=y

will be available in 1 or 2 days. 
`linux-5.2.2-807` kernel version or higher.

**Comment by mrkz** [comment]
A kernel update with built-in modules is available now (release **30500**) and should fix this issue :tada: 

If you continue to have issues when pairing Bluetooth devices please open a new issue with the relevant data
