### ISSUE TITLE
Systemd will not start haproxy

### ISSUE THREAD

**Issue by donnydavis** [clearlinux/distribution#959]
master-worker mode with systemd support (-Ws) requested, but not compiled. Use master-worker mode (-W) if you are not using Type=notify in your unit file or recompile with USE_SYSTEMD=1

**Comment by ahkok** [comment]
`haproxy` has the following line in the build logs:

`+ make -j12 TARGET=linux2628 USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_SYSTEMD=1`

**Comment by ahkok** [comment]
Can you show the full journal logs for `journalctl -u haproxy` ?

**Comment by donnydavis** [comment]
I already burned the box. I will spin it back up tomorrow to grab the logs.

**Comment by ahkok** [comment]
Do you have something like this in your `journalctl`:
```
haproxy[16346]: [ALERT] 190/153712 (16346) : Cannot open configuration file/directory /etc/haproxy/haproxy.cfg : No such file or directory
```

**Comment by ahkok** [comment]
I guess I need to at least see a useful config file, as I have no idea how to get a valid one in the first place :).

**Comment by ahkok** [comment]
```
# cat /etc/haproxy/haproxy.cfg 
global

defaults
  mode http
  timeout connect 5000ms
  timeout client 50000ms
  timeout server 50000ms

backend legacy
  server legacy_server 127.0.0.1:80

frontend app
  bind :8888
  default_backend legacy
```

Service starts, no errors, and is functional. I have a normal `nginx` on port `80`. This is about as simple as I can make it to test - and it works.

**Comment by ahkok** [comment]
Can you include your config, @donnydavis ?

**Comment by donnydavis** [comment]
The instance I was building was torn down. I tested a similar config on my local box and didn't get the error this time around. We can go ahead and close this
