### ISSUE TITLE
Add group wireshark

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#960]
Consider adding group wireshark. 

Wireshark needs privileged access to NICs. When launched from the desktop launcher icon, it is unable to capture and shows a recommendation to `usermod -aG wireshark <user>` which fails with `usermod: group 'wireshark' does not exist`.

The alternative, which works of course, is to launch wireshark with sudo.

**Comment by ahkok** [comment]
This is fine, can you consider making a patch for `clr-systemd-configs` ?

**Comment by mdhorn** [comment]
How will group `wireshark` be granted read access to all of the network devices?

**Comment by ahkok** [comment]
> How will group |wireshark| be granted read access to all of the network
> devices?
Wireshark has a setuid helper for this, I believe. It grants the
necessary CAP_ bit for the process. (CAP_NET_ADMIN I'm sure).

**Comment by puneetse** [comment]
This was added by me shortly after included in v190 of clr-systemd-config.
