### ISSUE TITLE
Manual Partition Settings

### ISSUE THREAD

**Issue by dedguy21** [clearlinux/distribution#963]
In the most recent iso version there isn't a way following the tui/gui to manually partion disk(s)  at install. Please update (or revert back to old installers which allowed this)

**Comment by mdhorn** [comment]
The Text-based clr-installer-tui does still have an Advanced Disk configuration, but there are several critical bugs that might inhibit various use cases.

We are currently working on a method of the Advanced disk configuration and hope to have it release in the coming weeks.

You can monitor GitHub Issue for updates: 
https://github.com/clearlinux/clr-installer/issues/410
