### ISSUE TITLE
Brackets text editor install gives error and fails

### ISSUE THREAD

**Issue by ebrent8** [clearlinux/distribution#964]
The IDE Text Editor 'Brackets' gives error and fails to install.  See screenshot.

To Reproduce:
1. Open Software app
2. Search for 'Brackets'
3. Click install button
4. See failure and notification error message

![bracket-error](https://user-images.githubusercontent.com/18618930/60306693-05e85600-98f6-11e9-8d55-9a78bc8ce97e.png)

**Comment by josuedhg** [comment]
this issue is duplicated https://github.com/clearlinux/distribution/issues/954
