### ISSUE TITLE
diffpdf

### ISSUE THREAD

**Issue by grayswandyr** [clearlinux/distribution#967]
diffpdf is a one-of-its-kind tool: it allows to "diff' two PDF files graphically in a rather efficient way. This is very useful for researchers writing articles for instance. The linux version is FOSS and has has licence GPL2+.

http://www.qtrac.eu/diffpdf-foss.html

**Comment by ahkok** [comment]
Quote from the website:

**This tool is no longer being developed or maintained. It has been superceded by our commercial GUI applications, DiffPDF and comparepdfcmd. These provide more functionality and are faster on multicore machines. **

**Comment by ahkok** [comment]
Depends on Qt4.

Sorry, we can't add this. This doesn't meet our requirements for packages.
