### ISSUE TITLE
CopyQ

### ISSUE THREAD

**Issue by atishpatel** [clearlinux/distribution#969]
https://github.com/hluk/CopyQ/releases

**Comment by ahkok** [comment]
What does this do? What purpose does it serve? Who may benefit from this? Why isn't this solved by other software?

Just linking a page with release notes doesn't help us decide whether you really really need it, or, you just thought it looked cool. It's important for us to know how important it is to you.

**Comment by lebensterben** [comment]
@atishpatel This is available as a flatpak package.

**Comment by atishpatel** [comment]
@ahkok Sorry, i thought it was popular so i didn't. "CopyQ is advanced clipboard manager with editing and scripting features."

@lebensterben Sorry, i didn't realize it was available on flathub. Closing issue.

**Comment by fenrus75** [comment]
looks cool, I'll try to add it see how it goes

**Comment by isabelomakhanya** [comment]
Use it frequently, however, the tray icon does not appear (using the bundled version). 

I wonder if any other apps with tray icons are experiencing the same?

**Comment by lebensterben** [comment]
>Use it frequently, however, the tray icon does not appear (using the bundled version).  ...

@isabelomakhanya Tray icons are deprecated in Gnome 3. You need to install one variant of 'topicons' extension.

**Comment by isabelomakhanya** [comment]
Thanks @lebensterben will get the extension, or learn to live without it lol
