### ISSUE TITLE
KVM image: not enough entropy

### ISSUE THREAD

**Issue by pohly** [clearlinux/distribution#97]
I tried to run Docker (or more precisely, Kubernetes) on the clear-linux-kvm image under QEMU. I got it installed and running, but then noticed that docker would not come up after a reboot. Eventually I noticed that it only started once the kernel printed "kernel: random: crng init done". I've not straced the docker daemon, but this very much like looks like a case of not having enough entropy in the virtual machine.

This has been observed before: https://wiki.yoctoproject.org/wiki/Entropy_on_Autobuilders

I employed the same solution (-device virtio-rng-pci in the start script, rngd installed from the cryptography bundle and enabled) and now the problem is gone.

Should this be something that the kvm image already does by default?

**Comment by ahkok** [comment]
Is the host clearlinux as well? We can certainly add the `-device virtio-rng-pci` flag to our `start_qemu.sh` script I think. @fenrus75 @bryteise

**Comment by bryteise** [comment]
Yea, that would make the most sense to me. @pohly Thanks for the report and guidenance on the resolution! A fix to our `start_qemu.sh`script should be out in our next release.

**Comment by pohly** [comment]
@bryteise has the issue really been resolved already or did you close accidentally?

@ahkok No, the host is Debian stable. The guest is Clear Linux. I'm not sure whether adding `-device virtio-rng-pci` alone is enough, I haven't tried that.

**Comment by ahkok** [comment]
I always thought that rngd is something that needs to run on the `host` and not the `VM`.

**Comment by bryteise** [comment]
Well in the sense the change to our qemu start script has been modified. For a Clear Linux host this should be working. Not sure how much we can do with other systems not having rngd running.

**Comment by pohly** [comment]
@ahkok no, rngd must be running on the VM. Without it, the kernel doesn't do anything with the new PCI device.

I've just tested it. Here's a 9 second delay *without* rngd:
```
# journalctl -f &
[1] 216
root@clr-8a18b270fedd4451ae77beccf8d7a6f8 ~ # -- Logs begin at Tue 2018-06-19 08:23:51 UTC. --
....
Jun 19 18:35:14 clr-8a18b270fedd4451ae77beccf8d7a6f8 pacdiscovery[196]: Unable to find wpad host

root@clr-8a18b270fedd4451ae77beccf8d7a6f8 ~ # systemctl start docker
Jun 19 18:35:21 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Starting Wait for Network to be Configured...
Jun 19 18:35:21 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd-networkd-wait-online[219]: ignoring: lo
Jun 19 18:35:21 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Started Wait for Network to be Configured.
Jun 19 18:35:21 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Reached target Network is Online.
Jun 19 18:35:21 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Starting Docker Application Container Engine...
Jun 19 18:35:30 clr-8a18b270fedd4451ae77beccf8d7a6f8 kernel: random: crng init done
Jun 19 18:35:30 clr-8a18b270fedd4451ae77beccf8d7a6f8 kernel: random: 7 urandom warning(s) missed due to ratelimiting
Jun 19 18:35:30 clr-8a18b270fedd4451ae77beccf8d7a6f8 dockerd[221]: time="2018-06-19T18:35:30Z" level=info msg="Using defined Default rutime (runc)"
Jun 19 18:35:30 clr-8a18b270fedd4451ae77beccf8d7a6f8 dockerd[221]: time="2018-06-19T18:35:30.767071872Z" level=warning msg="could not change group /var/run/docker.sock to docker: error parsing groups for docker: open /etc/group: no such file or directory"
```

And here the same *with* rngd:
```
# systemctl start docker
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Starting Wait for Network to be Configured...
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd-networkd-wait-online[219]: ignoring: lo
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Started Wait for Network to be Configured.
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Reached target Network is Online.
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 systemd[1]: Starting Docker Application Container Engine...
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 dockerd[221]: time="2018-06-19T18:40:46Z" level=info msg="Using defined Default rutime (runc)"
Jun 19 18:40:46 clr-8a18b270fedd4451ae77beccf8d7a6f8 dockerd[221]: time="2018-06-19T18:40:46.873218685Z" level=warning msg="could not change group /var/run/docker.sock to docker: error parsing groups for docker: open /etc/group: no such file or directory"
```

Both tests with virtio-rng-pci and directly after powering up the VM.

@bryteise without modifying the image the issue hasn't been resolved.

**Comment by ahkok** [comment]
then this needs to go into the images as a dependency.... thanks for clarifying.

**Comment by bryteise** [comment]
@pohly Ah for some reason I thought we had that in our kvm images but I see it is only in the cryptography bundle at the moment.

**Comment by ahkok** [comment]
This is good, but we should still be adding `rngd` to the bundles used in KVM images.

**Comment by bryteise** [comment]
We've made a change to our kvm kernel that should resolve this issue and that should be released tomorrow. Please re-open this issue if it isn't fixed.
