### ISSUE TITLE
Alienware WMI module

### ISSUE THREAD

**Issue by CaptSilver** [clearlinux/distribution#970]
It would be nice if we can enable the alienware wmi module for changing colors on alienware machines. I am was testing the alienware wmi script for my steam os application project and noticed the required kernel module isn't being built. No big deal, but it would be nice. :D

https://github.com/torvalds/linux/blob/master/drivers/platform/x86/alienware-wmi.c

**Comment by ahkok** [comment]
please request kernel changes by listing their appropriate `CONFIG_` name.

In this case, CONFIG_ALIENWARE_WMI, I believe

@miguelinux there's probably more WMI's that we may want to include as module.

**Comment by CaptSilver** [comment]
Roger that, and you are correct on the config name.

**Comment by fenrus75** [comment]
CONFIG_ALIENWARE_WMI=m

hmm we have that set as a module

**Comment by miguelinux** [comment]
yes, it is enabled as module

https://github.com/clearlinux-pkgs/linux/blob/master/config#L6253

**Comment by CaptSilver** [comment]
ok, weirdness... I ran:
`cat /lib/modules/$(uname -r)/modules.builtin`
to check for the builtin modules since my script wasn't working and it didn't show it. I guess i should have done it with modules.dep instead. :/ well, back to troubleshooting. Thanks for all the info!
