### ISSUE TITLE
Add parallel port support

### ISSUE THREAD

**Issue by kirkre** [clearlinux/distribution#972]
As far as I can see there are no parallel port modules loaded in Clear Linux. Let me know if I'm missing something, but before I look at adding this to the Kernel manually I see the docs suggest requesting modules be added here, that might be useful to others. 

Thanks,

Kirk

**Comment by miguelinux** [comment]
> As far as I can see there are no parallel port modules loaded in Clear Linux.

Can you help us to describe the use case?

**Comment by fenrus75** [comment]
controlling cnc machines of course...
or that's what I would use it for

we should be able to make this a module I hope

**Comment by miguelinux** [comment]
> controlling cnc machines of course...
> or that's what I would use it for
> 
> we should be able to make this a module I hope
> 

Ok, will do it.

**Comment by miguelinux** [comment]
Parallel port modules support will be 1 or 2 days

**Comment by kirkre** [comment]
> controlling cnc machines of course... or that's what I would use it for we should be able to make this a module I hope
> Ok, will do it.

CNC is a more lucrative application than serving my old LaserJet printer, I'm glad you pointed that out. After seeing for myself the performance improvements in Clear Linux I am hooked even if I did need to add parallel port modules myself, but if you add these modules I will practically be indentured to try Clear Linux on Azure where we badly need a better performing Linux distro for VMs and containers, so rest assured that your efforts to support odd use cases are never in vain.

**Comment by kirkre** [comment]
Thank you. Do I need to build a new kernel from clearlinux-pkgs/linux myself to use this for now, or is it going to show up in the distro?

**Comment by fenrus75** [comment]
It’ll be in the next update after we put it in. Which almost always is in 1
or 2 days.

**Comment by fenrus75** [comment]
(The delay is mostly for qa)

**Comment by fenrus75** [comment]
fwiw this is already released as an update

**Comment by kirkre** [comment]
Thank you. By the time I rechecked this my kernel was updated and after a reboot the parallel port shows up.
