### ISSUE TITLE
Error during compilation of NVIDIA dkms module

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/distribution#974]
I'm following the Clear Linux tutorial on installing NVIDIA proprietary driver. When installing the driver, it needs to compile a `DKMS` module. But it keeps failing.

Here is a slice of the build log:

```
during GIMPLE pass: printf-return-value
/var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_hal.c: In function ‘uvm_hal_init_table’:
/var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_hal.c:400:11: internal compiler error: Segmentation fault
  400 | NV_STATUS uvm_hal_init_table(void)
      |           ^~~~~~~~~~~~~~~~~~
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_gpu_access_counters.o
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_perf_events.o
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_perf_module.o
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_mmu.o
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_pte_batch.o
  CC [M]  /var/lib/dkms/nvidia/430.26/build/nvidia-uvm/uvm8_tlb_batch.o
0x7fa08f01869f ???
	/usr/src/debug/glibc-2.29/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7fa08effb002 __libc_start_main
../csu/libc-start.c:308
```

The complete build log is available [here](https://gist.github.com/lebensterben/5851e639d87caf171fee5441ab7999d7).

**Comment by huangli812** [comment]
Which gcc you used to compile the module？The latest for kernel module，gcc7 for CUDA. The same version of gcc should be used for the module and the kernel.

**Comment by lebensterben** [comment]
>Which gcc you used to compile the module？The latest for kernel module，gcc7 for CUDA. The same version of gcc should be used for the module and the kernel.  ...

@huangli812 I have previously installed the driver with dkms module compiled by gcc8 and CUDA compiled by gcc7. And there's no issue for different GCC versions.

I have also tried LTS kernel, and it didn't work.

Since I'm the author of some bash scripts to automatically install/uninstall NVIDIA driver, I am frequently re-installing it to test my scripts. Everytime I just do the same thing but aboit one week ago it stops working with the same GCC error.


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ephut** [comment]
@bktan8

**Comment by bktan8** [comment]
@ephut, @puneetse would be better for this issue since he's more knowledgeable on this topic.

**Comment by puneetse** [comment]
> I have previously installed the driver with dkms module compiled by gcc8 and CUDA compiled by gcc7.

@lebensterben I have a system with the same NVIDIA driver and kernel in your logs that compiled with DKMS fine using the distro distributed gcc 9.1.1. 

If you changed any gcc version / flags while testing, try reverting those.

**Comment by puneetse** [comment]
@lebensterben did this issue go away when #1048 got fixed?

**Comment by lebensterben** [comment]
> @lebensterben did this issue go away when #1048 got fixed?

It's fixed. I'm closing this.
