### ISSUE TITLE
Bcmwl-kernel-source

### ISSUE THREAD

**Issue by WIZARD-WIZ** [clearlinux/distribution#979]
After installing clear linux os I had could not find my wifi settings. I think this is due to missing bcmwl-kernel-source package. Because its relatively OS new I could not find any community support for the problem. Please address this problem in the next version.

**Comment by lebensterben** [comment]
>Because its relatively OS new I could not find any community support for the problem. Please address this problem in the next version.

@WIZARD-WIZ I think [this post](https://community.clearlinux.org/t/dkms-not-triggered-on-update/832) on Clear Linux community forum is related.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by WIZARD-WIZ** [comment]
I am relatively new to linux so I think I cannot do all these things without proper steps mentioned ....But I think this can be resolved in the next update and I can wait for the next update.

**Comment by miguelinux** [comment]
Currently CL is not adding any out-of-tree kernel modules. If your driver
is kernel upstream, we can enabled.

**Comment by lebensterben** [comment]
> Currently CL is not adding any out-of-tree kernel modules. If your driver is kernel upstream, we can enable it.

I think [this](https://launchpad.net/broadcom-sta) is the upstream dkms module.

**Comment by fenrus75** [comment]
we have the driver just not the firmware

**Comment by WIZARD-WIZ** [comment]
What should I do then?

**Comment by WIZARD-WIZ** [comment]
Should I give any information about my computer's hardware or architecture so that it can be fixed?

**Comment by ahkok** [comment]
In this case, I believe you may need to download the proprietary firmware yourself. We can not include it in the OS because Broadcom does not permit redistribution (otherwise the `linux-firmware` project would have it included already).

Steps to solve:

1. run `sudo dmesg | grep -i firmware`
2. Look for messages saying firmware file xxxx not found
3. Download the firmware files yourself 
4. Install them to `/etc/firmware` possibly with a subdirectory within that.

**Comment by WIZARD-WIZ** [comment]
> In this case, I believe you may need to download the proprietary firmware yourself. We can not include it in the OS because Broadcom does not permit redistribution (otherwise the `linux-firmware` project would have it included already).
> 
> Steps to solve:
> 
>     1. run `sudo dmesg | grep -i firmware`
> 
>     2. Look for messages saying firmware file xxxx not found
> 
>     3. Download the firmware files yourself
> 
>     4. Install them to `/etc/firmware` possibly with a subdirectory within that.

I did all those steps and bluetooth works fine now. Wifi still no adapter
![Screenshot from 2019-07-11 19-57-27](https://user-images.githubusercontent.com/51266822/61058008-22b47b80-a416-11e9-9b71-f0b9bab3538c.png)
 found.

**Comment by WIZARD-WIZ** [comment]
I can give screenshots of other commands if you want.

**Comment by WIZARD-WIZ** [comment]
![Screenshot from 2019-07-12 13-45-50](https://user-images.githubusercontent.com/51266822/61112402-77ee9c80-a4ab-11e9-9911-4ec52698ba50.png)
I think this might help

**Comment by WIZARD-WIZ** [comment]
can anyone add bcmwl-kernel-source to the software app repsoitory? :(

**Comment by ahkok** [comment]
According to https://help.ubuntu.com/community/WifiDocs/Driver/bcm43xx, you need the proprietary driver. We can't ship this.
