### ISSUE TITLE
Deprecate or update the hyperv-mini image

### ISSUE THREAD

**Issue by puneetse** [clearlinux/distribution#98]
It looks like the hyperv-mini image hasn't been updated in a while.  Can the mini image be combined and kernel patches merged?

https://github.com/clearlinux-pkgs/linux-hyperv
https://github.com/clearlinux-pkgs/linux-hyperv-mini 

https://github.com/clearlinux/clr-bundles/blob/master/bundles/kernel-hyperv
https://github.com/clearlinux/clr-bundles/blob/master/bundles/kernel-hyperv-mini

The differences I spotted were related to hypervisor-to-guest communication and some aufs patches.

**Comment by bryteise** [comment]
The bundle will just be going away, this is in progress.

**Comment by bryteise** [comment]
Deprecation complete.

**Comment by puneetse** [comment]
@bryteise It looks like the image is still on the downloads page and in the README-IMAGE.html

https://cdn.download.clearlinux.org/image/

**Comment by bryteise** [comment]
Looks like this is being updated (or updated as we speak). Thanks for double checking!
