### ISSUE TITLE
Samsung Chromebook Pro Clear Support

### ISSUE THREAD

**Issue by SparkyBoy006** [clearlinux/distribution#980]
I'm trying to run Clear Linux on my Samsung Chromebook Pro (AKA Caroline).

The touchpad and touchscreen do not work like they do on other popular Linux distributions. Also, on GalliumOS, the audio was recently fixed.

I will put what information I have about each issue and hopefully it will help in getting support added to Clear.

https://github.com/GalliumOS/galliumos-skylake

Touchpad/Touchscreen:
https://github.com/GalliumOS/galliumos-distro/issues/373

https://www.reddit.com/r/GalliumOS/comments/6ji3na/chromebook_pro_caroline_touchpad_issues/

https://github.com/GalliumOS/linux/blob/v4.12.0-galliumos/galliumos/diffs/add-touchpad-touchscreen-support.diff

Sound:
https://github.com/GalliumOS/galliumos-skylake/commit/f831889889eb2b8ba753204258400d5dd757683c

https://github.com/GalliumOS/galliumos-skylake/pull/1/files

https://github.com/GalliumOS/galliumos-skylake/pull/1

The initial fix above for audio worked, but volume was a bit low.. the following fixes the audio levels, but hasn't been merged/pushed yet to GalliumOS updates: https://github.com/GalliumOS/galliumos-skylake/pull/7/files

Also there was a problem with SD card detection and log spam that was fixed, but not sure if it's an issue in Clear:
https://github.com/GalliumOS/galliumos-skylake/commit/23f268b3899db4cc45db8e2922f17d19ad7714f8

Lastly, if you can please add the Chromebook keybindings and shortcuts, it would be greatly appreciated.  https://wiki.galliumos.org/Media_keys_and_default_keybindings

**Comment by ahkok** [comment]
It's not *that simple*. For instance, the github repo you list doesn't state where the firmware comes from, and whether it is even distributable or not. The modprobe.d files are incompatible with a generic linux. The module blacklist is plain wrong and would break everyone's audio, and probably not fix yours either.

Without a device in our hands, this is likely too risky to "just include".

If you are really attached to running Clear Linux on this device, I suggest tackling each issue one by one and seeing if you can submit patches that you have tested, and work with us on making them acceptable (by e.g. confirming the source of the firmware and submitting it to linux-firmware, where it should be, or making the proper kernel quirks for this device together with the upstream driver maintainers).

**Comment by SparkyBoy006** [comment]
> It's not _that simple_. For instance, the github repo you list doesn't state where the firmware comes from, and whether it is even distributable or not. The modprobe.d files are incompatible with a generic linux. The module blacklist is plain wrong and would break everyone's audio, and probably not fix yours either.
> 
> Without a device in our hands, this is likely too risky to "just include".
> 
> If you are really attached to running Clear Linux on this device, I suggest tackling each issue one by one and seeing if you can submit patches that you have tested, and work with us on making them acceptable (by e.g. confirming the source of the firmware and submitting it to linux-firmware, where it should be, or making the proper kernel quirks for this device together with the upstream driver maintainers).

Thank you for the quick reply.  If we were to concentrate on adding the touchscreen/touchpad support first, how do I get you what you need to add that support?

Every popular Linux distro (Ubuntu, Manjaro, Fedora...) I've tried so far has had support for the touchpad and touchscreen.  For some reason, Clear Linux doesn't load the proper firmware.  

Touchscreen driver: https://github.com/atmel-maxtouch/linux https://github.com/torvalds/linux/blob/master/drivers/input/touchscreen/atmel_mxt_ts.c

The touchscreen driver is already in the mainline kernel.  In other distro fixes, I see references to a spelling difference in the DMI_SYS_VENDOR.   For Caroline it is "Google" however the driver is looking for "GOOGLE".

Discussion of touchscreen/touchpad that seems relevant to this.
https://github.com/GalliumOS/galliumos-distro/issues/373

Thank you for your help and I'll see what I can do for getting proper audio support added.

**Comment by SparkyBoy006** [comment]
I just tried Clear Linux again on this device and the touchpad, keyboard, and touchscreen are all working now.  The firmware for audio (referenced above) comes from Chrome OS.  I will contact Google and see if it can be distributed.  I'm going to request to close this enhancement request and open a separate one when/if Google gives permission.  Thank you.
