### ISSUE TITLE
Cockpit missing sosreport

### ISSUE THREAD

**Issue by martenjacobs** [clearlinux/distribution#981]
## Issue
Creating diagnostic reports in Cockpit isn't working because the `sosreport` utility is missing.

## Steps to reproduce
Access the `Diagnostic Reports` menu in Cockpit and click `Create Report`

## Expected result
A diagnostic report is created

## Actual result
A dialog is shown with the following error message:
> The sosreport utility is not installed.  This should not happen.  Please complain to your distribution vendor.

**Comment by ahkok** [comment]
I'm adding a runtime dependency, however, I'm unsure it even works correctly at this time. if it doesn't, please open a separate bug for that.
