### ISSUE TITLE
Add libjemalloc to mariadb bundle.

### ISSUE THREAD

**Issue by zardoz-bzar** [clearlinux/distribution#982]
MariaDB actually has an internal LD_PRELOAD directive specifically because a sizable number of their power users prefer jemalloc over libc malloc for some mariadb storage engines and workloads.

e.g.
[mysqld_safe]
malloc-lib      = /usr/local/lib/libjemalloc.so.2

By adding libjemalloc to the bundle file, it adds exactly 1 tiny rpm, so a "many users will want this" use case can be addressed without the need for them to make a custom mix.

This would add no complexity to the build process of the actual mariadb package, since it already has support for this type of shim.

Cheers!

**Comment by fenrus75** [comment]
but.. jemalloc is likely slower....

**Comment by zardoz-bzar** [comment]
It depends...

a. your speed is zero when you OOM.
b. Performance may depend on the behavior of the storage engine used as well.

The most current I've looked at was:
https://github.com/microsoft/mimalloc#benchmark-results
Disclaimer: it was on AMD but I think the engineer in question did a very thorough job here. 

ClearLinux Redis actually forces LIBC for redis-native even though the upstream default is to use jemalloc on linux due to fragmentation with libc. In the above benchmark, libc and jemalloc are basically equally fast for Redis, but that doesn't address the "speed is zero at OOM" issue.

Side Note: I thought malloc research was dead and seeing the mi guys do their thing makes me happy.

**Comment by ahkok** [comment]
On 7/4/19 1:43 PM, zardoz-bzar wrote:
> Side Note: I thought malloc research was dead and seeing the mi guys 
> do their thing makes me happy.

It doesn't make clearlinux folks happy. We don't want to see random 
packages using different allocators, at all. It makes our work more complex.

Auke

**Comment by fenrus75** [comment]
if there's a better malloc we'll love it. and replace the normal malloc with it so that everyone wins.

last tests I saw (on phoronix) the current glibc is actually doing really well (unlike glibc from like 5 years ago)

**Comment by zardoz-bzar** [comment]
Noone is suggesting replacing anything, for this one bundle, I'm suggesting we make it easier for the end user to select a popular choice that is often made in the field. 

The allocator on a large dedicated SQL instance, _is just another knob_. We don't care what alloc the few other daemons are using.

**Comment by ZhongbaoShi** [comment]
Another concern is from size view. 
Background is We are creating Mariadb docker image. The docker image size is one of the important matrix under Cloud Native, compare with default docker image. https://clearlinux.org/software/docker/mariadb

So, how many library will be added to have jemalloc support? How much total size? 
Is it possible to have jemalloc by "swupd bundle-add **" way?

**Comment by zardoz-bzar** [comment]
There are no extra dependencies it pulls in as it only depends on libc. Size half a megabyte so cold starts for docker won't be impacted.

https://download.clearlinux.org/current/x86_64/os/Packages/jemalloc-lib-5.2.0-35.x86_64.rpm

One of the reasons maria admins shim this is for use cases like docker actually. You can test w/ and w/ out the lib to see how much memory gets consumed to detemine if it's right for your configuration.

**Comment by fenrus75** [comment]
ok time for less arguing and more doing; I've just added jemalloc-lib to the mariadb bundle, it's small enough anyway and if it's actually useful, why not
