### ISSUE TITLE
time mismatch windows and clear linux.

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/distribution#983]
clear linux : 12:45 not the real time
windows : 6:30 PM real time

![image](https://user-images.githubusercontent.com/12841320/60756352-2c0ba580-a01c-11e9-8e63-f0e0688eb267.png)

**Comment by lebensterben** [comment]
Is the timezone set correctly?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nazar2sfive** [comment]
yes time zone is correct.

![image](https://user-images.githubusercontent.com/12841320/60764316-0081cd00-a0a7-11e9-887f-88dc129f08c2.png)

**Comment by ahkok** [comment]
`UTC` isn't `Nepal`. `UTC` is everywhere. Are you in Nepal?

**Comment by ahkok** [comment]
`Nepal (GMT+5:45)` ... Try selecting "+0545" on the map (Click on Nepal) if you are actually in Nepal.

**Comment by nazar2sfive** [comment]
i had to restart following selection for the effect to take place. yes i am from nepal.
