### ISSUE TITLE
Hotspot: very low speed

### ISSUE THREAD

**Issue by lem0nez** [clearlinux/distribution#985]
Access point created with [create_ap](https://github.com/oblique/create_ap), as the button `Turn On Wi-Fi Hotspot...` in Wi-Fi settings just not working, and case with creating AP via `Advanced Network Configuration` also not working.

Wired connection speed: **100 MB / s**.
Wi-Fi: **10 MB / s** _(good, as a router located on long distance)_.
Hotspot: **0.6 MB / s**. On Windows 10 hotspot speed is good.

**uname -a**: `Linux lemonez-pc 5.1.16-794.native #1 SMP Wed Jul 3 10:56:51 PDT 2019 x86_64 GNU/Linux`.
Used Wi-FI driver: `rtl8723be`.
Compiled **hostapd** version: `2.8`.

What I tried:
* Disable power management of Wi-Fi adapter (tried `iwconfig` and .conf file in `/etc/NetworkManager/conf.d`).
* Install **haveged**.
* Set different values via **modprobe** for `rtl8723be`: `ant_sel`, `fwlps`, `ips` and `swenc`.
* Set country code.
* Use IEEE 802.11n.
* Use only WPA2.
* Create AP without password.
* Ignore IPv6.
* And many others, that I found in Google...

**Comment by ahkok** [comment]
What you are doing isn't supported. It's likely a bug that "Turn on Wi-Fi Hotspot" doesn't work, but "Low speed with software I compiled myself" isn't a bug we can fix - that is your own software.

**Comment by lem0nez** [comment]
@ahkok, thank you for reply! OK, let's try to determine, why the integrated methods doesn't work. What additional information and logs I need to attach?

**Comment by lem0nez** [comment]
So, after pushing on the **Turn On Wi-Fi Hotspot** button, I see this message in the system log: `Failed to add new connection: (2) Connection 'Hotspot' is not available on device wlp2s0 because profile is not compatible with device (wpa_supplicant does not support Access Point mode)`.

But my adapter support Access Point Mode. **iw list**:
```
	Supported interface modes:
		 * IBSS
		 * managed
		 * AP
		 * AP/VLAN
		 * monitor
		 * P2P-client
		 * P2P-GO
```

Maybe `wpa_supplicant` compiled without support of AP mode (`CONFIG_AP`)?

**Comment by ahkok** [comment]
> Maybe wpa_supplicant compiled without support of the AP mode (CONFIG_AP)?

@busykai

**Comment by ahkok** [comment]
I'm enabling `CONFIG_AP` in wpa_supplicant. This is likely the missing bit - NetworkManager likely sees that currently it doesn't support `AP` mode, while the hardware does.

**Comment by ahkok** [comment]
re-test in ~2 days when this is released.

**Comment by bwarden** [comment]
Looks like this was missed. I've theoretically enabled it now. Should be in release within 1-2 days. This issue will be automatically updated when it's published.
