### ISSUE TITLE
ponder shipping additional certbot plugins

### ISSUE THREAD

**Issue by AntonioMeireles** [clearlinux/distribution#998]
Hi all again!

currently `certbot` pkg (available as `letsencrypt-client` pundle) only ships `certbot-apache` and `certbot-nginx`. IMHO it would be very handy to ship all other available plugins.

Thanks in advance !

**Comment by ahkok** [comment]
Can you list them? "other" is not a valid plugin and open to interpretation. Better would be a list.

**Comment by AntonioMeireles** [comment]
currently we have ... 
```
clear@libvirt-host.clearlinux.local~ $ swupd info
Installed version: 30270
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
clear@foo.clearlinux.local~ $ certbot plugins

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
* apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT

* nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx.configurator:NginxConfigurator

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
clear@foo.clearlinux.local~ $
```

so from upstream only are being made available the `nginx` and the `apache` plugins (the selection is made [here](https://github.com/clearlinux-pkgs/certbot/blob/master/install_append#L1) on clear's side. on [0.35.1](https://github.com/certbot/certbot/tree/v0.35.1), which is what is being shiped in CL, upstream also has available:
- certbot-dns-cloudflare
- certbot-dns-cloudxns
- certbot-dns-digitalocean
- certbot-dns-dnsimple	
- certbot-dns-dnsmadeeasy
- certbot-dns-gehirn
- certbot-dns-google
- certbot-dns-linode
- certbot-dns-luadns
- certbot-dns-nsone
- certbot-dns-ovh
- certbot-dns-rfc2136
- certbot-dns-route53
- certbot-dns-sakuracloud
- certbot-postfix

which imho should also be made enabled for an optimal end user experience as without them in some key use cases / contexts the shipping `nginx` / `apache` only get the user half way ...

António

**Comment by AntonioMeireles** [comment]
so, at sight, something along...
```
diff --git a/install_append b/install_append
index ad1e9b4..6f14103 100644
--- a/install_append
+++ b/install_append
@@ -1,4 +1,19 @@
-for DIR in certbot-apache certbot-nginx certbot-nginx; do
+for DIR in certbot-apache \
+           certbot-nginx \
+           certbot-dns-cloudflare \
+           certbot-dns-cloudxns \
+           certbot-dns-digitalocean \
+           certbot-dns-dnsimple \
+           certbot-dns-dnsmadeeasy \
+           certbot-dns-gehirn certbot-dns-google \
+           certbot-dns-linode \
+           certbot-dns-luadns \
+           certbot-dns-nsone \
+           certbot-dns-ovh \
+           certbot-dns-rfc2136 \
+           certbot-dns-route53 \
+           certbot-dns-sakuracloud \
+           certbot-postfix; do
 (
 	cd ${DIR}
 	python3 setup.py build -b py3
```

**Comment by ahkok** [comment]
Done, thanks!

**Comment by AntonioMeireles** [comment]
@ahkok 

**THANKS**!

P.S. for the sake completeness also add please when you have time`acme` plugin to list above. while copy/pasting here somehow i missed to add it to the the list above :( . 

All the best, 

António
